In [3]:
# ============================================================
# CELL 1 - BENCHMARK GLOBAL CONFIGURATION & REPRODUCIBILITY LOCK
# ============================================================

from pathlib import Path
from datetime import datetime
import json
import sys
import platform

# ------------------------------------------------------------
# 1. Kernel / environment lock
# ------------------------------------------------------------
EXPECTED_PYTHON = Path(
    "/home/pc/miniconda3/envs/genpept_benchmark10_master/bin/python"
)

CURRENT_PYTHON = Path(sys.executable).resolve()

assert CURRENT_PYTHON == EXPECTED_PYTHON.resolve(), (
    f"WRONG KERNEL\n"
    f"Expected: {EXPECTED_PYTHON}\n"
    f"Current : {CURRENT_PYTHON}"
)

# ------------------------------------------------------------
# 2. Project paths
# ------------------------------------------------------------
PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

NOTEBOOK_PATH = PROJECT_ROOT / "BenchMark17model.ipynb"

assert PROJECT_ROOT.exists(), f"Project not found: {PROJECT_ROOT}"
assert NOTEBOOK_PATH.exists(), f"Notebook not found: {NOTEBOOK_PATH}"

# Heavy artifacts -> WSL filesystem
WORK_ROOT = Path.home() / "genpept_benchmark17_work"

RUNS_DIR  = WORK_ROOT / "runs"
CACHE_DIR = WORK_ROOT / "cache"
LOG_DIR   = WORK_ROOT / "logs"

# Final/auditable artifacts -> project directory
OUTPUT_ROOT = PROJECT_ROOT / "benchmark17_outputs"

AUDIT_DIR     = OUTPUT_ROOT / "audit"
SPLIT_DIR     = OUTPUT_ROOT / "splits"
TABLE_DIR     = OUTPUT_ROOT / "tables"
FIGURE_DIR    = OUTPUT_ROOT / "figures"
MANIFEST_DIR  = OUTPUT_ROOT / "manifests"

for p in [
    WORK_ROOT,
    RUNS_DIR,
    CACHE_DIR,
    LOG_DIR,
    OUTPUT_ROOT,
    AUDIT_DIR,
    SPLIT_DIR,
    TABLE_DIR,
    FIGURE_DIR,
    MANIFEST_DIR,
]:
    p.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# 3. Locked benchmark seeds
# Requirement from advisor:
# - 10 independent runs
# - consecutive seeds
# - no seed tuning
# - same seeds for every model/dataset
# ------------------------------------------------------------
SEEDS = list(range(100, 110))

assert SEEDS == [
    100, 101, 102, 103, 104,
    105, 106, 107, 108, 109
]

assert len(SEEDS) == 10
assert len(set(SEEDS)) == 10

# ------------------------------------------------------------
# 4. Locked 17-model benchmark set
# ------------------------------------------------------------
MODELS = [
    "LogisticRegression",
    "LinearSVM_Calibrated",
    "RandomForest",
    "ExtraTrees",
    "HistGradientBoosting",
    "LightGBM",
    "CNN",
    "BiLSTM",
    "BiLSTM_Attention",
    "TransformerEncoder",
    "AmPEP",
    "AMPScannerV2",
    "AmpGram",
    "ampir",
    "amPEPpy",
    "AI4AMP",
    "AMPlify",
]

assert len(MODELS) == 17
assert len(set(MODELS)) == 17

# ------------------------------------------------------------
# 5. Locked experimental protocols
# ------------------------------------------------------------
PROTOCOLS = {
    "protocol_1": "within_dataset",
    "protocol_2": "cross_dataset_transfer",
}

# ------------------------------------------------------------
# 6. Locked scientific rules
# ------------------------------------------------------------
SCIENTIFIC_LOCK = {
    "n_seeds": 10,
    "seed_policy": "consecutive_100_to_109",
    "seed_tuning": False,
    "same_seeds_for_all_models_and_datasets": True,

    "exact_duplicate_rule": "normalized_exact_sequence",
    "cross_dataset_overlap_action": "remove_from_external_target",
    "label_conflict_action": "log_and_remove_from_external_target",

    "external_target_tuning": False,
    "external_target_scaler_fit": False,
    "external_target_feature_fit": False,
    "external_target_early_stopping": False,

    "threshold_source": "source_validation_only",
    "threshold_external_policy": "freeze_source_validation_threshold",

    "summary_statistic": "mean_plus_minus_sample_sd_ddof1",
}

# ------------------------------------------------------------
# 7. Locked metrics
# ------------------------------------------------------------
METRICS = [
    "AUROC",
    "AUPRC",
    "MCC",
    "BACC",
    "F1",
    "Accuracy",
    "Sensitivity",
    "Specificity",
]

# ------------------------------------------------------------
# 8. Critical benchmark configuration
# ------------------------------------------------------------
CRITICAL_CONFIG = {
    "project_root": str(PROJECT_ROOT),
    "work_root": str(WORK_ROOT),
    "seeds": SEEDS,
    "models": MODELS,
    "protocols": PROTOCOLS,
    "metrics": METRICS,
    "scientific_lock": SCIENTIFIC_LOCK,
}

CONFIG_PATH = MANIFEST_DIR / "benchmark17_config.json"

# ------------------------------------------------------------
# 9. Persist immutable benchmark configuration
# ------------------------------------------------------------
if CONFIG_PATH.exists():

    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        old_config = json.load(f)

    for key, expected_value in CRITICAL_CONFIG.items():
        assert old_config.get(key) == expected_value, (
            f"CONFIG LOCK VIOLATION: {key}\n"
            f"Existing benchmark configuration differs from "
            f"the current locked configuration."
        )

    config_status = "EXISTING CONFIG VERIFIED - LOCK PRESERVED"

else:

    config_to_save = {
        "schema_version": "1.0",
        "created_at": datetime.now().astimezone().isoformat(),

        "python_executable": str(CURRENT_PYTHON),
        "python_version": platform.python_version(),

        **CRITICAL_CONFIG,
    }

    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(
            config_to_save,
            f,
            indent=2,
            ensure_ascii=False,
        )

    config_status = "NEW CONFIG CREATED AND LOCKED"

# ------------------------------------------------------------
# 10. Final validation
# ------------------------------------------------------------
assert CONFIG_PATH.exists()
assert len(MODELS) == 17
assert len(SEEDS) == 10
assert SEEDS[0] == 100
assert SEEDS[-1] == 109

print("=" * 72)
print("CELL 1 PASS - BENCHMARK CONFIGURATION LOCKED")
print("=" * 72)

print(f"Python        : {CURRENT_PYTHON}")
print(f"Python version: {platform.python_version()}")

print(f"Project       : {PROJECT_ROOT}")
print(f"Notebook      : {NOTEBOOK_PATH.name}")

print(f"Heavy work    : {WORK_ROOT}")
print(f"Final outputs : {OUTPUT_ROOT}")

print(f"Models        : {len(MODELS)}")
print(f"Seeds         : {SEEDS}")

print(f"Protocols     : {list(PROTOCOLS.values())}")

print(f"Config        : {CONFIG_PATH}")
print(f"Status        : {config_status}")

print("=" * 72)

========================================================================
CELL 1 PASS - BENCHMARK CONFIGURATION LOCKED
========================================================================
Python        : /home/pc/miniconda3/envs/genpept_benchmark10_master/bin/python3.11
Python version: 3.11.16
Project       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026
Notebook      : BenchMark17model.ipynb
Heavy work    : /home/pc/genpept_benchmark17_work
Final outputs : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs
Models        : 17
Seeds         : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
Protocols     : ['within_dataset', 'cross_dataset_transfer']
Config        : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_config.json
Status        : NEW CONFIG CREATED AND LOCKED
========================================================================

In [5]:
# ============================================================
# CELL 2 - SYSTEM, GPU & PACKAGE ENVIRONMENT AUDIT
# ============================================================

from pathlib import Path
from datetime import datetime

import os
import sys
import site
import json
import platform
import subprocess
import importlib.metadata as md


# ------------------------------------------------------------
# 1. Helper functions
# ------------------------------------------------------------
def get_version(package_name):
    try:
        return md.version(package_name)
    except md.PackageNotFoundError:
        return None


def run_cmd(cmd, env=None):
    result = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
        env=env,
    )

    return {
        "returncode": result.returncode,
        "stdout": result.stdout.strip(),
        "stderr": result.stderr.strip(),
    }


# ------------------------------------------------------------
# 2. Kernel lock
# ------------------------------------------------------------
EXPECTED_PYTHON = Path(
    "/home/pc/miniconda3/envs/"
    "genpept_benchmark10_master/bin/python"
)

CURRENT_PYTHON = Path(sys.executable).resolve()

assert CURRENT_PYTHON == EXPECTED_PYTHON.resolve(), (
    "WRONG KERNEL\n"
    f"Expected: {EXPECTED_PYTHON.resolve()}\n"
    f"Current : {CURRENT_PYTHON}"
)


# ------------------------------------------------------------
# 3. Required package audit
# ------------------------------------------------------------
PACKAGE_NAMES = [
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "biopython",
    "matplotlib",
    "lightgbm",
    "pyarrow",
    "h5py",
    "torch",
    "torchvision",
    "torchaudio",
    "fair-esm",
    "tensorflow",
]

package_versions = {
    package_name: get_version(package_name)
    for package_name in PACKAGE_NAMES
}

missing_packages = [
    package_name
    for package_name, version
    in package_versions.items()
    if version is None
]

assert not missing_packages, (
    "MISSING REQUIRED PACKAGES: "
    + ", ".join(missing_packages)
)


# ------------------------------------------------------------
# 4. NVIDIA / WSL GPU audit
# ------------------------------------------------------------
gpu_query = run_cmd([
    "nvidia-smi",
    "--query-gpu="
    "name,driver_version,memory.total,"
    "memory.free,utilization.gpu",
    "--format=csv,noheader,nounits",
])

assert gpu_query["returncode"] == 0, (
    "NVIDIA-SMI FAILED\n"
    + gpu_query["stderr"]
)

gpu_line = gpu_query["stdout"].splitlines()[0]

gpu_parts = [
    value.strip()
    for value in gpu_line.split(",")
]

assert len(gpu_parts) == 5, (
    "Unexpected nvidia-smi output:\n"
    + gpu_line
)

GPU_NAME = gpu_parts[0]
GPU_DRIVER = gpu_parts[1]
GPU_MEMORY_TOTAL_MIB = float(gpu_parts[2])
GPU_MEMORY_FREE_MIB = float(gpu_parts[3])
GPU_UTILIZATION = float(gpu_parts[4])


# ------------------------------------------------------------
# 5. PyTorch GPU test
#    Run in isolated subprocess so notebook keeps no GPU state.
# ------------------------------------------------------------
torch_test_code = r'''
import json
import torch

assert torch.cuda.is_available(), (
    "CUDA unavailable in PyTorch"
)

device = torch.device("cuda:0")

x = torch.tensor(
    [1.0, 2.0, 3.0],
    dtype=torch.float32,
    device=device,
)

y = (x * 2.0).sum()

assert y.device.type == "cuda"
assert float(y.cpu()) == 12.0

info = {
    "torch_version": torch.__version__,
    "cuda_available": bool(torch.cuda.is_available()),
    "cuda_runtime": torch.version.cuda,
    "cudnn_version": torch.backends.cudnn.version(),
    "gpu_name": torch.cuda.get_device_name(0),
    "device_count": torch.cuda.device_count(),
}

print(json.dumps(info))
'''

torch_test = run_cmd([
    sys.executable,
    "-c",
    torch_test_code,
])

assert torch_test["returncode"] == 0, (
    "PYTORCH GPU TEST FAILED\n\n"
    "STDOUT:\n"
    + torch_test["stdout"]
    + "\n\nSTDERR:\n"
    + torch_test["stderr"]
)

torch_info = json.loads(
    torch_test["stdout"].splitlines()[-1]
)

assert torch_info["cuda_available"] is True
assert torch_info["device_count"] >= 1


# ------------------------------------------------------------
# 6. Build explicit CUDA library path for TensorFlow
#
# tensorflow[and-cuda] installs NVIDIA libraries under:
# <site-packages>/nvidia/<component>/lib
#
# WSL driver libraries are under:
# /usr/lib/wsl/lib
# ------------------------------------------------------------
cuda_library_dirs = []

wsl_cuda_driver_dir = Path(
    "/usr/lib/wsl/lib"
)

if wsl_cuda_driver_dir.exists():
    cuda_library_dirs.append(
        str(wsl_cuda_driver_dir)
    )


candidate_site_dirs = []

for p in site.getsitepackages():
    candidate_site_dirs.append(Path(p))

user_site = site.getusersitepackages()

if user_site:
    candidate_site_dirs.append(
        Path(user_site)
    )


for site_dir in candidate_site_dirs:

    nvidia_root = site_dir / "nvidia"

    if not nvidia_root.exists():
        continue

    for lib_dir in sorted(
        nvidia_root.glob("*/lib")
    ):
        if lib_dir.is_dir():
            cuda_library_dirs.append(
                str(lib_dir.resolve())
            )


# Remove duplicates while preserving order
cuda_library_dirs = list(
    dict.fromkeys(cuda_library_dirs)
)

assert len(cuda_library_dirs) > 1, (
    "CUDA runtime library directories "
    "were not discovered."
)


# ------------------------------------------------------------
# 7. TensorFlow subprocess environment
# ------------------------------------------------------------
tf_env = os.environ.copy()

old_ld_library_path = tf_env.get(
    "LD_LIBRARY_PATH",
    "",
)

new_ld_parts = list(
    cuda_library_dirs
)

if old_ld_library_path:
    new_ld_parts.append(
        old_ld_library_path
    )

tf_env["LD_LIBRARY_PATH"] = ":".join(
    new_ld_parts
)

tf_env["CUDA_VISIBLE_DEVICES"] = "0"
tf_env["TF_CPP_MIN_LOG_LEVEL"] = "2"
tf_env["TF_FORCE_GPU_ALLOW_GROWTH"] = "true"


# ------------------------------------------------------------
# 8. TensorFlow GPU test
#    Also runs in isolated subprocess.
# ------------------------------------------------------------
tf_test_code = r'''
import os
import json

os.environ.setdefault(
    "TF_CPP_MIN_LOG_LEVEL",
    "2"
)

os.environ.setdefault(
    "TF_FORCE_GPU_ALLOW_GROWTH",
    "true"
)

import tensorflow as tf

gpus = tf.config.list_physical_devices(
    "GPU"
)

build_info = tf.sysconfig.get_build_info()

if len(gpus) == 0:

    diagnostic = {
        "tensorflow_version": tf.__version__,
        "gpu_count": 0,
        "gpu_devices": [],
        "is_cuda_build":
            bool(tf.test.is_built_with_cuda()),
        "build_info": build_info,
    }

    print(
        json.dumps(
            diagnostic,
            default=str
        )
    )

    raise RuntimeError(
        "TensorFlow installed but "
        "no physical GPU detected."
    )


for gpu in gpus:
    try:
        tf.config.experimental.set_memory_growth(
            gpu,
            True,
        )
    except RuntimeError:
        pass


with tf.device("/GPU:0"):

    x = tf.constant(
        [1.0, 2.0, 3.0],
        dtype=tf.float32,
    )

    y = tf.reduce_sum(
        x * 2.0
    )


assert float(y.numpy()) == 12.0


logical_gpus = (
    tf.config.list_logical_devices(
        "GPU"
    )
)


info = {
    "tensorflow_version":
        tf.__version__,

    "gpu_count":
        len(gpus),

    "logical_gpu_count":
        len(logical_gpus),

    "gpu_devices":
        [str(g) for g in gpus],

    "is_cuda_build":
        bool(
            tf.test.is_built_with_cuda()
        ),

    "build_info":
        build_info,
}

print(
    json.dumps(
        info,
        default=str
    )
)
'''

tf_test = run_cmd(
    [
        sys.executable,
        "-c",
        tf_test_code,
    ],
    env=tf_env,
)

assert tf_test["returncode"] == 0, (
    "TENSORFLOW GPU TEST FAILED\n\n"
    "CUDA LIBRARY DIRS:\n"
    + "\n".join(cuda_library_dirs)
    + "\n\nSTDOUT:\n"
    + tf_test["stdout"]
    + "\n\nSTDERR:\n"
    + tf_test["stderr"]
)

tf_info = json.loads(
    tf_test["stdout"].splitlines()[-1]
)

assert tf_info["gpu_count"] >= 1
assert tf_info["is_cuda_build"] is True


# ------------------------------------------------------------
# 9. ESM2 package import audit
# ------------------------------------------------------------
esm_test = run_cmd([
    sys.executable,
    "-c",
    (
        "import esm; "
        "print('ESM_IMPORT_PASS')"
    ),
])

assert esm_test["returncode"] == 0, (
    "ESM IMPORT FAILED\n"
    + esm_test["stdout"]
    + "\n"
    + esm_test["stderr"]
)

assert (
    "ESM_IMPORT_PASS"
    in esm_test["stdout"]
)


# ------------------------------------------------------------
# 10. pip dependency integrity audit
# ------------------------------------------------------------
pip_check = run_cmd([
    sys.executable,
    "-m",
    "pip",
    "check",
])

assert pip_check["returncode"] == 0, (
    "PIP CHECK FAILED\n"
    + pip_check["stdout"]
    + "\n"
    + pip_check["stderr"]
)


# ------------------------------------------------------------
# 11. Freeze exact Python packages to disk
# ------------------------------------------------------------
pip_freeze = run_cmd([
    sys.executable,
    "-m",
    "pip",
    "freeze",
])

assert pip_freeze["returncode"] == 0

PIP_FREEZE_PATH = (
    MANIFEST_DIR
    / "pip_freeze_benchmark17.txt"
)

with open(
    PIP_FREEZE_PATH,
    "w",
    encoding="utf-8",
) as f:

    f.write(
        pip_freeze["stdout"]
        + "\n"
    )


# ------------------------------------------------------------
# 12. Save CUDA runtime discovery
# ------------------------------------------------------------
CUDA_PATHS_FILE = (
    MANIFEST_DIR
    / "cuda_runtime_paths.json"
)

cuda_path_manifest = {
    "schema_version": "1.0",

    "cuda_library_dirs":
        cuda_library_dirs,

    "ld_library_path_used_for_tf":
        tf_env["LD_LIBRARY_PATH"],
}

with open(
    CUDA_PATHS_FILE,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        cuda_path_manifest,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 13. Save structured environment manifest
# ------------------------------------------------------------
ENV_AUDIT_PATH = (
    MANIFEST_DIR
    / "environment_audit.json"
)

environment_audit = {
    "schema_version": "1.1",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "python": {
        "executable":
            sys.executable,

        "resolved_executable":
            str(CURRENT_PYTHON),

        "version":
            platform.python_version(),

        "implementation":
            platform.python_implementation(),
    },

    "system": {
        "platform":
            platform.platform(),

        "machine":
            platform.machine(),

        "processor":
            platform.processor(),
    },

    "packages":
        package_versions,

    "nvidia": {
        "gpu_name":
            GPU_NAME,

        "driver_version":
            GPU_DRIVER,

        "memory_total_mib":
            GPU_MEMORY_TOTAL_MIB,

        "memory_free_mib":
            GPU_MEMORY_FREE_MIB,

        "utilization_percent":
            GPU_UTILIZATION,
    },

    "pytorch":
        torch_info,

    "tensorflow":
        tf_info,

    "tensorflow_cuda_library_dirs":
        cuda_library_dirs,

    "esm": {
        "version":
            package_versions["fair-esm"],

        "import_ok":
            True,
    },

    "pip_check":
        pip_check["stdout"],
}

with open(
    ENV_AUDIT_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        environment_audit,
        f,
        indent=2,
        ensure_ascii=False,
        default=str,
    )


# ------------------------------------------------------------
# 14. Final validation
# ------------------------------------------------------------
assert ENV_AUDIT_PATH.exists()
assert PIP_FREEZE_PATH.exists()
assert CUDA_PATHS_FILE.exists()

assert GPU_MEMORY_TOTAL_MIB > 0

assert (
    torch_info["cuda_available"]
    is True
)

assert (
    tf_info["gpu_count"]
    >= 1
)

assert (
    tf_info["is_cuda_build"]
    is True
)


# ------------------------------------------------------------
# 15. Final report
# ------------------------------------------------------------
print("=" * 72)
print(
    "CELL 2 PASS - SYSTEM / GPU / "
    "PACKAGE ENVIRONMENT VERIFIED"
)
print("=" * 72)

print(
    f"Python       : "
    f"{CURRENT_PYTHON}"
)

print(
    f"Python ver.  : "
    f"{platform.python_version()}"
)

print("-" * 72)

print(
    f"GPU          : "
    f"{GPU_NAME}"
)

print(
    f"NVIDIA driver: "
    f"{GPU_DRIVER}"
)

print(
    f"GPU VRAM     : "
    f"{GPU_MEMORY_TOTAL_MIB / 1024:.2f} GB"
)

print(
    f"GPU free     : "
    f"{GPU_MEMORY_FREE_MIB / 1024:.2f} GB"
)

print("-" * 72)

print(
    f"PyTorch      : "
    f"{torch_info['torch_version']}"
)

print(
    f"Torch CUDA   : "
    f"{torch_info['cuda_runtime']}"
)

print(
    f"Torch GPU    : "
    f"{torch_info['cuda_available']}"
)

print(
    f"TensorFlow   : "
    f"{tf_info['tensorflow_version']}"
)

print(
    f"TF CUDA build: "
    f"{tf_info['is_cuda_build']}"
)

print(
    f"TF GPUs      : "
    f"{tf_info['gpu_count']}"
)

print("-" * 72)

print(
    f"fair-esm     : "
    f"{package_versions['fair-esm']}"
)

print(
    f"LightGBM     : "
    f"{package_versions['lightgbm']}"
)

print(
    f"scikit-learn : "
    f"{package_versions['scikit-learn']}"
)

print("-" * 72)

print(
    f"CUDA lib dirs: "
    f"{len(cuda_library_dirs)}"
)

print(
    f"pip check    : "
    f"{pip_check['stdout']}"
)

print(
    f"Audit file   : "
    f"{ENV_AUDIT_PATH}"
)

print(
    f"CUDA paths   : "
    f"{CUDA_PATHS_FILE}"
)

print(
    f"pip freeze   : "
    f"{PIP_FREEZE_PATH}"
)

print("=" * 72)

========================================================================
CELL 2 PASS - SYSTEM / GPU / PACKAGE ENVIRONMENT VERIFIED
========================================================================
Python       : /home/pc/miniconda3/envs/genpept_benchmark10_master/bin/python3.11
Python ver.  : 3.11.16
------------------------------------------------------------------------
GPU          : NVIDIA GeForce RTX 3060
NVIDIA driver: 610.88
GPU VRAM     : 12.00 GB
GPU free     : 10.46 GB
------------------------------------------------------------------------
PyTorch      : 2.11.0+cu128
Torch CUDA   : 12.8
Torch GPU    : True
TensorFlow   : 2.21.0
TF CUDA build: True
TF GPUs      : 1
------------------------------------------------------------------------
fair-esm     : 2.0.0
LightGBM     : 4.7.0
scikit-learn : 1.9.0
------------------------------------------------------------------------
CUDA lib dirs: 16
pip check    : No broken requirements found.
Audit file   : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/environment_audit.json
CUDA paths   : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/cuda_runtime_paths.json
pip freeze   : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/pip_freeze_benchmark17.txt
========================================================================

In [9]:
# ============================================================
# CELL 3 - LOCK DATASET SOURCES WITHOUT SCHEMA ASSUMPTIONS
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import re
import pandas as pd


# ------------------------------------------------------------
# 1. Validate notebook state
# ------------------------------------------------------------
REQUIRED_GLOBALS = [
    "PROJECT_ROOT",
    "AUDIT_DIR",
    "MANIFEST_DIR",
]

for name in REQUIRED_GLOBALS:
    assert name in globals(), (
        f"{name} missing. Run CELL 1 first."
    )

assert PROJECT_ROOT.exists(), (
    f"Project root not found:\n{PROJECT_ROOT}"
)


# ------------------------------------------------------------
# 2. Lock GenPept PRIMARY dataset
#
# IMPORTANT:
# Primary manuscript dataset only.
# Do not use verified90 sensitivity dataset here.
# ------------------------------------------------------------
GENPEPT_PRIMARY = (
    PROJECT_ROOT
    / "Bộ dữ liệu trả lời_FINAL_LOCKED"
    / "01_CANONICAL_DATASET"
    / "GenPept_Curated_2025_primary_split_v1.1.csv"
)

assert GENPEPT_PRIMARY.is_file(), (
    "GenPept PRIMARY dataset not found:\n"
    f"{GENPEPT_PRIMARY}"
)


# ------------------------------------------------------------
# 3. Lock external benchmark root already identified
# ------------------------------------------------------------
EXTERNAL_DATA_ROOT = (
    PROJECT_ROOT
    / "Bộ dữ liệu tra lời"
    / "02_BENCHMARK"
    / "FROM_ZIP"
    / "Dataset"
    / "Dataset"
    / "Sota"
    / "SSFGM-Model-main"
    / "SSFGM-Model-main"
    / "Data"
)

assert EXTERNAL_DATA_ROOT.is_dir(), (
    "External benchmark root not found:\n"
    f"{EXTERNAL_DATA_ROOT}"
)


# ------------------------------------------------------------
# 4. SHA-256 helper
# ------------------------------------------------------------
def sha256_file(path: Path) -> str:

    h = hashlib.sha256()

    with open(path, "rb") as f:

        for chunk in iter(
            lambda: f.read(1024 * 1024),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


# ------------------------------------------------------------
# 5. Load GenPept canonical dataset
# ------------------------------------------------------------
genpept_df = pd.read_csv(
    GENPEPT_PRIMARY,
    low_memory=False,
)

assert len(genpept_df) == 11000, (
    "GenPept row count mismatch.\n"
    f"Expected : 11000\n"
    f"Observed : {len(genpept_df)}"
)


# ------------------------------------------------------------
# 6. Locate authoritative split column
# ------------------------------------------------------------
split_cols = [
    c
    for c in genpept_df.columns
    if str(c).strip().lower() == "split"
]

assert len(split_cols) == 1, (
    "Expected exactly one authoritative "
    "'split' column.\n"
    f"Found: {split_cols}"
)

GENPEPT_SPLIT_COL = split_cols[0]


# ------------------------------------------------------------
# 7. Validate primary manuscript split
# ------------------------------------------------------------
SPLIT_MAP = {
    "train": "train",
    "training": "train",

    "val": "validation",
    "valid": "validation",
    "validation": "validation",

    "test": "test",
}

raw_split = (
    genpept_df[GENPEPT_SPLIT_COL]
    .astype(str)
    .str.strip()
    .str.lower()
)

normalized_split = raw_split.map(
    SPLIT_MAP
)

assert normalized_split.notna().all(), (
    "Unknown value(s) in authoritative split:\n"
    + str(
        sorted(
            raw_split[
                normalized_split.isna()
            ].unique().tolist()
        )
    )
)

GENPEPT_SPLIT_COUNTS = {
    "train":
        int((normalized_split == "train").sum()),

    "validation":
        int((normalized_split == "validation").sum()),

    "test":
        int((normalized_split == "test").sum()),
}

EXPECTED_GENPEPT_SPLIT = {
    "train": 7700,
    "validation": 990,
    "test": 2310,
}

assert (
    GENPEPT_SPLIT_COUNTS
    == EXPECTED_GENPEPT_SPLIT
), (
    "GenPept authoritative split mismatch.\n"
    f"Expected : {EXPECTED_GENPEPT_SPLIT}\n"
    f"Observed : {GENPEPT_SPLIT_COUNTS}"
)

# This is the ONLY split object allowed downstream.
GENPEPT_AUTHORITATIVE_SPLIT = (
    normalized_split.copy()
)


# ------------------------------------------------------------
# 8. Legacy split audit only
#
# Presence is allowed.
# It must NEVER be used for benchmark partitioning.
# ------------------------------------------------------------
legacy_cols = [
    c
    for c in genpept_df.columns
    if (
        str(c).strip().lower()
        == "split_legacy_repaired"
    )
]

assert len(legacy_cols) <= 1

if len(legacy_cols) == 1:

    LEGACY_SPLIT_COL = legacy_cols[0]

    legacy_raw = (
        genpept_df[LEGACY_SPLIT_COL]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    legacy_normalized = (
        legacy_raw.map(SPLIT_MAP)
    )

    comparable = (
        legacy_normalized.notna()
        & normalized_split.notna()
    )

    legacy_disagreements = int(
        (
            comparable
            & (
                legacy_normalized
                != normalized_split
            )
        ).sum()
    )

    LEGACY_SPLIT_AUDIT = {
        "present": True,
        "column": LEGACY_SPLIT_COL,
        "policy": "AUDIT_ONLY_NEVER_USED",
        "comparable_rows":
            int(comparable.sum()),
        "disagreements":
            legacy_disagreements,
    }

else:

    LEGACY_SPLIT_COL = None

    LEGACY_SPLIT_AUDIT = {
        "present": False,
        "column": None,
        "policy": "NOT_PRESENT",
        "comparable_rows": 0,
        "disagreements": 0,
    }


# ------------------------------------------------------------
# 9. Locate Benchmark dataset 1, 2, 3
#
# IMPORTANT:
# We identify directories ONLY.
# No assumptions about internal class/split structure.
# ------------------------------------------------------------
dataset_pattern = re.compile(
    r"^Benchmark dataset\s*([123])$",
    flags=re.IGNORECASE,
)

external_dirs = {}

for p in EXTERNAL_DATA_ROOT.iterdir():

    if not p.is_dir():
        continue

    match = dataset_pattern.match(
        p.name.strip()
    )

    if match is not None:

        dataset_number = int(
            match.group(1)
        )

        external_dirs[
            dataset_number
        ] = p


assert set(external_dirs.keys()) == {1, 2, 3}, (
    "Could not identify exactly "
    "Benchmark dataset 1, 2, 3.\n"
    f"Found: {external_dirs}"
)


# ------------------------------------------------------------
# 10. File types to inspect
#
# Do NOT interpret meaning yet.
# ------------------------------------------------------------
DATA_EXTENSIONS = {
    ".csv",
    ".tsv",
    ".txt",
    ".fasta",
    ".fa",
    ".faa",
    ".xlsx",
    ".xls",
}


# ------------------------------------------------------------
# 11. Raw structural inventory
#
# No AMP/non-AMP inference.
# No train/val/test inference.
# ------------------------------------------------------------
external_records = []

for dataset_number in [1, 2, 3]:

    dataset_root = external_dirs[
        dataset_number
    ]

    files = sorted([
        p
        for p in dataset_root.rglob("*")
        if (
            p.is_file()
            and p.suffix.lower()
            in DATA_EXTENSIONS
        )
    ])

    assert len(files) > 0, (
        f"Benchmark dataset {dataset_number} "
        "contains no supported data files."
    )

    for path in files:

        relative = path.relative_to(
            dataset_root
        )

        external_records.append({
            "dataset_number":
                dataset_number,

            "dataset_id":
                f"External_Benchmark_{dataset_number}",

            "dataset_root":
                str(dataset_root),

            "relative_path":
                str(relative),

            "parent_relative":
                str(relative.parent),

            "file_name":
                path.name,

            "extension":
                path.suffix.lower(),

            "size_bytes":
                int(path.stat().st_size),

            "size_kb":
                round(
                    path.stat().st_size
                    / 1024,
                    3,
                ),

            "sha256":
                sha256_file(path),
        })


external_inventory_df = pd.DataFrame(
    external_records
)

assert len(external_inventory_df) > 0


# ------------------------------------------------------------
# 12. Count files per external benchmark
# ------------------------------------------------------------
external_summary_df = (
    external_inventory_df
    .groupby(
        "dataset_id",
        as_index=False,
    )
    .agg(
        n_files=(
            "relative_path",
            "count",
        ),

        total_size_mb=(
            "size_bytes",
            lambda x:
                round(
                    x.sum()
                    / (1024 ** 2),
                    3,
                ),
        ),
    )
)


# ------------------------------------------------------------
# 13. Four-dataset registry
# ------------------------------------------------------------
DATASET_REGISTRY = {

    "GenPept_Curated_2025": {

        "role":
            "primary_proposed_dataset",

        "source_type":
            "canonical_csv",

        "source":
            str(GENPEPT_PRIMARY),

        "n_rows":
            int(len(genpept_df)),

        "authoritative_split_column":
            GENPEPT_SPLIT_COL,

        "split_counts":
            GENPEPT_SPLIT_COUNTS,

        "sha256":
            sha256_file(
                GENPEPT_PRIMARY
            ),
    },

    "External_Benchmark_1": {

        "role":
            "published_comparator_dataset",

        "source_type":
            "directory_schema_pending",

        "source":
            str(external_dirs[1]),
    },

    "External_Benchmark_2": {

        "role":
            "published_comparator_dataset",

        "source_type":
            "directory_schema_pending",

        "source":
            str(external_dirs[2]),
    },

    "External_Benchmark_3": {

        "role":
            "published_comparator_dataset",

        "source_type":
            "directory_schema_pending",

        "source":
            str(external_dirs[3]),
    },
}

assert len(DATASET_REGISTRY) == 4


# ------------------------------------------------------------
# 14. Save structural inventory
# ------------------------------------------------------------
EXTERNAL_INVENTORY_PATH = (
    AUDIT_DIR
    / "external_benchmark_raw_structure.csv"
)

external_inventory_df.to_csv(
    EXTERNAL_INVENTORY_PATH,
    index=False,
)


# ------------------------------------------------------------
# 15. Save GenPept legacy audit
# ------------------------------------------------------------
LEGACY_AUDIT_PATH = (
    AUDIT_DIR
    / "genpept_legacy_split_audit.json"
)

with open(
    LEGACY_AUDIT_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        LEGACY_SPLIT_AUDIT,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 16. Save dataset registry
# ------------------------------------------------------------
DATASET_REGISTRY_PATH = (
    MANIFEST_DIR
    / "benchmark_dataset_source_registry.json"
)

registry_payload = {

    "schema_version": "3.0",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "n_datasets": 4,

    "policies": {

        "genpept_primary_dataset_only":
            True,

        "genpept_authoritative_split":
            "split",

        "legacy_split_usage":
            "audit_only_never_used",

        "external_schema_status":
            "pending_direct_inspection",

        "schema_assumptions":
            False,

        "previous_predictions_used":
            False,

        "previous_results_used":
            False,
    },

    "datasets":
        DATASET_REGISTRY,

    "legacy_split_audit":
        LEGACY_SPLIT_AUDIT,
}

with open(
    DATASET_REGISTRY_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        registry_payload,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 17. Final validation
# ------------------------------------------------------------
assert len(genpept_df) == 11000

assert (
    GENPEPT_SPLIT_COUNTS
    == EXPECTED_GENPEPT_SPLIT
)

assert len(external_dirs) == 3

assert len(DATASET_REGISTRY) == 4

assert EXTERNAL_INVENTORY_PATH.exists()

assert LEGACY_AUDIT_PATH.exists()

assert DATASET_REGISTRY_PATH.exists()


# ------------------------------------------------------------
# 18. Report
# ------------------------------------------------------------
print("=" * 100)

print(
    "CELL 3 PASS - FOUR DATASET SOURCES LOCKED "
    "WITHOUT SCHEMA ASSUMPTIONS"
)

print("=" * 100)

print("GENPEPT PRIMARY")

print(
    f"File                : {GENPEPT_PRIMARY}"
)

print(
    f"Rows                : {len(genpept_df):,}"
)

print(
    f"Authoritative split : {GENPEPT_SPLIT_COL}"
)

print(
    f"Split counts        : {GENPEPT_SPLIT_COUNTS}"
)

print(
    f"SHA-256             : "
    f"{DATASET_REGISTRY['GenPept_Curated_2025']['sha256']}"
)

print("-" * 100)

print("LEGACY SPLIT")

print(
    f"Present             : "
    f"{LEGACY_SPLIT_AUDIT['present']}"
)

print(
    f"Policy              : "
    f"{LEGACY_SPLIT_AUDIT['policy']}"
)

print(
    f"Disagreements       : "
    f"{LEGACY_SPLIT_AUDIT['disagreements']:,}"
)

print("-" * 100)

print("EXTERNAL BENCHMARK DIRECTORIES")

for i in [1, 2, 3]:

    print(
        f"Dataset {i}: "
        f"{external_dirs[i]}"
    )

print("-" * 100)

print("EXTERNAL FILE COUNTS")

print(
    external_summary_df.to_string(
        index=False
    )
)

print("-" * 100)

print("ACTUAL EXTERNAL DIRECTORY STRUCTURE")

print(
    external_inventory_df[
        [
            "dataset_id",
            "size_kb",
            "relative_path",
        ]
    ].to_string(
        index=False
    )
)

print("-" * 100)

print(
    f"Structure audit : "
    f"{EXTERNAL_INVENTORY_PATH}"
)

print(
    f"Dataset registry: "
    f"{DATASET_REGISTRY_PATH}"
)

print("=" * 100)

====================================================================================================
CELL 3 PASS - FOUR DATASET SOURCES LOCKED WITHOUT SCHEMA ASSUMPTIONS
====================================================================================================
GENPEPT PRIMARY
File                : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/Bộ dữ liệu trả lời_FINAL_LOCKED/01_CANONICAL_DATASET/GenPept_Curated_2025_primary_split_v1.1.csv
Rows                : 11,000
Authoritative split : split
Split counts        : {'train': 7700, 'validation': 990, 'test': 2310}
SHA-256             : d4fa256cbaa255adb49112e0a95122ae2a4da98e1bcadecc2f9965ed04fc5e0f
----------------------------------------------------------------------------------------------------
LEGACY SPLIT
Present             : True
Policy              : AUDIT_ONLY_NEVER_USED
Disagreements       : 4,939
----------------------------------------------------------------------------------------------------
EXTERNAL BENCHMARK DIRECTORIES
Dataset 1: /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/Bộ dữ liệu tra lời/02_BENCHMARK/FROM_ZIP/Dataset/Dataset/Sota/SSFGM-Model-main/SSFGM-Model-main/Data/Benchmark dataset1
Dataset 2: /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/Bộ dữ liệu tra lời/02_BENCHMARK/FROM_ZIP/Dataset/Dataset/Sota/SSFGM-Model-main/SSFGM-Model-main/Data/Benchmark dataset2
Dataset 3: /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/Bộ dữ liệu tra lời/02_BENCHMARK/FROM_ZIP/Dataset/Dataset/Sota/SSFGM-Model-main/SSFGM-Model-main/Data/Benchmark dataset 3
----------------------------------------------------------------------------------------------------
EXTERNAL FILE COUNTS
          dataset_id  n_files  total_size_mb
External_Benchmark_1        6          0.468
External_Benchmark_2       12          0.167
External_Benchmark_3        6          0.772
----------------------------------------------------------------------------------------------------
ACTUAL EXTERNAL DIRECTORY STRUCTURE
          dataset_id  size_kb                        relative_path
External_Benchmark_1   48.431                      amp_eval2.fasta
External_Benchmark_1   48.652                      amp_test2.fasta
External_Benchmark_1  156.911                     amp_train2.fasta
External_Benchmark_1   19.989                  non_amp_eval2.fasta
External_Benchmark_1   42.125                  non_amp_test2.fasta
External_Benchmark_1  162.861                 non_amp_train2.fasta
External_Benchmark_2   15.618                       AMP_eval.fasta
External_Benchmark_2   30.733                       AMP_test.fasta
External_Benchmark_2   30.809                      AMP_train.fasta
External_Benchmark_2   18.021                     DECOY_eval.fasta
External_Benchmark_2   36.366                     DECOY_test.fasta
External_Benchmark_2   36.548                    DECOY_train.fasta
External_Benchmark_2    0.383     example_fasta/AMP_eval_exm.fasta
External_Benchmark_2    0.366   example_fasta/AMP_test - exm.fasta
External_Benchmark_2    0.373  example_fasta/AMP_train - exm.fasta
External_Benchmark_2    0.485 example_fasta/DECOY_eval - exm.fasta
External_Benchmark_2    0.573 example_fasta/DECOY_test - exm.fasta
External_Benchmark_2    0.492 example_fasta/DECOY_train -exm.fasta
External_Benchmark_3   54.592                       AMP/test.fasta
External_Benchmark_3  256.791                      AMP/train.fasta
External_Benchmark_3   56.136                      AMP/valid.fasta
External_Benchmark_3   63.899                    nonAMP/test.fasta
External_Benchmark_3  294.989                   nonAMP/train.fasta
External_Benchmark_3   63.663                   nonAMP/valid.fasta
----------------------------------------------------------------------------------------------------
Structure audit : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/external_benchmark_raw_structure.csv
Dataset registry: /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark_dataset_source_registry.json
====================================================================================================

In [10]:
# ============================================================
# CELL 4 - PARSE AND STANDARDIZE THE FOUR DATASETS
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import pandas as pd


# ------------------------------------------------------------
# 1. Validate state inherited from CELL 3
# ------------------------------------------------------------
REQUIRED_GLOBALS = [
    "GENPEPT_PRIMARY",
    "GENPEPT_AUTHORITATIVE_SPLIT",
    "GENPEPT_SPLIT_COL",
    "external_dirs",
    "AUDIT_DIR",
    "MANIFEST_DIR",
]

for name in REQUIRED_GLOBALS:
    assert name in globals(), (
        f"{name} missing. Run CELL 3 first."
    )


# ------------------------------------------------------------
# 2. Scientific sequence contract
# ------------------------------------------------------------
AA20 = set(
    "ACDEFGHIKLMNPQRSTVWY"
)

MIN_LEN = 10
MAX_LEN = 200


# ------------------------------------------------------------
# 3. FASTA parser
# ------------------------------------------------------------
def parse_fasta(path):

    records = []

    header = None
    sequence_parts = []

    with open(
        path,
        "r",
        encoding="utf-8",
        errors="replace",
    ) as f:

        for raw_line in f:

            line = raw_line.strip()

            if not line:
                continue

            if line.startswith(">"):

                if header is not None:

                    sequence = "".join(
                        sequence_parts
                    )

                    records.append(
                        {
                            "header": header,
                            "sequence": sequence,
                        }
                    )

                header = line[1:].strip()
                sequence_parts = []

            else:

                assert header is not None, (
                    "FASTA sequence encountered "
                    "before first header:\n"
                    f"{path}"
                )

                sequence_parts.append(
                    line
                )

    if header is not None:

        sequence = "".join(
            sequence_parts
        )

        records.append(
            {
                "header": header,
                "sequence": sequence,
            }
        )

    assert len(records) > 0, (
        f"No FASTA records found:\n{path}"
    )

    return records


# ------------------------------------------------------------
# 4. Sequence normalization
#
# IMPORTANT:
# Normalization does not silently repair invalid residues.
# It only:
# - casts to string
# - removes whitespace
# - uppercases
# ------------------------------------------------------------
def normalize_sequence(seq):

    return "".join(
        str(seq)
        .split()
    ).upper()


# ------------------------------------------------------------
# 5. SHA256 helper for normalized sequence
# ------------------------------------------------------------
def sequence_sha256(seq):

    return hashlib.sha256(
        seq.encode("utf-8")
    ).hexdigest()


# ------------------------------------------------------------
# 6. Resolve GenPept sequence column
# ------------------------------------------------------------
def find_column_candidates(
    df,
    candidate_names,
):

    normalized_lookup = {
        str(col)
        .strip()
        .lower()
        .replace(" ", "")
        .replace("_", "")
        .replace("-", ""):
        col

        for col in df.columns
    }

    matches = []

    for candidate in candidate_names:

        key = (
            candidate
            .strip()
            .lower()
            .replace(" ", "")
            .replace("_", "")
            .replace("-", "")
        )

        if key in normalized_lookup:
            matches.append(
                normalized_lookup[key]
            )

    return list(
        dict.fromkeys(matches)
    )


GENPEPT_SEQUENCE_CANDIDATES = (
    find_column_candidates(
        genpept_df,
        [
            "sequence",
            "peptide_sequence",
            "peptide sequence",
            "seq",
        ],
    )
)

assert len(
    GENPEPT_SEQUENCE_CANDIDATES
) == 1, (
    "Could not uniquely determine "
    "GenPept sequence column.\n"
    f"Candidates: {GENPEPT_SEQUENCE_CANDIDATES}\n"
    f"Columns: {list(genpept_df.columns)}"
)

GENPEPT_SEQUENCE_COL = (
    GENPEPT_SEQUENCE_CANDIDATES[0]
)


# ------------------------------------------------------------
# 7. Resolve GenPept label column
# ------------------------------------------------------------
GENPEPT_LABEL_CANDIDATES = (
    find_column_candidates(
        genpept_df,
        [
            "label",
            "class",
            "target",
            "amp_label",
            "AMP label",
        ],
    )
)

assert len(
    GENPEPT_LABEL_CANDIDATES
) == 1, (
    "Could not uniquely determine "
    "GenPept label column.\n"
    f"Candidates: {GENPEPT_LABEL_CANDIDATES}\n"
    f"Columns: {list(genpept_df.columns)}"
)

GENPEPT_LABEL_COL = (
    GENPEPT_LABEL_CANDIDATES[0]
)


# ------------------------------------------------------------
# 8. Resolve optional GenPept sample ID
# ------------------------------------------------------------
GENPEPT_ID_CANDIDATES = (
    find_column_candidates(
        genpept_df,
        [
            "sample_id",
            "sample id",
            "id",
            "accession.version",
            "accession_version",
            "accession",
        ],
    )
)

if len(GENPEPT_ID_CANDIDATES) >= 1:

    GENPEPT_ID_COL = (
        GENPEPT_ID_CANDIDATES[0]
    )

else:

    GENPEPT_ID_COL = None


# ------------------------------------------------------------
# 9. Normalize GenPept labels
# ------------------------------------------------------------
raw_genpept_labels = (
    genpept_df[
        GENPEPT_LABEL_COL
    ]
    .astype(str)
    .str.strip()
    .str.lower()
)


def normalize_binary_label(value):

    value = (
        str(value)
        .strip()
        .lower()
    )

    positive_values = {
        "1",
        "true",
        "amp",
        "positive",
        "pos",
    }

    negative_values = {
        "0",
        "-1",
        "false",
        "nonamp",
        "non-amp",
        "negative",
        "neg",
        "decoy",
    }

    if value in positive_values:
        return 1

    if value in negative_values:
        return 0

    return None


genpept_labels = (
    raw_genpept_labels
    .map(normalize_binary_label)
)

assert genpept_labels.notna().all(), (
    "Unrecognized GenPept label values:\n"
    + str(
        sorted(
            raw_genpept_labels[
                genpept_labels.isna()
            ].unique().tolist()
        )
    )
)

genpept_labels = (
    genpept_labels.astype(int)
)


# ------------------------------------------------------------
# 10. Build standardized GenPept table
# ------------------------------------------------------------
genpept_sequences = (
    genpept_df[
        GENPEPT_SEQUENCE_COL
    ]
    .map(normalize_sequence)
)

if GENPEPT_ID_COL is not None:

    genpept_ids = (
        genpept_df[
            GENPEPT_ID_COL
        ]
        .astype(str)
        .str.strip()
    )

else:

    genpept_ids = pd.Series(
        [
            f"GenPept_{i:05d}"
            for i in range(
                1,
                len(genpept_df) + 1,
            )
        ],
        index=genpept_df.index,
    )


genpept_standardized = pd.DataFrame(
    {
        "dataset":
            "GenPept_Curated_2025",

        "sample_id":
            genpept_ids,

        "sequence":
            genpept_sequences,

        "label":
            genpept_labels,

        "split":
            GENPEPT_AUTHORITATIVE_SPLIT.values,

        "source_file":
            str(GENPEPT_PRIMARY),
    }
)


# ------------------------------------------------------------
# 11. Explicit external FASTA manifest
#
# No filename guessing downstream.
#
# eval = validation
# valid = validation
#
# Dataset 2 example_fasta files are explicitly excluded.
# ------------------------------------------------------------
EXTERNAL_FASTA_MANIFEST = [

    # ========================================================
    # External Benchmark 1
    # ========================================================
    {
        "dataset":
            "External_Benchmark_1",
        "path":
            external_dirs[1]
            / "amp_train2.fasta",
        "label": 1,
        "split": "train",
    },

    {
        "dataset":
            "External_Benchmark_1",
        "path":
            external_dirs[1]
            / "amp_eval2.fasta",
        "label": 1,
        "split": "validation",
    },

    {
        "dataset":
            "External_Benchmark_1",
        "path":
            external_dirs[1]
            / "amp_test2.fasta",
        "label": 1,
        "split": "test",
    },

    {
        "dataset":
            "External_Benchmark_1",
        "path":
            external_dirs[1]
            / "non_amp_train2.fasta",
        "label": 0,
        "split": "train",
    },

    {
        "dataset":
            "External_Benchmark_1",
        "path":
            external_dirs[1]
            / "non_amp_eval2.fasta",
        "label": 0,
        "split": "validation",
    },

    {
        "dataset":
            "External_Benchmark_1",
        "path":
            external_dirs[1]
            / "non_amp_test2.fasta",
        "label": 0,
        "split": "test",
    },


    # ========================================================
    # External Benchmark 2
    # ========================================================
    {
        "dataset":
            "External_Benchmark_2",
        "path":
            external_dirs[2]
            / "AMP_train.fasta",
        "label": 1,
        "split": "train",
    },

    {
        "dataset":
            "External_Benchmark_2",
        "path":
            external_dirs[2]
            / "AMP_eval.fasta",
        "label": 1,
        "split": "validation",
    },

    {
        "dataset":
            "External_Benchmark_2",
        "path":
            external_dirs[2]
            / "AMP_test.fasta",
        "label": 1,
        "split": "test",
    },

    {
        "dataset":
            "External_Benchmark_2",
        "path":
            external_dirs[2]
            / "DECOY_train.fasta",
        "label": 0,
        "split": "train",
    },

    {
        "dataset":
            "External_Benchmark_2",
        "path":
            external_dirs[2]
            / "DECOY_eval.fasta",
        "label": 0,
        "split": "validation",
    },

    {
        "dataset":
            "External_Benchmark_2",
        "path":
            external_dirs[2]
            / "DECOY_test.fasta",
        "label": 0,
        "split": "test",
    },


    # ========================================================
    # External Benchmark 3
    # ========================================================
    {
        "dataset":
            "External_Benchmark_3",
        "path":
            external_dirs[3]
            / "AMP"
            / "train.fasta",
        "label": 1,
        "split": "train",
    },

    {
        "dataset":
            "External_Benchmark_3",
        "path":
            external_dirs[3]
            / "AMP"
            / "valid.fasta",
        "label": 1,
        "split": "validation",
    },

    {
        "dataset":
            "External_Benchmark_3",
        "path":
            external_dirs[3]
            / "AMP"
            / "test.fasta",
        "label": 1,
        "split": "test",
    },

    {
        "dataset":
            "External_Benchmark_3",
        "path":
            external_dirs[3]
            / "nonAMP"
            / "train.fasta",
        "label": 0,
        "split": "train",
    },

    {
        "dataset":
            "External_Benchmark_3",
        "path":
            external_dirs[3]
            / "nonAMP"
            / "valid.fasta",
        "label": 0,
        "split": "validation",
    },

    {
        "dataset":
            "External_Benchmark_3",
        "path":
            external_dirs[3]
            / "nonAMP"
            / "test.fasta",
        "label": 0,
        "split": "test",
    },
]

assert len(
    EXTERNAL_FASTA_MANIFEST
) == 18


# ------------------------------------------------------------
# 12. Verify every expected source exists
# ------------------------------------------------------------
for item in EXTERNAL_FASTA_MANIFEST:

    assert item["path"].is_file(), (
        "Expected FASTA source not found:\n"
        f"{item['path']}"
    )


# ------------------------------------------------------------
# 13. Parse all 18 external FASTA files
# ------------------------------------------------------------
external_rows = []

source_file_summary = []

dataset_local_counter = {
    "External_Benchmark_1": 0,
    "External_Benchmark_2": 0,
    "External_Benchmark_3": 0,
}

for item in EXTERNAL_FASTA_MANIFEST:

    fasta_records = parse_fasta(
        item["path"]
    )

    source_file_summary.append(
        {
            "dataset":
                item["dataset"],

            "split":
                item["split"],

            "label":
                item["label"],

            "source_file":
                str(item["path"]),

            "n_records":
                len(fasta_records),
        }
    )

    for record in fasta_records:

        dataset_local_counter[
            item["dataset"]
        ] += 1

        sequence = normalize_sequence(
            record["sequence"]
        )

        sample_id = (
            f"{item['dataset']}_"
            f"{dataset_local_counter[item['dataset']]:06d}"
        )

        external_rows.append(
            {
                "dataset":
                    item["dataset"],

                "sample_id":
                    sample_id,

                "original_header":
                    record["header"],

                "sequence":
                    sequence,

                "label":
                    int(item["label"]),

                "split":
                    item["split"],

                "source_file":
                    str(item["path"]),
            }
        )


external_standardized = pd.DataFrame(
    external_rows
)

source_file_summary_df = pd.DataFrame(
    source_file_summary
)


# ------------------------------------------------------------
# 14. Combine all four datasets
# ------------------------------------------------------------
genpept_standardized[
    "original_header"
] = None

STANDARD_COLUMNS = [
    "dataset",
    "sample_id",
    "original_header",
    "sequence",
    "label",
    "split",
    "source_file",
]

genpept_standardized = (
    genpept_standardized[
        STANDARD_COLUMNS
    ]
)

external_standardized = (
    external_standardized[
        STANDARD_COLUMNS
    ]
)

benchmark_raw_df = pd.concat(
    [
        genpept_standardized,
        external_standardized,
    ],
    ignore_index=True,
)


# ------------------------------------------------------------
# 15. Add basic sequence audit fields
# ------------------------------------------------------------
benchmark_raw_df[
    "length"
] = benchmark_raw_df[
    "sequence"
].str.len()

benchmark_raw_df[
    "invalid_residues"
] = benchmark_raw_df[
    "sequence"
].apply(
    lambda seq:
        "".join(
            sorted(
                set(seq) - AA20
            )
        )
)

benchmark_raw_df[
    "is_valid_aa20"
] = (
    benchmark_raw_df[
        "invalid_residues"
    ] == ""
)

benchmark_raw_df[
    "within_10_200"
] = benchmark_raw_df[
    "length"
].between(
    MIN_LEN,
    MAX_LEN,
    inclusive="both",
)

benchmark_raw_df[
    "sequence_sha256"
] = benchmark_raw_df[
    "sequence"
].map(
    sequence_sha256
)


# ------------------------------------------------------------
# 16. Structural integrity checks
#
# Do NOT filter failures yet.
# Cell 5 will decide preprocessing policy.
# ------------------------------------------------------------
assert benchmark_raw_df[
    "dataset"
].nunique() == 4

assert set(
    benchmark_raw_df[
        "label"
    ].unique()
) <= {0, 1}

assert set(
    benchmark_raw_df[
        "split"
    ].unique()
) == {
    "train",
    "validation",
    "test",
}

assert benchmark_raw_df[
    "sequence"
].notna().all()

assert (
    benchmark_raw_df[
        "sequence"
    ].str.len()
    > 0
).all()

assert benchmark_raw_df[
    "sample_id"
].is_unique


# ------------------------------------------------------------
# 17. Dataset x split x class summary
# ------------------------------------------------------------
dataset_split_summary = (
    benchmark_raw_df
    .groupby(
        [
            "dataset",
            "split",
            "label",
        ],
        as_index=False,
    )
    .agg(
        n=(
            "sample_id",
            "count",
        ),

        min_len=(
            "length",
            "min",
        ),

        median_len=(
            "length",
            "median",
        ),

        max_len=(
            "length",
            "max",
        ),

        invalid_aa20=(
            "is_valid_aa20",
            lambda x:
                int((~x).sum()),
        ),

        outside_10_200=(
            "within_10_200",
            lambda x:
                int((~x).sum()),
        ),
    )
)


# ------------------------------------------------------------
# 18. Overall dataset summary
# ------------------------------------------------------------
dataset_summary = (
    benchmark_raw_df
    .groupby(
        "dataset",
        as_index=False,
    )
    .agg(
        total=(
            "sample_id",
            "count",
        ),

        AMP=(
            "label",
            lambda x:
                int((x == 1).sum()),
        ),

        non_AMP=(
            "label",
            lambda x:
                int((x == 0).sum()),
        ),

        min_len=(
            "length",
            "min",
        ),

        median_len=(
            "length",
            "median",
        ),

        max_len=(
            "length",
            "max",
        ),

        invalid_aa20=(
            "is_valid_aa20",
            lambda x:
                int((~x).sum()),
        ),

        outside_10_200=(
            "within_10_200",
            lambda x:
                int((~x).sum()),
        ),
    )
)


# ------------------------------------------------------------
# 19. Internal exact-duplicate audit
#
# IMPORTANT:
# Only count here.
# Do NOT remove anything yet.
# ------------------------------------------------------------
internal_duplicate_summary = []

for dataset_name, df_part in (
    benchmark_raw_df
    .groupby("dataset")
):

    n_rows = len(df_part)

    n_unique_sequences = (
        df_part[
            "sequence"
        ].nunique()
    )

    duplicate_rows = (
        n_rows
        - n_unique_sequences
    )

    sequence_label_counts = (
        df_part
        .groupby(
            "sequence"
        )["label"]
        .nunique()
    )

    label_conflict_sequences = int(
        (
            sequence_label_counts > 1
        ).sum()
    )

    internal_duplicate_summary.append(
        {
            "dataset":
                dataset_name,

            "n_rows":
                int(n_rows),

            "n_unique_sequences":
                int(n_unique_sequences),

            "duplicate_rows":
                int(duplicate_rows),

            "label_conflict_sequences":
                label_conflict_sequences,
        }
    )


internal_duplicate_summary_df = pd.DataFrame(
    internal_duplicate_summary
)


# ------------------------------------------------------------
# 20. Persist RAW standardized data
#
# "raw" here means:
# parsed and normalized case/whitespace,
# but NO sample removal.
# ------------------------------------------------------------
RAW_STANDARDIZED_PATH = (
    AUDIT_DIR
    / "benchmark4_raw_standardized.csv"
)

benchmark_raw_df.to_csv(
    RAW_STANDARDIZED_PATH,
    index=False,
)


# ------------------------------------------------------------
# 21. Persist summaries
# ------------------------------------------------------------
SOURCE_FILE_SUMMARY_PATH = (
    AUDIT_DIR
    / "external_fasta_file_counts.csv"
)

DATASET_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark4_dataset_summary_raw.csv"
)

SPLIT_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark4_split_class_summary_raw.csv"
)

DUPLICATE_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark4_internal_duplicate_summary_raw.csv"
)

source_file_summary_df.to_csv(
    SOURCE_FILE_SUMMARY_PATH,
    index=False,
)

dataset_summary.to_csv(
    DATASET_SUMMARY_PATH,
    index=False,
)

dataset_split_summary.to_csv(
    SPLIT_SUMMARY_PATH,
    index=False,
)

internal_duplicate_summary_df.to_csv(
    DUPLICATE_SUMMARY_PATH,
    index=False,
)


# ------------------------------------------------------------
# 22. Persist schema manifest
# ------------------------------------------------------------
SCHEMA_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark4_schema_manifest.json"
)

schema_manifest = {

    "schema_version": "1.0",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "genpept": {
        "sequence_column":
            GENPEPT_SEQUENCE_COL,

        "label_column":
            GENPEPT_LABEL_COL,

        "sample_id_column":
            GENPEPT_ID_COL,

        "split_column":
            GENPEPT_SPLIT_COL,

        "split_policy":
            "authoritative_split_only",
    },

    "external": {
        "n_source_fasta_files":
            18,

        "dataset_1": {
            "positive":
                "amp_*2.fasta",

            "negative":
                "non_amp_*2.fasta",

            "eval_interpretation":
                "validation",
        },

        "dataset_2": {
            "positive":
                "AMP_*.fasta",

            "negative":
                "DECOY_*.fasta",

            "eval_interpretation":
                "validation",

            "example_fasta_used":
                False,
        },

        "dataset_3": {
            "positive":
                "AMP/*.fasta",

            "negative":
                "nonAMP/*.fasta",

            "valid_interpretation":
                "validation",
        },
    },

    "sequence_normalization": {
        "uppercase":
            True,

        "remove_whitespace":
            True,

        "residue_replacement":
            False,

        "filtering_applied":
            False,
    },
}

with open(
    SCHEMA_MANIFEST_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        schema_manifest,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 23. Final assertions
# ------------------------------------------------------------
assert RAW_STANDARDIZED_PATH.exists()
assert SOURCE_FILE_SUMMARY_PATH.exists()
assert DATASET_SUMMARY_PATH.exists()
assert SPLIT_SUMMARY_PATH.exists()
assert DUPLICATE_SUMMARY_PATH.exists()
assert SCHEMA_MANIFEST_PATH.exists()

assert (
    len(
        benchmark_raw_df[
            benchmark_raw_df[
                "dataset"
            ]
            == "GenPept_Curated_2025"
        ]
    )
    == 11000
)

assert (
    source_file_summary_df[
        "source_file"
    ].nunique()
    == 18
)


# ------------------------------------------------------------
# 24. Final report
# ------------------------------------------------------------
print("=" * 100)

print(
    "CELL 4 PASS - FOUR DATASETS PARSED "
    "AND STANDARDIZED"
)

print("=" * 100)

print("GENPEPT SCHEMA")

print(
    f"Sequence column : "
    f"{GENPEPT_SEQUENCE_COL}"
)

print(
    f"Label column    : "
    f"{GENPEPT_LABEL_COL}"
)

print(
    f"Sample ID column: "
    f"{GENPEPT_ID_COL}"
)

print(
    f"Split column    : "
    f"{GENPEPT_SPLIT_COL}"
)

print("-" * 100)

print("DATASET SUMMARY - BEFORE FILTERING")

print(
    dataset_summary.to_string(
        index=False
    )
)

print("-" * 100)

print("DATASET x SPLIT x CLASS")

print(
    dataset_split_summary.to_string(
        index=False
    )
)

print("-" * 100)

print("INTERNAL EXACT-DUPLICATE AUDIT")

print(
    internal_duplicate_summary_df.to_string(
        index=False
    )
)

print("-" * 100)

print(
    "NOTE: NO RECORD HAS BEEN REMOVED."
)

print(
    "Dataset 2 example_fasta files used: FALSE"
)

print("-" * 100)

print(
    f"Raw standardized : "
    f"{RAW_STANDARDIZED_PATH}"
)

print(
    f"Schema manifest  : "
    f"{SCHEMA_MANIFEST_PATH}"
)

print("=" * 100)

====================================================================================================
CELL 4 PASS - FOUR DATASETS PARSED AND STANDARDIZED
====================================================================================================
GENPEPT SCHEMA
Sequence column : sequence
Label column    : label
Sample ID column: sample_id
Split column    : split
----------------------------------------------------------------------------------------------------
DATASET SUMMARY - BEFORE FILTERING
             dataset  total  AMP  non_AMP  min_len  median_len  max_len  invalid_aa20  outside_10_200
External_Benchmark_1   8221 4665     3556        4        38.0      183             2              63
External_Benchmark_2   3556 1778     1778       11        28.0      183             0               0
External_Benchmark_3  14141 7070     7071       10        27.0      100           306               0
GenPept_Curated_2025  11000 5500     5500       10       113.0      200             0               0
----------------------------------------------------------------------------------------------------
DATASET x SPLIT x CLASS
             dataset      split  label    n  min_len  median_len  max_len  invalid_aa20  outside_10_200
External_Benchmark_1       test      0  656       11        50.0      155             0               0
External_Benchmark_1       test      1  894        6        34.0      161             0               5
External_Benchmark_1      train      0 2599       11        46.0      142             2               0
External_Benchmark_1      train      1 2877        5        35.0      183             0              39
External_Benchmark_1 validation      0  301       11        56.0      138             0               0
External_Benchmark_1 validation      1  894        4        35.5      157             0              19
External_Benchmark_2       test      0  712       11        27.0      175             0               0
External_Benchmark_2       test      1  712       11        28.0      183             0               0
External_Benchmark_2      train      0  712       11        28.0      158             0               0
External_Benchmark_2      train      1  712       11        28.0      149             0               0
External_Benchmark_2 validation      0  354       11        28.0      172             0               0
External_Benchmark_2 validation      1  354       11        29.0      136             0               0
External_Benchmark_3       test      0 1060       10        28.0      100             0               0
External_Benchmark_3       test      1 1060       11        26.0      100            50               0
External_Benchmark_3      train      0 4949       10        28.0      100             0               0
External_Benchmark_3      train      1 4948       11        26.0      100           214               0
External_Benchmark_3 validation      0 1062       10        29.0      100             0               0
External_Benchmark_3 validation      1 1062       11        27.0       99            42               0
GenPept_Curated_2025       test      0 1155       10        90.0      199             0               0
GenPept_Curated_2025       test      1 1155       13       124.0      200             0               0
GenPept_Curated_2025      train      0 3850       10        91.0      200             0               0
GenPept_Curated_2025      train      1 3850       10       123.0      200             0               0
GenPept_Curated_2025 validation      0  495       10        92.0      199             0               0
GenPept_Curated_2025 validation      1  495       13       124.0      200             0               0
----------------------------------------------------------------------------------------------------
INTERNAL EXACT-DUPLICATE AUDIT
             dataset  n_rows  n_unique_sequences  duplicate_rows  label_conflict_sequences
External_Benchmark_1    8221                8221               0                         0
External_Benchmark_2    3556                3556               0                         0
External_Benchmark_3   14141               14141               0                         0
GenPept_Curated_2025   11000               11000               0                         0
----------------------------------------------------------------------------------------------------
NOTE: NO RECORD HAS BEEN REMOVED.
Dataset 2 example_fasta files used: FALSE
----------------------------------------------------------------------------------------------------
Raw standardized : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark4_raw_standardized.csv
Schema manifest  : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark4_schema_manifest.json
====================================================================================================

In [11]:
# ============================================================
# CELL 5 - SEQUENCE QC & CROSS-DATASET EXACT-OVERLAP AUDIT
# ============================================================

from pathlib import Path
from datetime import datetime

import json
import itertools
import pandas as pd


# ------------------------------------------------------------
# 1. Validate state inherited from CELL 4
# ------------------------------------------------------------
REQUIRED_GLOBALS = [
    "benchmark_raw_df",
    "AUDIT_DIR",
    "MANIFEST_DIR",
    "AA20",
    "MIN_LEN",
    "MAX_LEN",
]

for name in REQUIRED_GLOBALS:
    assert name in globals(), (
        f"{name} missing. Run CELL 4 first."
    )


EXPECTED_DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "External_Benchmark_2",
    "External_Benchmark_3",
]

assert set(
    benchmark_raw_df["dataset"].unique()
) == set(EXPECTED_DATASETS)


# ------------------------------------------------------------
# 2. Confirm NO filtering has occurred yet
# ------------------------------------------------------------
EXPECTED_RAW_COUNTS = {
    "GenPept_Curated_2025": 11000,
    "External_Benchmark_1": 8221,
    "External_Benchmark_2": 3556,
    "External_Benchmark_3": 14141,
}

observed_raw_counts = (
    benchmark_raw_df["dataset"]
    .value_counts()
    .to_dict()
)

assert observed_raw_counts == EXPECTED_RAW_COUNTS, (
    "RAW DATASET MEMBERSHIP CHANGED BEFORE CELL 5.\n"
    f"Expected: {EXPECTED_RAW_COUNTS}\n"
    f"Observed: {observed_raw_counts}"
)


# ------------------------------------------------------------
# 3. Detailed invalid-residue audit
# ------------------------------------------------------------
invalid_rows_df = (
    benchmark_raw_df[
        ~benchmark_raw_df["is_valid_aa20"]
    ]
    .copy()
    .reset_index(drop=True)
)

invalid_residue_records = []

for _, row in invalid_rows_df.iterrows():

    invalid_set = sorted(
        set(row["sequence"]) - AA20
    )

    for residue in invalid_set:

        invalid_residue_records.append({
            "dataset":
                row["dataset"],

            "sample_id":
                row["sample_id"],

            "split":
                row["split"],

            "label":
                int(row["label"]),

            "residue":
                residue,

            "count_in_sequence":
                int(
                    row["sequence"].count(
                        residue
                    )
                ),

            "length":
                int(row["length"]),

            "original_header":
                row["original_header"],

            "source_file":
                row["source_file"],
        })


invalid_residue_detail_df = pd.DataFrame(
    invalid_residue_records
)

if len(invalid_residue_detail_df) > 0:

    invalid_residue_summary_df = (
        invalid_residue_detail_df
        .groupby(
            [
                "dataset",
                "residue",
            ],
            as_index=False,
        )
        .agg(
            affected_records=(
                "sample_id",
                "nunique",
            ),

            total_occurrences=(
                "count_in_sequence",
                "sum",
            ),
        )
        .sort_values(
            [
                "dataset",
                "affected_records",
                "residue",
            ],
            ascending=[
                True,
                False,
                True,
            ],
        )
        .reset_index(drop=True)
    )

else:

    invalid_residue_summary_df = pd.DataFrame(
        columns=[
            "dataset",
            "residue",
            "affected_records",
            "total_occurrences",
        ]
    )


# ------------------------------------------------------------
# 4. Detailed length-domain audit
#
# No record removal.
# ------------------------------------------------------------
length_issue_df = (
    benchmark_raw_df[
        ~benchmark_raw_df["within_10_200"]
    ]
    .copy()
    .reset_index(drop=True)
)

length_issue_df[
    "length_status"
] = length_issue_df[
    "length"
].apply(
    lambda x:
        "below_10"
        if x < MIN_LEN
        else "above_200"
)


length_issue_summary_df = (
    length_issue_df
    .groupby(
        [
            "dataset",
            "length_status",
            "split",
            "label",
        ],
        as_index=False,
    )
    .agg(
        n=(
            "sample_id",
            "count",
        ),

        min_len=(
            "length",
            "min",
        ),

        max_len=(
            "length",
            "max",
        ),
    )
)


# ------------------------------------------------------------
# 5. Exact sequence membership sets
# ------------------------------------------------------------
dataset_sequence_sets = {
    dataset:
        set(
            benchmark_raw_df.loc[
                benchmark_raw_df[
                    "dataset"
                ] == dataset,
                "sequence",
            ]
        )

    for dataset in EXPECTED_DATASETS
}

for dataset in EXPECTED_DATASETS:

    assert (
        len(dataset_sequence_sets[dataset])
        == EXPECTED_RAW_COUNTS[dataset]
    ), (
        f"Unexpected internal exact duplicates "
        f"in {dataset}"
    )


# ------------------------------------------------------------
# 6. Whole-dataset pairwise exact-overlap audit
#
# This describes dataset relatedness only.
# ------------------------------------------------------------
pairwise_overlap_records = []

pairwise_overlap_detail_records = []

for dataset_a, dataset_b in itertools.combinations(
    EXPECTED_DATASETS,
    2,
):

    seqs_a = dataset_sequence_sets[
        dataset_a
    ]

    seqs_b = dataset_sequence_sets[
        dataset_b
    ]

    overlap = seqs_a.intersection(
        seqs_b
    )

    labels_a = (
        benchmark_raw_df[
            benchmark_raw_df["dataset"]
            == dataset_a
        ]
        .set_index("sequence")["label"]
        .to_dict()
    )

    labels_b = (
        benchmark_raw_df[
            benchmark_raw_df["dataset"]
            == dataset_b
        ]
        .set_index("sequence")["label"]
        .to_dict()
    )

    label_conflicts = sum(
        int(
            labels_a[seq]
            != labels_b[seq]
        )
        for seq in overlap
    )

    pairwise_overlap_records.append({
        "dataset_a":
            dataset_a,

        "dataset_b":
            dataset_b,

        "n_a":
            len(seqs_a),

        "n_b":
            len(seqs_b),

        "exact_overlap":
            len(overlap),

        "label_conflicts":
            int(label_conflicts),

        "pct_of_a":
            (
                100.0
                * len(overlap)
                / len(seqs_a)
            ),

        "pct_of_b":
            (
                100.0
                * len(overlap)
                / len(seqs_b)
            ),
    })

    for seq in sorted(overlap):

        pairwise_overlap_detail_records.append({
            "dataset_a":
                dataset_a,

            "dataset_b":
                dataset_b,

            "sequence":
                seq,

            "label_a":
                int(labels_a[seq]),

            "label_b":
                int(labels_b[seq]),

            "label_conflict":
                bool(
                    labels_a[seq]
                    != labels_b[seq]
                ),

            "length":
                len(seq),
        })


pairwise_overlap_df = pd.DataFrame(
    pairwise_overlap_records
)

pairwise_overlap_detail_df = pd.DataFrame(
    pairwise_overlap_detail_records
)


# ------------------------------------------------------------
# 7. Protocol-2 source-development sets
#
# Train + Validation ONLY.
#
# Target dataset remains untouched here.
# ------------------------------------------------------------
source_dev_sets = {}

source_dev_label_maps = {}

for dataset in EXPECTED_DATASETS:

    source_dev_df = benchmark_raw_df[
        (
            benchmark_raw_df["dataset"]
            == dataset
        )
        &
        (
            benchmark_raw_df["split"]
            .isin(
                [
                    "train",
                    "validation",
                ]
            )
        )
    ].copy()

    source_dev_sets[
        dataset
    ] = set(
        source_dev_df["sequence"]
    )

    source_dev_label_maps[
        dataset
    ] = (
        source_dev_df
        .set_index("sequence")["label"]
        .to_dict()
    )


# ------------------------------------------------------------
# 8. Protocol-2 directional overlap audit
#
# Source = Train + Validation
# Target = ENTIRE external target dataset
#
# This matches the advisor's design:
# train on one dataset;
# the remaining datasets are external test sets.
#
# NO removal is performed in this cell.
# ------------------------------------------------------------
directional_overlap_records = []

directional_overlap_detail_records = []

for source_dataset in EXPECTED_DATASETS:

    source_sequences = (
        source_dev_sets[
            source_dataset
        ]
    )

    source_labels = (
        source_dev_label_maps[
            source_dataset
        ]
    )

    for target_dataset in EXPECTED_DATASETS:

        if (
            target_dataset
            == source_dataset
        ):
            continue

        target_df = benchmark_raw_df[
            benchmark_raw_df[
                "dataset"
            ] == target_dataset
        ].copy()

        target_sequence_set = set(
            target_df["sequence"]
        )

        overlap = (
            source_sequences
            .intersection(
                target_sequence_set
            )
        )

        target_labels = (
            target_df
            .set_index(
                "sequence"
            )["label"]
            .to_dict()
        )

        label_conflicts = sum(
            int(
                source_labels[seq]
                != target_labels[seq]
            )
            for seq in overlap
        )

        directional_overlap_records.append({
            "source_dataset":
                source_dataset,

            "target_dataset":
                target_dataset,

            "source_dev_n":
                len(source_sequences),

            "target_raw_n":
                len(target_df),

            "exact_overlap_to_remove":
                len(overlap),

            "label_conflicts":
                int(label_conflicts),

            "target_clean_n_if_removed":
                (
                    len(target_df)
                    - len(overlap)
                ),

            "target_removed_pct":
                (
                    100.0
                    * len(overlap)
                    / len(target_df)
                ),
        })

        for seq in sorted(overlap):

            directional_overlap_detail_records.append({
                "source_dataset":
                    source_dataset,

                "target_dataset":
                    target_dataset,

                "sequence":
                    seq,

                "source_label":
                    int(
                        source_labels[seq]
                    ),

                "target_label":
                    int(
                        target_labels[seq]
                    ),

                "label_conflict":
                    bool(
                        source_labels[seq]
                        != target_labels[seq]
                    ),

                "length":
                    len(seq),
            })


directional_overlap_df = pd.DataFrame(
    directional_overlap_records
)

directional_overlap_detail_df = (
    pd.DataFrame(
        directional_overlap_detail_records
    )
)


# ------------------------------------------------------------
# 9. Save detailed QC artifacts
# ------------------------------------------------------------
INVALID_ROWS_PATH = (
    AUDIT_DIR
    / "invalid_aa20_records.csv"
)

INVALID_RESIDUE_SUMMARY_PATH = (
    AUDIT_DIR
    / "invalid_residue_summary.csv"
)

LENGTH_ISSUES_PATH = (
    AUDIT_DIR
    / "length_outside_10_200_records.csv"
)

LENGTH_ISSUE_SUMMARY_PATH = (
    AUDIT_DIR
    / "length_outside_10_200_summary.csv"
)

PAIRWISE_OVERLAP_PATH = (
    AUDIT_DIR
    / "cross_dataset_pairwise_exact_overlap.csv"
)

PAIRWISE_OVERLAP_DETAIL_PATH = (
    AUDIT_DIR
    / "cross_dataset_pairwise_exact_overlap_details.csv"
)

DIRECTIONAL_OVERLAP_PATH = (
    AUDIT_DIR
    / "protocol2_directional_exact_overlap.csv"
)

DIRECTIONAL_OVERLAP_DETAIL_PATH = (
    AUDIT_DIR
    / "protocol2_directional_exact_overlap_details.csv"
)


invalid_rows_df.to_csv(
    INVALID_ROWS_PATH,
    index=False,
)

invalid_residue_summary_df.to_csv(
    INVALID_RESIDUE_SUMMARY_PATH,
    index=False,
)

length_issue_df.to_csv(
    LENGTH_ISSUES_PATH,
    index=False,
)

length_issue_summary_df.to_csv(
    LENGTH_ISSUE_SUMMARY_PATH,
    index=False,
)

pairwise_overlap_df.to_csv(
    PAIRWISE_OVERLAP_PATH,
    index=False,
)

pairwise_overlap_detail_df.to_csv(
    PAIRWISE_OVERLAP_DETAIL_PATH,
    index=False,
)

directional_overlap_df.to_csv(
    DIRECTIONAL_OVERLAP_PATH,
    index=False,
)

directional_overlap_detail_df.to_csv(
    DIRECTIONAL_OVERLAP_DETAIL_PATH,
    index=False,
)


# ------------------------------------------------------------
# 10. Save QC / overlap manifest
# ------------------------------------------------------------
QC_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark4_qc_overlap_manifest.json"
)

qc_manifest = {
    "schema_version": "1.0",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "filtering_applied":
        False,

    "record_removal_applied":
        False,

    "aa20_contract":
        "".join(sorted(AA20)),

    "genpept_length_domain": {
        "min": MIN_LEN,
        "max": MAX_LEN,
    },

    "protocol2_overlap_definition": (
        "exact normalized sequence overlap "
        "between source train+validation "
        "and entire external target dataset"
    ),

    "protocol2_overlap_action_in_this_cell":
        "AUDIT_ONLY_NO_REMOVAL",

    "raw_dataset_counts":
        EXPECTED_RAW_COUNTS,

    "n_invalid_aa20_records":
        int(len(invalid_rows_df)),

    "n_outside_10_200_records":
        int(len(length_issue_df)),

    "n_pairwise_overlap_records":
        int(
            len(
                pairwise_overlap_detail_df
            )
        ),

    "n_directional_overlap_records":
        int(
            len(
                directional_overlap_detail_df
            )
        ),
}

with open(
    QC_MANIFEST_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        qc_manifest,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 11. Integrity assertions
# ------------------------------------------------------------
assert (
    benchmark_raw_df[
        "dataset"
    ]
    .value_counts()
    .to_dict()
    == EXPECTED_RAW_COUNTS
), (
    "Dataset membership changed during CELL 5."
)

assert len(
    directional_overlap_df
) == 12, (
    "Expected 4 x 3 = 12 "
    "directional source-target pairs."
)

assert len(
    pairwise_overlap_df
) == 6, (
    "Expected C(4,2) = 6 "
    "undirected dataset pairs."
)

assert QC_MANIFEST_PATH.exists()
assert PAIRWISE_OVERLAP_PATH.exists()
assert DIRECTIONAL_OVERLAP_PATH.exists()


# ------------------------------------------------------------
# 12. Report
# ------------------------------------------------------------
print("=" * 106)

print(
    "CELL 5 PASS - SEQUENCE QC AND "
    "CROSS-DATASET EXACT-OVERLAP AUDIT COMPLETE"
)

print("=" * 106)

print(
    "NO RECORD REMOVED IN CELL 5"
)

print("-" * 106)

print("INVALID AA20 SUMMARY")

if len(
    invalid_residue_summary_df
) == 0:

    print(
        "No invalid residues detected."
    )

else:

    print(
        invalid_residue_summary_df
        .to_string(
            index=False
        )
    )

print("-" * 106)

print("LENGTH OUTSIDE 10-200 SUMMARY")

if len(
    length_issue_summary_df
) == 0:

    print(
        "No length-domain issues detected."
    )

else:

    print(
        length_issue_summary_df
        .to_string(
            index=False
        )
    )

print("-" * 106)

print(
    "WHOLE-DATASET PAIRWISE EXACT OVERLAP"
)

print(
    pairwise_overlap_df[
        [
            "dataset_a",
            "dataset_b",
            "n_a",
            "n_b",
            "exact_overlap",
            "label_conflicts",
            "pct_of_a",
            "pct_of_b",
        ]
    ].to_string(
        index=False,
        float_format=lambda x:
            f"{x:.4f}",
    )
)

print("-" * 106)

print(
    "PROTOCOL 2 - SOURCE TRAIN+VALIDATION "
    "VS ENTIRE TARGET DATASET"
)

print(
    directional_overlap_df[
        [
            "source_dataset",
            "target_dataset",
            "source_dev_n",
            "target_raw_n",
            "exact_overlap_to_remove",
            "label_conflicts",
            "target_clean_n_if_removed",
            "target_removed_pct",
        ]
    ].to_string(
        index=False,
        float_format=lambda x:
            f"{x:.4f}",
    )
)

print("-" * 106)

print(
    f"Invalid records : "
    f"{INVALID_ROWS_PATH}"
)

print(
    f"Length issues   : "
    f"{LENGTH_ISSUES_PATH}"
)

print(
    f"Pairwise audit  : "
    f"{PAIRWISE_OVERLAP_PATH}"
)

print(
    f"Protocol2 audit : "
    f"{DIRECTIONAL_OVERLAP_PATH}"
)

print(
    f"QC manifest     : "
    f"{QC_MANIFEST_PATH}"
)

print("=" * 106)

==========================================================================================================
CELL 5 PASS - SEQUENCE QC AND CROSS-DATASET EXACT-OVERLAP AUDIT COMPLETE
==========================================================================================================
NO RECORD REMOVED IN CELL 5
----------------------------------------------------------------------------------------------------------
INVALID AA20 SUMMARY
             dataset residue  affected_records  total_occurrences
External_Benchmark_1       X                 2                  4
External_Benchmark_3       X               275                977
External_Benchmark_3       B                21                 70
External_Benchmark_3       J                20                 61
External_Benchmark_3       O                13                 31
External_Benchmark_3       Z                12                 23
External_Benchmark_3       U                 6                 15
----------------------------------------------------------------------------------------------------------
LENGTH OUTSIDE 10-200 SUMMARY
             dataset length_status      split  label  n  min_len  max_len
External_Benchmark_1      below_10       test      1  5        6        8
External_Benchmark_1      below_10      train      1 39        5        9
External_Benchmark_1      below_10 validation      1 19        4        9
----------------------------------------------------------------------------------------------------------
WHOLE-DATASET PAIRWISE EXACT OVERLAP
           dataset_a            dataset_b   n_a   n_b  exact_overlap  label_conflicts  pct_of_a  pct_of_b
GenPept_Curated_2025 External_Benchmark_1 11000  8221             81               10    0.7364    0.9853
GenPept_Curated_2025 External_Benchmark_2 11000  3556             28                1    0.2545    0.7874
GenPept_Curated_2025 External_Benchmark_3 11000 14141             63                5    0.5727    0.4455
External_Benchmark_1 External_Benchmark_2  8221  3556           1766                0   21.4816   49.6625
External_Benchmark_1 External_Benchmark_3  8221 14141           1117                0   13.5872    7.8990
External_Benchmark_2 External_Benchmark_3  3556 14141            564                0   15.8605    3.9884
----------------------------------------------------------------------------------------------------------
PROTOCOL 2 - SOURCE TRAIN+VALIDATION VS ENTIRE TARGET DATASET
      source_dataset       target_dataset  source_dev_n  target_raw_n  exact_overlap_to_remove  label_conflicts  target_clean_n_if_removed  target_removed_pct
GenPept_Curated_2025 External_Benchmark_1          8690          8221                       61                6                       8160              0.7420
GenPept_Curated_2025 External_Benchmark_2          8690          3556                       23                1                       3533              0.6468
GenPept_Curated_2025 External_Benchmark_3          8690         14141                       54                4                      14087              0.3819
External_Benchmark_1 GenPept_Curated_2025          6671         11000                       66                8                      10934              0.6000
External_Benchmark_1 External_Benchmark_2          6671          3556                     1419                0                       2137             39.9044
External_Benchmark_1 External_Benchmark_3          6671         14141                      894                0                      13247              6.3220
External_Benchmark_2 GenPept_Curated_2025          2132         11000                       13                0                      10987              0.1182
External_Benchmark_2 External_Benchmark_1          2132          8221                     1061                0                       7160             12.9060
External_Benchmark_2 External_Benchmark_3          2132         14141                      323                0                      13818              2.2841
External_Benchmark_3 GenPept_Curated_2025         12021         11000                       54                4                      10946              0.4909
External_Benchmark_3 External_Benchmark_1         12021          8221                      952                0                       7269             11.5801
External_Benchmark_3 External_Benchmark_2         12021          3556                      467                0                       3089             13.1327
----------------------------------------------------------------------------------------------------------
Invalid records : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/invalid_aa20_records.csv
Length issues   : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/length_outside_10_200_records.csv
Pairwise audit  : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/cross_dataset_pairwise_exact_overlap.csv
Protocol2 audit : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/protocol2_directional_exact_overlap.csv
QC manifest     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark4_qc_overlap_manifest.json
==========================================================================================================

In [12]:
# ============================================================
# CELL 6 - HARMONIZED QC COHORT LOCK
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import pandas as pd


# ------------------------------------------------------------
# 1. Validate upstream state
# ------------------------------------------------------------
REQUIRED_GLOBALS = [
    "benchmark_raw_df",
    "AA20",
    "MIN_LEN",
    "MAX_LEN",
    "AUDIT_DIR",
    "SPLIT_DIR",
    "MANIFEST_DIR",
]

for name in REQUIRED_GLOBALS:
    assert name in globals(), (
        f"{name} missing. Run previous cells first."
    )


EXPECTED_RAW_COUNTS = {
    "GenPept_Curated_2025": 11000,
    "External_Benchmark_1": 8221,
    "External_Benchmark_2": 3556,
    "External_Benchmark_3": 14141,
}

assert (
    benchmark_raw_df["dataset"]
    .value_counts()
    .to_dict()
    == EXPECTED_RAW_COUNTS
), "Raw dataset membership changed unexpectedly."


# ------------------------------------------------------------
# 2. Lock harmonized eligibility policy
#
# Applied identically to ALL FOUR datasets:
#
#   - 20 canonical amino acids only
#   - 10 <= length <= 200
#
# No balancing
# No relabeling
# No imputation/replacement
# No split reassignment
# ------------------------------------------------------------
HARMONIZED_QC_POLICY = {
    "canonical_amino_acids":
        "ACDEFGHIKLMNPQRSTVWY",

    "minimum_length":
        10,

    "maximum_length":
        200,

    "invalid_residue_action":
        "remove_record",

    "out_of_range_action":
        "remove_record",

    "residue_imputation":
        False,

    "class_balancing":
        False,

    "relabeling":
        False,

    "split_reassignment":
        False,
}


# ------------------------------------------------------------
# 3. Recompute QC directly from sequence
#
# Do not rely blindly on flags from CELL 4.
# ------------------------------------------------------------
qc_df = benchmark_raw_df.copy()

qc_df["length_qc"] = (
    qc_df["sequence"]
    .str.len()
)

qc_df["invalid_residues_qc"] = (
    qc_df["sequence"]
    .apply(
        lambda seq:
            "".join(
                sorted(
                    set(seq) - AA20
                )
            )
    )
)

qc_df["valid_aa20_qc"] = (
    qc_df["invalid_residues_qc"] == ""
)

qc_df["valid_length_qc"] = (
    qc_df["length_qc"]
    .between(
        MIN_LEN,
        MAX_LEN,
        inclusive="both",
    )
)


# ------------------------------------------------------------
# 4. Assign explicit removal reason
# ------------------------------------------------------------
def build_removal_reason(row):

    reasons = []

    if not row["valid_aa20_qc"]:
        reasons.append(
            "noncanonical_residue"
        )

    if row["length_qc"] < MIN_LEN:
        reasons.append(
            "length_below_10"
        )

    if row["length_qc"] > MAX_LEN:
        reasons.append(
            "length_above_200"
        )

    if len(reasons) == 0:
        return "KEEP"

    return ";".join(reasons)


qc_df["qc_decision"] = (
    qc_df.apply(
        build_removal_reason,
        axis=1,
    )
)

qc_df["qc_keep"] = (
    qc_df["qc_decision"] == "KEEP"
)


# ------------------------------------------------------------
# 5. Separate retained and removed records
# ------------------------------------------------------------
removed_qc_df = (
    qc_df[
        ~qc_df["qc_keep"]
    ]
    .copy()
    .reset_index(drop=True)
)

benchmark_qc_df = (
    qc_df[
        qc_df["qc_keep"]
    ]
    .copy()
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 6. Critical assertions
# ------------------------------------------------------------
assert (
    benchmark_qc_df[
        "valid_aa20_qc"
    ].all()
)

assert (
    benchmark_qc_df[
        "valid_length_qc"
    ].all()
)

assert (
    benchmark_qc_df[
        "length_qc"
    ].between(
        10,
        200,
        inclusive="both",
    ).all()
)

assert (
    benchmark_qc_df[
        "invalid_residues_qc"
    ] == ""
).all()


# ------------------------------------------------------------
# 7. Confirm no label/split modification
# ------------------------------------------------------------
assert set(
    benchmark_qc_df["label"].unique()
) <= {0, 1}

assert set(
    benchmark_qc_df["split"].unique()
) == {
    "train",
    "validation",
    "test",
}


# ------------------------------------------------------------
# 8. Verify no internal exact duplicates
# ------------------------------------------------------------
internal_duplicate_rows = []

for dataset_name, part in (
    benchmark_qc_df.groupby(
        "dataset"
    )
):

    n_rows = len(part)

    n_unique = (
        part["sequence"]
        .nunique()
    )

    label_conflicts = (
        part
        .groupby("sequence")["label"]
        .nunique()
        .gt(1)
        .sum()
    )

    internal_duplicate_rows.append({
        "dataset":
            dataset_name,

        "n_rows":
            int(n_rows),

        "n_unique_sequences":
            int(n_unique),

        "duplicate_rows":
            int(
                n_rows - n_unique
            ),

        "label_conflict_sequences":
            int(label_conflicts),
    })


qc_internal_duplicate_df = (
    pd.DataFrame(
        internal_duplicate_rows
    )
)

assert (
    qc_internal_duplicate_df[
        "duplicate_rows"
    ] == 0
).all()

assert (
    qc_internal_duplicate_df[
        "label_conflict_sequences"
    ] == 0
).all()


# ------------------------------------------------------------
# 9. Removal summary
# ------------------------------------------------------------
removal_summary_df = (
    removed_qc_df
    .groupby(
        [
            "dataset",
            "qc_decision",
        ],
        as_index=False,
    )
    .agg(
        n_removed=(
            "sample_id",
            "count",
        )
    )
)


# ------------------------------------------------------------
# 10. Dataset summary after harmonized QC
# ------------------------------------------------------------
qc_dataset_summary_df = (
    benchmark_qc_df
    .groupby(
        "dataset",
        as_index=False,
    )
    .agg(
        total=(
            "sample_id",
            "count",
        ),

        AMP=(
            "label",
            lambda x:
                int(
                    (x == 1).sum()
                ),
        ),

        non_AMP=(
            "label",
            lambda x:
                int(
                    (x == 0).sum()
                ),
        ),

        min_len=(
            "length_qc",
            "min",
        ),

        median_len=(
            "length_qc",
            "median",
        ),

        max_len=(
            "length_qc",
            "max",
        ),
    )
)


# ------------------------------------------------------------
# 11. Dataset x split x class summary
# ------------------------------------------------------------
qc_split_summary_df = (
    benchmark_qc_df
    .groupby(
        [
            "dataset",
            "split",
            "label",
        ],
        as_index=False,
    )
    .agg(
        n=(
            "sample_id",
            "count",
        ),

        min_len=(
            "length_qc",
            "min",
        ),

        median_len=(
            "length_qc",
            "median",
        ),

        max_len=(
            "length_qc",
            "max",
        ),
    )
)


# ------------------------------------------------------------
# 12. Before/after membership summary
# ------------------------------------------------------------
raw_counts_df = (
    benchmark_raw_df
    .groupby(
        "dataset",
        as_index=False,
    )
    .agg(
        raw_n=(
            "sample_id",
            "count",
        )
    )
)

clean_counts_df = (
    benchmark_qc_df
    .groupby(
        "dataset",
        as_index=False,
    )
    .agg(
        clean_n=(
            "sample_id",
            "count",
        )
    )
)

membership_summary_df = (
    raw_counts_df
    .merge(
        clean_counts_df,
        on="dataset",
        how="left",
    )
)

membership_summary_df[
    "removed_n"
] = (
    membership_summary_df[
        "raw_n"
    ]
    - membership_summary_df[
        "clean_n"
    ]
)

membership_summary_df[
    "removed_pct"
] = (
    100.0
    * membership_summary_df[
        "removed_n"
    ]
    / membership_summary_df[
        "raw_n"
    ]
)


# ------------------------------------------------------------
# 13. Expected values from CELL 5 audit
# ------------------------------------------------------------
EXPECTED_CLEAN_COUNTS = {
    "GenPept_Curated_2025": 11000,
    "External_Benchmark_1": 8156,
    "External_Benchmark_2": 3556,
    "External_Benchmark_3": 13835,
}

observed_clean_counts = (
    benchmark_qc_df[
        "dataset"
    ]
    .value_counts()
    .to_dict()
)

assert (
    observed_clean_counts
    == EXPECTED_CLEAN_COUNTS
), (
    "Unexpected harmonized QC counts.\n"
    f"Expected: {EXPECTED_CLEAN_COUNTS}\n"
    f"Observed: {observed_clean_counts}"
)

assert len(
    removed_qc_df
) == 371, (
    "Expected exactly 371 QC exclusions "
    "from CELL 5 evidence."
)


# ------------------------------------------------------------
# 14. Confirm GenPept membership unchanged
# ------------------------------------------------------------
genpept_clean = (
    benchmark_qc_df[
        benchmark_qc_df[
            "dataset"
        ]
        == "GenPept_Curated_2025"
    ]
)

assert len(
    genpept_clean
) == 11000

genpept_split_check = {
    split:
        int(
            (
                genpept_clean[
                    "split"
                ] == split
            ).sum()
        )

    for split in [
        "train",
        "validation",
        "test",
    ]
}

assert (
    genpept_split_check
    == {
        "train": 7700,
        "validation": 990,
        "test": 2310,
    }
)


# ------------------------------------------------------------
# 15. Save retained harmonized cohort
# ------------------------------------------------------------
HARMONIZED_DATA_PATH = (
    SPLIT_DIR
    / "benchmark4_harmonized_qc.csv"
)

benchmark_qc_df.to_csv(
    HARMONIZED_DATA_PATH,
    index=False,
)


# ------------------------------------------------------------
# 16. Save excluded records
# ------------------------------------------------------------
QC_REMOVED_PATH = (
    AUDIT_DIR
    / "benchmark4_harmonized_qc_removed_records.csv"
)

removed_qc_df.to_csv(
    QC_REMOVED_PATH,
    index=False,
)


# ------------------------------------------------------------
# 17. Save summaries
# ------------------------------------------------------------
QC_MEMBERSHIP_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark4_harmonized_qc_membership_summary.csv"
)

QC_DATASET_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark4_harmonized_qc_dataset_summary.csv"
)

QC_SPLIT_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark4_harmonized_qc_split_class_summary.csv"
)

QC_DUPLICATE_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark4_harmonized_qc_internal_duplicates.csv"
)


membership_summary_df.to_csv(
    QC_MEMBERSHIP_SUMMARY_PATH,
    index=False,
)

qc_dataset_summary_df.to_csv(
    QC_DATASET_SUMMARY_PATH,
    index=False,
)

qc_split_summary_df.to_csv(
    QC_SPLIT_SUMMARY_PATH,
    index=False,
)

qc_internal_duplicate_df.to_csv(
    QC_DUPLICATE_SUMMARY_PATH,
    index=False,
)


# ------------------------------------------------------------
# 18. SHA256 of harmonized cohort
# ------------------------------------------------------------
def file_sha256(path):

    h = hashlib.sha256()

    with open(path, "rb") as f:

        for chunk in iter(
            lambda:
                f.read(
                    1024 * 1024
                ),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


HARMONIZED_DATA_SHA256 = (
    file_sha256(
        HARMONIZED_DATA_PATH
    )
)


# ------------------------------------------------------------
# 19. Save immutable QC manifest
# ------------------------------------------------------------
HARMONIZED_QC_MANIFEST_PATH = (
    MANIFEST_DIR
    / "harmonized_qc_policy.json"
)

qc_manifest = {
    "schema_version":
        "1.0",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "purpose":
        (
            "Common evaluation domain "
            "for all four benchmark datasets"
        ),

    "policy":
        HARMONIZED_QC_POLICY,

    "raw_counts":
        EXPECTED_RAW_COUNTS,

    "clean_counts":
        EXPECTED_CLEAN_COUNTS,

    "total_raw":
        int(
            len(
                benchmark_raw_df
            )
        ),

    "total_clean":
        int(
            len(
                benchmark_qc_df
            )
        ),

    "total_removed":
        int(
            len(
                removed_qc_df
            )
        ),

    "balancing_applied":
        False,

    "relabeling_applied":
        False,

    "split_reassignment_applied":
        False,

    "sequence_repair_applied":
        False,

    "cross_dataset_overlap_removal_applied":
        False,

    "harmonized_data_file":
        str(
            HARMONIZED_DATA_PATH
        ),

    "harmonized_data_sha256":
        HARMONIZED_DATA_SHA256,
}

with open(
    HARMONIZED_QC_MANIFEST_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        qc_manifest,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 20. Final assertions
# ------------------------------------------------------------
assert (
    HARMONIZED_DATA_PATH.exists()
)

assert (
    QC_REMOVED_PATH.exists()
)

assert (
    HARMONIZED_QC_MANIFEST_PATH.exists()
)

assert len(
    benchmark_qc_df
) == 36547

assert len(
    removed_qc_df
) == 371


# ------------------------------------------------------------
# 21. Report
# ------------------------------------------------------------
print("=" * 104)

print(
    "CELL 6 PASS - HARMONIZED QC "
    "EVALUATION COHORT LOCKED"
)

print("=" * 104)

print(
    "POLICY:"
)

print(
    "  Canonical residues : "
    "ACDEFGHIKLMNPQRSTVWY"
)

print(
    "  Length domain      : "
    "10 <= L <= 200"
)

print(
    "  Residue imputation : FALSE"
)

print(
    "  Class balancing    : FALSE"
)

print(
    "  Relabeling         : FALSE"
)

print(
    "  Split reassignment : FALSE"
)

print("-" * 104)

print(
    "BEFORE / AFTER QC"
)

print(
    membership_summary_df
    .to_string(
        index=False,
        float_format=lambda x:
            f"{x:.4f}",
    )
)

print("-" * 104)

print(
    "REMOVAL REASONS"
)

print(
    removal_summary_df
    .to_string(
        index=False
    )
)

print("-" * 104)

print(
    "FINAL DATASET SUMMARY"
)

print(
    qc_dataset_summary_df
    .to_string(
        index=False
    )
)

print("-" * 104)

print(
    "FINAL DATASET x SPLIT x CLASS"
)

print(
    qc_split_summary_df
    .to_string(
        index=False
    )
)

print("-" * 104)

print(
    "INTERNAL DUPLICATE CHECK"
)

print(
    qc_internal_duplicate_df
    .to_string(
        index=False
    )
)

print("-" * 104)

print(
    f"Clean cohort : "
    f"{HARMONIZED_DATA_PATH}"
)

print(
    f"Removed rows : "
    f"{QC_REMOVED_PATH}"
)

print(
    f"SHA-256      : "
    f"{HARMONIZED_DATA_SHA256}"
)

print(
    f"Manifest     : "
    f"{HARMONIZED_QC_MANIFEST_PATH}"
)

print("=" * 104)

========================================================================================================
CELL 6 PASS - HARMONIZED QC EVALUATION COHORT LOCKED
========================================================================================================
POLICY:
  Canonical residues : ACDEFGHIKLMNPQRSTVWY
  Length domain      : 10 <= L <= 200
  Residue imputation : FALSE
  Class balancing    : FALSE
  Relabeling         : FALSE
  Split reassignment : FALSE
--------------------------------------------------------------------------------------------------------
BEFORE / AFTER QC
             dataset  raw_n  clean_n  removed_n  removed_pct
External_Benchmark_1   8221     8156         65       0.7907
External_Benchmark_2   3556     3556          0       0.0000
External_Benchmark_3  14141    13835        306       2.1639
GenPept_Curated_2025  11000    11000          0       0.0000
--------------------------------------------------------------------------------------------------------
REMOVAL REASONS
             dataset          qc_decision  n_removed
External_Benchmark_1      length_below_10         63
External_Benchmark_1 noncanonical_residue          2
External_Benchmark_3 noncanonical_residue        306
--------------------------------------------------------------------------------------------------------
FINAL DATASET SUMMARY
             dataset  total  AMP  non_AMP  min_len  median_len  max_len
External_Benchmark_1   8156 4602     3554       10        38.0      183
External_Benchmark_2   3556 1778     1778       11        28.0      183
External_Benchmark_3  13835 6764     7071       10        27.0      100
GenPept_Curated_2025  11000 5500     5500       10       113.0      200
--------------------------------------------------------------------------------------------------------
FINAL DATASET x SPLIT x CLASS
             dataset      split  label    n  min_len  median_len  max_len
External_Benchmark_1       test      0  656       11        50.0      155
External_Benchmark_1       test      1  889       10        35.0      161
External_Benchmark_1      train      0 2597       11        46.0      142
External_Benchmark_1      train      1 2838       10        35.0      183
External_Benchmark_1 validation      0  301       11        56.0      138
External_Benchmark_1 validation      1  875       10        36.0      157
External_Benchmark_2       test      0  712       11        27.0      175
External_Benchmark_2       test      1  712       11        28.0      183
External_Benchmark_2      train      0  712       11        28.0      158
External_Benchmark_2      train      1  712       11        28.0      149
External_Benchmark_2 validation      0  354       11        28.0      172
External_Benchmark_2 validation      1  354       11        29.0      136
External_Benchmark_3       test      0 1060       10        28.0      100
External_Benchmark_3       test      1 1010       11        26.0      100
External_Benchmark_3      train      0 4949       10        28.0      100
External_Benchmark_3      train      1 4734       11        27.0      100
External_Benchmark_3 validation      0 1062       10        29.0      100
External_Benchmark_3 validation      1 1020       11        28.0       99
GenPept_Curated_2025       test      0 1155       10        90.0      199
GenPept_Curated_2025       test      1 1155       13       124.0      200
GenPept_Curated_2025      train      0 3850       10        91.0      200
GenPept_Curated_2025      train      1 3850       10       123.0      200
GenPept_Curated_2025 validation      0  495       10        92.0      199
GenPept_Curated_2025 validation      1  495       13       124.0      200
--------------------------------------------------------------------------------------------------------
INTERNAL DUPLICATE CHECK
             dataset  n_rows  n_unique_sequences  duplicate_rows  label_conflict_sequences
External_Benchmark_1    8156                8156               0                         0
External_Benchmark_2    3556                3556               0                         0
External_Benchmark_3   13835               13835               0                         0
GenPept_Curated_2025   11000               11000               0                         0
--------------------------------------------------------------------------------------------------------
Clean cohort : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/splits/benchmark4_harmonized_qc.csv
Removed rows : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark4_harmonized_qc_removed_records.csv
SHA-256      : 2dcc840b8b481fdcbfaba7baa428773a81f255a73b0222560cfa8fd7c483a476
Manifest     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/harmonized_qc_policy.json
========================================================================================================

In [14]:
# ============================================================
# CELL 7 - FINAL EXPERIMENT SPLIT LOCK &
#          STRICT CROSS-DATASET DECONTAMINATION
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import pandas as pd


# ------------------------------------------------------------
# 1. Validate upstream state
# ------------------------------------------------------------
REQUIRED_GLOBALS = [
    "benchmark_qc_df",
    "SPLIT_DIR",
    "MANIFEST_DIR",
    "AUDIT_DIR",
    "SEEDS",
]

for name in REQUIRED_GLOBALS:
    assert name in globals(), (
        f"{name} missing. Run CELLS 1-6 first."
    )


DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "External_Benchmark_2",
    "External_Benchmark_3",
]


EXPECTED_CLEAN_COUNTS = {
    "GenPept_Curated_2025": 11000,
    "External_Benchmark_1": 8156,
    "External_Benchmark_2": 3556,
    "External_Benchmark_3": 13835,
}


observed_counts = (
    benchmark_qc_df[
        "dataset"
    ]
    .value_counts()
    .to_dict()
)

assert observed_counts == EXPECTED_CLEAN_COUNTS, (
    "CELL 6 cohort changed unexpectedly.\n"
    f"Expected: {EXPECTED_CLEAN_COUNTS}\n"
    f"Observed: {observed_counts}"
)


# ------------------------------------------------------------
# 2. Lock model seeds
# ------------------------------------------------------------
MODEL_SEEDS = list(SEEDS)

assert MODEL_SEEDS == list(
    range(100, 110)
)

assert len(MODEL_SEEDS) == 10


# ------------------------------------------------------------
# 3. Output directories
# ------------------------------------------------------------
WITHIN_DATASET_DIR = (
    SPLIT_DIR
    / "within_dataset"
)

CROSS_DATASET_DIR = (
    SPLIT_DIR
    / "cross_dataset_transfer"
)

WITHIN_DATASET_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

CROSS_DATASET_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ------------------------------------------------------------
# 4. SHA-256 helper
# ------------------------------------------------------------
def sha256_file(path):

    h = hashlib.sha256()

    with open(path, "rb") as f:

        for chunk in iter(
            lambda:
                f.read(1024 * 1024),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


# ------------------------------------------------------------
# 5. Experiment columns
# ------------------------------------------------------------
EXPERIMENT_COLUMNS = [
    "dataset",
    "sample_id",
    "original_header",
    "sequence",
    "label",
    "split",
    "source_file",
    "length_qc",
    "sequence_sha256",
]

for column in EXPERIMENT_COLUMNS:

    assert column in benchmark_qc_df.columns, (
        f"Required column missing: {column}"
    )


# ------------------------------------------------------------
# 6. Verify four datasets and fixed splits
# ------------------------------------------------------------
for dataset in DATASETS:

    subset = benchmark_qc_df[
        benchmark_qc_df[
            "dataset"
        ] == dataset
    ]

    assert set(
        subset["split"].unique()
    ) == {
        "train",
        "validation",
        "test",
    }

    assert subset[
        "sequence"
    ].is_unique

    for split_name in [
        "train",
        "validation",
        "test",
    ]:

        split_df = subset[
            subset[
                "split"
            ] == split_name
        ]

        assert len(split_df) > 0

        assert set(
            split_df[
                "label"
            ].unique()
        ) == {0, 1}


# ------------------------------------------------------------
# 7. Experiment 1:
#    persist frozen within-dataset splits
# ------------------------------------------------------------
within_registry = {}

within_summary_rows = []


for dataset in DATASETS:

    dataset_dir = (
        WITHIN_DATASET_DIR
        / dataset
    )

    dataset_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    within_registry[
        dataset
    ] = {}

    for split_name in [
        "train",
        "validation",
        "test",
    ]:

        split_df = (
            benchmark_qc_df[
                (
                    benchmark_qc_df[
                        "dataset"
                    ] == dataset
                )
                &
                (
                    benchmark_qc_df[
                        "split"
                    ] == split_name
                )
            ]
            [
                EXPERIMENT_COLUMNS
            ]
            .copy()
            .reset_index(drop=True)
        )

        assert split_df[
            "sequence"
        ].is_unique

        output_path = (
            dataset_dir
            / f"{split_name}.csv"
        )

        split_df.to_csv(
            output_path,
            index=False,
        )

        file_hash = sha256_file(
            output_path
        )

        n_amp = int(
            (
                split_df["label"] == 1
            ).sum()
        )

        n_nonamp = int(
            (
                split_df["label"] == 0
            ).sum()
        )

        within_registry[
            dataset
        ][
            split_name
        ] = {
            "path":
                str(output_path),

            "n":
                int(len(split_df)),

            "AMP":
                n_amp,

            "non_AMP":
                n_nonamp,

            "sha256":
                file_hash,
        }

        within_summary_rows.append({
            "dataset":
                dataset,

            "split":
                split_name,

            "n":
                int(len(split_df)),

            "AMP":
                n_amp,

            "non_AMP":
                n_nonamp,

            "path":
                str(output_path),

            "sha256":
                file_hash,
        })


within_summary_df = pd.DataFrame(
    within_summary_rows
)


# ------------------------------------------------------------
# 8. Verify GenPept frozen manuscript split
# ------------------------------------------------------------
GENPEPT_EXPECTED = {
    "train": 7700,
    "validation": 990,
    "test": 2310,
}

for split_name, expected_n in (
    GENPEPT_EXPECTED.items()
):

    observed_n = (
        within_registry[
            "GenPept_Curated_2025"
        ][
            split_name
        ][
            "n"
        ]
    )

    assert observed_n == expected_n


# ------------------------------------------------------------
# 9. Final Experiment 2 contract
#
# MODEL FIT:
#   source TRAIN only
#
# MODEL SELECTION:
#   source VALIDATION only
#
# INTERNAL SOURCE TEST:
#   NEVER used for fitting / tuning
#
# EXTERNAL EVALUATION:
#   target TEST only
#
# STRICT DECONTAMINATION:
#   remove target-test sequence if it occurs
#   ANYWHERE in source dataset:
#   train + validation + test.
#
# Source-test sequences are used ONLY for
# sequence-identity decontamination.
# ------------------------------------------------------------
CROSS_PROTOCOL = {

    "source_model_fit":
        "train_only",

    "source_model_selection":
        "validation_only",

    "source_test_model_usage":
        "none",

    "source_test_decontamination_usage":
        "sequence_identity_only",

    "target_evaluation":
        "test_only",

    "target_training":
        False,

    "target_validation_usage":
        False,

    "target_retraining":
        False,

    "target_finetuning":
        False,

    "target_threshold_tuning":
        False,

    "target_feature_fitting":
        False,

    "decontamination_reference":
        "entire_source_dataset",

    "decontamination_definition":
        "exact_normalized_sequence_identity",

    "decontamination_action":
        "remove_from_target_test",

    "data_resplitting_per_seed":
        False,
}


# ------------------------------------------------------------
# 10. Construct the 12 directional pairs
# ------------------------------------------------------------
cross_summary_rows = []

cross_pair_registry = {}


for source_dataset in DATASETS:

    source_all = (
        benchmark_qc_df[
            benchmark_qc_df[
                "dataset"
            ] == source_dataset
        ]
        .copy()
        .reset_index(drop=True)
    )

    source_train = (
        source_all[
            source_all[
                "split"
            ] == "train"
        ]
        .copy()
    )

    source_validation = (
        source_all[
            source_all[
                "split"
            ] == "validation"
        ]
        .copy()
    )

    source_test = (
        source_all[
            source_all[
                "split"
            ] == "test"
        ]
        .copy()
    )

    source_dev = pd.concat(
        [
            source_train,
            source_validation,
        ],
        ignore_index=True,
    )

    # No internal duplicates were allowed.
    assert source_all[
        "sequence"
    ].is_unique

    assert source_dev[
        "sequence"
    ].is_unique


    source_all_sequences = set(
        source_all[
            "sequence"
        ]
    )

    source_dev_sequences = set(
        source_dev[
            "sequence"
        ]
    )

    source_test_sequences = set(
        source_test[
            "sequence"
        ]
    )


    source_label_map = (
        source_all
        .set_index(
            "sequence"
        )[
            "label"
        ]
        .to_dict()
    )


    for target_dataset in DATASETS:

        if (
            target_dataset
            == source_dataset
        ):
            continue


        pair_id = (
            f"{source_dataset}"
            f"__TO__"
            f"{target_dataset}"
        )

        pair_dir = (
            CROSS_DATASET_DIR
            / pair_id
        )

        pair_dir.mkdir(
            parents=True,
            exist_ok=True,
        )


        # ----------------------------------------------------
        # Target TEST split only
        # ----------------------------------------------------
        target_test_raw = (
            benchmark_qc_df[
                (
                    benchmark_qc_df[
                        "dataset"
                    ] == target_dataset
                )
                &
                (
                    benchmark_qc_df[
                        "split"
                    ] == "test"
                )
            ]
            .copy()
            .reset_index(drop=True)
        )

        assert len(target_test_raw) > 0

        assert target_test_raw[
            "sequence"
        ].is_unique


        # ----------------------------------------------------
        # Identify overlap with source DEV
        # ----------------------------------------------------
        dev_overlap_mask = (
            target_test_raw[
                "sequence"
            ].isin(
                source_dev_sequences
            )
        )


        # ----------------------------------------------------
        # Identify overlap with ENTIRE source
        # ----------------------------------------------------
        all_source_overlap_mask = (
            target_test_raw[
                "sequence"
            ].isin(
                source_all_sequences
            )
        )


        # ----------------------------------------------------
        # Source-test-only overlap
        #
        # Useful to report separately.
        # These are ALSO REMOVED in final protocol.
        # ----------------------------------------------------
        source_test_only_mask = (
            all_source_overlap_mask
            &
            ~dev_overlap_mask
        )


        # ----------------------------------------------------
        # Removed records = overlap anywhere in source
        # ----------------------------------------------------
        overlap_removed_df = (
            target_test_raw[
                all_source_overlap_mask
            ]
            .copy()
            .reset_index(drop=True)
        )


        # ----------------------------------------------------
        # Final decontaminated external test
        # ----------------------------------------------------
        target_test_clean = (
            target_test_raw[
                ~all_source_overlap_mask
            ]
            .copy()
            .reset_index(drop=True)
        )


        # ----------------------------------------------------
        # Annotate removed records
        # ----------------------------------------------------
        if len(overlap_removed_df) > 0:

            overlap_removed_df[
                "source_label"
            ] = (
                overlap_removed_df[
                    "sequence"
                ]
                .map(
                    source_label_map
                )
                .astype(int)
            )

            overlap_removed_df[
                "target_label"
            ] = (
                overlap_removed_df[
                    "label"
                ]
                .astype(int)
            )

            overlap_removed_df[
                "label_conflict"
            ] = (
                overlap_removed_df[
                    "source_label"
                ]
                !=
                overlap_removed_df[
                    "target_label"
                ]
            )

            overlap_removed_df[
                "overlap_source_partition"
            ] = (
                overlap_removed_df[
                    "sequence"
                ]
                .apply(
                    lambda seq:
                        (
                            "source_train_or_validation"
                            if seq
                            in source_dev_sequences
                            else "source_test_only"
                        )
                )
            )

        else:

            overlap_removed_df[
                "source_label"
            ] = pd.Series(
                dtype="int64"
            )

            overlap_removed_df[
                "target_label"
            ] = pd.Series(
                dtype="int64"
            )

            overlap_removed_df[
                "label_conflict"
            ] = pd.Series(
                dtype="bool"
            )

            overlap_removed_df[
                "overlap_source_partition"
            ] = pd.Series(
                dtype="object"
            )


        # ----------------------------------------------------
        # Count overlap categories
        # ----------------------------------------------------
        dev_overlap_n = int(
            dev_overlap_mask.sum()
        )

        source_test_only_overlap_n = int(
            source_test_only_mask.sum()
        )

        total_overlap_n = int(
            all_source_overlap_mask.sum()
        )

        assert (
            total_overlap_n
            ==
            dev_overlap_n
            +
            source_test_only_overlap_n
        )


        # ----------------------------------------------------
        # Label conflict counts
        # ----------------------------------------------------
        total_conflicts = (
            int(
                overlap_removed_df[
                    "label_conflict"
                ].sum()
            )
            if len(
                overlap_removed_df
            ) > 0
            else 0
        )

        dev_conflicts = (
            int(
                (
                    overlap_removed_df[
                        "label_conflict"
                    ]
                    &
                    (
                        overlap_removed_df[
                            "overlap_source_partition"
                        ]
                        ==
                        "source_train_or_validation"
                    )
                ).sum()
            )
            if len(
                overlap_removed_df
            ) > 0
            else 0
        )

        test_only_conflicts = (
            total_conflicts
            -
            dev_conflicts
        )


        # ----------------------------------------------------
        # HARD decontamination assertion:
        # zero exact overlap with ENTIRE source
        # ----------------------------------------------------
        residual_source_overlap = (
            set(
                target_test_clean[
                    "sequence"
                ]
            )
            .intersection(
                source_all_sequences
            )
        )

        assert len(
            residual_source_overlap
        ) == 0, (
            "Residual source-target duplicate "
            f"in {pair_id}"
        )


        # ----------------------------------------------------
        # Both target classes must remain
        # ----------------------------------------------------
        assert set(
            target_test_clean[
                "label"
            ].unique()
        ) == {0, 1}, (
            f"{pair_id}: class lost "
            "after decontamination."
        )

        assert target_test_clean[
            "sequence"
        ].is_unique


        # ----------------------------------------------------
        # Save target before decontamination
        # ----------------------------------------------------
        target_raw_path = (
            pair_dir
            / "target_test_before_overlap_removal.csv"
        )

        target_test_raw[
            EXPERIMENT_COLUMNS
        ].to_csv(
            target_raw_path,
            index=False,
        )


        # ----------------------------------------------------
        # Save exact duplicates removed
        # ----------------------------------------------------
        removed_path = (
            pair_dir
            / "target_test_exact_overlaps_removed.csv"
        )

        overlap_removed_df.to_csv(
            removed_path,
            index=False,
        )


        # ----------------------------------------------------
        # Save final target test
        # ----------------------------------------------------
        clean_path = (
            pair_dir
            / "target_test_decontaminated.csv"
        )

        target_test_clean[
            EXPERIMENT_COLUMNS
        ].to_csv(
            clean_path,
            index=False,
        )


        # ----------------------------------------------------
        # Basic counts
        # ----------------------------------------------------
        raw_n = int(
            len(target_test_raw)
        )

        clean_n = int(
            len(target_test_clean)
        )

        assert (
            raw_n
            ==
            total_overlap_n
            +
            clean_n
        )


        clean_amp = int(
            (
                target_test_clean[
                    "label"
                ] == 1
            ).sum()
        )

        clean_nonamp = int(
            (
                target_test_clean[
                    "label"
                ] == 0
            ).sum()
        )


        # ----------------------------------------------------
        # Pair manifest
        # ----------------------------------------------------
        pair_manifest = {

            "schema_version":
                "2.0",

            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "pair_id":
                pair_id,

            "source_dataset":
                source_dataset,

            "target_dataset":
                target_dataset,

            "model_seeds":
                MODEL_SEEDS,

            "source": {

                "train_n":
                    int(
                        len(source_train)
                    ),

                "validation_n":
                    int(
                        len(source_validation)
                    ),

                "test_n":
                    int(
                        len(source_test)
                    ),

                "development_n":
                    int(
                        len(source_dev)
                    ),

                "all_n":
                    int(
                        len(source_all)
                    ),

                "model_fit":
                    "train_only",

                "model_selection":
                    "validation_only",

                "test_used_for_model":
                    False,

                "test_used_for_decontamination":
                    True,
            },

            "target": {

                "evaluation_split":
                    "test",

                "raw_test_n":
                    raw_n,

                "dev_overlap_removed":
                    dev_overlap_n,

                "source_test_only_overlap_removed":
                    source_test_only_overlap_n,

                "total_exact_overlap_removed":
                    total_overlap_n,

                "label_conflicts_removed":
                    total_conflicts,

                "clean_test_n":
                    clean_n,

                "AMP_clean":
                    clean_amp,

                "non_AMP_clean":
                    clean_nonamp,
            },

            "decontamination": {

                "reference_scope":
                    "entire_source_dataset",

                "identity_threshold":
                    "exact_100_percent",

                "target_scope":
                    "target_test_only",

                "residual_exact_source_overlap":
                    0,
            },

            "files": {

                "target_before":
                    str(
                        target_raw_path
                    ),

                "target_before_sha256":
                    sha256_file(
                        target_raw_path
                    ),

                "removed":
                    str(
                        removed_path
                    ),

                "removed_sha256":
                    sha256_file(
                        removed_path
                    ),

                "target_clean":
                    str(
                        clean_path
                    ),

                "target_clean_sha256":
                    sha256_file(
                        clean_path
                    ),
            },
        }


        pair_manifest_path = (
            pair_dir
            / "pair_manifest.json"
        )

        with open(
            pair_manifest_path,
            "w",
            encoding="utf-8",
        ) as f:

            json.dump(
                pair_manifest,
                f,
                indent=2,
                ensure_ascii=False,
            )


        # ----------------------------------------------------
        # Registry
        # ----------------------------------------------------
        cross_pair_registry[
            pair_id
        ] = {

            "source":
                source_dataset,

            "target":
                target_dataset,

            "clean_target_path":
                str(
                    clean_path
                ),

            "pair_manifest":
                str(
                    pair_manifest_path
                ),
        }


        # ----------------------------------------------------
        # Summary
        # ----------------------------------------------------
        cross_summary_rows.append({

            "source_dataset":
                source_dataset,

            "target_dataset":
                target_dataset,

            "source_train_n":
                int(
                    len(source_train)
                ),

            "source_validation_n":
                int(
                    len(
                        source_validation
                    )
                ),

            "source_test_n":
                int(
                    len(source_test)
                ),

            "source_all_n":
                int(
                    len(source_all)
                ),

            "target_test_raw_n":
                raw_n,

            "dev_overlap_removed":
                dev_overlap_n,

            "source_test_only_overlap_removed":
                source_test_only_overlap_n,

            "total_exact_overlap_removed":
                total_overlap_n,

            "label_conflicts_removed":
                total_conflicts,

            "dev_label_conflicts":
                dev_conflicts,

            "source_test_only_label_conflicts":
                test_only_conflicts,

            "target_test_clean_n":
                clean_n,

            "target_AMP_clean":
                clean_amp,

            "target_nonAMP_clean":
                clean_nonamp,

            "removed_pct":
                (
                    100.0
                    * total_overlap_n
                    / raw_n
                ),

            "residual_entire_source_overlap":
                int(
                    len(
                        residual_source_overlap
                    )
                ),
        })


# ------------------------------------------------------------
# 11. Build final cross-dataset summary
# ------------------------------------------------------------
cross_summary_df = pd.DataFrame(
    cross_summary_rows
)

assert len(
    cross_summary_df
) == 12

assert (
    cross_summary_df[
        "residual_entire_source_overlap"
    ] == 0
).all()


# ------------------------------------------------------------
# 12. Save summaries
# ------------------------------------------------------------
WITHIN_SUMMARY_PATH = (
    AUDIT_DIR
    / "protocol1_fixed_split_summary.csv"
)

CROSS_SUMMARY_PATH = (
    AUDIT_DIR
    / "protocol2_strict_decontamination_summary.csv"
)


within_summary_df.to_csv(
    WITHIN_SUMMARY_PATH,
    index=False,
)

cross_summary_df.to_csv(
    CROSS_SUMMARY_PATH,
    index=False,
)


# ------------------------------------------------------------
# 13. Final global experiment manifest
# ------------------------------------------------------------
EXPERIMENT_SPLIT_MANIFEST_PATH = (
    MANIFEST_DIR
    / "experiment_split_manifest.json"
)


experiment_manifest = {

    "schema_version":
        "2.0",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "datasets":
        DATASETS,

    "model_seeds":
        MODEL_SEEDS,

    "model_seed_policy":
        "consecutive_100_to_109",

    "seed_tuning":
        False,

    "data_resplitting":
        False,

    "experiment_1": {

        "name":
            "within_dataset",

        "model_fit":
            "train",

        "model_selection":
            "validation",

        "final_evaluation":
            "test",

        "fixed_splits":
            True,

        "n_datasets":
            4,
    },

    "experiment_2": {

        "name":
            "cross_dataset_transfer",

        "source_model_fit":
            "train_only",

        "source_model_selection":
            "validation_only",

        "source_test_used_for_model":
            False,

        "source_test_used_for_decontamination":
            True,

        "target_evaluation":
            "test_only",

        "target_retraining":
            False,

        "target_finetuning":
            False,

        "target_threshold_tuning":
            False,

        "decontamination_reference":
            "entire_source_dataset",

        "decontamination_target":
            "target_test",

        "overlap_definition":
            "exact_normalized_sequence_identity",

        "residual_overlap_required":
            0,

        "n_directional_pairs":
            12,
    },

    "within_dataset_files":
        within_registry,

    "cross_dataset_pairs":
        cross_pair_registry,
}


with open(
    EXPERIMENT_SPLIT_MANIFEST_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        experiment_manifest,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 14. Final hard assertions
# ------------------------------------------------------------
assert (
    EXPERIMENT_SPLIT_MANIFEST_PATH.exists()
)

assert (
    WITHIN_SUMMARY_PATH.exists()
)

assert (
    CROSS_SUMMARY_PATH.exists()
)

assert len(
    cross_pair_registry
) == 12

assert MODEL_SEEDS == [
    100,
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    108,
    109,
]


# ------------------------------------------------------------
# 15. Report
# ------------------------------------------------------------
print("=" * 124)

print(
    "CELL 7 PASS - FINAL EXPERIMENT SPLITS LOCKED "
    "WITH STRICT CROSS-DATASET DECONTAMINATION"
)

print("=" * 124)

print(
    f"MODEL SEEDS             : {MODEL_SEEDS}"
)

print(
    "DATA RESPLITTING        : FALSE"
)

print(
    "SOURCE TEST MODEL USAGE : FALSE"
)

print(
    "SOURCE TEST QC USAGE    : SEQUENCE IDENTITY ONLY"
)

print(
    "TARGET RETRAINING       : FALSE"
)

print(
    "TARGET FINE-TUNING      : FALSE"
)

print(
    "TARGET THRESHOLD TUNING : FALSE"
)

print("-" * 124)

print(
    "EXPERIMENT 1 - FIXED WITHIN-DATASET SPLITS"
)

print(
    within_summary_df[
        [
            "dataset",
            "split",
            "n",
            "AMP",
            "non_AMP",
        ]
    ].to_string(
        index=False
    )
)

print("-" * 124)

print(
    "EXPERIMENT 2 - STRICT SOURCE-DATASET "
    "DECONTAMINATION OF TARGET TEST"
)

print(
    cross_summary_df[
        [
            "source_dataset",
            "target_dataset",
            "source_all_n",
            "target_test_raw_n",
            "dev_overlap_removed",
            "source_test_only_overlap_removed",
            "total_exact_overlap_removed",
            "label_conflicts_removed",
            "target_test_clean_n",
            "target_AMP_clean",
            "target_nonAMP_clean",
            "removed_pct",
            "residual_entire_source_overlap",
        ]
    ].to_string(
        index=False,
        float_format=lambda x:
            f"{x:.4f}",
    )
)

print("-" * 124)

print(
    "CROSS-DATASET DECONTAMINATION REFERENCE "
    "= ENTIRE SOURCE DATASET"
)

print(
    "MODEL TRAINING REFERENCE "
    "= SOURCE TRAIN ONLY"
)

print(
    "MODEL SELECTION REFERENCE "
    "= SOURCE VALIDATION ONLY"
)

print(
    "EXTERNAL EVALUATION "
    "= TARGET TEST ONLY"
)

print(
    "RESIDUAL EXACT SOURCE<->TARGET OVERLAP "
    "= 0 FOR ALL 12 PAIRS"
)

print("-" * 124)

print(
    f"Within summary : "
    f"{WITHIN_SUMMARY_PATH}"
)

print(
    f"Cross summary  : "
    f"{CROSS_SUMMARY_PATH}"
)

print(
    f"Manifest       : "
    f"{EXPERIMENT_SPLIT_MANIFEST_PATH}"
)

print("=" * 124)

============================================================================================================================
CELL 7 PASS - FINAL EXPERIMENT SPLITS LOCKED WITH STRICT CROSS-DATASET DECONTAMINATION
============================================================================================================================
MODEL SEEDS             : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
DATA RESPLITTING        : FALSE
SOURCE TEST MODEL USAGE : FALSE
SOURCE TEST QC USAGE    : SEQUENCE IDENTITY ONLY
TARGET RETRAINING       : FALSE
TARGET FINE-TUNING      : FALSE
TARGET THRESHOLD TUNING : FALSE
----------------------------------------------------------------------------------------------------------------------------
EXPERIMENT 1 - FIXED WITHIN-DATASET SPLITS
             dataset      split    n  AMP  non_AMP
GenPept_Curated_2025      train 7700 3850     3850
GenPept_Curated_2025 validation  990  495      495
GenPept_Curated_2025       test 2310 1155     1155
External_Benchmark_1      train 5435 2838     2597
External_Benchmark_1 validation 1176  875      301
External_Benchmark_1       test 1545  889      656
External_Benchmark_2      train 1424  712      712
External_Benchmark_2 validation  708  354      354
External_Benchmark_2       test 1424  712      712
External_Benchmark_3      train 9683 4734     4949
External_Benchmark_3 validation 2082 1020     1062
External_Benchmark_3       test 2070 1010     1060
----------------------------------------------------------------------------------------------------------------------------
EXPERIMENT 2 - STRICT SOURCE-DATASET DECONTAMINATION OF TARGET TEST
      source_dataset       target_dataset  source_all_n  target_test_raw_n  dev_overlap_removed  source_test_only_overlap_removed  total_exact_overlap_removed  label_conflicts_removed  target_test_clean_n  target_AMP_clean  target_nonAMP_clean  removed_pct  residual_entire_source_overlap
GenPept_Curated_2025 External_Benchmark_1         11000               1545                    8                                 7                           15                        2                 1530               874                  656       0.9709                               0
GenPept_Curated_2025 External_Benchmark_2         11000               1424                   10                                 5                           15                        1                 1409               697                  712       1.0534                               0
GenPept_Curated_2025 External_Benchmark_3         11000               2070                    9                                 0                            9                        1                 2061              1001                 1060       0.4348                               0
External_Benchmark_1 GenPept_Curated_2025          8156               2310                   13                                 7                           20                        4                 2290              1137                 1153       0.8658                               0
External_Benchmark_1 External_Benchmark_2          8156               1424                  580                               125                          705                        0                  719                 8                  711      49.5084                               0
External_Benchmark_1 External_Benchmark_3          8156               2070                  129                                36                          165                        0                 1905               845                 1060       7.9710                               0
External_Benchmark_2 GenPept_Curated_2025          3556               2310                    0                                 5                            5                        0                 2305              1150                 1155       0.2165                               0
External_Benchmark_2 External_Benchmark_1          3556               1545                  222                               125                          347                        0                 1198               542                  656      22.4595                               0
External_Benchmark_2 External_Benchmark_3          3556               2070                   51                                46                           97                        0                 1973               913                 1060       4.6860                               0
External_Benchmark_3 GenPept_Curated_2025         13835               2310                    9                                 0                            9                        1                 2301              1147                 1154       0.3896                               0
External_Benchmark_3 External_Benchmark_1         13835               1545                  187                                36                          223                        0                 1322               666                  656      14.4337                               0
External_Benchmark_3 External_Benchmark_2         13835               1424                  195                                46                          241                        0                 1183               471                  712      16.9242                               0
----------------------------------------------------------------------------------------------------------------------------
CROSS-DATASET DECONTAMINATION REFERENCE = ENTIRE SOURCE DATASET
MODEL TRAINING REFERENCE = SOURCE TRAIN ONLY
MODEL SELECTION REFERENCE = SOURCE VALIDATION ONLY
EXTERNAL EVALUATION = TARGET TEST ONLY
RESIDUAL EXACT SOURCE<->TARGET OVERLAP = 0 FOR ALL 12 PAIRS
----------------------------------------------------------------------------------------------------------------------------
Within summary : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/protocol1_fixed_split_summary.csv
Cross summary  : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/protocol2_strict_decontamination_summary.csv
Manifest       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/experiment_split_manifest.json
============================================================================================================================

In [17]:
# ============================================================
# CELL 8 - AMPlify REPLACEMENT CANDIDATE AUDIT
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import pandas as pd


# ------------------------------------------------------------
# 1. Validate notebook state
# ------------------------------------------------------------
REQUIRED_GLOBALS = [
    "PROJECT_ROOT",
    "AUDIT_DIR",
    "MANIFEST_DIR",
    "SPLIT_DIR",
]

for name in REQUIRED_GLOBALS:
    assert name in globals(), (
        f"{name} missing. Run CELLS 1-7 first."
    )


# ------------------------------------------------------------
# 2. Lock AMPlify folder
# ------------------------------------------------------------
AMPLIFY_DIR = (
    PROJECT_ROOT
    / "AMPlify"
)

assert AMPLIFY_DIR.is_dir(), (
    "AMPlify directory not found:\n"
    f"{AMPLIFY_DIR}"
)


# ------------------------------------------------------------
# 3. Lock exact four source files
# ------------------------------------------------------------
AMPLIFY_FILES = [

    {
        "path":
            AMPLIFY_DIR
            / "AMPlify_AMP_train_common.fa",

        "split":
            "train",

        "label":
            1,

        "class_name":
            "AMP",
    },

    {
        "path":
            AMPLIFY_DIR
            / "AMPlify_non_AMP_train_balanced.fa",

        "split":
            "train",

        "label":
            0,

        "class_name":
            "non_AMP",
    },

    {
        "path":
            AMPLIFY_DIR
            / "AMPlify_AMP_test_common.fa",

        "split":
            "test",

        "label":
            1,

        "class_name":
            "AMP",
    },

    {
        "path":
            AMPLIFY_DIR
            / "AMPlify_non_AMP_test_balanced.fa",

        "split":
            "test",

        "label":
            0,

        "class_name":
            "non_AMP",
    },
]


assert len(AMPLIFY_FILES) == 4

for item in AMPLIFY_FILES:

    assert item["path"].is_file(), (
        "Required AMPlify file not found:\n"
        f"{item['path']}"
    )


# ------------------------------------------------------------
# 4. Local FASTA parser
# ------------------------------------------------------------
def parse_fasta_local(path):

    records = []

    header = None
    sequence_parts = []

    with open(
        path,
        "r",
        encoding="utf-8",
        errors="replace",
    ) as f:

        for raw_line in f:

            line = raw_line.strip()

            if not line:
                continue

            if line.startswith(">"):

                if header is not None:

                    records.append({
                        "header":
                            header,

                        "sequence":
                            "".join(
                                sequence_parts
                            ),
                    })

                header = (
                    line[1:]
                    .strip()
                )

                sequence_parts = []

            else:

                assert header is not None, (
                    "Sequence encountered "
                    "before FASTA header:\n"
                    f"{path}"
                )

                sequence_parts.append(
                    line
                )

    if header is not None:

        records.append({
            "header":
                header,

            "sequence":
                "".join(
                    sequence_parts
                ),
        })

    assert len(records) > 0, (
        f"No FASTA records found:\n{path}"
    )

    return records


# ------------------------------------------------------------
# 5. Sequence normalization
# ------------------------------------------------------------
AA20_LOCAL = set(
    "ACDEFGHIKLMNPQRSTVWY"
)

MIN_LEN_LOCAL = 10
MAX_LEN_LOCAL = 200


def normalize_sequence_local(seq):

    return "".join(
        str(seq).split()
    ).upper()


# ------------------------------------------------------------
# 6. SHA256 helper
# ------------------------------------------------------------
def sha256_file_local(path):

    h = hashlib.sha256()

    with open(path, "rb") as f:

        for chunk in iter(
            lambda:
                f.read(
                    1024 * 1024
                ),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


# ------------------------------------------------------------
# 7. Parse four AMPlify files
# ------------------------------------------------------------
amplify_rows = []

file_summary_rows = []


for item in AMPLIFY_FILES:

    records = parse_fasta_local(
        item["path"]
    )

    file_summary_rows.append({

        "file":
            item["path"].name,

        "split":
            item["split"],

        "label":
            item["label"],

        "class_name":
            item["class_name"],

        "n_records":
            len(records),

        "sha256":
            sha256_file_local(
                item["path"]
            ),
    })


    for index, record in enumerate(
        records,
        start=1,
    ):

        sequence = (
            normalize_sequence_local(
                record["sequence"]
            )
        )

        amplify_rows.append({

            "dataset":
                "AMPlify_balanced",

            "sample_id":
                (
                    f"AMPlify_"
                    f"{item['split']}_"
                    f"{item['label']}_"
                    f"{index:05d}"
                ),

            "original_header":
                record["header"],

            "sequence":
                sequence,

            "label":
                int(
                    item["label"]
                ),

            "split":
                item["split"],

            "source_file":
                str(
                    item["path"]
                ),
        })


amplify_raw_df = pd.DataFrame(
    amplify_rows
)

amplify_file_summary_df = (
    pd.DataFrame(
        file_summary_rows
    )
)


# ------------------------------------------------------------
# 8. Verify RAW AMPlify counts
# ------------------------------------------------------------
raw_count_table = (
    amplify_raw_df
    .groupby(
        [
            "split",
            "label",
        ]
    )
    .size()
    .to_dict()
)


EXPECTED_RAW_AMPLIFY_COUNTS = {
    ("train", 1): 3338,
    ("train", 0): 3338,
    ("test", 1): 835,
    ("test", 0): 835,
}


assert (
    raw_count_table
    ==
    EXPECTED_RAW_AMPLIFY_COUNTS
), (
    "AMPlify raw counts do not match "
    "the expected balanced release.\n"
    f"Expected: {EXPECTED_RAW_AMPLIFY_COUNTS}\n"
    f"Observed: {raw_count_table}"
)


assert len(
    amplify_raw_df
) == 8346


# ------------------------------------------------------------
# 9. Apply SAME harmonized QC contract
#    used in CELL 6
#
# 20 canonical AA
# 10 <= length <= 200
#
# NO residue replacement
# NO balancing
# ------------------------------------------------------------
amplify_raw_df[
    "length"
] = (
    amplify_raw_df[
        "sequence"
    ].str.len()
)


amplify_raw_df[
    "invalid_residues"
] = (
    amplify_raw_df[
        "sequence"
    ].apply(
        lambda seq:
            "".join(
                sorted(
                    set(seq)
                    - AA20_LOCAL
                )
            )
    )
)


amplify_raw_df[
    "valid_aa20"
] = (
    amplify_raw_df[
        "invalid_residues"
    ] == ""
)


amplify_raw_df[
    "valid_length"
] = (
    amplify_raw_df[
        "length"
    ].between(
        MIN_LEN_LOCAL,
        MAX_LEN_LOCAL,
        inclusive="both",
    )
)


def amplify_qc_reason(row):

    reasons = []

    if not row["valid_aa20"]:
        reasons.append(
            "noncanonical_residue"
        )

    if row["length"] < 10:
        reasons.append(
            "length_below_10"
        )

    if row["length"] > 200:
        reasons.append(
            "length_above_200"
        )

    if len(reasons) == 0:
        return "KEEP"

    return ";".join(reasons)


amplify_raw_df[
    "qc_decision"
] = (
    amplify_raw_df.apply(
        amplify_qc_reason,
        axis=1,
    )
)


amplify_raw_df[
    "qc_keep"
] = (
    amplify_raw_df[
        "qc_decision"
    ] == "KEEP"
)


amplify_removed_df = (
    amplify_raw_df[
        ~amplify_raw_df[
            "qc_keep"
        ]
    ]
    .copy()
    .reset_index(drop=True)
)


amplify_clean_df = (
    amplify_raw_df[
        amplify_raw_df[
            "qc_keep"
        ]
    ]
    .copy()
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 10. Clean cohort integrity
# ------------------------------------------------------------
assert amplify_clean_df[
    "valid_aa20"
].all()

assert amplify_clean_df[
    "valid_length"
].all()

assert amplify_clean_df[
    "length"
].between(
    10,
    200,
    inclusive="both",
).all()


# ------------------------------------------------------------
# 11. AMPlify clean split/class summary
# ------------------------------------------------------------
amplify_clean_summary_df = (
    amplify_clean_df
    .groupby(
        [
            "split",
            "label",
        ],
        as_index=False,
    )
    .agg(
        n=(
            "sample_id",
            "count",
        ),

        min_len=(
            "length",
            "min",
        ),

        median_len=(
            "length",
            "median",
        ),

        max_len=(
            "length",
            "max",
        ),
    )
)


# ------------------------------------------------------------
# 12. QC removal summary
# ------------------------------------------------------------
if len(
    amplify_removed_df
) > 0:

    amplify_removal_summary_df = (
        amplify_removed_df
        .groupby(
            [
                "split",
                "label",
                "qc_decision",
            ],
            as_index=False,
        )
        .agg(
            n_removed=(
                "sample_id",
                "count",
            )
        )
    )

else:

    amplify_removal_summary_df = (
        pd.DataFrame(
            columns=[
                "split",
                "label",
                "qc_decision",
                "n_removed",
            ]
        )
    )


# ------------------------------------------------------------
# 13. Internal duplicate / leakage audit
# ------------------------------------------------------------
n_raw = len(
    amplify_clean_df
)

n_unique = (
    amplify_clean_df[
        "sequence"
    ].nunique()
)

duplicate_rows = (
    n_raw - n_unique
)


sequence_label_counts = (
    amplify_clean_df
    .groupby(
        "sequence"
    )[
        "label"
    ]
    .nunique()
)


label_conflict_sequences = int(
    (
        sequence_label_counts > 1
    ).sum()
)


amplify_train_sequences = set(
    amplify_clean_df.loc[
        amplify_clean_df[
            "split"
        ] == "train",
        "sequence",
    ]
)


amplify_test_sequences = set(
    amplify_clean_df.loc[
        amplify_clean_df[
            "split"
        ] == "test",
        "sequence",
    ]
)


train_test_overlap = (
    amplify_train_sequences
    .intersection(
        amplify_test_sequences
    )
)


amplify_internal_audit = {

    "n_clean_rows":
        int(n_raw),

    "n_unique_sequences":
        int(n_unique),

    "duplicate_rows":
        int(duplicate_rows),

    "label_conflict_sequences":
        int(
            label_conflict_sequences
        ),

    "train_test_exact_overlap":
        int(
            len(
                train_test_overlap
            )
        ),
}


# ------------------------------------------------------------
# 14. Load existing harmonized benchmark FROM DISK
#
# External_Benchmark_2 is deliberately excluded.
# ------------------------------------------------------------
EXISTING_COHORT_PATH = (
    SPLIT_DIR
    / "benchmark4_harmonized_qc.csv"
)

assert EXISTING_COHORT_PATH.is_file(), (
    "CELL 6 harmonized cohort not found:\n"
    f"{EXISTING_COHORT_PATH}"
)


existing_df = pd.read_csv(
    EXISTING_COHORT_PATH,
    low_memory=False,
)


RETAINED_DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "External_Benchmark_3",
]


existing_retained_df = (
    existing_df[
        existing_df[
            "dataset"
        ].isin(
            RETAINED_DATASETS
        )
    ]
    .copy()
    .reset_index(drop=True)
)


assert set(
    existing_retained_df[
        "dataset"
    ].unique()
) == set(
    RETAINED_DATASETS
)


# ------------------------------------------------------------
# 15. Pairwise whole-dataset exact overlap:
#
# AMPlify versus each retained dataset
# ------------------------------------------------------------
pairwise_rows = []

amplify_all_sequences = set(
    amplify_clean_df[
        "sequence"
    ]
)


amplify_label_map = (
    amplify_clean_df
    .drop_duplicates(
        subset=[
            "sequence"
        ]
    )
    .set_index(
        "sequence"
    )[
        "label"
    ]
    .to_dict()
)


for dataset_name in RETAINED_DATASETS:

    other_df = (
        existing_retained_df[
            existing_retained_df[
                "dataset"
            ] == dataset_name
        ]
        .copy()
    )

    other_sequences = set(
        other_df[
            "sequence"
        ]
    )

    overlap = (
        amplify_all_sequences
        .intersection(
            other_sequences
        )
    )

    other_label_map = (
        other_df
        .set_index(
            "sequence"
        )[
            "label"
        ]
        .to_dict()
    )

    conflicts = int(
        sum(
            amplify_label_map[seq]
            != other_label_map[seq]
            for seq in overlap
        )
    )


    pairwise_rows.append({

        "dataset_a":
            "AMPlify_balanced",

        "dataset_b":
            dataset_name,

        "n_a":
            int(
                len(
                    amplify_all_sequences
                )
            ),

        "n_b":
            int(
                len(
                    other_sequences
                )
            ),

        "exact_overlap":
            int(
                len(overlap)
            ),

        "label_conflicts":
            conflicts,

        "pct_of_AMPlify":
            (
                100.0
                * len(overlap)
                / len(
                    amplify_all_sequences
                )
            ),

        "pct_of_other":
            (
                100.0
                * len(overlap)
                / len(
                    other_sequences
                )
            ),
    })


amplify_pairwise_overlap_df = (
    pd.DataFrame(
        pairwise_rows
    )
)


# ------------------------------------------------------------
# 16. Strict directional decontamination audit
#
# Same rule as FINAL CELL 7:
#
# target TEST is cleaned against
# ENTIRE SOURCE dataset.
#
# Six directions:
#
# Existing -> AMPlify
# AMPlify -> Existing
# ------------------------------------------------------------
directional_rows = []


def summarize_clean_target(
    source_name,
    target_name,
    source_sequences,
    target_test_df,
):

    overlap_mask = (
        target_test_df[
            "sequence"
        ].isin(
            source_sequences
        )
    )

    removed_df = (
        target_test_df[
            overlap_mask
        ]
    )

    clean_df = (
        target_test_df[
            ~overlap_mask
        ]
    )

    raw_n = int(
        len(
            target_test_df
        )
    )

    removed_n = int(
        len(
            removed_df
        )
    )

    clean_n = int(
        len(
            clean_df
        )
    )

    amp_n = int(
        (
            clean_df[
                "label"
            ] == 1
        ).sum()
    )

    nonamp_n = int(
        (
            clean_df[
                "label"
            ] == 0
        ).sum()
    )

    minority_n = min(
        amp_n,
        nonamp_n,
    )

    majority_n = max(
        amp_n,
        nonamp_n,
    )

    if minority_n > 0:

        class_ratio = (
            majority_n
            / minority_n
        )

    else:

        class_ratio = float(
            "inf"
        )


    residual_overlap = (
        set(
            clean_df[
                "sequence"
            ]
        )
        .intersection(
            source_sequences
        )
    )

    assert len(
        residual_overlap
    ) == 0


    return {

        "source_dataset":
            source_name,

        "target_dataset":
            target_name,

        "target_test_raw_n":
            raw_n,

        "exact_overlap_removed":
            removed_n,

        "target_test_clean_n":
            clean_n,

        "target_AMP_clean":
            amp_n,

        "target_nonAMP_clean":
            nonamp_n,

        "minority_class_n":
            minority_n,

        "majority_class_n":
            majority_n,

        "class_ratio_majority_to_minority":
            class_ratio,

        "removed_pct":
            (
                100.0
                * removed_n
                / raw_n
            ),

        # Flag only.
        # Does NOT alter target distribution.
        "severe_low_support_flag":
            bool(
                minority_n < 100
            ),

        "residual_exact_overlap":
            int(
                len(
                    residual_overlap
                )
            ),
    }


# ------------------------------------------------------------
# 17. AMPlify target TEST
# ------------------------------------------------------------
amplify_test_clean_df = (
    amplify_clean_df[
        amplify_clean_df[
            "split"
        ] == "test"
    ]
    .copy()
    .reset_index(drop=True)
)


assert set(
    amplify_test_clean_df[
        "label"
    ].unique()
) == {0, 1}


# ------------------------------------------------------------
# 18. Six directional comparisons
# ------------------------------------------------------------
for existing_name in RETAINED_DATASETS:

    existing_all = (
        existing_retained_df[
            existing_retained_df[
                "dataset"
            ] == existing_name
        ]
        .copy()
    )

    existing_all_sequences = set(
        existing_all[
            "sequence"
        ]
    )


    existing_test = (
        existing_all[
            existing_all[
                "split"
            ] == "test"
        ]
        .copy()
        .reset_index(drop=True)
    )


    # --------------------------------------------------------
    # Direction A:
    # Existing source -> AMPlify target test
    # --------------------------------------------------------
    directional_rows.append(
        summarize_clean_target(
            source_name=
                existing_name,

            target_name=
                "AMPlify_balanced",

            source_sequences=
                existing_all_sequences,

            target_test_df=
                amplify_test_clean_df,
        )
    )


    # --------------------------------------------------------
    # Direction B:
    # AMPlify source -> Existing target test
    # --------------------------------------------------------
    directional_rows.append(
        summarize_clean_target(
            source_name=
                "AMPlify_balanced",

            target_name=
                existing_name,

            source_sequences=
                amplify_all_sequences,

            target_test_df=
                existing_test,
        )
    )


amplify_directional_audit_df = (
    pd.DataFrame(
        directional_rows
    )
)


assert len(
    amplify_directional_audit_df
) == 6


assert (
    amplify_directional_audit_df[
        "residual_exact_overlap"
    ] == 0
).all()


# ------------------------------------------------------------
# 19. Candidate-level decision diagnostics
#
# IMPORTANT:
# These are FLAGS only.
# We do NOT automatically accept/reject AMPlify here.
# ------------------------------------------------------------
candidate_min_class_support = int(
    amplify_directional_audit_df[
        "minority_class_n"
    ].min()
)


candidate_max_class_ratio = float(
    amplify_directional_audit_df[
        "class_ratio_majority_to_minority"
    ].max()
)


candidate_max_removed_pct = float(
    amplify_directional_audit_df[
        "removed_pct"
    ].max()
)


candidate_low_support_pairs = int(
    amplify_directional_audit_df[
        "severe_low_support_flag"
    ].sum()
)


# ------------------------------------------------------------
# 20. Save AMPlify candidate data
#
# AUDIT only - not yet official benchmark split.
# ------------------------------------------------------------
AMPLIFY_RAW_AUDIT_PATH = (
    AUDIT_DIR
    / "amplify_candidate_raw.csv"
)

AMPLIFY_CLEAN_AUDIT_PATH = (
    AUDIT_DIR
    / "amplify_candidate_harmonized_qc.csv"
)

AMPLIFY_REMOVED_AUDIT_PATH = (
    AUDIT_DIR
    / "amplify_candidate_qc_removed.csv"
)

AMPLIFY_FILE_SUMMARY_PATH = (
    AUDIT_DIR
    / "amplify_candidate_file_summary.csv"
)

AMPLIFY_PAIRWISE_PATH = (
    AUDIT_DIR
    / "amplify_candidate_pairwise_overlap.csv"
)

AMPLIFY_DIRECTIONAL_PATH = (
    AUDIT_DIR
    / "amplify_candidate_directional_decontamination.csv"
)


amplify_raw_df.to_csv(
    AMPLIFY_RAW_AUDIT_PATH,
    index=False,
)

amplify_clean_df.to_csv(
    AMPLIFY_CLEAN_AUDIT_PATH,
    index=False,
)

amplify_removed_df.to_csv(
    AMPLIFY_REMOVED_AUDIT_PATH,
    index=False,
)

amplify_file_summary_df.to_csv(
    AMPLIFY_FILE_SUMMARY_PATH,
    index=False,
)

amplify_pairwise_overlap_df.to_csv(
    AMPLIFY_PAIRWISE_PATH,
    index=False,
)

amplify_directional_audit_df.to_csv(
    AMPLIFY_DIRECTIONAL_PATH,
    index=False,
)


# ------------------------------------------------------------
# 21. Save candidate manifest
# ------------------------------------------------------------
AMPLIFY_MANIFEST_PATH = (
    MANIFEST_DIR
    / "amplify_replacement_candidate_audit.json"
)


amplify_manifest = {

    "schema_version":
        "1.0",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "candidate":
        "AMPlify_balanced",

    "purpose":
        (
            "Evaluate AMPlify balanced "
            "as replacement for "
            "External_Benchmark_2"
        ),

    "benchmark_replacement_applied":
        False,

    "raw_n":
        int(
            len(
                amplify_raw_df
            )
        ),

    "clean_n":
        int(
            len(
                amplify_clean_df
            )
        ),

    "qc_removed_n":
        int(
            len(
                amplify_removed_df
            )
        ),

    "qc_policy": {

        "canonical_aa20_only":
            True,

        "minimum_length":
            10,

        "maximum_length":
            200,

        "residue_replacement":
            False,

        "class_balancing":
            False,
    },

    "internal_audit":
        amplify_internal_audit,

    "directional_overlap_audit": {

        "n_pairs":
            6,

        "decontamination_reference":
            "entire_source_dataset",

        "target_scope":
            "held_out_test_only",

        "minimum_class_support_after_decontamination":
            candidate_min_class_support,

        "maximum_class_ratio":
            candidate_max_class_ratio,

        "maximum_removed_pct":
            candidate_max_removed_pct,

        "pairs_with_minority_class_below_100":
            candidate_low_support_pairs,
    },
}


with open(
    AMPLIFY_MANIFEST_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        amplify_manifest,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 22. Final assertions
# ------------------------------------------------------------
assert (
    AMPLIFY_RAW_AUDIT_PATH.exists()
)

assert (
    AMPLIFY_CLEAN_AUDIT_PATH.exists()
)

assert (
    AMPLIFY_DIRECTIONAL_PATH.exists()
)

assert (
    AMPLIFY_MANIFEST_PATH.exists()
)

assert len(
    amplify_raw_df
) == 8346


# ------------------------------------------------------------
# 23. Report
# ------------------------------------------------------------
print("=" * 118)

print(
    "CELL 8 PASS - AMPlify REPLACEMENT "
    "CANDIDATE AUDIT COMPLETE"
)

print("=" * 118)

print(
    f"AMPlify directory : {AMPLIFY_DIR}"
)

print(
    "BENCHMARK REPLACEMENT APPLIED : FALSE"
)

print("-" * 118)

print(
    "SOURCE FILES"
)

print(
    amplify_file_summary_df[
        [
            "file",
            "split",
            "class_name",
            "n_records",
        ]
    ].to_string(
        index=False
    )
)

print("-" * 118)

print(
    "AMPlify AFTER COMMON QC "
    "(AA20, 10 <= L <= 200)"
)

print(
    amplify_clean_summary_df
    .to_string(
        index=False
    )
)

print("-" * 118)

print(
    "QC REMOVALS"
)

if len(
    amplify_removal_summary_df
) == 0:

    print(
        "No AMPlify records removed."
    )

else:

    print(
        amplify_removal_summary_df
        .to_string(
            index=False
        )
    )

print("-" * 118)

print(
    "INTERNAL AMPlify AUDIT"
)

for key, value in (
    amplify_internal_audit.items()
):

    print(
        f"{key:32s}: {value}"
    )

print("-" * 118)

print(
    "WHOLE-DATASET EXACT OVERLAP"
)

print(
    amplify_pairwise_overlap_df
    .to_string(
        index=False,
        float_format=lambda x:
            f"{x:.4f}",
    )
)

print("-" * 118)

print(
    "STRICT DIRECTIONAL TARGET-TEST "
    "DECONTAMINATION"
)

print(
    amplify_directional_audit_df[
        [
            "source_dataset",
            "target_dataset",
            "target_test_raw_n",
            "exact_overlap_removed",
            "target_test_clean_n",
            "target_AMP_clean",
            "target_nonAMP_clean",
            "minority_class_n",
            "class_ratio_majority_to_minority",
            "removed_pct",
            "severe_low_support_flag",
            "residual_exact_overlap",
        ]
    ].to_string(
        index=False,
        float_format=lambda x:
            f"{x:.4f}",
    )
)

print("-" * 118)

print(
    "CANDIDATE DIAGNOSTICS"
)

print(
    f"Minimum class support after decontamination : "
    f"{candidate_min_class_support}"
)

print(
    f"Maximum majority/minority ratio             : "
    f"{candidate_max_class_ratio:.4f}"
)

print(
    f"Maximum target records removed (%)          : "
    f"{candidate_max_removed_pct:.4f}"
)

print(
    f"Pairs with minority class < 100             : "
    f"{candidate_low_support_pairs}"
)

print("-" * 118)

print(
    "NO DATASET HAS BEEN REPLACED YET."
)

print(
    "NO TRAINING HAS BEEN PERFORMED."
)

print("-" * 118)

print(
    f"Candidate QC data : "
    f"{AMPLIFY_CLEAN_AUDIT_PATH}"
)

print(
    f"Overlap audit     : "
    f"{AMPLIFY_DIRECTIONAL_PATH}"
)

print(
    f"Manifest          : "
    f"{AMPLIFY_MANIFEST_PATH}"
)

print("=" * 118)

======================================================================================================================
CELL 8 PASS - AMPlify REPLACEMENT CANDIDATE AUDIT COMPLETE
======================================================================================================================
AMPlify directory : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/AMPlify
BENCHMARK REPLACEMENT APPLIED : FALSE
----------------------------------------------------------------------------------------------------------------------
SOURCE FILES
                             file split class_name  n_records
      AMPlify_AMP_train_common.fa train        AMP       3338
AMPlify_non_AMP_train_balanced.fa train    non_AMP       3338
       AMPlify_AMP_test_common.fa  test        AMP        835
 AMPlify_non_AMP_test_balanced.fa  test    non_AMP        835
----------------------------------------------------------------------------------------------------------------------
AMPlify AFTER COMMON QC (AA20, 10 <= L <= 200)
split  label    n  min_len  median_len  max_len
 test      0  806       10        28.0      161
 test      1  786       10        25.0      152
train      0 3228       10        28.0      183
train      1 3248       10        26.0      183
----------------------------------------------------------------------------------------------------------------------
QC REMOVALS
split  label     qc_decision  n_removed
 test      0 length_below_10         29
 test      1 length_below_10         49
train      0 length_below_10        110
train      1 length_below_10         90
----------------------------------------------------------------------------------------------------------------------
INTERNAL AMPlify AUDIT
n_clean_rows                    : 8068
n_unique_sequences              : 8068
duplicate_rows                  : 0
label_conflict_sequences        : 0
train_test_exact_overlap        : 0
----------------------------------------------------------------------------------------------------------------------
WHOLE-DATASET EXACT OVERLAP
       dataset_a            dataset_b  n_a   n_b  exact_overlap  label_conflicts  pct_of_AMPlify  pct_of_other
AMPlify_balanced GenPept_Curated_2025 8068 11000             84                7          1.0412        0.7636
AMPlify_balanced External_Benchmark_1 8068  8156           3045               43         37.7417       37.3345
AMPlify_balanced External_Benchmark_3 8068 13835           1039               14         12.8780        7.5099
----------------------------------------------------------------------------------------------------------------------
STRICT DIRECTIONAL TARGET-TEST DECONTAMINATION
      source_dataset       target_dataset  target_test_raw_n  exact_overlap_removed  target_test_clean_n  target_AMP_clean  target_nonAMP_clean  minority_class_n  class_ratio_majority_to_minority  removed_pct  severe_low_support_flag  residual_exact_overlap
GenPept_Curated_2025     AMPlify_balanced               1592                     10                 1582               784                  798               784                            1.0179       0.6281                    False                       0
    AMPlify_balanced GenPept_Curated_2025               2310                     15                 2295              1146                 1149              1146                            1.0026       0.6494                    False                       0
External_Benchmark_1     AMPlify_balanced               1592                    436                 1156               366                  790               366                            2.1585      27.3869                    False                       0
    AMPlify_balanced External_Benchmark_1               1545                    588                  957               309                  648               309                            2.0971      38.0583                    False                       0
External_Benchmark_3     AMPlify_balanced               1592                    195                 1397               593                  804               593                            1.3558      12.2487                    False                       0
    AMPlify_balanced External_Benchmark_3               2070                    160                 1910               850                 1060               850                            1.2471       7.7295                    False                       0
----------------------------------------------------------------------------------------------------------------------
CANDIDATE DIAGNOSTICS
Minimum class support after decontamination : 309
Maximum majority/minority ratio             : 2.1585
Maximum target records removed (%)          : 38.0583
Pairs with minority class < 100             : 0
----------------------------------------------------------------------------------------------------------------------
NO DATASET HAS BEEN REPLACED YET.
NO TRAINING HAS BEEN PERFORMED.
----------------------------------------------------------------------------------------------------------------------
Candidate QC data : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/amplify_candidate_harmonized_qc.csv
Overlap audit     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/amplify_candidate_directional_decontamination.csv
Manifest          : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/amplify_replacement_candidate_audit.json
======================================================================================================================

In [18]:
# ============================================================
# CELL 9 - FREEZE AMPlify TRAIN / VALIDATION / TEST
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import pandas as pd


# ------------------------------------------------------------
# 1. Validate notebook state
# ------------------------------------------------------------
REQUIRED_GLOBALS = [
    "AUDIT_DIR",
    "SPLIT_DIR",
    "MANIFEST_DIR",
    "SEEDS",
]

for name in REQUIRED_GLOBALS:
    assert name in globals(), (
        f"{name} missing. Run previous cells first."
    )


assert list(SEEDS) == list(range(100, 110)), (
    "Model seed lock changed unexpectedly."
)


# ------------------------------------------------------------
# 2. Load AMPlify candidate FROM DISK
#
# Do not depend on Cell 8 RAM state.
# ------------------------------------------------------------
AMPLIFY_CANDIDATE_PATH = (
    AUDIT_DIR
    / "amplify_candidate_harmonized_qc.csv"
)

assert AMPLIFY_CANDIDATE_PATH.is_file(), (
    "AMPlify candidate file not found:\n"
    f"{AMPLIFY_CANDIDATE_PATH}"
)


amplify_df = pd.read_csv(
    AMPLIFY_CANDIDATE_PATH,
    low_memory=False,
)


assert len(amplify_df) == 8068, (
    f"Unexpected AMPlify clean count: {len(amplify_df)}"
)

assert amplify_df["sequence"].is_unique

assert set(
    amplify_df["label"].unique()
) == {0, 1}

assert set(
    amplify_df["split"].unique()
) == {
    "train",
    "test",
}


# ------------------------------------------------------------
# 3. Separate original train and untouched test
# ------------------------------------------------------------
original_train_df = (
    amplify_df[
        amplify_df["split"] == "train"
    ]
    .copy()
    .reset_index(drop=True)
)

original_test_df = (
    amplify_df[
        amplify_df["split"] == "test"
    ]
    .copy()
    .reset_index(drop=True)
)


assert len(original_train_df) == 6476
assert len(original_test_df) == 1592

assert (
    len(
        set(original_train_df["sequence"])
        .intersection(
            set(original_test_df["sequence"])
        )
    )
    == 0
), (
    "Unexpected AMPlify train-test exact overlap."
)


# ------------------------------------------------------------
# 4. Lock validation-generation policy
#
# Original TRAIN only:
#     85% final training
#     15% validation
#
# Test is NEVER touched.
#
# Stratification:
#     label x fixed peptide-length interval
#
# Partition assignment:
#     deterministic SHA-256 ranking
#
# No model seed is used.
# ------------------------------------------------------------
VALIDATION_FRACTION = 0.15

AMPLIFY_PARTITION_VERSION = (
    "AMPlify_validation_v1"
)

AMPLIFY_PARTITION_SEED = 2026

HASH_SALT = (
    f"{AMPLIFY_PARTITION_VERSION}"
    f"|seed={AMPLIFY_PARTITION_SEED}"
)


assert AMPLIFY_PARTITION_SEED not in list(SEEDS)


# ------------------------------------------------------------
# 5. Fixed length bins
#
# Same biological length intervals used
# throughout the GenPept analysis.
# ------------------------------------------------------------
LENGTH_BINS = [
    9,
    50,
    100,
    150,
    200,
]

LENGTH_LABELS = [
    "10-50",
    "51-100",
    "101-150",
    "151-200",
]


assert original_train_df[
    "length"
].between(
    10,
    200,
    inclusive="both",
).all()


original_train_df[
    "length_bin"
] = pd.cut(
    original_train_df["length"],
    bins=LENGTH_BINS,
    labels=LENGTH_LABELS,
    include_lowest=True,
    right=True,
)


assert original_train_df[
    "length_bin"
].notna().all()


# ------------------------------------------------------------
# 6. Build fixed stratification key
# ------------------------------------------------------------
original_train_df[
    "stratum"
] = (
    original_train_df[
        "label"
    ].astype(str)
    + "|"
    + original_train_df[
        "length_bin"
    ].astype(str)
)


# ------------------------------------------------------------
# 7. Deterministic sequence hash
# ------------------------------------------------------------
def validation_rank_hash(sequence):

    payload = (
        HASH_SALT
        + "|"
        + str(sequence)
    )

    return hashlib.sha256(
        payload.encode("utf-8")
    ).hexdigest()


original_train_df[
    "partition_hash"
] = (
    original_train_df[
        "sequence"
    ].map(
        validation_rank_hash
    )
)


assert original_train_df[
    "partition_hash"
].is_unique


# ------------------------------------------------------------
# 8. Deterministically select validation
#    inside each label x length stratum
# ------------------------------------------------------------
validation_indices = []

stratum_summary_rows = []


for stratum, part in (
    original_train_df
    .groupby(
        "stratum",
        observed=True,
        sort=True,
    )
):

    part = (
        part
        .sort_values(
            [
                "partition_hash",
                "sample_id",
            ]
        )
    )

    n_total = len(part)

    assert n_total >= 2, (
        f"Stratum too small: {stratum} -> {n_total}"
    )

    n_validation = int(
        round(
            n_total
            * VALIDATION_FRACTION
        )
    )

    n_validation = max(
        1,
        n_validation,
    )

    n_validation = min(
        n_total - 1,
        n_validation,
    )

    selected_indices = (
        part
        .head(
            n_validation
        )
        .index
        .tolist()
    )

    validation_indices.extend(
        selected_indices
    )

    stratum_summary_rows.append({
        "stratum":
            stratum,

        "n_original_train":
            int(n_total),

        "n_final_train":
            int(
                n_total
                - n_validation
            ),

        "n_validation":
            int(n_validation),

        "validation_fraction":
            (
                n_validation
                / n_total
            ),
    })


stratum_summary_df = pd.DataFrame(
    stratum_summary_rows
)


# ------------------------------------------------------------
# 9. Materialize final train and validation
# ------------------------------------------------------------
validation_mask = (
    original_train_df.index.isin(
        validation_indices
    )
)


amplify_validation_df = (
    original_train_df[
        validation_mask
    ]
    .copy()
    .reset_index(drop=True)
)


amplify_train_df = (
    original_train_df[
        ~validation_mask
    ]
    .copy()
    .reset_index(drop=True)
)


amplify_test_df = (
    original_test_df
    .copy()
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 10. Assign final split names
# ------------------------------------------------------------
amplify_train_df[
    "split"
] = "train"

amplify_validation_df[
    "split"
] = "validation"

amplify_test_df[
    "split"
] = "test"


# ------------------------------------------------------------
# 11. Critical membership checks
# ------------------------------------------------------------
train_sequences = set(
    amplify_train_df[
        "sequence"
    ]
)

validation_sequences = set(
    amplify_validation_df[
        "sequence"
    ]
)

test_sequences = set(
    amplify_test_df[
        "sequence"
    ]
)


assert train_sequences.isdisjoint(
    validation_sequences
)

assert train_sequences.isdisjoint(
    test_sequences
)

assert validation_sequences.isdisjoint(
    test_sequences
)


# Final train + validation must equal
# original AMPlify training exactly.
assert (
    train_sequences
    .union(
        validation_sequences
    )
    ==
    set(
        original_train_df[
            "sequence"
        ]
    )
)


# Final test must be byte-membership equivalent
# to original clean AMPlify test.
assert (
    test_sequences
    ==
    set(
        original_test_df[
            "sequence"
        ]
    )
)


# ------------------------------------------------------------
# 12. Combine final AMPlify cohort
# ------------------------------------------------------------
amplify_final_df = pd.concat(
    [
        amplify_train_df,
        amplify_validation_df,
        amplify_test_df,
    ],
    ignore_index=True,
)


assert len(
    amplify_final_df
) == 8068

assert amplify_final_df[
    "sequence"
].is_unique


# ------------------------------------------------------------
# 13. Common downstream fields
# ------------------------------------------------------------
amplify_final_df[
    "dataset"
] = "AMPlify_balanced"


amplify_final_df[
    "length_qc"
] = (
    amplify_final_df[
        "sequence"
    ].str.len()
)


amplify_final_df[
    "sequence_sha256"
] = (
    amplify_final_df[
        "sequence"
    ].map(
        lambda seq:
            hashlib.sha256(
                seq.encode("utf-8")
            ).hexdigest()
    )
)


assert amplify_final_df[
    "length_qc"
].between(
    10,
    200,
    inclusive="both",
).all()


# ------------------------------------------------------------
# 14. Final split summary
# ------------------------------------------------------------
final_split_summary_df = (
    amplify_final_df
    .groupby(
        [
            "split",
            "label",
        ],
        as_index=False,
    )
    .agg(
        n=(
            "sample_id",
            "count",
        ),

        min_len=(
            "length_qc",
            "min",
        ),

        median_len=(
            "length_qc",
            "median",
        ),

        max_len=(
            "length_qc",
            "max",
        ),
    )
)


# ------------------------------------------------------------
# 15. Verify every split contains both classes
# ------------------------------------------------------------
for split_name in [
    "train",
    "validation",
    "test",
]:

    part = amplify_final_df[
        amplify_final_df[
            "split"
        ] == split_name
    ]

    assert set(
        part["label"].unique()
    ) == {0, 1}

    n_amp = int(
        (
            part["label"] == 1
        ).sum()
    )

    n_nonamp = int(
        (
            part["label"] == 0
        ).sum()
    )

    minority = min(
        n_amp,
        n_nonamp,
    )

    majority = max(
        n_amp,
        n_nonamp,
    )

    ratio = (
        majority
        / minority
    )

    assert ratio <= 1.10, (
        f"Unexpected class imbalance "
        f"in AMPlify {split_name}: "
        f"{n_amp}:{n_nonamp}"
    )


# ------------------------------------------------------------
# 16. Verify test was not altered
# ------------------------------------------------------------
original_test_label_counts = (
    original_test_df[
        "label"
    ]
    .value_counts()
    .to_dict()
)

final_test_label_counts = (
    amplify_test_df[
        "label"
    ]
    .value_counts()
    .to_dict()
)

assert (
    original_test_label_counts
    ==
    final_test_label_counts
)


# ------------------------------------------------------------
# 17. Output directory
# ------------------------------------------------------------
AMPLIFY_FINAL_DIR = (
    SPLIT_DIR
    / "AMPlify_balanced_FINAL"
)

AMPLIFY_FINAL_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


AMPLIFY_FINAL_ALL_PATH = (
    AMPLIFY_FINAL_DIR
    / "AMPlify_balanced_all.csv"
)

AMPLIFY_FINAL_TRAIN_PATH = (
    AMPLIFY_FINAL_DIR
    / "train.csv"
)

AMPLIFY_FINAL_VALIDATION_PATH = (
    AMPLIFY_FINAL_DIR
    / "validation.csv"
)

AMPLIFY_FINAL_TEST_PATH = (
    AMPLIFY_FINAL_DIR
    / "test.csv"
)


# ------------------------------------------------------------
# 18. Save datasets
# ------------------------------------------------------------
amplify_final_df.to_csv(
    AMPLIFY_FINAL_ALL_PATH,
    index=False,
)

amplify_train_df.to_csv(
    AMPLIFY_FINAL_TRAIN_PATH,
    index=False,
)

amplify_validation_df.to_csv(
    AMPLIFY_FINAL_VALIDATION_PATH,
    index=False,
)

amplify_test_df.to_csv(
    AMPLIFY_FINAL_TEST_PATH,
    index=False,
)


# ------------------------------------------------------------
# 19. File hash helper
# ------------------------------------------------------------
def sha256_file(path):

    h = hashlib.sha256()

    with open(path, "rb") as f:

        for chunk in iter(
            lambda:
                f.read(
                    1024 * 1024
                ),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


# ------------------------------------------------------------
# 20. Save summaries
# ------------------------------------------------------------
AMPLIFY_SPLIT_SUMMARY_PATH = (
    AUDIT_DIR
    / "amplify_final_split_summary.csv"
)

AMPLIFY_STRATUM_SUMMARY_PATH = (
    AUDIT_DIR
    / "amplify_validation_stratum_summary.csv"
)


final_split_summary_df.to_csv(
    AMPLIFY_SPLIT_SUMMARY_PATH,
    index=False,
)

stratum_summary_df.to_csv(
    AMPLIFY_STRATUM_SUMMARY_PATH,
    index=False,
)


# ------------------------------------------------------------
# 21. Save partition manifest
# ------------------------------------------------------------
AMPLIFY_PARTITION_MANIFEST_PATH = (
    MANIFEST_DIR
    / "amplify_final_partition_manifest.json"
)


partition_manifest = {

    "schema_version":
        "1.0",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "status":
        "FROZEN_BEFORE_MODEL_TRAINING",

    "dataset":
        "AMPlify_balanced",

    "replacement_for":
        "External_Benchmark_2",

    "replacement_decision":
        "ACCEPTED",

    "original_clean_counts": {

        "train":
            int(
                len(
                    original_train_df
                )
            ),

        "test":
            int(
                len(
                    original_test_df
                )
            ),
    },

    "validation_creation": {

        "source":
            "original_AMPlify_training_only",

        "validation_fraction":
            VALIDATION_FRACTION,

        "partition_method":
            (
                "deterministic_SHA256_ranking_"
                "within_label_x_length_bin"
            ),

        "partition_version":
            AMPLIFY_PARTITION_VERSION,

        "partition_seed":
            AMPLIFY_PARTITION_SEED,

        "model_seed_used":
            False,

        "model_seeds":
            list(SEEDS),

        "length_bins":
            LENGTH_LABELS,
    },

    "test_policy": {

        "original_test_modified":
            False,

        "test_used_for_validation":
            False,

        "test_used_for_model_selection":
            False,
    },

    "exact_overlap": {

        "train_validation":
            0,

        "train_test":
            0,

        "validation_test":
            0,
    },

    "files": {

        "all":
            str(
                AMPLIFY_FINAL_ALL_PATH
            ),

        "all_sha256":
            sha256_file(
                AMPLIFY_FINAL_ALL_PATH
            ),

        "train":
            str(
                AMPLIFY_FINAL_TRAIN_PATH
            ),

        "train_sha256":
            sha256_file(
                AMPLIFY_FINAL_TRAIN_PATH
            ),

        "validation":
            str(
                AMPLIFY_FINAL_VALIDATION_PATH
            ),

        "validation_sha256":
            sha256_file(
                AMPLIFY_FINAL_VALIDATION_PATH
            ),

        "test":
            str(
                AMPLIFY_FINAL_TEST_PATH
            ),

        "test_sha256":
            sha256_file(
                AMPLIFY_FINAL_TEST_PATH
            ),
    },
}


with open(
    AMPLIFY_PARTITION_MANIFEST_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        partition_manifest,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 22. Final hard assertions
# ------------------------------------------------------------
assert (
    AMPLIFY_FINAL_ALL_PATH.exists()
)

assert (
    AMPLIFY_FINAL_TRAIN_PATH.exists()
)

assert (
    AMPLIFY_FINAL_VALIDATION_PATH.exists()
)

assert (
    AMPLIFY_FINAL_TEST_PATH.exists()
)

assert (
    AMPLIFY_PARTITION_MANIFEST_PATH.exists()
)


assert (
    len(amplify_train_df)
    + len(amplify_validation_df)
    + len(amplify_test_df)
    == 8068
)


# ------------------------------------------------------------
# 23. Report
# ------------------------------------------------------------
print("=" * 110)

print(
    "CELL 9 PASS - AMPlify ACCEPTED AS "
    "REPLACEMENT AND FIXED PARTITION FROZEN"
)

print("=" * 110)

print(
    "REPLACES              : External_Benchmark_2"
)

print(
    "FINAL DATASET NAME    : AMPlify_balanced"
)

print(
    "MODEL SEEDS           : "
    f"{list(SEEDS)}"
)

print(
    "MODEL SEED USED FOR "
    "DATA SPLIT           : FALSE"
)

print(
    f"PARTITION SEED        : "
    f"{AMPLIFY_PARTITION_SEED}"
)

print(
    "PARTITION METHOD      : "
    "DETERMINISTIC SHA256"
)

print(
    "STRATIFICATION        : "
    "LABEL x LENGTH BIN"
)

print(
    "VALIDATION SOURCE     : "
    "ORIGINAL TRAIN ONLY"
)

print(
    "ORIGINAL TEST CHANGED : FALSE"
)

print("-" * 110)

print(
    "FINAL AMPlify SPLITS"
)

print(
    final_split_summary_df
    .to_string(
        index=False
    )
)

print("-" * 110)

print(
    "STRATUM PARTITION SUMMARY"
)

print(
    stratum_summary_df
    .to_string(
        index=False,
        float_format=lambda x:
            f"{x:.4f}",
    )
)

print("-" * 110)

print(
    "EXACT SPLIT OVERLAP"
)

print(
    "Train <-> Validation : 0"
)

print(
    "Train <-> Test       : 0"
)

print(
    "Validation <-> Test  : 0"
)

print("-" * 110)

print(
    f"Final AMPlify : "
    f"{AMPLIFY_FINAL_ALL_PATH}"
)

print(
    f"Manifest      : "
    f"{AMPLIFY_PARTITION_MANIFEST_PATH}"
)

print("=" * 110)

==============================================================================================================
CELL 9 PASS - AMPlify ACCEPTED AS REPLACEMENT AND FIXED PARTITION FROZEN
==============================================================================================================
REPLACES              : External_Benchmark_2
FINAL DATASET NAME    : AMPlify_balanced
MODEL SEEDS           : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
MODEL SEED USED FOR DATA SPLIT           : FALSE
PARTITION SEED        : 2026
PARTITION METHOD      : DETERMINISTIC SHA256
STRATIFICATION        : LABEL x LENGTH BIN
VALIDATION SOURCE     : ORIGINAL TRAIN ONLY
ORIGINAL TEST CHANGED : FALSE
--------------------------------------------------------------------------------------------------------------
FINAL AMPlify SPLITS
     split  label    n  min_len  median_len  max_len
      test      0  806       10        28.0      161
      test      1  786       10        25.0      152
     train      0 2743       10        27.0      183
     train      1 2761       10        27.0      183
validation      0  485       10        28.0      174
validation      1  487       10        25.0      161
--------------------------------------------------------------------------------------------------------------
STRATUM PARTITION SUMMARY
  stratum  n_original_train  n_final_train  n_validation  validation_fraction
  0|10-50              2966           2521           445               0.1500
0|101-150                46             39             7               0.1522
0|151-200                 6              5             1               0.1667
 0|51-100               210            178            32               0.1524
  1|10-50              2945           2503           442               0.1501
1|101-150                46             39             7               0.1522
1|151-200                 8              7             1               0.1250
 1|51-100               249            212            37               0.1486
--------------------------------------------------------------------------------------------------------------
EXACT SPLIT OVERLAP
Train <-> Validation : 0
Train <-> Test       : 0
Validation <-> Test  : 0
--------------------------------------------------------------------------------------------------------------
Final AMPlify : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/splits/AMPlify_balanced_FINAL/AMPlify_balanced_all.csv
Manifest      : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/amplify_final_partition_manifest.json
==============================================================================================================

In [19]:
# ============================================================
# CELL 10 - FINAL 4-DATASET BENCHMARK REBUILD
#           External_Benchmark_2 -> AMPlify_balanced
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import shutil
import pandas as pd


# ------------------------------------------------------------
# 1. Validate notebook state
# ------------------------------------------------------------
REQUIRED_GLOBALS = [
    "PROJECT_ROOT",
    "SPLIT_DIR",
    "AUDIT_DIR",
    "MANIFEST_DIR",
    "SEEDS",
]

for name in REQUIRED_GLOBALS:
    assert name in globals(), (
        f"{name} missing. Run previous cells first."
    )


LOCKED_SEEDS = list(SEEDS)

assert LOCKED_SEEDS == list(
    range(100, 110)
), (
    "Model seed lock changed unexpectedly."
)


# ------------------------------------------------------------
# 2. Final dataset identities
# ------------------------------------------------------------
FINAL_DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "AMPlify_balanced",
    "External_Benchmark_3",
]

RETIRED_DATASET = (
    "External_Benchmark_2"
)

assert len(FINAL_DATASETS) == 4

assert RETIRED_DATASET not in FINAL_DATASETS


# ------------------------------------------------------------
# 3. Source files FROM DISK
# ------------------------------------------------------------
ORIGINAL_HARMONIZED_PATH = (
    SPLIT_DIR
    / "benchmark4_harmonized_qc.csv"
)

AMPLIFY_FINAL_PATH = (
    SPLIT_DIR
    / "AMPlify_balanced_FINAL"
    / "AMPlify_balanced_all.csv"
)

AMPLIFY_PARTITION_MANIFEST_PATH = (
    MANIFEST_DIR
    / "amplify_final_partition_manifest.json"
)

AMPLIFY_CANDIDATE_AUDIT_PATH = (
    AUDIT_DIR
    / "amplify_candidate_directional_decontamination.csv"
)

OLD_PROTOCOL2_SUMMARY_PATH = (
    AUDIT_DIR
    / "protocol2_strict_decontamination_summary.csv"
)


assert ORIGINAL_HARMONIZED_PATH.is_file(), (
    f"Missing:\n{ORIGINAL_HARMONIZED_PATH}"
)

assert AMPLIFY_FINAL_PATH.is_file(), (
    f"Missing:\n{AMPLIFY_FINAL_PATH}"
)

assert AMPLIFY_PARTITION_MANIFEST_PATH.is_file(), (
    f"Missing:\n{AMPLIFY_PARTITION_MANIFEST_PATH}"
)

assert AMPLIFY_CANDIDATE_AUDIT_PATH.is_file(), (
    f"Missing:\n{AMPLIFY_CANDIDATE_AUDIT_PATH}"
)

assert OLD_PROTOCOL2_SUMMARY_PATH.is_file(), (
    f"Missing:\n{OLD_PROTOCOL2_SUMMARY_PATH}"
)


# ------------------------------------------------------------
# 4. Verify AMPlify acceptance manifest
# ------------------------------------------------------------
with open(
    AMPLIFY_PARTITION_MANIFEST_PATH,
    "r",
    encoding="utf-8",
) as f:
    amplify_partition_manifest = json.load(f)


assert (
    amplify_partition_manifest[
        "dataset"
    ]
    == "AMPlify_balanced"
)

assert (
    amplify_partition_manifest[
        "replacement_for"
    ]
    == "External_Benchmark_2"
)

assert (
    amplify_partition_manifest[
        "replacement_decision"
    ]
    == "ACCEPTED"
)

assert (
    amplify_partition_manifest[
        "test_policy"
    ][
        "original_test_modified"
    ]
    is False
)


# ------------------------------------------------------------
# 5. Load original harmonized cohort
# ------------------------------------------------------------
old_benchmark_df = pd.read_csv(
    ORIGINAL_HARMONIZED_PATH,
    low_memory=False,
)

assert set(
    old_benchmark_df[
        "dataset"
    ].unique()
) == {
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "External_Benchmark_2",
    "External_Benchmark_3",
}


# ------------------------------------------------------------
# 6. Retain only the three accepted old datasets
# ------------------------------------------------------------
RETAINED_OLD_DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "External_Benchmark_3",
]

retained_df = (
    old_benchmark_df[
        old_benchmark_df[
            "dataset"
        ].isin(
            RETAINED_OLD_DATASETS
        )
    ]
    .copy()
    .reset_index(drop=True)
)


assert set(
    retained_df[
        "dataset"
    ].unique()
) == set(
    RETAINED_OLD_DATASETS
)


# ------------------------------------------------------------
# 7. Load final AMPlify partition
# ------------------------------------------------------------
amplify_final_df = pd.read_csv(
    AMPLIFY_FINAL_PATH,
    low_memory=False,
)

assert len(
    amplify_final_df
) == 8068

assert amplify_final_df[
    "sequence"
].is_unique

assert set(
    amplify_final_df[
        "split"
    ].unique()
) == {
    "train",
    "validation",
    "test",
}

assert set(
    amplify_final_df[
        "label"
    ].unique()
) == {0, 1}


# ------------------------------------------------------------
# 8. Standard columns for final experiment cohort
# ------------------------------------------------------------
FINAL_COLUMNS = [
    "dataset",
    "sample_id",
    "original_header",
    "sequence",
    "label",
    "split",
    "source_file",
    "length_qc",
    "sequence_sha256",
]


for column in FINAL_COLUMNS:

    assert column in retained_df.columns, (
        f"Missing retained column: {column}"
    )

    assert column in amplify_final_df.columns, (
        f"Missing AMPlify column: {column}"
    )


retained_final = (
    retained_df[
        FINAL_COLUMNS
    ]
    .copy()
)

amplify_final = (
    amplify_final_df[
        FINAL_COLUMNS
    ]
    .copy()
)


# ------------------------------------------------------------
# 9. Build FINAL four-dataset benchmark
# ------------------------------------------------------------
benchmark4_final_df = pd.concat(
    [
        retained_final,
        amplify_final,
    ],
    ignore_index=True,
)


assert set(
    benchmark4_final_df[
        "dataset"
    ].unique()
) == set(
    FINAL_DATASETS
)


assert RETIRED_DATASET not in set(
    benchmark4_final_df[
        "dataset"
    ].unique()
)


# ------------------------------------------------------------
# 10. Expected final dataset totals
# ------------------------------------------------------------
EXPECTED_FINAL_COUNTS = {
    "GenPept_Curated_2025": 11000,
    "External_Benchmark_1": 8156,
    "AMPlify_balanced": 8068,
    "External_Benchmark_3": 13835,
}


observed_final_counts = (
    benchmark4_final_df[
        "dataset"
    ]
    .value_counts()
    .to_dict()
)


assert (
    observed_final_counts
    == EXPECTED_FINAL_COUNTS
), (
    "Final dataset count mismatch.\n"
    f"Expected: {EXPECTED_FINAL_COUNTS}\n"
    f"Observed: {observed_final_counts}"
)


assert len(
    benchmark4_final_df
) == 41059


# ------------------------------------------------------------
# 11. Global integrity
# ------------------------------------------------------------
assert benchmark4_final_df[
    "sample_id"
].is_unique

assert set(
    benchmark4_final_df[
        "label"
    ].unique()
) == {0, 1}

assert set(
    benchmark4_final_df[
        "split"
    ].unique()
) == {
    "train",
    "validation",
    "test",
}

assert benchmark4_final_df[
    "sequence"
].notna().all()

assert benchmark4_final_df[
    "length_qc"
].between(
    10,
    200,
    inclusive="both",
).all()


# ------------------------------------------------------------
# 12. Verify internal exact uniqueness
# ------------------------------------------------------------
internal_audit_rows = []


for dataset_name in FINAL_DATASETS:

    part = (
        benchmark4_final_df[
            benchmark4_final_df[
                "dataset"
            ] == dataset_name
        ]
        .copy()
    )

    n_rows = len(part)

    n_unique = (
        part[
            "sequence"
        ].nunique()
    )

    label_conflicts = int(
        (
            part
            .groupby(
                "sequence"
            )[
                "label"
            ]
            .nunique()
            > 1
        ).sum()
    )

    internal_audit_rows.append({
        "dataset":
            dataset_name,

        "n_rows":
            int(n_rows),

        "n_unique_sequences":
            int(n_unique),

        "duplicate_rows":
            int(
                n_rows
                - n_unique
            ),

        "label_conflict_sequences":
            label_conflicts,
    })


final_internal_audit_df = pd.DataFrame(
    internal_audit_rows
)


assert (
    final_internal_audit_df[
        "duplicate_rows"
    ] == 0
).all()


assert (
    final_internal_audit_df[
        "label_conflict_sequences"
    ] == 0
).all()


# ------------------------------------------------------------
# 13. Verify AMPlify final split exactly
# ------------------------------------------------------------
AMPLIFY_EXPECTED_SPLITS = {
    ("train", 0): 2743,
    ("train", 1): 2761,
    ("validation", 0): 485,
    ("validation", 1): 487,
    ("test", 0): 806,
    ("test", 1): 786,
}


amplify_observed_split_counts = (
    benchmark4_final_df[
        benchmark4_final_df[
            "dataset"
        ] == "AMPlify_balanced"
    ]
    .groupby(
        [
            "split",
            "label",
        ]
    )
    .size()
    .to_dict()
)


assert (
    amplify_observed_split_counts
    == AMPLIFY_EXPECTED_SPLITS
), (
    "AMPlify final partition changed.\n"
    f"Expected: {AMPLIFY_EXPECTED_SPLITS}\n"
    f"Observed: {amplify_observed_split_counts}"
)


# ------------------------------------------------------------
# 14. Verify GenPept frozen split remains untouched
# ------------------------------------------------------------
genpept_split_counts = (
    benchmark4_final_df[
        benchmark4_final_df[
            "dataset"
        ] == "GenPept_Curated_2025"
    ]
    .groupby(
        "split"
    )
    .size()
    .to_dict()
)


assert genpept_split_counts == {
    "train": 7700,
    "validation": 990,
    "test": 2310,
}


# ------------------------------------------------------------
# 15. Create isolated FINAL experiment directory
#
# Does NOT delete Cell 1-9 audit evidence.
# Only Cell-10-owned FINAL_v1 directory is rebuilt.
# ------------------------------------------------------------
FINAL_SPLIT_ROOT = (
    SPLIT_DIR
    / "benchmark4_FINAL_v1"
)


if FINAL_SPLIT_ROOT.exists():

    shutil.rmtree(
        FINAL_SPLIT_ROOT
    )


FINAL_SPLIT_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


FINAL_WITHIN_DIR = (
    FINAL_SPLIT_ROOT
    / "within_dataset"
)

FINAL_CROSS_DIR = (
    FINAL_SPLIT_ROOT
    / "cross_dataset_transfer"
)


FINAL_WITHIN_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

FINAL_CROSS_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ------------------------------------------------------------
# 16. SHA256 helper
# ------------------------------------------------------------
def sha256_file_final(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda:
                f.read(
                    1024 * 1024
                ),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


# ------------------------------------------------------------
# 17. Save complete FINAL cohort
# ------------------------------------------------------------
FINAL_ALL_PATH = (
    FINAL_SPLIT_ROOT
    / "benchmark4_FINAL_all.csv"
)


benchmark4_final_df.to_csv(
    FINAL_ALL_PATH,
    index=False,
)


FINAL_ALL_SHA256 = (
    sha256_file_final(
        FINAL_ALL_PATH
    )
)


# ------------------------------------------------------------
# 18. Materialize Protocol 1 fixed splits
# ------------------------------------------------------------
within_registry = {}

within_summary_rows = []


for dataset_name in FINAL_DATASETS:

    dataset_dir = (
        FINAL_WITHIN_DIR
        / dataset_name
    )

    dataset_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    within_registry[
        dataset_name
    ] = {}


    for split_name in [
        "train",
        "validation",
        "test",
    ]:

        part = (
            benchmark4_final_df[
                (
                    benchmark4_final_df[
                        "dataset"
                    ] == dataset_name
                )
                &
                (
                    benchmark4_final_df[
                        "split"
                    ] == split_name
                )
            ]
            .copy()
            .reset_index(drop=True)
        )


        assert len(part) > 0

        assert set(
            part[
                "label"
            ].unique()
        ) == {0, 1}

        assert part[
            "sequence"
        ].is_unique


        output_path = (
            dataset_dir
            / f"{split_name}.csv"
        )


        part[
            FINAL_COLUMNS
        ].to_csv(
            output_path,
            index=False,
        )


        file_hash = (
            sha256_file_final(
                output_path
            )
        )


        n_amp = int(
            (
                part[
                    "label"
                ] == 1
            ).sum()
        )

        n_nonamp = int(
            (
                part[
                    "label"
                ] == 0
            ).sum()
        )


        within_registry[
            dataset_name
        ][
            split_name
        ] = {

            "path":
                str(
                    output_path
                ),

            "sha256":
                file_hash,

            "n":
                int(
                    len(part)
                ),

            "AMP":
                n_amp,

            "non_AMP":
                n_nonamp,
        }


        within_summary_rows.append({

            "dataset":
                dataset_name,

            "split":
                split_name,

            "n":
                int(
                    len(part)
                ),

            "AMP":
                n_amp,

            "non_AMP":
                n_nonamp,

            "path":
                str(
                    output_path
                ),

            "sha256":
                file_hash,
        })


final_within_summary_df = (
    pd.DataFrame(
        within_summary_rows
    )
)


# ------------------------------------------------------------
# 19. Protocol 2 contract
#
# MODEL FIT:
#   source train only
#
# MODEL SELECTION:
#   source validation only
#
# SOURCE TEST:
#   never used for model fitting/tuning
#
# EXTERNAL TARGET:
#   target test only
#
# DECONTAMINATION:
#   remove target-test sequence if it occurs
#   anywhere in entire source dataset.
# ------------------------------------------------------------
FINAL_PROTOCOL2_POLICY = {

    "source_model_fit":
        "train_only",

    "source_model_selection":
        "validation_only",

    "source_test_model_usage":
        "none",

    "source_test_decontamination_usage":
        "sequence_identity_only",

    "target_evaluation":
        "test_only",

    "target_training":
        False,

    "target_validation_usage":
        False,

    "target_retraining":
        False,

    "target_finetuning":
        False,

    "target_threshold_tuning":
        False,

    "target_feature_fitting":
        False,

    "decontamination_reference":
        "entire_source_dataset",

    "identity_definition":
        "exact_normalized_sequence_identity",

    "action":
        "remove_overlap_from_target_test",

    "data_resplitting_per_seed":
        False,
}


# ------------------------------------------------------------
# 20. Rebuild ALL 12 directional cross-dataset pairs
# ------------------------------------------------------------
cross_summary_rows = []

cross_registry = {}


for source_dataset in FINAL_DATASETS:

    source_all = (
        benchmark4_final_df[
            benchmark4_final_df[
                "dataset"
            ] == source_dataset
        ]
        .copy()
        .reset_index(drop=True)
    )


    source_train = (
        source_all[
            source_all[
                "split"
            ] == "train"
        ]
        .copy()
    )


    source_validation = (
        source_all[
            source_all[
                "split"
            ] == "validation"
        ]
        .copy()
    )


    source_test = (
        source_all[
            source_all[
                "split"
            ] == "test"
        ]
        .copy()
    )


    source_all_sequences = set(
        source_all[
            "sequence"
        ]
    )


    source_label_map = (
        source_all
        .set_index(
            "sequence"
        )[
            "label"
        ]
        .to_dict()
    )


    assert source_all[
        "sequence"
    ].is_unique


    for target_dataset in FINAL_DATASETS:

        if (
            target_dataset
            == source_dataset
        ):
            continue


        pair_id = (
            f"{source_dataset}"
            f"__TO__"
            f"{target_dataset}"
        )


        pair_dir = (
            FINAL_CROSS_DIR
            / pair_id
        )


        pair_dir.mkdir(
            parents=True,
            exist_ok=True,
        )


        # ----------------------------------------------------
        # Target held-out TEST only
        # ----------------------------------------------------
        target_test_raw = (
            benchmark4_final_df[
                (
                    benchmark4_final_df[
                        "dataset"
                    ] == target_dataset
                )
                &
                (
                    benchmark4_final_df[
                        "split"
                    ] == "test"
                )
            ]
            .copy()
            .reset_index(drop=True)
        )


        assert target_test_raw[
            "sequence"
        ].is_unique


        # ----------------------------------------------------
        # Strict entire-source overlap
        # ----------------------------------------------------
        overlap_mask = (
            target_test_raw[
                "sequence"
            ].isin(
                source_all_sequences
            )
        )


        removed_df = (
            target_test_raw[
                overlap_mask
            ]
            .copy()
            .reset_index(drop=True)
        )


        target_clean_df = (
            target_test_raw[
                ~overlap_mask
            ]
            .copy()
            .reset_index(drop=True)
        )


        # ----------------------------------------------------
        # Annotate overlap conflicts
        # ----------------------------------------------------
        if len(
            removed_df
        ) > 0:

            removed_df[
                "source_label"
            ] = (
                removed_df[
                    "sequence"
                ]
                .map(
                    source_label_map
                )
                .astype(int)
            )


            removed_df[
                "target_label"
            ] = (
                removed_df[
                    "label"
                ]
                .astype(int)
            )


            removed_df[
                "label_conflict"
            ] = (
                removed_df[
                    "source_label"
                ]
                !=
                removed_df[
                    "target_label"
                ]
            )

        else:

            removed_df[
                "source_label"
            ] = pd.Series(
                dtype="int64"
            )

            removed_df[
                "target_label"
            ] = pd.Series(
                dtype="int64"
            )

            removed_df[
                "label_conflict"
            ] = pd.Series(
                dtype="bool"
            )


        # ----------------------------------------------------
        # Hard residual-overlap check
        # ----------------------------------------------------
        residual_overlap = (
            set(
                target_clean_df[
                    "sequence"
                ]
            )
            .intersection(
                source_all_sequences
            )
        )


        assert len(
            residual_overlap
        ) == 0, (
            f"Residual exact overlap: {pair_id}"
        )


        # ----------------------------------------------------
        # Both target classes must survive
        # ----------------------------------------------------
        assert set(
            target_clean_df[
                "label"
            ].unique()
        ) == {0, 1}, (
            f"Target lost a class: {pair_id}"
        )


        # ----------------------------------------------------
        # Counts
        # ----------------------------------------------------
        target_raw_n = int(
            len(
                target_test_raw
            )
        )


        overlap_removed_n = int(
            len(
                removed_df
            )
        )


        target_clean_n = int(
            len(
                target_clean_df
            )
        )


        assert (
            target_raw_n
            ==
            overlap_removed_n
            +
            target_clean_n
        )


        amp_clean = int(
            (
                target_clean_df[
                    "label"
                ] == 1
            ).sum()
        )


        nonamp_clean = int(
            (
                target_clean_df[
                    "label"
                ] == 0
            ).sum()
        )


        minority_n = min(
            amp_clean,
            nonamp_clean,
        )


        majority_n = max(
            amp_clean,
            nonamp_clean,
        )


        class_ratio = (
            majority_n
            / minority_n
        )


        label_conflicts = (
            int(
                removed_df[
                    "label_conflict"
                ].sum()
            )
            if len(
                removed_df
            ) > 0
            else 0
        )


        # ----------------------------------------------------
        # Acceptance criterion established in Cell 8:
        # no severe minority-class collapse (<100)
        # ----------------------------------------------------
        assert minority_n >= 100, (
            f"Severe low-support target detected "
            f"in {pair_id}: minority={minority_n}"
        )


        # ----------------------------------------------------
        # Save target BEFORE removal
        # ----------------------------------------------------
        before_path = (
            pair_dir
            / "target_test_before_overlap_removal.csv"
        )


        target_test_raw[
            FINAL_COLUMNS
        ].to_csv(
            before_path,
            index=False,
        )


        # ----------------------------------------------------
        # Save overlaps removed
        # ----------------------------------------------------
        removed_path = (
            pair_dir
            / "target_test_exact_overlaps_removed.csv"
        )


        removed_df.to_csv(
            removed_path,
            index=False,
        )


        # ----------------------------------------------------
        # Save FINAL clean target
        # ----------------------------------------------------
        clean_path = (
            pair_dir
            / "target_test_decontaminated.csv"
        )


        target_clean_df[
            FINAL_COLUMNS
        ].to_csv(
            clean_path,
            index=False,
        )


        # ----------------------------------------------------
        # Pair manifest
        # ----------------------------------------------------
        pair_manifest = {

            "schema_version":
                "1.0",

            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "benchmark_version":
                "benchmark4_FINAL_v1",

            "source_dataset":
                source_dataset,

            "target_dataset":
                target_dataset,

            "source": {

                "train_n":
                    int(
                        len(
                            source_train
                        )
                    ),

                "validation_n":
                    int(
                        len(
                            source_validation
                        )
                    ),

                "test_n":
                    int(
                        len(
                            source_test
                        )
                    ),

                "all_n":
                    int(
                        len(
                            source_all
                        )
                    ),

                "model_fit":
                    "train_only",

                "model_selection":
                    "validation_only",

                "source_test_model_usage":
                    False,

                "source_test_decontamination_usage":
                    True,
            },

            "target": {

                "evaluation_split":
                    "test",

                "raw_n":
                    target_raw_n,

                "overlap_removed_n":
                    overlap_removed_n,

                "label_conflicts_removed":
                    label_conflicts,

                "clean_n":
                    target_clean_n,

                "AMP_clean":
                    amp_clean,

                "non_AMP_clean":
                    nonamp_clean,

                "minority_class_n":
                    minority_n,

                "majority_minority_ratio":
                    class_ratio,
            },

            "decontamination": {

                "reference":
                    "entire_source_dataset",

                "identity":
                    "exact_100_percent",

                "residual_overlap":
                    0,
            },

            "files": {

                "target_before":
                    str(
                        before_path
                    ),

                "target_before_sha256":
                    sha256_file_final(
                        before_path
                    ),

                "removed":
                    str(
                        removed_path
                    ),

                "removed_sha256":
                    sha256_file_final(
                        removed_path
                    ),

                "target_clean":
                    str(
                        clean_path
                    ),

                "target_clean_sha256":
                    sha256_file_final(
                        clean_path
                    ),
            },
        }


        pair_manifest_path = (
            pair_dir
            / "pair_manifest.json"
        )


        with open(
            pair_manifest_path,
            "w",
            encoding="utf-8",
        ) as f:

            json.dump(
                pair_manifest,
                f,
                indent=2,
                ensure_ascii=False,
            )


        cross_registry[
            pair_id
        ] = {

            "source_dataset":
                source_dataset,

            "target_dataset":
                target_dataset,

            "target_clean_path":
                str(
                    clean_path
                ),

            "pair_manifest":
                str(
                    pair_manifest_path
                ),
        }


        cross_summary_rows.append({

            "source_dataset":
                source_dataset,

            "target_dataset":
                target_dataset,

            "source_train_n":
                int(
                    len(
                        source_train
                    )
                ),

            "source_validation_n":
                int(
                    len(
                        source_validation
                    )
                ),

            "source_test_n":
                int(
                    len(
                        source_test
                    )
                ),

            "source_all_n":
                int(
                    len(
                        source_all
                    )
                ),

            "target_test_raw_n":
                target_raw_n,

            "exact_overlap_removed":
                overlap_removed_n,

            "label_conflicts_removed":
                label_conflicts,

            "target_test_clean_n":
                target_clean_n,

            "target_AMP_clean":
                amp_clean,

            "target_nonAMP_clean":
                nonamp_clean,

            "minority_class_n":
                minority_n,

            "class_ratio_majority_to_minority":
                class_ratio,

            "removed_pct":
                (
                    100.0
                    * overlap_removed_n
                    / target_raw_n
                ),

            "residual_exact_overlap":
                int(
                    len(
                        residual_overlap
                    )
                ),
        })


# ------------------------------------------------------------
# 21. Build final 12-pair table
# ------------------------------------------------------------
final_cross_summary_df = pd.DataFrame(
    cross_summary_rows
)


assert len(
    final_cross_summary_df
) == 12


assert (
    final_cross_summary_df[
        "residual_exact_overlap"
    ] == 0
).all()


assert (
    final_cross_summary_df[
        "minority_class_n"
    ] >= 100
).all()


# ------------------------------------------------------------
# 22. Verify AMPlify directional results against
#     the independent Cell 8 candidate audit
#
# AMPlify validation creation must not alter:
# - entire AMPlify sequence membership
# - AMPlify test membership
# Therefore Cell-8 and Cell-10 overlap results
# involving AMPlify must remain identical.
# ------------------------------------------------------------
cell8_amplify_audit = pd.read_csv(
    AMPLIFY_CANDIDATE_AUDIT_PATH
)


cell10_amplify_pairs = (
    final_cross_summary_df[
        (
            final_cross_summary_df[
                "source_dataset"
            ] == "AMPlify_balanced"
        )
        |
        (
            final_cross_summary_df[
                "target_dataset"
            ] == "AMPlify_balanced"
        )
    ]
    .copy()
)


comparison_df = (
    cell10_amplify_pairs
    .merge(
        cell8_amplify_audit[
            [
                "source_dataset",
                "target_dataset",
                "exact_overlap_removed",
                "target_test_clean_n",
                "target_AMP_clean",
                "target_nonAMP_clean",
            ]
        ],
        on=[
            "source_dataset",
            "target_dataset",
        ],
        how="left",
        suffixes=(
            "_cell10",
            "_cell8",
        ),
        validate="one_to_one",
    )
)


assert len(
    comparison_df
) == 6


assert comparison_df[
    "exact_overlap_removed_cell8"
].notna().all()


for metric in [
    "exact_overlap_removed",
    "target_test_clean_n",
    "target_AMP_clean",
    "target_nonAMP_clean",
]:

    assert (
        comparison_df[
            f"{metric}_cell10"
        ]
        ==
        comparison_df[
            f"{metric}_cell8"
        ]
    ).all(), (
        f"AMPlify Cell 8 <-> Cell 10 "
        f"mismatch for {metric}"
    )


# ------------------------------------------------------------
# 23. Record evidence for retiring old Dataset 2
# ------------------------------------------------------------
old_protocol2_df = pd.read_csv(
    OLD_PROTOCOL2_SUMMARY_PATH
)


problem_pair_df = (
    old_protocol2_df[
        (
            old_protocol2_df[
                "source_dataset"
            ]
            == "External_Benchmark_1"
        )
        &
        (
            old_protocol2_df[
                "target_dataset"
            ]
            == "External_Benchmark_2"
        )
    ]
    .copy()
)


assert len(
    problem_pair_df
) == 1


problem_row = (
    problem_pair_df.iloc[0]
)


assert int(
    problem_row[
        "target_AMP_clean"
    ]
) == 8


assert int(
    problem_row[
        "target_nonAMP_clean"
    ]
) == 711


# ------------------------------------------------------------
# 24. Final dataset summary
# ------------------------------------------------------------
final_dataset_summary_df = (
    benchmark4_final_df
    .groupby(
        "dataset",
        as_index=False,
    )
    .agg(
        total=(
            "sample_id",
            "count",
        ),

        AMP=(
            "label",
            lambda x:
                int(
                    (x == 1).sum()
                ),
        ),

        non_AMP=(
            "label",
            lambda x:
                int(
                    (x == 0).sum()
                ),
        ),

        min_len=(
            "length_qc",
            "min",
        ),

        median_len=(
            "length_qc",
            "median",
        ),

        max_len=(
            "length_qc",
            "max",
        ),
    )
)


# ------------------------------------------------------------
# 25. Save audit tables
# ------------------------------------------------------------
FINAL_DATASET_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark4_FINAL_dataset_summary.csv"
)

FINAL_WITHIN_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark4_FINAL_protocol1_split_summary.csv"
)

FINAL_CROSS_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark4_FINAL_protocol2_decontamination_summary.csv"
)

FINAL_INTERNAL_AUDIT_PATH = (
    AUDIT_DIR
    / "benchmark4_FINAL_internal_duplicate_audit.csv"
)


final_dataset_summary_df.to_csv(
    FINAL_DATASET_SUMMARY_PATH,
    index=False,
)

final_within_summary_df.to_csv(
    FINAL_WITHIN_SUMMARY_PATH,
    index=False,
)

final_cross_summary_df.to_csv(
    FINAL_CROSS_SUMMARY_PATH,
    index=False,
)

final_internal_audit_df.to_csv(
    FINAL_INTERNAL_AUDIT_PATH,
    index=False,
)


# ------------------------------------------------------------
# 26. Replacement evidence record
# ------------------------------------------------------------
REPLACEMENT_RECORD_PATH = (
    MANIFEST_DIR
    / "dataset_replacement_record.json"
)


replacement_record = {

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "retired_dataset":
        "External_Benchmark_2",

    "replacement_dataset":
        "AMPlify_balanced",

    "decision_stage":
        "before_any_model_training",

    "reason":
        (
            "Severe target-class collapse after "
            "strict exact-sequence decontamination"
        ),

    "retired_dataset_evidence": {

        "problem_direction":
            (
                "External_Benchmark_1"
                "__TO__"
                "External_Benchmark_2"
            ),

        "AMP_remaining":
            int(
                problem_row[
                    "target_AMP_clean"
                ]
            ),

        "non_AMP_remaining":
            int(
                problem_row[
                    "target_nonAMP_clean"
                ]
            ),

        "source_audit_file":
            str(
                OLD_PROTOCOL2_SUMMARY_PATH
            ),
    },

    "replacement_acceptance_evidence": {

        "minimum_minority_class_support":
            int(
                final_cross_summary_df[
                    final_cross_summary_df[
                        "source_dataset"
                    ].eq(
                        "AMPlify_balanced"
                    )
                    |
                    final_cross_summary_df[
                        "target_dataset"
                    ].eq(
                        "AMPlify_balanced"
                    )
                ][
                    "minority_class_n"
                ].min()
            ),

        "all_AMPlify_directional_pairs_minority_ge_100":
            True,

        "cell8_audit":
            str(
                AMPLIFY_CANDIDATE_AUDIT_PATH
            ),

        "cell9_partition_manifest":
            str(
                AMPLIFY_PARTITION_MANIFEST_PATH
            ),
    },

    "old_dataset_files_deleted":
        False,

    "old_dataset_used_in_final_benchmark":
        False,
}


with open(
    REPLACEMENT_RECORD_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        replacement_record,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 27. Final benchmark manifest
# ------------------------------------------------------------
FINAL_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark4_FINAL_v1_manifest.json"
)


final_manifest = {

    "schema_version":
        "1.0",

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "status":
        "FINAL_DATA_LOCK_BEFORE_MODEL_TRAINING",

    "datasets":
        FINAL_DATASETS,

    "retired_dataset":
        RETIRED_DATASET,

    "replacement":
        {
            "from":
                "External_Benchmark_2",

            "to":
                "AMPlify_balanced",

            "record":
                str(
                    REPLACEMENT_RECORD_PATH
                ),
        },

    "model_seeds":
        LOCKED_SEEDS,

    "seed_tuning":
        False,

    "data_resplitting_per_model_seed":
        False,

    "total_sequences":
        int(
            len(
                benchmark4_final_df
            )
        ),

    "dataset_counts":
        EXPECTED_FINAL_COUNTS,

    "protocol_1": {

        "model_fit":
            "train",

        "model_selection":
            "validation",

        "final_evaluation":
            "test",

        "fixed_splits":
            True,

        "files":
            within_registry,
    },

    "protocol_2": {

        "policy":
            FINAL_PROTOCOL2_POLICY,

        "n_directional_pairs":
            12,

        "minimum_class_support":
            int(
                final_cross_summary_df[
                    "minority_class_n"
                ].min()
            ),

        "maximum_class_ratio":
            float(
                final_cross_summary_df[
                    "class_ratio_majority_to_minority"
                ].max()
            ),

        "residual_exact_overlap_all_pairs":
            0,

        "pairs":
            cross_registry,
    },

    "final_cohort": {

        "path":
            str(
                FINAL_ALL_PATH
            ),

        "sha256":
            FINAL_ALL_SHA256,
    },
}


with open(
    FINAL_MANIFEST_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        final_manifest,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 28. Final hard assertions
# ------------------------------------------------------------
assert FINAL_ALL_PATH.exists()

assert FINAL_MANIFEST_PATH.exists()

assert REPLACEMENT_RECORD_PATH.exists()

assert len(
    benchmark4_final_df
) == 41059

assert len(
    cross_registry
) == 12

assert (
    final_cross_summary_df[
        "residual_exact_overlap"
    ] == 0
).all()

assert (
    final_cross_summary_df[
        "minority_class_n"
    ].min()
    >= 100
)

assert RETIRED_DATASET not in (
    benchmark4_final_df[
        "dataset"
    ].unique()
)


# ------------------------------------------------------------
# 29. Report
# ------------------------------------------------------------
print("=" * 128)

print(
    "CELL 10 PASS - FINAL FOUR-DATASET BENCHMARK "
    "REBUILT WITH AMPlify REPLACING EXTERNAL_BENCHMARK_2"
)

print("=" * 128)

print(
    "FINAL DATASETS:"
)

for index, dataset_name in enumerate(
    FINAL_DATASETS,
    start=1,
):

    print(
        f"  {index}. {dataset_name}"
    )


print("-" * 128)

print(
    "RETIRED DATASET       : "
    "External_Benchmark_2"
)

print(
    "REPLACEMENT           : "
    "AMPlify_balanced"
)

print(
    "REPLACEMENT DECIDED   : "
    "BEFORE MODEL TRAINING"
)

print(
    "OLD DATA FILES DELETED: FALSE"
)

print("-" * 128)

print(
    "FINAL DATASET SUMMARY"
)

print(
    final_dataset_summary_df
    .to_string(
        index=False
    )
)

print("-" * 128)

print(
    "PROTOCOL 1 - FINAL FIXED SPLITS"
)

print(
    final_within_summary_df[
        [
            "dataset",
            "split",
            "n",
            "AMP",
            "non_AMP",
        ]
    ].to_string(
        index=False
    )
)

print("-" * 128)

print(
    "PROTOCOL 2 - FINAL STRICT "
    "CROSS-DATASET DECONTAMINATION"
)

print(
    final_cross_summary_df[
        [
            "source_dataset",
            "target_dataset",
            "source_all_n",
            "target_test_raw_n",
            "exact_overlap_removed",
            "label_conflicts_removed",
            "target_test_clean_n",
            "target_AMP_clean",
            "target_nonAMP_clean",
            "minority_class_n",
            "class_ratio_majority_to_minority",
            "removed_pct",
            "residual_exact_overlap",
        ]
    ].to_string(
        index=False,
        float_format=lambda x:
            f"{x:.4f}",
    )
)

print("-" * 128)

print(
    "MINIMUM MINORITY-CLASS SUPPORT : "
    f"{int(final_cross_summary_df['minority_class_n'].min())}"
)

print(
    "MAXIMUM CLASS RATIO             : "
    f"{final_cross_summary_df['class_ratio_majority_to_minority'].max():.4f}"
)

print(
    "RESIDUAL EXACT OVERLAP          : "
    "0 FOR ALL 12 PAIRS"
)

print("-" * 128)

print(
    "AMPlify CELL 8 <-> CELL 10 AUDIT : PASS"
)

print(
    "GenPept frozen 7700/990/2310   : PASS"
)

print(
    "Model training performed        : FALSE"
)

print("-" * 128)

print(
    f"Final cohort     : "
    f"{FINAL_ALL_PATH}"
)

print(
    f"Final cohort SHA : "
    f"{FINAL_ALL_SHA256}"
)

print(
    f"Cross summary    : "
    f"{FINAL_CROSS_SUMMARY_PATH}"
)

print(
    f"Replacement log  : "
    f"{REPLACEMENT_RECORD_PATH}"
)

print(
    f"Final manifest   : "
    f"{FINAL_MANIFEST_PATH}"
)

print("=" * 128)

================================================================================================================================
CELL 10 PASS - FINAL FOUR-DATASET BENCHMARK REBUILT WITH AMPlify REPLACING EXTERNAL_BENCHMARK_2
================================================================================================================================
FINAL DATASETS:
  1. GenPept_Curated_2025
  2. External_Benchmark_1
  3. AMPlify_balanced
  4. External_Benchmark_3
--------------------------------------------------------------------------------------------------------------------------------
RETIRED DATASET       : External_Benchmark_2
REPLACEMENT           : AMPlify_balanced
REPLACEMENT DECIDED   : BEFORE MODEL TRAINING
OLD DATA FILES DELETED: FALSE
--------------------------------------------------------------------------------------------------------------------------------
FINAL DATASET SUMMARY
             dataset  total  AMP  non_AMP  min_len  median_len  max_len
    AMPlify_balanced   8068 4034     4034       10        27.0      183
External_Benchmark_1   8156 4602     3554       10        38.0      183
External_Benchmark_3  13835 6764     7071       10        27.0      100
GenPept_Curated_2025  11000 5500     5500       10       113.0      200
--------------------------------------------------------------------------------------------------------------------------------
PROTOCOL 1 - FINAL FIXED SPLITS
             dataset      split    n  AMP  non_AMP
GenPept_Curated_2025      train 7700 3850     3850
GenPept_Curated_2025 validation  990  495      495
GenPept_Curated_2025       test 2310 1155     1155
External_Benchmark_1      train 5435 2838     2597
External_Benchmark_1 validation 1176  875      301
External_Benchmark_1       test 1545  889      656
    AMPlify_balanced      train 5504 2761     2743
    AMPlify_balanced validation  972  487      485
    AMPlify_balanced       test 1592  786      806
External_Benchmark_3      train 9683 4734     4949
External_Benchmark_3 validation 2082 1020     1062
External_Benchmark_3       test 2070 1010     1060
--------------------------------------------------------------------------------------------------------------------------------
PROTOCOL 2 - FINAL STRICT CROSS-DATASET DECONTAMINATION
      source_dataset       target_dataset  source_all_n  target_test_raw_n  exact_overlap_removed  label_conflicts_removed  target_test_clean_n  target_AMP_clean  target_nonAMP_clean  minority_class_n  class_ratio_majority_to_minority  removed_pct  residual_exact_overlap
GenPept_Curated_2025 External_Benchmark_1         11000               1545                     15                        2                 1530               874                  656               656                            1.3323       0.9709                       0
GenPept_Curated_2025     AMPlify_balanced         11000               1592                     10                        2                 1582               784                  798               784                            1.0179       0.6281                       0
GenPept_Curated_2025 External_Benchmark_3         11000               2070                      9                        1                 2061              1001                 1060              1001                            1.0589       0.4348                       0
External_Benchmark_1 GenPept_Curated_2025          8156               2310                     20                        4                 2290              1137                 1153              1137                            1.0141       0.8658                       0
External_Benchmark_1     AMPlify_balanced          8156               1592                    436                       12                 1156               366                  790               366                            2.1585      27.3869                       0
External_Benchmark_1 External_Benchmark_3          8156               2070                    165                        0                 1905               845                 1060               845                            1.2544       7.9710                       0
    AMPlify_balanced GenPept_Curated_2025          8068               2310                     15                        3                 2295              1146                 1149              1146                            1.0026       0.6494                       0
    AMPlify_balanced External_Benchmark_1          8068               1545                    588                        9                  957               309                  648               309                            2.0971      38.0583                       0
    AMPlify_balanced External_Benchmark_3          8068               2070                    160                        3                 1910               850                 1060               850                            1.2471       7.7295                       0
External_Benchmark_3 GenPept_Curated_2025         13835               2310                      9                        1                 2301              1147                 1154              1147                            1.0061       0.3896                       0
External_Benchmark_3 External_Benchmark_1         13835               1545                    223                        0                 1322               666                  656               656                            1.0152      14.4337                       0
External_Benchmark_3     AMPlify_balanced         13835               1592                    195                        2                 1397               593                  804               593                            1.3558      12.2487                       0
--------------------------------------------------------------------------------------------------------------------------------
MINIMUM MINORITY-CLASS SUPPORT : 309
MAXIMUM CLASS RATIO             : 2.1585
RESIDUAL EXACT OVERLAP          : 0 FOR ALL 12 PAIRS
--------------------------------------------------------------------------------------------------------------------------------
AMPlify CELL 8 <-> CELL 10 AUDIT : PASS
GenPept frozen 7700/990/2310   : PASS
Model training performed        : FALSE
--------------------------------------------------------------------------------------------------------------------------------
Final cohort     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/splits/benchmark4_FINAL_v1/benchmark4_FINAL_all.csv
Final cohort SHA : 205f292511f77ca7a3b9f0b2fd03549be60e9df29a62ce3b0b504f63935ad356
Cross summary    : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark4_FINAL_protocol2_decontamination_summary.csv
Replacement log  : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/dataset_replacement_record.json
Final manifest   : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark4_FINAL_v1_manifest.json
================================================================================================================================

In [20]:
# ============================================================
# CELL 11 - FINAL 17-MODEL REGISTRY &
#           EXECUTION CONTRACT LOCK
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import pandas as pd


# ------------------------------------------------------------
# 1. Validate notebook state
# ------------------------------------------------------------
REQUIRED_GLOBALS = [
    "PROJECT_ROOT",
    "AUDIT_DIR",
    "MANIFEST_DIR",
    "SEEDS",
]

for name in REQUIRED_GLOBALS:
    assert name in globals(), (
        f"{name} missing. Run CELLS 1-10 first."
    )


# ------------------------------------------------------------
# 2. Load FINAL benchmark manifest FROM DISK
# ------------------------------------------------------------
FINAL_BENCHMARK_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark4_FINAL_v1_manifest.json"
)

assert FINAL_BENCHMARK_MANIFEST_PATH.is_file(), (
    "Final benchmark manifest not found:\n"
    f"{FINAL_BENCHMARK_MANIFEST_PATH}"
)


with open(
    FINAL_BENCHMARK_MANIFEST_PATH,
    "r",
    encoding="utf-8",
) as f:
    final_benchmark_manifest = json.load(f)


# ------------------------------------------------------------
# 3. Verify FINAL data lock
# ------------------------------------------------------------
EXPECTED_DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "AMPlify_balanced",
    "External_Benchmark_3",
]

EXPECTED_SEEDS = list(
    range(100, 110)
)


assert (
    final_benchmark_manifest[
        "status"
    ]
    == "FINAL_DATA_LOCK_BEFORE_MODEL_TRAINING"
)

assert (
    final_benchmark_manifest[
        "datasets"
    ]
    == EXPECTED_DATASETS
)

assert (
    final_benchmark_manifest[
        "model_seeds"
    ]
    == EXPECTED_SEEDS
)

assert list(SEEDS) == EXPECTED_SEEDS

assert (
    final_benchmark_manifest[
        "seed_tuning"
    ]
    is False
)

assert (
    final_benchmark_manifest[
        "data_resplitting_per_model_seed"
    ]
    is False
)

assert (
    final_benchmark_manifest[
        "protocol_2"
    ][
        "n_directional_pairs"
    ]
    == 12
)

assert (
    final_benchmark_manifest[
        "protocol_2"
    ][
        "residual_exact_overlap_all_pairs"
    ]
    == 0
)


# ------------------------------------------------------------
# 4. FINAL 17-model registry
#
# GROUP A = controlled baselines
# GROUP B = published AMP methods
#
# IMPORTANT:
# Model identity is locked here BEFORE results.
# Hyperparameters are NOT selected here.
# ------------------------------------------------------------
MODEL_REGISTRY = [

    # ========================================================
    # GROUP A - CONTROLLED BASELINES
    # ========================================================

    {
        "model_no": 1,
        "model_id": "logistic_regression",
        "display_name": "Logistic Regression",
        "group": "controlled_baseline",
        "family": "classical_ml",
        "framework": "scikit-learn",
        "execution_environment": "master",
        "implementation_route": "native",
        "implementation_status": "READY",
        "published_amp_method": False,
        "seed_behavior": "may_be_deterministic",
    },

    {
        "model_no": 2,
        "model_id": "linear_svm_calibrated",
        "display_name": "Linear SVM (Calibrated)",
        "group": "controlled_baseline",
        "family": "classical_ml",
        "framework": "scikit-learn",
        "execution_environment": "master",
        "implementation_route": "native",
        "implementation_status": "READY",
        "published_amp_method": False,
        "seed_behavior": "may_be_deterministic",
    },

    {
        "model_no": 3,
        "model_id": "random_forest",
        "display_name": "Random Forest",
        "group": "controlled_baseline",
        "family": "classical_ml",
        "framework": "scikit-learn",
        "execution_environment": "master",
        "implementation_route": "native",
        "implementation_status": "READY",
        "published_amp_method": False,
        "seed_behavior": "stochastic",
    },

    {
        "model_no": 4,
        "model_id": "extra_trees",
        "display_name": "Extra Trees",
        "group": "controlled_baseline",
        "family": "classical_ml",
        "framework": "scikit-learn",
        "execution_environment": "master",
        "implementation_route": "native",
        "implementation_status": "READY",
        "published_amp_method": False,
        "seed_behavior": "stochastic",
    },

    {
        "model_no": 5,
        "model_id": "hist_gradient_boosting",
        "display_name": "HistGradientBoosting",
        "group": "controlled_baseline",
        "family": "classical_ml",
        "framework": "scikit-learn",
        "execution_environment": "master",
        "implementation_route": "native",
        "implementation_status": "READY",
        "published_amp_method": False,
        "seed_behavior": "may_be_deterministic",
    },

    {
        "model_no": 6,
        "model_id": "lightgbm",
        "display_name": "LightGBM",
        "group": "controlled_baseline",
        "family": "classical_ml",
        "framework": "LightGBM",
        "execution_environment": "master",
        "implementation_route": "native",
        "implementation_status": "READY",
        "published_amp_method": False,
        "seed_behavior": "stochastic",
    },

    {
        "model_no": 7,
        "model_id": "cnn1d",
        "display_name": "1D-CNN",
        "group": "controlled_baseline",
        "family": "deep_learning",
        "framework": "TensorFlow/Keras",
        "execution_environment": "master",
        "implementation_route": "native",
        "implementation_status": "READY",
        "published_amp_method": False,
        "seed_behavior": "stochastic",
    },

    {
        "model_no": 8,
        "model_id": "bilstm",
        "display_name": "BiLSTM",
        "group": "controlled_baseline",
        "family": "deep_learning",
        "framework": "TensorFlow/Keras",
        "execution_environment": "master",
        "implementation_route": "native",
        "implementation_status": "READY",
        "published_amp_method": False,
        "seed_behavior": "stochastic",
    },

    {
        "model_no": 9,
        "model_id": "bilstm_attention",
        "display_name": "BiLSTM-Attention",
        "group": "controlled_baseline",
        "family": "deep_learning",
        "framework": "TensorFlow/Keras",
        "execution_environment": "master",
        "implementation_route": "native",
        "implementation_status": "READY",
        "published_amp_method": False,
        "seed_behavior": "stochastic",
    },

    {
        "model_no": 10,
        "model_id": "transformer_encoder",
        "display_name": "Transformer Encoder",
        "group": "controlled_baseline",
        "family": "deep_learning",
        "framework": "TensorFlow/Keras",
        "execution_environment": "master",
        "implementation_route": "native",
        "implementation_status": "READY",
        "published_amp_method": False,
        "seed_behavior": "stochastic",
    },


    # ========================================================
    # GROUP B - PUBLISHED AMP METHODS
    # ========================================================

    {
        "model_no": 11,
        "model_id": "ampep",
        "display_name": "AmPEP",
        "group": "published_amp_method",
        "family": "published_predictor",
        "framework": "method_specific",
        "execution_environment": "separate_or_adapter",
        "implementation_route":
            "faithful_retraining_or_reimplementation",
        "implementation_status":
            "IMPLEMENTATION_AUDIT_REQUIRED",
        "published_amp_method": True,
        "seed_behavior": "method_specific",
    },

    {
        "model_no": 12,
        "model_id": "ampscannerv2",
        "display_name": "AMPScannerV2",
        "group": "published_amp_method",
        "family": "published_predictor",
        "framework": "method_specific",
        "execution_environment": "separate_or_adapter",
        "implementation_route":
            "faithful_retraining_or_reimplementation",
        "implementation_status":
            "IMPLEMENTATION_AUDIT_REQUIRED",
        "published_amp_method": True,
        "seed_behavior": "stochastic",
    },

    {
        "model_no": 13,
        "model_id": "ampgram",
        "display_name": "AmpGram",
        "group": "published_amp_method",
        "family": "published_predictor",
        "framework": "R/ranger_recipe",
        "execution_environment":
            "modern_faithful_reimplementation",
        "implementation_route":
            "published_source_recipe_reimplementation",
        "implementation_status": "ROUTE_PREPARED",
        "published_amp_method": True,
        "seed_behavior": "stochastic",
    },

    {
        "model_no": 14,
        "model_id": "ampir",
        "display_name": "ampir",
        "group": "published_amp_method",
        "family": "published_predictor",
        "framework": "R/caret/svmRadial",
        "execution_environment": "genpept_r_models",
        "implementation_route":
            "published_mature_recipe_retraining",
        "implementation_status": "ROUTE_PREPARED",
        "published_amp_method": True,
        "seed_behavior": "may_be_deterministic",
    },

    {
        "model_no": 15,
        "model_id": "ampeppy",
        "display_name": "amPEPpy",
        "group": "published_amp_method",
        "family": "published_predictor",
        "framework": "method_specific",
        "execution_environment": "separate_or_adapter",
        "implementation_route":
            "faithful_retraining_or_reimplementation",
        "implementation_status":
            "IMPLEMENTATION_AUDIT_REQUIRED",
        "published_amp_method": True,
        "seed_behavior": "method_specific",
    },

    {
        "model_no": 16,
        "model_id": "ai4amp",
        "display_name": "AI4AMP",
        "group": "published_amp_method",
        "family": "published_predictor",
        "framework": "method_specific",
        "execution_environment": "separate_or_adapter",
        "implementation_route":
            "faithful_reimplementation",
        "implementation_status":
            "IMPLEMENTATION_AUDIT_REQUIRED",
        "published_amp_method": True,
        "seed_behavior": "stochastic",
    },

    {
        "model_no": 17,
        "model_id": "amplify",
        "display_name": "AMPlify",
        "group": "published_amp_method",
        "family": "published_predictor",
        "framework": "method_specific",
        "execution_environment": "separate_or_adapter",
        "implementation_route":
            "faithful_retraining_or_reimplementation",
        "implementation_status":
            "IMPLEMENTATION_AUDIT_REQUIRED",
        "published_amp_method": True,
        "seed_behavior": "stochastic",
    },
]


# ------------------------------------------------------------
# 5. Registry integrity
# ------------------------------------------------------------
assert len(MODEL_REGISTRY) == 17


assert [
    x["model_no"]
    for x in MODEL_REGISTRY
] == list(
    range(1, 18)
)


MODEL_IDS = [
    x["model_id"]
    for x in MODEL_REGISTRY
]


assert len(
    set(MODEL_IDS)
) == 17


CONTROLLED_MODELS = [
    x
    for x in MODEL_REGISTRY
    if (
        x["group"]
        == "controlled_baseline"
    )
]


PUBLISHED_MODELS = [
    x
    for x in MODEL_REGISTRY
    if (
        x["group"]
        == "published_amp_method"
    )
]


assert len(
    CONTROLLED_MODELS
) == 10

assert len(
    PUBLISHED_MODELS
) == 7


# ------------------------------------------------------------
# 6. Lock 10-run statistical policy
# ------------------------------------------------------------
TEN_RUN_POLICY = {

    "n_runs_per_model_dataset":
        10,

    "seeds":
        EXPECTED_SEEDS,

    "seed_sequence":
        "consecutive_100_to_109",

    "seed_tuning":
        False,

    "seed_selection_after_results":
        False,

    "same_seeds_all_models":
        True,

    "same_seeds_all_datasets":
        True,

    "data_resplitting_per_seed":
        False,

    "deterministic_model_policy":
        (
            "Run under the same 10-seed schedule; "
            "identical results and SD=0 are valid "
            "and must not trigger seed replacement."
        ),
}


# ------------------------------------------------------------
# 7. Published-method scientific policy
# ------------------------------------------------------------
PUBLISHED_METHOD_POLICY = {

    "fixed_pretrained_predictor_repeated_10_times":
        False,

    "claim_repeated_pretrained_inference_as_10_runs":
        False,

    "faithful_training_or_reimplementation_required":
        True,

    "method_specific_environment_allowed":
        True,

    "source_version_must_be_recorded":
        True,

    "implementation_deviations_must_be_recorded":
        True,

    "hyperparameters_must_be_locked_before_results":
        True,

    "replace_method_due_to_bad_performance":
        False,

    "replacement_before_results_if_implementation_impossible":
        (
            "Allowed only with explicit versioned "
            "protocol amendment before any result "
            "from the replacement is inspected."
        ),
}


# ------------------------------------------------------------
# 8. Final execution contract
# ------------------------------------------------------------
N_MODELS = 17
N_DATASETS = 4
N_SEEDS = 10

N_PROTOCOL1_TRAIN_RUNS = (
    N_MODELS
    * N_DATASETS
    * N_SEEDS
)

N_DIRECTIONAL_PAIRS = 12

N_PROTOCOL2_EXTERNAL_EVALS = (
    N_MODELS
    * N_DIRECTIONAL_PAIRS
    * N_SEEDS
)


assert N_PROTOCOL1_TRAIN_RUNS == 680

assert N_PROTOCOL2_EXTERNAL_EVALS == 2040


EXECUTION_CONTRACT = {

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "datasets":
        EXPECTED_DATASETS,

    "n_models":
        N_MODELS,

    "n_controlled_models":
        10,

    "n_published_methods":
        7,

    "n_datasets":
        N_DATASETS,

    "n_seeds":
        N_SEEDS,

    "seeds":
        EXPECTED_SEEDS,

    "protocol_1": {

        "name":
            "within_dataset",

        "fit":
            "train",

        "model_selection":
            "validation",

        "final_evaluation":
            "test",

        "fixed_data_splits":
            True,

        "training_runs":
            N_PROTOCOL1_TRAIN_RUNS,
    },

    "protocol_2": {

        "name":
            "cross_dataset_transfer",

        "source_training":
            "reuse_protocol1_source_training",

        "source_model_selection":
            "reuse_protocol1_source_validation",

        "additional_training":
            False,

        "target_retraining":
            False,

        "target_finetuning":
            False,

        "target_threshold_tuning":
            False,

        "target_test":
            "strict_exact_sequence_decontaminated",

        "directional_pairs":
            N_DIRECTIONAL_PAIRS,

        "external_evaluations":
            N_PROTOCOL2_EXTERNAL_EVALS,
    },

    "ten_run_policy":
        TEN_RUN_POLICY,

    "published_method_policy":
        PUBLISHED_METHOD_POLICY,

    "hyperparameter_status":
        "TO_BE_LOCKED_BEFORE_TRAINING",

    "metric_status":
        "TO_BE_LOCKED_BEFORE_TRAINING",

    "threshold_status":
        "TO_BE_LOCKED_BEFORE_TRAINING",

    "model_list_change_after_first_result":
        False,
}


# ------------------------------------------------------------
# 9. Convert registry to dataframe
# ------------------------------------------------------------
model_registry_df = pd.DataFrame(
    MODEL_REGISTRY
)


model_registry_df[
    "ten_seed_required"
] = True


model_registry_df[
    "hyperparameters_locked"
] = False


model_registry_df[
    "training_started"
] = False


# ------------------------------------------------------------
# 10. Output paths
# ------------------------------------------------------------
MODEL_REGISTRY_CSV_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_model_registry.csv"
)


MODEL_REGISTRY_JSON_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_model_registry.json"
)


EXECUTION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_execution_contract.json"
)


# ------------------------------------------------------------
# 11. Save CSV
# ------------------------------------------------------------
model_registry_df.to_csv(
    MODEL_REGISTRY_CSV_PATH,
    index=False,
)


# ------------------------------------------------------------
# 12. Save registry JSON
# ------------------------------------------------------------
registry_payload = {

    "schema_version":
        "1.0",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "status":
        "MODEL_LIST_LOCKED_BEFORE_TRAINING",

    "benchmark_manifest":
        str(
            FINAL_BENCHMARK_MANIFEST_PATH
        ),

    "models":
        MODEL_REGISTRY,

    "n_models":
        17,

    "n_controlled":
        10,

    "n_published":
        7,

    "training_started":
        False,
}


with open(
    MODEL_REGISTRY_JSON_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        registry_payload,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 13. Save execution contract
# ------------------------------------------------------------
execution_payload = {

    "schema_version":
        "1.0",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "status":
        "EXECUTION_CONTRACT_LOCKED_BEFORE_TRAINING",

    "contract":
        EXECUTION_CONTRACT,
}


with open(
    EXECUTION_CONTRACT_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        execution_payload,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ------------------------------------------------------------
# 14. SHA-256 helper
# ------------------------------------------------------------
def sha256_file_cell11(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda:
                f.read(
                    1024 * 1024
                ),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


REGISTRY_SHA256 = (
    sha256_file_cell11(
        MODEL_REGISTRY_JSON_PATH
    )
)


CONTRACT_SHA256 = (
    sha256_file_cell11(
        EXECUTION_CONTRACT_PATH
    )
)


# ------------------------------------------------------------
# 15. Re-read persisted files
#     to verify disk reproducibility
# ------------------------------------------------------------
with open(
    MODEL_REGISTRY_JSON_PATH,
    "r",
    encoding="utf-8",
) as f:

    registry_check = json.load(f)


with open(
    EXECUTION_CONTRACT_PATH,
    "r",
    encoding="utf-8",
) as f:

    contract_check = json.load(f)


assert (
    registry_check[
        "n_models"
    ]
    == 17
)

assert (
    registry_check[
        "n_controlled"
    ]
    == 10
)

assert (
    registry_check[
        "n_published"
    ]
    == 7
)

assert (
    registry_check[
        "training_started"
    ]
    is False
)


assert (
    contract_check[
        "contract"
    ][
        "protocol_1"
    ][
        "training_runs"
    ]
    == 680
)


assert (
    contract_check[
        "contract"
    ][
        "protocol_2"
    ][
        "external_evaluations"
    ]
    == 2040
)


assert (
    contract_check[
        "contract"
    ][
        "seeds"
    ]
    == EXPECTED_SEEDS
)


# ------------------------------------------------------------
# 16. Final hard checks
# ------------------------------------------------------------
assert MODEL_REGISTRY_CSV_PATH.exists()

assert MODEL_REGISTRY_JSON_PATH.exists()

assert EXECUTION_CONTRACT_PATH.exists()


assert (
    model_registry_df[
        "training_started"
    ] == False
).all()


assert (
    model_registry_df[
        "hyperparameters_locked"
    ] == False
).all()


# ------------------------------------------------------------
# 17. Report
# ------------------------------------------------------------
print("=" * 122)

print(
    "CELL 11 PASS - FINAL 17-MODEL REGISTRY "
    "AND EXECUTION CONTRACT LOCKED"
)

print("=" * 122)

print(
    "FINAL BENCHMARK:"
)

for i, dataset_name in enumerate(
    EXPECTED_DATASETS,
    start=1,
):

    print(
        f"  {i}. {dataset_name}"
    )


print("-" * 122)

print(
    f"Models                 : "
    f"{len(MODEL_REGISTRY)}"
)

print(
    f"Controlled baselines   : "
    f"{len(CONTROLLED_MODELS)}"
)

print(
    f"Published AMP methods  : "
    f"{len(PUBLISHED_MODELS)}"
)

print(
    f"Seeds                  : "
    f"{EXPECTED_SEEDS}"
)

print(
    "Seed tuning            : FALSE"
)

print(
    "Data resplitting       : FALSE"
)

print(
    "Training started       : FALSE"
)

print("-" * 122)

print(
    "FINAL MODEL REGISTRY"
)

print(
    model_registry_df[
        [
            "model_no",
            "display_name",
            "group",
            "family",
            "execution_environment",
            "implementation_status",
        ]
    ].to_string(
        index=False
    )
)

print("-" * 122)

print(
    "EXECUTION COUNTS"
)

print(
    f"Protocol 1 training runs : "
    f"{N_PROTOCOL1_TRAIN_RUNS}"
)

print(
    f"Protocol 2 evaluations   : "
    f"{N_PROTOCOL2_EXTERNAL_EVALS}"
)

print(
    "Protocol 2 extra training: 0"
)

print("-" * 122)

print(
    "PUBLISHED-METHOD RULE:"
)

print(
    "Repeated inference from one fixed pretrained "
    "model DOES NOT count as 10 independent runs."
)

print(
    "Deterministic retraining may legitimately "
    "produce SD = 0."
)

print("-" * 122)

print(
    "HYPERPARAMETERS : NOT YET LOCKED"
)

print(
    "METRICS         : NOT YET LOCKED"
)

print(
    "THRESHOLD RULE  : NOT YET LOCKED"
)

print(
    "NO MODEL TRAINING IN CELL 11"
)

print("-" * 122)

print(
    f"Registry CSV    : "
    f"{MODEL_REGISTRY_CSV_PATH}"
)

print(
    f"Registry JSON   : "
    f"{MODEL_REGISTRY_JSON_PATH}"
)

print(
    f"Registry SHA256 : "
    f"{REGISTRY_SHA256}"
)

print(
    f"Contract JSON   : "
    f"{EXECUTION_CONTRACT_PATH}"
)

print(
    f"Contract SHA256 : "
    f"{CONTRACT_SHA256}"
)

print("=" * 122)

==========================================================================================================================
CELL 11 PASS - FINAL 17-MODEL REGISTRY AND EXECUTION CONTRACT LOCKED
==========================================================================================================================
FINAL BENCHMARK:
  1. GenPept_Curated_2025
  2. External_Benchmark_1
  3. AMPlify_balanced
  4. External_Benchmark_3
--------------------------------------------------------------------------------------------------------------------------
Models                 : 17
Controlled baselines   : 10
Published AMP methods  : 7
Seeds                  : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
Seed tuning            : FALSE
Data resplitting       : FALSE
Training started       : FALSE
--------------------------------------------------------------------------------------------------------------------------
FINAL MODEL REGISTRY
 model_no            display_name                group              family            execution_environment         implementation_status
        1     Logistic Regression  controlled_baseline        classical_ml                           master                         READY
        2 Linear SVM (Calibrated)  controlled_baseline        classical_ml                           master                         READY
        3           Random Forest  controlled_baseline        classical_ml                           master                         READY
        4             Extra Trees  controlled_baseline        classical_ml                           master                         READY
        5    HistGradientBoosting  controlled_baseline        classical_ml                           master                         READY
        6                LightGBM  controlled_baseline        classical_ml                           master                         READY
        7                  1D-CNN  controlled_baseline       deep_learning                           master                         READY
        8                  BiLSTM  controlled_baseline       deep_learning                           master                         READY
        9        BiLSTM-Attention  controlled_baseline       deep_learning                           master                         READY
       10     Transformer Encoder  controlled_baseline       deep_learning                           master                         READY
       11                   AmPEP published_amp_method published_predictor              separate_or_adapter IMPLEMENTATION_AUDIT_REQUIRED
       12            AMPScannerV2 published_amp_method published_predictor              separate_or_adapter IMPLEMENTATION_AUDIT_REQUIRED
       13                 AmpGram published_amp_method published_predictor modern_faithful_reimplementation                ROUTE_PREPARED
       14                   ampir published_amp_method published_predictor                 genpept_r_models                ROUTE_PREPARED
       15                 amPEPpy published_amp_method published_predictor              separate_or_adapter IMPLEMENTATION_AUDIT_REQUIRED
       16                  AI4AMP published_amp_method published_predictor              separate_or_adapter IMPLEMENTATION_AUDIT_REQUIRED
       17                 AMPlify published_amp_method published_predictor              separate_or_adapter IMPLEMENTATION_AUDIT_REQUIRED
--------------------------------------------------------------------------------------------------------------------------
EXECUTION COUNTS
Protocol 1 training runs : 680
Protocol 2 evaluations   : 2040
Protocol 2 extra training: 0
--------------------------------------------------------------------------------------------------------------------------
PUBLISHED-METHOD RULE:
Repeated inference from one fixed pretrained model DOES NOT count as 10 independent runs.
Deterministic retraining may legitimately produce SD = 0.
--------------------------------------------------------------------------------------------------------------------------
HYPERPARAMETERS : NOT YET LOCKED
METRICS         : NOT YET LOCKED
THRESHOLD RULE  : NOT YET LOCKED
NO MODEL TRAINING IN CELL 11
--------------------------------------------------------------------------------------------------------------------------
Registry CSV    : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_FINAL_model_registry.csv
Registry JSON   : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_model_registry.json
Registry SHA256 : a7062c153dd8bda9504b78f6a88bf059a5263057e9d173ebff0f07aa3e262339
Contract JSON   : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_execution_contract.json
Contract SHA256 : 1a6653964844ed0c6b0de195bf8297093e79c65a8d63c85fcf2b698c2157d485
==========================================================================================================================

In [2]:
# ============================================================
# CELL 12 - RESTART-SAFE
# METRICS, THRESHOLD, STATISTICS &
# HYPERPARAMETER POLICY LOCK
#
# Safe after:
# - PC reboot
# - VS Code restart
# - Jupyter kernel restart
#
# DOES NOT require Cells 1-11 to exist in RAM.
# Reads the authoritative state FROM DISK.
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json

import numpy as np
import pandas as pd

from scipy.stats import t as student_t

from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    balanced_accuracy_score,
    brier_score_loss,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    roc_auc_score,
)


# ============================================================
# 1. RESTORE PROJECT STATE FROM DISK
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

SPLIT_DIR = (
    OUTPUT_ROOT
    / "splits"
)


assert PROJECT_ROOT.is_dir(), (
    "PROJECT_ROOT does not exist:\n"
    f"{PROJECT_ROOT}"
)

assert OUTPUT_ROOT.is_dir(), (
    "benchmark17_outputs does not exist:\n"
    f"{OUTPUT_ROOT}"
)

assert AUDIT_DIR.is_dir(), (
    f"AUDIT_DIR missing:\n{AUDIT_DIR}"
)

assert MANIFEST_DIR.is_dir(), (
    f"MANIFEST_DIR missing:\n{MANIFEST_DIR}"
)

assert SPLIT_DIR.is_dir(), (
    f"SPLIT_DIR missing:\n{SPLIT_DIR}"
)


# ============================================================
# 2. AUTHORITATIVE MANIFESTS FROM CELLS 10-11
# ============================================================

FINAL_BENCHMARK_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark4_FINAL_v1_manifest.json"
)

MODEL_REGISTRY_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_model_registry.json"
)

EXECUTION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_execution_contract.json"
)


required_files = [
    FINAL_BENCHMARK_MANIFEST_PATH,
    MODEL_REGISTRY_PATH,
    EXECUTION_CONTRACT_PATH,
]


for path in required_files:

    assert path.is_file(), (
        "Required locked artifact missing:\n"
        f"{path}\n\n"
        "Do NOT recreate it automatically. "
        "Verify Cells 10-11 outputs first."
    )


# ============================================================
# 3. LOAD LOCKED STATE
# ============================================================

with open(
    FINAL_BENCHMARK_MANIFEST_PATH,
    "r",
    encoding="utf-8",
) as f:

    benchmark_manifest = json.load(f)


with open(
    MODEL_REGISTRY_PATH,
    "r",
    encoding="utf-8",
) as f:

    model_registry_manifest = json.load(f)


with open(
    EXECUTION_CONTRACT_PATH,
    "r",
    encoding="utf-8",
) as f:

    execution_manifest = json.load(f)


# ============================================================
# 4. RESTORE DATASETS AND SEEDS
# ============================================================

EXPECTED_DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "AMPlify_balanced",
    "External_Benchmark_3",
]


SEEDS = list(
    benchmark_manifest[
        "model_seeds"
    ]
)


EXPECTED_SEEDS = list(
    range(100, 110)
)


assert SEEDS == EXPECTED_SEEDS, (
    "Locked seed set on disk has changed.\n"
    f"Expected: {EXPECTED_SEEDS}\n"
    f"Found   : {SEEDS}"
)


assert (
    benchmark_manifest[
        "datasets"
    ]
    == EXPECTED_DATASETS
), (
    "Final dataset registry on disk changed."
)


assert (
    benchmark_manifest[
        "status"
    ]
    == "FINAL_DATA_LOCK_BEFORE_MODEL_TRAINING"
)


assert (
    benchmark_manifest[
        "seed_tuning"
    ]
    is False
)


assert (
    benchmark_manifest[
        "data_resplitting_per_model_seed"
    ]
    is False
)


assert (
    benchmark_manifest[
        "protocol_2"
    ][
        "n_directional_pairs"
    ]
    == 12
)


assert (
    benchmark_manifest[
        "protocol_2"
    ][
        "residual_exact_overlap_all_pairs"
    ]
    == 0
)


# ============================================================
# 5. VERIFY CELL 11 MODEL LOCK
# ============================================================

assert (
    model_registry_manifest[
        "status"
    ]
    == "MODEL_LIST_LOCKED_BEFORE_TRAINING"
)


assert (
    model_registry_manifest[
        "n_models"
    ]
    == 17
)


assert (
    model_registry_manifest[
        "n_controlled"
    ]
    == 10
)


assert (
    model_registry_manifest[
        "n_published"
    ]
    == 7
)


assert (
    model_registry_manifest[
        "training_started"
    ]
    is False
)


assert (
    execution_manifest[
        "status"
    ]
    == "EXECUTION_CONTRACT_LOCKED_BEFORE_TRAINING"
)


assert (
    execution_manifest[
        "contract"
    ][
        "seeds"
    ]
    == EXPECTED_SEEDS
)


assert (
    execution_manifest[
        "contract"
    ][
        "protocol_1"
    ][
        "training_runs"
    ]
    == 680
)


assert (
    execution_manifest[
        "contract"
    ][
        "protocol_2"
    ][
        "external_evaluations"
    ]
    == 2040
)


# ============================================================
# 6. VERIFY FINAL COHORT FILE ITSELF
# ============================================================

FINAL_COHORT_PATH = Path(
    benchmark_manifest[
        "final_cohort"
    ][
        "path"
    ]
)


EXPECTED_FINAL_COHORT_SHA256 = (
    benchmark_manifest[
        "final_cohort"
    ][
        "sha256"
    ]
)


assert FINAL_COHORT_PATH.is_file(), (
    "Final benchmark cohort missing:\n"
    f"{FINAL_COHORT_PATH}"
)


def sha256_file_cell12(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda: f.read(
                1024 * 1024
            ),
            b"",
        ):

            h.update(chunk)

    return h.hexdigest()


OBSERVED_FINAL_COHORT_SHA256 = (
    sha256_file_cell12(
        FINAL_COHORT_PATH
    )
)


assert (
    OBSERVED_FINAL_COHORT_SHA256
    ==
    EXPECTED_FINAL_COHORT_SHA256
), (
    "FINAL cohort SHA256 mismatch.\n"
    "The locked dataset may have changed."
)


# ============================================================
# 7. METRIC REGISTRY
#
# Primary:
#   AUROC
#   AUPRC
#   MCC
#
# AUPRC = Average Precision
# ============================================================

METRIC_REGISTRY = [

    {
        "metric": "AUROC",
        "category": "threshold_free",
        "primary": True,
        "higher_is_better": True,
        "definition": "roc_auc_score",
    },

    {
        "metric": "AUPRC",
        "category": "threshold_free",
        "primary": True,
        "higher_is_better": True,
        "definition": "average_precision_score",
    },

    {
        "metric": "MCC",
        "category": "threshold_dependent",
        "primary": True,
        "higher_is_better": True,
        "definition":
            "matthews_corrcoef_at_frozen_validation_threshold",
    },

    {
        "metric": "BACC",
        "category": "threshold_dependent",
        "primary": False,
        "higher_is_better": True,
        "definition": "balanced_accuracy_score",
    },

    {
        "metric": "F1",
        "category": "threshold_dependent",
        "primary": False,
        "higher_is_better": True,
        "definition":
            "binary_F1_positive_class_AMP",
    },

    {
        "metric": "ACC",
        "category": "threshold_dependent",
        "primary": False,
        "higher_is_better": True,
        "definition": "accuracy_score",
    },

    {
        "metric": "Sensitivity",
        "category": "threshold_dependent",
        "primary": False,
        "higher_is_better": True,
        "definition":
            "TP_divided_by_TP_plus_FN",
    },

    {
        "metric": "Specificity",
        "category": "threshold_dependent",
        "primary": False,
        "higher_is_better": True,
        "definition":
            "TN_divided_by_TN_plus_FP",
    },

    {
        "metric": "Brier",
        "category": "calibration",
        "primary": False,
        "higher_is_better": False,
        "definition":
            "mean_squared_probability_error",
    },

    {
        "metric": "ECE10",
        "category": "calibration",
        "primary": False,
        "higher_is_better": False,
        "definition":
            "expected_calibration_error_10_equal_width_bins",
    },
]


metric_registry_df = pd.DataFrame(
    METRIC_REGISTRY
)


assert len(
    metric_registry_df
) == 10


assert (
    metric_registry_df[
        "metric"
    ].nunique()
    == 10
)


PRIMARY_METRICS = [
    "AUROC",
    "AUPRC",
    "MCC",
]


assert (
    metric_registry_df[
        metric_registry_df[
            "primary"
        ]
    ][
        "metric"
    ].tolist()
    == PRIMARY_METRICS
)


# ============================================================
# 8. SCORE CONTRACT
# ============================================================

SCORE_CONTRACT = {

    "positive_class":
        "AMP",

    "positive_label":
        1,

    "negative_class":
        "non_AMP",

    "negative_label":
        0,

    "score_semantics":
        "estimated_score_or_probability_for_AMP",

    "required_score_range":
        [0.0, 1.0],

    "higher_score_means":
        "more_likely_AMP",

    "hard_label_rule":
        "y_pred = 1 if y_score >= tau else 0",

    "nan_scores_allowed":
        False,

    "infinite_scores_allowed":
        False,
}


# ============================================================
# 9. ECE DEFINITION
# ============================================================

ECE_N_BINS = 10


def binary_ece(
    y_true,
    y_score,
    n_bins=ECE_N_BINS,
):

    y_true = np.asarray(
        y_true,
        dtype=int,
    )

    y_score = np.asarray(
        y_score,
        dtype=float,
    )


    assert (
        len(y_true)
        == len(y_score)
    )

    assert len(y_true) > 0

    assert np.isfinite(
        y_score
    ).all()

    assert (
        (y_score >= 0.0)
        &
        (y_score <= 1.0)
    ).all()


    edges = np.linspace(
        0.0,
        1.0,
        n_bins + 1,
    )


    ece = 0.0

    n_total = len(
        y_true
    )


    for i in range(
        n_bins
    ):

        left = edges[i]
        right = edges[i + 1]


        if i < (
            n_bins - 1
        ):

            mask = (
                (y_score >= left)
                &
                (y_score < right)
            )

        else:

            mask = (
                (y_score >= left)
                &
                (y_score <= right)
            )


        n_bin = int(
            mask.sum()
        )


        if n_bin == 0:
            continue


        observed_fraction = float(
            y_true[
                mask
            ].mean()
        )


        mean_probability = float(
            y_score[
                mask
            ].mean()
        )


        ece += (
            n_bin
            / n_total
        ) * abs(
            observed_fraction
            - mean_probability
        )


    return float(ece)


# ============================================================
# 10. VALIDATION-ONLY THRESHOLD SELECTION
#
# tau* = threshold maximizing MCC
#
# Ties:
# 1. higher MCC
# 2. higher BACC
# 3. higher F1
# 4. closest to 0.5
# 5. lower threshold
# ============================================================

THRESHOLD_OBJECTIVE = (
    "validation_MCC"
)


def select_validation_threshold(
    y_true,
    y_score,
):

    y_true = np.asarray(
        y_true,
        dtype=int,
    )

    y_score = np.asarray(
        y_score,
        dtype=float,
    )


    assert (
        len(y_true)
        == len(y_score)
    )

    assert len(y_true) > 0


    assert set(
        np.unique(
            y_true
        ).tolist()
    ) == {
        0,
        1,
    }


    assert np.isfinite(
        y_score
    ).all()


    assert (
        (y_score >= 0.0)
        &
        (y_score <= 1.0)
    ).all()


    unique_scores = np.unique(
        y_score
    )


    if len(
        unique_scores
    ) >= 2:

        midpoints = (
            unique_scores[:-1]
            +
            unique_scores[1:]
        ) / 2.0

    else:

        midpoints = np.array(
            [],
            dtype=float,
        )


    candidates = np.unique(
        np.concatenate(
            [
                np.array(
                    [
                        0.0,
                        0.5,
                        1.0,
                    ],
                    dtype=float,
                ),
                unique_scores,
                midpoints,
            ]
        )
    )


    candidates = candidates[
        (
            candidates >= 0.0
        )
        &
        (
            candidates <= 1.0
        )
    ]


    rows = []


    for tau in candidates:

        y_pred = (
            y_score
            >= tau
        ).astype(int)


        mcc = float(
            matthews_corrcoef(
                y_true,
                y_pred,
            )
        )


        bacc = float(
            balanced_accuracy_score(
                y_true,
                y_pred,
            )
        )


        f1 = float(
            f1_score(
                y_true,
                y_pred,
                zero_division=0,
            )
        )


        rows.append(
            {
                "tau":
                    float(tau),

                "MCC":
                    mcc,

                "BACC":
                    bacc,

                "F1":
                    f1,

                "distance_to_0_5":
                    abs(
                        float(tau)
                        - 0.5
                    ),
            }
        )


    threshold_table = (
        pd.DataFrame(
            rows
        )
        .sort_values(
            [
                "MCC",
                "BACC",
                "F1",
                "distance_to_0_5",
                "tau",
            ],
            ascending=[
                False,
                False,
                False,
                True,
                True,
            ],
            kind="mergesort",
        )
        .reset_index(
            drop=True
        )
    )


    best = (
        threshold_table
        .iloc[0]
    )


    return {

        "tau":
            float(
                best["tau"]
            ),

        "validation_MCC":
            float(
                best["MCC"]
            ),

        "validation_BACC":
            float(
                best["BACC"]
            ),

        "validation_F1":
            float(
                best["F1"]
            ),

        "n_threshold_candidates":
            int(
                len(
                    threshold_table
                )
            ),
    }


# ============================================================
# 11. CANONICAL METRIC FUNCTION
# ============================================================

def compute_binary_metrics(
    y_true,
    y_score,
    tau,
):

    y_true = np.asarray(
        y_true,
        dtype=int,
    )

    y_score = np.asarray(
        y_score,
        dtype=float,
    )


    assert (
        len(y_true)
        == len(y_score)
    )

    assert len(y_true) > 0


    assert set(
        np.unique(
            y_true
        ).tolist()
    ) == {
        0,
        1,
    }


    assert np.isfinite(
        y_score
    ).all()


    assert (
        (y_score >= 0.0)
        &
        (y_score <= 1.0)
    ).all()


    assert (
        0.0
        <= float(tau)
        <= 1.0
    )


    y_pred = (
        y_score
        >= float(tau)
    ).astype(int)


    tn, fp, fn, tp = (
        confusion_matrix(
            y_true,
            y_pred,
            labels=[
                0,
                1,
            ],
        )
        .ravel()
    )


    sensitivity = (
        tp
        / (
            tp + fn
        )
    )


    specificity = (
        tn
        / (
            tn + fp
        )
    )


    return {

        "AUROC":
            float(
                roc_auc_score(
                    y_true,
                    y_score,
                )
            ),

        "AUPRC":
            float(
                average_precision_score(
                    y_true,
                    y_score,
                )
            ),

        "MCC":
            float(
                matthews_corrcoef(
                    y_true,
                    y_pred,
                )
            ),

        "BACC":
            float(
                balanced_accuracy_score(
                    y_true,
                    y_pred,
                )
            ),

        "F1":
            float(
                f1_score(
                    y_true,
                    y_pred,
                    zero_division=0,
                )
            ),

        "ACC":
            float(
                accuracy_score(
                    y_true,
                    y_pred,
                )
            ),

        "Sensitivity":
            float(
                sensitivity
            ),

        "Specificity":
            float(
                specificity
            ),

        "Brier":
            float(
                brier_score_loss(
                    y_true,
                    y_score,
                )
            ),

        "ECE10":
            float(
                binary_ece(
                    y_true,
                    y_score,
                    n_bins=10,
                )
            ),

        "threshold":
            float(
                tau
            ),

        "TP":
            int(tp),

        "TN":
            int(tn),

        "FP":
            int(fp),

        "FN":
            int(fn),

        "n":
            int(
                len(
                    y_true
                )
            ),

        "n_positive":
            int(
                (
                    y_true == 1
                ).sum()
            ),

        "n_negative":
            int(
                (
                    y_true == 0
                ).sum()
            ),
    }


# ============================================================
# 12. THRESHOLD POLICY
# ============================================================

THRESHOLD_POLICY = {

    "primary_threshold_name":
        "tau_star",

    "selection_dataset":
        "source_validation_only",

    "optimization_objective":
        "maximize_MCC",

    "prediction_rule":
        "AMP_if_score_greater_than_or_equal_to_tau_star",

    "tie_breaking_order": [
        "higher_validation_MCC",
        "higher_validation_BACC",
        "higher_validation_F1",
        "closest_to_0.5",
        "lower_threshold",
    ],

    "protocol_1": {

        "select_on":
            "dataset_validation",

        "apply_unchanged_to":
            "same_dataset_test",
    },

    "protocol_2": {

        "select_on":
            "source_validation",

        "apply_unchanged_to":
            "all_decontaminated_target_test_sets",

        "target_threshold_optimization":
            False,

        "target_threshold_recalibration":
            False,
    },

    "test_based_threshold_selection":
        False,

    "external_target_based_threshold_selection":
        False,

    "threshold_selected_separately_per_seed":
        True,
}


# ============================================================
# 13. STATISTICAL POLICY
# ============================================================

N_RUNS = 10

SAMPLE_SD_DDOF = 1


T_CRITICAL_95_DF9 = float(
    student_t.ppf(
        0.975,
        df=N_RUNS - 1,
    )
)


STATISTICAL_POLICY = {

    "n_runs":
        N_RUNS,

    "required_seed_set":
        EXPECTED_SEEDS,

    "complete_seed_set_required":
        True,

    "partial_group_aggregation_allowed":
        False,

    "seed_tuning":
        False,

    "seed_replacement":
        False,

    "data_resplitting":
        False,

    "summary_statistics": [
        "mean",
        "sample_standard_deviation",
        "standard_error",
        "95_percent_student_t_CI_of_seed_mean",
    ],

    "sample_sd_ddof":
        SAMPLE_SD_DDOF,

    "ci_method":
        "Student_t_across_10_run_values",

    "ci_df":
        9,

    "ci_confidence_level":
        0.95,

    "ci_t_critical":
        T_CRITICAL_95_DF9,

    "bootstrap":
        False,

    "deterministic_model_policy":
        (
            "If all 10 legitimate retraining runs "
            "are numerically identical, report SD=0. "
            "Do not replace seeds."
        ),

    "protocol_1_grouping": [
        "model",
        "dataset",
    ],

    "protocol_2_grouping": [
        "model",
        "source_dataset",
        "target_dataset",
    ],

    "support_reporting_required":
        True,

    "support_fields": [
        "n",
        "n_positive",
        "n_negative",
    ],
}


# ============================================================
# 14. CANONICAL 10-RUN AGGREGATOR
# ============================================================

def summarize_ten_runs(
    values,
):

    values = np.asarray(
        values,
        dtype=float,
    )


    assert len(
        values
    ) == 10, (
        "Exactly 10 run values required."
    )


    assert np.isfinite(
        values
    ).all()


    mean_value = float(
        np.mean(
            values
        )
    )


    sd_value = float(
        np.std(
            values,
            ddof=1,
        )
    )


    se_value = float(
        sd_value
        / np.sqrt(
            len(
                values
            )
        )
    )


    margin = float(
        T_CRITICAL_95_DF9
        * se_value
    )


    return {

        "mean":
            mean_value,

        "sd":
            sd_value,

        "se":
            se_value,

        "ci95_low":
            mean_value
            - margin,

        "ci95_high":
            mean_value
            + margin,
    }


# ============================================================
# 15. HYPERPARAMETER SELECTION POLICY
# ============================================================

HYPERPARAMETER_POLICY = {

    "status":
        "SELECTION_RULE_LOCKED_VALUES_PENDING",

    "test_data_for_hyperparameters":
        False,

    "cross_dataset_target_for_hyperparameters":
        False,

    "seed_cherry_picking":
        False,

    "default_strategy":
        "predeclared_fixed_configuration",

    "controlled_baselines": {

        "policy":
            (
                "Hyperparameters are specified before "
                "benchmark results and then kept fixed "
                "for the complete benchmark."
            ),

        "test_guided_tuning":
            False,

        "external_target_guided_tuning":
            False,
    },

    "published_methods": {

        "primary_policy":
            (
                "Use architecture, representation and "
                "training settings reported by the "
                "published method or official implementation "
                "whenever reproducible."
            ),

        "implementation_adaptation":
            (
                "Any unavoidable adaptation must be "
                "documented and frozen before benchmark "
                "performance is inspected."
            ),

        "test_guided_tuning":
            False,

        "external_target_guided_tuning":
            False,
    },

    "fallback_search_if_unavoidable": {

        "allowed":
            True,

        "must_be_declared_before_search":
            True,

        "data_scope":
            "source_train_and_source_validation_only",

        "selection_metric":
            "validation_AUPRC",

        "tie_breaker_1":
            "validation_AUROC",

        "tie_breaker_2":
            "lower_model_complexity",

        "test_access":
            False,

        "external_target_access":
            False,

        "reported_as_final_10_runs":
            False,
    },

    "validation_allowed_uses": [
        "early_stopping_when_model_requires_it",
        "hyperparameter_selection_only_if_predeclared",
        "tau_star_selection",
    ],

    "test_allowed_uses": [
        "final_locked_evaluation_only",
    ],
}


# ============================================================
# 16. REPORTING POLICY
# ============================================================

REPORTING_POLICY = {

    "primary_metrics": [
        "AUROC",
        "AUPRC",
        "MCC",
    ],

    "secondary_metrics": [
        "BACC",
        "F1",
        "ACC",
        "Sensitivity",
        "Specificity",
    ],

    "calibration_metrics": [
        "Brier",
        "ECE10",
    ],

    "required_confusion_counts": [
        "TP",
        "TN",
        "FP",
        "FN",
    ],

    "required_operating_threshold":
        "tau_star",

    "main_table_format":
        "mean_plus_or_minus_sample_SD",

    "CI_reporting":
        "95_percent_t_CI_across_10_runs",

    "cross_dataset_class_support_must_be_shown":
        True,

    "cross_dataset_removed_overlap_must_be_shown":
        True,

    "single_accuracy_only_claims_allowed":
        False,

    "AUPRC_definition":
        "Average Precision",

    "positive_class":
        "AMP",
}


# ============================================================
# 17. BUILD EVALUATION CONTRACT
# ============================================================

EVALUATION_CONTRACT = {

    "schema_version":
        "1.1",

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "status":
        "LOCKED_BEFORE_MODEL_TRAINING",

    "restart_safe":
        True,

    "state_source":
        "persisted_disk_manifests",

    "datasets":
        EXPECTED_DATASETS,

    "model_seeds":
        EXPECTED_SEEDS,

    "metric_registry":
        METRIC_REGISTRY,

    "score_contract":
        SCORE_CONTRACT,

    "threshold_policy":
        THRESHOLD_POLICY,

    "statistical_policy":
        STATISTICAL_POLICY,

    "hyperparameter_policy":
        HYPERPARAMETER_POLICY,

    "reporting_policy":
        REPORTING_POLICY,

    "training_started":
        False,
}


# ============================================================
# 18. SELF-TEST METRIC DEFINITIONS
# ============================================================

_self_y = np.array(
    [
        0,
        0,
        0,
        1,
        1,
        1,
    ],
    dtype=int,
)


_self_score = np.array(
    [
        0.05,
        0.15,
        0.25,
        0.75,
        0.85,
        0.95,
    ],
    dtype=float,
)


_self_threshold = (
    select_validation_threshold(
        _self_y,
        _self_score,
    )
)


_self_metrics = (
    compute_binary_metrics(
        _self_y,
        _self_score,
        _self_threshold[
            "tau"
        ],
    )
)


for metric in [
    "AUROC",
    "AUPRC",
    "MCC",
    "BACC",
    "F1",
    "ACC",
    "Sensitivity",
    "Specificity",
]:

    assert np.isclose(
        _self_metrics[
            metric
        ],
        1.0,
    ), (
        f"Metric self-test failed: {metric}"
    )


assert (
    0.0
    <= _self_metrics[
        "Brier"
    ]
    <= 1.0
)


assert (
    0.0
    <= _self_metrics[
        "ECE10"
    ]
    <= 1.0
)


# ============================================================
# 19. SELF-TEST 10-RUN STATISTICS
# ============================================================

_self_runs = np.array(
    [
        0.80,
        0.81,
        0.82,
        0.83,
        0.84,
        0.85,
        0.86,
        0.87,
        0.88,
        0.89,
    ],
    dtype=float,
)


_self_summary = (
    summarize_ten_runs(
        _self_runs
    )
)


assert np.isclose(
    _self_summary[
        "mean"
    ],
    0.845,
)


assert (
    _self_summary[
        "sd"
    ] > 0
)


assert (
    _self_summary[
        "ci95_low"
    ]
    <
    _self_summary[
        "mean"
    ]
    <
    _self_summary[
        "ci95_high"
    ]
)


# ============================================================
# 20. OUTPUT PATHS
# ============================================================

METRIC_REGISTRY_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_metric_registry.csv"
)


EVALUATION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_evaluation_contract.json"
)


THRESHOLD_POLICY_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_threshold_policy.json"
)


STATISTICAL_POLICY_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_statistical_policy.json"
)


HYPERPARAMETER_POLICY_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_hyperparameter_policy.json"
)


# ============================================================
# 21. SAVE TO DISK
# ============================================================

metric_registry_df.to_csv(
    METRIC_REGISTRY_PATH,
    index=False,
)


with open(
    EVALUATION_CONTRACT_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        EVALUATION_CONTRACT,
        f,
        indent=2,
        ensure_ascii=False,
    )


with open(
    THRESHOLD_POLICY_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        THRESHOLD_POLICY,
        f,
        indent=2,
        ensure_ascii=False,
    )


with open(
    STATISTICAL_POLICY_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        STATISTICAL_POLICY,
        f,
        indent=2,
        ensure_ascii=False,
    )


with open(
    HYPERPARAMETER_POLICY_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        HYPERPARAMETER_POLICY,
        f,
        indent=2,
        ensure_ascii=False,
    )


EVALUATION_CONTRACT_SHA256 = (
    sha256_file_cell12(
        EVALUATION_CONTRACT_PATH
    )
)


# ============================================================
# 22. RE-READ FROM DISK
# ============================================================

with open(
    EVALUATION_CONTRACT_PATH,
    "r",
    encoding="utf-8",
) as f:

    evaluation_check = json.load(f)


assert (
    evaluation_check[
        "status"
    ]
    == "LOCKED_BEFORE_MODEL_TRAINING"
)


assert (
    evaluation_check[
        "restart_safe"
    ]
    is True
)


assert (
    evaluation_check[
        "training_started"
    ]
    is False
)


assert (
    evaluation_check[
        "model_seeds"
    ]
    == EXPECTED_SEEDS
)


assert (
    evaluation_check[
        "reporting_policy"
    ][
        "primary_metrics"
    ]
    == [
        "AUROC",
        "AUPRC",
        "MCC",
    ]
)


assert (
    evaluation_check[
        "threshold_policy"
    ][
        "optimization_objective"
    ]
    == "maximize_MCC"
)


assert (
    evaluation_check[
        "threshold_policy"
    ][
        "test_based_threshold_selection"
    ]
    is False
)


assert (
    evaluation_check[
        "threshold_policy"
    ][
        "external_target_based_threshold_selection"
    ]
    is False
)


assert (
    evaluation_check[
        "statistical_policy"
    ][
        "n_runs"
    ]
    == 10
)


assert (
    evaluation_check[
        "statistical_policy"
    ][
        "bootstrap"
    ]
    is False
)


# ============================================================
# 23. FINAL HARD ASSERTIONS
# ============================================================

assert METRIC_REGISTRY_PATH.exists()

assert EVALUATION_CONTRACT_PATH.exists()

assert THRESHOLD_POLICY_PATH.exists()

assert STATISTICAL_POLICY_PATH.exists()

assert HYPERPARAMETER_POLICY_PATH.exists()


assert N_RUNS == 10

assert SAMPLE_SD_DDOF == 1

assert SEEDS == [
    100,
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    108,
    109,
]


# ============================================================
# 24. REPORT
# ============================================================

print("=" * 124)

print(
    "CELL 12 PASS - RESTART-SAFE EVALUATION "
    "CONTRACT RESTORED AND LOCKED"
)

print("=" * 124)


print(
    f"PROJECT ROOT          : {PROJECT_ROOT}"
)

print(
    "STATE SOURCE          : DISK MANIFESTS"
)

print(
    "CELLS 1-11 IN RAM     : NOT REQUIRED"
)

print(
    f"FINAL COHORT SHA256   : "
    f"{OBSERVED_FINAL_COHORT_SHA256}"
)

print("-" * 124)


print(
    "DATASETS:"
)

for i, dataset_name in enumerate(
    EXPECTED_DATASETS,
    start=1,
):

    print(
        f"  {i}. {dataset_name}"
    )


print("-" * 124)


print(
    "PRIMARY METRICS       : "
    "AUROC / AUPRC / MCC"
)

print(
    "SECONDARY METRICS     : "
    "BACC / F1 / ACC / Sensitivity / Specificity"
)

print(
    "CALIBRATION METRICS   : "
    "Brier / ECE10"
)

print(
    "AUPRC DEFINITION      : "
    "AVERAGE PRECISION"
)

print(
    "POSITIVE CLASS        : AMP = 1"
)

print("-" * 124)


print(
    "THRESHOLD POLICY"
)

print(
    "tau* selected on      : SOURCE VALIDATION ONLY"
)

print(
    "tau* objective        : MAXIMIZE MCC"
)

print(
    "Protocol 1 apply to   : SAME-DATASET TEST"
)

print(
    "Protocol 2 apply to   : EXTERNAL TARGET TESTS UNCHANGED"
)

print(
    "Target threshold tune : FALSE"
)

print(
    "Test threshold tune   : FALSE"
)

print("-" * 124)


print(
    "STATISTICAL POLICY"
)

print(
    f"Runs                   : {N_RUNS}"
)

print(
    f"Seeds                  : {SEEDS}"
)

print(
    "Summary               : MEAN +/- SAMPLE SD"
)

print(
    "Sample SD             : ddof=1"
)

print(
    "95% CI                : STUDENT-t ACROSS 10 RUNS"
)

print(
    f"t critical (df=9)      : "
    f"{T_CRITICAL_95_DF9:.6f}"
)

print(
    "Bootstrap             : FALSE"
)

print(
    "Incomplete seed set   : MUST NOT BE AGGREGATED"
)

print(
    "Deterministic SD=0    : ALLOWED"
)

print("-" * 124)


print(
    "HYPERPARAMETER POLICY"
)

print(
    "Default               : PREDECLARED FIXED CONFIGURATION"
)

print(
    "Published methods     : PUBLISHED/OFFICIAL SETTINGS FIRST"
)

print(
    "Test-guided tuning    : FALSE"
)

print(
    "Target-guided tuning  : FALSE"
)

print(
    "Seed cherry-picking   : FALSE"
)

print("-" * 124)


print(
    "SELF TEST"
)

print(
    f"Synthetic tau*        : "
    f"{_self_threshold['tau']:.6f}"
)

print(
    "Metric implementation : PASS"
)

print(
    "10-run aggregation    : PASS"
)

print(
    "MODEL TRAINING        : FALSE"
)

print("-" * 124)


print(
    f"Metric registry       : "
    f"{METRIC_REGISTRY_PATH}"
)

print(
    f"Evaluation contract   : "
    f"{EVALUATION_CONTRACT_PATH}"
)

print(
    f"Evaluation SHA256     : "
    f"{EVALUATION_CONTRACT_SHA256}"
)

print(
    f"Threshold policy      : "
    f"{THRESHOLD_POLICY_PATH}"
)

print(
    f"Statistical policy    : "
    f"{STATISTICAL_POLICY_PATH}"
)

print(
    f"Hyperparameter policy : "
    f"{HYPERPARAMETER_POLICY_PATH}"
)

print("=" * 124)

============================================================================================================================
CELL 12 PASS - RESTART-SAFE EVALUATION CONTRACT RESTORED AND LOCKED
============================================================================================================================
PROJECT ROOT          : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026
STATE SOURCE          : DISK MANIFESTS
CELLS 1-11 IN RAM     : NOT REQUIRED
FINAL COHORT SHA256   : 205f292511f77ca7a3b9f0b2fd03549be60e9df29a62ce3b0b504f63935ad356
----------------------------------------------------------------------------------------------------------------------------
DATASETS:
  1. GenPept_Curated_2025
  2. External_Benchmark_1
  3. AMPlify_balanced
  4. External_Benchmark_3
----------------------------------------------------------------------------------------------------------------------------
PRIMARY METRICS       : AUROC / AUPRC / MCC
SECONDARY METRICS     : BACC / F1 / ACC / Sensitivity / Specificity
CALIBRATION METRICS   : Brier / ECE10
AUPRC DEFINITION      : AVERAGE PRECISION
POSITIVE CLASS        : AMP = 1
----------------------------------------------------------------------------------------------------------------------------
THRESHOLD POLICY
tau* selected on      : SOURCE VALIDATION ONLY
tau* objective        : MAXIMIZE MCC
Protocol 1 apply to   : SAME-DATASET TEST
Protocol 2 apply to   : EXTERNAL TARGET TESTS UNCHANGED
Target threshold tune : FALSE
Test threshold tune   : FALSE
----------------------------------------------------------------------------------------------------------------------------
STATISTICAL POLICY
Runs                   : 10
Seeds                  : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
Summary               : MEAN +/- SAMPLE SD
Sample SD             : ddof=1
95% CI                : STUDENT-t ACROSS 10 RUNS
t critical (df=9)      : 2.262157
Bootstrap             : FALSE
Incomplete seed set   : MUST NOT BE AGGREGATED
Deterministic SD=0    : ALLOWED
----------------------------------------------------------------------------------------------------------------------------
HYPERPARAMETER POLICY
Default               : PREDECLARED FIXED CONFIGURATION
Published methods     : PUBLISHED/OFFICIAL SETTINGS FIRST
Test-guided tuning    : FALSE
Target-guided tuning  : FALSE
Seed cherry-picking   : FALSE
----------------------------------------------------------------------------------------------------------------------------
SELF TEST
Synthetic tau*        : 0.500000
Metric implementation : PASS
10-run aggregation    : PASS
MODEL TRAINING        : FALSE
----------------------------------------------------------------------------------------------------------------------------
Metric registry       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_FINAL_metric_registry.csv
Evaluation contract   : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_evaluation_contract.json
Evaluation SHA256     : a65ef63acc0d564643a62aaf58cf2c27ea203a1576cc622d986cd0f0ecc96c6f
Threshold policy      : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_threshold_policy.json
Statistical policy    : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_statistical_policy.json
Hyperparameter policy : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_hyperparameter_policy.json
============================================================================================================================

In [3]:
# ============================================================
# CELL 13 - RESTART-SAFE
# FINAL REPRESENTATION + HYPERPARAMETER LOCK
# FOR 10 CONTROLLED BASELINES
#
# NO MODEL TRAINING
# NO TEST ACCESS FOR MODEL SELECTION
# NO DATASET-SPECIFIC HYPERPARAMETER TUNING
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json

import numpy as np
import pandas as pd


# ============================================================
# 1. RESTORE PROJECT STATE FROM DISK
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

SPLIT_DIR = (
    OUTPUT_ROOT
    / "splits"
)


for path in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    SPLIT_DIR,
]:

    assert path.is_dir(), (
        f"Required directory missing:\n{path}"
    )


# ============================================================
# 2. LOAD AUTHORITATIVE LOCKS FROM DISK
# ============================================================

BENCHMARK_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark4_FINAL_v1_manifest.json"
)

MODEL_REGISTRY_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_model_registry.json"
)

EXECUTION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_execution_contract.json"
)

EVALUATION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_evaluation_contract.json"
)


for path in [
    BENCHMARK_MANIFEST_PATH,
    MODEL_REGISTRY_PATH,
    EXECUTION_CONTRACT_PATH,
    EVALUATION_CONTRACT_PATH,
]:

    assert path.is_file(), (
        f"Required locked artifact missing:\n{path}"
    )


with open(
    BENCHMARK_MANIFEST_PATH,
    "r",
    encoding="utf-8",
) as f:

    benchmark_manifest = json.load(f)


with open(
    MODEL_REGISTRY_PATH,
    "r",
    encoding="utf-8",
) as f:

    model_registry_manifest = json.load(f)


with open(
    EXECUTION_CONTRACT_PATH,
    "r",
    encoding="utf-8",
) as f:

    execution_manifest = json.load(f)


with open(
    EVALUATION_CONTRACT_PATH,
    "r",
    encoding="utf-8",
) as f:

    evaluation_manifest = json.load(f)


# ============================================================
# 3. VERIFY LOCKED BENCHMARK STATE
# ============================================================

EXPECTED_DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "AMPlify_balanced",
    "External_Benchmark_3",
]

EXPECTED_SEEDS = list(
    range(100, 110)
)


assert (
    benchmark_manifest[
        "datasets"
    ]
    == EXPECTED_DATASETS
)

assert (
    benchmark_manifest[
        "model_seeds"
    ]
    == EXPECTED_SEEDS
)

assert (
    benchmark_manifest[
        "status"
    ]
    == "FINAL_DATA_LOCK_BEFORE_MODEL_TRAINING"
)

assert (
    model_registry_manifest[
        "status"
    ]
    == "MODEL_LIST_LOCKED_BEFORE_TRAINING"
)

assert (
    model_registry_manifest[
        "n_models"
    ]
    == 17
)

assert (
    execution_manifest[
        "status"
    ]
    == "EXECUTION_CONTRACT_LOCKED_BEFORE_TRAINING"
)

assert (
    evaluation_manifest[
        "status"
    ]
    == "LOCKED_BEFORE_MODEL_TRAINING"
)

assert (
    evaluation_manifest[
        "training_started"
    ]
    is False
)


SEEDS = EXPECTED_SEEDS


# ============================================================
# 4. VERIFY CONTROLLED MODEL IDENTITIES
# ============================================================

EXPECTED_CONTROLLED_MODEL_IDS = [
    "logistic_regression",
    "linear_svm_calibrated",
    "random_forest",
    "extra_trees",
    "hist_gradient_boosting",
    "lightgbm",
    "cnn1d",
    "bilstm",
    "bilstm_attention",
    "transformer_encoder",
]


registry_models = (
    model_registry_manifest[
        "models"
    ]
)


controlled_registry = [
    row
    for row in registry_models
    if (
        row["group"]
        == "controlled_baseline"
    )
]


controlled_ids = [
    row["model_id"]
    for row in controlled_registry
]


assert (
    controlled_ids
    == EXPECTED_CONTROLLED_MODEL_IDS
), (
    "Controlled-model registry changed."
)


assert len(
    controlled_ids
) == 10


# ============================================================
# 5. LOAD FINAL COHORT AND VERIFY DATA CONTRACT
# ============================================================

FINAL_COHORT_PATH = Path(
    benchmark_manifest[
        "final_cohort"
    ][
        "path"
    ]
)


assert FINAL_COHORT_PATH.is_file()


benchmark_df = pd.read_csv(
    FINAL_COHORT_PATH,
    low_memory=False,
)


assert len(
    benchmark_df
) == 41059


assert set(
    benchmark_df[
        "dataset"
    ].unique()
) == set(
    EXPECTED_DATASETS
)


assert set(
    benchmark_df[
        "split"
    ].unique()
) == {
    "train",
    "validation",
    "test",
}


assert set(
    benchmark_df[
        "label"
    ].unique()
) == {0, 1}


# ============================================================
# 6. CANONICAL AMINO-ACID ALPHABET
# ============================================================

AA_ORDER = list(
    "ACDEFGHIKLMNPQRSTVWY"
)

AA_SET = set(
    AA_ORDER
)


assert len(
    AA_ORDER
) == 20


assert benchmark_df[
    "sequence"
].apply(
    lambda seq:
        set(
            str(seq)
        ).issubset(
            AA_SET
        )
).all()


sequence_lengths = (
    benchmark_df[
        "sequence"
    ].astype(str)
    .str.len()
)


assert sequence_lengths.between(
    10,
    200,
    inclusive="both",
).all()


# ============================================================
# 7. CLASSICAL ML REPRESENTATION
#
# ONE COMMON REPRESENTATION FOR ALL 6 ML MODELS:
#
# 1 feature  : normalized length
# 20 features: AAC
# 400        : DPC
# -------------------
# TOTAL      : 421
#
# No learned feature extraction.
# No validation/test fitting.
# ============================================================

AAC_FEATURE_NAMES = [
    f"AAC_{aa}"
    for aa in AA_ORDER
]


DPC_FEATURE_NAMES = [
    f"DPC_{aa1}{aa2}"
    for aa1 in AA_ORDER
    for aa2 in AA_ORDER
]


CLASSICAL_FEATURE_NAMES = (
    ["Length_norm"]
    + AAC_FEATURE_NAMES
    + DPC_FEATURE_NAMES
)


assert len(
    AAC_FEATURE_NAMES
) == 20

assert len(
    DPC_FEATURE_NAMES
) == 400

assert len(
    CLASSICAL_FEATURE_NAMES
) == 421

assert len(
    set(
        CLASSICAL_FEATURE_NAMES
    )
) == 421


CLASSICAL_REPRESENTATION = {

    "representation_id":
        "Length_AAC20_DPC400_v1",

    "feature_dimension":
        421,

    "feature_order": [
        "Length_norm",
        "AAC20",
        "DPC400",
    ],

    "length_feature": {

        "definition":
            "sequence_length_divided_by_200",

        "range":
            [0.05, 1.0],
    },

    "AAC": {

        "dimension":
            20,

        "definition":
            "count_of_each_amino_acid_divided_by_sequence_length",

        "amino_acid_order":
            AA_ORDER,
    },

    "DPC": {

        "dimension":
            400,

        "definition":
            "adjacent_dipeptide_count_divided_by_L_minus_1",

        "ordering":
            "AA_ORDER_x_AA_ORDER",

        "amino_acid_order":
            AA_ORDER,
    },

    "feature_extractor_fit_required":
        False,

    "uses_external_embedding":
        False,

    "uses_pretrained_language_model":
        False,

    "test_information_used":
        False,

    "target_information_used":
        False,
}


# ============================================================
# 8. DEEP-LEARNING RAW SEQUENCE REPRESENTATION
# ============================================================

TOKEN_TO_ID = {
    "PAD": 0
}


for index, aa in enumerate(
    AA_ORDER,
    start=1,
):

    TOKEN_TO_ID[
        aa
    ] = index


assert len(
    TOKEN_TO_ID
) == 21

assert TOKEN_TO_ID[
    "PAD"
] == 0


DEEP_REPRESENTATION = {

    "representation_id":
        "AA20_integer_tokens_L200_v1",

    "input_type":
        "raw_peptide_sequence",

    "vocabulary_size":
        21,

    "padding_token":
        "PAD",

    "padding_token_id":
        0,

    "amino_acid_order":
        AA_ORDER,

    "token_to_id":
        TOKEN_TO_ID,

    "maximum_length":
        200,

    "minimum_length":
        10,

    "padding":
        "post",

    "truncation":
        "post",

    "truncation_expected":
        False,

    "mask_padding":
        True,

    "embedding_dimension":
        64,

    "embedding_trainable":
        True,

    "external_embedding":
        False,

    "pretrained_language_model":
        False,

    "vocabulary_fit_on_dataset":
        False,

    "test_information_used":
        False,

    "target_information_used":
        False,
}


# ============================================================
# 9. GLOBAL TRAINING POLICY FOR CONTROLLED MODELS
# ============================================================

CONTROLLED_TRAINING_POLICY = {

    "model_seeds":
        EXPECTED_SEEDS,

    "runs_per_model_dataset":
        10,

    "same_data_split_all_seeds":
        True,

    "seed_tuning":
        False,

    "data_resplitting_per_seed":
        False,

    "class_oversampling":
        False,

    "class_undersampling":
        False,

    "SMOTE":
        False,

    "class_weight":
        None,

    "sample_weight":
        None,

    "test_guided_tuning":
        False,

    "external_target_guided_tuning":
        False,

    "source_train_use":
        "model_fitting",

    "source_validation_use": [
        "deep_learning_early_stopping",
        "tau_star_selection",
    ],

    "source_test_use":
        "final_evaluation_only",

    "external_target_test_use":
        "evaluation_only_after_strict_decontamination",

    "threshold_source":
        "source_validation_MCC",

    "threshold_target_tuning":
        False,
}


# ============================================================
# 10. SHARED DEEP-LEARNING TRAINING CONFIG
# ============================================================

DEEP_SHARED_TRAINING = {

    "optimizer":
        "Adam",

    "learning_rate":
        0.001,

    "beta_1":
        0.9,

    "beta_2":
        0.999,

    "epsilon":
        1e-7,

    "clipnorm":
        1.0,

    "loss":
        "binary_crossentropy",

    "output_activation":
        "sigmoid",

    "batch_size":
        64,

    "maximum_epochs":
        80,

    "shuffle_train_each_epoch":
        True,

    "early_stopping": {

        "enabled":
            True,

        "monitor":
            "val_loss",

        "mode":
            "min",

        "patience":
            8,

        "restore_best_weights":
            True,

        "min_delta":
            0.0,
    },

    "reduce_lr_on_plateau": {

        "enabled":
            True,

        "monitor":
            "val_loss",

        "mode":
            "min",

        "factor":
            0.5,

        "patience":
            3,

        "minimum_learning_rate":
            1e-6,
    },

    "checkpoint_monitor":
        "val_loss",

    "checkpoint_mode":
        "min",

    "validation_shuffle":
        False,

    "test_shuffle":
        False,

    "run_seed":
        "CURRENT_SEED_FROM_100_TO_109",

    "tensorflow_deterministic_ops":
        True,
}


# ============================================================
# 11. EXACT CONFIG - LOGISTIC REGRESSION
# ============================================================

LOGISTIC_REGRESSION_CONFIG = {

    "model_id":
        "logistic_regression",

    "representation":
        "Length_AAC20_DPC400_v1",

    "preprocessing": {

        "scaler":
            "StandardScaler",

        "with_mean":
            True,

        "with_std":
            True,

        "fit_on":
            "source_train_only",
    },

    "estimator": {

        "class":
            "sklearn.linear_model.LogisticRegression",

        "penalty":
            "l2",

        "C":
            1.0,

        "solver":
            "lbfgs",

        "max_iter":
            2000,

        "tol":
            1e-4,

        "class_weight":
            None,

        "random_state":
            None,
    },
}


# ============================================================
# 12. EXACT CONFIG - CALIBRATED LINEAR SVM
#
# Calibration folds are source TRAIN only.
# No official validation/test samples enter calibration.
# ============================================================

LINEAR_SVM_CONFIG = {

    "model_id":
        "linear_svm_calibrated",

    "representation":
        "Length_AAC20_DPC400_v1",

    "preprocessing": {

        "scaler":
            "StandardScaler",

        "with_mean":
            True,

        "with_std":
            True,

        "fit_on":
            "source_train_only",
    },

    "base_estimator": {

        "class":
            "sklearn.svm.LinearSVC",

        "C":
            1.0,

        "loss":
            "squared_hinge",

        "penalty":
            "l2",

        "dual":
            "auto",

        "tol":
            1e-4,

        "max_iter":
            20000,

        "class_weight":
            None,

        "random_state":
            "RUN_SEED",
    },

    "calibration": {

        "class":
            "sklearn.calibration.CalibratedClassifierCV",

        "method":
            "sigmoid",

        "cv":
            5,

        "cv_type":
            "StratifiedKFold",

        "cv_shuffle":
            True,

        "cv_random_state":
            "RUN_SEED",

        "ensemble":
            True,

        "calibration_data":
            "source_train_only",
    },
}


# ============================================================
# 13. EXACT CONFIG - RANDOM FOREST
# ============================================================

RANDOM_FOREST_CONFIG = {

    "model_id":
        "random_forest",

    "representation":
        "Length_AAC20_DPC400_v1",

    "preprocessing": {

        "scaler":
            None,
    },

    "estimator": {

        "class":
            "sklearn.ensemble.RandomForestClassifier",

        "n_estimators":
            500,

        "criterion":
            "gini",

        "max_depth":
            None,

        "min_samples_split":
            2,

        "min_samples_leaf":
            1,

        "max_features":
            "sqrt",

        "bootstrap":
            True,

        "class_weight":
            None,

        "n_jobs":
            -1,

        "random_state":
            "RUN_SEED",
    },
}


# ============================================================
# 14. EXACT CONFIG - EXTRA TREES
# ============================================================

EXTRA_TREES_CONFIG = {

    "model_id":
        "extra_trees",

    "representation":
        "Length_AAC20_DPC400_v1",

    "preprocessing": {

        "scaler":
            None,
    },

    "estimator": {

        "class":
            "sklearn.ensemble.ExtraTreesClassifier",

        "n_estimators":
            500,

        "criterion":
            "gini",

        "max_depth":
            None,

        "min_samples_split":
            2,

        "min_samples_leaf":
            1,

        "max_features":
            "sqrt",

        "bootstrap":
            False,

        "class_weight":
            None,

        "n_jobs":
            -1,

        "random_state":
            "RUN_SEED",
    },
}


# ============================================================
# 15. EXACT CONFIG - HISTGRADIENTBOOSTING
# ============================================================

HIST_GB_CONFIG = {

    "model_id":
        "hist_gradient_boosting",

    "representation":
        "Length_AAC20_DPC400_v1",

    "preprocessing": {

        "scaler":
            None,
    },

    "estimator": {

        "class":
            "sklearn.ensemble.HistGradientBoostingClassifier",

        "loss":
            "log_loss",

        "learning_rate":
            0.05,

        "max_iter":
            300,

        "max_leaf_nodes":
            31,

        "max_depth":
            None,

        "min_samples_leaf":
            20,

        "l2_regularization":
            1.0,

        "max_bins":
            255,

        "early_stopping":
            False,

        "random_state":
            "RUN_SEED",
    },
}


# ============================================================
# 16. EXACT CONFIG - LIGHTGBM
# ============================================================

LIGHTGBM_CONFIG = {

    "model_id":
        "lightgbm",

    "representation":
        "Length_AAC20_DPC400_v1",

    "preprocessing": {

        "scaler":
            None,
    },

    "estimator": {

        "class":
            "lightgbm.LGBMClassifier",

        "objective":
            "binary",

        "n_estimators":
            500,

        "learning_rate":
            0.05,

        "num_leaves":
            31,

        "max_depth":
            -1,

        "min_child_samples":
            20,

        "subsample":
            0.8,

        "subsample_freq":
            1,

        "colsample_bytree":
            0.8,

        "reg_alpha":
            0.0,

        "reg_lambda":
            1.0,

        "class_weight":
            None,

        "n_jobs":
            -1,

        "random_state":
            "RUN_SEED",

        "deterministic":
            True,

        "force_col_wise":
            True,

        "verbosity":
            -1,

        "device_type":
            "cpu",
    },
}


# ============================================================
# 17. EXACT CONFIG - 1D CNN
# ============================================================

CNN1D_CONFIG = {

    "model_id":
        "cnn1d",

    "representation":
        "AA20_integer_tokens_L200_v1",

    "architecture": {

        "embedding_dim":
            64,

        "embedding_mask_zero":
            True,

        "conv1_filters":
            128,

        "conv1_kernel_size":
            5,

        "conv1_padding":
            "same",

        "conv1_activation":
            "relu",

        "conv2_filters":
            128,

        "conv2_kernel_size":
            3,

        "conv2_padding":
            "same",

        "conv2_activation":
            "relu",

        "pooling":
            "masked_global_max_pooling",

        "dense_units":
            64,

        "dense_activation":
            "relu",

        "dropout":
            0.30,

        "output_units":
            1,

        "output_activation":
            "sigmoid",
    },

    "training":
        DEEP_SHARED_TRAINING,
}


# ============================================================
# 18. EXACT CONFIG - BiLSTM
# ============================================================

BILSTM_CONFIG = {

    "model_id":
        "bilstm",

    "representation":
        "AA20_integer_tokens_L200_v1",

    "architecture": {

        "embedding_dim":
            64,

        "embedding_mask_zero":
            True,

        "bilstm_units_per_direction":
            64,

        "return_sequences":
            False,

        "lstm_dropout":
            0.20,

        "recurrent_dropout":
            0.0,

        "dense_units":
            64,

        "dense_activation":
            "relu",

        "dense_dropout":
            0.30,

        "output_units":
            1,

        "output_activation":
            "sigmoid",
    },

    "training":
        DEEP_SHARED_TRAINING,
}


# ============================================================
# 19. EXACT CONFIG - BiLSTM ATTENTION
# ============================================================

BILSTM_ATTENTION_CONFIG = {

    "model_id":
        "bilstm_attention",

    "representation":
        "AA20_integer_tokens_L200_v1",

    "architecture": {

        "embedding_dim":
            64,

        "embedding_mask_zero":
            True,

        "bilstm_units_per_direction":
            64,

        "return_sequences":
            True,

        "lstm_dropout":
            0.20,

        "recurrent_dropout":
            0.0,

        "attention_type":
            "trainable_masked_additive_attention",

        "attention_units":
            64,

        "padding_mask_applied_before_softmax":
            True,

        "dense_units":
            64,

        "dense_activation":
            "relu",

        "dense_dropout":
            0.30,

        "output_units":
            1,

        "output_activation":
            "sigmoid",
    },

    "training":
        DEEP_SHARED_TRAINING,
}


# ============================================================
# 20. EXACT CONFIG - TRANSFORMER ENCODER
# ============================================================

TRANSFORMER_CONFIG = {

    "model_id":
        "transformer_encoder",

    "representation":
        "AA20_integer_tokens_L200_v1",

    "architecture": {

        "token_embedding_dim":
            64,

        "positional_embedding":
            "learned",

        "maximum_positions":
            200,

        "n_encoder_blocks":
            2,

        "num_attention_heads":
            4,

        "key_dim_per_head":
            16,

        "model_dimension":
            64,

        "feed_forward_dimension":
            128,

        "attention_dropout":
            0.10,

        "feed_forward_dropout":
            0.10,

        "residual_connections":
            True,

        "layer_normalization":
            True,

        "padding_attention_mask":
            True,

        "sequence_pooling":
            "masked_global_average",

        "dense_units":
            64,

        "dense_activation":
            "relu",

        "dense_dropout":
            0.30,

        "output_units":
            1,

        "output_activation":
            "sigmoid",
    },

    "training":
        DEEP_SHARED_TRAINING,
}


# ============================================================
# 21. COMPLETE 10-MODEL CONFIGURATION
# ============================================================

CONTROLLED_MODEL_CONFIGS = {

    "logistic_regression":
        LOGISTIC_REGRESSION_CONFIG,

    "linear_svm_calibrated":
        LINEAR_SVM_CONFIG,

    "random_forest":
        RANDOM_FOREST_CONFIG,

    "extra_trees":
        EXTRA_TREES_CONFIG,

    "hist_gradient_boosting":
        HIST_GB_CONFIG,

    "lightgbm":
        LIGHTGBM_CONFIG,

    "cnn1d":
        CNN1D_CONFIG,

    "bilstm":
        BILSTM_CONFIG,

    "bilstm_attention":
        BILSTM_ATTENTION_CONFIG,

    "transformer_encoder":
        TRANSFORMER_CONFIG,
}


assert list(
    CONTROLLED_MODEL_CONFIGS.keys()
) == EXPECTED_CONTROLLED_MODEL_IDS


assert len(
    CONTROLLED_MODEL_CONFIGS
) == 10


# ============================================================
# 22. SCIENTIFIC FAIRNESS CONTRACT
# ============================================================

FAIRNESS_CONTRACT = {

    "same_four_datasets":
        True,

    "same_fixed_splits":
        True,

    "same_ten_seeds":
        True,

    "same_classical_representation_for_six_ml_models":
        True,

    "same_raw_sequence_representation_for_four_dl_models":
        True,

    "dataset_specific_hyperparameter_tuning":
        False,

    "test_guided_model_selection":
        False,

    "target_guided_model_selection":
        False,

    "resampling":
        False,

    "synthetic_samples":
        False,

    "class_weights":
        False,

    "external_pretrained_embedding_for_controlled_models":
        False,

    "threshold_rule":
        "source_validation_MCC",

    "protocol2_target_adaptation":
        False,
}


# ============================================================
# 23. FEATURE REGISTRY
# ============================================================

feature_registry_df = pd.DataFrame(
    {
        "feature_index":
            list(
                range(
                    421
                )
            ),

        "feature_name":
            CLASSICAL_FEATURE_NAMES,
    }
)


assert (
    feature_registry_df[
        "feature_index"
    ].iloc[-1]
    == 420
)


# ============================================================
# 24. MODEL SUMMARY TABLE
# ============================================================

model_summary_rows = []


for model_id in EXPECTED_CONTROLLED_MODEL_IDS:

    config = (
        CONTROLLED_MODEL_CONFIGS[
            model_id
        ]
    )

    representation = (
        config[
            "representation"
        ]
    )

    if representation == (
        "Length_AAC20_DPC400_v1"
    ):

        input_dim = 421
        model_family = "classical_ml"

    else:

        input_dim = 200
        model_family = "deep_learning"


    model_summary_rows.append(
        {
            "model_id":
                model_id,

            "family":
                model_family,

            "representation":
                representation,

            "input_dimension":
                input_dim,

            "n_runs":
                10,

            "seed_start":
                100,

            "seed_end":
                109,

            "dataset_specific_tuning":
                False,

            "training_started":
                False,
        }
    )


controlled_model_summary_df = (
    pd.DataFrame(
        model_summary_rows
    )
)


assert len(
    controlled_model_summary_df
) == 10


# ============================================================
# 25. REPRESENTATION SELF-TEST
#
# Defines canonical deterministic feature extraction.
# This does NOT build the full feature cache yet.
# ============================================================

AA_TO_INDEX = {
    aa: i
    for i, aa in enumerate(
        AA_ORDER
    )
}


DPC_TO_INDEX = {
    aa1 + aa2:
        (
            i * 20
            + j
        )
    for i, aa1 in enumerate(
        AA_ORDER
    )
    for j, aa2 in enumerate(
        AA_ORDER
    )
}


def extract_421_features(
    sequence,
):

    seq = str(
        sequence
    ).upper()


    assert 10 <= len(
        seq
    ) <= 200


    assert set(
        seq
    ).issubset(
        AA_SET
    )


    length_feature = np.array(
        [
            len(seq)
            / 200.0
        ],
        dtype=np.float32,
    )


    aac = np.zeros(
        20,
        dtype=np.float32,
    )


    for aa in seq:

        aac[
            AA_TO_INDEX[
                aa
            ]
        ] += 1.0


    aac /= float(
        len(seq)
    )


    dpc = np.zeros(
        400,
        dtype=np.float32,
    )


    for i in range(
        len(seq) - 1
    ):

        pair = (
            seq[i]
            + seq[i + 1]
        )

        dpc[
            DPC_TO_INDEX[
                pair
            ]
        ] += 1.0


    dpc /= float(
        len(seq) - 1
    )


    features = np.concatenate(
        [
            length_feature,
            aac,
            dpc,
        ]
    ).astype(
        np.float32
    )


    assert features.shape == (
        421,
    )


    return features


SELF_TEST_SEQUENCE = (
    "ACDEFGHIKLMNPQRSTVWY"
)


self_features = (
    extract_421_features(
        SELF_TEST_SEQUENCE
    )
)


assert self_features.shape == (
    421,
)


assert np.isclose(
    self_features[
        0
    ],
    20 / 200,
)


assert np.isclose(
    self_features[
        1:21
    ].sum(),
    1.0,
)


assert np.isclose(
    self_features[
        21:
    ].sum(),
    1.0,
)


# ============================================================
# 26. TOKENIZATION SELF-TEST
# ============================================================

def encode_sequence_200(
    sequence,
):

    seq = str(
        sequence
    ).upper()


    assert 10 <= len(
        seq
    ) <= 200


    assert set(
        seq
    ).issubset(
        AA_SET
    )


    encoded = np.zeros(
        200,
        dtype=np.int32,
    )


    for i, aa in enumerate(
        seq
    ):

        encoded[i] = (
            TOKEN_TO_ID[
                aa
            ]
        )


    return encoded


self_tokens = (
    encode_sequence_200(
        SELF_TEST_SEQUENCE
    )
)


assert self_tokens.shape == (
    200,
)


assert (
    self_tokens[:20]
    > 0
).all()


assert (
    self_tokens[20:]
    == 0
).all()


# ============================================================
# 27. BUILD IMMUTABLE CONTRACT CORE
# ============================================================

CONTROLLED_CONTRACT_CORE = {

    "schema_version":
        "1.0",

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "model_registry":
        "benchmark17_FINAL_model_registry.json",

    "evaluation_contract":
        "benchmark17_FINAL_evaluation_contract.json",

    "datasets":
        EXPECTED_DATASETS,

    "model_seeds":
        EXPECTED_SEEDS,

    "n_controlled_models":
        10,

    "controlled_model_ids":
        EXPECTED_CONTROLLED_MODEL_IDS,

    "classical_representation":
        CLASSICAL_REPRESENTATION,

    "deep_representation":
        DEEP_REPRESENTATION,

    "training_policy":
        CONTROLLED_TRAINING_POLICY,

    "deep_shared_training":
        DEEP_SHARED_TRAINING,

    "model_configs":
        CONTROLLED_MODEL_CONFIGS,

    "fairness_contract":
        FAIRNESS_CONTRACT,

    "training_started":
        False,
}


# ============================================================
# 28. OUTPUT PATHS
# ============================================================

CONTROLLED_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_controlled_model_contract.json"
)

FEATURE_REGISTRY_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_classical_421_feature_registry.csv"
)

TOKEN_REGISTRY_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_AA20_token_registry.json"
)

CONTROLLED_MODEL_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_controlled_model_summary.csv"
)


# ============================================================
# 29. IDEMPOTENT LOCK
#
# If rerun after reboot:
# - same contract -> PASS
# - different contract -> STOP
#
# We never silently change locked hyperparameters.
# ============================================================

if CONTROLLED_CONTRACT_PATH.exists():

    with open(
        CONTROLLED_CONTRACT_PATH,
        "r",
        encoding="utf-8",
    ) as f:

        existing_contract = (
            json.load(f)
        )


    assert (
        existing_contract[
            "contract"
        ]
        ==
        CONTROLLED_CONTRACT_CORE
    ), (
        "CELL 13 CONTRACT ALREADY EXISTS "
        "BUT CONTENT DIFFERS.\n"
        "Do NOT overwrite a locked model contract."
    )


    created_at = (
        existing_contract[
            "created_at"
        ]
    )

    lock_action = (
        "EXISTING IDENTICAL LOCK VERIFIED"
    )

else:

    created_at = (
        datetime.now()
        .astimezone()
        .isoformat()
    )


    payload = {

        "created_at":
            created_at,

        "status":
            "CONTROLLED_MODELS_LOCKED_BEFORE_TRAINING",

        "restart_safe":
            True,

        "contract":
            CONTROLLED_CONTRACT_CORE,
    }


    with open(
        CONTROLLED_CONTRACT_PATH,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            payload,
            f,
            indent=2,
            ensure_ascii=False,
        )


    lock_action = (
        "NEW LOCK CREATED"
    )


# ============================================================
# 30. SAVE SUPPORTING REGISTRIES
# ============================================================

feature_registry_df.to_csv(
    FEATURE_REGISTRY_PATH,
    index=False,
)


controlled_model_summary_df.to_csv(
    CONTROLLED_MODEL_SUMMARY_PATH,
    index=False,
)


TOKEN_REGISTRY = {

    "representation_id":
        "AA20_integer_tokens_L200_v1",

    "maximum_length":
        200,

    "padding":
        "post",

    "padding_token_id":
        0,

    "token_to_id":
        TOKEN_TO_ID,
}


with open(
    TOKEN_REGISTRY_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        TOKEN_REGISTRY,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ============================================================
# 31. SHA256
# ============================================================

def sha256_file_cell13(
    path,
):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda:
                f.read(
                    1024 * 1024
                ),
            b"",
        ):

            h.update(chunk)

    return h.hexdigest()


CONTROLLED_CONTRACT_SHA256 = (
    sha256_file_cell13(
        CONTROLLED_CONTRACT_PATH
    )
)


# ============================================================
# 32. RE-READ FINAL CONTRACT FROM DISK
# ============================================================

with open(
    CONTROLLED_CONTRACT_PATH,
    "r",
    encoding="utf-8",
) as f:

    controlled_check = json.load(f)


assert (
    controlled_check[
        "status"
    ]
    == "CONTROLLED_MODELS_LOCKED_BEFORE_TRAINING"
)


assert (
    controlled_check[
        "restart_safe"
    ]
    is True
)


assert (
    controlled_check[
        "contract"
    ][
        "training_started"
    ]
    is False
)


assert (
    controlled_check[
        "contract"
    ][
        "model_seeds"
    ]
    == EXPECTED_SEEDS
)


assert (
    controlled_check[
        "contract"
    ][
        "classical_representation"
    ][
        "feature_dimension"
    ]
    == 421
)


assert (
    controlled_check[
        "contract"
    ][
        "deep_representation"
    ][
        "maximum_length"
    ]
    == 200
)


assert len(
    controlled_check[
        "contract"
    ][
        "model_configs"
    ]
) == 10


# ============================================================
# 33. FINAL REPORT
# ============================================================

print("=" * 124)

print(
    "CELL 13 PASS - CONTROLLED MODEL REPRESENTATION "
    "AND HYPERPARAMETERS LOCKED"
)

print("=" * 124)

print(
    f"LOCK ACTION            : {lock_action}"
)

print(
    "RESTART SAFE           : TRUE"
)

print(
    "TRAINING STARTED       : FALSE"
)

print(
    f"SEEDS                  : {EXPECTED_SEEDS}"
)

print("-" * 124)

print(
    "CLASSICAL ML REPRESENTATION"
)

print(
    "Models                 : LR / Linear SVM / RF / ExtraTrees / HistGB / LightGBM"
)

print(
    "Representation         : Length + AAC20 + DPC400"
)

print(
    "Feature dimension      : 421"
)

print(
    "Feature fitting        : NONE"
)

print(
    "Scaler fitting         : SOURCE TRAIN ONLY where required"
)

print("-" * 124)

print(
    "DEEP LEARNING REPRESENTATION"
)

print(
    "Models                 : 1D-CNN / BiLSTM / BiLSTM-Attention / Transformer"
)

print(
    "Input                  : RAW AA20 SEQUENCE"
)

print(
    "Maximum length         : 200"
)

print(
    "Vocabulary             : 20 AA + PAD"
)

print(
    "Embedding dimension    : 64"
)

print(
    "Pretrained embedding   : FALSE"
)

print(
    "External LM            : FALSE"
)

print("-" * 124)

print(
    "COMMON DEEP TRAINING"
)

print(
    "Optimizer              : Adam"
)

print(
    "Learning rate          : 0.001"
)

print(
    "Batch size             : 64"
)

print(
    "Maximum epochs         : 80"
)

print(
    "Early stopping         : val_loss / patience 8"
)

print(
    "Reduce LR              : factor 0.5 / patience 3"
)

print(
    "Class weighting        : FALSE"
)

print(
    "Resampling / SMOTE     : FALSE"
)

print("-" * 124)

print(
    "CONTROLLED MODEL SUMMARY"
)

print(
    controlled_model_summary_df[
        [
            "model_id",
            "family",
            "representation",
            "input_dimension",
            "n_runs",
            "dataset_specific_tuning",
        ]
    ].to_string(
        index=False
    )
)

print("-" * 124)

print(
    "SELF TEST"
)

print(
    "421D feature extractor : PASS"
)

print(
    "AA20 tokenizer         : PASS"
)

print(
    "Dataset AA20/10-200    : PASS"
)

print(
    "Test-guided tuning     : FALSE"
)

print(
    "Target-guided tuning   : FALSE"
)

print(
    "Dataset-specific tune  : FALSE"
)

print("-" * 124)

print(
    f"Contract JSON          : "
    f"{CONTROLLED_CONTRACT_PATH}"
)

print(
    f"Contract SHA256        : "
    f"{CONTROLLED_CONTRACT_SHA256}"
)

print(
    f"Feature registry       : "
    f"{FEATURE_REGISTRY_PATH}"
)

print(
    f"Token registry         : "
    f"{TOKEN_REGISTRY_PATH}"
)

print(
    f"Model summary          : "
    f"{CONTROLLED_MODEL_SUMMARY_PATH}"
)

print("=" * 124)

============================================================================================================================
CELL 13 PASS - CONTROLLED MODEL REPRESENTATION AND HYPERPARAMETERS LOCKED
============================================================================================================================
LOCK ACTION            : NEW LOCK CREATED
RESTART SAFE           : TRUE
TRAINING STARTED       : FALSE
SEEDS                  : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
----------------------------------------------------------------------------------------------------------------------------
CLASSICAL ML REPRESENTATION
Models                 : LR / Linear SVM / RF / ExtraTrees / HistGB / LightGBM
Representation         : Length + AAC20 + DPC400
Feature dimension      : 421
Feature fitting        : NONE
Scaler fitting         : SOURCE TRAIN ONLY where required
----------------------------------------------------------------------------------------------------------------------------
DEEP LEARNING REPRESENTATION
Models                 : 1D-CNN / BiLSTM / BiLSTM-Attention / Transformer
Input                  : RAW AA20 SEQUENCE
Maximum length         : 200
Vocabulary             : 20 AA + PAD
Embedding dimension    : 64
Pretrained embedding   : FALSE
External LM            : FALSE
----------------------------------------------------------------------------------------------------------------------------
COMMON DEEP TRAINING
Optimizer              : Adam
Learning rate          : 0.001
Batch size             : 64
Maximum epochs         : 80
Early stopping         : val_loss / patience 8
Reduce LR              : factor 0.5 / patience 3
Class weighting        : FALSE
Resampling / SMOTE     : FALSE
----------------------------------------------------------------------------------------------------------------------------
CONTROLLED MODEL SUMMARY
              model_id        family              representation  input_dimension  n_runs  dataset_specific_tuning
   logistic_regression  classical_ml      Length_AAC20_DPC400_v1              421      10                    False
 linear_svm_calibrated  classical_ml      Length_AAC20_DPC400_v1              421      10                    False
         random_forest  classical_ml      Length_AAC20_DPC400_v1              421      10                    False
           extra_trees  classical_ml      Length_AAC20_DPC400_v1              421      10                    False
hist_gradient_boosting  classical_ml      Length_AAC20_DPC400_v1              421      10                    False
              lightgbm  classical_ml      Length_AAC20_DPC400_v1              421      10                    False
                 cnn1d deep_learning AA20_integer_tokens_L200_v1              200      10                    False
                bilstm deep_learning AA20_integer_tokens_L200_v1              200      10                    False
      bilstm_attention deep_learning AA20_integer_tokens_L200_v1              200      10                    False
   transformer_encoder deep_learning AA20_integer_tokens_L200_v1              200      10                    False
----------------------------------------------------------------------------------------------------------------------------
SELF TEST
421D feature extractor : PASS
AA20 tokenizer         : PASS
Dataset AA20/10-200    : PASS
Test-guided tuning     : FALSE
Target-guided tuning   : FALSE
Dataset-specific tune  : FALSE
----------------------------------------------------------------------------------------------------------------------------
Contract JSON          : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_controlled_model_contract.json
Contract SHA256        : 15dbfa757ae540cc95f5685d4fd936ffe4de54f813b871c102fc71ae96214f34
Feature registry       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_FINAL_classical_421_feature_registry.csv
Token registry         : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_AA20_token_registry.json
Model summary          : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_FINAL_controlled_model_summary.csv
============================================================================================================================

In [4]:
# ============================================================
# CELL 14 - RESTART-SAFE
# FINAL FEATURE / TOKEN CACHE BUILD & LOCK
#
# Builds ONCE:
#   X_classical : 41059 x 421 float32
#   X_tokens    : 41059 x 200 int16
#
# NO MODEL TRAINING
# NO SCALER FITTING
# NO TEST-BASED PROCESSING
#
# Heavy cache -> WSL filesystem
# Metadata/manifests -> project D:
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import os

import numpy as np
import pandas as pd


# ============================================================
# 1. RESTORE PROJECT STATE
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

SPLIT_DIR = (
    OUTPUT_ROOT
    / "splits"
)

WORK_ROOT = Path(
    "/home/pc/genpept_benchmark17_work"
)

CACHE_ROOT = (
    WORK_ROOT
    / "feature_cache"
    / "benchmark4_FINAL_v1"
)


for path in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    SPLIT_DIR,
]:

    assert path.is_dir(), (
        f"Required directory missing:\n{path}"
    )


WORK_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

CACHE_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# 2. LOAD AUTHORITATIVE MANIFESTS
# ============================================================

BENCHMARK_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark4_FINAL_v1_manifest.json"
)

CONTROLLED_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_controlled_model_contract.json"
)

TOKEN_REGISTRY_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_AA20_token_registry.json"
)


for path in [
    BENCHMARK_MANIFEST_PATH,
    CONTROLLED_CONTRACT_PATH,
    TOKEN_REGISTRY_PATH,
]:

    assert path.is_file(), (
        f"Required locked artifact missing:\n{path}"
    )


with open(
    BENCHMARK_MANIFEST_PATH,
    "r",
    encoding="utf-8",
) as f:

    benchmark_manifest = json.load(f)


with open(
    CONTROLLED_CONTRACT_PATH,
    "r",
    encoding="utf-8",
) as f:

    controlled_payload = json.load(f)


with open(
    TOKEN_REGISTRY_PATH,
    "r",
    encoding="utf-8",
) as f:

    token_registry = json.load(f)


controlled_contract = (
    controlled_payload[
        "contract"
    ]
)


# ============================================================
# 3. VERIFY LOCKS
# ============================================================

EXPECTED_DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "AMPlify_balanced",
    "External_Benchmark_3",
]

EXPECTED_SEEDS = list(
    range(100, 110)
)


assert (
    benchmark_manifest[
        "datasets"
    ]
    == EXPECTED_DATASETS
)

assert (
    benchmark_manifest[
        "model_seeds"
    ]
    == EXPECTED_SEEDS
)

assert (
    controlled_payload[
        "status"
    ]
    == "CONTROLLED_MODELS_LOCKED_BEFORE_TRAINING"
)

assert (
    controlled_contract[
        "training_started"
    ]
    is False
)

assert (
    controlled_contract[
        "classical_representation"
    ][
        "feature_dimension"
    ]
    == 421
)

assert (
    controlled_contract[
        "deep_representation"
    ][
        "maximum_length"
    ]
    == 200
)


# ============================================================
# 4. LOAD FINAL COHORT FROM DISK
# ============================================================

FINAL_COHORT_PATH = Path(
    benchmark_manifest[
        "final_cohort"
    ][
        "path"
    ]
)

EXPECTED_COHORT_SHA256 = (
    benchmark_manifest[
        "final_cohort"
    ][
        "sha256"
    ]
)


assert FINAL_COHORT_PATH.is_file(), (
    f"Final cohort missing:\n{FINAL_COHORT_PATH}"
)


def sha256_file(
    path,
):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda:
                f.read(
                    1024 * 1024
                ),
            b"",
        ):

            h.update(chunk)

    return h.hexdigest()


OBSERVED_COHORT_SHA256 = (
    sha256_file(
        FINAL_COHORT_PATH
    )
)


assert (
    OBSERVED_COHORT_SHA256
    ==
    EXPECTED_COHORT_SHA256
), (
    "FINAL cohort SHA256 mismatch."
)


df = pd.read_csv(
    FINAL_COHORT_PATH,
    low_memory=False,
)


assert len(df) == 41059

assert df[
    "sample_id"
].is_unique

assert df[
    "sequence"
].notna().all()


# ============================================================
# 5. RESTORE AA ORDER / TOKEN MAP FROM LOCK
# ============================================================

AA_ORDER = (
    controlled_contract[
        "classical_representation"
    ][
        "AAC"
    ][
        "amino_acid_order"
    ]
)


AA_SET = set(
    AA_ORDER
)


TOKEN_TO_ID = {
    key: int(value)
    for key, value in (
        token_registry[
            "token_to_id"
        ].items()
    )
}


assert len(
    AA_ORDER
) == 20

assert len(
    AA_SET
) == 20

assert (
    TOKEN_TO_ID[
        "PAD"
    ]
    == 0
)


for seq in df[
    "sequence"
]:

    assert set(
        str(seq)
    ).issubset(
        AA_SET
    )

    assert (
        10
        <= len(
            str(seq)
        )
        <= 200
    )


# ============================================================
# 6. FEATURE INDEX MAPS
# ============================================================

AA_TO_INDEX = {
    aa: i
    for i, aa in enumerate(
        AA_ORDER
    )
}


DPC_TO_INDEX = {
    aa1 + aa2:
        (
            i * 20
            + j
        )
    for i, aa1 in enumerate(
        AA_ORDER
    )
    for j, aa2 in enumerate(
        AA_ORDER
    )
}


assert len(
    AA_TO_INDEX
) == 20

assert len(
    DPC_TO_INDEX
) == 400


# ============================================================
# 7. CANONICAL 421D FEATURE EXTRACTOR
# ============================================================

def extract_421_features(
    sequence,
):

    seq = str(
        sequence
    ).upper()


    L = len(seq)


    assert (
        10 <= L <= 200
    )

    assert set(
        seq
    ).issubset(
        AA_SET
    )


    # -----------------------------
    # Length / 200
    # -----------------------------
    length_feature = np.array(
        [
            L / 200.0
        ],
        dtype=np.float32,
    )


    # -----------------------------
    # AAC20
    # -----------------------------
    aac = np.zeros(
        20,
        dtype=np.float32,
    )


    for aa in seq:

        aac[
            AA_TO_INDEX[
                aa
            ]
        ] += 1.0


    aac /= np.float32(
        L
    )


    # -----------------------------
    # DPC400
    # -----------------------------
    dpc = np.zeros(
        400,
        dtype=np.float32,
    )


    for i in range(
        L - 1
    ):

        pair = (
            seq[i]
            + seq[i + 1]
        )

        dpc[
            DPC_TO_INDEX[
                pair
            ]
        ] += 1.0


    dpc /= np.float32(
        L - 1
    )


    x = np.concatenate(
        [
            length_feature,
            aac,
            dpc,
        ],
        axis=0,
    ).astype(
        np.float32,
        copy=False,
    )


    assert x.shape == (
        421,
    )


    return x


# ============================================================
# 8. CANONICAL TOKEN ENCODER
# ============================================================

def encode_sequence_200(
    sequence,
):

    seq = str(
        sequence
    ).upper()


    L = len(seq)


    assert (
        10 <= L <= 200
    )


    encoded = np.zeros(
        200,
        dtype=np.int16,
    )


    for i, aa in enumerate(
        seq
    ):

        encoded[i] = (
            TOKEN_TO_ID[
                aa
            ]
        )


    return encoded


# ============================================================
# 9. CACHE PATHS
# ============================================================

CLASSICAL_CACHE_PATH = (
    CACHE_ROOT
    / "X_classical_421_float32.npy"
)

TOKEN_CACHE_PATH = (
    CACHE_ROOT
    / "X_tokens_L200_int16.npy"
)

LABEL_CACHE_PATH = (
    CACHE_ROOT
    / "y_int8.npy"
)

ROW_METADATA_PATH = (
    CACHE_ROOT
    / "row_metadata.csv"
)

CACHE_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_feature_cache_manifest.json"
)

CACHE_AUDIT_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_feature_cache_summary.csv"
)


# ============================================================
# 10. DETERMINE WHETHER IDENTICAL CACHE ALREADY EXISTS
# ============================================================

CACHE_REUSE = False


if CACHE_MANIFEST_PATH.exists():

    with open(
        CACHE_MANIFEST_PATH,
        "r",
        encoding="utf-8",
    ) as f:

        existing_manifest = json.load(f)


    manifest_matches = (

        existing_manifest.get(
            "source_cohort_sha256"
        )
        ==
        EXPECTED_COHORT_SHA256

        and

        existing_manifest.get(
            "n_rows"
        )
        ==
        41059

        and

        existing_manifest.get(
            "classical_dimension"
        )
        ==
        421

        and

        existing_manifest.get(
            "token_length"
        )
        ==
        200
    )


    files_exist = all(
        path.is_file()
        for path in [
            CLASSICAL_CACHE_PATH,
            TOKEN_CACHE_PATH,
            LABEL_CACHE_PATH,
            ROW_METADATA_PATH,
        ]
    )


    if (
        manifest_matches
        and files_exist
    ):

        expected_hashes = (
            existing_manifest[
                "files"
            ]
        )


        actual_hashes = {

            "X_classical":
                sha256_file(
                    CLASSICAL_CACHE_PATH
                ),

            "X_tokens":
                sha256_file(
                    TOKEN_CACHE_PATH
                ),

            "y":
                sha256_file(
                    LABEL_CACHE_PATH
                ),

            "row_metadata":
                sha256_file(
                    ROW_METADATA_PATH
                ),
        }


        CACHE_REUSE = all(

            actual_hashes[key]
            ==
            expected_hashes[
                key
            ][
                "sha256"
            ]

            for key in actual_hashes
        )


# ============================================================
# 11. BUILD CACHE IF NECESSARY
# ============================================================

if not CACHE_REUSE:

    n_rows = len(df)


    X_classical = np.empty(
        (
            n_rows,
            421,
        ),
        dtype=np.float32,
    )


    X_tokens = np.zeros(
        (
            n_rows,
            200,
        ),
        dtype=np.int16,
    )


    y = (
        df[
            "label"
        ]
        .to_numpy(
            dtype=np.int8
        )
    )


    sequences = (
        df[
            "sequence"
        ]
        .astype(str)
        .tolist()
    )


    for row_idx, seq in enumerate(
        sequences
    ):

        X_classical[
            row_idx
        ] = (
            extract_421_features(
                seq
            )
        )


        X_tokens[
            row_idx
        ] = (
            encode_sequence_200(
                seq
            )
        )


        if (
            (row_idx + 1) % 5000
            == 0
        ):

            print(
                f"Processed "
                f"{row_idx + 1:,}"
                f"/{n_rows:,}"
            )


    # --------------------------------------------------------
    # Hard numeric checks
    # --------------------------------------------------------
    assert (
        X_classical.shape
        ==
        (
            41059,
            421,
        )
    )


    assert (
        X_tokens.shape
        ==
        (
            41059,
            200,
        )
    )


    assert y.shape == (
        41059,
    )


    assert np.isfinite(
        X_classical
    ).all()


    assert (
        X_tokens >= 0
    ).all()


    assert (
        X_tokens <= 20
    ).all()


    # AAC rows sum to 1
    aac_sums = (
        X_classical[
            :,
            1:21,
        ]
        .sum(
            axis=1
        )
    )


    assert np.allclose(
        aac_sums,
        1.0,
        atol=1e-5,
    )


    # DPC rows sum to 1
    dpc_sums = (
        X_classical[
            :,
            21:
        ]
        .sum(
            axis=1
        )
    )


    assert np.allclose(
        dpc_sums,
        1.0,
        atol=1e-5,
    )


    # Number of non-PAD tokens must equal sequence length
    token_lengths = (
        X_tokens
        != 0
    ).sum(
        axis=1
    )


    true_lengths = (
        df[
            "sequence"
        ]
        .str.len()
        .to_numpy()
    )


    assert np.array_equal(
        token_lengths,
        true_lengths,
    )


    # --------------------------------------------------------
    # Save cache atomically through temporary files
    # --------------------------------------------------------
    temp_classical = Path(
        str(
            CLASSICAL_CACHE_PATH
        )
        + ".tmp.npy"
    )

    temp_tokens = Path(
        str(
            TOKEN_CACHE_PATH
        )
        + ".tmp.npy"
    )

    temp_y = Path(
        str(
            LABEL_CACHE_PATH
        )
        + ".tmp.npy"
    )


    np.save(
        temp_classical,
        X_classical,
        allow_pickle=False,
    )

    np.save(
        temp_tokens,
        X_tokens,
        allow_pickle=False,
    )

    np.save(
        temp_y,
        y,
        allow_pickle=False,
    )


    os.replace(
        temp_classical,
        CLASSICAL_CACHE_PATH,
    )

    os.replace(
        temp_tokens,
        TOKEN_CACHE_PATH,
    )

    os.replace(
        temp_y,
        LABEL_CACHE_PATH,
    )


    # --------------------------------------------------------
    # Row identity metadata
    # --------------------------------------------------------
    row_metadata = pd.DataFrame(
        {
            "row_index":
                np.arange(
                    n_rows,
                    dtype=np.int64,
                ),

            "sample_id":
                df[
                    "sample_id"
                ].astype(str),

            "dataset":
                df[
                    "dataset"
                ].astype(str),

            "split":
                df[
                    "split"
                ].astype(str),

            "label":
                y.astype(
                    np.int8
                ),

            "sequence_length":
                true_lengths.astype(
                    np.int16
                ),

            "sequence_sha256":
                df[
                    "sequence"
                ].astype(str)
                .map(
                    lambda seq:
                        hashlib.sha256(
                            seq.encode(
                                "utf-8"
                            )
                        ).hexdigest()
                ),
        }
    )


    assert row_metadata[
        "row_index"
    ].is_unique


    assert row_metadata[
        "sample_id"
    ].is_unique


    row_metadata.to_csv(
        ROW_METADATA_PATH,
        index=False,
    )


    CACHE_ACTION = (
        "NEW CACHE BUILT"
    )

else:

    CACHE_ACTION = (
        "EXISTING IDENTICAL CACHE REUSED"
    )


# ============================================================
# 12. LOAD CACHE FROM DISK
# ============================================================

X_classical_check = np.load(
    CLASSICAL_CACHE_PATH,
    mmap_mode="r",
    allow_pickle=False,
)

X_tokens_check = np.load(
    TOKEN_CACHE_PATH,
    mmap_mode="r",
    allow_pickle=False,
)

y_check = np.load(
    LABEL_CACHE_PATH,
    mmap_mode="r",
    allow_pickle=False,
)

row_metadata_check = pd.read_csv(
    ROW_METADATA_PATH,
    low_memory=False,
)


# ============================================================
# 13. HARD DISK-CACHE VALIDATION
# ============================================================

assert (
    X_classical_check.shape
    ==
    (
        41059,
        421,
    )
)

assert (
    X_classical_check.dtype
    ==
    np.float32
)


assert (
    X_tokens_check.shape
    ==
    (
        41059,
        200,
    )
)

assert (
    X_tokens_check.dtype
    ==
    np.int16
)


assert (
    y_check.shape
    ==
    (
        41059,
    )
)


assert (
    y_check.dtype
    ==
    np.int8
)


assert len(
    row_metadata_check
) == 41059


assert np.array_equal(
    y_check,
    df[
        "label"
    ].to_numpy(
        dtype=np.int8
    ),
)


assert np.array_equal(
    row_metadata_check[
        "sample_id"
    ].astype(str)
    .to_numpy(),
    df[
        "sample_id"
    ].astype(str)
    .to_numpy(),
)


assert np.array_equal(
    row_metadata_check[
        "dataset"
    ].astype(str)
    .to_numpy(),
    df[
        "dataset"
    ].astype(str)
    .to_numpy(),
)


assert np.array_equal(
    row_metadata_check[
        "split"
    ].astype(str)
    .to_numpy(),
    df[
        "split"
    ].astype(str)
    .to_numpy(),
)


# ============================================================
# 14. RANDOM-FREE SAMPLE RECONSTRUCTION CHECK
#
# Fixed deterministic row positions.
# ============================================================

CHECK_ROWS = [
    0,
    1,
    100,
    1000,
    10000,
    20000,
    30000,
    41058,
]


for idx in CHECK_ROWS:

    seq = str(
        df.iloc[
            idx
        ][
            "sequence"
        ]
    )


    expected_feature = (
        extract_421_features(
            seq
        )
    )


    expected_tokens = (
        encode_sequence_200(
            seq
        )
    )


    assert np.allclose(
        X_classical_check[
            idx
        ],
        expected_feature,
        atol=1e-7,
    )


    assert np.array_equal(
        X_tokens_check[
            idx
        ],
        expected_tokens,
    )


# ============================================================
# 15. DATASET/SPLIT CACHE INDEX SUMMARY
# ============================================================

cache_summary_df = (
    row_metadata_check
    .groupby(
        [
            "dataset",
            "split",
            "label",
        ],
        as_index=False,
    )
    .agg(
        n=(
            "sample_id",
            "count",
        ),

        first_row_index=(
            "row_index",
            "min",
        ),

        last_row_index=(
            "row_index",
            "max",
        ),
    )
)


# ============================================================
# 16. COMPUTE FILE HASHES
# ============================================================

CACHE_FILES = {

    "X_classical": {

        "path":
            str(
                CLASSICAL_CACHE_PATH
            ),

        "sha256":
            sha256_file(
                CLASSICAL_CACHE_PATH
            ),

        "shape":
            [
                41059,
                421,
            ],

        "dtype":
            "float32",
    },

    "X_tokens": {

        "path":
            str(
                TOKEN_CACHE_PATH
            ),

        "sha256":
            sha256_file(
                TOKEN_CACHE_PATH
            ),

        "shape":
            [
                41059,
                200,
            ],

        "dtype":
            "int16",
    },

    "y": {

        "path":
            str(
                LABEL_CACHE_PATH
            ),

        "sha256":
            sha256_file(
                LABEL_CACHE_PATH
            ),

        "shape":
            [
                41059
            ],

        "dtype":
            "int8",
    },

    "row_metadata": {

        "path":
            str(
                ROW_METADATA_PATH
            ),

        "sha256":
            sha256_file(
                ROW_METADATA_PATH
            ),

        "n_rows":
            41059,
    },
}


# ============================================================
# 17. CACHE MANIFEST CORE
# ============================================================

CACHE_MANIFEST_CORE = {

    "schema_version":
        "1.0",

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "source_cohort_path":
        str(
            FINAL_COHORT_PATH
        ),

    "source_cohort_sha256":
        EXPECTED_COHORT_SHA256,

    "n_rows":
        41059,

    "classical_representation":
        "Length_AAC20_DPC400_v1",

    "classical_dimension":
        421,

    "classical_dtype":
        "float32",

    "deep_representation":
        "AA20_integer_tokens_L200_v1",

    "token_length":
        200,

    "token_dtype":
        "int16",

    "label_dtype":
        "int8",

    "row_order":
        "exact_final_cohort_row_order",

    "sample_id_alignment_required":
        True,

    "sequence_sha256_alignment_required":
        True,

    "feature_scaling_applied":
        False,

    "scaler_fit_applied":
        False,

    "test_specific_processing":
        False,

    "target_specific_processing":
        False,

    "files":
        CACHE_FILES,
}


# ============================================================
# 18. IDEMPOTENT MANIFEST LOCK
# ============================================================

if CACHE_MANIFEST_PATH.exists():

    with open(
        CACHE_MANIFEST_PATH,
        "r",
        encoding="utf-8",
    ) as f:

        old_cache_manifest = (
            json.load(f)
        )


    old_core = {
        key: value
        for key, value in (
            old_cache_manifest.items()
        )
        if key not in [
            "created_at",
            "status",
        ]
    }


    assert (
        old_core
        ==
        CACHE_MANIFEST_CORE
    ), (
        "Existing cache manifest differs "
        "from current verified cache.\n"
        "Do NOT silently overwrite."
    )


    created_at = (
        old_cache_manifest[
            "created_at"
        ]
    )

else:

    created_at = (
        datetime.now()
        .astimezone()
        .isoformat()
    )


    cache_manifest_payload = {

        "created_at":
            created_at,

        "status":
            "FINAL_FEATURE_CACHE_LOCKED",

        **CACHE_MANIFEST_CORE,
    }


    with open(
        CACHE_MANIFEST_PATH,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            cache_manifest_payload,
            f,
            indent=2,
            ensure_ascii=False,
        )


# ============================================================
# 19. SAVE AUDIT SUMMARY
# ============================================================

cache_summary_df.to_csv(
    CACHE_AUDIT_PATH,
    index=False,
)


# ============================================================
# 20. FINAL RE-READ MANIFEST
# ============================================================

with open(
    CACHE_MANIFEST_PATH,
    "r",
    encoding="utf-8",
) as f:

    cache_manifest_check = (
        json.load(f)
    )


assert (
    cache_manifest_check[
        "status"
    ]
    == "FINAL_FEATURE_CACHE_LOCKED"
)


assert (
    cache_manifest_check[
        "source_cohort_sha256"
    ]
    == EXPECTED_COHORT_SHA256
)


assert (
    cache_manifest_check[
        "files"
    ][
        "X_classical"
    ][
        "sha256"
    ]
    ==
    sha256_file(
        CLASSICAL_CACHE_PATH
    )
)


assert (
    cache_manifest_check[
        "files"
    ][
        "X_tokens"
    ][
        "sha256"
    ]
    ==
    sha256_file(
        TOKEN_CACHE_PATH
    )
)


# ============================================================
# 21. FILE SIZES
# ============================================================

classical_mb = (
    CLASSICAL_CACHE_PATH
    .stat()
    .st_size
    / 1024**2
)

tokens_mb = (
    TOKEN_CACHE_PATH
    .stat()
    .st_size
    / 1024**2
)

labels_mb = (
    LABEL_CACHE_PATH
    .stat()
    .st_size
    / 1024**2
)

metadata_mb = (
    ROW_METADATA_PATH
    .stat()
    .st_size
    / 1024**2
)


# ============================================================
# 22. REPORT
# ============================================================

print("=" * 126)

print(
    "CELL 14 PASS - FINAL FEATURE/TOKEN CACHE "
    "BUILT, VERIFIED AND LOCKED"
)

print("=" * 126)

print(
    f"CACHE ACTION           : {CACHE_ACTION}"
)

print(
    "RESTART SAFE           : TRUE"
)

print(
    "MODEL TRAINING         : FALSE"
)

print(
    "SCALER FITTING         : FALSE"
)

print(
    f"FINAL ROWS             : {len(df):,}"
)

print(
    f"SOURCE COHORT SHA256   : "
    f"{EXPECTED_COHORT_SHA256}"
)

print("-" * 126)

print(
    "CLASSICAL CACHE"
)

print(
    f"Shape                  : "
    f"{X_classical_check.shape}"
)

print(
    f"dtype                  : "
    f"{X_classical_check.dtype}"
)

print(
    "Representation         : "
    "Length + AAC20 + DPC400"
)

print(
    f"Size                   : "
    f"{classical_mb:.2f} MB"
)

print(
    f"SHA256                 : "
    f"{CACHE_FILES['X_classical']['sha256']}"
)

print("-" * 126)

print(
    "DEEP TOKEN CACHE"
)

print(
    f"Shape                  : "
    f"{X_tokens_check.shape}"
)

print(
    f"dtype                  : "
    f"{X_tokens_check.dtype}"
)

print(
    "Representation         : "
    "AA20 integer tokens, post-padding L=200"
)

print(
    f"Size                   : "
    f"{tokens_mb:.2f} MB"
)

print(
    f"SHA256                 : "
    f"{CACHE_FILES['X_tokens']['sha256']}"
)

print("-" * 126)

print(
    "ALIGNMENT CHECK"
)

print(
    "sample_id alignment   : PASS"
)

print(
    "label alignment       : PASS"
)

print(
    "dataset/split align   : PASS"
)

print(
    "token length align    : PASS"
)

print(
    "fixed row rebuild     : PASS"
)

print("-" * 126)

print(
    "DATASET / SPLIT / LABEL INDEX SUMMARY"
)

print(
    cache_summary_df
    .to_string(
        index=False
    )
)

print("-" * 126)

print(
    f"Classical cache        : "
    f"{CLASSICAL_CACHE_PATH}"
)

print(
    f"Token cache            : "
    f"{TOKEN_CACHE_PATH}"
)

print(
    f"Label cache            : "
    f"{LABEL_CACHE_PATH}"
)

print(
    f"Row metadata           : "
    f"{ROW_METADATA_PATH}"
)

print(
    f"Cache manifest         : "
    f"{CACHE_MANIFEST_PATH}"
)

print(
    f"Cache audit            : "
    f"{CACHE_AUDIT_PATH}"
)

print("-" * 126)

print(
    f"Approx cache size      : "
    f"{classical_mb + tokens_mb + labels_mb + metadata_mb:.2f} MB"
)

print("=" * 126)

Processed 5,000/41,059
Processed 10,000/41,059
Processed 15,000/41,059
Processed 20,000/41,059
Processed 25,000/41,059
Processed 30,000/41,059
Processed 35,000/41,059
Processed 40,000/41,059
==============================================================================================================================
CELL 14 PASS - FINAL FEATURE/TOKEN CACHE BUILT, VERIFIED AND LOCKED
==============================================================================================================================
CACHE ACTION           : NEW CACHE BUILT
RESTART SAFE           : TRUE
MODEL TRAINING         : FALSE
SCALER FITTING         : FALSE
FINAL ROWS             : 41,059
SOURCE COHORT SHA256   : 205f292511f77ca7a3b9f0b2fd03549be60e9df29a62ce3b0b504f63935ad356
------------------------------------------------------------------------------------------------------------------------------
CLASSICAL CACHE
Shape                  : (41059, 421)
dtype                  : float32
Representation         : Length + AAC20 + DPC400
Size                   : 65.94 MB
SHA256                 : c3a8e1e52348922340e564834d2fa800b2affd64322c8f6b08aab9c0c4a15f88
------------------------------------------------------------------------------------------------------------------------------
DEEP TOKEN CACHE
Shape                  : (41059, 200)
dtype                  : int16
Representation         : AA20 integer tokens, post-padding L=200
Size                   : 15.66 MB
SHA256                 : e9ccde8f28ea6e7c18391c4ddf3fa5a2bfdbf545eaad6b295aceacdb942a9662
------------------------------------------------------------------------------------------------------------------------------
ALIGNMENT CHECK
sample_id alignment   : PASS
label alignment       : PASS
dataset/split align   : PASS
token length align    : PASS
fixed row rebuild     : PASS
------------------------------------------------------------------------------------------------------------------------------
DATASET / SPLIT / LABEL INDEX SUMMARY
             dataset      split  label    n  first_row_index  last_row_index
    AMPlify_balanced       test      0  806            40253           41058
    AMPlify_balanced       test      1  786            39467           40252
    AMPlify_balanced      train      0 2743            35752           38494
    AMPlify_balanced      train      1 2761            32991           35751
    AMPlify_balanced validation      0  485            38982           39466
    AMPlify_balanced validation      1  487            38495           38981
External_Benchmark_1       test      0  656            18500           19155
External_Benchmark_1       test      1  889            14713           15601
External_Benchmark_1      train      0 2597            15602           18198
External_Benchmark_1      train      1 2838            11000           13837
External_Benchmark_1 validation      0  301            18199           18499
External_Benchmark_1 validation      1  875            13838           14712
External_Benchmark_3       test      0 1060            31931           32990
External_Benchmark_3       test      1 1010            24910           25919
External_Benchmark_3      train      0 4949            25920           30868
External_Benchmark_3      train      1 4734            19156           23889
External_Benchmark_3 validation      0 1062            30869           31930
External_Benchmark_3 validation      1 1020            23890           24909
GenPept_Curated_2025       test      0 1155             3181            9832
GenPept_Curated_2025       test      1 1155                2           10995
GenPept_Curated_2025      train      0 3850             3182            9830
GenPept_Curated_2025      train      1 3850                0           10998
GenPept_Curated_2025 validation      0  495             3188            9819
GenPept_Curated_2025 validation      1  495               16           10999
------------------------------------------------------------------------------------------------------------------------------
Classical cache        : /home/pc/genpept_benchmark17_work/feature_cache/benchmark4_FINAL_v1/X_classical_421_float32.npy
Token cache            : /home/pc/genpept_benchmark17_work/feature_cache/benchmark4_FINAL_v1/X_tokens_L200_int16.npy
Label cache            : /home/pc/genpept_benchmark17_work/feature_cache/benchmark4_FINAL_v1/y_int8.npy
Row metadata           : /home/pc/genpept_benchmark17_work/feature_cache/benchmark4_FINAL_v1/row_metadata.csv
Cache manifest         : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_feature_cache_manifest.json
Cache audit            : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_FINAL_feature_cache_summary.csv
------------------------------------------------------------------------------------------------------------------------------
Approx cache size      : 86.57 MB
==============================================================================================================================

In [5]:
# ============================================================
# CELL 15 - RESTART-SAFE
# EXECUTION INDEX + RUN PLAN + RESULT SCHEMA LOCK
#
# PURPOSE
# -------
# 1. Restore ALL state from disk.
# 2. Verify FINAL feature caches.
# 3. Build immutable row-index arrays for:
#       - Protocol 1 train / validation / test
#       - Protocol 2 decontaminated target tests
# 4. Build immutable run plan for 10 controlled models:
#       10 models x 4 sources x 10 seeds = 400 trainings
#       400 trainings x 3 external targets = 1200 external evals
# 5. Lock artifact/result schemas.
#
# IMPORTANT
# ---------
# NO MODEL TRAINING
# NO SCALER FITTING
# NO TEST TUNING
# NO TARGET TUNING
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json

import numpy as np
import pandas as pd


# ============================================================
# 1. RESTORE PROJECT STATE
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

SPLIT_DIR = (
    OUTPUT_ROOT
    / "splits"
)

RESULTS_ROOT = (
    OUTPUT_ROOT
    / "results"
)

WORK_ROOT = Path(
    "/home/pc/genpept_benchmark17_work"
)

CACHE_ROOT = (
    WORK_ROOT
    / "feature_cache"
    / "benchmark4_FINAL_v1"
)

RUN_ROOT = (
    WORK_ROOT
    / "runs"
    / "benchmark4_FINAL_v1"
)

INDEX_ROOT = (
    WORK_ROOT
    / "execution_index"
    / "benchmark4_FINAL_v1"
)


for path in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    SPLIT_DIR,
    CACHE_ROOT,
]:

    assert path.is_dir(), (
        f"Required directory missing:\n{path}"
    )


RESULTS_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

RUN_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

INDEX_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# 2. SHA256 HELPER
# ============================================================

def sha256_file_cell15(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda: f.read(
                1024 * 1024
            ),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


# ============================================================
# 3. AUTHORITATIVE MANIFESTS
# ============================================================

BENCHMARK_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark4_FINAL_v1_manifest.json"
)

MODEL_REGISTRY_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_model_registry.json"
)

EXECUTION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_execution_contract.json"
)

EVALUATION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_evaluation_contract.json"
)

CONTROLLED_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_controlled_model_contract.json"
)

FEATURE_CACHE_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_feature_cache_manifest.json"
)


for path in [
    BENCHMARK_MANIFEST_PATH,
    MODEL_REGISTRY_PATH,
    EXECUTION_CONTRACT_PATH,
    EVALUATION_CONTRACT_PATH,
    CONTROLLED_CONTRACT_PATH,
    FEATURE_CACHE_MANIFEST_PATH,
]:

    assert path.is_file(), (
        f"Required locked artifact missing:\n{path}"
    )


def load_json(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as f:

        return json.load(f)


benchmark_manifest = load_json(
    BENCHMARK_MANIFEST_PATH
)

model_registry = load_json(
    MODEL_REGISTRY_PATH
)

execution_contract = load_json(
    EXECUTION_CONTRACT_PATH
)

evaluation_contract = load_json(
    EVALUATION_CONTRACT_PATH
)

controlled_payload = load_json(
    CONTROLLED_CONTRACT_PATH
)

feature_cache_manifest = load_json(
    FEATURE_CACHE_MANIFEST_PATH
)


controlled_contract = (
    controlled_payload[
        "contract"
    ]
)


# ============================================================
# 4. VERIFY LOCKED GLOBAL CONTRACT
# ============================================================

EXPECTED_DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "AMPlify_balanced",
    "External_Benchmark_3",
]

EXPECTED_SEEDS = list(
    range(100, 110)
)

SEEDS = EXPECTED_SEEDS


assert (
    benchmark_manifest[
        "datasets"
    ]
    == EXPECTED_DATASETS
)

assert (
    benchmark_manifest[
        "model_seeds"
    ]
    == EXPECTED_SEEDS
)

assert (
    benchmark_manifest[
        "protocol_2"
    ][
        "n_directional_pairs"
    ]
    == 12
)

assert (
    benchmark_manifest[
        "protocol_2"
    ][
        "residual_exact_overlap_all_pairs"
    ]
    == 0
)

assert (
    model_registry[
        "n_models"
    ]
    == 17
)

assert (
    controlled_payload[
        "status"
    ]
    == "CONTROLLED_MODELS_LOCKED_BEFORE_TRAINING"
)

assert (
    controlled_contract[
        "training_started"
    ]
    is False
)

assert (
    evaluation_contract[
        "status"
    ]
    == "LOCKED_BEFORE_MODEL_TRAINING"
)

assert (
    evaluation_contract[
        "model_seeds"
    ]
    == EXPECTED_SEEDS
)

assert (
    execution_contract[
        "contract"
    ][
        "protocol_1"
    ][
        "training_runs"
    ]
    == 680
)

assert (
    execution_contract[
        "contract"
    ][
        "protocol_2"
    ][
        "external_evaluations"
    ]
    == 2040
)


# ============================================================
# 5. CONTROLLED MODEL IDS
# ============================================================

CONTROLLED_MODEL_IDS = (
    controlled_contract[
        "controlled_model_ids"
    ]
)


EXPECTED_CONTROLLED_MODEL_IDS = [
    "logistic_regression",
    "linear_svm_calibrated",
    "random_forest",
    "extra_trees",
    "hist_gradient_boosting",
    "lightgbm",
    "cnn1d",
    "bilstm",
    "bilstm_attention",
    "transformer_encoder",
]


assert (
    CONTROLLED_MODEL_IDS
    == EXPECTED_CONTROLLED_MODEL_IDS
)

assert len(
    CONTROLLED_MODEL_IDS
) == 10


# ============================================================
# 6. VERIFY FEATURE CACHE FILES
# ============================================================

cache_files = (
    feature_cache_manifest[
        "files"
    ]
)


CLASSICAL_CACHE_PATH = Path(
    cache_files[
        "X_classical"
    ][
        "path"
    ]
)

TOKEN_CACHE_PATH = Path(
    cache_files[
        "X_tokens"
    ][
        "path"
    ]
)

LABEL_CACHE_PATH = Path(
    cache_files[
        "y"
    ][
        "path"
    ]
)

ROW_METADATA_PATH = Path(
    cache_files[
        "row_metadata"
    ][
        "path"
    ]
)


for key, path in [
    (
        "X_classical",
        CLASSICAL_CACHE_PATH,
    ),
    (
        "X_tokens",
        TOKEN_CACHE_PATH,
    ),
    (
        "y",
        LABEL_CACHE_PATH,
    ),
    (
        "row_metadata",
        ROW_METADATA_PATH,
    ),
]:

    assert path.is_file(), (
        f"Cache missing:\n{path}"
    )

    observed_hash = (
        sha256_file_cell15(
            path
        )
    )

    expected_hash = (
        cache_files[
            key
        ][
            "sha256"
        ]
    )

    assert (
        observed_hash
        == expected_hash
    ), (
        f"Cache SHA256 mismatch: {key}"
    )


# ============================================================
# 7. MEMORY-MAP CACHES
# ============================================================

X_CLASSICAL = np.load(
    CLASSICAL_CACHE_PATH,
    mmap_mode="r",
    allow_pickle=False,
)

X_TOKENS = np.load(
    TOKEN_CACHE_PATH,
    mmap_mode="r",
    allow_pickle=False,
)

Y = np.load(
    LABEL_CACHE_PATH,
    mmap_mode="r",
    allow_pickle=False,
)

ROW_META = pd.read_csv(
    ROW_METADATA_PATH,
    low_memory=False,
)


assert (
    X_CLASSICAL.shape
    == (
        41059,
        421,
    )
)

assert (
    X_TOKENS.shape
    == (
        41059,
        200,
    )
)

assert (
    Y.shape
    == (
        41059,
    )
)

assert len(
    ROW_META
) == 41059


assert np.array_equal(
    ROW_META[
        "row_index"
    ].to_numpy(
        dtype=np.int64
    ),
    np.arange(
        41059,
        dtype=np.int64,
    ),
)


assert np.array_equal(
    ROW_META[
        "label"
    ].to_numpy(
        dtype=np.int8
    ),
    Y,
)


assert ROW_META[
    "sample_id"
].is_unique


# ============================================================
# 8. SAMPLE-ID -> GLOBAL CACHE INDEX
# ============================================================

sample_to_index = pd.Series(
    ROW_META[
        "row_index"
    ].to_numpy(
        dtype=np.int64
    ),
    index=ROW_META[
        "sample_id"
    ].astype(str),
)


assert sample_to_index.index.is_unique


# ============================================================
# 9. BUILD PROTOCOL-1 INDEX ARRAYS
# ============================================================

INDEX_ARRAYS = {}

within_index_rows = []


for dataset_name in EXPECTED_DATASETS:

    for split_name in [
        "train",
        "validation",
        "test",
    ]:

        mask = (
            (
                ROW_META[
                    "dataset"
                ]
                == dataset_name
            )
            &
            (
                ROW_META[
                    "split"
                ]
                == split_name
            )
        )


        idx = (
            ROW_META.loc[
                mask,
                "row_index",
            ]
            .to_numpy(
                dtype=np.int64
            )
        )


        assert len(idx) > 0


        labels = np.asarray(
            Y[
                idx
            ],
            dtype=np.int8,
        )


        assert set(
            np.unique(
                labels
            ).tolist()
        ) == {
            0,
            1,
        }


        key = (
            f"within__"
            f"{dataset_name}"
            f"__{split_name}"
        )


        INDEX_ARRAYS[
            key
        ] = idx


        within_index_rows.append(
            {
                "dataset":
                    dataset_name,

                "split":
                    split_name,

                "n":
                    int(
                        len(idx)
                    ),

                "AMP":
                    int(
                        (
                            labels == 1
                        ).sum()
                    ),

                "non_AMP":
                    int(
                        (
                            labels == 0
                        ).sum()
                    ),

                "index_key":
                    key,
            }
        )


within_index_summary_df = (
    pd.DataFrame(
        within_index_rows
    )
)


assert len(
    within_index_summary_df
) == 12


# ============================================================
# 10. VERIFY PROTOCOL-1 COUNTS AGAINST FINAL MANIFEST
# ============================================================

within_manifest = (
    benchmark_manifest[
        "protocol_1"
    ][
        "files"
    ]
)


for row in (
    within_index_summary_df
    .itertuples(
        index=False
    )
):

    locked = (
        within_manifest[
            row.dataset
        ][
            row.split
        ]
    )


    assert int(
        locked[
            "n"
        ]
    ) == int(
        row.n
    )


    assert int(
        locked[
            "AMP"
        ]
    ) == int(
        row.AMP
    )


    assert int(
        locked[
            "non_AMP"
        ]
    ) == int(
        row.non_AMP
    )


# ============================================================
# 11. BUILD PROTOCOL-2 CLEAN TARGET INDEX ARRAYS
# ============================================================

pair_registry = (
    benchmark_manifest[
        "protocol_2"
    ][
        "pairs"
    ]
)


assert len(
    pair_registry
) == 12


cross_index_rows = []


for pair_id in sorted(
    pair_registry.keys()
):

    pair_info = (
        pair_registry[
            pair_id
        ]
    )


    source_dataset = (
        pair_info[
            "source_dataset"
        ]
    )

    target_dataset = (
        pair_info[
            "target_dataset"
        ]
    )


    assert (
        source_dataset
        != target_dataset
    )


    assert (
        source_dataset
        in EXPECTED_DATASETS
    )

    assert (
        target_dataset
        in EXPECTED_DATASETS
    )


    target_clean_path = Path(
        pair_info[
            "target_clean_path"
        ]
    )


    pair_manifest_path = Path(
        pair_info[
            "pair_manifest"
        ]
    )


    assert target_clean_path.is_file()

    assert pair_manifest_path.is_file()


    pair_manifest = load_json(
        pair_manifest_path
    )


    assert (
        pair_manifest[
            "source_dataset"
        ]
        == source_dataset
    )

    assert (
        pair_manifest[
            "target_dataset"
        ]
        == target_dataset
    )

    assert (
        pair_manifest[
            "decontamination"
        ][
            "residual_overlap"
        ]
        == 0
    )


    target_clean_df = pd.read_csv(
        target_clean_path,
        low_memory=False,
    )


    assert len(
        target_clean_df
    ) == int(
        pair_manifest[
            "target"
        ][
            "clean_n"
        ]
    )


    assert target_clean_df[
        "sample_id"
    ].is_unique


    assert set(
        target_clean_df[
            "label"
        ].unique()
    ) == {
        0,
        1,
    }


    mapped = (
        target_clean_df[
            "sample_id"
        ]
        .astype(str)
        .map(
            sample_to_index
        )
    )


    assert mapped.notna().all(), (
        f"Unmapped target sample_id: "
        f"{pair_id}"
    )


    idx = mapped.to_numpy(
        dtype=np.int64
    )


    assert len(
        np.unique(
            idx
        )
    ) == len(
        idx
    )


    # --------------------------------------------------------
    # Verify mapped rows really belong to target TEST
    # --------------------------------------------------------
    mapped_meta = (
        ROW_META.iloc[
            idx
        ]
        .reset_index(
            drop=True
        )
    )


    assert (
        mapped_meta[
            "dataset"
        ]
        == target_dataset
    ).all()


    assert (
        mapped_meta[
            "split"
        ]
        == "test"
    ).all()


    assert np.array_equal(
        mapped_meta[
            "label"
        ].to_numpy(
            dtype=np.int8
        ),
        target_clean_df[
            "label"
        ].to_numpy(
            dtype=np.int8
        ),
    )


    # --------------------------------------------------------
    # Verify exact sequence identity via stored SHA256
    # --------------------------------------------------------
    if (
        "sequence_sha256"
        in target_clean_df.columns
    ):

        assert np.array_equal(
            mapped_meta[
                "sequence_sha256"
            ].astype(str)
            .to_numpy(),
            target_clean_df[
                "sequence_sha256"
            ].astype(str)
            .to_numpy(),
        )


    key = (
        f"cross__"
        f"{source_dataset}"
        f"__TO__"
        f"{target_dataset}"
        f"__target_test"
    )


    INDEX_ARRAYS[
        key
    ] = idx


    labels = np.asarray(
        Y[
            idx
        ],
        dtype=np.int8,
    )


    amp_n = int(
        (
            labels == 1
        ).sum()
    )

    nonamp_n = int(
        (
            labels == 0
        ).sum()
    )


    assert amp_n == int(
        pair_manifest[
            "target"
        ][
            "AMP_clean"
        ]
    )


    assert nonamp_n == int(
        pair_manifest[
            "target"
        ][
            "non_AMP_clean"
        ]
    )


    assert min(
        amp_n,
        nonamp_n,
    ) >= 100


    cross_index_rows.append(
        {
            "pair_id":
                pair_id,

            "source_dataset":
                source_dataset,

            "target_dataset":
                target_dataset,

            "n":
                int(
                    len(idx)
                ),

            "AMP":
                amp_n,

            "non_AMP":
                nonamp_n,

            "minority_class_n":
                int(
                    min(
                        amp_n,
                        nonamp_n,
                    )
                ),

            "index_key":
                key,

            "residual_exact_overlap":
                0,
        }
    )


cross_index_summary_df = (
    pd.DataFrame(
        cross_index_rows
    )
)


assert len(
    cross_index_summary_df
) == 12


assert (
    cross_index_summary_df[
        "residual_exact_overlap"
    ]
    == 0
).all()


assert (
    cross_index_summary_df[
        "minority_class_n"
    ]
    >= 100
).all()


# ============================================================
# 12. INDEX CACHE PATH
# ============================================================

INDEX_CACHE_PATH = (
    INDEX_ROOT
    / "benchmark4_FINAL_v1_execution_indices.npz"
)


# ============================================================
# 13. IDEMPOTENT INDEX CACHE
# ============================================================

if INDEX_CACHE_PATH.exists():

    with np.load(
        INDEX_CACHE_PATH,
        allow_pickle=False,
    ) as old_indices:

        assert set(
            old_indices.files
        ) == set(
            INDEX_ARRAYS.keys()
        ), (
            "Existing execution-index keys differ."
        )


        for key in (
            INDEX_ARRAYS.keys()
        ):

            assert np.array_equal(
                old_indices[
                    key
                ],
                INDEX_ARRAYS[
                    key
                ],
            ), (
                f"Execution index differs: {key}"
            )


    INDEX_ACTION = (
        "EXISTING IDENTICAL INDEX CACHE VERIFIED"
    )

else:

    np.savez_compressed(
        INDEX_CACHE_PATH,
        **INDEX_ARRAYS,
    )


    INDEX_ACTION = (
        "NEW EXECUTION INDEX CACHE CREATED"
    )


assert INDEX_CACHE_PATH.is_file()


INDEX_CACHE_SHA256 = (
    sha256_file_cell15(
        INDEX_CACHE_PATH
    )
)


# ============================================================
# 14. RESULT / ARTIFACT SCHEMA
# ============================================================

PREDICTION_COLUMNS = [
    "run_id",
    "protocol",
    "model_id",
    "source_dataset",
    "target_dataset",
    "seed",
    "sample_id",
    "y_true",
    "y_score",
    "y_pred",
    "threshold",
]


METRIC_COLUMNS = [
    "run_id",
    "protocol",
    "model_id",
    "source_dataset",
    "target_dataset",
    "seed",
    "AUROC",
    "AUPRC",
    "MCC",
    "BACC",
    "F1",
    "ACC",
    "Sensitivity",
    "Specificity",
    "Brier",
    "ECE10",
    "threshold",
    "TP",
    "TN",
    "FP",
    "FN",
    "n",
    "n_positive",
    "n_negative",
]


RESOURCE_COLUMNS = [
    "run_id",
    "model_id",
    "source_dataset",
    "seed",
    "device",
    "feature_or_token_load_seconds",
    "preprocessing_seconds",
    "training_seconds",
    "validation_seconds",
    "source_test_inference_seconds",
    "source_test_ms_per_sequence",
    "source_test_sequences_per_second",
    "peak_process_ram_mb",
    "peak_gpu_vram_mb",
    "model_parameter_count",
    "checkpoint_size_mb",
]


TRAINING_HISTORY_REQUIRED_FIELDS = [
    "epoch",
    "loss",
    "val_loss",
]


RUN_MANIFEST_REQUIRED_FIELDS = [
    "run_id",
    "model_id",
    "source_dataset",
    "seed",
    "benchmark_version",
    "controlled_contract_sha256",
    "evaluation_contract_sha256",
    "feature_cache_manifest_sha256",
    "train_index_key",
    "validation_index_key",
    "source_test_index_key",
    "validation_threshold",
    "status",
]


RUN_STATUS_VALUES = [
    "PLANNED",
    "RUNNING",
    "TRAINED",
    "EVALUATED",
    "COMPLETE",
    "FAILED",
]


ARTIFACT_SCHEMA = {

    "schema_version":
        "1.0",

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "prediction_columns":
        PREDICTION_COLUMNS,

    "metric_columns":
        METRIC_COLUMNS,

    "resource_columns":
        RESOURCE_COLUMNS,

    "training_history_required_fields":
        TRAINING_HISTORY_REQUIRED_FIELDS,

    "run_manifest_required_fields":
        RUN_MANIFEST_REQUIRED_FIELDS,

    "run_status_values":
        RUN_STATUS_VALUES,

    "per_run_files": {

        "config":
            "config.json",

        "run_manifest":
            "run_manifest.json",

        "validation_predictions":
            "validation_predictions.csv",

        "source_test_predictions":
            "source_test_predictions.csv",

        "source_test_metrics":
            "source_test_metrics.json",

        "threshold":
            "validation_threshold.json",

        "training_history":
            "history.csv",

        "resources":
            "resources.json",

        "checkpoint":
            "checkpoint.model_or_framework_native",
    },

    "protocol2_target_files": {

        "predictions":
            (
                "external/"
                "<target_dataset>/predictions.csv"
            ),

        "metrics":
            (
                "external/"
                "<target_dataset>/metrics.json"
            ),
    },

    "prediction_score_range":
        [
            0.0,
            1.0,
        ],

    "positive_label":
        1,

    "positive_class":
        "AMP",

    "threshold_source":
        "source_validation_only",

    "protocol2_threshold_reuse":
        True,

    "target_threshold_tuning":
        False,
}


# ============================================================
# 15. BUILD IMMUTABLE CONTROLLED RUN PLAN
#
# One training per:
# model x source dataset x seed
#
# That trained source model is reused for:
# - source test
# - 3 decontaminated external target tests
# ============================================================

run_plan_rows = []

job_no = 0


for model_id in CONTROLLED_MODEL_IDS:

    for source_dataset in EXPECTED_DATASETS:

        train_key = (
            f"within__"
            f"{source_dataset}"
            f"__train"
        )

        validation_key = (
            f"within__"
            f"{source_dataset}"
            f"__validation"
        )

        source_test_key = (
            f"within__"
            f"{source_dataset}"
            f"__test"
        )


        train_n = int(
            len(
                INDEX_ARRAYS[
                    train_key
                ]
            )
        )

        validation_n = int(
            len(
                INDEX_ARRAYS[
                    validation_key
                ]
            )
        )

        source_test_n = int(
            len(
                INDEX_ARRAYS[
                    source_test_key
                ]
            )
        )


        external_targets = [
            target
            for target
            in EXPECTED_DATASETS
            if (
                target
                != source_dataset
            )
        ]


        assert len(
            external_targets
        ) == 3


        for seed in EXPECTED_SEEDS:

            job_no += 1


            run_id = (
                f"{model_id}"
                f"__{source_dataset}"
                f"__seed_{seed:03d}"
            )


            run_dir = (
                RUN_ROOT
                / model_id
                / source_dataset
                / f"seed_{seed:03d}"
            )


            run_plan_rows.append(
                {
                    "job_no":
                        job_no,

                    "run_id":
                        run_id,

                    "model_id":
                        model_id,

                    "source_dataset":
                        source_dataset,

                    "seed":
                        int(seed),

                    "train_index_key":
                        train_key,

                    "validation_index_key":
                        validation_key,

                    "source_test_index_key":
                        source_test_key,

                    "train_n":
                        train_n,

                    "validation_n":
                        validation_n,

                    "source_test_n":
                        source_test_n,

                    "external_target_1":
                        external_targets[
                            0
                        ],

                    "external_target_2":
                        external_targets[
                            1
                        ],

                    "external_target_3":
                        external_targets[
                            2
                        ],

                    "n_external_targets":
                        3,

                    "run_dir":
                        str(
                            run_dir
                        ),
                }
            )


controlled_run_plan_df = pd.DataFrame(
    run_plan_rows
)


# ============================================================
# 16. RUN PLAN HARD ASSERTIONS
# ============================================================

assert len(
    controlled_run_plan_df
) == 400


assert controlled_run_plan_df[
    "run_id"
].is_unique


assert (
    controlled_run_plan_df[
        "seed"
    ]
    .unique()
    .tolist()
    == EXPECTED_SEEDS
)


assert (
    controlled_run_plan_df
    .groupby(
        [
            "model_id",
            "source_dataset",
        ]
    )
    .size()
    .eq(
        10
    )
    .all()
)


assert (
    controlled_run_plan_df[
        "n_external_targets"
    ]
    == 3
).all()


CONTROLLED_TRAIN_RUNS = int(
    len(
        controlled_run_plan_df
    )
)

CONTROLLED_EXTERNAL_EVALS = int(
    CONTROLLED_TRAIN_RUNS
    * 3
)


assert CONTROLLED_TRAIN_RUNS == 400

assert CONTROLLED_EXTERNAL_EVALS == 1200


# ============================================================
# 17. RUN PLAN OUTPUT
# ============================================================

CONTROLLED_RUN_PLAN_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_controlled_run_plan.csv"
)


if CONTROLLED_RUN_PLAN_PATH.exists():

    old_run_plan = pd.read_csv(
        CONTROLLED_RUN_PLAN_PATH,
        low_memory=False,
    )


    pd.testing.assert_frame_equal(
        old_run_plan.reset_index(
            drop=True
        ),
        controlled_run_plan_df.reset_index(
            drop=True
        ),
        check_dtype=False,
    )


    RUN_PLAN_ACTION = (
        "EXISTING IDENTICAL RUN PLAN VERIFIED"
    )

else:

    controlled_run_plan_df.to_csv(
        CONTROLLED_RUN_PLAN_PATH,
        index=False,
    )


    RUN_PLAN_ACTION = (
        "NEW CONTROLLED RUN PLAN CREATED"
    )


# ============================================================
# 18. SAVE INDEX AUDIT TABLES
# ============================================================

WITHIN_INDEX_AUDIT_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_within_index_registry.csv"
)

CROSS_INDEX_AUDIT_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_cross_index_registry.csv"
)


within_index_summary_df.to_csv(
    WITHIN_INDEX_AUDIT_PATH,
    index=False,
)

cross_index_summary_df.to_csv(
    CROSS_INDEX_AUDIT_PATH,
    index=False,
)


# ============================================================
# 19. SAVE RESULT SCHEMA IDEMPOTENTLY
# ============================================================

ARTIFACT_SCHEMA_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_run_artifact_schema.json"
)


if ARTIFACT_SCHEMA_PATH.exists():

    old_artifact_schema = load_json(
        ARTIFACT_SCHEMA_PATH
    )


    assert (
        old_artifact_schema[
            "schema"
        ]
        == ARTIFACT_SCHEMA
    ), (
        "Existing artifact schema differs. "
        "Do NOT silently overwrite."
    )


    ARTIFACT_SCHEMA_ACTION = (
        "EXISTING IDENTICAL ARTIFACT SCHEMA VERIFIED"
    )

else:

    artifact_payload = {

        "created_at":
            datetime.now()
            .astimezone()
            .isoformat(),

        "status":
            "LOCKED_BEFORE_MODEL_TRAINING",

        "schema":
            ARTIFACT_SCHEMA,
    }


    with open(
        ARTIFACT_SCHEMA_PATH,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            artifact_payload,
            f,
            indent=2,
            ensure_ascii=False,
        )


    ARTIFACT_SCHEMA_ACTION = (
        "NEW ARTIFACT SCHEMA CREATED"
    )


# ============================================================
# 20. HASH ALL IMMUTABLE INPUT CONTRACTS
# ============================================================

CONTROLLED_CONTRACT_SHA256 = (
    sha256_file_cell15(
        CONTROLLED_CONTRACT_PATH
    )
)

EVALUATION_CONTRACT_SHA256 = (
    sha256_file_cell15(
        EVALUATION_CONTRACT_PATH
    )
)

FEATURE_CACHE_MANIFEST_SHA256 = (
    sha256_file_cell15(
        FEATURE_CACHE_MANIFEST_PATH
    )
)

RUN_PLAN_SHA256 = (
    sha256_file_cell15(
        CONTROLLED_RUN_PLAN_PATH
    )
)

ARTIFACT_SCHEMA_SHA256 = (
    sha256_file_cell15(
        ARTIFACT_SCHEMA_PATH
    )
)


# ============================================================
# 21. EXECUTION MANIFEST CORE
# ============================================================

EXECUTION_INDEX_MANIFEST_CORE = {

    "schema_version":
        "1.0",

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "status":
        "CONTROLLED_EXECUTION_INFRASTRUCTURE_LOCKED",

    "training_started":
        False,

    "datasets":
        EXPECTED_DATASETS,

    "controlled_models":
        CONTROLLED_MODEL_IDS,

    "seeds":
        EXPECTED_SEEDS,

    "controlled_training_jobs":
        400,

    "controlled_external_evaluations":
        1200,

    "all_17_training_jobs_eventually":
        680,

    "all_17_external_evaluations_eventually":
        2040,

    "one_source_training_reused_for_three_targets":
        True,

    "index_cache": {

        "path":
            str(
                INDEX_CACHE_PATH
            ),

        "sha256":
            INDEX_CACHE_SHA256,

        "n_arrays":
            int(
                len(
                    INDEX_ARRAYS
                )
            ),

        "n_within_arrays":
            12,

        "n_cross_target_arrays":
            12,
    },

    "run_plan": {

        "path":
            str(
                CONTROLLED_RUN_PLAN_PATH
            ),

        "sha256":
            RUN_PLAN_SHA256,

        "n_jobs":
            400,
    },

    "artifact_schema": {

        "path":
            str(
                ARTIFACT_SCHEMA_PATH
            ),

        "sha256":
            ARTIFACT_SCHEMA_SHA256,
    },

    "upstream_contracts": {

        "controlled_model_contract": {

            "path":
                str(
                    CONTROLLED_CONTRACT_PATH
                ),

            "sha256":
                CONTROLLED_CONTRACT_SHA256,
        },

        "evaluation_contract": {

            "path":
                str(
                    EVALUATION_CONTRACT_PATH
                ),

            "sha256":
                EVALUATION_CONTRACT_SHA256,
        },

        "feature_cache_manifest": {

            "path":
                str(
                    FEATURE_CACHE_MANIFEST_PATH
                ),

            "sha256":
                FEATURE_CACHE_MANIFEST_SHA256,
        },
    },

    "run_root":
        str(
            RUN_ROOT
        ),

    "final_results_root":
        str(
            RESULTS_ROOT
        ),

    "source_train_only_model_fitting":
        True,

    "source_validation_only_threshold_selection":
        True,

    "source_test_final_evaluation_only":
        True,

    "protocol2_target_test_only":
        True,

    "protocol2_target_adaptation":
        False,
}


# ============================================================
# 22. IDEMPOTENT EXECUTION MANIFEST LOCK
# ============================================================

EXECUTION_INDEX_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_controlled_execution_manifest.json"
)


if EXECUTION_INDEX_MANIFEST_PATH.exists():

    old_execution_index_manifest = load_json(
        EXECUTION_INDEX_MANIFEST_PATH
    )


    old_core = {
        key: value
        for key, value
        in old_execution_index_manifest.items()
        if key != "created_at"
    }


    assert (
        old_core
        == EXECUTION_INDEX_MANIFEST_CORE
    ), (
        "Existing controlled execution manifest "
        "differs from current verified state.\n"
        "Do NOT overwrite."
    )


    EXECUTION_MANIFEST_ACTION = (
        "EXISTING IDENTICAL EXECUTION MANIFEST VERIFIED"
    )

else:

    execution_index_payload = {

        "created_at":
            datetime.now()
            .astimezone()
            .isoformat(),

        **EXECUTION_INDEX_MANIFEST_CORE,
    }


    with open(
        EXECUTION_INDEX_MANIFEST_PATH,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            execution_index_payload,
            f,
            indent=2,
            ensure_ascii=False,
        )


    EXECUTION_MANIFEST_ACTION = (
        "NEW EXECUTION MANIFEST CREATED"
    )


# ============================================================
# 23. RE-READ FROM DISK
# ============================================================

execution_index_check = load_json(
    EXECUTION_INDEX_MANIFEST_PATH
)


assert (
    execution_index_check[
        "status"
    ]
    == "CONTROLLED_EXECUTION_INFRASTRUCTURE_LOCKED"
)

assert (
    execution_index_check[
        "training_started"
    ]
    is False
)

assert (
    execution_index_check[
        "controlled_training_jobs"
    ]
    == 400
)

assert (
    execution_index_check[
        "controlled_external_evaluations"
    ]
    == 1200
)

assert (
    execution_index_check[
        "index_cache"
    ][
        "n_within_arrays"
    ]
    == 12
)

assert (
    execution_index_check[
        "index_cache"
    ][
        "n_cross_target_arrays"
    ]
    == 12
)


# ============================================================
# 24. FINAL CROSS-DATASET SUPPORT CHECK
# ============================================================

MIN_CROSS_SUPPORT = int(
    cross_index_summary_df[
        "minority_class_n"
    ].min()
)


assert MIN_CROSS_SUPPORT == 309


assert (
    cross_index_summary_df[
        "residual_exact_overlap"
    ]
    == 0
).all()


# ============================================================
# 25. REPORT
# ============================================================

print("=" * 128)

print(
    "CELL 15 PASS - EXECUTION INDEX, CONTROLLED RUN PLAN "
    "AND RESULT SCHEMA LOCKED"
)

print("=" * 128)

print(
    f"INDEX ACTION           : {INDEX_ACTION}"
)

print(
    f"RUN PLAN ACTION        : {RUN_PLAN_ACTION}"
)

print(
    f"ARTIFACT SCHEMA        : {ARTIFACT_SCHEMA_ACTION}"
)

print(
    f"EXECUTION MANIFEST     : {EXECUTION_MANIFEST_ACTION}"
)

print(
    "RESTART SAFE           : TRUE"
)

print(
    "MODEL TRAINING         : FALSE"
)

print("-" * 128)

print(
    "CONTROLLED EXECUTION PLAN"
)

print(
    f"Models                 : {len(CONTROLLED_MODEL_IDS)}"
)

print(
    f"Datasets / sources     : {len(EXPECTED_DATASETS)}"
)

print(
    f"Seeds                  : {EXPECTED_SEEDS}"
)

print(
    f"Training jobs          : {CONTROLLED_TRAIN_RUNS}"
)

print(
    f"External evaluations   : {CONTROLLED_EXTERNAL_EVALS}"
)

print(
    "Additional Protocol-2 training : 0"
)

print("-" * 128)

print(
    "PROTOCOL 1 INDEX REGISTRY"
)

print(
    within_index_summary_df[
        [
            "dataset",
            "split",
            "n",
            "AMP",
            "non_AMP",
            "index_key",
        ]
    ].to_string(
        index=False
    )
)

print("-" * 128)

print(
    "PROTOCOL 2 CLEAN TARGET INDEX REGISTRY"
)

print(
    cross_index_summary_df[
        [
            "source_dataset",
            "target_dataset",
            "n",
            "AMP",
            "non_AMP",
            "minority_class_n",
            "residual_exact_overlap",
        ]
    ].to_string(
        index=False
    )
)

print("-" * 128)

print(
    f"Minimum external minority support : "
    f"{MIN_CROSS_SUPPORT}"
)

print(
    "Residual exact overlap           : "
    "0 FOR ALL 12 PAIRS"
)

print("-" * 128)

print(
    "RESULT SCHEMA"
)

print(
    f"Prediction columns      : "
    f"{len(PREDICTION_COLUMNS)}"
)

print(
    f"Metric columns          : "
    f"{len(METRIC_COLUMNS)}"
)

print(
    f"Resource fields         : "
    f"{len(RESOURCE_COLUMNS)}"
)

print(
    "Checkpoint per run     : REQUIRED"
)

print(
    "Validation predictions : REQUIRED"
)

print(
    "Source-test predictions: REQUIRED"
)

print(
    "External predictions   : REQUIRED"
)

print(
    "Validation threshold   : REQUIRED"
)

print("-" * 128)

print(
    f"Run root               : {RUN_ROOT}"
)

print(
    f"Final results root     : {RESULTS_ROOT}"
)

print(
    f"Index cache            : {INDEX_CACHE_PATH}"
)

print(
    f"Index cache SHA256     : {INDEX_CACHE_SHA256}"
)

print(
    f"Controlled run plan    : {CONTROLLED_RUN_PLAN_PATH}"
)

print(
    f"Run plan SHA256        : {RUN_PLAN_SHA256}"
)

print(
    f"Artifact schema        : {ARTIFACT_SCHEMA_PATH}"
)

print(
    f"Execution manifest     : {EXECUTION_INDEX_MANIFEST_PATH}"
)

print("-" * 128)

print(
    "NO TRAINING HAS BEEN PERFORMED."
)

print(
    "NEXT REQUIRED STAGE BEFORE FIRST RESULT:"
)

print(
    "AUDIT AND LOCK IMPLEMENTATION ROUTES FOR "
    "ALL 7 PUBLISHED AMP METHODS."
)

print("=" * 128)

================================================================================================================================
CELL 15 PASS - EXECUTION INDEX, CONTROLLED RUN PLAN AND RESULT SCHEMA LOCKED
================================================================================================================================
INDEX ACTION           : NEW EXECUTION INDEX CACHE CREATED
RUN PLAN ACTION        : NEW CONTROLLED RUN PLAN CREATED
ARTIFACT SCHEMA        : NEW ARTIFACT SCHEMA CREATED
EXECUTION MANIFEST     : NEW EXECUTION MANIFEST CREATED
RESTART SAFE           : TRUE
MODEL TRAINING         : FALSE
--------------------------------------------------------------------------------------------------------------------------------
CONTROLLED EXECUTION PLAN
Models                 : 10
Datasets / sources     : 4
Seeds                  : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
Training jobs          : 400
External evaluations   : 1200
Additional Protocol-2 training : 0
--------------------------------------------------------------------------------------------------------------------------------
PROTOCOL 1 INDEX REGISTRY
             dataset      split    n  AMP  non_AMP                                index_key
GenPept_Curated_2025      train 7700 3850     3850      within__GenPept_Curated_2025__train
GenPept_Curated_2025 validation  990  495      495 within__GenPept_Curated_2025__validation
GenPept_Curated_2025       test 2310 1155     1155       within__GenPept_Curated_2025__test
External_Benchmark_1      train 5435 2838     2597      within__External_Benchmark_1__train
External_Benchmark_1 validation 1176  875      301 within__External_Benchmark_1__validation
External_Benchmark_1       test 1545  889      656       within__External_Benchmark_1__test
    AMPlify_balanced      train 5504 2761     2743          within__AMPlify_balanced__train
    AMPlify_balanced validation  972  487      485     within__AMPlify_balanced__validation
    AMPlify_balanced       test 1592  786      806           within__AMPlify_balanced__test
External_Benchmark_3      train 9683 4734     4949      within__External_Benchmark_3__train
External_Benchmark_3 validation 2082 1020     1062 within__External_Benchmark_3__validation
External_Benchmark_3       test 2070 1010     1060       within__External_Benchmark_3__test
--------------------------------------------------------------------------------------------------------------------------------
PROTOCOL 2 CLEAN TARGET INDEX REGISTRY
      source_dataset       target_dataset    n  AMP  non_AMP  minority_class_n  residual_exact_overlap
    AMPlify_balanced External_Benchmark_1  957  309      648               309                       0
    AMPlify_balanced External_Benchmark_3 1910  850     1060               850                       0
    AMPlify_balanced GenPept_Curated_2025 2295 1146     1149              1146                       0
External_Benchmark_1     AMPlify_balanced 1156  366      790               366                       0
External_Benchmark_1 External_Benchmark_3 1905  845     1060               845                       0
External_Benchmark_1 GenPept_Curated_2025 2290 1137     1153              1137                       0
External_Benchmark_3     AMPlify_balanced 1397  593      804               593                       0
External_Benchmark_3 External_Benchmark_1 1322  666      656               656                       0
External_Benchmark_3 GenPept_Curated_2025 2301 1147     1154              1147                       0
GenPept_Curated_2025     AMPlify_balanced 1582  784      798               784                       0
GenPept_Curated_2025 External_Benchmark_1 1530  874      656               656                       0
GenPept_Curated_2025 External_Benchmark_3 2061 1001     1060              1001                       0
--------------------------------------------------------------------------------------------------------------------------------
Minimum external minority support : 309
Residual exact overlap           : 0 FOR ALL 12 PAIRS
--------------------------------------------------------------------------------------------------------------------------------
RESULT SCHEMA
Prediction columns      : 11
Metric columns          : 24
Resource fields         : 16
Checkpoint per run     : REQUIRED
Validation predictions : REQUIRED
Source-test predictions: REQUIRED
External predictions   : REQUIRED
Validation threshold   : REQUIRED
--------------------------------------------------------------------------------------------------------------------------------
Run root               : /home/pc/genpept_benchmark17_work/runs/benchmark4_FINAL_v1
Final results root     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results
Index cache            : /home/pc/genpept_benchmark17_work/execution_index/benchmark4_FINAL_v1/benchmark4_FINAL_v1_execution_indices.npz
Index cache SHA256     : 78d396c49c35cbc0a8fca71e30257621bfe9575c084b88e9867a9c63e192d32c
Controlled run plan    : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_FINAL_controlled_run_plan.csv
Run plan SHA256        : 897c819fcd66a20f6fabe342139a0313d8d44642662ecef31eea4cb9b3b4282b
Artifact schema        : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_run_artifact_schema.json
Execution manifest     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_controlled_execution_manifest.json
--------------------------------------------------------------------------------------------------------------------------------
NO TRAINING HAS BEEN PERFORMED.
NEXT REQUIRED STAGE BEFORE FIRST RESULT:
AUDIT AND LOCK IMPLEMENTATION ROUTES FOR ALL 7 PUBLISHED AMP METHODS.
================================================================================================================================

In [6]:
# ============================================================
# CELL 16 - RESTART-SAFE
# PUBLISHED AMP METHODS:
# ROUTE LOCK + LOCAL READINESS AUDIT
#
# PURPOSE
# -------
# Lock the scientific implementation route for:
#
# 11. AmPEP
# 12. AMPScannerV2
# 13. AmpGram
# 14. ampir
# 15. amPEPpy
# 16. AI4AMP
# 17. AMPlify
#
# IMPORTANT
# ---------
# - NO MODEL TRAINING
# - NO PACKAGE INSTALLATION
# - NO SOURCE DOWNLOAD
# - NO TEST RESULTS
# - NO TARGET RESULTS
#
# Route contract is immutable.
# Local readiness audit may change later as sources/envs
# are prepared.
# ============================================================


from pathlib import Path
from datetime import datetime

import hashlib
import json
import platform
import shutil
import subprocess
import sys

import pandas as pd


# ============================================================
# 1. RESTORE PROJECT STATE FROM DISK
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

WORK_ROOT = Path(
    "/home/pc/genpept_benchmark17_work"
)

SOURCE_ROOT = Path(
    "/home/pc/genpept_sources"
)


for path in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    WORK_ROOT,
]:

    assert path.is_dir(), (
        f"Required directory missing:\n{path}"
    )


SOURCE_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# 2. HELPERS
# ============================================================

def load_json(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as f:

        return json.load(f)


def sha256_file(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda: f.read(
                1024 * 1024
            ),
            b"",
        ):

            h.update(chunk)

    return h.hexdigest()


def run_command(
    command,
    timeout=30,
):

    try:

        result = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout,
            check=False,
        )

        return {
            "returncode":
                int(
                    result.returncode
                ),

            "stdout":
                result.stdout.strip(),

            "stderr":
                result.stderr.strip(),
        }

    except Exception as exc:

        return {
            "returncode":
                -999,

            "stdout":
                "",

            "stderr":
                repr(exc),
        }


def first_existing_source(
    candidates,
    required_any=None,
):

    if required_any is None:
        required_any = []


    for candidate in candidates:

        candidate = Path(
            candidate
        )


        if not candidate.is_dir():
            continue


        if len(
            required_any
        ) == 0:

            return candidate


        marker_found = False


        for marker in required_any:

            marker_path = (
                candidate
                / marker
            )


            if marker_path.exists():

                marker_found = True
                break


        if marker_found:

            return candidate


    return None


def git_commit_or_none(
    path,
):

    if path is None:
        return None


    path = Path(
        path
    )


    if not (
        path
        / ".git"
    ).exists():

        return None


    result = run_command(
        [
            "git",
            "-C",
            str(path),
            "rev-parse",
            "HEAD",
        ]
    )


    if result[
        "returncode"
    ] != 0:

        return None


    commit = result[
        "stdout"
    ].strip()


    if len(
        commit
    ) == 40:

        return commit


    return None


# ============================================================
# 3. LOAD ALL UPSTREAM LOCKS
# ============================================================

BENCHMARK_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark4_FINAL_v1_manifest.json"
)

MODEL_REGISTRY_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_model_registry.json"
)

EXECUTION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_execution_contract.json"
)

EVALUATION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_evaluation_contract.json"
)

CONTROLLED_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_controlled_model_contract.json"
)

FEATURE_CACHE_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_feature_cache_manifest.json"
)

CONTROLLED_EXECUTION_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_controlled_execution_manifest.json"
)


for path in [
    BENCHMARK_MANIFEST_PATH,
    MODEL_REGISTRY_PATH,
    EXECUTION_CONTRACT_PATH,
    EVALUATION_CONTRACT_PATH,
    CONTROLLED_CONTRACT_PATH,
    FEATURE_CACHE_MANIFEST_PATH,
    CONTROLLED_EXECUTION_PATH,
]:

    assert path.is_file(), (
        f"Required upstream lock missing:\n{path}"
    )


benchmark_manifest = load_json(
    BENCHMARK_MANIFEST_PATH
)

model_registry = load_json(
    MODEL_REGISTRY_PATH
)

execution_contract = load_json(
    EXECUTION_CONTRACT_PATH
)

evaluation_contract = load_json(
    EVALUATION_CONTRACT_PATH
)

controlled_contract = load_json(
    CONTROLLED_CONTRACT_PATH
)

feature_cache_manifest = load_json(
    FEATURE_CACHE_MANIFEST_PATH
)

controlled_execution = load_json(
    CONTROLLED_EXECUTION_PATH
)


# ============================================================
# 4. VERIFY GLOBAL LOCK STATE
# ============================================================

EXPECTED_DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "AMPlify_balanced",
    "External_Benchmark_3",
]

EXPECTED_SEEDS = list(
    range(100, 110)
)


assert (
    benchmark_manifest[
        "datasets"
    ]
    == EXPECTED_DATASETS
)


assert (
    benchmark_manifest[
        "model_seeds"
    ]
    == EXPECTED_SEEDS
)


assert (
    model_registry[
        "n_models"
    ]
    == 17
)


assert (
    execution_contract[
        "contract"
    ][
        "protocol_1"
    ][
        "training_runs"
    ]
    == 680
)


assert (
    execution_contract[
        "contract"
    ][
        "protocol_2"
    ][
        "external_evaluations"
    ]
    == 2040
)


assert (
    evaluation_contract[
        "training_started"
    ]
    is False
)


assert (
    controlled_contract[
        "contract"
    ][
        "training_started"
    ]
    is False
)


assert (
    controlled_execution[
        "training_started"
    ]
    is False
)


SEEDS = EXPECTED_SEEDS


# ============================================================
# 5. VERIFY EXACT 7 PUBLISHED METHODS
# ============================================================

EXPECTED_PUBLISHED_IDS = [
    "ampep",
    "ampscannerv2",
    "ampgram",
    "ampir",
    "ampeppy",
    "ai4amp",
    "amplify",
]


published_registry_rows = [
    row
    for row
    in model_registry[
        "models"
    ]
    if (
        row[
            "group"
        ]
        == "published_amp_method"
    )
]


published_ids = [
    row[
        "model_id"
    ]
    for row
    in published_registry_rows
]


assert (
    published_ids
    == EXPECTED_PUBLISHED_IDS
), (
    "Published-method registry changed."
)


assert len(
    published_ids
) == 7


# ============================================================
# 6. IMMUTABLE SCIENTIFIC ROUTE CONTRACT
#
# IMPORTANT:
# This locks WHICH implementation strategy will be used.
#
# It does NOT yet claim that every implementation is ready.
# ============================================================

PUBLISHED_ROUTE_CONTRACT = {


    # --------------------------------------------------------
    # 11. AmPEP
    # --------------------------------------------------------
    "ampep": {

        "display_name":
            "AmPEP",

        "paper_year":
            2018,

        "paper_doi":
            "10.1038/s41598-018-19752-w",

        "published_family":
            "random_forest",

        "published_representation":
            (
                "selected_distribution_descriptors_"
                "of_amino_acid_properties"
            ),

        "reported_selected_features":
            23,

        "original_training_software":
            "MATLAB_TreeBagger",

        "official_public_training_repo":
            False,

        "locked_route":
            "faithful_reimplementation_from_publication",

        "implementation_language":
            "Python",

        "implementation_environment":
            "dedicated_adapter_or_master",

        "pretrained_repeated_inference_allowed":
            False,

        "ten_independent_retraining_runs":
            True,

        "must_match_published_representation":
            True,

        "must_match_published_RF_method":
            True,

        "config_lock_required_before_training":
            True,
    },


    # --------------------------------------------------------
    # 12. AMPScannerV2
    # --------------------------------------------------------
    "ampscannerv2": {

        "display_name":
            "AMPScannerV2",

        "paper_year":
            2018,

        "paper_doi":
            "10.1093/bioinformatics/bty179",

        "published_family":
            "deep_neural_network",

        "published_representation":
            "learned_amino_acid_embedding",

        "published_architecture":
            (
                "embedding_convolution_"
                "max_pooling_LSTM"
            ),

        "official_repository":
            "dan-veltri/amp-scanner-v2",

        "official_training_script":
            "amp_scanner_v2_train_tf1.py",

        "locked_route":
            "official_source_retraining",

        "implementation_environment":
            "isolated_legacy_environment",

        "original_tensorflow_family":
            "TensorFlow_1.x",

        "pretrained_repeated_inference_allowed":
            False,

        "ten_independent_retraining_runs":
            True,

        "benchmark_split_adapter_allowed":
            True,

        "architecture_change_allowed":
            False,

        "config_lock_required_before_training":
            True,
    },


    # --------------------------------------------------------
    # 13. AmpGram
    # --------------------------------------------------------
    "ampgram": {

        "display_name":
            "AmpGram",

        "paper_year":
            2020,

        "paper_doi":
            "10.3390/ijms21124310",

        "published_family":
            "stacked_random_forest",

        "published_representation":
            "10mer_ngram_based",

        "published_architecture":
            (
                "first_level_10mer_RF_"
                "plus_second_level_peptide_RF"
            ),

        "official_repository":
            "michbur/AmpGram-analysis",

        "locked_route":
            (
                "faithful_source_recipe_"
                "reimplementation"
            ),

        "implementation_environment":
            "modern_reimplementation",

        "legacy_dependency_repair_required":
            False,

        "pretrained_repeated_inference_allowed":
            False,

        "ten_independent_retraining_runs":
            True,

        "source_recipe_must_be_preserved":
            True,

        "config_lock_required_before_training":
            True,
    },


    # --------------------------------------------------------
    # 14. ampir
    # --------------------------------------------------------
    "ampir": {

        "display_name":
            "ampir",

        "paper_year":
            2020,

        "paper_doi":
            "10.1093/bioinformatics/btaa653",

        "published_family":
            "radial_SVM",

        "published_representation":
            "physicochemical_plus_PseAAC_features",

        "reported_feature_count":
            27,

        "official_repository":
            "Legana/ampir",

        "locked_route":
            (
                "official_R_package_"
                "custom_retraining_mature_recipe"
            ),

        "implementation_environment":
            "genpept_r_models",

        "classifier":
            "caret_svmRadial",

        "pretrained_repeated_inference_allowed":
            False,

        "ten_independent_retraining_runs":
            True,

        "custom_training_supported":
            True,

        "config_lock_required_before_training":
            True,
    },


    # --------------------------------------------------------
    # 15. amPEPpy
    # --------------------------------------------------------
    "ampeppy": {

        "display_name":
            "amPEPpy",

        "paper_year":
            2020,

        "paper_doi":
            "10.1093/bioinformatics/btaa917",

        "published_family":
            "random_forest",

        "published_representation":
            (
                "CTD_distribution_descriptor_"
                "feature_set"
            ),

        "reported_feature_count":
            105,

        "official_repository":
            "tlawrence3/amPEPpy",

        "locked_route":
            "official_source_retraining",

        "implementation_environment":
            "dedicated_python_environment",

        "official_train_module":
            True,

        "pretrained_repeated_inference_allowed":
            False,

        "ten_independent_retraining_runs":
            True,

        "config_lock_required_before_training":
            True,
    },


    # --------------------------------------------------------
    # 16. AI4AMP
    # --------------------------------------------------------
    "ai4amp": {

        "display_name":
            "AI4AMP",

        "paper_year":
            2021,

        "paper_doi":
            "10.1128/mSystems.00299-21",

        "published_family":
            "deep_learning",

        "published_representation":
            "PC6_encoding",

        "published_architecture":
            "PC6_CNN_LSTM_Dense",

        "official_repository":
            "LinTzuTang/AI4AMP_predictor",

        "locked_route":
            (
                "faithful_reimplementation_"
                "using_official_PC6_and_"
                "published_architecture"
            ),

        "implementation_environment":
            "dedicated_python_environment",

        "pretrained_repeated_inference_allowed":
            False,

        "ten_independent_retraining_runs":
            True,

        "PC6_encoding_must_be_preserved":
            True,

        "architecture_change_allowed":
            False,

        "config_lock_required_before_training":
            True,
    },


    # --------------------------------------------------------
    # 17. AMPlify
    # --------------------------------------------------------
    "amplify": {

        "display_name":
            "AMPlify",

        "paper_year":
            2022,

        "paper_doi":
            "10.1186/s12864-022-08310-4",

        "published_family":
            "attentive_deep_learning",

        "published_representation":
            "sequence_embedding",

        "published_architecture":
            (
                "BiLSTM_multihead_scaled_"
                "dot_product_attention_"
                "context_attention_ensemble"
            ),

        "official_repository":
            "BirolLab/AMPlify",

        "locked_route":
            "official_source_retraining",

        "implementation_environment":
            "isolated_legacy_environment",

        "original_tensorflow_family":
            "TensorFlow_1.x",

        "official_training_command_available":
            True,

        "pretrained_repeated_inference_allowed":
            False,

        "ten_independent_retraining_runs":
            True,

        "ensemble_definition_must_be_preserved":
            True,

        "config_lock_required_before_training":
            True,
    },
}


assert list(
    PUBLISHED_ROUTE_CONTRACT.keys()
) == EXPECTED_PUBLISHED_IDS


assert len(
    PUBLISHED_ROUTE_CONTRACT
) == 7


# ============================================================
# 7. GLOBAL PUBLISHED-METHOD RULES
# ============================================================

PUBLISHED_GLOBAL_POLICY = {

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "datasets":
        EXPECTED_DATASETS,

    "model_seeds":
        EXPECTED_SEEDS,

    "runs_per_model_source":
        10,

    "same_seed_schedule":
        True,

    "seed_tuning":
        False,

    "seed_replacement":
        False,

    "data_resplitting_per_seed":
        False,

    "source_train_only_model_fitting":
        True,

    "source_validation_only_model_selection":
        True,

    "source_validation_only_threshold_selection":
        True,

    "source_test_final_evaluation_only":
        True,

    "external_target_test_evaluation_only":
        True,

    "external_target_adaptation":
        False,

    "external_target_threshold_tuning":
        False,

    "pretrained_model_repeated_10_times":
        False,

    "faithful_retraining_required":
        True,

    "implementation_deviation":
        (
            "must_be_documented_and_locked_"
            "before_benchmark_result_inspection"
        ),

    "method_replacement_after_results":
        False,

    "training_gate":
        "CLOSED_UNTIL_ALL_7_IMPLEMENTATIONS_VALIDATED",
}


# ============================================================
# 8. SOURCE CANDIDATE LOCATIONS
#
# NO recursive whole-disk search.
# Only controlled expected locations.
# ============================================================

HOME = Path.home()


SOURCE_CANDIDATES = {

    "ampscannerv2": [

        SOURCE_ROOT
        / "amp-scanner-v2",

        SOURCE_ROOT
        / "ampscannerv2",

        SOURCE_ROOT
        / "AMPScannerV2",

        PROJECT_ROOT
        / "amp-scanner-v2",

        PROJECT_ROOT
        / "AMPScannerV2",
    ],


    "ampgram": [

        SOURCE_ROOT
        / "AmpGram-analysis",

        SOURCE_ROOT
        / "ampgram-analysis",

        PROJECT_ROOT
        / "AmpGram-analysis",
    ],


    "ampir": [

        SOURCE_ROOT
        / "ampir",

        PROJECT_ROOT
        / "ampir",
    ],


    "ampeppy": [

        SOURCE_ROOT
        / "amPEPpy",

        SOURCE_ROOT
        / "ampeppy",

        PROJECT_ROOT
        / "amPEPpy",
    ],


    "ai4amp": [

        SOURCE_ROOT
        / "AI4AMP_predictor",

        SOURCE_ROOT
        / "AI4AMP",

        PROJECT_ROOT
        / "AI4AMP_predictor",
    ],


    "amplify": [

        SOURCE_ROOT
        / "AMPlify",

        SOURCE_ROOT
        / "amplify",

        PROJECT_ROOT
        / "AMPlify-source",
    ],
}


# ============================================================
# 9. METHOD-SPECIFIC SOURCE MARKERS
# ============================================================

SOURCE_MARKERS = {

    "ampscannerv2": [
        "amp_scanner_v2_train_tf1.py",
        "amp_train_and_predict_cnn-lstm_model.py",
    ],

    "ampgram": [
        "analysis.R",
        "generate_benchmark_data.R",
    ],

    "ampir": [
        "DESCRIPTION",
    ],

    "ampeppy": [
        "setup.py",
        "requirements.txt",
    ],

    "ai4amp": [
        "PC6",
        "code",
    ],

    "amplify": [
        "src",
        "amplify.yml",
    ],
}


# ============================================================
# 10. AUDIT LOCAL SOURCE AVAILABILITY
# ============================================================

source_audit = {}


# AmPEP does not require a public official repository
# under the locked route.
source_audit[
    "ampep"
] = {

    "source_path":
        None,

    "source_found":
        False,

    "git_commit":
        None,

    "note":
        (
            "Locked route is paper-based faithful "
            "reimplementation; original MATLAB "
            "training code is not required as a "
            "public repository dependency."
        ),
}


for method_id in [
    "ampscannerv2",
    "ampgram",
    "ampir",
    "ampeppy",
    "ai4amp",
    "amplify",
]:

    found_path = (
        first_existing_source(
            SOURCE_CANDIDATES[
                method_id
            ],
            required_any=
                SOURCE_MARKERS[
                    method_id
                ],
        )
    )


    source_audit[
        method_id
    ] = {

        "source_path":
            (
                str(
                    found_path
                )
                if found_path
                is not None
                else None
            ),

        "source_found":
            bool(
                found_path
                is not None
            ),

        "git_commit":
            git_commit_or_none(
                found_path
            ),

        "note":
            (
                "Local source discovered."
                if found_path
                is not None
                else
                "Local source not yet discovered "
                "in controlled source locations."
            ),
    }


# ============================================================
# 11. CONDA ENVIRONMENT AUDIT
# ============================================================

CONDA_EXE = shutil.which(
    "conda"
)


if CONDA_EXE is None:

    fallback_conda = (
        HOME
        / "miniconda3"
        / "bin"
        / "conda"
    )


    if fallback_conda.is_file():

        CONDA_EXE = str(
            fallback_conda
        )


conda_env_paths = []

conda_env_names = []


if CONDA_EXE is not None:

    conda_result = run_command(
        [
            CONDA_EXE,
            "env",
            "list",
            "--json",
        ]
    )


    if (
        conda_result[
            "returncode"
        ] == 0
    ):

        try:

            env_json = json.loads(
                conda_result[
                    "stdout"
                ]
            )


            conda_env_paths = (
                env_json.get(
                    "envs",
                    []
                )
            )


            conda_env_names = [
                Path(
                    p
                ).name
                for p
                in conda_env_paths
            ]

        except Exception:

            pass


# ============================================================
# 12. VERIFY ampir R ENVIRONMENT
# ============================================================

AMPIR_ENV_NAME = (
    "genpept_r_models"
)


ampir_env_present = (
    AMPIR_ENV_NAME
    in conda_env_names
)


ampir_version = None

caret_version = None

kernlab_version = None

ampir_runtime_ok = False


if (
    CONDA_EXE is not None
    and ampir_env_present
):

    r_code = (
        'suppressPackageStartupMessages(library(ampir));'
        'suppressPackageStartupMessages(library(caret));'
        'suppressPackageStartupMessages(library(kernlab));'
        'cat('
        'as.character(packageVersion("ampir")), "|",'
        'as.character(packageVersion("caret")), "|",'
        'as.character(packageVersion("kernlab"))'
        ')'
    )


    ampir_check = run_command(
        [
            CONDA_EXE,
            "run",
            "-n",
            AMPIR_ENV_NAME,
            "Rscript",
            "-e",
            r_code,
        ],
        timeout=30,
    )


    if (
        ampir_check[
            "returncode"
        ] == 0
    ):

        parts = [
            item.strip()
            for item
            in ampir_check[
                "stdout"
            ].split("|")
        ]


        if len(
            parts
        ) == 3:

            ampir_version = (
                parts[0]
            )

            caret_version = (
                parts[1]
            )

            kernlab_version = (
                parts[2]
            )

            ampir_runtime_ok = True


# ============================================================
# 13. AUDIT LEGACY / AUXILIARY ENVIRONMENTS
# ============================================================

AMPGRAM_LEGACY_ENV = (
    "genpept_ampgram_legacy"
)


ampgram_legacy_env_present = (
    AMPGRAM_LEGACY_ENV
    in conda_env_names
)


docker_path = shutil.which(
    "docker"
)


matlab_path = shutil.which(
    "matlab"
)


# ============================================================
# 14. BUILD CURRENT READINESS AUDIT
#
# "route_locked" != "implementation_validated"
#
# No method receives implementation_validated=True
# until its adapter passes a later end-to-end self-test.
# ============================================================

readiness_rows = []


for method_id in EXPECTED_PUBLISHED_IDS:

    route = (
        PUBLISHED_ROUTE_CONTRACT[
            method_id
        ]
    )


    audit = (
        source_audit[
            method_id
        ]
    )


    if (
        method_id
        == "ampir"
    ):

        local_state = (
            "ENV_PACKAGE_READY_ADAPTER_PENDING"
            if ampir_runtime_ok
            else
            "ENV_OR_PACKAGE_PENDING"
        )


    elif (
        method_id
        == "ampgram"
    ):

        local_state = (
            "SOURCE_READY_REIMPLEMENTATION_PENDING"
            if audit[
                "source_found"
            ]
            else
            "SOURCE_PENDING"
        )


    elif (
        method_id
        == "ampep"
    ):

        local_state = (
            "PAPER_REIMPLEMENTATION_PENDING"
        )


    else:

        local_state = (
            "SOURCE_READY_ADAPTER_PENDING"
            if audit[
                "source_found"
            ]
            else
            "SOURCE_PENDING"
        )


    readiness_rows.append(
        {
            "model_id":
                method_id,

            "display_name":
                route[
                    "display_name"
                ],

            "paper_year":
                route[
                    "paper_year"
                ],

            "paper_doi":
                route[
                    "paper_doi"
                ],

            "published_family":
                route[
                    "published_family"
                ],

            "locked_route":
                route[
                    "locked_route"
                ],

            "implementation_environment":
                route[
                    "implementation_environment"
                ],

            "local_source_found":
                bool(
                    audit[
                        "source_found"
                    ]
                ),

            "local_source_path":
                audit[
                    "source_path"
                ],

            "local_git_commit":
                audit[
                    "git_commit"
                ],

            "local_state":
                local_state,

            "route_locked":
                True,

            "adapter_self_test_passed":
                False,

            "implementation_validated":
                False,

            "training_allowed":
                False,
        }
    )


published_readiness_df = (
    pd.DataFrame(
        readiness_rows
    )
)


assert len(
    published_readiness_df
) == 7


assert (
    published_readiness_df[
        "route_locked"
    ]
).all()


assert not (
    published_readiness_df[
        "training_allowed"
    ]
).any()


# ============================================================
# 15. PUBLISHED RUN COUNTS
# ============================================================

N_PUBLISHED_MODELS = 7

N_DATASETS = 4

N_SEEDS = 10

N_TARGETS_PER_SOURCE = 3


PUBLISHED_TRAIN_RUNS = (
    N_PUBLISHED_MODELS
    * N_DATASETS
    * N_SEEDS
)


PUBLISHED_EXTERNAL_EVALS = (
    PUBLISHED_TRAIN_RUNS
    * N_TARGETS_PER_SOURCE
)


assert (
    PUBLISHED_TRAIN_RUNS
    == 280
)


assert (
    PUBLISHED_EXTERNAL_EVALS
    == 840
)


assert (
    400
    +
    PUBLISHED_TRAIN_RUNS
    == 680
)


assert (
    1200
    +
    PUBLISHED_EXTERNAL_EVALS
    == 2040
)


# ============================================================
# 16. IMMUTABLE ROUTE CONTRACT CORE
# ============================================================

ROUTE_CONTRACT_CORE = {

    "schema_version":
        "1.0",

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "datasets":
        EXPECTED_DATASETS,

    "model_seeds":
        EXPECTED_SEEDS,

    "published_model_ids":
        EXPECTED_PUBLISHED_IDS,

    "n_published_models":
        7,

    "published_training_runs":
        280,

    "published_external_evaluations":
        840,

    "methods":
        PUBLISHED_ROUTE_CONTRACT,

    "global_policy":
        PUBLISHED_GLOBAL_POLICY,

    "training_gate_open":
        False,

    "training_gate_requirement":
        (
            "All seven published methods must have "
            "versioned implementation contracts and "
            "successful adapter self-tests before "
            "benchmark-result generation starts."
        ),
}


# ============================================================
# 17. ROUTE CONTRACT PATH
# ============================================================

PUBLISHED_ROUTE_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_published_method_route_contract.json"
)


# ============================================================
# 18. IDEMPOTENT ROUTE LOCK
# ============================================================

if (
    PUBLISHED_ROUTE_CONTRACT_PATH
    .exists()
):

    existing_route_payload = (
        load_json(
            PUBLISHED_ROUTE_CONTRACT_PATH
        )
    )


    assert (
        existing_route_payload[
            "contract"
        ]
        ==
        ROUTE_CONTRACT_CORE
    ), (
        "Published-method route contract already exists "
        "but differs from the current definition.\n"
        "DO NOT silently change published-method routes."
    )


    route_created_at = (
        existing_route_payload[
            "created_at"
        ]
    )


    ROUTE_LOCK_ACTION = (
        "EXISTING IDENTICAL ROUTE LOCK VERIFIED"
    )


else:

    route_created_at = (
        datetime.now()
        .astimezone()
        .isoformat()
    )


    route_payload = {

        "created_at":
            route_created_at,

        "status":
            "PUBLISHED_METHOD_ROUTES_LOCKED_BEFORE_TRAINING",

        "restart_safe":
            True,

        "contract":
            ROUTE_CONTRACT_CORE,
    }


    with open(
        PUBLISHED_ROUTE_CONTRACT_PATH,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            route_payload,
            f,
            indent=2,
            ensure_ascii=False,
        )


    ROUTE_LOCK_ACTION = (
        "NEW ROUTE LOCK CREATED"
    )


# ============================================================
# 19. LOCAL READINESS SNAPSHOT
#
# Mutable audit snapshot:
# it is expected to change after sources/envs are prepared.
#
# It is NOT the immutable scientific route contract.
# ============================================================

PUBLISHED_READINESS_PATH = (
    AUDIT_DIR
    / "benchmark17_published_method_local_readiness_latest.csv"
)


published_readiness_df.to_csv(
    PUBLISHED_READINESS_PATH,
    index=False,
)


timestamp_tag = (
    datetime.now()
    .astimezone()
    .strftime(
        "%Y%m%d_%H%M%S"
    )
)


PUBLISHED_READINESS_HISTORY_PATH = (
    AUDIT_DIR
    / (
        "benchmark17_published_method_"
        f"local_readiness_{timestamp_tag}.csv"
    )
)


published_readiness_df.to_csv(
    PUBLISHED_READINESS_HISTORY_PATH,
    index=False,
)


# ============================================================
# 20. LOCAL ENVIRONMENT AUDIT MANIFEST
# ============================================================

LOCAL_ENV_AUDIT = {

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "python_executable":
        sys.executable,

    "python_version":
        platform.python_version(),

    "platform":
        platform.platform(),

    "conda_executable":
        CONDA_EXE,

    "conda_environment_names":
        conda_env_names,

    "ampir": {

        "environment":
            AMPIR_ENV_NAME,

        "environment_present":
            ampir_env_present,

        "runtime_ok":
            ampir_runtime_ok,

        "ampir_version":
            ampir_version,

        "caret_version":
            caret_version,

        "kernlab_version":
            kernlab_version,
    },

    "ampgram": {

        "legacy_environment":
            AMPGRAM_LEGACY_ENV,

        "legacy_environment_present":
            ampgram_legacy_env_present,

        "legacy_environment_required":
            False,

        "locked_route":
            (
                "modern_faithful_"
                "source_recipe_reimplementation"
            ),
    },

    "docker_available":
        bool(
            docker_path
        ),

    "matlab_available":
        bool(
            matlab_path
        ),

    "source_root":
        str(
            SOURCE_ROOT
        ),

    "source_audit":
        source_audit,
}


LOCAL_ENV_AUDIT_PATH = (
    MANIFEST_DIR
    / "benchmark17_published_method_local_environment_latest.json"
)


with open(
    LOCAL_ENV_AUDIT_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        LOCAL_ENV_AUDIT,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ============================================================
# 21. TRAINING GATE
#
# CLOSED intentionally.
#
# It may only become TRUE after later cells create and
# validate all seven versioned implementation contracts.
# ============================================================

TRAINING_GATE = {

    "schema_version":
        "1.0",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "gate":
        "PUBLISHED_METHOD_IMPLEMENTATION_GATE",

    "open":
        False,

    "route_contract_locked":
        True,

    "published_methods_total":
        7,

    "published_methods_implementation_validated":
        0,

    "required_for_open":
        7,

    "benchmark_training_allowed":
        False,

    "reason":
        (
            "Scientific routes are locked, but "
            "method-specific implementation adapters "
            "have not yet passed end-to-end validation."
        ),
}


TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)


with open(
    TRAINING_GATE_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        TRAINING_GATE,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ============================================================
# 22. ROUTE SUMMARY AUDIT TABLE
# ============================================================

route_summary_rows = []


for method_id in (
    EXPECTED_PUBLISHED_IDS
):

    method = (
        PUBLISHED_ROUTE_CONTRACT[
            method_id
        ]
    )


    route_summary_rows.append(
        {
            "model_id":
                method_id,

            "display_name":
                method[
                    "display_name"
                ],

            "year":
                method[
                    "paper_year"
                ],

            "doi":
                method[
                    "paper_doi"
                ],

            "family":
                method[
                    "published_family"
                ],

            "representation":
                method[
                    "published_representation"
                ],

            "locked_route":
                method[
                    "locked_route"
                ],

            "environment":
                method[
                    "implementation_environment"
                ],

            "ten_retraining_runs":
                method[
                    "ten_independent_retraining_runs"
                ],

            "pretrained_repeat_allowed":
                method[
                    "pretrained_repeated_inference_allowed"
                ],
        }
    )


route_summary_df = pd.DataFrame(
    route_summary_rows
)


PUBLISHED_ROUTE_SUMMARY_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_published_method_route_summary.csv"
)


route_summary_df.to_csv(
    PUBLISHED_ROUTE_SUMMARY_PATH,
    index=False,
)


# ============================================================
# 23. HASH IMMUTABLE ROUTE CONTRACT
# ============================================================

PUBLISHED_ROUTE_SHA256 = (
    sha256_file(
        PUBLISHED_ROUTE_CONTRACT_PATH
    )
)


# ============================================================
# 24. RE-READ AND HARD VERIFY
# ============================================================

route_check = load_json(
    PUBLISHED_ROUTE_CONTRACT_PATH
)


gate_check = load_json(
    TRAINING_GATE_PATH
)


assert (
    route_check[
        "status"
    ]
    ==
    "PUBLISHED_METHOD_ROUTES_LOCKED_BEFORE_TRAINING"
)


assert (
    route_check[
        "restart_safe"
    ]
    is True
)


assert (
    route_check[
        "contract"
    ][
        "published_model_ids"
    ]
    == EXPECTED_PUBLISHED_IDS
)


assert (
    route_check[
        "contract"
    ][
        "model_seeds"
    ]
    == EXPECTED_SEEDS
)


assert (
    route_check[
        "contract"
    ][
        "published_training_runs"
    ]
    == 280
)


assert (
    route_check[
        "contract"
    ][
        "published_external_evaluations"
    ]
    == 840
)


for method_id in (
    EXPECTED_PUBLISHED_IDS
):

    assert (
        route_check[
            "contract"
        ][
            "methods"
        ][
            method_id
        ][
            "pretrained_repeated_inference_allowed"
        ]
        is False
    )


    assert (
        route_check[
            "contract"
        ][
            "methods"
        ][
            method_id
        ][
            "ten_independent_retraining_runs"
        ]
        is True
    )


assert (
    gate_check[
        "open"
    ]
    is False
)


assert (
    gate_check[
        "benchmark_training_allowed"
    ]
    is False
)


# ============================================================
# 25. LOCAL AUDIT COUNTS
# ============================================================

local_source_count = int(
    published_readiness_df[
        "local_source_found"
    ].sum()
)


route_lock_count = int(
    published_readiness_df[
        "route_locked"
    ].sum()
)


implementation_validated_count = int(
    published_readiness_df[
        "implementation_validated"
    ].sum()
)


assert route_lock_count == 7

assert (
    implementation_validated_count
    == 0
)


# ============================================================
# 26. REPORT
# ============================================================

print("=" * 132)

print(
    "CELL 16 PASS - ALL 7 PUBLISHED AMP METHOD "
    "ROUTES LOCKED; LOCAL READINESS AUDITED"
)

print("=" * 132)

print(
    f"ROUTE LOCK ACTION      : {ROUTE_LOCK_ACTION}"
)

print(
    "RESTART SAFE           : TRUE"
)

print(
    "PACKAGE INSTALLATION   : FALSE"
)

print(
    "SOURCE DOWNLOAD        : FALSE"
)

print(
    "MODEL TRAINING         : FALSE"
)

print(
    "TEST RESULT INSPECTION : FALSE"
)

print("-" * 132)

print(
    "PUBLISHED METHOD ROUTES"
)

print(
    route_summary_df[
        [
            "model_id",
            "display_name",
            "year",
            "family",
            "representation",
            "locked_route",
            "environment",
        ]
    ].to_string(
        index=False
    )
)

print("-" * 132)

print(
    "CURRENT LOCAL READINESS"
)

print(
    published_readiness_df[
        [
            "model_id",
            "local_source_found",
            "local_source_path",
            "local_git_commit",
            "local_state",
            "adapter_self_test_passed",
            "implementation_validated",
            "training_allowed",
        ]
    ].to_string(
        index=False
    )
)

print("-" * 132)

print(
    "ampir R ENVIRONMENT"
)

print(
    f"Environment            : {AMPIR_ENV_NAME}"
)

print(
    f"Environment present    : {ampir_env_present}"
)

print(
    f"ampir runtime          : {ampir_runtime_ok}"
)

print(
    f"ampir version          : {ampir_version}"
)

print(
    f"caret version          : {caret_version}"
)

print(
    f"kernlab version        : {kernlab_version}"
)

print("-" * 132)

print(
    "AUXILIARY ENVIRONMENT AUDIT"
)

print(
    f"AmpGram legacy env     : {ampgram_legacy_env_present}"
)

print(
    "AmpGram legacy needed : FALSE"
)

print(
    f"Docker available       : {bool(docker_path)}"
)

print(
    f"MATLAB available       : {bool(matlab_path)}"
)

print("-" * 132)

print(
    "EXECUTION COUNTS"
)

print(
    f"Published training runs: {PUBLISHED_TRAIN_RUNS}"
)

print(
    f"Published external eval: {PUBLISHED_EXTERNAL_EVALS}"
)

print(
    "Controlled train runs : 400"
)

print(
    "Controlled ext. evals : 1200"
)

print(
    "TOTAL 17-model trains : 680"
)

print(
    "TOTAL external evals  : 2040"
)

print("-" * 132)

print(
    "SCIENTIFIC GATE"
)

print(
    f"Routes locked          : {route_lock_count}/7"
)

print(
    f"Local sources detected : {local_source_count}/7"
)

print(
    f"Implementations valid  : {implementation_validated_count}/7"
)

print(
    "TRAINING GATE          : CLOSED"
)

print(
    "BENCHMARK TRAINING     : NOT YET ALLOWED"
)

print(
    "Reason                 : each published adapter "
    "must pass versioned end-to-end self-test first"
)

print("-" * 132)

print(
    f"Route contract         : "
    f"{PUBLISHED_ROUTE_CONTRACT_PATH}"
)

print(
    f"Route contract SHA256  : "
    f"{PUBLISHED_ROUTE_SHA256}"
)

print(
    f"Route summary          : "
    f"{PUBLISHED_ROUTE_SUMMARY_PATH}"
)

print(
    f"Readiness latest       : "
    f"{PUBLISHED_READINESS_PATH}"
)

print(
    f"Readiness history      : "
    f"{PUBLISHED_READINESS_HISTORY_PATH}"
)

print(
    f"Environment audit      : "
    f"{LOCAL_ENV_AUDIT_PATH}"
)

print(
    f"Training gate          : "
    f"{TRAINING_GATE_PATH}"
)

print("=" * 132)

====================================================================================================================================
CELL 16 PASS - ALL 7 PUBLISHED AMP METHOD ROUTES LOCKED; LOCAL READINESS AUDITED
====================================================================================================================================
ROUTE LOCK ACTION      : NEW ROUTE LOCK CREATED
RESTART SAFE           : TRUE
PACKAGE INSTALLATION   : FALSE
SOURCE DOWNLOAD        : FALSE
MODEL TRAINING         : FALSE
TEST RESULT INSPECTION : FALSE
------------------------------------------------------------------------------------------------------------------------------------
PUBLISHED METHOD ROUTES
    model_id display_name  year                  family                                             representation                                                            locked_route                  environment
       ampep        AmPEP  2018           random_forest selected_distribution_descriptors_of_amino_acid_properties                              faithful_reimplementation_from_publication  dedicated_adapter_or_master
ampscannerv2 AMPScannerV2  2018     deep_neural_network                               learned_amino_acid_embedding                                              official_source_retraining  isolated_legacy_environment
     ampgram      AmpGram  2020   stacked_random_forest                                          10mer_ngram_based                                 faithful_source_recipe_reimplementation      modern_reimplementation
       ampir        ampir  2020              radial_SVM                       physicochemical_plus_PseAAC_features                      official_R_package_custom_retraining_mature_recipe             genpept_r_models
     ampeppy      amPEPpy  2020           random_forest                    CTD_distribution_descriptor_feature_set                                              official_source_retraining dedicated_python_environment
      ai4amp       AI4AMP  2021           deep_learning                                               PC6_encoding faithful_reimplementation_using_official_PC6_and_published_architecture dedicated_python_environment
     amplify      AMPlify  2022 attentive_deep_learning                                         sequence_embedding                                              official_source_retraining  isolated_legacy_environment
------------------------------------------------------------------------------------------------------------------------------------
CURRENT LOCAL READINESS
    model_id  local_source_found                         local_source_path                         local_git_commit                           local_state  adapter_self_test_passed  implementation_validated  training_allowed
       ampep               False                                       NaN                                      NaN        PAPER_REIMPLEMENTATION_PENDING                     False                     False             False
ampscannerv2               False                                       NaN                                      NaN                        SOURCE_PENDING                     False                     False             False
     ampgram                True /home/pc/genpept_sources/AmpGram-analysis 9a76d4c90a74622ec5ad9dc8b3d908799ac7745a SOURCE_READY_REIMPLEMENTATION_PENDING                     False                     False             False
       ampir               False                                       NaN                                      NaN     ENV_PACKAGE_READY_ADAPTER_PENDING                     False                     False             False
     ampeppy               False                                       NaN                                      NaN                        SOURCE_PENDING                     False                     False             False
      ai4amp               False                                       NaN                                      NaN                        SOURCE_PENDING                     False                     False             False
     amplify               False                                       NaN                                      NaN                        SOURCE_PENDING                     False                     False             False
------------------------------------------------------------------------------------------------------------------------------------
ampir R ENVIRONMENT
Environment            : genpept_r_models
Environment present    : True
ampir runtime          : True
ampir version          : 1.1.0
caret version          : 7.0.1
kernlab version        : 0.9.33
------------------------------------------------------------------------------------------------------------------------------------
AUXILIARY ENVIRONMENT AUDIT
AmpGram legacy env     : True
AmpGram legacy needed : FALSE
Docker available       : False
MATLAB available       : False
------------------------------------------------------------------------------------------------------------------------------------
EXECUTION COUNTS
Published training runs: 280
Published external eval: 840
Controlled train runs : 400
Controlled ext. evals : 1200
TOTAL 17-model trains : 680
TOTAL external evals  : 2040
------------------------------------------------------------------------------------------------------------------------------------
SCIENTIFIC GATE
Routes locked          : 7/7
Local sources detected : 1/7
Implementations valid  : 0/7
TRAINING GATE          : CLOSED
BENCHMARK TRAINING     : NOT YET ALLOWED
Reason                 : each published adapter must pass versioned end-to-end self-test first
------------------------------------------------------------------------------------------------------------------------------------
Route contract         : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_published_method_route_contract.json
Route contract SHA256  : dd7d6a743f088cef95fb49288dcf1801c9dc335be2656e627e7fc7f3bf7170bd
Route summary          : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_FINAL_published_method_route_summary.csv
Readiness latest       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_published_method_local_readiness_latest.csv
Readiness history      : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_published_method_local_readiness_20260911_194917.csv
Environment audit      : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_published_method_local_environment_latest.json
Training gate          : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_training_gate.json
====================================================================================================================================

In [13]:
# ============================================================
# CELL 17 - FINAL CORRECTED / RESTART-SAFE
# ampir 1.1.0 - OFFICIAL INSTALLED MATURE MODEL RECIPE LOCK
#
# VERIFIED SCIENTIFIC ROUTE
# -------------------------
# Package model:
#   ampir:::ampir_package_data[["mature_model"]]
#
# Installed ampir 1.1.0 mature model:
#   method      = svmRadial
#   predictors  = 27
#   sigma       = 0.07
#   C           = 1
#   preprocess  = center + scale
#
# NOTE:
# sigma=0.06 belongs to an earlier tuning result.
# The packaged FINAL/FULL mature model in ampir 1.1.0
# exposes sigma=0.07 and is authoritative here.
#
# NO BENCHMARK TRAINING
# NO TEST DATA
# NO PACKAGE INSTALLATION
# NO TRAINING-GATE CHANGE
# ============================================================


from pathlib import Path
from datetime import datetime

import hashlib
import json
import re
import shutil
import subprocess
import tempfile


# ============================================================
# 1. RESTORE PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)


for path in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
]:
    assert path.is_dir(), (
        f"Missing directory:\n{path}"
    )


# ============================================================
# 2. HELPERS
# ============================================================

def load_json(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as f:
        return json.load(f)


def sha256_file(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda: f.read(
                1024 * 1024
            ),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


def get_value(
    text,
    key,
):

    m = re.search(
        rf"(?m)^{re.escape(key)}=(.*)$",
        text,
    )

    assert m is not None, (
        f"Missing R output field: {key}"
    )

    return m.group(1).strip()


# ============================================================
# 3. VERIFY UPSTREAM ROUTE / TRAINING GATE
# ============================================================

ROUTE_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_published_method_route_contract.json"
)

TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)


assert ROUTE_CONTRACT_PATH.is_file()
assert TRAINING_GATE_PATH.is_file()


route_contract = load_json(
    ROUTE_CONTRACT_PATH
)

gate_before = load_json(
    TRAINING_GATE_PATH
)


assert (
    route_contract[
        "contract"
    ][
        "methods"
    ][
        "ampir"
    ][
        "locked_route"
    ]
    ==
    "official_R_package_custom_retraining_mature_recipe"
)


assert gate_before["open"] is False

assert (
    gate_before[
        "benchmark_training_allowed"
    ]
    is False
)


# ============================================================
# 4. LOCATE CONDA ENVIRONMENT
# ============================================================

CONDA_EXE = shutil.which(
    "conda"
)


if CONDA_EXE is None:

    fallback = Path(
        "/home/pc/miniconda3/bin/conda"
    )

    if fallback.is_file():
        CONDA_EXE = str(
            fallback
        )


assert CONDA_EXE is not None


AMPIR_ENV = (
    "genpept_r_models"
)


# ============================================================
# 5. EXACT EXPECTED FINAL PACKAGE RECIPE
# ============================================================

EXPECTED_PREDICTORS = [

    "Amphiphilicity",
    "Hydrophobicity",
    "pI",
    "Mw",
    "Charge",

    "Xc1.A",
    "Xc1.R",
    "Xc1.N",
    "Xc1.D",
    "Xc1.C",
    "Xc1.E",
    "Xc1.Q",
    "Xc1.G",
    "Xc1.H",
    "Xc1.I",
    "Xc1.L",
    "Xc1.K",
    "Xc1.M",
    "Xc1.F",
    "Xc1.P",
    "Xc1.S",
    "Xc1.T",
    "Xc1.W",
    "Xc1.Y",
    "Xc1.V",

    "Xc2.lambda.1",
    "Xc2.lambda.2",
]


assert len(
    EXPECTED_PREDICTORS
) == 27


# ============================================================
# 6. R SCRIPT
#
# Reads ONLY the exact package model actually used by:
# predict_amps(..., model="mature")
# ============================================================

R_SCRIPT = r'''
options(width=500)

suppressPackageStartupMessages(
    library(ampir)
)

suppressPackageStartupMessages(
    library(caret)
)

suppressPackageStartupMessages(
    library(kernlab)
)


pkg_data <- get(
    "ampir_package_data",
    envir=asNamespace("ampir"),
    inherits=FALSE
)


stopifnot(
    is.list(pkg_data)
)


stopifnot(
    "mature_model"
    %in%
    names(pkg_data)
)


mature_model <- pkg_data[["mature_model"]]


stopifnot(
    inherits(
        mature_model,
        "train"
    )
)


# ------------------------------------------------------------
# Runtime
# ------------------------------------------------------------

cat(
    "R_VERSION=",
    as.character(
        getRversion()
    ),
    "\n",
    sep=""
)

cat(
    "AMPIR_VERSION=",
    as.character(
        packageVersion("ampir")
    ),
    "\n",
    sep=""
)

cat(
    "CARET_VERSION=",
    as.character(
        packageVersion("caret")
    ),
    "\n",
    sep=""
)

cat(
    "KERNLAB_VERSION=",
    as.character(
        packageVersion("kernlab")
    ),
    "\n",
    sep=""
)


# ------------------------------------------------------------
# Exact installed mature model
# ------------------------------------------------------------

cat(
    "METHOD=",
    mature_model$method,
    "\n",
    sep=""
)


cat(
    "SIGMA=",
    format(
        mature_model$bestTune$sigma[1],
        scientific=FALSE,
        trim=TRUE,
        digits=15
    ),
    "\n",
    sep=""
)


cat(
    "C=",
    format(
        mature_model$bestTune$C[1],
        scientific=FALSE,
        trim=TRUE,
        digits=15
    ),
    "\n",
    sep=""
)


predictors <- colnames(
    mature_model$trainingData
)[-1]


cat(
    "PREDICTOR_COUNT=",
    length(predictors),
    "\n",
    sep=""
)


cat(
    "PREDICTORS=",
    paste(
        predictors,
        collapse="|"
    ),
    "\n",
    sep=""
)


cat(
    "COEFNAME_COUNT=",
    length(
        mature_model$coefnames
    ),
    "\n",
    sep=""
)


cat(
    "COEFNAMES=",
    paste(
        mature_model$coefnames,
        collapse="|"
    ),
    "\n",
    sep=""
)


cat(
    "COEFNAMES_MATCH=",
    identical(
        as.character(
            predictors
        ),
        as.character(
            mature_model$coefnames
        )
    ),
    "\n",
    sep=""
)


# ------------------------------------------------------------
# Preprocessing
# ------------------------------------------------------------

stopifnot(
    !is.null(
        mature_model$preProcess
    )
)


pp_methods <- names(
    mature_model$preProcess$method
)


cat(
    "PREPROCESS_METHODS=",
    paste(
        pp_methods,
        collapse="|"
    ),
    "\n",
    sep=""
)


cat(
    "CENTER_COUNT=",
    length(
        mature_model$preProcess$mean
    ),
    "\n",
    sep=""
)


cat(
    "SCALE_COUNT=",
    length(
        mature_model$preProcess$std
    ),
    "\n",
    sep=""
)


# ------------------------------------------------------------
# Verify calculate_features produces all 27 inputs
# ------------------------------------------------------------

audit_df <- data.frame(
    seq_name="audit_sequence",
    seq_aa="ACDEFGHIKLMNPQRSTVWY",
    stringsAsFactors=FALSE
)


feature_df <- calculate_features(
    audit_df,
    min_len=10
)


compatible <- all(
    predictors
    %in%
    colnames(
        feature_df
    )
)


cat(
    "FEATURE_COMPATIBLE=",
    compatible,
    "\n",
    sep=""
)


stopifnot(
    compatible
)


# ------------------------------------------------------------
# Official predictor smoke test
# ------------------------------------------------------------

pred <- predict_amps(
    audit_df,
    min_len=10,
    n_cores=1,
    model="mature"
)


stopifnot(
    "prob_AMP"
    %in%
    colnames(pred)
)


stopifnot(
    is.finite(
        pred$prob_AMP[1]
    )
)


stopifnot(
    pred$prob_AMP[1]
    >= 0
)


stopifnot(
    pred$prob_AMP[1]
    <= 1
)


cat(
    "SMOKE_PROB=",
    format(
        pred$prob_AMP[1],
        scientific=FALSE,
        trim=TRUE,
        digits=15
    ),
    "\n",
    sep=""
)


cat(
    "SMOKE_TEST=PASS\n"
)


cat(
    "AUDIT_COMPLETE=TRUE\n"
)
'''


# ============================================================
# 7. WRITE TEMP SCRIPT
# ============================================================

R_SCRIPT_PATH = (
    Path(
        tempfile.gettempdir()
    )
    / "benchmark17_cell17_ampir_final.R"
)


with open(
    R_SCRIPT_PATH,
    "w",
    encoding="utf-8",
    newline="\n",
) as f:

    f.write(
        R_SCRIPT
    )


assert R_SCRIPT_PATH.is_file()


# ============================================================
# 8. EXECUTE
# ============================================================

result = subprocess.run(
    [
        CONDA_EXE,
        "run",
        "--no-capture-output",
        "-n",
        AMPIR_ENV,
        "Rscript",
        str(
            R_SCRIPT_PATH
        ),
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    text=True,
    timeout=180,
    check=False,
)


stdout_text = (
    result.stdout or ""
)

stderr_text = (
    result.stderr or ""
)


# Always show diagnostic first.
print("=" * 120)

print(
    "ampir 1.1.0 FINAL PACKAGE RECIPE AUDIT"
)

print("=" * 120)

print(
    stdout_text
)


if stderr_text.strip():

    print("-" * 120)

    print(
        "R STDERR / WARNINGS"
    )

    print("-" * 120)

    print(
        stderr_text
    )


print("=" * 120)


assert result.returncode == 0, (
    "R audit failed. "
    "See complete diagnostic above."
)


# ============================================================
# 9. PARSE ACTUAL VALUES
# ============================================================

R_VERSION = get_value(
    stdout_text,
    "R_VERSION",
)

AMPIR_VERSION = get_value(
    stdout_text,
    "AMPIR_VERSION",
)

CARET_VERSION = get_value(
    stdout_text,
    "CARET_VERSION",
)

KERNLAB_VERSION = get_value(
    stdout_text,
    "KERNLAB_VERSION",
)

METHOD = get_value(
    stdout_text,
    "METHOD",
)

SIGMA = float(
    get_value(
        stdout_text,
        "SIGMA",
    )
)

C_VALUE = float(
    get_value(
        stdout_text,
        "C",
    )
)

PREDICTOR_COUNT = int(
    get_value(
        stdout_text,
        "PREDICTOR_COUNT",
    )
)

PREDICTORS = (
    get_value(
        stdout_text,
        "PREDICTORS",
    )
    .split("|")
)

COEFNAME_COUNT = int(
    get_value(
        stdout_text,
        "COEFNAME_COUNT",
    )
)

COEFNAMES = (
    get_value(
        stdout_text,
        "COEFNAMES",
    )
    .split("|")
)

COEFNAMES_MATCH = (
    get_value(
        stdout_text,
        "COEFNAMES_MATCH",
    )
    == "TRUE"
)

PREPROCESS_METHODS = (
    get_value(
        stdout_text,
        "PREPROCESS_METHODS",
    )
    .split("|")
)

CENTER_COUNT = int(
    get_value(
        stdout_text,
        "CENTER_COUNT",
    )
)

SCALE_COUNT = int(
    get_value(
        stdout_text,
        "SCALE_COUNT",
    )
)

FEATURE_COMPATIBLE = (
    get_value(
        stdout_text,
        "FEATURE_COMPATIBLE",
    )
    == "TRUE"
)

SMOKE_PROB = float(
    get_value(
        stdout_text,
        "SMOKE_PROB",
    )
)

SMOKE_TEST = get_value(
    stdout_text,
    "SMOKE_TEST",
)

AUDIT_COMPLETE = get_value(
    stdout_text,
    "AUDIT_COMPLETE",
)


# ============================================================
# 10. HARD SCIENTIFIC ASSERTIONS
#
# IMPORTANT:
# 0.07 is the installed FINAL package model.
# We do NOT force historical 0.06 here.
# ============================================================

assert AMPIR_VERSION == "1.1.0"

assert METHOD == "svmRadial"


assert abs(
    SIGMA - 0.07
) < 1e-12, (
    f"Installed mature sigma changed: {SIGMA}"
)


assert abs(
    C_VALUE - 1.0
) < 1e-12


assert PREDICTOR_COUNT == 27

assert COEFNAME_COUNT == 27


assert (
    PREDICTORS
    == EXPECTED_PREDICTORS
), (
    "Installed mature-model predictor list "
    "does not match verified 27-feature recipe."
)


assert (
    COEFNAMES
    == EXPECTED_PREDICTORS
)


assert COEFNAMES_MATCH is True


assert (
    "center"
    in PREPROCESS_METHODS
)


assert (
    "scale"
    in PREPROCESS_METHODS
)


assert CENTER_COUNT == 27

assert SCALE_COUNT == 27


assert FEATURE_COMPATIBLE is True

assert SMOKE_TEST == "PASS"

assert AUDIT_COMPLETE == "TRUE"


assert (
    0.0
    <= SMOKE_PROB
    <= 1.0
)


# ============================================================
# 11. LOCK ampir IMPLEMENTATION CONTRACT
# ============================================================

AMPIR_IMPLEMENTATION_CONTRACT = {

    "schema_version":
        "1.0",

    "model_id":
        "ampir",

    "display_name":
        "ampir",

    "package_version":
        AMPIR_VERSION,

    "benchmark_route":
        (
            "retrain_ampir_mature_recipe_"
            "on_each_source_training_set"
        ),

    "reference_model":
        "mature",

    "classifier":
        "caret_svmRadial",

    "features": {

        "count":
            27,

        "names":
            EXPECTED_PREDICTORS,

        "generated_by":
            "ampir::calculate_features",

        "minimum_length":
            10,
    },

    "preprocessing": {

        "center":
            True,

        "scale":
            True,

        "fit_scope":
            "source_train_only",
    },

    "hyperparameters": {

        "sigma":
            0.07,

        "C":
            1.0,

        "source":
            (
                "installed_ampir_1.1.0_"
                "final_mature_model"
            ),
    },

    "historical_tuning_note": {

        "earlier_reported_mature_sigma":
            0.06,

        "earlier_reported_mature_C":
            1.0,

        "benchmark_value_used":
            0.07,

        "reason":
            (
                "The installed ampir 1.1.0 final/full "
                "mature model is the executable "
                "reference implementation."
            ),
    },

    "ten_runs": {

        "seeds":
            list(
                range(
                    100,
                    110
                )
            ),

        "retraining_required":
            True,

        "fixed_pretrained_repeat":
            False,
    },

    "source_train_only":
        True,

    "source_validation_threshold_only":
        True,

    "test_guided_tuning":
        False,

    "external_target_tuning":
        False,

    "benchmark_training_started":
        False,

    "adapter_self_test_status":
        "PENDING",
}


# ============================================================
# 12. SAVE AUDIT + CONTRACT
# ============================================================

AUDIT_TXT_PATH = (
    AUDIT_DIR
    / "benchmark17_ampir_final_package_recipe_audit.txt"
)

CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampir_FINAL_implementation_contract.json"
)


with open(
    AUDIT_TXT_PATH,
    "w",
    encoding="utf-8",
) as f:

    f.write(
        stdout_text
    )

    if stderr_text.strip():

        f.write(
            "\n\n=== STDERR / WARNINGS ===\n"
        )

        f.write(
            stderr_text
        )


AUDIT_SHA256 = sha256_file(
    AUDIT_TXT_PATH
)


contract_payload = {

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "status":
        "AMPIR_RECIPE_LOCKED_ADAPTER_SELF_TEST_PENDING",

    "audit_sha256":
        AUDIT_SHA256,

    "contract":
        AMPIR_IMPLEMENTATION_CONTRACT,
}


# ============================================================
# 13. IDEMPOTENT CONTRACT LOCK
# ============================================================

if CONTRACT_PATH.exists():

    existing = load_json(
        CONTRACT_PATH
    )

    assert (
        existing[
            "contract"
        ]
        ==
        AMPIR_IMPLEMENTATION_CONTRACT
    ), (
        "An ampir implementation contract already exists "
        "with different content. "
        "Do NOT silently overwrite."
    )

    LOCK_ACTION = (
        "EXISTING IDENTICAL CONTRACT VERIFIED"
    )

else:

    with open(
        CONTRACT_PATH,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            contract_payload,
            f,
            indent=2,
            ensure_ascii=False,
        )

    LOCK_ACTION = (
        "NEW ampir IMPLEMENTATION CONTRACT CREATED"
    )


# ============================================================
# 14. VERIFY GATE UNCHANGED
# ============================================================

gate_after = load_json(
    TRAINING_GATE_PATH
)


assert gate_after["open"] is False

assert (
    gate_after[
        "benchmark_training_allowed"
    ]
    is False
)


# ============================================================
# 15. FINAL REPORT
# ============================================================

print("=" * 126)

print(
    "CELL 17 PASS - ampir 1.1.0 FINAL MATURE "
    "MODEL RECIPE VERIFIED AND LOCKED"
)

print("=" * 126)

print(
    f"LOCK ACTION            : {LOCK_ACTION}"
)

print(
    f"R                      : {R_VERSION}"
)

print(
    f"ampir                  : {AMPIR_VERSION}"
)

print(
    f"caret                  : {CARET_VERSION}"
)

print(
    f"kernlab                : {KERNLAB_VERSION}"
)

print("-" * 126)

print(
    "ampir MATURE RECIPE"
)

print(
    f"Classifier             : {METHOD}"
)

print(
    f"Predictors             : {PREDICTOR_COUNT}"
)

print(
    f"sigma                  : {SIGMA}"
)

print(
    f"C                      : {C_VALUE}"
)

print(
    f"Preprocess             : "
    f"{' | '.join(PREPROCESS_METHODS)}"
)

print(
    f"Center count           : {CENTER_COUNT}"
)

print(
    f"Scale count            : {SCALE_COUNT}"
)

print(
    "Feature compatibility  : PASS"
)

print(
    "Official smoke test    : PASS"
)

print(
    f"Smoke probability      : {SMOKE_PROB:.8f}"
)

print("-" * 126)

print(
    "HISTORICAL DISCREPANCY"
)

print(
    "Earlier tuning report : sigma=0.06, C=1"
)

print(
    "Installed final model : sigma=0.07, C=1"
)

print(
    "BENCHMARK LOCK        : sigma=0.07, C=1"
)

print("-" * 126)

print(
    "Benchmark training     : FALSE"
)

print(
    "Adapter self-test      : PENDING"
)

print(
    "Training gate          : CLOSED"
)

print("-" * 126)

print(
    "27 PREDICTORS"
)

print(
    " | ".join(
        EXPECTED_PREDICTORS
    )
)

print("-" * 126)

print(
    f"Audit TXT              : {AUDIT_TXT_PATH}"
)

print(
    f"Audit SHA256           : {AUDIT_SHA256}"
)

print(
    f"Implementation contract: {CONTRACT_PATH}"
)

print("=" * 126)

========================================================================================================================
ampir 1.1.0 FINAL PACKAGE RECIPE AUDIT
========================================================================================================================
R_VERSION=4.6.1
AMPIR_VERSION=1.1.0
CARET_VERSION=7.0.1
KERNLAB_VERSION=0.9.33
METHOD=svmRadial
SIGMA=0.07
C=1
PREDICTOR_COUNT=27
PREDICTORS=Amphiphilicity|Hydrophobicity|pI|Mw|Charge|Xc1.A|Xc1.R|Xc1.N|Xc1.D|Xc1.C|Xc1.E|Xc1.Q|Xc1.G|Xc1.H|Xc1.I|Xc1.L|Xc1.K|Xc1.M|Xc1.F|Xc1.P|Xc1.S|Xc1.T|Xc1.W|Xc1.Y|Xc1.V|Xc2.lambda.1|Xc2.lambda.2
COEFNAME_COUNT=27
COEFNAMES=Amphiphilicity|Hydrophobicity|pI|Mw|Charge|Xc1.A|Xc1.R|Xc1.N|Xc1.D|Xc1.C|Xc1.E|Xc1.Q|Xc1.G|Xc1.H|Xc1.I|Xc1.L|Xc1.K|Xc1.M|Xc1.F|Xc1.P|Xc1.S|Xc1.T|Xc1.W|Xc1.Y|Xc1.V|Xc2.lambda.1|Xc2.lambda.2
COEFNAMES_MATCH=TRUE
PREPROCESS_METHODS=center|scale|ignore
CENTER_COUNT=27
SCALE_COUNT=27
FEATURE_COMPATIBLE=TRUE
SMOKE_PROB=0.0129205131655137
SMOKE_TEST=PASS
AUDIT_COMPLETE=TRUE

========================================================================================================================
==============================================================================================================================
CELL 17 PASS - ampir 1.1.0 FINAL MATURE MODEL RECIPE VERIFIED AND LOCKED
==============================================================================================================================
LOCK ACTION            : NEW ampir IMPLEMENTATION CONTRACT CREATED
R                      : 4.6.1
ampir                  : 1.1.0
caret                  : 7.0.1
kernlab                : 0.9.33
------------------------------------------------------------------------------------------------------------------------------
ampir MATURE RECIPE
Classifier             : svmRadial
Predictors             : 27
sigma                  : 0.07
C                      : 1.0
Preprocess             : center | scale | ignore
Center count           : 27
Scale count            : 27
Feature compatibility  : PASS
Official smoke test    : PASS
Smoke probability      : 0.01292051
------------------------------------------------------------------------------------------------------------------------------
HISTORICAL DISCREPANCY
Earlier tuning report : sigma=0.06, C=1
Installed final model : sigma=0.07, C=1
BENCHMARK LOCK        : sigma=0.07, C=1
------------------------------------------------------------------------------------------------------------------------------
Benchmark training     : FALSE
Adapter self-test      : PENDING
Training gate          : CLOSED
------------------------------------------------------------------------------------------------------------------------------
27 PREDICTORS
Amphiphilicity | Hydrophobicity | pI | Mw | Charge | Xc1.A | Xc1.R | Xc1.N | Xc1.D | Xc1.C | Xc1.E | Xc1.Q | Xc1.G | Xc1.H | Xc1.I | Xc1.L | Xc1.K | Xc1.M | Xc1.F | Xc1.P | Xc1.S | Xc1.T | Xc1.W | Xc1.Y | Xc1.V | Xc2.lambda.1 | Xc2.lambda.2
------------------------------------------------------------------------------------------------------------------------------
Audit TXT              : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_ampir_final_package_recipe_audit.txt
Audit SHA256           : b62e3a69b7f61b6dbe1bace8f44f2069620f7569af40651cc391883c8d087dfe
Implementation contract: /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampir_FINAL_implementation_contract.json
==============================================================================================================================

In [15]:
# ============================================================
# CELL 18 - FINAL CORRECTED / RESTART-SAFE
# ampir 1.1.0 ADAPTER END-TO-END SELF-TEST
#
# OFFICIAL SEMANTICS
# ------------------
# Benchmark label 0 -> Bg  (background / non-AMP)
# Benchmark label 1 -> Tg  (target / AMP)
#
# ampir::predict_amps() returns probability column #2.
# Therefore this cell verifies explicitly:
#
#   predict(..., type="prob") columns == Bg | Tg
#   column 2 == Tg
#   ampir::predict_amps(... )$prob_AMP == P(Tg)
#
# OFFICIAL RECIPE
# ---------------
# Features    : ampir::calculate_features()
# Predictors  : 27
# Model       : caret::svmRadial
# sigma       : 0.07
# C           : 1
# Preprocess  : center + scale
#
# SELF-TEST DATA ONLY
# -------------------
# GenPept TRAIN:
#   64 Bg + 64 Tg
#
# GenPept VALIDATION:
#   16 Bg + 16 Tg
#
# NO TEST DATA
# NO EXTERNAL TARGET
# NO BENCHMARK RESULT
# ============================================================


from pathlib import Path
from datetime import datetime

import hashlib
import json
import re
import shutil
import subprocess

import numpy as np
import pandas as pd


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

WORK_ROOT = Path(
    "/home/pc/genpept_benchmark17_work"
)

SELFTEST_ROOT = (
    WORK_ROOT
    / "published_selftests"
    / "ampir"
)


for path in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    WORK_ROOT,
]:
    assert path.is_dir(), (
        f"Missing required directory:\n{path}"
    )


SELFTEST_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# 2. HELPERS
# ============================================================

def load_json(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as f:
        return json.load(f)


def sha256_file(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda: f.read(
                1024 * 1024
            ),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


def get_value(
    text,
    key,
):

    match = re.search(
        rf"(?m)^{re.escape(key)}=(.*)$",
        text,
    )

    assert match is not None, (
        f"Missing R output field: {key}"
    )

    return match.group(1).strip()


# ============================================================
# 3. LOAD LOCKED STATE
# ============================================================

BENCHMARK_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark4_FINAL_v1_manifest.json"
)

AMPIR_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampir_FINAL_implementation_contract.json"
)

TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)


for path in [
    BENCHMARK_MANIFEST_PATH,
    AMPIR_CONTRACT_PATH,
    TRAINING_GATE_PATH,
]:
    assert path.is_file(), (
        f"Missing required artifact:\n{path}"
    )


benchmark_manifest = load_json(
    BENCHMARK_MANIFEST_PATH
)

ampir_payload = load_json(
    AMPIR_CONTRACT_PATH
)

gate_before = load_json(
    TRAINING_GATE_PATH
)


ampir_contract = (
    ampir_payload[
        "contract"
    ]
)


# ============================================================
# 4. VERIFY LOCKED ampir RECIPE
# ============================================================

assert (
    ampir_contract[
        "package_version"
    ]
    == "1.1.0"
)


assert (
    ampir_contract[
        "classifier"
    ]
    == "caret_svmRadial"
)


assert (
    ampir_contract[
        "features"
    ][
        "count"
    ]
    == 27
)


assert np.isclose(
    ampir_contract[
        "hyperparameters"
    ][
        "sigma"
    ],
    0.07,
)


assert np.isclose(
    ampir_contract[
        "hyperparameters"
    ][
        "C"
    ],
    1.0,
)


assert gate_before[
    "open"
] is False


assert (
    gate_before[
        "benchmark_training_allowed"
    ]
    is False
)


EXPECTED_PREDICTORS = (
    ampir_contract[
        "features"
    ][
        "names"
    ]
)


assert len(
    EXPECTED_PREDICTORS
) == 27


# ============================================================
# 5. LOAD FINAL COHORT
# ============================================================

FINAL_COHORT_PATH = Path(
    benchmark_manifest[
        "final_cohort"
    ][
        "path"
    ]
)


EXPECTED_COHORT_SHA256 = (
    benchmark_manifest[
        "final_cohort"
    ][
        "sha256"
    ]
)


assert FINAL_COHORT_PATH.is_file()


assert (
    sha256_file(
        FINAL_COHORT_PATH
    )
    ==
    EXPECTED_COHORT_SHA256
)


df = pd.read_csv(
    FINAL_COHORT_PATH,
    low_memory=False,
)


required_columns = {
    "sample_id",
    "dataset",
    "split",
    "label",
    "sequence",
}


assert required_columns.issubset(
    df.columns
)


# ============================================================
# 6. SOURCE DATASET
# ============================================================

SOURCE_DATASET = (
    "GenPept_Curated_2025"
)


source_df = (
    df[
        df[
            "dataset"
        ]
        == SOURCE_DATASET
    ]
    .copy()
)


train_pool = (
    source_df[
        source_df[
            "split"
        ]
        == "train"
    ]
    .copy()
)


validation_pool = (
    source_df[
        source_df[
            "split"
        ]
        == "validation"
    ]
    .copy()
)


assert len(
    train_pool
) == 7700


assert len(
    validation_pool
) == 990


assert set(
    train_pool[
        "label"
    ].unique()
) == {
    0,
    1,
}


assert set(
    validation_pool[
        "label"
    ].unique()
) == {
    0,
    1,
}


# ============================================================
# 7. DETERMINISTIC SELF-TEST SUBSET
# ============================================================

def deterministic_class_sample(
    frame,
    label,
    n,
):

    subset = (
        frame[
            frame[
                "label"
            ]
            == label
        ]
        .assign(
            _sort_id=
                lambda x:
                    x[
                        "sample_id"
                    ].astype(str)
        )
        .sort_values(
            [
                "_sort_id",
                "sequence",
            ],
            kind="mergesort",
        )
        .head(n)
        .drop(
            columns=[
                "_sort_id"
            ]
        )
        .copy()
    )


    assert len(
        subset
    ) == n


    return subset


train_subset = pd.concat(
    [
        deterministic_class_sample(
            train_pool,
            label=0,
            n=64,
        ),

        deterministic_class_sample(
            train_pool,
            label=1,
            n=64,
        ),
    ],
    ignore_index=True,
)


validation_subset = pd.concat(
    [
        deterministic_class_sample(
            validation_pool,
            label=0,
            n=16,
        ),

        deterministic_class_sample(
            validation_pool,
            label=1,
            n=16,
        ),
    ],
    ignore_index=True,
)


train_subset = (
    train_subset
    .sort_values(
        "sample_id",
        kind="mergesort",
    )
    .reset_index(
        drop=True
    )
)


validation_subset = (
    validation_subset
    .sort_values(
        "sample_id",
        kind="mergesort",
    )
    .reset_index(
        drop=True
    )
)


# ============================================================
# 8. HARD SCOPE CHECKS
# ============================================================

assert len(
    train_subset
) == 128


assert len(
    validation_subset
) == 32


assert (
    train_subset[
        "label"
    ]
    .value_counts()
    .sort_index()
    .to_dict()
    ==
    {
        0: 64,
        1: 64,
    }
)


assert (
    validation_subset[
        "label"
    ]
    .value_counts()
    .sort_index()
    .to_dict()
    ==
    {
        0: 16,
        1: 16,
    }
)


assert (
    train_subset[
        "split"
    ]
    == "train"
).all()


assert (
    validation_subset[
        "split"
    ]
    == "validation"
).all()


assert not (
    train_subset[
        "split"
    ]
    == "test"
).any()


assert not (
    validation_subset[
        "split"
    ]
    == "test"
).any()


assert set(
    train_subset[
        "sample_id"
    ]
).isdisjoint(
    set(
        validation_subset[
            "sample_id"
        ]
    )
)


assert set(
    train_subset[
        "sequence"
    ]
).isdisjoint(
    set(
        validation_subset[
            "sequence"
        ]
    )
)


# ============================================================
# 9. MAP BENCHMARK LABELS TO OFFICIAL ampir LABELS
#
# Official AMP_pub convention:
#
#   Bg = Background = non-AMP = benchmark 0
#   Tg = Target     = AMP     = benchmark 1
#
# This is important because predict_amps_core() uses
# probability column 2 as prob_AMP.
# ============================================================

LABEL_MAP = {
    0: "Bg",
    1: "Tg",
}


def prepare_ampir_input(
    frame,
):

    out = pd.DataFrame(
        {
            "seq_name":
                frame[
                    "sample_id"
                ].astype(str),

            "seq_aa":
                frame[
                    "sequence"
                ].astype(str),

            "Label":
                frame[
                    "label"
                ]
                .map(
                    LABEL_MAP
                ),
        }
    )


    assert out[
        "Label"
    ].notna().all()


    return out


train_r = prepare_ampir_input(
    train_subset
)

validation_r = prepare_ampir_input(
    validation_subset
)


assert (
    train_r[
        "Label"
    ]
    .value_counts()
    .to_dict()
    ==
    {
        "Bg": 64,
        "Tg": 64,
    }
)


assert (
    validation_r[
        "Label"
    ]
    .value_counts()
    .to_dict()
    ==
    {
        "Bg": 16,
        "Tg": 16,
    }
)


# ============================================================
# 10. SAVE SELF-TEST INPUTS
# ============================================================

TRAIN_INPUT_PATH = (
    SELFTEST_ROOT
    / "ampir_selftest_train.csv"
)

VALIDATION_INPUT_PATH = (
    SELFTEST_ROOT
    / "ampir_selftest_validation.csv"
)

MODEL_PATH = (
    SELFTEST_ROOT
    / "ampir_selftest_model.rds"
)

PREDICTION_PATH = (
    SELFTEST_ROOT
    / "ampir_selftest_validation_predictions.csv"
)

R_SCRIPT_PATH = (
    SELFTEST_ROOT
    / "ampir_adapter_selftest.R"
)


train_r.to_csv(
    TRAIN_INPUT_PATH,
    index=False,
)


validation_r.to_csv(
    VALIDATION_INPUT_PATH,
    index=False,
)


# Remove incomplete artifacts from the previous failed
# self-test attempt, if they exist.
for stale_path in [
    MODEL_PATH,
    PREDICTION_PATH,
]:

    if stale_path.exists():
        stale_path.unlink()


# ============================================================
# 11. LOCATE CONDA
# ============================================================

CONDA_EXE = shutil.which(
    "conda"
)


if CONDA_EXE is None:

    fallback = Path(
        "/home/pc/miniconda3/bin/conda"
    )

    if fallback.is_file():
        CONDA_EXE = str(
            fallback
        )


assert CONDA_EXE is not None


AMPIR_ENV = (
    "genpept_r_models"
)


# ============================================================
# 12. R ADAPTER SELF-TEST
#
# IMPORTANT:
# - Uses official Bg/Tg semantics.
# - Does NOT assert adapter_model$levels.
# - Verifies actual probability-column order instead.
# ============================================================

R_SCRIPT = r'''
args <- commandArgs(
    trailingOnly=TRUE
)


stopifnot(
    length(args) == 4
)


train_path <- args[1]
validation_path <- args[2]
model_path <- args[3]
prediction_path <- args[4]


suppressPackageStartupMessages(
    library(ampir)
)

suppressPackageStartupMessages(
    library(caret)
)

suppressPackageStartupMessages(
    library(kernlab)
)


# ============================================================
# LOCKED OFFICIAL PREDICTORS
# ============================================================

predictors <- c(
    "Amphiphilicity",
    "Hydrophobicity",
    "pI",
    "Mw",
    "Charge",
    "Xc1.A",
    "Xc1.R",
    "Xc1.N",
    "Xc1.D",
    "Xc1.C",
    "Xc1.E",
    "Xc1.Q",
    "Xc1.G",
    "Xc1.H",
    "Xc1.I",
    "Xc1.L",
    "Xc1.K",
    "Xc1.M",
    "Xc1.F",
    "Xc1.P",
    "Xc1.S",
    "Xc1.T",
    "Xc1.W",
    "Xc1.Y",
    "Xc1.V",
    "Xc2.lambda.1",
    "Xc2.lambda.2"
)


stopifnot(
    length(
        predictors
    ) == 27
)


# ============================================================
# READ TRAIN + VALIDATION ONLY
# ============================================================

train_df <- read.csv(
    train_path,
    stringsAsFactors=FALSE,
    check.names=FALSE
)


validation_df <- read.csv(
    validation_path,
    stringsAsFactors=FALSE,
    check.names=FALSE
)


stopifnot(
    nrow(
        train_df
    ) == 128
)


stopifnot(
    nrow(
        validation_df
    ) == 32
)


stopifnot(
    all(
        c(
            "seq_name",
            "seq_aa",
            "Label"
        )
        %in%
        colnames(
            train_df
        )
    )
)


stopifnot(
    all(
        train_df$Label
        %in%
        c(
            "Bg",
            "Tg"
        )
    )
)


stopifnot(
    all(
        validation_df$Label
        %in%
        c(
            "Bg",
            "Tg"
        )
    )
)


# ============================================================
# FORCE OFFICIAL SEMANTIC ORDER
#
# Bg = class 1 = non-AMP
# Tg = class 2 = AMP
#
# This matches ampir predict_amps_core(), which takes
# probability column 2.
# ============================================================

train_df$Label <- factor(
    train_df$Label,
    levels=c(
        "Bg",
        "Tg"
    )
)


validation_df$Label <- factor(
    validation_df$Label,
    levels=c(
        "Bg",
        "Tg"
    )
)


stopifnot(
    identical(
        levels(
            train_df$Label
        ),
        c(
            "Bg",
            "Tg"
        )
    )
)


stopifnot(
    identical(
        levels(
            validation_df$Label
        ),
        c(
            "Bg",
            "Tg"
        )
    )
)


# ============================================================
# OFFICIAL FEATURE EXTRACTION
# ============================================================

train_features <- calculate_features(
    train_df[
        ,
        c(
            "seq_name",
            "seq_aa"
        )
    ],
    min_len=10
)


validation_features <- calculate_features(
    validation_df[
        ,
        c(
            "seq_name",
            "seq_aa"
        )
    ],
    min_len=10
)


stopifnot(
    all(
        predictors
        %in%
        colnames(
            train_features
        )
    )
)


stopifnot(
    all(
        predictors
        %in%
        colnames(
            validation_features
        )
    )
)


# ============================================================
# TRAINING FRAME
# ============================================================

training_frame <- train_features[
    ,
    predictors,
    drop=FALSE
]


training_frame$Label <- (
    train_df$Label
)


stopifnot(
    nrow(
        training_frame
    ) == 128
)


stopifnot(
    ncol(
        training_frame
    ) == 28
)


# ============================================================
# OFFICIAL AMP_pub WEIGHT FORMULA
#
# Reproduces the published source literally:
#
# model_weights <- ifelse(
#   Label == "Tg",
#   (1/table(Label)[1]) * 0.5,
#   (1/table(Label)[2]) * 0.5
# )
#
# In this balanced self-test both class counts are 64.
# ============================================================

label_table <- table(
    train_df$Label
)


stopifnot(
    identical(
        names(
            label_table
        ),
        c(
            "Bg",
            "Tg"
        )
    )
)


model_weights <- ifelse(
    train_df$Label == "Tg",
    (
        1
        /
        as.numeric(
            label_table[1]
        )
    )
    * 0.5,
    (
        1
        /
        as.numeric(
            label_table[2]
        )
    )
    * 0.5
)


stopifnot(
    length(
        model_weights
    ) == 128
)


stopifnot(
    all(
        is.finite(
            model_weights
        )
    )
)


# Balanced self-test:
# both totals should be exactly 0.5.
bg_total_weight <- sum(
    model_weights[
        train_df$Label
        ==
        "Bg"
    ]
)


tg_total_weight <- sum(
    model_weights[
        train_df$Label
        ==
        "Tg"
    ]
)


stopifnot(
    abs(
        bg_total_weight
        - 0.5
    )
    < 1e-12
)


stopifnot(
    abs(
        tg_total_weight
        - 0.5
    )
    < 1e-12
)


# ============================================================
# FIXED-HYPERPARAMETER FIT
#
# No CV tuning here because sigma/C were locked
# before benchmark results.
# ============================================================

ctrl <- trainControl(
    method="none",
    classProbs=TRUE
)


set.seed(100)


adapter_model <- train(
    Label ~ .,
    data=training_frame,
    method="svmRadial",
    trControl=ctrl,
    preProcess=c(
        "center",
        "scale"
    ),
    weights=model_weights,
    tuneGrid=data.frame(
        sigma=0.07,
        C=1
    )
)


# ============================================================
# MODEL STRUCTURE CHECK
# ============================================================

stopifnot(
    adapter_model$method
    ==
    "svmRadial"
)


stopifnot(
    abs(
        adapter_model$bestTune$sigma[1]
        - 0.07
    )
    < 1e-12
)


stopifnot(
    abs(
        adapter_model$bestTune$C[1]
        - 1
    )
    < 1e-12
)


stopifnot(
    !is.null(
        adapter_model$trainingData
    )
)


stopifnot(
    colnames(
        adapter_model$trainingData
    )[1]
    ==
    ".outcome"
)


adapter_predictors <- colnames(
    adapter_model$trainingData
)[-1]


stopifnot(
    identical(
        as.character(
            adapter_predictors
        ),
        as.character(
            predictors
        )
    )
)


# ============================================================
# CRITICAL CORRECTION:
#
# Do NOT use adapter_model$levels.
#
# Verify class semantics from the stored training outcome.
# ============================================================

stored_outcome_levels <- levels(
    adapter_model$trainingData$.outcome
)


cat(
    "STORED_OUTCOME_LEVELS=",
    paste(
        stored_outcome_levels,
        collapse="|"
    ),
    "\n",
    sep=""
)


stopifnot(
    identical(
        stored_outcome_levels,
        c(
            "Bg",
            "Tg"
        )
    )
)


# ============================================================
# PREPROCESS CHECK
# ============================================================

stopifnot(
    !is.null(
        adapter_model$preProcess
    )
)


stopifnot(
    length(
        adapter_model$preProcess$mean
    )
    == 27
)


stopifnot(
    length(
        adapter_model$preProcess$std
    )
    == 27
)


# ============================================================
# DIRECT caret PROBABILITY
# ============================================================

direct_prob <- predict(
    adapter_model,
    newdata=validation_features[
        ,
        predictors,
        drop=FALSE
    ],
    type="prob"
)


prob_columns <- colnames(
    direct_prob
)


cat(
    "DIRECT_PROB_COLUMNS=",
    paste(
        prob_columns,
        collapse="|"
    ),
    "\n",
    sep=""
)


# Critical semantic requirement for ampir:
# column 2 MUST be Tg = AMP.
stopifnot(
    identical(
        prob_columns,
        c(
            "Bg",
            "Tg"
        )
    )
)


stopifnot(
    prob_columns[2]
    ==
    "Tg"
)


p_tg_direct <- direct_prob[
    ,
    "Tg"
]


p_column2_direct <- direct_prob[
    ,
    2
]


stopifnot(
    max(
        abs(
            p_tg_direct
            -
            p_column2_direct
        )
    )
    <
    1e-15
)


# ============================================================
# OFFICIAL ampir CUSTOM-MODEL INTERFACE
# ============================================================

ampir_input <- validation_df[
    ,
    c(
        "seq_name",
        "seq_aa"
    )
]


ampir_prediction <- predict_amps(
    ampir_input,
    min_len=10,
    n_cores=1,
    model=adapter_model
)


stopifnot(
    "prob_AMP"
    %in%
    colnames(
        ampir_prediction
    )
)


p_ampir <- (
    ampir_prediction$prob_AMP
)


stopifnot(
    length(
        p_ampir
    ) == 32
)


stopifnot(
    all(
        is.finite(
            p_ampir
        )
    )
)


stopifnot(
    all(
        p_ampir
        >= 0
        &
        p_ampir
        <= 1
    )
)


# ============================================================
# CRITICAL END-TO-END EQUALITY
#
# ampir::predict_amps() must return exactly P(Tg).
# ============================================================

max_abs_difference <- max(
    abs(
        p_tg_direct
        -
        p_ampir
    )
)


stopifnot(
    max_abs_difference
    <
    1e-10
)


# ============================================================
# SAVE SELF-TEST MODEL / PREDICTIONS
# ============================================================

saveRDS(
    adapter_model,
    model_path
)


output_df <- data.frame(

    seq_name=
        validation_df$seq_name,

    true_label=
        as.character(
            validation_df$Label
        ),

    direct_prob_Bg=
        direct_prob[
            ,
            "Bg"
        ],

    direct_prob_Tg=
        direct_prob[
            ,
            "Tg"
        ],

    ampir_prob_AMP=
        p_ampir,

    abs_difference_Tg_vs_ampir=
        abs(
            p_tg_direct
            -
            p_ampir
        ),

    stringsAsFactors=FALSE
)


write.csv(
    output_df,
    prediction_path,
    row.names=FALSE
)


stopifnot(
    file.exists(
        model_path
    )
)


stopifnot(
    file.exists(
        prediction_path
    )
)


# ============================================================
# MACHINE-READABLE REPORT
# ============================================================

cat(
    "AMPIR_VERSION=",
    as.character(
        packageVersion(
            "ampir"
        )
    ),
    "\n",
    sep=""
)


cat(
    "METHOD=",
    adapter_model$method,
    "\n",
    sep=""
)


cat(
    "SIGMA=",
    adapter_model$bestTune$sigma[1],
    "\n",
    sep=""
)


cat(
    "C=",
    adapter_model$bestTune$C[1],
    "\n",
    sep=""
)


cat(
    "PREDICTOR_COUNT=",
    length(
        adapter_predictors
    ),
    "\n",
    sep=""
)


cat(
    "TRAIN_N=",
    nrow(
        train_df
    ),
    "\n",
    sep=""
)


cat(
    "VALIDATION_N=",
    nrow(
        validation_df
    ),
    "\n",
    sep=""
)


cat(
    "TRAIN_BG_N=",
    sum(
        train_df$Label
        ==
        "Bg"
    ),
    "\n",
    sep=""
)


cat(
    "TRAIN_TG_N=",
    sum(
        train_df$Label
        ==
        "Tg"
    ),
    "\n",
    sep=""
)


cat(
    "VALIDATION_BG_N=",
    sum(
        validation_df$Label
        ==
        "Bg"
    ),
    "\n",
    sep=""
)


cat(
    "VALIDATION_TG_N=",
    sum(
        validation_df$Label
        ==
        "Tg"
    ),
    "\n",
    sep=""
)


cat(
    "WEIGHT_SUM_BG=",
    format(
        bg_total_weight,
        digits=17
    ),
    "\n",
    sep=""
)


cat(
    "WEIGHT_SUM_TG=",
    format(
        tg_total_weight,
        digits=17
    ),
    "\n",
    sep=""
)


cat(
    "CENTER_COUNT=",
    length(
        adapter_model$preProcess$mean
    ),
    "\n",
    sep=""
)


cat(
    "SCALE_COUNT=",
    length(
        adapter_model$preProcess$std
    ),
    "\n",
    sep=""
)


cat(
    "PROBABILITY_COLUMNS=",
    paste(
        prob_columns,
        collapse="|"
    ),
    "\n",
    sep=""
)


cat(
    "AMP_PROBABILITY_COLUMN=",
    prob_columns[2],
    "\n",
    sep=""
)


cat(
    "PROB_MIN=",
    min(
        p_ampir
    ),
    "\n",
    sep=""
)


cat(
    "PROB_MAX=",
    max(
        p_ampir
    ),
    "\n",
    sep=""
)


cat(
    "MAX_ABS_DIFFERENCE=",
    format(
        max_abs_difference,
        scientific=TRUE,
        digits=17
    ),
    "\n",
    sep=""
)


cat(
    "MODEL_FILE_EXISTS=",
    file.exists(
        model_path
    ),
    "\n",
    sep=""
)


cat(
    "PREDICTION_FILE_EXISTS=",
    file.exists(
        prediction_path
    ),
    "\n",
    sep=""
)


cat(
    "SELFTEST_PASS=TRUE\n"
)
'''


with open(
    R_SCRIPT_PATH,
    "w",
    encoding="utf-8",
    newline="\n",
) as f:

    f.write(
        R_SCRIPT
    )


assert R_SCRIPT_PATH.is_file()


# ============================================================
# 13. EXECUTE R SELF-TEST
# ============================================================

result = subprocess.run(
    [
        CONDA_EXE,
        "run",
        "--no-capture-output",
        "-n",
        AMPIR_ENV,
        "Rscript",
        str(
            R_SCRIPT_PATH
        ),
        str(
            TRAIN_INPUT_PATH
        ),
        str(
            VALIDATION_INPUT_PATH
        ),
        str(
            MODEL_PATH
        ),
        str(
            PREDICTION_PATH
        ),
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    text=True,
    timeout=300,
    check=False,
)


stdout_text = (
    result.stdout or ""
)

stderr_text = (
    result.stderr or ""
)


# ============================================================
# 14. ALWAYS SHOW R OUTPUT BEFORE ASSERT
# ============================================================

print("=" * 122)

print(
    "ampir FINAL ADAPTER SELF-TEST OUTPUT"
)

print("=" * 122)

print(
    stdout_text
)


if stderr_text.strip():

    print("-" * 122)

    print(
        "R STDERR / WARNINGS"
    )

    print("-" * 122)

    print(
        stderr_text
    )


print("=" * 122)


assert result.returncode == 0, (
    "ampir adapter self-test failed. "
    "Full R diagnostic is printed above."
)


# ============================================================
# 15. PARSE RESULTS
# ============================================================

AMPIR_VERSION = get_value(
    stdout_text,
    "AMPIR_VERSION",
)

METHOD = get_value(
    stdout_text,
    "METHOD",
)

SIGMA = float(
    get_value(
        stdout_text,
        "SIGMA",
    )
)

C_VALUE = float(
    get_value(
        stdout_text,
        "C",
    )
)

PREDICTOR_COUNT = int(
    get_value(
        stdout_text,
        "PREDICTOR_COUNT",
    )
)

TRAIN_N = int(
    get_value(
        stdout_text,
        "TRAIN_N",
    )
)

VALIDATION_N = int(
    get_value(
        stdout_text,
        "VALIDATION_N",
    )
)

TRAIN_BG_N = int(
    get_value(
        stdout_text,
        "TRAIN_BG_N",
    )
)

TRAIN_TG_N = int(
    get_value(
        stdout_text,
        "TRAIN_TG_N",
    )
)

VALIDATION_BG_N = int(
    get_value(
        stdout_text,
        "VALIDATION_BG_N",
    )
)

VALIDATION_TG_N = int(
    get_value(
        stdout_text,
        "VALIDATION_TG_N",
    )
)

WEIGHT_SUM_BG = float(
    get_value(
        stdout_text,
        "WEIGHT_SUM_BG",
    )
)

WEIGHT_SUM_TG = float(
    get_value(
        stdout_text,
        "WEIGHT_SUM_TG",
    )
)

CENTER_COUNT = int(
    get_value(
        stdout_text,
        "CENTER_COUNT",
    )
)

SCALE_COUNT = int(
    get_value(
        stdout_text,
        "SCALE_COUNT",
    )
)

STORED_OUTCOME_LEVELS = (
    get_value(
        stdout_text,
        "STORED_OUTCOME_LEVELS",
    )
)

PROBABILITY_COLUMNS = (
    get_value(
        stdout_text,
        "PROBABILITY_COLUMNS",
    )
)

AMP_PROBABILITY_COLUMN = (
    get_value(
        stdout_text,
        "AMP_PROBABILITY_COLUMN",
    )
)

PROB_MIN = float(
    get_value(
        stdout_text,
        "PROB_MIN",
    )
)

PROB_MAX = float(
    get_value(
        stdout_text,
        "PROB_MAX",
    )
)

MAX_ABS_DIFFERENCE = float(
    get_value(
        stdout_text,
        "MAX_ABS_DIFFERENCE",
    )
)

MODEL_FILE_EXISTS = (
    get_value(
        stdout_text,
        "MODEL_FILE_EXISTS",
    )
    == "TRUE"
)

PREDICTION_FILE_EXISTS = (
    get_value(
        stdout_text,
        "PREDICTION_FILE_EXISTS",
    )
    == "TRUE"
)

SELFTEST_PASS = (
    get_value(
        stdout_text,
        "SELFTEST_PASS",
    )
    == "TRUE"
)


# ============================================================
# 16. HARD SCIENTIFIC ASSERTIONS
# ============================================================

assert AMPIR_VERSION == "1.1.0"

assert METHOD == "svmRadial"

assert np.isclose(
    SIGMA,
    0.07,
)

assert np.isclose(
    C_VALUE,
    1.0,
)

assert PREDICTOR_COUNT == 27

assert TRAIN_N == 128

assert VALIDATION_N == 32

assert TRAIN_BG_N == 64

assert TRAIN_TG_N == 64

assert VALIDATION_BG_N == 16

assert VALIDATION_TG_N == 16

assert np.isclose(
    WEIGHT_SUM_BG,
    0.5,
)

assert np.isclose(
    WEIGHT_SUM_TG,
    0.5,
)

assert CENTER_COUNT == 27

assert SCALE_COUNT == 27


# Critical semantic checks.
assert (
    STORED_OUTCOME_LEVELS
    == "Bg|Tg"
)

assert (
    PROBABILITY_COLUMNS
    == "Bg|Tg"
)

assert (
    AMP_PROBABILITY_COLUMN
    == "Tg"
)


assert (
    0.0
    <= PROB_MIN
    <= 1.0
)

assert (
    0.0
    <= PROB_MAX
    <= 1.0
)

assert (
    PROB_MIN
    <= PROB_MAX
)

assert (
    MAX_ABS_DIFFERENCE
    < 1e-10
)

assert MODEL_FILE_EXISTS is True

assert PREDICTION_FILE_EXISTS is True

assert SELFTEST_PASS is True

assert MODEL_PATH.is_file()

assert PREDICTION_PATH.is_file()


# ============================================================
# 17. VERIFY SAVED PREDICTION FILE
# ============================================================

pred_df = pd.read_csv(
    PREDICTION_PATH
)


assert len(
    pred_df
) == 32


assert {
    "seq_name",
    "true_label",
    "direct_prob_Bg",
    "direct_prob_Tg",
    "ampir_prob_AMP",
    "abs_difference_Tg_vs_ampir",
}.issubset(
    pred_df.columns
)


assert pred_df[
    "direct_prob_Tg"
].between(
    0.0,
    1.0,
    inclusive="both",
).all()


assert pred_df[
    "ampir_prob_AMP"
].between(
    0.0,
    1.0,
    inclusive="both",
).all()


assert (
    pred_df[
        "abs_difference_Tg_vs_ampir"
    ].max()
    < 1e-10
)


# ============================================================
# 18. FINAL ampir ADAPTER CONTRACT
# ============================================================

AMPIR_ADAPTER_CONTRACT = {

    "model_id":
        "ampir",

    "package":
        "ampir",

    "package_version":
        "1.1.0",

    "implementation":
        (
            "official_ampir_custom_"
            "caret_svmRadial_adapter"
        ),

    "official_class_semantics": {

        "Bg":
            "benchmark_label_0_non_AMP",

        "Tg":
            "benchmark_label_1_AMP",
    },

    "class_order": [
        "Bg",
        "Tg",
    ],

    "AMP_probability":
        "second_probability_column_Tg",

    "representation":
        "official_ampir_calculate_features",

    "predictor_count":
        27,

    "predictors":
        EXPECTED_PREDICTORS,

    "classifier":
        "caret::train_svmRadial",

    "hyperparameters": {

        "sigma":
            0.07,

        "C":
            1.0,
    },

    "preprocessing": {

        "methods": [
            "center",
            "scale",
        ],

        "fit_scope":
            "source_train_only",
    },

    "case_weighting": {

        "enabled":
            True,

        "implementation":
            "literal_AMP_pub_tune_model_R_formula",

        "formula": (
            "if Tg: 0.5/table(Label)[1]; "
            "else: 0.5/table(Label)[2]"
        ),
    },

    "hyperparameter_tuning_in_benchmark":
        False,

    "benchmark_internal_resampling_for_tuning":
        False,

    "fixed_hyperparameters_locked_before_results":
        True,

    "model_seeds":
        list(
            range(
                100,
                110
            )
        ),

    "seed_tuning":
        False,

    "source_train_only_fit":
        True,

    "source_validation_only_threshold":
        True,

    "source_test_final_evaluation_only":
        True,

    "external_target_adaptation":
        False,

    "probability_interface_verified":
        True,

    "predict_amps_equals_Tg_probability":
        True,

    "adapter_self_test_status":
        "PASS",
}


# ============================================================
# 19. SAVE SELF-TEST MANIFEST
# ============================================================

SELFTEST_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampir_FINAL_adapter_selftest.json"
)


selftest_payload = {

    "schema_version":
        "2.0",

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "status":
        "IMPLEMENTATION_VALIDATED",

    "implementation_validated":
        True,

    "benchmark_training_performed":
        False,

    "benchmark_test_used":
        False,

    "external_target_used":
        False,

    "selftest": {

        "source_dataset":
            SOURCE_DATASET,

        "train_n":
            128,

        "train_Bg":
            64,

        "train_Tg":
            64,

        "validation_n":
            32,

        "validation_Bg":
            16,

        "validation_Tg":
            16,

        "seed":
            100,

        "probability_columns":
            [
                "Bg",
                "Tg",
            ],

        "AMP_probability_column":
            "Tg",

        "max_abs_difference":
            MAX_ABS_DIFFERENCE,

        "probability_range": [
            PROB_MIN,
            PROB_MAX,
        ],
    },

    "adapter_contract":
        AMPIR_ADAPTER_CONTRACT,

    "upstream_contract": {

        "path":
            str(
                AMPIR_CONTRACT_PATH
            ),

        "sha256":
            sha256_file(
                AMPIR_CONTRACT_PATH
            ),
    },

    "artifacts": {

        "train_input": {

            "path":
                str(
                    TRAIN_INPUT_PATH
                ),

            "sha256":
                sha256_file(
                    TRAIN_INPUT_PATH
                ),
        },

        "validation_input": {

            "path":
                str(
                    VALIDATION_INPUT_PATH
                ),

            "sha256":
                sha256_file(
                    VALIDATION_INPUT_PATH
                ),
        },

        "model": {

            "path":
                str(
                    MODEL_PATH
                ),

            "sha256":
                sha256_file(
                    MODEL_PATH
                ),
        },

        "predictions": {

            "path":
                str(
                    PREDICTION_PATH
                ),

            "sha256":
                sha256_file(
                    PREDICTION_PATH
                ),
        },
    },
}


with open(
    SELFTEST_MANIFEST_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        selftest_payload,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ============================================================
# 20. UPDATE READINESS TABLE
# ============================================================

READINESS_PATH = (
    AUDIT_DIR
    / "benchmark17_published_method_local_readiness_latest.csv"
)


assert READINESS_PATH.is_file()


readiness_df = pd.read_csv(
    READINESS_PATH,
    low_memory=False,
)


ampir_mask = (
    readiness_df[
        "model_id"
    ]
    == "ampir"
)


assert (
    ampir_mask.sum()
    == 1
)


readiness_df.loc[
    ampir_mask,
    "adapter_self_test_passed"
] = True


readiness_df.loc[
    ampir_mask,
    "implementation_validated"
] = True


readiness_df.loc[
    ampir_mask,
    "local_state"
] = (
    "IMPLEMENTATION_VALIDATED"
)


readiness_df.loc[
    ampir_mask,
    "training_allowed"
] = False


readiness_df.to_csv(
    READINESS_PATH,
    index=False,
)


# ============================================================
# 21. RECOMPUTE GLOBAL VALIDATION STATE
# ============================================================

PUBLISHED_IDS = [
    "ampep",
    "ampscannerv2",
    "ampgram",
    "ampir",
    "ampeppy",
    "ai4amp",
    "amplify",
]


validated_methods = []


for model_id in PUBLISHED_IDS:

    manifest_path = (
        MANIFEST_DIR
        / (
            f"benchmark17_{model_id}_"
            "FINAL_adapter_selftest.json"
        )
    )


    if not manifest_path.is_file():
        continue


    payload = load_json(
        manifest_path
    )


    if (
        payload.get(
            "implementation_validated",
            False,
        )
        is True
    ):
        validated_methods.append(
            model_id
        )


validated_methods = sorted(
    validated_methods
)


validated_count = len(
    validated_methods
)


assert "ampir" in validated_methods

assert (
    1
    <= validated_count
    <= 7
)


# ============================================================
# 22. UPDATE TRAINING GATE
# ============================================================

gate_after = load_json(
    TRAINING_GATE_PATH
)


gate_after[
    "published_methods_implementation_validated"
] = validated_count


gate_after[
    "validated_methods"
] = validated_methods


gate_after[
    "updated_at"
] = (
    datetime.now()
    .astimezone()
    .isoformat()
)


if validated_count == 7:

    gate_after[
        "open"
    ] = True


    gate_after[
        "benchmark_training_allowed"
    ] = True


    gate_after[
        "reason"
    ] = (
        "All seven published-method "
        "implementations validated."
    )

else:

    gate_after[
        "open"
    ] = False


    gate_after[
        "benchmark_training_allowed"
    ] = False


    gate_after[
        "reason"
    ] = (
        f"{validated_count}/7 published-method "
        "implementations validated."
    )


with open(
    TRAINING_GATE_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        gate_after,
        f,
        indent=2,
        ensure_ascii=False,
    )


# ============================================================
# 23. FINAL DISK VERIFY
# ============================================================

selftest_check = load_json(
    SELFTEST_MANIFEST_PATH
)


gate_check = load_json(
    TRAINING_GATE_PATH
)


assert (
    selftest_check[
        "implementation_validated"
    ]
    is True
)


assert (
    selftest_check[
        "benchmark_training_performed"
    ]
    is False
)


assert (
    selftest_check[
        "benchmark_test_used"
    ]
    is False
)


assert (
    selftest_check[
        "adapter_contract"
    ][
        "class_order"
    ]
    == [
        "Bg",
        "Tg",
    ]
)


assert (
    selftest_check[
        "adapter_contract"
    ][
        "AMP_probability"
    ]
    ==
    "second_probability_column_Tg"
)


assert (
    "ampir"
    in gate_check[
        "validated_methods"
    ]
)


if validated_count < 7:

    assert (
        gate_check[
            "open"
        ]
        is False
    )


    assert (
        gate_check[
            "benchmark_training_allowed"
        ]
        is False
    )


# ============================================================
# 24. FINAL REPORT
# ============================================================

print("=" * 126)

print(
    "CELL 18 PASS - ampir OFFICIAL ADAPTER "
    "END-TO-END SELF-TEST PASSED"
)

print("=" * 126)

print(
    "Published method       : ampir"
)

print(
    "Implementation status  : VALIDATED"
)

print(
    "ampir version          : 1.1.0"
)

print(
    "Classifier             : svmRadial"
)

print(
    "Predictors             : 27"
)

print(
    "sigma                  : 0.07"
)

print(
    "C                      : 1"
)

print(
    "Preprocess             : center + scale"
)

print("-" * 126)

print(
    "CLASS SEMANTICS"
)

print(
    "Benchmark 0            : Bg = background / non-AMP"
)

print(
    "Benchmark 1            : Tg = target / AMP"
)

print(
    f"Stored outcome levels  : {STORED_OUTCOME_LEVELS}"
)

print(
    f"Probability columns    : {PROBABILITY_COLUMNS}"
)

print(
    f"AMP probability column : {AMP_PROBABILITY_COLUMN}"
)

print("-" * 126)

print(
    f"Self-test train        : {TRAIN_N} "
    f"({TRAIN_BG_N} Bg + {TRAIN_TG_N} Tg)"
)

print(
    f"Self-test validation   : {VALIDATION_N} "
    f"({VALIDATION_BG_N} Bg + {VALIDATION_TG_N} Tg)"
)

print(
    "Test rows used         : 0"
)

print(
    "External target used   : 0"
)

print(
    "Benchmark training     : FALSE"
)

print("-" * 126)

print(
    f"Probability range      : "
    f"[{PROB_MIN:.8f}, {PROB_MAX:.8f}]"
)

print(
    f"caret P(Tg) vs ampir   : "
    f"max |delta| = {MAX_ABS_DIFFERENCE:.3e}"
)

print(
    "Probability semantics  : PASS"
)

print(
    "Serialization          : PASS"
)

print("-" * 126)

print(
    f"Published validated    : {validated_count}/7"
)

print(
    f"Validated methods      : {validated_methods}"
)

print(
    f"TRAINING GATE          : "
    f"{'OPEN' if gate_check['open'] else 'CLOSED'}"
)

print("-" * 126)

print(
    f"Self-test model        : {MODEL_PATH}"
)

print(
    f"Predictions            : {PREDICTION_PATH}"
)

print(
    f"Self-test manifest     : {SELFTEST_MANIFEST_PATH}"
)

print(
    f"Training gate          : {TRAINING_GATE_PATH}"
)

print("=" * 126)

==========================================================================================================================
ampir FINAL ADAPTER SELF-TEST OUTPUT
==========================================================================================================================
STORED_OUTCOME_LEVELS=Bg|Tg
DIRECT_PROB_COLUMNS=Bg|Tg
AMPIR_VERSION=1.1.0
METHOD=svmRadial
SIGMA=0.07
C=1
PREDICTOR_COUNT=27
TRAIN_N=128
VALIDATION_N=32
TRAIN_BG_N=64
TRAIN_TG_N=64
VALIDATION_BG_N=16
VALIDATION_TG_N=16
WEIGHT_SUM_BG=0.5
WEIGHT_SUM_TG=0.5
CENTER_COUNT=27
SCALE_COUNT=27
PROBABILITY_COLUMNS=Bg|Tg
AMP_PROBABILITY_COLUMN=Tg
PROB_MIN=0.0111469
PROB_MAX=0.9741405
MAX_ABS_DIFFERENCE=0e+00
MODEL_FILE_EXISTS=TRUE
PREDICTION_FILE_EXISTS=TRUE
SELFTEST_PASS=TRUE

==========================================================================================================================
==============================================================================================================================
CELL 18 PASS - ampir OFFICIAL ADAPTER END-TO-END SELF-TEST PASSED
==============================================================================================================================
Published method       : ampir
Implementation status  : VALIDATED
ampir version          : 1.1.0
Classifier             : svmRadial
Predictors             : 27
sigma                  : 0.07
C                      : 1
Preprocess             : center + scale
------------------------------------------------------------------------------------------------------------------------------
CLASS SEMANTICS
Benchmark 0            : Bg = background / non-AMP
Benchmark 1            : Tg = target / AMP
Stored outcome levels  : Bg|Tg
Probability columns    : Bg|Tg
AMP probability column : Tg
------------------------------------------------------------------------------------------------------------------------------
Self-test train        : 128 (64 Bg + 64 Tg)
Self-test validation   : 32 (16 Bg + 16 Tg)
Test rows used         : 0
External target used   : 0
Benchmark training     : FALSE
------------------------------------------------------------------------------------------------------------------------------
Probability range      : [0.01114690, 0.97414050]
caret P(Tg) vs ampir   : max |delta| = 0.000e+00
Probability semantics  : PASS
Serialization          : PASS
------------------------------------------------------------------------------------------------------------------------------
Published validated    : 1/7
Validated methods      : ['ampir']
TRAINING GATE          : CLOSED
------------------------------------------------------------------------------------------------------------------------------
Self-test model        : /home/pc/genpept_benchmark17_work/published_selftests/ampir/ampir_selftest_model.rds
Predictions            : /home/pc/genpept_benchmark17_work/published_selftests/ampir/ampir_selftest_validation_predictions.csv
Self-test manifest     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampir_FINAL_adapter_selftest.json
Training gate          : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_training_gate.json
==============================================================================================================================

In [16]:
# ============================================================
# CELL 19 - RESTART-SAFE
# AmpGram OFFICIAL SOURCE RECIPE AUDIT + LOCK
#
# SOURCE:
#   michbur/AmpGram-analysis
#
# EXPECTED LOCAL COMMIT:
#   9a76d4c90a74622ec5ad9dc8b3d908799ac7745a
#
# THIS CELL:
# - verifies local source files against Git HEAD
# - extracts exact published algorithm structure
# - locks the benchmark adaptation BEFORE results
#
# NO R EXECUTION
# NO PACKAGE INSTALLATION
# NO MODEL TRAINING
# NO TEST EVALUATION
# NO TRAINING-GATE CHANGE
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import re
import subprocess


# ============================================================
# 1. PROJECT STATE
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

AMPGRAM_SOURCE = Path(
    "/home/pc/genpept_sources/AmpGram-analysis"
)


for path in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    AMPGRAM_SOURCE,
]:
    assert path.is_dir(), (
        f"Required directory missing:\n{path}"
    )


# ============================================================
# 2. HELPERS
# ============================================================

def load_json(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as f:

        return json.load(f)


def read_text(path):

    with open(
        path,
        "r",
        encoding="utf-8",
        errors="replace",
    ) as f:

        return f.read()


def sha256_file(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda: f.read(
                1024 * 1024
            ),
            b"",
        ):

            h.update(chunk)

    return h.hexdigest()


def git_output(*args):

    result = subprocess.run(
        [
            "git",
            "-C",
            str(AMPGRAM_SOURCE),
            *args,
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
        timeout=30,
    )

    assert result.returncode == 0, (
        f"git command failed:\n"
        f"{' '.join(args)}\n\n"
        f"{result.stderr}"
    )

    return result.stdout.strip()


def require_regex(
    text,
    pattern,
    description,
):

    found = re.search(
        pattern,
        text,
        flags=re.MULTILINE | re.DOTALL,
    )

    assert found is not None, (
        "AmpGram official-source marker missing:\n"
        f"{description}"
    )


# ============================================================
# 3. VERIFY GLOBAL TRAINING GATE
# ============================================================

TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)

AMPIR_SELFTEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampir_FINAL_adapter_selftest.json"
)

ROUTE_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_published_method_route_contract.json"
)


for path in [
    TRAINING_GATE_PATH,
    AMPIR_SELFTEST_PATH,
    ROUTE_CONTRACT_PATH,
]:
    assert path.is_file(), (
        f"Required upstream artifact missing:\n{path}"
    )


gate_before = load_json(
    TRAINING_GATE_PATH
)

ampir_selftest = load_json(
    AMPIR_SELFTEST_PATH
)

route_contract = load_json(
    ROUTE_CONTRACT_PATH
)


assert (
    ampir_selftest[
        "implementation_validated"
    ]
    is True
)


assert (
    "ampir"
    in gate_before.get(
        "validated_methods",
        [],
    )
)


assert gate_before[
    "open"
] is False


assert (
    gate_before[
        "benchmark_training_allowed"
    ]
    is False
)


assert (
    route_contract[
        "contract"
    ][
        "methods"
    ][
        "ampgram"
    ][
        "locked_route"
    ]
    ==
    "faithful_source_recipe_reimplementation"
)


# ============================================================
# 4. VERIFY EXACT OFFICIAL LOCAL COMMIT
# ============================================================

EXPECTED_COMMIT = (
    "9a76d4c90a74622ec5ad9dc8b3d908799ac7745a"
)


LOCAL_COMMIT = git_output(
    "rev-parse",
    "HEAD",
)


assert (
    LOCAL_COMMIT
    == EXPECTED_COMMIT
), (
    "AmpGram local source is not the previously audited "
    "official commit.\n"
    f"Expected: {EXPECTED_COMMIT}\n"
    f"Actual  : {LOCAL_COMMIT}"
)


# ============================================================
# 5. REQUIRED OFFICIAL SOURCE FILES
# ============================================================

SOURCE_FILES = {

    "README":
        "README.md",

    "analysis":
        "analysis.R",

    "generate_model":
        "generate_benchmark_data.R",

    "get_mers":
        "functions/get_mers.R",

    "count_ampgrams":
        "functions/count_ampgrams.R",

    "do_cv":
        "functions/do_cv.R",

    "train_peptides":
        "functions/train_model_peptides.R",

    "benchmark_functions":
        "functions/benchmark_functions.R",

    "renv_lock":
        "renv.lock",
}


SOURCE_PATHS = {
    key:
        AMPGRAM_SOURCE
        / relative_path

    for key, relative_path
    in SOURCE_FILES.items()
}


for key, path in SOURCE_PATHS.items():

    assert path.is_file(), (
        f"Missing AmpGram source file "
        f"{key}:\n{path}"
    )


# ============================================================
# 6. VERIFY EACH SOURCE FILE MATCHES GIT HEAD
#
# This detects local edits without requiring the whole
# repository to be clean.
# ============================================================

source_integrity_rows = []


for key, relative_path in (
    SOURCE_FILES.items()
):

    working_blob = git_output(
        "hash-object",
        relative_path,
    )

    committed_blob = git_output(
        "rev-parse",
        f"HEAD:{relative_path}",
    )


    exact_git_match = (
        working_blob
        == committed_blob
    )


    assert exact_git_match, (
        f"Local AmpGram source file was modified:\n"
        f"{relative_path}"
    )


    path = (
        AMPGRAM_SOURCE
        / relative_path
    )


    source_integrity_rows.append(
        {
            "source_key":
                key,

            "relative_path":
                relative_path,

            "git_blob":
                working_blob,

            "sha256":
                sha256_file(
                    path
                ),

            "exact_git_match":
                True,
        }
    )


# ============================================================
# 7. READ SOURCE
# ============================================================

README_TEXT = read_text(
    SOURCE_PATHS[
        "README"
    ]
)

ANALYSIS_TEXT = read_text(
    SOURCE_PATHS[
        "analysis"
    ]
)

GENERATE_TEXT = read_text(
    SOURCE_PATHS[
        "generate_model"
    ]
)

GET_MERS_TEXT = read_text(
    SOURCE_PATHS[
        "get_mers"
    ]
)

COUNT_TEXT = read_text(
    SOURCE_PATHS[
        "count_ampgrams"
    ]
)

DO_CV_TEXT = read_text(
    SOURCE_PATHS[
        "do_cv"
    ]
)

PEPTIDE_TEXT = read_text(
    SOURCE_PATHS[
        "train_peptides"
    ]
)

BENCHMARK_FUNCTIONS_TEXT = read_text(
    SOURCE_PATHS[
        "benchmark_functions"
    ]
)


# ============================================================
# 8. VERIFY OFFICIAL RUNTIME DOCUMENTATION
# ============================================================

assert (
    "R version 3.6.2"
    in README_TEXT
), (
    "Official README no longer reports R 3.6.2."
)


assert (
    "renv.lock"
    in README_TEXT
)


# ============================================================
# 9. VERIFY 10-MER CONSTRUCTION
# ============================================================

require_regex(
    GET_MERS_TEXT,
    r"seq2ngrams\s*\(\s*seq.*?,\s*10\s*,",
    "create_mer_df must create 10-mers",
)


assert (
    "Creates dataframe of 10-mers"
    in GET_MERS_TEXT
)


require_regex(
    GET_MERS_TEXT,
    r"cvFolds\s*\(\s*length\(ith_group\)\s*,\s*K\s*=\s*5\s*\)",
    "original analysis must use 5 folds",
)


# ============================================================
# 10. VERIFY MULTIGRAM CONFIGURATION
#
# analysis.R:
#
# 1-grams:
#   n=1, d=0
#
# 2-grams:
#   n=2 with d=0,1,2,3
#
# 3-grams:
#   d=(0,0), (0,1), (1,0), (1,1)
# ============================================================

assert (
    "ns = c(1, rep(2, 4))"
    in ANALYSIS_TEXT
)


assert (
    "ds = list(0, 0, 1, 2, 3)"
    in ANALYSIS_TEXT
)


assert (
    "ds = list(c(0, 0), c(0, 1))"
    in ANALYSIS_TEXT
)


assert (
    "ds = list(c(1, 0), c(1, 1))"
    in ANALYSIS_TEXT
)


assert (
    "binary_ngrams = cbind("
    in ANALYSIS_TEXT
)


require_regex(
    COUNT_TEXT,
    r"count_multigrams\s*\(",
    "AmpGram must use biogram multigram counting",
)


assert (
    "binarize"
    in COUNT_TEXT
)


# ============================================================
# 11. VERIFY IMPORTANT-FEATURE SELECTION
# ============================================================

require_regex(
    BENCHMARK_FUNCTIONS_TEXT,
    r"calc_imp_bigrams\s*<-\s*function"
    r"\([^)]*cutoff\s*=\s*0\.05",
    "important-feature cutoff must default to 0.05",
)


assert (
    "test_features"
    in BENCHMARK_FUNCTIONS_TEXT
)


require_regex(
    BENCHMARK_FUNCTIONS_TEXT,
    r"breaks\s*=\s*c\s*\(\s*0\s*,\s*cutoff\s*,\s*1\s*\)",
    "feature significance split must use 0 / cutoff / 1",
)


assert (
    'c("[11,19]", "(19,26]"), 0.05'
    in GENERATE_TEXT
)


# ============================================================
# 12. VERIFY FIRST-STAGE RANDOM FOREST
#
# mer-level RF:
# - ranger
# - probability = TRUE
# - 2000 trees
# - official final seed = 990
# ============================================================

require_regex(
    BENCHMARK_FUNCTIONS_TEXT,
    r"train_model_mers\s*<-\s*function",
    "train_model_mers missing",
)


require_regex(
    BENCHMARK_FUNCTIONS_TEXT,
    r"num\.trees\s*=\s*2000",
    "first-stage RF must use 2000 trees",
)


require_regex(
    BENCHMARK_FUNCTIONS_TEXT,
    r"probability\s*=\s*TRUE",
    "first-stage RF must be probabilistic",
)


require_regex(
    BENCHMARK_FUNCTIONS_TEXT,
    r"seed\s*=\s*990",
    "official first-stage RF seed must be 990",
)


# ============================================================
# 13. VERIFY 14 PEPTIDE-LEVEL STATISTICS
# ============================================================

PEPTIDE_STATISTICS = [

    "fraction_true",
    "pred_mean",
    "pred_median",
    "n_peptide",
    "n_pos",
    "pred_min",
    "pred_max",
    "longest_pos",
    "n_pos_10",
    "frac_0_0.2",
    "frac_0.2_0.4",
    "frac_0.4_0.6",
    "frac_0.6_0.8",
    "frac_0.8_1",
]


assert len(
    PEPTIDE_STATISTICS
) == 14


for statistic in (
    PEPTIDE_STATISTICS
):

    assert statistic in PEPTIDE_TEXT, (
        f"Missing AmpGram peptide statistic: "
        f"{statistic}"
    )


assert (
    "pred > 0.5"
    in PEPTIDE_TEXT
)


# ============================================================
# 14. VERIFY SECOND-STAGE RANDOM FOREST
#
# peptide-level RF:
# - ranger
# - probability = TRUE
# - 500 trees
# - official final seed = 990
# ============================================================

require_regex(
    PEPTIDE_TEXT,
    r"train_model_peptides\s*<-\s*function",
    "train_model_peptides missing",
)


require_regex(
    PEPTIDE_TEXT,
    r"num\.trees\s*=\s*500",
    "second-stage RF must use 500 trees",
)


require_regex(
    PEPTIDE_TEXT,
    r"probability\s*=\s*TRUE",
    "second-stage RF must be probabilistic",
)


require_regex(
    PEPTIDE_TEXT,
    r"seed\s*=\s*990",
    "official second-stage RF seed must be 990",
)


# ============================================================
# 15. VERIFY FINAL MODEL CONSTRUCTION
# ============================================================

assert (
    'full_model_mers <- train_model_mers'
    in GENERATE_TEXT
)


assert (
    'full_model_peptides <- train_model_peptides'
    in GENERATE_TEXT
)


assert (
    '"rf_mers" = full_model_mers'
    in GENERATE_TEXT
)


assert (
    '"rf_peptides" = full_model_peptides'
    in GENERATE_TEXT
)


assert (
    '"imp_features" = imp_bigrams'
    in GENERATE_TEXT
)


assert (
    'class(AmpGram_model) <- "ag_model"'
    in GENERATE_TEXT
)


# ============================================================
# 16. VERIFY FINAL PREDICTION SEMANTICS
# ============================================================

assert (
    '["predictions"]][, "TRUE"]'
    in GENERATE_TEXT
)


assert (
    "Probability >= 0.5"
    in GENERATE_TEXT
)


# ============================================================
# 17. ORIGINAL CV / RANDOM-SEED EVIDENCE
# ============================================================

assert (
    "make(analysis_AmpGram, seed = 990, jobs = 8)"
    in ANALYSIS_TEXT
)


require_regex(
    DO_CV_TEXT,
    r"num\.trees\s*=\s*2000",
    "CV mer RF must use 2000 trees",
)


# ============================================================
# 18. PARSE LOCAL renv.lock
# ============================================================

RENV = load_json(
    SOURCE_PATHS[
        "renv_lock"
    ]
)


R_LOCK_VERSION = (
    RENV
    .get(
        "R",
        {}
    )
    .get(
        "Version"
    )
)


RENV_PACKAGES = (
    RENV.get(
        "Packages",
        {}
    )
)


RELEVANT_PACKAGES = [
    "ranger",
    "biogram",
    "drake",
    "dplyr",
    "magrittr",
    "pbapply",
    "cvTools",
]


package_versions = {}


for package_name in (
    RELEVANT_PACKAGES
):

    package_info = (
        RENV_PACKAGES.get(
            package_name,
            {}
        )
    )


    package_versions[
        package_name
    ] = package_info.get(
        "Version"
    )


# At minimum these are algorithmically essential.
assert (
    package_versions[
        "ranger"
    ]
    is not None
)


assert (
    package_versions[
        "biogram"
    ]
    is not None
)


# ============================================================
# 19. LOCKED FAITHFUL REIMPLEMENTATION SPEC
#
# IMPORTANT SEED ADAPTATION
# -------------------------
# Original released source fixes random seed = 990.
#
# Our advisor-required benchmark requires 10 independent
# runs with seeds 100..109.
#
# Therefore ONLY the RNG seed is substituted:
#
#     990 -> current benchmark RUN_SEED
#
# Architecture, feature generation, cutoff, tree counts,
# statistics and scoring are unchanged.
#
# This adaptation is locked BEFORE benchmark results.
# ============================================================

BENCHMARK_SEEDS = list(
    range(
        100,
        110
    )
)


AMPGRAM_SPEC = {

    "schema_version":
        "1.0",

    "model_id":
        "ampgram",

    "display_name":
        "AmpGram",

    "implementation_route":
        (
            "faithful_source_recipe_"
            "modern_reimplementation"
        ),

    "official_source": {

        "repository":
            "michbur/AmpGram-analysis",

        "local_path":
            str(
                AMPGRAM_SOURCE
            ),

        "commit":
            LOCAL_COMMIT,

        "documented_R_version":
            "3.6.2",

        "renv_R_version":
            R_LOCK_VERSION,

        "package_versions":
            package_versions,
    },

    "sequence_processing": {

        "window_type":
            "overlapping",

        "window_length":
            10,

        "alphabet":
            "full_amino_acid_alphabet",
    },

    "multigram_representation": {

        "binary_features":
            True,

        "patterns": {

            "1gram": {
                "n": 1,
                "d": [0],
            },

            "2gram": {
                "n": 2,
                "d": [
                    0,
                    1,
                    2,
                    3,
                ],
            },

            "3gram": {
                "n": 3,
                "d": [
                    [0, 0],
                    [0, 1],
                    [1, 0],
                    [1, 1],
                ],
            },
        },
    },

    "important_feature_selection": {

        "method":
            "biogram_test_features",

        "cutoff":
            0.05,

        "fit_scope":
            "source_train_only",

        "target_information_used":
            False,

        "test_information_used":
            False,
    },

    "mer_level_model": {

        "family":
            "ranger_probability_random_forest",

        "num_trees":
            2000,

        "probability":
            True,

        "positive_class":
            "TRUE",
    },

    "peptide_statistics": {

        "count":
            14,

        "names":
            PEPTIDE_STATISTICS,

        "internal_mer_positive_cutoff":
            0.5,
    },

    "peptide_level_model": {

        "family":
            "ranger_probability_random_forest",

        "num_trees":
            500,

        "probability":
            True,

        "positive_class":
            "TRUE",
    },

    "final_model_structure": [
        "rf_mers",
        "rf_peptides",
        "imp_features",
    ],

    "native_probability":
        "P_TRUE_from_peptide_level_RF",

    "native_decision_threshold":
        0.5,

    "benchmark_threshold_policy":
        (
            "inherit_global_source_validation_"
            "MCC_threshold_contract"
        ),

    "seed_policy": {

        "official_source_seed":
            990,

        "benchmark_seeds":
            BENCHMARK_SEEDS,

        "adaptation":
            (
                "replace_only_fixed_RNG_seed_990_"
                "with_current_RUN_SEED"
            ),

        "reason":
            (
                "advisor_required_10_independent_"
                "runs_without_seed_tuning"
            ),

        "feature_definition_changed":
            False,

        "architecture_changed":
            False,

        "tree_counts_changed":
            False,

        "feature_cutoff_changed":
            False,
    },

    "training_scope": {

        "fit":
            "source_train_only",

        "validation":
            (
                "threshold_selection_only_under_"
                "global_benchmark_contract"
            ),

        "source_test":
            "final_evaluation_only",

        "external_target":
            "evaluation_only",

        "target_adaptation":
            False,
    },

    "benchmark_training_started":
        False,

    "adapter_self_test_status":
        "PENDING",
}


# ============================================================
# 20. SOURCE INTEGRITY TABLE
# ============================================================

import pandas as pd


source_integrity_df = pd.DataFrame(
    source_integrity_rows
)


assert len(
    source_integrity_df
) == len(
    SOURCE_FILES
)


assert (
    source_integrity_df[
        "exact_git_match"
    ]
).all()


# ============================================================
# 21. SAVE SOURCE AUDIT
# ============================================================

SOURCE_AUDIT_PATH = (
    AUDIT_DIR
    / "benchmark17_ampgram_official_source_integrity.csv"
)


source_integrity_df.to_csv(
    SOURCE_AUDIT_PATH,
    index=False,
)


# ============================================================
# 22. SAVE / LOCK AMPGRAM SPEC
# ============================================================

AMPGRAM_SPEC_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_implementation_contract.json"
)


contract_payload = {

    "created_at":
        datetime.now()
        .astimezone()
        .isoformat(),

    "status":
        (
            "AMPGRAM_SOURCE_RECIPE_LOCKED_"
            "ADAPTER_SELFTEST_PENDING"
        ),

    "contract":
        AMPGRAM_SPEC,
}


if AMPGRAM_SPEC_PATH.exists():

    existing = load_json(
        AMPGRAM_SPEC_PATH
    )


    assert (
        existing[
            "contract"
        ]
        == AMPGRAM_SPEC
    ), (
        "Existing AmpGram contract differs.\n"
        "Do NOT silently overwrite a locked "
        "published-method implementation."
    )


    LOCK_ACTION = (
        "EXISTING IDENTICAL CONTRACT VERIFIED"
    )

else:

    with open(
        AMPGRAM_SPEC_PATH,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            contract_payload,
            f,
            indent=2,
            ensure_ascii=False,
        )


    LOCK_ACTION = (
        "NEW AMPGRAM IMPLEMENTATION CONTRACT CREATED"
    )


# ============================================================
# 23. CONTRACT HASH
# ============================================================

AMPGRAM_CONTRACT_SHA256 = (
    sha256_file(
        AMPGRAM_SPEC_PATH
    )
)


# ============================================================
# 24. VERIFY TRAINING GATE UNCHANGED
# ============================================================

gate_after = load_json(
    TRAINING_GATE_PATH
)


assert (
    gate_after[
        "open"
    ]
    is False
)


assert (
    gate_after[
        "benchmark_training_allowed"
    ]
    is False
)


assert (
    "ampir"
    in gate_after.get(
        "validated_methods",
        [],
    )
)


assert (
    "ampgram"
    not in gate_after.get(
        "validated_methods",
        [],
    )
)


# ============================================================
# 25. FINAL REPORT
# ============================================================

print("=" * 128)

print(
    "CELL 19 PASS - AmpGram OFFICIAL SOURCE "
    "RECIPE VERIFIED AND LOCKED"
)

print("=" * 128)

print(
    f"Local source           : {AMPGRAM_SOURCE}"
)

print(
    f"Official commit        : {LOCAL_COMMIT}"
)

print(
    f"Source files verified  : "
    f"{len(source_integrity_df)}"
)

print(
    "Modified audited files: 0"
)

print(
    f"LOCK ACTION            : {LOCK_ACTION}"
)

print("-" * 128)

print(
    "OFFICIAL AMPGRAM PIPELINE"
)

print(
    "Window                 : overlapping 10-mer"
)

print(
    "Representation         : binary multigrams"
)

print(
    "1-gram distance        : 0"
)

print(
    "2-gram distances       : 0 / 1 / 2 / 3"
)

print(
    "3-gram distances       : "
    "(0,0) / (0,1) / (1,0) / (1,1)"
)

print(
    "Feature selection      : "
    "biogram::test_features, cutoff=0.05"
)

print(
    "Mer-level RF           : "
    "ranger probability, 2000 trees"
)

print(
    "Peptide statistics     : 14"
)

print(
    "Peptide-level RF       : "
    "ranger probability, 500 trees"
)

print(
    "Native AMP threshold   : 0.5"
)

print("-" * 128)

print(
    "SEED POLICY"
)

print(
    "Official source seed   : 990"
)

print(
    f"Benchmark seeds        : {BENCHMARK_SEEDS}"
)

print(
    "Benchmark adaptation   : "
    "ONLY RNG seed 990 -> current RUN_SEED"
)

print(
    "Architecture changed   : FALSE"
)

print(
    "Representation changed : FALSE"
)

print(
    "Tree counts changed    : FALSE"
)

print(
    "Feature cutoff changed : FALSE"
)

print("-" * 128)

print(
    "LOCAL renv.lock"
)

print(
    f"R lock version         : {R_LOCK_VERSION}"
)

for package_name in (
    RELEVANT_PACKAGES
):

    print(
        f"{package_name:<22}: "
        f"{package_versions[package_name]}"
    )


print("-" * 128)

print(
    "Benchmark training     : FALSE"
)

print(
    "Benchmark test used    : FALSE"
)

print(
    "External target used   : FALSE"
)

print(
    "AmpGram validated      : FALSE - SELF-TEST PENDING"
)

print(
    "Published validated    : 1/7 (ampir)"
)

print(
    "TRAINING GATE          : CLOSED"
)

print("-" * 128)

print(
    f"Source audit           : {SOURCE_AUDIT_PATH}"
)

print(
    f"Implementation contract: {AMPGRAM_SPEC_PATH}"
)

print(
    f"Contract SHA256        : "
    f"{AMPGRAM_CONTRACT_SHA256}"
)

print("=" * 128)

================================================================================================================================
CELL 19 PASS - AmpGram OFFICIAL SOURCE RECIPE VERIFIED AND LOCKED
================================================================================================================================
Local source           : /home/pc/genpept_sources/AmpGram-analysis
Official commit        : 9a76d4c90a74622ec5ad9dc8b3d908799ac7745a
Source files verified  : 9
Modified audited files: 0
LOCK ACTION            : NEW AMPGRAM IMPLEMENTATION CONTRACT CREATED
--------------------------------------------------------------------------------------------------------------------------------
OFFICIAL AMPGRAM PIPELINE
Window                 : overlapping 10-mer
Representation         : binary multigrams
1-gram distance        : 0
2-gram distances       : 0 / 1 / 2 / 3
3-gram distances       : (0,0) / (0,1) / (1,0) / (1,1)
Feature selection      : biogram::test_features, cutoff=0.05
Mer-level RF           : ranger probability, 2000 trees
Peptide statistics     : 14
Peptide-level RF       : ranger probability, 500 trees
Native AMP threshold   : 0.5
--------------------------------------------------------------------------------------------------------------------------------
SEED POLICY
Official source seed   : 990
Benchmark seeds        : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
Benchmark adaptation   : ONLY RNG seed 990 -> current RUN_SEED
Architecture changed   : FALSE
Representation changed : FALSE
Tree counts changed    : FALSE
Feature cutoff changed : FALSE
--------------------------------------------------------------------------------------------------------------------------------
LOCAL renv.lock
R lock version         : 3.6.2
ranger                : 0.12.1
biogram               : 1.6.3
drake                 : 7.12.0
dplyr                 : 0.8.5
magrittr              : 1.5
pbapply               : 1.4-2
cvTools               : 0.3.2
--------------------------------------------------------------------------------------------------------------------------------
Benchmark training     : FALSE
Benchmark test used    : FALSE
External target used   : FALSE
AmpGram validated      : FALSE - SELF-TEST PENDING
Published validated    : 1/7 (ampir)
TRAINING GATE          : CLOSED
--------------------------------------------------------------------------------------------------------------------------------
Source audit           : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_ampgram_official_source_integrity.csv
Implementation contract: /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampgram_FINAL_implementation_contract.json
Contract SHA256        : 64d8219a1f5875e20990709c59772dc784e09afa800a81f8074e66b64eaa41f9
================================================================================================================================

In [17]:
# ============================================================
# CELL 20 - RESTART-SAFE
# AMPGRAM EXACT BIOGRAM-1.6.3 CONTRACT AMENDMENT
# + 10-MER MULTIGRAM ENCODER SELF-TEST
#
# PURPOSE
# -------
# 1. Verify exact biogram dependency recorded by AmpGram:
#       biogram 1.6.3
#       SHA 148d3d9b323998d759b967a30f13b2b445169a5e
#
# 2. Lock previously missing details:
#       - test_features criterion = "ig"
#       - p-value adjustment = "BH"
#       - occurrence threshold = 1
#       - quick permutation test = TRUE
#       - significant cutoff = 0.05
#       - binarization = count > 0
#       - mer-RF training lengths = 11..26
#
# 3. Build deterministic 33,620-feature AmpGram multigram
#    registry.
#
# 4. Self-test the exact distance semantics on synthetic
#    10-mers.
#
# IMPORTANT
# ---------
# NO MODEL TRAINING
# NO TEST DATA
# NO VALIDATION RESULTS
# NO PACKAGE INSTALLATION
# NO TRAINING-GATE CHANGE
# ============================================================


from pathlib import Path
from datetime import datetime
from itertools import product

import hashlib
import json
import re

import pandas as pd


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

AMPGRAM_SOURCE = Path(
    "/home/pc/genpept_sources/AmpGram-analysis"
)


for path in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    AMPGRAM_SOURCE,
]:

    assert path.is_dir(), (
        f"Required directory missing:\n{path}"
    )


# ============================================================
# 2. HELPERS
# ============================================================

def load_json(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as f:

        return json.load(f)


def read_text(path):

    with open(
        path,
        "r",
        encoding="utf-8",
        errors="replace",
    ) as f:

        return f.read()


def sha256_file(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda: f.read(
                1024 * 1024
            ),
            b"",
        ):

            h.update(chunk)

    return h.hexdigest()


def normalize_ws(text):

    return re.sub(
        r"\s+",
        " ",
        text,
    ).strip()


# ============================================================
# 3. VERIFY CELL 19 CONTRACT
# ============================================================

AMPGRAM_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_implementation_contract.json"
)

TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)


assert AMPGRAM_CONTRACT_PATH.is_file()

assert TRAINING_GATE_PATH.is_file()


ampgram_contract_payload = load_json(
    AMPGRAM_CONTRACT_PATH
)

ampgram_contract = (
    ampgram_contract_payload[
        "contract"
    ]
)

gate_before = load_json(
    TRAINING_GATE_PATH
)


assert (
    ampgram_contract[
        "model_id"
    ]
    == "ampgram"
)


assert (
    ampgram_contract[
        "adapter_self_test_status"
    ]
    == "PENDING"
)


assert (
    ampgram_contract[
        "official_source"
    ][
        "commit"
    ]
    ==
    "9a76d4c90a74622ec5ad9dc8b3d908799ac7745a"
)


assert gate_before[
    "open"
] is False


assert (
    gate_before[
        "benchmark_training_allowed"
    ]
    is False
)


assert (
    "ampir"
    in gate_before.get(
        "validated_methods",
        [],
    )
)


# ============================================================
# 4. LOCAL OFFICIAL SOURCE FILES
# ============================================================

RENV_PATH = (
    AMPGRAM_SOURCE
    / "renv.lock"
)

GENERATE_MODEL_PATH = (
    AMPGRAM_SOURCE
    / "generate_benchmark_data.R"
)

BENCHMARK_FUNCTIONS_PATH = (
    AMPGRAM_SOURCE
    / "functions"
    / "benchmark_functions.R"
)

GET_MERS_PATH = (
    AMPGRAM_SOURCE
    / "functions"
    / "get_mers.R"
)

COUNT_AMPGRAMS_PATH = (
    AMPGRAM_SOURCE
    / "functions"
    / "count_ampgrams.R"
)

TRAIN_PEPTIDE_PATH = (
    AMPGRAM_SOURCE
    / "functions"
    / "train_model_peptides.R"
)


for path in [
    RENV_PATH,
    GENERATE_MODEL_PATH,
    BENCHMARK_FUNCTIONS_PATH,
    GET_MERS_PATH,
    COUNT_AMPGRAMS_PATH,
    TRAIN_PEPTIDE_PATH,
]:

    assert path.is_file(), (
        f"Required AmpGram source missing:\n{path}"
    )


# ============================================================
# 5. VERIFY EXACT BIOGRAM VERSION / SHA
# ============================================================

renv = load_json(
    RENV_PATH
)


biogram_info = (
    renv[
        "Packages"
    ][
        "biogram"
    ]
)


BIOGRAM_VERSION = (
    biogram_info[
        "Version"
    ]
)

BIOGRAM_REMOTE_REPO = (
    biogram_info[
        "RemoteRepo"
    ]
)

BIOGRAM_REMOTE_USER = (
    biogram_info[
        "RemoteUsername"
    ]
)

BIOGRAM_REMOTE_SHA = (
    biogram_info[
        "RemoteSha"
    ]
)


EXPECTED_BIOGRAM_VERSION = (
    "1.6.3"
)

EXPECTED_BIOGRAM_SHA = (
    "148d3d9b323998d759b967a30f13b2b445169a5e"
)


assert (
    BIOGRAM_VERSION
    == EXPECTED_BIOGRAM_VERSION
)


assert (
    BIOGRAM_REMOTE_REPO
    == "biogram"
)


assert (
    BIOGRAM_REMOTE_USER
    == "michbur"
)


assert (
    BIOGRAM_REMOTE_SHA
    == EXPECTED_BIOGRAM_SHA
)


# ============================================================
# 6. READ LOCAL AMPGRAM SOURCE
# ============================================================

generate_text = read_text(
    GENERATE_MODEL_PATH
)

benchmark_functions_text = read_text(
    BENCHMARK_FUNCTIONS_PATH
)

get_mers_text = read_text(
    GET_MERS_PATH
)

count_ampgrams_text = read_text(
    COUNT_AMPGRAMS_PATH
)

train_peptide_text = read_text(
    TRAIN_PEPTIDE_PATH
)


generate_norm = normalize_ws(
    generate_text
)

benchmark_norm = normalize_ws(
    benchmark_functions_text
)

get_mers_norm = normalize_ws(
    get_mers_text
)

count_norm = normalize_ws(
    count_ampgrams_text
)

train_peptide_norm = normalize_ws(
    train_peptide_text
)


# ============================================================
# 7. VERIFY EXACT AMPGRAM SOURCE DETAILS
# ============================================================

# ------------------------------------------------------------
# Overlapping 10-mers
# ------------------------------------------------------------

assert (
    "seq2ngrams(seq[i, ][!is.na(seq[i, ])], 10"
    in get_mers_norm
), (
    "AmpGram 10-mer extraction marker missing."
)


# ------------------------------------------------------------
# Binary multigrams
# ------------------------------------------------------------

assert (
    "count_multigrams("
    in count_norm
)


assert (
    "binarize"
    in count_norm
)


# ------------------------------------------------------------
# Feature selection
# ------------------------------------------------------------

assert (
    "calc_imp_bigrams <- function"
    in benchmark_norm
)


assert (
    "cutoff = 0.05"
    in benchmark_norm
)


assert (
    "test_features("
    in benchmark_norm
)


assert (
    "breaks = c(0, cutoff, 1)"
    in benchmark_norm
)


# ------------------------------------------------------------
# IMPORTANT:
# final mer model uses only the first two original
# length groups:
#
# [11,19]
# (19,26]
# ------------------------------------------------------------

assert (
    'c("[11,19]", "(19,26]"), 0.05'
    in generate_norm
), (
    "Official final AmpGram training length groups changed."
)


# ------------------------------------------------------------
# Mer RF = 2000 trees
# ------------------------------------------------------------

assert (
    "num.trees = 2000"
    in benchmark_norm
)


# ------------------------------------------------------------
# Peptide RF = 500 trees
# ------------------------------------------------------------

assert (
    "num.trees = 500"
    in train_peptide_norm
)


# ------------------------------------------------------------
# Native probability is TRUE-class probability
# ------------------------------------------------------------

assert (
    '["predictions"]][, "TRUE"]'
    in generate_norm
)


# ============================================================
# 8. EXACT BIOGRAM 1.6.3 STATISTICAL CONTRACT
#
# Verified from official biogram 1.6.3 source at:
# 148d3d9b323998d759b967a30f13b2b445169a5e
#
# test_features(
#   target,
#   features,
#   criterion = "ig",
#   adjust = "BH",
#   threshold = 1,
#   quick = TRUE,
#   times = 1e5
# )
#
# binarize(x):
#   x > 0
# ============================================================

BIOGRAM_TEST_FEATURES = {

    "criterion":
        "ig",

    "criterion_full_name":
        "information_gain_mutual_information",

    "log_base":
        "natural_log",

    "adjust":
        "BH",

    "occurrence_threshold":
        1,

    "quick":
        True,

    "times_if_nonquick":
        100000,

    "significance_cutoff":
        0.05,

    "cut_rule":
        (
            "include.lowest=TRUE,"
            "right=TRUE,"
            "first_bin_[0,0.05]"
        ),

    "binarization":
        "count_greater_than_zero",
}


# ============================================================
# 9. AMPGRAM MULTIGRAM PATTERN ORDER
#
# analysis.R:
#
# n=1:
#   d=0
#
# n=2:
#   d=0,1,2,3
#
# n=3:
#   d=(0,0),(0,1),(1,0),(1,1)
# ============================================================

MULTIGRAM_PATTERNS = [

    (
        1,
        (0,),
    ),

    (
        2,
        (0,),
    ),

    (
        2,
        (1,),
    ),

    (
        2,
        (2,),
    ),

    (
        2,
        (3,),
    ),

    (
        3,
        (0, 0),
    ),

    (
        3,
        (0, 1),
    ),

    (
        3,
        (1, 0),
    ),

    (
        3,
        (1, 1),
    ),
]


assert len(
    MULTIGRAM_PATTERNS
) == 9


# ============================================================
# 10. CANONICAL AA20
#
# Column order is implementation bookkeeping only.
# Feature identity is defined by the AmpGram/biogram
# feature NAME.
# ============================================================

AA20 = tuple(
    "ARNDCEQGHILKMFPSTWYV"
)


assert len(
    AA20
) == 20


assert len(
    set(
        AA20
    )
) == 20


# ============================================================
# 11. BIOGRAM-COMPATIBLE FEATURE NAME
#
# Official convention:
#
# NGRAM_DISTANCE
#
# examples:
#   A_0
#   A.C_0
#   A.D_1
#   A.C.E_0.1
# ============================================================

def ampgram_feature_name(
    residues,
    distances,
):

    residues_part = ".".join(
        residues
    )

    distance_part = ".".join(
        str(
            int(d)
        )
        for d in distances
    )

    return (
        f"{residues_part}_"
        f"{distance_part}"
    )


# ============================================================
# 12. BUILD COMPLETE FEATURE UNIVERSE
#
# 1gram:
#   20
#
# 2gram:
#   20^2 * 4 = 1,600
#
# 3gram:
#   20^3 * 4 = 32,000
#
# TOTAL:
#   33,620
# ============================================================

feature_rows = []

feature_index = 0


for n, distances in (
    MULTIGRAM_PATTERNS
):

    for residues in product(
        AA20,
        repeat=n,
    ):

        feature_name = (
            ampgram_feature_name(
                residues,
                distances,
            )
        )


        feature_rows.append(
            {
                "feature_index":
                    feature_index,

                "feature_name":
                    feature_name,

                "n":
                    n,

                "distance":
                    ".".join(
                        str(d)
                        for d in distances
                    ),
            }
        )


        feature_index += 1


feature_registry_df = pd.DataFrame(
    feature_rows
)


EXPECTED_FEATURE_COUNT = (
    20
    +
    (20 ** 2) * 4
    +
    (20 ** 3) * 4
)


assert (
    EXPECTED_FEATURE_COUNT
    == 33620
)


assert len(
    feature_registry_df
) == 33620


assert feature_registry_df[
    "feature_name"
].is_unique


# ============================================================
# 13. FEATURE LOOKUP
# ============================================================

FEATURE_TO_INDEX = {

    name: int(index)

    for index, name
    in zip(
        feature_registry_df[
            "feature_index"
        ],
        feature_registry_df[
            "feature_name"
        ],
    )
}


assert len(
    FEATURE_TO_INDEX
) == 33620


# ============================================================
# 14. EXACT DISTANCE SEMANTICS
#
# biogram definition:
#
# d = number of residues BETWEEN consecutive
# n-gram elements.
#
# Therefore:
#
# d=0:
#     positions 0,1
#
# d=1:
#     positions 0,2
#
# d=(0,1):
#     positions 0,1,3
#
# d=(1,0):
#     positions 0,2,3
#
# d=(1,1):
#     positions 0,2,4
# ============================================================

def offsets_from_distances(
    n,
    distances,
):

    if n == 1:

        assert tuple(
            distances
        ) == (0,)

        return (
            0,
        )


    if len(
        distances
    ) == 1:

        distances = (
            tuple(
                distances
            )
            *
            (n - 1)
        )


    assert len(
        distances
    ) == (
        n - 1
    )


    offsets = [
        0
    ]


    for gap in distances:

        assert gap >= 0

        offsets.append(
            offsets[-1]
            +
            int(gap)
            +
            1
        )


    return tuple(
        offsets
    )


# hard semantic checks

assert (
    offsets_from_distances(
        2,
        (0,),
    )
    ==
    (0, 1)
)


assert (
    offsets_from_distances(
        2,
        (1,),
    )
    ==
    (0, 2)
)


assert (
    offsets_from_distances(
        3,
        (0, 1),
    )
    ==
    (0, 1, 3)
)


assert (
    offsets_from_distances(
        3,
        (1, 0),
    )
    ==
    (0, 2, 3)
)


assert (
    offsets_from_distances(
        3,
        (1, 1),
    )
    ==
    (0, 2, 4)
)


# ============================================================
# 15. EXACT BINARY MULTIGRAM EXTRACTION FOR ONE 10-MER
#
# Equivalent logical behavior:
#
# count_multigrams(...)
#     ->
# binarize(...)
#
# i.e. a feature is 1 iff it occurs at least once.
# ============================================================

def active_ampgram_features_10mer(
    sequence,
):

    sequence = str(
        sequence
    ).upper()


    assert len(
        sequence
    ) == 10


    assert set(
        sequence
    ).issubset(
        set(
            AA20
        )
    )


    active = set()


    for n, distances in (
        MULTIGRAM_PATTERNS
    ):

        offsets = (
            offsets_from_distances(
                n,
                distances,
            )
        )


        max_offset = max(
            offsets
        )


        n_start_positions = (
            len(sequence)
            -
            max_offset
        )


        assert (
            n_start_positions
            >= 1
        )


        for start in range(
            n_start_positions
        ):

            residues = tuple(
                sequence[
                    start
                    +
                    offset
                ]
                for offset
                in offsets
            )


            feature_name = (
                ampgram_feature_name(
                    residues,
                    distances,
                )
            )


            assert (
                feature_name
                in FEATURE_TO_INDEX
            )


            # binarize(count) => present / absent only
            active.add(
                feature_name
            )


    return active


# ============================================================
# 16. SYNTHETIC SELF-TEST 1
#
# All 10 residues unique:
#
# unigram = 10
#
# bigrams:
# d0 = 9
# d1 = 8
# d2 = 7
# d3 = 6
# total = 30
#
# trigrams:
# (0,0) = 8
# (0,1) = 7
# (1,0) = 7
# (1,1) = 6
# total = 28
#
# grand total = 68
# ============================================================

TEST_SEQ_UNIQUE = (
    "ACDEFGHIKL"
)


active_unique = (
    active_ampgram_features_10mer(
        TEST_SEQ_UNIQUE
    )
)


assert len(
    active_unique
) == 68, (
    f"Expected 68 active features, "
    f"found {len(active_unique)}"
)


# explicit feature semantics

assert (
    "A_0"
    in active_unique
)


assert (
    "A.C_0"
    in active_unique
)


assert (
    "A.D_1"
    in active_unique
)


assert (
    "A.E_2"
    in active_unique
)


assert (
    "A.F_3"
    in active_unique
)


assert (
    "A.C.D_0.0"
    in active_unique
)


assert (
    "A.C.E_0.1"
    in active_unique
)


assert (
    "A.D.E_1.0"
    in active_unique
)


assert (
    "A.D.F_1.1"
    in active_unique
)


# ============================================================
# 17. SYNTHETIC SELF-TEST 2
#
# AAAAAAAAAA:
#
# Because binarize(count) = count > 0,
# repeated occurrences collapse to one active feature
# for each of the 9 pattern configurations.
# ============================================================

TEST_SEQ_REPEAT = (
    "AAAAAAAAAA"
)


active_repeat = (
    active_ampgram_features_10mer(
        TEST_SEQ_REPEAT
    )
)


assert len(
    active_repeat
) == 9, (
    f"Expected 9 binary active features, "
    f"found {len(active_repeat)}"
)


EXPECTED_REPEAT_FEATURES = {

    "A_0",

    "A.A_0",
    "A.A_1",
    "A.A_2",
    "A.A_3",

    "A.A.A_0.0",
    "A.A.A_0.1",
    "A.A.A_1.0",
    "A.A.A_1.1",
}


assert (
    active_repeat
    ==
    EXPECTED_REPEAT_FEATURES
)


# ============================================================
# 18. LENGTH POLICY FOR FAITHFUL BENCHMARK ADAPTATION
#
# Original final first-stage mer RF:
#
#   [11,19] + (19,26]
#
# => integer peptide lengths 11..26.
#
# Benchmark dataset permits length 10.
#
# Minimal predeclared adaptation:
#
# - first-stage MER RF FIT:
#       source-train lengths 11..26 only
#
# - peptide-stage RF FIT:
#       all source-train peptides length >=10
#
# - length=10 peptide:
#       one 10-mer, can be scored normally
#
# No target/test information is used.
# ============================================================

FIRST_STAGE_MIN_LENGTH = 11
FIRST_STAGE_MAX_LENGTH = 26

BENCHMARK_MIN_LENGTH = 10
BENCHMARK_MAX_LENGTH = 200


assert (
    FIRST_STAGE_MIN_LENGTH
    == 11
)


assert (
    FIRST_STAGE_MAX_LENGTH
    == 26
)


# ============================================================
# 19. SAVE 33,620 FEATURE REGISTRY
# ============================================================

FEATURE_REGISTRY_PATH = (
    AUDIT_DIR
    / "benchmark17_ampgram_33620_feature_registry.csv"
)


if FEATURE_REGISTRY_PATH.exists():

    existing_registry = pd.read_csv(
        FEATURE_REGISTRY_PATH,
        low_memory=False,
    )


    pd.testing.assert_frame_equal(
        existing_registry.reset_index(
            drop=True
        ),
        feature_registry_df.reset_index(
            drop=True
        ),
        check_dtype=False,
    )


    FEATURE_REGISTRY_ACTION = (
        "EXISTING IDENTICAL FEATURE REGISTRY VERIFIED"
    )

else:

    feature_registry_df.to_csv(
        FEATURE_REGISTRY_PATH,
        index=False,
    )


    FEATURE_REGISTRY_ACTION = (
        "NEW FEATURE REGISTRY CREATED"
    )


FEATURE_REGISTRY_SHA256 = (
    sha256_file(
        FEATURE_REGISTRY_PATH
    )
)


# ============================================================
# 20. CONTRACT AMENDMENT
#
# Do NOT overwrite Cell 19 immutable contract.
# This supplement adds the exact missing source details.
# ============================================================

AMPGRAM_AMENDMENT = {

    "schema_version":
        "1.1",

    "model_id":
        "ampgram",

    "base_contract": {

        "path":
            str(
                AMPGRAM_CONTRACT_PATH
            ),

        "sha256":
            sha256_file(
                AMPGRAM_CONTRACT_PATH
            ),
    },

    "official_ampgram_source": {

        "repository":
            "michbur/AmpGram-analysis",

        "commit":
            (
                "9a76d4c90a74622ec5ad9dc8b3d908"
                "799ac7745a"
            ),
    },

    "exact_biogram_dependency": {

        "package":
            "biogram",

        "version":
            BIOGRAM_VERSION,

        "repository":
            (
                f"{BIOGRAM_REMOTE_USER}/"
                f"{BIOGRAM_REMOTE_REPO}"
            ),

        "remote_sha":
            BIOGRAM_REMOTE_SHA,
    },

    "feature_universe": {

        "total_features":
            33620,

        "unigram_features":
            20,

        "bigram_features":
            1600,

        "trigram_features":
            32000,

        "binary":
            True,

        "binarization_rule":
            "count_greater_than_zero",

        "registry_path":
            str(
                FEATURE_REGISTRY_PATH
            ),

        "registry_sha256":
            FEATURE_REGISTRY_SHA256,
    },

    "feature_patterns": {

        "1gram":
            [
                [0]
            ],

        "2gram":
            [
                [0],
                [1],
                [2],
                [3],
            ],

        "3gram":
            [
                [0, 0],
                [0, 1],
                [1, 0],
                [1, 1],
            ],
    },

    "feature_selection": {

        "function":
            "biogram::test_features",

        "criterion":
            "ig",

        "criterion_definition":
            "mutual_information_in_nats",

        "adjust":
            "BH",

        "occurrence_threshold":
            1,

        "quick_permutation_test":
            True,

        "times_if_nonquick":
            100000,

        "significance_cutoff":
            0.05,

        "selected_bin":
            "[0,0.05]",

        "scope":
            "source_train_only",
    },

    "first_stage_mer_RF": {

        "training_length_groups":
            [
                "[11,19]",
                "(19,26]",
            ],

        "integer_training_length_min":
            11,

        "integer_training_length_max":
            26,

        "num_trees":
            2000,

        "probability":
            True,

        "positive_class":
            "TRUE",
    },

    "peptide_stage": {

        "source_train_lengths":
            "all_benchmark_eligible_lengths_10_to_200",

        "length_10_handling":
            "one_valid_10mer",

        "statistics_count":
            14,

        "mer_internal_threshold":
            0.5,

        "num_trees":
            500,

        "probability":
            True,

        "positive_class":
            "TRUE",
    },

    "benchmark_adaptation": {

        "source_train_only":
            True,

        "target_test_information":
            False,

        "source_test_information":
            False,

        "validation_feature_selection":
            False,

        "original_fixed_seed":
            990,

        "benchmark_seed_schedule":
            list(
                range(
                    100,
                    110
                )
            ),

        "only_RNG_seed_changes":
            True,

        "architecture_change":
            False,

        "feature_definition_change":
            False,

        "feature_selection_rule_change":
            False,

        "tree_count_change":
            False,
    },

    "encoder_selftest": {

        "unique_10mer":
            TEST_SEQ_UNIQUE,

        "unique_10mer_active_features":
            len(
                active_unique
            ),

        "expected_unique_active_features":
            68,

        "repeat_10mer":
            TEST_SEQ_REPEAT,

        "repeat_10mer_active_features":
            len(
                active_repeat
            ),

        "expected_repeat_active_features":
            9,

        "status":
            "PASS",
    },

    "benchmark_training_started":
        False,

    "full_adapter_selftest":
        "PENDING",
}


# ============================================================
# 21. SAVE AMENDMENT IDEMPOTENTLY
# ============================================================

AMENDMENT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_source_recipe_amendment_v1.1.json"
)


if AMENDMENT_PATH.exists():

    existing = load_json(
        AMENDMENT_PATH
    )


    assert (
        existing[
            "contract_amendment"
        ]
        ==
        AMPGRAM_AMENDMENT
    ), (
        "Existing AmpGram v1.1 amendment differs.\n"
        "Do NOT silently overwrite."
    )


    AMENDMENT_ACTION = (
        "EXISTING IDENTICAL AMENDMENT VERIFIED"
    )

else:

    amendment_payload = {

        "created_at":
            datetime.now()
            .astimezone()
            .isoformat(),

        "status":
            (
                "AMPGRAM_EXACT_BIOGRAM_RECIPE_"
                "LOCKED_BEFORE_TRAINING"
            ),

        "contract_amendment":
            AMPGRAM_AMENDMENT,
    }


    with open(
        AMENDMENT_PATH,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            amendment_payload,
            f,
            indent=2,
            ensure_ascii=False,
        )


    AMENDMENT_ACTION = (
        "NEW AMPGRAM v1.1 AMENDMENT CREATED"
    )


# ============================================================
# 22. RE-READ FROM DISK
# ============================================================

amendment_check = load_json(
    AMENDMENT_PATH
)


assert (
    amendment_check[
        "status"
    ]
    ==
    "AMPGRAM_EXACT_BIOGRAM_RECIPE_LOCKED_BEFORE_TRAINING"
)


assert (
    amendment_check[
        "contract_amendment"
    ][
        "exact_biogram_dependency"
    ][
        "version"
    ]
    == "1.6.3"
)


assert (
    amendment_check[
        "contract_amendment"
    ][
        "exact_biogram_dependency"
    ][
        "remote_sha"
    ]
    ==
    EXPECTED_BIOGRAM_SHA
)


assert (
    amendment_check[
        "contract_amendment"
    ][
        "feature_universe"
    ][
        "total_features"
    ]
    == 33620
)


assert (
    amendment_check[
        "contract_amendment"
    ][
        "encoder_selftest"
    ][
        "status"
    ]
    == "PASS"
)


# ============================================================
# 23. VERIFY TRAINING GATE UNCHANGED
# ============================================================

gate_after = load_json(
    TRAINING_GATE_PATH
)


assert gate_after[
    "open"
] is False


assert (
    gate_after[
        "benchmark_training_allowed"
    ]
    is False
)


assert (
    "ampir"
    in gate_after.get(
        "validated_methods",
        [],
    )
)


assert (
    "ampgram"
    not in gate_after.get(
        "validated_methods",
        [],
    )
)


# ============================================================
# 24. FINAL REPORT
# ============================================================

print("=" * 128)

print(
    "CELL 20 PASS - AMPGRAM EXACT BIOGRAM-1.6.3 "
    "RECIPE AND MULTIGRAM ENCODER LOCKED"
)

print("=" * 128)

print(
    "AmpGram commit         : "
    "9a76d4c90a74622ec5ad9dc8b3d908799ac7745a"
)

print(
    f"biogram version        : {BIOGRAM_VERSION}"
)

print(
    f"biogram exact SHA      : {BIOGRAM_REMOTE_SHA}"
)

print(
    f"AMENDMENT ACTION       : {AMENDMENT_ACTION}"
)

print(
    f"FEATURE REGISTRY       : {FEATURE_REGISTRY_ACTION}"
)

print("-" * 128)

print(
    "EXACT FEATURE-SELECTION CONTRACT"
)

print(
    "Criterion              : Information Gain"
)

print(
    "p-value adjustment     : BH"
)

print(
    "Occurrence threshold   : 1"
)

print(
    "QuiPT                  : TRUE"
)

print(
    "Significance cutoff    : 0.05"
)

print(
    "Binarization           : count > 0"
)

print("-" * 128)

print(
    "MULTIGRAM FEATURE UNIVERSE"
)

print(
    "1-gram                 : 20"
)

print(
    "2-gram                 : 1,600"
)

print(
    "3-gram                 : 32,000"
)

print(
    "TOTAL                  : 33,620"
)

print(
    f"Registry SHA256        : "
    f"{FEATURE_REGISTRY_SHA256}"
)

print("-" * 128)

print(
    "10-MER ENCODER SELF-TEST"
)

print(
    f"{TEST_SEQ_UNIQUE}     : "
    f"{len(active_unique)} active features "
    "(expected 68) - PASS"
)

print(
    f"{TEST_SEQ_REPEAT}     : "
    f"{len(active_repeat)} active features "
    "(expected 9) - PASS"
)

print("-" * 128)

print(
    "FIRST-STAGE MER RF"
)

print(
    "Training lengths       : 11..26"
)

print(
    "Official groups        : [11,19] + (19,26]"
)

print(
    "Trees                  : 2000"
)

print(
    "Feature selection      : SOURCE TRAIN ONLY"
)

print("-" * 128)

print(
    "SECOND-STAGE PEPTIDE RF"
)

print(
    "Training lengths       : benchmark-eligible 10..200"
)

print(
    "Length 10              : one valid 10-mer"
)

print(
    "Statistics             : 14"
)

print(
    "Trees                  : 500"
)

print("-" * 128)

print(
    "Benchmark training     : FALSE"
)

print(
    "Benchmark test used    : FALSE"
)

print(
    "External target used   : FALSE"
)

print(
    "AmpGram validated      : FALSE - FULL ADAPTER SELF-TEST PENDING"
)

print(
    "Published validated    : 1/7 (ampir)"
)

print(
    "TRAINING GATE          : CLOSED"
)

print("-" * 128)

print(
    f"Feature registry       : {FEATURE_REGISTRY_PATH}"
)

print(
    f"Contract amendment     : {AMENDMENT_PATH}"
)

print("=" * 128)

================================================================================================================================
CELL 20 PASS - AMPGRAM EXACT BIOGRAM-1.6.3 RECIPE AND MULTIGRAM ENCODER LOCKED
================================================================================================================================
AmpGram commit         : 9a76d4c90a74622ec5ad9dc8b3d908799ac7745a
biogram version        : 1.6.3
biogram exact SHA      : 148d3d9b323998d759b967a30f13b2b445169a5e
AMENDMENT ACTION       : NEW AMPGRAM v1.1 AMENDMENT CREATED
FEATURE REGISTRY       : NEW FEATURE REGISTRY CREATED
--------------------------------------------------------------------------------------------------------------------------------
EXACT FEATURE-SELECTION CONTRACT
Criterion              : Information Gain
p-value adjustment     : BH
Occurrence threshold   : 1
QuiPT                  : TRUE
Significance cutoff    : 0.05
Binarization           : count > 0
--------------------------------------------------------------------------------------------------------------------------------
MULTIGRAM FEATURE UNIVERSE
1-gram                 : 20
2-gram                 : 1,600
3-gram                 : 32,000
TOTAL                  : 33,620
Registry SHA256        : f7f1b33697d926c233ef3f9d3d5228d13dbf8139d8e48dc2cd4b2a92550ed6d8
--------------------------------------------------------------------------------------------------------------------------------
10-MER ENCODER SELF-TEST
ACDEFGHIKL     : 68 active features (expected 68) - PASS
AAAAAAAAAA     : 9 active features (expected 9) - PASS
--------------------------------------------------------------------------------------------------------------------------------
FIRST-STAGE MER RF
Training lengths       : 11..26
Official groups        : [11,19] + (19,26]
Trees                  : 2000
Feature selection      : SOURCE TRAIN ONLY
--------------------------------------------------------------------------------------------------------------------------------
SECOND-STAGE PEPTIDE RF
Training lengths       : benchmark-eligible 10..200
Length 10              : one valid 10-mer
Statistics             : 14
Trees                  : 500
--------------------------------------------------------------------------------------------------------------------------------
Benchmark training     : FALSE
Benchmark test used    : FALSE
External target used   : FALSE
AmpGram validated      : FALSE - FULL ADAPTER SELF-TEST PENDING
Published validated    : 1/7 (ampir)
TRAINING GATE          : CLOSED
--------------------------------------------------------------------------------------------------------------------------------
Feature registry       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_ampgram_33620_feature_registry.csv
Contract amendment     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampgram_FINAL_source_recipe_amendment_v1.1.json
================================================================================================================================

In [1]:
# ============================================================
# CELL 21 - RESTART-SAFE
# AMPGRAM MODERN-REIMPLEMENTATION HOST PREFLIGHT
# + ROUTE CONSISTENCY + UPSTREAM INTEGRITY LOCK
#
# PURPOSE
# -------
# Correct Cell 21 after verifying that the AmpGram legacy
# environment is AUXILIARY and is explicitly NOT required by
# the locked route from Cell 16.
#
# This cell verifies:
#   1) Cell 16 route is modern faithful reimplementation.
#   2) Cell 19 source/recipe contract remains unchanged.
#   3) Cell 20 biogram recipe and 33,620-feature registry remain
#      unchanged.
#   4) Official AmpGram source still matches the pinned commit.
#   5) Modern host dependencies are available and recorded.
#
# IMPORTANT
# ---------
# NO PACKAGE INSTALLATION
# NO FEATURE-SELECTION FIT
# NO RF1 / RF2 FIT
# NO BENCHMARK TRAINING
# NO TEST / EXTERNAL TARGET
# NO TRAINING-GATE UPDATE
# DOES NOT CLAIM AMPGRAM IS VALIDATED
# ============================================================

from pathlib import Path
from datetime import datetime
import hashlib
import importlib.metadata as importlib_metadata
import importlib.util
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile

import pandas as pd


# ============================================================
# 1. RESTART-SAFE PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

WORK_ROOT = Path(
    "/home/pc/genpept_benchmark17_work"
)

AMPGRAM_SOURCE = Path(
    "/home/pc/genpept_sources/AmpGram-analysis"
)


for path in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    WORK_ROOT,
    AMPGRAM_SOURCE,
]:

    assert path.is_dir(), (
        f"Required directory missing:\n{path}"
    )


# ============================================================
# 2. HELPERS
# ============================================================

def load_json(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as f:

        return json.load(f)


def sha256_file(
    path,
    chunk_size=1024 * 1024,
):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        while True:

            chunk = f.read(
                chunk_size
            )

            if not chunk:
                break

            h.update(
                chunk
            )

    return h.hexdigest()


def run_cmd(
    command,
    cwd=None,
):

    result = subprocess.run(
        [
            str(x)
            for x
            in command
        ],
        cwd=(
            None
            if cwd is None
            else str(cwd)
        ),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )

    if result.returncode != 0:

        print(
            "=" * 120
        )

        print(
            "SUBPROCESS FAILURE"
        )

        print(
            "COMMAND     :",
            [
                str(x)
                for x
                in command
            ],
        )

        print(
            "RETURN CODE :",
            result.returncode,
        )

        print(
            "--- STDOUT ---"
        )

        print(
            result.stdout
            or "<EMPTY>"
        )

        print(
            "--- STDERR ---"
        )

        print(
            result.stderr
            or "<EMPTY>"
        )

        print(
            "=" * 120
        )

    return result


def atomic_lock_json(
    path,
    status,
    contract,
):

    # Existing locked artifact:
    # verify/reuse, never overwrite silently.
    if path.exists():

        old = load_json(
            path
        )

        assert (
            old.get(
                "status"
            )
            == status
        ), (
            "Existing Cell 21 artifact "
            "has a different status:\n"
            f"{path}"
        )

        assert (
            old.get(
                "contract"
            )
            == contract
        ), (
            "Existing locked Cell 21 contract differs.\n"
            "Refusing silent overwrite:\n"
            f"{path}"
        )

        return (
            "EXISTING IDENTICAL CONTRACT VERIFIED"
        )

    payload = {

        "created_at":
            datetime.now()
            .astimezone()
            .isoformat(),

        "status":
            status,

        "contract":
            contract,
    }

    text = (
        json.dumps(
            payload,
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fd, tmp_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=str(
            path.parent
        ),
    )

    tmp_path = Path(
        tmp_name
    )

    try:

        with os.fdopen(
            fd,
            "w",
            encoding="utf-8",
            newline="\n",
        ) as f:

            f.write(
                text
            )

            f.flush()

            os.fsync(
                f.fileno()
            )

        os.replace(
            tmp_path,
            path,
        )

    finally:

        if tmp_path.exists():

            tmp_path.unlink()

    check = load_json(
        path
    )

    assert (
        check.get(
            "status"
        )
        == status
    )

    assert (
        check.get(
            "contract"
        )
        == contract
    )

    return (
        "NEW CONTRACT ATOMICALLY COMMITTED"
    )


# ============================================================
# 3. REQUIRED UPSTREAM ARTIFACTS
# ============================================================

ROUTE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_published_method_route_contract.json"
)

LOCAL_ENV_AUDIT_PATH = (
    MANIFEST_DIR
    / "benchmark17_published_method_local_environment_latest.json"
)

AMPGRAM_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_implementation_contract.json"
)

AMPGRAM_AMENDMENT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_source_recipe_amendment_v1.1.json"
)

SOURCE_AUDIT_PATH = (
    AUDIT_DIR
    / "benchmark17_ampgram_official_source_integrity.csv"
)

FEATURE_REGISTRY_PATH = (
    AUDIT_DIR
    / "benchmark17_ampgram_33620_feature_registry.csv"
)

TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)

RENV_PATH = (
    AMPGRAM_SOURCE
    / "renv.lock"
)


for path in [

    ROUTE_PATH,
    LOCAL_ENV_AUDIT_PATH,
    AMPGRAM_CONTRACT_PATH,
    AMPGRAM_AMENDMENT_PATH,
    SOURCE_AUDIT_PATH,
    FEATURE_REGISTRY_PATH,
    TRAINING_GATE_PATH,
    RENV_PATH,

]:

    assert path.is_file(), (
        "Required upstream artifact missing:\n"
        f"{path}"
    )


# ============================================================
# 4. LOAD LOCKED STATE
# ============================================================

route_payload = load_json(
    ROUTE_PATH
)

local_env_audit = load_json(
    LOCAL_ENV_AUDIT_PATH
)

ampgram_payload = load_json(
    AMPGRAM_CONTRACT_PATH
)

amendment_payload = load_json(
    AMPGRAM_AMENDMENT_PATH
)

gate_before = load_json(
    TRAINING_GATE_PATH
)

renv = load_json(
    RENV_PATH
)


route_core = (
    route_payload[
        "contract"
    ]
)

route_ampgram = (
    route_core[
        "methods"
    ][
        "ampgram"
    ]
)

ampgram_contract = (
    ampgram_payload[
        "contract"
    ]
)

amendment = (
    amendment_payload[
        "contract_amendment"
    ]
)


EXPECTED_COMMIT = (
    "9a76d4c90a74622ec5ad9dc8b3d908799ac7745a"
)

EXPECTED_BIOGRAM_SHA = (
    "148d3d9b323998d759b967a30f13b2b445169a5e"
)

EXPECTED_SEEDS = list(
    range(
        100,
        110,
    )
)

EXPECTED_PUBLISHED_IDS = [

    "ampep",
    "ampscannerv2",
    "ampgram",
    "ampir",
    "ampeppy",
    "ai4amp",
    "amplify",

]


# ============================================================
# 5. VERIFY CELL 16 ROUTE
#
# THIS IS THE CRITICAL CORRECTION.
#
# Cell 16 explicitly locked:
#
#   implementation_environment = modern_reimplementation
#   legacy_dependency_repair_required = False
#
# Therefore genpept_ampgram_legacy is NOT a mandatory runtime.
# ============================================================

assert (
    route_core[
        "model_seeds"
    ]
    == EXPECTED_SEEDS
)


assert (
    route_core[
        "published_model_ids"
    ]
    == EXPECTED_PUBLISHED_IDS
)


assert (
    route_ampgram[
        "locked_route"
    ]
    ==
    "faithful_source_recipe_reimplementation"
)


assert (
    route_ampgram[
        "implementation_environment"
    ]
    ==
    "modern_reimplementation"
)


assert (
    route_ampgram[
        "legacy_dependency_repair_required"
    ]
    is False
)


assert (
    local_env_audit[
        "ampgram"
    ][
        "legacy_environment_required"
    ]
    is False
)


assert (
    local_env_audit[
        "ampgram"
    ][
        "locked_route"
    ]
    ==
    "modern_faithful_source_recipe_reimplementation"
)


LEGACY_ENV_NAME = (
    local_env_audit[
        "ampgram"
    ][
        "legacy_environment"
    ]
)


LEGACY_ENV_PRESENT = bool(
    local_env_audit[
        "ampgram"
    ][
        "legacy_environment_present"
    ]
)


# ============================================================
# 6. VERIFY CELL 19 IMPLEMENTATION CONTRACT
# ============================================================

assert (
    ampgram_contract[
        "model_id"
    ]
    == "ampgram"
)


assert (
    ampgram_contract[
        "implementation_route"
    ]
    ==
    "faithful_source_recipe_modern_reimplementation"
)


assert (
    ampgram_contract[
        "official_source"
    ][
        "commit"
    ]
    == EXPECTED_COMMIT
)


assert (
    ampgram_contract[
        "official_source"
    ][
        "documented_R_version"
    ]
    == "3.6.2"
)


assert (
    ampgram_contract[
        "seed_policy"
    ][
        "benchmark_seeds"
    ]
    == EXPECTED_SEEDS
)


assert (
    ampgram_contract[
        "seed_policy"
    ][
        "official_source_seed"
    ]
    == 990
)


assert (
    ampgram_contract[
        "adapter_self_test_status"
    ]
    == "PENDING"
)


assert (
    ampgram_contract[
        "benchmark_training_started"
    ]
    is False
)


# ============================================================
# 7. VERIFY CELL 20 CONTRACT AMENDMENT
# ============================================================

assert (
    amendment_payload[
        "status"
    ]
    ==
    "AMPGRAM_EXACT_BIOGRAM_RECIPE_LOCKED_BEFORE_TRAINING"
)


assert (
    amendment[
        "base_contract"
    ][
        "sha256"
    ]
    ==
    sha256_file(
        AMPGRAM_CONTRACT_PATH
    )
)


assert (
    amendment[
        "exact_biogram_dependency"
    ][
        "version"
    ]
    == "1.6.3"
)


assert (
    amendment[
        "exact_biogram_dependency"
    ][
        "remote_sha"
    ]
    ==
    EXPECTED_BIOGRAM_SHA
)


assert (
    amendment[
        "feature_universe"
    ][
        "total_features"
    ]
    == 33620
)


assert (
    amendment[
        "encoder_selftest"
    ][
        "status"
    ]
    == "PASS"
)


assert (
    amendment[
        "full_adapter_selftest"
    ]
    == "PENDING"
)


assert (
    amendment[
        "benchmark_training_started"
    ]
    is False
)


# ============================================================
# 8. VERIFY OFFICIAL REFERENCE RUNTIME FROM renv.lock
#
# IMPORTANT:
# These are the AUTHOR'S REFERENCE DEPENDENCIES.
#
# They are NOT interpreted as:
# "these packages must already be installed inside
#  genpept_ampgram_legacy".
# ============================================================

assert (
    renv[
        "R"
    ][
        "Version"
    ]
    == "3.6.2"
)


renv_packages = (
    renv[
        "Packages"
    ]
)


assert (
    renv_packages[
        "biogram"
    ][
        "Version"
    ]
    == "1.6.3"
)


assert (
    renv_packages[
        "biogram"
    ][
        "RemoteSha"
    ]
    ==
    EXPECTED_BIOGRAM_SHA
)


assert (
    renv_packages[
        "ranger"
    ][
        "Version"
    ]
    == "0.12.1"
)


REFERENCE_R = {

    "R":
        renv[
            "R"
        ][
            "Version"
        ],

    "biogram":
        renv_packages[
            "biogram"
        ][
            "Version"
        ],

    "biogram_remote_sha":
        renv_packages[
            "biogram"
        ][
            "RemoteSha"
        ],

    "ranger":
        renv_packages[
            "ranger"
        ][
            "Version"
        ],
}


# ============================================================
# 9. VERIFY OFFICIAL LOCAL SOURCE
# ============================================================

GIT = shutil.which(
    "git"
)

assert (
    GIT is not None
), (
    "git executable not found"
)


head = run_cmd(
    [
        GIT,
        "rev-parse",
        "HEAD",
    ],
    cwd=AMPGRAM_SOURCE,
)


assert (
    head.returncode
    == 0
)


LOCAL_COMMIT = (
    head.stdout.strip()
)


assert (
    LOCAL_COMMIT
    == EXPECTED_COMMIT
), (
    "AmpGram source commit changed.\n"
    f"Expected: {EXPECTED_COMMIT}\n"
    f"Actual  : {LOCAL_COMMIT}"
)


# ============================================================
# 10. VERIFY EACH CELL-19 AUDITED SOURCE FILE
# ============================================================

source_audit = pd.read_csv(
    SOURCE_AUDIT_PATH,
    low_memory=False,
)


required_source_cols = {

    "source_key",
    "relative_path",
    "git_blob",
    "sha256",
    "exact_git_match",

}


assert (
    required_source_cols
    .issubset(
        source_audit.columns
    )
)


assert (
    len(
        source_audit
    )
    > 0
)


assert (
    source_audit[
        "relative_path"
    ]
    .is_unique
)


assert (
    source_audit[
        "exact_git_match"
    ]
    .astype(str)
    .str.lower()
    .eq("true")
    .all()
)


for row in (
    source_audit
    .itertuples(
        index=False
    )
):

    relative_path = str(
        row.relative_path
    )

    source_path = (
        AMPGRAM_SOURCE
        / relative_path
    )

    assert (
        source_path.is_file()
    ), (
        "Audited source file missing:\n"
        f"{source_path}"
    )


    working_blob = run_cmd(
        [
            GIT,
            "hash-object",
            relative_path,
        ],
        cwd=AMPGRAM_SOURCE,
    )


    committed_blob = run_cmd(
        [
            GIT,
            "rev-parse",
            f"HEAD:{relative_path}",
        ],
        cwd=AMPGRAM_SOURCE,
    )


    assert (
        working_blob.returncode
        == 0
    )


    assert (
        committed_blob.returncode
        == 0
    )


    working_blob_sha = (
        working_blob.stdout.strip()
    )

    committed_blob_sha = (
        committed_blob.stdout.strip()
    )


    assert (
        working_blob_sha
        == committed_blob_sha
    ), (
        "Local audited source modified:\n"
        f"{relative_path}"
    )


    assert (
        working_blob_sha
        == str(
            row.git_blob
        )
    ), (
        "Cell 19 git blob no longer matches:\n"
        f"{relative_path}"
    )


    assert (
        sha256_file(
            source_path
        )
        ==
        str(
            row.sha256
        )
    ), (
        "Cell 19 SHA256 no longer matches:\n"
        f"{relative_path}"
    )


# ============================================================
# 11. VERIFY CELL 20 FEATURE REGISTRY
# + RECOMPUTE COUNTS INDEPENDENTLY
# ============================================================

feature_registry = pd.read_csv(
    FEATURE_REGISTRY_PATH,
    low_memory=False,
)


required_feature_cols = {

    "feature_index",
    "feature_name",
    "n",

}


assert (
    required_feature_cols
    .issubset(
        feature_registry.columns
    )
)


# ------------------------------------------------------------
# Mathematical derivation:
#
# 1-gram:
#   20
#
# 2-gram:
#   4 distance patterns * 20^2
#
# 3-gram:
#   4 distance patterns * 20^3
#
# Total:
#   20 + 1600 + 32000 = 33620
# ------------------------------------------------------------

EXPECTED_FEATURE_COUNT = (
    20
    +
    4 * (20 ** 2)
    +
    4 * (20 ** 3)
)


# ------------------------------------------------------------
# For ACDEFGHIKL:
#
# unigram:
#   10
#
# bigram active:
#   9 + 8 + 7 + 6 = 30
#
# trigram active:
#   8 + 7 + 7 + 6 = 28
#
# Total:
#   10 + 30 + 28 = 68
# ------------------------------------------------------------

EXPECTED_UNIQUE_ACTIVE = (
    10
    +
    (
        9
        +
        8
        +
        7
        +
        6
    )
    +
    (
        8
        +
        7
        +
        7
        +
        6
    )
)


# ------------------------------------------------------------
# For AAAAAAAAAA:
# exactly one active feature per one of the 9 pattern families.
# ------------------------------------------------------------

EXPECTED_REPEAT_ACTIVE = (
    9
)


assert (
    EXPECTED_FEATURE_COUNT
    == 33620
)


assert (
    EXPECTED_UNIQUE_ACTIVE
    == 68
)


assert (
    EXPECTED_REPEAT_ACTIVE
    == 9
)


assert (
    len(
        feature_registry
    )
    == EXPECTED_FEATURE_COUNT
)


assert (
    feature_registry[
        "feature_name"
    ]
    .is_unique
)


assert (
    feature_registry[
        "feature_index"
    ]
    .is_unique
)


feature_indices = (
    feature_registry[
        "feature_index"
    ]
    .astype(int)
    .tolist()
)


assert (
    feature_indices
    ==
    list(
        range(
            EXPECTED_FEATURE_COUNT
        )
    )
), (
    "Feature registry index is not exactly 0..33619"
)


n_counts = {

    int(k):
        int(v)

    for k, v
    in (
        feature_registry[
            "n"
        ]
        .value_counts()
        .to_dict()
        .items()
    )
}


assert (
    n_counts
    ==
    {
        1: 20,
        2: 1600,
        3: 32000,
    }
)


# ============================================================
# 12. MODERN HOST PREFLIGHT
#
# This records the modern Python host available to the faithful
# reimplementation.
#
# It DOES NOT claim that sklearn RF == ranger RF.
#
# RF-backend fidelity/equivalence remains PENDING and must be
# validated before full AmpGram adapter can become VALIDATED.
# ============================================================

HOST_DISTRIBUTIONS = {

    "numpy":
        "numpy",

    "pandas":
        "pandas",

    "scipy":
        "scipy",

    "scikit-learn":
        "sklearn",

    "joblib":
        "joblib",

}


host_packages = {}

missing_host_modules = []


for distribution, module_name in (
    HOST_DISTRIBUTIONS.items()
):

    available = (
        importlib.util.find_spec(
            module_name
        )
        is not None
    )

    if not available:

        missing_host_modules.append(
            module_name
        )

        continue


    host_packages[
        distribution
    ] = {

        "module":
            module_name,

        "version":
            importlib_metadata.version(
                distribution
            ),
    }


if missing_host_modules:

    print(
        "=" * 120
    )

    print(
        "MODERN HOST PREFLIGHT FAILURE"
    )

    print(
        "Missing modules:",
        missing_host_modules,
    )

    print(
        "Cell 21 installed/modified nothing."
    )

    print(
        "=" * 120
    )


assert (
    not missing_host_modules
), (
    "Modern host is incomplete; "
    "see diagnostic above."
)


# ============================================================
# 13. TRAINING GATE - READ ONLY
# ============================================================

GATE_SHA_BEFORE = (
    sha256_file(
        TRAINING_GATE_PATH
    )
)


assert (
    gate_before[
        "gate"
    ]
    ==
    "PUBLISHED_METHOD_IMPLEMENTATION_GATE"
)


assert (
    gate_before[
        "open"
    ]
    is False
)


assert (
    gate_before[
        "benchmark_training_allowed"
    ]
    is False
)


validated_before = sorted(
    gate_before.get(
        "validated_methods",
        [],
    )
)


assert (
    "ampir"
    in validated_before
)


assert (
    "ampgram"
    not in validated_before
)


# ============================================================
# 14. BUILD IMMUTABLE CELL-21 PREFLIGHT CONTRACT
# ============================================================

CELL21_CONTRACT = {

    "schema_version":
        "1.0",

    "model_id":
        "ampgram",

    "stage":
        "modern_reimplementation_host_preflight",

    "route": {

        "cell16_locked_route":
            route_ampgram[
                "locked_route"
            ],

        "cell16_implementation_environment":
            route_ampgram[
                "implementation_environment"
            ],

        "cell16_legacy_dependency_repair_required":
            route_ampgram[
                "legacy_dependency_repair_required"
            ],

        "cell19_implementation_route":
            ampgram_contract[
                "implementation_route"
            ],

        "legacy_environment_name":
            LEGACY_ENV_NAME,

        "legacy_environment_present":
            LEGACY_ENV_PRESENT,

        "legacy_environment_required":
            False,
    },

    "official_source": {

        "repository":
            "michbur/AmpGram-analysis",

        "commit":
            LOCAL_COMMIT,

        "source_audit_path":
            str(
                SOURCE_AUDIT_PATH
            ),

        "source_audit_sha256":
            sha256_file(
                SOURCE_AUDIT_PATH
            ),

        "audited_file_count":
            int(
                len(
                    source_audit
                )
            ),
    },

    "official_reference_runtime":
        REFERENCE_R,

    "upstream_locks": {

        "route_contract_sha256":
            sha256_file(
                ROUTE_PATH
            ),

        "ampgram_contract_sha256":
            sha256_file(
                AMPGRAM_CONTRACT_PATH
            ),

        "ampgram_amendment_sha256":
            sha256_file(
                AMPGRAM_AMENDMENT_PATH
            ),

        "feature_registry_sha256":
            sha256_file(
                FEATURE_REGISTRY_PATH
            ),
    },

    "feature_registry": {

        "total_features":
            EXPECTED_FEATURE_COUNT,

        "unigram_features":
            n_counts[
                1
            ],

        "bigram_features":
            n_counts[
                2
            ],

        "trigram_features":
            n_counts[
                3
            ],

        "feature_names_unique":
            True,

        "feature_indices_exact_0_to_33619":
            True,

        "independent_expected_unique_10mer_active":
            EXPECTED_UNIQUE_ACTIVE,

        "independent_expected_repeat_10mer_active":
            EXPECTED_REPEAT_ACTIVE,
    },

    "modern_host": {

        "python_executable":
            sys.executable,

        "python_version":
            platform.python_version(),

        "platform":
            platform.platform(),

        "packages":
            host_packages,
    },

    "scientific_boundary": {

        "package_installation_performed":
            False,

        "feature_selection_fit":
            False,

        "rf1_fit":
            False,

        "rf2_fit":
            False,

        "benchmark_training_performed":
            False,

        "benchmark_test_used":
            False,

        "external_target_used":
            False,

        "training_gate_modified":
            False,

        "rf_backend_equivalence_claimed":
            False,

        "ampgram_implementation_validated":
            False,
    },

    "seed_policy": {

        "official_source_seed":
            990,

        "benchmark_seeds":
            EXPECTED_SEEDS,

        "seed_tuning":
            False,
    },
}


CELL21_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_modern_host_preflight.json"
)


CELL21_ACTION = atomic_lock_json(

    CELL21_PATH,

    "AMPGRAM_MODERN_REIMPLEMENTATION_HOST_PREFLIGHT_PASS",

    CELL21_CONTRACT,

)


# ============================================================
# 15. RE-READ COMMITTED ARTIFACT
# ============================================================

cell21_check = load_json(
    CELL21_PATH
)


assert (
    cell21_check[
        "status"
    ]
    ==
    "AMPGRAM_MODERN_REIMPLEMENTATION_HOST_PREFLIGHT_PASS"
)


assert (
    cell21_check[
        "contract"
    ]
    ==
    CELL21_CONTRACT
)


# ============================================================
# 16. VERIFY TRAINING GATE REMAINS BYTE-IDENTICAL
# ============================================================

assert (
    sha256_file(
        TRAINING_GATE_PATH
    )
    ==
    GATE_SHA_BEFORE
), (
    "Cell 21 modified the global training gate - forbidden."
)


# ============================================================
# 17. FINAL PASS REPORT
# ============================================================

print(
    "=" * 128
)

print(
    "CELL 21 PASS - AMPGRAM MODERN-REIMPLEMENTATION "
    "HOST PREFLIGHT + ROUTE CONSISTENCY VERIFIED"
)

print(
    "=" * 128
)


print(
    "AmpGram source commit  :",
    LOCAL_COMMIT,
)

print(
    "Cell 16 route          :",
    route_ampgram[
        "locked_route"
    ],
)

print(
    "Implementation env     :",
    route_ampgram[
        "implementation_environment"
    ],
)

print(
    "Legacy env             :",
    LEGACY_ENV_NAME,
)

print(
    "Legacy env present     :",
    LEGACY_ENV_PRESENT,
)

print(
    "Legacy env required    : FALSE"
)


print(
    "-" * 128
)

print(
    "OFFICIAL REFERENCE RUNTIME - PINNED renv.lock"
)

print(
    "R                      :",
    REFERENCE_R[
        "R"
    ],
)

print(
    "biogram                :",
    REFERENCE_R[
        "biogram"
    ],
)

print(
    "biogram RemoteSha      :",
    REFERENCE_R[
        "biogram_remote_sha"
    ],
)

print(
    "ranger                 :",
    REFERENCE_R[
        "ranger"
    ],
)


print(
    "-" * 128
)

print(
    "CELL 20 FEATURE LOCK"
)

print(
    "Feature universe       :",
    f"{EXPECTED_FEATURE_COUNT:,}",
    "= 20 + 4*20^2 + 4*20^3",
)

print(
    "1-gram                 :",
    f"{n_counts[1]:,}",
)

print(
    "2-gram                 :",
    f"{n_counts[2]:,}",
)

print(
    "3-gram                 :",
    f"{n_counts[3]:,}",
)

print(
    "ACDEFGHIKL expected    :",
    EXPECTED_UNIQUE_ACTIVE,
)

print(
    "AAAAAAAAAA expected    :",
    EXPECTED_REPEAT_ACTIVE,
)


print(
    "-" * 128
)

print(
    "MODERN HOST"
)

print(
    "Python                 :",
    platform.python_version(),
)


for distribution in sorted(
    host_packages
):

    print(
        f"{distribution:<23}:",
        host_packages[
            distribution
        ][
            "version"
        ],
    )


print(
    "-" * 128
)

print(
    "SCIENTIFIC STATUS"
)

print(
    "Package installation   : FALSE"
)

print(
    "Feature selection fit  : FALSE"
)

print(
    "RF1 fitted             : FALSE"
)

print(
    "RF2 fitted             : FALSE"
)

print(
    "Benchmark training     : FALSE"
)

print(
    "Benchmark test used    : FALSE"
)

print(
    "External target used   : FALSE"
)

print(
    "RF backend equivalence : NOT CLAIMED YET"
)

print(
    "AmpGram validated      : FALSE"
)

print(
    "Training gate modified : FALSE"
)

print(
    "Validated methods      :",
    validated_before,
)

print(
    "TRAINING GATE          : CLOSED"
)


print(
    "-" * 128
)

print(
    "LOCK ACTION            :",
    CELL21_ACTION,
)

print(
    "Cell 21 artifact       :",
    CELL21_PATH,
)

print(
    "Artifact SHA256        :",
    sha256_file(
        CELL21_PATH
    ),
)

print(
    "=" * 128
)

================================================================================================================================
CELL 21 PASS - AMPGRAM MODERN-REIMPLEMENTATION HOST PREFLIGHT + ROUTE CONSISTENCY VERIFIED
================================================================================================================================
AmpGram source commit  : 9a76d4c90a74622ec5ad9dc8b3d908799ac7745a
Cell 16 route          : faithful_source_recipe_reimplementation
Implementation env     : modern_reimplementation
Legacy env             : genpept_ampgram_legacy
Legacy env present     : True
Legacy env required    : FALSE
--------------------------------------------------------------------------------------------------------------------------------
OFFICIAL REFERENCE RUNTIME - PINNED renv.lock
R                      : 3.6.2
biogram                : 1.6.3
biogram RemoteSha      : 148d3d9b323998d759b967a30f13b2b445169a5e
ranger                 : 0.12.1
--------------------------------------------------------------------------------------------------------------------------------
CELL 20 FEATURE LOCK
Feature universe       : 33,620 = 20 + 4*20^2 + 4*20^3
1-gram                 : 20
2-gram                 : 1,600
3-gram                 : 32,000
ACDEFGHIKL expected    : 68
AAAAAAAAAA expected    : 9
--------------------------------------------------------------------------------------------------------------------------------
MODERN HOST
Python                 : 3.11.16
joblib                 : 1.6.0
numpy                  : 2.4.6
pandas                 : 3.0.5
scikit-learn           : 1.9.0
scipy                  : 1.17.1
--------------------------------------------------------------------------------------------------------------------------------
SCIENTIFIC STATUS
Package installation   : FALSE
Feature selection fit  : FALSE
RF1 fitted             : FALSE
RF2 fitted             : FALSE
Benchmark training     : FALSE
Benchmark test used    : FALSE
External target used   : FALSE
RF backend equivalence : NOT CLAIMED YET
AmpGram validated      : FALSE
Training gate modified : FALSE
Validated methods      : ['ampir']
TRAINING GATE          : CLOSED
--------------------------------------------------------------------------------------------------------------------------------
LOCK ACTION            : NEW CONTRACT ATOMICALLY COMMITTED
Cell 21 artifact       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampgram_FINAL_modern_host_preflight.json
Artifact SHA256        : 8cc0ee5a898e358b2edae199f40a0ed8ac346068b2b23cfd0bfa35ab8cfaef98
================================================================================================================================

In [2]:
# ============================================================
# CELL 22 - RESTART-SAFE
# AMPGRAM EXACT RANGER BACKEND DISCOVERY + DECISION GATE
#
# NO INSTALLATION / NO FEATURE SELECTION / NO RF FIT
# NO BENCHMARK TRAINING / NO TEST / NO EXTERNAL TARGET
# NO GLOBAL TRAINING-GATE UPDATE
# ============================================================

from pathlib import Path
from datetime import datetime
import csv
import hashlib
import json
import os
import shutil
import subprocess
import tempfile


# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------
PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

WORK_ROOT = Path(
    "/home/pc/genpept_benchmark17_work"
)

AMPGRAM_SOURCE = Path(
    "/home/pc/genpept_sources/AmpGram-analysis"
)

AMPGRAM_WORK = (
    WORK_ROOT
    / "published_selftests"
    / "ampgram"
)

AMPGRAM_WORK.mkdir(
    parents=True,
    exist_ok=True,
)


for p in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    WORK_ROOT,
    AMPGRAM_SOURCE,
]:
    assert p.is_dir(), (
        f"Required directory missing: {p}"
    )


CELL21_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_modern_host_preflight.json"
)

LOCAL_ENV_AUDIT_PATH = (
    MANIFEST_DIR
    / "benchmark17_published_method_local_environment_latest.json"
)

TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)

RENV_PATH = (
    AMPGRAM_SOURCE
    / "renv.lock"
)


for p in [
    CELL21_PATH,
    LOCAL_ENV_AUDIT_PATH,
    TRAINING_GATE_PATH,
    RENV_PATH,
]:
    assert p.is_file(), (
        f"Required upstream artifact missing: {p}"
    )


# ------------------------------------------------------------
# 2. Helpers
# ------------------------------------------------------------
def load_json(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as f:

        return json.load(f)


def sha256_file(
    path,
    chunk_size=1024 * 1024,
):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        while True:

            b = f.read(
                chunk_size
            )

            if not b:
                break

            h.update(
                b
            )

    return h.hexdigest()


def sha256_tree(
    root,
):

    root = Path(
        root
    ).resolve()

    files = sorted(

        [
            p
            for p
            in root.rglob("*")
            if p.is_file()
        ],

        key=lambda p:
            p.relative_to(root)
            .as_posix(),

    )

    h = hashlib.sha256()

    for p in files:

        rel = (
            p.relative_to(root)
            .as_posix()
            .encode("utf-8")
        )

        h.update(
            len(rel)
            .to_bytes(
                8,
                "big",
            )
        )

        h.update(
            rel
        )

        with open(
            p,
            "rb",
        ) as f:

            while True:

                b = f.read(
                    1024 * 1024
                )

                if not b:
                    break

                h.update(
                    b
                )

    return (
        h.hexdigest(),
        len(files),
    )


def run_cmd(
    cmd,
    env=None,
):

    return subprocess.run(

        [
            str(x)
            for x
            in cmd
        ],

        env=env,

        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,

    )


def atomic_write_text(
    path,
    text,
):

    path = Path(
        path
    )

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if path.exists():

        assert (
            path.read_text(
                encoding="utf-8"
            )
            ==
            text
        ), (
            "Existing locked artifact differs; "
            "refusing overwrite:\n"
            f"{path}"
        )

        return (
            "EXISTING IDENTICAL VERIFIED"
        )

    fd, tmp_name = (
        tempfile.mkstemp(
            prefix=f".{path.name}.",
            suffix=".tmp",
            dir=str(
                path.parent
            ),
        )
    )

    tmp = Path(
        tmp_name
    )

    try:

        with os.fdopen(
            fd,
            "w",
            encoding="utf-8",
            newline="\n",
        ) as f:

            f.write(
                text
            )

            f.flush()

            os.fsync(
                f.fileno()
            )

        os.replace(
            tmp,
            path,
        )

    finally:

        if tmp.exists():

            tmp.unlink()

    return (
        "NEW ATOMIC COMMIT"
    )


def atomic_write_json(
    path,
    status,
    contract,
):

    path = Path(
        path
    )

    if path.exists():

        old = load_json(
            path
        )

        assert (
            old.get(
                "status"
            )
            ==
            status
        ), (
            f"Existing status differs: {path}"
        )

        assert (
            old.get(
                "contract"
            )
            ==
            contract
        ), (
            f"Existing contract differs: {path}"
        )

        return (
            "EXISTING IDENTICAL CONTRACT VERIFIED"
        )

    payload = {

        "created_at":
            datetime.now()
            .astimezone()
            .isoformat(),

        "status":
            status,

        "contract":
            contract,

    }

    return atomic_write_text(

        path,

        json.dumps(
            payload,
            indent=2,
            ensure_ascii=False,
        )
        + "\n",

    )


# ------------------------------------------------------------
# 3. Verify Cell 21 exactly
# ------------------------------------------------------------
EXPECTED_CELL21_SHA256 = (
    "8cc0ee5a898e358b2edae199f40a0ed8"
    "ac346068b2b23cfd0bfa35ab8cfaef98"
)


assert (
    sha256_file(
        CELL21_PATH
    )
    ==
    EXPECTED_CELL21_SHA256
), (
    "Cell 21 artifact hash changed; "
    "do not proceed."
)


cell21 = load_json(
    CELL21_PATH
)


assert (
    cell21[
        "status"
    ]
    ==
    "AMPGRAM_MODERN_REIMPLEMENTATION_HOST_PREFLIGHT_PASS"
)


assert (
    cell21[
        "contract"
    ][
        "model_id"
    ]
    ==
    "ampgram"
)


assert (
    cell21[
        "contract"
    ][
        "scientific_boundary"
    ][
        "benchmark_training_performed"
    ]
    is False
)


assert (
    cell21[
        "contract"
    ][
        "scientific_boundary"
    ][
        "ampgram_implementation_validated"
    ]
    is False
)


assert (
    cell21[
        "contract"
    ][
        "scientific_boundary"
    ][
        "rf_backend_equivalence_claimed"
    ]
    is False
)


# ------------------------------------------------------------
# 4. Official runtime contract from exact renv.lock
# ------------------------------------------------------------
renv = load_json(
    RENV_PATH
)


EXPECTED_R = (
    "3.6.2"
)

EXPECTED_RANGER = (
    "0.12.1"
)

EXPECTED_BIOGRAM = (
    "1.6.3"
)


assert (
    renv[
        "R"
    ][
        "Version"
    ]
    ==
    EXPECTED_R
)


assert (
    renv[
        "Packages"
    ][
        "ranger"
    ][
        "Version"
    ]
    ==
    EXPECTED_RANGER
)


assert (
    renv[
        "Packages"
    ][
        "biogram"
    ][
        "Version"
    ]
    ==
    EXPECTED_BIOGRAM
)


# ------------------------------------------------------------
# Global training gate is read-only
# ------------------------------------------------------------
gate_before = load_json(
    TRAINING_GATE_PATH
)


GATE_SHA_BEFORE = (
    sha256_file(
        TRAINING_GATE_PATH
    )
)


assert (
    gate_before[
        "open"
    ]
    is False
)


assert (
    gate_before[
        "benchmark_training_allowed"
    ]
    is False
)


assert (
    "ampgram"
    not in
    gate_before.get(
        "validated_methods",
        [],
    )
)


# ------------------------------------------------------------
# 5. Discover all existing Rscript runtimes
# ------------------------------------------------------------
env_audit = load_json(
    LOCAL_ENV_AUDIT_PATH
)


CONDA_EXE = Path(
    env_audit[
        "conda_executable"
    ]
)


LEGACY_ENV_NAME = (
    env_audit[
        "ampgram"
    ][
        "legacy_environment"
    ]
)


assert (
    CONDA_EXE.is_file()
), (
    f"Conda executable missing: {CONDA_EXE}"
)


conda = run_cmd(
    [
        CONDA_EXE,
        "env",
        "list",
        "--json",
    ]
)


if (
    conda.returncode
    != 0
):

    print(
        "STDOUT:\n",
        conda.stdout,
    )

    print(
        "STDERR:\n",
        conda.stderr,
    )


assert (
    conda.returncode
    == 0
)


conda_envs = [

    Path(x).resolve()

    for x
    in json.loads(
        conda.stdout
    ).get(
        "envs",
        [],
    )

]


candidate_map = {}


system_r = shutil.which(
    "Rscript"
)


if system_r:

    rp = Path(
        system_r
    ).resolve()

    candidate_map[
        str(rp)
    ] = {

        "rscript":
            rp,

        "source":
            "PATH",

        "env_name":
            "",

        "env_path":
            "",

    }


for env_path in sorted(
    conda_envs,
    key=str,
):

    rp = (
        env_path
        / "bin"
        / "Rscript"
    )

    if rp.is_file():

        rp = rp.resolve()

        candidate_map[
            str(rp)
        ] = {

            "rscript":
                rp,

            "source":
                "CONDA",

            "env_name":
                env_path.name,

            "env_path":
                str(
                    env_path
                ),

        }


candidates = [

    candidate_map[k]

    for k
    in sorted(
        candidate_map
    )

]


assert candidates, (
    "No Rscript found in PATH or conda environments."
)


# ------------------------------------------------------------
# 6. Probe script
#
# IMPORTANT:
# only runtime/package discovery.
# NO ranger model is fitted here.
# ------------------------------------------------------------
R_PROBE_PATH = (
    AMPGRAM_WORK
    / "ampgram_cell22_ranger_probe.R"
)


R_PROBE = r'''
emit <- function(k, v) {
  cat(
    "AMPGRAM22\t",
    k,
    "\t",
    v,
    "\n",
    sep = ""
  )
}

emit(
  "R_VERSION",
  as.character(
    getRversion()
  )
)

emit(
  "R_PLATFORM",
  R.version$platform
)

emit(
  "R_HOME",
  R.home()
)

emit(
  "LIBPATHS",
  paste(
    .libPaths(),
    collapse = "|"
  )
)

ok <- requireNamespace(
  "ranger",
  quietly = TRUE
)

emit(
  "RANGER_AVAILABLE",
  toupper(
    as.character(
      ok
    )
  )
)

if (ok) {

  d <- packageDescription(
    "ranger"
  )

  emit(
    "RANGER_VERSION",
    as.character(
      packageVersion(
        "ranger"
      )
    )
  )

  emit(
    "RANGER_PATH",
    normalizePath(
      find.package(
        "ranger"
      ),
      mustWork = TRUE
    )
  )

  emit(
    "RANGER_BUILT",
    if (
      is.null(
        d$Built
      )
    ) {
      ""
    } else {
      d$Built
    }
  )

}
'''


PROBE_ACTION = (
    atomic_write_text(
        R_PROBE_PATH,
        R_PROBE,
    )
)


# ------------------------------------------------------------
# 7. Probe every R runtime
# ------------------------------------------------------------
rows = []


for c in candidates:

    env = (
        os.environ.copy()
    )


    for key in [

        "R_HOME",
        "R_LIBS",
        "R_LIBS_USER",
        "R_ENVIRON",
        "R_ENVIRON_USER",
        "R_PROFILE",
        "R_PROFILE_USER",

    ]:

        env.pop(
            key,
            None,
        )


    result = run_cmd(

        [
            c[
                "rscript"
            ],
            "--vanilla",
            R_PROBE_PATH,
        ],

        env=env,

    )


    parsed = {}


    if (
        result.returncode
        == 0
    ):

        for line in (
            result.stdout
            .splitlines()
        ):

            if line.startswith(
                "AMPGRAM22\t"
            ):

                parts = (
                    line.split(
                        "\t",
                        2,
                    )
                )

                assert (
                    len(parts)
                    == 3
                ), (
                    f"Malformed probe line: {line}"
                )

                parsed[
                    parts[
                        1
                    ]
                ] = (
                    parts[
                        2
                    ]
                )

    else:

        print(
            "=" * 120
        )

        print(
            "R PROBE FAILED:",
            c[
                "rscript"
            ],
        )

        print(
            "RETURN CODE:",
            result.returncode,
        )

        print(
            "STDOUT:\n",
            result.stdout
            or "<EMPTY>",
        )

        print(
            "STDERR:\n",
            result.stderr
            or "<EMPTY>",
        )

        print(
            "=" * 120
        )


    available = (
        parsed.get(
            "RANGER_AVAILABLE"
        )
        ==
        "TRUE"
    )


    ranger_path = (
        parsed.get(
            "RANGER_PATH",
            "",
        )
    )


    inside_env = False


    if (
        available
        and
        c[
            "source"
        ]
        ==
        "CONDA"
        and
        ranger_path
    ):

        pkg = Path(
            ranger_path
        ).resolve()

        root = Path(
            c[
                "env_path"
            ]
        ).resolve()

        try:

            inside_env = (
                Path(
                    os.path.commonpath(
                        [
                            str(
                                pkg
                            ),
                            str(
                                root
                            ),
                        ]
                    )
                )
                ==
                root
            )

        except ValueError:

            inside_env = False


    r_exact = (
        parsed.get(
            "R_VERSION"
        )
        ==
        EXPECTED_R
    )


    ranger_exact = (
        parsed.get(
            "RANGER_VERSION"
        )
        ==
        EXPECTED_RANGER
    )


    exact_backend = bool(

        result.returncode
        == 0

        and
        available

        and
        r_exact

        and
        ranger_exact

        and
        c[
            "source"
        ]
        ==
        "CONDA"

        and
        inside_env

    )


    rows.append(
        {

            "rscript_path":
                str(
                    c[
                        "rscript"
                    ]
                ),

            "source":
                c[
                    "source"
                ],

            "conda_env_name":
                c[
                    "env_name"
                ],

            "conda_env_path":
                c[
                    "env_path"
                ],

            "probe_returncode":
                int(
                    result.returncode
                ),

            "r_version":
                parsed.get(
                    "R_VERSION",
                    "",
                ),

            "r_platform":
                parsed.get(
                    "R_PLATFORM",
                    "",
                ),

            "r_home":
                parsed.get(
                    "R_HOME",
                    "",
                ),

            "libpaths":
                parsed.get(
                    "LIBPATHS",
                    "",
                ),

            "ranger_available":
                available,

            "ranger_version":
                parsed.get(
                    "RANGER_VERSION",
                    "",
                ),

            "ranger_path":
                ranger_path,

            "ranger_built":
                parsed.get(
                    "RANGER_BUILT",
                    "",
                ),

            "ranger_path_inside_conda_env":
                inside_env,

            "reference_r_exact":
                r_exact,

            "reference_ranger_exact":
                ranger_exact,

            "exact_reference_backend":
                exact_backend,

        }
    )


# ------------------------------------------------------------
# 8. Deterministic exact-backend selection
#
# Only exact:
#     isolated CONDA runtime
#     R 3.6.2
#     ranger 0.12.1
#
# A different ranger/R version is NOT silently accepted.
# ------------------------------------------------------------
exact = [

    r

    for r
    in rows

    if r[
        "exact_reference_backend"
    ]

]


exact.sort(

    key=lambda r: (

        0
        if
        r[
            "conda_env_name"
        ]
        ==
        LEGACY_ENV_NAME
        else
        1,

        r[
            "rscript_path"
        ],

    )

)


selected = (
    exact[
        0
    ]
    if exact
    else None
)


selected_backend = None


if (
    selected
    is not None
):

    ranger_root = Path(
        selected[
            "ranger_path"
        ]
    ).resolve()


    desc = (
        ranger_root
        / "DESCRIPTION"
    )


    assert (
        desc.is_file()
    ), (
        f"ranger DESCRIPTION missing: {desc}"
    )


    tree_sha, tree_files = (
        sha256_tree(
            ranger_root
        )
    )


    selected_backend = {

        "rscript_path":
            selected[
                "rscript_path"
            ],

        "source":
            selected[
                "source"
            ],

        "conda_env_name":
            selected[
                "conda_env_name"
            ],

        "conda_env_path":
            selected[
                "conda_env_path"
            ],

        "r_version":
            selected[
                "r_version"
            ],

        "r_platform":
            selected[
                "r_platform"
            ],

        "ranger_version":
            selected[
                "ranger_version"
            ],

        "ranger_path":
            selected[
                "ranger_path"
            ],

        "ranger_built":
            selected[
                "ranger_built"
            ],

        "ranger_description_sha256":
            sha256_file(
                desc
            ),

        "ranger_tree_sha256":
            tree_sha,

        "ranger_tree_file_count":
            tree_files,

    }


# ------------------------------------------------------------
# 9. Immutable discovery audit CSV
# ------------------------------------------------------------
AUDIT_CSV_PATH = (
    AUDIT_DIR
    / "benchmark17_ampgram_ranger_backend_discovery.csv"
)


columns = list(
    rows[
        0
    ].keys()
)


with tempfile.NamedTemporaryFile(

    mode="w",
    encoding="utf-8",
    newline="",
    delete=False,
    dir=str(
        AUDIT_DIR
    ),
    suffix=".csv",

) as tf:

    writer = csv.DictWriter(
        tf,
        fieldnames=columns,
    )

    writer.writeheader()

    for row in sorted(
        rows,
        key=lambda r:
            r[
                "rscript_path"
            ],
    ):

        writer.writerow(
            row
        )

    temp_csv = Path(
        tf.name
    )


try:

    AUDIT_ACTION = (
        atomic_write_text(

            AUDIT_CSV_PATH,

            temp_csv.read_text(
                encoding="utf-8"
            ),

        )
    )

finally:

    if temp_csv.exists():

        temp_csv.unlink()


# ------------------------------------------------------------
# 10. Immutable decision contract
# ------------------------------------------------------------
BACKEND_READY = (
    selected_backend
    is not None
)


DECISION = (

    "EXACT_REFERENCE_RANGER_BACKEND_FOUND"

    if BACKEND_READY

    else

    "NO_EXACT_REFERENCE_RANGER_BACKEND_FOUND"

)


CELL22_CONTRACT = {

    "schema_version":
        "1.0",

    "model_id":
        "ampgram",

    "stage":
        "exact_ranger_backend_discovery_and_decision",

    "upstream_cell21_sha256":
        EXPECTED_CELL21_SHA256,

    "official_reference": {

        "R_version":
            EXPECTED_R,

        "ranger_version":
            EXPECTED_RANGER,

        "biogram_version":
            EXPECTED_BIOGRAM,

    },

    "discovery": {

        "runtimes_scanned":
            len(
                rows
            ),

        "ranger_available":
            sum(
                r[
                    "ranger_available"
                ]
                for r
                in rows
            ),

        "exact_reference_backends":
            len(
                exact
            ),

        "audit_csv_path":
            str(
                AUDIT_CSV_PATH
            ),

        "audit_csv_sha256":
            sha256_file(
                AUDIT_CSV_PATH
            ),

    },

    "decision":
        DECISION,

    "backend_ready_for_full_adapter_selftest":
        BACKEND_READY,

    "selected_backend":
        selected_backend,

    "scientific_boundary": {

        "package_installation_performed":
            False,

        "feature_selection_fit":
            False,

        "rf1_fit":
            False,

        "rf2_fit":
            False,

        "benchmark_training_performed":
            False,

        "benchmark_test_used":
            False,

        "external_target_used":
            False,

        "training_gate_modified":
            False,

        "nonexact_ranger_backend_accepted":
            False,

        "sklearn_declared_equivalent_to_ranger":
            False,

        "ampgram_implementation_validated":
            False,

    },

}


CELL22_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_ranger_backend_decision.json"
)


CELL22_STATUS = (

    "AMPGRAM_EXACT_RANGER_BACKEND_READY"

    if BACKEND_READY

    else

    "AMPGRAM_EXACT_RANGER_BACKEND_NOT_FOUND"

)


CONTRACT_ACTION = (
    atomic_write_json(
        CELL22_PATH,
        CELL22_STATUS,
        CELL22_CONTRACT,
    )
)


check = load_json(
    CELL22_PATH
)


assert (
    check[
        "status"
    ]
    ==
    CELL22_STATUS
)


assert (
    check[
        "contract"
    ]
    ==
    CELL22_CONTRACT
)


# ------------------------------------------------------------
# 11. Global training gate must remain byte-identical
# ------------------------------------------------------------
assert (
    sha256_file(
        TRAINING_GATE_PATH
    )
    ==
    GATE_SHA_BEFORE
), (
    "Cell 22 modified the global training gate."
)


# ------------------------------------------------------------
# 12. Report
#
# PASS here means discovery/decision itself is correct.
# Backend readiness is reported separately.
# ------------------------------------------------------------
print(
    "=" * 128
)

print(
    "CELL 22 PASS - AMPGRAM EXACT RANGER "
    "BACKEND DISCOVERY + DECISION COMPLETED"
)

print(
    "=" * 128
)


print(
    "Official R             :",
    EXPECTED_R,
)

print(
    "Official ranger        :",
    EXPECTED_RANGER,
)

print(
    "Official biogram       :",
    EXPECTED_BIOGRAM,
)

print(
    "R runtimes scanned     :",
    len(
        rows
    ),
)

print(
    "ranger available       :",
    sum(
        r[
            "ranger_available"
        ]
        for r
        in rows
    ),
)

print(
    "Exact reference backend:",
    len(
        exact
    ),
)

print(
    "Decision               :",
    DECISION,
)

print(
    "Backend ready          :",
    str(
        BACKEND_READY
    ).upper(),
)


if (
    selected_backend
):

    print(
        "Selected Rscript       :",
        selected_backend[
            "rscript_path"
        ],
    )

    print(
        "Selected env           :",
        selected_backend[
            "conda_env_name"
        ],
    )

    print(
        "Selected R             :",
        selected_backend[
            "r_version"
        ],
    )

    print(
        "Selected ranger        :",
        selected_backend[
            "ranger_version"
        ],
    )

    print(
        "ranger package path    :",
        selected_backend[
            "ranger_path"
        ],
    )

    print(
        "ranger tree SHA256     :",
        selected_backend[
            "ranger_tree_sha256"
        ],
    )

else:

    print(
        "Selected backend       : NONE"
    )

    print(
        "Self-test readiness    : BLOCKED - "
        "exact isolated R 3.6.2 + ranger 0.12.1 not found"
    )


print(
    "-" * 128
)

print(
    "Package installation   : FALSE"
)

print(
    "Feature selection fit  : FALSE"
)

print(
    "RF1 fitted             : FALSE"
)

print(
    "RF2 fitted             : FALSE"
)

print(
    "Benchmark training     : FALSE"
)

print(
    "Benchmark test used    : FALSE"
)

print(
    "External target used   : FALSE"
)

print(
    "sklearn == ranger claim: FALSE"
)

print(
    "AmpGram validated      : FALSE"
)

print(
    "Training gate modified : FALSE"
)

print(
    "TRAINING GATE          : CLOSED"
)


print(
    "-" * 128
)

print(
    "Probe action           :",
    PROBE_ACTION,
)

print(
    "Audit action           :",
    AUDIT_ACTION,
)

print(
    "Contract action        :",
    CONTRACT_ACTION,
)

print(
    "Cell 22 artifact       :",
    CELL22_PATH,
)

print(
    "Artifact SHA256        :",
    sha256_file(
        CELL22_PATH
    ),
)

print(
    "=" * 128
)

================================================================================================================================
CELL 22 PASS - AMPGRAM EXACT RANGER BACKEND DISCOVERY + DECISION COMPLETED
================================================================================================================================
Official R             : 3.6.2
Official ranger        : 0.12.1
Official biogram       : 1.6.3
R runtimes scanned     : 2
ranger available       : 1
Exact reference backend: 1
Decision               : EXACT_REFERENCE_RANGER_BACKEND_FOUND
Backend ready          : TRUE
Selected Rscript       : /home/pc/miniconda3/envs/genpept_ampgram_legacy/bin/Rscript
Selected env           : genpept_ampgram_legacy
Selected R             : 3.6.2
Selected ranger        : 0.12.1
ranger package path    : /home/pc/miniconda3/envs/genpept_ampgram_legacy/lib/R/library/ranger
ranger tree SHA256     : 798275a6438ad9b212cd6d0d22a2d5c970488cb6853f7f5196d577da013b07e6
--------------------------------------------------------------------------------------------------------------------------------
Package installation   : FALSE
Feature selection fit  : FALSE
RF1 fitted             : FALSE
RF2 fitted             : FALSE
Benchmark training     : FALSE
Benchmark test used    : FALSE
External target used   : FALSE
sklearn == ranger claim: FALSE
AmpGram validated      : FALSE
Training gate modified : FALSE
TRAINING GATE          : CLOSED
--------------------------------------------------------------------------------------------------------------------------------
Probe action           : NEW ATOMIC COMMIT
Audit action           : NEW ATOMIC COMMIT
Contract action        : NEW ATOMIC COMMIT
Cell 22 artifact       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampgram_FINAL_ranger_backend_decision.json
Artifact SHA256        : 868cd243cfc0fe356d9d1b29596c64b0c1b00ab7599503c547e889a3a53bc49b
================================================================================================================================

In [8]:
# ============================================================
# CELL 23 - RESTART-SAFE
# AMPGRAM EXACT R-3.6.2 ENVIRONMENT RESTORATION v5
# + TOOLCHAIN-COMPATIBILITY PREFLIGHT
# + BIOGRAM-1.6.3 OFFICIAL RUNTIME SMOKE TEST
#
# WHY v5 EXISTS
# -------------
# Cell 23 v4 correctly identified the missing exact dependency
# partitions 1.9-22, but its source build used the legacy conda
# compiler/linker shipped with the R-3.6.2 environment. On this
# modern host, that old linker cannot parse .relr.dyn sections in
# the current glibc/libm objects. That is a BUILD-TOOLCHAIN problem,
# not an AmpGram/biogram/source-code problem.
#
# This replacement Cell 23:
#   1) preserves the exact locked R/package/source versions;
#   2) does NOT modify/upgrade the conda compiler toolchain;
#   3) uses an isolated temporary R_MAKEVARS_USER override pointing
#      to the host GCC/G++/binutils ONLY for source compilation;
#   4) first proves that this compiler path can compile+link C and
#      C++ shared libraries against the selected R 3.6.2 runtime;
#   5) then restores only missing exact package versions from the
#      already-audited exact source commits;
#   6) loads biogram 1.6.3 + ranger 0.12.1 and runs the official
#      QuiPT-style synthetic smoke test;
#   7) never fits AmpGram RF1/RF2, never touches benchmark test or
#      external targets, and never opens/modifies the training gate.
#
# IMPORTANT
# ---------
# - Replace the entire previous Cell 23 with this Cell.
# - Do NOT run Cell 24 until this Cell prints CELL 23 PASS.
# ============================================================

from pathlib import Path
from datetime import datetime
import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)
OUTPUT_ROOT = PROJECT_ROOT / "benchmark17_outputs"
AUDIT_DIR = OUTPUT_ROOT / "audit"
MANIFEST_DIR = OUTPUT_ROOT / "manifests"
WORK_ROOT = Path("/home/pc/genpept_benchmark17_work")
SOURCE_ROOT = Path("/home/pc/genpept_sources")
AMPGRAM_SOURCE = SOURCE_ROOT / "AmpGram-analysis"
AMPGRAM_WORK = WORK_ROOT / "published_selftests" / "ampgram"
EXACT_CRAN_SOURCE_ROOT = SOURCE_ROOT / "ampgram_exact_cran_sources"

AMPGRAM_WORK.mkdir(parents=True, exist_ok=True)
EXACT_CRAN_SOURCE_ROOT.mkdir(parents=True, exist_ok=True)

for path in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    WORK_ROOT,
    SOURCE_ROOT,
    AMPGRAM_SOURCE,
]:
    assert path.is_dir(), f"Required directory missing:\n{path}"

CELL22_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_ranger_backend_decision.json"
)
TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)
AMPGRAM_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_implementation_contract.json"
)
AMPGRAM_AMENDMENT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_source_recipe_amendment_v1.1.json"
)
RENV_PATH = AMPGRAM_SOURCE / "renv.lock"

for path in [
    CELL22_PATH,
    TRAINING_GATE_PATH,
    AMPGRAM_CONTRACT_PATH,
    AMPGRAM_AMENDMENT_PATH,
    RENV_PATH,
]:
    assert path.is_file(), f"Required upstream artifact missing:\n{path}"


# ============================================================
# 2. HELPERS
# ============================================================

def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def sha256_file(path, chunk_size=1024 * 1024):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            b = f.read(chunk_size)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def normalize_git_remote(value):
    value = str(value).strip().removesuffix(".git")
    if value.startswith("git@github.com:"):
        value = "https://github.com/" + value[len("git@github.com:"):]
    if value.startswith("ssh://git@github.com/"):
        value = "https://github.com/" + value[len("ssh://git@github.com/"):]
    return value.rstrip("/")


def run_cmd(command, cwd=None, env=None, timeout=1800):
    try:
        return subprocess.run(
            [str(x) for x in command],
            cwd=None if cwd is None else str(cwd),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout,
            check=False,
        )
    except Exception as exc:
        class FailedResult:
            returncode = -999
            stdout = ""
            stderr = repr(exc)
        return FailedResult()


def print_subprocess_failure(label, result, command=None):
    print("=" * 128)
    print(f"SUBPROCESS FAILURE - {label}")
    if command is not None:
        print("COMMAND:", [str(x) for x in command])
    print("RETURN CODE:", result.returncode)
    print("--- STDOUT ---")
    print(result.stdout or "<EMPTY>")
    print("--- STDERR ---")
    print(result.stderr or "<EMPTY>")
    print("=" * 128)


def git(repo, *args, timeout=120):
    return run_cmd(
        ["git", "-C", str(repo), *[str(x) for x in args]],
        timeout=timeout,
    )


def source_git_head(path):
    result = git(path, "rev-parse", "HEAD")
    if result.returncode != 0:
        print_subprocess_failure(
            f"git rev-parse HEAD: {path}",
            result,
        )
    assert result.returncode == 0, f"Cannot read git HEAD: {path}"
    return result.stdout.strip()


def source_git_remote(path):
    result = git(path, "remote", "get-url", "origin")
    if result.returncode != 0:
        print_subprocess_failure(
            f"git remote get-url origin: {path}",
            result,
        )
    assert result.returncode == 0, f"Cannot read git remote: {path}"
    return normalize_git_remote(result.stdout)


def atomic_write_text(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists():
        old = path.read_text(encoding="utf-8")
        assert old == text, (
            "Existing locked artifact differs; refusing overwrite:\n"
            f"{path}"
        )
        return "EXISTING IDENTICAL VERIFIED"

    fd, tmp_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=str(path.parent),
    )
    tmp_path = Path(tmp_name)

    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_path, path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()

    return "NEW ATOMIC COMMIT"


def atomic_write_contract(path, status, contract):
    path = Path(path)

    if path.exists():
        old = load_json(path)
        assert old.get("status") == status, (
            "Existing Cell 23 status differs; refusing overwrite:\n"
            f"{path}"
        )
        assert old.get("contract") == contract, (
            "Existing Cell 23 contract differs; refusing overwrite:\n"
            f"{path}"
        )
        return "EXISTING IDENTICAL CONTRACT VERIFIED"

    payload = {
        "created_at": datetime.now().astimezone().isoformat(),
        "status": status,
        "contract": contract,
    }

    action = atomic_write_text(
        path,
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
    )
    check = load_json(path)
    assert check["status"] == status
    assert check["contract"] == contract

    return action.replace(
        "NEW ATOMIC COMMIT",
        "NEW CONTRACT ATOMICALLY COMMITTED",
    )


def ensure_exact_git_source(repo_full_name, commit, destination):
    """
    Reuse an exact local checkout if present.
    Otherwise fetch exactly the audited commit.
    Never mutate an existing non-matching checkout.
    """
    destination = Path(destination)
    expected_remote = f"https://github.com/{repo_full_name}"

    if destination.exists():
        assert destination.is_dir(), (
            f"Source destination exists but is not a directory:\n{destination}"
        )
        assert (destination / ".git").is_dir(), (
            "Existing source directory is not a git checkout; refusing mutation:\n"
            f"{destination}"
        )
        assert source_git_head(destination) == commit, (
            "Existing exact-source destination has wrong commit:\n"
            f"{destination}"
        )
        assert source_git_remote(destination) == expected_remote, (
            "Existing exact-source destination has wrong remote:\n"
            f"{destination}"
        )
        return destination, "EXISTING EXACT SOURCE VERIFIED"

    tmp_parent = destination.parent
    tmp_dir = Path(
        tempfile.mkdtemp(
            prefix=f".{destination.name}.",
            dir=str(tmp_parent),
        )
    )

    try:
        result = run_cmd(["git", "init", "-q", str(tmp_dir)], timeout=120)
        if result.returncode != 0:
            print_subprocess_failure("git init exact source", result)
        assert result.returncode == 0

        result = run_cmd(
            [
                "git", "-C", str(tmp_dir),
                "remote", "add", "origin",
                f"https://github.com/{repo_full_name}.git",
            ],
            timeout=120,
        )
        if result.returncode != 0:
            print_subprocess_failure("git remote add exact source", result)
        assert result.returncode == 0

        result = run_cmd(
            [
                "git", "-C", str(tmp_dir),
                "fetch", "-q", "--depth", "1", "origin", commit,
            ],
            timeout=600,
        )

        if result.returncode != 0:
            # Fallback to a normal clone, still followed by exact detached checkout.
            shutil.rmtree(tmp_dir, ignore_errors=True)
            result = run_cmd(
                [
                    "git", "clone", "-q",
                    f"https://github.com/{repo_full_name}.git",
                    str(tmp_dir),
                ],
                timeout=900,
            )
            if result.returncode != 0:
                print_subprocess_failure(
                    f"clone exact source {repo_full_name}",
                    result,
                )
            assert result.returncode == 0

            result = run_cmd(
                [
                    "git", "-C", str(tmp_dir),
                    "checkout", "-q", "--detach", commit,
                ],
                timeout=300,
            )
        else:
            result = run_cmd(
                [
                    "git", "-C", str(tmp_dir),
                    "checkout", "-q", "--detach", "FETCH_HEAD",
                ],
                timeout=300,
            )

        if result.returncode != 0:
            print_subprocess_failure(
                f"checkout exact source {repo_full_name}",
                result,
            )
        assert result.returncode == 0

        assert source_git_head(tmp_dir) == commit
        assert source_git_remote(tmp_dir) == expected_remote

        os.rename(tmp_dir, destination)
        return destination, "EXACT SOURCE ACQUIRED AND LOCKED"

    finally:
        if tmp_dir.exists():
            shutil.rmtree(tmp_dir, ignore_errors=True)


def get_tool_version(executable, args=("--version",)):
    result = run_cmd([executable, *args], timeout=60)
    if result.returncode != 0:
        return "<UNAVAILABLE>"
    first = (result.stdout or result.stderr or "").splitlines()
    return first[0].strip() if first else "<UNKNOWN>"


# ============================================================
# 3. VERIFY UPSTREAM CELL 22 EXACTLY
# ============================================================

EXPECTED_CELL22_SHA256 = (
    "868cd243cfc0fe356d9d1b29596c64b0"
    "c1b00ab7599503c547e889a3a53bc49b"
)

assert sha256_file(CELL22_PATH) == EXPECTED_CELL22_SHA256, (
    "Cell 22 artifact hash changed; do not continue."
)

cell22 = load_json(CELL22_PATH)
assert cell22["status"] == "AMPGRAM_EXACT_RANGER_BACKEND_READY"
assert cell22["contract"]["model_id"] == "ampgram"
assert (
    cell22["contract"]["decision"]
    == "EXACT_REFERENCE_RANGER_BACKEND_FOUND"
)
assert cell22["contract"]["backend_ready_for_full_adapter_selftest"] is True

selected_backend = cell22["contract"]["selected_backend"]
assert selected_backend is not None

R_SCRIPT = Path(selected_backend["rscript_path"])
AMPGRAM_ENV = Path(selected_backend["conda_env_path"])
R_BIN = R_SCRIPT.parent / "R"
R_LIB = AMPGRAM_ENV / "lib" / "R" / "library"

for path in [R_SCRIPT, R_BIN, R_LIB]:
    assert path.exists(), f"Cell 22 selected runtime component missing:\n{path}"

assert selected_backend["r_version"] == "3.6.2"
assert selected_backend["ranger_version"] == "0.12.1"


# ============================================================
# 4. GLOBAL TRAINING GATE - READ ONLY
# ============================================================

gate_before = load_json(TRAINING_GATE_PATH)
GATE_SHA_BEFORE = sha256_file(TRAINING_GATE_PATH)

assert gate_before["open"] is False
assert gate_before["benchmark_training_allowed"] is False
assert "ampir" in gate_before.get("validated_methods", [])
assert "ampgram" not in gate_before.get("validated_methods", [])


# ============================================================
# 5. OFFICIAL SOURCE + renv.lock
# ============================================================

EXPECTED_AMPGRAM_COMMIT = (
    "9a76d4c90a74622ec5ad9dc8b3d908799ac7745a"
)
EXPECTED_BIOGRAM_COMMIT = (
    "148d3d9b323998d759b967a30f13b2b445169a5e"
)

assert source_git_head(AMPGRAM_SOURCE) == EXPECTED_AMPGRAM_COMMIT
assert (
    source_git_remote(AMPGRAM_SOURCE)
    == "https://github.com/michbur/AmpGram-analysis"
)

renv = load_json(RENV_PATH)
assert renv["R"]["Version"] == "3.6.2"

EXPECTED_VERSIONS = {
    "slam": str(renv["Packages"]["slam"]["Version"]),
    "combinat": str(renv["Packages"]["combinat"]["Version"]),
    "entropy": str(renv["Packages"]["entropy"]["Version"]),
    "gmp": str(renv["Packages"]["gmp"]["Version"]),
    "polynom": str(renv["Packages"]["polynom"]["Version"]),
    "sets": str(renv["Packages"]["sets"]["Version"]),
    "partitions": str(renv["Packages"]["partitions"]["Version"]),
    "biogram": str(renv["Packages"]["biogram"]["Version"]),
    "ranger": str(renv["Packages"]["ranger"]["Version"]),
}

assert EXPECTED_VERSIONS == {
    "slam": "0.1-47",
    "combinat": "0.0-8",
    "entropy": "1.2.1",
    "gmp": "0.5-13.6",
    "polynom": "1.4-0",
    "sets": "1.0-18",
    "partitions": "1.9-22",
    "biogram": "1.6.3",
    "ranger": "0.12.1",
}

biogram_lock = renv["Packages"]["biogram"]
assert biogram_lock["RemoteRepo"] == "biogram"
assert biogram_lock["RemoteUsername"] == "michbur"
assert biogram_lock["RemoteSha"] == EXPECTED_BIOGRAM_COMMIT


# ============================================================
# 6. EXACT LOCAL BIOGRAM SOURCE
# ============================================================

biogram_candidates = []

for child in sorted(SOURCE_ROOT.iterdir(), key=lambda p: p.name.lower()):
    if not child.is_dir() or not (child / ".git").is_dir():
        continue

    h = git(child, "rev-parse", "HEAD")
    r = git(child, "remote", "get-url", "origin")

    if h.returncode != 0 or r.returncode != 0:
        continue

    if (
        h.stdout.strip() == EXPECTED_BIOGRAM_COMMIT
        and normalize_git_remote(r.stdout)
        == "https://github.com/michbur/biogram"
    ):
        biogram_candidates.append(child.resolve())

assert biogram_candidates, (
    "Exact local michbur/biogram source at locked commit was not found.\n"
    f"Expected commit: {EXPECTED_BIOGRAM_COMMIT}\n"
    f"Search root    : {SOURCE_ROOT}"
)

BIOGRAM_SOURCE = sorted(biogram_candidates, key=lambda p: str(p))[0]
assert source_git_head(BIOGRAM_SOURCE) == EXPECTED_BIOGRAM_COMMIT
assert source_git_remote(BIOGRAM_SOURCE) == "https://github.com/michbur/biogram"

bio_desc = (BIOGRAM_SOURCE / "DESCRIPTION").read_text(
    encoding="utf-8",
    errors="replace",
)
bio_namespace = (BIOGRAM_SOURCE / "NAMESPACE").read_text(
    encoding="utf-8",
    errors="replace",
)

assert re.search(r"(?m)^Version:\s*1\.6\.3\s*$", bio_desc)
assert "import(slam)" in bio_namespace
assert "importFrom(combinat,permn)" in bio_namespace
assert "importFrom(entropy,KL.plugin)" in bio_namespace
assert "importFrom(partitions,listParts)" in bio_namespace


# ============================================================
# 7. EXACT CRAN SOURCE COMMITS PINNED BY OFFICIAL renv.lock
# ============================================================

PINNED_CRAN_SOURCES = {
    "gmp": {
        "version": "0.5-13.6",
        "repo": "cran/gmp",
        "commit": "86b289fa6afce4790ad71f91e8def621ec2739e7",
    },
    "polynom": {
        "version": "1.4-0",
        "repo": "cran/polynom",
        "commit": "b0c90fb9a9ad30bba124bb0fa9a039cb4bd30e1e",
    },
    "sets": {
        "version": "1.0-18",
        "repo": "cran/sets",
        "commit": "e2b1bfdc9bb23c40ae135f9dae4c5d5300607898",
    },
    "partitions": {
        "version": "1.9-22",
        "repo": "cran/partitions",
        "commit": "d4d1cb5a354678c0951abd95a1d8c0f88b348183",
    },
}

for pkg, info in PINNED_CRAN_SOURCES.items():
    assert EXPECTED_VERSIONS[pkg] == info["version"]

# Official partitions 1.9-22 is a compiled package and imports these.
partitions_source, partitions_source_action = ensure_exact_git_source(
    PINNED_CRAN_SOURCES["partitions"]["repo"],
    PINNED_CRAN_SOURCES["partitions"]["commit"],
    EXACT_CRAN_SOURCE_ROOT / "partitions-1.9-22",
)
part_desc = (partitions_source / "DESCRIPTION").read_text(
    encoding="utf-8",
    errors="replace",
)
assert re.search(r"(?m)^Version:\s*1\.9-22\s*$", part_desc)
assert re.search(r"(?m)^NeedsCompilation:\s*yes\s*$", part_desc)
for required in ["gmp", "polynom", "sets"]:
    assert required in part_desc


# ============================================================
# 8. RUNTIME ENVIRONMENT
# ============================================================

r_env = os.environ.copy()

for key in [
    "R_HOME",
    "R_LIBS",
    "R_LIBS_USER",
    "R_ENVIRON",
    "R_ENVIRON_USER",
    "R_PROFILE",
    "R_PROFILE_USER",
    "R_MAKEVARS_USER",
    "R_MAKEVARS_SITE",
]:
    r_env.pop(key, None)

r_env["PATH"] = str(AMPGRAM_ENV / "bin") + os.pathsep + r_env.get("PATH", "")
r_env["R_LIBS_USER"] = str(R_LIB)
r_env["R_LIBS_SITE"] = str(R_LIB)
r_env["MAKEFLAGS"] = "-j2"

# Keep headers/libraries from the isolated AmpGram environment available.
r_env["CPPFLAGS"] = (
    f"-I{AMPGRAM_ENV / 'include'} " + r_env.get("CPPFLAGS", "")
).strip()
r_env["LDFLAGS"] = (
    f"-L{AMPGRAM_ENV / 'lib'} "
    f"-Wl,-rpath,{AMPGRAM_ENV / 'lib'} "
    + r_env.get("LDFLAGS", "")
).strip()


# ============================================================
# 9. EXACT PACKAGE PROBE - SEMANTIC R VERSION COMPARISON
# ============================================================

R_PROBE_PATH = AMPGRAM_WORK / "ampgram_cell23_v5_exact_package_probe.R"

r_expected_entries = ",\n".join(
    f'  {pkg} = "{version}"'
    for pkg, version in EXPECTED_VERSIONS.items()
)

R_PROBE = f'''expected <- c(
{r_expected_entries}
)

emit <- function(k, v) {{
  cat("AMPGRAM23\\t", k, "\\t", v, "\\n", sep = "")
}}

emit("R_VERSION", as.character(getRversion()))
emit("R_HOME", R.home())
emit("R_PLATFORM", R.version$platform)
emit("LIBPATHS", paste(.libPaths(), collapse = "|"))

for (pkg in names(expected)) {{
  key <- toupper(pkg)
  ok <- requireNamespace(pkg, quietly = TRUE)
  emit(paste0("PKG_", key, "_AVAILABLE"), toupper(as.character(ok)))

  if (ok) {{
    actual <- as.character(packageVersion(pkg))
    semantic <- utils::compareVersion(actual, expected[[pkg]]) == 0
    desc <- packageDescription(pkg)
    built <- if (is.null(desc$Built)) "" else desc$Built
    pkg_path <- normalizePath(find.package(pkg), mustWork = TRUE)

    emit(paste0("PKG_", key, "_EXPECTED"), expected[[pkg]])
    emit(paste0("PKG_", key, "_VERSION"), actual)
    emit(paste0("PKG_", key, "_SEMANTIC_MATCH"), toupper(as.character(semantic)))
    emit(paste0("PKG_", key, "_PATH"), pkg_path)
    emit(paste0("PKG_", key, "_BUILT"), built)
  }} else {{
    emit(paste0("PKG_", key, "_EXPECTED"), expected[[pkg]])
    emit(paste0("PKG_", key, "_VERSION"), "")
    emit(paste0("PKG_", key, "_SEMANTIC_MATCH"), "FALSE")
    emit(paste0("PKG_", key, "_PATH"), "")
    emit(paste0("PKG_", key, "_BUILT"), "")
  }}
}}
'''

PROBE_ACTION = atomic_write_text(R_PROBE_PATH, R_PROBE)


def parse_probe(result):
    parsed = {}
    for line in result.stdout.splitlines():
        if not line.startswith("AMPGRAM23\t"):
            continue
        parts = line.split("\t", 2)
        assert len(parts) == 3, f"Malformed R probe line: {line}"
        parsed[parts[1]] = parts[2]
    return parsed


def run_package_probe(label):
    command = [R_SCRIPT, "--vanilla", R_PROBE_PATH]
    result = run_cmd(command, env=r_env, timeout=180)
    if result.returncode != 0:
        print_subprocess_failure(label, result, command)
    assert result.returncode == 0, f"R package probe failed: {label}"
    parsed = parse_probe(result)
    assert parsed.get("R_VERSION") == "3.6.2", (
        f"Unexpected R runtime during {label}: {parsed.get('R_VERSION')}"
    )
    return parsed, result


def package_state(parsed, pkg):
    key = pkg.upper()
    available = parsed.get(f"PKG_{key}_AVAILABLE") == "TRUE"
    semantic = parsed.get(f"PKG_{key}_SEMANTIC_MATCH") == "TRUE"
    path_text = parsed.get(f"PKG_{key}_PATH", "")

    inside = False
    if available and path_text:
        package_path = Path(path_text).resolve()
        env_root = AMPGRAM_ENV.resolve()
        try:
            inside = (
                Path(os.path.commonpath([str(package_path), str(env_root)]))
                == env_root
            )
        except ValueError:
            inside = False

    return {
        "available": available,
        "semantic_match": semantic,
        "version": parsed.get(f"PKG_{key}_VERSION", ""),
        "expected": parsed.get(
            f"PKG_{key}_EXPECTED",
            EXPECTED_VERSIONS[pkg],
        ),
        "path": path_text,
        "inside_locked_env": inside,
        "built": parsed.get(f"PKG_{key}_BUILT", ""),
    }


before_probe, before_probe_result = run_package_probe(
    "Cell 23 v5 pre-restoration probe"
)


# ============================================================
# 10. FOUNDATION PACKAGES MUST ALREADY MATCH
# ============================================================

FOUNDATION_PACKAGES = [
    "slam",
    "combinat",
    "entropy",
    "ranger",
]

foundation_before = {
    pkg: package_state(before_probe, pkg)
    for pkg in FOUNDATION_PACKAGES
}

bad_foundation = {
    pkg: state
    for pkg, state in foundation_before.items()
    if not (
        state["available"]
        and state["semantic_match"]
        and state["inside_locked_env"]
    )
}

if bad_foundation:
    print("=" * 128)
    print("CELL 23 FAIL - LOCKED FOUNDATION PACKAGE STATE CHANGED")
    for pkg, state in bad_foundation.items():
        print(
            f"{pkg:<12} expected={state['expected']:<10} "
            f"available={state['available']} "
            f"actual={state['version'] or '<NONE>'} "
            f"semantic_match={state['semantic_match']} "
            f"inside_locked_env={state['inside_locked_env']} "
            f"path={state['path'] or '<NONE>'}"
        )
    print("Cell 23 will not replace already-locked foundation packages.")
    print("=" * 128)

assert not bad_foundation, (
    "Locked foundation package state no longer matches the verified state."
)


# ============================================================
# 11. TOOLCHAIN DIAGNOSIS AND SAFE BUILD OVERRIDE
#
# v4 failed because the legacy conda linker could not parse
# .relr.dyn in the modern glibc/libm objects. We do not upgrade or
# delete that legacy toolchain. Instead, source builds get a local,
# auditable R_MAKEVARS_USER pointing to the host compiler/binutils.
# ============================================================

SYSTEM_GCC = shutil.which("gcc", path="/usr/bin:/bin:/usr/local/bin")
SYSTEM_GXX = shutil.which("g++", path="/usr/bin:/bin:/usr/local/bin")
SYSTEM_LD = shutil.which("ld", path="/usr/bin:/bin:/usr/local/bin")
SYSTEM_AR = shutil.which("ar", path="/usr/bin:/bin:/usr/local/bin")
SYSTEM_RANLIB = shutil.which("ranlib", path="/usr/bin:/bin:/usr/local/bin")
SYSTEM_NM = shutil.which("nm", path="/usr/bin:/bin:/usr/local/bin")
SYSTEM_STRIP = shutil.which("strip", path="/usr/bin:/bin:/usr/local/bin")

missing_build_tools = [
    name
    for name, value in {
        "gcc": SYSTEM_GCC,
        "g++": SYSTEM_GXX,
        "ld": SYSTEM_LD,
        "ar": SYSTEM_AR,
        "ranlib": SYSTEM_RANLIB,
        "nm": SYSTEM_NM,
        "strip": SYSTEM_STRIP,
    }.items()
    if value is None
]

if missing_build_tools:
    print("=" * 128)
    print("CELL 23 FAIL - HOST BUILD TOOLCHAIN INCOMPLETE")
    print("Missing:", missing_build_tools)
    print("No package installation attempted by v5.")
    print("=" * 128)

assert not missing_build_tools, (
    "A complete host GCC/binutils toolchain is required for the isolated build workaround."
)

SYSTEM_GCC = str(Path(SYSTEM_GCC).resolve())
SYSTEM_GXX = str(Path(SYSTEM_GXX).resolve())
SYSTEM_LD = str(Path(SYSTEM_LD).resolve())
SYSTEM_AR = str(Path(SYSTEM_AR).resolve())
SYSTEM_RANLIB = str(Path(SYSTEM_RANLIB).resolve())
SYSTEM_NM = str(Path(SYSTEM_NM).resolve())
SYSTEM_STRIP = str(Path(SYSTEM_STRIP).resolve())

TOOLCHAIN_VERSIONS = {
    "gcc": get_tool_version(SYSTEM_GCC),
    "g++": get_tool_version(SYSTEM_GXX),
    "ld": get_tool_version(SYSTEM_LD),
    "ar": get_tool_version(SYSTEM_AR),
}

MAKEVARS_PATH = AMPGRAM_WORK / "ampgram_cell23_v5_host_toolchain.Makevars"

MAKEVARS_TEXT = f'''# Cell 23 v5 - local build-only compiler override.
# Does not alter R/package/model semantics.
CC = {SYSTEM_GCC}
CXX = {SYSTEM_GXX}
CXX11 = {SYSTEM_GXX}
CXX14 = {SYSTEM_GXX}
CXX17 = {SYSTEM_GXX}
LD = {SYSTEM_LD}
AR = {SYSTEM_AR}
RANLIB = {SYSTEM_RANLIB}
NM = {SYSTEM_NM}
STRIP = {SYSTEM_STRIP}
SHLIB_LD = {SYSTEM_GCC}
SHLIB_CXXLD = {SYSTEM_GXX} -std=gnu++11
SHLIB_CXX11LD = {SYSTEM_GXX} -std=gnu++11
CXXSTD = -std=gnu++11
CXX11STD = -std=gnu++11
'''

MAKEVARS_ACTION = atomic_write_text(MAKEVARS_PATH, MAKEVARS_TEXT)

build_env = r_env.copy()
build_env["R_MAKEVARS_USER"] = str(MAKEVARS_PATH)
build_env["CC"] = SYSTEM_GCC
build_env["CXX"] = SYSTEM_GXX
build_env["CXX11"] = SYSTEM_GXX
build_env["CXX14"] = SYSTEM_GXX
build_env["CXX17"] = SYSTEM_GXX
build_env["LD"] = SYSTEM_LD
build_env["AR"] = SYSTEM_AR
build_env["RANLIB"] = SYSTEM_RANLIB
build_env["NM"] = SYSTEM_NM
build_env["STRIP"] = SYSTEM_STRIP


# ============================================================
# 12. R CMD SHLIB C/C++ LINKER PREFLIGHT
#
# This must pass BEFORE any package restoration. It directly tests
# R 3.6.2 + the temporary host compiler/linker path.
# ============================================================

with tempfile.TemporaryDirectory(
    prefix="ampgram_cell23_v5_shlib_",
    dir=str(AMPGRAM_WORK),
) as td:
    td = Path(td)

    c_src = td / "smoke_c.c"
    cpp_src = td / "smoke_cpp.cpp"

    c_src.write_text(
        "void ampgram23_c(void) {}\n",
        encoding="utf-8",
    )
    cpp_src.write_text(
        'extern "C" void ampgram23_cpp(void) {}\n',
        encoding="utf-8",
    )

    c_cmd = [R_BIN, "CMD", "SHLIB", c_src.name]
    c_res = run_cmd(c_cmd, cwd=td, env=build_env, timeout=300)
    if c_res.returncode != 0:
        print_subprocess_failure(
            "Cell 23 v5 R CMD SHLIB C toolchain preflight",
            c_res,
            c_cmd,
        )
    assert c_res.returncode == 0, (
        "Host-toolchain override cannot compile/link a C shared library against R 3.6.2."
    )
    assert (td / "smoke_c.so").is_file()

    cpp_cmd = [R_BIN, "CMD", "SHLIB", cpp_src.name]
    cpp_res = run_cmd(cpp_cmd, cwd=td, env=build_env, timeout=300)
    if cpp_res.returncode != 0:
        print_subprocess_failure(
            "Cell 23 v5 R CMD SHLIB C++ toolchain preflight",
            cpp_res,
            cpp_cmd,
        )
    assert cpp_res.returncode == 0, (
        "Host-toolchain override cannot compile/link a C++ shared library against R 3.6.2."
    )
    assert (td / "smoke_cpp.so").is_file()

TOOLCHAIN_PREFLIGHT = "PASS"


# ============================================================
# 13. RESTORE EXACT PACKAGE CLOSURE
# ============================================================

RESTORE_ORDER = [
    "gmp",
    "polynom",
    "sets",
    "partitions",
]

RESTORATION_ACTIONS = []
SOURCE_ACTIONS = [
    f"partitions: {partitions_source_action} @ {PINNED_CRAN_SOURCES['partitions']['commit']}"
]
STALE_LOCK_ACTIONS = []


def clear_stale_lock(pkg):
    candidates = [
        R_LIB / f"00LOCK-{pkg}",
    ]

    for lock_path in candidates:
        if not lock_path.exists():
            continue

        assert lock_path.is_dir(), (
            f"Unexpected non-directory R install lock: {lock_path}"
        )

        shutil.rmtree(lock_path)
        STALE_LOCK_ACTIONS.append(
            f"REMOVED STALE FAILED-INSTALL LOCK: {lock_path}"
        )


def install_r_package_from_source(pkg, source_dir):
    clear_stale_lock(pkg)

    command = [
        R_BIN,
        "CMD",
        "INSTALL",
        f"--library={R_LIB}",
        "--preclean",
        "--no-multiarch",
        "--with-keep.source",
        source_dir,
    ]

    result = run_cmd(
        command,
        env=build_env,
        timeout=1800,
    )

    if result.returncode != 0:
        print_subprocess_failure(
            f"R CMD INSTALL {pkg} using v5 host-toolchain override",
            result,
            command,
        )

    assert result.returncode == 0, (
        f"Exact source installation failed for {pkg} even after "
        "the R CMD SHLIB toolchain preflight passed."
    )

    return result


current_probe = before_probe

for pkg in RESTORE_ORDER:
    state = package_state(current_probe, pkg)

    if (
        state["available"]
        and state["semantic_match"]
        and state["inside_locked_env"]
    ):
        RESTORATION_ACTIONS.append(
            f"{pkg}: REUSED EXACT INSTALLED VERSION {state['version']}"
        )
        continue

    source_info = PINNED_CRAN_SOURCES[pkg]
    source_dest = (
        EXACT_CRAN_SOURCE_ROOT
        / f"{pkg}-{source_info['version']}"
    )

    exact_source, source_action = ensure_exact_git_source(
        source_info["repo"],
        source_info["commit"],
        source_dest,
    )

    if pkg != "partitions":
        SOURCE_ACTIONS.append(
            f"{pkg}: {source_action} @ {source_info['commit']}"
        )

    desc = exact_source / "DESCRIPTION"
    assert desc.is_file(), f"DESCRIPTION missing: {exact_source}"
    desc_text = desc.read_text(encoding="utf-8", errors="replace")
    assert re.search(
        rf"(?m)^Version:\s*{re.escape(source_info['version'])}\s*$",
        desc_text,
    ), f"Exact source DESCRIPTION version mismatch for {pkg}."

    # Prove tracked source content is untouched before build.
    diff_before = git(exact_source, "diff", "--exit-code")
    assert diff_before.returncode == 0, (
        f"Tracked exact source was modified before installation: {exact_source}"
    )

    install_r_package_from_source(pkg, exact_source)

    current_probe, _ = run_package_probe(
        f"Cell 23 v5 post-install probe: {pkg}"
    )
    new_state = package_state(current_probe, pkg)

    assert (
        new_state["available"]
        and new_state["semantic_match"]
        and new_state["inside_locked_env"]
    ), (
        f"Installed {pkg} did not satisfy exact runtime contract."
    )

    diff_after = git(exact_source, "diff", "--exit-code")
    assert diff_after.returncode == 0, (
        f"R installation modified tracked exact source: {exact_source}"
    )

    RESTORATION_ACTIONS.append(
        f"{pkg}: INSTALLED EXACT SOURCE VERSION {new_state['version']} "
        "USING AUDITED HOST BUILD TOOLCHAIN"
    )


# ============================================================
# 14. INSTALL / VERIFY EXACT BIOGRAM 1.6.3 SOURCE COMMIT
# ============================================================

biogram_state = package_state(current_probe, "biogram")

if not (
    biogram_state["available"]
    and biogram_state["semantic_match"]
    and biogram_state["inside_locked_env"]
):
    diff_before = git(BIOGRAM_SOURCE, "diff", "--exit-code")
    assert diff_before.returncode == 0, (
        "Tracked biogram source changed before installation."
    )

    install_r_package_from_source(
        "biogram",
        BIOGRAM_SOURCE,
    )

    diff_after = git(BIOGRAM_SOURCE, "diff", "--exit-code")
    assert diff_after.returncode == 0, (
        "R installation modified tracked biogram source."
    )

    RESTORATION_ACTIONS.append(
        "biogram: INSTALLED VERSION 1.6.3 FROM EXACT SOURCE COMMIT "
        f"{EXPECTED_BIOGRAM_COMMIT}"
    )
else:
    RESTORATION_ACTIONS.append(
        f"biogram: REUSED EXACT INSTALLED VERSION {biogram_state['version']}"
    )


# ============================================================
# 15. FINAL EXACT PACKAGE PROBE
# ============================================================

final_probe, final_probe_result = run_package_probe(
    "Cell 23 v5 final exact-package probe"
)

final_states = {
    pkg: package_state(final_probe, pkg)
    for pkg in EXPECTED_VERSIONS
}

bad_final = {
    pkg: state
    for pkg, state in final_states.items()
    if not (
        state["available"]
        and state["semantic_match"]
        and state["inside_locked_env"]
    )
}

if bad_final:
    print("=" * 128)
    print("CELL 23 FAIL - FINAL EXACT R PACKAGE CLOSURE INCOMPLETE")
    for pkg, state in bad_final.items():
        print(
            f"{pkg:<12} expected={state['expected']:<10} "
            f"available={state['available']} "
            f"actual={state['version'] or '<NONE>'} "
            f"semantic_match={state['semantic_match']} "
            f"inside_locked_env={state['inside_locked_env']} "
            f"path={state['path'] or '<NONE>'}"
        )
    print("=" * 128)

assert not bad_final, "Exact AmpGram R package closure is incomplete."


# ============================================================
# 16. OFFICIAL BIOGRAM / QUI-PT RUNTIME SMOKE TEST
#
# Synthetic package self-test only.
# NO benchmark sample, NO RF model fit.
# ============================================================

R_SMOKE_PATH = AMPGRAM_WORK / "ampgram_cell23_v5_official_biogram_smoke.R"

R_SMOKE = r'''
emit <- function(k, v) {
  cat("AMPGRAM23SMOKE\t", k, "\t", v, "\n", sep = "")
}

suppressPackageStartupMessages({
  library(biogram)
  library(ranger)
})

emit("R_VERSION", as.character(getRversion()))
emit("BIOGRAM_VERSION", as.character(packageVersion("biogram")))
emit("RANGER_VERSION", as.character(packageVersion("ranger")))
emit("PARTITIONS_VERSION", as.character(packageVersion("partitions")))

# Same synthetic construction used by the official biogram QuiPT test.
tar_feat1 <- create_feature_target(10, 390, 0, 600)
tar_feat2 <- create_feature_target(9, 391, 1, 599)
tar_feat3 <- create_feature_target(8, 392, 2, 598)

fast_results <- test_features(
  tar_feat1[, 1, drop = FALSE],
  cbind(
    tar_feat1[, 2],
    tar_feat2[, 2],
    tar_feat3[, 2]
  )
)

if (length(fast_results) != 3L) {
  stop("Official QuiPT smoke result does not contain three features")
}

fast_numeric <- as.numeric(fast_results)

if (!all(is.finite(fast_numeric))) {
  stop("Official QuiPT smoke result contains non-finite values")
}

if (!all(fast_numeric >= 0 & fast_numeric <= 1)) {
  stop("Official QuiPT smoke p-values are outside [0,1]")
}

emit("QUIPT_N_FEATURES", length(fast_numeric))
emit("QUIPT_PVALUES", paste(format(fast_numeric, digits = 17), collapse = ","))
emit("LIBRARY_BIOGRAM_LOAD", "TRUE")
emit("LIBRARY_RANGER_LOAD", "TRUE")
emit("SMOKE_PASS", "TRUE")
'''

SMOKE_ACTION = atomic_write_text(R_SMOKE_PATH, R_SMOKE)

smoke_command = [R_SCRIPT, "--vanilla", R_SMOKE_PATH]
smoke_result = run_cmd(
    smoke_command,
    env=r_env,
    timeout=600,
)

if smoke_result.returncode != 0:
    print_subprocess_failure(
        "Cell 23 v5 official biogram runtime smoke",
        smoke_result,
        smoke_command,
    )

assert smoke_result.returncode == 0, (
    "Official biogram 1.6.3 runtime smoke test failed."
)

smoke_parsed = {}
for line in smoke_result.stdout.splitlines():
    if line.startswith("AMPGRAM23SMOKE\t"):
        parts = line.split("\t", 2)
        assert len(parts) == 3
        smoke_parsed[parts[1]] = parts[2]

assert smoke_parsed.get("R_VERSION") == "3.6.2"
assert (
    smoke_parsed.get("BIOGRAM_VERSION", "").replace("-", ".")
    == "1.6.3"
)
assert (
    smoke_parsed.get("RANGER_VERSION", "").replace("-", ".")
    == "0.12.1"
)
assert (
    smoke_parsed.get("PARTITIONS_VERSION", "").replace("-", ".")
    == "1.9.22"
)
assert smoke_parsed.get("QUIPT_N_FEATURES") == "3"
assert smoke_parsed.get("LIBRARY_BIOGRAM_LOAD") == "TRUE"
assert smoke_parsed.get("LIBRARY_RANGER_LOAD") == "TRUE"
assert smoke_parsed.get("SMOKE_PASS") == "TRUE"


# ============================================================
# 17. BUILD AUDIT / CONTRACT
# ============================================================

BUILD_AUDIT_PATH = (
    AUDIT_DIR
    / "benchmark17_ampgram_cell23_v5_build_toolchain_audit.json"
)

build_audit = {
    "schema_version": "1.0",
    "purpose": "build-only toolchain compatibility audit",
    "selected_R": str(R_BIN),
    "selected_Rscript": str(R_SCRIPT),
    "selected_environment": str(AMPGRAM_ENV),
    "R_version": "3.6.2",
    "legacy_conda_toolchain_preserved": True,
    "legacy_conda_toolchain_upgraded": False,
    "legacy_conda_toolchain_deleted": False,
    "temporary_R_MAKEVARS_USER": str(MAKEVARS_PATH),
    "host_build_tools": {
        "gcc": SYSTEM_GCC,
        "g++": SYSTEM_GXX,
        "ld": SYSTEM_LD,
        "ar": SYSTEM_AR,
        "ranlib": SYSTEM_RANLIB,
        "nm": SYSTEM_NM,
        "strip": SYSTEM_STRIP,
    },
    "host_build_tool_versions": TOOLCHAIN_VERSIONS,
    "R_CMD_SHLIB_C_preflight": "PASS",
    "R_CMD_SHLIB_CPP_preflight": "PASS",
    "reason": (
        "legacy conda linker cannot parse modern .relr.dyn glibc/libm sections; "
        "host compiler/binutils are used only for package source compilation"
    ),
    "model_semantics_changed": False,
    "package_versions_changed_from_official_lock": False,
    "source_versions_changed_from_official_lock": False,
}

BUILD_AUDIT_ACTION = atomic_write_text(
    BUILD_AUDIT_PATH,
    json.dumps(build_audit, indent=2, ensure_ascii=False) + "\n",
)


CELL23_CONTRACT = {
    "schema_version": "1.0",
    "model_id": "ampgram",
    "stage": "exact_R_environment_restoration_and_runtime_smoke",
    "upstream_cell22_sha256": EXPECTED_CELL22_SHA256,
    "official_source": {
        "ampgram_commit": EXPECTED_AMPGRAM_COMMIT,
        "biogram_commit": EXPECTED_BIOGRAM_COMMIT,
        "renv_lock_sha256": sha256_file(RENV_PATH),
    },
    "runtime": {
        "R": "3.6.2",
        "Rscript": str(R_SCRIPT),
        "environment": str(AMPGRAM_ENV),
        "library": str(R_LIB),
    },
    "exact_package_versions": {
        pkg: final_states[pkg]["version"]
        for pkg in EXPECTED_VERSIONS
    },
    "exact_package_expected_versions": EXPECTED_VERSIONS,
    "build_toolchain": {
        "mode": "temporary_R_MAKEVARS_USER_host_toolchain_override",
        "preflight": TOOLCHAIN_PREFLIGHT,
        "audit_path": str(BUILD_AUDIT_PATH),
        "audit_sha256": sha256_file(BUILD_AUDIT_PATH),
        "makevars_path": str(MAKEVARS_PATH),
        "makevars_sha256": sha256_file(MAKEVARS_PATH),
        "legacy_conda_toolchain_mutated": False,
    },
    "restoration_actions": RESTORATION_ACTIONS,
    "source_actions": SOURCE_ACTIONS,
    "stale_lock_actions": STALE_LOCK_ACTIONS,
    "official_runtime_smoke": {
        "status": "PASS",
        "R": smoke_parsed["R_VERSION"],
        "biogram": smoke_parsed["BIOGRAM_VERSION"],
        "ranger": smoke_parsed["RANGER_VERSION"],
        "partitions": smoke_parsed["PARTITIONS_VERSION"],
        "QuiPT_features": int(smoke_parsed["QUIPT_N_FEATURES"]),
        "QuiPT_pvalues": smoke_parsed["QUIPT_PVALUES"],
    },
    "scientific_boundary": {
        "benchmark_feature_selection_performed": False,
        "rf1_fit": False,
        "rf2_fit": False,
        "benchmark_training_performed": False,
        "benchmark_test_used": False,
        "external_target_used": False,
        "training_gate_modified": False,
        "ampgram_implementation_validated": False,
        "full_adapter_selftest": "PENDING",
    },
}

CELL23_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_exact_R_environment_runtime_v5.json"
)

CONTRACT_ACTION = atomic_write_contract(
    CELL23_PATH,
    "AMPGRAM_EXACT_R_ENVIRONMENT_RUNTIME_READY",
    CELL23_CONTRACT,
)

check = load_json(CELL23_PATH)
assert check["status"] == "AMPGRAM_EXACT_R_ENVIRONMENT_RUNTIME_READY"
assert check["contract"] == CELL23_CONTRACT


# ============================================================
# 18. GLOBAL GATE MUST REMAIN BYTE-IDENTICAL
# ============================================================

assert sha256_file(TRAINING_GATE_PATH) == GATE_SHA_BEFORE, (
    "Cell 23 modified the global training gate - forbidden."
)


# ============================================================
# 19. FINAL REPORT
# ============================================================

print("=" * 128)
print(
    "CELL 23 PASS - AMPGRAM EXACT R-3.6.2 ENVIRONMENT + "
    "BIOGRAM-1.6.3 RUNTIME VERIFIED"
)
print("=" * 128)

print("AmpGram commit         :", EXPECTED_AMPGRAM_COMMIT)
print("biogram commit         :", EXPECTED_BIOGRAM_COMMIT)
print("R                      :", "3.6.2")
print("Rscript                :", R_SCRIPT)
print("Environment            :", AMPGRAM_ENV)

print("-" * 128)
print("BUILD TOOLCHAIN COMPATIBILITY")
print("Legacy conda toolchain : PRESERVED / NOT MODIFIED")
print("Host gcc               :", SYSTEM_GCC)
print("Host g++               :", SYSTEM_GXX)
print("Host ld                :", SYSTEM_LD)
print("gcc version            :", TOOLCHAIN_VERSIONS["gcc"])
print("ld version             :", TOOLCHAIN_VERSIONS["ld"])
print("R CMD SHLIB C          : PASS")
print("R CMD SHLIB C++        : PASS")
print("Build-only Makevars    :", MAKEVARS_PATH)

print("-" * 128)
print("EXACT PACKAGE STATE")
for pkg in EXPECTED_VERSIONS:
    state = final_states[pkg]
    print(
        f"{pkg:<12} expected={state['expected']:<10} "
        f"actual={state['version']:<10} "
        f"semantic_match={state['semantic_match']} "
        f"inside_env={state['inside_locked_env']}"
    )

print("-" * 128)
print("RESTORATION ACTIONS")
for action in RESTORATION_ACTIONS:
    print(" -", action)

if STALE_LOCK_ACTIONS:
    print("STALE LOCK CLEANUP")
    for action in STALE_LOCK_ACTIONS:
        print(" -", action)

print("-" * 128)
print("OFFICIAL BIOGRAM RUNTIME SMOKE")
print("library(biogram)       : PASS")
print("library(ranger)        : PASS")
print("QuiPT synthetic test   : PASS")
print("QuiPT features         :", smoke_parsed["QUIPT_N_FEATURES"])
print("QuiPT p-values         :", smoke_parsed["QUIPT_PVALUES"])

print("-" * 128)
print("SCIENTIFIC STATUS")
print("Benchmark feature select: FALSE")
print("RF1 fitted             : FALSE")
print("RF2 fitted             : FALSE")
print("Benchmark training     : FALSE")
print("Benchmark test used    : FALSE")
print("External target used   : FALSE")
print("AmpGram validated      : FALSE - FULL ADAPTER SELF-TEST STILL REQUIRED")
print("Training gate modified : FALSE")
print("TRAINING GATE          : CLOSED")

print("-" * 128)
print("Probe action           :", PROBE_ACTION)
print("Makevars action        :", MAKEVARS_ACTION)
print("Smoke action           :", SMOKE_ACTION)
print("Build audit action     :", BUILD_AUDIT_ACTION)
print("Contract action        :", CONTRACT_ACTION)
print("Cell 23 artifact       :", CELL23_PATH)
print("Artifact SHA256        :", sha256_file(CELL23_PATH))
print("=" * 128)

================================================================================================================================
CELL 23 PASS - AMPGRAM EXACT R-3.6.2 ENVIRONMENT + BIOGRAM-1.6.3 RUNTIME VERIFIED
================================================================================================================================
AmpGram commit         : 9a76d4c90a74622ec5ad9dc8b3d908799ac7745a
biogram commit         : 148d3d9b323998d759b967a30f13b2b445169a5e
R                      : 3.6.2
Rscript                : /home/pc/miniconda3/envs/genpept_ampgram_legacy/bin/Rscript
Environment            : /home/pc/miniconda3/envs/genpept_ampgram_legacy
--------------------------------------------------------------------------------------------------------------------------------
BUILD TOOLCHAIN COMPATIBILITY
Legacy conda toolchain : PRESERVED / NOT MODIFIED
Host gcc               : /usr/bin/x86_64-linux-gnu-gcc-13
Host g++               : /usr/bin/x86_64-linux-gnu-g++-13
Host ld                : /usr/bin/x86_64-linux-gnu-ld.bfd
gcc version            : x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0
ld version             : GNU ld (GNU Binutils for Ubuntu) 2.42
R CMD SHLIB C          : PASS
R CMD SHLIB C++        : PASS
Build-only Makevars    : /home/pc/genpept_benchmark17_work/published_selftests/ampgram/ampgram_cell23_v5_host_toolchain.Makevars
--------------------------------------------------------------------------------------------------------------------------------
EXACT PACKAGE STATE
slam         expected=0.1-47     actual=0.1.47     semantic_match=True inside_env=True
combinat     expected=0.0-8      actual=0.0.8      semantic_match=True inside_env=True
entropy      expected=1.2.1      actual=1.2.1      semantic_match=True inside_env=True
gmp          expected=0.5-13.6   actual=0.5.13.6   semantic_match=True inside_env=True
polynom      expected=1.4-0      actual=1.4.0      semantic_match=True inside_env=True
sets         expected=1.0-18     actual=1.0.18     semantic_match=True inside_env=True
partitions   expected=1.9-22     actual=1.9.22     semantic_match=True inside_env=True
biogram      expected=1.6.3      actual=1.6.3      semantic_match=True inside_env=True
ranger       expected=0.12.1     actual=0.12.1     semantic_match=True inside_env=True
--------------------------------------------------------------------------------------------------------------------------------
RESTORATION ACTIONS
 - gmp: REUSED EXACT INSTALLED VERSION 0.5.13.6
 - polynom: REUSED EXACT INSTALLED VERSION 1.4.0
 - sets: REUSED EXACT INSTALLED VERSION 1.0.18
 - partitions: INSTALLED EXACT SOURCE VERSION 1.9.22 USING AUDITED HOST BUILD TOOLCHAIN
 - biogram: INSTALLED VERSION 1.6.3 FROM EXACT SOURCE COMMIT 148d3d9b323998d759b967a30f13b2b445169a5e
--------------------------------------------------------------------------------------------------------------------------------
OFFICIAL BIOGRAM RUNTIME SMOKE
library(biogram)       : PASS
library(ranger)        : PASS
QuiPT synthetic test   : PASS
QuiPT features         : 3
QuiPT p-values         : 0.00029381707585762751,0.00240125950358832663,0.01780161072795394261
--------------------------------------------------------------------------------------------------------------------------------
SCIENTIFIC STATUS
Benchmark feature select: FALSE
RF1 fitted             : FALSE
RF2 fitted             : FALSE
Benchmark training     : FALSE
Benchmark test used    : FALSE
External target used   : FALSE
AmpGram validated      : FALSE - FULL ADAPTER SELF-TEST STILL REQUIRED
Training gate modified : FALSE
TRAINING GATE          : CLOSED
--------------------------------------------------------------------------------------------------------------------------------
Probe action           : NEW ATOMIC COMMIT
Makevars action        : NEW ATOMIC COMMIT
Smoke action           : NEW ATOMIC COMMIT
Build audit action     : NEW ATOMIC COMMIT
Contract action        : NEW CONTRACT ATOMICALLY COMMITTED
Cell 23 artifact       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampgram_FINAL_exact_R_environment_runtime_v5.json
Artifact SHA256        : 341463cd12faddbf24beecd4cd649b7702d8508c0b7e57dbf550799319d91ab8
================================================================================================================================

In [10]:
# ============================================================
# CELL 24 - RESTART-SAFE
# AMPGRAM FULL ADAPTER END-TO-END SELF-TEST
# + IMPLEMENTATION VALIDATION + GLOBAL GATE MERGE
#
# PURPOSE
# -------
# Validate the locked AmpGram implementation end-to-end BEFORE any
# benchmark training is allowed:
#
#   synthetic peptide sequence
#   -> source-faithful overlapping 10-mer extraction
#   -> exact biogram 1/2/3-multigram representation
#   -> exact biogram::test_features / QuiPT selection
#   -> exact ranger RF1 (2000 trees, probability=TRUE)
#   -> exact 14 peptide statistics
#   -> exact ranger RF2 (500 trees, probability=TRUE)
#   -> P(TRUE)
#
# SCIENTIFIC BOUNDARY
# -------------------
# - SYNTHETIC data only.
# - NO benchmark train / validation / test row is read.
# - NO external target is read.
# - NO benchmark model is trained.
# - The locked AmpGram helper sources are integrity-checked at the exact commit.
# - Core helper semantics are reimplemented literally with base R + exact
#   biogram/ranger. This is the route locked earlier as modern reimplementation.
# - dplyr/magrittr are intentionally NOT runtime requirements: Cell 23 did not
#   validate them, and they are only syntax/data-wrangling dependencies of the
#   historical helper wrappers, not of the locked mathematical/model recipe.
# - Exact R/biogram/ranger runtime must match Cell 23.
# - On complete PASS only, mark AmpGram implementation validated and
#   merge that state into the global published-method gate.
# - The global training gate remains CLOSED unless all 7 published
#   methods have validated self-test manifests.
# ============================================================

from pathlib import Path
from datetime import datetime
import copy
import hashlib
import json
import math
import os
import random
import re
import shutil
import subprocess
import tempfile

import numpy as np
import pandas as pd


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)
OUTPUT_ROOT = PROJECT_ROOT / "benchmark17_outputs"
AUDIT_DIR = OUTPUT_ROOT / "audit"
MANIFEST_DIR = OUTPUT_ROOT / "manifests"
WORK_ROOT = Path("/home/pc/genpept_benchmark17_work")
SOURCE_ROOT = Path("/home/pc/genpept_sources")
AMPGRAM_SOURCE = SOURCE_ROOT / "AmpGram-analysis"
SELFTEST_ROOT = WORK_ROOT / "published_selftests" / "ampgram"

CELL23_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_exact_R_environment_runtime_v5.json"
)
AMPGRAM_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_implementation_contract.json"
)
AMPGRAM_AMENDMENT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_source_recipe_amendment_v1.1.json"
)
TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)
READINESS_PATH = (
    AUDIT_DIR
    / "benchmark17_published_method_local_readiness_latest.csv"
)
FEATURE_REGISTRY_PATH = (
    AUDIT_DIR
    / "benchmark17_ampgram_33620_feature_registry.csv"
)
RENV_PATH = AMPGRAM_SOURCE / "renv.lock"

SELFTEST_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_adapter_selftest.json"
)
FINAL_BUNDLE_DIR = SELFTEST_ROOT / "cell24_final_adapter_selftest"

for path in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    WORK_ROOT,
    SOURCE_ROOT,
    AMPGRAM_SOURCE,
]:
    assert path.is_dir(), f"Required directory missing:\n{path}"

SELFTEST_ROOT.mkdir(parents=True, exist_ok=True)

for path in [
    CELL23_PATH,
    AMPGRAM_CONTRACT_PATH,
    AMPGRAM_AMENDMENT_PATH,
    TRAINING_GATE_PATH,
    READINESS_PATH,
    FEATURE_REGISTRY_PATH,
    RENV_PATH,
]:
    assert path.is_file(), f"Required upstream artifact missing:\n{path}"


# ============================================================
# 2. HELPERS
# ============================================================

def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def sha256_file(path, chunk_size=1024 * 1024):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def atomic_write_text(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=str(path.parent),
    )
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_path, path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def atomic_write_json(path, payload):
    text = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    atomic_write_text(path, text)


def atomic_write_csv(path, frame):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=str(path.parent),
    )
    os.close(fd)
    tmp_path = Path(tmp_name)
    try:
        frame.to_csv(tmp_path, index=False)
        os.replace(tmp_path, path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def run_cmd(command, cwd=None, env=None, timeout=1800):
    try:
        return subprocess.run(
            [str(x) for x in command],
            cwd=None if cwd is None else str(cwd),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout,
            check=False,
        )
    except Exception as exc:
        class FailedResult:
            returncode = -999
            stdout = ""
            stderr = repr(exc)
        return FailedResult()


def print_subprocess_failure(label, result, command=None):
    print("=" * 128)
    print(f"SUBPROCESS FAILURE - {label}")
    if command is not None:
        print("COMMAND:", [str(x) for x in command])
    print("RETURN CODE:", result.returncode)
    print("--- STDOUT ---")
    print(result.stdout or "<EMPTY>")
    print("--- STDERR ---")
    print(result.stderr or "<EMPTY>")
    print("=" * 128)


def normalize_git_remote(value):
    value = str(value).strip().removesuffix(".git")
    if value.startswith("git@github.com:"):
        value = "https://github.com/" + value[len("git@github.com:"):]
    if value.startswith("ssh://git@github.com/"):
        value = "https://github.com/" + value[len("ssh://git@github.com/"):]
    return value.rstrip("/")


def git(*args, timeout=120):
    return run_cmd(
        ["git", "-C", str(AMPGRAM_SOURCE), *[str(x) for x in args]],
        timeout=timeout,
    )


def parse_machine_output(text, prefix="AMPGRAM24"):
    parsed = {}
    marker = prefix + "\t"
    for line in text.splitlines():
        if not line.startswith(marker):
            continue
        parts = line.split("\t", 2)
        assert len(parts) == 3, f"Malformed machine output: {line}"
        key = parts[1]
        value = parts[2]
        assert key not in parsed, f"Duplicate machine output key: {key}"
        parsed[key] = value
    return parsed


def r_version_equal(rscript, env, package, expected):
    expr = (
        "actual <- as.character(packageVersion(\"%s\")); "
        "quit(status=ifelse(utils::compareVersion(actual, \"%s\") == 0, 0, 17))"
        % (package, expected)
    )
    result = run_cmd(
        [rscript, "--vanilla", "-e", expr],
        env=env,
        timeout=120,
    )
    return result.returncode == 0


def verify_artifact_entry(entry):
    path = Path(entry["path"])
    assert path.is_file(), f"Committed artifact missing: {path}"
    actual = sha256_file(path)
    assert actual == entry["sha256"], (
        f"Committed artifact hash mismatch:\n{path}\n"
        f"Expected: {entry['sha256']}\nActual  : {actual}"
    )


# ============================================================
# 3. VERIFY CELL 23 EXACTLY
# ============================================================

EXPECTED_CELL23_SHA256 = (
    "341463cd12faddbf24beecd4cd649b7702d8508c0b7e57dbf550799319d91ab8"
)

actual_cell23_sha = sha256_file(CELL23_PATH)
assert actual_cell23_sha == EXPECTED_CELL23_SHA256, (
    "Cell 23 artifact changed; do not continue.\n"
    f"Expected: {EXPECTED_CELL23_SHA256}\n"
    f"Actual  : {actual_cell23_sha}"
)

cell23 = load_json(CELL23_PATH)
assert cell23["status"] == "AMPGRAM_EXACT_R_ENVIRONMENT_RUNTIME_READY"
cell23_contract = cell23["contract"]
assert cell23_contract["model_id"] == "ampgram"
assert cell23_contract["stage"] == "exact_R_environment_restoration_and_runtime_smoke"
assert cell23_contract["official_source"]["ampgram_commit"] == (
    "9a76d4c90a74622ec5ad9dc8b3d908799ac7745a"
)
assert cell23_contract["official_source"]["biogram_commit"] == (
    "148d3d9b323998d759b967a30f13b2b445169a5e"
)
assert cell23_contract["runtime"]["R"] == "3.6.2"
assert cell23_contract["official_runtime_smoke"]["status"] == "PASS"
assert cell23_contract["scientific_boundary"]["benchmark_training_performed"] is False
assert cell23_contract["scientific_boundary"]["benchmark_test_used"] is False
assert cell23_contract["scientific_boundary"]["external_target_used"] is False
assert cell23_contract["scientific_boundary"]["full_adapter_selftest"] == "PENDING"

R_SCRIPT = Path(cell23_contract["runtime"]["Rscript"])
AMPGRAM_ENV = Path(cell23_contract["runtime"]["environment"])
R_LIB = Path(cell23_contract["runtime"]["library"])

for path in [R_SCRIPT, AMPGRAM_ENV, R_LIB]:
    assert path.exists(), f"Cell 23 runtime component missing:\n{path}"


# ============================================================
# 4. RUNTIME ENVIRONMENT - EXACTLY THE CLOSURE VERIFIED BY CELL 23
#
# IMPORTANT CONTINUITY RULE
# -------------------------
# Cell 24 MUST NOT invent a new package requirement that Cell 23 did not
# validate.  Therefore the source of truth for the runtime closure is the
# committed Cell-23 contract itself, not a fresh ad-hoc package list.
# ============================================================

r_env = os.environ.copy()
for key in [
    "R_HOME",
    "R_LIBS",
    "R_LIBS_USER",
    "R_ENVIRON",
    "R_ENVIRON_USER",
    "R_PROFILE",
    "R_PROFILE_USER",
    "R_MAKEVARS_USER",
]:
    r_env.pop(key, None)

r_env["PATH"] = str(AMPGRAM_ENV / "bin") + os.pathsep + r_env.get("PATH", "")
r_env["R_LIBS_USER"] = str(R_LIB)
r_env["R_LIBS_SITE"] = str(R_LIB)

renv = load_json(RENV_PATH)
assert renv["R"]["Version"] == "3.6.2"

CELL23_EXPECTED_PACKAGES = dict(
    cell23_contract["exact_package_expected_versions"]
)
CELL23_ACTUAL_PACKAGES = dict(
    cell23_contract["exact_package_versions"]
)

assert CELL23_EXPECTED_PACKAGES == {
    "slam": "0.1-47",
    "combinat": "0.0-8",
    "entropy": "1.2.1",
    "gmp": "0.5-13.6",
    "polynom": "1.4-0",
    "sets": "1.0-18",
    "partitions": "1.9-22",
    "biogram": "1.6.3",
    "ranger": "0.12.1",
}
assert set(CELL23_ACTUAL_PACKAGES) == set(CELL23_EXPECTED_PACKAGES)

# Re-verify only the exact package closure Cell 23 already committed.
for pkg, expected in CELL23_EXPECTED_PACKAGES.items():
    assert pkg in renv["Packages"], f"{pkg} missing from official renv.lock"
    assert str(renv["Packages"][pkg]["Version"]) == expected
    assert r_version_equal(R_SCRIPT, r_env, pkg, expected), (
        f"Cell-23 exact package state is no longer available for {pkg}; "
        f"expected {expected}."
    )

# Cell 24 directly calls only these packages; all are already in the
# Cell-23 verified closure.  No package installation/repair is permitted here.
DIRECT_RUNTIME_PACKAGES = ["slam", "biogram", "ranger"]
assert set(DIRECT_RUNTIME_PACKAGES).issubset(CELL23_EXPECTED_PACKAGES)

r_probe = run_cmd(
    [
        R_SCRIPT,
        "--vanilla",
        "-e",
        'cat(as.character(getRversion()), "\\n", sep="")',
    ],
    env=r_env,
    timeout=120,
)
if r_probe.returncode != 0:
    print_subprocess_failure("Cell 24 R 3.6.2 runtime probe", r_probe)
assert r_probe.returncode == 0
assert r_probe.stdout.strip() == "3.6.2"


# ============================================================
# 5. VERIFY LOCKED AMPGRAM CONTRACT + AMENDMENT
# ============================================================

ampgram_payload = load_json(AMPGRAM_CONTRACT_PATH)
ampgram_contract = ampgram_payload["contract"]
assert ampgram_contract["model_id"] == "ampgram"
assert ampgram_contract["implementation_route"] == (
    "faithful_source_recipe_modern_reimplementation"
)
assert ampgram_contract["official_source"]["commit"] == (
    "9a76d4c90a74622ec5ad9dc8b3d908799ac7745a"
)
assert ampgram_contract["sequence_processing"]["window_length"] == 10
assert ampgram_contract["sequence_processing"]["window_type"] == "overlapping"
assert ampgram_contract["mer_level_model"]["num_trees"] == 2000
assert ampgram_contract["peptide_statistics"]["count"] == 14
assert ampgram_contract["peptide_statistics"]["internal_mer_positive_cutoff"] == 0.5
assert ampgram_contract["peptide_level_model"]["num_trees"] == 500
assert ampgram_contract["native_probability"] == "P_TRUE_from_peptide_level_RF"
assert ampgram_contract["native_decision_threshold"] == 0.5
assert ampgram_contract["benchmark_training_started"] is False
assert ampgram_contract["adapter_self_test_status"] == "PENDING"

amendment_payload = load_json(AMPGRAM_AMENDMENT_PATH)
amendment = amendment_payload["contract_amendment"]
assert amendment["model_id"] == "ampgram"
assert amendment["exact_biogram_dependency"]["version"] == "1.6.3"
assert amendment["exact_biogram_dependency"]["remote_sha"] == (
    "148d3d9b323998d759b967a30f13b2b445169a5e"
)
assert amendment["feature_universe"]["total_features"] == 33620
assert amendment["feature_selection"]["criterion"] == "ig"
assert amendment["feature_selection"]["adjust"] == "BH"
assert amendment["feature_selection"]["occurrence_threshold"] == 1
assert amendment["feature_selection"]["quick_permutation_test"] is True
assert amendment["feature_selection"]["significance_cutoff"] == 0.05
assert amendment["feature_selection"]["scope"] == "source_train_only"
assert amendment["first_stage_mer_RF"]["training_length_groups"] == [
    "[11,19]",
    "(19,26]",
]
assert amendment["first_stage_mer_RF"]["num_trees"] == 2000
assert amendment["peptide_stage"]["statistics_count"] == 14
assert amendment["peptide_stage"]["num_trees"] == 500
assert amendment["peptide_stage"]["mer_internal_threshold"] == 0.5
assert amendment["benchmark_adaptation"]["original_fixed_seed"] == 990
assert amendment["benchmark_training_started"] is False
assert amendment["full_adapter_selftest"] == "PENDING"

assert sha256_file(FEATURE_REGISTRY_PATH) == (
    amendment["feature_universe"]["registry_sha256"]
)
feature_registry = pd.read_csv(FEATURE_REGISTRY_PATH, low_memory=False)
assert len(feature_registry) == 33620
assert "feature_name" in feature_registry.columns
assert feature_registry["feature_name"].is_unique
FEATURE_NAME_SET = set(feature_registry["feature_name"].astype(str))


# ============================================================
# 6. VERIFY OFFICIAL SOURCE CHECKOUT + RELEVANT FILE INTEGRITY
# ============================================================

head = git("rev-parse", "HEAD")
remote = git("remote", "get-url", "origin")
assert head.returncode == 0
assert remote.returncode == 0
assert head.stdout.strip() == "9a76d4c90a74622ec5ad9dc8b3d908799ac7745a"
assert normalize_git_remote(remote.stdout) == "https://github.com/michbur/AmpGram-analysis"

SOURCE_RELATIVE_FILES = [
    "functions/get_mers.R",
    "functions/count_ampgrams.R",
    "functions/benchmark_functions.R",
    "functions/train_model_peptides.R",
    "generate_benchmark_data.R",
    "renv.lock",
]

source_sha256 = {}
for rel in SOURCE_RELATIVE_FILES:
    working = AMPGRAM_SOURCE / rel
    assert working.is_file(), f"Official source file missing: {working}"
    diff = git("diff", "--quiet", "HEAD", "--", rel)
    assert diff.returncode == 0, f"Official source file modified relative to locked HEAD: {rel}"
    source_sha256[rel] = sha256_file(working)


# ============================================================
# 7. GLOBAL GATE PRECONDITION
# ============================================================

PUBLISHED_IDS = [
    "ampep",
    "ampscannerv2",
    "ampgram",
    "ampir",
    "ampeppy",
    "ai4amp",
    "amplify",
]

gate_before = load_json(TRAINING_GATE_PATH)
assert "ampir" in gate_before.get("validated_methods", [])

# Cell 24 may be rerun after its own successful commit. Before first success,
# AmpGram must not already be claimed validated by the gate.
if not SELFTEST_MANIFEST_PATH.exists():
    assert "ampgram" not in gate_before.get("validated_methods", []), (
        "Global gate claims ampgram validated but the AmpGram self-test manifest is absent."
    )
    assert gate_before["open"] is False
    assert gate_before["benchmark_training_allowed"] is False


# ============================================================
# 8. GATE / READINESS MERGE HELPERS
# ============================================================

def validated_methods_from_manifests():
    validated = []
    for model_id in PUBLISHED_IDS:
        path = MANIFEST_DIR / f"benchmark17_{model_id}_FINAL_adapter_selftest.json"
        if not path.is_file():
            continue
        payload = load_json(path)
        if payload.get("implementation_validated", False) is True:
            validated.append(model_id)
    return sorted(validated)


def merge_readiness_and_gate():
    readiness = pd.read_csv(READINESS_PATH, low_memory=False)
    required_cols = {
        "model_id",
        "adapter_self_test_passed",
        "implementation_validated",
        "local_state",
        "training_allowed",
    }
    assert required_cols.issubset(readiness.columns), (
        f"Readiness table missing columns: {sorted(required_cols - set(readiness.columns))}"
    )

    mask = readiness["model_id"].astype(str) == "ampgram"
    assert int(mask.sum()) == 1
    readiness.loc[mask, "adapter_self_test_passed"] = True
    readiness.loc[mask, "implementation_validated"] = True
    readiness.loc[mask, "local_state"] = "IMPLEMENTATION_VALIDATED"

    validated = validated_methods_from_manifests()
    assert "ampgram" in validated
    assert "ampir" in validated
    assert 2 <= len(validated) <= 7

    gate = load_json(TRAINING_GATE_PATH)
    gate["published_methods_implementation_validated"] = len(validated)
    gate["validated_methods"] = validated

    if len(validated) == 7:
        gate["open"] = True
        gate["benchmark_training_allowed"] = True
        gate["reason"] = "All seven published-method implementations validated."
        readiness.loc[:, "training_allowed"] = True
    else:
        gate["open"] = False
        gate["benchmark_training_allowed"] = False
        gate["reason"] = f"{len(validated)}/7 published-method implementations validated."
        readiness.loc[mask, "training_allowed"] = False

    gate["updated_at"] = datetime.now().astimezone().isoformat()

    atomic_write_csv(READINESS_PATH, readiness)
    atomic_write_json(TRAINING_GATE_PATH, gate)

    gate_check = load_json(TRAINING_GATE_PATH)
    readiness_check = pd.read_csv(READINESS_PATH, low_memory=False)
    mask_check = readiness_check["model_id"].astype(str) == "ampgram"

    assert int(mask_check.sum()) == 1
    assert bool(readiness_check.loc[mask_check, "adapter_self_test_passed"].iloc[0]) is True
    assert bool(readiness_check.loc[mask_check, "implementation_validated"].iloc[0]) is True
    assert str(readiness_check.loc[mask_check, "local_state"].iloc[0]) == "IMPLEMENTATION_VALIDATED"
    assert gate_check["validated_methods"] == validated
    assert gate_check["published_methods_implementation_validated"] == len(validated)

    if len(validated) < 7:
        assert gate_check["open"] is False
        assert gate_check["benchmark_training_allowed"] is False
    else:
        assert gate_check["open"] is True
        assert gate_check["benchmark_training_allowed"] is True

    return validated, gate_check


# ============================================================
# 9. IDEMPOTENT COMPLETED-RUN REUSE
# ============================================================

def validate_existing_manifest_and_reuse():
    payload = load_json(SELFTEST_MANIFEST_PATH)
    assert payload["status"] == "IMPLEMENTATION_VALIDATED"
    assert payload["implementation_validated"] is True
    assert payload["model_id"] == "ampgram"
    assert payload["benchmark_training_performed"] is False
    assert payload["benchmark_test_used"] is False
    assert payload["external_target_used"] is False
    assert payload["upstream"]["cell23_sha256"] == EXPECTED_CELL23_SHA256
    assert payload["source"]["ampgram_commit"] == (
        "9a76d4c90a74622ec5ad9dc8b3d908799ac7745a"
    )
    assert payload["source"]["biogram_commit"] == (
        "148d3d9b323998d759b967a30f13b2b445169a5e"
    )

    artifacts = payload["artifacts"]
    for key in [
        "synthetic_train",
        "synthetic_validation",
        "r_adapter_script",
        "selected_features",
        "statistics_oracle",
        "model",
        "predictions",
    ]:
        verify_artifact_entry(artifacts[key])

    validated, gate_check = merge_readiness_and_gate()

    print("=" * 128)
    print("CELL 24 PASS - AMPGRAM FULL ADAPTER END-TO-END SELF-TEST REUSED AND VERIFIED")
    print("=" * 128)
    print("Implementation status  : VALIDATED")
    print("Run action             : EXISTING IMMUTABLE SELF-TEST VERIFIED")
    print("Published validated    : %d/7" % len(validated))
    print("Validated methods      :", validated)
    print("TRAINING GATE          :", "OPEN" if gate_check["open"] else "CLOSED")
    print("Self-test manifest     :", SELFTEST_MANIFEST_PATH)
    print("Manifest SHA256        :", sha256_file(SELFTEST_MANIFEST_PATH))
    print("=" * 128)


if SELFTEST_MANIFEST_PATH.exists():
    validate_existing_manifest_and_reuse()
else:
    # ============================================================
    # 10. FIRST-RUN FINAL-PATH PRECONDITION
    # ============================================================
    assert not FINAL_BUNDLE_DIR.exists(), (
        "Final Cell 24 bundle exists without a committed self-test manifest.\n"
        "Refusing silent reuse/overwrite. Inspect this path first:\n"
        f"{FINAL_BUNDLE_DIR}"
    )

    # ============================================================
    # 11. BUILD DETERMINISTIC SYNTHETIC PEPTIDES
    #
    # The positive and negative alphabets are intentionally disjoint so
    # the feature-selection mechanics receive a strong, deterministic
    # signal. This is NOT a performance experiment.
    # ============================================================

    rng = random.Random(240990)
    POS_ALPHABET = "KLRW"
    NEG_ALPHABET = "DEGN"
    CANONICAL_AA = set("ARNDCEQGHILKMFPSTWYV")

    def unique_random_sequences(prefix, alphabet, label, length, n, used):
        rows = []
        attempts = 0
        while len(rows) < n:
            attempts += 1
            assert attempts < 100000
            seq = "".join(rng.choice(alphabet) for _ in range(length))
            if seq in used:
                continue
            used.add(seq)
            rows.append(
                {
                    "sample_id": f"{prefix}_{length}_{len(rows)+1:03d}",
                    "sequence": seq,
                    "label": int(label),
                    "length": int(length),
                }
            )
        return rows

    used_sequences = set()
    train_rows = []
    validation_rows = []

    # Synthetic source-train mechanics exercise BOTH locked scopes:
    # - RF1 feature selection / fit uses only lengths 11..26 (15 and 24 here).
    # - RF2 peptide fit receives all eligible synthetic train lengths,
    #   including length 10 and >26 after they are scored by RF1.
    for label, alphabet, tag in [
        (0, NEG_ALPHABET, "NEG"),
        (1, POS_ALPHABET, "AMP"),
    ]:
        for length, n_seq in [(10, 6), (15, 12), (24, 12), (30, 6)]:
            train_rows.extend(
                unique_random_sequences(
                    f"TR_{tag}", alphabet, label, length, n_seq, used_sequences
                )
            )

    # Validation is synthetic and is never used in feature selection or fit.
    # It includes length 10 to explicitly exercise the locked one-10-mer rule,
    # plus lengths inside and outside the RF1 fit range.
    for label, alphabet, tag in [
        (0, NEG_ALPHABET, "NEG"),
        (1, POS_ALPHABET, "AMP"),
    ]:
        for length in [10, 15, 24, 30]:
            validation_rows.extend(
                unique_random_sequences(
                    f"VA_{tag}", alphabet, label, length, 3, used_sequences
                )
            )

    train_df = pd.DataFrame(train_rows).sort_values("sample_id").reset_index(drop=True)
    validation_df = pd.DataFrame(validation_rows).sort_values("sample_id").reset_index(drop=True)

    assert len(train_df) == 72
    assert len(validation_df) == 24
    assert train_df["label"].value_counts().sort_index().to_dict() == {0: 36, 1: 36}
    assert validation_df["label"].value_counts().sort_index().to_dict() == {0: 12, 1: 12}
    assert set(train_df["length"].unique()) == {10, 15, 24, 30}
    assert set(validation_df["length"].unique()) == {10, 15, 24, 30}
    assert train_df["sample_id"].is_unique
    assert validation_df["sample_id"].is_unique
    assert set(train_df["sample_id"]).isdisjoint(set(validation_df["sample_id"]))
    assert set(train_df["sequence"]).isdisjoint(set(validation_df["sequence"]))
    assert train_df["sequence"].is_unique
    assert validation_df["sequence"].is_unique
    assert all(len(s) == n for s, n in zip(train_df["sequence"], train_df["length"]))
    assert all(len(s) == n for s, n in zip(validation_df["sequence"], validation_df["length"]))
    assert all(set(s).issubset(CANONICAL_AA) for s in train_df["sequence"])
    assert all(set(s).issubset(CANONICAL_AA) for s in validation_df["sequence"])

    # ============================================================
    # 12. STAGING BUNDLE
    # ============================================================

    staging_dir = Path(
        tempfile.mkdtemp(
            prefix=".cell24_ampgram_staging_",
            dir=str(SELFTEST_ROOT),
        )
    )

    try:
        TRAIN_PATH = staging_dir / "ampgram_selftest_synthetic_train.csv"
        VALIDATION_PATH = staging_dir / "ampgram_selftest_synthetic_validation.csv"
        R_ADAPTER_PATH = staging_dir / "ampgram_full_adapter_selftest.R"
        SELECTED_FEATURES_PATH = staging_dir / "ampgram_selftest_selected_features.csv"
        ORACLE_PATH = staging_dir / "ampgram_selftest_statistics_oracle.csv"
        MODEL_PATH = staging_dir / "ampgram_selftest_model.rds"
        PREDICTIONS_PATH = staging_dir / "ampgram_selftest_validation_predictions.csv"

        train_df.to_csv(TRAIN_PATH, index=False)
        validation_df.to_csv(VALIDATION_PATH, index=False)

        # ========================================================
        # 13. EXACT R SOURCE-RECIPE ADAPTER
        # ========================================================

        R_ADAPTER = r'''args <- commandArgs(trailingOnly = TRUE)
stopifnot(length(args) == 8L)

ampgram_source <- args[1]
train_path <- args[2]
validation_path <- args[3]
model_path <- args[4]
prediction_path <- args[5]
selected_features_path <- args[6]
oracle_path <- args[7]
feature_registry_path <- args[8]

emit <- function(k, v) {
  cat("AMPGRAM24\t", k, "\t", v, "\n", sep = "")
}

suppressPackageStartupMessages({
  library(slam)
  library(biogram)
  library(ranger)
})

stopifnot(as.character(getRversion()) == "3.6.2")
stopifnot(utils::compareVersion(as.character(packageVersion("slam")), "0.1-47") == 0)
stopifnot(utils::compareVersion(as.character(packageVersion("biogram")), "1.6.3") == 0)
stopifnot(utils::compareVersion(as.character(packageVersion("ranger")), "0.12.1") == 0)

# ------------------------------------------------------------------
# LOCKED CORE RECIPE
# ------------------------------------------------------------------
# Historical helper files use dplyr/magrittr for piping, filtering,
# grouping and mutation.  The benchmark route locked before results is a
# faithful modern reimplementation, so Cell 24 reproduces those helper
# semantics literally with base R while executing the exact biogram 1.6.3
# and ranger 0.12.1 algorithms already validated by Cell 23.
# ------------------------------------------------------------------

AA20 <- strsplit("ARNDCEQGHILKMFPSTWYV", "", fixed = TRUE)[[1]]
stopifnot(length(AA20) == 20L)
stopifnot(length(unique(AA20)) == 20L)

STAT_NAMES <- c(
  "fraction_true",
  "pred_mean",
  "pred_median",
  "n_peptide",
  "n_pos",
  "pred_min",
  "pred_max",
  "longest_pos",
  "n_pos_10",
  "frac_0_0.2",
  "frac_0.2_0.4",
  "frac_0.4_0.6",
  "frac_0.6_0.8",
  "frac_0.8_1"
)
stopifnot(length(STAT_NAMES) == 14L)

make_mer_df_reimpl <- function(input_df, training_mode = FALSE) {
  pieces <- lapply(seq_len(nrow(input_df)), function(i) {
    chars <- strsplit(input_df$sequence[i], "", fixed = TRUE)[[1]]
    n_mers <- length(chars) - 9L
    stopifnot(n_mers >= 1L)

    mer_matrix <- t(vapply(
      seq_len(n_mers),
      function(start) chars[start:(start + 9L)],
      character(10L)
    ))
    colnames(mer_matrix) <- paste0("X", seq_len(10L))

    group_value <- NA_character_
    if (training_mode) {
      if (input_df$length[i] >= 11L && input_df$length[i] <= 19L) {
        group_value <- "[11,19]"
      } else if (input_df$length[i] > 19L && input_df$length[i] <= 26L) {
        group_value <- "(19,26]"
      }
    }

    data.frame(
      mer_matrix,
      source_peptide = rep(input_df$sample_id[i], n_mers),
      mer_id = paste0(input_df$sample_id[i], "m", seq_len(n_mers)),
      target = rep(as.logical(input_df$label[i] == 1L), n_mers),
      peptide_length = rep(as.integer(input_df$length[i]), n_mers),
      group = rep(group_value, n_mers),
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  })

  out <- do.call(rbind, pieces)
  rownames(out) <- NULL
  out
}

count_ampgrams_reimpl <- function(mer_df, ns, ds) {
  seq_matrix <- as.matrix(mer_df[, grep("^X", colnames(mer_df)), drop = FALSE])
  counted <- biogram::count_multigrams(
    ns = ns,
    ds = ds,
    seq = seq_matrix,
    u = AA20
  )
  biogram::binarize(counted)
}

calc_imp_bigrams_reimpl <- function(
  train_mer_df,
  train_binary_ngrams,
  train_groups,
  cutoff = 0.05
) {
  keep <- train_mer_df$group %in% train_groups
  stopifnot(any(keep))
  stopifnot(length(unique(train_mer_df$target[keep])) == 2L)

  test_bis <- biogram::test_features(
    target = train_mer_df$target[keep],
    features = train_binary_ngrams[keep, , drop = FALSE],
    criterion = "ig",
    adjust = "BH",
    threshold = 1,
    quick = TRUE,
    times = 1e5
  )

  cut(test_bis, breaks = c(0, cutoff, 1))[[1]]
}

train_model_mers_reimpl <- function(
  train_mer_df,
  train_groups,
  train_binary_ngrams,
  imp_bigrams
) {
  keep <- train_mer_df$group %in% train_groups
  train_dat <- train_mer_df[keep, , drop = FALSE]
  ranger_train_data <- data.frame(
    as.matrix(train_binary_ngrams[keep, imp_bigrams, drop = FALSE]),
    tar = as.factor(train_dat$target)
  )

  ranger::ranger(
    dependent.variable.name = "tar",
    data = ranger_train_data,
    write.forest = TRUE,
    probability = TRUE,
    num.trees = 2000,
    verbose = FALSE,
    seed = 990
  )
}

count_imp_ampgrams_reimpl <- function(mer_df, imp_ampgrams) {
  seq_matrix <- as.matrix(mer_df[, grep("^X", colnames(mer_df)), drop = FALSE])
  biogram::binarize(
    biogram::count_specified(seq_matrix, imp_ampgrams)
  )
}

count_longest_reimpl <- function(x) {
  splitted_x <- strsplit(
    x = paste0(as.numeric(x > 0.5), collapse = ""),
    split = "0"
  )[[1]]
  len <- unname(sapply(splitted_x, nchar))
  if (length(len[len > 0]) == 0) {
    0
  } else {
    len[len > 0]
  }
}

calculate_statistics_reimpl <- function(pred_mers) {
  ids <- unique(as.character(pred_mers$source_peptide))

  rows <- lapply(ids, function(id) {
    dat <- pred_mers[pred_mers$source_peptide == id, , drop = FALSE]
    stopifnot(nrow(dat) >= 1L)
    stopifnot(length(unique(dat$target)) == 1L)

    pred <- as.numeric(dat$pred)
    runs <- count_longest_reimpl(pred)
    n_pred <- length(pred)

    data.frame(
      source_peptide = id,
      target = as.logical(dat$target[1]),
      fraction_true = mean(pred > 0.5),
      pred_mean = mean(pred),
      pred_median = median(pred),
      n_peptide = n_pred,
      n_pos = sum(pred > 0.5),
      pred_min = min(pred),
      pred_max = max(pred),
      longest_pos = max(runs),
      n_pos_10 = sum(runs >= 10),
      frac_0_0.2 = sum(pred <= 0.2) / n_pred,
      frac_0.2_0.4 = sum(pred > 0.2 & pred <= 0.4) / n_pred,
      frac_0.4_0.6 = sum(pred > 0.4 & pred <= 0.6) / n_pred,
      frac_0.6_0.8 = sum(pred > 0.6 & pred <= 0.8) / n_pred,
      frac_0.8_1 = sum(pred > 0.8 & pred <= 1) / n_pred,
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  })

  out <- do.call(rbind, rows)
  rownames(out) <- NULL
  out$target <- factor(out$target)
  out
}

train_model_peptides_reimpl <- function(mer_statistics) {
  train_dat <- mer_statistics[, c("target", STAT_NAMES), drop = FALSE]
  ranger::ranger(
    dependent.variable.name = "target",
    data = train_dat,
    write.forest = TRUE,
    probability = TRUE,
    num.trees = 500,
    verbose = FALSE,
    classification = TRUE,
    seed = 990
  )
}

# ------------------------------------------------------------------
# INPUTS - SYNTHETIC ONLY
# ------------------------------------------------------------------
train_df <- read.csv(train_path, stringsAsFactors = FALSE, check.names = FALSE)
validation_df <- read.csv(validation_path, stringsAsFactors = FALSE, check.names = FALSE)
registry_df <- read.csv(feature_registry_path, stringsAsFactors = FALSE, check.names = FALSE)

required_input_columns <- c("sample_id", "sequence", "label", "length")
stopifnot(all(required_input_columns %in% colnames(train_df)))
stopifnot(all(required_input_columns %in% colnames(validation_df)))
stopifnot(nrow(train_df) == 72L)
stopifnot(nrow(validation_df) == 24L)
stopifnot(identical(sort(unique(train_df$length)), c(10L, 15L, 24L, 30L)))
stopifnot(identical(sort(unique(validation_df$length)), c(10L, 15L, 24L, 30L)))
stopifnot(all(train_df$label %in% c(0L, 1L)))
stopifnot(all(validation_df$label %in% c(0L, 1L)))
train_label_table <- table(train_df$label)
validation_label_table <- table(validation_df$label)
stopifnot(identical(names(train_label_table), c("0", "1")))
stopifnot(identical(as.integer(train_label_table), c(36L, 36L)))
stopifnot(identical(names(validation_label_table), c("0", "1")))
stopifnot(identical(as.integer(validation_label_table), c(12L, 12L)))
stopifnot(nrow(registry_df) == 33620L)
stopifnot("feature_name" %in% colnames(registry_df))
stopifnot(length(unique(registry_df$feature_name)) == 33620L)

# ------------------------------------------------------------------
# 10-MER EXTRACTION ORACLE
# Verify the base-R reimplementation against exact biogram::seq2ngrams
# on a deterministic sequence before any model fit.
# ------------------------------------------------------------------
oracle_sequence <- "ACDEFGHIKLMN"
oracle_chars <- strsplit(oracle_sequence, "", fixed = TRUE)[[1]]
official_encoded <- biogram::seq2ngrams(oracle_chars, 10L, AA20)
official_decoded <- as.character(
  unname(biogram::decode_ngrams(as.vector(official_encoded)))
)
base_decoded <- vapply(
  seq_len(length(oracle_chars) - 9L),
  function(start) paste0(oracle_chars[start:(start + 9L)], collapse = ""),
  character(1L)
)
stopifnot(identical(official_decoded, base_decoded))

train_mer_df <- make_mer_df_reimpl(train_df, training_mode = TRUE)
validation_mer_df <- make_mer_df_reimpl(validation_df, training_mode = FALSE)

train_mer_counts <- table(train_mer_df$source_peptide)
validation_mer_counts <- table(validation_mer_df$source_peptide)
train_expected <- setNames(train_df$length - 9L, train_df$sample_id)
validation_expected <- setNames(validation_df$length - 9L, validation_df$sample_id)

stopifnot(all(as.integer(train_mer_counts[names(train_expected)]) == as.integer(train_expected)))
stopifnot(all(as.integer(validation_mer_counts[names(validation_expected)]) == as.integer(validation_expected)))
stopifnot(all(as.integer(train_mer_counts[train_df$sample_id[train_df$length == 10L]]) == 1L))
stopifnot(all(as.integer(validation_mer_counts[validation_df$sample_id[validation_df$length == 10L]]) == 1L))

rf1_fit_rows <- !is.na(train_mer_df$group)
stopifnot(any(rf1_fit_rows))
stopifnot(setequal(unique(train_mer_df$group[rf1_fit_rows]), c("[11,19]", "(19,26]")))
stopifnot(all(train_mer_df$peptide_length[rf1_fit_rows] >= 11L))
stopifnot(all(train_mer_df$peptide_length[rf1_fit_rows] <= 26L))
stopifnot(all(is.na(train_mer_df$group[train_mer_df$peptide_length %in% c(10L, 30L)])))

# ------------------------------------------------------------------
# EXACT BIOGRAM MULTIGRAM UNIVERSE
# ------------------------------------------------------------------
ngrams12 <- count_ampgrams_reimpl(
  train_mer_df,
  ns = c(1, rep(2, 4)),
  ds = list(0, 0, 1, 2, 3)
)
ngrams3_1 <- count_ampgrams_reimpl(
  train_mer_df,
  ns = c(3, 3),
  ds = list(c(0, 0), c(0, 1))
)
ngrams3_2 <- count_ampgrams_reimpl(
  train_mer_df,
  ns = c(3, 3),
  ds = list(c(1, 0), c(1, 1))
)
train_binary_ngrams <- cbind(ngrams12, ngrams3_1, ngrams3_2)

stopifnot(inherits(train_binary_ngrams, "simple_triplet_matrix"))
stopifnot(nrow(train_binary_ngrams) == nrow(train_mer_df))
stopifnot(ncol(train_binary_ngrams) == 33620L)
stopifnot(length(unique(colnames(train_binary_ngrams))) == 33620L)
stopifnot(setequal(colnames(train_binary_ngrams), registry_df$feature_name))
if (length(train_binary_ngrams$v) > 0L) {
  stopifnot(all(train_binary_ngrams$v == 1))
}

# ------------------------------------------------------------------
# SOURCE-TRAIN-ONLY EXACT QuiPT FEATURE SELECTION
# ------------------------------------------------------------------
imp_features <- calc_imp_bigrams_reimpl(
  train_mer_df,
  train_binary_ngrams,
  c("[11,19]", "(19,26]"),
  0.05
)

stopifnot(is.character(imp_features))
stopifnot(length(imp_features) >= 2L)
stopifnot(length(unique(imp_features)) == length(imp_features))
stopifnot(all(imp_features %in% colnames(train_binary_ngrams)))
stopifnot(all(imp_features %in% registry_df$feature_name))

write.csv(
  data.frame(feature_name = imp_features, stringsAsFactors = FALSE),
  selected_features_path,
  row.names = FALSE
)

# ------------------------------------------------------------------
# RF1 - EXACT ranger 0.12.1 / 2000 trees / seed 990
# Fit only on the locked 11..26 source-train scope.
# ------------------------------------------------------------------
rf_mers <- train_model_mers_reimpl(
  train_mer_df,
  c("[11,19]", "(19,26]"),
  train_binary_ngrams,
  imp_features
)
stopifnot(inherits(rf_mers, "ranger"))
stopifnot(rf_mers$num.trees == 2000L)

# Score ALL eligible synthetic source-train peptides with the fitted RF1;
# this mirrors generate_benchmark_data.R before RF2 is fitted.
rf1_train_input <- data.frame(
  as.matrix(train_binary_ngrams[, imp_features, drop = FALSE])
)
rf1_train_prediction_matrix <- predict(rf_mers, rf1_train_input)[["predictions"]]
stopifnot(setequal(colnames(rf1_train_prediction_matrix), c("FALSE", "TRUE")))
rf1_train_p_true <- rf1_train_prediction_matrix[, "TRUE"]
stopifnot(length(rf1_train_p_true) == nrow(train_mer_df))
stopifnot(all(is.finite(rf1_train_p_true)))
stopifnot(all(rf1_train_p_true >= 0 & rf1_train_p_true <= 1))

train_mer_preds <- train_mer_df
train_mer_preds$pred <- rf1_train_p_true
train_stats <- calculate_statistics_reimpl(train_mer_preds)
stopifnot(identical(colnames(train_stats)[3:16], STAT_NAMES))
stopifnot(nrow(train_stats) == nrow(train_df))
stopifnot(setequal(as.character(train_stats$source_peptide), train_df$sample_id))

# ------------------------------------------------------------------
# EXACT 14-STATISTICS BOUNDARY ORACLE
# ------------------------------------------------------------------
oracle_mer <- data.frame(
  source_peptide = rep("oracle", 10L),
  target = rep(TRUE, 10L),
  pred = seq(0.1, 1.0, by = 0.1),
  stringsAsFactors = FALSE
)
oracle <- calculate_statistics_reimpl(oracle_mer)
stopifnot(nrow(oracle) == 1L)
stopifnot(identical(colnames(oracle)[3:16], STAT_NAMES))
stopifnot(abs(oracle$fraction_true[1] - 0.5) < 1e-12)
stopifnot(abs(oracle$pred_mean[1] - 0.55) < 1e-12)
stopifnot(abs(oracle$pred_median[1] - 0.55) < 1e-12)
stopifnot(oracle$n_peptide[1] == 10L)
stopifnot(oracle$n_pos[1] == 5L)
stopifnot(abs(oracle$pred_min[1] - 0.1) < 1e-12)
stopifnot(abs(oracle$pred_max[1] - 1.0) < 1e-12)
stopifnot(oracle$longest_pos[1] == 5L)
stopifnot(oracle$n_pos_10[1] == 0L)
stopifnot(abs(oracle$frac_0_0.2[1] - 0.2) < 1e-12)
stopifnot(abs(oracle$frac_0.2_0.4[1] - 0.2) < 1e-12)
stopifnot(abs(oracle$frac_0.4_0.6[1] - 0.2) < 1e-12)
stopifnot(abs(oracle$frac_0.6_0.8[1] - 0.2) < 1e-12)
stopifnot(abs(oracle$frac_0.8_1[1] - 0.2) < 1e-12)
write.csv(oracle, oracle_path, row.names = FALSE)

# ------------------------------------------------------------------
# RF2 - EXACT ranger 0.12.1 / 500 trees / seed 990
# Fit on all eligible synthetic source-train peptide statistics.
# ------------------------------------------------------------------
rf_peptides <- train_model_peptides_reimpl(train_stats)
stopifnot(inherits(rf_peptides, "ranger"))
stopifnot(rf_peptides$num.trees == 500L)

AmpGram_model <- list(
  "rf_mers" = rf_mers,
  "rf_peptides" = rf_peptides,
  "imp_features" = imp_features
)
class(AmpGram_model) <- "ag_model"
saveRDS(AmpGram_model, model_path)
stopifnot(file.exists(model_path))

# ------------------------------------------------------------------
# FULL SYNTHETIC VALIDATION INFERENCE - NO REFIT / NO FEATURE SELECTION
# ------------------------------------------------------------------
validation_ngrams <- count_imp_ampgrams_reimpl(validation_mer_df, imp_features)
stopifnot(nrow(validation_ngrams) == nrow(validation_mer_df))
stopifnot(ncol(validation_ngrams) == length(imp_features))

rf1_validation_prediction_matrix <- predict(
  rf_mers,
  data.frame(as.matrix(validation_ngrams))
)[["predictions"]]
stopifnot(setequal(colnames(rf1_validation_prediction_matrix), c("FALSE", "TRUE")))
rf1_validation_p_true <- rf1_validation_prediction_matrix[, "TRUE"]
stopifnot(all(is.finite(rf1_validation_p_true)))
stopifnot(all(rf1_validation_p_true >= 0 & rf1_validation_p_true <= 1))

validation_mer_preds <- validation_mer_df
validation_mer_preds$pred <- rf1_validation_p_true
validation_stats <- calculate_statistics_reimpl(validation_mer_preds)
stopifnot(identical(colnames(validation_stats)[3:16], STAT_NAMES))
stopifnot(nrow(validation_stats) == nrow(validation_df))
stopifnot(setequal(as.character(validation_stats$source_peptide), validation_df$sample_id))

rf2_validation_prediction_matrix <- predict(
  rf_peptides,
  data.frame(validation_stats[, STAT_NAMES, drop = FALSE])
)[["predictions"]]
stopifnot(setequal(colnames(rf2_validation_prediction_matrix), c("FALSE", "TRUE")))
probability <- rf2_validation_prediction_matrix[, "TRUE"]
stopifnot(length(probability) == nrow(validation_df))
stopifnot(all(is.finite(probability)))
stopifnot(all(probability >= 0 & probability <= 1))

decision <- probability >= 0.5
length_lookup <- setNames(validation_df$length, validation_df$sample_id)
sequence_lookup <- setNames(validation_df$sequence, validation_df$sample_id)
label_lookup <- setNames(validation_df$label, validation_df$sample_id)

prediction_df <- data.frame(
  sample_id = as.character(validation_stats$source_peptide),
  sequence = unname(sequence_lookup[as.character(validation_stats$source_peptide)]),
  sequence_length = as.integer(unname(length_lookup[as.character(validation_stats$source_peptide)])),
  true_label = as.integer(unname(label_lookup[as.character(validation_stats$source_peptide)])),
  n_10mers = as.integer(validation_stats$n_peptide),
  ampgram_probability_TRUE = as.numeric(probability),
  ampgram_decision_threshold_0.5 = as.logical(decision),
  stringsAsFactors = FALSE
)

stopifnot(nrow(prediction_df) == nrow(validation_df))
stopifnot(all(!is.na(prediction_df$sequence)))
stopifnot(all(!is.na(prediction_df$true_label)))
stopifnot(all(prediction_df$n_10mers == prediction_df$sequence_length - 9L))
stopifnot(all(prediction_df$n_10mers[prediction_df$sequence_length == 10L] == 1L))

write.csv(prediction_df, prediction_path, row.names = FALSE)
stopifnot(file.exists(prediction_path))

# ------------------------------------------------------------------
# SERIALIZATION ROUNDTRIP
# ------------------------------------------------------------------
reloaded_model <- readRDS(model_path)
stopifnot(identical(names(reloaded_model), c("rf_mers", "rf_peptides", "imp_features")))
stopifnot(identical(as.character(reloaded_model$imp_features), as.character(imp_features)))

reload_rf1_matrix <- predict(
  reloaded_model$rf_mers,
  data.frame(as.matrix(validation_ngrams))
)[["predictions"]]
reload_rf1_p_true <- reload_rf1_matrix[, "TRUE"]
reload_mer_preds <- validation_mer_df
reload_mer_preds$pred <- reload_rf1_p_true
reload_stats <- calculate_statistics_reimpl(reload_mer_preds)
reload_rf2_matrix <- predict(
  reloaded_model$rf_peptides,
  data.frame(reload_stats[, STAT_NAMES, drop = FALSE])
)[["predictions"]]
reload_probability <- reload_rf2_matrix[, "TRUE"]
serialization_delta <- max(abs(reload_probability - probability))
stopifnot(is.finite(serialization_delta))
stopifnot(serialization_delta < 1e-15)

# ------------------------------------------------------------------
# MACHINE-READABLE REPORT
# ------------------------------------------------------------------
emit("R_VERSION", as.character(getRversion()))
emit("SLAM_VERSION", as.character(packageVersion("slam")))
emit("BIOGRAM_VERSION", as.character(packageVersion("biogram")))
emit("RANGER_VERSION", as.character(packageVersion("ranger")))
emit("TRAIN_PEPTIDES", nrow(train_df))
emit("TRAIN_MERS", nrow(train_mer_df))
emit("RF1_FIT_MERS", sum(rf1_fit_rows))
emit("VALIDATION_PEPTIDES", nrow(validation_df))
emit("VALIDATION_MERS", nrow(validation_mer_df))
emit("FEATURE_UNIVERSE", ncol(train_binary_ngrams))
emit("FEATURE_REGISTRY_MATCH", "TRUE")
emit("MER_EXTRACTION_ORACLE_PASS", "TRUE")
emit("SELECTED_FEATURES", length(imp_features))
emit("RF1_TREES", rf_mers$num.trees)
emit("RF2_TREES", rf_peptides$num.trees)
emit("RF1_CLASSES", paste(colnames(rf1_validation_prediction_matrix), collapse = "|"))
emit("RF2_CLASSES", paste(colnames(rf2_validation_prediction_matrix), collapse = "|"))
emit("PEPTIDE_STATISTICS", length(STAT_NAMES))
emit("STAT_ORACLE_PASS", "TRUE")
emit("TRAIN_LENGTH10_ONE_MER_PASS", "TRUE")
emit("VALIDATION_LENGTH10_ONE_MER_PASS", "TRUE")
emit("PROB_MIN", format(min(probability), digits = 17))
emit("PROB_MAX", format(max(probability), digits = 17))
emit("SERIALIZATION_MAX_DELTA", format(serialization_delta, scientific = TRUE, digits = 17))
emit("NATIVE_THRESHOLD", "0.5")
emit("FEATURE_SELECTION_SCOPE", "SYNTHETIC_TRAIN_11_TO_26_ONLY")
emit("RF2_TRAIN_SCOPE", "ALL_SYNTHETIC_TRAIN_10_15_24_30")
emit("DPLYR_REQUIRED", "FALSE")
emit("MAGRITTR_REQUIRED", "FALSE")
emit("BENCHMARK_DATA_USED", "FALSE")
emit("BENCHMARK_TEST_USED", "FALSE")
emit("EXTERNAL_TARGET_USED", "FALSE")
emit("SELFTEST_PASS", "TRUE")
'''

        R_ADAPTER_PATH.write_text(R_ADAPTER, encoding="utf-8", newline="\n")

        # ========================================================
        # 14. EXECUTE EXACT R ADAPTER SELF-TEST
        # ========================================================

        command = [
            R_SCRIPT,
            "--vanilla",
            R_ADAPTER_PATH,
            AMPGRAM_SOURCE,
            TRAIN_PATH,
            VALIDATION_PATH,
            MODEL_PATH,
            PREDICTIONS_PATH,
            SELECTED_FEATURES_PATH,
            ORACLE_PATH,
            FEATURE_REGISTRY_PATH,
        ]

        result = run_cmd(
            command,
            env=r_env,
            timeout=1800,
        )

        print("=" * 128)
        print("AMPGRAM CELL 24 - FULL ADAPTER R OUTPUT")
        print("=" * 128)
        print(result.stdout or "<EMPTY STDOUT>")
        if (result.stderr or "").strip():
            print("-" * 128)
            print("R STDERR / WARNINGS")
            print("-" * 128)
            print(result.stderr)
        print("=" * 128)

        if result.returncode != 0:
            print_subprocess_failure(
                "Cell 24 AmpGram full adapter self-test",
                result,
                command,
            )
        assert result.returncode == 0, (
            "AmpGram full adapter self-test failed. Full R diagnostic is printed above."
        )

        machine = parse_machine_output(result.stdout)
        required_keys = {
            "R_VERSION",
            "SLAM_VERSION",
            "BIOGRAM_VERSION",
            "RANGER_VERSION",
            "TRAIN_PEPTIDES",
            "TRAIN_MERS",
            "RF1_FIT_MERS",
            "VALIDATION_PEPTIDES",
            "VALIDATION_MERS",
            "FEATURE_UNIVERSE",
            "FEATURE_REGISTRY_MATCH",
            "MER_EXTRACTION_ORACLE_PASS",
            "SELECTED_FEATURES",
            "RF1_TREES",
            "RF2_TREES",
            "RF1_CLASSES",
            "RF2_CLASSES",
            "PEPTIDE_STATISTICS",
            "STAT_ORACLE_PASS",
            "TRAIN_LENGTH10_ONE_MER_PASS",
            "VALIDATION_LENGTH10_ONE_MER_PASS",
            "PROB_MIN",
            "PROB_MAX",
            "SERIALIZATION_MAX_DELTA",
            "NATIVE_THRESHOLD",
            "FEATURE_SELECTION_SCOPE",
            "RF2_TRAIN_SCOPE",
            "DPLYR_REQUIRED",
            "MAGRITTR_REQUIRED",
            "BENCHMARK_DATA_USED",
            "BENCHMARK_TEST_USED",
            "EXTERNAL_TARGET_USED",
            "SELFTEST_PASS",
        }
        missing = sorted(required_keys - set(machine))
        assert not missing, f"R self-test output missing keys: {missing}"

        # ========================================================
        # 15. HARD SCIENTIFIC ASSERTIONS
        # ========================================================

        assert machine["R_VERSION"] == "3.6.2"
        assert int(machine["TRAIN_PEPTIDES"]) == 72
        assert int(machine["TRAIN_MERS"]) == 768
        assert int(machine["RF1_FIT_MERS"]) == 504
        assert int(machine["VALIDATION_PEPTIDES"]) == 24
        assert int(machine["VALIDATION_MERS"]) == 258
        assert int(machine["FEATURE_UNIVERSE"]) == 33620
        assert machine["FEATURE_REGISTRY_MATCH"] == "TRUE"
        assert machine["MER_EXTRACTION_ORACLE_PASS"] == "TRUE"
        assert int(machine["SELECTED_FEATURES"]) >= 2
        assert int(machine["RF1_TREES"]) == 2000
        assert int(machine["RF2_TREES"]) == 500
        assert "TRUE" in machine["RF1_CLASSES"].split("|")
        assert "FALSE" in machine["RF1_CLASSES"].split("|")
        assert "TRUE" in machine["RF2_CLASSES"].split("|")
        assert "FALSE" in machine["RF2_CLASSES"].split("|")
        assert int(machine["PEPTIDE_STATISTICS"]) == 14
        assert machine["STAT_ORACLE_PASS"] == "TRUE"
        assert machine["TRAIN_LENGTH10_ONE_MER_PASS"] == "TRUE"
        assert machine["VALIDATION_LENGTH10_ONE_MER_PASS"] == "TRUE"
        assert np.isclose(float(machine["NATIVE_THRESHOLD"]), 0.5)
        assert machine["FEATURE_SELECTION_SCOPE"] == "SYNTHETIC_TRAIN_11_TO_26_ONLY"
        assert machine["RF2_TRAIN_SCOPE"] == "ALL_SYNTHETIC_TRAIN_10_15_24_30"
        assert machine["DPLYR_REQUIRED"] == "FALSE"
        assert machine["MAGRITTR_REQUIRED"] == "FALSE"
        assert machine["BENCHMARK_DATA_USED"] == "FALSE"
        assert machine["BENCHMARK_TEST_USED"] == "FALSE"
        assert machine["EXTERNAL_TARGET_USED"] == "FALSE"
        assert machine["SELFTEST_PASS"] == "TRUE"

        prob_min = float(machine["PROB_MIN"])
        prob_max = float(machine["PROB_MAX"])
        serialization_delta = float(machine["SERIALIZATION_MAX_DELTA"])
        assert 0.0 <= prob_min <= prob_max <= 1.0
        assert serialization_delta < 1e-15

        # Directly executed R packages are rechecked after the self-test.
        # The full nine-package closure was already re-verified from Cell 23 above.
        for key, pkg in [
            ("SLAM_VERSION", "slam"),
            ("BIOGRAM_VERSION", "biogram"),
            ("RANGER_VERSION", "ranger"),
        ]:
            actual = machine[key]
            expected = CELL23_EXPECTED_PACKAGES[pkg]
            semantic_check = run_cmd(
                [
                    R_SCRIPT,
                    "--vanilla",
                    "-e",
                    (
                        'quit(status=ifelse(utils::compareVersion("%s", "%s") == 0, 0, 17))'
                        % (actual, expected)
                    ),
                ],
                env=r_env,
                timeout=120,
            )
            assert semantic_check.returncode == 0, (
                f"R self-test package mismatch: {pkg} actual={actual} expected={expected}"
            )

        # ========================================================
        # 16. VERIFY R OUTPUT ARTIFACTS
        # ========================================================

        for path in [
            MODEL_PATH,
            PREDICTIONS_PATH,
            SELECTED_FEATURES_PATH,
            ORACLE_PATH,
            R_ADAPTER_PATH,
            TRAIN_PATH,
            VALIDATION_PATH,
        ]:
            assert path.is_file(), f"Self-test artifact missing: {path}"
            assert path.stat().st_size > 0, f"Self-test artifact is empty: {path}"

        selected_df = pd.read_csv(SELECTED_FEATURES_PATH)
        assert list(selected_df.columns) == ["feature_name"]
        assert len(selected_df) == int(machine["SELECTED_FEATURES"])
        assert selected_df["feature_name"].is_unique
        assert set(selected_df["feature_name"].astype(str)).issubset(FEATURE_NAME_SET)

        pred_df = pd.read_csv(PREDICTIONS_PATH)
        required_pred_cols = {
            "sample_id",
            "sequence",
            "sequence_length",
            "true_label",
            "n_10mers",
            "ampgram_probability_TRUE",
            "ampgram_decision_threshold_0.5",
        }
        assert required_pred_cols.issubset(pred_df.columns)
        assert len(pred_df) == len(validation_df) == 24
        assert pred_df["sample_id"].is_unique
        assert set(pred_df["sample_id"].astype(str)) == set(validation_df["sample_id"].astype(str))
        assert set(pred_df["sample_id"].astype(str)).isdisjoint(set(train_df["sample_id"].astype(str)))
        assert pred_df["ampgram_probability_TRUE"].between(0.0, 1.0, inclusive="both").all()
        assert np.isfinite(pred_df["ampgram_probability_TRUE"].to_numpy(dtype=float)).all()
        assert (
            pred_df["n_10mers"].astype(int)
            == pred_df["sequence_length"].astype(int) - 9
        ).all()
        assert (
            pred_df.loc[pred_df["sequence_length"].astype(int) == 10, "n_10mers"].astype(int)
            == 1
        ).all()

        oracle_df = pd.read_csv(ORACLE_PATH)
        assert len(oracle_df) == 1
        expected_stat_names = list(ampgram_contract["peptide_statistics"]["names"])
        assert len(expected_stat_names) == 14
        assert all(name in oracle_df.columns for name in expected_stat_names)

        # ========================================================
        # 17. ATOMICALLY COMMIT THE COMPLETE SELF-TEST BUNDLE
        # ========================================================

        os.rename(staging_dir, FINAL_BUNDLE_DIR)
        staging_dir = None

        final_paths = {
            "synthetic_train": FINAL_BUNDLE_DIR / TRAIN_PATH.name,
            "synthetic_validation": FINAL_BUNDLE_DIR / VALIDATION_PATH.name,
            "r_adapter_script": FINAL_BUNDLE_DIR / R_ADAPTER_PATH.name,
            "selected_features": FINAL_BUNDLE_DIR / SELECTED_FEATURES_PATH.name,
            "statistics_oracle": FINAL_BUNDLE_DIR / ORACLE_PATH.name,
            "model": FINAL_BUNDLE_DIR / MODEL_PATH.name,
            "predictions": FINAL_BUNDLE_DIR / PREDICTIONS_PATH.name,
        }

        for path in final_paths.values():
            assert path.is_file()

        # ========================================================
        # 18. IMMUTABLE AMPGRAM SELF-TEST MANIFEST
        # ========================================================

        adapter_contract = {
            "model_id": "ampgram",
            "implementation_route": ampgram_contract["implementation_route"],
            "orchestration": "Python restart-safe adapter",
            "execution_backend": (
                "exact isolated R-3.6.2 runtime selected by Cell 22 and restored by Cell 23"
            ),
            "source_recipe_execution": (
                "locked AmpGram-analysis helper semantics faithfully reimplemented "
                "with base R plus exact biogram/ranger; helper sources hash-locked"
            ),
            "sequence_processing": {
                "window": "overlapping_10mer",
                "validation_length10": "one_valid_10mer_verified",
            },
            "feature_representation": {
                "family": "binary_biogram_multigrams",
                "feature_universe": 33620,
                "selected_features_in_synthetic_selftest": int(machine["SELECTED_FEATURES"]),
            },
            "feature_selection": {
                "function": "direct biogram::test_features with exact calc_imp_bigrams semantics",
                "criterion": "ig",
                "adjust": "BH",
                "occurrence_threshold": 1,
                "quick": True,
                "cutoff": 0.05,
                "fit_scope": "synthetic_train_lengths_11_to_26_only_for_selftest",
            },
            "rf1": {
                "backend": "ranger",
                "version": machine["RANGER_VERSION"],
                "trees": 2000,
                "probability": True,
                "positive_class": "TRUE",
                "selftest_seed": 990,
            },
            "peptide_statistics": {
                "count": 14,
                "names": expected_stat_names,
                "internal_mer_positive_rule": "pred > 0.5",
                "boundary_oracle": "PASS",
            },
            "rf2": {
                "fit_scope": "all_synthetic_train_lengths_10_15_24_30",
                "backend": "ranger",
                "version": machine["RANGER_VERSION"],
                "trees": 500,
                "probability": True,
                "positive_class": "TRUE",
                "selftest_seed": 990,
            },
            "native_score": "P(TRUE)_from_peptide_level_RF",
            "native_threshold": 0.5,
            "serialization_roundtrip_max_abs_delta": serialization_delta,
            "benchmark_seed_schedule_locked": list(range(100, 110)),
            "adapter_self_test_status": "PASS",
        }

        artifact_entries = {
            key: {
                "path": str(path),
                "sha256": sha256_file(path),
            }
            for key, path in final_paths.items()
        }

        manifest = {
            "schema_version": "2.0",
            "created_at": datetime.now().astimezone().isoformat(),
            "status": "IMPLEMENTATION_VALIDATED",
            "model_id": "ampgram",
            "implementation_validated": True,
            "benchmark_training_performed": False,
            "benchmark_test_used": False,
            "external_target_used": False,
            "synthetic_selftest_only": True,
            "upstream": {
                "cell23_path": str(CELL23_PATH),
                "cell23_sha256": EXPECTED_CELL23_SHA256,
                "implementation_contract_path": str(AMPGRAM_CONTRACT_PATH),
                "implementation_contract_sha256": sha256_file(AMPGRAM_CONTRACT_PATH),
                "source_recipe_amendment_path": str(AMPGRAM_AMENDMENT_PATH),
                "source_recipe_amendment_sha256": sha256_file(AMPGRAM_AMENDMENT_PATH),
                "feature_registry_path": str(FEATURE_REGISTRY_PATH),
                "feature_registry_sha256": sha256_file(FEATURE_REGISTRY_PATH),
            },
            "source": {
                "repository": "michbur/AmpGram-analysis",
                "ampgram_commit": "9a76d4c90a74622ec5ad9dc8b3d908799ac7745a",
                "biogram_commit": "148d3d9b323998d759b967a30f13b2b445169a5e",
                "relevant_file_sha256": source_sha256,
            },
            "runtime": {
                "R": machine["R_VERSION"],
                "Rscript": str(R_SCRIPT),
                "environment": str(AMPGRAM_ENV),
                "packages": dict(CELL23_ACTUAL_PACKAGES),
                "directly_executed_packages": {
                    "slam": machine["SLAM_VERSION"],
                    "biogram": machine["BIOGRAM_VERSION"],
                    "ranger": machine["RANGER_VERSION"],
                },
                "dplyr_required": False,
                "magrittr_required": False,
            },
            "selftest": {
                "train_peptides": int(machine["TRAIN_PEPTIDES"]),
                "train_mers": int(machine["TRAIN_MERS"]),
                "validation_peptides": int(machine["VALIDATION_PEPTIDES"]),
                "validation_mers": int(machine["VALIDATION_MERS"]),
                "feature_universe": int(machine["FEATURE_UNIVERSE"]),
                "feature_registry_exact_set_match": True,
                "mer_extraction_oracle_verified": True,
                "rf1_fit_mers": int(machine["RF1_FIT_MERS"]),
                "selected_features": int(machine["SELECTED_FEATURES"]),
                "probability_range": [prob_min, prob_max],
                "length10_one_mer_verified": True,
                "statistics_oracle_verified": True,
                "serialization_roundtrip_verified": True,
            },
            "adapter_contract": adapter_contract,
            "scientific_boundary": {
                "benchmark_dataset_read": False,
                "benchmark_train_used": False,
                "benchmark_validation_used": False,
                "benchmark_test_used": False,
                "external_target_used": False,
                "benchmark_feature_selection_performed": False,
                "benchmark_RF1_fitted": False,
                "benchmark_RF2_fitted": False,
                "benchmark_training_performed": False,
            },
            "artifacts": artifact_entries,
        }

        atomic_write_json(SELFTEST_MANIFEST_PATH, manifest)

        manifest_check = load_json(SELFTEST_MANIFEST_PATH)
        assert manifest_check["status"] == "IMPLEMENTATION_VALIDATED"
        assert manifest_check["implementation_validated"] is True
        assert manifest_check["model_id"] == "ampgram"
        assert manifest_check["benchmark_training_performed"] is False
        assert manifest_check["benchmark_test_used"] is False
        assert manifest_check["external_target_used"] is False
        assert manifest_check["adapter_contract"]["adapter_self_test_status"] == "PASS"

        for entry in manifest_check["artifacts"].values():
            verify_artifact_entry(entry)

        # ========================================================
        # 19. UPDATE READINESS + RECOMPUTE GLOBAL GATE
        # ========================================================

        validated_methods, gate_after = merge_readiness_and_gate()
        assert "ampgram" in validated_methods
        assert "ampir" in validated_methods

        # ========================================================
        # 20. FINAL REPORT
        # ========================================================

        print("=" * 128)
        print("CELL 24 PASS - AMPGRAM FULL ADAPTER END-TO-END SELF-TEST PASSED")
        print("=" * 128)
        print("Published method       : AmpGram")
        print("Implementation status  : VALIDATED")
        print("AmpGram commit         : 9a76d4c90a74622ec5ad9dc8b3d908799ac7745a")
        print("biogram commit         : 148d3d9b323998d759b967a30f13b2b445169a5e")
        print("R                      :", machine["R_VERSION"])
        print("biogram                :", machine["BIOGRAM_VERSION"])
        print("ranger                 :", machine["RANGER_VERSION"])
        print("-" * 128)
        print("END-TO-END PIPELINE")
        print("Sequence               : PASS")
        print("Overlapping 10-mer     : PASS")
        print("Multigram universe     : 33,620 - PASS")
        print("QuiPT/test_features    : PASS")
        print("Selected features      :", int(machine["SELECTED_FEATURES"]), "(synthetic self-test only)")
        print("RF1                     : ranger probability, 2000 trees - PASS")
        print("14 statistics          : PASS")
        print("RF2                     : ranger probability, 500 trees - PASS")
        print("P(TRUE) semantics      : PASS")
        print("Native threshold       : 0.5")
        print("Serialization          : PASS; max delta = %.3e" % serialization_delta)
        print("Length=10 one 10-mer   : PASS (train + validation)")
        print("-" * 128)
        print("SCIENTIFIC SCOPE")
        print("Synthetic train        :", int(machine["TRAIN_PEPTIDES"]), "peptides /", int(machine["TRAIN_MERS"]), "10-mers")
        print("Synthetic validation   :", int(machine["VALIDATION_PEPTIDES"]), "peptides /", int(machine["VALIDATION_MERS"]), "10-mers")
        print("Benchmark data used    : FALSE")
        print("Benchmark test used    : FALSE")
        print("External target used   : FALSE")
        print("Benchmark training     : FALSE")
        print("-" * 128)
        print("Published validated    : %d/7" % len(validated_methods))
        print("Validated methods      :", validated_methods)
        print("TRAINING GATE          :", "OPEN" if gate_after["open"] else "CLOSED")
        print("-" * 128)
        print("Self-test bundle       :", FINAL_BUNDLE_DIR)
        print("Self-test manifest     :", SELFTEST_MANIFEST_PATH)
        print("Manifest SHA256        :", sha256_file(SELFTEST_MANIFEST_PATH))
        print("=" * 128)

    finally:
        if staging_dir is not None and Path(staging_dir).exists():
            shutil.rmtree(staging_dir, ignore_errors=True)

================================================================================================================================
AMPGRAM CELL 24 - FULL ADAPTER R OUTPUT
================================================================================================================================
AMPGRAM24	R_VERSION	3.6.2
AMPGRAM24	SLAM_VERSION	0.1.47
AMPGRAM24	BIOGRAM_VERSION	1.6.3
AMPGRAM24	RANGER_VERSION	0.12.1
AMPGRAM24	TRAIN_PEPTIDES	72
AMPGRAM24	TRAIN_MERS	768
AMPGRAM24	RF1_FIT_MERS	504
AMPGRAM24	VALIDATION_PEPTIDES	24
AMPGRAM24	VALIDATION_MERS	258
AMPGRAM24	FEATURE_UNIVERSE	33620
AMPGRAM24	FEATURE_REGISTRY_MATCH	TRUE
AMPGRAM24	MER_EXTRACTION_ORACLE_PASS	TRUE
AMPGRAM24	SELECTED_FEATURES	641
AMPGRAM24	RF1_TREES	2000
AMPGRAM24	RF2_TREES	500
AMPGRAM24	RF1_CLASSES	FALSE|TRUE
AMPGRAM24	RF2_CLASSES	FALSE|TRUE
AMPGRAM24	PEPTIDE_STATISTICS	14
AMPGRAM24	STAT_ORACLE_PASS	TRUE
AMPGRAM24	TRAIN_LENGTH10_ONE_MER_PASS	TRUE
AMPGRAM24	VALIDATION_LENGTH10_ONE_MER_PASS	TRUE
AMPGRAM24	PROB_MIN	0.00064285714285714293
AMPGRAM24	PROB_MAX	1
AMPGRAM24	SERIALIZATION_MAX_DELTA	0e+00
AMPGRAM24	NATIVE_THRESHOLD	0.5
AMPGRAM24	FEATURE_SELECTION_SCOPE	SYNTHETIC_TRAIN_11_TO_26_ONLY
AMPGRAM24	RF2_TRAIN_SCOPE	ALL_SYNTHETIC_TRAIN_10_15_24_30
AMPGRAM24	DPLYR_REQUIRED	FALSE
AMPGRAM24	MAGRITTR_REQUIRED	FALSE
AMPGRAM24	BENCHMARK_DATA_USED	FALSE
AMPGRAM24	BENCHMARK_TEST_USED	FALSE
AMPGRAM24	EXTERNAL_TARGET_USED	FALSE
AMPGRAM24	SELFTEST_PASS	TRUE

--------------------------------------------------------------------------------------------------------------------------------
R STDERR / WARNINGS
--------------------------------------------------------------------------------------------------------------------------------
Warning messages:
1: package 'slam' was built under R version 3.6.3
2: package 'ranger' was built under R version 3.6.3

================================================================================================================================
================================================================================================================================
CELL 24 PASS - AMPGRAM FULL ADAPTER END-TO-END SELF-TEST PASSED
================================================================================================================================
Published method       : AmpGram
Implementation status  : VALIDATED
AmpGram commit         : 9a76d4c90a74622ec5ad9dc8b3d908799ac7745a
biogram commit         : 148d3d9b323998d759b967a30f13b2b445169a5e
R                      : 3.6.2
biogram                : 1.6.3
ranger                 : 0.12.1
--------------------------------------------------------------------------------------------------------------------------------
END-TO-END PIPELINE
Sequence               : PASS
Overlapping 10-mer     : PASS
Multigram universe     : 33,620 - PASS
QuiPT/test_features    : PASS
Selected features      : 641 (synthetic self-test only)
RF1                     : ranger probability, 2000 trees - PASS
14 statistics          : PASS
RF2                     : ranger probability, 500 trees - PASS
P(TRUE) semantics      : PASS
Native threshold       : 0.5
Serialization          : PASS; max delta = 0.000e+00
Length=10 one 10-mer   : PASS (train + validation)
--------------------------------------------------------------------------------------------------------------------------------
SCIENTIFIC SCOPE
Synthetic train        : 72 peptides / 768 10-mers
Synthetic validation   : 24 peptides / 258 10-mers
Benchmark data used    : FALSE
Benchmark test used    : FALSE
External target used   : FALSE
Benchmark training     : FALSE
--------------------------------------------------------------------------------------------------------------------------------
Published validated    : 2/7
Validated methods      : ['ampgram', 'ampir']
TRAINING GATE          : CLOSED
--------------------------------------------------------------------------------------------------------------------------------
Self-test bundle       : /home/pc/genpept_benchmark17_work/published_selftests/ampgram/cell24_final_adapter_selftest
Self-test manifest     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampgram_FINAL_adapter_selftest.json
Manifest SHA256        : 399d1d695e72f42ad591caf637de03b910d07e09b1f1f5805054e629153aee3d
================================================================================================================================

In [14]:
# ============================================================
# CELL 25 v2 - RESTART-SAFE FULL REPLACEMENT
# AmPEP AUTHOR-RELEASE SOURCE LOCK + CANONICAL 105-D_F CONTRACT
#
# WHY THIS REPLACES CELL 25 v1
# ----------------------------
# Cell 25 v1 incorrectly promoted the paper's 23-feature reduced variant
# to a mandatory implementation target. After auditing the authors'
# released MATLAB code, the released AmPEP main_function() is explicit:
#   sequence -> Seq2Distribution() -> ALL 105 D_F descriptors
#            -> TreeBagger(100, all predictors, class)
# There is no 23-feature selection in main_function.m,
# train_seqs2distribution.m, test_seqs2distribution.m, or RF_test_yan.m.
#
# This cell therefore corrects the SOURCE/CONTRACT layer BEFORE Cell 26.
# It does NOT train a benchmark model and does NOT open/modify the gate.
#
# STAGE
# -----
# SOURCE -> CONTRACT
#
# SCIENTIFIC BOUNDARY
# -------------------
# - No benchmark train/validation/test data are read.
# - No external target data are read.
# - No RF is fitted.
# - No feature selection is performed.
# - The paper's 23-feature D_F,PCC<0.5 subset is retained as a published
#   reduced-feature VARIANT, not silently discarded.
# - The canonical AmPEP implementation for this benchmark is resolved from
#   the authors' released main_function pipeline: full 105 D_F features.
# - Global training gate must remain byte-identical.
# ============================================================

from pathlib import Path
from datetime import datetime
import csv
import hashlib
import json
import math
import os
import re
import shutil
import ssl
import tempfile
import urllib.request
import zipfile

import pandas as pd


# ============================================================
# 1. PATHS / LOCKED UPSTREAM ARTIFACTS
# ============================================================

PROJECT_ROOT = Path("/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026")
OUTPUT_ROOT = PROJECT_ROOT / "benchmark17_outputs"
AUDIT_DIR = OUTPUT_ROOT / "audit"
MANIFEST_DIR = OUTPUT_ROOT / "manifests"
SOURCE_ROOT = Path("/home/pc/genpept_sources")
AMPEP_SOURCE_ROOT = SOURCE_ROOT / "AmPEP_author_release"

ROUTE_CONTRACT_PATH = MANIFEST_DIR / "benchmark17_FINAL_published_method_route_contract.json"
TRAINING_GATE_PATH = MANIFEST_DIR / "benchmark17_FINAL_training_gate.json"
READINESS_PATH = AUDIT_DIR / "benchmark17_published_method_local_readiness_latest.csv"
AMPGRAM_SELFTEST_PATH = MANIFEST_DIR / "benchmark17_ampgram_FINAL_adapter_selftest.json"
AMPIR_SELFTEST_PATH = MANIFEST_DIR / "benchmark17_ampir_FINAL_adapter_selftest.json"

# Same canonical Cell-25 output path. v1 is explicitly superseded only if its
# exact known hash is present; unknown content is never overwritten.
AMPEP_CONTRACT_PATH = MANIFEST_DIR / "benchmark17_ampep_FINAL_publication_source_contract.json"
SUPERSEDED_CELL25_PATH = MANIFEST_DIR / "benchmark17_ampep_CELL25_v1_SUPERSEDED_exact23_requirement.json"
AMPEP_105_REGISTRY_PATH = AUDIT_DIR / "benchmark17_ampep_author_release_105DF_registry.csv"
SOURCE_AUDIT_PATH = MANIFEST_DIR / "benchmark17_ampep_author_release_source_audit.json"

EXPECTED_ROUTE_SHA256 = "dd7d6a743f088cef95fb49288dcf1801c9dc335be2656e627e7fc7f3bf7170bd"
EXPECTED_AMPGRAM_SELFTEST_SHA256 = "399d1d695e72f42ad591caf637de03b910d07e09b1f1f5805054e629153aee3d"
SUPERSEDED_CELL25_V1_SHA256 = "dfa5de1c3cf95bf070e5200d34325224f2d62b6c60b4ff45cad4956c1d0f166b"

for d in [PROJECT_ROOT, OUTPUT_ROOT, AUDIT_DIR, MANIFEST_DIR, SOURCE_ROOT]:
    assert d.is_dir(), f"Required directory missing:\n{d}"

for f in [
    ROUTE_CONTRACT_PATH,
    TRAINING_GATE_PATH,
    READINESS_PATH,
    AMPGRAM_SELFTEST_PATH,
    AMPIR_SELFTEST_PATH,
]:
    assert f.is_file(), f"Required upstream artifact missing:\n{f}"

AMPEP_SOURCE_ROOT.mkdir(parents=True, exist_ok=True)


# ============================================================
# 2. HELPERS
# ============================================================

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def git_blob_sha1_bytes(data: bytes) -> str:
    header = f"blob {len(data)}\0".encode("ascii")
    return hashlib.sha1(header + data).hexdigest()


def git_blob_sha1_file(path: Path) -> str:
    return git_blob_sha1_bytes(path.read_bytes())


def load_json(path: Path):
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def atomic_write_json(path: Path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".tmp.", dir=str(path.parent))
    os.close(fd)
    tmp = Path(tmp_name)
    try:
        with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(payload, fh, indent=2, ensure_ascii=False, sort_keys=True)
            fh.write("\n")
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def atomic_write_csv(path: Path, df: pd.DataFrame):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".tmp.", dir=str(path.parent))
    os.close(fd)
    tmp = Path(tmp_name)
    try:
        df.to_csv(tmp, index=False)
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def normalize_matlab_text(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def boolish(value):
    if isinstance(value, bool):
        return value
    if pd.isna(value):
        return False
    return str(value).strip().lower() in {"true", "1", "yes", "y"}


def download_bytes(url: str, timeout: int = 90) -> bytes:
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Mozilla/5.0 GenPept-Curated-2025 reproducibility audit",
            "Accept": "*/*",
        },
    )
    ctx = ssl.create_default_context()
    with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
        return resp.read()


# ============================================================
# 3. VERIFY UPSTREAM ROUTE + VALIDATED METHODS + CLOSED GATE
# ============================================================

assert sha256_file(ROUTE_CONTRACT_PATH) == EXPECTED_ROUTE_SHA256, (
    "Published-method route contract changed. Refusing to continue."
)
assert sha256_file(AMPGRAM_SELFTEST_PATH) == EXPECTED_AMPGRAM_SELFTEST_SHA256, (
    "Cell 24 AmpGram manifest changed. Refusing to continue."
)

route_payload = load_json(ROUTE_CONTRACT_PATH)
assert route_payload["status"] == "PUBLISHED_METHOD_ROUTES_LOCKED_BEFORE_TRAINING"
assert route_payload["restart_safe"] is True

route_core = route_payload["contract"]
assert route_core["published_model_ids"] == [
    "ampep", "ampscannerv2", "ampgram", "ampir", "ampeppy", "ai4amp", "amplify"
]
ampep_route = route_core["methods"]["ampep"]

# Preserve the immutable high-level route established earlier.
assert ampep_route["paper_doi"] == "10.1038/s41598-018-19752-w"
assert ampep_route["published_family"] == "random_forest"
assert ampep_route["locked_route"] == "faithful_reimplementation_from_publication"
assert ampep_route["original_training_software"] == "MATLAB_TreeBagger"
assert ampep_route["reported_selected_features"] == 23
assert ampep_route["must_match_published_representation"] is True
assert ampep_route["must_match_published_RF_method"] is True

# Existing validated methods must still be exactly ampir + ampgram before AmPEP validation.
for model_id, path in [("ampgram", AMPGRAM_SELFTEST_PATH), ("ampir", AMPIR_SELFTEST_PATH)]:
    payload = load_json(path)
    assert payload["status"] == "IMPLEMENTATION_VALIDATED"
    assert payload["implementation_validated"] is True
    observed = payload.get("model_id") or payload.get("adapter_contract", {}).get("model_id")
    assert observed == model_id
    assert payload["benchmark_training_performed"] is False
    assert payload["benchmark_test_used"] is False

GATE_SHA_BEFORE = sha256_file(TRAINING_GATE_PATH)
gate_before = load_json(TRAINING_GATE_PATH)
assert gate_before["open"] is False
assert gate_before["benchmark_training_allowed"] is False
assert gate_before["published_methods_implementation_validated"] == 2
assert sorted(gate_before.get("validated_methods", [])) == ["ampgram", "ampir"]


# ============================================================
# 4. AUTHOR-RELEASE SOURCE ACQUISITION
#
# Primary channel: official SourceForge release.
# Fallback channel: exact public GitHub mirror at a pinned commit.
# Every required file is verified by Git blob SHA-1 against the pinned mirror.
# ============================================================

MIRROR_REPO = "lassebuur/bacteriocin_classifier"
MIRROR_COMMIT = "1fedfe1c3203fdd5a417ba1c2e92123478f2cfc0"
MIRROR_SUBDIR = "code_modules/ampep/ampep-matlab-code"

REQUIRED_SOURCE_BLOBS = {
    "README.txt": "9fd99b122e2bd9a63c01e232632f9022433e09d9",
    "main_function.m": "931370156d4256d5393fdd54bb35cb91711afecf",
    "RF_test_yan.m": "285307459a96f8445dbde14d2e3f26d6b7291b08",
    "Seq2Distribution.m": "7dd28d6f2116d86f3e407d4897148c2fc0a128c0",
    "train_seqs2distribution.m": "7b22939623cbecd8eba2677adb2b303d998f200f",
    "test_seqs2distribution.m": "e424e3b97a2dc8f922d4ad978a6ca222f4ffa395",
    "trian_po_set3298_for_ampep_sever.fasta": "b424bf408cb84b2f3d669fdbf100e7ec3eca514f",
    "trian_ne_set9894_for_ampep_sever.fasta": "36519de57843569429f65adee132a609a8324b01",
}

SOURCEFORGE_URLS = [
    "https://sourceforge.net/projects/axpep/files/AmPEP_MATLAB_code/ampep-matlab-code.zip/download",
    "https://downloads.sourceforge.net/project/axpep/AmPEP_MATLAB_code/ampep-matlab-code.zip",
]


def required_files_exact(root: Path):
    states = {}
    all_ok = True
    for name, expected_blob in REQUIRED_SOURCE_BLOBS.items():
        path = root / name
        if not path.is_file():
            states[name] = {"present": False, "expected_git_blob_sha1": expected_blob}
            all_ok = False
            continue
        actual = git_blob_sha1_file(path)
        ok = actual == expected_blob
        states[name] = {
            "present": True,
            "path": str(path),
            "size_bytes": path.stat().st_size,
            "git_blob_sha1": actual,
            "expected_git_blob_sha1": expected_blob,
            "exact": ok,
            "sha256": sha256_file(path),
        }
        all_ok = all_ok and ok
    return all_ok, states


def locate_exact_existing_source():
    candidates = [
        AMPEP_SOURCE_ROOT,
        SOURCE_ROOT / "ampep-matlab-code",
        SOURCE_ROOT / "AmPEP_MATLAB_code",
        SOURCE_ROOT / "AmPEP_publication_source" / "ampep-matlab-code",
        Path.home() / "Downloads" / "ampep-matlab-code",
    ]
    for root in candidates:
        if root.is_dir():
            ok, states = required_files_exact(root)
            if ok:
                return root, states
    return None, None


def install_exact_source_from_directory(src_root: Path):
    AMPEP_SOURCE_ROOT.mkdir(parents=True, exist_ok=True)
    for name, expected_blob in REQUIRED_SOURCE_BLOBS.items():
        src = src_root / name
        assert src.is_file()
        assert git_blob_sha1_file(src) == expected_blob
        dst = AMPEP_SOURCE_ROOT / name
        if dst.is_file() and git_blob_sha1_file(dst) == expected_blob:
            continue
        tmp = dst.with_name(dst.name + ".tmp-copy")
        if tmp.exists():
            tmp.unlink()
        shutil.copy2(src, tmp)
        assert git_blob_sha1_file(tmp) == expected_blob
        os.replace(tmp, dst)


def try_sourceforge_archive():
    failures = []
    for url in SOURCEFORGE_URLS:
        try:
            data = download_bytes(url, timeout=120)
            if not data.startswith(b"PK"):
                raise RuntimeError(f"response is not ZIP; first bytes={data[:20]!r}")
            zip_path = AMPEP_SOURCE_ROOT / "ampep-matlab-code.author-sourceforge.zip"
            tmp_zip = zip_path.with_name(zip_path.name + ".tmp")
            tmp_zip.write_bytes(data)
            with zipfile.ZipFile(tmp_zip, "r") as zf:
                with tempfile.TemporaryDirectory(prefix="ampep_sf_") as td:
                    td_path = Path(td)
                    zf.extractall(td_path)
                    candidates = []
                    for readme in td_path.rglob("README.txt"):
                        root = readme.parent
                        if all((root / n).is_file() for n in REQUIRED_SOURCE_BLOBS):
                            candidates.append(root)
                    if len(candidates) != 1:
                        raise RuntimeError(
                            f"archive did not resolve to one exact AmPEP source root; candidates={candidates}"
                        )
                    root = candidates[0]
                    ok, states = required_files_exact(root)
                    if not ok:
                        bad = [n for n, s in states.items() if not s.get("exact", False)]
                        raise RuntimeError(
                            "official SourceForge archive differs from pinned public mirror for: "
                            + ", ".join(bad)
                        )
                    install_exact_source_from_directory(root)
            os.replace(tmp_zip, zip_path)
            return True, url, sha256_file(zip_path), failures
        except Exception as exc:
            failures.append(f"{url} -> {type(exc).__name__}: {exc}")
            try:
                tmp_zip = AMPEP_SOURCE_ROOT / "ampep-matlab-code.author-sourceforge.zip.tmp"
                if tmp_zip.exists():
                    tmp_zip.unlink()
            except Exception:
                pass
    return False, None, None, failures


def acquire_from_pinned_github_mirror():
    base = (
        "https://raw.githubusercontent.com/"
        f"lassebuur/bacteriocin_classifier/{MIRROR_COMMIT}/{MIRROR_SUBDIR}"
    )
    actions = []
    for name, expected_blob in REQUIRED_SOURCE_BLOBS.items():
        dst = AMPEP_SOURCE_ROOT / name
        if dst.is_file() and git_blob_sha1_file(dst) == expected_blob:
            actions.append(f"REUSED {name}")
            continue
        data = download_bytes(f"{base}/{name}", timeout=120)
        actual_blob = git_blob_sha1_bytes(data)
        assert actual_blob == expected_blob, (
            f"Pinned mirror content mismatch for {name}: expected {expected_blob}, got {actual_blob}"
        )
        tmp = dst.with_name(dst.name + ".tmp-download")
        tmp.write_bytes(data)
        assert git_blob_sha1_file(tmp) == expected_blob
        os.replace(tmp, dst)
        actions.append(f"DOWNLOADED {name}")
    return actions


existing_root, _ = locate_exact_existing_source()
SOURCEFORGE_ARCHIVE_SHA256 = None
SOURCEFORGE_FAILURES = []

if existing_root is not None:
    if existing_root.resolve() != AMPEP_SOURCE_ROOT.resolve():
        install_exact_source_from_directory(existing_root)
    SOURCE_ACQUISITION = "REUSED EXACT LOCAL AUTHOR-RELEASE SOURCE"
    SOURCE_ORIGIN = str(existing_root)
else:
    sf_ok, sf_url, sf_sha, sf_failures = try_sourceforge_archive()
    SOURCEFORGE_FAILURES = sf_failures
    if sf_ok:
        SOURCE_ACQUISITION = "DOWNLOADED + VERIFIED OFFICIAL SOURCEFORGE AUTHOR RELEASE"
        SOURCE_ORIGIN = sf_url
        SOURCEFORGE_ARCHIVE_SHA256 = sf_sha
    else:
        mirror_actions = acquire_from_pinned_github_mirror()
        SOURCE_ACQUISITION = "ACQUIRED PINNED PUBLIC MIRROR OF AUTHOR RELEASE"
        SOURCE_ORIGIN = f"https://github.com/{MIRROR_REPO}/tree/{MIRROR_COMMIT}/{MIRROR_SUBDIR}"

source_ok, SOURCE_FILE_STATES = required_files_exact(AMPEP_SOURCE_ROOT)
assert source_ok, "AmPEP author-release source closure is incomplete or hash-mismatched."


# ============================================================
# 5. VERIFY AUTHOR-RELEASE EXECUTION PATH - NO PDF PARSING
# ============================================================

README_TEXT = normalize_matlab_text((AMPEP_SOURCE_ROOT / "README.txt").read_text(encoding="utf-8", errors="replace"))
MAIN_TEXT = normalize_matlab_text((AMPEP_SOURCE_ROOT / "main_function.m").read_text(encoding="utf-8", errors="replace"))
RF_TEXT = normalize_matlab_text((AMPEP_SOURCE_ROOT / "RF_test_yan.m").read_text(encoding="utf-8", errors="replace"))
SEQ_TEXT = normalize_matlab_text((AMPEP_SOURCE_ROOT / "Seq2Distribution.m").read_text(encoding="utf-8", errors="replace"))
TRAIN_TEXT = normalize_matlab_text((AMPEP_SOURCE_ROOT / "train_seqs2distribution.m").read_text(encoding="utf-8", errors="replace"))
TEST_TEXT = normalize_matlab_text((AMPEP_SOURCE_ROOT / "test_seqs2distribution.m").read_text(encoding="utf-8", errors="replace"))

# Author identity / release intent.
assert "MATLAB code and datasets for AmPEP" in README_TEXT
assert "University of Macau" in README_TEXT
assert "main_function(test_fasta_path)" in README_TEXT
assert re.search(r"Prediction is performed by random forest with 100 trees", README_TEXT, re.I)

# Canonical released execution path.
assert "train_seqs2distribution(train_positive_fasta,train_negative_fasta)" in MAIN_TEXT.replace(" ...\n        ", "") or "train_seqs2distribution" in MAIN_TEXT
assert "test_seqs2distribution(test_fasta)" in MAIN_TEXT
assert "RF_test_yan(train_data, test_data)" in MAIN_TEXT
assert "trian_po_set3298_for_ampep_sever.fasta" in MAIN_TEXT
assert "trian_ne_set9894_for_ampep_sever.fasta" in MAIN_TEXT

# Feature generation: every sequence gets the complete Seq2Distribution vector.
assert "[d_vector,ft_names] = Seq2Distribution(seq);" in TRAIN_TEXT
assert "d_mat=[d_mat;d_vector];" in TRAIN_TEXT.replace(" ", "") or "d_mat=[d_mat;d_vector];" in TRAIN_TEXT
assert "d_mat = [d_mat,class];" in TRAIN_TEXT
assert "[d_vector,ft_names] = Seq2Distribution(seq);" in TEST_TEXT

# Exact RF call: ALL feature columns except the final class column; no 23-column slicing.
rf_compact = re.sub(r"\s+", "", RF_TEXT)
assert "TreeBagger(100,train(:,1:end-1),train(:,end))" in rf_compact
assert "sco=score(:,2);" in rf_compact

# No reduced-feature selection exists in the released four-stage predictor path.
combined_path_text = "\n".join([MAIN_TEXT, TRAIN_TEXT, TEST_TEXT, RF_TEXT])
for forbidden in ["PCC", "0.5", "selected_feature", "feature_selection"]:
    assert forbidden.lower() not in combined_path_text.lower(), (
        f"Unexpected reduced-feature-selection token in author release: {forbidden}"
    )


# ============================================================
# 6. EXACT 105-D_F REGISTRY FROM Seq2Distribution.m
# ============================================================

# These literals are not guessed. They are the exact group definitions and order
# in the pinned Seq2Distribution.m, verified above by source hash.
PROPERTY_GROUPS = [
    ("charge", ["ACFGHILMNPQSTVWY", "DE", "KR"]),
    ("hydrophobicity", ["CFILMVW", "AGHPSTY", "DEKNQR"]),
    ("normalized_vander_waals", ["ACDGPST", "EILNQV", "FHKMRWY"]),
    ("polarity", ["CFILMVWY", "AGPST", "DEHKNQR"]),
    ("polarizability", ["ADGST", "CEILNPQV", "FHKMRWY"]),
    ("secondary_structure", ["DGNPS", "AEHKLMQR", "CFITVWY"]),
    ("solvent_accessibility", ["ACFGILVW", "HMPSTY", "DEKNRQ"]),
]
RESIDUE_NAMES = ["residue0%", "residue25%", "residue50%", "residue75%", "residue100%"]

# Verify every property/group literal against exact MATLAB source before using it.
for prop, groups in PROPERTY_GROUPS:
    assert prop in SEQ_TEXT
    for group in groups:
        assert f"'{group}'" in SEQ_TEXT
for residue_name in RESIDUE_NAMES:
    assert f"'{residue_name}'" in SEQ_TEXT
assert "for i = 1:7" in SEQ_TEXT
assert "for j = 1:3" in SEQ_TEXT
assert "ft_names" in SEQ_TEXT

registry_rows = []
feature_index = 1
for prop, groups in PROPERTY_GROUPS:
    for group_idx, amino_acids in enumerate(groups, start=1):
        for residue_name in RESIDUE_NAMES:
            registry_rows.append({
                "feature_index_1based": feature_index,
                "property": prop,
                "group": f"group{group_idx}",
                "amino_acids": amino_acids,
                "distribution": residue_name,
                "matlab_feature_name": f"{prop}_group{group_idx}_{residue_name}",
                "canonical_author_release": True,
            })
            feature_index += 1

registry_df = pd.DataFrame(registry_rows)
assert len(registry_df) == 105
assert registry_df["matlab_feature_name"].nunique() == 105
assert registry_df["feature_index_1based"].tolist() == list(range(1, 106))

# Atomic registry lock: identical reuse; different content => fail.
if AMPEP_105_REGISTRY_PATH.exists():
    existing_registry = pd.read_csv(AMPEP_105_REGISTRY_PATH, keep_default_na=False)
    # Normalize bool serialization before equality check.
    expected_cmp = registry_df.copy()
    existing_cmp = existing_registry.copy()
    expected_cmp["canonical_author_release"] = expected_cmp["canonical_author_release"].astype(str).str.lower()
    existing_cmp["canonical_author_release"] = existing_cmp["canonical_author_release"].astype(str).str.lower()
    assert existing_cmp.astype(str).equals(expected_cmp.astype(str)), (
        "Existing AmPEP 105-D_F registry differs. Refusing silent overwrite."
    )
    REGISTRY_ACTION = "EXISTING IDENTICAL 105-D_F REGISTRY VERIFIED"
else:
    atomic_write_csv(AMPEP_105_REGISTRY_PATH, registry_df)
    REGISTRY_ACTION = "NEW 105-D_F REGISTRY ATOMICALLY COMMITTED"

REGISTRY_SHA256 = sha256_file(AMPEP_105_REGISTRY_PATH)


# ============================================================
# 7. RESOLVE PAPER VARIANT VS RELEASED CANONICAL AmPEP
# ============================================================

# Paper facts retained exactly:
# - Full D_F = 105.
# - Reduced D_F,PCC<0.5 = 23 is an evaluated reduced-feature variant.
# - Author-released main_function does not select that subset; it uses all 105.
# Therefore model_id='ampep' in this benchmark follows the author-released
# canonical executable path (105 D_F). The 23-feature variant is documented,
# not silently substituted for the released predictor.

CANONICAL_FEATURE_COUNT = 105
PUBLISHED_REDUCED_VARIANT_COUNT = 23
TREEBAGGER_NUM_TREES = 100
TREEBAGGER_MTRY_105 = math.ceil(math.sqrt(CANONICAL_FEATURE_COUNT))
assert TREEBAGGER_MTRY_105 == 11


# ============================================================
# 8. SOURCE AUDIT MANIFEST
# ============================================================

SOURCE_AUDIT_CORE = {
    "schema_version": "2.0",
    "model_id": "ampep",
    "paper_doi": "10.1038/s41598-018-19752-w",
    "author_release": {
        "official_host": "SourceForge",
        "official_project": "AmPEP and AxPEP",
        "official_directory": "https://sourceforge.net/projects/axpep/files/AmPEP_MATLAB_code/",
        "archive_name": "ampep-matlab-code.zip",
        "local_source_root": str(AMPEP_SOURCE_ROOT),
        "source_origin_this_run": SOURCE_ORIGIN,
        "source_acquisition_this_run": SOURCE_ACQUISITION,
        "sourceforge_archive_sha256": SOURCEFORGE_ARCHIVE_SHA256,
        "pinned_public_mirror": {
            "repository": MIRROR_REPO,
            "commit": MIRROR_COMMIT,
            "subdir": MIRROR_SUBDIR,
        },
        "required_files": SOURCE_FILE_STATES,
    },
    "resolved_execution_path": [
        "main_function.m",
        "train_seqs2distribution.m",
        "Seq2Distribution.m",
        "test_seqs2distribution.m",
        "RF_test_yan.m",
    ],
    "source_facts": {
        "feature_count": 105,
        "feature_registry_path": str(AMPEP_105_REGISTRY_PATH),
        "feature_registry_sha256": REGISTRY_SHA256,
        "rf_software": "MATLAB TreeBagger",
        "rf_trees": 100,
        "rf_input_expression": "train(:,1:end-1)",
        "rf_label_expression": "train(:,end)",
        "positive_score_expression": "score(:,2)",
        "released_feature_selection_step": False,
        "paper_reduced_23_variant_exists": True,
        "paper_reduced_23_variant_is_required_for_author_release_main_function": False,
    },
    "scientific_boundary": {
        "benchmark_data_read": False,
        "benchmark_training_performed": False,
        "benchmark_test_used": False,
        "external_target_used": False,
        "rf_fitted": False,
    },
}

if SOURCE_AUDIT_PATH.exists():
    existing_source_audit = load_json(SOURCE_AUDIT_PATH)
    # source_origin/acquisition can differ on rerun, so compare stable source facts only.
    assert existing_source_audit["model_id"] == "ampep"
    assert existing_source_audit["source_facts"] == SOURCE_AUDIT_CORE["source_facts"]
    assert existing_source_audit["resolved_execution_path"] == SOURCE_AUDIT_CORE["resolved_execution_path"]
    SOURCE_AUDIT_ACTION = "EXISTING AUTHOR-RELEASE SOURCE AUDIT VERIFIED"
else:
    source_payload = {
        **SOURCE_AUDIT_CORE,
        "created_at": datetime.now().astimezone().isoformat(),
        "status": "AMPEP_AUTHOR_RELEASE_SOURCE_VERIFIED",
    }
    atomic_write_json(SOURCE_AUDIT_PATH, source_payload)
    SOURCE_AUDIT_ACTION = "NEW AUTHOR-RELEASE SOURCE AUDIT COMMITTED"

SOURCE_AUDIT_SHA256 = sha256_file(SOURCE_AUDIT_PATH)


# ============================================================
# 9. CORRECTED CELL-25 CONTRACT
# ============================================================

AMPEP_CONTRACT_CORE = {
    "schema_version": "2.0",
    "model_id": "ampep",
    "display_name": "AmPEP",
    "stage": "author_release_source_and_canonical_105DF_contract_locked",
    "locked_route": ampep_route,
    "route_resolution": {
        "canonical_benchmark_variant": "author_release_full_DF_105",
        "reason": (
            "The authors' released main_function -> train_seqs2distribution -> "
            "Seq2Distribution -> RF_test_yan path passes all 105 D_F predictors "
            "to TreeBagger(100). No 23-feature selection occurs in the released predictor."
        ),
        "paper_full_DF_count": 105,
        "paper_reduced_DF_PCC_lt_0_5_count": 23,
        "reduced_23_status": "published_evaluated_variant_not_author_release_main_function",
        "exact_23_registry_required_for_canonical_ampep": False,
    },
    "representation": {
        "family": "D_F_distribution_descriptors",
        "count": 105,
        "properties": [p for p, _ in PROPERTY_GROUPS],
        "classes_per_property": 3,
        "distribution_points": RESIDUE_NAMES,
        "registry_path": str(AMPEP_105_REGISTRY_PATH),
        "registry_sha256": REGISTRY_SHA256,
        "source_function": "Seq2Distribution.m",
    },
    "random_forest": {
        "source_function": "RF_test_yan.m",
        "original_software": "MATLAB TreeBagger",
        "trees": TREEBAGGER_NUM_TREES,
        "predictors": 105,
        "published_mtry_rule": "default_sqrt_number_of_features",
        "treebagger_default_mtry_for_105": TREEBAGGER_MTRY_105,
        "positive_score": "TreeBagger predict() score column 2",
        "class_labels_in_author_training_data": [0, 1],
    },
    "author_release_source": {
        "local_root": str(AMPEP_SOURCE_ROOT),
        "pinned_mirror_repository": MIRROR_REPO,
        "pinned_mirror_commit": MIRROR_COMMIT,
        "source_audit_path": str(SOURCE_AUDIT_PATH),
        "source_audit_sha256": SOURCE_AUDIT_SHA256,
        "required_git_blob_sha1": REQUIRED_SOURCE_BLOBS,
    },
    "implementation_boundary": {
        "implementation_validated": False,
        "adapter_selftest_passed": False,
        "benchmark_training_performed": False,
        "benchmark_test_used": False,
        "external_target_used": False,
        "feature_selection_on_benchmark_data": False,
        "next_cell": 26,
        "next_task": (
            "Run one synthetic-only full adapter self-test for the exact 105-D_F "
            "author-release pipeline and method-faithful 100-tree RF reimplementation; "
            "validate score-column semantics before marking AmPEP validated."
        ),
    },
    "upstream": {
        "published_route_contract_sha256": EXPECTED_ROUTE_SHA256,
        "ampgram_cell24_selftest_sha256": EXPECTED_AMPGRAM_SELFTEST_SHA256,
    },
}

CORRECTED_STATUS = "AMPEP_AUTHOR_RELEASE_105DF_CONTRACT_LOCKED"

if AMPEP_CONTRACT_PATH.exists():
    existing_sha = sha256_file(AMPEP_CONTRACT_PATH)
    existing_payload = load_json(AMPEP_CONTRACT_PATH)

    if (
        existing_payload.get("status") == CORRECTED_STATUS
        and existing_payload.get("contract") == AMPEP_CONTRACT_CORE
    ):
        CONTRACT_ACTION = "EXISTING IDENTICAL CORRECTED CELL-25 CONTRACT VERIFIED"
    else:
        # Only the exact known v1 contract is eligible for explicit supersession.
        assert existing_sha == SUPERSEDED_CELL25_V1_SHA256, (
            "Cell 25 contract differs from both the corrected v2 contract and the exact "
            "known v1 contract. Refusing silent overwrite.\n"
            f"Observed SHA256: {existing_sha}"
        )
        if SUPERSEDED_CELL25_PATH.exists():
            assert sha256_file(SUPERSEDED_CELL25_PATH) == SUPERSEDED_CELL25_V1_SHA256
        else:
            tmp_old = SUPERSEDED_CELL25_PATH.with_name(SUPERSEDED_CELL25_PATH.name + ".tmp")
            shutil.copy2(AMPEP_CONTRACT_PATH, tmp_old)
            assert sha256_file(tmp_old) == SUPERSEDED_CELL25_V1_SHA256
            os.replace(tmp_old, SUPERSEDED_CELL25_PATH)

        corrected_payload = {
            "schema_version": "2.0",
            "created_at": datetime.now().astimezone().isoformat(),
            "status": CORRECTED_STATUS,
            "restart_safe": True,
            "implementation_validated": False,
            "benchmark_training_performed": False,
            "benchmark_test_used": False,
            "external_target_used": False,
            "supersedes": {
                "path": str(SUPERSEDED_CELL25_PATH),
                "sha256": SUPERSEDED_CELL25_V1_SHA256,
                "reason": (
                    "v1 incorrectly made the paper's reduced 23-feature variant a mandatory "
                    "implementation dependency; author-release source proves canonical main_function uses all 105 D_F features."
                ),
            },
            "contract": AMPEP_CONTRACT_CORE,
        }
        atomic_write_json(AMPEP_CONTRACT_PATH, corrected_payload)
        CONTRACT_ACTION = "KNOWN CELL-25 v1 ARCHIVED; CORRECTED v2 CONTRACT ATOMICALLY COMMITTED"
else:
    corrected_payload = {
        "schema_version": "2.0",
        "created_at": datetime.now().astimezone().isoformat(),
        "status": CORRECTED_STATUS,
        "restart_safe": True,
        "implementation_validated": False,
        "benchmark_training_performed": False,
        "benchmark_test_used": False,
        "external_target_used": False,
        "supersedes": None,
        "contract": AMPEP_CONTRACT_CORE,
    }
    atomic_write_json(AMPEP_CONTRACT_PATH, corrected_payload)
    CONTRACT_ACTION = "NEW CORRECTED CELL-25 CONTRACT ATOMICALLY COMMITTED"

contract_check = load_json(AMPEP_CONTRACT_PATH)
assert contract_check["status"] == CORRECTED_STATUS
assert contract_check["contract"] == AMPEP_CONTRACT_CORE
assert contract_check["implementation_validated"] is False
assert contract_check["benchmark_training_performed"] is False
assert contract_check["benchmark_test_used"] is False
assert contract_check["external_target_used"] is False
CONTRACT_SHA256 = sha256_file(AMPEP_CONTRACT_PATH)


# ============================================================
# 10. UPDATE ONLY AmPEP READINESS ROW; DO NOT TOUCH GLOBAL GATE
# ============================================================

readiness = pd.read_csv(READINESS_PATH, low_memory=False)
required_cols = {
    "model_id", "local_source_found", "local_source_path", "local_git_commit",
    "local_state", "adapter_self_test_passed", "implementation_validated", "training_allowed"
}
missing_cols = required_cols - set(readiness.columns)
assert not missing_cols, f"Readiness table missing columns: {sorted(missing_cols)}"

mask = readiness["model_id"].astype(str) == "ampep"
assert int(mask.sum()) == 1

readiness.loc[mask, "local_source_found"] = True
readiness.loc[mask, "local_source_path"] = str(AMPEP_SOURCE_ROOT)
readiness.loc[mask, "local_git_commit"] = MIRROR_COMMIT
readiness.loc[mask, "local_state"] = "AUTHOR_RELEASE_105DF_SOURCE_LOCKED_SELFTEST_PENDING"
readiness.loc[mask, "adapter_self_test_passed"] = False
readiness.loc[mask, "implementation_validated"] = False
readiness.loc[mask, "training_allowed"] = False
atomic_write_csv(READINESS_PATH, readiness)

readiness_check = pd.read_csv(READINESS_PATH, low_memory=False)
mask2 = readiness_check["model_id"].astype(str) == "ampep"
assert int(mask2.sum()) == 1
assert boolish(readiness_check.loc[mask2, "local_source_found"].iloc[0]) is True
assert boolish(readiness_check.loc[mask2, "adapter_self_test_passed"].iloc[0]) is False
assert boolish(readiness_check.loc[mask2, "implementation_validated"].iloc[0]) is False
assert boolish(readiness_check.loc[mask2, "training_allowed"].iloc[0]) is False
assert readiness_check.loc[mask2, "local_state"].iloc[0] == "AUTHOR_RELEASE_105DF_SOURCE_LOCKED_SELFTEST_PENDING"


# ============================================================
# 11. FINAL HARD GATE / SCIENTIFIC BOUNDARY CHECKS
# ============================================================

# The global gate must be byte-identical to its pre-cell state.
assert sha256_file(TRAINING_GATE_PATH) == GATE_SHA_BEFORE, (
    "Cell 25 must not modify the global training gate."
)
gate_after = load_json(TRAINING_GATE_PATH)
assert gate_after == gate_before
assert gate_after["open"] is False
assert gate_after["benchmark_training_allowed"] is False
assert gate_after["published_methods_implementation_validated"] == 2
assert sorted(gate_after["validated_methods"]) == ["ampgram", "ampir"]

# Canonical source facts must remain exact.
assert len(registry_df) == 105
assert TREEBAGGER_NUM_TREES == 100
assert TREEBAGGER_MTRY_105 == 11
assert contract_check["contract"]["route_resolution"]["exact_23_registry_required_for_canonical_ampep"] is False
assert contract_check["contract"]["implementation_boundary"]["benchmark_training_performed"] is False


# ============================================================
# 12. FINAL REPORT
# ============================================================

print("=" * 128)
print("CELL 25 PASS - AmPEP AUTHOR-RELEASE SOURCE + CANONICAL 105-D_F CONTRACT CORRECTED AND LOCKED")
print("=" * 128)
print("Published method       : AmPEP")
print("DOI                    : 10.1038/s41598-018-19752-w")
print("Locked route           : faithful_reimplementation_from_publication")
print("Source acquisition     :", SOURCE_ACQUISITION)
print("Source origin          :", SOURCE_ORIGIN)
print("Pinned mirror commit   :", MIRROR_COMMIT)
print("Source files exact     : 8/8 - PASS")
print("-")
print("AUTHOR-RELEASE EXECUTION PATH")
print("main_function           : PASS")
print("Seq2Distribution        : PASS")
print("train_seqs2distribution: PASS")
print("test_seqs2distribution : PASS")
print("RF_test_yan             : PASS")
print("Canonical predictors    : 105 D_F")
print("Exact 105 registry      : PASS")
print("RF                     : MATLAB TreeBagger, 100 trees")
print("TreeBagger mtry(105)    : 11 (ceil(sqrt(105)))")
print("Positive score          : score(:,2)")
print("-")
print("PAPER VARIANT RESOLUTION")
print("Full D_F                : 105 - CANONICAL AUTHOR-RELEASE main_function")
print("Reduced D_F PCC<0.5     : 23 - PUBLISHED EVALUATED VARIANT")
print("Exact 23 registry needed: FALSE for canonical author-release AmPEP")
print("PDF Table S1 parser     : NOT REQUIRED")
print("-")
print("SCIENTIFIC STATUS")
print("Benchmark data read     : FALSE")
print("Feature calculation     : FALSE")
print("Feature selection       : FALSE")
print("RF fitted               : FALSE")
print("Benchmark training      : FALSE")
print("Benchmark test used     : FALSE")
print("External target used    : FALSE")
print("AmPEP validated         : FALSE - FULL ADAPTER SELF-TEST STILL REQUIRED")
print("Published validated     : 2/7")
print("Validated methods       : ['ampgram', 'ampir']")
print("Training gate modified  : FALSE")
print("TRAINING GATE           : CLOSED")
print("-")
print("Registry action         :", REGISTRY_ACTION)
print("Source audit action     :", SOURCE_AUDIT_ACTION)
print("Contract action         :", CONTRACT_ACTION)
print("105-D_F registry        :", AMPEP_105_REGISTRY_PATH)
print("Registry SHA256         :", REGISTRY_SHA256)
print("Source audit            :", SOURCE_AUDIT_PATH)
print("Source audit SHA256     :", SOURCE_AUDIT_SHA256)
print("Contract                :", AMPEP_CONTRACT_PATH)
print("Contract SHA256         :", CONTRACT_SHA256)
print("NEXT                    : CELL 26 - 105-D_F ORACLE + FULL AmPEP ADAPTER SELF-TEST")
print("=" * 128)

================================================================================================================================
CELL 25 PASS - AmPEP AUTHOR-RELEASE SOURCE + CANONICAL 105-D_F CONTRACT CORRECTED AND LOCKED
================================================================================================================================
Published method       : AmPEP
DOI                    : 10.1038/s41598-018-19752-w
Locked route           : faithful_reimplementation_from_publication
Source acquisition     : ACQUIRED PINNED PUBLIC MIRROR OF AUTHOR RELEASE
Source origin          : https://github.com/lassebuur/bacteriocin_classifier/tree/1fedfe1c3203fdd5a417ba1c2e92123478f2cfc0/code_modules/ampep/ampep-matlab-code
Pinned mirror commit   : 1fedfe1c3203fdd5a417ba1c2e92123478f2cfc0
Source files exact     : 8/8 - PASS
-
AUTHOR-RELEASE EXECUTION PATH
main_function           : PASS
Seq2Distribution        : PASS
train_seqs2distribution: PASS
test_seqs2distribution : PASS
RF_test_yan             : PASS
Canonical predictors    : 105 D_F
Exact 105 registry      : PASS
RF                     : MATLAB TreeBagger, 100 trees
TreeBagger mtry(105)    : 11 (ceil(sqrt(105)))
Positive score          : score(:,2)
-
PAPER VARIANT RESOLUTION
Full D_F                : 105 - CANONICAL AUTHOR-RELEASE main_function
Reduced D_F PCC<0.5     : 23 - PUBLISHED EVALUATED VARIANT
Exact 23 registry needed: FALSE for canonical author-release AmPEP
PDF Table S1 parser     : NOT REQUIRED
-
SCIENTIFIC STATUS
Benchmark data read     : FALSE
Feature calculation     : FALSE
Feature selection       : FALSE
RF fitted               : FALSE
Benchmark training      : FALSE
Benchmark test used     : FALSE
External target used    : FALSE
AmPEP validated         : FALSE - FULL ADAPTER SELF-TEST STILL REQUIRED
Published validated     : 2/7
Validated methods       : ['ampgram', 'ampir']
Training gate modified  : FALSE
TRAINING GATE           : CLOSED
-
Registry action         : NEW 105-D_F REGISTRY ATOMICALLY COMMITTED
Source audit action     : NEW AUTHOR-RELEASE SOURCE AUDIT COMMITTED
Contract action         : KNOWN CELL-25 v1 ARCHIVED; CORRECTED v2 CONTRACT ATOMICALLY COMMITTED
105-D_F registry        : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_ampep_author_release_105DF_registry.csv
Registry SHA256         : f50877295c3fcb500ff8b2aaaf3da906ad5e652e30da16f7b961cc24b08844b1
Source audit            : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampep_author_release_source_audit.json
Source audit SHA256     : 0fde32e54585627e2cf6266acbd3586a60d7c63ce53871899be072d9325f35e5
Contract                : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampep_FINAL_publication_source_contract.json
Contract SHA256         : 70502c65de5bcc6d776fb10a994db06426cb886c3fe40c0a609e87f41244b6cb
NEXT                    : CELL 26 - 105-D_F ORACLE + FULL AmPEP ADAPTER SELF-TEST
================================================================================================================================

In [15]:
# ============================================================
# CELL 26 - RESTART-SAFE FULL REPLACEMENT
# AmPEP 105-D_F ORACLE + FULL ADAPTER END-TO-END SELF-TEST
#
# STAGE
# -----
# SOURCE -> CONTRACT -> SELF-TEST -> VALIDATE -> LOCK
#
# PURPOSE
# -------
# 1. Verify the corrected Cell 25 author-release 105-D_F contract byte-for-byte.
# 2. Re-verify the exact pinned AmPEP MATLAB source closure used by Cell 25.
# 3. Reimplement Seq2Distribution.m literally for all 105 D_F descriptors.
# 4. Validate the D_F implementation with:
#      a) exact 105-name registry/order,
#      b) manually derived source-level oracle values,
#      c) an independent registry-driven oracle across deterministic sequences.
# 5. Run a synthetic-only full AmPEP adapter self-test:
#      sequence -> 105 D_F -> RF(100, mtry=11) -> P(class=1)
# 6. Verify serialization/reload, class-column semantics, and deterministic replay.
# 7. ONLY after all checks pass, commit the immutable self-test manifest,
#    mark AmPEP implementation validated, and recompute the global 7-method gate.
#
# SCIENTIFIC BOUNDARY
# -------------------
# - NO benchmark train/validation/test data are read.
# - NO external target data are read.
# - NO feature selection is performed.
# - The canonical author-release AmPEP path uses all 105 D_F descriptors.
# - The RF is a method-faithful Python reimplementation of the locked
#   TreeBagger recipe: 100 trees, 105 predictors, mtry=11, bootstrap bagging.
# - This cell does NOT start benchmark training.
# ============================================================

from pathlib import Path
from datetime import datetime
import hashlib
import json
import math
import os
import pickle
import random
import shutil
import tempfile

import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
import sklearn


# ============================================================
# 1. PATHS / EXACT UPSTREAM LOCKS
# ============================================================

PROJECT_ROOT = Path("/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026")
OUTPUT_ROOT = PROJECT_ROOT / "benchmark17_outputs"
AUDIT_DIR = OUTPUT_ROOT / "audit"
MANIFEST_DIR = OUTPUT_ROOT / "manifests"
WORK_ROOT = Path("/home/pc/genpept_benchmark17_work")
SELFTEST_ROOT = WORK_ROOT / "published_selftests" / "ampep"
SOURCE_ROOT = Path("/home/pc/genpept_sources")
AMPEP_SOURCE_ROOT = SOURCE_ROOT / "AmPEP_author_release"

ROUTE_CONTRACT_PATH = MANIFEST_DIR / "benchmark17_FINAL_published_method_route_contract.json"
TRAINING_GATE_PATH = MANIFEST_DIR / "benchmark17_FINAL_training_gate.json"
READINESS_PATH = AUDIT_DIR / "benchmark17_published_method_local_readiness_latest.csv"
AMPGRAM_SELFTEST_PATH = MANIFEST_DIR / "benchmark17_ampgram_FINAL_adapter_selftest.json"
AMPIR_SELFTEST_PATH = MANIFEST_DIR / "benchmark17_ampir_FINAL_adapter_selftest.json"

CELL25_CONTRACT_PATH = MANIFEST_DIR / "benchmark17_ampep_FINAL_publication_source_contract.json"
CELL25_SOURCE_AUDIT_PATH = MANIFEST_DIR / "benchmark17_ampep_author_release_source_audit.json"
CELL25_REGISTRY_PATH = AUDIT_DIR / "benchmark17_ampep_author_release_105DF_registry.csv"

SELFTEST_MANIFEST_PATH = MANIFEST_DIR / "benchmark17_ampep_FINAL_adapter_selftest.json"
FINAL_BUNDLE_DIR = SELFTEST_ROOT / "cell26_105df_final_adapter_selftest"

EXPECTED_ROUTE_SHA256 = "dd7d6a743f088cef95fb49288dcf1801c9dc335be2656e627e7fc7f3bf7170bd"
EXPECTED_AMPGRAM_SELFTEST_SHA256 = "399d1d695e72f42ad591caf637de03b910d07e09b1f1f5805054e629153aee3d"
EXPECTED_CELL25_CONTRACT_SHA256 = "70502c65de5bcc6d776fb10a994db06426cb886c3fe40c0a609e87f41244b6cb"
EXPECTED_CELL25_SOURCE_AUDIT_SHA256 = "0fde32e54585627e2cf6266acbd3586a60d7c63ce53871899be072d9325f35e5"
EXPECTED_CELL25_REGISTRY_SHA256 = "f50877295c3fcb500ff8b2aaaf3da906ad5e652e30da16f7b961cc24b08844b1"

PUBLISHED_IDS = [
    "ampep",
    "ampscannerv2",
    "ampgram",
    "ampir",
    "ampeppy",
    "ai4amp",
    "amplify",
]

for directory in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    WORK_ROOT,
    SOURCE_ROOT,
    AMPEP_SOURCE_ROOT,
]:
    assert directory.is_dir(), f"Required directory missing:\n{directory}"

SELFTEST_ROOT.mkdir(parents=True, exist_ok=True)

for path in [
    ROUTE_CONTRACT_PATH,
    TRAINING_GATE_PATH,
    READINESS_PATH,
    AMPGRAM_SELFTEST_PATH,
    AMPIR_SELFTEST_PATH,
    CELL25_CONTRACT_PATH,
    CELL25_SOURCE_AUDIT_PATH,
    CELL25_REGISTRY_PATH,
]:
    assert path.is_file(), f"Required upstream artifact missing:\n{path}"


# ============================================================
# 2. HELPERS
# ============================================================

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def git_blob_sha1_bytes(data: bytes) -> str:
    header = f"blob {len(data)}\0".encode("ascii")
    return hashlib.sha1(header + data).hexdigest()


def git_blob_sha1_file(path: Path) -> str:
    return git_blob_sha1_bytes(path.read_bytes())


def load_json(path: Path):
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def atomic_write_json(path: Path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".tmp.", dir=str(path.parent))
    os.close(fd)
    tmp = Path(tmp_name)
    try:
        with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(payload, fh, indent=2, ensure_ascii=False, sort_keys=True)
            fh.write("\n")
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def atomic_write_csv(path: Path, df: pd.DataFrame):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".tmp.", dir=str(path.parent))
    os.close(fd)
    tmp = Path(tmp_name)
    try:
        df.to_csv(tmp, index=False)
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def boolish(value):
    if isinstance(value, (bool, np.bool_)):
        return bool(value)
    if pd.isna(value):
        return False
    return str(value).strip().lower() in {"true", "1", "yes", "y"}


def normalize_sequence(seq: str) -> str:
    seq = str(seq).strip().upper()
    assert len(seq) > 0
    allowed = set("ACDEFGHIKLMNPQRSTVWY")
    assert set(seq).issubset(allowed), f"Non-canonical amino acid in sequence: {seq}"
    return seq


def verify_artifact_entry(entry):
    path = Path(entry["path"])
    assert path.is_file(), f"Artifact missing: {path}"
    assert path.stat().st_size == int(entry["size_bytes"]), f"Artifact size changed: {path}"
    assert sha256_file(path) == entry["sha256"], f"Artifact SHA256 changed: {path}"


# ============================================================
# 3. VERIFY EXACT CELL 25 CONTINUITY + CLOSED GATE
# ============================================================

assert sha256_file(ROUTE_CONTRACT_PATH) == EXPECTED_ROUTE_SHA256, (
    "Published-method route contract changed. Refusing to continue."
)
assert sha256_file(AMPGRAM_SELFTEST_PATH) == EXPECTED_AMPGRAM_SELFTEST_SHA256, (
    "AmpGram self-test manifest changed. Refusing to continue."
)
assert sha256_file(CELL25_CONTRACT_PATH) == EXPECTED_CELL25_CONTRACT_SHA256, (
    "Corrected Cell 25 AmPEP contract changed. Refusing to continue."
)
assert sha256_file(CELL25_SOURCE_AUDIT_PATH) == EXPECTED_CELL25_SOURCE_AUDIT_SHA256, (
    "Cell 25 AmPEP source audit changed. Refusing to continue."
)
assert sha256_file(CELL25_REGISTRY_PATH) == EXPECTED_CELL25_REGISTRY_SHA256, (
    "Cell 25 exact 105-D_F registry changed. Refusing to continue."
)

route_payload = load_json(ROUTE_CONTRACT_PATH)
assert route_payload["status"] == "PUBLISHED_METHOD_ROUTES_LOCKED_BEFORE_TRAINING"
assert route_payload["restart_safe"] is True
route_core = route_payload["contract"]
assert route_core["published_model_ids"] == PUBLISHED_IDS

ampep_route = route_core["methods"]["ampep"]
assert ampep_route["paper_doi"] == "10.1038/s41598-018-19752-w"
assert ampep_route["published_family"] == "random_forest"
assert ampep_route["locked_route"] == "faithful_reimplementation_from_publication"
assert ampep_route["original_training_software"] == "MATLAB_TreeBagger"

cell25 = load_json(CELL25_CONTRACT_PATH)
assert cell25["status"] == "AMPEP_AUTHOR_RELEASE_105DF_CONTRACT_LOCKED"
assert cell25["implementation_validated"] is False
assert cell25["benchmark_training_performed"] is False
assert cell25["benchmark_test_used"] is False
assert cell25["external_target_used"] is False

cell25_core = cell25["contract"]
assert cell25_core["model_id"] == "ampep"
assert cell25_core["route_resolution"]["canonical_benchmark_variant"] == "author_release_full_DF_105"
assert cell25_core["route_resolution"]["exact_23_registry_required_for_canonical_ampep"] is False
assert cell25_core["representation"]["count"] == 105
assert cell25_core["representation"]["registry_sha256"] == EXPECTED_CELL25_REGISTRY_SHA256
assert cell25_core["random_forest"]["trees"] == 100
assert cell25_core["random_forest"]["predictors"] == 105
assert cell25_core["random_forest"]["treebagger_default_mtry_for_105"] == 11
assert cell25_core["random_forest"]["positive_score"] == "TreeBagger predict() score column 2"

for model_id, path in [
    ("ampgram", AMPGRAM_SELFTEST_PATH),
    ("ampir", AMPIR_SELFTEST_PATH),
]:
    payload = load_json(path)
    assert payload["status"] == "IMPLEMENTATION_VALIDATED"
    assert payload["implementation_validated"] is True
    observed = payload.get("model_id") or payload.get("adapter_contract", {}).get("model_id")
    assert observed == model_id
    assert payload["benchmark_training_performed"] is False
    assert payload["benchmark_test_used"] is False

# First run requires the known 2/7 state. A successful rerun may already be 3/7.
gate_before = load_json(TRAINING_GATE_PATH)
assert gate_before["open"] is False
assert gate_before["benchmark_training_allowed"] is False
if not SELFTEST_MANIFEST_PATH.exists():
    assert gate_before["published_methods_implementation_validated"] == 2
    assert sorted(gate_before.get("validated_methods", [])) == ["ampgram", "ampir"]
else:
    assert gate_before["published_methods_implementation_validated"] >= 3
    assert "ampep" in gate_before.get("validated_methods", [])


# ============================================================
# 4. RE-VERIFY EXACT AUTHOR-RELEASE SOURCE CLOSURE
# ============================================================

EXPECTED_SOURCE_BLOBS = {
    "README.txt": "9fd99b122e2bd9a63c01e232632f9022433e09d9",
    "main_function.m": "931370156d4256d5393fdd54bb35cb91711afecf",
    "RF_test_yan.m": "285307459a96f8445dbde14d2e3f26d6b7291b08",
    "Seq2Distribution.m": "7dd28d6f2116d86f3e407d4897148c2fc0a128c0",
    "train_seqs2distribution.m": "7b22939623cbecd8eba2677adb2b303d998f200f",
    "test_seqs2distribution.m": "e424e3b97a2dc8f922d4ad978a6ca222f4ffa395",
    "trian_po_set3298_for_ampep_sever.fasta": "b424bf408cb84b2f3d669fdbf100e7ec3eca514f",
    "trian_ne_set9894_for_ampep_sever.fasta": "36519de57843569429f65adee132a609a8324b01",
}

for name, expected_blob in EXPECTED_SOURCE_BLOBS.items():
    path = AMPEP_SOURCE_ROOT / name
    assert path.is_file(), f"Pinned AmPEP source file missing: {path}"
    assert git_blob_sha1_file(path) == expected_blob, f"Pinned source changed: {name}"

SEQ_SOURCE_TEXT = (AMPEP_SOURCE_ROOT / "Seq2Distribution.m").read_text(
    encoding="utf-8", errors="replace"
).replace("\r\n", "\n").replace("\r", "\n")
RF_SOURCE_TEXT = (AMPEP_SOURCE_ROOT / "RF_test_yan.m").read_text(
    encoding="utf-8", errors="replace"
).replace("\r\n", "\n").replace("\r", "\n")

assert "for i = 1:7" in SEQ_SOURCE_TEXT
assert "for j = 1:3" in SEQ_SOURCE_TEXT
assert "residue0 = 100*index_aa(1)/len_seq;" in SEQ_SOURCE_TEXT
assert "floor(len_common*0.25)" in SEQ_SOURCE_TEXT
assert "floor(len_common*0.5)" in SEQ_SOURCE_TEXT
assert "floor(len_common*0.75)" in SEQ_SOURCE_TEXT
assert "residue100 = 100*index_aa(floor(len_common))/len_seq;" in SEQ_SOURCE_TEXT
assert "TreeBagger(100,train(:,1:end-1),train(:,end))" in "".join(RF_SOURCE_TEXT.split())
assert "sco=score(:,2);" in "".join(RF_SOURCE_TEXT.split())


# ============================================================
# 5. EXACT 105-D_F REGISTRY / SOURCE GROUPS
# ============================================================

registry = pd.read_csv(CELL25_REGISTRY_PATH, keep_default_na=False)
expected_columns = [
    "feature_index_1based",
    "property",
    "group",
    "amino_acids",
    "distribution",
    "matlab_feature_name",
    "canonical_author_release",
]
assert list(registry.columns) == expected_columns
assert len(registry) == 105
assert registry["feature_index_1based"].astype(int).tolist() == list(range(1, 106))
assert registry["matlab_feature_name"].nunique() == 105
assert all(registry["canonical_author_release"].map(boolish))

PROPERTY_GROUPS = [
    ("charge", ["ACFGHILMNPQSTVWY", "DE", "KR"]),
    ("hydrophobicity", ["CFILMVW", "AGHPSTY", "DEKNQR"]),
    ("normalized_vander_waals", ["ACDGPST", "EILNQV", "FHKMRWY"]),
    ("polarity", ["CFILMVWY", "AGPST", "DEHKNQR"]),
    ("polarizability", ["ADGST", "CEILNPQV", "FHKMRWY"]),
    ("secondary_structure", ["DGNPS", "AEHKLMQR", "CFITVWY"]),
    ("solvent_accessibility", ["ACFGILVW", "HMPSTY", "DEKNRQ"]),
]
RESIDUE_NAMES = ["residue0%", "residue25%", "residue50%", "residue75%", "residue100%"]

expected_registry_rows = []
idx = 1
for prop, groups in PROPERTY_GROUPS:
    for group_no, aas in enumerate(groups, start=1):
        for residue_name in RESIDUE_NAMES:
            expected_registry_rows.append(
                {
                    "feature_index_1based": idx,
                    "property": prop,
                    "group": f"group{group_no}",
                    "amino_acids": aas,
                    "distribution": residue_name,
                    "matlab_feature_name": f"{prop}_group{group_no}_{residue_name}",
                }
            )
            idx += 1

expected_registry = pd.DataFrame(expected_registry_rows)
for col in expected_registry.columns:
    assert registry[col].astype(str).tolist() == expected_registry[col].astype(str).tolist(), (
        f"Cell 25 registry content/order mismatch in column: {col}"
    )

FEATURE_NAMES = registry["matlab_feature_name"].tolist()
assert len(FEATURE_NAMES) == 105


# ============================================================
# 6. LITERAL Seq2Distribution.m REIMPLEMENTATION
# ============================================================

def _distribution_positions_matlab(index_aa_1based, seq_len):
    """Literal translation of the released Seq2Distribution.m logic."""
    n = len(index_aa_1based)
    if n == 0:
        return [0.0] * 5

    residue0 = 100.0 * index_aa_1based[0] / seq_len

    k25 = math.floor(n * 0.25)
    residue25 = residue0 if k25 == 0 else 100.0 * index_aa_1based[k25 - 1] / seq_len

    k50 = math.floor(n * 0.50)
    residue50 = residue0 if k50 == 0 else 100.0 * index_aa_1based[k50 - 1] / seq_len

    k75 = math.floor(n * 0.75)
    residue75 = residue0 if k75 == 0 else 100.0 * index_aa_1based[k75 - 1] / seq_len

    residue100 = 100.0 * index_aa_1based[n - 1] / seq_len
    return [residue0, residue25, residue50, residue75, residue100]


def seq2distribution_literal(seq: str):
    seq = normalize_sequence(seq)
    n = len(seq)
    values = []
    names = []
    for prop, groups in PROPERTY_GROUPS:
        for group_no, group in enumerate(groups, start=1):
            index_aa = [i for i, aa in enumerate(seq, start=1) if aa in group]
            dist_values = _distribution_positions_matlab(index_aa, n)
            values.extend(dist_values)
            names.extend(
                [f"{prop}_group{group_no}_{residue_name}" for residue_name in RESIDUE_NAMES]
            )

    out = np.asarray(values, dtype=np.float64)
    assert len(out) == 105
    assert names == FEATURE_NAMES
    assert np.all(np.isfinite(out))
    assert np.all((out >= 0.0) & (out <= 100.0))
    return out


# ============================================================
# 7. INDEPENDENT REGISTRY-DRIVEN ORACLE
# ============================================================

def seq2distribution_registry_oracle(seq: str):
    """Independent implementation driven row-by-row by the locked registry."""
    seq = normalize_sequence(seq)
    seq_len = len(seq)
    positions_by_group = {}

    for row in registry.itertuples(index=False):
        key = (row.property, row.group, row.amino_acids)
        if key not in positions_by_group:
            aa_set = set(str(row.amino_acids))
            positions_by_group[key] = [
                pos for pos, aa in enumerate(seq, start=1) if aa in aa_set
            ]

    result = []
    for row in registry.itertuples(index=False):
        pos = positions_by_group[(row.property, row.group, row.amino_acids)]
        if not pos:
            result.append(0.0)
            continue

        dist = str(row.distribution)
        n = len(pos)
        if dist == "residue0%":
            selected_pos = pos[0]
        elif dist == "residue25%":
            k = math.floor(n * 0.25)
            selected_pos = pos[0] if k == 0 else pos[k - 1]
        elif dist == "residue50%":
            k = math.floor(n * 0.50)
            selected_pos = pos[0] if k == 0 else pos[k - 1]
        elif dist == "residue75%":
            k = math.floor(n * 0.75)
            selected_pos = pos[0] if k == 0 else pos[k - 1]
        elif dist == "residue100%":
            selected_pos = pos[-1]
        else:
            raise AssertionError(f"Unexpected distribution label: {dist}")
        result.append(100.0 * selected_pos / seq_len)

    out = np.asarray(result, dtype=np.float64)
    assert out.shape == (105,)
    return out


# ============================================================
# 8. HARD D_F ORACLES - MANUAL + CROSS-IMPLEMENTATION
# ============================================================

# Manual source-level oracle for the first 15 features (charge property)
# on the canonical 20-amino-acid sequence ACDEFGHIKLMNPQRSTVWY.
ORACLE_SEQ = "ACDEFGHIKLMNPQRSTVWY"
oracle_vec = seq2distribution_literal(ORACLE_SEQ)
manual_charge_15 = np.asarray(
    [
        5.0, 30.0, 55.0, 80.0, 100.0,   # charge group1
        15.0, 15.0, 15.0, 15.0, 20.0,  # charge group2 D/E at positions 3,4
        45.0, 45.0, 45.0, 45.0, 75.0,  # charge group3 K/R at positions 9,15
    ],
    dtype=np.float64,
)
assert np.allclose(oracle_vec[:15], manual_charge_15, rtol=0.0, atol=1e-12), (
    f"Manual D_F oracle mismatch.\nExpected={manual_charge_15}\nObserved={oracle_vec[:15]}"
)

# Empty-group and floor-index edge-case oracle.
edge_vec = seq2distribution_literal("AAAAAA")
expected_charge_A6 = np.asarray(
    [
        100.0 / 6.0, 100.0 / 6.0, 50.0, 400.0 / 6.0, 100.0,
        0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0,
    ]
)
assert np.allclose(edge_vec[:15], expected_charge_A6, rtol=0.0, atol=1e-12)

# Independent whole-vector comparison over deterministic edge and random sequences.
oracle_sequences = [
    ORACLE_SEQ,
    "AAAAAA",
    "KKKKKK",
    "DDDDDD",
    "KRLWVFIDEAGSTNQPHCMY",
    "MKWVTFISLLFLFSSAYSRGVFRR",
]
_rng_oracle = random.Random(2601)
AA20 = "ACDEFGHIKLMNPQRSTVWY"
for i in range(24):
    length = 10 + (i % 31)
    oracle_sequences.append("".join(_rng_oracle.choice(AA20) for _ in range(length)))

max_oracle_delta = 0.0
for seq in oracle_sequences:
    a = seq2distribution_literal(seq)
    b = seq2distribution_registry_oracle(seq)
    delta = float(np.max(np.abs(a - b)))
    max_oracle_delta = max(max_oracle_delta, delta)
    assert delta <= 1e-12, f"D_F oracle mismatch for sequence {seq}: {delta}"

assert max_oracle_delta <= 1e-12


# ============================================================
# 9. SYNTHETIC-ONLY DATASET - AUTHOR PAPER RATIO 1:3
# ============================================================

SELFTEST_SEED = 100
TRAIN_POS = 32
TRAIN_NEG = 96
VAL_POS = 16
VAL_NEG = 48
assert TRAIN_NEG == 3 * TRAIN_POS
assert VAL_NEG == 3 * VAL_POS

POS_MOTIFS = [
    "KRFWILVM",
    "RWKLFIVC",
    "KRLWVFIM",
    "RKWLIFVC",
]
NEG_MOTIFS = [
    "DEAGSTNQ",
    "EEDGNQST",
    "DENTQGSP",
    "EDQNSTAG",
]


def make_synthetic_sequence(label: int, index: int, split: str) -> str:
    assert label in (0, 1)
    assert split in {"train", "validation"}
    motifs = POS_MOTIFS if label == 1 else NEG_MOTIFS
    motif = motifs[index % len(motifs)]
    offset = (index * 3 + (0 if split == "train" else 1)) % len(motif)
    rotated = motif[offset:] + motif[:offset]
    length = 18 + ((index * 7 + label * 5 + (11 if split == "validation" else 0)) % 33)
    repeats = (length // len(rotated)) + 2
    seq = (rotated * repeats)[:length]

    # Deterministic sparse perturbation stays within the same class-specific alphabet
    # and prevents duplicated feature rows without introducing benchmark information.
    seq_list = list(seq)
    class_alphabet = "KRFWILVMHC" if label == 1 else "DEAGSTNQP"
    if len(seq_list) >= 12:
        p1 = (index * 5 + label) % len(seq_list)
        p2 = (index * 11 + 3) % len(seq_list)
        seq_list[p1] = class_alphabet[(index + 2) % len(class_alphabet)]
        seq_list[p2] = class_alphabet[(index + 5) % len(class_alphabet)]
    return normalize_sequence("".join(seq_list))


def build_synthetic_split(n_pos: int, n_neg: int, split: str) -> pd.DataFrame:
    rows = []
    for i in range(n_pos):
        rows.append({
            "sequence_id": f"{split}_AMP_{i:03d}",
            "sequence": make_synthetic_sequence(1, i, split),
            "label": 1,
            "class_name": "AMP",
        })
    for i in range(n_neg):
        rows.append({
            "sequence_id": f"{split}_NONAMP_{i:03d}",
            "sequence": make_synthetic_sequence(0, i, split),
            "label": 0,
            "class_name": "non-AMP",
        })
    df = pd.DataFrame(rows)
    assert df["sequence_id"].is_unique
    assert int((df["label"] == 1).sum()) == n_pos
    assert int((df["label"] == 0).sum()) == n_neg
    assert all(df["sequence"].map(lambda s: set(s).issubset(set(AA20))))
    return df


train_df = build_synthetic_split(TRAIN_POS, TRAIN_NEG, "train")
val_df = build_synthetic_split(VAL_POS, VAL_NEG, "validation")
assert len(train_df) == 128
assert len(val_df) == 64
assert set(train_df["sequence_id"]).isdisjoint(set(val_df["sequence_id"]))


def feature_matrix(df: pd.DataFrame) -> np.ndarray:
    matrix = np.vstack([seq2distribution_literal(s) for s in df["sequence"]])
    assert matrix.shape == (len(df), 105)
    assert np.all(np.isfinite(matrix))
    assert np.all((matrix >= 0.0) & (matrix <= 100.0))
    return matrix


X_train = feature_matrix(train_df)
y_train = train_df["label"].to_numpy(dtype=np.int64)
X_val = feature_matrix(val_df)
y_val = val_df["label"].to_numpy(dtype=np.int64)

assert X_train.shape == (128, 105)
assert X_val.shape == (64, 105)
assert set(np.unique(y_train).tolist()) == {0, 1}
assert set(np.unique(y_val).tolist()) == {0, 1}
assert int(y_train.sum()) == TRAIN_POS
assert int(y_val.sum()) == VAL_POS

# Ensure the mechanics exercise non-constant representation columns.
nonconstant_train_features = int(np.sum(np.ptp(X_train, axis=0) > 0.0))
assert nonconstant_train_features >= 70, (
    f"Synthetic self-test under-exercises D_F representation: only {nonconstant_train_features}/105 varying features."
)


# ============================================================
# 10. METHOD-FAITHFUL 100-TREE RF ADAPTER
# ============================================================

N_TREES = int(cell25_core["random_forest"]["trees"])
MTRY = int(cell25_core["random_forest"]["treebagger_default_mtry_for_105"])
assert N_TREES == 100
assert MTRY == 11
assert math.ceil(math.sqrt(105)) == 11


def make_ampep_rf(seed: int):
    # Locked recipe: TreeBagger classification semantics reimplemented with
    # bootstrap-bagged CART classification trees and the exact mtry count.
    return RandomForestClassifier(
        n_estimators=100,
        criterion="gini",
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        min_weight_fraction_leaf=0.0,
        max_features=11,
        max_leaf_nodes=None,
        min_impurity_decrease=0.0,
        bootstrap=True,
        oob_score=False,
        n_jobs=1,
        random_state=seed,
        verbose=0,
        warm_start=False,
        class_weight=None,
        ccp_alpha=0.0,
        max_samples=None,
    )


model = make_ampep_rf(SELFTEST_SEED)
model.fit(X_train, y_train)

assert len(model.estimators_) == 100
assert np.array_equal(model.classes_, np.asarray([0, 1]))
assert all(int(tree.max_features_) == 11 for tree in model.estimators_)
assert model.bootstrap is True
assert model.max_samples is None
assert model.class_weight is None

val_proba_matrix = model.predict_proba(X_val)
assert val_proba_matrix.shape == (len(val_df), 2)
assert np.all(np.isfinite(val_proba_matrix))
assert np.all(val_proba_matrix >= 0.0)
assert np.all(val_proba_matrix <= 1.0)
assert np.allclose(val_proba_matrix.sum(axis=1), 1.0, atol=1e-12, rtol=0.0)

positive_class_index = int(np.where(model.classes_ == 1)[0][0])
assert positive_class_index == 1
amp_score = val_proba_matrix[:, positive_class_index]
assert np.all((amp_score >= 0.0) & (amp_score <= 1.0))
assert float(np.ptp(amp_score)) > 0.0

predicted_label = model.predict(X_val).astype(np.int64)
assert predicted_label.shape == (len(val_df),)
assert set(np.unique(predicted_label).tolist()).issubset({0, 1})

# Synthetic sanity check only: not a benchmark metric claim.
pos_mean_score = float(np.mean(amp_score[y_val == 1]))
neg_mean_score = float(np.mean(amp_score[y_val == 0]))
assert pos_mean_score > neg_mean_score, (
    f"Synthetic adapter sanity failed: mean AMP score {pos_mean_score} <= mean non-AMP score {neg_mean_score}"
)


# ============================================================
# 11. DETERMINISTIC REPLAY CHECK
# ============================================================

model_replay = make_ampep_rf(SELFTEST_SEED)
model_replay.fit(X_train, y_train)
replay_proba = model_replay.predict_proba(X_val)
replay_delta = float(np.max(np.abs(replay_proba - val_proba_matrix)))
assert replay_delta <= 1e-15, f"Deterministic RF replay mismatch: {replay_delta}"
assert np.array_equal(model_replay.predict(X_val), predicted_label)


# ============================================================
# 12. BUILD TEMP SELF-TEST BUNDLE
# ============================================================

# If the top-level manifest already exists, the reuse path below handles it.
# If a previous process committed the final bundle but died before promoting the
# top-level manifest, recovery from the bundle-local manifest is supported.
BUNDLE_LOCAL_MANIFEST_NAME = "bundle_manifest.json"


def artifact_entry(path: Path):
    return {
        "path": str(path),
        "size_bytes": int(path.stat().st_size),
        "sha256": sha256_file(path),
    }


def validated_methods_from_manifests():
    validated = []
    for model_id in PUBLISHED_IDS:
        path = MANIFEST_DIR / f"benchmark17_{model_id}_FINAL_adapter_selftest.json"
        if not path.is_file():
            continue
        payload = load_json(path)
        if payload.get("implementation_validated", False) is True:
            validated.append(model_id)
    return sorted(validated)


def merge_readiness_and_gate():
    readiness = pd.read_csv(READINESS_PATH, low_memory=False)
    required_cols = {
        "model_id",
        "adapter_self_test_passed",
        "implementation_validated",
        "local_state",
        "training_allowed",
    }
    assert required_cols.issubset(readiness.columns), (
        f"Readiness table missing columns: {sorted(required_cols - set(readiness.columns))}"
    )

    mask = readiness["model_id"].astype(str) == "ampep"
    assert int(mask.sum()) == 1
    readiness.loc[mask, "adapter_self_test_passed"] = True
    readiness.loc[mask, "implementation_validated"] = True
    readiness.loc[mask, "local_state"] = "IMPLEMENTATION_VALIDATED"

    validated = validated_methods_from_manifests()
    assert "ampep" in validated
    assert "ampgram" in validated
    assert "ampir" in validated
    assert 3 <= len(validated) <= 7

    gate = load_json(TRAINING_GATE_PATH)
    gate["published_methods_implementation_validated"] = len(validated)
    gate["validated_methods"] = validated

    if len(validated) == 7:
        gate["open"] = True
        gate["benchmark_training_allowed"] = True
        gate["reason"] = "All seven published-method implementations validated."
        readiness.loc[:, "training_allowed"] = True
    else:
        gate["open"] = False
        gate["benchmark_training_allowed"] = False
        gate["reason"] = f"{len(validated)}/7 published-method implementations validated."
        readiness.loc[mask, "training_allowed"] = False

    gate["updated_at"] = datetime.now().astimezone().isoformat()
    atomic_write_csv(READINESS_PATH, readiness)
    atomic_write_json(TRAINING_GATE_PATH, gate)

    gate_check = load_json(TRAINING_GATE_PATH)
    readiness_check = pd.read_csv(READINESS_PATH, low_memory=False)
    mask_check = readiness_check["model_id"].astype(str) == "ampep"
    assert int(mask_check.sum()) == 1
    assert boolish(readiness_check.loc[mask_check, "adapter_self_test_passed"].iloc[0]) is True
    assert boolish(readiness_check.loc[mask_check, "implementation_validated"].iloc[0]) is True
    assert str(readiness_check.loc[mask_check, "local_state"].iloc[0]) == "IMPLEMENTATION_VALIDATED"
    assert gate_check["validated_methods"] == validated
    assert gate_check["published_methods_implementation_validated"] == len(validated)

    if len(validated) < 7:
        assert gate_check["open"] is False
        assert gate_check["benchmark_training_allowed"] is False
    else:
        assert gate_check["open"] is True
        assert gate_check["benchmark_training_allowed"] is True

    return validated, gate_check


def validate_selftest_manifest(payload):
    assert payload["status"] == "IMPLEMENTATION_VALIDATED"
    assert payload["model_id"] == "ampep"
    assert payload["implementation_validated"] is True
    assert payload["synthetic_selftest_only"] is True
    assert payload["benchmark_training_performed"] is False
    assert payload["benchmark_test_used"] is False
    assert payload["external_target_used"] is False
    assert payload["feature_selection_performed"] is False
    assert payload["adapter_contract"]["canonical_feature_count"] == 105
    assert payload["adapter_contract"]["rf_trees"] == 100
    assert payload["adapter_contract"]["rf_mtry"] == 11
    assert payload["adapter_contract"]["positive_score_class"] == 1
    assert payload["upstream"]["cell25_contract_sha256"] == EXPECTED_CELL25_CONTRACT_SHA256
    assert payload["upstream"]["cell25_registry_sha256"] == EXPECTED_CELL25_REGISTRY_SHA256
    assert payload["upstream"]["cell25_source_audit_sha256"] == EXPECTED_CELL25_SOURCE_AUDIT_SHA256
    for entry in payload["artifacts"].values():
        verify_artifact_entry(entry)


def reuse_or_recover_if_available():
    if SELFTEST_MANIFEST_PATH.is_file():
        payload = load_json(SELFTEST_MANIFEST_PATH)
        validate_selftest_manifest(payload)
        validated, gate_check = merge_readiness_and_gate()
        print("=" * 128)
        print("CELL 26 PASS - AMPEP 105-D_F FULL ADAPTER SELF-TEST REUSED AND VERIFIED")
        print("=" * 128)
        print("Implementation status  : VALIDATED")
        print("Run action             : EXISTING IMMUTABLE SELF-TEST VERIFIED")
        print("Published validated    : %d/7" % len(validated))
        print("Validated methods      :", validated)
        print("TRAINING GATE          :", "OPEN" if gate_check["open"] else "CLOSED")
        print("Self-test manifest     :", SELFTEST_MANIFEST_PATH)
        print("Manifest SHA256        :", sha256_file(SELFTEST_MANIFEST_PATH))
        print("=" * 128)
        return True

    if FINAL_BUNDLE_DIR.is_dir():
        local_manifest = FINAL_BUNDLE_DIR / BUNDLE_LOCAL_MANIFEST_NAME
        assert local_manifest.is_file(), (
            "Final Cell 26 bundle exists without either a top-level or bundle-local manifest.\n"
            f"Refusing silent recovery: {FINAL_BUNDLE_DIR}"
        )
        payload = load_json(local_manifest)
        validate_selftest_manifest(payload)
        atomic_write_json(SELFTEST_MANIFEST_PATH, payload)
        assert sha256_file(SELFTEST_MANIFEST_PATH) == sha256_file(local_manifest)
        validated, gate_check = merge_readiness_and_gate()
        print("=" * 128)
        print("CELL 26 PASS - AMPEP 105-D_F FULL ADAPTER SELF-TEST RECOVERED AND VERIFIED")
        print("=" * 128)
        print("Implementation status  : VALIDATED")
        print("Run action             : BUNDLE-LOCAL MANIFEST PROMOTED AFTER INTERRUPTED COMMIT")
        print("Published validated    : %d/7" % len(validated))
        print("Validated methods      :", validated)
        print("TRAINING GATE          :", "OPEN" if gate_check["open"] else "CLOSED")
        print("Self-test manifest     :", SELFTEST_MANIFEST_PATH)
        print("Manifest SHA256        :", sha256_file(SELFTEST_MANIFEST_PATH))
        print("=" * 128)
        return True

    return False


if not reuse_or_recover_if_available():
    # ========================================================
    # 13. FIRST-RUN ARTIFACT BUILD
    # ========================================================

    staging_dir = Path(tempfile.mkdtemp(prefix="cell26_ampep_105df_", dir=str(SELFTEST_ROOT)))
    try:
        train_path = staging_dir / "synthetic_train.csv"
        val_path = staging_dir / "synthetic_validation.csv"
        train_features_path = staging_dir / "synthetic_train_105DF.csv"
        val_features_path = staging_dir / "synthetic_validation_105DF.csv"
        predictions_path = staging_dir / "synthetic_validation_predictions.csv"
        oracle_path = staging_dir / "df_oracle_report.json"
        model_path = staging_dir / "ampep_rf100_selftest.pkl"

        train_df.to_csv(train_path, index=False)
        val_df.to_csv(val_path, index=False)

        train_feature_df = pd.DataFrame(X_train, columns=FEATURE_NAMES)
        train_feature_df.insert(0, "sequence_id", train_df["sequence_id"].tolist())
        train_feature_df["label"] = y_train
        train_feature_df.to_csv(train_features_path, index=False)

        val_feature_df = pd.DataFrame(X_val, columns=FEATURE_NAMES)
        val_feature_df.insert(0, "sequence_id", val_df["sequence_id"].tolist())
        val_feature_df["label"] = y_val
        val_feature_df.to_csv(val_features_path, index=False)

        pred_df = pd.DataFrame(
            {
                "sequence_id": val_df["sequence_id"],
                "label": y_val,
                "P_nonAMP": val_proba_matrix[:, 0],
                "P_AMP": amp_score,
                "predicted_label": predicted_label,
            }
        )
        assert np.allclose(
            pred_df["P_nonAMP"].to_numpy() + pred_df["P_AMP"].to_numpy(),
            1.0,
            atol=1e-12,
            rtol=0.0,
        )
        pred_df.to_csv(predictions_path, index=False)

        oracle_payload = {
            "schema_version": "1.0",
            "source_function": "Seq2Distribution.m",
            "feature_count": 105,
            "registry_sha256": EXPECTED_CELL25_REGISTRY_SHA256,
            "manual_oracle_sequence": ORACLE_SEQ,
            "manual_charge_first_15_expected": manual_charge_15.tolist(),
            "manual_charge_first_15_observed": oracle_vec[:15].tolist(),
            "edge_sequence": "AAAAAA",
            "edge_charge_first_15_expected": expected_charge_A6.tolist(),
            "edge_charge_first_15_observed": edge_vec[:15].tolist(),
            "cross_oracle_sequences": len(oracle_sequences),
            "max_abs_cross_oracle_difference": max_oracle_delta,
            "status": "PASS",
        }
        atomic_write_json(oracle_path, oracle_payload)

        with open(model_path, "wb") as fh:
            pickle.dump(model, fh, protocol=pickle.HIGHEST_PROTOCOL)

        with open(model_path, "rb") as fh:
            reloaded = pickle.load(fh)
        reload_proba = reloaded.predict_proba(X_val)
        reload_delta = float(np.max(np.abs(reload_proba - val_proba_matrix)))
        assert reload_delta <= 1e-15
        assert np.array_equal(reloaded.predict(X_val), predicted_label)
        assert np.array_equal(reloaded.classes_, np.asarray([0, 1]))
        assert len(reloaded.estimators_) == 100
        assert all(int(tree.max_features_) == 11 for tree in reloaded.estimators_)

        # ====================================================
        # 14. COMMIT BUNDLE AT FINAL PATH
        # ====================================================

        assert not FINAL_BUNDLE_DIR.exists(), (
            "Final Cell 26 bundle appeared during first-run build. Refusing overwrite."
        )
        os.replace(staging_dir, FINAL_BUNDLE_DIR)
        staging_dir = None

        final_paths = {
            "synthetic_train": FINAL_BUNDLE_DIR / train_path.name,
            "synthetic_validation": FINAL_BUNDLE_DIR / val_path.name,
            "train_105df": FINAL_BUNDLE_DIR / train_features_path.name,
            "validation_105df": FINAL_BUNDLE_DIR / val_features_path.name,
            "predictions": FINAL_BUNDLE_DIR / predictions_path.name,
            "oracle_report": FINAL_BUNDLE_DIR / oracle_path.name,
            "model": FINAL_BUNDLE_DIR / model_path.name,
        }

        for path in final_paths.values():
            assert path.is_file(), f"Committed Cell 26 artifact missing: {path}"

        artifact_entries = {key: artifact_entry(path) for key, path in final_paths.items()}

        # ====================================================
        # 15. IMMUTABLE SELF-TEST MANIFEST
        # ====================================================

        adapter_contract = {
            "model_id": "ampep",
            "display_name": "AmPEP",
            "implementation_route": "faithful_reimplementation_from_publication",
            "author_release_pipeline": [
                "sequence",
                "Seq2Distribution_105_DF",
                "random_forest_100_trees",
                "P_class_1",
            ],
            "canonical_feature_count": 105,
            "feature_registry_sha256": EXPECTED_CELL25_REGISTRY_SHA256,
            "rf_original_software": "MATLAB TreeBagger",
            "rf_reimplementation": "sklearn.ensemble.RandomForestClassifier",
            "rf_trees": 100,
            "rf_mtry": 11,
            "rf_bootstrap": True,
            "rf_max_samples": "all_rows_with_replacement_per_tree",
            "positive_score_class": 1,
            "feature_selection": False,
            "selftest_seed": SELFTEST_SEED,
        }

        manifest = {
            "schema_version": "2.0",
            "created_at": datetime.now().astimezone().isoformat(),
            "status": "IMPLEMENTATION_VALIDATED",
            "model_id": "ampep",
            "implementation_validated": True,
            "synthetic_selftest_only": True,
            "benchmark_training_performed": False,
            "benchmark_test_used": False,
            "external_target_used": False,
            "feature_selection_performed": False,
            "adapter_contract": adapter_contract,
            "environment": {
                "python": os.sys.version.split()[0],
                "numpy": np.__version__,
                "pandas": pd.__version__,
                "scikit_learn": sklearn.__version__,
            },
            "source_validation": {
                "author_release_source_root": str(AMPEP_SOURCE_ROOT),
                "source_files_exact": True,
                "source_file_git_blob_sha1": EXPECTED_SOURCE_BLOBS,
                "seq2distribution_oracle_pass": True,
                "manual_oracle_pass": True,
                "registry_oracle_pass": True,
                "max_abs_oracle_difference": max_oracle_delta,
            },
            "selftest": {
                "train_n": int(len(train_df)),
                "train_AMP": TRAIN_POS,
                "train_nonAMP": TRAIN_NEG,
                "validation_n": int(len(val_df)),
                "validation_AMP": VAL_POS,
                "validation_nonAMP": VAL_NEG,
                "positive_negative_ratio": "1:3",
                "feature_count": 105,
                "nonconstant_train_features": nonconstant_train_features,
                "rf_trees": 100,
                "rf_mtry": 11,
                "classes": [int(x) for x in model.classes_.tolist()],
                "positive_class_index": positive_class_index,
                "probability_min": float(np.min(amp_score)),
                "probability_max": float(np.max(amp_score)),
                "mean_AMP_score_on_synthetic_AMP": pos_mean_score,
                "mean_AMP_score_on_synthetic_nonAMP": neg_mean_score,
                "deterministic_replay_max_abs_difference": replay_delta,
                "serialization_reload_max_abs_difference": reload_delta,
            },
            "upstream": {
                "published_route_contract_sha256": EXPECTED_ROUTE_SHA256,
                "ampgram_cell24_selftest_sha256": EXPECTED_AMPGRAM_SELFTEST_SHA256,
                "cell25_contract_path": str(CELL25_CONTRACT_PATH),
                "cell25_contract_sha256": EXPECTED_CELL25_CONTRACT_SHA256,
                "cell25_registry_path": str(CELL25_REGISTRY_PATH),
                "cell25_registry_sha256": EXPECTED_CELL25_REGISTRY_SHA256,
                "cell25_source_audit_path": str(CELL25_SOURCE_AUDIT_PATH),
                "cell25_source_audit_sha256": EXPECTED_CELL25_SOURCE_AUDIT_SHA256,
            },
            "scientific_boundary": {
                "benchmark_data_read": False,
                "benchmark_training_performed": False,
                "benchmark_test_used": False,
                "external_target_used": False,
                "feature_selection_performed": False,
            },
            "artifacts": artifact_entries,
        }

        # Write the bundle-local recovery manifest first.
        local_manifest = FINAL_BUNDLE_DIR / BUNDLE_LOCAL_MANIFEST_NAME
        atomic_write_json(local_manifest, manifest)

        # Add the local manifest to neither artifacts nor itself to avoid recursive hash dependency.
        validate_selftest_manifest(manifest)

        # Promote identical payload to canonical manifest path.
        atomic_write_json(SELFTEST_MANIFEST_PATH, manifest)
        promoted = load_json(SELFTEST_MANIFEST_PATH)
        validate_selftest_manifest(promoted)
        assert promoted == manifest

        # ====================================================
        # 16. UPDATE READINESS + GLOBAL GATE ONLY AFTER PASS
        # ====================================================

        validated_methods, gate_after = merge_readiness_and_gate()
        assert "ampep" in validated_methods
        assert "ampgram" in validated_methods
        assert "ampir" in validated_methods

        # ====================================================
        # 17. FINAL REPORT
        # ====================================================

        print("=" * 128)
        print("CELL 26 PASS - AMPEP 105-D_F ORACLE + FULL ADAPTER END-TO-END SELF-TEST PASSED")
        print("=" * 128)
        print("Published method       : AmPEP")
        print("Implementation status  : VALIDATED")
        print("Canonical predictors   : 105 D_F - PASS")
        print("Exact registry/order   : PASS")
        print("Manual D_F oracle      : PASS")
        print("Registry D_F oracle    : PASS")
        print("Oracle max |delta|     :", max_oracle_delta)
        print("-")
        print("FULL ADAPTER PIPELINE")
        print("Sequence               : PASS")
        print("Seq2Distribution       : 105 features - PASS")
        print("RF                     : 100 trees - PASS")
        print("mtry                   : 11 - PASS")
        print("RF classes             :", model.classes_.tolist())
        print("Positive score         : P(class=1) / column 2 semantics - PASS")
        print("Deterministic replay   : PASS")
        print("Serialization reload   : PASS")
        print("-")
        print("SYNTHETIC SELF-TEST")
        print("Train                  :", len(train_df), f"({TRAIN_POS} AMP / {TRAIN_NEG} non-AMP)")
        print("Validation             :", len(val_df), f"({VAL_POS} AMP / {VAL_NEG} non-AMP)")
        print("Varying D_F features   :", f"{nonconstant_train_features}/105")
        print("P(AMP) range           :", float(np.min(amp_score)), "..", float(np.max(amp_score)))
        print("Mean P(AMP), AMP       :", pos_mean_score)
        print("Mean P(AMP), non-AMP   :", neg_mean_score)
        print("-")
        print("SCIENTIFIC SCOPE")
        print("Benchmark data used    : FALSE")
        print("Feature selection      : FALSE")
        print("Benchmark training     : FALSE")
        print("Benchmark test used    : FALSE")
        print("External target used   : FALSE")
        print("-")
        print("Published validated    : %d/7" % len(validated_methods))
        print("Validated methods      :", validated_methods)
        print("TRAINING GATE          :", "OPEN" if gate_after["open"] else "CLOSED")
        print("-")
        print("Self-test bundle       :", FINAL_BUNDLE_DIR)
        print("Self-test manifest     :", SELFTEST_MANIFEST_PATH)
        print("Manifest SHA256        :", sha256_file(SELFTEST_MANIFEST_PATH))
        print("NEXT                    : CELL 27 - AMPScannerV2 SOURCE/ENV/ADAPTER CLOSURE")
        print("=" * 128)

    finally:
        if staging_dir is not None and Path(staging_dir).exists():
            shutil.rmtree(staging_dir, ignore_errors=True)

================================================================================================================================
CELL 26 PASS - AMPEP 105-D_F ORACLE + FULL ADAPTER END-TO-END SELF-TEST PASSED
================================================================================================================================
Published method       : AmPEP
Implementation status  : VALIDATED
Canonical predictors   : 105 D_F - PASS
Exact registry/order   : PASS
Manual D_F oracle      : PASS
Registry D_F oracle    : PASS
Oracle max |delta|     : 0.0
-
FULL ADAPTER PIPELINE
Sequence               : PASS
Seq2Distribution       : 105 features - PASS
RF                     : 100 trees - PASS
mtry                   : 11 - PASS
RF classes             : [0, 1]
Positive score         : P(class=1) / column 2 semantics - PASS
Deterministic replay   : PASS
Serialization reload   : PASS
-
SYNTHETIC SELF-TEST
Train                  : 128 (32 AMP / 96 non-AMP)
Validation             : 64 (16 AMP / 48 non-AMP)
Varying D_F features   : 105/105
P(AMP) range           : 0.0 .. 1.0
Mean P(AMP), AMP       : 0.998125
Mean P(AMP), non-AMP   : 0.00020833333333333335
-
SCIENTIFIC SCOPE
Benchmark data used    : FALSE
Feature selection      : FALSE
Benchmark training     : FALSE
Benchmark test used    : FALSE
External target used   : FALSE
-
Published validated    : 3/7
Validated methods      : ['ampep', 'ampgram', 'ampir']
TRAINING GATE          : CLOSED
-
Self-test bundle       : /home/pc/genpept_benchmark17_work/published_selftests/ampep/cell26_105df_final_adapter_selftest
Self-test manifest     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampep_FINAL_adapter_selftest.json
Manifest SHA256        : 18786bf2b024c8dab4e1bf28fbd84326568bda559e56a9c20f5895091ca64f4e
NEXT                    : CELL 27 - AMPScannerV2 SOURCE/ENV/ADAPTER CLOSURE
================================================================================================================================

In [19]:
# ============================================================
# CELL 27 - AMPScannerV2
# OFFICIAL SOURCE + ORIGINAL-PAPER TF1 ENVIRONMENT
# + FULL SYNTHETIC ADAPTER SELF-TEST
#
# SOURCE -> CONTRACT -> ENVIRONMENT -> SELF-TEST
# -> VALIDATE -> LOCK
#
# RESTART-SAFE
#
# SCIENTIFIC BOUNDARY
# -------------------
# NO benchmark train data
# NO benchmark validation data
# NO benchmark test data
# NO external target data
# NO architecture substitution
# NO pretrained-model shortcut
#
# Important dependency closure:
#   Keras 2.0.6 metadata requires:
#       theano
#       pyyaml
#       six
#
#   TensorFlow 1.2.1 metadata requires EXACT:
#       backports.weakref == 1.0rc1
#
# Theano is installed only to satisfy Keras 2.0.6 package
# metadata. Runtime backend is explicitly forced to TensorFlow.
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import urllib.request

import numpy as np
import pandas as pd


# ============================================================
# 1. PATHS / LOCKED UPSTREAM
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

WORK_ROOT = Path(
    "/home/pc/genpept_benchmark17_work"
)

SOURCE_ROOT = Path(
    "/home/pc/genpept_sources"
)

METHOD_ID = "ampscannerv2"

OFFICIAL_REPO = (
    "dan-veltri/amp-scanner-v2"
)

OFFICIAL_COMMIT = (
    "933052e2365631fe93098892120ee535e0ba381a"
)

SOURCE_DIR = (
    SOURCE_ROOT
    / (
        "amp-scanner-v2_"
        + OFFICIAL_COMMIT
    )
)

SELFTEST_ROOT = (
    WORK_ROOT
    / "published_selftests"
    / METHOD_ID
)

ROUTE_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_published_method_route_contract.json"
)

TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)

READINESS_PATH = (
    AUDIT_DIR
    / "benchmark17_published_method_local_readiness_latest.csv"
)

AMPEP_SELFTEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampep_FINAL_adapter_selftest.json"
)

AMPGRAM_SELFTEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_adapter_selftest.json"
)

AMPIR_SELFTEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampir_FINAL_adapter_selftest.json"
)

SOURCE_AUDIT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampscannerv2_official_source_audit.json"
)

ENV_AUDIT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampscannerv2_original_paper_environment.json"
)

ADAPTER_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampscannerv2_FINAL_implementation_contract.json"
)

SELFTEST_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampscannerv2_FINAL_adapter_selftest.json"
)

FINAL_BUNDLE_DIR = (
    SELFTEST_ROOT
    / "cell27_final_adapter_selftest"
)

EXPECTED_ROUTE_SHA256 = (
    "dd7d6a743f088cef95fb49288dcf1801"
    "c9dc335be2656e627e7fc7f3bf7170bd"
)

EXPECTED_AMPEP_SELFTEST_SHA256 = (
    "18786bf2b024c8dab4e1bf28fbd843265"
    "68bda559e56a9c20f5895091ca64f4e"
)

EXPECTED_AMPGRAM_SELFTEST_SHA256 = (
    "399d1d695e72f42ad591caf637de03b91"
    "0d07e09b1f1f5805054e629153aee3d"
)

PUBLISHED_IDS = [
    "ampep",
    "ampscannerv2",
    "ampgram",
    "ampir",
    "ampeppy",
    "ai4amp",
    "amplify",
]


for directory in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    WORK_ROOT,
    SOURCE_ROOT,
]:
    assert directory.is_dir(), (
        f"Required directory missing:\n{directory}"
    )


SELFTEST_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

SOURCE_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


for path in [
    ROUTE_CONTRACT_PATH,
    TRAINING_GATE_PATH,
    READINESS_PATH,
    AMPEP_SELFTEST_PATH,
    AMPGRAM_SELFTEST_PATH,
    AMPIR_SELFTEST_PATH,
]:
    assert path.is_file(), (
        f"Required upstream artifact missing:\n{path}"
    )


# ============================================================
# 2. HELPERS
# ============================================================

def sha256_file(path):

    h = hashlib.sha256()

    with open(path, "rb") as f:

        for chunk in iter(
            lambda: f.read(1024 * 1024),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


def git_blob_sha1_bytes(data):

    header = (
        f"blob {len(data)}\0"
    ).encode("utf-8")

    return hashlib.sha1(
        header + data
    ).hexdigest()


def git_blob_sha1_file(path):

    return git_blob_sha1_bytes(
        Path(path).read_bytes()
    )


def load_json(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as f:

        return json.load(f)


def atomic_write_json(
    path,
    payload,
):

    path = Path(path)

    tmp = path.with_name(
        path.name + ".tmp"
    )

    with open(
        tmp,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            payload,
            f,
            indent=2,
            ensure_ascii=False,
        )

        f.flush()

        os.fsync(
            f.fileno()
        )

    os.replace(
        tmp,
        path,
    )


def atomic_write_csv(
    path,
    dataframe,
):

    path = Path(path)

    tmp = path.with_name(
        path.name + ".tmp"
    )

    dataframe.to_csv(
        tmp,
        index=False,
    )

    os.replace(
        tmp,
        path,
    )


def run_cmd(
    command,
    timeout=1800,
    env=None,
    check=True,
    label="subprocess",
):

    result = subprocess.run(
        [
            str(x)
            for x in command
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        env=env,
        timeout=timeout,
    )

    if (
        check
        and
        result.returncode != 0
    ):

        print(
            "=" * 128
        )

        print(
            "SUBPROCESS FAILURE -",
            label,
        )

        print(
            "COMMAND:",
            [
                str(x)
                for x in command
            ],
        )

        print(
            "RETURN CODE:",
            result.returncode,
        )

        print(
            "--- STDOUT ---"
        )

        print(
            result.stdout
        )

        print(
            "--- STDERR ---"
        )

        print(
            result.stderr
        )

        print(
            "=" * 128
        )

        raise AssertionError(
            f"{label} failed "
            f"with return code "
            f"{result.returncode}"
        )

    return result


def version_tuple(value):

    numbers = re.findall(
        r"[0-9]+",
        str(value),
    )

    return tuple(
        int(x)
        for x
        in numbers[:4]
    )


def boolish(value):

    if isinstance(
        value,
        (bool, np.bool_),
    ):
        return bool(value)

    text = (
        str(value)
        .strip()
        .lower()
    )

    if text in {
        "true",
        "1",
        "yes",
    }:
        return True

    if text in {
        "false",
        "0",
        "no",
    }:
        return False

    raise AssertionError(
        f"Cannot interpret as bool: "
        f"{value!r}"
    )


def artifact_entry(path):

    path = Path(path)

    assert path.is_file(), (
        f"Artifact missing: {path}"
    )

    return {
        "path":
            str(path),

        "size_bytes":
            int(
                path.stat().st_size
            ),

        "sha256":
            sha256_file(path),
    }


def verify_artifact_entry(
    entry,
):

    path = Path(
        entry["path"]
    )

    assert path.is_file()

    assert (
        int(
            path.stat().st_size
        )
        ==
        int(
            entry["size_bytes"]
        )
    )

    assert (
        sha256_file(path)
        ==
        entry["sha256"]
    )


# ============================================================
# 3. VERIFY UPSTREAM STATE
# ============================================================

assert (
    sha256_file(
        ROUTE_CONTRACT_PATH
    )
    ==
    EXPECTED_ROUTE_SHA256
)

assert (
    sha256_file(
        AMPEP_SELFTEST_PATH
    )
    ==
    EXPECTED_AMPEP_SELFTEST_SHA256
)

assert (
    sha256_file(
        AMPGRAM_SELFTEST_PATH
    )
    ==
    EXPECTED_AMPGRAM_SELFTEST_SHA256
)


for model_id, path in [

    (
        "ampep",
        AMPEP_SELFTEST_PATH,
    ),

    (
        "ampgram",
        AMPGRAM_SELFTEST_PATH,
    ),

    (
        "ampir",
        AMPIR_SELFTEST_PATH,
    ),

]:

    payload = load_json(
        path
    )

    assert (
        payload[
            "implementation_validated"
        ]
        is True
    )

    assert (
        payload[
            "benchmark_training_performed"
        ]
        is False
    )

    assert (
        payload[
            "benchmark_test_used"
        ]
        is False
    )

    observed_model = (
        payload.get(
            "model_id"
        )
        or
        payload.get(
            "adapter_contract",
            {},
        ).get(
            "model_id"
        )
    )

    assert (
        observed_model
        ==
        model_id
    )


route_payload = load_json(
    ROUTE_CONTRACT_PATH
)

assert (
    route_payload["status"]
    ==
    "PUBLISHED_METHOD_ROUTES_LOCKED_BEFORE_TRAINING"
)

assert (
    route_payload["restart_safe"]
    is True
)

route_core = (
    route_payload["contract"]
)

assert (
    route_core[
        "published_model_ids"
    ]
    ==
    PUBLISHED_IDS
)

route = (
    route_core[
        "methods"
    ][
        METHOD_ID
    ]
)


assert (
    route[
        "paper_doi"
    ]
    ==
    "10.1093/bioinformatics/bty179"
)

assert (
    route[
        "published_family"
    ]
    ==
    "deep_neural_network"
)

assert (
    route[
        "published_representation"
    ]
    ==
    "learned_amino_acid_embedding"
)

assert (
    route[
        "locked_route"
    ]
    ==
    "official_source_retraining"
)

assert (
    route[
        "implementation_environment"
    ]
    ==
    "isolated_legacy_environment"
)

assert (
    route[
        "architecture_change_allowed"
    ]
    is False
)

assert (
    route[
        "ten_independent_retraining_runs"
    ]
    is True
)


gate_before = load_json(
    TRAINING_GATE_PATH
)

assert (
    gate_before["open"]
    is False
)

assert (
    gate_before[
        "benchmark_training_allowed"
    ]
    is False
)


if not SELFTEST_MANIFEST_PATH.is_file():

    assert (
        gate_before[
            "published_methods_implementation_validated"
        ]
        ==
        3
    )

    assert sorted(
        gate_before.get(
            "validated_methods",
            [],
        )
    ) == [
        "ampep",
        "ampgram",
        "ampir",
    ]

else:

    assert (
        gate_before[
            "published_methods_implementation_validated"
        ]
        >=
        4
    )

    assert (
        METHOD_ID
        in gate_before.get(
            "validated_methods",
            [],
        )
    )


# ============================================================
# 4. PIN OFFICIAL SOURCE
# ============================================================

PINNED_FILES = {

    "README.md":
        "34c7b28d4b29912fdf26cbd6f5dd9190f6856703",

    "amp_scanner_v2_train_tf1.py":
        "edcfb5378e18cf6c4195b48e54c72f4add6ddb46",

    "amp_scanner_v2_predict_tf1.py":
        "e896d8a63302026c551d0c1c1d54ec64541b9373",

    "environment_original_paper_model.yml":
        "65b07e91c2c3b909f60fbf912aa017efba1bc14d",

    "requirements_original_paper_model.txt":
        "8272642b58cafbbe4402d7b4664b724830ab5064",

    "tests/test_amp_scanner_v2_train_tf1.py":
        "2ec2dae0da7d5f67e9d3bff9b3a1f9b45d44830b",
}


DOCKERFILE_REL = (
    "docker/Dockerfile.orig_paper_tf1"
)

DOCKERFILE_BLOB_SHA1 = (
    "56e0589ea8f4a647bdb0a6a033b5008e04f9b4c2"
)

RAW_BASE = (
    "https://raw.githubusercontent.com/"
    "dan-veltri/amp-scanner-v2/"
    + OFFICIAL_COMMIT
)


def acquire_pinned_file(
    relpath,
    expected_blob,
):

    destination = (
        SOURCE_DIR
        / relpath
    )

    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if destination.is_file():

        if (
            git_blob_sha1_file(
                destination
            )
            ==
            expected_blob
        ):

            return (
                "REUSED EXACT PINNED FILE"
            )


    url = (
        RAW_BASE
        + "/"
        + relpath
    )

    request = urllib.request.Request(
        url,
        headers={
            "User-Agent":
                "GenPept-Benchmark17/1.0"
        },
    )

    try:

        with urllib.request.urlopen(
            request,
            timeout=120,
        ) as response:

            data = response.read()

    except Exception as exc:

        raise AssertionError(
            "Could not acquire "
            "pinned AMPScannerV2 source:\n"
            f"{url}\n"
            f"{type(exc).__name__}: {exc}"
        )


    observed_blob = (
        git_blob_sha1_bytes(
            data
        )
    )


    assert (
        observed_blob
        ==
        expected_blob
    ), (
        f"Source blob mismatch: "
        f"{relpath}\n"
        f"Expected: {expected_blob}\n"
        f"Actual  : {observed_blob}"
    )


    tmp = (
        destination.with_name(
            destination.name
            + ".download.tmp"
        )
    )

    tmp.write_bytes(
        data
    )

    os.replace(
        tmp,
        destination,
    )

    assert (
        git_blob_sha1_file(
            destination
        )
        ==
        expected_blob
    )

    return (
        "DOWNLOADED EXACT PINNED FILE"
    )


for relpath, blob in (
    PINNED_FILES.items()
):

    acquire_pinned_file(
        relpath,
        blob,
    )


acquire_pinned_file(
    DOCKERFILE_REL,
    DOCKERFILE_BLOB_SHA1,
)


for relpath, blob in (
    PINNED_FILES.items()
):

    path = (
        SOURCE_DIR
        / relpath
    )

    assert path.is_file()

    assert (
        git_blob_sha1_file(path)
        ==
        blob
    )


DOCKERFILE_PATH = (
    SOURCE_DIR
    / DOCKERFILE_REL
)

assert (
    git_blob_sha1_file(
        DOCKERFILE_PATH
    )
    ==
    DOCKERFILE_BLOB_SHA1
)


TRAIN_SCRIPT = (
    SOURCE_DIR
    / "amp_scanner_v2_train_tf1.py"
)

README_PATH = (
    SOURCE_DIR
    / "README.md"
)

ENV_YML_PATH = (
    SOURCE_DIR
    / "environment_original_paper_model.yml"
)

REQ_PATH = (
    SOURCE_DIR
    / "requirements_original_paper_model.txt"
)


train_text = (
    TRAIN_SCRIPT.read_text(
        encoding="utf-8"
    )
)

readme_text = (
    README_PATH.read_text(
        encoding="utf-8"
    )
)

env_yml_text = (
    ENV_YML_PATH.read_text(
        encoding="utf-8"
    )
)

req_text = (
    REQ_PATH.read_text(
        encoding="utf-8"
    )
)

docker_text = (
    DOCKERFILE_PATH.read_text(
        encoding="utf-8"
    )
)


# ============================================================
# 5. SOURCE CONTRACT
#
# IMPORTANT:
# Keep EXACT schema from Cell 27 v1 source audit.
# ============================================================

SOURCE_PATTERNS = {

    "max_length_200":
        r"max_length\s*=\s*200",

    "embedding_128":
        r"embedding_vector_length\s*=\s*128",

    "conv_filters_64":
        r"nbf\s*=\s*64",

    "conv_kernel_16":
        r"flen\s*=\s*16",

    "maxpool_5":
        r"mpsize\s*=\s*5",

    "lstm_units_100":
        r"nlstm\s*=\s*100",

    "lstm_dropout_0_1":
        r"ndrop\s*=\s*0\.1",

    "batch_32":
        r"nbatch\s*=\s*32",

    "epochs_10":
        r"nepochs\s*=\s*10",

    "alphabet":
        r'amino_acids\s*=\s*"XACDEFGHIKLMNPQRSTVWY"',

    "zero_mapping":
        (
            r"aa2int\s*=\s*dict"
            r"\(\(c,\s*i\)\s*"
            r"for\s*i,\s*c\s*"
            r"in\s*enumerate"
            r"\(amino_acids\)\)"
        ),

    "pad_sequences":
        (
            r"sequence\.pad_sequences"
            r"\(x_train,\s*"
            r"maxlen=max_length\)"
        ),

    "embedding_layer":
        (
            r"Embedding"
            r"\(len\(amino_acids\),\s*"
            r"embedding_vector_length,\s*"
            r"input_length=max_length\)"
        ),

    "conv_layer":
        (
            r"Conv1D"
            r"\(filters=nbf,\s*"
            r"kernel_size=flen,\s*"
            r'padding="same",\s*'
            r"activation=['\"]relu['\"]\)"
        ),

    "pool_layer":
        (
            r"MaxPooling1D"
            r"\(pool_size=mpsize\)"
        ),

    "lstm_layer":
        (
            r"LSTM"
            r"\(nlstm,\s*"
            r"use_bias=True,\s*"
            r"dropout=ndrop,\s*"
            r"return_sequences=False\)"
        ),

    "dense_sigmoid":
        (
            r"Dense"
            r"\(1,\s*"
            r"activation=['\"]sigmoid['\"]\)"
        ),

    "binary_crossentropy":
        (
            r"loss=['\"]"
            r"binary_crossentropy"
            r"['\"]"
        ),

    "adam":
        (
            r"optimizer=['\"]"
            r"adam"
            r"['\"]"
        ),

    "fit_epochs_batch":
        (
            r"epochs=nepochs,\s*"
            r"batch_size=nbatch"
        ),

    "threshold":
        (
            r"Prediction probabilities "
            r"> 0\.5 predict AMPs"
        ),
}


SOURCE_CHECKS = {

    key:
        bool(
            re.search(
                pattern,
                train_text,
                flags=re.M,
            )
        )

    for key, pattern
    in SOURCE_PATTERNS.items()
}


failed_source_checks = [

    key

    for key, passed
    in SOURCE_CHECKS.items()

    if not passed
]


assert not failed_source_checks, (
    "Pinned source contract failed:\n"
    f"{failed_source_checks}"
)


for required in [

    "Python==3.6",
    "Tensorflow==1.2.1",
    "Keras==2.0.6",
    "numpy==1.16.0",
    "h5py==2.6",

]:

    assert (
        required
        in readme_text
    )


for required in [

    "python=3.6",
    "tensorflow==1.2.1",
    "Keras==2.0.6",
    "numpy=1.16.0",
    "h5py==2.6",
    "biopython==1.69",

]:

    assert (
        required
        in env_yml_text
    )


for required in [

    "tensorflow==1.2.1",
    "numpy==1.16.0",
    "h5py==2.6",
    "Keras==2.0.6",
    "biopython>=1.69",
    "scikit-learn>=0.20.0",

]:

    assert (
        required
        in req_text
    )


for required in [

    "FROM python:3.6 AS build",
    "tensorflow==1.2.1",
    "numpy==1.16.0",
    "keras==2.0.6",
    "h5py==2.6",
    "biopython==1.69",
    "scikit-learn==0.20.0",

]:

    assert (
        required
        in docker_text
    )


# ============================================================
# 6. EXACT IMMUTABLE SOURCE AUDIT
#
# This MUST equal the audit already written by Cell 27 v1.
# ============================================================

SOURCE_AUDIT_CORE = {

    "schema_version":
        "1.0",

    "model_id":
        METHOD_ID,

    "official_repository":
        OFFICIAL_REPO,

    "pinned_commit":
        OFFICIAL_COMMIT,

    "source_directory":
        str(SOURCE_DIR),

    "files": {

        relpath: {

            "git_blob_sha1":
                blob,

            "sha256":
                sha256_file(
                    SOURCE_DIR
                    / relpath
                ),

            "path":
                str(
                    SOURCE_DIR
                    / relpath
                ),
        }

        for relpath, blob
        in PINNED_FILES.items()
    },

    "source_recipe": {

        "max_length":
            200,

        "minimum_length":
            10,

        "alphabet":
            "XACDEFGHIKLMNPQRSTVWY",

        "integer_mapping":
            "zero_based_enumeration",

        "padding":
            "keras pad_sequences defaults; maxlen=200",

        "embedding_input_dim":
            21,

        "embedding_dim":
            128,

        "conv1d_filters":
            64,

        "conv1d_kernel":
            16,

        "conv1d_padding":
            "same",

        "conv1d_activation":
            "relu",

        "maxpool_size":
            5,

        "lstm_units":
            100,

        "lstm_use_bias":
            True,

        "lstm_dropout":
            0.1,

        "lstm_return_sequences":
            False,

        "dense_units":
            1,

        "dense_activation":
            "sigmoid",

        "loss":
            "binary_crossentropy",

        "optimizer":
            "adam",

        "epochs":
            10,

        "batch_size":
            32,

        "native_threshold":
            0.5,

        "amp_score":
            "single sigmoid probability",
    },

    "source_contract_checks":
        SOURCE_CHECKS,
}


if SOURCE_AUDIT_PATH.is_file():

    existing_source_audit = (
        load_json(
            SOURCE_AUDIT_PATH
        )
    )

    assert (
        existing_source_audit[
            "status"
        ]
        ==
        "AMPSCANNERV2_OFFICIAL_SOURCE_LOCKED"
    )

    assert (
        existing_source_audit[
            "audit"
        ]
        ==
        SOURCE_AUDIT_CORE
    ), (
        "Existing source audit differs "
        "from known Cell27-v1 audit. "
        "Refusing overwrite."
    )

    SOURCE_AUDIT_ACTION = (
        "EXISTING CELL27-v1 "
        "SOURCE AUDIT VERIFIED"
    )

else:

    atomic_write_json(
        SOURCE_AUDIT_PATH,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AMPSCANNERV2_OFFICIAL_SOURCE_LOCKED",

            "audit":
                SOURCE_AUDIT_CORE,
        },
    )

    SOURCE_AUDIT_ACTION = (
        "NEW SOURCE AUDIT COMMITTED"
    )


# ============================================================
# 7. LEGACY ENVIRONMENT
# ============================================================

def locate_conda():

    candidates = []

    if os.environ.get(
        "CONDA_EXE"
    ):

        candidates.append(
            Path(
                os.environ[
                    "CONDA_EXE"
                ]
            )
        )

    candidates.extend(
        [
            (
                Path.home()
                / "miniconda3"
                / "bin"
                / "conda"
            ),

            (
                Path.home()
                / "anaconda3"
                / "bin"
                / "conda"
            ),
        ]
    )

    which_conda = shutil.which(
        "conda"
    )

    if which_conda:

        candidates.append(
            Path(
                which_conda
            )
        )

    seen = set()

    for candidate in candidates:

        key = str(
            candidate
        )

        if key in seen:
            continue

        seen.add(key)

        if (
            candidate.is_file()
            and
            os.access(
                candidate,
                os.X_OK,
            )
        ):

            return (
                candidate.resolve()
            )

    raise AssertionError(
        "Conda executable not found."
    )


CONDA_EXE = (
    locate_conda()
)

CONDA_ROOT = (
    CONDA_EXE
    .parent
    .parent
)

ENV_PREFIX = (
    CONDA_ROOT
    / "envs"
    / "genpept_ampscannerv2_orig"
)

ENV_PYTHON = (
    ENV_PREFIX
    / "bin"
    / "python"
)


# ============================================================
# 7A. PROBE
#
# KERAS_BACKEND explicitly TensorFlow.
#
# Theano is checked as installed distribution only.
# It is NOT selected as runtime backend.
# ============================================================

PROBE_CODE = r'''
import json
import os
import sys

os.environ["KERAS_BACKEND"] = "tensorflow"
os.environ["CUDA_VISIBLE_DEVICES"] = ""

payload = {
    "python":
        ".".join(
            str(x)
            for x
            in sys.version_info[:3]
        )
}

for key, module_name in [
    ("numpy", "numpy"),
    ("scipy", "scipy"),
    ("tensorflow", "tensorflow"),
    ("keras", "keras"),
    ("h5py", "h5py"),
    ("biopython", "Bio"),
    ("sklearn", "sklearn"),
    ("yaml", "yaml"),
    ("protobuf", "google.protobuf"),
]:

    try:

        module = __import__(
            module_name,
            fromlist=["*"],
        )

        payload[key] = (
            module.__version__
        )

        payload[
            key + "_path"
        ] = (
            module.__file__
        )

    except Exception as exc:

        payload[
            key + "_error"
        ] = (
            type(exc).__name__
            + ": "
            + str(exc)
        )


try:

    import pkg_resources

    payload[
        "theano_distribution"
    ] = (
        pkg_resources
        .get_distribution(
            "Theano"
        )
        .version
    )

except Exception as exc:

    payload[
        "theano_distribution_error"
    ] = (
        type(exc).__name__
        + ": "
        + str(exc)
    )


try:

    import pkg_resources

    payload[
        "backports_weakref_distribution"
    ] = (
        pkg_resources
        .get_distribution(
            "backports.weakref"
        )
        .version
    )

except Exception as exc:

    payload[
        "backports_weakref_distribution_error"
    ] = (
        type(exc).__name__
        + ": "
        + str(exc)
    )


print(
    "GENPEPT_PROBE_JSON="
    + json.dumps(
        payload,
        sort_keys=True,
    )
)
'''


def probe_environment():

    if not ENV_PYTHON.is_file():

        return (
            None,
            None,
        )

    probe_env = (
        os.environ.copy()
    )

    probe_env.update(
        {
            "KERAS_BACKEND":
                "tensorflow",

            "CUDA_VISIBLE_DEVICES":
                "",

            "TF_CPP_MIN_LOG_LEVEL":
                "2",
        }
    )

    result = run_cmd(
        [
            ENV_PYTHON,
            "-c",
            PROBE_CODE,
        ],
        timeout=240,
        env=probe_env,
        label=(
            "AMPScannerV2 "
            "environment probe"
        ),
        check=False,
    )

    payload = None

    for line in (
        result.stdout
        .splitlines()
    ):

        if line.startswith(
            "GENPEPT_PROBE_JSON="
        ):

            payload = json.loads(
                line.split(
                    "=",
                    1,
                )[1]
            )

            break

    return (
        payload,
        result,
    )


def python_is_36():

    if not ENV_PYTHON.is_file():

        return False

    result = run_cmd(
        [
            ENV_PYTHON,
            "-c",
            (
                "import sys;"
                "print('%d.%d.%d' "
                "% sys.version_info[:3])"
            ),
        ],
        timeout=60,
        check=False,
        label="Python 3.6 probe",
    )

    return (
        result.returncode == 0
        and
        result.stdout
        .strip()
        .startswith(
            "3.6."
        )
    )


def core_environment_ok(
    probe,
):

    if not probe:

        return False

    required = [

        "python",
        "numpy",
        "scipy",
        "tensorflow",
        "keras",
        "h5py",
        "biopython",
        "sklearn",
        "yaml",
        "protobuf",
    ]

    if any(
        key not in probe
        for key in required
    ):

        return False

    return (

        str(
            probe["python"]
        ).startswith(
            "3.6."
        )

        and

        str(
            probe["tensorflow"]
        )
        ==
        "1.2.1"

        and

        str(
            probe["keras"]
        )
        ==
        "2.0.6"

        and

        str(
            probe["numpy"]
        )
        ==
        "1.16.0"

        and

        version_tuple(
            probe["h5py"]
        )
        ==
        version_tuple(
            "2.6.0"
        )

        and

        version_tuple(
            probe["biopython"]
        )
        ==
        version_tuple(
            "1.69"
        )

        and

        version_tuple(
            probe["sklearn"]
        )
        ==
        version_tuple(
            "0.20.0"
        )
    )


def dependency_closure_ok(
    probe,
):

    if not probe:

        return False

    return (

        str(
            probe.get(
                "theano_distribution",
                "",
            )
        )
        ==
        "0.9.0"

        and

        str(
            probe.get(
                "backports_weakref_distribution",
                "",
            )
        )
        ==
        "1.0rc1"
    )


# ============================================================
# 7B. CREATE MINIMAL PYTHON 3.6 ENV IF NEEDED
# ============================================================

initial_probe, _ = (
    probe_environment()
)


if not ENV_PYTHON.is_file():

    attempts = [

        [
            CONDA_EXE,
            "create",
            "-y",
            "-p",
            ENV_PREFIX,
            "-c",
            "defaults",
            "python=3.6.13",
            "pip",
        ],

        [
            CONDA_EXE,
            "create",
            "-y",
            "-p",
            ENV_PREFIX,
            "-c",
            "conda-forge",
            "python=3.6.15",
            "pip",
        ],
    ]

    created = False

    failures = []


    for index, command in enumerate(
        attempts,
        start=1,
    ):

        result = run_cmd(
            command,
            timeout=3600,
            label=(
                "create minimal Python3.6 "
                f"environment attempt {index}"
            ),
            check=False,
        )

        if (
            result.returncode == 0
            and
            ENV_PYTHON.is_file()
            and
            python_is_36()
        ):

            created = True

            break

        failures.append(
            {
                "attempt":
                    index,

                "returncode":
                    result.returncode,

                "stdout":
                    result.stdout[-12000:],

                "stderr":
                    result.stderr[-12000:],
            }
        )


    if not created:

        print(
            "=" * 128
        )

        print(
            "MINIMAL PYTHON 3.6 "
            "ENVIRONMENT CREATION FAILED"
        )

        for failure in failures:

            print(
                "ATTEMPT:",
                failure["attempt"],
            )

            print(
                failure["stdout"]
            )

            print(
                failure["stderr"]
            )

        print(
            "=" * 128
        )

        raise AssertionError(
            "Could not create "
            "minimal Python 3.6 "
            "environment."
        )


assert (
    ENV_PYTHON.is_file()
)

assert (
    python_is_36()
)


# ============================================================
# 7C. PACKAGING TOOLCHAIN
# ============================================================

run_cmd(
    [
        ENV_PYTHON,
        "-m",
        "pip",
        "install",
        "--upgrade",

        "pip==21.3.1",
        "setuptools==59.6.0",
        "wheel==0.37.1",
    ],
    timeout=1800,
    label=(
        "pin Python3.6 "
        "packaging toolchain"
    ),
)


# ============================================================
# 7D. RESTORE DIRECT ORIGINAL-PAPER STACK IF NEEDED
# ============================================================

probe_before_restore, _ = (
    probe_environment()
)


if not core_environment_ok(
    probe_before_restore
):

    # Binary scientific packages.
    run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--only-binary=:all:",

            "numpy==1.16.0",
            "scipy==1.5.4",
            "h5py==2.6.0",
            "scikit-learn==0.20.0",
            "PyYAML==5.4.1",
            "protobuf==3.19.6",
        ],
        timeout=5400,
        label=(
            "restore binary "
            "legacy scientific stack"
        ),
    )


    # TensorFlow-era supporting packages.
    run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",

            "six==1.16.0",
            "Markdown==3.3.7",
            "Werkzeug==0.16.1",

            # TF 1.2.1 exact requirements:
            "bleach==1.5.0",
            "html5lib==0.9999999",
        ],
        timeout=1800,
        label=(
            "restore TF1.2 "
            "support packages"
        ),
    )


    # TensorFlow 1.2.1 exact wheel.
    run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--only-binary=tensorflow",
            "--no-deps",
            "--force-reinstall",

            "tensorflow==1.2.1",
        ],
        timeout=5400,
        label=(
            "restore TensorFlow 1.2.1"
        ),
    )


    # Keras 2.0.6.
    run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--no-deps",
            "--force-reinstall",

            "Keras==2.0.6",
        ],
        timeout=1800,
        label=(
            "restore Keras 2.0.6"
        ),
    )


    # Biopython 1.69.
    run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--no-deps",
            "--force-reinstall",

            "biopython==1.69",
        ],
        timeout=5400,
        label=(
            "restore Biopython 1.69"
        ),
    )


# ============================================================
# 7E. EXACT PACKAGE-METADATA DEPENDENCY CLOSURE
#
# This is the correction for the latest failure.
#
# Keras 2.0.6 setup.py:
#     install_requires=[
#         'theano',
#         'pyyaml',
#         'six'
#     ]
#
# TensorFlow 1.2.1 setup.py:
#     backports.weakref == 1.0rc1
#
# Theano 0.9.0 was the stable Theano release available when
# Keras 2.0.6 was released. Runtime backend remains tensorflow.
# ============================================================

run_cmd(
    [
        ENV_PYTHON,
        "-m",
        "pip",
        "install",
        "--no-cache-dir",
        "--no-deps",
        "--force-reinstall",

        "backports.weakref==1.0rc1",
    ],
    timeout=1800,
    label=(
        "restore exact "
        "backports.weakref 1.0rc1"
    ),
)


run_cmd(
    [
        ENV_PYTHON,
        "-m",
        "pip",
        "install",
        "--no-cache-dir",
        "--no-deps",
        "--force-reinstall",

        "Theano==0.9.0",
    ],
    timeout=3600,
    label=(
        "install Keras 2.0.6 "
        "Theano metadata dependency"
    ),
)


# ============================================================
# 7F. PIP DEPENDENCY CONSISTENCY
# ============================================================

pip_check = run_cmd(
    [
        ENV_PYTHON,
        "-m",
        "pip",
        "check",
    ],
    timeout=300,
    label=(
        "legacy environment "
        "pip dependency check"
    ),
    check=False,
)


if (
    pip_check.returncode
    !=
    0
):

    print(
        "=" * 128
    )

    print(
        "PIP CHECK FAILED"
    )

    print(
        pip_check.stdout
    )

    print(
        pip_check.stderr
    )

    print(
        "=" * 128
    )

    raise AssertionError(
        "Legacy environment "
        "dependency check failed."
    )


# ============================================================
# 8. FINAL ENVIRONMENT PROBE
# ============================================================

FINAL_PROBE, FINAL_PROBE_RESULT = (
    probe_environment()
)


if not core_environment_ok(
    FINAL_PROBE
):

    print(
        "=" * 128
    )

    print(
        "AMPScannerV2 CORE "
        "ENVIRONMENT PROBE FAILED"
    )

    print(
        json.dumps(
            FINAL_PROBE,
            indent=2,
            sort_keys=True,
        )
        if FINAL_PROBE
        else
        "NO PROBE JSON"
    )

    if (
        FINAL_PROBE_RESULT
        is not None
    ):

        print(
            FINAL_PROBE_RESULT.stdout
        )

        print(
            FINAL_PROBE_RESULT.stderr
        )

    print(
        "=" * 128
    )

    raise AssertionError(
        "AMPScannerV2 direct "
        "original-paper stack "
        "is not exact-compatible."
    )


assert (
    dependency_closure_ok(
        FINAL_PROBE
    )
), (
    "AMPScannerV2 package metadata "
    "dependency closure is incomplete.\n"
    f"{json.dumps(FINAL_PROBE, indent=2)}"
)


environment_root = str(
    ENV_PREFIX.resolve()
)


for key in [

    "numpy_path",
    "scipy_path",
    "tensorflow_path",
    "keras_path",
    "h5py_path",
    "biopython_path",
    "sklearn_path",
    "yaml_path",
    "protobuf_path",

]:

    assert (
        key
        in FINAL_PROBE
    )

    assert (
        str(
            FINAL_PROBE[key]
        ).startswith(
            environment_root
        )
    ), (
        f"{key} resolved outside "
        f"dedicated environment:\n"
        f"{FINAL_PROBE[key]}"
    )


# ============================================================
# 9. ENVIRONMENT AUDIT
# ============================================================

ENV_AUDIT_CORE = {

    "schema_version":
        "1.1",

    "model_id":
        METHOD_ID,

    "environment_prefix":
        str(ENV_PREFIX),

    "python_executable":
        str(ENV_PYTHON),

    "observed":
        FINAL_PROBE,

    "official_original_paper_environment": {

        "python":
            "3.6",

        "tensorflow":
            "1.2.1",

        "keras":
            "2.0.6",

        "numpy":
            "1.16.0",

        "h5py":
            "2.6",

        "biopython":
            "1.69",

        "scikit_learn":
            "0.20.0",
    },

    "dependency_metadata_closure": {

        "keras_2_0_6_requires_theano":
            True,

        "theano_distribution":
            "0.9.0",

        "keras_runtime_backend":
            "tensorflow",

        "tensorflow_1_2_1_requires_backports_weakref":
            "1.0rc1",

        "backports_weakref_distribution":
            "1.0rc1",

        "pip_check":
            "PASS",
    },

    "restoration_route":
        (
            "minimal_python36_then_"
            "pip_original_direct_stack_"
            "plus_exact_metadata_closure"
        ),

    "official_dockerfile": {

        "path":
            str(
                DOCKERFILE_PATH
            ),

        "git_blob_sha1":
            DOCKERFILE_BLOB_SHA1,

        "sha256":
            sha256_file(
                DOCKERFILE_PATH
            ),
    },

    "source_commit":
        OFFICIAL_COMMIT,
}


if ENV_AUDIT_PATH.is_file():

    existing_env_audit = (
        load_json(
            ENV_AUDIT_PATH
        )
    )

    assert (
        existing_env_audit[
            "status"
        ]
        ==
        "AMPSCANNERV2_ORIGINAL_PAPER_ENVIRONMENT_READY"
    )

    assert (
        existing_env_audit[
            "audit"
        ]
        ==
        ENV_AUDIT_CORE
    ), (
        "Existing environment audit "
        "differs; refusing overwrite."
    )

else:

    atomic_write_json(
        ENV_AUDIT_PATH,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AMPSCANNERV2_ORIGINAL_PAPER_ENVIRONMENT_READY",

            "audit":
                ENV_AUDIT_CORE,
        },
    )


# ============================================================
# 10. IMPLEMENTATION CONTRACT
# ============================================================

ADAPTER_CONTRACT_CORE = {

    "schema_version":
        "1.0",

    "model_id":
        METHOD_ID,

    "display_name":
        "AMPScannerV2",

    "paper_doi":
        "10.1093/bioinformatics/bty179",

    "implementation_route":
        "official_source_retraining",

    "official_repository":
        OFFICIAL_REPO,

    "official_commit":
        OFFICIAL_COMMIT,

    "training_script":
        "amp_scanner_v2_train_tf1.py",

    "runtime_backend":
        "tensorflow",

    "preprocessing":
        SOURCE_AUDIT_CORE[
            "source_recipe"
        ],

    "architecture": {

        "layers": [

            "Embedding(21,128,input_length=200)",

            (
                "Conv1D(filters=64,"
                "kernel_size=16,"
                "padding=same,"
                "activation=relu)"
            ),

            "MaxPooling1D(pool_size=5)",

            (
                "LSTM(100,"
                "use_bias=True,"
                "dropout=0.1,"
                "return_sequences=False)"
            ),

            "Dense(1,activation=sigmoid)",
        ],

        "loss":
            "binary_crossentropy",

        "optimizer":
            "adam",
    },

    "training": {

        "epochs":
            10,

        "batch_size":
            32,

        "benchmark_retraining_seeds":
            list(
                range(
                    100,
                    110,
                )
            ),

        "architecture_change_allowed":
            False,
    },

    "score_semantics": {

        "amp_score":
            "single sigmoid probability",

        "native_threshold":
            0.5,

        "native_positive_rule":
            "probability > 0.5",
    },

    "selftest_boundary": {

        "synthetic_only":
            True,

        "benchmark_training":
            False,

        "benchmark_test":
            False,

        "external_target":
            False,
    },
}


if ADAPTER_CONTRACT_PATH.is_file():

    existing_contract = (
        load_json(
            ADAPTER_CONTRACT_PATH
        )
    )

    assert (
        existing_contract[
            "status"
        ]
        ==
        "AMPSCANNERV2_IMPLEMENTATION_CONTRACT_LOCKED"
    )

    assert (
        existing_contract[
            "contract"
        ]
        ==
        ADAPTER_CONTRACT_CORE
    ), (
        "Existing adapter contract "
        "differs; refusing overwrite."
    )

else:

    atomic_write_json(
        ADAPTER_CONTRACT_PATH,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AMPSCANNERV2_IMPLEMENTATION_CONTRACT_LOCKED",

            "implementation_validated":
                False,

            "benchmark_training_performed":
                False,

            "benchmark_test_used":
                False,

            "external_target_used":
                False,

            "contract":
                ADAPTER_CONTRACT_CORE,
        },
    )


# ============================================================
# 11. GLOBAL GATE HELPERS
# ============================================================

def validated_methods_from_manifests():

    validated = []

    for model_id in PUBLISHED_IDS:

        path = (
            MANIFEST_DIR
            /
            (
                f"benchmark17_{model_id}_"
                f"FINAL_adapter_selftest.json"
            )
        )

        if not path.is_file():

            continue

        payload = load_json(
            path
        )

        if (
            payload.get(
                "implementation_validated",
                False,
            )
            is True
        ):

            validated.append(
                model_id
            )

    return sorted(
        validated
    )


def update_readiness_and_gate():

    readiness = pd.read_csv(
        READINESS_PATH,
        low_memory=False,
    )

    required_columns = {

        "model_id",
        "adapter_self_test_passed",
        "implementation_validated",
        "local_state",
        "training_allowed",
    }

    assert (
        required_columns
        .issubset(
            readiness.columns
        )
    )


    mask = (
        readiness[
            "model_id"
        ]
        .astype(str)
        ==
        METHOD_ID
    )

    assert (
        int(
            mask.sum()
        )
        ==
        1
    )


    readiness.loc[
        mask,
        "adapter_self_test_passed",
    ] = True

    readiness.loc[
        mask,
        "implementation_validated",
    ] = True

    readiness.loc[
        mask,
        "local_state",
    ] = (
        "IMPLEMENTATION_VALIDATED"
    )


    validated = (
        validated_methods_from_manifests()
    )


    for required_model in [

        "ampep",
        "ampscannerv2",
        "ampgram",
        "ampir",

    ]:

        assert (
            required_model
            in validated
        )


    assert (
        4
        <= len(validated)
        <= 7
    )


    gate = load_json(
        TRAINING_GATE_PATH
    )


    gate[
        "published_methods_implementation_validated"
    ] = len(validated)

    gate[
        "validated_methods"
    ] = validated

    gate[
        "updated_at"
    ] = (
        datetime.now()
        .astimezone()
        .isoformat()
    )


    if len(validated) == 7:

        gate["open"] = True

        gate[
            "benchmark_training_allowed"
        ] = True

        gate["reason"] = (
            "All seven published-method "
            "implementations validated."
        )

        readiness.loc[
            :,
            "training_allowed",
        ] = True

    else:

        gate["open"] = False

        gate[
            "benchmark_training_allowed"
        ] = False

        gate["reason"] = (
            f"{len(validated)}/7 "
            f"published-method "
            f"implementations validated."
        )

        readiness.loc[
            mask,
            "training_allowed",
        ] = False


    atomic_write_csv(
        READINESS_PATH,
        readiness,
    )

    atomic_write_json(
        TRAINING_GATE_PATH,
        gate,
    )


    gate_check = load_json(
        TRAINING_GATE_PATH
    )

    readiness_check = pd.read_csv(
        READINESS_PATH,
        low_memory=False,
    )

    mask_check = (
        readiness_check[
            "model_id"
        ]
        .astype(str)
        ==
        METHOD_ID
    )


    assert (
        boolish(
            readiness_check.loc[
                mask_check,
                "adapter_self_test_passed",
            ].iloc[0]
        )
        is True
    )

    assert (
        boolish(
            readiness_check.loc[
                mask_check,
                "implementation_validated",
            ].iloc[0]
        )
        is True
    )

    assert (
        str(
            readiness_check.loc[
                mask_check,
                "local_state",
            ].iloc[0]
        )
        ==
        "IMPLEMENTATION_VALIDATED"
    )

    assert (
        gate_check[
            "validated_methods"
        ]
        ==
        validated
    )

    assert (
        gate_check[
            "published_methods_implementation_validated"
        ]
        ==
        len(validated)
    )


    if len(validated) < 7:

        assert (
            gate_check[
                "open"
            ]
            is False
        )

        assert (
            gate_check[
                "benchmark_training_allowed"
            ]
            is False
        )


    return (
        validated,
        gate_check,
    )


# ============================================================
# 12. SELF-TEST MANIFEST VALIDATOR
# ============================================================

def validate_selftest_manifest(
    payload,
):

    assert (
        payload[
            "status"
        ]
        ==
        "IMPLEMENTATION_VALIDATED"
    )

    assert (
        payload[
            "model_id"
        ]
        ==
        METHOD_ID
    )

    assert (
        payload[
            "implementation_validated"
        ]
        is True
    )

    assert (
        payload[
            "synthetic_selftest_only"
        ]
        is True
    )

    assert (
        payload[
            "benchmark_training_performed"
        ]
        is False
    )

    assert (
        payload[
            "benchmark_test_used"
        ]
        is False
    )

    assert (
        payload[
            "external_target_used"
        ]
        is False
    )

    assert (
        payload[
            "official_commit"
        ]
        ==
        OFFICIAL_COMMIT
    )

    assert (
        payload[
            "source_audit_sha256"
        ]
        ==
        sha256_file(
            SOURCE_AUDIT_PATH
        )
    )

    assert (
        payload[
            "environment_audit_sha256"
        ]
        ==
        sha256_file(
            ENV_AUDIT_PATH
        )
    )

    assert (
        payload[
            "adapter_contract_sha256"
        ]
        ==
        sha256_file(
            ADAPTER_CONTRACT_PATH
        )
    )


    selftest = (
        payload[
            "selftest"
        ]
    )


    assert (
        selftest[
            "preprocessing"
        ][
            "max_length"
        ]
        ==
        200
    )

    assert (
        selftest[
            "preprocessing"
        ][
            "alphabet"
        ]
        ==
        "XACDEFGHIKLMNPQRSTVWY"
    )


    architecture = (
        selftest[
            "architecture"
        ]
    )


    assert (
        architecture[
            "layer_names"
        ]
        ==
        [
            "Embedding",
            "Conv1D",
            "MaxPooling1D",
            "LSTM",
            "Dense",
        ]
    )

    assert (
        architecture[
            "embedding_dim"
        ]
        ==
        128
    )

    assert (
        architecture[
            "conv_filters"
        ]
        ==
        64
    )

    assert (
        architecture[
            "conv_kernel"
        ]
        ==
        16
    )

    assert (
        architecture[
            "maxpool_size"
        ]
        ==
        5
    )

    assert (
        architecture[
            "lstm_units"
        ]
        ==
        100
    )

    assert (
        architecture[
            "dense_units"
        ]
        ==
        1
    )


    assert (
        selftest[
            "score_semantics"
        ][
            "positive_class"
        ]
        ==
        1
    )

    assert (
        selftest[
            "score_semantics"
        ][
            "threshold"
        ]
        ==
        0.5
    )

    assert (
        selftest[
            "serialization"
        ][
            "pass"
        ]
        is True
    )

    assert (
        selftest[
            "deterministic_replay"
        ][
            "pass"
        ]
        is True
    )


    for entry in (
        payload[
            "artifacts"
        ].values()
    ):

        verify_artifact_entry(
            entry
        )


# ============================================================
# 13. REUSE COMPLETED SELF-TEST
# ============================================================

if SELFTEST_MANIFEST_PATH.is_file():

    existing_selftest = (
        load_json(
            SELFTEST_MANIFEST_PATH
        )
    )

    validate_selftest_manifest(
        existing_selftest
    )

    validated, gate_check = (
        update_readiness_and_gate()
    )


    print(
        "=" * 128
    )

    print(
        "CELL 27 PASS - "
        "AMPScannerV2 FULL ADAPTER "
        "SELF-TEST REUSED AND VERIFIED"
    )

    print(
        "=" * 128
    )

    print(
        "Implementation status  : VALIDATED"
    )

    print(
        "Python                 :",
        FINAL_PROBE[
            "python"
        ],
    )

    print(
        "TensorFlow             :",
        FINAL_PROBE[
            "tensorflow"
        ],
    )

    print(
        "Keras                  :",
        FINAL_PROBE[
            "keras"
        ],
    )

    print(
        "Theano dependency      :",
        FINAL_PROBE[
            "theano_distribution"
        ],
        "(NOT runtime backend)",
    )

    print(
        "backports.weakref      :",
        FINAL_PROBE[
            "backports_weakref_distribution"
        ],
    )

    print(
        "Published validated    : "
        f"{len(validated)}/7"
    )

    print(
        "Validated methods      :",
        validated,
    )

    print(
        "TRAINING GATE          :",
        (
            "OPEN"
            if gate_check[
                "open"
            ]
            else
            "CLOSED"
        ),
    )

    print(
        "Manifest SHA256        :",
        sha256_file(
            SELFTEST_MANIFEST_PATH
        ),
    )

    print(
        "NEXT                   : "
        "CELL 28 - amPEPpy"
    )

    print(
        "=" * 128
    )


else:

    # ========================================================
    # 14. FIRST-RUN PRECONDITION
    # ========================================================

    assert (
        not FINAL_BUNDLE_DIR.exists()
    ), (
        "Final Cell27 bundle exists "
        "without self-test manifest:\n"
        f"{FINAL_BUNDLE_DIR}"
    )


    # ========================================================
    # 15. SYNTHETIC-ONLY DATA
    # ========================================================

    rng = np.random.RandomState(
        270027
    )

    AMP_ALPHABET = np.array(
        list(
            "KRWFLIV"
        )
    )

    DECOY_ALPHABET = np.array(
        list(
            "DENQGSTAP"
        )
    )


    def synthetic_sequence(
        alphabet,
        length,
    ):

        value = "".join(
            rng.choice(
                alphabet,
                size=length,
            ).tolist()
        )

        assert (
            10
            <= len(value)
            <= 200
        )

        assert (
            set(value)
            .issubset(
                set(
                    "ACDEFGHIKLMNPQRSTVWY"
                )
            )
        )

        return value


    train_amp = [

        synthetic_sequence(
            AMP_ALPHABET,
            24 + (i % 17),
        )

        for i in range(24)
    ]


    train_decoy = [

        synthetic_sequence(
            DECOY_ALPHABET,
            24 + (i % 17),
        )

        for i in range(24)
    ]


    validation_amp = [

        synthetic_sequence(
            AMP_ALPHABET,
            26 + (i % 13),
        )

        for i in range(12)
    ]


    validation_decoy = [

        synthetic_sequence(
            DECOY_ALPHABET,
            26 + (i % 13),
        )

        for i in range(12)
    ]


    staging_dir = Path(
        tempfile.mkdtemp(
            prefix=(
                "cell27_ampscannerv2_"
            ),
            dir=str(
                SELFTEST_ROOT
            ),
        )
    )


    try:

        def write_fasta(
            path,
            sequences,
            prefix,
        ):

            with open(
                path,
                "w",
                encoding="utf-8",
            ) as f:

                for index, sequence_value in enumerate(
                    sequences,
                    start=1,
                ):

                    f.write(
                        f">{prefix}_{index:03d}\n"
                        f"{sequence_value}\n"
                    )


        amp_train_fasta = (
            staging_dir
            / "synthetic_amp_train.fasta"
        )

        decoy_train_fasta = (
            staging_dir
            / "synthetic_decoy_train.fasta"
        )

        amp_validation_fasta = (
            staging_dir
            / "synthetic_amp_validation.fasta"
        )

        decoy_validation_fasta = (
            staging_dir
            / "synthetic_decoy_validation.fasta"
        )


        write_fasta(
            amp_train_fasta,
            train_amp,
            "AMP_TR",
        )

        write_fasta(
            decoy_train_fasta,
            train_decoy,
            "DEC_TR",
        )

        write_fasta(
            amp_validation_fasta,
            validation_amp,
            "AMP_VA",
        )

        write_fasta(
            decoy_validation_fasta,
            validation_decoy,
            "DEC_VA",
        )


        # ====================================================
        # 16. EXACT-PYTHON3.6 RUNNER
        # ====================================================

        runner_path = (
            staging_dir
            / "run_official_ampscannerv2_selftest.py"
        )


        runner_code = r'''
from pathlib import Path

import csv
import importlib.util
import json
import os
import sys


# CRITICAL:
# Keras 2.0.6 must execute TensorFlow backend.
# Theano is installed only to satisfy package metadata.
os.environ["KERAS_BACKEND"] = "tensorflow"
os.environ["CUDA_VISIBLE_DEVICES"] = ""
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"


import numpy as np
import tensorflow as tf
import keras

from keras import backend as K
from keras.models import load_model
from keras.preprocessing import sequence


SOURCE_SCRIPT = Path(
    sys.argv[1]
).resolve()

AMP_TRAIN = Path(
    sys.argv[2]
).resolve()

DECOY_TRAIN = Path(
    sys.argv[3]
).resolve()

AMP_VALIDATION = Path(
    sys.argv[4]
).resolve()

DECOY_VALIDATION = Path(
    sys.argv[5]
).resolve()

OUTPUT_DIR = Path(
    sys.argv[6]
).resolve()

SEED = int(
    sys.argv[7]
)


OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


assert (
    sys.version_info[:2]
    ==
    (3, 6)
)

assert (
    tf.__version__
    ==
    "1.2.1"
)

assert (
    keras.__version__
    ==
    "2.0.6"
)

assert (
    np.__version__
    ==
    "1.16.0"
)


# Confirm TensorFlow backend.
backend_name = (
    K.backend()
)

assert (
    backend_name
    ==
    "tensorflow"
), (
    "Unexpected Keras backend: "
    + str(
        backend_name
    )
)


config = tf.ConfigProto(
    intra_op_parallelism_threads=1,
    inter_op_parallelism_threads=1,
    device_count={
        "GPU":
            0
    },
)


session = tf.Session(
    config=config
)


if hasattr(
    K,
    "set_session",
):

    K.set_session(
        session
    )


tf.set_random_seed(
    SEED
)

np.random.seed(
    SEED
)


spec = (
    importlib.util
    .spec_from_file_location(
        "amp_scanner_v2_train_pinned",
        str(
            SOURCE_SCRIPT
        ),
    )
)


module = (
    importlib.util
    .module_from_spec(
        spec
    )
)


spec.loader.exec_module(
    module
)


assert (
    module.max_length
    ==
    200
)

assert (
    module.embedding_vector_length
    ==
    128
)

assert (
    module.nbf
    ==
    64
)

assert (
    module.flen
    ==
    16
)

assert (
    module.mpsize
    ==
    5
)

assert (
    module.nlstm
    ==
    100
)

assert (
    abs(
        module.ndrop
        -
        0.1
    )
    <
    1e-12
)

assert (
    module.nbatch
    ==
    32
)

assert (
    module.nepochs
    ==
    10
)

assert (
    module.amino_acids
    ==
    "XACDEFGHIKLMNPQRSTVWY"
)


for fasta_path in [

    AMP_TRAIN,
    DECOY_TRAIN,
    AMP_VALIDATION,
    DECOY_VALIDATION,

]:

    module.check_format(
        str(
            fasta_path
        ),
        module.amino_acids,
        module.max_length,
        min_len=10,
        verbose=False,
    )


(
    x_train,
    x_validation,
    x_probe,
    y_train,
    y_validation,
    y_probe,

) = module.encode_sequences(

    str(
        AMP_TRAIN
    ),

    str(
        AMP_VALIDATION
    ),

    str(
        AMP_VALIDATION
    ),

    str(
        DECOY_TRAIN
    ),

    str(
        DECOY_VALIDATION
    ),

    str(
        DECOY_VALIDATION
    ),

    shuffle_seed=SEED,
)


assert (
    x_train.shape
    ==
    (48, 200)
)

assert (
    y_train.shape
    ==
    (48,)
)

assert (
    x_validation.shape
    ==
    (24, 200)
)

assert (
    y_validation.shape
    ==
    (24,)
)

assert (
    x_probe.shape
    ==
    (24, 200)
)

assert (
    y_probe.shape
    ==
    (24,)
)


assert (
    set(
        np.unique(
            y_train
        ).tolist()
    )
    ==
    {0, 1}
)

assert (
    set(
        np.unique(
            y_validation
        ).tolist()
    )
    ==
    {0, 1}
)


# ------------------------------------------------------------
# Independent token + padding oracle
# ------------------------------------------------------------

oracle_sequence = (
    "ACDEFGHIKL"
)


oracle_ids = [

    module.aa2int[aa]

    for aa
    in oracle_sequence
]


assert (
    oracle_ids
    ==
    [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
    ]
)


oracle_padded = (
    sequence.pad_sequences(
        [
            oracle_ids
        ],
        maxlen=200,
    )
)


assert (
    oracle_padded.shape
    ==
    (1, 200)
)

assert (
    np.all(
        oracle_padded[
            0,
            :-10
        ]
        ==
        0
    )
)

assert (
    oracle_padded[
        0,
        -10:
    ].tolist()
    ==
    oracle_ids
)


# ------------------------------------------------------------
# Exact official compile_model()
# ------------------------------------------------------------

model_path = (
    OUTPUT_DIR
    / "model.h5"
)


model = (
    module.compile_model(
        x_train,
        y_train,
        x_validation,
        y_validation,
        saved_model_name=str(
            model_path
        ),
        merge_train_and_val=False,
    )
)


assert (
    model_path.is_file()
)


# ------------------------------------------------------------
# Runtime architecture oracle
# ------------------------------------------------------------

layers = (
    model.layers
)


layer_names = [

    layer.__class__.__name__

    for layer
    in layers
]


assert (
    layer_names
    ==
    [
        "Embedding",
        "Conv1D",
        "MaxPooling1D",
        "LSTM",
        "Dense",
    ]
)


embedding_layer = (
    layers[0]
)

conv_layer = (
    layers[1]
)

pool_layer = (
    layers[2]
)

lstm_layer = (
    layers[3]
)

dense_layer = (
    layers[4]
)


embedding_input_dim = int(
    getattr(
        embedding_layer,
        "input_dim"
    )
)

embedding_output_dim = int(
    getattr(
        embedding_layer,
        "output_dim"
    )
)


conv_filters = int(
    getattr(
        conv_layer,
        "filters"
    )
)


conv_kernel = (
    getattr(
        conv_layer,
        "kernel_size"
    )
)

if isinstance(
    conv_kernel,
    (tuple, list),
):

    conv_kernel = (
        conv_kernel[0]
    )

conv_kernel = int(
    conv_kernel
)


pool_size = (
    getattr(
        pool_layer,
        "pool_size"
    )
)

if isinstance(
    pool_size,
    (tuple, list),
):

    pool_size = (
        pool_size[0]
    )

pool_size = int(
    pool_size
)


lstm_units = (
    getattr(
        lstm_layer,
        "units",
        None,
    )
)

if lstm_units is None:

    lstm_units = (
        getattr(
            lstm_layer,
            "output_dim"
        )
    )

lstm_units = int(
    lstm_units
)


dense_units = (
    getattr(
        dense_layer,
        "units",
        None,
    )
)

if dense_units is None:

    dense_units = (
        getattr(
            dense_layer,
            "output_dim"
        )
    )

dense_units = int(
    dense_units
)


assert (
    embedding_input_dim
    ==
    21
)

assert (
    embedding_output_dim
    ==
    128
)

assert (
    conv_filters
    ==
    64
)

assert (
    conv_kernel
    ==
    16
)

assert (
    pool_size
    ==
    5
)

assert (
    lstm_units
    ==
    100
)

assert (
    dense_units
    ==
    1
)


# ------------------------------------------------------------
# Prediction semantics
# ------------------------------------------------------------

probabilities = np.asarray(
    model.predict(
        x_validation,
        batch_size=32,
        verbose=0,
    )
).reshape(-1)


assert (
    probabilities.shape
    ==
    (24,)
)

assert (
    np.all(
        np.isfinite(
            probabilities
        )
    )
)

assert (
    np.all(
        probabilities
        >=
        0.0
    )
)

assert (
    np.all(
        probabilities
        <=
        1.0
    )
)


native_class = (
    probabilities
    >
    0.5
).astype(int)


prediction_path = (
    OUTPUT_DIR
    / "validation_predictions.csv"
)


with open(
    prediction_path,
    "w",
    newline="",
    encoding="utf-8",
) as f:

    writer = (
        csv.writer(f)
    )

    writer.writerow(
        [
            "row_index",
            "y_true",
            "p_amp",
            "pred_native_gt_0_5",
        ]
    )

    for index, values in enumerate(
        zip(
            y_validation.tolist(),
            probabilities.tolist(),
            native_class.tolist(),
        )
    ):

        y_true, probability, predicted = (
            values
        )

        writer.writerow(
            [
                index,
                int(
                    y_true
                ),
                float(
                    probability
                ),
                int(
                    predicted
                ),
            ]
        )


# ------------------------------------------------------------
# Serialization / reload oracle
# ------------------------------------------------------------

reloaded_model = (
    load_model(
        str(
            model_path
        )
    )
)


reloaded_probabilities = np.asarray(
    reloaded_model.predict(
        x_validation,
        batch_size=32,
        verbose=0,
    )
).reshape(-1)


reload_delta = float(
    np.max(
        np.abs(
            probabilities
            -
            reloaded_probabilities
        )
    )
)


assert (
    reload_delta
    <=
    1e-7
)


summary = {

    "python":
        ".".join(
            str(x)
            for x
            in sys.version_info[:3]
        ),

    "tensorflow":
        tf.__version__,

    "keras":
        keras.__version__,

    "keras_backend":
        backend_name,

    "numpy":
        np.__version__,

    "seed":
        SEED,

    "train_n":
        int(
            len(
                y_train
            )
        ),

    "train_amp":
        int(
            np.sum(
                y_train == 1
            )
        ),

    "train_decoy":
        int(
            np.sum(
                y_train == 0
            )
        ),

    "validation_n":
        int(
            len(
                y_validation
            )
        ),

    "validation_amp":
        int(
            np.sum(
                y_validation == 1
            )
        ),

    "validation_decoy":
        int(
            np.sum(
                y_validation == 0
            )
        ),

    "preprocessing": {

        "max_length":
            200,

        "alphabet":
            module.amino_acids,

        "oracle_ids":
            oracle_ids,

        "oracle_padding_pass":
            True,
    },

    "architecture": {

        "layer_names":
            layer_names,

        "embedding_input_dim":
            embedding_input_dim,

        "embedding_dim":
            embedding_output_dim,

        "conv_filters":
            conv_filters,

        "conv_kernel":
            conv_kernel,

        "maxpool_size":
            pool_size,

        "lstm_units":
            lstm_units,

        "lstm_dropout":
            0.1,

        "dense_units":
            dense_units,
    },

    "training": {

        "epochs":
            10,

        "batch_size":
            32,

        "loss":
            "binary_crossentropy",

        "optimizer":
            "adam",
    },

    "score_semantics": {

        "positive_class":
            1,

        "threshold":
            0.5,

        "positive_rule":
            "p_amp > 0.5",

        "probability_min":
            float(
                np.min(
                    probabilities
                )
            ),

        "probability_max":
            float(
                np.max(
                    probabilities
                )
            ),
    },

    "serialization": {

        "reload_max_abs_delta":
            reload_delta,

        "pass":
            True,
    },
}


summary_path = (
    OUTPUT_DIR
    / "run_summary.json"
)


with open(
    summary_path,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        summary,
        f,
        indent=2,
        sort_keys=True,
    )


print(
    "AMPSCANNER27_JSON="
    +
    json.dumps(
        summary,
        sort_keys=True,
    )
)
'''


        runner_path.write_text(
            runner_code,
            encoding="utf-8",
        )


        runtime_env = (
            os.environ.copy()
        )

        runtime_env.update(
            {
                "KERAS_BACKEND":
                    "tensorflow",

                "CUDA_VISIBLE_DEVICES":
                    "",

                "OMP_NUM_THREADS":
                    "1",

                "MKL_NUM_THREADS":
                    "1",

                "NUMEXPR_NUM_THREADS":
                    "1",

                "TF_CPP_MIN_LOG_LEVEL":
                    "2",

                "PYTHONHASHSEED":
                    "0",
            }
        )


        def run_selftest(
            output_dir,
        ):

            return run_cmd(
                [
                    ENV_PYTHON,
                    runner_path,
                    TRAIN_SCRIPT,
                    amp_train_fasta,
                    decoy_train_fasta,
                    amp_validation_fasta,
                    decoy_validation_fasta,
                    output_dir,
                    "100",
                ],
                timeout=5400,
                env=runtime_env,
                label=(
                    "AMPScannerV2 exact-source "
                    "synthetic self-test"
                ),
            )


        run1_dir = (
            staging_dir
            / "run1"
        )

        run2_dir = (
            staging_dir
            / "run2"
        )


        result1 = (
            run_selftest(
                run1_dir
            )
        )

        result2 = (
            run_selftest(
                run2_dir
            )
        )


        def parse_runner_summary(
            stdout,
        ):

            for line in (
                stdout
                .splitlines()
            ):

                if line.startswith(
                    "AMPSCANNER27_JSON="
                ):

                    return json.loads(
                        line.split(
                            "=",
                            1,
                        )[1]
                    )

            raise AssertionError(
                "Runner summary marker "
                "was not produced."
            )


        summary1 = (
            parse_runner_summary(
                result1.stdout
            )
        )

        summary2 = (
            parse_runner_summary(
                result2.stdout
            )
        )


        assert (
            summary1[
                "python"
            ].startswith(
                "3.6."
            )
        )

        assert (
            summary1[
                "tensorflow"
            ]
            ==
            "1.2.1"
        )

        assert (
            summary1[
                "keras"
            ]
            ==
            "2.0.6"
        )

        assert (
            summary1[
                "keras_backend"
            ]
            ==
            "tensorflow"
        )

        assert (
            summary1[
                "numpy"
            ]
            ==
            "1.16.0"
        )

        assert (
            summary1[
                "preprocessing"
            ][
                "oracle_padding_pass"
            ]
            is True
        )

        assert (
            summary1[
                "architecture"
            ][
                "layer_names"
            ]
            ==
            [
                "Embedding",
                "Conv1D",
                "MaxPooling1D",
                "LSTM",
                "Dense",
            ]
        )

        assert (
            summary1[
                "serialization"
            ][
                "pass"
            ]
            is True
        )


        predictions1 = pd.read_csv(
            run1_dir
            / "validation_predictions.csv"
        )

        predictions2 = pd.read_csv(
            run2_dir
            / "validation_predictions.csv"
        )


        assert (
            predictions1.shape
            ==
            predictions2.shape
            ==
            (24, 4)
        )


        assert (
            predictions1[
                "y_true"
            ].tolist()
            ==
            predictions2[
                "y_true"
            ].tolist()
        )


        deterministic_delta = float(
            np.max(
                np.abs(
                    predictions1[
                        "p_amp"
                    ].to_numpy()
                    -
                    predictions2[
                        "p_amp"
                    ].to_numpy()
                )
            )
        )


        assert (
            deterministic_delta
            <=
            1e-7
        ), (
            "AMPScannerV2 deterministic "
            "replay failed.\n"
            f"max |delta|="
            f"{deterministic_delta}"
        )


        # ====================================================
        # 17. ATOMIC FINAL BUNDLE
        # ====================================================

        staged_bundle = (
            staging_dir
            / "final_bundle"
        )

        staged_bundle.mkdir(
            parents=True,
            exist_ok=False,
        )


        copy_map = {

            amp_train_fasta:
                (
                    staged_bundle
                    / "synthetic_amp_train.fasta"
                ),

            decoy_train_fasta:
                (
                    staged_bundle
                    / "synthetic_decoy_train.fasta"
                ),

            amp_validation_fasta:
                (
                    staged_bundle
                    / "synthetic_amp_validation.fasta"
                ),

            decoy_validation_fasta:
                (
                    staged_bundle
                    / "synthetic_decoy_validation.fasta"
                ),

            runner_path:
                (
                    staged_bundle
                    / "run_official_ampscannerv2_selftest.py"
                ),

            run1_dir / "model.h5":
                (
                    staged_bundle
                    / "model.h5"
                ),

            run1_dir / "validation_predictions.csv":
                (
                    staged_bundle
                    / "validation_predictions.csv"
                ),

            run1_dir / "run_summary.json":
                (
                    staged_bundle
                    / "run_summary.json"
                ),
        }


        for source, destination in (
            copy_map.items()
        ):

            shutil.copy2(
                source,
                destination,
            )


        assert (
            not FINAL_BUNDLE_DIR.exists()
        )


        os.replace(
            staged_bundle,
            FINAL_BUNDLE_DIR,
        )


        final_paths = {

            "synthetic_amp_train":
                (
                    FINAL_BUNDLE_DIR
                    / "synthetic_amp_train.fasta"
                ),

            "synthetic_decoy_train":
                (
                    FINAL_BUNDLE_DIR
                    / "synthetic_decoy_train.fasta"
                ),

            "synthetic_amp_validation":
                (
                    FINAL_BUNDLE_DIR
                    / "synthetic_amp_validation.fasta"
                ),

            "synthetic_decoy_validation":
                (
                    FINAL_BUNDLE_DIR
                    / "synthetic_decoy_validation.fasta"
                ),

            "runner":
                (
                    FINAL_BUNDLE_DIR
                    / "run_official_ampscannerv2_selftest.py"
                ),

            "model":
                (
                    FINAL_BUNDLE_DIR
                    / "model.h5"
                ),

            "predictions":
                (
                    FINAL_BUNDLE_DIR
                    / "validation_predictions.csv"
                ),

            "run_summary":
                (
                    FINAL_BUNDLE_DIR
                    / "run_summary.json"
                ),
        }


        artifacts = {

            key:
                artifact_entry(
                    path
                )

            for key, path
            in final_paths.items()
        }


        # ====================================================
        # 18. SELF-TEST MANIFEST
        # ====================================================

        manifest = {

            "schema_version":
                "2.0",

            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "IMPLEMENTATION_VALIDATED",

            "model_id":
                METHOD_ID,

            "implementation_validated":
                True,

            "synthetic_selftest_only":
                True,

            "benchmark_training_performed":
                False,

            "benchmark_test_used":
                False,

            "external_target_used":
                False,

            "official_repository":
                OFFICIAL_REPO,

            "official_commit":
                OFFICIAL_COMMIT,

            "source_audit_sha256":
                sha256_file(
                    SOURCE_AUDIT_PATH
                ),

            "environment_audit_sha256":
                sha256_file(
                    ENV_AUDIT_PATH
                ),

            "adapter_contract_sha256":
                sha256_file(
                    ADAPTER_CONTRACT_PATH
                ),

            "selftest": {

                **summary1,

                "deterministic_replay": {

                    "seed":
                        100,

                    "two_independent_processes":
                        True,

                    "single_thread_cpu":
                        True,

                    "max_abs_probability_delta":
                        deterministic_delta,

                    "pass":
                        True,
                },
            },

            "artifacts":
                artifacts,
        }


        atomic_write_json(
            SELFTEST_MANIFEST_PATH,
            manifest,
        )


        validate_selftest_manifest(
            load_json(
                SELFTEST_MANIFEST_PATH
            )
        )


        # ====================================================
        # 19. GLOBAL GATE
        # ====================================================

        validated, gate_after = (
            update_readiness_and_gate()
        )


        assert (
            METHOD_ID
            in validated
        )

        assert (
            len(validated)
            >=
            4
        )


        # ====================================================
        # 20. FINAL REPORT
        # ====================================================

        print(
            "=" * 128
        )

        print(
            "CELL 27 PASS - "
            "AMPScannerV2 OFFICIAL-SOURCE "
            "FULL ADAPTER END-TO-END "
            "SELF-TEST PASSED"
        )

        print(
            "=" * 128
        )

        print(
            "Published method       : AMPScannerV2"
        )

        print(
            "Implementation status  : VALIDATED"
        )

        print(
            "Official commit        :",
            OFFICIAL_COMMIT,
        )

        print(
            "Source audit continuity:",
            SOURCE_AUDIT_ACTION,
        )

        print(
            "-"
            * 128
        )

        print(
            "ENVIRONMENT"
        )

        print(
            "Python                 :",
            FINAL_PROBE[
                "python"
            ],
        )

        print(
            "TensorFlow             :",
            FINAL_PROBE[
                "tensorflow"
            ],
        )

        print(
            "Keras                  :",
            FINAL_PROBE[
                "keras"
            ],
        )

        print(
            "Keras backend          : tensorflow"
        )

        print(
            "NumPy                  :",
            FINAL_PROBE[
                "numpy"
            ],
        )

        print(
            "h5py                   :",
            FINAL_PROBE[
                "h5py"
            ],
        )

        print(
            "Biopython              :",
            FINAL_PROBE[
                "biopython"
            ],
        )

        print(
            "scikit-learn           :",
            FINAL_PROBE[
                "sklearn"
            ],
        )

        print(
            "Theano dependency      :",
            FINAL_PROBE[
                "theano_distribution"
            ],
            "(installed, NOT backend)",
        )

        print(
            "backports.weakref      :",
            FINAL_PROBE[
                "backports_weakref_distribution"
            ],
        )

        print(
            "pip check              : PASS"
        )

        print(
            "-"
            * 128
        )

        print(
            "SOURCE-NATIVE PIPELINE"
        )

        print(
            "Alphabet               : "
            "XACDEFGHIKLMNPQRSTVWY - PASS"
        )

        print(
            "Zero-based encoding    : PASS"
        )

        print(
            "Pre-padding to 200     : PASS"
        )

        print(
            "Embedding              : "
            "21 -> 128 - PASS"
        )

        print(
            "Conv1D                 : "
            "64 filters, kernel 16 - PASS"
        )

        print(
            "MaxPooling1D           : "
            "pool 5 - PASS"
        )

        print(
            "LSTM                   : "
            "100 units, dropout 0.1 - PASS"
        )

        print(
            "Dense sigmoid          : PASS"
        )

        print(
            "Training               : "
            "10 epochs, batch 32 - PASS"
        )

        print(
            "Score                  : "
            "sigmoid P(AMP) - PASS"
        )

        print(
            "Native threshold       : > 0.5"
        )

        print(
            "Deterministic replay   : PASS"
        )

        print(
            "Replay max |delta|     :",
            deterministic_delta,
        )

        print(
            "Serialization reload   : PASS"
        )

        print(
            "-"
            * 128
        )

        print(
            "SCIENTIFIC SCOPE"
        )

        print(
            "Benchmark data used    : FALSE"
        )

        print(
            "Benchmark training     : FALSE"
        )

        print(
            "Benchmark test used    : FALSE"
        )

        print(
            "External target used   : FALSE"
        )

        print(
            "-"
            * 128
        )

        print(
            "Published validated    : "
            f"{len(validated)}/7"
        )

        print(
            "Validated methods      :",
            validated,
        )

        print(
            "TRAINING GATE          :",
            (
                "OPEN"
                if gate_after[
                    "open"
                ]
                else
                "CLOSED"
            ),
        )

        print(
            "Self-test manifest     :",
            SELFTEST_MANIFEST_PATH,
        )

        print(
            "Manifest SHA256        :",
            sha256_file(
                SELFTEST_MANIFEST_PATH
            ),
        )

        print(
            "NEXT                   : "
            "CELL 28 - amPEPpy "
            "OFFICIAL SOURCE + "
            "FULL ADAPTER CLOSURE"
        )

        print(
            "=" * 128
        )


    finally:

        if staging_dir.exists():

            shutil.rmtree(
                staging_dir,
                ignore_errors=True,
            )

================================================================================================================================
CELL 27 PASS - AMPScannerV2 OFFICIAL-SOURCE FULL ADAPTER END-TO-END SELF-TEST PASSED
================================================================================================================================
Published method       : AMPScannerV2
Implementation status  : VALIDATED
Official commit        : 933052e2365631fe93098892120ee535e0ba381a
Source audit continuity: EXISTING CELL27-v1 SOURCE AUDIT VERIFIED
--------------------------------------------------------------------------------------------------------------------------------
ENVIRONMENT
Python                 : 3.6.13
TensorFlow             : 1.2.1
Keras                  : 2.0.6
Keras backend          : tensorflow
NumPy                  : 1.16.0
h5py                   : 2.6.0
Biopython              : 1.69
scikit-learn           : 0.20.0
Theano dependency      : 0.9.0 (installed, NOT backend)
backports.weakref      : 1.0rc1
pip check              : PASS
--------------------------------------------------------------------------------------------------------------------------------
SOURCE-NATIVE PIPELINE
Alphabet               : XACDEFGHIKLMNPQRSTVWY - PASS
Zero-based encoding    : PASS
Pre-padding to 200     : PASS
Embedding              : 21 -> 128 - PASS
Conv1D                 : 64 filters, kernel 16 - PASS
MaxPooling1D           : pool 5 - PASS
LSTM                   : 100 units, dropout 0.1 - PASS
Dense sigmoid          : PASS
Training               : 10 epochs, batch 32 - PASS
Score                  : sigmoid P(AMP) - PASS
Native threshold       : > 0.5
Deterministic replay   : PASS
Replay max |delta|     : 0.0
Serialization reload   : PASS
--------------------------------------------------------------------------------------------------------------------------------
SCIENTIFIC SCOPE
Benchmark data used    : FALSE
Benchmark training     : FALSE
Benchmark test used    : FALSE
External target used   : FALSE
--------------------------------------------------------------------------------------------------------------------------------
Published validated    : 4/7
Validated methods      : ['ampep', 'ampgram', 'ampir', 'ampscannerv2']
TRAINING GATE          : CLOSED
Self-test manifest     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampscannerv2_FINAL_adapter_selftest.json
Manifest SHA256        : 025c951b10807b789108d13baca066486cc2d2e127397c3b54ae44a666a1b96f
NEXT                   : CELL 28 - amPEPpy OFFICIAL SOURCE + FULL ADAPTER CLOSURE
================================================================================================================================

In [20]:
# ============================================================
# CELL 28 - amPEPpy 1.0
# OFFICIAL v1.0 SOURCE + PAPER ENVIRONMENT
# + FULL SYNTHETIC ADAPTER SELF-TEST
#
# SOURCE -> CONTRACT -> ENVIRONMENT -> SELF-TEST -> VALIDATE -> LOCK
#
# SCIENTIFIC BOUNDARY
# -------------------
# - NO benchmark train/validation/test data are read.
# - NO external target data are read.
# - NO pretrained repeated-inference shortcut is used.
# - Official amPEPpy v1.0 source is pinned to tag v1.0 commit.
# - Paper RF recipe is locked:
#       105 CTD Distribution descriptors
#       160 trees
# - Benchmark seeds remain 100..109.
# - Synthetic self-test uses seed 100.
# - Training gate remains CLOSED unless all 7 published methods pass.
# ============================================================

from pathlib import Path
from datetime import datetime

import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import urllib.request

import numpy as np
import pandas as pd


# ============================================================
# 1. PATHS / UPSTREAM LOCKS
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

WORK_ROOT = Path(
    "/home/pc/genpept_benchmark17_work"
)

SOURCE_ROOT = Path(
    "/home/pc/genpept_sources"
)


METHOD_ID = "ampeppy"

DISPLAY_NAME = "amPEPpy"


SELFTEST_ROOT = (
    WORK_ROOT
    / "published_selftests"
    / METHOD_ID
)


OFFICIAL_REPO = (
    "tlawrence3/amPEPpy"
)

OFFICIAL_TAG = "v1.0"

OFFICIAL_COMMIT = (
    "aa1f694c6cb3d09b16bc9378bed77f59e4f1e780"
)

SOURCE_DIR = (
    SOURCE_ROOT
    / (
        "amPEPpy_v1.0_"
        + OFFICIAL_COMMIT
    )
)


ROUTE_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_published_method_route_contract.json"
)

TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)

READINESS_PATH = (
    AUDIT_DIR
    / "benchmark17_published_method_local_readiness_latest.csv"
)


AMPEP_SELFTEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampep_FINAL_adapter_selftest.json"
)

AMPSCANNER_SELFTEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampscannerv2_FINAL_adapter_selftest.json"
)

AMPGRAM_SELFTEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampgram_FINAL_adapter_selftest.json"
)

AMPIR_SELFTEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampir_FINAL_adapter_selftest.json"
)


SOURCE_AUDIT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampeppy_v1_official_source_audit.json"
)

ENV_AUDIT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampeppy_v1_environment.json"
)

ADAPTER_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampeppy_FINAL_implementation_contract.json"
)

SELFTEST_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_ampeppy_FINAL_adapter_selftest.json"
)


FINAL_BUNDLE_DIR = (
    SELFTEST_ROOT
    / "cell28_final_adapter_selftest"
)


EXPECTED_ROUTE_SHA256 = (
    "dd7d6a743f088cef95fb49288dcf1801"
    "c9dc335be2656e627e7fc7f3bf7170bd"
)

EXPECTED_AMPEP_SELFTEST_SHA256 = (
    "18786bf2b024c8dab4e1bf28fbd843265"
    "68bda559e56a9c20f5895091ca64f4e"
)

EXPECTED_AMPSCANNER_SELFTEST_SHA256 = (
    "025c951b10807b789108d13baca066486"
    "cc2d2e127397c3b54ae44a666a1b96f"
)

EXPECTED_AMPGRAM_SELFTEST_SHA256 = (
    "399d1d695e72f42ad591caf637de03b91"
    "0d07e09b1f1f5805054e629153aee3d"
)


PUBLISHED_IDS = [
    "ampep",
    "ampscannerv2",
    "ampgram",
    "ampir",
    "ampeppy",
    "ai4amp",
    "amplify",
]


for directory in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    WORK_ROOT,
    SOURCE_ROOT,
]:

    assert directory.is_dir(), (
        f"Required directory missing:\n"
        f"{directory}"
    )


SELFTEST_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

SOURCE_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


for path in [
    ROUTE_CONTRACT_PATH,
    TRAINING_GATE_PATH,
    READINESS_PATH,
    AMPEP_SELFTEST_PATH,
    AMPSCANNER_SELFTEST_PATH,
    AMPGRAM_SELFTEST_PATH,
    AMPIR_SELFTEST_PATH,
]:

    assert path.is_file(), (
        f"Required upstream artifact missing:\n"
        f"{path}"
    )


# ============================================================
# 2. HELPERS
# ============================================================

def sha256_file(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as handle:

        for chunk in iter(
            lambda: handle.read(
                1024 * 1024
            ),
            b"",
        ):

            h.update(
                chunk
            )

    return h.hexdigest()


def git_blob_sha1_bytes(data):

    header = (
        f"blob {len(data)}\0"
    ).encode(
        "utf-8"
    )

    return hashlib.sha1(
        header
        + data
    ).hexdigest()


def git_blob_sha1_file(path):

    return git_blob_sha1_bytes(
        Path(path)
        .read_bytes()
    )


def load_json(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as handle:

        return json.load(
            handle
        )


def atomic_write_json(
    path,
    payload,
):

    path = Path(
        path
    )

    tmp = path.with_name(
        path.name
        + ".tmp"
    )

    with open(
        tmp,
        "w",
        encoding="utf-8",
    ) as handle:

        json.dump(
            payload,
            handle,
            indent=2,
            ensure_ascii=False,
        )

        handle.flush()

        os.fsync(
            handle.fileno()
        )

    os.replace(
        tmp,
        path,
    )


def atomic_write_csv(
    path,
    dataframe,
):

    path = Path(
        path
    )

    tmp = path.with_name(
        path.name
        + ".tmp"
    )

    dataframe.to_csv(
        tmp,
        index=False,
    )

    os.replace(
        tmp,
        path,
    )


def boolish(value):

    if isinstance(
        value,
        (
            bool,
            np.bool_,
        ),
    ):

        return bool(
            value
        )

    text = (
        str(value)
        .strip()
        .lower()
    )

    if text in {
        "true",
        "1",
        "yes",
    }:

        return True

    if text in {
        "false",
        "0",
        "no",
    }:

        return False

    raise AssertionError(
        f"Cannot interpret as bool: "
        f"{value!r}"
    )


def run_cmd(
    command,
    timeout=1800,
    env=None,
    check=True,
    label="subprocess",
    cwd=None,
):

    result = subprocess.run(
        [
            str(x)
            for x
            in command
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        env=env,
        cwd=(
            None
            if cwd is None
            else str(cwd)
        ),
        timeout=timeout,
    )

    if (
        check
        and
        result.returncode != 0
    ):

        print(
            "=" * 128
        )

        print(
            "SUBPROCESS FAILURE -",
            label,
        )

        print(
            "COMMAND:",
            [
                str(x)
                for x
                in command
            ],
        )

        print(
            "RETURN CODE:",
            result.returncode,
        )

        print(
            "--- STDOUT ---"
        )

        print(
            result.stdout
        )

        print(
            "--- STDERR ---"
        )

        print(
            result.stderr
        )

        print(
            "=" * 128
        )

        raise AssertionError(
            f"{label} failed "
            f"with return code "
            f"{result.returncode}"
        )

    return result


def artifact_entry(path):

    path = Path(
        path
    )

    assert path.is_file(), (
        f"Artifact missing: "
        f"{path}"
    )

    return {

        "path":
            str(path),

        "size_bytes":
            int(
                path.stat().st_size
            ),

        "sha256":
            sha256_file(
                path
            ),
    }


def verify_artifact_entry(
    entry,
):

    path = Path(
        entry[
            "path"
        ]
    )

    assert path.is_file()

    assert (
        int(
            path.stat().st_size
        )
        ==
        int(
            entry[
                "size_bytes"
            ]
        )
    )

    assert (
        sha256_file(
            path
        )
        ==
        entry[
            "sha256"
        ]
    )


# ============================================================
# 3. VERIFY IMMUTABLE UPSTREAM STATE
# ============================================================

assert (
    sha256_file(
        ROUTE_CONTRACT_PATH
    )
    ==
    EXPECTED_ROUTE_SHA256
)


assert (
    sha256_file(
        AMPEP_SELFTEST_PATH
    )
    ==
    EXPECTED_AMPEP_SELFTEST_SHA256
)


assert (
    sha256_file(
        AMPSCANNER_SELFTEST_PATH
    )
    ==
    EXPECTED_AMPSCANNER_SELFTEST_SHA256
)


assert (
    sha256_file(
        AMPGRAM_SELFTEST_PATH
    )
    ==
    EXPECTED_AMPGRAM_SELFTEST_SHA256
)


for model_id, path in [

    (
        "ampep",
        AMPEP_SELFTEST_PATH,
    ),

    (
        "ampscannerv2",
        AMPSCANNER_SELFTEST_PATH,
    ),

    (
        "ampgram",
        AMPGRAM_SELFTEST_PATH,
    ),

    (
        "ampir",
        AMPIR_SELFTEST_PATH,
    ),

]:

    payload = load_json(
        path
    )

    assert (
        payload[
            "implementation_validated"
        ]
        is True
    )

    assert (
        payload[
            "benchmark_training_performed"
        ]
        is False
    )

    assert (
        payload[
            "benchmark_test_used"
        ]
        is False
    )


    observed_model = (

        payload.get(
            "model_id"
        )

        or

        payload.get(
            "adapter_contract",
            {},
        ).get(
            "model_id"
        )
    )


    assert (
        observed_model
        ==
        model_id
    )


route_payload = load_json(
    ROUTE_CONTRACT_PATH
)


assert (
    route_payload[
        "status"
    ]
    ==
    "PUBLISHED_METHOD_ROUTES_LOCKED_BEFORE_TRAINING"
)


assert (
    route_payload[
        "restart_safe"
    ]
    is True
)


route_core = (
    route_payload[
        "contract"
    ]
)


assert (
    route_core[
        "published_model_ids"
    ]
    ==
    PUBLISHED_IDS
)


route = (
    route_core[
        "methods"
    ][
        METHOD_ID
    ]
)


assert (
    route[
        "paper_doi"
    ]
    ==
    "10.1093/bioinformatics/btaa917"
)


assert (
    route[
        "published_family"
    ]
    ==
    "random_forest"
)


assert (
    route[
        "published_representation"
    ]
    ==
    "CTD_distribution_descriptor_feature_set"
)


assert (
    route[
        "reported_feature_count"
    ]
    ==
    105
)


assert (
    route[
        "official_repository"
    ]
    ==
    OFFICIAL_REPO
)


assert (
    route[
        "locked_route"
    ]
    ==
    "official_source_retraining"
)


assert (
    route[
        "implementation_environment"
    ]
    ==
    "dedicated_python_environment"
)


assert (
    route[
        "official_train_module"
    ]
    is True
)


assert (
    route[
        "pretrained_repeated_inference_allowed"
    ]
    is False
)


assert (
    route[
        "ten_independent_retraining_runs"
    ]
    is True
)


assert (
    route[
        "config_lock_required_before_training"
    ]
    is True
)


gate_before = load_json(
    TRAINING_GATE_PATH
)


assert (
    gate_before[
        "open"
    ]
    is False
)


assert (
    gate_before[
        "benchmark_training_allowed"
    ]
    is False
)


if not SELFTEST_MANIFEST_PATH.is_file():

    assert (
        gate_before[
            "published_methods_implementation_validated"
        ]
        ==
        4
    )

    assert sorted(
        gate_before[
            "validated_methods"
        ]
    ) == [

        "ampep",
        "ampgram",
        "ampir",
        "ampscannerv2",
    ]

else:

    assert (
        gate_before[
            "published_methods_implementation_validated"
        ]
        >=
        5
    )

    assert (
        METHOD_ID
        in gate_before[
            "validated_methods"
        ]
    )


# ============================================================
# 4. PIN OFFICIAL amPEPpy v1.0 SOURCE
# ============================================================

PINNED_FILES = {

    "README.md":
        "3cfdbae82a6a928241b7eb4217d4222092d58384",

    "requirements.txt":
        "5cddbb17cf94d1ab654eb558d756c8e6ad1f345c",

    "setup.py":
        "2f6dc2ce475f7984e732bc868d80aa4f37805704",

    "amPEPpy/__init__.py":
        "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391",

    "amPEPpy/_version.py":
        "4802e90f8edc38346215a3277cf96f0fa7474c32",

    "amPEPpy/amPEP.py":
        "29b87cb6ba75469b16f575785c92c5b87dbeaece",

    "paper_results/feature_drop.lengthbalanced.txt":
        "226d9cbf1b63b32229f2b08e9872d677ef7180fd",
}


RAW_BASE = (
    "https://raw.githubusercontent.com/"
    "tlawrence3/amPEPpy/"
    + OFFICIAL_COMMIT
)


def acquire_pinned_file(
    relpath,
    expected_blob,
):

    destination = (
        SOURCE_DIR
        / relpath
    )

    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    if (
        destination.is_file()
        and
        git_blob_sha1_file(
            destination
        )
        ==
        expected_blob
    ):

        return (
            "REUSED EXACT PINNED FILE"
        )


    url = (
        RAW_BASE
        + "/"
        + relpath
    )


    request = urllib.request.Request(
        url,
        headers={
            "User-Agent":
                "GenPept-Benchmark17-amPEPpy-v1/1.0"
        },
    )


    try:

        with urllib.request.urlopen(
            request,
            timeout=120,
        ) as response:

            data = (
                response.read()
            )

    except Exception as exc:

        raise AssertionError(
            "Could not acquire "
            "pinned amPEPpy v1.0 source:\n"
            f"{url}\n"
            f"{type(exc).__name__}: {exc}"
        )


    observed_blob = (
        git_blob_sha1_bytes(
            data
        )
    )


    assert (
        observed_blob
        ==
        expected_blob
    ), (
        f"Source blob mismatch: "
        f"{relpath}\n"
        f"Expected: {expected_blob}\n"
        f"Actual  : {observed_blob}"
    )


    tmp = (
        destination.with_name(
            destination.name
            + ".download.tmp"
        )
    )

    tmp.write_bytes(
        data
    )

    os.replace(
        tmp,
        destination,
    )


    assert (
        git_blob_sha1_file(
            destination
        )
        ==
        expected_blob
    )


    return (
        "DOWNLOADED EXACT PINNED FILE"
    )


source_actions = {}


for relpath, blob in (
    PINNED_FILES.items()
):

    source_actions[
        relpath
    ] = acquire_pinned_file(
        relpath,
        blob,
    )


for relpath, blob in (
    PINNED_FILES.items()
):

    path = (
        SOURCE_DIR
        / relpath
    )

    assert (
        path.is_file()
    )

    assert (
        git_blob_sha1_file(
            path
        )
        ==
        blob
    )


README_PATH = (
    SOURCE_DIR
    / "README.md"
)

SETUP_PATH = (
    SOURCE_DIR
    / "setup.py"
)

VERSION_PATH = (
    SOURCE_DIR
    / "amPEPpy/_version.py"
)

SOURCE_SCRIPT = (
    SOURCE_DIR
    / "amPEPpy/amPEP.py"
)

FEATURE_DROP_PATH = (
    SOURCE_DIR
    / "paper_results/feature_drop.lengthbalanced.txt"
)


readme_text = (
    README_PATH.read_text(
        encoding="utf-8"
    )
)

setup_text = (
    SETUP_PATH.read_text(
        encoding="utf-8"
    )
)

version_text = (
    VERSION_PATH.read_text(
        encoding="utf-8"
    )
)

source_text = (
    SOURCE_SCRIPT.read_text(
        encoding="utf-8"
    )
)

feature_drop_text = (
    FEATURE_DROP_PATH
    .read_text(
        encoding="utf-8"
    )
    .strip()
)


assert (
    '__version__ = "1.0"'
    in version_text
)


assert (
    feature_drop_text
    ==
    "polarizability.1.0"
)


assert (
    "same settings as the manuscript"
    in readme_text
)


assert (
    "--seed 2012"
    in readme_text
)


assert re.search(
    r'--num-trees".*default=160',
    source_text,
    flags=re.S,
)


assert (
    "Default is 160 which was shown "
    "to produce the lowest out of bag "
    "error on training data."
    in source_text
)


assert re.search(
    (
        r"RandomForestClassifier"
        r"\(n_estimators=args\.num_trees,"
        r"\s*oob_score=True,"
        r"\s*random_state=args\.seed,"
        r"\s*n_jobs=args\.num_processes\)"
    ),
    source_text,
    flags=re.S,
)


assert (
    "training_df = sklearn.utils.shuffle"
    "(training_df, random_state=args.seed)"
    in source_text
)


assert (
    "preds = clf.predict_proba(classify_df)"
    in source_text
)


assert (
    'print("probability_nonAMP\\t'
    'probability_AMP\\tpredicted\\tseq_id"'
    in source_text
)


assert (
    "CTD = {'hydrophobicity':"
    in source_text
)


assert (
    "groups = [1, 2, 3]"
    in source_text
)


assert (
    "values = [0, 25, 50, 75, 100]"
    in source_text
)


assert (
    "python_requires='~=3.5'"
    in setup_text
)


for dependency in [
    "biopython",
    "numpy",
    "scikit-learn",
    "pandas",
]:

    assert (
        dependency
        in setup_text
    )


# ============================================================
# 5. IMMUTABLE SOURCE / PUBLICATION CONTRACT
# ============================================================

SOURCE_AUDIT_CORE = {

    "schema_version":
        "1.0",

    "model_id":
        METHOD_ID,

    "official_repository":
        OFFICIAL_REPO,

    "official_tag":
        OFFICIAL_TAG,

    "pinned_commit":
        OFFICIAL_COMMIT,

    "source_directory":
        str(
            SOURCE_DIR
        ),

    "files": {

        relpath: {

            "git_blob_sha1":
                blob,

            "sha256":
                sha256_file(
                    SOURCE_DIR
                    / relpath
                ),

            "path":
                str(
                    SOURCE_DIR
                    / relpath
                ),
        }

        for relpath, blob
        in PINNED_FILES.items()
    },

    "published_recipe": {

        "version":
            "1.0",

        "descriptor_family":
            (
                "CTD Distribution / "
                "Global Protein Sequence Descriptors"
            ),

        "feature_count":
            105,

        "feature_drop_for_canonical_manuscript_command":
            [],

        "exploratory_feature_drop_artifact":
            [
                "polarizability.1.0"
            ],

        "rf_trees":
            160,

        "oob_score":
            True,

        "random_state":
            "seed_argument",

        "n_jobs":
            "num_processes_argument",

        "paper_example_seed":
            2012,

        "benchmark_seeds":
            list(
                range(
                    100,
                    110,
                )
            ),

        "positive_probability":
            "predict_proba column for class 1",

        "native_classification":
            "RandomForestClassifier.predict",
    },

    "paper_environment": {

        "python":
            "3.8.3",

        "scikit_learn":
            "0.23.1",
    },
}


if SOURCE_AUDIT_PATH.is_file():

    existing = load_json(
        SOURCE_AUDIT_PATH
    )

    assert (
        existing[
            "status"
        ]
        ==
        "AMPEPPY_V1_OFFICIAL_SOURCE_LOCKED"
    )

    assert (
        existing[
            "audit"
        ]
        ==
        SOURCE_AUDIT_CORE
    ), (
        "Existing amPEPpy source audit "
        "differs; refusing silent overwrite."
    )

    SOURCE_AUDIT_ACTION = (
        "EXISTING IDENTICAL "
        "SOURCE AUDIT VERIFIED"
    )

else:

    atomic_write_json(
        SOURCE_AUDIT_PATH,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AMPEPPY_V1_OFFICIAL_SOURCE_LOCKED",

            "audit":
                SOURCE_AUDIT_CORE,
        },
    )

    SOURCE_AUDIT_ACTION = (
        "NEW SOURCE AUDIT "
        "ATOMICALLY COMMITTED"
    )


# ============================================================
# 6. DEDICATED PYTHON 3.8.3 ENVIRONMENT
#
# Conda creates ONLY Python 3.8.3 + pip.
# Historical scientific packages are then restored from wheels.
#
# Paper-locked:
#   Python       3.8.3
#   scikit-learn 0.23.1
# ============================================================

def locate_conda():

    candidates = []


    if os.environ.get(
        "CONDA_EXE"
    ):

        candidates.append(
            Path(
                os.environ[
                    "CONDA_EXE"
                ]
            )
        )


    candidates.extend(
        [
            (
                Path.home()
                / "miniconda3"
                / "bin"
                / "conda"
            ),

            (
                Path.home()
                / "anaconda3"
                / "bin"
                / "conda"
            ),
        ]
    )


    which_conda = (
        shutil.which(
            "conda"
        )
    )


    if which_conda:

        candidates.append(
            Path(
                which_conda
            )
        )


    seen = set()


    for candidate in candidates:

        key = str(
            candidate
        )

        if key in seen:

            continue


        seen.add(
            key
        )


        if (
            candidate.is_file()
            and
            os.access(
                candidate,
                os.X_OK,
            )
        ):

            return (
                candidate.resolve()
            )


    raise AssertionError(
        "Conda executable not found."
    )


CONDA_EXE = (
    locate_conda()
)

CONDA_ROOT = (
    CONDA_EXE
    .parent
    .parent
)

ENV_PREFIX = (
    CONDA_ROOT
    / "envs"
    / "genpept_ampeppy_v1"
)

ENV_PYTHON = (
    ENV_PREFIX
    / "bin"
    / "python"
)


PROBE_CODE = r'''
import json
import sys

payload = {
    "python":
        ".".join(
            str(x)
            for x
            in sys.version_info[:3]
        )
}

for key, module_name in [
    ("numpy", "numpy"),
    ("scipy", "scipy"),
    ("pandas", "pandas"),
    ("biopython", "Bio"),
    ("sklearn", "sklearn"),
    ("joblib", "joblib"),
    ("threadpoolctl", "threadpoolctl"),
]:

    try:

        module = __import__(
            module_name,
            fromlist=["*"],
        )

        payload[key] = (
            module.__version__
        )

        payload[
            key + "_path"
        ] = (
            module.__file__
        )

    except Exception as exc:

        payload[
            key + "_error"
        ] = (
            type(exc).__name__
            + ": "
            + str(exc)
        )

print(
    "AMPEPPY28_PROBE="
    + json.dumps(
        payload,
        sort_keys=True,
    )
)
'''


def probe_environment():

    if not ENV_PYTHON.is_file():

        return (
            None,
            None,
        )


    result = run_cmd(
        [
            ENV_PYTHON,
            "-c",
            PROBE_CODE,
        ],
        timeout=240,
        label=(
            "amPEPpy "
            "environment probe"
        ),
        check=False,
    )


    payload = None


    for line in (
        result.stdout
        .splitlines()
    ):

        if line.startswith(
            "AMPEPPY28_PROBE="
        ):

            payload = json.loads(
                line.split(
                    "=",
                    1,
                )[1]
            )

            break


    return (
        payload,
        result,
    )


def environment_ok(
    probe,
):

    if not probe:

        return False


    required = [

        "python",
        "numpy",
        "scipy",
        "pandas",
        "biopython",
        "sklearn",
        "joblib",
        "threadpoolctl",
    ]


    if any(
        key not in probe
        for key in required
    ):

        return False


    return (

        str(
            probe[
                "python"
            ]
        )
        ==
        "3.8.3"

        and

        str(
            probe[
                "sklearn"
            ]
        )
        ==
        "0.23.1"

        and

        str(
            probe[
                "numpy"
            ]
        )
        ==
        "1.18.5"

        and

        str(
            probe[
                "scipy"
            ]
        )
        ==
        "1.5.0"

        and

        str(
            probe[
                "pandas"
            ]
        )
        ==
        "1.0.5"

        and

        str(
            probe[
                "biopython"
            ]
        )
        ==
        "1.77"

        and

        str(
            probe[
                "joblib"
            ]
        )
        ==
        "0.15.1"

        and

        str(
            probe[
                "threadpoolctl"
            ]
        )
        ==
        "2.1.0"
    )


def python_is_383():

    if not ENV_PYTHON.is_file():

        return False


    result = run_cmd(
        [
            ENV_PYTHON,
            "-c",
            (
                "import sys;"
                "print('%d.%d.%d' "
                "% sys.version_info[:3])"
            ),
        ],
        timeout=60,
        label=(
            "Python 3.8.3 probe"
        ),
        check=False,
    )


    return (
        result.returncode == 0
        and
        result.stdout
        .strip()
        ==
        "3.8.3"
    )


initial_probe, _ = (
    probe_environment()
)


if not environment_ok(
    initial_probe
):

    # --------------------------------------------------------
    # Remove ONLY this method-specific prefix if wrong Python.
    # --------------------------------------------------------

    if (
        ENV_PREFIX.exists()
        and
        not python_is_383()
    ):

        removal = run_cmd(
            [
                CONDA_EXE,
                "remove",
                "-y",
                "-p",
                ENV_PREFIX,
                "--all",
            ],
            timeout=1800,
            label=(
                "remove invalid amPEPpy "
                "dedicated environment"
            ),
            check=False,
        )


        if (
            removal.returncode != 0
            and
            ENV_PREFIX.exists()
        ):

            shutil.rmtree(
                ENV_PREFIX
            )


    # --------------------------------------------------------
    # Create ONLY Python 3.8.3 + pip.
    # --------------------------------------------------------

    if not ENV_PYTHON.is_file():

        attempts = [

            [
                CONDA_EXE,
                "create",
                "-y",
                "-p",
                ENV_PREFIX,
                "-c",
                "defaults",
                "python=3.8.3",
                "pip",
            ],

            [
                CONDA_EXE,
                "create",
                "-y",
                "-p",
                ENV_PREFIX,
                "-c",
                "conda-forge",
                "python=3.8.3",
                "pip",
            ],
        ]


        created = False

        failures = []


        for index, command in enumerate(
            attempts,
            start=1,
        ):

            result = run_cmd(
                command,
                timeout=3600,
                label=(
                    "create amPEPpy "
                    "Python3.8.3 environment "
                    f"attempt {index}"
                ),
                check=False,
            )


            # Accept a valid dedicated Python 3.8.3 prefix even if
            # Conda returned non-zero after leaving a usable prefix.
            if (
                ENV_PYTHON.is_file()
                and
                python_is_383()
            ):

                created = True

                break


            failures.append(
                {
                    "attempt":
                        index,

                    "returncode":
                        result.returncode,

                    "stdout":
                        result.stdout[
                            -12000:
                        ],

                    "stderr":
                        result.stderr[
                            -12000:
                        ],
                }
            )


            if (
                ENV_PREFIX.exists()
                and
                not python_is_383()
            ):

                cleanup = run_cmd(
                    [
                        CONDA_EXE,
                        "remove",
                        "-y",
                        "-p",
                        ENV_PREFIX,
                        "--all",
                    ],
                    timeout=1800,
                    label=(
                        "cleanup failed "
                        "amPEPpy environment attempt"
                    ),
                    check=False,
                )


                if (
                    cleanup.returncode != 0
                    and
                    ENV_PREFIX.exists()
                ):

                    shutil.rmtree(
                        ENV_PREFIX
                    )


        if not created:

            print(
                "=" * 128
            )

            print(
                "amPEPpy PYTHON 3.8.3 "
                "ENVIRONMENT CREATION FAILED"
            )


            for failure in failures:

                print(
                    "ATTEMPT:",
                    failure[
                        "attempt"
                    ],
                )

                print(
                    "RETURN CODE:",
                    failure[
                        "returncode"
                    ],
                )

                print(
                    "--- STDOUT TAIL ---"
                )

                print(
                    failure[
                        "stdout"
                    ]
                )

                print(
                    "--- STDERR TAIL ---"
                )

                print(
                    failure[
                        "stderr"
                    ]
                )


            print(
                "=" * 128
            )


            raise AssertionError(
                "Could not create dedicated "
                "Python 3.8.3 environment."
            )


    assert (
        ENV_PYTHON.is_file()
    )


    assert (
        python_is_383()
    )


    # --------------------------------------------------------
    # Packaging toolchain.
    # --------------------------------------------------------

    run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "install",
            "--upgrade",

            "pip==23.1.2",
            "setuptools==68.0.0",
            "wheel==0.40.0",
        ],
        timeout=1800,
        label=(
            "pin Python 3.8 "
            "packaging toolchain"
        ),
    )


    # --------------------------------------------------------
    # 2020 wheel-backed scientific stack.
    # --------------------------------------------------------

    run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--only-binary=:all:",
            "--force-reinstall",

            "numpy==1.18.5",
            "scipy==1.5.0",
            "pandas==1.0.5",
            "biopython==1.77",
            "scikit-learn==0.23.1",
            "joblib==0.15.1",
            "threadpoolctl==2.1.0",
            "python-dateutil==2.8.1",
            "pytz==2020.1",
            "six==1.15.0",
        ],
        timeout=5400,
        label=(
            "restore amPEPpy v1 "
            "scientific environment"
        ),
    )


    pip_check = run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "check",
        ],
        timeout=300,
        label=(
            "amPEPpy pip "
            "dependency check"
        ),
        check=False,
    )


    if (
        pip_check.returncode != 0
    ):

        print(
            "=" * 128
        )

        print(
            "amPEPpy PIP CHECK FAILED"
        )

        print(
            pip_check.stdout
        )

        print(
            pip_check.stderr
        )

        print(
            "=" * 128
        )

        raise AssertionError(
            "amPEPpy dedicated environment "
            "dependency check failed."
        )


# ============================================================
# 7. FINAL ENVIRONMENT PROBE
# ============================================================

FINAL_PROBE, FINAL_PROBE_RESULT = (
    probe_environment()
)


if not environment_ok(
    FINAL_PROBE
):

    print(
        "=" * 128
    )

    print(
        "amPEPpy FINAL ENVIRONMENT "
        "PROBE FAILED"
    )

    print(
        json.dumps(
            FINAL_PROBE,
            indent=2,
            sort_keys=True,
        )
        if FINAL_PROBE
        else
        "NO PROBE JSON"
    )


    if (
        FINAL_PROBE_RESULT
        is not None
    ):

        print(
            "--- STDOUT ---"
        )

        print(
            FINAL_PROBE_RESULT.stdout
        )

        print(
            "--- STDERR ---"
        )

        print(
            FINAL_PROBE_RESULT.stderr
        )


    print(
        "=" * 128
    )


    raise AssertionError(
        "amPEPpy v1 environment "
        "is not exact-compatible."
    )


environment_root = str(
    ENV_PREFIX.resolve()
)


for key in [

    "numpy_path",
    "scipy_path",
    "pandas_path",
    "biopython_path",
    "sklearn_path",
    "joblib_path",
    "threadpoolctl_path",

]:

    assert (
        key
        in FINAL_PROBE
    )


    assert (
        str(
            FINAL_PROBE[
                key
            ]
        ).startswith(
            environment_root
        )
    ), (
        f"{key} resolved outside "
        f"dedicated environment:\n"
        f"{FINAL_PROBE[key]}"
    )


# ============================================================
# 8. ENVIRONMENT AUDIT + IMPLEMENTATION CONTRACT
# ============================================================

ENV_AUDIT_CORE = {

    "schema_version":
        "1.0",

    "model_id":
        METHOD_ID,

    "environment_prefix":
        str(
            ENV_PREFIX
        ),

    "python_executable":
        str(
            ENV_PYTHON
        ),

    "observed":
        FINAL_PROBE,

    "paper_locked": {

        "python":
            "3.8.3",

        "scikit_learn":
            "0.23.1",
    },

    "compatibility_support": {

        "numpy":
            "1.18.5",

        "scipy":
            "1.5.0",

        "pandas":
            "1.0.5",

        "biopython":
            "1.77",

        "joblib":
            "0.15.1",

        "threadpoolctl":
            "2.1.0",
    },

    "source_tag":
        OFFICIAL_TAG,

    "source_commit":
        OFFICIAL_COMMIT,
}


if ENV_AUDIT_PATH.is_file():

    existing = load_json(
        ENV_AUDIT_PATH
    )

    assert (
        existing[
            "status"
        ]
        ==
        "AMPEPPY_V1_ENVIRONMENT_READY"
    )

    assert (
        existing[
            "audit"
        ]
        ==
        ENV_AUDIT_CORE
    ), (
        "Existing amPEPpy environment "
        "audit differs; refusing silent overwrite."
    )

    ENV_AUDIT_ACTION = (
        "EXISTING IDENTICAL "
        "ENVIRONMENT AUDIT VERIFIED"
    )

else:

    atomic_write_json(
        ENV_AUDIT_PATH,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AMPEPPY_V1_ENVIRONMENT_READY",

            "audit":
                ENV_AUDIT_CORE,
        },
    )

    ENV_AUDIT_ACTION = (
        "NEW ENVIRONMENT AUDIT "
        "ATOMICALLY COMMITTED"
    )


ADAPTER_CONTRACT_CORE = {

    "schema_version":
        "1.0",

    "model_id":
        METHOD_ID,

    "display_name":
        DISPLAY_NAME,

    "paper_doi":
        "10.1093/bioinformatics/btaa917",

    "implementation_route":
        "official_source_retraining",

    "official_repository":
        OFFICIAL_REPO,

    "official_tag":
        OFFICIAL_TAG,

    "official_commit":
        OFFICIAL_COMMIT,

    "paper_environment": {

        "python":
            "3.8.3",

        "scikit_learn":
            "0.23.1",
    },

    "representation": {

        "family":
            "CTD_distribution_descriptor_feature_set",

        "feature_count":
            105,

        "feature_selection":
            "none_for_canonical_manuscript_command",
    },

    "random_forest": {

        "n_estimators":
            160,

        "criterion":
            "gini_default",

        "max_features":
            "auto_default",

        "bootstrap":
            True,

        "oob_score":
            True,

        "random_state":
            "benchmark_seed",

        "n_jobs":
            "1_for_reproducible_selftest",
    },

    "training": {

        "paper_example_seed":
            2012,

        "benchmark_retraining_seeds":
            list(
                range(
                    100,
                    110,
                )
            ),
    },

    "score_semantics": {

        "classes":
            [
                0,
                1,
            ],

        "positive_class":
            1,

        "amp_score":
            (
                "predict_proba[:, "
                "class_1_column]"
            ),

        "native_classification":
            "RandomForestClassifier.predict",
    },

    "selftest_boundary": {

        "synthetic_only":
            True,

        "benchmark_training":
            False,

        "benchmark_test":
            False,

        "external_target":
            False,
    },
}


if ADAPTER_CONTRACT_PATH.is_file():

    existing = load_json(
        ADAPTER_CONTRACT_PATH
    )

    assert (
        existing[
            "status"
        ]
        ==
        "AMPEPPY_IMPLEMENTATION_CONTRACT_LOCKED"
    )

    assert (
        existing[
            "contract"
        ]
        ==
        ADAPTER_CONTRACT_CORE
    ), (
        "Existing amPEPpy adapter contract "
        "differs; refusing silent overwrite."
    )

    ADAPTER_CONTRACT_ACTION = (
        "EXISTING IDENTICAL "
        "ADAPTER CONTRACT VERIFIED"
    )

else:

    atomic_write_json(
        ADAPTER_CONTRACT_PATH,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AMPEPPY_IMPLEMENTATION_CONTRACT_LOCKED",

            "implementation_validated":
                False,

            "benchmark_training_performed":
                False,

            "benchmark_test_used":
                False,

            "external_target_used":
                False,

            "contract":
                ADAPTER_CONTRACT_CORE,
        },
    )

    ADAPTER_CONTRACT_ACTION = (
        "NEW ADAPTER CONTRACT "
        "ATOMICALLY COMMITTED"
    )


# ============================================================
# 9. GLOBAL GATE HELPERS
# ============================================================

def validated_methods_from_manifests():

    validated = []


    for model_id in PUBLISHED_IDS:

        path = (
            MANIFEST_DIR
            / (
                f"benchmark17_{model_id}_"
                f"FINAL_adapter_selftest.json"
            )
        )


        if not path.is_file():

            continue


        payload = load_json(
            path
        )


        if (
            payload.get(
                "implementation_validated",
                False,
            )
            is True
        ):

            validated.append(
                model_id
            )


    return sorted(
        validated
    )


def update_readiness_and_gate():

    readiness = pd.read_csv(
        READINESS_PATH,
        low_memory=False,
    )


    required_columns = {

        "model_id",
        "adapter_self_test_passed",
        "implementation_validated",
        "local_state",
        "training_allowed",
    }


    assert (
        required_columns
        .issubset(
            readiness.columns
        )
    )


    mask = (
        readiness[
            "model_id"
        ]
        .astype(str)
        ==
        METHOD_ID
    )


    assert (
        int(
            mask.sum()
        )
        ==
        1
    )


    readiness.loc[
        mask,
        "adapter_self_test_passed",
    ] = True


    readiness.loc[
        mask,
        "implementation_validated",
    ] = True


    readiness.loc[
        mask,
        "local_state",
    ] = (
        "IMPLEMENTATION_VALIDATED"
    )


    validated = (
        validated_methods_from_manifests()
    )


    for required_model in [

        "ampep",
        "ampscannerv2",
        "ampgram",
        "ampir",
        "ampeppy",

    ]:

        assert (
            required_model
            in validated
        )


    assert (
        5
        <= len(
            validated
        )
        <= 7
    )


    gate = load_json(
        TRAINING_GATE_PATH
    )


    gate[
        "published_methods_implementation_validated"
    ] = len(
        validated
    )


    gate[
        "validated_methods"
    ] = validated


    gate[
        "updated_at"
    ] = (
        datetime.now()
        .astimezone()
        .isoformat()
    )


    if len(
        validated
    ) == 7:

        gate[
            "open"
        ] = True

        gate[
            "benchmark_training_allowed"
        ] = True

        gate[
            "reason"
        ] = (
            "All seven published-method "
            "implementations validated."
        )

        readiness.loc[
            :,
            "training_allowed",
        ] = True

    else:

        gate[
            "open"
        ] = False

        gate[
            "benchmark_training_allowed"
        ] = False

        gate[
            "reason"
        ] = (
            f"{len(validated)}/7 "
            f"published-method "
            f"implementations validated."
        )

        readiness.loc[
            mask,
            "training_allowed",
        ] = False


    atomic_write_csv(
        READINESS_PATH,
        readiness,
    )


    atomic_write_json(
        TRAINING_GATE_PATH,
        gate,
    )


    gate_check = load_json(
        TRAINING_GATE_PATH
    )


    readiness_check = pd.read_csv(
        READINESS_PATH,
        low_memory=False,
    )


    mask_check = (
        readiness_check[
            "model_id"
        ]
        .astype(str)
        ==
        METHOD_ID
    )


    assert (
        int(
            mask_check.sum()
        )
        ==
        1
    )


    assert (
        boolish(
            readiness_check.loc[
                mask_check,
                "adapter_self_test_passed",
            ].iloc[0]
        )
        is True
    )


    assert (
        boolish(
            readiness_check.loc[
                mask_check,
                "implementation_validated",
            ].iloc[0]
        )
        is True
    )


    assert (
        str(
            readiness_check.loc[
                mask_check,
                "local_state",
            ].iloc[0]
        )
        ==
        "IMPLEMENTATION_VALIDATED"
    )


    assert (
        gate_check[
            "validated_methods"
        ]
        ==
        validated
    )


    assert (
        gate_check[
            "published_methods_implementation_validated"
        ]
        ==
        len(
            validated
        )
    )


    if len(
        validated
    ) < 7:

        assert (
            gate_check[
                "open"
            ]
            is False
        )

        assert (
            gate_check[
                "benchmark_training_allowed"
            ]
            is False
        )

    else:

        assert (
            gate_check[
                "open"
            ]
            is True
        )

        assert (
            gate_check[
                "benchmark_training_allowed"
            ]
            is True
        )


    return (
        validated,
        gate_check,
    )


# ============================================================
# 10. SELF-TEST MANIFEST VALIDATOR
# ============================================================

def validate_selftest_manifest(
    payload,
):

    assert (
        payload[
            "status"
        ]
        ==
        "IMPLEMENTATION_VALIDATED"
    )


    assert (
        payload[
            "model_id"
        ]
        ==
        METHOD_ID
    )


    assert (
        payload[
            "implementation_validated"
        ]
        is True
    )


    assert (
        payload[
            "synthetic_selftest_only"
        ]
        is True
    )


    assert (
        payload[
            "benchmark_training_performed"
        ]
        is False
    )


    assert (
        payload[
            "benchmark_test_used"
        ]
        is False
    )


    assert (
        payload[
            "external_target_used"
        ]
        is False
    )


    assert (
        payload[
            "official_tag"
        ]
        ==
        OFFICIAL_TAG
    )


    assert (
        payload[
            "official_commit"
        ]
        ==
        OFFICIAL_COMMIT
    )


    assert (
        payload[
            "source_audit_sha256"
        ]
        ==
        sha256_file(
            SOURCE_AUDIT_PATH
        )
    )


    assert (
        payload[
            "environment_audit_sha256"
        ]
        ==
        sha256_file(
            ENV_AUDIT_PATH
        )
    )


    assert (
        payload[
            "adapter_contract_sha256"
        ]
        ==
        sha256_file(
            ADAPTER_CONTRACT_PATH
        )
    )


    selftest = (
        payload[
            "selftest"
        ]
    )


    assert (
        selftest[
            "source_version"
        ]
        ==
        "1.0"
    )


    assert (
        selftest[
            "feature_count"
        ]
        ==
        105
    )


    assert (
        selftest[
            "feature_oracle"
        ][
            "pass"
        ]
        is True
    )


    assert (
        selftest[
            "feature_oracle"
        ][
            "max_abs_delta"
        ]
        <=
        1e-12
    )


    assert (
        selftest[
            "rf"
        ][
            "n_estimators"
        ]
        ==
        160
    )


    assert (
        selftest[
            "rf"
        ][
            "oob_score"
        ]
        is True
    )


    assert (
        selftest[
            "rf"
        ][
            "classes"
        ]
        ==
        [
            0,
            1,
        ]
    )


    assert (
        selftest[
            "rf"
        ][
            "effective_max_features_per_tree"
        ]
        ==
        10
    )


    assert (
        selftest[
            "score_semantics"
        ][
            "positive_class"
        ]
        ==
        1
    )


    assert (
        selftest[
            "source_predict_alignment"
        ][
            "pass"
        ]
        is True
    )


    assert (
        selftest[
            "source_predict_alignment"
        ][
            "max_abs_delta"
        ]
        <=
        1e-12
    )


    assert (
        selftest[
            "serialization"
        ][
            "pass"
        ]
        is True
    )


    assert (
        selftest[
            "deterministic_replay"
        ][
            "pass"
        ]
        is True
    )


    assert (
        selftest[
            "deterministic_replay"
        ][
            "max_abs_probability_delta"
        ]
        <=
        1e-12
    )


    for entry in (
        payload[
            "artifacts"
        ].values()
    ):

        verify_artifact_entry(
            entry
        )


# ============================================================
# 11. REUSE COMPLETED SELF-TEST
# ============================================================

if SELFTEST_MANIFEST_PATH.is_file():

    existing_selftest = load_json(
        SELFTEST_MANIFEST_PATH
    )


    validate_selftest_manifest(
        existing_selftest
    )


    validated, gate_check = (
        update_readiness_and_gate()
    )


    print(
        "=" * 128
    )

    print(
        "CELL 28 PASS - "
        "amPEPpy v1.0 FULL ADAPTER "
        "SELF-TEST REUSED AND VERIFIED"
    )

    print(
        "=" * 128
    )

    print(
        "Published method       : amPEPpy"
    )

    print(
        "Implementation status  : VALIDATED"
    )

    print(
        "Official tag           :",
        OFFICIAL_TAG,
    )

    print(
        "Official commit        :",
        OFFICIAL_COMMIT,
    )

    print(
        "Python                 :",
        FINAL_PROBE[
            "python"
        ],
    )

    print(
        "scikit-learn           :",
        FINAL_PROBE[
            "sklearn"
        ],
    )

    print(
        "Published validated    : "
        f"{len(validated)}/7"
    )

    print(
        "Validated methods      :",
        validated,
    )

    print(
        "TRAINING GATE          :",
        (
            "OPEN"
            if gate_check[
                "open"
            ]
            else
            "CLOSED"
        ),
    )

    print(
        "Self-test manifest     :",
        SELFTEST_MANIFEST_PATH,
    )

    print(
        "Manifest SHA256        :",
        sha256_file(
            SELFTEST_MANIFEST_PATH
        ),
    )

    print(
        "NEXT                   : "
        "CELL 29 - AI4AMP "
        "SOURCE + PC6 + "
        "FULL ADAPTER CLOSURE"
    )

    print(
        "=" * 128
    )


else:

    # ========================================================
    # 12. FIRST-RUN PRECONDITION
    # ========================================================

    if FINAL_BUNDLE_DIR.exists():

        orphan_path = (
            SELFTEST_ROOT
            / (
                "cell28_orphaned_"
                + datetime.now()
                .strftime(
                    "%Y%m%d_%H%M%S"
                )
            )
        )

        os.replace(
            FINAL_BUNDLE_DIR,
            orphan_path,
        )

        print(
            "Archived incomplete prior "
            "Cell 28 bundle to:",
            orphan_path,
        )


    # ========================================================
    # 13. SYNTHETIC-ONLY DATA
    # ========================================================

    rng = np.random.RandomState(
        280028
    )


    AMP_ALPHABET = np.array(
        list(
            "KRWFLIV"
        )
    )


    DECOY_ALPHABET = np.array(
        list(
            "DENQGSTAP"
        )
    )


    def synthetic_sequence(
        alphabet,
        length,
    ):

        value = "".join(
            rng.choice(
                alphabet,
                size=length,
            ).tolist()
        )


        assert (
            10
            <= len(value)
            <= 100
        )


        assert (
            set(
                value
            ).issubset(
                set(
                    "ACDEFGHIKLMNPQRSTVWY"
                )
            )
        )


        return value


    train_amp = [

        synthetic_sequence(
            AMP_ALPHABET,
            18 + (
                i % 31
            ),
        )

        for i in range(
            64
        )
    ]


    train_decoy = [

        synthetic_sequence(
            DECOY_ALPHABET,
            18 + (
                i % 31
            ),
        )

        for i in range(
            64
        )
    ]


    validation_amp = [

        synthetic_sequence(
            AMP_ALPHABET,
            20 + (
                i % 23
            ),
        )

        for i in range(
            16
        )
    ]


    validation_decoy = [

        synthetic_sequence(
            DECOY_ALPHABET,
            20 + (
                i % 23
            ),
        )

        for i in range(
            16
        )
    ]


    staging_dir = Path(
        tempfile.mkdtemp(
            prefix=(
                "cell28_ampeppy_"
            ),
            dir=str(
                SELFTEST_ROOT
            ),
        )
    )


    try:

        def write_fasta(
            path,
            sequences,
            prefix,
        ):

            with open(
                path,
                "w",
                encoding="utf-8",
            ) as handle:

                for index, sequence in enumerate(
                    sequences,
                    start=1,
                ):

                    handle.write(
                        f">{prefix}_{index:03d}\n"
                        f"{sequence}\n"
                    )


        amp_train_fasta = (
            staging_dir
            / "synthetic_amp_train.fasta"
        )

        decoy_train_fasta = (
            staging_dir
            / "synthetic_decoy_train.fasta"
        )

        validation_fasta = (
            staging_dir
            / "synthetic_validation.fasta"
        )


        write_fasta(
            amp_train_fasta,
            train_amp,
            "AMP_TR",
        )


        write_fasta(
            decoy_train_fasta,
            train_decoy,
            "DEC_TR",
        )


        with open(
            validation_fasta,
            "w",
            encoding="utf-8",
        ) as handle:

            for index, sequence in enumerate(
                validation_amp,
                start=1,
            ):

                handle.write(
                    f">AMP_VA_{index:03d}\n"
                    f"{sequence}\n"
                )


            for index, sequence in enumerate(
                validation_decoy,
                start=1,
            ):

                handle.write(
                    f">DEC_VA_{index:03d}\n"
                    f"{sequence}\n"
                )


        # ====================================================
        # 14. PAPER-LOCKED RUNNER
        # ====================================================

        runner_path = (
            staging_dir
            / "run_official_ampeppy_v1_selftest.py"
        )


        runner_code = r'''
from pathlib import Path
from types import SimpleNamespace

import json
import os
import pickle
import sys

import numpy as np
import pandas as pd
import sklearn

from Bio import __version__ as biopython_version


SOURCE_ROOT = Path(
    sys.argv[1]
).resolve()

AMP_TRAIN = Path(
    sys.argv[2]
).resolve()

DECOY_TRAIN = Path(
    sys.argv[3]
).resolve()

VALIDATION_FASTA = Path(
    sys.argv[4]
).resolve()

OUT_DIR = Path(
    sys.argv[5]
).resolve()

SEED = int(
    sys.argv[6]
)


OUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


assert (
    ".".join(
        str(x)
        for x in sys.version_info[:3]
    )
    ==
    "3.8.3"
)


assert (
    sklearn.__version__
    ==
    "0.23.1"
)


sys.path.insert(
    0,
    str(
        SOURCE_ROOT
    ),
)


from amPEPpy import amPEP as mod
from amPEPpy._version import __version__


assert (
    __version__
    ==
    "1.0"
)


# ============================================================
# A. EXACT 105-FEATURE REGISTRY + NUMERIC ORACLE
# ============================================================

PROPERTY_ORDER = [

    "hydrophobicity",

    "normalized.van.der.waals",

    "polarity",

    "polarizability",

    "charge",

    "secondary",

    "solvent",
]


EXPECTED_COLUMNS = [

    f"{prop}.{group}.{percent}"

    for prop
    in PROPERTY_ORDER

    for group
    in [
        1,
        2,
        3,
    ]

    for percent
    in [
        0,
        25,
        50,
        75,
        100,
    ]
]


assert (
    len(
        EXPECTED_COLUMNS
    )
    ==
    105
)


assert (
    len(
        set(
            EXPECTED_COLUMNS
        )
    )
    ==
    105
)


oracle_fasta = (
    OUT_DIR
    / "feature_oracle.fasta"
)


oracle_fasta.write_text(
    ">oracle_A10\n"
    "AAAAAAAAAA\n",
    encoding="utf-8",
)


with open(
    oracle_fasta,
    "r",
    encoding="utf-8",
) as handle:

    oracle_df = (
        mod.score(
            handle
        )
    )


assert (
    oracle_df.shape
    ==
    (
        1,
        105,
    )
)


assert (
    oracle_df.columns.tolist()
    ==
    EXPECTED_COLUMNS
)


assert (
    oracle_df.index.tolist()
    ==
    [
        "oracle_A10"
    ]
)


assert (
    np.all(
        np.isfinite(
            oracle_df.to_numpy(
                dtype=float
            )
        )
    )
)


# AAAAAAAAAA:
#
# hydrophobicity              group 2
# normalized van der Waals    group 1
# polarity                    group 2
# polarizability              group 1
# charge                      group 2
# secondary                   group 1
# solvent                     group 1
#
# With 10 residues, source distribution indexes are:
# first, 25%, 50%, 75%, last
# => 10, 20, 50, 70, 100 percent.


ACTIVE_GROUP = {

    "hydrophobicity":
        2,

    "normalized.van.der.waals":
        1,

    "polarity":
        2,

    "polarizability":
        1,

    "charge":
        2,

    "secondary":
        1,

    "solvent":
        1,
}


ACTIVE_VALUES = [

    10.0,
    20.0,
    50.0,
    70.0,
    100.0,
]


expected_oracle = []


for prop in PROPERTY_ORDER:

    for group in [
        1,
        2,
        3,
    ]:

        if (
            group
            ==
            ACTIVE_GROUP[
                prop
            ]
        ):

            expected_oracle.extend(
                ACTIVE_VALUES
            )

        else:

            expected_oracle.extend(
                [
                    0.0
                ]
                * 5
            )


expected_oracle = np.asarray(
    expected_oracle,
    dtype=float,
)


observed_oracle = (
    oracle_df.iloc[
        0
    ].to_numpy(
        dtype=float
    )
)


feature_oracle_delta = float(
    np.max(
        np.abs(
            expected_oracle
            -
            observed_oracle
        )
    )
)


assert (
    feature_oracle_delta
    <=
    1e-12
)


# ============================================================
# B. SOURCE score() ON SYNTHETIC TRAIN DATA
# ============================================================

with open(
    AMP_TRAIN,
    "r",
    encoding="utf-8",
) as handle:

    amp_features = (
        mod.score(
            handle
        )
    )


with open(
    DECOY_TRAIN,
    "r",
    encoding="utf-8",
) as handle:

    decoy_features = (
        mod.score(
            handle
        )
    )


assert (
    amp_features.shape
    ==
    (
        64,
        105,
    )
)


assert (
    decoy_features.shape
    ==
    (
        64,
        105,
    )
)


assert (
    amp_features.columns.tolist()
    ==
    EXPECTED_COLUMNS
)


assert (
    decoy_features.columns.tolist()
    ==
    EXPECTED_COLUMNS
)


all_features = pd.concat(
    [
        amp_features,
        decoy_features,
    ],
    axis=0,
)


assert (
    np.all(
        np.isfinite(
            all_features.to_numpy(
                dtype=float
            )
        )
    )
)


for prop in PROPERTY_ORDER:

    for group in [
        1,
        2,
        3,
    ]:

        block = [

            f"{prop}.{group}.{percent}"

            for percent in [
                0,
                25,
                50,
                75,
                100,
            ]
        ]


        assert (
            float(
                np.abs(
                    all_features[
                        block
                    ].to_numpy(
                        dtype=float
                    )
                ).sum()
            )
            >
            0.0
        )


# ============================================================
# C. EXACT OFFICIAL train()
# ============================================================

original_cwd = (
    Path.cwd()
)


os.chdir(
    str(
        OUT_DIR
    )
)


try:

    train_args = (
        SimpleNamespace(

            positive=
                str(
                    AMP_TRAIN
                ),

            negative=
                str(
                    DECOY_TRAIN
                ),

            drop_feature=
                None,

            max_tree=
                175,

            min_tree=
                23,

            seed=
                SEED,

            num_processes=
                1,

            num_trees=
                160,

            tree_test=
                False,

            feature_importance=
                False,
        )
    )


    mod.train(
        train_args
    )


finally:

    os.chdir(
        str(
            original_cwd
        )
    )


model_path = (
    OUT_DIR
    / "amPEP.model"
)


assert (
    model_path.is_file()
)


with open(
    model_path,
    "rb",
) as handle:

    clf = (
        pickle.load(
            handle
        )
    )


assert (
    clf.__class__.__name__
    ==
    "RandomForestClassifier"
)


assert (
    clf.n_estimators
    ==
    160
)


assert (
    clf.oob_score
    is True
)


assert (
    clf.random_state
    ==
    SEED
)


assert (
    clf.n_jobs
    ==
    1
)


assert (
    clf.bootstrap
    is True
)


assert (
    clf.criterion
    ==
    "gini"
)


assert (
    clf.max_features
    ==
    "auto"
)


classes = [

    int(x)

    for x in (
        clf.classes_
        .tolist()
    )
]


assert (
    classes
    ==
    [
        0,
        1,
    ]
)


assert (
    len(
        clf.estimators_
    )
    ==
    160
)


tree_max_features = sorted(
    set(
        int(
            tree.max_features_
        )

        for tree
        in clf.estimators_
    )
)


assert (
    tree_max_features
    ==
    [
        10
    ]
)


# ============================================================
# D. EXACT OFFICIAL predict() + DIRECT ALIGNMENT
# ============================================================

prediction_path = (
    OUT_DIR
    / "source_predictions.tsv"
)


predict_args = (
    SimpleNamespace(

        model=
            str(
                model_path
            ),

        seq_file=
            str(
                VALIDATION_FASTA
            ),

        out_file=
            str(
                prediction_path
            ),

        drop_feature=
            None,
    )
)


mod.predict(
    predict_args
)


assert (
    prediction_path.is_file()
)


source_predictions = pd.read_csv(
    prediction_path,
    sep="\t",
)


assert (
    source_predictions.columns.tolist()
    ==
    [
        "probability_nonAMP",
        "probability_AMP",
        "predicted",
        "seq_id",
    ]
)


assert (
    source_predictions.shape
    ==
    (
        32,
        4,
    )
)


with open(
    VALIDATION_FASTA,
    "r",
    encoding="utf-8",
) as handle:

    validation_features = (
        mod.score(
            handle
        )
    )


assert (
    validation_features.shape
    ==
    (
        32,
        105,
    )
)


assert (
    validation_features.columns.tolist()
    ==
    EXPECTED_COLUMNS
)


direct_probabilities = (
    clf.predict_proba(
        validation_features
    )
)


assert (
    direct_probabilities.shape
    ==
    (
        32,
        2,
    )
)


assert (
    [
        int(x)
        for x in (
            clf.classes_
            .tolist()
        )
    ]
    ==
    [
        0,
        1,
    ]
)


positive_index = (
    classes.index(
        1
    )
)


direct_p_amp = (
    direct_probabilities[
        :,
        positive_index
    ]
)


source_p_amp = (
    source_predictions[
        "probability_AMP"
    ].to_numpy(
        dtype=float
    )
)


alignment_delta = float(
    np.max(
        np.abs(
            direct_p_amp
            -
            source_p_amp
        )
    )
)


assert (
    alignment_delta
    <=
    1e-12
)


direct_class = (
    clf.predict(
        validation_features
    )
    .astype(
        int
    )
)


source_class = (

    source_predictions[
        "predicted"
    ]

    .map(
        {
            "nonAMP":
                0,

            "AMP":
                1,
        }
    )

    .to_numpy(
        dtype=int
    )
)


assert (
    np.array_equal(
        direct_class,
        source_class,
    )
)


assert (
    np.all(
        np.isfinite(
            direct_p_amp
        )
    )
)


assert (
    np.all(
        direct_p_amp
        >=
        0.0
    )
)


assert (
    np.all(
        direct_p_amp
        <=
        1.0
    )
)


# ============================================================
# E. SERIALIZATION / RELOAD
# ============================================================

with open(
    model_path,
    "rb",
) as handle:

    reloaded = (
        pickle.load(
            handle
        )
    )


reloaded_p_amp = (

    reloaded.predict_proba(
        validation_features
    )[
        :,
        positive_index
    ]
)


reload_delta = float(
    np.max(
        np.abs(
            direct_p_amp
            -
            reloaded_p_amp
        )
    )
)


assert (
    reload_delta
    <=
    1e-12
)


normalized_prediction_path = (
    OUT_DIR
    / "validation_predictions.csv"
)


normalized = pd.DataFrame(
    {
        "seq_id":
            source_predictions[
                "seq_id"
            ].astype(
                str
            ),

        "p_nonamp":
            direct_probabilities[
                :,
                0
            ],

        "p_amp":
            direct_probabilities[
                :,
                1
            ],

        "predicted_class":
            direct_class,
    }
)


normalized.to_csv(
    normalized_prediction_path,
    index=False,
)


summary = {

    "source_version":
        "1.0",

    "python":
        ".".join(
            str(x)
            for x
            in sys.version_info[:3]
        ),

    "sklearn":
        sklearn.__version__,

    "biopython":
        biopython_version,

    "seed":
        SEED,

    "train": {

        "amp":
            64,

        "nonamp":
            64,

        "total":
            128,
    },

    "validation": {

        "amp":
            16,

        "nonamp":
            16,

        "total":
            32,
    },

    "feature_count":
        105,

    "feature_oracle": {

        "sequence":
            "AAAAAAAAAA",

        "expected_active_distribution":
            ACTIVE_VALUES,

        "max_abs_delta":
            feature_oracle_delta,

        "pass":
            True,
    },

    "rf": {

        "n_estimators":
            int(
                clf.n_estimators
            ),

        "oob_score":
            bool(
                clf.oob_score
            ),

        "oob_accuracy":
            float(
                clf.oob_score_
            ),

        "random_state":
            int(
                clf.random_state
            ),

        "n_jobs":
            int(
                clf.n_jobs
            ),

        "bootstrap":
            bool(
                clf.bootstrap
            ),

        "criterion":
            str(
                clf.criterion
            ),

        "max_features_parameter":
            str(
                clf.max_features
            ),

        "effective_max_features_per_tree":
            int(
                tree_max_features[
                    0
                ]
            ),

        "classes":
            classes,
    },

    "score_semantics": {

        "positive_class":
            1,

        "probability_column":
            "probability_AMP",

        "probability_min":
            float(
                np.min(
                    direct_p_amp
                )
            ),

        "probability_max":
            float(
                np.max(
                    direct_p_amp
                )
            ),
    },

    "source_predict_alignment": {

        "max_abs_delta":
            alignment_delta,

        "class_labels_equal":
            True,

        "pass":
            True,
    },

    "serialization": {

        "reload_max_abs_delta":
            reload_delta,

        "pass":
            True,
    },
}


summary_path = (
    OUT_DIR
    / "run_summary.json"
)


with open(
    summary_path,
    "w",
    encoding="utf-8",
) as handle:

    json.dump(
        summary,
        handle,
        indent=2,
        sort_keys=True,
    )


print(
    "AMPEPPY28_JSON="
    +
    json.dumps(
        summary,
        sort_keys=True,
    )
)
'''


        runner_path.write_text(
            runner_code,
            encoding="utf-8",
        )


        runtime_env = (
            os.environ.copy()
        )


        runtime_env.update(
            {
                "OMP_NUM_THREADS":
                    "1",

                "MKL_NUM_THREADS":
                    "1",

                "OPENBLAS_NUM_THREADS":
                    "1",

                "NUMEXPR_NUM_THREADS":
                    "1",

                "PYTHONHASHSEED":
                    "0",
            }
        )


        def run_selftest(
            output_dir,
        ):

            return run_cmd(
                [
                    ENV_PYTHON,
                    runner_path,
                    SOURCE_DIR,
                    amp_train_fasta,
                    decoy_train_fasta,
                    validation_fasta,
                    output_dir,
                    "100",
                ],
                timeout=5400,
                env=runtime_env,
                label=(
                    "amPEPpy v1 exact-source "
                    "synthetic self-test"
                ),
            )


        run1_dir = (
            staging_dir
            / "run1"
        )

        run2_dir = (
            staging_dir
            / "run2"
        )


        result1 = (
            run_selftest(
                run1_dir
            )
        )


        result2 = (
            run_selftest(
                run2_dir
            )
        )


        def parse_runner_summary(
            stdout,
        ):

            for line in (
                stdout
                .splitlines()
            ):

                if line.startswith(
                    "AMPEPPY28_JSON="
                ):

                    return json.loads(
                        line.split(
                            "=",
                            1,
                        )[1]
                    )


            raise AssertionError(
                "amPEPpy runner summary "
                "marker was not produced."
            )


        summary1 = (
            parse_runner_summary(
                result1.stdout
            )
        )


        summary2 = (
            parse_runner_summary(
                result2.stdout
            )
        )


        assert (
            summary1[
                "source_version"
            ]
            ==
            "1.0"
        )


        assert (
            summary1[
                "python"
            ]
            ==
            "3.8.3"
        )


        assert (
            summary1[
                "sklearn"
            ]
            ==
            "0.23.1"
        )


        assert (
            summary1[
                "feature_count"
            ]
            ==
            105
        )


        assert (
            summary1[
                "feature_oracle"
            ][
                "pass"
            ]
            is True
        )


        assert (
            summary1[
                "feature_oracle"
            ][
                "max_abs_delta"
            ]
            <=
            1e-12
        )


        assert (
            summary1[
                "rf"
            ][
                "n_estimators"
            ]
            ==
            160
        )


        assert (
            summary1[
                "rf"
            ][
                "oob_score"
            ]
            is True
        )


        assert (
            summary1[
                "rf"
            ][
                "random_state"
            ]
            ==
            100
        )


        assert (
            summary1[
                "rf"
            ][
                "effective_max_features_per_tree"
            ]
            ==
            10
        )


        assert (
            summary1[
                "rf"
            ][
                "classes"
            ]
            ==
            [
                0,
                1,
            ]
        )


        assert (
            summary1[
                "source_predict_alignment"
            ][
                "pass"
            ]
            is True
        )


        assert (
            summary1[
                "source_predict_alignment"
            ][
                "max_abs_delta"
            ]
            <=
            1e-12
        )


        assert (
            summary1[
                "serialization"
            ][
                "pass"
            ]
            is True
        )


        assert (
            summary1[
                "serialization"
            ][
                "reload_max_abs_delta"
            ]
            <=
            1e-12
        )


        predictions1 = pd.read_csv(
            run1_dir
            / "validation_predictions.csv"
        )


        predictions2 = pd.read_csv(
            run2_dir
            / "validation_predictions.csv"
        )


        assert (
            predictions1.shape
            ==
            predictions2.shape
            ==
            (
                32,
                4,
            )
        )


        assert (
            predictions1[
                "seq_id"
            ].tolist()
            ==
            predictions2[
                "seq_id"
            ].tolist()
        )


        assert (
            predictions1[
                "predicted_class"
            ].tolist()
            ==
            predictions2[
                "predicted_class"
            ].tolist()
        )


        deterministic_delta = float(
            np.max(
                np.abs(
                    predictions1[
                        "p_amp"
                    ].to_numpy(
                        dtype=float
                    )
                    -
                    predictions2[
                        "p_amp"
                    ].to_numpy(
                        dtype=float
                    )
                )
            )
        )


        assert (
            deterministic_delta
            <=
            1e-12
        ), (
            "amPEPpy deterministic replay failed.\n"
            f"max |delta| = "
            f"{deterministic_delta}"
        )


        # ====================================================
        # 15. ATOMIC FINAL BUNDLE
        # ====================================================

        staged_bundle = (
            staging_dir
            / "final_bundle"
        )


        staged_bundle.mkdir(
            parents=True,
            exist_ok=False,
        )


        copy_map = {

            amp_train_fasta:
                (
                    staged_bundle
                    / "synthetic_amp_train.fasta"
                ),

            decoy_train_fasta:
                (
                    staged_bundle
                    / "synthetic_decoy_train.fasta"
                ),

            validation_fasta:
                (
                    staged_bundle
                    / "synthetic_validation.fasta"
                ),

            runner_path:
                (
                    staged_bundle
                    / "run_official_ampeppy_v1_selftest.py"
                ),

            run1_dir / "feature_oracle.fasta":
                (
                    staged_bundle
                    / "feature_oracle.fasta"
                ),

            run1_dir / "amPEP.model":
                (
                    staged_bundle
                    / "amPEP.model"
                ),

            run1_dir / "source_predictions.tsv":
                (
                    staged_bundle
                    / "source_predictions.tsv"
                ),

            run1_dir / "validation_predictions.csv":
                (
                    staged_bundle
                    / "validation_predictions.csv"
                ),

            run1_dir / "run_summary.json":
                (
                    staged_bundle
                    / "run_summary.json"
                ),
        }


        for source, destination in (
            copy_map.items()
        ):

            shutil.copy2(
                source,
                destination,
            )


        assert (
            not FINAL_BUNDLE_DIR.exists()
        )


        os.replace(
            staged_bundle,
            FINAL_BUNDLE_DIR,
        )


        final_paths = {

            "synthetic_amp_train":
                (
                    FINAL_BUNDLE_DIR
                    / "synthetic_amp_train.fasta"
                ),

            "synthetic_decoy_train":
                (
                    FINAL_BUNDLE_DIR
                    / "synthetic_decoy_train.fasta"
                ),

            "synthetic_validation":
                (
                    FINAL_BUNDLE_DIR
                    / "synthetic_validation.fasta"
                ),

            "runner":
                (
                    FINAL_BUNDLE_DIR
                    / "run_official_ampeppy_v1_selftest.py"
                ),

            "feature_oracle":
                (
                    FINAL_BUNDLE_DIR
                    / "feature_oracle.fasta"
                ),

            "model":
                (
                    FINAL_BUNDLE_DIR
                    / "amPEP.model"
                ),

            "source_predictions":
                (
                    FINAL_BUNDLE_DIR
                    / "source_predictions.tsv"
                ),

            "predictions":
                (
                    FINAL_BUNDLE_DIR
                    / "validation_predictions.csv"
                ),

            "run_summary":
                (
                    FINAL_BUNDLE_DIR
                    / "run_summary.json"
                ),
        }


        artifacts = {

            key:
                artifact_entry(
                    path
                )

            for key, path
            in final_paths.items()
        }


        # ====================================================
        # 16. COMMIT SELF-TEST MANIFEST
        # ====================================================

        manifest = {

            "schema_version":
                "2.0",

            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "IMPLEMENTATION_VALIDATED",

            "model_id":
                METHOD_ID,

            "implementation_validated":
                True,

            "synthetic_selftest_only":
                True,

            "benchmark_training_performed":
                False,

            "benchmark_test_used":
                False,

            "external_target_used":
                False,

            "official_repository":
                OFFICIAL_REPO,

            "official_tag":
                OFFICIAL_TAG,

            "official_commit":
                OFFICIAL_COMMIT,

            "source_audit_sha256":
                sha256_file(
                    SOURCE_AUDIT_PATH
                ),

            "environment_audit_sha256":
                sha256_file(
                    ENV_AUDIT_PATH
                ),

            "adapter_contract_sha256":
                sha256_file(
                    ADAPTER_CONTRACT_PATH
                ),

            "selftest": {

                **summary1,

                "deterministic_replay": {

                    "seed":
                        100,

                    "two_independent_processes":
                        True,

                    "single_worker_rf":
                        True,

                    "max_abs_probability_delta":
                        deterministic_delta,

                    "pass":
                        True,
                },
            },

            "artifacts":
                artifacts,
        }


        atomic_write_json(
            SELFTEST_MANIFEST_PATH,
            manifest,
        )


        validate_selftest_manifest(
            load_json(
                SELFTEST_MANIFEST_PATH
            )
        )


        # ====================================================
        # 17. UPDATE GLOBAL GATE
        # ====================================================

        validated, gate_after = (
            update_readiness_and_gate()
        )


        assert (
            METHOD_ID
            in validated
        )


        assert (
            len(
                validated
            )
            >=
            5
        )


        # ====================================================
        # 18. FINAL REPORT
        # ====================================================

        print(
            "=" * 128
        )

        print(
            "CELL 28 PASS - "
            "amPEPpy v1.0 OFFICIAL-SOURCE "
            "FULL ADAPTER END-TO-END "
            "SELF-TEST PASSED"
        )

        print(
            "=" * 128
        )

        print(
            "Published method       : amPEPpy"
        )

        print(
            "Implementation status  : VALIDATED"
        )

        print(
            "Official tag           :",
            OFFICIAL_TAG,
        )

        print(
            "Official commit        :",
            OFFICIAL_COMMIT,
        )

        print(
            "Source audit           :",
            SOURCE_AUDIT_ACTION,
        )

        print(
            "-" * 128
        )

        print(
            "PAPER / SOURCE ENVIRONMENT"
        )

        print(
            "Python                 :",
            FINAL_PROBE[
                "python"
            ],
        )

        print(
            "scikit-learn           :",
            FINAL_PROBE[
                "sklearn"
            ],
        )

        print(
            "NumPy                  :",
            FINAL_PROBE[
                "numpy"
            ],
        )

        print(
            "SciPy                  :",
            FINAL_PROBE[
                "scipy"
            ],
        )

        print(
            "pandas                 :",
            FINAL_PROBE[
                "pandas"
            ],
        )

        print(
            "Biopython              :",
            FINAL_PROBE[
                "biopython"
            ],
        )

        print(
            "-" * 128
        )

        print(
            "SOURCE-NATIVE PIPELINE"
        )

        print(
            "CTD Distribution       : "
            "105 features - PASS"
        )

        print(
            "Exact feature order    : PASS"
        )

        print(
            "A10 numeric oracle     : PASS"
        )

        print(
            "Oracle max |delta|     :",
            summary1[
                "feature_oracle"
            ][
                "max_abs_delta"
            ],
        )

        print(
            "Feature drop           : "
            "NONE - canonical manuscript command"
        )

        print(
            "Random Forest          : "
            "160 trees - PASS"
        )

        print(
            "OOB enabled            : TRUE"
        )

        print(
            "max_features           : "
            "auto -> 10/tree - PASS"
        )

        print(
            "RF classes             :",
            summary1[
                "rf"
            ][
                "classes"
            ],
        )

        print(
            "Positive score         : "
            "P(class=1) - PASS"
        )

        print(
            "Source predict align   : PASS"
        )

        print(
            "Predict max |delta|    :",
            summary1[
                "source_predict_alignment"
            ][
                "max_abs_delta"
            ],
        )

        print(
            "Serialization reload   : PASS"
        )

        print(
            "Deterministic replay   : PASS"
        )

        print(
            "Replay max |delta|     :",
            deterministic_delta,
        )

        print(
            "-" * 128
        )

        print(
            "SYNTHETIC SELF-TEST"
        )

        print(
            "Train                  : "
            "128 (64 AMP / 64 non-AMP)"
        )

        print(
            "Validation             : "
            "32 (16 AMP / 16 non-AMP)"
        )

        print(
            "P(AMP) range           :",
            summary1[
                "score_semantics"
            ][
                "probability_min"
            ],
            "..",
            summary1[
                "score_semantics"
            ][
                "probability_max"
            ],
        )

        print(
            "-" * 128
        )

        print(
            "SCIENTIFIC SCOPE"
        )

        print(
            "Benchmark data used    : FALSE"
        )

        print(
            "Benchmark training     : FALSE"
        )

        print(
            "Benchmark test used    : FALSE"
        )

        print(
            "External target used   : FALSE"
        )

        print(
            "-" * 128
        )

        print(
            "Published validated    : "
            f"{len(validated)}/7"
        )

        print(
            "Validated methods      :",
            validated,
        )

        print(
            "TRAINING GATE          :",
            (
                "OPEN"
                if gate_after[
                    "open"
                ]
                else
                "CLOSED"
            ),
        )

        print(
            "-" * 128
        )

        print(
            "Source audit SHA256    :",
            sha256_file(
                SOURCE_AUDIT_PATH
            ),
        )

        print(
            "Environment SHA256     :",
            sha256_file(
                ENV_AUDIT_PATH
            ),
        )

        print(
            "Contract SHA256        :",
            sha256_file(
                ADAPTER_CONTRACT_PATH
            ),
        )

        print(
            "Self-test manifest     :",
            SELFTEST_MANIFEST_PATH,
        )

        print(
            "Manifest SHA256        :",
            sha256_file(
                SELFTEST_MANIFEST_PATH
            ),
        )

        print(
            "NEXT                   : "
            "CELL 29 - AI4AMP "
            "SOURCE + PC6 + "
            "FULL ADAPTER CLOSURE"
        )

        print(
            "=" * 128
        )


    finally:

        if staging_dir.exists():

            shutil.rmtree(
                staging_dir,
                ignore_errors=True,
            )

================================================================================================================================
CELL 28 PASS - amPEPpy v1.0 OFFICIAL-SOURCE FULL ADAPTER END-TO-END SELF-TEST PASSED
================================================================================================================================
Published method       : amPEPpy
Implementation status  : VALIDATED
Official tag           : v1.0
Official commit        : aa1f694c6cb3d09b16bc9378bed77f59e4f1e780
Source audit           : NEW SOURCE AUDIT ATOMICALLY COMMITTED
--------------------------------------------------------------------------------------------------------------------------------
PAPER / SOURCE ENVIRONMENT
Python                 : 3.8.3
scikit-learn           : 0.23.1
NumPy                  : 1.18.5
SciPy                  : 1.5.0
pandas                 : 1.0.5
Biopython              : 1.77
--------------------------------------------------------------------------------------------------------------------------------
SOURCE-NATIVE PIPELINE
CTD Distribution       : 105 features - PASS
Exact feature order    : PASS
A10 numeric oracle     : PASS
Oracle max |delta|     : 0.0
Feature drop           : NONE - canonical manuscript command
Random Forest          : 160 trees - PASS
OOB enabled            : TRUE
max_features           : auto -> 10/tree - PASS
RF classes             : [0, 1]
Positive score         : P(class=1) - PASS
Source predict align   : PASS
Predict max |delta|    : 0.0
Serialization reload   : PASS
Deterministic replay   : PASS
Replay max |delta|     : 0.0
--------------------------------------------------------------------------------------------------------------------------------
SYNTHETIC SELF-TEST
Train                  : 128 (64 AMP / 64 non-AMP)
Validation             : 32 (16 AMP / 16 non-AMP)
P(AMP) range           : 0.0 .. 1.0
--------------------------------------------------------------------------------------------------------------------------------
SCIENTIFIC SCOPE
Benchmark data used    : FALSE
Benchmark training     : FALSE
Benchmark test used    : FALSE
External target used   : FALSE
--------------------------------------------------------------------------------------------------------------------------------
Published validated    : 5/7
Validated methods      : ['ampep', 'ampeppy', 'ampgram', 'ampir', 'ampscannerv2']
TRAINING GATE          : CLOSED
--------------------------------------------------------------------------------------------------------------------------------
Source audit SHA256    : 8660a505b0c6e66a4b96f67d29039753901cffb122ba34350ce8576720733827
Environment SHA256     : b103b8d5f863b57d05f2e86983eecaeb1865b909c9cd758bd28a451934650756
Contract SHA256        : fa90bad6385dc97d8b282c7ad43299ec417bf3c7143e0266735dce0a4c5cb781
Self-test manifest     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ampeppy_FINAL_adapter_selftest.json
Manifest SHA256        : 32faf1720fe467fbd073527ea10b6f77da93e51f694f8af7553b465da72adec9
NEXT                   : CELL 29 - AI4AMP SOURCE + PC6 + FULL ADAPTER CLOSURE
================================================================================================================================

In [22]:
# ============================================================
# CELL 29 - AI4AMP
# Official PC6 + published CNN-LSTM-Dense + full synthetic self-test
# Restart-safe; no benchmark/test/external data.
# ============================================================

from pathlib import Path
from datetime import datetime
import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import urllib.request

import numpy as np
import pandas as pd


# ============================================================
# 1. PATHS / LOCKS
# ============================================================

ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUT = (
    ROOT
    / "benchmark17_outputs"
)

AUDIT = (
    OUT
    / "audit"
)

MAN = (
    OUT
    / "manifests"
)

WORK = Path(
    "/home/pc/genpept_benchmark17_work"
)

SRCROOT = Path(
    "/home/pc/genpept_sources"
)

METHOD = "ai4amp"

PIDS = [
    "ampep",
    "ampscannerv2",
    "ampgram",
    "ampir",
    "ampeppy",
    "ai4amp",
    "amplify",
]


ROUTE = (
    MAN
    / "benchmark17_FINAL_published_method_route_contract.json"
)

GATE = (
    MAN
    / "benchmark17_FINAL_training_gate.json"
)

READY = (
    AUDIT
    / "benchmark17_published_method_local_readiness_latest.csv"
)


UP = {

    "ampep":
        (
            MAN
            / "benchmark17_ampep_FINAL_adapter_selftest.json"
        ),

    "ampeppy":
        (
            MAN
            / "benchmark17_ampeppy_FINAL_adapter_selftest.json"
        ),

    "ampscannerv2":
        (
            MAN
            / "benchmark17_ampscannerv2_FINAL_adapter_selftest.json"
        ),

    "ampgram":
        (
            MAN
            / "benchmark17_ampgram_FINAL_adapter_selftest.json"
        ),

    "ampir":
        (
            MAN
            / "benchmark17_ampir_FINAL_adapter_selftest.json"
        ),
}


SRC_CONTRACT = (
    MAN
    / "benchmark17_ai4amp_FINAL_source_contract.json"
)

ENV_AUDIT = (
    MAN
    / "benchmark17_ai4amp_FINAL_environment.json"
)

IMPL_CONTRACT = (
    MAN
    / "benchmark17_ai4amp_FINAL_implementation_contract.json"
)

SELFTEST = (
    MAN
    / "benchmark17_ai4amp_FINAL_adapter_selftest.json"
)


SELFROOT = (
    WORK
    / "published_selftests"
    / METHOD
)

BUNDLE = (
    SELFROOT
    / "cell29_final_adapter_selftest"
)


PRED_REPO = (
    "LinTzuTang/AI4AMP_predictor"
)

PRED_COMMIT = (
    "04ea9fcb9956027f373d36b9ef621a41d778eaca"
)

PC6_REPO = (
    "LinTzuTang/PC6-protein-encoding-method"
)

PC6_COMMIT = (
    "15f9e9997d26f1dbb6863d9c19881b5cf49f0533"
)


PRED_DIR = (
    SRCROOT
    / (
        "AI4AMP_predictor_"
        + PRED_COMMIT
    )
)

PC6_DIR = (
    SRCROOT
    / (
        "PC6-protein-encoding-method_"
        + PC6_COMMIT
    )
)


ROUTE_SHA = (
    "dd7d6a743f088cef95fb49288dcf1801"
    "c9dc335be2656e627e7fc7f3bf7170bd"
)


UP_SHA = {

    "ampep":
        (
            "18786bf2b024c8dab4e1bf28fbd843265"
            "68bda559e56a9c20f5895091ca64f4e"
        ),

    "ampeppy":
        (
            "32faf1720fe467fbd073527ea10b6f77"
            "da93e51f694f8af7553b465da72adec9"
        ),

    "ampscannerv2":
        (
            "025c951b10807b789108d13baca066486"
            "cc2d2e127397c3b54ae44a666a1b96f"
        ),

    "ampgram":
        (
            "399d1d695e72f42ad591caf637de03b91"
            "0d07e09b1f1f5805054e629153aee3d"
        ),
}


PRED_FILES = {

    "README.md":
        "1d28b94ef03c789d11efb90d0fb42e8deebe7e43",

    "requirements.txt":
        "290fb359f8ca87a6d89ac081d43e2e05f3b88f9e",

    "PC6/6-pc":
        "9b2dcfdc462cd823f0e35d4170dd3bd6a06f8971",

    "PC6/PC6_encoding.py":
        "218b3b691a3fb2b815dbeab93674375651a319d4",

    "PC6/PC6_predictor.py":
        "58b72ab1f13f496bc08a70ac64312ec8e847737c",

    "code/Model/PC_6_model.py":
        "c8f117d922bd557bb98bc3262654d715c7b02ecd",

    "code/PC_6.ipynb":
        "22960e46f90c6e6c85094014ba126c163279d2b9",
}


PC6_FILES = {

    "6-pc":
        "9b2dcfdc462cd823f0e35d4170dd3bd6a06f8971",

    "Protein_Encoding.py":
        "4ca70ba5b45bda3084ae53e0c9d1e3da8b8d79ef",
}


for directory in [
    ROOT,
    OUT,
    AUDIT,
    MAN,
    WORK,
    SRCROOT,
]:

    assert directory.is_dir(), (
        f"Required directory missing: "
        f"{directory}"
    )


SELFROOT.mkdir(
    parents=True,
    exist_ok=True,
)

PRED_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

PC6_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


for path in [
    ROUTE,
    GATE,
    READY,
    *UP.values(),
]:

    assert path.is_file(), (
        f"Required upstream artifact missing: "
        f"{path}"
    )


# ============================================================
# 2. HELPERS
# ============================================================

def sha256(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda: f.read(
                1 << 20
            ),
            b"",
        ):

            h.update(
                chunk
            )

    return h.hexdigest()


def blob_bytes(data):

    return hashlib.sha1(
        (
            f"blob {len(data)}\0"
        ).encode(
            "utf-8"
        )
        +
        data
    ).hexdigest()


def blob_file(path):

    return blob_bytes(
        Path(
            path
        ).read_bytes()
    )


def jload(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as f:

        return json.load(
            f
        )


def jwrite(
    path,
    payload,
):

    path = Path(
        path
    )

    tmp = path.with_name(
        path.name
        +
        ".tmp"
    )

    with open(
        tmp,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            payload,
            f,
            indent=2,
            ensure_ascii=False,
        )

        f.flush()

        os.fsync(
            f.fileno()
        )

    os.replace(
        tmp,
        path,
    )


def cwrite(
    path,
    dataframe,
):

    path = Path(
        path
    )

    tmp = path.with_name(
        path.name
        +
        ".tmp"
    )

    dataframe.to_csv(
        tmp,
        index=False,
    )

    os.replace(
        tmp,
        path,
    )


def run(
    command,
    timeout=1800,
    env=None,
    check=True,
    label="subprocess",
):

    result = subprocess.run(
        [
            str(x)
            for x in command
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        env=env,
        timeout=timeout,
    )

    if (
        check
        and
        result.returncode != 0
    ):

        print(
            "=" * 128
        )

        print(
            "SUBPROCESS FAILURE -",
            label,
        )

        print(
            "COMMAND:",
            [
                str(x)
                for x in command
            ],
        )

        print(
            "RETURN CODE:",
            result.returncode,
        )

        print(
            "--- STDOUT ---"
        )

        print(
            result.stdout
        )

        print(
            "--- STDERR ---"
        )

        print(
            result.stderr
        )

        print(
            "=" * 128
        )

        raise AssertionError(
            f"{label} failed "
            f"with return code "
            f"{result.returncode}"
        )

    return result


def boolish(value):

    if isinstance(
        value,
        (
            bool,
            np.bool_,
        ),
    ):

        return bool(
            value
        )

    value = (
        str(value)
        .strip()
        .lower()
    )

    if value in {
        "true",
        "1",
        "yes",
    }:

        return True

    if value in {
        "false",
        "0",
        "no",
    }:

        return False

    raise AssertionError(
        f"Cannot interpret as bool: "
        f"{value!r}"
    )


def art(path):

    path = Path(
        path
    )

    assert path.is_file()

    return {

        "path":
            str(
                path
            ),

        "size_bytes":
            int(
                path.stat().st_size
            ),

        "sha256":
            sha256(
                path
            ),
    }


def check_art(
    entry,
):

    path = Path(
        entry[
            "path"
        ]
    )

    assert path.is_file()

    assert (
        int(
            path.stat().st_size
        )
        ==
        int(
            entry[
                "size_bytes"
            ]
        )
    )

    assert (
        sha256(
            path
        )
        ==
        entry[
            "sha256"
        ]
    )


# ============================================================
# 3. UPSTREAM VERIFICATION
# ============================================================

assert (
    sha256(
        ROUTE
    )
    ==
    ROUTE_SHA
)


for model_id, path in (
    UP.items()
):

    if (
        model_id
        in UP_SHA
    ):

        assert (
            sha256(
                path
            )
            ==
            UP_SHA[
                model_id
            ]
        )


    payload = jload(
        path
    )


    assert (
        payload[
            "implementation_validated"
        ]
        is True
    )


    assert (
        payload[
            "benchmark_training_performed"
        ]
        is False
    )


    assert (
        payload[
            "benchmark_test_used"
        ]
        is False
    )


    observed = (

        payload.get(
            "model_id"
        )

        or

        payload.get(
            "adapter_contract",
            {},
        ).get(
            "model_id"
        )
    )


    assert (
        observed
        ==
        model_id
    )


route_payload = jload(
    ROUTE
)


assert (
    route_payload[
        "status"
    ]
    ==
    "PUBLISHED_METHOD_ROUTES_LOCKED_BEFORE_TRAINING"
)


assert (
    route_payload[
        "restart_safe"
    ]
    is True
)


route_core = (
    route_payload[
        "contract"
    ]
)


assert (
    route_core[
        "published_model_ids"
    ]
    ==
    PIDS
)


route = (
    route_core[
        "methods"
    ][
        METHOD
    ]
)


assert (
    route[
        "paper_doi"
    ]
    ==
    "10.1128/mSystems.00299-21"
)


assert (
    route[
        "published_representation"
    ]
    ==
    "PC6_encoding"
)


assert (
    route[
        "published_architecture"
    ]
    ==
    "PC6_CNN_LSTM_Dense"
)


assert (
    route[
        "locked_route"
    ]
    ==
    (
        "faithful_reimplementation_"
        "using_official_PC6_and_"
        "published_architecture"
    )
)


assert (
    route[
        "implementation_environment"
    ]
    ==
    "dedicated_python_environment"
)


assert (
    route[
        "PC6_encoding_must_be_preserved"
    ]
    is True
)


assert (
    route[
        "architecture_change_allowed"
    ]
    is False
)


assert (
    route[
        "ten_independent_retraining_runs"
    ]
    is True
)


assert (
    route[
        "pretrained_repeated_inference_allowed"
    ]
    is False
)


gate_before = jload(
    GATE
)


assert (
    gate_before[
        "open"
    ]
    is False
)


assert (
    gate_before[
        "benchmark_training_allowed"
    ]
    is False
)


if not SELFTEST.is_file():

    assert (
        gate_before[
            "published_methods_implementation_validated"
        ]
        ==
        5
    )

    assert sorted(
        gate_before[
            "validated_methods"
        ]
    ) == [
        "ampep",
        "ampeppy",
        "ampgram",
        "ampir",
        "ampscannerv2",
    ]


# ============================================================
# 4. OFFICIAL SOURCE PINNING
# ============================================================

def acquire(
    repo,
    commit,
    root,
    relpath,
    expected_blob,
):

    destination = (
        root
        / relpath
    )

    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    if (
        destination.is_file()
        and
        blob_file(
            destination
        )
        ==
        expected_blob
    ):

        return (
            "REUSED"
        )


    url = (
        "https://raw.githubusercontent.com/"
        f"{repo}/"
        f"{commit}/"
        f"{relpath}"
    )


    request = urllib.request.Request(
        url,
        headers={
            "User-Agent":
                "GenPept-AI4AMP/1.0"
        },
    )


    try:

        with urllib.request.urlopen(
            request,
            timeout=120,
        ) as response:

            data = (
                response.read()
            )

    except Exception as exc:

        raise AssertionError(
            f"Cannot download {url}: "
            f"{type(exc).__name__}: "
            f"{exc}"
        )


    assert (
        blob_bytes(
            data
        )
        ==
        expected_blob
    ), (
        relpath,
        blob_bytes(
            data
        ),
        expected_blob,
    )


    tmp = (
        destination.with_name(
            destination.name
            +
            ".tmp"
        )
    )


    tmp.write_bytes(
        data
    )


    os.replace(
        tmp,
        destination,
    )


    assert (
        blob_file(
            destination
        )
        ==
        expected_blob
    )


    return (
        "DOWNLOADED"
    )


for relpath, digest in (
    PRED_FILES.items()
):

    acquire(
        PRED_REPO,
        PRED_COMMIT,
        PRED_DIR,
        relpath,
        digest,
    )


for relpath, digest in (
    PC6_FILES.items()
):

    acquire(
        PC6_REPO,
        PC6_COMMIT,
        PC6_DIR,
        relpath,
        digest,
    )


for relpath, digest in (
    PRED_FILES.items()
):

    assert (
        blob_file(
            PRED_DIR
            / relpath
        )
        ==
        digest
    )


for relpath, digest in (
    PC6_FILES.items()
):

    assert (
        blob_file(
            PC6_DIR
            / relpath
        )
        ==
        digest
    )


assert (
    (
        PRED_DIR
        / "PC6/6-pc"
    ).read_bytes()
    ==
    (
        PC6_DIR
        / "6-pc"
    ).read_bytes()
)


readme = (
    PRED_DIR
    / "README.md"
).read_text(
    encoding="utf-8"
)


requirements_text = (
    PRED_DIR
    / "requirements.txt"
).read_text(
    encoding="utf-8"
)


encoder_source = (
    PRED_DIR
    / "PC6/PC6_encoding.py"
).read_text(
    encoding="utf-8"
)


predictor_source = (
    PRED_DIR
    / "PC6/PC6_predictor.py"
).read_text(
    encoding="utf-8"
)


model_source = (
    PRED_DIR
    / "code/Model/PC_6_model.py"
).read_text(
    encoding="utf-8"
)


notebook_source = (
    PRED_DIR
    / "code/PC_6.ipynb"
).read_text(
    encoding="utf-8"
)


pc6_source = (
    PC6_DIR
    / "Protein_Encoding.py"
).read_text(
    encoding="utf-8"
)


assert (
    "one convolution layer, "
    "one long short-term memory (LSTM) layer, "
    "and one dense layer"
    in readme
)


for item in [

    "Keras==2.2.4",
    "tensorflow-gpu==1.9.0",
    "numpy==1.18.2",
    "scipy==1.4.1",
    "pandas==0.23.4",
    "biopython==1.73",
    "h5py==2.10.0",

]:

    assert (
        item
        in requirements_text
    )


assert (
    '"version": "3.6.9"'
    in notebook_source
)


for item in [

    "length=200",
    "pad_value='X'",
    "table['X'] = [0,0,0,0,0,0]",
    "ddof=1",

]:

    assert (
        item
        in encoder_source
    )


for item in [

    "H1",
    "V",
    "P1",
    "Pl",
    "PKa",
    "NCI",
    "def PC_6(fasta_name, length=200)",

]:

    assert (
        item
        in pc6_source
    )


assert re.search(
    r"Input\(shape=\(200,6\)\)",
    model_source,
)


assert re.search(
    (
        r"Conv1D\(64\s*,16,"
        r"activation\s*=\s*['\"]relu['\"],"
        r"\s*padding=['\"]same['\"]\)"
    ),
    model_source,
)


assert re.search(
    r"LSTM\(units=100,return_sequences=False\)",
    model_source,
)


assert re.search(
    r"Dense\(1,\s*activation\s*=\s*['\"]sigmoid['\"]\)",
    model_source,
)


assert (
    "score = model.predict(data)"
    in predictor_source
)


assert (
    "classifier = score>0.5"
    in predictor_source
)


assert (
    "optimizers.Adam(lr=1e-4)"
    in model_source
)


assert (
    "epochs=500"
    in model_source
)


assert (
    "patience=80"
    in model_source
)


assert (
    "callbacks=[saveBestModel,CSVLogger]"
    in model_source
)


SOURCE_CORE = {

    "schema_version":
        "1.0",

    "model_id":
        METHOD,

    "paper_doi":
        "10.1128/mSystems.00299-21",

    "predictor_repository":
        PRED_REPO,

    "predictor_commit":
        PRED_COMMIT,

    "pc6_repository":
        PC6_REPO,

    "pc6_commit":
        PC6_COMMIT,

    "predictor_files": {

        relpath: {

            "git_blob_sha1":
                digest,

            "sha256":
                sha256(
                    PRED_DIR
                    / relpath
                ),
        }

        for relpath, digest
        in PRED_FILES.items()
    },

    "pc6_files": {

        relpath: {

            "git_blob_sha1":
                digest,

            "sha256":
                sha256(
                    PC6_DIR
                    / relpath
                ),
        }

        for relpath, digest
        in PC6_FILES.items()
    },

    "pc6": {

        "shape":
            [
                200,
                6,
            ],

        "properties":
            [
                "H1",
                "V",
                "P1",
                "Pl",
                "PKa",
                "NCI",
            ],

        "normalization":
            "zscore_ddof_1",

        "padding_token":
            "X",

        "padding_vector":
            [
                0.0
            ]
            * 6,
    },

    "architecture": {

        "input_shape":
            [
                200,
                6,
            ],

        "conv_filters":
            64,

        "conv_kernel":
            16,

        "conv_activation":
            "relu",

        "conv_padding":
            "same",

        "pooling":
            False,

        "lstm_units":
            100,

        "dense_units":
            1,

        "dense_activation":
            "sigmoid",

        "loss":
            "binary_crossentropy",
    },

    "paper_training": {

        "optimizer":
            "Adam",

        "learning_rate":
            0.0003,

        "epoch_cap":
            200,

        "batch_size":
            "half_training_set",

        "early_stopping_reported":
            True,

        "patience_reported":
            False,

        "resolution":
            (
                "200_epoch_cap_plus_"
                "best_validation_loss_checkpoint"
            ),
    },

    "source_scaffold": {

        "learning_rate":
            0.0001,

        "epochs":
            500,

        "declared_patience":
            80,

        "declared_early_stopping_used_in_fit":
            False,
    },

    "score": {

        "threshold":
            0.5,

        "positive_rule":
            "score > 0.5",
    },
}


if SRC_CONTRACT.is_file():

    existing_source_contract = jload(
        SRC_CONTRACT
    )


    assert (
        existing_source_contract[
            "status"
        ]
        ==
        "AI4AMP_SOURCE_AND_PUBLICATION_CONTRACT_LOCKED"
    )


    assert (
        existing_source_contract[
            "contract"
        ]
        ==
        SOURCE_CORE
    )


    SOURCE_ACTION = (
        "EXISTING SOURCE CONTRACT VERIFIED"
    )

else:

    jwrite(
        SRC_CONTRACT,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AI4AMP_SOURCE_AND_PUBLICATION_CONTRACT_LOCKED",

            "contract":
                SOURCE_CORE,
        },
    )


    SOURCE_ACTION = (
        "NEW SOURCE CONTRACT COMMITTED"
    )


# ============================================================
# 5. DEDICATED LEGACY ENVIRONMENT - CORRECTED
# ============================================================

def locate_conda():

    candidates = []


    if os.environ.get(
        "CONDA_EXE"
    ):

        candidates.append(
            Path(
                os.environ[
                    "CONDA_EXE"
                ]
            )
        )


    candidates.extend(
        [
            (
                Path.home()
                / "miniconda3/bin/conda"
            ),

            (
                Path.home()
                / "anaconda3/bin/conda"
            ),
        ]
    )


    found = shutil.which(
        "conda"
    )


    if found:

        candidates.append(
            Path(
                found
            )
        )


    for path in candidates:

        if (
            path.is_file()
            and
            os.access(
                path,
                os.X_OK,
            )
        ):

            return (
                path.resolve()
            )


    raise AssertionError(
        "conda not found"
    )


CONDA = locate_conda()


PREFIX = (
    CONDA
    .parent
    .parent
    / "envs/genpept_ai4amp_legacy"
)


PY = (
    PREFIX
    / "bin/python"
)


PROBE_CODE = r'''
import json
import os
import sys

os.environ["KERAS_BACKEND"] = "tensorflow"
os.environ["CUDA_VISIBLE_DEVICES"] = ""

payload = {
    "python":
        ".".join(
            str(x)
            for x
            in sys.version_info[:3]
        )
}

for key, module_name in [

    ("numpy", "numpy"),
    ("scipy", "scipy"),
    ("pandas", "pandas"),
    ("biopython", "Bio"),
    ("tensorflow", "tensorflow"),
    ("keras", "keras"),
    ("h5py", "h5py"),

]:

    try:

        module = __import__(
            module_name,
            fromlist=["*"],
        )

        payload[key] = (
            module.__version__
        )

        payload[
            key + "_path"
        ] = (
            module.__file__
        )

    except Exception as exc:

        payload[
            key + "_error"
        ] = (
            type(exc).__name__
            + ": "
            + str(exc)
        )


try:

    import keras.backend as K

    payload[
        "keras_backend"
    ] = (
        K.backend()
    )

except Exception as exc:

    payload[
        "keras_backend_error"
    ] = (
        type(exc).__name__
        + ": "
        + str(exc)
    )


try:

    import pkg_resources

    for key, dist_name in [

        (
            "tensorboard_dist",
            "tensorboard",
        ),

        (
            "keras_applications_dist",
            "Keras-Applications",
        ),

        (
            "keras_preprocessing_dist",
            "Keras-Preprocessing",
        ),

        (
            "pyyaml_dist",
            "PyYAML",
        ),

        (
            "six_dist",
            "six",
        ),

        (
            "protobuf_dist",
            "protobuf",
        ),

        (
            "grpcio_dist",
            "grpcio",
        ),

        (
            "absl_py_dist",
            "absl-py",
        ),

        (
            "astor_dist",
            "astor",
        ),

        (
            "gast_dist",
            "gast",
        ),

        (
            "markdown_dist",
            "Markdown",
        ),

        (
            "werkzeug_dist",
            "Werkzeug",
        ),

        (
            "setuptools_dist",
            "setuptools",
        ),

        (
            "wheel_dist",
            "wheel",
        ),
    ]:

        payload[
            key
        ] = (
            pkg_resources
            .get_distribution(
                dist_name
            )
            .version
        )

except Exception as exc:

    payload[
        "distribution_probe_error"
    ] = (
        type(exc).__name__
        + ": "
        + str(exc)
    )


print(
    "AI4AMP29_PROBE="
    +
    json.dumps(
        payload,
        sort_keys=True,
    )
)
'''


def probe_environment():

    if not PY.is_file():

        return (
            None,
            None,
        )


    env = (
        os.environ.copy()
    )


    env.update(
        {
            "KERAS_BACKEND":
                "tensorflow",

            "CUDA_VISIBLE_DEVICES":
                "",

            "TF_CPP_MIN_LOG_LEVEL":
                "2",
        }
    )


    result = run(
        [
            PY,
            "-c",
            PROBE_CODE,
        ],
        timeout=300,
        env=env,
        check=False,
        label=(
            "AI4AMP env probe"
        ),
    )


    payload = None


    for line in (
        result.stdout
        .splitlines()
    ):

        if line.startswith(
            "AI4AMP29_PROBE="
        ):

            payload = json.loads(
                line.split(
                    "=",
                    1,
                )[1]
            )

            break


    return (
        payload,
        result,
    )


def python_369():

    if not PY.is_file():

        return False


    result = run(
        [
            PY,
            "-c",
            (
                "import sys;"
                "print('%d.%d.%d'"
                "%sys.version_info[:3])"
            ),
        ],
        timeout=60,
        check=False,
        label=(
            "AI4AMP Python probe"
        ),
    )


    return (
        result.returncode == 0
        and
        result.stdout.strip()
        ==
        "3.6.9"
    )


EXPECTED_ENV = {

    "python":
        "3.6.9",

    "numpy":
        "1.18.2",

    "scipy":
        "1.4.1",

    "pandas":
        "0.23.4",

    "biopython":
        "1.73",

    "tensorflow":
        "1.9.0",

    "keras":
        "2.2.4",

    "h5py":
        "2.10.0",

    "keras_backend":
        "tensorflow",

    "tensorboard_dist":
        "1.9.0",

    "keras_applications_dist":
        "1.0.8",

    "keras_preprocessing_dist":
        "1.1.0",

    "pyyaml_dist":
        "3.13",

    "six_dist":
        "1.14.0",

    "protobuf_dist":
        "3.11.3",

    "grpcio_dist":
        "1.28.1",

    "absl_py_dist":
        "0.9.0",

    "astor_dist":
        "0.8.1",

    "gast_dist":
        "0.2.2",

    "markdown_dist":
        "3.2.1",

    "werkzeug_dist":
        "1.0.1",

    "setuptools_dist":
        "39.1.0",

    "wheel_dist":
        "0.37.1",
}


def env_ok(
    payload,
):

    if not payload:

        return False


    return all(

        str(
            payload.get(
                key,
                "",
            )
        )
        ==
        expected

        for key, expected
        in EXPECTED_ENV.items()
    )


initial_probe, _ = (
    probe_environment()
)


if not env_ok(
    initial_probe
):

    # --------------------------------------------------------
    # Recreate only if Python itself is wrong/missing.
    # Current failed environment has Python 3.6.9, so normally
    # this branch simply repairs packages in-place.
    # --------------------------------------------------------

    if (
        PREFIX.exists()
        and
        not python_369()
    ):

        removal = run(
            [
                CONDA,
                "remove",
                "-y",
                "-p",
                PREFIX,
                "--all",
            ],
            timeout=1800,
            check=False,
            label=(
                "remove invalid "
                "AI4AMP environment"
            ),
        )


        if (
            removal.returncode != 0
            and
            PREFIX.exists()
        ):

            shutil.rmtree(
                PREFIX
            )


    if not PY.is_file():

        attempts = [

            [
                CONDA,
                "create",
                "-y",
                "-p",
                PREFIX,
                "-c",
                "defaults",
                "python=3.6.9",
                "pip",
            ],

            [
                CONDA,
                "create",
                "-y",
                "-p",
                PREFIX,
                "-c",
                "conda-forge",
                "python=3.6.9",
                "pip",
            ],
        ]


        created = False

        failures = []


        for index, command in enumerate(
            attempts,
            start=1,
        ):

            result = run(
                command,
                timeout=3600,
                check=False,
                label=(
                    "create AI4AMP "
                    "Python 3.6.9 "
                    f"attempt {index}"
                ),
            )


            if (
                PY.is_file()
                and
                python_369()
            ):

                created = True

                break


            failures.append(
                (
                    index,
                    result.returncode,
                    result.stdout[
                        -8000:
                    ],
                    result.stderr[
                        -8000:
                    ],
                )
            )


        if not created:

            print(
                "=" * 128
            )

            print(
                "AI4AMP PYTHON 3.6.9 "
                "CREATION FAILED"
            )


            for failure in failures:

                print(
                    "ATTEMPT",
                    failure[
                        0
                    ],
                    "RC",
                    failure[
                        1
                    ],
                )

                print(
                    failure[
                        2
                    ]
                )

                print(
                    failure[
                        3
                    ]
                )


            print(
                "=" * 128
            )


            raise AssertionError(
                "Could not create "
                "AI4AMP Python 3.6.9 "
                "environment"
            )


    assert (
        python_369()
    )


    # --------------------------------------------------------
    # Packaging layer.
    #
    # TensorFlow 1.9.0 requires setuptools <= 39.1.0.
    # --------------------------------------------------------

    run(
        [
            PY,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--force-reinstall",

            "pip==21.3.1",
            "setuptools==39.1.0",
            "wheel==0.37.1",
        ],
        timeout=1800,
        label=(
            "AI4AMP packaging toolchain"
        ),
    )


    # --------------------------------------------------------
    # Exact binary scientific stack from pinned AI4AMP source.
    #
    # --no-deps is CRITICAL:
    # pip must NOT upgrade NumPy/SciPy/h5py again.
    # --------------------------------------------------------

    run(
        [
            PY,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--force-reinstall",
            "--no-deps",
            "--only-binary=:all:",

            "numpy==1.18.2",
            "scipy==1.4.1",
            "pandas==0.23.4",
            "biopython==1.73",
            "h5py==2.10.0",
        ],
        timeout=5400,
        label=(
            "AI4AMP exact "
            "scientific stack"
        ),
    )


    # --------------------------------------------------------
    # Exact Keras stack.
    #
    # Again --no-deps:
    # Keras 2.2.4 otherwise has unbounded h5py dependency.
    # --------------------------------------------------------

    run(
        [
            PY,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--force-reinstall",
            "--no-deps",

            "Keras==2.2.4",
            "Keras-Applications==1.0.8",
            "Keras-Preprocessing==1.1.0",
            "PyYAML==3.13",
            "six==1.14.0",
        ],
        timeout=3600,
        label=(
            "AI4AMP exact "
            "Keras stack"
        ),
    )


    # --------------------------------------------------------
    # Exact TensorFlow 1.9 runtime.
    #
    # The official freeze contains tensorflow-gpu==1.9.0.
    # We use the CPU wheel of the SAME TensorFlow 1.9.0
    # framework for the adapter self-test.
    #
    # Every dependency is explicit; resolver cannot drift.
    # --------------------------------------------------------

    run(
        [
            PY,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--force-reinstall",
            "--no-deps",

            "tensorflow==1.9.0",
            "tensorboard==1.9.0",
            "protobuf==3.11.3",
            "grpcio==1.28.1",
            "absl-py==0.9.0",
            "astor==0.8.1",
            "gast==0.2.2",
            "termcolor==1.1.0",
            "Markdown==3.2.1",
            "Werkzeug==1.0.1",
            "bleach==1.5.0",
            "html5lib==0.9999999",
            "python-dateutil==2.7.5",
            "pytz==2018.9",
        ],
        timeout=5400,
        label=(
            "AI4AMP exact "
            "TensorFlow 1.9 runtime"
        ),
    )


    # --------------------------------------------------------
    # Dependency closure must be clean.
    # --------------------------------------------------------

    pip_check = run(
        [
            PY,
            "-m",
            "pip",
            "check",
        ],
        timeout=300,
        check=False,
        label=(
            "AI4AMP pip check"
        ),
    )


    if (
        pip_check.returncode
        != 0
    ):

        print(
            "=" * 128
        )

        print(
            "AI4AMP PIP CHECK FAILED"
        )

        print(
            pip_check.stdout
        )

        print(
            pip_check.stderr
        )

        print(
            "=" * 128
        )


        raise AssertionError(
            "AI4AMP exact legacy "
            "environment dependency "
            "check failed"
        )


# ============================================================
# 6. FINAL ENVIRONMENT GATE
# ============================================================

FINAL_PROBE, FINAL_RESULT = (
    probe_environment()
)


if not env_ok(
    FINAL_PROBE
):

    print(
        "=" * 128
    )

    print(
        "AI4AMP FINAL ENVIRONMENT "
        "PROBE FAILED"
    )

    print(
        json.dumps(
            FINAL_PROBE,
            indent=2,
            sort_keys=True,
        )
        if FINAL_PROBE
        else
        "NO PROBE JSON"
    )


    if (
        FINAL_RESULT
        is not None
    ):

        print(
            "--- STDOUT ---"
        )

        print(
            FINAL_RESULT.stdout
        )

        print(
            "--- STDERR ---"
        )

        print(
            FINAL_RESULT.stderr
        )


    print(
        "=" * 128
    )


    raise AssertionError(
        "AI4AMP environment is "
        "not exact after reconciliation"
    )


final_check = run(
    [
        PY,
        "-m",
        "pip",
        "check",
    ],
    timeout=300,
    check=False,
    label=(
        "AI4AMP final pip check"
    ),
)


if (
    final_check.returncode
    != 0
):

    print(
        final_check.stdout
    )

    print(
        final_check.stderr
    )

    raise AssertionError(
        "AI4AMP final pip check failed"
    )


environment_root = str(
    PREFIX.resolve()
)


for key in [

    "numpy_path",
    "scipy_path",
    "pandas_path",
    "biopython_path",
    "tensorflow_path",
    "keras_path",
    "h5py_path",

]:

    assert (
        str(
            FINAL_PROBE[
                key
            ]
        ).startswith(
            environment_root
        )
    ), (
        key,
        FINAL_PROBE[
            key
        ],
    )


ENV_CORE = {

    "schema_version":
        "1.1",

    "model_id":
        METHOD,

    "environment_prefix":
        str(
            PREFIX
        ),

    "python_executable":
        str(
            PY
        ),

    "observed":
        FINAL_PROBE,

    "source_notebook_python":
        "3.6.9",

    "runtime_python_rule":
        "3.6.9",

    "source_tf_gpu":
        "1.9.0",

    "runtime_tf_cpu":
        "1.9.0",

    "framework_version_changed":
        False,

    "resolver_policy":
        (
            "all legacy package versions "
            "explicitly pinned; framework "
            "installs use --no-deps"
        ),

    "pip_check":
        "PASS",
}


if ENV_AUDIT.is_file():

    existing_environment = jload(
        ENV_AUDIT
    )


    assert (
        existing_environment[
            "status"
        ]
        ==
        "AI4AMP_DEDICATED_ENVIRONMENT_READY"
    )


    assert (
        existing_environment[
            "audit"
        ]
        ==
        ENV_CORE
    )

else:

    jwrite(
        ENV_AUDIT,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AI4AMP_DEDICATED_ENVIRONMENT_READY",

            "audit":
                ENV_CORE,
        },
    )


# ============================================================
# 7. IMPLEMENTATION CONTRACT
# ============================================================

CONTRACT = {

    "schema_version":
        "1.0",

    "model_id":
        METHOD,

    "paper_doi":
        "10.1128/mSystems.00299-21",

    "route":
        (
            "faithful_reimplementation_"
            "using_official_PC6_and_"
            "published_architecture"
        ),

    "predictor_commit":
        PRED_COMMIT,

    "pc6_commit":
        PC6_COMMIT,

    "pc6":
        SOURCE_CORE[
            "pc6"
        ],

    "architecture":
        SOURCE_CORE[
            "architecture"
        ],

    "training":
        SOURCE_CORE[
            "paper_training"
        ],

    "seeds":
        list(
            range(
                100,
                110,
            )
        ),

    "score":
        SOURCE_CORE[
            "score"
        ],

    "test_based_selection":
        False,

    "selftest": {

        "synthetic_only":
            True,

        "benchmark_training":
            False,

        "benchmark_test":
            False,

        "external":
            False,
    },
}


if IMPL_CONTRACT.is_file():

    existing_contract = jload(
        IMPL_CONTRACT
    )


    assert (
        existing_contract[
            "status"
        ]
        ==
        "AI4AMP_IMPLEMENTATION_CONTRACT_LOCKED"
    )


    assert (
        existing_contract[
            "contract"
        ]
        ==
        CONTRACT
    )

else:

    jwrite(
        IMPL_CONTRACT,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AI4AMP_IMPLEMENTATION_CONTRACT_LOCKED",

            "implementation_validated":
                False,

            "benchmark_training_performed":
                False,

            "benchmark_test_used":
                False,

            "external_target_used":
                False,

            "contract":
                CONTRACT,
        },
    )


# ============================================================
# 8. GATE HELPERS
# ============================================================

def valid_methods():

    result = []


    for model_id in PIDS:

        path = (
            MAN
            / (
                f"benchmark17_{model_id}_"
                f"FINAL_adapter_selftest.json"
            )
        )


        if (
            path.is_file()
            and
            jload(
                path
            ).get(
                "implementation_validated"
            )
            is True
        ):

            result.append(
                model_id
            )


    return sorted(
        result
    )


def update_gate():

    readiness = pd.read_csv(
        READY,
        low_memory=False,
    )


    mask = (
        readiness[
            "model_id"
        ]
        .astype(str)
        ==
        METHOD
    )


    assert (
        int(
            mask.sum()
        )
        ==
        1
    )


    readiness.loc[
        mask,
        "adapter_self_test_passed",
    ] = True


    readiness.loc[
        mask,
        "implementation_validated",
    ] = True


    readiness.loc[
        mask,
        "local_state",
    ] = (
        "IMPLEMENTATION_VALIDATED"
    )


    validated = (
        valid_methods()
    )


    for required in [

        "ampep",
        "ampeppy",
        "ampscannerv2",
        "ampgram",
        "ampir",
        "ai4amp",

    ]:

        assert (
            required
            in validated
        )


    gate = jload(
        GATE
    )


    gate[
        "published_methods_implementation_validated"
    ] = len(
        validated
    )


    gate[
        "validated_methods"
    ] = validated


    gate[
        "updated_at"
    ] = (
        datetime.now()
        .astimezone()
        .isoformat()
    )


    if (
        len(
            validated
        )
        ==
        7
    ):

        gate[
            "open"
        ] = True

        gate[
            "benchmark_training_allowed"
        ] = True

        gate[
            "reason"
        ] = (
            "All seven published-method "
            "implementations validated."
        )

        readiness.loc[
            :,
            "training_allowed",
        ] = True

    else:

        gate[
            "open"
        ] = False

        gate[
            "benchmark_training_allowed"
        ] = False

        gate[
            "reason"
        ] = (
            f"{len(validated)}/7 "
            "published-method "
            "implementations validated."
        )

        readiness.loc[
            mask,
            "training_allowed",
        ] = False


    cwrite(
        READY,
        readiness,
    )


    jwrite(
        GATE,
        gate,
    )


    readiness_check = pd.read_csv(
        READY,
        low_memory=False,
    )


    mask_check = (
        readiness_check[
            "model_id"
        ]
        .astype(str)
        ==
        METHOD
    )


    gate_check = jload(
        GATE
    )


    assert (
        boolish(
            readiness_check.loc[
                mask_check,
                "adapter_self_test_passed",
            ].iloc[
                0
            ]
        )
        is True
    )


    assert (
        boolish(
            readiness_check.loc[
                mask_check,
                "implementation_validated",
            ].iloc[
                0
            ]
        )
        is True
    )


    assert (
        gate_check[
            "validated_methods"
        ]
        ==
        validated
    )


    assert (
        gate_check[
            "published_methods_implementation_validated"
        ]
        ==
        len(
            validated
        )
    )


    return (
        validated,
        gate_check,
    )


def validate_self(
    payload,
):

    assert (
        payload[
            "status"
        ]
        ==
        "IMPLEMENTATION_VALIDATED"
    )


    assert (
        payload[
            "model_id"
        ]
        ==
        METHOD
    )


    assert (
        payload[
            "implementation_validated"
        ]
        is True
    )


    assert (
        payload[
            "synthetic_selftest_only"
        ]
        is True
    )


    assert (
        payload[
            "benchmark_training_performed"
        ]
        is False
    )


    assert (
        payload[
            "benchmark_test_used"
        ]
        is False
    )


    assert (
        payload[
            "external_target_used"
        ]
        is False
    )


    assert (
        payload[
            "source_contract_sha256"
        ]
        ==
        sha256(
            SRC_CONTRACT
        )
    )


    assert (
        payload[
            "environment_audit_sha256"
        ]
        ==
        sha256(
            ENV_AUDIT
        )
    )


    assert (
        payload[
            "adapter_contract_sha256"
        ]
        ==
        sha256(
            IMPL_CONTRACT
        )
    )


    selftest = (
        payload[
            "selftest"
        ]
    )


    assert (
        selftest[
            "pc6"
        ][
            "shape"
        ]
        ==
        [
            200,
            6,
        ]
    )


    assert (
        selftest[
            "pc6"
        ][
            "oracle_pass"
        ]
        is True
    )


    assert (
        selftest[
            "pc6"
        ][
            "oracle_delta"
        ]
        <=
        1e-12
    )


    assert (
        selftest[
            "architecture"
        ][
            "layers"
        ]
        ==
        [
            "InputLayer",
            "Conv1D",
            "LSTM",
            "Dense",
        ]
    )


    assert (
        selftest[
            "architecture"
        ][
            "conv_filters"
        ]
        ==
        64
    )


    assert (
        selftest[
            "architecture"
        ][
            "conv_kernel"
        ]
        ==
        16
    )


    assert (
        selftest[
            "architecture"
        ][
            "lstm_units"
        ]
        ==
        100
    )


    assert (
        selftest[
            "architecture"
        ][
            "dense_units"
        ]
        ==
        1
    )


    assert (
        abs(
            selftest[
                "training"
            ][
                "learning_rate"
            ]
            -
            0.0003
        )
        <=
        1e-10
    )


    assert (
        selftest[
            "training"
        ][
            "epochs"
        ]
        ==
        200
    )


    assert (
        selftest[
            "score"
        ][
            "threshold"
        ]
        ==
        0.5
    )


    assert (
        selftest[
            "serialization"
        ][
            "pass"
        ]
        is True
    )


    assert (
        selftest[
            "determinism"
        ][
            "pass"
        ]
        is True
    )


    for entry in (
        payload[
            "artifacts"
        ].values()
    ):

        check_art(
            entry
        )


# ============================================================
# 9. REUSE PASS OR RUN FULL SELF-TEST
# ============================================================

if SELFTEST.is_file():

    validate_self(
        jload(
            SELFTEST
        )
    )


    validated, gate_check = (
        update_gate()
    )


    print(
        "=" * 128
    )

    print(
        "CELL 29 PASS - "
        "AI4AMP FULL ADAPTER "
        "SELF-TEST REUSED AND VERIFIED"
    )

    print(
        "Published validated    :",
        f"{len(validated)}/7",
    )

    print(
        "Validated methods      :",
        validated,
    )

    print(
        "TRAINING GATE          :",
        (
            "OPEN"
            if gate_check[
                "open"
            ]
            else
            "CLOSED"
        ),
    )

    print(
        "Manifest SHA256        :",
        sha256(
            SELFTEST
        ),
    )

    print(
        "NEXT                   : "
        "CELL 30 - AMPlify"
    )

    print(
        "=" * 128
    )


else:

    if BUNDLE.exists():

        orphan = (
            SELFROOT
            / (
                "cell29_orphaned_"
                +
                datetime.now()
                .strftime(
                    "%Y%m%d_%H%M%S"
                )
            )
        )

        os.replace(
            BUNDLE,
            orphan,
        )


    rng = np.random.RandomState(
        290029
    )


    AMP_ALPHA = np.array(
        list(
            "KRWFLIV"
        )
    )


    DEC_ALPHA = np.array(
        list(
            "DENQGSTAP"
        )
    )


    def synth(
        alphabet,
        length,
    ):

        sequence = "".join(
            rng.choice(
                alphabet,
                size=length,
            ).tolist()
        )


        assert (
            10
            <= len(
                sequence
            )
            <= 200
        )


        return (
            sequence
        )


    train_amp = [

        synth(
            AMP_ALPHA,
            24
            +
            i % 15,
        )

        for i in range(
            12
        )
    ]


    train_dec = [

        synth(
            DEC_ALPHA,
            24
            +
            i % 15,
        )

        for i in range(
            12
        )
    ]


    val_amp = [

        synth(
            AMP_ALPHA,
            28
            +
            i % 9,
        )

        for i in range(
            6
        )
    ]


    val_dec = [

        synth(
            DEC_ALPHA,
            28
            +
            i % 9,
        )

        for i in range(
            6
        )
    ]


    stage = Path(
        tempfile.mkdtemp(
            prefix=(
                "cell29_ai4amp_"
            ),
            dir=str(
                SELFROOT
            ),
        )
    )


    try:

        def write_fasta(
            path,
            sequences,
            prefix,
        ):

            with open(
                path,
                "w",
                encoding="utf-8",
            ) as f:

                for index, sequence in enumerate(
                    sequences,
                    1,
                ):

                    f.write(
                        f">{prefix}_{index:03d}\n"
                        f"{sequence}\n"
                    )


        amp_train_path = (
            stage
            / "amp_train.fa"
        )

        dec_train_path = (
            stage
            / "dec_train.fa"
        )

        amp_val_path = (
            stage
            / "amp_val.fa"
        )

        dec_val_path = (
            stage
            / "dec_val.fa"
        )


        write_fasta(
            amp_train_path,
            train_amp,
            "ATR",
        )

        write_fasta(
            dec_train_path,
            train_dec,
            "DTR",
        )

        write_fasta(
            amp_val_path,
            val_amp,
            "AVA",
        )

        write_fasta(
            dec_val_path,
            val_dec,
            "DVA",
        )


        runner = (
            stage
            / "runner.py"
        )


        runner.write_text(
r'''
from pathlib import Path

import importlib.util
import json
import os
import random
import sys

os.environ["KERAS_BACKEND"] = "tensorflow"
os.environ["CUDA_VISIBLE_DEVICES"] = ""
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import numpy as np
import pandas as pd
import tensorflow as tf
import keras

from keras import backend as K
from keras import optimizers
from keras.callbacks import ModelCheckpoint
from keras.layers import Input, Conv1D, LSTM, Dense
from keras.models import Model, load_model


PC6 = Path(
    sys.argv[1]
)

TABLE = Path(
    sys.argv[2]
)

AMP_TRAIN = Path(
    sys.argv[3]
)

DEC_TRAIN = Path(
    sys.argv[4]
)

AMP_VAL = Path(
    sys.argv[5]
)

DEC_VAL = Path(
    sys.argv[6]
)

OUT = Path(
    sys.argv[7]
)

SEED = int(
    sys.argv[8]
)


OUT.mkdir(
    parents=True,
    exist_ok=True,
)


assert (
    ".".join(
        str(x)
        for x
        in sys.version_info[:3]
    )
    ==
    "3.6.9"
)


assert (
    tf.__version__
    ==
    "1.9.0"
)


assert (
    keras.__version__
    ==
    "2.2.4"
)


assert (
    np.__version__
    ==
    "1.18.2"
)


assert (
    K.backend()
    ==
    "tensorflow"
)


random.seed(
    SEED
)

np.random.seed(
    SEED
)

tf.set_random_seed(
    SEED
)


K.set_session(
    tf.Session(
        config=tf.ConfigProto(
            intra_op_parallelism_threads=1,
            inter_op_parallelism_threads=1,
            device_count={
                "GPU":
                    0
            },
        )
    )
)


spec = (
    importlib.util
    .spec_from_file_location(
        "pc6",
        str(
            PC6
        ),
    )
)


pc6 = (
    importlib.util
    .module_from_spec(
        spec
    )
)


spec.loader.exec_module(
    pc6
)


# ============================================================
# PC6 TABLE ORACLE
# ============================================================

raw = pd.read_csv(
    TABLE,
    sep=" ",
    index_col=0,
)


properties = [
    "H1",
    "V",
    "P1",
    "Pl",
    "PKa",
    "NCI",
]


aminos = list(
    "ACDEFGHIKLMNPQRSTVWY"
)


manual = {}


for aa in aminos:

    manual[
        aa
    ] = [

        (
            float(
                raw.loc[
                    aa,
                    prop
                ]
            )
            -
            float(
                raw[
                    prop
                ].mean()
            )
        )
        /
        float(
            raw[
                prop
            ].std(
                ddof=1
            )
        )

        for prop
        in properties
    ]


manual[
    "X"
] = [
    0.0
] * 6


official_table = (
    pc6.amino_encode_table_6()
)


table_delta = max(

    float(
        np.max(
            np.abs(
                np.asarray(
                    official_table[
                        aa
                    ],
                    dtype=float,
                )
                -
                np.asarray(
                    manual[
                        aa
                    ],
                    dtype=float,
                )
            )
        )
    )

    for aa
    in official_table
)


assert (
    table_delta
    <=
    1e-12
)


oracle_path = (
    OUT
    / "oracle.fa"
)


oracle_path.write_text(
    ">oracle\n"
    "ACDEFGHIKL\n",
    encoding="utf-8",
)


encoded_oracle = np.asarray(
    pc6.PC_6(
        str(
            oracle_path
        ),
        length=200,
    )[
        "oracle"
    ],
    dtype=float,
)


expected_oracle = np.zeros(
    (
        200,
        6,
    ),
    dtype=float,
)


for index, aa in enumerate(
    "ACDEFGHIKL"
):

    expected_oracle[
        index
    ] = (
        manual[
            aa
        ]
    )


oracle_delta = float(
    np.max(
        np.abs(
            encoded_oracle
            -
            expected_oracle
        )
    )
)


assert (
    encoded_oracle.shape
    ==
    (
        200,
        6,
    )
)


assert (
    oracle_delta
    <=
    1e-12
)


# ============================================================
# SYNTHETIC DATA ENCODING
# ============================================================

def encode(
    path,
):

    data = pc6.PC_6(
        str(
            path
        ),
        length=200,
    )


    return (
        list(
            data.keys()
        ),
        np.asarray(
            list(
                data.values()
            ),
            dtype=np.float32,
        ),
    )


id_amp_train, x_amp_train = encode(
    AMP_TRAIN
)

id_dec_train, x_dec_train = encode(
    DEC_TRAIN
)

id_amp_val, x_amp_val = encode(
    AMP_VAL
)

id_dec_val, x_dec_val = encode(
    DEC_VAL
)


X = np.concatenate(
    [
        x_amp_train,
        x_dec_train,
    ],
    axis=0,
)


y = np.concatenate(
    [
        np.ones(
            len(
                x_amp_train
            )
        ),
        np.zeros(
            len(
                x_dec_train
            )
        ),
    ]
).astype(
    np.float32
)


XV = np.concatenate(
    [
        x_amp_val,
        x_dec_val,
    ],
    axis=0,
)


yv = np.concatenate(
    [
        np.ones(
            len(
                x_amp_val
            )
        ),
        np.zeros(
            len(
                x_dec_val
            )
        ),
    ]
).astype(
    np.float32
)


validation_ids = (
    id_amp_val
    +
    id_dec_val
)


permutation = (
    np.random.RandomState(
        SEED
    )
    .permutation(
        len(
            y
        )
    )
)


X = X[
    permutation
]


y = y[
    permutation
]


assert (
    X.shape
    ==
    (
        24,
        200,
        6,
    )
)


assert (
    XV.shape
    ==
    (
        12,
        200,
        6,
    )
)


# ============================================================
# PUBLISHED ARCHITECTURE
# ============================================================

input_layer = Input(
    shape=(
        200,
        6,
    )
)


x = Conv1D(
    64,
    16,
    activation="relu",
    padding="same",
)(
    input_layer
)


x = LSTM(
    100,
    return_sequences=False,
)(
    x
)


output_layer = Dense(
    1,
    activation="sigmoid",
)(
    x
)


model = Model(
    input_layer,
    output_layer,
)


model.compile(
    optimizer=optimizers.Adam(
        lr=0.0003
    ),
    loss="binary_crossentropy",
    metrics=[
        "accuracy"
    ],
)


layers = [

    layer.__class__.__name__

    for layer
    in model.layers
]


assert (
    layers
    ==
    [
        "InputLayer",
        "Conv1D",
        "LSTM",
        "Dense",
    ]
)


assert (
    model.layers[
        1
    ].filters
    ==
    64
)


assert (
    model.layers[
        1
    ].kernel_size[
        0
    ]
    ==
    16
)


assert (
    model.layers[
        2
    ].units
    ==
    100
)


assert (
    model.layers[
        3
    ].units
    ==
    1
)


# ============================================================
# PUBLISHED TRAINING RECIPE
# ============================================================

batch_size = int(
    0.5
    *
    len(
        X
    )
)


assert (
    batch_size
    ==
    12
)


best_model_path = (
    OUT
    / "best.h5"
)


history = model.fit(
    X,
    y,
    validation_data=(
        XV,
        yv,
    ),
    shuffle=True,
    epochs=200,
    batch_size=batch_size,
    callbacks=[
        ModelCheckpoint(
            str(
                best_model_path
            ),
            monitor="val_loss",
            save_best_only=True,
            mode="min",
            verbose=0,
        )
    ],
    verbose=0,
)


assert (
    len(
        history.history[
            "loss"
        ]
    )
    ==
    200
)


assert (
    best_model_path.is_file()
)


best_model = load_model(
    str(
        best_model_path
    )
)


probability = np.asarray(
    best_model.predict(
        XV,
        batch_size=batch_size,
        verbose=0,
    )
).reshape(
    -1
)


assert (
    probability.shape
    ==
    (
        12,
    )
)


assert (
    np.all(
        np.isfinite(
            probability
        )
    )
)


assert (
    np.all(
        (
            probability
            >=
            0.0
        )
        &
        (
            probability
            <=
            1.0
        )
    )
)


pd.DataFrame(
    {
        "seq_id":
            validation_ids,

        "y_true":
            yv.astype(
                int
            ),

        "p_amp":
            probability,

        "pred_gt_0_5":
            (
                probability
                >
                0.5
            ).astype(
                int
            ),
    }
).to_csv(
    OUT
    / "pred.csv",
    index=False,
)


# ============================================================
# SERIALIZATION ORACLE
# ============================================================

reloaded = load_model(
    str(
        best_model_path
    )
)


probability_reloaded = np.asarray(
    reloaded.predict(
        XV,
        batch_size=batch_size,
        verbose=0,
    )
).reshape(
    -1
)


reload_delta = float(
    np.max(
        np.abs(
            probability
            -
            probability_reloaded
        )
    )
)


assert (
    reload_delta
    <=
    1e-7
)


learning_rate = float(
    K.get_value(
        best_model.optimizer.lr
    )
)


assert (
    abs(
        learning_rate
        -
        0.0003
    )
    <=
    1e-10
)


summary = {

    "python":
        ".".join(
            str(x)
            for x
            in sys.version_info[:3]
        ),

    "tensorflow":
        tf.__version__,

    "keras":
        keras.__version__,

    "numpy":
        np.__version__,

    "pc6": {

        "shape":
            [
                200,
                6,
            ],

        "properties":
            properties,

        "table_delta":
            table_delta,

        "oracle_delta":
            oracle_delta,

        "oracle_pass":
            True,
    },

    "architecture": {

        "layers":
            layers,

        "conv_filters":
            64,

        "conv_kernel":
            16,

        "pooling":
            False,

        "lstm_units":
            100,

        "dense_units":
            1,
    },

    "training": {

        "learning_rate":
            learning_rate,

        "epochs":
            200,

        "batch_size":
            batch_size,

        "best_val_loss_checkpoint":
            True,

        "invented_patience":
            False,
    },

    "score": {

        "threshold":
            0.5,

        "min":
            float(
                probability.min()
            ),

        "max":
            float(
                probability.max()
            ),
    },

    "serialization": {

        "delta":
            reload_delta,

        "pass":
            True,
    },
}


with open(
    OUT
    / "summary.json",
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        summary,
        f,
        indent=2,
        sort_keys=True,
    )


print(
    "AI4AMP29="
    +
    json.dumps(
        summary,
        sort_keys=True,
    )
)
''',
            encoding="utf-8",
        )


        runtime_env = (
            os.environ.copy()
        )


        runtime_env.update(
            {
                "KERAS_BACKEND":
                    "tensorflow",

                "CUDA_VISIBLE_DEVICES":
                    "",

                "OMP_NUM_THREADS":
                    "1",

                "MKL_NUM_THREADS":
                    "1",

                "OPENBLAS_NUM_THREADS":
                    "1",

                "TF_CPP_MIN_LOG_LEVEL":
                    "2",

                "PYTHONHASHSEED":
                    "0",
            }
        )


        def run_once(
            output_dir,
        ):

            return run(
                [
                    PY,
                    runner,
                    (
                        PC6_DIR
                        / "Protein_Encoding.py"
                    ),
                    (
                        PC6_DIR
                        / "6-pc"
                    ),
                    amp_train_path,
                    dec_train_path,
                    amp_val_path,
                    dec_val_path,
                    output_dir,
                    "100",
                ],
                timeout=7200,
                env=runtime_env,
                label=(
                    "AI4AMP synthetic "
                    "full-adapter self-test"
                ),
            )


        run1_dir = (
            stage
            / "run1"
        )

        run2_dir = (
            stage
            / "run2"
        )


        run1 = run_once(
            run1_dir
        )


        run2 = run_once(
            run2_dir
        )


        def parse_runner(
            stdout,
        ):

            for line in (
                stdout
                .splitlines()
            ):

                if line.startswith(
                    "AI4AMP29="
                ):

                    return json.loads(
                        line.split(
                            "=",
                            1,
                        )[1]
                    )


            raise AssertionError(
                "AI4AMP29 runner "
                "marker missing"
            )


        summary1 = parse_runner(
            run1.stdout
        )


        summary2 = parse_runner(
            run2.stdout
        )


        assert (
            summary1[
                "python"
            ]
            ==
            "3.6.9"
        )


        assert (
            summary1[
                "tensorflow"
            ]
            ==
            "1.9.0"
        )


        assert (
            summary1[
                "keras"
            ]
            ==
            "2.2.4"
        )


        assert (
            summary1[
                "numpy"
            ]
            ==
            "1.18.2"
        )


        assert (
            summary1[
                "pc6"
            ][
                "oracle_pass"
            ]
            is True
        )


        assert (
            summary1[
                "pc6"
            ][
                "oracle_delta"
            ]
            <=
            1e-12
        )


        assert (
            summary1[
                "architecture"
            ][
                "layers"
            ]
            ==
            [
                "InputLayer",
                "Conv1D",
                "LSTM",
                "Dense",
            ]
        )


        assert (
            abs(
                summary1[
                    "training"
                ][
                    "learning_rate"
                ]
                -
                0.0003
            )
            <=
            1e-10
        )


        assert (
            summary1[
                "training"
            ][
                "epochs"
            ]
            ==
            200
        )


        assert (
            summary1[
                "serialization"
            ][
                "pass"
            ]
            is True
        )


        predictions1 = pd.read_csv(
            run1_dir
            / "pred.csv"
        )


        predictions2 = pd.read_csv(
            run2_dir
            / "pred.csv"
        )


        assert (
            predictions1[
                "seq_id"
            ].tolist()
            ==
            predictions2[
                "seq_id"
            ].tolist()
        )


        assert (
            predictions1[
                "y_true"
            ].tolist()
            ==
            predictions2[
                "y_true"
            ].tolist()
        )


        replay_delta = float(
            np.max(
                np.abs(
                    predictions1[
                        "p_amp"
                    ].to_numpy()
                    -
                    predictions2[
                        "p_amp"
                    ].to_numpy()
                )
            )
        )


        assert (
            replay_delta
            <=
            1e-7
        )


        # ====================================================
        # ATOMIC FINAL BUNDLE
        # ====================================================

        staged_bundle = (
            stage
            / "final_bundle"
        )


        staged_bundle.mkdir(
            parents=True,
            exist_ok=False,
        )


        copies = {

            amp_train_path:
                "amp_train.fa",

            dec_train_path:
                "dec_train.fa",

            amp_val_path:
                "amp_val.fa",

            dec_val_path:
                "dec_val.fa",

            runner:
                "runner.py",

            run1_dir
            / "oracle.fa":
                "oracle.fa",

            run1_dir
            / "best.h5":
                "best.h5",

            run1_dir
            / "pred.csv":
                "pred.csv",

            run1_dir
            / "summary.json":
                "summary.json",
        }


        for source, name in (
            copies.items()
        ):

            shutil.copy2(
                source,
                staged_bundle
                / name,
            )


        assert (
            not BUNDLE.exists()
        )


        os.replace(
            staged_bundle,
            BUNDLE,
        )


        artifacts = {

            name:
                art(
                    BUNDLE
                    / name
                )

            for name
            in copies.values()
        }


        manifest = {

            "schema_version":
                "2.0",

            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "IMPLEMENTATION_VALIDATED",

            "model_id":
                METHOD,

            "implementation_validated":
                True,

            "synthetic_selftest_only":
                True,

            "benchmark_training_performed":
                False,

            "benchmark_test_used":
                False,

            "external_target_used":
                False,

            "predictor_commit":
                PRED_COMMIT,

            "pc6_commit":
                PC6_COMMIT,

            "source_contract_sha256":
                sha256(
                    SRC_CONTRACT
                ),

            "environment_audit_sha256":
                sha256(
                    ENV_AUDIT
                ),

            "adapter_contract_sha256":
                sha256(
                    IMPL_CONTRACT
                ),

            "selftest": {

                **summary1,

                "determinism": {

                    "seed":
                        100,

                    "two_independent_processes":
                        True,

                    "single_thread_cpu":
                        True,

                    "max_abs_probability_delta":
                        replay_delta,

                    "pass":
                        True,
                },
            },

            "artifacts":
                artifacts,
        }


        jwrite(
            SELFTEST,
            manifest,
        )


        validate_self(
            jload(
                SELFTEST
            )
        )


        validated, gate_after = (
            update_gate()
        )


        # ====================================================
        # FINAL REPORT
        # ====================================================

        print(
            "=" * 128
        )

        print(
            "CELL 29 PASS - "
            "AI4AMP OFFICIAL-PC6 + "
            "PUBLISHED-ARCHITECTURE "
            "FULL ADAPTER SELF-TEST PASSED"
        )

        print(
            "=" * 128
        )

        print(
            "Published method       : AI4AMP"
        )

        print(
            "Implementation status  : VALIDATED"
        )

        print(
            "Predictor commit       :",
            PRED_COMMIT,
        )

        print(
            "PC6 commit             :",
            PC6_COMMIT,
        )

        print(
            "Source contract        :",
            SOURCE_ACTION,
        )

        print(
            "-" * 128
        )

        print(
            "EXACT DEDICATED ENVIRONMENT"
        )

        print(
            "Python                 :",
            FINAL_PROBE[
                "python"
            ],
        )

        print(
            "TensorFlow             :",
            FINAL_PROBE[
                "tensorflow"
            ],
            (
                "(CPU package; "
                "same TF 1.9.0 framework)"
            ),
        )

        print(
            "Keras                  :",
            FINAL_PROBE[
                "keras"
            ],
        )

        print(
            "NumPy                  :",
            FINAL_PROBE[
                "numpy"
            ],
        )

        print(
            "SciPy                  :",
            FINAL_PROBE[
                "scipy"
            ],
        )

        print(
            "pandas                 :",
            FINAL_PROBE[
                "pandas"
            ],
        )

        print(
            "Biopython              :",
            FINAL_PROBE[
                "biopython"
            ],
        )

        print(
            "h5py                   :",
            FINAL_PROBE[
                "h5py"
            ],
        )

        print(
            "pip check              : PASS"
        )

        print(
            "-" * 128
        )

        print(
            "PC6                    : "
            "200 x 6 - PASS"
        )

        print(
            "PC6 table max |delta|  :",
            summary1[
                "pc6"
            ][
                "table_delta"
            ],
        )

        print(
            "PC6 oracle max |delta| :",
            summary1[
                "pc6"
            ][
                "oracle_delta"
            ],
        )

        print(
            "Conv1D                 : "
            "64 filters, kernel 16 - PASS"
        )

        print(
            "Pooling                : NONE - PASS"
        )

        print(
            "LSTM                   : "
            "100 units - PASS"
        )

        print(
            "Dense sigmoid          : PASS"
        )

        print(
            "Adam learning rate     : "
            "0.0003 - PASS"
        )

        print(
            "Epoch cap              : "
            "200 - PASS"
        )

        print(
            "Batch                  : "
            "half training set - PASS"
        )

        print(
            "Best val_loss restore  : "
            "PASS; no invented patience"
        )

        print(
            "Native threshold       : > 0.5"
        )

        print(
            "Serialization reload   : PASS"
        )

        print(
            "Deterministic replay   : PASS"
        )

        print(
            "Replay max |delta|     :",
            replay_delta,
        )

        print(
            "-" * 128
        )

        print(
            "Benchmark data used    : FALSE"
        )

        print(
            "Benchmark training     : FALSE"
        )

        print(
            "Benchmark test used    : FALSE"
        )

        print(
            "External target used   : FALSE"
        )

        print(
            "-" * 128
        )

        print(
            "Published validated    :",
            f"{len(validated)}/7",
        )

        print(
            "Validated methods      :",
            validated,
        )

        print(
            "TRAINING GATE          :",
            (
                "OPEN"
                if gate_after[
                    "open"
                ]
                else
                "CLOSED"
            ),
        )

        print(
            "Self-test manifest     :",
            SELFTEST,
        )

        print(
            "Manifest SHA256        :",
            sha256(
                SELFTEST
            ),
        )

        print(
            "NEXT                   : "
            "CELL 30 - AMPlify "
            "OFFICIAL SOURCE + "
            "ENSEMBLE ADAPTER CLOSURE"
        )

        print(
            "=" * 128
        )


    finally:

        if stage.exists():

            shutil.rmtree(
                stage,
                ignore_errors=True,
            )

================================================================================================================================
CELL 29 PASS - AI4AMP OFFICIAL-PC6 + PUBLISHED-ARCHITECTURE FULL ADAPTER SELF-TEST PASSED
================================================================================================================================
Published method       : AI4AMP
Implementation status  : VALIDATED
Predictor commit       : 04ea9fcb9956027f373d36b9ef621a41d778eaca
PC6 commit             : 15f9e9997d26f1dbb6863d9c19881b5cf49f0533
Source contract        : EXISTING SOURCE CONTRACT VERIFIED
--------------------------------------------------------------------------------------------------------------------------------
EXACT DEDICATED ENVIRONMENT
Python                 : 3.6.9
TensorFlow             : 1.9.0 (CPU package; same TF 1.9.0 framework)
Keras                  : 2.2.4
NumPy                  : 1.18.2
SciPy                  : 1.4.1
pandas                 : 0.23.4
Biopython              : 1.73
h5py                   : 2.10.0
pip check              : PASS
--------------------------------------------------------------------------------------------------------------------------------
PC6                    : 200 x 6 - PASS
PC6 table max |delta|  : 0.0
PC6 oracle max |delta| : 0.0
Conv1D                 : 64 filters, kernel 16 - PASS
Pooling                : NONE - PASS
LSTM                   : 100 units - PASS
Dense sigmoid          : PASS
Adam learning rate     : 0.0003 - PASS
Epoch cap              : 200 - PASS
Batch                  : half training set - PASS
Best val_loss restore  : PASS; no invented patience
Native threshold       : > 0.5
Serialization reload   : PASS
Deterministic replay   : PASS
Replay max |delta|     : 0.0
--------------------------------------------------------------------------------------------------------------------------------
Benchmark data used    : FALSE
Benchmark training     : FALSE
Benchmark test used    : FALSE
External target used   : FALSE
--------------------------------------------------------------------------------------------------------------------------------
Published validated    : 6/7
Validated methods      : ['ai4amp', 'ampep', 'ampeppy', 'ampgram', 'ampir', 'ampscannerv2']
TRAINING GATE          : CLOSED
Self-test manifest     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_ai4amp_FINAL_adapter_selftest.json
Manifest SHA256        : 73854f3438545c2e862dab5ecc3312e011a8816b49baebab05e591b3105e72cd
NEXT                   : CELL 30 - AMPlify OFFICIAL SOURCE + ENSEMBLE ADAPTER CLOSURE
================================================================================================================================

In [23]:
# ============================================================
# CELL 30 - AMPlify v1.0.0
# OFFICIAL SOURCE + 5-SUBMODEL ENSEMBLE ADAPTER CLOSURE
# ============================================================

from pathlib import Path
from datetime import datetime
import hashlib
import json
import os
import random
import re
import shutil
import subprocess
import tempfile
import urllib.request

import numpy as np
import pandas as pd


# ============================================================
# 1. PATHS / IMMUTABLE UPSTREAM
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

WORK_ROOT = Path(
    "/home/pc/genpept_benchmark17_work"
)

SOURCE_ROOT = Path(
    "/home/pc/genpept_sources"
)

METHOD_ID = "amplify"

DISPLAY_NAME = "AMPlify"

PUBLISHED_IDS = [
    "ampep",
    "ampscannerv2",
    "ampgram",
    "ampir",
    "ampeppy",
    "ai4amp",
    "amplify",
]

MODEL_SEEDS = list(
    range(
        100,
        110,
    )
)


ROUTE_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_published_method_route_contract.json"
)

TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)

READINESS_PATH = (
    AUDIT_DIR
    / "benchmark17_published_method_local_readiness_latest.csv"
)


UPSTREAM_SELFTESTS = {

    "ampep":
        (
            MANIFEST_DIR
            / "benchmark17_ampep_FINAL_adapter_selftest.json"
        ),

    "ampscannerv2":
        (
            MANIFEST_DIR
            / "benchmark17_ampscannerv2_FINAL_adapter_selftest.json"
        ),

    "ampgram":
        (
            MANIFEST_DIR
            / "benchmark17_ampgram_FINAL_adapter_selftest.json"
        ),

    "ampir":
        (
            MANIFEST_DIR
            / "benchmark17_ampir_FINAL_adapter_selftest.json"
        ),

    "ampeppy":
        (
            MANIFEST_DIR
            / "benchmark17_ampeppy_FINAL_adapter_selftest.json"
        ),

    "ai4amp":
        (
            MANIFEST_DIR
            / "benchmark17_ai4amp_FINAL_adapter_selftest.json"
        ),
}


EXPECTED_ROUTE_SHA256 = (
    "dd7d6a743f088cef95fb49288dcf1801"
    "c9dc335be2656e627e7fc7f3bf7170bd"
)


EXPECTED_UPSTREAM_SHA256 = {

    "ampep":
        (
            "18786bf2b024c8dab4e1bf28fbd843265"
            "68bda559e56a9c20f5895091ca64f4e"
        ),

    "ampscannerv2":
        (
            "025c951b10807b789108d13baca066486"
            "cc2d2e127397c3b54ae44a666a1b96f"
        ),

    "ampgram":
        (
            "399d1d695e72f42ad591caf637de03b91"
            "0d07e09b1f1f5805054e629153aee3d"
        ),

    "ampeppy":
        (
            "32faf1720fe467fbd073527ea10b6f77"
            "da93e51f694f8af7553b465da72adec9"
        ),

    "ai4amp":
        (
            "73854f3438545c2e862dab5ecc3312e0"
            "11a8816b49baebab05e591b3105e72cd"
        ),
}


OFFICIAL_REPOSITORY = (
    "BirolLab/AMPlify"
)

OFFICIAL_TAG = (
    "v1.0.0"
)

OFFICIAL_COMMIT = (
    "ba1f6d196873876cd53d2afb8a71938f6d1687d1"
)

SOURCE_DIR = (
    SOURCE_ROOT
    / (
        "AMPlify_v1.0.0_"
        + OFFICIAL_COMMIT
    )
)


SOURCE_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_amplify_FINAL_source_contract.json"
)

ENVIRONMENT_AUDIT_PATH = (
    MANIFEST_DIR
    / "benchmark17_amplify_FINAL_environment.json"
)

IMPLEMENTATION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_amplify_FINAL_implementation_contract.json"
)

SELFTEST_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_amplify_FINAL_adapter_selftest.json"
)

SELFTEST_ROOT = (
    WORK_ROOT
    / "published_selftests"
    / METHOD_ID
)

FINAL_BUNDLE_DIR = (
    SELFTEST_ROOT
    / "cell30_final_adapter_selftest"
)


for directory in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    WORK_ROOT,
    SOURCE_ROOT,
]:

    assert directory.is_dir(), (
        f"Required directory missing: "
        f"{directory}"
    )


SOURCE_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

SELFTEST_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


for path in [
    ROUTE_CONTRACT_PATH,
    TRAINING_GATE_PATH,
    READINESS_PATH,
    *UPSTREAM_SELFTESTS.values(),
]:

    assert path.is_file(), (
        f"Required upstream artifact missing: "
        f"{path}"
    )


# ============================================================
# 2. HELPERS
# ============================================================

def sha256_file(path):

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as handle:

        for chunk in iter(
            lambda:
                handle.read(
                    1024 * 1024
                ),
            b"",
        ):

            h.update(
                chunk
            )

    return h.hexdigest()


def git_blob_sha1_bytes(data):

    header = (
        f"blob {len(data)}\0"
    ).encode(
        "ascii"
    )

    return hashlib.sha1(
        header
        +
        data
    ).hexdigest()


def git_blob_sha1_file(path):

    return git_blob_sha1_bytes(
        Path(
            path
        ).read_bytes()
    )


def load_json(path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as handle:

        return json.load(
            handle
        )


def atomic_write_json(
    path,
    payload,
):

    path = Path(
        path
    )

    tmp = path.with_name(
        path.name
        +
        ".tmp"
    )

    with open(
        tmp,
        "w",
        encoding="utf-8",
    ) as handle:

        json.dump(
            payload,
            handle,
            indent=2,
            ensure_ascii=False,
            sort_keys=True,
        )

        handle.write(
            "\n"
        )

        handle.flush()

        os.fsync(
            handle.fileno()
        )

    os.replace(
        tmp,
        path,
    )


def atomic_write_csv(
    path,
    dataframe,
):

    path = Path(
        path
    )

    tmp = path.with_name(
        path.name
        +
        ".tmp"
    )

    dataframe.to_csv(
        tmp,
        index=False,
    )

    os.replace(
        tmp,
        path,
    )


def run_cmd(
    command,
    timeout=1800,
    env=None,
    check=True,
    label="subprocess",
):

    result = subprocess.run(
        [
            str(x)
            for x in command
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        env=env,
        timeout=timeout,
    )

    if (
        check
        and
        result.returncode != 0
    ):

        print(
            "=" * 128
        )

        print(
            "SUBPROCESS FAILURE -",
            label,
        )

        print(
            "COMMAND:",
            [
                str(x)
                for x in command
            ],
        )

        print(
            "RETURN CODE:",
            result.returncode,
        )

        print(
            "--- STDOUT ---"
        )

        print(
            result.stdout
        )

        print(
            "--- STDERR ---"
        )

        print(
            result.stderr
        )

        print(
            "=" * 128
        )

        raise AssertionError(
            f"{label} failed "
            f"with return code "
            f"{result.returncode}"
        )

    return result


def boolish(value):

    if isinstance(
        value,
        (
            bool,
            np.bool_,
        ),
    ):

        return bool(
            value
        )

    text = (
        str(value)
        .strip()
        .lower()
    )

    if text in {
        "true",
        "1",
        "yes",
    }:

        return True

    if text in {
        "false",
        "0",
        "no",
    }:

        return False

    raise AssertionError(
        f"Cannot interpret as bool: "
        f"{value!r}"
    )


def artifact_entry(path):

    path = Path(
        path
    )

    assert path.is_file(), (
        f"Artifact missing: "
        f"{path}"
    )

    return {

        "path":
            str(
                path
            ),

        "size_bytes":
            int(
                path.stat().st_size
            ),

        "sha256":
            sha256_file(
                path
            ),
    }


def verify_artifact_entry(
    entry,
):

    path = Path(
        entry[
            "path"
        ]
    )

    assert path.is_file()

    assert (
        int(
            path.stat().st_size
        )
        ==
        int(
            entry[
                "size_bytes"
            ]
        )
    )

    assert (
        sha256_file(
            path
        )
        ==
        entry[
            "sha256"
        ]
    )


# ============================================================
# 3. VERIFY 6/7 UPSTREAM STATE
# ============================================================

assert (
    sha256_file(
        ROUTE_CONTRACT_PATH
    )
    ==
    EXPECTED_ROUTE_SHA256
)


for model_id, path in (
    UPSTREAM_SELFTESTS.items()
):

    if (
        model_id
        in EXPECTED_UPSTREAM_SHA256
    ):

        assert (
            sha256_file(
                path
            )
            ==
            EXPECTED_UPSTREAM_SHA256[
                model_id
            ]
        ), (
            f"Upstream {model_id} "
            f"self-test manifest changed."
        )


    payload = load_json(
        path
    )


    assert (
        payload[
            "implementation_validated"
        ]
        is True
    )


    assert (
        payload[
            "benchmark_training_performed"
        ]
        is False
    )


    assert (
        payload[
            "benchmark_test_used"
        ]
        is False
    )


    observed = (

        payload.get(
            "model_id"
        )

        or

        payload.get(
            "adapter_contract",
            {},
        ).get(
            "model_id"
        )
    )


    assert (
        observed
        ==
        model_id
    )


route_payload = load_json(
    ROUTE_CONTRACT_PATH
)


assert (
    route_payload[
        "status"
    ]
    ==
    "PUBLISHED_METHOD_ROUTES_LOCKED_BEFORE_TRAINING"
)


assert (
    route_payload[
        "restart_safe"
    ]
    is True
)


route_core = (
    route_payload[
        "contract"
    ]
)


assert (
    route_core[
        "published_model_ids"
    ]
    ==
    PUBLISHED_IDS
)


assert (
    route_core[
        "model_seeds"
    ]
    ==
    MODEL_SEEDS
)


assert (
    route_core[
        "n_published_models"
    ]
    ==
    7
)


amplify_route = (
    route_core[
        "methods"
    ][
        METHOD_ID
    ]
)


assert (
    amplify_route[
        "locked_route"
    ]
    ==
    "official_source_retraining"
)


assert (
    amplify_route[
        "pretrained_repeated_inference_allowed"
    ]
    is False
)


assert (
    amplify_route[
        "ten_independent_retraining_runs"
    ]
    is True
)


assert (
    amplify_route[
        "config_lock_required_before_training"
    ]
    is True
)


if (
    "paper_doi"
    in amplify_route
):

    assert (
        amplify_route[
            "paper_doi"
        ]
        ==
        "10.1186/s12864-022-08310-4"
    )


if (
    "official_repository"
    in amplify_route
):

    assert (
        amplify_route[
            "official_repository"
        ]
        in {
            "bcgsc/AMPlify",
            "BirolLab/AMPlify",
        }
    )


gate_before = load_json(
    TRAINING_GATE_PATH
)


assert (
    gate_before[
        "open"
    ]
    is False
)


assert (
    gate_before[
        "benchmark_training_allowed"
    ]
    is False
)


if not SELFTEST_MANIFEST_PATH.is_file():

    assert (
        gate_before[
            "published_methods_implementation_validated"
        ]
        ==
        6
    )

    assert (
        sorted(
            gate_before.get(
                "validated_methods",
                [],
            )
        )
        ==
        sorted(
            UPSTREAM_SELFTESTS.keys()
        )
    )

else:

    assert (
        gate_before[
            "published_methods_implementation_validated"
        ]
        ==
        7
    )

    assert (
        METHOD_ID
        in gate_before.get(
            "validated_methods",
            [],
        )
    )


# ============================================================
# 4. PIN ORIGINAL AMPlify v1.0.0 SOURCE
# ============================================================

PINNED_SOURCE_FILES = {

    "README.md":
        "684ca62a6d044cef30f0786237b3c91116279bad",

    "src/train_amplify.py":
        "d67f6f5d824f87238da42c7860023086177dfbd4",

    "src/AMPlify.py":
        "2966823a9dd35944d254f6f9d77b6041cf16e9b5",

    "src/layers.py":
        "faf47f1353cde4873c3c686f380db26262170db7",
}


RAW_BASE = (
    "https://raw.githubusercontent.com/"
    f"{OFFICIAL_REPOSITORY}/"
    f"{OFFICIAL_COMMIT}"
)


def acquire_pinned_source(
    relpath,
    expected_blob,
):

    destination = (
        SOURCE_DIR
        / relpath
    )

    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    if (
        destination.is_file()
        and
        git_blob_sha1_file(
            destination
        )
        ==
        expected_blob
    ):

        return (
            "REUSED"
        )


    url = (
        f"{RAW_BASE}/"
        f"{relpath}"
    )


    request = urllib.request.Request(
        url,
        headers={
            "User-Agent":
                "GenPept-Benchmark17-AMPlify-v1.0.0/1.0"
        },
    )


    try:

        with urllib.request.urlopen(
            request,
            timeout=120,
        ) as response:

            data = (
                response.read()
            )


    except Exception as exc:

        raise AssertionError(
            "Could not acquire pinned "
            "AMPlify source:\n"
            f"{url}\n"
            f"{type(exc).__name__}: "
            f"{exc}"
        )


    observed_blob = (
        git_blob_sha1_bytes(
            data
        )
    )


    assert (
        observed_blob
        ==
        expected_blob
    ), (
        f"Git blob mismatch for "
        f"{relpath}: "
        f"expected={expected_blob}, "
        f"observed={observed_blob}"
    )


    tmp = (
        destination.with_name(
            destination.name
            +
            ".tmp"
        )
    )


    tmp.write_bytes(
        data
    )


    os.replace(
        tmp,
        destination,
    )


    assert (
        git_blob_sha1_file(
            destination
        )
        ==
        expected_blob
    )


    return (
        "DOWNLOADED"
    )


source_actions = {

    relpath:
        acquire_pinned_source(
            relpath,
            blob,
        )

    for relpath, blob
    in PINNED_SOURCE_FILES.items()
}


for relpath, blob in (
    PINNED_SOURCE_FILES.items()
):

    assert (
        git_blob_sha1_file(
            SOURCE_DIR
            / relpath
        )
        ==
        blob
    )


README_PATH = (
    SOURCE_DIR
    / "README.md"
)

TRAIN_SOURCE_PATH = (
    SOURCE_DIR
    / "src/train_amplify.py"
)

PREDICT_SOURCE_PATH = (
    SOURCE_DIR
    / "src/AMPlify.py"
)

LAYERS_SOURCE_PATH = (
    SOURCE_DIR
    / "src/layers.py"
)


readme_text = (
    README_PATH
    .read_text(
        encoding="utf-8"
    )
)

train_text = (
    TRAIN_SOURCE_PATH
    .read_text(
        encoding="utf-8"
    )
)

predict_text = (
    PREDICT_SOURCE_PATH
    .read_text(
        encoding="utf-8"
    )
)

layers_text = (
    LAYERS_SOURCE_PATH
    .read_text(
        encoding="utf-8"
    )
)


# ------------------------------------------------------------
# Release README constraints
# ------------------------------------------------------------

assert (
    "Keras 2.2.4"
    in readme_text
)


assert (
    "Tensorflow 1.11/1.12/1.13"
    in readme_text
)


assert (
    "File names of 5 trained models"
    in readme_text
)


# ------------------------------------------------------------
# Source-native mechanics
# ------------------------------------------------------------

source_checks = {

    "max_len_200":
        bool(
            re.search(
                r"MAX_LEN\s*=\s*200",
                train_text,
            )
        ),

    "aa20":
        (
            "['A','C','D','E','F','G','H','I','K','L','M','N','P','Q','R','S','T','V','W','Y']"
            in train_text
        ),

    "input_200x20":
        (
            "Input(shape=(MAX_LEN, 20), name='Input')"
            in train_text
        ),

    "masking":
        (
            "Masking(mask_value=0.0"
            in train_text
        ),

    "bilstm_512":
        (
            "Bidirectional(LSTM(512, use_bias=True, dropout=0.5, return_sequences=True)"
            in train_text
        ),

    "mha_32":
        (
            "MultiHeadAttention(head_num=32, activation='relu', use_bias=True"
            in train_text
        ),

    "dropout_02":
        (
            "Dropout(0.2"
            in train_text
        ),

    "context_attention":
        (
            "Attention(name='Attention')"
            in train_text
        ),

    "dense_sigmoid":
        (
            "Dense(1, activation='sigmoid'"
            in train_text
        ),

    "adam_0001":
        (
            "Adam(lr=0.001, beta_1=0.9, beta_2=0.999"
            in train_text
        ),

    "bce":
        (
            "loss='binary_crossentropy'"
            in train_text
        ),

    "source_pre_shuffle_123":
        (
            "random.Random(123).shuffle(train)"
            in train_text
        ),

    "five_folds":
        (
            "ensemble_number = 5"
            in train_text
        ),

    "fold_seed_50":
        (
            "StratifiedKFold(n_splits=ensemble_number, shuffle=True, random_state=50)"
            in train_text
        ),

    "early_stopping":
        (
            "EarlyStopping(monitor='val_acc',  min_delta=0.001, patience=50, restore_best_weights=True)"
            in train_text
        ),

    "epoch_cap_1000_batch_32":
        bool(
            re.search(
                r"epochs=1000,\s*batch_size=32",
                train_text,
            )
        ),

    "native_threshold":
        (
            "if scores[i]>0.5:"
            in train_text
        ),

    "inference_5_models":
        (
            "nargs=5"
            in predict_text
        ),

    "inference_mean":
        (
            "ens_pred = np.mean(np.array(indv_pred), axis=0)"
            in predict_text
        ),

    "load_by_name":
        (
            "model.load_weights(model_dir_list[i], by_name=True)"
            in predict_text
        ),
}


failed_checks = [

    key

    for key, value
    in source_checks.items()

    if not value
]


assert not failed_checks, (
    "AMPlify v1.0.0 "
    "source contract failed: "
    f"{failed_checks}"
)


# ------------------------------------------------------------
# Train / inference architecture must agree at SAME commit
# ------------------------------------------------------------

for literal in [

    "Input(shape=(MAX_LEN, 20), name='Input')",

    "Masking(mask_value=0.0",

    (
        "Bidirectional(LSTM(512, "
        "use_bias=True, "
        "dropout=0.5, "
        "return_sequences=True)"
    ),

    (
        "MultiHeadAttention("
        "head_num=32, "
        "activation='relu', "
        "use_bias=True"
    ),

    "Dropout(0.2",

    "Dense(1, activation='sigmoid'",

]:

    assert (
        literal
        in train_text
    )

    assert (
        literal
        in predict_text
    )


# ============================================================
# 4B. SOURCE CONTRACT
# ============================================================

SOURCE_CONTRACT_CORE = {

    "schema_version":
        "1.0",

    "model_id":
        METHOD_ID,

    "display_name":
        DISPLAY_NAME,

    "paper_doi":
        "10.1186/s12864-022-08310-4",

    "official_repository":
        OFFICIAL_REPOSITORY,

    "official_release_tag":
        OFFICIAL_TAG,

    "official_release_commit":
        OFFICIAL_COMMIT,

    "source_files": {

        relpath: {

            "git_blob_sha1":
                blob,

            "sha256":
                sha256_file(
                    SOURCE_DIR
                    / relpath
                ),

            "path":
                str(
                    SOURCE_DIR
                    / relpath
                ),
        }

        for relpath, blob
        in PINNED_SOURCE_FILES.items()
    },

    "source_checks":
        source_checks,

    "preprocessing": {

        "alphabet":
            "ACDEFGHIKLMNPQRSTVWY",

        "feature_type":
            "20-dimensional one-hot encoding",

        "max_length":
            200,

        "padding":
            (
                "post-padding with "
                "all-zero 20-vectors"
            ),

        "mask_value":
            0.0,
    },

    "architecture": {

        "input_shape":
            [
                200,
                20,
            ],

        "bidirectional_lstm_units_per_direction":
            512,

        "lstm_dropout":
            0.5,

        "lstm_return_sequences":
            True,

        "multi_head_attention_heads":
            32,

        "multi_head_attention_activation":
            "relu",

        "post_mha_dropout":
            0.2,

        "context_attention":
            True,

        "output_units":
            1,

        "output_activation":
            "sigmoid",
    },

    "training_recipe": {

        "optimizer":
            "Adam",

        "learning_rate":
            0.001,

        "beta_1":
            0.9,

        "beta_2":
            0.999,

        "loss":
            "binary_crossentropy",

        "batch_size":
            32,

        "epoch_cap":
            1000,

        "early_stopping_monitor":
            "val_acc",

        "early_stopping_min_delta":
            0.001,

        "early_stopping_patience":
            50,

        "early_stopping_restore_best_weights":
            True,

        "ensemble_submodels":
            5,

        "source_pre_shuffle_seed":
            123,

        "source_stratified_kfold_random_state":
            50,
    },

    "prediction": {

        "submodel_combination":
            (
                "arithmetic_mean_of_"
                "5_probabilities"
            ),

        "positive_score":
            "mean sigmoid P(AMP)",

        "native_threshold":
            0.5,

        "native_positive_rule":
            "score > 0.5",
    },

    "seed_separation": {

        "benchmark_model_seeds":
            MODEL_SEEDS,

        "amplify_dataset_partition_seed":
            2026,

        "partition_seed_is_model_seed":
            False,

        "source_pre_shuffle_seed":
            123,

        "source_internal_fold_seed":
            50,

        "benchmark_run_rng_policy":
            (
                "RUN_SEED seeds Python/NumPy/"
                "TensorFlow model RNG before the "
                "5-submodel run; source-local "
                "shuffle seed 123 and internal "
                "fold seed 50 remain unchanged"
            ),
    },
}


if SOURCE_CONTRACT_PATH.is_file():

    existing = load_json(
        SOURCE_CONTRACT_PATH
    )

    assert (
        existing[
            "status"
        ]
        ==
        "AMPLIFY_V1_SOURCE_CONTRACT_LOCKED"
    )

    assert (
        existing[
            "contract"
        ]
        ==
        SOURCE_CONTRACT_CORE
    ), (
        "Existing AMPlify source "
        "contract differs; refusing "
        "silent overwrite."
    )

    SOURCE_CONTRACT_ACTION = (
        "EXISTING IDENTICAL SOURCE "
        "CONTRACT VERIFIED"
    )


else:

    atomic_write_json(
        SOURCE_CONTRACT_PATH,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AMPLIFY_V1_SOURCE_CONTRACT_LOCKED",

            "contract":
                SOURCE_CONTRACT_CORE,
        },
    )

    SOURCE_CONTRACT_ACTION = (
        "NEW SOURCE CONTRACT "
        "ATOMICALLY COMMITTED"
    )


# ============================================================
# 5. DEDICATED PAPER-COMPATIBLE ENVIRONMENT
#
# Paper-exact core:
#   Python      3.6.7
#   Keras       2.2.4
#   TensorFlow  1.12.0
#
# The remaining pins below are explicit compatibility pins,
# NOT claims that the paper reported those exact versions.
#
# --no-deps is intentional to prevent modern pip from silently
# replacing the legacy NumPy/h5py stack.
# ============================================================

COMPATIBILITY_PINS = {

    "numpy":
        "1.16.6",

    "scipy":
        "1.2.1",

    "pandas":
        "0.24.2",

    "biopython":
        "1.73",

    "sklearn":
        "0.20.4",

    "h5py":
        "2.10.0",
}


def locate_conda():

    candidates = []


    if os.environ.get(
        "CONDA_EXE"
    ):

        candidates.append(
            Path(
                os.environ[
                    "CONDA_EXE"
                ]
            )
        )


    candidates.extend(
        [
            (
                Path.home()
                / "miniconda3/bin/conda"
            ),

            (
                Path.home()
                / "anaconda3/bin/conda"
            ),
        ]
    )


    located = shutil.which(
        "conda"
    )


    if located:

        candidates.append(
            Path(
                located
            )
        )


    seen = set()


    for candidate in candidates:

        key = str(
            candidate
        )


        if key in seen:

            continue


        seen.add(
            key
        )


        if (
            candidate.is_file()
            and
            os.access(
                candidate,
                os.X_OK,
            )
        ):

            return (
                candidate.resolve()
            )


    raise AssertionError(
        "Conda executable not found."
    )


CONDA_EXE = (
    locate_conda()
)

CONDA_ROOT = (
    CONDA_EXE
    .parent
    .parent
)

ENV_PREFIX = (
    CONDA_ROOT
    / "envs/genpept_amplify_v1"
)

ENV_PYTHON = (
    ENV_PREFIX
    / "bin/python"
)


PROBE_CODE = r'''
import json
import os
import sys

os.environ["KERAS_BACKEND"] = "tensorflow"
os.environ["CUDA_VISIBLE_DEVICES"] = ""

payload = {
    "python":
        ".".join(
            str(x)
            for x in sys.version_info[:3]
        )
}

for key, module_name in [

    ("numpy", "numpy"),
    ("scipy", "scipy"),
    ("pandas", "pandas"),
    ("biopython", "Bio"),
    ("sklearn", "sklearn"),
    ("tensorflow", "tensorflow"),
    ("keras", "keras"),
    ("h5py", "h5py"),

]:

    try:

        module = __import__(
            module_name,
            fromlist=["*"],
        )

        payload[key] = (
            module.__version__
        )

        payload[
            key + "_path"
        ] = (
            module.__file__
        )

    except Exception as exc:

        payload[
            key + "_error"
        ] = (
            type(exc).__name__
            + ": "
            + str(exc)
        )


try:

    import keras.backend as K

    payload[
        "keras_backend"
    ] = (
        K.backend()
    )

except Exception as exc:

    payload[
        "keras_backend_error"
    ] = (
        type(exc).__name__
        + ": "
        + str(exc)
    )


try:

    import pkg_resources

    for key, distribution in [

        (
            "tensorboard_dist",
            "tensorboard",
        ),

        (
            "keras_applications_dist",
            "Keras-Applications",
        ),

        (
            "keras_preprocessing_dist",
            "Keras-Preprocessing",
        ),

        (
            "protobuf_dist",
            "protobuf",
        ),

        (
            "grpcio_dist",
            "grpcio",
        ),

        (
            "absl_py_dist",
            "absl-py",
        ),

        (
            "astor_dist",
            "astor",
        ),

        (
            "gast_dist",
            "gast",
        ),

        (
            "six_dist",
            "six",
        ),
    ]:

        payload[key] = (
            pkg_resources
            .get_distribution(
                distribution
            )
            .version
        )

except Exception as exc:

    payload[
        "distribution_probe_error"
    ] = (
        type(exc).__name__
        + ": "
        + str(exc)
    )


print(
    "AMPLIFY30_PROBE="
    +
    json.dumps(
        payload,
        sort_keys=True,
    )
)
'''


def probe_environment():

    if not ENV_PYTHON.is_file():

        return (
            None,
            None,
        )


    runtime_env = (
        os.environ.copy()
    )


    runtime_env.update(
        {
            "KERAS_BACKEND":
                "tensorflow",

            "CUDA_VISIBLE_DEVICES":
                "",

            "TF_CPP_MIN_LOG_LEVEL":
                "2",
        }
    )


    result = run_cmd(
        [
            ENV_PYTHON,
            "-c",
            PROBE_CODE,
        ],
        timeout=300,
        env=runtime_env,
        check=False,
        label=(
            "AMPlify environment probe"
        ),
    )


    payload = None


    for line in (
        result.stdout
        .splitlines()
    ):

        if line.startswith(
            "AMPLIFY30_PROBE="
        ):

            payload = json.loads(
                line.split(
                    "=",
                    1,
                )[1]
            )

            break


    return (
        payload,
        result,
    )


def python_is_367():

    if not ENV_PYTHON.is_file():

        return False


    result = run_cmd(
        [
            ENV_PYTHON,
            "-c",
            (
                "import sys; "
                "print('%d.%d.%d' "
                "% sys.version_info[:3])"
            ),
        ],
        timeout=60,
        check=False,
        label=(
            "AMPlify Python 3.6.7 probe"
        ),
    )


    return (
        result.returncode == 0
        and
        result.stdout.strip()
        ==
        "3.6.7"
    )


EXPECTED_ENV = {

    "python":
        "3.6.7",

    "tensorflow":
        "1.12.0",

    "keras":
        "2.2.4",

    "numpy":
        COMPATIBILITY_PINS[
            "numpy"
        ],

    "scipy":
        COMPATIBILITY_PINS[
            "scipy"
        ],

    "pandas":
        COMPATIBILITY_PINS[
            "pandas"
        ],

    "biopython":
        COMPATIBILITY_PINS[
            "biopython"
        ],

    "sklearn":
        COMPATIBILITY_PINS[
            "sklearn"
        ],

    "h5py":
        COMPATIBILITY_PINS[
            "h5py"
        ],

    "keras_backend":
        "tensorflow",

    "tensorboard_dist":
        "1.12.2",

    "keras_applications_dist":
        "1.0.8",

    "keras_preprocessing_dist":
        "1.1.0",

    "protobuf_dist":
        "3.11.3",

    "grpcio_dist":
        "1.24.3",

    "absl_py_dist":
        "0.7.1",

    "astor_dist":
        "0.7.1",

    "gast_dist":
        "0.2.2",

    "six_dist":
        "1.12.0",
}


def environment_ok(
    payload,
):

    if not payload:

        return False


    return all(

        str(
            payload.get(
                key,
                "",
            )
        )
        ==
        expected

        for key, expected
        in EXPECTED_ENV.items()
    )


initial_probe, _ = (
    probe_environment()
)


if not environment_ok(
    initial_probe
):

    # --------------------------------------------------------
    # Remove ONLY this method-specific prefix if Python differs
    # from the paper-exact 3.6.7 runtime.
    # --------------------------------------------------------

    if (
        ENV_PREFIX.exists()
        and
        not python_is_367()
    ):

        removal = run_cmd(
            [
                CONDA_EXE,
                "remove",
                "-y",
                "-p",
                ENV_PREFIX,
                "--all",
            ],
            timeout=1800,
            check=False,
            label=(
                "remove invalid AMPlify "
                "dedicated environment"
            ),
        )


        if (
            removal.returncode != 0
            and
            ENV_PREFIX.exists()
        ):

            shutil.rmtree(
                ENV_PREFIX
            )


    # --------------------------------------------------------
    # Create ONLY Python 3.6.7 + pip.
    # --------------------------------------------------------

    if not ENV_PYTHON.is_file():

        create_attempts = [

            [
                CONDA_EXE,
                "create",
                "-y",
                "-p",
                ENV_PREFIX,
                "-c",
                "defaults",
                "python=3.6.7",
                "pip",
            ],

            [
                CONDA_EXE,
                "create",
                "-y",
                "-p",
                ENV_PREFIX,
                "-c",
                "conda-forge",
                "python=3.6.7",
                "pip",
            ],
        ]


        created = False

        failures = []


        for index, command in enumerate(
            create_attempts,
            1,
        ):

            result = run_cmd(
                command,
                timeout=3600,
                check=False,
                label=(
                    "create AMPlify "
                    "Python 3.6.7 "
                    f"environment attempt {index}"
                ),
            )


            if (
                ENV_PYTHON.is_file()
                and
                python_is_367()
            ):

                created = True

                break


            failures.append(
                {
                    "attempt":
                        index,

                    "returncode":
                        result.returncode,

                    "stdout":
                        result.stdout[
                            -12000:
                        ],

                    "stderr":
                        result.stderr[
                            -12000:
                        ],
                }
            )


            if (
                ENV_PREFIX.exists()
                and
                not python_is_367()
            ):

                cleanup = run_cmd(
                    [
                        CONDA_EXE,
                        "remove",
                        "-y",
                        "-p",
                        ENV_PREFIX,
                        "--all",
                    ],
                    timeout=1800,
                    check=False,
                    label=(
                        "cleanup failed "
                        "AMPlify environment "
                        "attempt"
                    ),
                )


                if (
                    cleanup.returncode != 0
                    and
                    ENV_PREFIX.exists()
                ):

                    shutil.rmtree(
                        ENV_PREFIX
                    )


        if not created:

            print(
                "=" * 128
            )

            print(
                "AMPlify PYTHON 3.6.7 "
                "ENVIRONMENT CREATION FAILED"
            )


            for failure in failures:

                print(
                    "ATTEMPT:",
                    failure[
                        "attempt"
                    ],
                    "RC:",
                    failure[
                        "returncode"
                    ],
                )

                print(
                    "--- STDOUT TAIL ---"
                )

                print(
                    failure[
                        "stdout"
                    ]
                )

                print(
                    "--- STDERR TAIL ---"
                )

                print(
                    failure[
                        "stderr"
                    ]
                )


            print(
                "=" * 128
            )


            raise AssertionError(
                "Could not create "
                "paper-exact Python "
                "3.6.7 environment."
            )


    assert (
        python_is_367()
    )


    # --------------------------------------------------------
    # Python 3.6-compatible packaging toolchain
    # --------------------------------------------------------

    run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--force-reinstall",

            "pip==21.3.1",
            "setuptools==59.6.0",
            "wheel==0.37.1",
        ],
        timeout=1800,
        label=(
            "pin AMPlify Python 3.6 "
            "packaging toolchain"
        ),
    )


    # --------------------------------------------------------
    # Explicit compatibility stack.
    #
    # These versions are compatibility pins, not claims that
    # the paper explicitly reported them.
    #
    # --no-deps prevents dependency resolver drift.
    # --------------------------------------------------------

    run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--force-reinstall",
            "--no-deps",

            "numpy==1.16.6",
            "scipy==1.2.1",
            "pandas==0.24.2",
            "biopython==1.73",
            "scikit-learn==0.20.4",
            "h5py==2.10.0",
            "python-dateutil==2.8.1",
            "pytz==2020.1",
        ],
        timeout=5400,
        label=(
            "restore AMPlify numerical "
            "compatibility stack"
        ),
    )


    # --------------------------------------------------------
    # Exact Keras 2.2.4 stack.
    # --------------------------------------------------------

    run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--force-reinstall",
            "--no-deps",

            "Keras==2.2.4",
            "Keras-Applications==1.0.8",
            "Keras-Preprocessing==1.1.0",
            "PyYAML==5.4.1",
            "six==1.12.0",
        ],
        timeout=3600,
        label=(
            "restore exact AMPlify "
            "Keras stack"
        ),
    )


    # --------------------------------------------------------
    # Exact TensorFlow 1.12.0 runtime.
    # Every dependency is explicit.
    # --------------------------------------------------------

    run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "install",
            "--no-cache-dir",
            "--force-reinstall",
            "--no-deps",

            "tensorflow==1.12.0",
            "tensorboard==1.12.2",
            "protobuf==3.11.3",
            "grpcio==1.24.3",
            "absl-py==0.7.1",
            "astor==0.7.1",
            "gast==0.2.2",
            "termcolor==1.1.0",
            "Markdown==3.1.1",
            "Werkzeug==0.16.1",
        ],
        timeout=5400,
        label=(
            "restore exact AMPlify "
            "TensorFlow 1.12 stack"
        ),
    )


    # --------------------------------------------------------
    # Dependency consistency
    # --------------------------------------------------------

    dependency_check = run_cmd(
        [
            ENV_PYTHON,
            "-m",
            "pip",
            "check",
        ],
        timeout=300,
        check=False,
        label=(
            "AMPlify pip dependency check"
        ),
    )


    if (
        dependency_check.returncode
        != 0
    ):

        print(
            "=" * 128
        )

        print(
            "AMPlify PIP CHECK FAILED"
        )

        print(
            dependency_check.stdout
        )

        print(
            dependency_check.stderr
        )

        print(
            "=" * 128
        )


        raise AssertionError(
            "AMPlify dedicated environment "
            "dependency check failed."
        )


# ============================================================
# 5B. FINAL ENVIRONMENT GATE
# ============================================================

FINAL_PROBE, FINAL_PROBE_RESULT = (
    probe_environment()
)


if not environment_ok(
    FINAL_PROBE
):

    print(
        "=" * 128
    )

    print(
        "AMPlify FINAL ENVIRONMENT "
        "PROBE FAILED"
    )


    print(
        json.dumps(
            FINAL_PROBE,
            indent=2,
            sort_keys=True,
        )
        if FINAL_PROBE
        else
        "NO PROBE JSON"
    )


    if (
        FINAL_PROBE_RESULT
        is not None
    ):

        print(
            "--- STDOUT ---"
        )

        print(
            FINAL_PROBE_RESULT.stdout
        )

        print(
            "--- STDERR ---"
        )

        print(
            FINAL_PROBE_RESULT.stderr
        )


    print(
        "=" * 128
    )


    raise AssertionError(
        "AMPlify paper-compatible "
        "environment is not exact-ready."
    )


final_pip_check = run_cmd(
    [
        ENV_PYTHON,
        "-m",
        "pip",
        "check",
    ],
    timeout=300,
    check=False,
    label=(
        "AMPlify final pip check"
    ),
)


if (
    final_pip_check.returncode
    != 0
):

    print(
        final_pip_check.stdout
    )

    print(
        final_pip_check.stderr
    )

    raise AssertionError(
        "AMPlify final pip check failed."
    )


environment_root = str(
    ENV_PREFIX.resolve()
)


for key in [

    "numpy_path",
    "scipy_path",
    "pandas_path",
    "biopython_path",
    "sklearn_path",
    "tensorflow_path",
    "keras_path",
    "h5py_path",

]:

    assert (
        key
        in FINAL_PROBE
    )


    assert (
        str(
            FINAL_PROBE[
                key
            ]
        ).startswith(
            environment_root
        )
    ), (
        f"{key} resolved outside "
        f"dedicated environment: "
        f"{FINAL_PROBE[key]}"
    )


# ============================================================
# 5C. ENVIRONMENT AUDIT
# ============================================================

ENVIRONMENT_CORE = {

    "schema_version":
        "1.0",

    "model_id":
        METHOD_ID,

    "environment_prefix":
        str(
            ENV_PREFIX
        ),

    "python_executable":
        str(
            ENV_PYTHON
        ),

    "observed":
        FINAL_PROBE,

    "paper_exact": {

        "python":
            "3.6.7",

        "keras":
            "2.2.4",

        "tensorflow":
            "1.12.0",
    },

    "compatibility_pins_not_claimed_as_paper_exact":
        COMPATIBILITY_PINS,

    "official_release_constraints": {

        "keras":
            "2.2.4",

        "tensorflow":
            "1.11/1.12/1.13",
    },

    "resolver_policy":
        (
            "legacy packages explicitly "
            "pinned; Keras/TensorFlow "
            "installed with --no-deps"
        ),

    "pip_check":
        "PASS",
}


if ENVIRONMENT_AUDIT_PATH.is_file():

    existing = load_json(
        ENVIRONMENT_AUDIT_PATH
    )


    assert (
        existing[
            "status"
        ]
        ==
        "AMPLIFY_V1_ENVIRONMENT_READY"
    )


    assert (
        existing[
            "audit"
        ]
        ==
        ENVIRONMENT_CORE
    ), (
        "Existing AMPlify environment "
        "audit differs; refusing silent "
        "overwrite."
    )


    ENVIRONMENT_ACTION = (
        "EXISTING IDENTICAL ENVIRONMENT "
        "AUDIT VERIFIED"
    )


else:

    atomic_write_json(
        ENVIRONMENT_AUDIT_PATH,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AMPLIFY_V1_ENVIRONMENT_READY",

            "audit":
                ENVIRONMENT_CORE,
        },
    )


    ENVIRONMENT_ACTION = (
        "NEW ENVIRONMENT AUDIT "
        "ATOMICALLY COMMITTED"
    )


# ============================================================
# 6. FINAL IMPLEMENTATION CONTRACT BEFORE SELF-TEST
# ============================================================

IMPLEMENTATION_CORE = {

    "schema_version":
        "1.0",

    "model_id":
        METHOD_ID,

    "display_name":
        DISPLAY_NAME,

    "paper_doi":
        "10.1186/s12864-022-08310-4",

    "implementation_route":
        "official_source_retraining",

    "official_release_tag":
        OFFICIAL_TAG,

    "official_release_commit":
        OFFICIAL_COMMIT,

    "preprocessing":
        SOURCE_CONTRACT_CORE[
            "preprocessing"
        ],

    "architecture":
        SOURCE_CONTRACT_CORE[
            "architecture"
        ],

    "production_training":
        SOURCE_CONTRACT_CORE[
            "training_recipe"
        ],

    "production_prediction":
        SOURCE_CONTRACT_CORE[
            "prediction"
        ],

    "benchmark_model_seeds":
        MODEL_SEEDS,

    "benchmark_rng_adaptation": {

        "run_seed_role":
            (
                "model initialization/"
                "training stochasticity only"
            ),

        "python_random_seed":
            "RUN_SEED",

        "numpy_seed":
            "RUN_SEED",

        "tensorflow_graph_seed":
            "RUN_SEED",

        "source_pre_shuffle_seed_123_preserved":
            True,

        "source_internal_fold_seed_50_preserved":
            True,

        "amplify_dataset_partition_seed_2026_preserved_separately":
            True,

        "amplify_dataset_partition_seed_2026_is_model_seed":
            False,
    },

    "selftest_reduction": {

        "purpose":
            "implementation mechanics only",

        "synthetic_only":
            True,

        "five_submodels_preserved":
            True,

        "five_fold_partition_preserved":
            True,

        "source_pre_shuffle_seed_123_preserved":
            True,

        "source_fold_seed_50_preserved":
            True,

        "batch_size_32_preserved":
            True,

        "early_stopping_callback_configuration_preserved":
            True,

        "epochs_executed_per_submodel":
            1,

        "production_epoch_cap_remains_locked_at":
            1000,

        "production_early_stopping_patience_remains_locked_at":
            50,

        "performance_claim_allowed":
            False,
    },

    "scientific_boundary": {

        "benchmark_train_used":
            False,

        "benchmark_validation_used":
            False,

        "benchmark_test_used":
            False,

        "external_target_used":
            False,
    },
}


if IMPLEMENTATION_CONTRACT_PATH.is_file():

    existing = load_json(
        IMPLEMENTATION_CONTRACT_PATH
    )


    assert (
        existing[
            "status"
        ]
        ==
        "AMPLIFY_IMPLEMENTATION_CONTRACT_LOCKED"
    )


    assert (
        existing[
            "contract"
        ]
        ==
        IMPLEMENTATION_CORE
    ), (
        "Existing AMPlify implementation "
        "contract differs; refusing "
        "silent overwrite."
    )


    IMPLEMENTATION_ACTION = (
        "EXISTING IDENTICAL IMPLEMENTATION "
        "CONTRACT VERIFIED"
    )


else:

    atomic_write_json(
        IMPLEMENTATION_CONTRACT_PATH,
        {
            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "AMPLIFY_IMPLEMENTATION_CONTRACT_LOCKED",

            "implementation_validated":
                False,

            "benchmark_training_performed":
                False,

            "benchmark_test_used":
                False,

            "external_target_used":
                False,

            "contract":
                IMPLEMENTATION_CORE,
        },
    )


    IMPLEMENTATION_ACTION = (
        "NEW IMPLEMENTATION CONTRACT "
        "ATOMICALLY COMMITTED"
    )


# ============================================================
# 7. GATE / MANIFEST HELPERS
# ============================================================

def validated_methods_from_manifests():

    validated = []


    for model_id in PUBLISHED_IDS:

        path = (
            MANIFEST_DIR
            / (
                f"benchmark17_{model_id}_"
                f"FINAL_adapter_selftest.json"
            )
        )


        if (
            path.is_file()
            and
            load_json(
                path
            ).get(
                "implementation_validated"
            )
            is True
        ):

            validated.append(
                model_id
            )


    return sorted(
        validated
    )


def update_readiness_and_gate():

    readiness = pd.read_csv(
        READINESS_PATH,
        low_memory=False,
    )


    required_columns = {

        "model_id",
        "adapter_self_test_passed",
        "implementation_validated",
        "local_state",
        "training_allowed",
    }


    assert (
        required_columns
        .issubset(
            readiness.columns
        )
    )


    mask = (
        readiness[
            "model_id"
        ]
        .astype(str)
        ==
        METHOD_ID
    )


    assert (
        int(
            mask.sum()
        )
        ==
        1
    )


    readiness.loc[
        mask,
        "adapter_self_test_passed",
    ] = True


    readiness.loc[
        mask,
        "implementation_validated",
    ] = True


    readiness.loc[
        mask,
        "local_state",
    ] = (
        "IMPLEMENTATION_VALIDATED"
    )


    validated = (
        validated_methods_from_manifests()
    )


    assert (
        validated
        ==
        sorted(
            PUBLISHED_IDS
        )
    ), validated


    gate = load_json(
        TRAINING_GATE_PATH
    )


    gate[
        "published_methods_implementation_validated"
    ] = 7


    gate[
        "validated_methods"
    ] = validated


    gate[
        "open"
    ] = True


    gate[
        "benchmark_training_allowed"
    ] = True


    gate[
        "reason"
    ] = (
        "All seven published-method "
        "implementations validated."
    )


    gate[
        "updated_at"
    ] = (
        datetime.now()
        .astimezone()
        .isoformat()
    )


    # --------------------------------------------------------
    # Global training permission changes only NOW,
    # after 7/7 validated manifests exist.
    # --------------------------------------------------------

    readiness.loc[
        :,
        "training_allowed",
    ] = True


    atomic_write_csv(
        READINESS_PATH,
        readiness,
    )


    atomic_write_json(
        TRAINING_GATE_PATH,
        gate,
    )


    readiness_check = pd.read_csv(
        READINESS_PATH,
        low_memory=False,
    )


    gate_check = load_json(
        TRAINING_GATE_PATH
    )


    mask_check = (
        readiness_check[
            "model_id"
        ]
        .astype(str)
        ==
        METHOD_ID
    )


    assert (
        int(
            mask_check.sum()
        )
        ==
        1
    )


    assert (
        boolish(
            readiness_check.loc[
                mask_check,
                "adapter_self_test_passed",
            ].iloc[
                0
            ]
        )
        is True
    )


    assert (
        boolish(
            readiness_check.loc[
                mask_check,
                "implementation_validated",
            ].iloc[
                0
            ]
        )
        is True
    )


    assert (
        str(
            readiness_check.loc[
                mask_check,
                "local_state",
            ].iloc[
                0
            ]
        )
        ==
        "IMPLEMENTATION_VALIDATED"
    )


    assert (
        gate_check[
            "open"
        ]
        is True
    )


    assert (
        gate_check[
            "benchmark_training_allowed"
        ]
        is True
    )


    assert (
        gate_check[
            "published_methods_implementation_validated"
        ]
        ==
        7
    )


    assert (
        gate_check[
            "validated_methods"
        ]
        ==
        sorted(
            PUBLISHED_IDS
        )
    )


    return (
        validated,
        gate_check,
    )


def validate_selftest_manifest(
    payload,
):

    assert (
        payload[
            "status"
        ]
        ==
        "IMPLEMENTATION_VALIDATED"
    )


    assert (
        payload[
            "model_id"
        ]
        ==
        METHOD_ID
    )


    assert (
        payload[
            "implementation_validated"
        ]
        is True
    )


    assert (
        payload[
            "synthetic_selftest_only"
        ]
        is True
    )


    assert (
        payload[
            "benchmark_training_performed"
        ]
        is False
    )


    assert (
        payload[
            "benchmark_validation_used"
        ]
        is False
    )


    assert (
        payload[
            "benchmark_test_used"
        ]
        is False
    )


    assert (
        payload[
            "external_target_used"
        ]
        is False
    )


    assert (
        payload[
            "official_release_tag"
        ]
        ==
        OFFICIAL_TAG
    )


    assert (
        payload[
            "official_release_commit"
        ]
        ==
        OFFICIAL_COMMIT
    )


    assert (
        payload[
            "source_contract_sha256"
        ]
        ==
        sha256_file(
            SOURCE_CONTRACT_PATH
        )
    )


    assert (
        payload[
            "environment_audit_sha256"
        ]
        ==
        sha256_file(
            ENVIRONMENT_AUDIT_PATH
        )
    )


    assert (
        payload[
            "implementation_contract_sha256"
        ]
        ==
        sha256_file(
            IMPLEMENTATION_CONTRACT_PATH
        )
    )


    selftest = (
        payload[
            "selftest"
        ]
    )


    assert (
        selftest[
            "one_hot_oracle"
        ][
            "pass"
        ]
        is True
    )


    assert (
        selftest[
            "one_hot_oracle"
        ][
            "max_abs_delta"
        ]
        ==
        0.0
    )


    assert (
        selftest[
            "architecture"
        ][
            "pass"
        ]
        is True
    )


    assert (
        selftest[
            "architecture"
        ][
            "bilstm_units_per_direction"
        ]
        ==
        512
    )


    assert (
        selftest[
            "architecture"
        ][
            "multi_head_attention_heads"
        ]
        ==
        32
    )


    assert (
        selftest[
            "architecture"
        ][
            "lstm_dropout"
        ]
        ==
        0.5
    )


    assert (
        selftest[
            "architecture"
        ][
            "post_mha_dropout"
        ]
        ==
        0.2
    )


    assert (
        selftest[
            "architecture"
        ][
            "dense_units"
        ]
        ==
        1
    )


    assert (
        selftest[
            "ensemble"
        ][
            "submodels"
        ]
        ==
        5
    )


    assert (
        selftest[
            "ensemble"
        ][
            "fold_validation_coverage_once"
        ]
        is True
    )


    assert (
        selftest[
            "ensemble"
        ][
            "manual_mean_max_abs_delta"
        ]
        <=
        1e-7
    )


    assert (
        selftest[
            "ensemble"
        ][
            "reload_max_abs_delta"
        ]
        <=
        1e-7
    )


    assert (
        selftest[
            "inference_replay"
        ][
            "max_abs_delta"
        ]
        <=
        1e-7
    )


    assert (
        selftest[
            "inference_replay"
        ][
            "pass"
        ]
        is True
    )


    assert (
        selftest[
            "production_recipe_locked"
        ][
            "epoch_cap"
        ]
        ==
        1000
    )


    assert (
        selftest[
            "production_recipe_locked"
        ][
            "early_stopping_patience"
        ]
        ==
        50
    )


    assert (
        selftest[
            "production_recipe_locked"
        ][
            "batch_size"
        ]
        ==
        32
    )


    assert (
        selftest[
            "selftest_execution"
        ][
            "epochs_per_submodel"
        ]
        ==
        1
    )


    for entry in (
        payload[
            "artifacts"
        ].values()
    ):

        verify_artifact_entry(
            entry
        )


# ============================================================
# 8. REUSE COMPLETED PASS
# ============================================================

if SELFTEST_MANIFEST_PATH.is_file():

    existing_selftest = load_json(
        SELFTEST_MANIFEST_PATH
    )


    validate_selftest_manifest(
        existing_selftest
    )


    validated, gate_after = (
        update_readiness_and_gate()
    )


    print(
        "=" * 128
    )

    print(
        "CELL 30 PASS - "
        "AMPlify v1.0.0 FULL ADAPTER "
        "SELF-TEST REUSED AND VERIFIED"
    )

    print(
        "=" * 128
    )

    print(
        "Published method       : AMPlify"
    )

    print(
        "Implementation status  : VALIDATED"
    )

    print(
        "Official tag           :",
        OFFICIAL_TAG,
    )

    print(
        "Official commit        :",
        OFFICIAL_COMMIT,
    )

    print(
        "Python                 :",
        FINAL_PROBE[
            "python"
        ],
    )

    print(
        "TensorFlow             :",
        FINAL_PROBE[
            "tensorflow"
        ],
    )

    print(
        "Keras                  :",
        FINAL_PROBE[
            "keras"
        ],
    )

    print(
        "Published validated    : 7/7"
    )

    print(
        "Validated methods      :",
        validated,
    )

    print(
        "TRAINING GATE          : OPEN"
    )

    print(
        "Benchmark training     : "
        "FALSE in Cell 30"
    )

    print(
        "Self-test manifest     :",
        SELFTEST_MANIFEST_PATH,
    )

    print(
        "Manifest SHA256        :",
        sha256_file(
            SELFTEST_MANIFEST_PATH
        ),
    )

    print(
        "NEXT                   : "
        "CELL 31 - 7/7 AUDIT + "
        "BENCHMARK TRAINING LAUNCHER LOCK"
    )

    print(
        "=" * 128
    )


else:

    # ========================================================
    # 9. FIRST-RUN BOUNDARY
    # ========================================================

    if FINAL_BUNDLE_DIR.exists():

        orphan = (
            SELFTEST_ROOT
            / (
                "cell30_orphaned_"
                +
                datetime.now()
                .strftime(
                    "%Y%m%d_%H%M%S"
                )
            )
        )


        os.replace(
            FINAL_BUNDLE_DIR,
            orphan,
        )


        print(
            "Archived incomplete prior "
            "Cell 30 bundle to:",
            orphan,
        )


    # ========================================================
    # 10. DETERMINISTIC SYNTHETIC-ONLY SUPPORT
    #
    # Exactly 5 positives + 5 negatives so source 5-fold
    # StratifiedKFold gives one positive + one negative
    # validation sample in every fold.
    #
    # NO benchmark data.
    # ========================================================

    synthetic_amp = [

        "KRWFLIVKRWFLIVKRWFL",

        "RKWLIVFKRWLIVFKRWLI",

        "KKRWFLLIVKRWFLLIVKR",

        "RRLIVWFKRRLIVWFKRRL",

        "KWRLIFVKKWRLIFVKKWR",
    ]


    synthetic_nonamp = [

        "DENQGSTAPDENQGSTAPDE",

        "NQGSTAPDENQGSTAPDENQ",

        "GSTAPDENQGSTAPDENQGS",

        "TAPDENQGSTAPDENQGSTA",

        "APDENQGSTAPDENQGSTAP",
    ]


    synthetic_probe = [

        "ACDEFGHIKLMNPQRSTVWY",

        "YWVTSRQPNMLKIHGFEDCA",

        "KRWFLIVDENQGSTAPKRWF",

        "DENQGSTAPKRWFLIVDENQ",
    ]


    aa20 = set(
        "ACDEFGHIKLMNPQRSTVWY"
    )


    for sequence in (
        synthetic_amp
        +
        synthetic_nonamp
        +
        synthetic_probe
    ):

        assert (
            2
            <= len(
                sequence
            )
            <= 200
        )


        assert (
            set(
                sequence
            )
            .issubset(
                aa20
            )
        )


    staging_dir = Path(
        tempfile.mkdtemp(
            prefix=(
                "cell30_amplify_"
            ),
            dir=str(
                SELFTEST_ROOT
            ),
        )
    )


    try:

        def write_fasta(
            path,
            sequences,
            prefix,
        ):

            with open(
                path,
                "w",
                encoding="utf-8",
            ) as handle:

                for index, sequence in enumerate(
                    sequences,
                    1,
                ):

                    handle.write(
                        f">{prefix}_{index:03d}\n"
                        f"{sequence}\n"
                    )


        amp_train_fasta = (
            staging_dir
            / "synthetic_amp_train.fasta"
        )

        nonamp_train_fasta = (
            staging_dir
            / "synthetic_nonamp_train.fasta"
        )

        probe_fasta = (
            staging_dir
            / "synthetic_probe.fasta"
        )


        write_fasta(
            amp_train_fasta,
            synthetic_amp,
            "AMP",
        )


        write_fasta(
            nonamp_train_fasta,
            synthetic_nonamp,
            "NONAMP",
        )


        write_fasta(
            probe_fasta,
            synthetic_probe,
            "PROBE",
        )


        # ====================================================
        # 11. RUNNER EXECUTED INSIDE PAPER-COMPATIBLE ENV
        # ====================================================

        runner_path = (
            staging_dir
            / "run_amplify_v1_full_adapter_selftest.py"
        )


        runner_path.write_text(
r'''
from pathlib import Path

import importlib.util
import json
import os
import random
import sys

os.environ["KERAS_BACKEND"] = "tensorflow"
os.environ["CUDA_VISIBLE_DEVICES"] = ""
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import numpy as np
import pandas as pd
import tensorflow as tf
import keras

from Bio import SeqIO
from keras import backend as K
from keras.callbacks import EarlyStopping
from sklearn.model_selection import StratifiedKFold


SOURCE_DIR = Path(
    sys.argv[1]
).resolve()

AMP_FASTA = Path(
    sys.argv[2]
).resolve()

NONAMP_FASTA = Path(
    sys.argv[3]
).resolve()

PROBE_FASTA = Path(
    sys.argv[4]
).resolve()

OUT_DIR = Path(
    sys.argv[5]
).resolve()

RUN_SEED = int(
    sys.argv[6]
)


OUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


SRC_DIR = (
    SOURCE_DIR
    / "src"
)


sys.path.insert(
    0,
    str(
        SRC_DIR
    ),
)


assert (
    ".".join(
        str(x)
        for x in sys.version_info[:3]
    )
    ==
    "3.6.7"
)


assert (
    tf.__version__
    ==
    "1.12.0"
)


assert (
    keras.__version__
    ==
    "2.2.4"
)


assert (
    np.__version__
    ==
    "1.16.6"
)


assert (
    K.backend()
    ==
    "tensorflow"
)


# ============================================================
# MODEL RNG ONLY.
#
# Source-local:
#   random.Random(123)
#   StratifiedKFold(... random_state=50)
#
# remain unchanged below.
# ============================================================

random.seed(
    RUN_SEED
)

np.random.seed(
    RUN_SEED
)

tf.set_random_seed(
    RUN_SEED
)


session = tf.Session(
    config=tf.ConfigProto(
        intra_op_parallelism_threads=1,
        inter_op_parallelism_threads=1,
        device_count={
            "GPU":
                0
        },
    )
)


K.set_session(
    session
)


def import_from_path(
    module_name,
    path,
):

    spec = (
        importlib.util
        .spec_from_file_location(
            module_name,
            str(
                path
            ),
        )
    )


    module = (
        importlib.util
        .module_from_spec(
            spec
        )
    )


    spec.loader.exec_module(
        module
    )


    return module


train_mod = import_from_path(
    "amplify_train_v1",
    SRC_DIR
    / "train_amplify.py",
)


pred_mod = import_from_path(
    "amplify_predict_v1",
    SRC_DIR
    / "AMPlify.py",
)


assert (
    train_mod.MAX_LEN
    ==
    200
)


assert (
    pred_mod.MAX_LEN
    ==
    200
)


# ============================================================
# A. ONE-HOT + ZERO-PADDING ORACLE
# ============================================================

alphabet = (
    "ACDEFGHIKLMNPQRSTVWY"
)


train_oracle = (
    train_mod
    .one_hot_padding(
        [
            alphabet
        ],
        200,
    )
    .astype(
        np.float64
    )
)


pred_oracle = (
    pred_mod
    .one_hot_padding(
        [
            alphabet
        ],
        200,
    )
    .astype(
        np.float64
    )
)


expected_oracle = np.zeros(
    (
        1,
        200,
        20,
    ),
    dtype=np.float64,
)


expected_oracle[
    0,
    :20,
    :
] = np.eye(
    20,
    dtype=np.float64,
)


assert (
    train_oracle.shape
    ==
    (
        1,
        200,
        20,
    )
)


assert (
    pred_oracle.shape
    ==
    (
        1,
        200,
        20,
    )
)


assert (
    np.array_equal(
        train_oracle,
        pred_oracle,
    )
)


oracle_delta = float(
    np.max(
        np.abs(
            train_oracle
            -
            expected_oracle
        )
    )
)


assert (
    oracle_delta
    ==
    0.0
)


assert (
    float(
        np.abs(
            train_oracle[
                :,
                20:,
                :
            ]
        ).sum()
    )
    ==
    0.0
)


# ============================================================
# B. ARCHITECTURE ORACLE
#
# Compare official training builder and official inference
# builder from the SAME v1.0.0 commit.
# ============================================================

architecture_probe_train = (
    train_mod
    .build_model()
)


architecture_probe_pred = (
    pred_mod
    .build_amplify()
)


expected_layers = [

    "InputLayer",
    "Masking",
    "Bidirectional",
    "MultiHeadAttention",
    "Dropout",
    "Attention",
    "Dense",
]


train_layer_names = [

    layer.__class__.__name__

    for layer
    in architecture_probe_train.layers
]


pred_layer_names = [

    layer.__class__.__name__

    for layer
    in architecture_probe_pred.layers
]


assert (
    train_layer_names
    ==
    expected_layers
)


assert (
    pred_layer_names
    ==
    expected_layers
)


bidir = (
    architecture_probe_train
    .get_layer(
        "Bidirectional-LSTM"
    )
)


mha = (
    architecture_probe_train
    .get_layer(
        "Multi-Head-Attention"
    )
)


dropout_layer = (
    architecture_probe_train
    .get_layer(
        "Dropout_1"
    )
)


dense = (
    architecture_probe_train
    .get_layer(
        "Output"
    )
)


assert (
    int(
        bidir.forward_layer.units
    )
    ==
    512
)


assert (
    int(
        bidir.backward_layer.units
    )
    ==
    512
)


assert (
    abs(
        float(
            bidir.forward_layer.dropout
        )
        -
        0.5
    )
    <=
    1e-12
)


assert (
    abs(
        float(
            bidir.backward_layer.dropout
        )
        -
        0.5
    )
    <=
    1e-12
)


assert (
    bool(
        bidir.forward_layer.return_sequences
    )
    is True
)


assert (
    bool(
        bidir.backward_layer.return_sequences
    )
    is True
)


assert (
    int(
        mha.head_num
    )
    ==
    32
)


assert (
    abs(
        float(
            dropout_layer.rate
        )
        -
        0.2
    )
    <=
    1e-12
)


assert (
    int(
        dense.units
    )
    ==
    1
)


assert (
    dense.activation.__name__
    ==
    "sigmoid"
)


learning_rate = float(
    K.get_value(
        architecture_probe_train
        .optimizer
        .lr
    )
)


assert (
    abs(
        learning_rate
        -
        0.001
    )
    <=
    1e-10
)


assert (
    architecture_probe_train.loss
    ==
    "binary_crossentropy"
)


train_weight_shapes = [

    tuple(
        int(d)
        for d
        in weight.shape.as_list()
    )

    for weight
    in architecture_probe_train.weights
]


pred_weight_shapes = [

    tuple(
        int(d)
        for d
        in weight.shape.as_list()
    )

    for weight
    in architecture_probe_pred.weights
]


assert (
    train_weight_shapes
    ==
    pred_weight_shapes
)


# ============================================================
# C. SYNTHETIC DATA
#
# Preserve source:
#   random.Random(123)
#   StratifiedKFold(5, shuffle=True, random_state=50)
# ============================================================

amp_sequences = [

    str(
        record.seq
    )

    for record
    in SeqIO.parse(
        str(
            AMP_FASTA
        ),
        "fasta",
    )
]


nonamp_sequences = [

    str(
        record.seq
    )

    for record
    in SeqIO.parse(
        str(
            NONAMP_FASTA
        ),
        "fasta",
    )
]


probe_sequences = [

    str(
        record.seq
    )

    for record
    in SeqIO.parse(
        str(
            PROBE_FASTA
        ),
        "fasta",
    )
]


assert (
    len(
        amp_sequences
    )
    ==
    5
)


assert (
    len(
        nonamp_sequences
    )
    ==
    5
)


assert (
    len(
        probe_sequences
    )
    ==
    4
)


train_sequences = (
    amp_sequences
    +
    nonamp_sequences
)


y_train = np.array(
    [
        1
    ]
    * len(
        amp_sequences
    )
    +
    [
        0
    ]
    * len(
        nonamp_sequences
    ),
    dtype=np.int64,
)


train_pairs = list(
    zip(
        train_sequences,
        y_train.tolist(),
    )
)


# Exact source-local shuffle.
random.Random(
    123
).shuffle(
    train_pairs
)


train_sequences, shuffled_labels = zip(
    *train_pairs
)


train_sequences = list(
    train_sequences
)


y_train = np.asarray(
    shuffled_labels,
    dtype=np.int64,
)


X_train = (
    train_mod
    .one_hot_padding(
        train_sequences,
        200,
    )
    .astype(
        np.float32
    )
)


X_probe = (
    pred_mod
    .one_hot_padding(
        probe_sequences,
        200,
    )
    .astype(
        np.float32
    )
)


assert (
    X_train.shape
    ==
    (
        10,
        200,
        20,
    )
)


assert (
    X_probe.shape
    ==
    (
        4,
        200,
        20,
    )
)


assert (
    int(
        y_train.sum()
    )
    ==
    5
)


# Exact source fold mechanism.
splitter = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=50,
)


folds = list(
    splitter.split(
        X_train,
        y_train,
    )
)


assert (
    len(
        folds
    )
    ==
    5
)


validation_indices_all = []


for fold_index, (
    train_index,
    validation_index,
) in enumerate(
    folds,
    1,
):

    assert (
        len(
            train_index
        )
        ==
        8
    )


    assert (
        len(
            validation_index
        )
        ==
        2
    )


    assert (
        int(
            y_train[
                validation_index
            ].sum()
        )
        ==
        1
    )


    validation_indices_all.extend(
        validation_index.tolist()
    )


assert (
    sorted(
        validation_indices_all
    )
    ==
    list(
        range(
            10
        )
    )
)


assert (
    len(
        set(
            validation_indices_all
        )
    )
    ==
    10
)


# ============================================================
# D. FULL FIVE-SUBMODEL ADAPTER MECHANICS
#
# IMPORTANT:
# Production:
#   epochs = 1000
#   patience = 50
#
# This synthetic implementation self-test:
#   epochs = 1
#
# Only to exercise:
#   encoding -> 5 folds -> model fit -> save weights
#   -> official reload -> official ensemble.
#
# NO performance claim.
# ============================================================

weight_paths = []

original_probe_predictions = []

fold_records = []


for fold_number, (
    train_index,
    validation_index,
) in enumerate(
    folds,
    1,
):

    model = (
        train_mod
        .build_model()
    )


    callback = EarlyStopping(
        monitor="val_acc",
        min_delta=0.001,
        patience=50,
        restore_best_weights=True,
    )


    assert (
        callback.monitor
        ==
        "val_acc"
    )


    assert (
        int(
            callback.patience
        )
        ==
        50
    )


    assert (
        callback.restore_best_weights
        is True
    )


    history = model.fit(
        X_train[
            train_index
        ],
        y_train[
            train_index
        ],
        epochs=1,
        batch_size=32,
        validation_data=(
            X_train[
                validation_index
            ],
            y_train[
                validation_index
            ],
        ),
        verbose=0,
        initial_epoch=0,
        callbacks=[
            callback
        ],
    )


    assert (
        len(
            history.history[
                "loss"
            ]
        )
        ==
        1
    )


    probe_prediction = np.asarray(
        model.predict(
            X_probe,
            batch_size=32,
            verbose=0,
        )
    ).reshape(
        -1
    )


    assert (
        probe_prediction.shape
        ==
        (
            4,
        )
    )


    assert (
        np.all(
            np.isfinite(
                probe_prediction
            )
        )
    )


    assert (
        np.all(
            (
                probe_prediction
                >=
                0.0
            )
            &
            (
                probe_prediction
                <=
                1.0
            )
        )
    )


    weight_path = (
        OUT_DIR
        / (
            "synthetic_submodel_"
            f"weights_{fold_number}.h5"
        )
    )


    model.save_weights(
        str(
            weight_path
        )
    )


    assert (
        weight_path.is_file()
    )


    weight_paths.append(
        str(
            weight_path
        )
    )


    original_probe_predictions.append(
        probe_prediction
    )


    fold_records.append(
        {
            "fold":
                fold_number,

            "train_n":
                int(
                    len(
                        train_index
                    )
                ),

            "validation_n":
                int(
                    len(
                        validation_index
                    )
                ),

            "validation_positive":
                int(
                    y_train[
                        validation_index
                    ].sum()
                ),

            "validation_negative":
                int(
                    len(
                        validation_index
                    )
                    -
                    y_train[
                        validation_index
                    ].sum()
                ),
        }
    )


# ============================================================
# E. OFFICIAL INFERENCE LOAD + OFFICIAL ENSEMBLE
# ============================================================

loaded_models = (
    pred_mod
    .load_multi_model(
        weight_paths,
        pred_mod.build_amplify,
    )
)


assert (
    len(
        loaded_models
    )
    ==
    5
)


# ------------------------------------------------------------
# Reloaded submodel output must equal original trained output
# ------------------------------------------------------------

reload_deltas = []

reloaded_individual = []


for index, loaded_model in enumerate(
    loaded_models
):

    prediction = np.asarray(
        loaded_model.predict(
            X_probe,
            batch_size=32,
            verbose=0,
        )
    ).reshape(
        -1
    )


    reloaded_individual.append(
        prediction
    )


    delta = float(
        np.max(
            np.abs(
                prediction
                -
                original_probe_predictions[
                    index
                ]
            )
        )
    )


    reload_deltas.append(
        delta
    )


reload_max_delta = float(
    max(
        reload_deltas
    )
)


assert (
    reload_max_delta
    <=
    1e-7
)


# ------------------------------------------------------------
# Exact author ensemble()
# ------------------------------------------------------------

ensemble_probability, official_individual = (
    pred_mod
    .ensemble(
        loaded_models,
        X_probe,
    )
)


ensemble_probability = np.asarray(
    ensemble_probability,
    dtype=np.float64,
).reshape(
    -1
)


official_individual = np.asarray(
    official_individual,
    dtype=np.float64,
)


manual_individual = np.asarray(
    reloaded_individual,
    dtype=np.float64,
)


assert (
    official_individual.shape
    ==
    (
        5,
        4,
    )
)


assert (
    manual_individual.shape
    ==
    (
        5,
        4,
    )
)


individual_delta = float(
    np.max(
        np.abs(
            official_individual
            -
            manual_individual
        )
    )
)


assert (
    individual_delta
    <=
    1e-7
)


manual_mean = np.mean(
    manual_individual,
    axis=0,
)


manual_mean_delta = float(
    np.max(
        np.abs(
            ensemble_probability
            -
            manual_mean
        )
    )
)


assert (
    manual_mean_delta
    <=
    1e-7
)


# ------------------------------------------------------------
# Native author threshold
# ------------------------------------------------------------

native_class = np.asarray(
    [
        1
        if score > 0.5
        else 0

        for score
        in ensemble_probability
    ],
    dtype=np.int64,
)


assert (
    native_class.shape
    ==
    (
        4,
    )
)


# ------------------------------------------------------------
# Deterministic inference replay
# ------------------------------------------------------------

ensemble_replay, official_individual_replay = (
    pred_mod
    .ensemble(
        loaded_models,
        X_probe,
    )
)


ensemble_replay = np.asarray(
    ensemble_replay,
    dtype=np.float64,
).reshape(
    -1
)


official_individual_replay = np.asarray(
    official_individual_replay,
    dtype=np.float64,
)


replay_delta = float(
    np.max(
        np.abs(
            ensemble_probability
            -
            ensemble_replay
        )
    )
)


replay_individual_delta = float(
    np.max(
        np.abs(
            official_individual
            -
            official_individual_replay
        )
    )
)


assert (
    replay_delta
    <=
    1e-7
)


assert (
    replay_individual_delta
    <=
    1e-7
)


# ============================================================
# F. SELF-TEST PREDICTION ARTIFACT
# ============================================================

prediction_table = pd.DataFrame(
    {
        "seq_id":
            [
                f"PROBE_{i:03d}"
                for i in range(
                    1,
                    5,
                )
            ],

        "p_amp_ensemble":
            ensemble_probability,

        "pred_native_gt_0_5":
            native_class,
    }
)


for index in range(
    5
):

    prediction_table[
        f"p_amp_submodel_{index + 1}"
    ] = (
        official_individual[
            index
        ]
    )


prediction_table.to_csv(
    OUT_DIR
    / "synthetic_probe_predictions.csv",
    index=False,
)


# ============================================================
# G. RUN SUMMARY
# ============================================================

summary = {

    "python":
        ".".join(
            str(x)
            for x
            in sys.version_info[:3]
        ),

    "tensorflow":
        tf.__version__,

    "keras":
        keras.__version__,

    "numpy":
        np.__version__,

    "run_seed_for_model_rng":
        RUN_SEED,

    "source_explicit_seeds": {

        "pre_shuffle":
            123,

        "stratified_kfold":
            50,
    },

    "one_hot_oracle": {

        "shape":
            [
                1,
                200,
                20,
            ],

        "alphabet":
            alphabet,

        "max_abs_delta":
            oracle_delta,

        "train_predict_encoder_equal":
            True,

        "post_padding_zero":
            True,

        "pass":
            True,
    },

    "architecture": {

        "layers":
            train_layer_names,

        "train_predict_weight_shapes_equal":
            True,

        "bilstm_units_per_direction":
            512,

        "bilstm_output_width":
            1024,

        "lstm_dropout":
            0.5,

        "multi_head_attention_heads":
            32,

        "post_mha_dropout":
            0.2,

        "context_attention":
            True,

        "dense_units":
            1,

        "dense_activation":
            "sigmoid",

        "optimizer":
            "Adam",

        "learning_rate":
            learning_rate,

        "loss":
            "binary_crossentropy",

        "pass":
            True,
    },

    "ensemble": {

        "submodels":
            5,

        "folds":
            fold_records,

        "fold_validation_coverage_once":
            True,

        "official_individual_vs_reloaded_max_abs_delta":
            individual_delta,

        "manual_mean_max_abs_delta":
            manual_mean_delta,

        "reload_max_abs_delta":
            reload_max_delta,

        "mean_probability_min":
            float(
                ensemble_probability.min()
            ),

        "mean_probability_max":
            float(
                ensemble_probability.max()
            ),

        "native_threshold":
            0.5,

        "native_positive_rule":
            "score > 0.5",
    },

    "inference_replay": {

        "max_abs_delta":
            replay_delta,

        "individual_max_abs_delta":
            replay_individual_delta,

        "pass":
            True,
    },

    "production_recipe_locked": {

        "epoch_cap":
            1000,

        "batch_size":
            32,

        "early_stopping_monitor":
            "val_acc",

        "early_stopping_min_delta":
            0.001,

        "early_stopping_patience":
            50,

        "early_stopping_restore_best_weights":
            True,
    },

    "selftest_execution": {

        "synthetic_only":
            True,

        "epochs_per_submodel":
            1,

        "performance_claim":
            False,
    },
}


with open(
    OUT_DIR
    / "selftest_summary.json",
    "w",
    encoding="utf-8",
) as handle:

    json.dump(
        summary,
        handle,
        indent=2,
        sort_keys=True,
    )


print(
    "AMPLIFY30_JSON="
    +
    json.dumps(
        summary,
        sort_keys=True,
    )
)
''',
            encoding="utf-8",
        )


        runtime_env = (
            os.environ.copy()
        )


        runtime_env.update(
            {
                "KERAS_BACKEND":
                    "tensorflow",

                "CUDA_VISIBLE_DEVICES":
                    "",

                "OMP_NUM_THREADS":
                    "1",

                "MKL_NUM_THREADS":
                    "1",

                "OPENBLAS_NUM_THREADS":
                    "1",

                "NUMEXPR_NUM_THREADS":
                    "1",

                "TF_CPP_MIN_LOG_LEVEL":
                    "2",

                "PYTHONHASHSEED":
                    "100",
            }
        )


        run_output_dir = (
            staging_dir
            / "run"
        )


        result = run_cmd(
            [
                ENV_PYTHON,
                runner_path,
                SOURCE_DIR,
                amp_train_fasta,
                nonamp_train_fasta,
                probe_fasta,
                run_output_dir,
                "100",
            ],
            timeout=10800,
            env=runtime_env,
            label=(
                "AMPlify v1.0.0 "
                "five-submodel synthetic "
                "adapter self-test"
            ),
        )


        summary = None


        for line in (
            result.stdout
            .splitlines()
        ):

            if line.startswith(
                "AMPLIFY30_JSON="
            ):

                summary = json.loads(
                    line.split(
                        "=",
                        1,
                    )[1]
                )

                break


        assert (
            summary
            is not None
        ), (
            "AMPlify self-test runner "
            "did not emit summary marker."
        )


        assert (
            summary[
                "python"
            ]
            ==
            "3.6.7"
        )


        assert (
            summary[
                "tensorflow"
            ]
            ==
            "1.12.0"
        )


        assert (
            summary[
                "keras"
            ]
            ==
            "2.2.4"
        )


        assert (
            summary[
                "numpy"
            ]
            ==
            "1.16.6"
        )


        assert (
            summary[
                "one_hot_oracle"
            ][
                "pass"
            ]
            is True
        )


        assert (
            summary[
                "one_hot_oracle"
            ][
                "max_abs_delta"
            ]
            ==
            0.0
        )


        assert (
            summary[
                "architecture"
            ][
                "pass"
            ]
            is True
        )


        assert (
            summary[
                "architecture"
            ][
                "bilstm_units_per_direction"
            ]
            ==
            512
        )


        assert (
            summary[
                "architecture"
            ][
                "multi_head_attention_heads"
            ]
            ==
            32
        )


        assert (
            abs(
                summary[
                    "architecture"
                ][
                    "learning_rate"
                ]
                -
                0.001
            )
            <=
            1e-10
        )


        assert (
            summary[
                "ensemble"
            ][
                "submodels"
            ]
            ==
            5
        )


        assert (
            summary[
                "ensemble"
            ][
                "fold_validation_coverage_once"
            ]
            is True
        )


        assert (
            summary[
                "ensemble"
            ][
                "reload_max_abs_delta"
            ]
            <=
            1e-7
        )


        assert (
            summary[
                "ensemble"
            ][
                "manual_mean_max_abs_delta"
            ]
            <=
            1e-7
        )


        assert (
            summary[
                "inference_replay"
            ][
                "pass"
            ]
            is True
        )


        assert (
            summary[
                "production_recipe_locked"
            ][
                "epoch_cap"
            ]
            ==
            1000
        )


        assert (
            summary[
                "production_recipe_locked"
            ][
                "early_stopping_patience"
            ]
            ==
            50
        )


        assert (
            summary[
                "selftest_execution"
            ][
                "epochs_per_submodel"
            ]
            ==
            1
        )


        # ====================================================
        # 12. ATOMIC FINAL BUNDLE
        # ====================================================

        staged_bundle = (
            staging_dir
            / "final_bundle"
        )


        staged_bundle.mkdir(
            parents=True,
            exist_ok=False,
        )


        copy_map = {

            amp_train_fasta:
                "synthetic_amp_train.fasta",

            nonamp_train_fasta:
                "synthetic_nonamp_train.fasta",

            probe_fasta:
                "synthetic_probe.fasta",

            runner_path:
                "run_amplify_v1_full_adapter_selftest.py",

            (
                run_output_dir
                / "selftest_summary.json"
            ):
                "selftest_summary.json",

            (
                run_output_dir
                / "synthetic_probe_predictions.csv"
            ):
                "synthetic_probe_predictions.csv",
        }


        for fold_number in range(
            1,
            6,
        ):

            copy_map[
                (
                    run_output_dir
                    / (
                        "synthetic_submodel_"
                        f"weights_{fold_number}.h5"
                    )
                )
            ] = (
                "synthetic_submodel_"
                f"weights_{fold_number}.h5"
            )


        for source, name in (
            copy_map.items()
        ):

            assert (
                source.is_file()
            ), source


            shutil.copy2(
                source,
                staged_bundle
                / name,
            )


        assert (
            not FINAL_BUNDLE_DIR.exists()
        )


        os.replace(
            staged_bundle,
            FINAL_BUNDLE_DIR,
        )


        artifacts = {

            name:
                artifact_entry(
                    FINAL_BUNDLE_DIR
                    / name
                )

            for name
            in copy_map.values()
        }


        # ====================================================
        # 13. SELF-TEST MANIFEST
        # ====================================================

        manifest = {

            "schema_version":
                "2.0",

            "created_at":
                datetime.now()
                .astimezone()
                .isoformat(),

            "status":
                "IMPLEMENTATION_VALIDATED",

            "model_id":
                METHOD_ID,

            "implementation_validated":
                True,

            "synthetic_selftest_only":
                True,

            "benchmark_training_performed":
                False,

            "benchmark_validation_used":
                False,

            "benchmark_test_used":
                False,

            "external_target_used":
                False,

            "official_repository":
                OFFICIAL_REPOSITORY,

            "official_release_tag":
                OFFICIAL_TAG,

            "official_release_commit":
                OFFICIAL_COMMIT,

            "source_contract_sha256":
                sha256_file(
                    SOURCE_CONTRACT_PATH
                ),

            "environment_audit_sha256":
                sha256_file(
                    ENVIRONMENT_AUDIT_PATH
                ),

            "implementation_contract_sha256":
                sha256_file(
                    IMPLEMENTATION_CONTRACT_PATH
                ),

            "selftest":
                summary,

            "artifacts":
                artifacts,
        }


        # ----------------------------------------------------
        # Commit self-test BEFORE global gate mutation.
        # ----------------------------------------------------

        atomic_write_json(
            SELFTEST_MANIFEST_PATH,
            manifest,
        )


        validate_selftest_manifest(
            load_json(
                SELFTEST_MANIFEST_PATH
            )
        )


        # ====================================================
        # 14. OPEN GLOBAL GATE ONLY AFTER 7/7 EXIST
        # ====================================================

        validated, gate_after = (
            update_readiness_and_gate()
        )


        assert (
            validated
            ==
            sorted(
                PUBLISHED_IDS
            )
        )


        assert (
            gate_after[
                "open"
            ]
            is True
        )


        assert (
            gate_after[
                "benchmark_training_allowed"
            ]
            is True
        )


        # ====================================================
        # 15. FINAL REPORT
        # ====================================================

        print(
            "=" * 128
        )


        print(
            "CELL 30 PASS - "
            "AMPlify v1.0.0 OFFICIAL-SOURCE "
            "5-SUBMODEL ENSEMBLE ADAPTER "
            "SELF-TEST PASSED"
        )


        print(
            "=" * 128
        )


        print(
            "Published method       : AMPlify"
        )


        print(
            "Implementation status  : VALIDATED"
        )


        print(
            "Official tag           :",
            OFFICIAL_TAG,
        )


        print(
            "Official commit        :",
            OFFICIAL_COMMIT,
        )


        print(
            "Source contract        :",
            SOURCE_CONTRACT_ACTION,
        )


        print(
            "Environment audit      :",
            ENVIRONMENT_ACTION,
        )


        print(
            "Implementation contract:",
            IMPLEMENTATION_ACTION,
        )


        print(
            "-" * 128
        )


        print(
            "PAPER-EXACT CORE ENVIRONMENT"
        )


        print(
            "Python                 :",
            FINAL_PROBE[
                "python"
            ],
        )


        print(
            "TensorFlow             :",
            FINAL_PROBE[
                "tensorflow"
            ],
        )


        print(
            "Keras                  :",
            FINAL_PROBE[
                "keras"
            ],
        )


        print(
            "NumPy                  :",
            FINAL_PROBE[
                "numpy"
            ],
            "(compatibility pin)",
        )


        print(
            "h5py                   :",
            FINAL_PROBE[
                "h5py"
            ],
            "(compatibility pin)",
        )


        print(
            "pip check              : PASS"
        )


        print(
            "-" * 128
        )


        print(
            "SOURCE-NATIVE PIPELINE"
        )


        print(
            "One-hot input          : "
            "200 x 20 - PASS"
        )


        print(
            "Zero post-padding      : PASS"
        )


        print(
            "Masking                : "
            "0.0 - PASS"
        )


        print(
            "BiLSTM                 : "
            "512 units/direction, "
            "dropout 0.5 - PASS"
        )


        print(
            "BiLSTM output width    : "
            "1024 - PASS"
        )


        print(
            "Multi-head attention   : "
            "32 heads - PASS"
        )


        print(
            "Post-MHA dropout       : "
            "0.2 - PASS"
        )


        print(
            "Context attention      : PASS"
        )


        print(
            "Dense sigmoid          : "
            "1 unit - PASS"
        )


        print(
            "Adam learning rate     : "
            "0.001 - PASS"
        )


        print(
            "Production batch size  : "
            "32 - LOCKED"
        )


        print(
            "Production epoch cap   : "
            "1000 - LOCKED"
        )


        print(
            "Early stopping         : "
            "val_acc / min_delta 0.001 / "
            "patience 50 / restore best "
            "- LOCKED"
        )


        print(
            "Ensemble               : "
            "5 stratified submodels - PASS"
        )


        print(
            "Source pre-shuffle     : "
            "random.Random(123) - PRESERVED"
        )


        print(
            "Source fold seed       : "
            "50 - PRESERVED"
        )


        print(
            "Model benchmark seeds  : "
            "100..109 - SEPARATE"
        )


        print(
            "AMPlify partition seed : "
            "2026 - SEPARATE, NOT MODEL RNG"
        )


        print(
            "Ensemble rule          : "
            "arithmetic mean of 5 P(AMP) "
            "- PASS"
        )


        print(
            "Native threshold       : "
            "score > 0.5"
        )


        print(
            "One-hot oracle delta   :",
            summary[
                "one_hot_oracle"
            ][
                "max_abs_delta"
            ],
        )


        print(
            "Reload max |delta|     :",
            summary[
                "ensemble"
            ][
                "reload_max_abs_delta"
            ],
        )


        print(
            "Mean max |delta|       :",
            summary[
                "ensemble"
            ][
                "manual_mean_max_abs_delta"
            ],
        )


        print(
            "Inference replay       : PASS"
        )


        print(
            "Replay max |delta|     :",
            summary[
                "inference_replay"
            ][
                "max_abs_delta"
            ],
        )


        print(
            "-" * 128
        )


        print(
            "SELF-TEST SCOPE"
        )


        print(
            "Synthetic submodels    : 5"
        )


        print(
            "Epochs/submodel        : "
            "1 ONLY FOR MECHANICS SELF-TEST"
        )


        print(
            "Performance claim      : FALSE"
        )


        print(
            "Benchmark data used    : FALSE"
        )


        print(
            "Benchmark training     : FALSE"
        )


        print(
            "Benchmark validation   : FALSE"
        )


        print(
            "Benchmark test used    : FALSE"
        )


        print(
            "External target used   : FALSE"
        )


        print(
            "-" * 128
        )


        print(
            "Published validated    : 7/7"
        )


        print(
            "Validated methods      :",
            validated,
        )


        print(
            "TRAINING GATE          : OPEN"
        )


        print(
            "Benchmark training allowed "
            "from NEXT cell: TRUE"
        )


        print(
            "-" * 128
        )


        print(
            "Self-test manifest     :",
            SELFTEST_MANIFEST_PATH,
        )


        print(
            "Manifest SHA256        :",
            sha256_file(
                SELFTEST_MANIFEST_PATH
            ),
        )


        print(
            "NEXT                   : "
            "CELL 31 - 7/7 AUDIT + "
            "BENCHMARK TRAINING LAUNCHER LOCK"
        )


        print(
            "=" * 128
        )


    finally:

        if staging_dir.exists():

            shutil.rmtree(
                staging_dir,
                ignore_errors=True,
            )

================================================================================================================================
CELL 30 PASS - AMPlify v1.0.0 OFFICIAL-SOURCE 5-SUBMODEL ENSEMBLE ADAPTER SELF-TEST PASSED
================================================================================================================================
Published method       : AMPlify
Implementation status  : VALIDATED
Official tag           : v1.0.0
Official commit        : ba1f6d196873876cd53d2afb8a71938f6d1687d1
Source contract        : NEW SOURCE CONTRACT ATOMICALLY COMMITTED
Environment audit      : NEW ENVIRONMENT AUDIT ATOMICALLY COMMITTED
Implementation contract: NEW IMPLEMENTATION CONTRACT ATOMICALLY COMMITTED
--------------------------------------------------------------------------------------------------------------------------------
PAPER-EXACT CORE ENVIRONMENT
Python                 : 3.6.7
TensorFlow             : 1.12.0
Keras                  : 2.2.4
NumPy                  : 1.16.6 (compatibility pin)
h5py                   : 2.10.0 (compatibility pin)
pip check              : PASS
--------------------------------------------------------------------------------------------------------------------------------
SOURCE-NATIVE PIPELINE
One-hot input          : 200 x 20 - PASS
Zero post-padding      : PASS
Masking                : 0.0 - PASS
BiLSTM                 : 512 units/direction, dropout 0.5 - PASS
BiLSTM output width    : 1024 - PASS
Multi-head attention   : 32 heads - PASS
Post-MHA dropout       : 0.2 - PASS
Context attention      : PASS
Dense sigmoid          : 1 unit - PASS
Adam learning rate     : 0.001 - PASS
Production batch size  : 32 - LOCKED
Production epoch cap   : 1000 - LOCKED
Early stopping         : val_acc / min_delta 0.001 / patience 50 / restore best - LOCKED
Ensemble               : 5 stratified submodels - PASS
Source pre-shuffle     : random.Random(123) - PRESERVED
Source fold seed       : 50 - PRESERVED
Model benchmark seeds  : 100..109 - SEPARATE
AMPlify partition seed : 2026 - SEPARATE, NOT MODEL RNG
Ensemble rule          : arithmetic mean of 5 P(AMP) - PASS
Native threshold       : score > 0.5
One-hot oracle delta   : 0.0
Reload max |delta|     : 0.0
Mean max |delta|       : 2.384185793236071e-08
Inference replay       : PASS
Replay max |delta|     : 0.0
--------------------------------------------------------------------------------------------------------------------------------
SELF-TEST SCOPE
Synthetic submodels    : 5
Epochs/submodel        : 1 ONLY FOR MECHANICS SELF-TEST
Performance claim      : FALSE
Benchmark data used    : FALSE
Benchmark training     : FALSE
Benchmark validation   : FALSE
Benchmark test used    : FALSE
External target used   : FALSE
--------------------------------------------------------------------------------------------------------------------------------
Published validated    : 7/7
Validated methods      : ['ai4amp', 'ampep', 'ampeppy', 'ampgram', 'ampir', 'amplify', 'ampscannerv2']
TRAINING GATE          : OPEN
Benchmark training allowed from NEXT cell: TRUE
--------------------------------------------------------------------------------------------------------------------------------
Self-test manifest     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_amplify_FINAL_adapter_selftest.json
Manifest SHA256        : 0be7945c3f42b38ea5f67d36383b0f91e65ec4215edcf3b94243aabb963fc434
NEXT                   : CELL 31 - 7/7 AUDIT + BENCHMARK TRAINING LAUNCHER LOCK
================================================================================================================================

In [26]:
# ============================================================
# CELL 31 - RESTART-SAFE
# 7/7 PUBLISHED-METHOD AUDIT + FULL 680-JOB EXECUTION PLAN
# + 2040 EXTERNAL-EVALUATION PLAN + TRAINING LAUNCHER LOCK
#
# CORRECTED VERSION
#
# Fix:
# pandas default read_csv converts empty strings "" -> NaN.
# That affected exactly the 400/680 controlled-model rows whose
# selftest_manifest/selftest_sha256 are intentionally empty.
#
# This version uses lossless CSV reads:
#   keep_default_na=False
#   na_filter=False
#
# PURPOSE
# -------
# 1. Verify published-method training gate OPEN (7/7).
# 2. Re-verify all published self-test manifests/artifacts.
# 3. Re-verify controlled contracts, cache and Cell-15 plan.
# 4. Lock:
#       17 x 4 x 10 = 680 training jobs.
# 5. Lock:
#       680 x 3 = 2040 Protocol-2 external evaluations.
# 6. Initialize/reuse restart-safe mutable run ledger.
# 7. Lock production launcher for Cell 32.
#
# IMPORTANT
# ---------
# NO MODEL TRAINING IN THIS CELL.
# NO TEST RESULT INSPECTION.
# NO THRESHOLD TUNING.
# NO EXTERNAL TARGET TUNING.
# NO CHANGE TO SPLITS / SEEDS / MODELS / HYPERPARAMETERS.
# ============================================================


from pathlib import Path
from datetime import datetime

import hashlib
import json
import os
import tempfile

import numpy as np
import pandas as pd


# ============================================================
# 1. PATHS / LOCKED GLOBAL STATE
# ============================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = (
    PROJECT_ROOT
    / "benchmark17_outputs"
)

AUDIT_DIR = (
    OUTPUT_ROOT
    / "audit"
)

MANIFEST_DIR = (
    OUTPUT_ROOT
    / "manifests"
)

RESULTS_ROOT = (
    OUTPUT_ROOT
    / "results"
)

WORK_ROOT = Path(
    "/home/pc/genpept_benchmark17_work"
)

RUN_ROOT = (
    WORK_ROOT
    / "runs"
    / "benchmark4_FINAL_v1"
)

INDEX_ROOT = (
    WORK_ROOT
    / "execution_index"
    / "benchmark4_FINAL_v1"
)


for directory in [
    PROJECT_ROOT,
    OUTPUT_ROOT,
    AUDIT_DIR,
    MANIFEST_DIR,
    RESULTS_ROOT,
    WORK_ROOT,
    RUN_ROOT,
    INDEX_ROOT,
]:

    assert directory.is_dir(), (
        f"Required directory missing:\n"
        f"{directory}"
    )


BENCHMARK_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark4_FINAL_v1_manifest.json"
)

MODEL_REGISTRY_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_model_registry.json"
)

EXECUTION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_execution_contract.json"
)

EVALUATION_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_evaluation_contract.json"
)

CONTROLLED_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_controlled_model_contract.json"
)

FEATURE_CACHE_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_feature_cache_manifest.json"
)

CONTROLLED_EXECUTION_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_controlled_execution_manifest.json"
)

RUN_ARTIFACT_SCHEMA_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_run_artifact_schema.json"
)

PUBLISHED_ROUTE_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_published_method_route_contract.json"
)

TRAINING_GATE_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_gate.json"
)

PUBLISHED_READINESS_PATH = (
    AUDIT_DIR
    / "benchmark17_published_method_local_readiness_latest.csv"
)

CONTROLLED_RUN_PLAN_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_controlled_run_plan.csv"
)

WITHIN_INDEX_REGISTRY_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_within_index_registry.csv"
)

CROSS_INDEX_REGISTRY_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_cross_index_registry.csv"
)

ENVIRONMENT_AUDIT_PATH = (
    MANIFEST_DIR
    / "environment_audit.json"
)


for path in [
    BENCHMARK_MANIFEST_PATH,
    MODEL_REGISTRY_PATH,
    EXECUTION_CONTRACT_PATH,
    EVALUATION_CONTRACT_PATH,
    CONTROLLED_CONTRACT_PATH,
    FEATURE_CACHE_MANIFEST_PATH,
    CONTROLLED_EXECUTION_MANIFEST_PATH,
    RUN_ARTIFACT_SCHEMA_PATH,
    PUBLISHED_ROUTE_CONTRACT_PATH,
    TRAINING_GATE_PATH,
    PUBLISHED_READINESS_PATH,
    CONTROLLED_RUN_PLAN_PATH,
    WITHIN_INDEX_REGISTRY_PATH,
    CROSS_INDEX_REGISTRY_PATH,
    ENVIRONMENT_AUDIT_PATH,
]:

    assert path.is_file(), (
        f"Required locked artifact missing:\n"
        f"{path}"
    )


EXPECTED_ROUTE_SHA256 = (
    "dd7d6a743f088cef95fb49288dcf1801"
    "c9dc335be2656e627e7fc7f3bf7170bd"
)

EXPECTED_CELL30_AMPLIFY_SELFTEST_SHA256 = (
    "0be7945c3f42b38ea5f67d36383b0f91"
    "e65ec4215edcf3b94243aabb963fc434"
)


EXPECTED_DATASETS = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "AMPlify_balanced",
    "External_Benchmark_3",
]


EXPECTED_SEEDS = list(
    range(
        100,
        110,
    )
)


EXPECTED_CONTROLLED_IDS = [
    "logistic_regression",
    "linear_svm_calibrated",
    "random_forest",
    "extra_trees",
    "hist_gradient_boosting",
    "lightgbm",
    "cnn1d",
    "bilstm",
    "bilstm_attention",
    "transformer_encoder",
]


EXPECTED_PUBLISHED_IDS = [
    "ampep",
    "ampscannerv2",
    "ampgram",
    "ampir",
    "ampeppy",
    "ai4amp",
    "amplify",
]


EXPECTED_ALL_MODEL_IDS = (
    EXPECTED_CONTROLLED_IDS
    +
    EXPECTED_PUBLISHED_IDS
)


# ============================================================
# 2. HELPERS
# ============================================================

def sha256_file(path: Path) -> str:

    h = hashlib.sha256()

    with open(
        path,
        "rb",
    ) as f:

        for chunk in iter(
            lambda:
                f.read(
                    1024 * 1024
                ),
            b"",
        ):

            h.update(
                chunk
            )

    return h.hexdigest()


def sha256_text(text: str) -> str:

    return hashlib.sha256(
        text.encode(
            "utf-8"
        )
    ).hexdigest()


def load_json(path: Path):

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as f:

        return json.load(
            f
        )


# ------------------------------------------------------------
# IMPORTANT CELL-31 FIX
#
# Preserve "" exactly as "".
# Do NOT convert empty strings to NaN.
# ------------------------------------------------------------

def read_csv_exact(
    path: Path,
):

    return pd.read_csv(
        path,
        low_memory=False,
        keep_default_na=False,
        na_filter=False,
    )


def atomic_write_json(
    path: Path,
    payload,
):

    path = Path(
        path
    )

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    fd, tmp_name = tempfile.mkstemp(
        prefix=(
            path.name
            +
            ".tmp."
        ),
        dir=str(
            path.parent
        ),
    )


    os.close(
        fd
    )


    tmp = Path(
        tmp_name
    )


    try:

        with open(
            tmp,
            "w",
            encoding="utf-8",
            newline="\n",
        ) as f:

            json.dump(
                payload,
                f,
                indent=2,
                ensure_ascii=False,
                sort_keys=True,
            )


            f.write(
                "\n"
            )


            f.flush()


            os.fsync(
                f.fileno()
            )


        os.replace(
            tmp,
            path,
        )


    finally:

        if tmp.exists():

            tmp.unlink()


def atomic_write_csv(
    path: Path,
    df: pd.DataFrame,
):

    path = Path(
        path
    )

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    fd, tmp_name = tempfile.mkstemp(
        prefix=(
            path.name
            +
            ".tmp."
        ),
        dir=str(
            path.parent
        ),
    )


    os.close(
        fd
    )


    tmp = Path(
        tmp_name
    )


    try:

        df.to_csv(
            tmp,
            index=False,
        )


        os.replace(
            tmp,
            path,
        )


    finally:

        if tmp.exists():

            tmp.unlink()


def assert_or_create_immutable_csv(
    path: Path,
    df: pd.DataFrame,
    label: str,
):

    if path.is_file():

        # FIX:
        # preserve blank strings rather than converting them to NaN.
        old = read_csv_exact(
            path
        )


        pd.testing.assert_frame_equal(
            old.reset_index(
                drop=True
            ),
            df.reset_index(
                drop=True
            ),
            check_dtype=False,
            check_like=False,
        )


        return (
            f"EXISTING IDENTICAL "
            f"{label} VERIFIED"
        )


    atomic_write_csv(
        path,
        df,
    )


    # FIX:
    # exact CSV round-trip semantics.
    check = read_csv_exact(
        path
    )


    pd.testing.assert_frame_equal(
        check.reset_index(
            drop=True
        ),
        df.reset_index(
            drop=True
        ),
        check_dtype=False,
        check_like=False,
    )


    return (
        f"NEW {label} "
        f"ATOMICALLY COMMITTED"
    )


def assert_or_create_immutable_json(
    path: Path,
    status: str,
    core_key: str,
    core_payload,
    label: str,
):

    if path.is_file():

        old = load_json(
            path
        )


        assert (
            old[
                "status"
            ]
            ==
            status
        )


        assert (
            old[
                core_key
            ]
            ==
            core_payload
        ), (
            f"Existing {label} differs. "
            f"Refusing silent overwrite."
        )


        return (
            f"EXISTING IDENTICAL "
            f"{label} VERIFIED"
        )


    payload = {

        "created_at":
            datetime.now()
            .astimezone()
            .isoformat(),

        "status":
            status,

        core_key:
            core_payload,
    }


    atomic_write_json(
        path,
        payload,
    )


    check = load_json(
        path
    )


    assert (
        check[
            "status"
        ]
        ==
        status
    )


    assert (
        check[
            core_key
        ]
        ==
        core_payload
    )


    return (
        f"NEW {label} "
        f"ATOMICALLY COMMITTED"
    )


def boolish(value):

    if isinstance(
        value,
        (
            bool,
            np.bool_,
        ),
    ):

        return bool(
            value
        )


    text = (
        str(
            value
        )
        .strip()
        .lower()
    )


    if text in {
        "true",
        "1",
        "yes",
    }:

        return True


    if text in {
        "false",
        "0",
        "no",
    }:

        return False


    raise AssertionError(
        f"Cannot interpret bool value: "
        f"{value!r}"
    )


def manifest_model_id(
    payload,
):

    return (

        payload.get(
            "model_id"
        )

        or

        payload.get(
            "adapter_contract",
            {},
        ).get(
            "model_id"
        )

        or

        payload.get(
            "contract",
            {},
        ).get(
            "model_id"
        )
    )


def verify_committed_artifact_entry(
    entry,
    model_id,
    artifact_name,
):

    if not isinstance(
        entry,
        dict,
    ):

        return


    if (
        "path"
        not in entry
        or
        "sha256"
        not in entry
    ):

        return


    artifact_path = Path(
        entry[
            "path"
        ]
    )


    assert (
        artifact_path.is_file()
    ), (
        f"{model_id}: committed artifact "
        f"missing: {artifact_name}\n"
        f"{artifact_path}"
    )


    observed = sha256_file(
        artifact_path
    )


    assert (
        observed
        ==
        str(
            entry[
                "sha256"
            ]
        )
    ), (
        f"{model_id}: artifact hash mismatch: "
        f"{artifact_name}\n"
        f"Expected: {entry['sha256']}\n"
        f"Actual  : {observed}"
    )


    if (
        "size_bytes"
        in entry
    ):

        assert (
            int(
                artifact_path
                .stat()
                .st_size
            )
            ==
            int(
                entry[
                    "size_bytes"
                ]
            )
        )


# ============================================================
# 3. GLOBAL CONTRACT / COUNT AUDIT
# ============================================================

assert (
    sha256_file(
        PUBLISHED_ROUTE_CONTRACT_PATH
    )
    ==
    EXPECTED_ROUTE_SHA256
)


benchmark_manifest = load_json(
    BENCHMARK_MANIFEST_PATH
)

model_registry = load_json(
    MODEL_REGISTRY_PATH
)

execution_contract = load_json(
    EXECUTION_CONTRACT_PATH
)

evaluation_contract = load_json(
    EVALUATION_CONTRACT_PATH
)

controlled_payload = load_json(
    CONTROLLED_CONTRACT_PATH
)

feature_cache_manifest = load_json(
    FEATURE_CACHE_MANIFEST_PATH
)

controlled_execution = load_json(
    CONTROLLED_EXECUTION_MANIFEST_PATH
)

artifact_schema = load_json(
    RUN_ARTIFACT_SCHEMA_PATH
)

route_payload = load_json(
    PUBLISHED_ROUTE_CONTRACT_PATH
)

training_gate = load_json(
    TRAINING_GATE_PATH
)


assert (
    benchmark_manifest[
        "datasets"
    ]
    ==
    EXPECTED_DATASETS
)


assert (
    benchmark_manifest[
        "model_seeds"
    ]
    ==
    EXPECTED_SEEDS
)


assert (
    benchmark_manifest[
        "protocol_2"
    ][
        "n_directional_pairs"
    ]
    ==
    12
)


assert (
    benchmark_manifest[
        "protocol_2"
    ][
        "residual_exact_overlap_all_pairs"
    ]
    ==
    0
)


assert (
    model_registry[
        "n_models"
    ]
    ==
    17
)


registry_rows = (
    model_registry[
        "models"
    ]
)


registry_ids = [

    row[
        "model_id"
    ]

    for row
    in registry_rows
]


assert (
    registry_ids
    ==
    EXPECTED_ALL_MODEL_IDS
)


controlled_rows = [

    row

    for row
    in registry_rows

    if (
        row[
            "group"
        ]
        ==
        "controlled_baseline"
    )
]


published_rows = [

    row

    for row
    in registry_rows

    if (
        row[
            "group"
        ]
        ==
        "published_amp_method"
    )
]


assert (
    [
        row[
            "model_id"
        ]

        for row
        in controlled_rows
    ]
    ==
    EXPECTED_CONTROLLED_IDS
)


assert (
    [
        row[
            "model_id"
        ]

        for row
        in published_rows
    ]
    ==
    EXPECTED_PUBLISHED_IDS
)


assert (
    controlled_payload[
        "status"
    ]
    ==
    "CONTROLLED_MODELS_LOCKED_BEFORE_TRAINING"
)


controlled_contract = (
    controlled_payload[
        "contract"
    ]
)


assert (
    controlled_contract[
        "controlled_model_ids"
    ]
    ==
    EXPECTED_CONTROLLED_IDS
)


assert (
    controlled_contract[
        "model_seeds"
    ]
    ==
    EXPECTED_SEEDS
)


assert (
    controlled_contract[
        "training_started"
    ]
    is False
)


assert (
    evaluation_contract[
        "status"
    ]
    ==
    "LOCKED_BEFORE_MODEL_TRAINING"
)


assert (
    evaluation_contract[
        "model_seeds"
    ]
    ==
    EXPECTED_SEEDS
)


assert (
    execution_contract[
        "contract"
    ][
        "protocol_1"
    ][
        "training_runs"
    ]
    ==
    680
)


assert (
    execution_contract[
        "contract"
    ][
        "protocol_2"
    ][
        "external_evaluations"
    ]
    ==
    2040
)


assert (
    controlled_execution[
        "status"
    ]
    ==
    "CONTROLLED_EXECUTION_INFRASTRUCTURE_LOCKED"
)


assert (
    controlled_execution[
        "training_started"
    ]
    is False
)


assert (
    controlled_execution[
        "controlled_training_jobs"
    ]
    ==
    400
)


assert (
    controlled_execution[
        "controlled_external_evaluations"
    ]
    ==
    1200
)


assert (
    controlled_execution[
        "all_17_training_jobs_eventually"
    ]
    ==
    680
)


assert (
    controlled_execution[
        "all_17_external_evaluations_eventually"
    ]
    ==
    2040
)


assert (
    artifact_schema[
        "status"
    ]
    ==
    "LOCKED_BEFORE_MODEL_TRAINING"
)


route_core = (
    route_payload[
        "contract"
    ]
)


assert (
    route_payload[
        "status"
    ]
    ==
    "PUBLISHED_METHOD_ROUTES_LOCKED_BEFORE_TRAINING"
)


assert (
    route_payload[
        "restart_safe"
    ]
    is True
)


assert (
    route_core[
        "published_model_ids"
    ]
    ==
    EXPECTED_PUBLISHED_IDS
)


assert (
    route_core[
        "model_seeds"
    ]
    ==
    EXPECTED_SEEDS
)


assert (
    route_core[
        "n_published_models"
    ]
    ==
    7
)


# ============================================================
# 4. 7/7 TRAINING-GATE AUDIT
# ============================================================

assert (
    training_gate[
        "open"
    ]
    is True
)


assert (
    training_gate[
        "benchmark_training_allowed"
    ]
    is True
)


assert (
    training_gate[
        "published_methods_total"
    ]
    ==
    7
)


assert (
    training_gate[
        "required_for_open"
    ]
    ==
    7
)


assert (
    training_gate[
        "published_methods_implementation_validated"
    ]
    ==
    7
)


assert (
    sorted(
        training_gate[
            "validated_methods"
        ]
    )
    ==
    sorted(
        EXPECTED_PUBLISHED_IDS
    )
)


readiness = read_csv_exact(
    PUBLISHED_READINESS_PATH
)


required_readiness_columns = {

    "model_id",
    "adapter_self_test_passed",
    "implementation_validated",
    "local_state",
    "training_allowed",
}


assert (
    required_readiness_columns
    .issubset(
        readiness.columns
    )
)


assert (
    set(
        readiness[
            "model_id"
        ]
        .astype(
            str
        )
    )
    ==
    set(
        EXPECTED_PUBLISHED_IDS
    )
)


assert (
    len(
        readiness
    )
    ==
    7
)


for model_id in (
    EXPECTED_PUBLISHED_IDS
):

    row = readiness.loc[
        readiness[
            "model_id"
        ]
        .astype(
            str
        )
        .eq(
            model_id
        )
    ]


    assert (
        len(
            row
        )
        ==
        1
    )


    row = row.iloc[
        0
    ]


    assert (
        boolish(
            row[
                "adapter_self_test_passed"
            ]
        )
        is True
    )


    assert (
        boolish(
            row[
                "implementation_validated"
            ]
        )
        is True
    )


    assert (
        boolish(
            row[
                "training_allowed"
            ]
        )
        is True
    )


    assert (
        str(
            row[
                "local_state"
            ]
        )
        ==
        "IMPLEMENTATION_VALIDATED"
    )


# ============================================================
# 5. RE-VERIFY ALL 7 PUBLISHED SELF-TEST CLOSURES
# ============================================================

published_closure_rows = []

published_selftest_sha = {}

published_bundle_sha = {}


for model_id in (
    EXPECTED_PUBLISHED_IDS
):

    selftest_path = (
        MANIFEST_DIR
        /
        (
            f"benchmark17_{model_id}_"
            f"FINAL_adapter_selftest.json"
        )
    )


    assert (
        selftest_path.is_file()
    ), (
        f"Missing self-test manifest: "
        f"{selftest_path}"
    )


    selftest_sha = sha256_file(
        selftest_path
    )


    if (
        model_id
        ==
        "amplify"
    ):

        assert (
            selftest_sha
            ==
            EXPECTED_CELL30_AMPLIFY_SELFTEST_SHA256
        ), (
            "Cell 30 AMPlify manifest "
            "changed after PASS."
        )


    payload = load_json(
        selftest_path
    )


    assert (
        payload.get(
            "implementation_validated"
        )
        is True
    )


    assert (
        manifest_model_id(
            payload
        )
        ==
        model_id
    )


    if (
        "status"
        in payload
    ):

        assert (
            payload[
                "status"
            ]
            ==
            "IMPLEMENTATION_VALIDATED"
        )


    if (
        "benchmark_training_performed"
        in payload
    ):

        assert (
            payload[
                "benchmark_training_performed"
            ]
            is False
        )


    if (
        "benchmark_test_used"
        in payload
    ):

        assert (
            payload[
                "benchmark_test_used"
            ]
            is False
        )


    if (
        "external_target_used"
        in payload
    ):

        assert (
            payload[
                "external_target_used"
            ]
            is False
        )


    for artifact_name, entry in (
        payload.get(
            "artifacts",
            {},
        ).items()
    ):

        verify_committed_artifact_entry(
            entry,
            model_id,
            artifact_name,
        )


    closure_bundle_hash = sha256_text(
        EXPECTED_ROUTE_SHA256
        +
        "\n"
        +
        selftest_sha
        +
        "\n"
    )


    published_selftest_sha[
        model_id
    ] = (
        selftest_sha
    )


    published_bundle_sha[
        model_id
    ] = (
        closure_bundle_hash
    )


    route = (
        route_core[
            "methods"
        ][
            model_id
        ]
    )


    assert (
        route[
            "ten_independent_retraining_runs"
        ]
        is True
    )


    assert (
        route[
            "pretrained_repeated_inference_allowed"
        ]
        is False
    )


    assert (
        route[
            "config_lock_required_before_training"
        ]
        is True
    )


    published_closure_rows.append(
        {
            "model_id":
                model_id,

            "display_name":
                route[
                    "display_name"
                ],

            "locked_route":
                route[
                    "locked_route"
                ],

            "implementation_environment":
                route[
                    "implementation_environment"
                ],

            "selftest_manifest":
                str(
                    selftest_path
                ),

            "selftest_sha256":
                selftest_sha,

            "method_closure_bundle_sha256":
                closure_bundle_hash,
        }
    )


published_closure_df = pd.DataFrame(
    published_closure_rows
)


assert (
    published_closure_df[
        "model_id"
    ].tolist()
    ==
    EXPECTED_PUBLISHED_IDS
)


assert (
    len(
        published_closure_df
    )
    ==
    7
)


# ============================================================
# 6. VERIFY CELL-15 CONTROLLED PLAN / EXECUTION INDEX
# ============================================================

controlled_plan = read_csv_exact(
    CONTROLLED_RUN_PLAN_PATH
)


assert (
    len(
        controlled_plan
    )
    ==
    400
)


assert (
    controlled_plan[
        "run_id"
    ].is_unique
)


assert (
    controlled_plan[
        "model_id"
    ]
    .drop_duplicates()
    .tolist()
    ==
    EXPECTED_CONTROLLED_IDS
)


assert (
    pd.to_numeric(
        controlled_plan[
            "seed"
        ],
        errors="raise",
    )
    .drop_duplicates()
    .astype(
        int
    )
    .tolist()
    ==
    EXPECTED_SEEDS
)


assert (
    pd.to_numeric(
        controlled_plan[
            "n_external_targets"
        ],
        errors="raise",
    )
    .eq(
        3
    )
    .all()
)


expected_controlled_plan_sha = (
    controlled_execution[
        "run_plan"
    ][
        "sha256"
    ]
)


assert (
    sha256_file(
        CONTROLLED_RUN_PLAN_PATH
    )
    ==
    expected_controlled_plan_sha
)


index_cache_path = Path(
    controlled_execution[
        "index_cache"
    ][
        "path"
    ]
)


assert (
    index_cache_path.is_file()
)


assert (
    sha256_file(
        index_cache_path
    )
    ==
    controlled_execution[
        "index_cache"
    ][
        "sha256"
    ]
)


assert (
    controlled_execution[
        "index_cache"
    ][
        "n_within_arrays"
    ]
    ==
    12
)


assert (
    controlled_execution[
        "index_cache"
    ][
        "n_cross_target_arrays"
    ]
    ==
    12
)


within_registry = read_csv_exact(
    WITHIN_INDEX_REGISTRY_PATH
)


cross_registry = read_csv_exact(
    CROSS_INDEX_REGISTRY_PATH
)


assert (
    len(
        within_registry
    )
    ==
    12
)


assert (
    len(
        cross_registry
    )
    ==
    12
)


assert (
    pd.to_numeric(
        cross_registry[
            "residual_exact_overlap"
        ],
        errors="raise",
    )
    .eq(
        0
    )
    .all()
)


assert (
    int(
        pd.to_numeric(
            cross_registry[
                "minority_class_n"
            ],
            errors="raise",
        ).min()
    )
    ==
    309
)


within_lookup = {

    (
        str(
            row.dataset
        ),
        str(
            row.split
        ),
    ):
        row

    for row
    in within_registry.itertuples(
        index=False
    )
}


cross_lookup = {

    (
        str(
            row.source_dataset
        ),
        str(
            row.target_dataset
        ),
    ):
        row

    for row
    in cross_registry.itertuples(
        index=False
    )
}


with np.load(
    index_cache_path,
    allow_pickle=False,
) as indices:

    index_keys = set(
        indices.files
    )


    assert (
        len(
            index_keys
        )
        ==
        24
    )


    for dataset in (
        EXPECTED_DATASETS
    ):

        for split in [
            "train",
            "validation",
            "test",
        ]:

            key = (
                f"within__{dataset}__{split}"
            )


            assert (
                key
                in index_keys
            )


            row = (
                within_lookup[
                    (
                        dataset,
                        split,
                    )
                ]
            )


            assert (
                len(
                    indices[
                        key
                    ]
                )
                ==
                int(
                    row.n
                )
            )


    for source in (
        EXPECTED_DATASETS
    ):

        for target in (
            EXPECTED_DATASETS
        ):

            if (
                source
                ==
                target
            ):

                continue


            key = (
                f"cross__{source}"
                f"__TO__{target}"
                f"__target_test"
            )


            assert (
                key
                in index_keys
            )


            row = (
                cross_lookup[
                    (
                        source,
                        target,
                    )
                ]
            )


            assert (
                len(
                    indices[
                        key
                    ]
                )
                ==
                int(
                    row.n
                )
            )


# ============================================================
# 7. BUILD IMMUTABLE FULL 680-JOB PLAN
# ============================================================

registry_by_id = {

    row[
        "model_id"
    ]:
        row

    for row
    in registry_rows
}


controlled_lookup = {

    (
        str(
            row.model_id
        ),
        str(
            row.source_dataset
        ),
        int(
            row.seed
        ),
    ):
        row

    for row
    in controlled_plan.itertuples(
        index=False
    )
}


full_rows = []

job_no = 0


for model_id in (
    EXPECTED_ALL_MODEL_IDS
):

    registry_row = (
        registry_by_id[
            model_id
        ]
    )


    model_group = str(
        registry_row[
            "group"
        ]
    )


    if (
        model_id
        in EXPECTED_CONTROLLED_IDS
    ):

        implementation_route = str(
            registry_row[
                "implementation_route"
            ]
        )


        implementation_environment = (
            "master_environment_from_Cell2"
        )


        closure_manifest = str(
            CONTROLLED_CONTRACT_PATH
        )


        closure_sha = sha256_file(
            CONTROLLED_CONTRACT_PATH
        )


        selftest_manifest = ""

        selftest_sha = ""


    else:

        route = (
            route_core[
                "methods"
            ][
                model_id
            ]
        )


        implementation_route = str(
            route[
                "locked_route"
            ]
        )


        implementation_environment = str(
            route[
                "implementation_environment"
            ]
        )


        closure_manifest = str(
            MANIFEST_DIR
            /
            (
                f"benchmark17_{model_id}_"
                f"FINAL_adapter_selftest.json"
            )
        )


        closure_sha = (
            published_bundle_sha[
                model_id
            ]
        )


        selftest_manifest = (
            closure_manifest
        )


        selftest_sha = (
            published_selftest_sha[
                model_id
            ]
        )


    for source_dataset in (
        EXPECTED_DATASETS
    ):

        train_key = (
            f"within__{source_dataset}__train"
        )


        validation_key = (
            f"within__{source_dataset}__validation"
        )


        source_test_key = (
            f"within__{source_dataset}__test"
        )


        train_n = int(
            within_lookup[
                (
                    source_dataset,
                    "train",
                )
            ].n
        )


        validation_n = int(
            within_lookup[
                (
                    source_dataset,
                    "validation",
                )
            ].n
        )


        source_test_n = int(
            within_lookup[
                (
                    source_dataset,
                    "test",
                )
            ].n
        )


        external_targets = [

            target

            for target
            in EXPECTED_DATASETS

            if (
                target
                !=
                source_dataset
            )
        ]


        assert (
            len(
                external_targets
            )
            ==
            3
        )


        for seed in (
            EXPECTED_SEEDS
        ):

            job_no += 1


            run_id = (
                f"{model_id}__"
                f"{source_dataset}__"
                f"seed_{seed:03d}"
            )


            run_dir = (
                RUN_ROOT
                / model_id
                / source_dataset
                / f"seed_{seed:03d}"
            )


            full_rows.append(
                {
                    "job_no":
                        int(
                            job_no
                        ),

                    "run_id":
                        run_id,

                    "model_id":
                        model_id,

                    "model_group":
                        model_group,

                    "implementation_route":
                        implementation_route,

                    "implementation_environment":
                        implementation_environment,

                    "source_dataset":
                        source_dataset,

                    "seed":
                        int(
                            seed
                        ),

                    "train_index_key":
                        train_key,

                    "validation_index_key":
                        validation_key,

                    "source_test_index_key":
                        source_test_key,

                    "train_n":
                        train_n,

                    "validation_n":
                        validation_n,

                    "source_test_n":
                        source_test_n,

                    "external_target_1":
                        external_targets[
                            0
                        ],

                    "external_target_2":
                        external_targets[
                            1
                        ],

                    "external_target_3":
                        external_targets[
                            2
                        ],

                    "n_external_targets":
                        3,

                    "run_dir":
                        str(
                            run_dir
                        ),

                    "closure_manifest":
                        closure_manifest,

                    "closure_sha256":
                        closure_sha,

                    "selftest_manifest":
                        selftest_manifest,

                    "selftest_sha256":
                        selftest_sha,
                }
            )


full_plan = pd.DataFrame(
    full_rows
)


assert (
    len(
        full_plan
    )
    ==
    680
)


assert (
    full_plan[
        "run_id"
    ].is_unique
)


assert (
    full_plan[
        "job_no"
    ].tolist()
    ==
    list(
        range(
            1,
            681,
        )
    )
)


assert (
    full_plan[
        "model_id"
    ]
    .drop_duplicates()
    .tolist()
    ==
    EXPECTED_ALL_MODEL_IDS
)


assert (
    full_plan[
        "seed"
    ]
    .drop_duplicates()
    .tolist()
    ==
    EXPECTED_SEEDS
)


assert (
    full_plan[
        "n_external_targets"
    ]
    .eq(
        3
    )
    .all()
)


assert (
    full_plan
    .groupby(
        [
            "model_id",
            "source_dataset",
        ]
    )
    .size()
    .eq(
        10
    )
    .all()
)


assert (
    full_plan
    .groupby(
        "model_id"
    )
    .size()
    .eq(
        40
    )
    .all()
)


# ------------------------------------------------------------
# Explicitly verify the intentional blank fields.
#
# Controlled models:
#   10 models x 4 datasets x 10 seeds = 400 rows
#   have no published self-test manifest.
#
# Published:
#   7 x 4 x 10 = 280 rows
#   must have a self-test manifest.
#
# This is exactly the 58.82353% seen in the previous failure.
# ------------------------------------------------------------

controlled_blank_count = int(
    full_plan[
        "selftest_manifest"
    ]
    .eq(
        ""
    )
    .sum()
)


published_nonblank_count = int(
    full_plan[
        "selftest_manifest"
    ]
    .ne(
        ""
    )
    .sum()
)


assert (
    controlled_blank_count
    ==
    400
)


assert (
    published_nonblank_count
    ==
    280
)


assert (
    controlled_blank_count
    /
    len(
        full_plan
    )
    ==
    400
    /
    680
)


controlled_full = (
    full_plan.loc[
        full_plan[
            "model_id"
        ].isin(
            EXPECTED_CONTROLLED_IDS
        )
    ]
    .copy()
)


assert (
    len(
        controlled_full
    )
    ==
    400
)


# ------------------------------------------------------------
# Verify original Cell-15 controlled rows preserved exactly.
# ------------------------------------------------------------

for old in (
    controlled_plan.itertuples(
        index=False
    )
):

    key = (
        str(
            old.model_id
        ),
        str(
            old.source_dataset
        ),
        int(
            old.seed
        ),
    )


    assert (
        key
        in controlled_lookup
    )


    new = controlled_full.loc[
        controlled_full[
            "run_id"
        ]
        .astype(
            str
        )
        .eq(
            str(
                old.run_id
            )
        )
    ]


    assert (
        len(
            new
        )
        ==
        1
    )


    new = new.iloc[
        0
    ]


    for column in (
        controlled_plan.columns
    ):

        if (
            column
            ==
            "job_no"
        ):

            continue


        old_value = getattr(
            old,
            column
        )


        new_value = (
            new[
                column
            ]
        )


        assert (
            str(
                old_value
            )
            ==
            str(
                new_value
            )
        ), (
            f"Controlled plan drift in "
            f"{old.run_id}: {column}\n"
            f"old={old_value!r} "
            f"new={new_value!r}"
        )


published_full = (
    full_plan.loc[
        full_plan[
            "model_id"
        ].isin(
            EXPECTED_PUBLISHED_IDS
        )
    ]
    .copy()
)


assert (
    len(
        published_full
    )
    ==
    280
)


assert (
    published_full
    .groupby(
        "model_id"
    )
    .size()
    .eq(
        40
    )
    .all()
)


assert (
    published_full[
        "selftest_manifest"
    ]
    .ne(
        ""
    )
    .all()
)


assert (
    published_full[
        "selftest_sha256"
    ]
    .ne(
        ""
    )
    .all()
)


# ============================================================
# 8. BUILD IMMUTABLE 2040 EXTERNAL-EVALUATION PLAN
# ============================================================

external_rows = []

eval_no = 0


for run in (
    full_plan.itertuples(
        index=False
    )
):

    for target_dataset in [

        run.external_target_1,
        run.external_target_2,
        run.external_target_3,

    ]:

        eval_no += 1


        cross_row = (
            cross_lookup[
                (
                    str(
                        run.source_dataset
                    ),
                    str(
                        target_dataset
                    ),
                )
            ]
        )


        target_index_key = (
            f"cross__{run.source_dataset}"
            f"__TO__{target_dataset}"
            f"__target_test"
        )


        external_rows.append(
            {
                "eval_no":
                    int(
                        eval_no
                    ),

                "run_id":
                    str(
                        run.run_id
                    ),

                "model_id":
                    str(
                        run.model_id
                    ),

                "model_group":
                    str(
                        run.model_group
                    ),

                "source_dataset":
                    str(
                        run.source_dataset
                    ),

                "target_dataset":
                    str(
                        target_dataset
                    ),

                "seed":
                    int(
                        run.seed
                    ),

                "target_index_key":
                    target_index_key,

                "target_n":
                    int(
                        cross_row.n
                    ),

                "target_AMP":
                    int(
                        cross_row.AMP
                    ),

                "target_non_AMP":
                    int(
                        cross_row.non_AMP
                    ),

                "minority_class_n":
                    int(
                        cross_row.minority_class_n
                    ),

                "residual_exact_overlap":
                    int(
                        cross_row.residual_exact_overlap
                    ),

                "threshold_source":
                    "source_validation_only",

                "target_threshold_tuning":
                    False,

                "target_retraining":
                    False,

                "run_dir":
                    str(
                        run.run_dir
                    ),

                "external_dir":
                    str(
                        Path(
                            run.run_dir
                        )
                        / "external"
                        / str(
                            target_dataset
                        )
                    ),
            }
        )


external_plan = pd.DataFrame(
    external_rows
)


assert (
    len(
        external_plan
    )
    ==
    2040
)


assert (
    external_plan[
        "eval_no"
    ].tolist()
    ==
    list(
        range(
            1,
            2041,
        )
    )
)


assert (
    external_plan
    .groupby(
        "run_id"
    )
    .size()
    .eq(
        3
    )
    .all()
)


assert (
    external_plan[
        "residual_exact_overlap"
    ]
    .eq(
        0
    )
    .all()
)


assert (
    external_plan[
        "minority_class_n"
    ]
    .ge(
        309
    )
    .all()
)


assert (
    external_plan[
        "target_threshold_tuning"
    ]
    .eq(
        False
    )
    .all()
)


assert (
    external_plan[
        "target_retraining"
    ]
    .eq(
        False
    )
    .all()
)


# ============================================================
# 9. IMMUTABLE OUTPUTS
# ============================================================

PUBLISHED_CLOSURE_AUDIT_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_published_7of7_closure_audit.csv"
)

FULL_RUN_PLAN_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_full_680_run_plan.csv"
)

EXTERNAL_EVAL_PLAN_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_external_2040_eval_plan.csv"
)


PUBLISHED_CLOSURE_ACTION = (
    assert_or_create_immutable_csv(
        PUBLISHED_CLOSURE_AUDIT_PATH,
        published_closure_df,
        "7/7 PUBLISHED CLOSURE AUDIT",
    )
)


FULL_PLAN_ACTION = (
    assert_or_create_immutable_csv(
        FULL_RUN_PLAN_PATH,
        full_plan,
        "680-JOB FULL RUN PLAN",
    )
)


EXTERNAL_PLAN_ACTION = (
    assert_or_create_immutable_csv(
        EXTERNAL_EVAL_PLAN_PATH,
        external_plan,
        "2040-ROW EXTERNAL EVALUATION PLAN",
    )
)


FULL_PLAN_SHA256 = sha256_file(
    FULL_RUN_PLAN_PATH
)


EXTERNAL_PLAN_SHA256 = sha256_file(
    EXTERNAL_EVAL_PLAN_PATH
)


PUBLISHED_CLOSURE_SHA256 = sha256_file(
    PUBLISHED_CLOSURE_AUDIT_PATH
)


# ============================================================
# 10. MUTABLE RESTART-SAFE RUN LEDGER
# ============================================================

RUN_LEDGER_PATH = (
    AUDIT_DIR
    / "benchmark17_FINAL_run_ledger.csv"
)


LEDGER_IDENTITY_COLUMNS = [
    "job_no",
    "run_id",
    "model_id",
    "model_group",
    "source_dataset",
    "seed",
]


LEDGER_COLUMNS = (
    LEDGER_IDENTITY_COLUMNS
    +
    [
        "status",
        "attempt_count",
        "started_at",
        "finished_at",
        "run_manifest",
        "last_error",
    ]
)


ALLOWED_LEDGER_STATUS = {
    "PLANNED",
    "RUNNING",
    "TRAINED",
    "EVALUATED",
    "COMPLETE",
    "FAILED",
}


if RUN_LEDGER_PATH.is_file():

    ledger = read_csv_exact(
        RUN_LEDGER_PATH
    )


    assert (
        list(
            ledger.columns
        )
        ==
        LEDGER_COLUMNS
    )


    assert (
        len(
            ledger
        )
        ==
        680
    )


    assert (
        ledger[
            "run_id"
        ].is_unique
    )


    expected_identity = (
        full_plan[
            LEDGER_IDENTITY_COLUMNS
        ]
        .copy()
    )


    observed_identity = (
        ledger[
            LEDGER_IDENTITY_COLUMNS
        ]
        .copy()
    )


    pd.testing.assert_frame_equal(
        observed_identity.reset_index(
            drop=True
        ),
        expected_identity.reset_index(
            drop=True
        ),
        check_dtype=False,
    )


    assert (
        set(
            ledger[
                "status"
            ]
            .astype(
                str
            )
        )
        .issubset(
            ALLOWED_LEDGER_STATUS
        )
    )


    assert (
        pd.to_numeric(
            ledger[
                "attempt_count"
            ],
            errors="raise",
        )
        .ge(
            0
        )
        .all()
    )


    LEDGER_ACTION = (
        "EXISTING RUN LEDGER "
        "VERIFIED WITHOUT RESET"
    )


else:

    ledger = (
        full_plan[
            LEDGER_IDENTITY_COLUMNS
        ]
        .copy()
    )


    ledger[
        "status"
    ] = (
        "PLANNED"
    )


    ledger[
        "attempt_count"
    ] = (
        0
    )


    ledger[
        "started_at"
    ] = (
        ""
    )


    ledger[
        "finished_at"
    ] = (
        ""
    )


    ledger[
        "run_manifest"
    ] = (
        ""
    )


    ledger[
        "last_error"
    ] = (
        ""
    )


    ledger = ledger[
        LEDGER_COLUMNS
    ]


    atomic_write_csv(
        RUN_LEDGER_PATH,
        ledger,
    )


    check = read_csv_exact(
        RUN_LEDGER_PATH
    )


    pd.testing.assert_frame_equal(
        check.reset_index(
            drop=True
        ),
        ledger.reset_index(
            drop=True
        ),
        check_dtype=False,
    )


    LEDGER_ACTION = (
        "NEW 680-ROW RUN LEDGER "
        "ATOMICALLY INITIALIZED"
    )


# ============================================================
# 11. LOCK PRODUCTION-LAUNCHER CONTRACT
# ============================================================

LAUNCHER_CONTRACT_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_training_launcher_contract.json"
)


FULL_EXECUTION_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_full_execution_manifest.json"
)


controlled_contract_sha = (
    sha256_file(
        CONTROLLED_CONTRACT_PATH
    )
)


feature_cache_manifest_sha = (
    sha256_file(
        FEATURE_CACHE_MANIFEST_PATH
    )
)


evaluation_contract_sha = (
    sha256_file(
        EVALUATION_CONTRACT_PATH
    )
)


execution_contract_sha = (
    sha256_file(
        EXECUTION_CONTRACT_PATH
    )
)


model_registry_sha = (
    sha256_file(
        MODEL_REGISTRY_PATH
    )
)


benchmark_manifest_sha = (
    sha256_file(
        BENCHMARK_MANIFEST_PATH
    )
)


artifact_schema_sha = (
    sha256_file(
        RUN_ARTIFACT_SCHEMA_PATH
    )
)


environment_audit_sha = (
    sha256_file(
        ENVIRONMENT_AUDIT_PATH
    )
)


index_cache_sha = (
    sha256_file(
        index_cache_path
    )
)


LAUNCHER_CORE = {

    "schema_version":
        "1.0",

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "status":
        "READY_TO_LAUNCH_FINAL_17_MODEL_BENCHMARK",

    "training_gate_open":
        True,

    "published_methods_validated":
        7,

    "controlled_models":
        10,

    "published_models":
        7,

    "total_models":
        17,

    "datasets":
        EXPECTED_DATASETS,

    "model_seeds":
        EXPECTED_SEEDS,

    "protocol_1_training_jobs":
        680,

    "protocol_2_external_evaluations":
        2040,

    "additional_protocol2_training_jobs":
        0,

    "source_training_reused_for_three_targets":
        True,

    "training_scope": {

        "fit_rows":
            "source TRAIN only",

        "model_selection_rows":
            "source VALIDATION only",

        "source_test_rows":
            "final evaluation only",

        "external_rows":
            "decontaminated target TEST only",

        "source_test_used_for_training":
            False,

        "external_target_training":
            False,

        "external_target_scaler_fit":
            False,

        "external_target_feature_fit":
            False,

        "external_target_early_stopping":
            False,

        "external_target_calibration":
            False,

        "external_target_threshold_tuning":
            False,

        "protocol2_threshold":
            "reuse source-validation threshold",
    },

    "resume_policy": {

        "run_plan_is_immutable":
            True,

        "run_ledger_is_mutable":
            True,

        "never_reset_completed_jobs_on_rerun":
            True,

        "complete_requires_run_manifest_and_required_artifacts":
            True,

        "failed_job_may_be_retried_with_same_locked_config":
            True,

        "seed_change_on_retry":
            False,

        "hyperparameter_change_on_retry":
            False,

        "split_change_on_retry":
            False,
    },

    "execution_order": {

        "model_order":
            EXPECTED_ALL_MODEL_IDS,

        "source_dataset_order":
            EXPECTED_DATASETS,

        "seed_order":
            EXPECTED_SEEDS,

        "scientific_meaning":
            "none; deterministic scheduling order only",
    },

    "immutable_inputs": {

        "benchmark_manifest": {

            "path":
                str(
                    BENCHMARK_MANIFEST_PATH
                ),

            "sha256":
                benchmark_manifest_sha,
        },

        "model_registry": {

            "path":
                str(
                    MODEL_REGISTRY_PATH
                ),

            "sha256":
                model_registry_sha,
        },

        "execution_contract": {

            "path":
                str(
                    EXECUTION_CONTRACT_PATH
                ),

            "sha256":
                execution_contract_sha,
        },

        "evaluation_contract": {

            "path":
                str(
                    EVALUATION_CONTRACT_PATH
                ),

            "sha256":
                evaluation_contract_sha,
        },

        "controlled_model_contract": {

            "path":
                str(
                    CONTROLLED_CONTRACT_PATH
                ),

            "sha256":
                controlled_contract_sha,
        },

        "feature_cache_manifest": {

            "path":
                str(
                    FEATURE_CACHE_MANIFEST_PATH
                ),

            "sha256":
                feature_cache_manifest_sha,
        },

        "run_artifact_schema": {

            "path":
                str(
                    RUN_ARTIFACT_SCHEMA_PATH
                ),

            "sha256":
                artifact_schema_sha,
        },

        "published_route_contract": {

            "path":
                str(
                    PUBLISHED_ROUTE_CONTRACT_PATH
                ),

            "sha256":
                EXPECTED_ROUTE_SHA256,
        },

        "environment_audit": {

            "path":
                str(
                    ENVIRONMENT_AUDIT_PATH
                ),

            "sha256":
                environment_audit_sha,
        },

        "execution_index": {

            "path":
                str(
                    index_cache_path
                ),

            "sha256":
                index_cache_sha,
        },

        "published_closure_audit": {

            "path":
                str(
                    PUBLISHED_CLOSURE_AUDIT_PATH
                ),

            "sha256":
                PUBLISHED_CLOSURE_SHA256,
        },

        "full_run_plan": {

            "path":
                str(
                    FULL_RUN_PLAN_PATH
                ),

            "sha256":
                FULL_PLAN_SHA256,
        },

        "external_eval_plan": {

            "path":
                str(
                    EXTERNAL_EVAL_PLAN_PATH
                ),

            "sha256":
                EXTERNAL_PLAN_SHA256,
        },
    },

    "published_method_closure_sha256":
        published_bundle_sha,

    "published_selftest_sha256":
        published_selftest_sha,

    "mutable_run_ledger":
        str(
            RUN_LEDGER_PATH
        ),

    "run_root":
        str(
            RUN_ROOT
        ),

    "results_root":
        str(
            RESULTS_ROOT
        ),

    "cell31_model_training_performed":
        False,

    "cell31_test_result_inspection":
        False,
}


LAUNCHER_ACTION = (
    assert_or_create_immutable_json(
        LAUNCHER_CONTRACT_PATH,
        "TRAINING_LAUNCHER_CONTRACT_LOCKED",
        "contract",
        LAUNCHER_CORE,
        "TRAINING LAUNCHER CONTRACT",
    )
)


FULL_EXECUTION_CORE = {

    "schema_version":
        "1.0",

    "benchmark_version":
        "benchmark4_FINAL_v1",

    "status":
        "FULL_EXECUTION_PLAN_LOCKED_READY_TO_LAUNCH",

    "training_started_at_lock_time":
        False,

    "training_gate_open":
        True,

    "n_models":
        17,

    "n_controlled_models":
        10,

    "n_published_models":
        7,

    "n_source_datasets":
        4,

    "n_seeds":
        10,

    "training_jobs":
        680,

    "external_evaluations":
        2040,

    "additional_protocol2_training_jobs":
        0,

    "full_run_plan": {

        "path":
            str(
                FULL_RUN_PLAN_PATH
            ),

        "sha256":
            FULL_PLAN_SHA256,
    },

    "external_eval_plan": {

        "path":
            str(
                EXTERNAL_EVAL_PLAN_PATH
            ),

        "sha256":
            EXTERNAL_PLAN_SHA256,
    },

    "run_ledger": {

        "path":
            str(
                RUN_LEDGER_PATH
            ),

        "mutable":
            True,
    },

    "launcher_contract": {

        "path":
            str(
                LAUNCHER_CONTRACT_PATH
            ),

        "sha256":
            None,
    },
}


FULL_EXECUTION_CORE[
    "launcher_contract"
][
    "sha256"
] = sha256_file(
    LAUNCHER_CONTRACT_PATH
)


FULL_EXECUTION_ACTION = (
    assert_or_create_immutable_json(
        FULL_EXECUTION_MANIFEST_PATH,
        "FULL_EXECUTION_INFRASTRUCTURE_LOCKED",
        "manifest",
        FULL_EXECUTION_CORE,
        "FULL EXECUTION MANIFEST",
    )
)


# ============================================================
# 12. FINAL RE-READ / ACCEPTANCE GATE
# ============================================================

launcher_check = load_json(
    LAUNCHER_CONTRACT_PATH
)


full_execution_check = load_json(
    FULL_EXECUTION_MANIFEST_PATH
)


gate_check = load_json(
    TRAINING_GATE_PATH
)


assert (
    launcher_check[
        "status"
    ]
    ==
    "TRAINING_LAUNCHER_CONTRACT_LOCKED"
)


assert (
    launcher_check[
        "contract"
    ]
    ==
    LAUNCHER_CORE
)


assert (
    full_execution_check[
        "status"
    ]
    ==
    "FULL_EXECUTION_INFRASTRUCTURE_LOCKED"
)


assert (
    full_execution_check[
        "manifest"
    ]
    ==
    FULL_EXECUTION_CORE
)


assert (
    gate_check[
        "open"
    ]
    is True
)


assert (
    gate_check[
        "benchmark_training_allowed"
    ]
    is True
)


assert (
    gate_check[
        "published_methods_implementation_validated"
    ]
    ==
    7
)


assert (
    sorted(
        gate_check[
            "validated_methods"
        ]
    )
    ==
    sorted(
        EXPECTED_PUBLISHED_IDS
    )
)


full_plan_check = read_csv_exact(
    FULL_RUN_PLAN_PATH
)


external_plan_check = read_csv_exact(
    EXTERNAL_EVAL_PLAN_PATH
)


ledger_check = read_csv_exact(
    RUN_LEDGER_PATH
)


assert (
    len(
        full_plan_check
    )
    ==
    680
)


assert (
    len(
        external_plan_check
    )
    ==
    2040
)


assert (
    len(
        ledger_check
    )
    ==
    680
)


assert (
    full_plan_check[
        "run_id"
    ].is_unique
)


assert (
    ledger_check[
        "run_id"
    ].is_unique
)


# Critical regression guard for this exact Cell-31 bug.

assert (
    int(
        full_plan_check[
            "selftest_manifest"
        ]
        .eq(
            ""
        )
        .sum()
    )
    ==
    400
)


assert (
    int(
        full_plan_check[
            "selftest_manifest"
        ]
        .ne(
            ""
        )
        .sum()
    )
    ==
    280
)


assert (
    int(
        full_plan_check[
            "selftest_sha256"
        ]
        .eq(
            ""
        )
        .sum()
    )
    ==
    400
)


assert (
    set(
        ledger_check[
            "status"
        ]
        .astype(
            str
        )
    )
    .issubset(
        ALLOWED_LEDGER_STATUS
    )
)


ledger_status_counts = (
    ledger_check[
        "status"
    ]
    .astype(
        str
    )
    .value_counts()
    .sort_index()
    .to_dict()
)


training_already_started = any(

    status
    !=
    "PLANNED"

    and

    count
    >
    0

    for status, count
    in ledger_status_counts.items()
)


if (
    LEDGER_ACTION.startswith(
        "NEW"
    )
):

    assert (
        training_already_started
        is False
    )


    assert (
        ledger_status_counts
        ==
        {
            "PLANNED":
                680
        }
    )


# ============================================================
# 13. FINAL REPORT
# ============================================================

print(
    "=" * 128
)


print(
    "CELL 31 PASS - "
    "7/7 PUBLISHED CLOSURES AUDITED; "
    "FULL 680-JOB TRAINING PLAN + "
    "2040-EVAL PLAN + "
    "LAUNCHER CONTRACT LOCKED"
)


print(
    "=" * 128
)


print(
    "Published gate         : "
    "OPEN (7/7)"
)


print(
    "Published methods      :",
    EXPECTED_PUBLISHED_IDS,
)


print(
    "Controlled models      :",
    len(
        EXPECTED_CONTROLLED_IDS
    ),
)


print(
    "Published models       :",
    len(
        EXPECTED_PUBLISHED_IDS
    ),
)


print(
    "Total models           :",
    len(
        EXPECTED_ALL_MODEL_IDS
    ),
)


print(
    "Datasets / sources     :",
    len(
        EXPECTED_DATASETS
    ),
)


print(
    "Model seeds            :",
    EXPECTED_SEEDS,
)


print(
    "-" * 128
)


print(
    "FINAL EXECUTION COUNTS"
)


print(
    "Protocol-1 trainings   :",
    len(
        full_plan_check
    ),
)


print(
    "  controlled           :",
    len(
        controlled_full
    ),
)


print(
    "  published            :",
    len(
        published_full
    ),
)


print(
    "Protocol-2 evaluations :",
    len(
        external_plan_check
    ),
)


print(
    "Additional P2 training : 0"
)


print(
    "Source checkpoint reuse: "
    "1 training -> 3 external targets"
)


print(
    "-" * 128
)


print(
    "CSV ROUND-TRIP FIX"
)


print(
    "Controlled blank selftest rows :",
    controlled_blank_count,
)


print(
    "Published selftest rows        :",
    published_nonblank_count,
)


print(
    "Empty string -> NaN conversion : DISABLED"
)


print(
    "CSV lossless re-read           : PASS"
)


print(
    "-" * 128
)


print(
    "SCIENCE / LEAKAGE LOCK"
)


print(
    "Fit                    : "
    "SOURCE TRAIN ONLY"
)


print(
    "Selection / early stop : "
    "SOURCE VALIDATION ONLY"
)


print(
    "Source test            : "
    "FINAL EVALUATION ONLY"
)


print(
    "External target        : "
    "DECONTAMINATED TARGET TEST ONLY"
)


print(
    "External retraining    : FALSE"
)


print(
    "External threshold tune: FALSE"
)


print(
    "External scaler/feature: FALSE"
)


print(
    "Residual exact overlap : "
    "0 FOR ALL 12 DIRECTIONS"
)


print(
    "Minimum target minority:",
    int(
        pd.to_numeric(
            cross_registry[
                "minority_class_n"
            ],
            errors="raise",
        ).min()
    ),
)


print(
    "-" * 128
)


print(
    "ARTIFACT ACTIONS"
)


print(
    "7/7 closure audit      :",
    PUBLISHED_CLOSURE_ACTION,
)


print(
    "680-job plan           :",
    FULL_PLAN_ACTION,
)


print(
    "2040-eval plan         :",
    EXTERNAL_PLAN_ACTION,
)


print(
    "Run ledger             :",
    LEDGER_ACTION,
)


print(
    "Launcher contract      :",
    LAUNCHER_ACTION,
)


print(
    "Full exec manifest     :",
    FULL_EXECUTION_ACTION,
)


print(
    "-" * 128
)


print(
    "Full plan              :",
    FULL_RUN_PLAN_PATH,
)


print(
    "Full plan SHA256       :",
    FULL_PLAN_SHA256,
)


print(
    "External plan          :",
    EXTERNAL_EVAL_PLAN_PATH,
)


print(
    "External plan SHA256   :",
    EXTERNAL_PLAN_SHA256,
)


print(
    "Run ledger             :",
    RUN_LEDGER_PATH,
)


print(
    "Launcher contract      :",
    LAUNCHER_CONTRACT_PATH,
)


print(
    "Launcher SHA256        :",
    sha256_file(
        LAUNCHER_CONTRACT_PATH
    ),
)


print(
    "Full exec manifest     :",
    FULL_EXECUTION_MANIFEST_PATH,
)


print(
    "Full exec SHA256       :",
    sha256_file(
        FULL_EXECUTION_MANIFEST_PATH
    ),
)


print(
    "-" * 128
)


print(
    "Ledger status          :",
    ledger_status_counts,
)


print(
    "Training already start :",
    training_already_started,
)


print(
    "MODEL TRAINING IN CELL31: FALSE"
)


print(
    "TEST RESULT INSPECTION : FALSE"
)


print(
    "TRAINING GATE          : OPEN"
)


print(
    "NEXT                   : "
    "CELL 32 - PRODUCTION TRAINER + "
    "RESUME-AWARE FINAL TRAINING LAUNCH"
)


print(
    "=" * 128
)

================================================================================================================================
CELL 31 PASS - 7/7 PUBLISHED CLOSURES AUDITED; FULL 680-JOB TRAINING PLAN + 2040-EVAL PLAN + LAUNCHER CONTRACT LOCKED
================================================================================================================================
Published gate         : OPEN (7/7)
Published methods      : ['ampep', 'ampscannerv2', 'ampgram', 'ampir', 'ampeppy', 'ai4amp', 'amplify']
Controlled models      : 10
Published models       : 7
Total models           : 17
Datasets / sources     : 4
Model seeds            : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
--------------------------------------------------------------------------------------------------------------------------------
FINAL EXECUTION COUNTS
Protocol-1 trainings   : 680
  controlled           : 400
  published            : 280
Protocol-2 evaluations : 2040
Additional P2 training : 0
Source checkpoint reuse: 1 training -> 3 external targets
--------------------------------------------------------------------------------------------------------------------------------
CSV ROUND-TRIP FIX
Controlled blank selftest rows : 400
Published selftest rows        : 280
Empty string -> NaN conversion : DISABLED
CSV lossless re-read           : PASS
--------------------------------------------------------------------------------------------------------------------------------
SCIENCE / LEAKAGE LOCK
Fit                    : SOURCE TRAIN ONLY
Selection / early stop : SOURCE VALIDATION ONLY
Source test            : FINAL EVALUATION ONLY
External target        : DECONTAMINATED TARGET TEST ONLY
External retraining    : FALSE
External threshold tune: FALSE
External scaler/feature: FALSE
Residual exact overlap : 0 FOR ALL 12 DIRECTIONS
Minimum target minority: 309
--------------------------------------------------------------------------------------------------------------------------------
ARTIFACT ACTIONS
7/7 closure audit      : EXISTING IDENTICAL 7/7 PUBLISHED CLOSURE AUDIT VERIFIED
680-job plan           : EXISTING IDENTICAL 680-JOB FULL RUN PLAN VERIFIED
2040-eval plan         : NEW 2040-ROW EXTERNAL EVALUATION PLAN ATOMICALLY COMMITTED
Run ledger             : NEW 680-ROW RUN LEDGER ATOMICALLY INITIALIZED
Launcher contract      : NEW TRAINING LAUNCHER CONTRACT ATOMICALLY COMMITTED
Full exec manifest     : NEW FULL EXECUTION MANIFEST ATOMICALLY COMMITTED
--------------------------------------------------------------------------------------------------------------------------------
Full plan              : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_FINAL_full_680_run_plan.csv
Full plan SHA256       : 900e75614fc21e809525f4f4a7b79e4dc6532e260cdd7653c1612acd6269898a
External plan          : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_FINAL_external_2040_eval_plan.csv
External plan SHA256   : cf89ef02de8d6880bce463a2f890ec264a5fc650194ed7a83cf30b2ea7bd24a7
Run ledger             : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark17_FINAL_run_ledger.csv
Launcher contract      : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_training_launcher_contract.json
Launcher SHA256        : baf4f20e23e42bbc8713014f275abba499d9bc4a1dc501c1b16929fdc0b54b22
Full exec manifest     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark17_FINAL_full_execution_manifest.json
Full exec SHA256       : 7dee36c79ca443d2c140c494d92de3071e5cdc0667fb7a500163fa34a307d221
--------------------------------------------------------------------------------------------------------------------------------
Ledger status          : {'PLANNED': 680}
Training already start : False
MODEL TRAINING IN CELL31: FALSE
TEST RESULT INSPECTION : FALSE
TRAINING GATE          : OPEN
NEXT                   : CELL 32 - PRODUCTION TRAINER + RESUME-AWARE FINAL TRAINING LAUNCH
================================================================================================================================

In [38]:
# ============================================================
# CELL 32 - v4 TECHNICAL BUGFIX / INCIDENT-RECOVERY / RESTART-SAFE
#
# PURPOSE
# - Preserve all 320 already-TRAINED v3 runs unchanged.
# - Preserve the failed BiLSTM-Attention attempt as audit evidence.
# - Version the Keras mask-dtype technical correction.
# - First v4 invocation retries ONLY the affected failed run.
# - Rerunning this identical Cell after that retry resumes all remaining jobs.
#
# SCIENTIFIC CONTRACT UNCHANGED
# - same datasets/splits/seeds/model configs/hyperparameters
# - SOURCE TRAIN only for fit
# - SOURCE VALIDATION only for selection/tau*
# - no SOURCE TEST / no EXTERNAL target in Cell 32
# ============================================================

from pathlib import Path
from datetime import datetime
import base64, hashlib, json, os, tempfile, zlib
import pandas as pd

PROJECT_ROOT=Path("/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026")
OUTPUT_ROOT=PROJECT_ROOT/"benchmark17_outputs"
AUDIT_DIR=OUTPUT_ROOT/"audit"
MANIFEST_DIR=OUTPUT_ROOT/"manifests"
WORK_ROOT=Path("/home/pc/genpept_benchmark17_work")
RUN_ROOT=WORK_ROOT/"runs"/"benchmark4_FINAL_v1"
SCRIPT_DIR=PROJECT_ROOT/"scripts_manual"
SCRIPT_DIR.mkdir(parents=True,exist_ok=True)

RUN_LEDGER_PATH=AUDIT_DIR/"benchmark17_FINAL_run_ledger.csv"
FULL_RUN_PLAN_PATH=AUDIT_DIR/"benchmark17_FINAL_full_680_run_plan.csv"
V3_SCRIPT=SCRIPT_DIR/"Cell32_Benchmark17_Production_Trainer_v3.py"
V4_SCRIPT=SCRIPT_DIR/"Cell32_Benchmark17_Production_Trainer_v4.py"
V3_EXPECTED_SHA="e2f06a0e296387b92951ad06a662fa6b8e865a208168e707a61f47c4eabf5e0a"
V4_EXPECTED_SHA="73380864a613019839d699041140b42926deba7f0e2b12ee5ab23bbdebb887bb"
FAILED_RUN_ID="bilstm_attention__GenPept_Curated_2025__seed_100"
INCIDENT_AUDIT=AUDIT_DIR/"benchmark17_CELL32_v3_bilstm_attention_mask_dtype_incident.json"
ERROR_LOG=WORK_ROOT/"failed_runs"/"benchmark4_FINAL_v1"/FAILED_RUN_ID/"cell32_error.log"

def now_iso(): return datetime.now().astimezone().isoformat()
def sha256_file(path):
    h=hashlib.sha256()
    with open(path,"rb") as f:
        for chunk in iter(lambda:f.read(1024*1024),b""): h.update(chunk)
    return h.hexdigest()
def read_csv_exact(path): return pd.read_csv(path,low_memory=False,keep_default_na=False,na_filter=False)
def load_json(path):
    with open(path,"r",encoding="utf-8") as f: return json.load(f)
def atomic_write_json(path,payload):
    path=Path(path); path.parent.mkdir(parents=True,exist_ok=True)
    fd,tmp=tempfile.mkstemp(prefix="."+path.name+".",suffix=".tmp",dir=str(path.parent))
    try:
        with os.fdopen(fd,"w",encoding="utf-8",newline="\n") as f:
            json.dump(payload,f,indent=2,ensure_ascii=False,sort_keys=True)
            f.write("\n"); f.flush(); os.fsync(f.fileno())
        os.replace(tmp,path)
    finally:
        if os.path.exists(tmp): os.unlink(tmp)
def tree_inventory(root):
    root=Path(root); rows=[]
    for p in sorted(x for x in root.rglob("*") if x.is_file()):
        rows.append({"relative_path":p.relative_to(root).as_posix(),"size_bytes":int(p.stat().st_size),"sha256":sha256_file(p)})
    return rows

for p in [PROJECT_ROOT,OUTPUT_ROOT,AUDIT_DIR,MANIFEST_DIR,WORK_ROOT,RUN_ROOT,RUN_LEDGER_PATH,FULL_RUN_PLAN_PATH]:
    assert p.exists(), f"Missing required path: {p}"
assert V3_SCRIPT.is_file() and sha256_file(V3_SCRIPT)==V3_EXPECTED_SHA, "v3 trainer changed; refusing unaudited recovery"

ledger=read_csv_exact(RUN_LEDGER_PATH)
plan=read_csv_exact(FULL_RUN_PLAN_PATH)
assert len(ledger)==680 and ledger["run_id"].is_unique
assert len(plan)==680 and plan["run_id"].is_unique
mask=ledger["run_id"].astype(str).eq(FAILED_RUN_ID)
assert int(mask.sum())==1
failed_status=str(ledger.loc[mask,"status"].iloc[0])
failed_plan=plan.loc[plan["run_id"].astype(str).eq(FAILED_RUN_ID)].iloc[0]
failed_final_dir=Path(str(failed_plan["run_dir"]))
failed_staging=list(failed_final_dir.parent.glob(failed_final_dir.name+".cell32_staging.*.FAILED"))

# Write/verify immutable incident evidence. No trained bundle is deleted or rewritten.
if INCIDENT_AUDIT.is_file():
    inc=load_json(INCIDENT_AUDIT)
    assert inc["run_id"]==FAILED_RUN_ID
    assert inc["v3_trainer_sha256"]==V3_EXPECTED_SHA
    print("v3 attention incident    : EXISTING AUDIT VERIFIED")
else:
    assert failed_status=="FAILED", f"Expected failed row before first v4 recovery, got {failed_status}"
    assert ERROR_LOG.is_file(), f"Missing failure traceback: {ERROR_LOG}"
    assert not failed_final_dir.exists(), "Failed run unexpectedly has a promoted final run directory"
    payload_inc={
        "schema_version":"1.0",
        "created_at":now_iso(),
        "status":"VERSIONED_TECHNICAL_FIX_REQUIRED",
        "run_id":FAILED_RUN_ID,
        "ledger_status_before_v4":failed_status,
        "v3_trainer_path":str(V3_SCRIPT),
        "v3_trainer_sha256":V3_EXPECTED_SHA,
        "error_log":{"path":str(ERROR_LOG),"sha256":sha256_file(ERROR_LOG),"size_bytes":int(ERROR_LOG.stat().st_size)},
        "failed_staging_bundles":[{"path":str(d),"inventory":tree_inventory(d)} for d in failed_staging],
        "root_cause":"Keras 3 autocast converted the padding mask supplied to MaskedAdditiveAttention into float32; tf.where requires a boolean condition.",
        "observed_failure_signature":"Input condition of SelectV2 has type float32 that does not match expected type of bool",
        "technical_fix":"Inside MaskedAdditiveAttention.call(), cast the received mask explicitly with tf.cast(mask, tf.bool) before tf.where().",
        "scientific_change":False,
        "scientific_contract_unchanged":["datasets","splits","seeds","features/tokens","architecture","hyperparameters","optimizer","training rows","validation rows","threshold policy"],
        "retrain_scope":"ONLY the failed run; all valid TRAINED runs are retained verbatim"
    }
    atomic_write_json(INCIDENT_AUDIT,payload_inc)
    print("v3 attention incident    : NEW IMMUTABLE AUDIT WRITTEN")

# Materialize exact v4 trainer without overwriting v3.
_CELL32_B64=(
    'eNrtvely20iyMPqfT4EPPTMiuiGapHd2syNoibJ1rG20uN3Bw4uASFDCiFsDoCy1wzfuQ9wnvE9yc6kVC0XZ3TNnzjkT0xYBVGVVZWVlZWZlZU6SxcwJgskq'
    'WyVREDjxbLlIMieczxdZmMWLeVqrTbDMMsyup/GlLHACj/xhHGZRFs8i+UU+89fsfhml8tMZ/J1GR+EsSpfhKKqJ11cj+es6TLER+fiPdDGXv2fYoPi9SOWv'
    'ZTy6mSpASTgfL2bqKUoXq0Q3k16vsniqnlaXy2QxilIFK4tmy0msodEg5O8E+nsZjm5q8s18NVveO2HqzJeqM9A8vID/L8cCayn0LkzmjcswVQgaTRfzyP48'
    'CmHUCeFbltoRr6LxzjRM03gSR8nOB7taNE+j2eVUQe7fQT/PkyhKdR3feRen2dskHMfRPHuzWKRZPL8yv58S1vYWgK9Mv7dbmsZz+BvMFuNoKls7WFwB5Hh0'
    'Gl1B1RT6bteZRVkSj9Tk12sO/C8cjVaAy/sgHUGDPr+7jZLwKgqWSTSKEY758TKchvNRNA7Kal4m0FN+EUwXacpvR4v5ZEVwgGiS+I7fTlpmTfiSXUef0gBe'
    'JaNFNOHXQBFBuBrJkl5uRDj8II2m0cicqrMMpw6QNn6/t5iO7TrLeBkh9tTCEc+5UkkkqBEmR8NFgkrGZ0Ae+QlJb2dqHmhuzj7s1Gq175zuN/wPqu/0Dw6c'
    'p21n2zk5Pd692DnfPz5yzk97+0f9U+f46OBX5wfntH92cdjf7v3SO+07e/tHvQMusX/01jnoXRztvHNunwGsN9F8dD0Lk5uOcyl/PguoQnDbqn0HRY6XEZN9'
    'ON1ezKf3TjS/jZPFfAa0ivOYJYtp2oGCjrMTTafYs3CVLbaXi2k8uucP287b/tFJ/+Q8wM4/bQeHvY/Bfxy/Oes2nVkUzmFFQs0kmoXxHLH7j8VlKiouF2mc'
    'xbcwOfMsuooSZxQuU4c6kl3HQLrz28WIl2V9obsKwEYLINr7J6PraHSzXEB1T4CcxEmKaxwaNqvDQoFOAKHE0J/oLhxl0EbLmS5GN9EYu+R8uo7mju66AJdE'
    'yWpO3QZydfZ3+0fn+zuA8FFEY0pXwEsLY4O6t8+An42u5zHQjoM0Lki2fnTspCNkBUCwIweILluMFlDkOpxfRR5j9D2MNHWewiK5J3SPQhhS6FwuFjSsZTge'
    'Y2OzML2BhzSFESDfc1JAy3wMw16ugGUunJCgjVZpBpR7EN4DggFTCxrKlB5HixmUjZwx7hNOfTJdhNnTttdwDgF2NO5BQzg/vSzDHgOHQYDzxSdA4RIoIEYs'
    'Yu9gqjLEwyiC0mPuGbJr7EU2aWDPgQYnsKjxEVCdRHWvQZg6WlgICRPYnjLsaSoJcAoQL5EiImDiJoHehkkcAv9NG9+68Gqw2v6jv3MenB4fnztd2l7r7pPZ'
    'PHsyfnJ20XvT2w/eRvOTaJlt76xoW9huN9vPA6fVbrxqwM8Xrlc7vjg/udAwTJBPHFetwdbLYLHKAO+pW+td7O6fB7v7p1DBrA7lwxUg360d9o729/pnFYVm'
    '4TyewMYBoJAtHJyfyeZzBZFWp1jsl+PT97lhXi9m0ZPl6MlVNF/CCAOzp58WyQ0M7fTiSFbSABDsap661ug0h3Fr7/oHJ/3T0opA+eMVrYngOprC2t4MTGN2'
    'M46TOpAJEEDaPU9WkQ/ECBthsLihR69W27s4OAiwxycHPfind/4OWteYzs0FtzNZTafBi1fNAEYULGHPa4zSW7fW/3jeP8Xv/Q/wzyPgRXdAxMCrgnbzWTOI'
    'buGXhop9O+jvvoVBbQYNOwXLAFgkA2A2D9V3jo+A9wOVCTgWtZSCIh4I7COYhiv4Bvs3LTPgiA2U91zGXv9jf+cCN59AQdy4BUJldBeNVhkLAUyiArzcqoK3'
    'vfP+V3T7ChafAPWmD0g47AFVbdxJTVb5fhEmjw9gWr4CqZpTsYyWxylSz0WP8Pl44Eg8K9rGClPV751fnPaDnR4Qw9fMVBSS3jEKgRDyCDm5eHOwf/YO8HEK'
    'vKT/FR1fri6ncXqNSImy68U4SIDvRflB4GLonZ7v7yHsMxjIYW/zJnBhhAnsHQAPpMZr2InlfF7sMpwzKHrQL4E2Wo1DBICKRoD6VSpn6+jD/unx0SFs9gEv'
    'zIr+GJtRQOxaAAC2cQKsH1C32zvvnfXPz6DygCRcV2wjgdhGAtxGXJZ+3b5kGkp0C1ryW+/wZBpP7gMpkK+p8xS+DXUfzvr9XewAzEVWT1DOqLeaTd9ptZqe'
    'Z9L9/q7Rz6lQL4JE6ReySaGNgAwcjJSaJD+yEhhMSJ+RLyPUjGANg2okX10jz74SelFwKRQj3cTVdXZ1OZPPo/m8pZq4jKdpNrOfglDKKPI9tDhPoRszYHGA'
    'GliWCeFF07U13nAGe5+sCw/pCJTwKLltG++guzPjMU6Mh2i5vFeP8TN4Y3zEmaPGe8Bbudkc3n9wrH6hRNLf3d8RLOPg4vDI6CtSfQzooG2UBEj8zZyH37Pq'
    'HYzDDDTfDN9kYXIVZfoNQ0qjiMtjJyNR+R5mahXxL9LE+CcoSfQ5u4apvQZNi0ZUq42jCcqEQZwu6p6z/TMI20mH1bkI2MtcmSQaUArEPpAX4eF30MLhASrh'
    'HIVZ3ROg0uuw/fxFgKaAOq7KDokpNuBrwIUwVjS4PFTHD5/i7NoBVWFOVaGzyaXroXQ84YqkiS5A8L1ezW9AGga5NUrq03B2OQ47zqSRROEYVkf7mfO9g388'
    '37l0XU9XptYbqyWOqU5QPHOo143r6G4cXwHt5weUwSKo4z8dHEcponJDwsINJt26u8om269czytpAKT2cYCcx8RXpwIfMIMEEhZbVwLNIUj0BiE2EHZ9IltC'
    '9AQggQSkQuWnZzlu7AJ57aEIb40LPsiaoh9ToJdZNFsk9929cJqCEHcTRcsA2ghBTA3moXw9D5ESYJL4hexICCoN8KZPCcxffug+aBH32G/q1BHQGXcGSzRY'
    'ctxEjCRSGftONltCf2YRkJw0UUH1FH/XYUlM4rsuQaYyPzhuAyo0AMvQQBcmuG406zHURdoYTRdpVJ+M+QXUkNK4bE18SO71tOi5hEIwlZ9KphIQFn1C/tx1'
    '/3NemFj8H83qeIWdZyz5zsSHlTCG/nXbCDFFkSAEpSyWk5Aukiy4ie4lpkChh/mbh3M5KWYDoN/hrNSpA7kvk+kqva7bbwEbk/R+PqrDZ8DtHJiILgAfkwgE'
    '51HEg0ZkiqmJYdObGuiJJ4jHBs1iWs8tWfyymgNibuqlJCQpU1LQeNKxyPm/GSmNJ41sQYMmrOLs3+Xn8k9EPeMc2VvAs2Dh3uaR/32QjnD1yIm7P7iA/xmz'
    'gUYwoYSvmQe1V33FNECPqFac8rZu9IlKozWry0VonyD8FHYpVQdNXklmVO06jMwJSMPinbYvODw0mM/JJErSH2FTQvM0lEEbIk1Ix/mMjX9xqYkIloHBdUtp'
    'lbFjbf15uUXtmSCsjWbjOvznO9/jjN92kah9OuEAjUg8jT6Nxa9peBlNu+5oMQOVbCylD6iPEiCS5J1HQswdCjDweii6gRYeKKKPVhrQdl2NBDugiRG6zxOm'
    'XqXZGHtjVD/ZP+lb36Mkqf6OA4P/jDbE+MRf/UEOFQkDfqOtjx4R80hodXjpGcXRyiv2InqpqIrH3OAZQDnJ+T9dp2lIMmEMEE9Zx+snySKp2zuS+5mQ/cWZ'
    'hDHaGWmPJUCfC7C/wILM1d45PgSdcBfoB5AL38/Od0FX7vznXNZmnA62W+1ms9kZloCAKv3TU7sKoFlX0RUscuPSgsbQwApKzm0dWQ+tWeBfLEt16CMtYfwh'
    '5LLwExAK8BShwTZANahrtoWYhRJiWgqCoYBs9Sb8BB1P4iWI9CAbACfxkDg/uy3SGKQ6geof/HG/yD1Yqu7AP5L7oviKLyRn1RxPrH+bpeDqP4z5AEeCtde1'
    '6OpnNRwXP7qELoauSc5N49+j4PI+gx530GrO20CaoaICfwL8bpWn1Y/A8myAC8kRi6UTLKPwJgDJIphdstJEtnceNdp7cLuiV3V5jopzlKzSENR39er04qz3'
    'tg8a/sGeB4s9mIV3SZoylr7Dk6nVnaNe43y+j980TGRwU09I12k0RR+vlivu3+wyuARFI4gmwG4yyba/c3YXztHxuTwAOweRcZHswbTjlOPhwnyRRUBsN09m'
    'oOsB65X8QlSno6S2A5BDYSAyYbw9ucBjSijPJ0EAMzR4Gi1RAYgOMvgIB809jjDmOGkUJqNrJhBnFxQL8yiB1OTUWQFjyK7DTIBKcfc3WknxUDG6uneAOyw+'
    'WTjDNWFsnRHuV9j7CQrFGgStR9SvidUJ3AnSzRmnyqnYHBktBGmgA7LOARAULqCX26/KGzHPU8iEBcDL64s2yGomVAc0KindM9clJkIAz5Yxq2h5A1wDBIq0'
    'dJ8z2iV2xfY7Mj8l9wFWA94yGHpDExWgT9Txk+f87LRqUvvHMzJqqJOXKYjTjNEsgRAZVQfGPIjmsHI0ykB9dWaMSEDb2J4FZBpq+ANX04g7HLi4xEYLIFd3'
    'CF3rir5JwaaqFvSKBn25iqdjd4gLGrdwiWmbpY8Wy3uhai2mOFXwgRF3sBsc7L857Z3+SnhHliykK5DkslSaCglvcj8AEBpZVKwRLkEXHdfhi5rrQQH2EKC5'
    'Hbfxj0WMMzHKGniOjrpknaB4Rl2ioA/7Z/tvDvrBbv/D/k7/jAE0XV3qfC/YOTkJDvePgoPjt8FB/0P/gEu17VJ7x6c7/QDYSdA7ODj+JXh7evyL7BHtSHJs'
    'uEgRl8C2chsegTr59fzd8dG73tk7tKRSfSROnF+s6VnbMtQQvAGES7TXGrwBJ13zB8lOSdroOonrumWON7o+KvPZpAZQcIqySQMdLeKrBk5WsLy+T/GwORhH'
    'tzGAr2/BwLe8mrEOsCITm+9s5Rjuah7eggSEp6nwGwQQxX2AV2+3bfaKzGirhgsJQOJSQsidEoVHdTG6Awk8RiYTThtplAnbT3CVLD7BgoP6vqPVhehuFC0z'
    'S2wzaS9NaySmAXgebH3rCYyh09wSGL1T6IEdBmZp0Go0faeN/zxtNIc+H3d3M7RH8IE3VbvnakkEikMEEzWr3znfYzWFRd6Q7xvkfFT3PNQ8WlCgtkyQGpRp'
    'Ja1/3tLzttVBsEEABEFeMQGgX61/+Kjmht9vsUCCbwbNofcF6AtJg2hsjXRPDJPYF/CA9B74AJ3A4YyCaAACw/QWWD+04W6PYMUj1Q3/ONm/RJ1AdeDB/XEz'
    'Kb9awGfEuzlqRrWeThAcJZC7oNonQhz3HlOdhXNVHbBgCaFW34AcgMbkhlEJlXUNQxE1lFV5ztngGUdLAG2Hd3onlMNopMtpnFEJlLYnzp0Uwe0tEAswKueT'
    'BcBSdt20Tt9A1Rh6+Z0Ly1ZtU4LVYRHgdbv9/kmAZ/t0HL3bl7ys0m3RYHK+A5TqW65+Dzn2VbHF2iG0jYcrXST+MLm6HbSGNeTYXeLU8mUbxnp+/L7PB/ld'
    'WjHq41P4eNB7A3BKPj6Dj/tHu/2PZR+fI1g82g7e93/VXXgxrKHjgPXu5bDssDkH79WQ/EnwpDH35bX+spE3BDKS7uN2C6wCzAipVog3JDChIG2QKrqGRMm/'
    'diMAyDfoLdVA39KUIIoDSNya6zj9Xk31paIf0Ry5ZLDA8wdQV2awANMZiE6i+T79gRFLnRTarQlJtKsPScgyXzKxho1viyxZW8DR5Rl4V8AZbMk3W8Ma9zHt'
    'yleDLeVUgO+hBE6F8RkfA1A8E+S1goEgnMlVV9QZyNUxHGyhbhRnIL6ukghKfezOlzwCvSx8ZzYLl+TL0N1KtqTFn919paH4XlXUS2ajivH4TlXVC6q8LDA0'
    'LBumYZKE93WoOlDLTO3kUADW+ItnXg2EmHxxsf5KCn/MErPwxwE0liuGssG9Xew+X0wJER9vbXDQmTJwtza0XCkF7X1XEnetNkK/YOGU93a6uAynh+HdyWIB'
    '/PuqtVt/3yB3vrRBTn5CCkIZFJb4FITUKZ3woMeZYXm988lPr8sf1Gt6hwsFVPc6Pvh3DeqcZxUBtVZ58sEPWE+w7EBnmqVU6eemv93y/DtfQtpuRa8VJC9v'
    'UdJi1yy8qzN8PwRG1m15ZaPvscvyN2PgKxEAe1Q3Jyl+X4IEQoEchTp6ieZYF8YZz6CiDYZqcQ0fD0QRFPNxhUiUZSvxCB17Ag3YKCt4cVZjKwiAd2RBwBhb'
    'we/U//77m0+w8ZiIS1d4VuA1VHFVRhcBAA3YLP7RVY3tor98nYEC24pvyaepuwUy+vVWria5HeSrtvxVGgWXcZiaZ1X2LH/1JAs3VaMf+D39bRVFv0d13am6'
    'Gln9zhPTu93KVeN1QXBTewmkhakLscJ83kgXkwypPy2QTGGRlFJcaJGboACY+wN0WI/GJ+RrvZj3Z5cR+Q9vSgXQp2ApKqc+70TQ4DfRxQKkf9kPPcu6axVt'
    'lk34ndG+qkKrkzydQANMsm7Tn8azOKMZvQ6XEUwdSIc+gM3CEkzf/VDsZl0BB+RmixugSOj5PpJVnWB26+1m0/d85uRbxO23fDSqA4lTeSByojsD8eh3ItxP'
    'nIz0xPkiC6LfVuG0nvlNT9QXLt8BVt/y6gwO+gFCvxJ7u1vkJLXF6Pi9DK3tlo+yMMgFgy01METs1tCjZRL8HiULZjiqkRy0ncX8FhiugjPCZ+GjkSKc3BfY'
    'weZ4ayP+PcKvYiTdLTS4bll8IImmKxjc7xs12a5ssv0NTVbusF598DthaFjoHfMm1YUxPgbE5bDxjQa4myyWoNCx/70Aw68AhKqACnqBI5rw0/hqtojH3EQ0'
    'tYmD3eT+bOp4E7NllO5pGBzm7PxQo0h47BGOAuAYgaqDLfEaBPkdWO8cdBNhEhAI6Ro4IigaUVBztEpQFQpKChc+ImpLJ+PPmU8C8yfNqnZ+/HecX1Jb/+zp'
    'rRKFVKcVCtVc//PX/J9DIyWOsIJMxl01BLXHAnSeKNaYFzcVpDR+gGTWSR64UY7l1ia+6p2WNzhhkZpV7ZYz2i0tkVsKPwKynlGxbeIfTx0CXaJxkuxpJCgo'
    'TMwlkgIqQZRgnBPp/hyupln8LgrHmppA/g6u4U2qEYuvdE/oI9LITYRnVjNdTryg9YKlsFAJnWtQxsrg8c6uw+Cv462/1qnfP7SQfvzffRsN3XCmxZ3fu7YM'
    'eISeuNP495AHI7E4D6bzAuQfQg1nMqlcGpMoGqMzOIiBY4u81qySAsjiUrHBGitmMlnXrbFdYJPxTyalo5dgbJmhoJf++/IQ6QPFLjTvo3t2n5F8BYRPYhkA'
    '8xD/itXvo58PIU4XpHINvGqIp8/cmWUG8jjwDqiufqeN3jic6RMNummLWxSexIs1gJYu2BnML4gtVecyysKgZRXmV8VS7WKptlUqWqbxFDBjFhPvrHKjabyc'
    'A+VYBeVLVVL8wWvSuG3P8dB6lMATur4slvdbeN0Z1Rq8N5l22dP/fUO9afTDZHp/li2WS2ShWpNdAMksku4WXjFD6Fu+w+a3WTzf8g1zaRbjfkscRwwGIQap'
    'ALk1HGzJQtb48CIH3vAmV5BPER5hpLmzHmgqYGXKQlYBviqXR4s50FNScg9Oj+cnU5jfcPX4waLzDxQzOyNU52kSLOiCHwLGLnFRa8AlqKqqXYowHOV0s9bR'
    '1jyDHaKcoj28YJE1yYGuARvDhA9jUMeu4f2ZLi+tSZwxij5miX8P/0kvonjM18bw0ke3/vHWv78VkKPlYnSdGgMU9qiAP6geXIbZ6Jo0KaOsfqnKpderyWQa'
    'GWShSVn9Ev2KkstFGoFOXkPzbhijLDgqG+N21qyZTth1dt3aoj5uddCKKq4z+XiGihhp4D+L5B54BFLH0AN2zc3yi05ZIVFA0VSukHoPBb940nFaHME82RLl'
    '8GLmlm95Uo+WXVVK31Q3Lgs2xGpqXD/fEmwyDW8jucjqoyVgqFU6/WwgMwzJXB3v6MSjDOfamLr28xe+Qru0UBB50tEwWUTQhoUjrZyLljwdQlN2OkELT1Sn'
    'bngNtMZ4DkhiTp1f/Qzt/I1//gQSmShRg6o4QI08g0ipcNqYIyvk+A9l5wHol0YOVfpUh17xYqs44LnSB014aEmnXeguQO4wW1h/y2963pM6u8F9/3177eFP'
    'uprNgH13BTmaJ/25g34uYBz2I51udhYnyRbPsbY6eJAlXqibsHzdH8hVLSJNyAqpsoyYWlGCpX112V72Dpe43K3hBRdI66ov5BSIo7llz8WtDr4RHzWFb3Ue'
    'JndYSjV9FUVg1KczNEUcdKzFp4yBKEEXLLf8rU9bni/vrLB/hOFsrS/j8sGYdrmRV+R88vnxqXiy+ASPWXjF2rA0hIp2hQeq8Z2ujuaa4MKN5T2f2hd9xg1o'
    'vpM/MfcMB66NPAo90yHc8NHYyAHEKm/0K/dFoir3Wns92e/57JAvIpMzn/2ZTwgrPxPbLOuFmKAGkzgXA02popRB+FVFq65554qZ9MBfhg964Fj+9X+SQ43l'
    'X/8tHjM72iGWzvWZEDb0l6mu/HhvmUkBGrodCIjCKx/V9c+SIIWXpWAIll9pbpVW8Q+34O0ivlY5vNB2BC3JQ+tcO6WbmFt+nm00TGUbc1CKyY/M/FS1xZpl'
    'xE6LvWw2mp7zN0e8+AmAwQuzimbHBV5G1C6Hr8u5tkuQ/qDdiOn7Zrjw9J2jskrVE7W+XjUbzlUU5zp6rRqhqGz8GDoESRQKNflt1zUl/lzZ4gZslbYornQr'
    'topLjJDvbn4LdqWqIG+CsGYZjaI6X+P2HRmyy5kH8DXttppii+MCTNfKH0FUYhmRAitxUWMN6LICsClQ5r2vGSC5SvIj0zMJi+b3n51m1QqQdcrWgPxoLgP5'
    'Si4EsyIGUUnFUgZkYBy8ehM9Q8lHlDEE3EucCQIaHYJLT/MgW4A46XTNjit7YqxtiQzGsBpOo0kG0gZ5/3W5DwP0+hC/sMGheX8vdn6Sfdl2WvYNPgqu1HXM'
    'gSN4e+Tclmbc9p22jcF083CoU1CNJEWA0MCjaOMwG/ouilibjggLl8Vz4a1ORqBLmMNbtOOhFxN6lMkrL4zaAdnNGhhDzGwCnwPYNC/Dy3gaZ/dGLep1RTWc'
    'yh9gvNy9J3IyPed7J7xM68XObBdasngJtwlQ1TV/iksXGGtfBUrIL8V/g/WX4oUwvCoa/7aSrAR1X7oZwJ7Pn3HVfPlnLFruhdhQGAeqY9yKFHxwRFZp2sXb'
    'HcM2MyY+j2DskoPOdmsIK9F+2eqAIPAEvcBL7oaawMgagbMyGJZMyAjQjWSR6z78gmUxgvdzjCehZXkNjZhTs/GcOFQOtG931tcdYpHVK2lcPwzqxgdjJoy3'
    'YjKE7Lv4RK7IQ8XyspC8PnUFjRoOF5JjMFCewn/ACOqKtCVoeZ/ks8U1XKjjdsRqw/q+/flwZ0d9LgSVNNYd9sbLV37TM2pXRLp8CMZeS0GQIS5zVXwHD8lA'
    'Zrml6JrdZgHGOMaLCiNQGRdBM3gOAJEl6TEDLwIKMGp9EadzdF+ja0UqqCMuvQaFbKDbfalxR4DQ5YuB+9R5v9i8z1g3rgeE6QimBp0oBiIkhP2HPY/xX6PS'
    'DehgXXcWJbDHQW9EyBnSRaOMFbQ6HlQYF8XRxIy3MHBcjRh04UFzWHF306QLrDbgPpt3Mg1WbJIJl8Y3VaVtuqDi9KqqvEEDXBpeWGWNvSDQq0XcLCWbEKnp'
    'ubuiIjpjIGQ6EdC1KNchifzvjvKoHUVUhKL42VhpXLhWycJ00SIny+agzi7hP/ibYUSIfCTcAmOgy+dpd4DjHsLKCG8j2cMUT0oz4Bkk4QC4J04d/v0BoIsC'
    'y2iEMTNFgTkVmGOBpVexZnoXp8easK1guwURxSTf3sXJqa5XES94LYSvZdPfyqK/lT27ZvObt3qmJ0/VNibUKqqnURfV7yxcYLhljYxc8OW1+O/v9FtNXXUj'
    'JdGsr2N+le/F7vmJ4GbZEu+YnR/Jxzk+7smvE/q6J78CLZtc0mCIgj/YTFTGCxbl6pLdwZr1hCZilZ9HV2F5+aZdXt/Op+MTpOkJbabfs40YLcYy1BqfOAor'
    'shVmDTmxGWTN3uUd7QKLRKcirqW+8y/h6I9mb4tVlpc1DN4iYtJ1JL6MKAsyRl1H41B/VVHrOhqvRlgFO45dJ49xUx6w4tt1KueCY94xRZAl2/ykwuB1+A70'
    'LFzWKZqGni6LxkSovI6cQvMLh87rOFbIdPGNYul1JAfabJ19sXdi7B7eAgR0rmbzlDbQYtBAcyeA0lYApnkYiMNLK+4PRm/guD8iZkFZoCy/khDodBa6P0Bt'
    'xUXOhA9AkvNwjm/kcar9FhulN/B3KIZrh4uaAD2G9XxgLo6EtD7m3eMDpaFyk3A8i/GkgTECsxVMf1o3z3c7pWHPJu7Pn/EsQhHMFwztgi+Ew+MXiutkjoxc'
    '9Xl8ackAAVBgz8/cfiXHbaGpgdLzeDJwScZwh+ZybkS/1VveUIQI0C14XwGnacAxeub9EdHwgZy39w7237477zgHxzvv+7uOPLQ5c3pHuw4GZD775uDfONtL'
    'nGvWv83A3b4ZR9vXYZp9Kxas75jBt3m1qmjX8FEEz/ZrQysKyNIKM3EK9BEjRy6LLbH84hb6WQxz7TsV8aq5D0bIae5jeRhp31kXAtp3ihGcGVpFOGbfqTpz'
    'g+5WxEVmgGvCG/vO2vDEXL8qsnDpPOjQKGoiRAgEGU0oPx0qgPanBE0XiXUUVY5ar6aCY5fWWod4r4ahr63ixZnwaipGsornbFWpmCRxI5XPUsp6VnluWisJ'
    'T20He6mYY8CFCD9d2tE1k+/VOJB0WT/XkoVXy8WKLgVRRTbA0uTem5v5gYuBoVYpxgbpgvArp6VIBMzFXEU72HABmESjO8w3mGvotN/b/TU4PxYNiZjYrZcB'
    'O1+quXaLcKx46gHulkY8mWJpNJVzaHPRdutlsZSU7oKWDteOGTG4xotXzTVV2jpiviYoURND6BerCsFOlClE3C5WkOljonG+DkXILlbQMewXCUaPHkoY4hFh'
    'iIDOG1W2ZVcTyga9L4OHTtBlUKzx4AQPXHuGyVbDHzS/UHNG59bRuEgQXCMf1j0NKK8U+VpRB4VljCBAtxSloBUwGtcZiiokoeCJO5QWhaxo2CowgbXuc4tB'
    '1zjsn787FgzgTCw5WAx7x8BO5Np0K0DqtWcNVGgmoq1cqO7vnNNoG2M3OxFmpXHi2Yz9bkQqFkxXA7NEWUw4jU6rQZv5TXSPkmmWUJQzPdcKQMDXVkHqApFs'
    'pkIGmWHxqPqAQ9kNi/HxZBRQ3Nj2c/2SsR0Gn6EjX4Z2tLw1MTvldOYj3SFqRHdEOLxhWbOc62Ysm0XBBjdFTI+BsUPsENNFIQdd8wSnKK9SIQN5Nc6gUayQ'
    'k42soEmqa57gYbR01NuB1HuHiCi2bZrVra56BWYGJbhTFnR+tQ600b7Sn4cNNKYH4xVm5kHzcl1bV0s4FegY2SKYr2ZREo/qBkBSj/FsGv39065LFwBcrwS6'
    'qQmYLZXzIQsVjStYd8vL+7ocpNdAT9U6qRRPpaW2tKsWnAEmtonHK9w2cC4DjOk6DZdlAyBlRUA2xR1DaikKQWW7cUndgVtIAaK4hR3pfy2Qh7Yo3tcB4N7+'
    '2zO7v3kgIvAH9JrcDc/e9U5BfaqoUhZABGpiQjJMDZLyfkFXXEgvnoXk0t+oceYQZAF4NJgX6AYufQFIOwe9szPMnGX4AEoOZsAYuB9ZG0aHWGLBgq3l3Qsr'
    '6vIlFLNi3vGwtOK9WeP0+BfcQXq4FVdXSSiAfRbiZm7WVmydeLTS1erWwEAlKsEH8Oi6HgPoWeUulXUXfcuKDpXwweoU6Hz5kXgFzcfi8LWHmLuJARjkUPP5'
    'Wu1joMZkeMqVjdOMEUP5CMr85D4GNPwzA1YeHxvB+dUAkMfZRgAEPozhcQgBxEf9Wav5/LXvPGu3jILc8WKpdlNHkvu18NnD1faBYgZSXNNROF/I9HHXlBNU'
    'qqG/7IN4c3FOGgtu30qC42P0GgUED7hWYIoKRdUQF6gubNKx3GjysAxqKaGUQnEim03a1YSkfYFlv9cJRqZgTDVLBqEhGr2nwEMGcehCa+kAt2yqSskK2Ora'
    'fkacUiRIxKx9M9ghkxivEkbO2fHF6U6frSbOD/IRRJP9XdKKHbliKdxtQ6TEI1VhO0OtGNOV4EWxbbZo83CQyTiUInE0XaFsiRFHGhyCTEQ8OmNnDeRIUudA'
    'hlTQNZgjWDUbuMnOx4ZDysRFs2o8D4LPEtiXgPcK13+glD4pF0UFnwxoDHO7aYs/yRIGxvUQ4SVGCH3YocY4DiFAAwRbEg9KWn5L+1VDbxqz7f5H2JQxrx0e'
    'bOc7pc+1a2pDCWQhPkVRGVHYVpXn1fK6YC5PCh/93sRLXOtdcRca7djBfNFx6uIXnr3zdRz5YttpeRTg1ByXGoWHd7ESYfeiLSQQxwrQ188i6RCm+KEVls8X'
    'ZGQZopCE+IOtxSrLEJu+A1g9V7A0feOVWPh4H0RqZGX9gJWbri4R1QV0qhMQc40WSil/hfxUqWqFKgNjzMrurcilKJWX9m4gcKIA4MGKJFePHA4+u2IdmU4l'
    'rsIHztqGYEHEdZFngLQbzjH6r6r35tdAcrwiArU/jkWLGyKCJ5k8eQSNAtHzZn1+DCLvWqETE+9GqTQdIPMm+QddkVCnkTgwwA3ck94uS8fN2v4uvuz1kEzx'
    'QO/W4+ipNxw5+sZ3bonidXWpSVPgXy75f9B6ADC/mBMpIbNRIlKZ02Afb3leWcmGcLfyVBW3t7Pb33v7bv/9weHRyd9Pz84//PKrOvwZR3gNgpPvjVU8jLpC'
    'NR1RYjzHZTRCOwkvHnprZ+RgidE+95ViyACxokB6FVwPRI0lhfNmUAMBEW+OFMJpc1kaI4W4trsnnVd+wyjLIuyzRBD1hUB7Q/YfxN84PwzTYJq5NgHe+gZl'
    'Do7oN4ncSYABSPU9oDr8p7OZFFNVfee8CxMR7xh28cvFCpM/QxVcT09oA8Y9F1ShJMLOX8bjcTRvmD0t2zbogouQDFQtvYV3HDKCCJPL+M6eRN6tqjcrgwih'
    'rkafZpYlrJ7zbwNrNVmBZA902gewhmb4cNEM1nmAJZpWALNHNUkVHPLF9iIVB60I/uGjVqasiqUjaL2h6d135LvcHmTmmJKu37AVFfPKQb31OdhyVjEbGocK'
    't9pnuGZENIEV6QCLxM4IG0/WOFyYvgo8NfqNvSvIWbB8ILhR9KiQ7RufefeWcHMnvzzdr0rhavcLriqfH+4Q7WZqJCV7W0klTYsdJDdzACxoKHg5AWRYarsq'
    'c7OQjtgiJpuRQUvjhY1TsFwkZnzLj1ss5l9pXdkL+ZVnXtwTTSJoNT/DBrqg6IskLPClHVr0dHfLXO5rNh1PeN8WfCBpJBItl1H2KQKG22qyvmoUl8lfJlUO'
    'vH/Agb82lXEAo28/2+ebGVnAmUg4KjD+w9toR+bzEkkTKoP961u3HF64oQB5UsUo/2DFQa6KXW3ESV4XzVhDLUD+iujGOgNX2UV3K8ry+mIcEJkwPQtvIm3n'
    'YkOoukks8hLlsT+aYPIvy7I5kFWG8ihCvqCTnrLUtEbOBpQ3J1cDN8I8o2G2SNxhPsDjSbyMUDMyFFw2raXQbcwT65xlGHQ8GZ/RizqqtQHeBxJBtuk5zcZM'
    '+jl//jqbYNFKJ3p6qjpaL/gEAs8Pp9l9F0/W+Ccar3dERAN4S37nDt3fTrAU/zLd8/WdrrsAd1CK1QEl5TMBAC6nYcKD5aGuY9mgKxLf0xfZyCQFZhiFh15Z'
    'tczBD73y+SrNF1wyY5ewVwRl04YfoNABATr7sGNjsYArCrIDT+RmBsgsRbEFAk8Q8DP+xRplyFqL3tpjsEgeoLm0XlQPIwCcYeaheBJH4/d7eHdsHtBumHaf'
    '+3aYlSLMNcxhRPcWdxT6d2iRQivJzoe6QnkXEe07fCLbdUVIKEwXcdsd3VJy0Gh2KTpQYCHnsLHlgrQ/2LQ95V/ZfmFVVy9kjwzlcn3CO6+CaO081o9jL6dU'
    'd4+q6tHaRDvXo04lQZnviOJG6IqXoFc6fFUPeeJFOhzDBFwLWsP4QywLpkw7imDzHwqUa5aYRuGkrCa+V+tBHPnQcjOf8328XCwyzKm17GKUZQSp3vBIi0tm'
    'Ts4j3e2WDenBlZSfSTP5+OPmsY81z7Hi/87iv3oWK/LFP25C3wGQtwLGGwGiamrzm0hZODr8bL4uzsS6HRkfcBqCOQw0NYvot6UQq8jkobm2x9dG+Wk1DRMR'
    '8NAYU/6T6i7dDTE6is8FyHbcN5lE+tEzTslyri5nbkGAll9QfJ5eXT6KBKB84+Dtm8OqaV9c/gNj1d5GXZevyaCr+Aar3MbthrSCAftxdm719Os3a6bemAF6'
    'wfMDMz66jqdjOe8mKVgfCpBRfaRPuq/qFUuf8imYJNFvErD9tigGLabi8+U9sl8NPP+F2gCSC8Lp8jrU5dSrAmz8wsqwXZrffTMzcrSuBOK7kLdAFhhFeCAR'
    'fIpTKYRxXLUYpMs8VI7nFZC6746WKzdP8LnQmirikryMJG47mSEIuJDvfJSeYLbB0AoCx/XqH72y++iImygtqy0+Bbger+FTJoNB+Y4rv7ke5+ql95g/StWS'
    'uUelLIbm6wW2pMFiLkcK1eykN7QifnQmIkQgNDgfoy8JCL5R4ohAaiJxKMaWWGTr+oQnXvnPGIwUCD+Llqlr2BHXIMCoIZxp3Pz4YEgiCAbU5mQPCiBeRhs0'
    'h5i7zbw2Nej4WG1YdbsV4yxZcfSwnnGbFR9LIvsUrvZQbkgOh1OifgsMrDNEvOc0eJx55kEFfeCa6YTw/F5h95H5ajbJ2GLkrSH8Wzk9jKgmVmYPp5C/RSex'
    '4bKVaWzwHNV3MK8GNmsl8nCKSVgeSmjjqOQc5TjaLKvNPxlPsB+V5kUsy3fDmMqnLxFZbxjKmrw3oqLv5DLfOGbqm/Vox84+cSgDTh7FG2bBKc+B4nDWGqck'
    '58mGeU+snDiAitKsOI4Rj9nFtDhuCQB5ybMQzNkpy47z51FLIWEO9ZCLPZg2xynkzTFqG9lznDS/7NLS+Q+5ppVGp5QQy3PpFOk5zBGzQU+PzqlTQVN2khtH'
    'Z9b5Q8jMzF1jUktVkh0nl2WnhHDucv1RlQWDsBLuOKUZd5xCyh0z7Y7zg/NA4h3ruLs0/Y6QdVzKv4OyOwYjd4VTpTj8ZHLeOA2P0/QkHDMRj2sk4inTXygd'
    'j6G83JVPQ7vFh5SsuJh5OYTWVZ1loQA1lynHtZLzELjcJyNVTqk92D4K4Dw6eM4YuTazwhD1gI+7R/SrXd2v9p/cr3VpfgQjHFaMxI7a7xpR+2kYj8BJMXi/'
    'K8L2uxi236jGEmSR35uNSVMpVRShqvIEyXlZ/rkUuS5hjDWrqsHq7DFCSyxND2RLG4W8Ga6ZTEbAqc4m4xY+WkTorZnUP5U8zNwOfy6R6JQl/93IxY6p+y+h'
    'lodyEbm5XEQ01f9axvTPoLySPEUG8Y2Fwk39yWUrcg2kAHlVk+l4M3J8KHcRwhHyQCF7kWtkL+LoGRln3qmWOMpSGUnBUzZkZ/FxzWRGDyQ0cvMJjVwroZHs'
    'o9m9ksxGhR24mOrILUl1VLp553MfufncR6W1ShZeIRlSaUVC4MTF9EifRQqfL27uELt+Rxp+PleSnDtbXL2zp7I8cdDElZmTdKPQDIi4+N4GOJmsWcnlGZQ2'
    'WNQlkIsruyyRkptPpFTVx3Gx2Ia44axKecyYwPJyWllqpf8+LLEYW7TaOMyJcOCRmrCyL2HDgmPoCqq8nYNp4zxMVQcaxr3Ch47BrLRMVj3+QvNhZWUqFmoX'
    'z5msBE1WDfFJnANY+ZmscvKbvWPrn3QI6Jaka3JNxz2hvxKSlXN3tAxkNpZHGO3rH30nl7nFMVK3OJW5WyrMykvbqLw0TcrLNQbl5R8Sv0fek2frsfOuf3DS'
    'P/12p77e4QnM4cnpMUA7/zV4e3p8cXKmcmHU3dE13pQCVXDg9nbQFZI8IdkR0nfc3T7++/5UTXrdvb7HlXy9uORAfFhzZw+qffgFi/bevjs5Oxd13x/93aw5'
    'F+wN2Ogt4BjjeISgkYjGd99CRazX3z84+vsHirn67v3hKXREg1gu8KTVbvZXblfU3u2/yzXLdX4Xx0Lc2u5bLr2DjZ1UtcYR6ZGe0yxZsdkeq+++PTo5o1ah'
    'sYNDaA1B7e0T1ozq6H0Gom44wqwVsdk+oHr/gDH27tBE2OnfCcBQrI1wtoTFgVFnk/iSr+4pGw9ae4CDyXMKPvKBd538OS4GRh463zvP2TKHUfNFYHYobZ68'
    'DFpNDPP5PUIZQJUnzlz7nmO0b7ql22y0n1OcZYq2/PL5UDeIktsMLw/CqgNOzE19T1WtvNZ0KwGPergd6PsNXVLhozJ8e4PXsIbmLiF9vmUfFRjopRpEvhCC'
    'wljVqkzhEIgxLK9j31I4KfQrN8+A2JOenVt/8xo4Gcu611gtycjIXq0Co+SRLnKK5Zz3A9+hq/x4E9EpXZd2VDUqjGW5VrVBcRBzVH3YNEMsH9H9f7zUB72h'
    'hD1JBvIxopkLEMChBQ+7K68yPkR00gw690ziMdg0AjO8t4kF5y5i4Fzpe72t5nN/7fyIoLDjiZgReYixbNzC8EY39UH5PPLdppSj01m+4oa//NAzUiIRnDon'
    '0RlPfAdD7NAPnQZJZz7KmmjPLck5JlLMwVer/xKsCCtJBeS7Sid5ibmP0W0enuicZwk6D7nUWS4aLdTRtNeVewV7oevnXWdqZe5S7GnVLvGrafE79idQaQL4'
    'GwZpr5luGsqhqtUq+Plov514tlwh44dejZIoxC3eBKS9rdjVYLG45FCS0qVGuDO0cs41JZEtddI9ByR9KgjLR4ApcZQYjZbCF6MwNOlconFoipiYixDTECId'
    'SA94kZ0M86CUUxawxaxZTFQjyJIyveh8YkQrjeXN1M1FezSSuDjup8tCUEe+z80Jx4RENtFhXbvi87v9t+8o0Njp8fnxzvGBZ2UAKnWwiG49PN233AFyvhSm'
    'V8DQiLJohOA0RmukFKQNeQZsFe/IbSNFU0Rb53TvR0cUoy0StggMzHI5jVz7RhxHfzVxY01IjaSp/dPgFBG+tbWF50nOT9sYfHwGRNWDR1rhqHUdz6f33fPT'
    'i75XQ++ueAIt1/nuSJ3OoXCczw9kWke6ww+g8NOgNfyR2Y71tg1vZQYc4/VTeI1Itt8+g7eIJaRtepkiJ4mugITo+3PgeSnsX+hqfwL8E9TFM6Tz1fIQ3sBT'
    'Wv9MTsiAbaAiYHg/OvJ5FALCjGc8gADW5X3xamK2gbEQXuowH8vrGP4/FcKi+y4nPbrLffjn8BP8syNEUffjqNXoib+n4u+R+Lsr/u6Iv33x9+/i71vx9534'
    'uy/+Hoi/78XfQ/F3T/w9EX/PxN9z8fcX8fdX8fcD/W032B7VaNmPbRcnFMeOV9aRKOt6fnEnToA00l66R5lU0+5e7+CsL0iOnGnEKwwVaEFR5PAoIJryUGkZ'
    'oUD7WzCnox/6GYbw44B2Hc/5azz/K/qhEQTotufhWP5Cn7EvnP21Ll+hl+ctRmQHsG+uAM75let5SLiFKvJVeRVoZELUEk5HK0z3qnYEaGvgl/YaL+dS6tho'
    'juG3AVtVIKLbDUHYuDIIOY+XCZ3JrysDvUHkUVhs7BbUGfi6tM/3v3GKYJVSKY0yid5aFl7SM/IphXSvJvJC4qd4gtKy+sbxFAGtIE49gfUug0ABBOAonvc9'
    'ZUYpfmuLb15tlCWiD0CyItVcXV4wAJ6Kyg+x6ZME91LB3aKML3JJdiOyWCtAde7d/+00QCTE7LoTjtWrbi7czk7DcUyxfrJENNvFvuCOE51wzj+kmVGEeyBO'
    'IV5QcGEaZIpl8RcArObR2yQed7GlBgcmR+sRbc4v/R1MsFrDvQi7l7M5zKNP1D+YvqrpggboxBwhuCbNxJhfEy9y1RUVYBk0qZi0DlXC2+h090y2qRk6TC1u'
    'c7Tazc7Li6rQrb9IKlbhz7vGXGJ7A2qHvFBLuYTn673Cx9vENr+APc2WhONkU0n4OppycFA2XFAQX9yfCQju/uMVCYHA0EW0jtFNwJXq/Md3xO5qykIito2x'
    '4TNA+kqbPtsD1W5ZUhY/6qLGFrpGbIqTRjJOuYbeXUuAhxgMToXCT3U7JNtXXkiW7KhjiP8Vd5Ltq8jIuqxKpRqNUedA3E9W4lZR3yiEu/YFI0HKta/6kgqy'
    'wagErTxqULrOo8ekqn7FkLJE5qk2t2rzSj1uarKMsRFbCaxF2rYxelel13gpFboWj67rLr2F/RX1UJF2tnG9AMxhsix0OI+pxNMnl/H8iShsasocUA3fe7n4'
    'Y2u1T0rvOxvXB1TVp6wDOP5t+vcqmoNqkAWJjFQL705T0AOXFJJme/s2nMfTKYZGE6vTPisyUWWgRC8ui9HY2XBzF2VwAHhY9erFM9RFaQa7vLoczTcc0JZc'
    'GTFjI/1IpGwwwwepLhmaCqjSaGTGT0ZwF3ysJF5voFIWDDUg7JCCSMEhHloEhqZv+Js/QtthJE3iOxip2kYRUz9y1vrN1Z7UnjtL43l72jv843Sel3+qziON'
    'gvaX56gNRXi/OLm3v7x4QE96+Qg9KQUlwFCLLuPFVWK9ocPmBPUkQ9iELQP0HtikocmrKDsVjvwiNI77tPGCtIper93EDsIQyO4CqtXp0e5O/+9osn9/uHdy'
    'dv7Lr2TGhv+IIngmBoDZYe3svHceHPUO+2dCL1M2GcrJAVoYB5EK5/o30BI+wTzhLfZxxL8XqSoR68LhHfycLuYY50OUobJBqwk/sbGgGTRhIPKh0Yb/nunH'
    'Z/DfC/34Av57pR9fBS1AAd2YB1mHNIvVfCQcQZarjKQSFZOZghSyREMBuZZxhIFUoNYU18A9WkUDCs8DApACgFK9huqJUF44N6mFd1n+L3KXouykZVj/0Zlj'
    'd7llXgUEztt+fQCUqkiAS/3cbR3IgDOJsO+RDF2/zfWaipu9JQuVx30d0EOH3/3w+gDVHE1greaBh0qaElJ1Wx5JxBj6oVl3P7q+bI6qUL+usMRRL1Dggh9B'
    'B6lbePc+wxuFIh41IAgG1zpw/vY3p/jpp24LesnA3UGr5bdeD10+BygHBcWrILVfKEj11mu//WLocoo0Q6DWI1Y5iQSBd5NoaUyv5Nk4vwrnWBtkcYGn8sLu'
    'TGNPVPRkviNqA9Y8xmVAbUGPArc9qN1FMtDtia6JYCyytmRRRRwYVcnITzWu9MtHGA9QQPqRbPuAz/GiQd7NCQgpY59XFHyFBcR0hFdyfto+ujg4oCq1LzXa'
    'kYMZusdYCxYxCMt1DnpV6n2e/bQN4xHWbP408K+w0+7/BURo0SmtUUMZg/YFj+106NgZoyKrN0b7+CKtz9MuNdodpzg93Zm/6iJX9bwvNZGQVloNyjqM6aIB'
    'T6tsMSEj9nPvM16++Gmbv/+FT2vYEFBXhOwrQoTeYnisn7ZVD/HRsHUwfQho/DTAFoa+spBDF+iVb+mkhvU+BhE3HP9jlWZd980711c5krot/7dVPLoh9uSj'
    '3JR2W9FzZAWrrI498S9BTLpBPbvp8yh90JWJkcnJxFxrpaiJZ8s/fypFprdoXJ/52CBMm9hxrD7deZ9TmBXFr8VSNRTlu58pQyh0CPaDFLR5UAjcpiuZNqyl'
    'n7ZX8zlr38x6l/4cuR6yTmBKgpnDnwH893Nz6HW7TU+eXurXQFdZmNnUtJwBixyn2AKFNbT2/+XsLzZL8niNQXGxdWEONL1Ljb3P45+2l7NBoWK3G49929C0'
    'pPmRSBj/hTLxAXiAzWisL+ERxi6Gh0+mIcKGD+AFxRrcbCzptgWMyBIxupRjesmYV8KGeKveoMjR5T/4Voke3blP4kQXb6BYQGIoHxsgwrsu3miBZ0MaoVeJ'
    '50uRhMAkP6PZz9eyCQP/CdZ223sy9005RbXb/hsVeGYUIMlFFXjGBV4YBUiWUQVecIFXRgGQbtTnV/i5hR8rOHWRUQsu/dO2zaMpt201hxYz9dO2sNHqVwzu'
    'yxo79sZdQ5G+woz9CBgguVtALEl+c0Al1nAdmVXbHHwZj1VG+iqzjLMB+KtBRLcIgsRPGAxwj6dPX7RBziozpmbJDEcvhV9o3icRE3Frf4lufTHSkDU0tQFC'
    'pZk/qrd85MZt/xm0TmHcmn7Tb/lt/ynymcuftotVnsI3Lov7AqwX/NNiGfKh8i0u3xLlgSqhBtJmPfQv/ZE5IXNADabaVKhAFTTjS0UKa/gdRnD1F3nIj69B'
    'NoXNgCR0ew+nDuGeTXu1KW8L/oZ7yM/d9gF8K7W8mq10sbBvKZd+wXrK4gA0u4kskExa2BasWt2i3j7VRg/tWvskMl3kuOowZmaJCoANAPzTNmuanQ7/rY8j'
    'dIqJ5lnjFrZWyhgt7nqFieuT0Vv0x2dUcCgfFhaMK/X8AraQBoWI6babzaYvz8t53SHRdjX1LjPYX6SdHdrwK4dbGCoKH65hWnWHQzRvQw9c2M2yGeOaftFe'
    'Bu1kCc4zbv6w7dbhA6Kj/Sh0XGFwZsJImtHJkXynVWhLcnkcwp4X8DUSDhojdnWl8jkckgEEtmVcVcmEJHmcLh9+i/0Rn9uIQO1MgQT7I5/W8FkDMH83ZCVt'
    '6gKarHMI8xgiuuWVqoQuYCwscYEMEd1uMJ0E4eH5g4kByPxTzmB0izacW2MK27h20URlNtw2G07xjE9Pj01E1X146LzFksxSPH2xRTO/5AyGswn7VYcv2iT6'
    '8NELir5/wOELgtn8+IVNfQ8ewBBQfQTz45rzFyr6NScwWJHOYH5ccwBD0CuPYAxHw5JqipvLNaMrYswV9KuzY7fr/V3FbFfRU4cGykDvQQDDTY4V2EBsFV97'
    'whBNp+2nVgo+M7kmDk9lkGi9lGgUye44689pIAJ4YszLAPCCymBw+7yB0EAJMpP4kJWYTwVUZhfqASVcwooYhVyeG6AWB7CDZLFYV9xonqok0/hyTXFhPJX3'
    'llAY7OrkolUjJilCeQNKidE4MJzjQZaOZmrGcKZo6OTp6p4G744P0cXkNDjYf3OmfgQXZ/1Teuoffdg/PT4yf+uPJ6fHe/sHffO3/njYe9//0DsVsAwnWuhS'
    'Y7lY1m98Bx3HPNlhjOZ+/k7FWVWoRhTEmJj3BxwQUk4aLeEB4VxhlFuqhjZKA5Q5DgkRZ4LnUH0/2z/v298fcfIkSKf8POmxR0hitVLso+KJEna6C//56jip'
    '9bL9yjhP6s2Wb4Ew/rwTpR///Y+TJI6yTwvcf68ivh6X4JXOeBn9oYdKZzu9oyPMIverOFjCEPSUZAnZgQi6gzyhJn7zH4w2joervoO+7+zKCZDv05oZmfh9'
    '/7R3Frzp7bzvH+26QxDsVPQe2E7MkjsXu73gw/7Z/htYmrv9D5jlAivkih0fngRHF4fB+TvMI0olWrkih+8PHioCn/sfT04fKna+F+ycnASH+0fBwfHb4KD/'
    'oX+A5dquxAVNMrpszpeYPWs+hp/w/yWsjnycIgwRg9GJCL1v4oVE7Vn02/4xv6UC8j2GlgLhGCu/Nz6jH+eSPXEwSIYoLHfEGmfq6RIPh8logMx8i0agH1Go'
    'yL1u4+uj46Pc66f4+kOx+DN6Xyz/HN9j2sLc+xf4/vjiPPf6Jb7GONXs8itfvxKlG7MbzC69DPFusrj5TPkgg8WNiKAqMwhAVXFGB4t7shh02sNuFxTfFwBJ'
    'lMkmjSCQhYIuTHGj3cBpVtkPEKV2kXYDT8Bq74lrpCICMgA6Ez85XjUGCdmhXyfojIs8MAkxYDX0HOSgCJQEkMyuE7pt2vLxoCCp/izCrhGr6352355cuJ3m'
    'F3L8mxRCaiPy0EBoh+8Wbwuvaqg5dO1F28B3nGsCvRgCYGp80xFlMuCA4Xwesa+QiyJ0nakKbQfARvKw4NWKoulh/1BLwX+QC8MfSlMVJQ1KHs0FUdHxRIjz'
    '31LO09ZRF2TqSSMeU5sJZh/w+NpAgkIALRTYVZOUuCzX9F3K+e56QwIJa6DOmUtTDVQuDqir8y6k9QEGBGuEYRvmZhBycg+6lJEOxS0Ruq0gwA39WXiHLoqc'
    'ES1LutR9WCY4FfIRVgcS323Ijx/EZ/XM36NbfsRFg3alLoD7YY46833XuLwB6/Z7PLqCr94PgyY/zNEBJ5dXAwTzrqYGvnVwhl71TAG4jWIKMpphhHGPM/mx'
    'i8gCaIPlEBu+h7+1W+jLbfgDdBhe3ZZ25jY0OgMPxc58/ECgbxOhMdOu04W1/SSnWQhCu203rp+7XBavgMornyIW3Ef/3v/4wb+/9VFVlpkqyU6Qyph5vPP7'
    'oPtdRawPBXgvHfZplZuvT52KbqV80K2+zdj3jduMT9u+vstoX1+03a/M5BbqIhCFDoxuh76SLDr054sntQzCS5nm5FtKR0EtVcgzdFOdiembVFUF2tRXl/dr'
    'FVYtRghJjnR0qU64T9DR6sly9ET6O/H39Ak0ty3a24YGXz992nzejtpPXzx/8bQ1iV4/bb5+9ep1u9VuRtHzp8+j5mX49FUL3bi4r4pbQWVGRDZpqc7C5sw9'
    'KHf0gp0+VT2yBr5I4ivyA1veZ9egjrEf2GzZFUh84goqmy0bkxA2lPlinv8Gr9Rn4ADqqzFL+vu89LsJAriGKoL0Qro8fDGES74UQxwx1WQBEHwAJM2rdimb'
    'ZG5D/1YXpCLSpc+HpSNUjm6JcP6j1jaW974gDJ5k2QGGDnB8MQ4/rzzkVAapMQB18cR8aBfUhh+lNFvWqW1DX+ia2oKFyPzCMzWI7tfqDwJG2v0zVYcntuJg'
    'Y2oxmcQjdkNDt7RWc5u1BrEyyTlNahAcQJgUCY59Oi7XIlS7axh5Tr/on5z8uoFyQR8QDUoAPqMM7Udom1uGINqK16Bu8K0nH5UN8dIWvS2pXMRrrZC7/yh5'
    'uUT+fVYu/z4vl39fPFr+dRsiVRmuojsWlO5IfikIxk/xYNx92njVeKplX4GYnPTbbLSfgoRcQyCcfXSOpevNnCBI6AzxktfyXqKUHhHvsJ/aJRqyDVnUaFR1'
    'KC+pN93a6NOY0NeAH8hjFmgKRvxgZwBbdGkFs0ag2MCXHHJkU5cRiUlYQHnMn0dXoXqDEhkZqqWNiu8I4qVBCv/cevncx9sp9NB+ykcCOH14mBAITQx9OOiZ'
    'DxdaL5o+/grQnUNcWJQWMB5/CBKo2Nk9zn07ve/Yo4MRe0KAYtmJUNmQxwYyvxlJLtobmcwgSfiJq0hDucHgMjS8IbaktJPHF7eoJCuPPKgQOr0jkdUHHq1f'
    'ySZL0IhXPLoFKw2UBaDLrvufaPb5zjmWjArALlcZhQJJ8fYnOZkgRVMyuvarhiJ942QngDl1sdBS5tSksBHkzQ7c1fqyRmJbDmQN29ddy23LQaFZVZR59bcL'
    'ddESGP+jzhq6hviGNEIgHiG3CfZsCm3dB0U2WtPBLSzRIAxbkxevn41ejC6fjpuvL1svLkevn758dRmNX76cPH8dPZu0opevmmI/Wd53DXHsyTphjAZy2/oj'
    'pbAqEerHR8lPf7RY9GiBSLLd/5WF1shCEklIpdZN/K91y9d4MhixJezsP4MF9dWGVBBshBn138SKenzSP3pzAD37Q82olihXMKIaNtRKa6mvQ0SZRcknC8up'
    'ShSGakdJsmZZDoIlC1LIXp8DwvoY19Gn6FhmBb69Y0H26WyQAyyd7LwoEzLPezBRZWJmUfp8Wi59Pquw1j6vsNa+qJBWX5ZLq6/KpdXX/wxp9UXjtbvOkvsa'
    'JMQHLLntxjO3VmIlLbedVtta/4sYgx9lyl2OXrD1FmgPJXZ4/lbTLYDwlJ2VLbc1B3aT0YvGyU7wwjDLCjd5NJb+qLLYoN/MuIEJiTGlmWF/E19ULmrfjljz'
    'tO3V4tC/C8mExzbVeD737+b0go2q8S2UuOUiwu4a30KZWy4kTK/xOPLvInrD1teP2ArMImAtmqPJdHAHcOZI3/eFT/AMUm1KRtS7kMeAYTnFmzls2Z6RcVZ2'
    '/ivtsx9Ny+zHD8WO0oi5q7fr+3pb7OxtVW9r8XzZLQQpJxK664qg2C+e+a0XfiEYoW+HtfbwXgRVo1i4GOGmPBIyhhMkZ9eujDpYFXRQ3ELrcgRBAI+6iFCT'
    'VKhAHSEwHx9wmuCNgWYTfSOro+TNoiyJR2l34Iaj0SoJR+T0QDZh8mCmFVxvNp6TEfwjO1WiqlewccfPUPa8fu6yqaVrxJvx733T9oaObnUyc4PGZWZMJEGF'
    'PPxMqzT99NWO1h3k9jJaitgnz58t5jGmKUS7YkCJwciQHuDXYEE3BbEduqzl0l0ybe8eGr/zyhN1zO1QsmGRZh7RgeNsCLlKJiLzfmh5Pv/ulH33dd9y39X7'
    'YU65soQ9S6m6nHX1xqvxUGb3v5wpNfguKqK3wu7/o1OtRiJ/+YNN/URD32Tkz+mIBHBjFVEKtUJ/G70A6A9piLDjbGOMoiieb1McX+AJ2xxmImg9n7yOXr9+'
    '/XLcfjFpjS8vX7x68XT8etR6/epV6/L5aPLs9aT5/OnTxyqMPKppdAXL9d/Ecv/jf1GzPU/yE/eEpzDoiylEQlEfYYZH7uNN++3nr9uGaZ+o63+mIruJaV3t'
    'Hzmj+sH+3q9/jKKJfuwoOP53Ujj/FPeejfXSb/DtKWiofcxKeSaSUnJJabbnc2/2xjMM67lMzP+OBxxQ+3Snyx1/4qbJCL3ky48jTne8b9MwX67VMFvt/3Eq'
    'JoodQEoU89yXKl66qdJJtZQWiNL6wyoncuZSPyGtOc7w8hVCIgelaTy5F2f97KIEZGDs6vgZdyqU0/K12EtUV4I1oIqzxAUI+gN9kkB2QIDCDYgfhA8QP5AS'
    'Ch0N4wSE+HrqtzzT+Sgc/oAvm9bL+VC5ebEuWW+1n3oNoTXUCRZtob+l/n3a/T1e1r+XLy0HI+D+ReedLqAaNcfgepEFQp9jBR0Bej6q9KU67sc+7KvFqoPU'
    '7Hs0rAJQmwC7SrvU0pp08pZuZEUQfQ5g+aYx6FZk8IDJBqQCtq7xDib9knHKBsMahVIG6H49i/3b2LMD9lJvYDb4bBFkFUQL56lkxQIv9Vx2LQZdt1Qt0B1d'
    'Ojrk9GGod7ZwRcWo+EJvfTRGoxhBipjsmOCA16aqOMjioX9P/wptsNW01UF0Uiook4NbqnaLwQh0LFVDZxxdIk/+tCS9VS8SHHrw1zGKHX/F31LpbpDaKDpK'
    '5P5piXgWb2TE509LiXv55ps9rbwfa8KfCnVBe6KupbLILvas4A4wXQhPu+zEZxfH4nZoyqXyGv/Qknop/mvpoTZcrTwPOCS/Ow/nsMTJBFDZB28QDzHKjFQ8'
    '6Zq1jpVMWPJ8SpvSXKtX5hzKvtmfLNcWYSoHwqSGam2bQtkKGbJBIW3F0XzeR4SAPSdokmCgWuPqd7z0/6mDf0mWCpMOTzZF3BZFO/i+ARyFuSygLBmRB+CS'
    'Lm+VnKRic994kip2jE1PUoVM/piTVLH90Elqoxlc4lnquPX6xauXT1+9fDEaP386boeTy1fhy9brp6/wG3watx5/lipa+d+zVNBAXzSf2c5liJz/mSrod85O'
    'CFjDkBGI222KCqsORfEicwpS0G+rGO/bwHYMW+KPmGU8hMU+ps1TFY5TxAbIybcYAi1CsTOLpvcNcZFrOr6uQFQVm+EektWUqjfoLvflfV3wbj9MA5MTDYQx'
    '0eDhw6FguHwpVBs7RVi/bDGDt4JczU5Z7A4fBgPZakkjj/GUq+aCpob/zUlMDo533jsnp8e7Fzvn+8dHwsfXYZ3qzHnT3zs+7Tu9o1/h59HOu8Pe6Xvn/LS3'
    'f7R/9PabM50IPiob64oIXhwkz+049Ycjk+oQpL6qi9cJy2sXr9aad2g1BOWmWA6myu0579+sAaKLSjmsEi8cy91GwiADTxmIMiOtaY3VnUCSKu9EyQZm7VR+'
    '7YucrHe9s3c8V19IMA7YWus7dXFnLMiiu4xkZHt6G7B4Zmld7KQWtIEAMqRrsnrPtCDKlCn0spGCcB/fUbw97K2+iimPdqgS3zoUPv+Oi0qj6/0Ry+b04sjp'
    'f+zvXOCi+XZwf2RvnP/v//l/eYk6P4h1vA264/5uj74eHx38WvsOKp3t7PePzvf39necN8cXR7u9U3jvbBf/B2/Jre5p2zm8ODt3joBskD1L/+DzPrxEsZDc'
    '6awiUBUTlCRz2DY4KgMVbDj7mYM5IbIoRe/P36O5BKaZYOpDba2rOMYm6VNLXGPbKKJiZ6UOcvAGAOjjUTF/hY0ndDDUeELjaXwz+yIpkgQWimM0jyeon1F/'
    '6jBMz9n+GbNcTDvqji1e4hQXHchKsPjUkAKmTN4soBTvzuNP+ZlvfptJhKyK2s2zkFiItkBx8/2+Y6S+4OrWPXULpk4GhJktZT9Ii0GtepWCVI4dgXX/2SXy'
    '6+9SaiigvYveOT/sHANP6Z/33S+dshTZunOl7SAG8HTX+T/icrNAXzz2vgaczCFnA1SZ5b4GpHCjRbUaJDYbsP1tQ/AoluaaiNDlniDjR4KMcutm8Mhb14LH'
    'AjfJR8FNdC9Ay07nvn51K4bNoaqpsiJf3Z5ANsXrq2qwtMyGLboqhGaYZDGG9kldSf6yJ5tBMi93mz0q6AQNsn2nde/b4AqXBRE74huASsb+OCBKSeg6JXRo'
    'I9QHGcMr1AzY61sKiyrCOFu/eVx2uGqT+gq2jsqSajMpBWkJ/vYnqMZae77iF502l88J7CEB105Xl8Ab6vif/ObZaXATkIw4/sI8Q2VqroDY8pVKC2RtIqK2'
    'nWtaZKEr2zTWTqXBopYN3APqmGeNLHSKPVEvQdeEd8HlPRCgO3wk+PQ6bD9/wT1bqvUr4dLHzWEaKlZCibeKnMMuQtc/aP/jaBzWLohos4tvsAAqckDZcKpb'
    'qZql8raWAZNJfrGZqqZYbrnVJibWaLhihmUbgu/qifYdtMduyMCNSdZNqtnOtcGTzvOxEcuhl6jOczCVu1G0zJw+/YGVXiEjsXi3Wo4xOc00GmMYMpY2KM+g'
    '73z/PX9MRSe4TDBffMKZFfYLDuFTBwk9OOjvvkW9sHf+Tgp7lDdb1xtIEceyyGA2BNqzWNSxMg2wfJDeNDAaJccfb7FYSNlNsvvgMppwci/dDNmBsJYvcooS'
    '2/rH4hI+upx2QMRPUiKS+k22FQqtZIs6FGwJJBOCNxwWgvNE9+SPtIqQZQm8FTmWOj8lzmb0WFzL8Z2JezG/gTfyKxubOs5nqPPF1ZltywYLRVDDpG7YSAon'
    'Gd1w/pfhaDlu4O6MrjOMg4BimwUcT1EvFXtW8eRDGQYphhrZrPxieRrgg8Vp6QV80seX0YwMeAUjWI6mfQN70tBFauJmi0FMPR6ScD0i5hevmjVrw8QvxjIB'
    'bshReU1tzJQimHHQcWuHFC+ZpZj1K1LFtHojmrF1KNNoZ6ZO0ayuw5sg2SVsLmkmTWG21bF3NLJMcG4TMQQM2xImIjgBDoUoIaXlj1plRxpkT/fP93d6Bx3S'
    'dZUyToq/Vo8dQ/UHqJjqNUpiTunbsCKgATbGEz5uV9Kw4jtluoBKmqr9yx6EUSrki6zfBgWopJtIA6TmWH2YF0jG6kWhlultZ1VFQUsn15Hr1DapI7DP5hhy'
    'ityXPECrL38YVCN/EB5dl4FjGdp9qEPV9XVBd137FWcPsGLGcfoPcio2MgcX26+oX0w5XuHKKhYKWvNWmbFQAJW5VcJ8QsZCE5gW+6gR2LBQxE4vb09Nrmhu'
    '3kRwMlJwTBLkuKC0HeIl3qDMGmT0jy1C5hyonmIm4oODYH/3zJoiu49QqP/xpL9z3t8NYPX3zvrndvGI78uqQuhbZJVAsdPqqtLyfEdPr7uHRRDPDhShDL73'
    'TjhFLn3vcAXKYYo5CUI5i9C0MBA9UdahJ9I0pCXV/5zr/dw9jSYrimOVAtsE2XlxGyW0FXXMYhP3s9VnIREITNrDYb+yMiczJ3cxiaY0C6+Qxow5A+FlSYfZ'
    'AAJ/a6wAC5/Ed127PdTxnB8ct4ERE5+2AwGxYSiI6DCNlFDWUbFLSKqwrHcV64SD2q3dTMx1Gsww7n7CvmZMr+rzd84HvGV974ymi3QF+wgGhcbpQOEuA2XY'
    'oa0drbuOkDgncUbyjJYuuGpgbr0m3cvvkgAMZUvQpAkhtz9Lc5yxSnaOj85Pjw9A0sDFYisKchmYeocBnPhhWd+4gm4S0wfYkNNoOskMC25hmKpAyTitFWrA'
    'KRksZfG+5GPUQBWG/lE2Mz0sC05pSxVQcmzO+GZhgDWqJcdlvVzNx9PI7gWew9QL6rnZxZOLNwf7Z+9gnk6PL877AU1cb+fckA7N/8EaMte8fl06kE2ql6Kl'
    'dFDrqcI4hEJbFKD8Hq3pRVuVkF87YoPKGZCURtFR9JwrkVMsOjn2ny+NSkeHHVrsLxTRAcO6MssAvSXDVIDmGMuKeOvBmOFi1wIzCuZB5s3SNpy8KFptxauC'
    'UCqIlmM5Z0TulG3/OSNyDpDg+HxUlEi3YIDk3j5Drit0LlgNd3ljYhaNrsntgj5CjUMoHo174zHFKullGWp4izmSK2VsBlVgFOK2C7txFKOPhfCvZHNDtkDP'
    'YjyVknwaHikjI/rxgIowuoZNdYSBOZ5cQ58S9M+YRbAvPEHieiITimOGqjmmfi4daQqqLRLS58Lqc2FbQMSh0uTy6aTQWfBgMgdOUK9wXM9Xyx1qltY1Zgdl'
    'Eqht6LVWUWnODvic8qHiJuRInTGuqSAR136w+Jc8TnP7oqBAa7+qqKJ1zmquVWaffsROarM6dK0Z3ajYe/yRohEfHu/2D5C17+2/PRtI6MM1O2kF5OXqchqn'
    '1xgehtgVAqdfwacEPTgTMx72wGXPghR+Ftssa6WwPetYypUb+GYApbHaecTOmpsIy2uiaPPON609OoRHhdkH2wNDI0cLXabBhw6ETSH4Se7EJde4sRniiqfc'
    'dmsCUBcs4xgUSJ9Oi8iNghNx3Xyhq+UqWEbhTYCqQRKPI1lgM6oedF4MbYxyTuwuZ2vhpA/Ih9mpW23MjtbsbHE8Ht9BZcOjef9ot/9xsG4bG/pOzs3egoue'
    'ZBtALd3aHgD9kTcnG/THYOegd3aGRqaBGpMJSHnkm6Duy0D9Wg6gtCfQ/+p+CByU9qJMihMDa5CH+KA5RBHOsjCVV0IX1XwV28ZUJBV2wef2fImGEsrAFfRQ'
    '+HK1ZvIEIHuwyYKSNEOehqgMigBngRGdSmY1pyF7la090N18x+ypsBZ2nofok6gR55GfRuPG8mZqS+jkPE5O47qC77ifLtkXfFLkhRz6rzFegWIuxjjB8PS8'
    'C3fF53f7b99hJoaT0+Pz453jAxsDhQhCRTXGHk31qbCwTki28QWdprcxCSCdMDpo+58Bw00eiDfk5/QWY/tcz91edHLcrTgWRSrFnhtIL3zL07RfBjhHSMUy'
    'pSy+WKzA5HMIEWeqmpSCcRQtg3R1KQLw1Stalpyc/XGBjfrm3FZjPS+0fMUSNScO/RnJKdTtrJkfcz7KeIqKEVcc7RpzkURA1biLmrJNdKLv6Ln77X2Pk39F'
    '39lz+Nt7T5mA/gX9N/yWv30QOm7040byZwyM/af/iCWxvP/nT4zw3f7W7nN8j3/9ZLAf+bdPBt28+rMnI8+g6VgojNPIeR/d95NkkdTt05614g8G9SmAazaa'
    'JdviRoISinp0STCPJa9ypzclOkNINrDPkjHf3rHC0OfEXFWFRV2c3npR0PUL9VBwTyfQ3SzSzXoNzK9ZKFvXJZyfu4gqz/mbY7z8qeu0GniLk6vrMw3pfkc3'
    '8VFw5GSRZR569aqJw+NGzvtlXGti9MQFm2OJ/KOHk4Ur6IOYK6trAxe+Ydinkq7/lzcA667i8RQa12AwRJpuAYY0w+lGZTcMjKMvQr4qxwwHMRerwAqiQFvB'
    '4c5OvqB2zgyS1ZSK4yWWeMLzElzRlYEEJj6ElhL2jglgYqs6ncVRQEmycWUtknGEt4oGRePcdXx1jYZZPY5i7yoKvultWnKvVVYOrXFo/YFRNBvPy0pMF59o'
    'zGKmckWGa4zWqzSqsGEWzJ3VRb//3qb3Un/Wh0xFa/xqi8vFZnYlnrsiW5cgFc4CafsB0qrqli0upQGW9kmHScmhWa7DbvmCtJdfd91qFAjfpCiFEC+uWuVA'
    'kXarXSv8glFmFXXLWWO+KF9Cr1AHYal14b8yHin9cTAwQ5XLNfvx0fnqyWl/d59uHQageV8cHp0VINmbkQFoAxefUp+1arIsOIZX0J55ymfaNTgZovZdLZxd'
    'l7jwri+j3I+zhdlvowPK0/y//kbDcWTw9mGRwYl4bxjkBdPqFo92c6YNfV4snWDyIp9Td9FSoIMvBeLwgLJVGuYA13nQbMIA3dFy5doCYv7QRQbuh40pW9xE'
    '84BuUgl5DkZO6QIKG55O0ba+aF5AhFIbSY5uUY5VVYuf1h+BTqIEQ5Ks76h12QQokzxKRBrWByuocJ+iHrZTgTq0AgnkBXitd3apxiVfUxn+hrFiSwAgldyq'
    '2sUjhA2pQ1WcXXKQlmgyWSRZ3Stdbzkrl1p8a61fpqWUXE+N8VZ66QOPq7ea7WewiTttz/uqrTt/naXIdSw/ob44h3bCeRZvTwEpmJWSGRzt3egxJO6TNgqa'
    'xQI0hlz7m12KeiykimtQm4ApufhUqxWsocjhKSNxbY29uPrO0iM2qg3rrb3PtLEd+wHiUGWH1q0litBio6bUH8u4hISu/ocx565Ectl+2lYQHOnd3XE+L7+4'
    'tbJrrP9F90GV+dj0AlEvn4m8z7ct91/gQkIOIgSGXEjIrxyjiMT4HTZmR56rO6s5u3+MC93UhndZOCh1fDc4qe3ulddTlLPEAwCFJylLk2sAyl16FALX1Le2'
    'S2Hu9XvnF6f9YKe3864fqLTdZWBzXgkPdHa9x9t/Z1eoMobkYtCmVb5FvlQO5Kouk5egBfAd4mqcg4gXp4t6hefVZn5AsvTmrkDVtwU7pjBfJck3QthDF2l8'
    'V+x3yQW9TuXtFkPtqJIa9a3aMq+s5SZdrG5/WXTSrOD6VY5Ola5Hlqyf888Qa/cP8NkpAbWpt84jBKlCAAff0d0xXa2Fm7zDnqfSUY8bMPzsQcydLSheS2ED'
    'DIgkrGgOD/amIPzYwAZySZJDhFqVxfvZHP4J2lZUkgKAWaj9s/gZvbPMXgQ5CNDQf+YPSmVVCnlZDp4l8sq2Td+wR7euKn99++vbtKQmemle8RbFSkUnVdie'
    'NRSjzCadmZCp7GhdwBTor3GFsoIIqjjqEOOr2Bdv10Mo5bIGFGNB9JjyR4vZDBSLxcTJriMK9DMFbUneJRGrRa+FRQpcbTnFVHUG7fv2NRDjBoR1w8P2HPvO'
    '4Xsu4xgkJM43x3FsHb45WrISZazgivAw+fsX4saTfTmoPOqLvssyNe6AUBgMPQJAI+ouOAy6DSiuIRiMvTxoA4yUY7aJsna4NsBwhLmvx3F4NV+kGUwKXWtJ'
    'AHqEF0HCeQ7aZaQv7UzvHWDsEd7/WUicRRTbWlwNQuG8YQGYUGfyN6XMcdCVmr3ePkiSrlcW2ECDqBjyWlpRlb0/KtoaUOpO/+Bgu+28PblAI+jewf7bd+ff'
    'Cvx8LwB4gYKHF53pyo5pBUM7heELg1kg0YjqnlORPYxSjp3C+0tTjDnXcU56Z2fONuxUefjeHxFFqw+C7w5MncPXgZ3eW1jKZ+fs2q0Wdu/0fH8PpOOzb47Y'
    'JO6MP3wj2TBAcx11G1l9wbflN5EpTgegEpjxZIXhHafhHO+6J9kKOFZaN4MRdmQQpzVxpMwwTUbEgAeiBeibjoaL7SrBu2QB7+RCtGFoxoV3tdE3YnzZHFpX'
    'rHIwvjrmkx1ZocSzzhqDX+Z6B+13K9QDwSNZJQuzboWCIA+LJNbp+l15fK4KoakIbxqiARA9C7puwWHPKrgpNW5Ot4yUAEg0JuuTpBQ1owal1GADWXzC61KS'
    'Gj67JwcYvJDmDWBjkEf8+eDUwm/Bgr/UjDvDVm8avDzqdFFYBLqxewADlatgGt9EyoiTIwUVVGLTNbbBEqt9qY2mYTyDr6IUeRyIi2vGCqnZ5CfHFoNMVR88'
    'jKihGRFAxpDgeBDW1CgOVOhV1zFxJO/iugdMIVQ8lUWeCOsJ/FLS0j8Wl6nz6XqRopFHhnSVBjaW/pTWqES3lGIHxHNCWMM5Xc1JBJPV4vmIIk1sg2aCpvN7'
    'R8rCAqDQYIzQubIJdct34sqhUvDVz7AfQb/r+fFvW8P3vujqalat+hZBbefR6YG8C1SHYb/pAjkGMZQmW3j4akrLUaxkkmZnakPcQHsrEG1DlKM4VAdMxjbK'
    'x8BE0MbmLBfTeARS3nfQ9wVFq8Hsx0tyG6bfo3BJgQ15IXHobzEbjpyNJ9o+gJOK+CGAh72PwX8cvznrNh2Mfou8HOFxYyjQfUI3qUmcgNoQ3RJ1QTFzFoEi'
    'REIHaGwGg8PAi5HDh21IarW9/VN2rxYBZoP9ow/HO3xry/DEl/OJ9N2syY6JO/Q6FQsHAHrbPzrpn5wHKEaBIiFL40JrujrNh4KCfkc1mBX9wmnyXoSLIcDr'
    'y4Exkq5j0sOgI6sNa+QNt2ZEjwDaQmjSN22DGjUpqnVd53un1X6lZDfEAsbm3DbD+DIjOqWLcbBxnfbPLg77271feqd9h0zMKoivc9C7ONp553qVDRzwbCqm'
    'QBwE/tdBeUjX64lb/3Klyv91XL84z6rWCY+xAF3WMnGga/0HFqJr5wbCjFplCNW194ii7Zqy9prZVfWPjfWnaErUl8+q8Fk+SCrFxEHs7fUOzvoaf/2SQKlU'
    'uFDyTFvkxTGWk14vPs1LQGKEDBwh+T7pKRGKSNmk1zh7gGR5On1CGU7JFTPJuq3SeBu5LVsIjo8LjiUqVcu6ZgsPBcUKM4zTkKWCr2DQJXIKxJjfddGSKQeL'
    '8uKYdug7JNWBzEkOpK6n5GNQQlusl1dItflTJym8KiHLMCMabXZlj62auLFVyLSmyGsKn5aMa34oEVaFLZIpY+IOPsdfnnyuXFVfhs7ZOWhoUOMzj/KLWxaj'
    'Ih/Ztjx6i2kSWaMglB3irdcHNtAFCnqAHf/WLlwh5HtGDJBN0SfV3Dz68nHq0FAC7zRKoXmHxMFRhHlaGrByQZaARTUyDrK1qUZYUWxM/nJ8+l5FAhfWDuhH'
    '6uJz2bkkRpGkfpaM2W5r09AqYiiLRJJGrstP9MEMloIFeqWtlGxuxxgTAdvH6xoUrddvpieh2DyanAwKqRPHgnnxGgE52gYBmq06jgt/KJwlfPIGnXaz2RxW'
    'E5O7rbh0nsqkEICdvYA9HmOAG/SUL65pyvpfx/lc7OkXeAsvysDsajOgokIGoyehWK9qS9TbV6682hnN/XNN+SKaiF9XGE6vRuiViF6f6MfBBtiN9W0uTrwa'
    'dxWzdrnSzamrRY06JdKhBEeeUn3l5WYVRmsDoJurn7wngtIj1rrZWv3hlujoR1pbxf5aIpoayrZogIxnZIm2G+5KUTwnzbLdESNdUUVhODUDRsC2eebIkaEo'
    'o+XpHKydd/2d9yfH+0fnAFHJvRij/tf+uQKxTgJmchB2EscSbU0K0PbUyvBWWMVCjZZKCavFuzDUiIGzP1Wy5JD6eKrjaM+LEpAnwot6u22Vc75CVv16Wjnq'
    'fzwvuz0EveCpfwrzLUkGsfSD024+azpQrX+KOpD2GTkro5818E/7mHPh/F3f2d/FLAo7AE2SW2/vHE3ZF7v750hn5+/2zzCd5cnFeRmJ/f891dOd'
)
trainer_bytes=zlib.decompress(base64.b64decode("".join(_CELL32_B64)))
assert hashlib.sha256(trainer_bytes).hexdigest()==V4_EXPECTED_SHA
if V4_SCRIPT.is_file():
    assert sha256_file(V4_SCRIPT)==V4_EXPECTED_SHA, "Existing v4 trainer differs; refusing overwrite"
    action="EXISTING IDENTICAL v4 TRAINER VERIFIED"
else:
    fd,tmp=tempfile.mkstemp(prefix="."+V4_SCRIPT.name+".",suffix=".tmp",dir=str(SCRIPT_DIR))
    try:
        with os.fdopen(fd,"wb") as f:
            f.write(trainer_bytes); f.flush(); os.fsync(f.fileno())
        os.replace(tmp,V4_SCRIPT)
    finally:
        if os.path.exists(tmp): os.unlink(tmp)
    assert sha256_file(V4_SCRIPT)==V4_EXPECTED_SHA
    action="NEW EXACT v4 TRAINER ATOMICALLY COMMITTED"
compile(V4_SCRIPT.read_text(encoding="utf-8"),str(V4_SCRIPT),"exec")

# Operational recovery gate: first v4 attempt runs exactly the failed job only.
ledger=read_csv_exact(RUN_LEDGER_PATH)
failed_status=str(ledger.loc[ledger["run_id"].astype(str).eq(FAILED_RUN_ID),"status"].iloc[0])
failed_manifest=failed_final_dir/"run_manifest.json"
if failed_status=="FAILED" and not failed_manifest.is_file():
    os.environ["GENPEPT_CELL32_MAX_JOBS"]="1"
    recovery_mode="RETRY_FAILED_RUN_ONLY"
else:
    os.environ["GENPEPT_CELL32_MAX_JOBS"]="0"
    recovery_mode="RESUME_ALL_REMAINING"

print("Trainer action           :",action)
print("v4 trainer SHA256        :",V4_EXPECTED_SHA)
print("Recovery mode            :",recovery_mode)
print("Affected failed run      :",FAILED_RUN_ID)
print("Existing TRAINED runs    : PRESERVED; NOT RETRAINED")
print("Scientific protocol      : UNCHANGED")
print("Source TEST rows in C32  : FORBIDDEN")
print("External rows in C32     : FORBIDDEN")
print("="*128)
exec(compile(V4_SCRIPT.read_text(encoding="utf-8"),str(V4_SCRIPT),"exec"),globals(),globals())

v3 attention incident    : EXISTING AUDIT VERIFIED
Trainer action           : EXISTING IDENTICAL v4 TRAINER VERIFIED
v4 trainer SHA256        : 73380864a613019839d699041140b42926deba7f0e2b12ee5ab23bbdebb887bb
Recovery mode            : RESUME_ALL_REMAINING
Affected failed run      : bilstm_attention__GenPept_Curated_2025__seed_100
Existing TRAINED runs    : PRESERVED; NOT RETRAINED
Scientific protocol      : UNCHANGED
Source TEST rows in C32  : FORBIDDEN
External rows in C32     : FORBIDDEN
================================================================================================================================
TensorFlow GPU preflight: PASS - {'tensorflow': '2.21.0', 'gpu_count': 1, 'gpu': "PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')"}
================================================================================================================================
CELL 32 - PRODUCTION TRAINER ONLY / RESUME-AWARE FINAL TRAINING LAUNCH
================================================================================================================================
Locked training jobs    : 680
Already trained         : 321
Pending training jobs   : 359
Jobs this invocation    : 359
First invocation        : False
Operational MAX_JOBS    : 0
Source TEST rows read   : FALSE
External target rows read: FALSE
Scientific metrics shown: FALSE
Execution order         : LOCKED
================================================================================================================================
[1/359] START   bilstm_attention__GenPept_Curated_2025__seed_101
[1/359] TRAINED bilstm_attention__GenPept_Curated_2025__seed_101
[2/359] START   bilstm_attention__GenPept_Curated_2025__seed_102
[2/359] TRAINED bilstm_attention__GenPept_Curated_2025__seed_102
[3/359] START   bilstm_attention__GenPept_Curated_2025__seed_103
[3/359] TRAINED bilstm_attention__GenPept_Curated_2025__seed_103
[4/359] START   bilstm_attention__GenPept_Curated_2025__seed_104
[4/359] TRAINED bilstm_attention__GenPept_Curated_2025__seed_104
[5/359] START   bilstm_attention__GenPept_Curated_2025__seed_105
[5/359] TRAINED bilstm_attention__GenPept_Curated_2025__seed_105
[6/359] START   bilstm_attention__GenPept_Curated_2025__seed_106
[6/359] TRAINED bilstm_attention__GenPept_Curated_2025__seed_106
[7/359] START   bilstm_attention__GenPept_Curated_2025__seed_107
[7/359] TRAINED bilstm_attention__GenPept_Curated_2025__seed_107
[8/359] START   bilstm_attention__GenPept_Curated_2025__seed_108
[8/359] TRAINED bilstm_attention__GenPept_Curated_2025__seed_108
[9/359] START   bilstm_attention__GenPept_Curated_2025__seed_109
[9/359] TRAINED bilstm_attention__GenPept_Curated_2025__seed_109
[10/359] START   bilstm_attention__External_Benchmark_1__seed_100
[10/359] TRAINED bilstm_attention__External_Benchmark_1__seed_100
[11/359] START   bilstm_attention__External_Benchmark_1__seed_101
[11/359] TRAINED bilstm_attention__External_Benchmark_1__seed_101
[12/359] START   bilstm_attention__External_Benchmark_1__seed_102
[12/359] TRAINED bilstm_attention__External_Benchmark_1__seed_102
[13/359] START   bilstm_attention__External_Benchmark_1__seed_103
[13/359] TRAINED bilstm_attention__External_Benchmark_1__seed_103
[14/359] START   bilstm_attention__External_Benchmark_1__seed_104
[14/359] TRAINED bilstm_attention__External_Benchmark_1__seed_104
[15/359] START   bilstm_attention__External_Benchmark_1__seed_105

KeyboardInterrupt:

In [43]:
# ============================================================
# CELL 32 - v8 FAST + TIMING + EXACT WORKER ROUTING RECOVERY
# ONE-CELL REPLACEMENT FOR v7/v7.1
#
# VERIFIED v7 FAILURE:
# - AMPScannerV2 helper fix existed in v7, but the spawned worker still executed
#   Cell32_Benchmark17_Production_Trainer_v6.py and therefore called the old
#   ampscannerv2_production.py helper that imports pandas.
# - v8 pins every child process to the exact committed v8 trainer path+SHA.
# - AMPScannerV2 uses ampscannerv2_production_v2.py (stdlib csv; no pandas).
# - All valid TRAINED runs are reused; failed/unfinished only are retried.
# - Scientific protocol/data/splits/seeds/hyperparameters/threshold policy unchanged.
# - Source TEST and external target rows remain forbidden in Cell 32.
# ============================================================

from pathlib import Path
from datetime import datetime
import base64, hashlib, json, os, subprocess, tempfile, zlib
import pandas as pd

PROJECT_ROOT=Path("/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026")
OUTPUT_ROOT=PROJECT_ROOT/"benchmark17_outputs"
AUDIT_DIR=OUTPUT_ROOT/"audit"
MANIFEST_DIR=OUTPUT_ROOT/"manifests"
WORK_ROOT=Path("/home/pc/genpept_benchmark17_work")
RUN_ROOT=WORK_ROOT/"runs"/"benchmark4_FINAL_v1"
SCRIPT_DIR=PROJECT_ROOT/"scripts_manual"
SCRIPT_DIR.mkdir(parents=True,exist_ok=True)
RUN_LEDGER_PATH=AUDIT_DIR/"benchmark17_FINAL_run_ledger.csv"
FULL_RUN_PLAN_PATH=AUDIT_DIR/"benchmark17_FINAL_full_680_run_plan.csv"
V8_SCRIPT=SCRIPT_DIR/"Cell32_Benchmark17_Production_Trainer_v8.py"
V8_EXPECTED_SHA="0ba627482077c879ef38c75a84e45c5430aadc6d54ebd014354ecd8a43c1b825"
V7_BAD_LOG=WORK_ROOT/"worker_logs"/"benchmark4_FINAL_v1"/"cell32_v6"/"ampscannerv2__GenPept_Curated_2025__seed_100__attempt_2.log"
MIGRATION_AUDIT=AUDIT_DIR/"benchmark17_CELL32_v8_exact_worker_route_recovery.json"
AMPSCANNER_ENV_PY=Path.home()/"miniconda3/envs/genpept_ampscannerv2_orig/bin/python"

def now_iso(): return datetime.now().astimezone().isoformat()
def sha256_file(path):
    h=hashlib.sha256()
    with open(path,"rb") as f:
        for chunk in iter(lambda:f.read(1024*1024),b""): h.update(chunk)
    return h.hexdigest()
def read_csv_exact(path): return pd.read_csv(path,low_memory=False,keep_default_na=False,na_filter=False)
def atomic_write_bytes(path,data):
    path=Path(path); path.parent.mkdir(parents=True,exist_ok=True)
    fd,tmp=tempfile.mkstemp(prefix="."+path.name+".",suffix=".tmp",dir=str(path.parent))
    try:
        with os.fdopen(fd,"wb") as f:
            f.write(data); f.flush(); os.fsync(f.fileno())
        os.replace(tmp,path)
    finally:
        if os.path.exists(tmp): os.unlink(tmp)
def atomic_write_json(path,obj):
    atomic_write_bytes(path,(json.dumps(obj,indent=2,sort_keys=True,ensure_ascii=False)+"\n").encode("utf-8"))

for p in [PROJECT_ROOT,OUTPUT_ROOT,AUDIT_DIR,MANIFEST_DIR,WORK_ROOT,RUN_ROOT,RUN_LEDGER_PATH,FULL_RUN_PLAN_PATH,AMPSCANNER_ENV_PY]:
    assert p.exists(), f"Missing required path: {p}"

ledger=read_csv_exact(RUN_LEDGER_PATH); plan=read_csv_exact(FULL_RUN_PLAN_PATH)
assert len(ledger)==680 and ledger["run_id"].is_unique
assert len(plan)==680 and plan["run_id"].is_unique
before_counts=ledger["status"].astype(str).value_counts().to_dict()
failed_rows=ledger.loc[ledger["status"].astype(str).eq("FAILED"),"run_id"].astype(str).tolist()
running_rows=ledger.loc[ledger["status"].astype(str).eq("RUNNING"),"run_id"].astype(str).tolist()
print("Ledger before v8         :",before_counts)
print("Existing TRAINED-like    :",int(ledger["status"].astype(str).isin(["TRAINED","EVALUATED","COMPLETE"]).sum()))
print("Existing FAILED rows     :",failed_rows or "NONE")
print("Existing RUNNING rows    :",running_rows or "NONE")
print("Committed runs           : PRESERVED; NOT RETRAINED")

# Verify the observed v7 worker-routing failure when its log exists.
incident={"verified":False,"log":str(V7_BAD_LOG)}
if V7_BAD_LOG.is_file():
    bad=V7_BAD_LOG.read_text(encoding="utf-8",errors="replace")
    assert "Cell32_Benchmark17_Production_Trainer_v6.py" in bad
    assert "ampscannerv2_production.py" in bad
    assert "ModuleNotFoundError: No module named 'pandas'" in bad
    incident={"verified":True,"log":str(V7_BAD_LOG),"sha256":sha256_file(V7_BAD_LOG)}
print("v7 routing incident      :", "VERIFIED" if incident["verified"] else "LOG NOT FOUND; CONTINUING WITH DISK STATE")

# Exact legacy env preflight: pandas deliberately not required.
preflight_code=(
    "import sys, numpy as np, tensorflow as tf, keras; "
    "from Bio import SeqIO; from keras.preprocessing import sequence; "
    "assert sys.version_info[:2]==(3,6); assert tf.__version__=='1.2.1'; assert keras.__version__=='2.0.6'; "
    "print('python=%d.%d tf=%s keras=%s numpy=%s biopython=PASS pandas_required=FALSE' % "
    "(sys.version_info[0],sys.version_info[1],tf.__version__,keras.__version__,np.__version__))"
)
pre=subprocess.run([str(AMPSCANNER_ENV_PY),"-c",preflight_code],stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True,check=False)
if pre.returncode!=0:
    print("AMPScannerV2 environment preflight STDOUT:\n"+pre.stdout)
    print("AMPScannerV2 environment preflight STDERR:\n"+pre.stderr)
    raise AssertionError(f"AMPScannerV2 exact legacy environment preflight failed: returncode={pre.returncode}")
print("AMPScannerV2 env preflight:",pre.stdout.strip())

_CELL32_V8_B64=(
    'eNrsvfty2zjSOPq/noIfZ3ctztCyJCdO4oymSrGVxL/4traTyZRWh0VJlM21RGlISrEnlVPnIc4Tnic5fQFAgBdZTmb29u3UxJJIoAE0Go3uRqN7Es9nludN'
    'lukyDjzPCmeLeZxafhTNUz8N51FSq02wzMJPb6bhUBY4h5/8YuynQRrOAvlG/ua36f0iSOSrS/icBqf+LEgW/iioicfXI/ntxk+wEfnz78k8kt9n2KD4Pk/k'
    't0U4up0qQLEfjecz9StI5ss4ayYJryN/qn7dLNMw+7UcLuL5KEgU5DSYLSZhBpuGJL/H0PuhP7qtySfRcra4t/zEihaqa9AZeAD/L8YChwn01Y+jxtBPFLpG'
    '03kUmK9HPuAgJuzLUgfiUTA+mPpJEk7CID74YFYLoiSYDacKcu8O+nkVB0GS1XGtt2GSvon9cRhE6av5PEnD6Fp/f0E4fD0H7KXZc7OlaRjBpzebj4OpbO14'
    'fg2Qw9FFcA1VE+i7WWcWpHE4UqRQr1nwnz8aLQGX914yggZdfrYKYv868BZxMAoRjv5y6E/9aBSMvbKawxh6yg+86TxJ+OloHk2WBAdIKA7v+OmkpdeEN+lN'
    '8Cnx4FE8mgcTfgwU4fnLkSzp5EaEw/eSYBqM9Km6THHqAGnjd6/n07FZZxEuAsSeWkbid65UHAhqhMnJ4CJBxeNLII/8hCSrmZoHmpvLDwe1Wu07q/MN/0H1'
    'g97xsbXbtrat84uzw/cHV0dnp9bVRffotHdhnZ0e/2L9YF30Lt+f9La7P3cvetbro9PuMZc4On1jHXffnx68tVbPAdarIBrdzPz4dt8ayq9PPKrgrVq176DI'
    '2SJgsven2/Noem8F0SqM59EMaBXnMY3n02QfClrWQTCdYs/8ZTrfXsyn4eieX2xbb3qn573zKw87v9v2Trofvf9z9uqy07RmgR/BioSacTDzwwix+/f5MBEV'
    'F/MkTMMVTE6UBtdBbI38RWJRR9KbEEg3Ws1HvCzr86yrAGw0B6K93xndBKPbxRyqOwLkJIwTXOPQsF4dFgp0AgglhP4Ed/4ohTZa1nQ+ug3G2CXr000QWVnX'
    'Bbg4iJcRdRvI1To67J1eHR0AwkcBjSlZAmctjA3qrp5bWod3/OU4RITGsSDd+umZlYyQJQDhjiwgvnQ+mk+t0Y0fXQfOvmo+pR5j46sn1juAmMDaSW6tMfJ5'
    'GO2dKNk9OQc6jaIg/tC2boIpNG5FcxhghHhlUk0Ei3xJ8MTYz+/TG+jQbmNv5+p1q9FutHaomXaj2dhDerDGcxgj7E7Yy1U4htlKXdivxoDUMW5Qo2QFr4Ik'
    'iFe484xxULBkLFrEFrBIHx8kakg0dwnUhmVlXbw/JcKN558SaxpMUmt4D+O8H85h5R0BWcTxcpFan0Lo5RL2Olj8yECtAHsCjEmDGo+TnUUMtADjDOJtmDjr'
    'E5DeDs061NlZAU8fMz3A5oJQcBRA4lP83rvqmsCg6ws/9pHBTwIft+uddH4bRNvTuT+mqibbEDCBkGLEERBzRACBTwa4EhKAMFYjoZmWhCXmAlj2zXxs0aaN'
    'S5D6KjoVzEIYmG9lJK/2W6h+bRF7gibnESFfvksauKdbfgyEBlQvZwGWBQBKSjAd3C1gbYe4PpI5dy4YIw1FAUyboPVEzhsR+9HJ+dnFVff0ah/pfpnQkuDm'
    't/1PPmAD8Tidwt41j7HZVOy16RwKjpcwghSEnylN1/YIkUG7fwNgn4uZFMgNE7GUeY6CsWsNAZnQLHI3XijBXTBaEnzkYMFdigORPUBgADYDh4Q9CxOcSSBh'
    'KD9GCWIZUd0IWrBGMWxt27z3Qm3qmXWpFi9Ao3c7QFr+ThIE4530BmDdwF7EPBTxbiEaACqt73HjW3eKGmwP/6d3cOVdnJ1dWR2SDuv2zixKd8Y7l++7r7pH'
    '3psgOg8W6fbBkuSY7Xaz/dSzWu3G8wZ83bOd2tn7q/P3GQwd5I5lq02j9cwDil0s08Sudd8fHl15h0cXUEGvDuWJydm1k+7p0eveZUUhYAbhBCgAQOE+dnx1'
    'KZvPFUTmOsViP59dvMsN82Y+C3YWo53rIFrACD29p5/m8S0MDehTVsoAINhllNjG6LIt0a697R2f9y5KK8JCB0pFsvKYvW4GpjG7HYdxHcgPyCXpXMXLwAUK'
    'BcnNm9/ST6dWe/3++NjDHp8fd+FP9+ottJ5hOjcX3M5kOZ16e8+bHozIW4CQ1gA+bNd6H696F/i+9wH+PAIerJMghr3KazefNL0AeKUGFft23Dt8A4PaDBp2'
    'ivkGA2C5BKofnJ2CsAJUJuAY1FIKSrJvb+rj+gGBUy4qYm02Y6/3sXfwHqUlT0HcuAVCpeIaniRRAV7KVt6b7lXvK7p9DYtPgHrVAyScdIGqNu5kRlb5fhEm'
    'z45hWr4CqUK2gylipSKPU6Se913C5+OBI/EsicMXpqrXvXp/0fMOukAMXzNTvA97Ix8IIY+Q8/evjo8u3wI+LoCX9L6i44vlcBomN4gU2om9GPhekB8ELobu'
    'xdXRa4R9CQM56W7eBC4MuRmDmnMD26mcz/eHDOcSih73SqCNlmPfEzuQh+aBRM7W6Yeji7PTE5BOPV6YFf3RxHuP2LVsmyV34Mhn7y8Oet7x2ZsHF7qoo+hc'
    'bvmgCV7zos9DBbUFiP+Xr4cM4jYUuTc7/eE58DoY+eWmcFfPxWKfx0CqyJaN7gK8R3ZUB1jaRaHAeZdvu+2newBxnjTEVDSug7Ru5zQos7ztWrbtNEBqChd1'
    'p3bZO36tSoge5rfuZARl0wRXyNKf0kaF+huAfqV1/zzb0q4Q18BaV88bi3u7BtvIOcCDpXTYvepe9q4uoZE+qei2ECs8IVZ4KFbYrL7bPbmJqGa8lnwHGso0'
    'nNx70qKwps4uvBtkfbjs9Q6xA7A203qMAlS91Wy6VqvVdBydDx4dav2cCvsIkI80kMgmhTkFlHhvpOw88iXbtLwJGWTkwwBNO0CRQZDIRze4h18Lw443FJad'
    'rInrm/R6OJO/R1HUUk0Mw2mSzsxfnp+mKFFmvYQWowS6MYN5AdQAm44JLxmfM8brz0AWknXhR8Lq4KqtPYPuzrSfYaz9CBYw8/Jn+ASeaC9x5qjxLuy13GwO'
    '7z9YRr9QQu0dHh2ILeT4/cmp1lfkguEYCVtqvviddyJ+LlY8ytRJkOKT1I9hrWRPGBLK21QeOxmIyvcwU8uAv5EWyl9BwqfXSjynEdVq42ACasAnL0zmdcfa'
    '/glUjHif7VEBbDeRsrA2oFTdafgJ/vhtHgXwAyrhHPkpLE0Gldz4sGo9tGXWkUvvk9hqAr4BXAjba4PLQ3V8geohmg4iqgqdjYe2gxrJhCuSKW0egxq4jG6t'
    'MAJFM4jrU382HPv71qQRB/4YVkf7ifW9hR8OKEjAPbLK1HpjucAx1QmKow/1pnET3I3Da6D9/IBQlarjn30cRymickPCwg0m3bq9TCfbz23HMRv4zuqhNWYb'
    'xXZU9WDDRcXseglK6b6FKuc9jDUEVWq2TFKh2wVsHhrNZ6AUo8YG+h+i2wVwrKaS9QdkxZDe7u2snpE9nbVkUPkCWK+31vV0Dtwo2dG2xQaN2AMYyKuSYDrh'
    'fQjWIALI0YefJAFaCvMsGaiC5x/QP7FPQjYQGP0VUPetz4XaX2xhq02BeQOh6ARVKMyzF06s0r0jm3fRVQm0U17eFXZiRWo2dBWxIPtLU4wK8wwtCPtoLghG'
    'MKTO51J4X0SDnc/8KYaG/xlkx29rNRjHA3sjIQCEroN3HtpDcT03YYXAgOyWzcPlaQOsAe7WzCSVJYNRfWJrm3/WwHn38vJvackEwUPVyBfowmS6TG6ENkej'
    '8sMksC7vkzSY9e7CtN6UawltRx4KBzpr2K9Y+gCZVg8QT0eunxwvEPhDiA2EXZ/IlpATeCDYeGTuzHOixbhxCJz0NWwIgbGE4YWsKfoxBdY4C2bz+L7zGlYL'
    '6K+3QbDwoA0fNHQv8uXjyEcaBX7ED2RH/HQ+g234Ey7G/NBdWJb32G/q1CmwVO4Mlmiw0ryJBk2kOnatdLaA/swCmHh5nATVcRYWdeD+k/CuQ5CpzA+W3YAK'
    'DcAyNNCBRV3XmnUYKlDjaDpPgvpkzA+ghjREyNbEi/g+m5ZsLqEQTOWnkqkEhAWfUBTp2H+LChOL/9GsjpfYecYSUJoLjA1NrJ02QkSboucnozCUk5DM49S7'
    'De4lpvwpzl/kR3JSjOXdoFmpUwdyb4im6+ZTwMYkuY9GdXgNuI1gv8wKwMs4WEz9UcCDRmSKqQlBvptq6IFljpinWUzqud0J3ywjQMxtvZSEJGVKChpP9g1y'
    '/lclpcdQDuB5TOSDXXmIekppZzxppHPClSCZu3IC+FeaZp5flBo8nnFjnk3R4z+HVyDcbOQkND3ILP4Rs4F2eGHrXDMPShb6immAHlEtJS1lfaLSKDR1uAjt'
    'SYSfwo6YF3Gyqh2LkTkBJVM8y8y48pRsHE4mQZy8hA0Qj62hDJ5P0YSAcIaNC6ElgNWjrdNSWmXsGKJNXh1Q+zPoQKPZuA7/XOt7nPFVB4napbMPkIPFr9Gn'
    'sfg29YfBtGOjGAk6qhTqoT4qVkiSdw7pBneoF8DjgegGGtJRjFQuFw1oO5PzsAMZMUL3ecLUoyQdY2+06udH5z3jfRDH1e9xYPBPa0OMT3xmL+RQkTDgOx7P'
    '0E/EPBJaHR46WnE8ChP7Xi0TKcOJGHODZwDVD+t/OlZTk5pIPrtgU1ovjudxXuz9TMj+Yk18mDc+tbMI0OcC7C+wIHO1D85OTrqnh0A/gFx4f3l1ePb+av9v'
    'kazNOO1vt9rNZnN/UAICqvQuLswqgOasSoUkzaUFjYGWM/UA93VkPbRmgX+x3LZPL2kJ4xchA/qfitapjG0hZqGEmJaCECogG73xP0nDFYinn4CTOEicn0FW'
    'R0VcauloVYEP+4vc76WFFPhHfF8UlUmXE5w143hi/ZssRVfAJFhzXYuuflbDsfGlTehi6BnJ2Un4W+AN71Po8T66LfA2kKSo/8OHh++N8rT6EVieDXAhOWKx'
    'dLxF4N96IMV4syHrmhOQ+1IeNZrVcbuiR3VpFcU5ipeJfx1kjy7eX3bf9EiVcWCxezP/Lk4SxtJ36LGyvLPUY5zPd+Grho4MbmqHTAiNpugj2zm88ZKPb+tJ'
    'MJpH48TcBoBGxHO1fOcxnbJGC5gV2JVQ4OQhSABOgZTs0y5PDhSBEUNH602X8B3Pl9E4X19swMBI42AG5cfhajYf43vXer73pNnk9ze59/DDtXb35Gv4keRe'
    '7jUV5Y8LnQQuMf4ytj7f7Dfb4y/7n2fiM6FPg7igaFUpxq3ctOiAQBm80SuijsdwXqmQW6LEoRsF7AbM+nEzgCe44gSQBpqL0uViGiR1XSjUxgbtw+YtVxeu'
    'AQDREI81OVCevnhiMcqKfMiaP5zJUCf8EsqqGT4Lti640Cm93mC2wCV5mZDLZArhnAZoXgbZZqSLYvq40OCslHWjbVNYVu0aFczeOJpcMwoW6CqIH7CIHugd'
    'riaYAYVMsoggt1kmfCzg0NiJpbKF4hCfi+M7/gGb0flx76pnf3mgMeEfM8fJF6YxYGrUJFtOxmpWPSqryV64Y4O4id4ydQXHIS8Z7KB6hMT00JTEtOY/G4Wk'
    'yZi5sqTIUBcHqJiyIWcF5aN80ZyJOatgvihUQ4vzvuBFUBh+5otIOxP6OaFBf79kEkd8HpMvCvO1jG6j+ScQ8kvBIo8QfA/gZksmmya9RB5E5gJVDaSkTB6M'
    'PIedxx65RHlE+JUQ1xfPAze8qqqBlhfLAxNoRmJB76JqcFUFC73DDVru1rxRl/StpFApoOvF0luthaKXKCd2dG2aBSk5RoBEW4RTXqyAKeVYRkJMaY9KyuTB'
    'jINVOAqKVcXzfHGTT8pFaDLPyiqlwlVl5S8Zg4FdsuEvFkGE2/zIEW7L00SdUOVOqdafTMkzqMJarlUvXbd0LboPLS0NZDn9u9Uk75YTrw4yT3BuFY25pfSi'
    'gRLT7RZm2C2ZQK43yJmhlWiDfDZxcYKWsyjp4ESZFiMlL2V9KpeaSNEG/RnkH9TulQaUqTPxeAJE8LA0JjSOvF2yypHCRcBcJ1rOgjikHe6LktLQ9xc28f6/'
    'GMXU1rI9t5xiKgljYNiicMhCdgHcNMTsPiyi4CKFOU3nnsBkHar3ofrAtQJU5RM0kQQxMpvGOJ4vIl8zb4o6VL4oZIDYKvx0xQ4/DSIUZ5LCXpwsZ1BEGitU'
    'MbQ5NdlewSoKPm1A4XoBAvrGbw4CS5fBGIePg4LlS+CEjwESlkHw7x4BAdQ5p8CZxRmHMSs2u0hpkpTdajR1whzFAbmh+LjxqVN8rYBy2NGBlLlt6kB5QUhO'
    'YTOrqMvfTp6zQ/sGl9CoB9e9UZ48jz08g4ZSptlJN1MG26s9VI4ScQkAXZtBTZrH4XUYFRy8GxaUVo76E38INA5osez8PLMhBPG8U+a9njSsS3bcTlEFCqNJ'
    'EKObvXSYlu7fwLOG4XgcRPkWoKPqpkiEdjP4rru/q/e7Dc2ApeFHdyMDBOUWqCYkVLHawkotExI2qPxF65TgGtK7CymNn0gjTmEzICVwnQNcdvIptjLkosRO'
    'Z0NviCpWMAEsp1KB/c46nFunZ1fy2tFVECXz+PWU1Xv0e5duDTszP4GdWpqUGqI6ob1tAWRfeDnqMN6cv8fLYVCe798ATF+zGJMBVADSLiygz6L0ibeSwI9H'
    'N2x+sw6DYGFlXqbsIp/g5QCo76cCVIJnK1ordDMguL4HkoFOGRYpZC3awUSApwHY+wkeb2YgyNqJAhkZkh3DTSPnYVluI9RHRiYKqbYBLeYASD8Nhl7uhFne'
    'iH7NivwwAXh5fdEGuX5mDDKzM+S6xBsdgGf3TqNoeQPCchbGSekpgtauUAHwCfnMxfdouEEBoj9wBjoqkO/hK8f6yWopGYcWPz4uOKWQpWmMvlQIkVF1rM2D'
    'aA4rB6N0Dt8EIwO0jc1ZQLarht+3MxqxB30blxjLrwPoWkf0TR4bVdWCXtGgh8twOrYHaNbEAxKJadNgPpov7oW4gfc/OliCEXd86B0fvbqQ65/NN2Ljw7tZ'
    'wr+R8CZtjgAiQxYVk2oLvFFz3S/ARtHG3rcbfwcpDCCO0gY6PqFXQJ2gOFpdoqAPR5dHr4573mHvw9FB75IBNO2s1NVr7+D83Ds5OiVeedz70DvmUm2z1Osz'
    '5HTATrzu8fHZz96bi7OfZY/I3p9ZiYOxvIBjHicQqPNfrt6enb7tXr5F90+qj8SJ80smF+PQA2oI3iDcfTTegJOe8QfJTuksp2PFtm2XXX7O6uPRejqpARSc'
    'ohQF1WgSXjdwsrzFzX2C1608VneS+hYMfMupaesAKzKxudZWjuEuI3/lh2Q0g+9j4NmS+wCv3m6b7BWZ0VYNFxKAxKWEkPdLjpNVF9E3Kw7pItm0Abqq8OLx'
    'rkFEgQUH9V0rO4wVlkn9UEynvSSp0SEYgOfB1rd2YAz7zS2B0TuFHthhYJb6IKi5Vhv/7DaaIJzTlcVOii4HIAnutrnZe67G98Bwg63fWd9jNYVFFhzvG3Tl'
    'G+RGlClbUKDGvlvKSSapf97K5m1rH8F6UujzPEC/Wv/wUs0NP99ioQKf9JsD5wvQF5IG0dias1NimMS+gAck98AHyEERZ9RpoCgzXQUo6lr29sh2ieoGv9/J'
    'aslhLR62Prg/bnaGWn18yoi3c9SMThPk9myp407b+gHg8DCdx1Tno09VHbBgHPEZfUMVAxAsNoxKqHySqx3za64AUtkWMin6WdB2eJfthHIYjWQxDVMqgWeZ'
    'E+tOHnCaWyAWYFRGkznAUh56SZ3e9bdbAye/c2HZqm1KsDosArzusNc79/CCGt2pOuxJXlYZOkJjcq4FlOoaARYeCqdQxRZrJ9A2eoR3kPj9+HrVbw1qyLE7'
    'xKnlwzaM9ersXY9vo3X4aEm+3IWXx91XAKfk5RN4eXR62PtY9vIpgsVjD+9d75esC3uDGt5+M549G5TdmMrBez6gS5F41yP35kX2ZqMrfchIOo/bLbAKMCOk'
    'WqmnocCEgrRGquwo/c/dCADyLd4Rb2BEj4QgilsTuDXXcfqdmupLRT+CCLmkN0dPUlBXQL0MkxmITuUnZNRuTUiinczdlZzkSiZW86DaIj+hLeDo8iJXR8Dp'
    'b8knW4Ma9xHNi/yov6VuxuFzKIFTob3Gn2jBjJHXCgaCcCbXHVGnL1fHoL+FuhEohiM01UEpEsvTJvnANAArE17x6CBR+9iJFjy6bMm4FmieC7qs19mKt6Rf'
    'J4djkZ5996pitpw2qhiO71TVbLGVlwVmh2X9xI9j/74OVftqCapdHs/6o3TviVMDASdfXKzNksLSclmGlm2BshraLSpRl8Z6ax/70NtcOyh43JvF7vPFlITy'
    'cWWCg9GUgVuZ0HKlFDTqedXwxLBq7zpyedVqI4wHY534Cexsb+hE9sS/O5/PMWBB67D+rjH170G+aRzjh5DDUArGo9g6OqijzwRe3NaOXO9ciiDR4RfacT48'
    'w6XqgxKCP9y7Bo3AMYqAYg2FKMZBHb7AioaFD1rbLKFKPzXd7Zbj3rkS0nYreKEgOXkPikzwQ5Mgw3d9YKWdllM2+i6HqvlmDHwlAmCX7ORk1e9LkEAokKNQ'
    '/rhBhHVhnOEMKppgqBbXcNG5HkHxTqIQidJ0JR6hYzvQgImy7nhM0VW68mJZNbY8D91yPI8xtoTvifv997efYOvTEZcs0RfUaajiqkxWBAA0YLv6e0c1dohx'
    'kuoMFBhnuKITjM4WaAk3W7madFsrX7XlLpPAG4Z+orswm7P81ZMMP+gYKOsHvk9+XQbBb0E961Rdjax+54jp3W7lqvG6ILiJuQSSwtT5WCGKGsl8kiL1JwWS'
    'KSySUorzDXITFABzf4yBioLxOcXYmUe92TAY4364KRVAn7yFqJy4vBdCg99EF3PQP2Q/slnOulbRZtmE32ntqyq0OumCKOigcdpputNwFqY0ozf+IoCpA/nU'
    'BbCpX4Lpux+K3awr4IBcOl9LoOdHSFZ1gtmpt5tN13GZ3W/RlrDlotMkkDiVByInutMQj9f1xK09KyVNNZqnXvDr0p/WU7fpiPoLn/rgYfUtp87gHLompQTv'
    'zhbdLd1idPxWhtZ2y0VpHCST/pYaGCJ2a+DQMvF+C+I5MxzVSA7awTxaAcNVcEb4W9z3SRBO7g3sYBFG6wp/C/CtGElnC02+WwYfiIPpEgb320ZNtiubbH9D'
    'k5U7rFPv/0YYGhR6x7xJdWGMPz3ictj4RgM8jOcLUCmFNyOD4UcAQlVAE0GBI+rwk/B6Ng/H3EQwNYmDbxf/0dTxKmTbLIW70jjM5dVJhiJx0Zlw5AHH8FQd'
    'bInXIIhHwHoj0I6EUUIgpKPhiKBkiIKao2WMyphXUrjwElFbOhl/zHwSmD9oVrM74/+O80uK8x89vVWikOq0QqGa63/8mv9jaKQkfoAgk3FHDUHtsQCdJ4p1'
    '9vltBSmNHyCZdZIHbpRjubWJt9lOyxucsInNqnbLGe2WhsgthR8BOZtRsW3ih6OOoYYUXwwteiQoKExEEkkelSBK0E6qsv6cLKdp+Dbwxxk1gfzt3cCTJEMs'
    'Psp6Qi+RRm4DPDWbZeXEA1ovWAoLldB5BkpbGTze2Y3v/Xm89ec69fuHFtKP+5troqHjzzJx57eOKQOeomP/NPyN3foVFiNvGhUg/+BncCaTyqUxCYIxxtAA'
    'MXBskNeaVVIAWVwqJlhtxUwm67o1NgtsMv7JpHT0EowpMxT00n9fHiLvuPEVqXfBPV+PknwFhE9iGQDzBD/F6nfxHhchLitI5RroM4Pn39yZBfqRAO+A6up7'
    '0uiO/Vl2pkIRVsn5zk8DsQbQ1gY7g/4GsaXqDIPU91pGYX5ULNUulmobpYJFEk4BM3ox8cwoN5qGiwgoxygoH6qS4gPD4+K2HeGxOUUUxKtN88X9Foa5RbUG'
    'wxsnHfYAfNdQTxo9P57eX6bzxQJZaKbJzoFk5nFnCyO1IfQt12Ij3yyMtlzNYJuGuN8SxxGDQYheIkBuDfpbspAxPox/g5F9yRnlU4CHKEnutAma8liZMpBV'
    'gK/K5dGiD/SClNzji7PofArz6y8fP1i83AXF9M4I1Xkae3OKk4eAsUtc1BhwCaqqapciDEc53ax1tHbPYIcop2gH49JUWDgx7FCHl9YkTBlFH9PYvYd/Ne0W'
    'B20VPsxM/ePKvV8JyMFiPrpJtAEKe5THL1QPhhjdgzQprWz2UJVLbpaTyTTQyCIjZfVN9CuIh/MkAJ28hkZkP4wqTaFo5NX9f9kJbIv6uLWPplYRBcrFU1zE'
    'SAP/zON74BFIHQMH2DU3yw/2ywqJAoqmcoXUcyj4xZG36cUh0M6WKIexw7Zc44L9aNFRpTRn2MwbqiFWU+Pm6ZZgk4m/CuQiq48WgKFW6fSzgUyzNnN1DG0U'
    'jlKca23qMKCLQru0UBB50uE0WUTQhoUjrZyLljyf0u/vUTecBlpj+JJPnR/9BO38hb/+CBKZKFGDqjjADHm6JzMWThoRskKO+1126oCeceTSlZ0r0SNebBVH'
    'TNfZURcem9J5GzoskEPOFtbfcpuOs1Pna47ff99ee/wkvP86ghx1X4OcqwEX0NwNkE43Ow2UZIsnaVv7eJQmHqx184YWxC9RutTXe2tfnkCIUnkncxiIXJjZ'
    '4si5nG/tC3IRJUovCGztI9uQEgA84AKJcvvdynuOQ9/giXiZrZqt/YeXECzPWhYqRcySSyeDiuDosI7PTo0YfVvu1qctx5UxVdjrQ7ugn8XJ5OO+zJFI3glx'
    'yZPJpeLx/JOLga2vWcOWxlXRrrjxqL2nqI65JrgwheErjzOgQXOtvB+Ao7mlbeQn6ehBBDTPk43cWozyWr9yb0pu4Jm+XOZzPvXkGKE5p1x8zWebla+JFZf1'
    'QkxQg0mci4H2VVFKI/yqolURWHPFdHowbrpsGpPhD3ITMmIyfIsf0EHm5kveCkwIG3oBVVd+vA/QpAANnSkERBHJAU0AnyVBCt9RwRAMb9ncKq3iH3bBh0e8'
    'rXLj4aj4HUset+faKd0Y7fKTeK1hKtuIQNEm7zj9VdW2rZcRuzf2stloOtZfLPHgRwAGD/QqWgD6PC8japfDz8rZpqNT9iJzjqb3m+HCyeLUlFWqnqj19arZ'
    'cK6iOCvK1qqW1sTEj6aXcLgCiZrC3S5di8iVLbnzpZc2KK78rp5eXGLkwfulRi82ucXrEuWsh1B1AU2rKW9DCE05GAV1jubpWjL1jBV58DbptJpie+UCvKaU'
    'E4aoxDIvJQjhotr6y8oKwLqAnPdnZ4DkfMo/eS2R8Ku//8lqVq0+Wads/cmX+hKUj+Qi1CtibPVEsBFABmZ3qjfR15a8bhlDwDnFGSeg0SK4fAPR43QLHb3j'
    'yj4aZrZRBqNZQTFBB0g65E/Z4T700dVFfMMGB/odv9D6UfZl22rl4ywktwBEHziCN0fObWnhE4wYTBuD6eThUKegGkmpAEFc0TNCTnARY8MrvZM4H1Lqk7E3'
    'Qb8w9NGTIVoYtX2yA8obfJm1AH7jjcqhPwynYXqv1aJeV1TDqfwBxsvd25GT6VjfW/4wqRc7s11oyeBj3CZAVdFeKb+Sp/EdFS83vxT/DdZfggGMMLRZ+OtS'
    'shLU5emuBfuSf8ZV8+UfsWi5F2IzYxyojnErUujCERmlSYJo72u2pjHtMQjGLNnf324NYCWaD1v7IITsoF99SSwzHRhZV3BW+oOSCRkBupEsct2Hb7As8MZh'
    'hGGFMz0ig0bMqdl4ShwqB9o1O+tmHWJx2SlpPPvRr2svtJnQnorJGFTEyEl98qPNKmSo4ajROQYD5SkKNIygrkg7H1ggd3MR6tj7YrVh/dwtxZODA/W6kBxN'
    'W3fYm8Ll21ddrXZFxraHYLxuKQgyVVuuimvhoR/ISyvKEtdpFmCMQ7z6MQJ1de41vacAEFlSNmbgRUAB+h1LcdpIN2A6xUv/ToPCmVI0qkS7dUHocsXAXeq8'
    'W2zeZaxrFy78ZARTg04hfREu1fxgX278q1W6Bf2vY8+CGPY46I24J0x6cJCycljHgxctsOGQ4wfRuBoh6OH95qAi1phOF1itz33Wr8RqrFgnEy6NT6pKm3RB'
    'xelRVXmNBrg0PDDKanuBl60W7bYzmwhysc3wCAjzaAiZTiQmLMp1SCL/3VEetaOIilAUX2srjQvXKllYVrTIydIIVOkF/IPPFCOY5jM6FhgDBUtMOn0c9wBW'
    'hr8KZA8TPPlNgWeQhAPgdqw6/P0BoIsCi2CEebREgYgKRFhg4VSsme77i7OMsI2kkQURRSff7vvzi6xeRd7LtRC+lk1/K4v+VvZs681v3uplNnmqtjahRtFs'
    'GrOi2TMDF5g2NENGLonoWvz3DnqtZlZ1IyXRiL6gUj+U78X21bngZukCb+1dncqfEf58Ld9O6O1r+RZoWeeSGkMU/MFkojLvpShXl+wO1qxTCBYC5aPg2i8v'
    '3zTLZ9Ek6TgIaXpCm+n3bJ9Ga7XMuMEnqMKCbcQ0Qk6s59owd3krc+lFolOJNxLX+qdw9EezN8y+mJM1PteKceYEvvTwOSJVyX6Gw1pZ4DmF19qaWHMmxnV5'
    'wEhzsl85F3ogulwQOi0byj7fKp/5izpFf82my6AxkTFlX06h/oYzqOxbRupf8W7BoXIEB9psnX0xd2LsHt6rFAGAaAMt5o7RdwIobYR/inxPHMYacaoxHgbH'
    'qd4vD9bEJyhVhECnzdD9PmorNnIm/AEkGfnRgIMxecWnIq5LHz8HYrhmsKoJ0KNfL0amejgfxOOTCGgBQDeJ/amnBJjYP32m+IaSYL5gKGIKeMgOnF8oDrk+'
    'Mrp6wONLSgYIgDxzfiLzkRy3gaYGSs/jSd8mGcMe6Mu5EfxabzkDEXQha8H5CjhNDY7WM+f3yOoM5Lz9+vjozdurfev47OBd79CSB0aXVvf00MI8jZffnBMU'
    'Z3uRhRHTk4K5enpNN8to5hop4lxLz8nJq1UlwXQtmVPTrQ2MuCoLI3DHBdBHiBy5LFrHAgPe5vpZzH7pWhVpLLkPWiZK7mN5dknXWpcZ0rWKiR0ZWkWWRteq'
    'Ou+D7lakS2SAa7IeutbarIVcvyrhYOk8ZMFm1ESIoBIy+nV+OlRezU8xmi5i4xisHLVOTeXMLK21DvFODTNiGsWLM+HUsrBdpQF5KyZJ3PHlc5yynlWe2dZK'
    'slaa4XMq5hhwIQ5GSju6ZvKdGueXLOvnWrJwarkUkqUgqsgGWJrce3Mz35ehhQeUT0lNS5EImIvZinaw4QIwiUZ7kG8w19BFr3v4i3d1JhoSIdlazzx2JlVz'
    'bRfhGGlWPdwttQg9xdJoKueMp6Lt1rNiKSndea0sByVmducae8+ba6q0s0S6GUGJmphZt1hVCHaiTCHxYrECi5co8uXrUKLEYoUstS2mzI4xphHDED8Rhsjr'
    't1FlU3bVoWzQ+zJ46NRdBsUYD05w3zZnmGw1/CLjF2rO6Mw8GBcJgmvks70mnpl4XR6BEATolqIUtAIG4zpDUYUkFDzth9KikJEUUYV6MNZ9bjFkNU56V2/P'
    'BAO4FEsOFsPrM2Ancm3aFSCztWcMVGgmoq1cxsbvrItgm/K7cd69cDZjnx++Qq1yrlvDexHEr9Wgzfw2uEfJNI0pblw21wqAx9dwQeoCkWymgjDpaRyoep8D'
    '/A2K+Rxk1hrc2I5y/ZLRMvqfoSNfBmZ2hzU5ZuR05jMzIGpEd0TwwEFZsyKXu2wWBRvcFDFALEZjMdOvFYUcdDUUnKK8SoUM5NQ4sXaxQk42MsJQqa45gofR'
    '0lFP+1LvHSCi2LapVze66hSYGZTgThnQ+dE60Fr7Sn8eUNBWbwyKCsWwxBj00rpawqnMULAaQFKPtZiwdKFBhIQ1oeuagN5SOR8yUNG4hnW3GN7X5SCdBnre'
    '1kml2JWW2tKuGnD6GPcyHC9x28C59DAH0dRflA2AlBUBWRd3NKmlKASV7cYldft2ITO44hZmwte1QB7aonhfB4Cvj95cmv3NAxGhVKDX5Op4+bZ7AepTRZWy'
    'kCxQEzjbAWYMT3i/oCs7pBfPfLqi0KhxQnFkAXg0mBfo+ja9AUgHx93Ly6ODru5/KDmYBqNvf2RtGB18iQULtpZ3bayoy5dq9Ip5p8fSivd6jYuzn3EH6eJW'
    'XF0lpuSOqY+buV5bsXXi0UpXqxsDA5WoBB/Ao+vZGEDPKnfnrNvo11Z05oQXRqdA58uPxCloPgaHrz3E3HUMwCAHGZ+v1T56akyal17ZOPXIOpSrs8xH76NH'
    'w7/UYOXxsRGcXzQAeZxtBEDgQxseh0RAfNSftJpPX7jWk3ZLK8gdL5ZqN7PYfL8UXlNO3w8UhZEixY78aB4htcCKvcEYYkoN/fkIxJv3V6Sx4PatJDg+Rq9R'
    'AjuPa3m6qFBUDXGBZoV1OpYbTR6WRi0llFIoTmSzSbsZIWV+yLLf6wQjXTCmmiWDyCBqvadwTRpxZIXW0gFu2VSVMjyy1bX9hDilCN888+/hH+xRIV6NDCyO'
    'YcxWE+sH+RNEk6ND0ootuWIpgHADIJ3OhZmbg0ljmHu8+LbNFm0eDjIZFM/DaDRdomyJEVQaHNRNxIm6ZGcN5EhS50CGVNA1mCMYNRu4yUZjzSFlYqNZNYw8'
    '77ME9sXjvUILAF5eKjsplwHtmU96NIbIbNrgT7KEhvFsiPAQY64+7FCjHYcQoD6CLYmiJS2/pf2qoTeN3nbvI2zKV+jLG6T1fKeyc+2a2lA8WYhPUVS2YLZV'
    '5Xm1vP6YyyHMR7+34QLXekfc7UY7thfN9626+IZn73y9SD7Ytloq5VFxFA7eLYuF3Yu2EE8cK6io8rS58ArLp43XU3pgkEf8wtZilWyeTd8erJ5rzmWhHqlU'
    'Fl+URlbWD1i5yXKIqC6gU52A6Gu0UEr5K+SnSlUrVOlrY1Z2b0UuRam8tHd9gRMFAA9WJLk65HDw2RbrSHcqsRU+cNY2BAsiro08A6RdP8J4yqreq188yfGK'
    'CMz8cQxa3BARPMnkySNoFIieN+urMxB51wqd6NkcJNJ0gMybfaRB4EedRuJAA9e3z7uHLB03a0eH+LDbRTLFA72Vw/FobzkW961rrYjis+pSk5YpwqDk/6D1'
    'AGB+0SdSQmajBDyQVyct2OydspIN4W7lqCp29+Cw9/rN26N3xyen53+9uLz68PMv6vBnHOAVDI+EqrGK71FXqKYjSldliheLh56aqQNZYjTPfaUY0hf5thik'
    'U8H1QNRYUIB0BtUXEPHWSiFAOZelMVLQcLN70nnlV4xbLQJpSwRRXwi0M2D/QfyO88MwNaaZaxPgrW9Q5owNfpXInXgY0jW7g1SHf1n23WIGwO+st34sIkjD'
    'Lj7EdIl+DFVwPe3QBox7LqhCcZClcWjoPS3bNuhyjZAMsuQPagvft8gIIkwu4ztzEnm3qt6sNCKEuhn6MmZZwuo5ZSOwVp0VSPZAp30Aa6AHZBfNYJ0HWKJu'
    'BdB7VJNUwSFsSjMtIviHj1qZsiqWjswtl9G7q+WbM/YgPTG3dP2GrQhgoyFvGg4bvDEh6TU4wEldJk52GjfB3Ti8DmhoOauYCa2TJcczNzw9wpvAinSARWJn'
    'hFFOpapzdt1Xgacme2LuCnIWDB8IbhQ9KmT72mvevSXc3MkvT/fzUriZ+wVXlb8f7hDtZmokJXtbSaWMFveR3PQBsKCh4OUEkEGp7arMzUI6YosYc1lYSu1E'
    'nI1TsFwkZlzDj1ss5l9oXZkL+bmjXxoUTSJoNT+DBrqgZBdJWOBL9mnR070xfbmv2XQc4X1b8IGkkUi0DIP0UwAMt9VkfVUrLpMVT6oceH+HA//MVMYBmb79'
    'bJ9vZqQe53bhOMv4h7fRfZl/XqShqEyfkN345YDNDQXIkSpG+QsjsnRVNHAt8vS6+NAZ1NIErI+MF71ZZlW6wL++GIeYJkzP/Nsgs3OxIVTdYhZ5tPPYH00w'
    'Wb1h2ezLKgN5FCEf0EnPdH6N6Z5GIDxex3gpDnNTZeNBeXNy3beBPYczzJ1qD/IBK8/DRYCakabgsmktgW4HaAq6TDGMezy+pAd1VGsxx1kkwpbT7yQdM+nn'
    '/PlF5ki00omeXqiO1gs+gcDz/Wl638GTNf6KxusDEaEBnpLfuUV3x2Msxd909/zsTtedhzsoxR6BkvI3AQAul8GEH4aHehabB12ROEYAhY1wLUmBKUYVokdG'
    'LX3wA6d8vgDTPqy91Qx2bMpJg2eDJTM2hL3CK5s2fAGFjgnQ5YcDE4sFXFHQIPhFbmaAzFIUGyDwBAFf4yfWKEPWWvTWHoNF8gDNpaGnehh94BJzOYWTMBi/'
    'e413xyKPdsOk89Q1w8YUYa5hDiO6t3ig0H9AixRaiQ8+1BXKO4ho1+IT2Y4tQlxhAo5VZ7TCs8okmA1FBwos5Ao2tlzY+webNqf8K9svrOrqheyQoVyuT3jm'
    'VBCtQO4EL1alj2QvF1T3NVXNRmsSbZSNOpEEpT8jihuhK16MXunwVv3IEy/S4Rgm4EbQGsZTYlkwYdpRBJt/UaBcvcQ08CdlNfG5Wg/iyIeWm/4738fhfJ5i'
    'lrJFhzICouOBfMIjLS6ZiJxHOtstE9KDKyk/k8EdtOKlcYA3bh41jz2seYUV/zuL/+xZRE9l7zr2xyEGLYVmKeHjIyf0LQB5I2C8EiCqpja/iZSF18PX+uPi'
    'TKzbkfEHToMXwUATvUj2tBRiFZk8NNfm+NooPy2nfiwCOGpjyr9S3aW7IVpH8XcBshnHThgFHz/jlH7oejizCwK0fIPi8/R6+CgSgPKN4zevTqqmfT78O8be'
    'XQUdm6/JoKv4BqvcxO2GtIIJCHB2Vtn0Z0/WTL02A/SA5wdmfHQTTsdy3nVSMF4UIKP6SK+yvqpHLH3KX94kDn6VgM2nRTFoPhWvh/fIfjPg+TfUBpCc508X'
    'N35WTj0qwMY3rAybpfnZNzMjK9OVQHwX8hbIApgrez71PoWJFMI4TlwI0mUeKscn80jdt0eLpZ0n+FyoUBXtSV5GEred9BAEXMi1PkpPMNNgaAS143r1j07Z'
    'fXTETZCU1RavPFyPN/AqlYGoMEW1eGc7nJuYnmNGLlXLEcZUKYuh+XqOLWVgMTsmhZ62kltaES+tiQh5CA1GY/QlAcE3iC0RGE6kYsXYEvN0XZ/wxCv/GoOr'
    'AuGnwSKxNTviGgRoNYQzjZ0fHwxJBMGA2py8QgHEy2j95gCz4enXpvr7LlYbVN1uxRhPRlxArKfdZsWfJVGFCld7KNsmh+IpUb8FBtYZIt5xYkHOpPOggt63'
    '9QRNeH6vsPvI/DubZKDR8vAQ/o0cJVpUEyNTiVXIR5Ml5eGylWl58BzVtTBPCDZrJCaxikllHkrQY6lkI+U42ixLzz8YT7AflWaaLMvfw5jKp2MRWXwYypo8'
    'PqKia+Uy+Vh6Kp/1aMfO7liU0SeP4g2z+pTndLE4C49VksNlwzwuRo4fQEVplh9Liy9tY5ofuwSAvORZCE5tlWX7+eOopZAAiHrIxR5MA2QV8gBptbVsQFaS'
    'X3ZJ6fz7XNNIC1RKiOW5gYr07OeIWaOnR+cIqqApM2mPlWUK+l3ITM/Fo1NLVdIgK5c1qIRw7nL9UZUFgzASCFmlGYSsQgohPY2Q9YP1QCIh47i7NJ2QkHVs'
    'yieEsjsGV7eFU6U4/GRy3jitkNV0JBw9sZCtJRYq018ovZCmvNyVT0O7xYeUrLjoeUaE1lWdNaIANZf5xzaSDRG43Cst9U+pPdg8CuC8QHjOGNgms8KQ+4CP'
    'u0f0q13dr/Yf3K91aYsEIxxUjMTMQmBrWQhoGI/ASTEZgS3SENiYhkCrxhJkkd/rjUlTKVUUoaryBMl5Zv6xFLkuAY4xq6rB6mw4QkssTXdkShuFPCC2nhxH'
    'wKnOjmMXXhpE6KyZ1D+UPPRcFX8skWQpWP7TyMWM5/tPoZaHcivZudxKNNX/XMb0j6C8krxLGvGNhcJN/cllX7I1pAB5VZPpeDNyfCgXE8IR8kAhG5OtZWPi'
    '6BkpZxKqljjKUjNJwVM2ZGYlsvXkTA8kaLLzCZpsI0GT7KPevZJMTYUduJi6yS5J3VS6eedzOdn5XE6ltUoWXiG5U2lFQuDExnRPn0VKoi927hC7fkcafj73'
    'k5w7U1y9M6eyPBHSxJaZoLJGoRkQcfG5CXAyWbOSyzNCbbCoSyAXV3ZZYig7nxiqqo/jYrENccNZovKY0YHl5bSyVFH/OSyxGFu02jjMiX3gJzVhZJPChgXH'
    'yCqo8mZOqY3zSlUdaGj3Ch86BjPSTBn1+A3Nh5FlqlioXTxnMhJOGTXEK3EOYOSbMsrJd+aOnX2lQ0C7JP2UrTvuCf2VkKycu4OFJ7PLPMJoX//oWrlMNJaW'
    'isaqzEVTYVZemEblhW5SXqwxKC9+l/g98p48W4+tt73j897Ftzv1dU/OYQ7PL84A2tUv3puLs/fnlyoPR90e3eBNKVAF+3b3AF0hyROSHSFdyz7s4d93F2rS'
    '6/bNPa7km/mQA/FhzYPXUO3Dz1i0++bt+eWVqPvu9K96zUiwN2CjK8AxxvHwQSMRjR++gYpYr3d0fPrXDxRz9e27kwvoSAZiMceTVrPZX7hdUfuw9zbXLNf5'
    'TRwLcWuHb7j0ATZ2XtUah49Hek7SeMlme6x++Ob0/JJahcaOT6A1BPX6iLCmVUfvMxB1/RHFo9fbB1QfHTPG3p7oCLv4KwEYiLXhzxawODDqbBwO+eqesvGg'
    'tQc4mDyn4CMfeLafP8fFwMgD63vrKVvmMGK/CMwOpfWTl36riWE+v0cofaiyY0WZ7zlG+6Zbus1G+ynFWaZoy8+eDrIGUXKb4eVBWHXAibmp76mqkaebbiXg'
    'UQ+3A32/pUsqfFSGT2/xGtZA3yWkz7fsowIDvVSDyBdCUBirWpUpHAIxhuV17BWFk0K/cv0MiD3p2bn1V6eBk7GoO43lgoyM7NUqMEoe6SJHWs5533MtusqP'
    'NxGt0nVpRlWjwliWa1UbFPshR9WHTdPH8gHd/8dLfdAbShYUpyAfI5q5AAEcGPCwu/Iq40NEJ82gkaMTj8amEZjmvU0sOHcRA+cqu9fbaj51186PCAo7nogZ'
    'kYcYi8YKhje6rffL55HvNiUcnc7wFdf85QeOlo6J4NQ5gc944loYYoe+ZCmYsqxLaRPtuSU51ETKPHhr9F+CFWElqYB8VukkLzH3MVjl4YnOOYag85BLneGi'
    '0UIdLfO6sq9hL7TdvOtMrcxdij2t2iV+NS1+xv4EKk0Av8Mg7TXdTUM5VLVaBT+fzG8nnC2WyPihV6M48HGL1wFl3lbsajCfDzmUpHSpEe4MrZxzTUlkyyyJ'
    'oAWSPhWE5SPAlDhKjEYL4YtRGJp0LslwqIuYmFsR0yoiHUgPeJEZDZOWlFMWsMW0WUySI8iSssxkucyIVhqL26mdi/aoJZCx7E/DQlBHvs/Nyc6ERDbJwrp2'
    'xOu3R2/eUqCxi7Ors4OzY8fIPlTqYBGsHDzdN9wBcr4UulfAQIuyqIXg1EarpUikDXkGbBXvyG0jRVNEW+vi9UtLFKMtErYIDMwynAa2eSOOo7/quDEmpEbS'
    '1NGFd4EI39rawvMk68dtDD4+A6Lqwk9a4ah1nUXT+87VxfueU0PvrnACLdf57kidzqFwnE+PZZpKusMPoPBVvzV4yWzHeNqGpzL7jvZ4Fx4jks2nT+ApYglp'
    'mx4myEmCayAhev8UeF4C+xe62p8D/wR18RLpfLk4gSfwK6l/JidkwDZQETC8l5b8PfIBYdpvPIAA1uV8cWpitoGxEF7qMB+LmxD+nwph0X6bkx7txRH8OfkE'
    'fw6EKGp/HLUaXfF5IT5Pxeeh+DwQnz3x+Vfx+UZ8vhWfR+LzWHy+E58n4vO1+DwXn5fi80p8/iw+fxGfH+iz3WB7VKNl/mzbOKE4dryyjkRZz+YXd+IYSCPp'
    'Jq8pM2zSed09vuwJkiNnGvEIQwUaUBQ5PApIRnmotIxQoP3Vi+joh776Pnw5pl3Hsf4cRn9GPzSCAN12HBzLn+g19oWz2dblI/TyXGFEdgD76hrgXF3bjoOE'
    'W6giH5VXgUYmRC3+dLTE9LVqR4C2+m5pr/FyLqXCDSIMvw3YqgIRrDYEYeJKI+Q8XiZ0Jr+uDPQGkUdhsbFbUKfvZqVdvv+NUwSrlEplKJPoraX+kH4jn1JI'
    'd2oiJyW+CicoLat3HE8R0Ari1A6sdxkECiAAR3Gc7ykzSvFdW7xzaqM0Fn0AkhVp7uryggHwVFR+iE2fx7iXCu4WpHyRS7IbkZVbAapz7/5vqwEiIWYLnnCs'
    'XnVzYTW78MchxfpJY9FsB/uCO05wztm8kGZGAe6BOIV4QcGGaZApo8UnAFhGwZs4HHewpQYHJkfrEW3Oz9wDTBhbw70Iu5ezOUTBJ+ofTF/VdEEDdGKOEGyd'
    'ZkLM7YkXueqKCrAMmlR0Wocq/iq4OLyUbWYMHaYWtzla7Xrn5UVV6NafJBWr8OcdbS6xvT61Q16opVzCcbO9wsXbxCa/gD3NlITDeFNJ+CaYcnBQNlxQEF/c'
    'nwkI7v7jJQmBwNBFtI7RrceV6vzhWmJ31WUhEdtG2/AZIL2lTZ/tgWq3LCmLL7Oi2ha6RmwK40Y8TrhGtruWAPcxGJwKhZ9k7ZBsX3khWbKjfU38r7iTbF5F'
    'RtZlVCrVaLQ6x+J+shK3ivpGIdy1KxgJUq551ZdUkA1GJWjlUYPK6jx6TKrqVwwpjWXebX2r1q/U46Ymy2gbsZGQW6RtG6N3VXKDl1Kha+Hopm7TU9hfUQ8V'
    'KW8bN3PAHCbLQofzkErs7gzDaEcU1jVlDqiGz51c/LG12ielFp6N632q6lLWARz/Nv29DiJQDVIvlpFq4dlFAnrggkLSbG+v/CicTjE0mlid5lmRjioNJdni'
    'MhiNmYk3d1EGB4CHVc/3nqAuSjPY4dVlZXzDAm3JlhEzNtKPRMoGPXyQ6pKmqYAqjUZmfKUFd8GflcTr9FXKgkEGCDukIFJwiIcWgabpa/7mj9B2GEmT8A5G'
    'qrZRxBRQLKYW2FztScy5MzSeNxfdk99P53n2h+o80ihovnmK2lCA94vje/PN3gN60rNH6EkJKAGaWjQM59ex8YQOm2PUkzRhE7YM0Htgk4Ymr4P0Qjjyi9A4'
    '9m5jj7SKbrfdxA7CEMjuAqrVxenhQe+vaLJ/d/L6/PLq51/IjA3/iCJ4JvqA2UHt8qp75Z12T3qXQi9TNhnKyeHaCw4i5UfZd6Al/AXzhLfYxwF/nyeqRJgV'
    '9u/g63QeYZwPUYbKeq0mfMXGvKbXhIHIH402/HuS/XwC//ayn3vw73n287nXAhTQjXmQdUizWEYj4QiyWKYklaiYzBSkkCUaCsi1CAMMpAK1prgG7tEq6lF4'
    'HhCAFACU6jOojgjlhXOTGHiX5f8kdynKTlqG9ZdWhN3llnkVEDhn+8UxUKoiAS71U6d1LAPOxMK+RzJ0fZXrNRXXe0sWKof72qcf+/zshxfHqOZkBNZqHjuo'
    'pCkhNWvLIYkYQz806/ZH25XNURXq1zWWOO16Cpz3EnSQuoF35zM8USjiUQOCYHCtY+svf7GKr37stKCXDNzut1pu68XA5nOAclBQvApSe09BqrdeuO29gc0p'
    '0jSBOhuxykkkCLwTBwtteiXPxvlVOMfaIIsLPJUXtmcZ9kRFR+Y7ojZgzWNcBtQWslHgtge1O0gGWXuiayIYi6wtWVQRB1pVMvJTjevs4SOMByggvSTbPuBz'
    'PG+Qd3MMQsrY5RUFb2EBMR3hlZwft0/fHx9TldqXGu3I3gzdY4wFixiE5RqBXpU4n2c/bsN4hDWbX/Xda+y0/X8BERp0SmtUU8agfcFj9/fp2BmjIqsnWvv4'
    'IKlHSYca7YwTnJ7OzF12kKs6zpeaSEgrrQZlHcZ00YCnZTqfkBH7qfMZL1/8uM3v/8SnNWwIqCtCdhUhQm8xPNaP26qH+FOzdTB9CGj8q48tDFxlIYcu0CPX'
    '0Ek1630IIq4//vsySTv2q7e2q3IkdVrur8twdEvsyUW5Kem0gqfICpZpHXviDkFMukU9u+nyKF3QlYmRycnEXGulqAlniz9+KkWmt2Bcn7nYIEyb2HGMPt05'
    'nxOYFcWvxVLVFOW7nyhDKHQI9oMEtHlQCOymLZk2rKUft5dRxNo3s96FGyHXQ9YJTEkwc/jow7+fmgOn02k68vQyewx0lfqpSU2LGbDIcYItUFhDY/9fzP5k'
    'siSH1xgUF1sX5kDLdqmx83n84/Zi1i9U7HTCsWsamhY0PxIJ4z9RJj4AD7AZjfUF/ISxi+HhL90QYcIH8IJiNW42lnTbAkZkiBgdyjG9YMwrYUM8VU9Q5Ojw'
    'Bz5Vokcnckmc6OANFANICOVDDYR/18EbLfBbk0boUey4UiQhMPFPaPZzM9mEgf8Ia7vt7ESuLqeodtt/oQJPtAIkuagCT7jAnlaAZBlVYI8LPNcKgHSjXj/H'
    '1y18WcGpi4xacOkft00eTbltqzm0mKkft4WNNnvE4L6ssWNv3DUU6SvM2I+AAZK7AcSQ5DcHVGINzyKzZjYHV8ZjlZG+yizjbAD+ahDBCkGQ+AmDAe6xu7vX'
    'BjmrzJiaxjMcvRR+oXmXREzErfkmWLlipD5raGoDhEozd1RvuciN2+4TaJ3CuDXdptty2+4u8pnhj9vFKrvwjsvivgDrBT9aLEM+VL7F5VuiPFAl1EDarPvu'
    '0B3pExIBajDVpkIFqqApXypSWMP3MILrP8lDfnwMsilsBiShm3s4dQj3bNqrdXlb8DfcQ37qtI/hXanlVW+lg4VdQ7l0C9ZTFgeg2U1kgXjSwrZg1WYtZtun'
    '2uihXWOfRKaLHFcdxswMUQGwAYB/3GZNc3+fP+vjAJ1igihtrGBrpYzR4q6XH9suGb1Ff1xGBYfyYWFBu1LPD2ALaVCImE672Wy68ryc1x0SbSej3kUK+4u0'
    's0MbbuVwC0NF4cPWTKv2YIDmbeiBDbtZOmNc0zfay6CdNMZ5xs0ftt06vEB0tB+FjmsMzkwYSVI6OZLPMhXakFweh7CnBXyNhIPGiF1dqXwOh2QAgW0ZV1U8'
    'IUkep8uF72J/xN9tRGDmTIEE+5JPa/isAZi/7bOSNrUBTcY5hH4MEax4pSqhCxgLS1wgQwSrDaaTIDw8fzAxAJm/yhkMVmjDWWlT2Ma1iyYqveG23nCCZ3zZ'
    '9JhEVN2Hh85bDMkswdMXUzRzS85gOJuwW3X4kplEHz56QdH3dzh8QTCbH7+wqe/BAxgCmh3BvFxz/kJFv+YEBivSGczLNQcwBL3yCEZzNCyppri5XDNZRYy5'
    'gn51Zuz2bH9XMdtV9NSBhjLQexDAYJNjBTYQG8XXnjAE02l710jBpyfXxOGpDBKtZxKNItkdZ/258EQAT4x56QFeUBn0Vk8bCA2UID2JD1mJ+VRAZXahHlDC'
    'JayIUcjluQFqcQDbi+fzdcW15qlKPA2Ha4oL46m8t4TCYCdLLlo1YpIilDeglBi1A8MID7KyaKZ6DGeKhk6ervaF9/bsBF1MLrzjo1eX6ov3/rJ3Qb96px+O'
    'Ls5O9e/Zy/OLs9dHxz39e/bypPuu96F7IWBpTrTQpcZivqjfuhY6jjmywxjN/eqtirOqUI0oCDEx7w84IKScJFjAD4RzjVFuqRraKDVQ+jgkRJwJnkP1/vLo'
    'qme+f8TJkyCd8vOkxx4hidVKsY+KJ0rY6Q78c9VxUutZ+7l2ntSdLd4AYfxxJ0ov//2PkySO0k9z3H+vA74eF+OVznAR/K6HSpcH3dNTzCL3izhYwhD0lGQJ'
    '2YEIuoM8oSa+Qx9d8RxDjuMJq2uhAzz7cwL4+6Smhyd+17voXnqvugfveqeH9gCkOxXCB/YUveTB+8Ou9+Ho8ugVrM/D3gdMdYEVcsXOTs690/cn3tVbTCZK'
    'JVq5Iifvjh8qAq97H88vHip29do7OD/3To5OveOzN95x70PvGMu1bYkQmmn024wWbiE8EUaGwaBEhNVX4Vxi9DL49eiMn1IB+RwjSoFMjJXfaa/RfXPBDjgY'
    'G0MUlhthjRP0dIh1A/obICqv0PbzEmWJ3OM2Pj49O8093sXHH4rFn9DzYvmn+ByzFeae7+Hzs/dXucfP8DGGp2ZPX/n4uSjdmN1iUumFj1eSxYVnSgPpzW9F'
    '4FSZOACqiqM5WNOTeX+/Peh0QN/dA0iiTDppeJ4s5HVgUhvtBk6sSnqAKDWLtBt48FV7R8wiEYGPAdCl+MphqjE2yAF9O0cfXGR9sY9xqqHnIP4EoBuAQHYT'
    '0yXTlovnA3H1axFtjThc57P95vy9vd/8Qv5+k0IkbUQe2gXNqN3iaeFRDRWGjrlMG/iMU0yg84IHvIwvOKIoBozPj6KAXYRslJzrTFVoMgDukYcFj5YURA/7'
    'h8oJ/kHmCx+UnSqIG5QzmguifuOIyOa/JpyebV/di6nHjXBMbcaYdMDh2wIx7v20UGAzjRNirlzTtSnVu+0MCCSsgTonLE0yoHJxQN0s3UJS72McsIbvt2Fu'
    '+j7n9KC7GMlAXA6hSwoC3MCd+XfomciJ0NK4Q92HZYJTIX/C6kDiW/n884N4rX7z+2DFP3HRoDmpA+B+iFBVvu9odzZg3X6PJ1bw1vmh3+QfEfrd5NJpgDze'
    'yaiBLxtcojM9UwDunph5jGYYYdzjTH7sILIAWn8xwIbv4bO2gr6s/B+gw/BoVdqZla91Bn4UO/PxA4FexUJRps2mA2t7J6dQCEJbtRs3T20uizc/5U1PEQLu'
    'o3vvfvzg3q9c1JBlgkoyDyQyVB5v+C6ofNcBq0EeXkeH7Vml5OtRp4KVFAs61ZcYe652iXG37WZXGM1bi5n3PnaEBlim+QCRfrLdKPiEIQXxbINc+29AvCRJ'
    'IO5AoQZ/rU9upPErFo/mn+qG1pNJJrC9I51mCrLrOS6l8UG6/S1coP2R9d/9IsysFm4o4nIw1Xbw+k1B+1WTpanAWcKnb9KIFWhNLfaAKhb3a1XjTGARMiNZ'
    'A6TiYu+gS9fOYrQjPav4fbIDLW6LJrehzRe7u82n7aC9u/d0b7c1CV7sNl88f/6i3Wo3g+Dp7tOgOfR3n7fQYYy7qxgkVGZcpJOW6ixIANyDcpcyECcS1SNj'
    '7PM4vCaPs8V9egOKH3uczRYdgccdWxD2bNGY+LCHRfMo/w4eqdfAdNRbbaKy91Hpex0EMCpVBCmbrAbwRhNj+foNMeEkowyA4AIgSctmKZNqVr67ygpSEek8'
    '6MJqFcpNp0QNeJnpNYt7VxAGT7LsAEMHOK4Yh5tXU3LKidRNgLp4Yj60CwrKSyk3l3VqW9NMOrpeYiCywCI0XaXztZqKgJF0/kglZcdUUUxMzSeTcMQOb+gA'
    '12pus34iVia5wUldhUMVk8rCUVbH5fqKanfN3pHTZHrn579soMbQC0SDkrkvKRf8KVoBFz5I0+Ix6DR8v8pFjUY8xHgnwMfh/8XYNUV/ERm2QtT/vUT0EpH7'
    'SbnI/bRc5N57tMhtN0RSNFxFdyyb3ZHIVJDFd/EI3t5tPG/sZuK2QExO4G422rsglNcQCOc5jbB0vZmTPQmdPl4nW9xLlNJPxDts4WaJhmxDFtUaVR3KKwdN'
    'uzb6NCb0NeAL8pg5Gp0RP2KPp+sxmJ8CJRW+TpEjm7qMfUzyCYqAsPlf++oJCoFkEpfWML6NiNcTKdB069lTF+/B0I/2Lh8+4PThsYUnlD/0FqHffIzR2mu6'
    '+M1DxxFxNVLa2nj8Pgi9QhhyOMvu9H7fHB2M2BEyG4trhMqGPKCQmdRIWMr8nsngEvufuIo0yWsMLkUTH2JLClh5fHGLSphzyFcLodMzkpJd4NHZI9lkCRrx'
    'MkmnYA+CsgB00bH/hgam76wzyagA7GKZUtCRBO+ZkjsLUjSlvWs/byjS186QPJhTGwstZPZOClBBfvPAXY03NdM1X098tujLGqZXveLoWCLfrCrKvPqLI43U'
    'leKna9isC3JdsADG/6hTjY4mwSGNEAj9ROMBuU2wZ11o6zwostGa9lawRD3fb032XjwZ7Y2Gu+Pmi2Frbzh6sfvs+TAYP3s2efoieDJpBc+eN8V+srjvaOLY'
    'zjphjAayav2eUliVCPXyUfLT7y0WPVogkmz3v7LQGllIIgmp1Ljz/7UXADI8aYzYEHaOnsCC2txkm7PWgmAjbLX/Jqbas/Pe6atj6Nnvaqs1RLmC3VYz21Ya'
    'aN0sGJVelLy/sJyqRAGvDpQkq5flcFuyIAUHdjn0rIsRJF2Kw6VX4HtCBmSXTiE5lNP5wV6ZkHnVhYkqEzOL0uduufT5pMJA/LTCQLxXIa0+K5dWn5dLqy/+'
    'EdLqXuOFvc54/AIkxAeMx+3GE7tWYpgtN9dWm3f/RezPj7IeL0Z7bDAG2kOJHX5/q7UYQDjKtMvG4poFu8lor3F+4O1plmDhkI/22ZcqXw566IwbmPoYk6dp'
    'Jj/xRmW9ds3YOLttpxb67p1PVkM244ZR5N5F9IDtuOEKSqy4iDD1hisos+JCwtobjgP3LqAnbPD9iK3ALALWggittP07gBMhfd8XXsFvkGoTstve+TwGDAAq'
    'nkRorNNy28rOf6VJ+KNuDP74odhRGjF3dbW+r6tiZ1dVva2F0aJTCIdOJHTXEeG39564rT23EPbQNQNoO3gDg6pR1F2MpVMecxkDF5JbbUfGN6wKbyjuu3U4'
    'ViGAR11EqEkqKGEWizAfiXAa492EZhO9MKvj8c2CNA5HSadv+6PRMvZH5F5BZmjylaYVXG82npLd/SO7b6KqVzCrh09Q9rx5arOppaNFtnHvXd32hi51dbKs'
    'g8al52YkQYV8CXVDOH111Y7W6ef2MlqK2CfHnc2jEBMiol3RoxRkZLv38K03pzuJ2A5dC7Pp1lpmYh9o3/PKE3XM3qe0xiKhPaIDx9kQcpVMeeb80HJc/r5f'
    '9t7N+pZ7r54PcsqVIewZStVw1sk23gwPZUcNw5lSg++CInorjhpeWtVqJPKXTGWkj2/VComGvsnOn9MRCeDGKqIUaoX+NtoD6A9piLDjbGM0pCCMtiliMPCE'
    'bQ5o4bWeTl4EL168eDZu701a4+Fw7/ne7vjFqPXi+fPW8Olo8uTFpPl0d/exCiOPahpcw3L9N7Hcv/wXNdvzJO/Y5zyFXk9MIRKKegkzPLIfb9pvP33R1kz7'
    'RF3/OxXZTUzrav/IGdWPj17/8vsomugxj4Ljf5LC+Yf4EG2sl36DO1FBQ+1h/stLkf6SS0qzPR+1s9+fZljP5Xz+dzzggNoXBx3u+I6dxCP0xy8/jrg4cL5N'
    'w3y2VsNstf/XqZgodgApUXR1V6p4yaZKJ9VSWiBK6w+rnMiZS12TMs1xhte8EBL5RE3Dyb0462evKCADbVfH17hToZyWr8X+qFklWAOqOEtcgKDf0Q0KZAcE'
    'KDyP+IdwO+IfpIRCR/0wBiG+nrgtR/d38gc/4MOm8TAaKM8y1iXrrfau0xBaQ51g0Rb6a+LeJx30PflePjR8moD7F/2FOoBq1By9m3nqCX2OFXQE6Lio0pfq'
    'uB97sK8Wq/YTve/BoApAbQLsKulQS2sS1xu6kRGr9CmA5TvNoFuRwQMmG5AK2LrB2570TUZE6w9qFLQZoLv1NHRXoWOGBqbewGzw2SLIKogWzojJigVeHxp2'
    'DAZdN1Qt0B1tOjrkRGWod7ZwRYWo+EJvXTRGoxhBipjsmOCAN7qq2E/DgXtPf4U22Gqa6iD6RRWUyf6Kqq0w7EEWtVXTGUdD5MmfFqS3ZosEh+79eYxix5/x'
    'u1S6G6Q2io4SuX9aIJ7FExlb+tNC4l4++WbnLudlTYRwRl3QnKgbqSyyMz8ruH1MTMLTLjvx2cax2Ps05VJ5DX9oSb0U/xp6qAk3U5777J1lR34ES5xMAJV9'
    'cPrhAOPZSMWTLnRnUZkJS45LCVqaa/VKFcPaE6voG5XMXFuEqRwInRqqtW1yuxMyZMN0vzN9RAjYU4ImCQaqNa5/I5e8ffwkWcqP93myKba3KLqPzxvAUZjL'
    'AsriETkdLuiaWMlJKjb3jSepYsfY9CRVyOSPOUkV2w+dpDaa3hDPUsetF3vPn+0+f7Y3Gj/dHbf9yfC5/6z1Yvc5voNX49bjz1JFK/89SwUNdK/5xHQuQ+T8'
    '71RBv7MOfMAaBqdA3G5T/Fl1KIpXphOQgn5dhnizB7Zj2BJfYj5zHxb7mDZPVThMEBsgJ68w2FqAYmcaTO8b4srYdHxTgagqNsM9JKspVW/QrfHhfV3wbtdP'
    'PJ0T9YUxUePhg4FguHz9NDN2igCC6XwGTwW56p0y2B3+6PdlqyWNPMZTrpoL6hr+N6dLOT47eGedX5wdvj+4Ojo7FW6+FutUl9ar3uuzi57VPf0Fvp4evD3p'
    'Xryzri66R6dHp2++OaeK4KOysY6IFcbh+Ox9q/5wDNQs2Kmr6uLFxfLaxUu8+m3dDIJyUywHs8bzOe/inMFEL5VycCWOOIbHjYRBNp4yEGV2Wt0gm3UCqaq8'
    'EyV7mLFZubUvcr7edi/f8nR9IdnYY4Ota9XFBTUvDe5SEpPNGW7A+pkldbGZGtD6AsiA7uRm26YBUeZnoYeNBOT78I6C+2Fvs3uf8nSHKvEVR3HTwLJRb7Sd'
    '32PlXLw/tXofewfvcd18O7jfszfW//f//L+8Sq0fxFLeBvXx6LBLb89Oj3+pfQeVLg+OeqdXR6+PDqxXZ+9PD7sX8NzaLv4HT8mzbrdtnby/vLJOgWyQQ0sX'
    '4asePETJkDzqjCJQFbOhxBHsHBwCggo2rKPUwgQUaZCgA+hvQSSBZXwwcaF2pq5Y2j7pUktcY1srogJ1JRYy8QYA6OFpMb+Fvce3MK55TONpfDMHI0GSZBYK'
    'mhSFE1TRqD91GKZjbf+EKTWm++pCL94YFXcdyFAw/9SQMqbMFC2gFC/q41f5mq+Z6xmLjIqZp2chixHtguKa/f2+lmeDqxuX4g2YWeYhTKMp+0GKDCrWywQE'
    'c+wIrPvPNpFf75DyUAHtve9e8Y+DM+Apvaue/WW/LB931rnSdhADeMBr/Y+4SS3QF46drwEnE9aZAFUau68BKTxpUbMGoc0EbL7bEDxKprkmAvS6J8j4kiCj'
    '6LoZPHLYNeCxzE0ikncb3AvQstO5t1/dimZ2qGqqrMhXtyeQTcEBqxosLbNhi7aK1+nHaYhxhBJbkr/syWaQ9Jvkeo8KakGDzN9J3fk2uMJrQQSq+AagkrE/'
    'DojSEzpWCR2aCHVBxnAKNT12/JbyogpnzgZwHpcZG1unvoK5o7Kk2kxKQRqyv/kKqrHinq/4JcvRy0cF5pCAayfLIfCGOv6T7xwz524MkhEHe4hS1KciBcSU'
    'r1QOImMTEbXNxNYi5V3ZprF2KjUWtWjgHlDHpG5kpFPsiXoJ6iY884b3QID24JHgkxu//XSPe7ZQ61fCpZebw9S0rJiyfBU5h1mEboDQ/sehP4xdENFmFt9g'
    'AVQknDLhVLdSNUvlbS08JpP8YtO1TbHccqtNTKzWcMUMyzYE380m2rXQJLshA9cmOWtSzXauDZ50no+NWA49RI2eI7fcjYJFavXoA1Z6hYzE4t1yMcZMONNg'
    'jDHPWNqgpIau9f33/DIRneAyXjT/hDMrTBgcL6gOErp33Dt8g3ph9+qtFPYoSXdWry9FHMMog6kXaM9iUcdIa8DyQXLbwNCXHOy8xWIhpVJJ771hMOFMYlkz'
    'ZArCWq5IYEps6+/zIby0OceBCNakRCT1ncwrFMfJFHUoshNIJgRvMChEAgruySWJ7zkLvBU5ljpCJc6m9VjczHGtif0+uoUn8i3bm/atz1Dni52l0S0bLBRB'
    'DZO6YSLJn6R0z/mfhqPFuIG7M3rPMA48CqTmcfDGbKmYs4qHH8o2SAHbyGzlFsvTAB8sTkvP48M+vo+mpdsr2MFyNO1q2JO2LlITN1sMYurxnITrETHvPW/W'
    'jA0T32jLBLghhwDWtTFdimDGQSeu+6R4yZTIrF+RKpapN6IZU4fS7XZ6npaM1e3zJkh2CZNL6hlamG3tmzsaWSY4kYoYAgaL8WMREgGHQpSQ0PJHrXJf2mQv'
    'jq6ODrrH+6TrKmWcFP9MPbY01R+gYl7ZIA45f3DDCLcG2BhP+MRdScOK75TpAipDa+Zi9iCMUiFfpBjXKEBl+EQaIDXH6ENUIBmjF4VausOdURUFrSyTj1yn'
    'plUdgX3Wx5BT5L7kARp9+d2gasmK8PS6DBzL0PZDHaqunxW017VfcfwAK2YcJn8nv2ItTXGx/Yr6xfzmFd6sYqGgNW+ZagsFUJlbJfjrEx6yUCKHB6KthWMZ'
    'oU1MidhwtXCLhSJm0ntzDnNFcxMsQqaRJqTTKkcrpX0TL/x6ZWYjrX9sOtInS/UU8yMfH3tHh5fGXJp9hEK9j+e9g6veoQdsonvZuzKLB3y3VhVCPySjBMqn'
    'RleVOuhaGR3Yr7EI4tmCIpRX+N7yp8jO7y2uQJlVMVOCL6cbmhaWpB1lRtqRNqRMpP1blG389kUwWVKYrQT4KwjZ81UQ0561rxeb2J+NPgvRQWDSHA77oJU5'
    'pFm5S0w0pal/jcSozRlIOQs6+AYQ+D3DCvD6SXjXMdtDZdD6wbIbGMdxt+0JiA1Nk0TnaqSEso6K7URShWHmY6GCLHwPrQh9a3ALXP6hTaq0xQfiA+Y7p/MQ'
    'b4YJCGJ2heMlol5/Z33AS+D31mg6T5awx2F0bKQAFDxTUNQtEjvQ8mwJaXgSpiRrZZIPV/V0sUBfavK9pDlNERTLQIeQkx2kqVBbmAdnp1cXZ8cgBeH6NJUY'
    'ufJ0nUgDTry6rG9cIWsS8yiYkJNgOkk163JhmKpAyTgNpqDBKRkspTMf8imvpwpD/yitWzYsA05pSxVQcpxVe2dggLW9BQeoHS6j8TQwe4FnRPWC6UDv4vn7'
    'V8dHl29hni7O3l/1PJq47sGVJrnq/8Gy1dlM9rh0IJtUL0VL6aDWU4V2QIZ2MkD5PS61oh1NyNb7Yk/MGbeUtrOv6DlXIqf07Od2nHxpVIj22d/GfEMBJzC+'
    'LbMd0KlSzImoj7GsiLMejB43dy0wrWAeZN5kbsLJi8nVFsYqCKVCcjmWcwbu/TKJI2fgzgESmwwfY8XSaxkg2avnyi3Yw/txqFWp42/v0zy+hQ/CuYcB96Dm'
    'vb0euFKBDnrHx/CcN/cL7/JtF55jbscsx3uG7WB0Q74nsCDvqF9P2HJCeiqQcxwL3/YYXU6iYPzSWj0XP9AxRZwT+p9Q/5EjsnhEO7LnpDLFwQx+4DmmtYRB'
    'YswWH14Jn34Z8H50z0FrjDBKB5cfrGAWki+2Nby3WAY5JycqmJQx3rkADRj9pUAPG92AQDLCACg7NzCIGHs1C2CD28FVsiNTxGPOsQiTeZdiNRnNF7giPhfY'
    'iA37G1IAaqY2HwELxRBPf3PgxDIUFwTy1XInx6V1NTJDeQ5qa8YDo6g8M/D4MPih4jrkQB3krqkgEdd+sPiXPE5zG7xYSsbGW1ElU+yr2W/ZIcAjRAKTZ6ML'
    '0+hWhVXklxRf+uTssHeMe9TrozeXfQl9sEYkqIC8WA6nYXKDYXiI7yJwXuqfYvSUjfUI532b3TcS+Fpss6yVgpyRRceulEQ2AyhPBKxHiAi5iTBcU4oHC/mm'
    'NS8gdlvR+2C6uWTIyaRH3apGp+66ArGTO9bKNa7t6rjiNxHpjeMH5LaZC4AIyik4EdfNF7peLL1F4N96yDTjcBzkC8gAVvPYS+e3QZQX/Y3CRlzkqkJi64GC'
    'qyDCiFhQwAal08vcBzENFq62sV3bbHX19/cG5sxytvUO5wHidCK45bATv5J0rEw7zw94Y6UqU6zC8R2U1dzej04Pex/764SJgWvl7mIYcNHdcAOopQLGA6A/'
    '8i5ugv7oHRx3Ly/RDNlXY9IBqWsbOqj7MlC/lAMo7Qn0v7ofAgcP9uIhSq1QUgvTbR63VlB0s9HMp2suEvXIHyHHfdJuHap0GtQQMmSUtZYRyQ/ogyvy+I3M'
    'FjX617QFMXUNuijRbw5QVTCsrOWV0FM7X8W0sxZXEN9E4fZcOdEltG9ipwLVkqXlSVz2YNPVhhRBDrdouBBx/jwtSJtI38NDdipbe6C7+Y6ZU2Hw3TyLz05j'
    'aVOdg4A6bixup6YmmIUuziq4lv1pKKITF7cqjoDZGC9nCznGCeaDYCGpI16/PXrzFlOfnF+cXZ0dnB2bGCgE0iqqy+Zoqj0jhOFNctMveHdgG2Mb0ym7hedf'
    'M9gP4wfCbrk5/ViTbtYz/b39HNMvjkWRSrHnGtIL7/I07ZYBzhFSsUzpDlwsVtiDS7C8jrcVi5dyrRyahbdCRqDeOAgWXrIciqr1ivHIbZOd3WH7cXWKWWPr'
    'KOWR2KjFuqcld31rNvMXO7STkfci6XI0JTuacyjtFNr5Fz/NhAi7tkZM/s46lxKx5Y/9RYphv1jFtNKbAChfaJkTH1bpZDm1hJycNKzLAOYJdizkGPN4loMr'
    'pgr9ZEWqT6DcBCUrgGthgByLo1VYGap3ZPJSWvdsy3yZg7vas8Zz0GXJPO8PY8yNFli+GrA56cTThMF0ngQs6yeNh+cjpygAuaWkqadSUUDTQfAy1xp2KvEn'
    'AZ5bUn9gXSvzPym91CdAAOsjlmqGe2Z/65agMwr0ISdHfHt/DT/Q13/ZHqZCcxbXwRpTulwaVSuiuCpMJif6jhcmvr3vYfzP6Dtf2Pj23lOqt39C/7XrIt8+'
    'iCxi/+NG8kcMjO+s/B5LYnH/j58YcV/mW7vPYZX++ZPBd3e+fTLowusfPRn53ZNO2P0Q9pV3wX0vjudx3Tw4XytuYyy1AjhQqErEsI0Ec1Qt6G52HktOpWSp'
    'axCa2qlhn3VNvjRpJBzJqVWqCqtWOL31omLlFuqhKpxMoLtpkDXrNDCBcqFsPSth/US6p2P9xdIe/tixWg28PM/VM1OLdHmmACioqHA24DKv6HrVxKGLByd2'
    '1G6TMnrCwllKibytHT/7S+iDmCuja30b3mG0vZKu/8sfbGVdxZN+tLXDYIg07QIMaZXPGpXd0DCO/l/5qpyqAdQqrAIriOIbeicHB/mCmUO8Fy+nVBwvDoYT'
    'nhfvmq5pgRgHUhnqE+SRCGKeV9XpNAy8IVS6xZU1j8cBXubsF231N+H1DR44ZeMo9q6i4KvupiVft8rKoXEejcEwimbjaVmJ6fwTjVnMVK7IYM1h3DIJKo40'
    'Cqcf1UW//96k99I7BA9ZjtfcZSguF5PZldyWEOkYBalwml/T95pWVadscSmLQ2mfsuhUOTTLddgpX5Dm8uusW40C4ZsUpcwNxVWrnNaSTrU7m1swcy6DTjlr'
    'zBfl2B8V5gdYah34V8YjpQ8kxsOpuubCvtPkN3J+0Ts8osve3sHZ8fuT08sCJHMz0gBt4FZZ6idcTZaFyzgVtKd7L+h2NM52m90XKPjklFybWF9GXflI53q/'
    '9Q7w4WvmWfiAWdB0QdSuGohLQv/6+xVHAcOL40U+KaJ1Smt00fMlZ5HL3GmkW2JecrTqNhq4stB5njiSpKzGmr3Jth609jFAe7RY2qacmT/KXWsvg5E/wp5m'
    'lxrTAMYGRjbbdKcr9IIkoeIrpwpKvuoDAq9dFL9V1eKr9R4pkyDGAFYanBLXDuNeYkJnHCo9+IMVVHBoUQ/bKa9FxlKBew+DQMyGalzyMZXhdxhZvAQAUuVK'
    '1S4ehG5IjaribMghvYLJZB6ndad0feeMwWqxrzUS6wcKdEtBG2/lhS5gzfVWs/0EZA+r7VR4CeW5Xga2/H2BMvMmRABQeFaQmtDNe/57uyYpsFM/wm5oWczp'
    'ltmb3ul57/zKE65KHF7h7MI77p72+CYPmpGRI7Dbre1UNYAz9ogG0IeDbhiJHcIjxyU13up2FEbQRg+y5sNtnncvukCh5DFy1ft4hc0u+XpVdTPATb2Rv/BH'
    'eK9oCQqpvP/yQGMH5++9g+559+Do6hfv/enR1SU217Qd9PtqOl8l4uav2ha3VcNPuHeHh0hhavlRGm5PYRViem4WBEjGRQO4iHXRKGjgc9Csc+1vdmH7sZAq'
    'rmhvAqbkUnatVjilQkkIJRZTK1vneLKu4Ma3qzfXT2pfdb74AHGosgPjRjUFkDNRU+qPrV2QxmuIJyEfZSC5bO+2FQRL3jzbtz4vvmiHSlqIjX9RQW8I2+nN'
    'zI9vdVarHj7xXh+ddo+9Vcv+rwvpGhfSxdQHmjO9Q0UiXXYk3ab7eugwKjLZ0cG+7iOajEK8t4nuHdLLzlpG7Aw6LiAoO5GVhb3Su4aaRGJ6sec5vXKdfACg'
    'uJPDyuQagFJ6Jv+WLFBOKczXve7V+4se7BQHb3veSff06DX5JpSAzR89ru/sekf+/2QP7zI+i3KXblDgFjmOD6wPFb+nBC2Abx+ZDEgJXpjM6xWi4mZewbL0'
    '5o7B1QEa9nVdvkqRb/ggGsyT8K7Y75KYCPuVF4o1q0OV9pUFMinz0V5s0sXq9hfFuycVm1mV23OlI7Kho+e8JMXa/R08eEtAbeq7+wj5sBAzy7Wy7ug3yMSF'
    'Q4sv1Mh7YtyAdmMRtJTZnELkFfZ1j0jCCKD1YG8KMp0JrC+XJPnfqVVZDInDQTehbUUlCQCY+Zm3Nv9GX229F14OAjT0t7yfhKxKgcbLwbNmW9m27in+6NZV'
    '5a9vf32bhjBID/WoOqJYqUSoCpuzhtKh3qQ1E6KiGSMVmAJ9alErKoigiqMOMKSdGetkPYRSLqtB0RZElyl/NJ/NQF+aT8gZB2MrToM0kLdyxWrJ1gKogEIA'
    '0mnfNS/UZkRv3pUlr2+tC3xjeByCnMZZfkfCkYuCdZSsRJmhoSIiX/5qqrhkbl6zLg+0l90Knmq3aSnyWDaCkJ2tcBgkCorblRpjL4+TBSPlSLmirBkkFzAM'
    'o/UBD/51NE9SmBS6IBwD9ADdtfwoB20YZNefQdAExh7gTeq5xFlAGUXEJWvUOUw3rwl1Jn/nXB8HXU5+3T0CSdJ2ymJJZSAqhryWVlRl5/eKcQuUiurCdtt6'
    'c/4ez0BeHx+9eYvBTy+PTt8c97YxgObPZxfvehd0heZbW2VQHsY5OToELD5gGTGKc1yjBuA8XIDyLt+d/SxXCODYqMCYlcrUDAPl55R7vPhMscPgE7jVZIlR'
    'p6d+hPF34nQJSzqpG9Hac6H1tFgIuA8ZrdcyhVo7QMr1huMSacF7dsZLcucFViJ8OWVkpc8GdMEbDSTkYPebg5qOEygD6wcxxYi5eu3BpHvZpHeYm9zrRwxo'
    'lNU8WUVMnhitWvYVFXuNSXyQevDK/hRDMu9b593LS2sbJizfhlMjHx7EXdatLFbEOtfkb+7uz4zPr+x1Uo21z3ZyG8KGinI5Rz+wYf9IWNE/gDbETCqv02US'
    '6C6cfIM/3zF25/yCC70rIYjAHuLePrAw4qgcK2KbD4sDYlzEZiN0r7UoMyZUIafZGx93WQ5HhGFejzlUlMyeSQyWjLasiqdzy1/NgRdiZsxljC9IPY9RkW8U'
    'iUty+f18GIyKnSerbYbEEFP1ifJFIYqgI7Ap0d0YP1LRMZhPj/QQ7IBxYMLFhejkeIGyOJXGStH6VXt4/8yXZnqb2IKJ/f/NXetuG8eS/s+nGExgmDwhqYu9'
    'WYEKAzAybetElgSR8knAEARFUTKPeRFISoqODoF9iH3CfZKtW3dXT/dQlJws1kAQcWa6+l5dVV311ec9w8da5wcHzVbr92VmL8ODbMtWsAyvxreLLwpAgx3F'
    'Wg+wWibNP0bL4vafcg6cNs6ax+1actaErXcAZ1fCEFRJ4wPIMq02R7payaZx1j583zhot761ZoEpexoES7FPLmMBsOwbfBoHv/ouOWMrFAoRoL8AdQRpZ1jm'
    '8fBqiTHJw/58PIJPYKkOL2azrwmlf5rf3iwXVdh9XJIOiQUQxJX4QI7ZtEnuvwynGHzk1qEDabG2T7vi+NivFogmLjZ6DYcSJ9TZ9CSqRcB5ssA8GkQvH0BP'
    'F2GlSugJl3Bwb1bnqo7w4XbXIo+bcqCKyfimzIHyt76DIpKK3WiYjDOmZQWuwX3A5YZ3COJGzvYafIxVHGVq3aluK3NNyuja+aYaZexptRtHzZ70qIf743Pz'
    'DM6l9yewdZvtMx30LeO7IDuUaqv+wh4Kp/PRTK025kHIf5Hj2bUH60e0bY/FKQFf1+9Moz0Jjg+sRBsEpG8YiJ4a027P3H59m1F7VXCrADEOfRwShP6Q1HSz'
    '+RJxbvQIY5ag2s4ui1p28Hr928uRxXNpnL87bPfeHZ6BZHvlLPc7/2kkTWi6K2o792hbtPKBxWPVxABIb2iiteUjVjIwdkg3qXTHrqwuA9zEhqAQuheHJqBY'
    '1WW7jRwkpXAVzPwX7jr850N/Rnzdgtsn2FD1VBQj/yV67pKpur+s5xhOtdpZTzPlx330FEDP6XoqnJ4VRsfrKTQ0IitYpoz3CtCEW07KMjeoSMjm8XS429Mb'
    'raQgTTdEcBQBtOUfQOZyJElqaTnJzKebyycLY8bJJiZvwKMOEZ6A9RrZaDatkJkAewsK8ZLFTm67FUdFsoOjrD9AJYTeV19wHI2uNuP2G55MmUNNhepzg3sv'
    'Oq6koRkaLwboX7MXeO17fSjHYkRpc8QvFjbcIcEuwWrjyRRyzK0hPb2xgshS78NNt8LmEh8PSg89SUhjNyvFzqhaKQU4b2b3w0u3Gh7T0yPMNEPzZuSRcvL0'
    '1MLfwqNWBQXw6LWmyoJlkVAdBZXcbwF01OyC8eirE09iMtqzjQ/rt1hhVRiM+6MJvJWvKFRBkLzUDin4y8/0bbSAM7bz9EB1S4HgI0vEnxoruwetqid6jIzy'
    'l7I+umUM1mggJmuGEYTu9mBd4oWvhTa8Sg1tyk71KMdjtsKKV19p5YrbYfTKezNYyba/tEqhbwWUUkllRF3C2JVeZFOK2JOEI+mGFLrI5E8ImxuOsNkNBYjT'
    '34P+DWkj+8k2Rv9OQXEejxG2SfSPf84uQOn41Pi19/eTn1uCrPmE9c18Ld5IdjItFQyhQeHcPUi25dDyR0b/7NTM59Sbyjf8wxOvKYl8Gv8ANTYxvmLJ6cnR'
    '4cFv306/5RwOBDIa9skWBW8kHOFsrDigj1ZwznGuCVDY+iVUMeR40n8Acnhoj/t4F2kws5YJWohwetjbgcw0MFbjYQWtQOiDV02OaM0nUu2Cjn/4m7MIsecW'
    'Tj2IOSjab9nMQpx7CNqCDLdK2LC9yXDS69/1R2PUYHvXF0Zc9eAwHaJCiphbgy0oheEW5H6XYo4FzmhfT2+XV5W9KM7C1zvOhZW9iR3DeqadEVq+DRg6snz4'
    'StLRpigf7YTXul/vOg643NqF7dsLGyL19Y7X96fhpGF6Tos6+fpzapLeljwJQa5AgIh4f1a32f9zM6B8RDUpHJ18QNwV9O9TO468BNE1tUj+fW9LhcZnOHQa'
    'mAAeE659+Nm2OzJXJdxvQQHYiG/3xNyNjrjkfAhk9tjcGvv+zW7k+x/yv9/djnz/Nv/7nRj9N0qu9V7sFhqwbT1PSIlv3C3DITAt7pXNL29Ut7ZgSsqKFgxQ'
    '6E65GbuLumEiVw6aVnK8MFIZdr6ANmJ8B/ypefa5+Zx2RIvict1RPDhOnxgysL6jXguNee9adik95e+qytDOqO7+h6rNIwlMvkCD/I8mGsBVgsLx7HqE93Cg'
    'QF/POft6Wkt2JM8e7uj+vLe4m/RAARtdINbCpXovyajxnCeUOfOc8B/g5B0Snrx5is6Ovet5/xL5c+9iNqMcAV5111+W1xcT9UiwDPRvSqi4GyRJfBtPergb'
    '5C3cyWYhfBNkFXyLOQKZ9yI3V7qQMAtKH69FgCfuQyR4A6YgFbqcCjOkjKtNzRRNfVAJ8lYlzFzfYGxpJyPGeAf6SHeFrH7Yg64lMXgJiQMi0T5pw95ufzxs'
    '9Q6PP58cMMAiQyxpAqTuNtGWitKNU+vZ7JSggycjdON52mw3lABp7uqhEUsECZkvlnj+VgtDIdez/rF0P2Ae4i258TzHJhStaFcqCAaQQ0ZT0U9wBEJvsQNh'
    'BTJdveXkxqvLOuiqTBjk85ETbYDji0RMSJs7kPBpJ6WvyX8I82lQ7DFmdC3y2zyqXTjoUQEE9XQwG0J70pihKVvDFHNKTwvqFaPvx2vP5LgyVZdyqhaKcOCv'
    'pReJ13mC4pWkdSeyfrurV6PxeNovbuP9vm6Ae6EpGZcvb1yq91+G82HRfwYiPpSmEHR/EH9Ct/+wZU5nnCB20LWddZva12Xuq+mo1UUwVNemoTmjogri/zqZ'
    'KPuFiZtfUFu72rIicZKLjGdD7hYhAD7oUKlrTyssXgV9a9SfosiDl1Roz1+gSXx4h0IzHDWUtpJuCviyUqxbC9B5pugMQsmY95NhHyRnvtQ0Wx+WBZBkAyk6'
    'rgC7JDPpwvflWdIdj70DhcZP6fYTdeZhtdD83Dxum2BRq/6l1D7JhTOa3s0G4s16mZ8cJycbjjnIMAynTMF6wugluIRNXHO5zCgjuK21FOFPNLTP/R1tjlo6'
    'HgYYfuPsZIiYxiZ6GFz8FWzKcjQQTmiujxQs54X/lfOZmhAOondkLDKhNmWWP3B5wVv67URnlA+vL4BiF3mxu5ilOWyR1Slrvqd5XDCof8ZeFS3vNifiE2Ni'
    'CL0+PN8o/EDUe1tLyLm9RnTgNe6PNA0a577xauwqWVt/DnzgHSy09xSnLpXWvZKw4dzZy346aOOkKN7p7L6Ifrj4418zOL/JIecKfxbTV7+9mry6bL/6+OrT'
    'q9arf6XWSQdkdrp8YRcZm1/ZLTc4wbbiERUUcMML5G4vzRDcJPVEQQzo9TT5G2gleyXzAGcRU/eCSFBJ3jda7awxwST0Bq7fPvzEfzR/bRy0jUcU+sujbbGU'
    'W8cR2wbsNTDp+QlZ7X/Y23YFG+LRYMxV9h+qvhaR0livbLFTlog4l4NjNlwsKkrZoiCxVZCzGLEsqFHJg5ghugjql3IDqe+UXOsPNqUFG7OkxoZ2K6pQC0+v'
    'x1Jay3OjZPZzAnpmUvww+rnkSlylj1k9tFbduVp5zUwM00hY83TFQ0VODxUZacTz0BXFclFFzBZt2ptd5Pe6j+Tjw6GSZOSBtcXMHWYfK7OxNMT+LUHxjJGg'
    'H07WZfvQah69t3E/zJPixSQmSIr1xI8K3cltOBFSLrrJigXt2HqflQrekmyzqC5c3Rsb23k/wGjffkypS4zhC4UBDP+xlFvZ9NuUbY0ov28ctZqpmp8wBzd9'
    'HXypDIEWhF5ae3588LFx/IF8PgNGULhA+/XTuZaM1HHZw83cU5sZdfo+IdaQMoGOrDcgjlR+EjNgAf1C8eTlnwt2JrFpNS4eegbCGTQR/ZiWHV6XoPZWg0Jl'
    '1sLwz1UBhLWbHhvb2UNFJ3/sCSSpDWNXuufE80jx4axEpAwaR1I7CbUd51WCHweWNRYQQRwV8ZAkTVtkwvfWubJmDrl82RQISoNwtHqR9pOFFpvv9FmvF7bc'
    'k12xX5a8XF8/kDFRhn3Zdy4WZuht4rvD6WB8C2xGVgserygVo55qMGSBu1ze8q0B7SbsB4PMUmY8EnmrUvtEbAEEoaKPA+BVHby3nd2DrkIaPoUgUK1VSiIJ'
    'jcK+zzssvXaVkcDQHoS0By+nfWBpkwvocIBL8HZSjCzUkiMrfeThdvI1X5vllf4bWSJ3ys7sUsqQHGiS3BaP+JahEDt01MzjV9KdsqFVMkuBVZ8eiXbFOX7B'
    'cnw5cdJ9OXE6ADxfzAd1dM+UBTMFtWmGS/7ydjJ50Ojy1+PZBTBFKzbaiy0UhQcyO/wQaOJT/B8MgZj7WUfz/LKsWsQh8WQOMeRx0nf0laKvN9USTxwNrx5r'
    '+dfsOkg4tHwV1kQKx5PT6yIcLuzlmlevBT2BxosXqnZCy+pyQgc/5uf+HavS84SkeqIJaxUw7t4W0QoNVoV75d3vOmXRtNI8iLrNyTJ0b5RWKeNKYzK75uhE'
    'r6MRhBZcW7lWosJ6iBZXNmoRKmyMc+MIrf9S08zDu3G04l9oGvnwIo5K3jdeW0IIjFwcjcw6DSAtQq6ll73WwWueHK++CjTzWnCJpB0DM/orqiGwXDv2cdnX'
    'avlFFxM3jK6niNXHF+7OlTqA4oqq9OVc3dpy4SX0g50U2ZsOWDa6X84X9Z3d7e3t2N0qCbA6wW6VzAtEJHuv6qxzEhGUBleUWK5TsfXWutEbSryfhWehDJL+'
    'eDs1di4SkyXUAOaxljxCkdVPacFeX6A0WCSkcmRpm3ghm7CBZyX+lkKbOS0/lfC7v8TUknTNSMmIPTuo1KTdxuR7wRVSBlLyv09L1p0MT63CGh+wrC+kcfWy'
    'LknKV1NVWTcN9koKs495gGkHMe2qles3GXHt4qHkowc1DiO5WsGNL530TRNLxcLFExv9ZGw96Gj7yEOw6vVMDx9N51ZVPA8sjSukQA4HhiKaI2OeBry8p3d+'
    '9Ji6J4FHnfWBZF1B/R1d5hbwUY2wAI7G058TRhEZ6vK4ay6NAHOIyFjGbekRB59i6hPM9QOCJzBmhB4F3RSRLuazxUKUGOgjqpo98l5a5Nccufk2oeZ5Eup3'
    'yQHwTo522KNYJcorOvoDsQZGY8NG2PvkZjSdchAP2tfZu5bjZ2FRCzmgshjMRzeSYzx5NyMT6XxYIa7Upxgl4FNbo+mXIbLtS2PNqND6wxVx15+z7iISh4JG'
    'wfuYfDNH7shoY4odk4iZ5anybHAhCmHbmE9OkIN2rOMmrO3FA6xvMiBhxwk8eTa+Q9fDck47uuIxPGP1x8TBVU9pZzn/2YnHlS5h9uq8Cb3HwCHqikir/e7k'
    'vF32zjE2ubr0ENO7OvyXYVy96fAeRp38AVQBo+oMfEUBqyNQwNlAC6GgcdRQBQklbPyfljZZfK4JM/NFE4OHYZmM//bKvNMjwaI2YuldMShb1naTJ6dnWLUk'
    'DidNtoPdq96MLrusUnlxY52jBpqUksd8m9D3ZFZlWqXV1mPU1rvqJo84OLUf36wSw4o1EOX3CdSW/FtGqv7I/1+lHvM/sMw/xTtUHZQmYgEKidwUczz4Xgh4'
    'IIfaDavMMPs56r3Tm2wzbI3XtsZMVf3pQzFbkk6v/MosUYH0xt6QuFh0Qiq7Flknd2RMymYRCFVWj/4uOTVGY3ILZAc+DBij0EzkhlOUBslTYoTBZodXyWhp'
    'XfNhnw+gGDQezhDDKbEr/YTcW8gJ0XkS/nN2wV7+SKssqEtoE6SaoN+3ZGx2voRVe2c1uvyjbBw1hiQcgUTjGWaUcyDFGmcEARmae4RQzwycf6VlXFMu/zBW'
    'KxxQ4wVJl7o0QeWE3KopxJVSlbNsQn2ccYzrGN7t8+WHxDwLSb4HJtu6OTYNxgSmrdUQAcklHC/owonnF8rJvlUMlJ+qmfbYQscVth26/xWyq8GoC8P5ZDRF'
    'YVGWL8eEyeCqRUp2sexK1XFFxOJpqRPD9G7gmbnMEMLeD/l2eHcPUdiBr6Px+Oa6aJgTLD/Qn/rjauvwQ7t59imbPzrPCXJtNab5VTsWxdC182naRAZEf3pB'
    'czgiazbxZ7qOJPncpJf7U4b2HiSbYWx0Oa+SqvlH26RaIcjDsBgPhzfF7epO6a+etF8Oj47+3EnDyr59vqL1WKsQnMJdShOrV8b6GjzKUUPlc+KTXhDXE8bx'
    '/B/F7fjKXE6YTph45KXdMzF8Ob1bH6uX0T2Z93VqaCjpZhOMFOz6kF2n3BMRsEW5GuJ5SNu5pjByxGVeAyXglbfDBFS4lEvg+rQz9UopUiou7xKsRPtctwR/'
    '04eeSJL1fBK7iSoIGx04AN6rf2C5Jmi4dxlslCkeCkZfpJbbO2lOUEZ9TK6GQ3u2K4nF70t27zGZeo5j8SgjdLFA6Gfu9OfJk4usncNe4LNz93bsCgSh4aU5'
    'leiZG7Ifzuy6RoIrxeDXsVSU05p/lKwj3LDEXlQ/aTKBWFiJZzEzIqzKnAcLUV/WYVK80KoDPF3udD08O+T0kRMNNOPJIliC88yRJgdNFqIIPssdENw5o+nt'
    'MB69i400cfs32eRF0SPFZ/ekVkQOlvWHwmZHj3c4rD0gnrRm2mPX3pTkpzewtzSsOnbDtEBQtogzAyJkyaVmzAnty0wVvQn7akuKUe45h0lA7IlDIi/ee/PQ'
    '1meEt0aPSq+3OYXWxLGGsazqStOF7K8ZQx9IOcIAwltaJSHMB+EFbSmy8XKtAMbE7S3NwLdiMVyC8tG/HUed/zvdktm4wS1gaS111LE7StvuPoPOcNy/WdA9'
    'e3z3ZL1mQgJLsunFHSIieVzRABFff2kn39CyxrRi8HCMYeX3yAYim5D6M6cBOHz1RxzJ1/jn6+4q+Tfzgvojj6W97HudvQN9XZbL29fT/vR1CRh/dfdqtQAC'
    'ebUB5wjJhtejzycslk2ctPqjm31bTuYcKp/NQV/vGUeUorwordYQb7YbbqJx/4dUln2iwAdh/VFZyCo7qzzuY81Z5Rcl78OjCe8Ayd/f3gVmL7j/Ks4aRdT4'
    'Vsaapk8y0iKsoj0LUGfdAWAND1b7KhrH7BGLfkTLrP645pxbpSXRCDbh1TH+alWULHt9XEWggX3fOcPB5IKRaURdFuzMR5hb4DqH6yuHJ6UV6yoY/+BKOyqL'
    '4zF28fysmfzPf/23M+zmE3Az5PvZJjhfa8q5q+CgHPEqGQ7gV7lE7Cjldf94eC8myeGCBu5mKK6a7bPzZi5d4zFd8cVnLCdoDGgl5C1AopXgtRrJKZ+wm4+s'
    'vE1By1rgzWDfsgCOygAJ5+RpVfAhI711YRCyssprqHpA2dhHypqkIzRLft73Yr7qXLJtWKccfpe8G14Npwsc5+vb/vyyZvFy5sniy+x2fAmDft9/WCQXw8Q4'
    'E4iduY/wbMA5UAOvbtb6goj0vwwfLmZQ3aHBLfIAcX6fqn1xeNxunp2dn6IP/0Hz8DPwnEpiDIw01nqZJHKllVDc1EISbler1QjoXmiyTYN24cKARnAYwn6m'
    'Lls+gubl4pH2PdAhg4dclWXKfiruBthCrLsYxLKVEzWuxOJ2MunPHxy21V8HlmanwDuQNnblyxXBEL0+753GLWMZQjlIbSZY/n9ydvrzMNpWhTgEmHNzap1/'
    '+tQ4+038nIJ1ohAnMfyOEadVikHyFuZC1QIDRW+M7sOf06SgYUOXjkP8sJleShRL6L+DyXRAzjeCBL0SB58N6G2OcyPeRAXBXtb1bFAR3T8aPGhD6nmbuZjp'
    'IgFf0vD7TUIbArFOSUYlk+OC89ft9bX7fJMt/CfnItNghibaomeyvHgLPbXYiSabWMroKWSuJI/6G+Do1veajIO2VRxaWXj+7qdMjFhCLJW2QNR8Wi5sxi02'
    '5xTfwi71fIZcU/IhbsQ7zQIxS3Q5W/bHJjWIWZomPJRXq/lEL14z52sZ3wZMT3zMnZ9xPE7TxsBKhcH3JgyQXNmiRWRz5RTTrNUOEa9/4q83aMCXuUpPh/MK'
    'ofPBiLO31ATEpdu5BbhHq77B+8lNuCRevfvJJbtNTfpfMU7NuoUl5BZW4UAgcQtjUCuGHYJNCGILzQb5cVEUK7qZGZjRVWHzwyTLg2IxmCCXZlQvT7hTop3R'
    'dQ4+Ng9+OT0BMQNWYqOdHDUxZPPkuKmVIorBIql3c7YZrZixwJMG/MKCgpXPE2wDQ1uJOSm42gxko6HltdwGlR6ftJPfmm1LYl0UKZ+sAnCXiZTUp6mLreOT'
    'bcsea1umGizijY0tw+MXUfypFjVqLqDSMJpsACqWyOVCtvihs2Qac6CqMGPd2ZAjZSIvEczT4gWoYM94AHe2qDlDk2hRb5ubsmfG3SRQml3ZkL8EpdfUHGcz'
    'f2noI7OcJcFX2xRoMZqnclZXdv0Pk3XhlJLUETXJ+6n68uWb+Lj5azuJ/uPseMmbN7B2zGbGofo+2d1+u51AuebZceMocQncWoahrGNX6yok6OGk/bGZvD88'
    'g6pkmwnTgiWwn7w7IW6Afr+Hx+fQpBPTzBhbWVfZWRMTdmBlh+9gYaN8kSheCoRh+Zx/ijKbXJ6sbWHOO7uHorv/eUeu8RmovmGyhzbRZoh2LM4fmjjTIU9j'
    'zdqw9kNjIlRYfzS1op3pfwGVYwAH'
)
trainer_bytes=zlib.decompress(base64.b64decode("".join(_CELL32_V8_B64)))
assert hashlib.sha256(trainer_bytes).hexdigest()==V8_EXPECTED_SHA
trainer_text=trainer_bytes.decode("utf-8")
# Static route/helper assertions before commit.
assert 'SELF_TRAINER_PATH = PROJECT_ROOT / "scripts_manual" / "Cell32_Benchmark17_Production_Trainer_v8.py"' in trainer_text
assert 'cmd = [str(Path(os.sys.executable).resolve()), str(SELF_TRAINER_PATH)]' in trainer_text
assert 'ampscannerv2_production_v2.py' in trainer_text
_amp_marker="AMPSCANNER_PY = r\'\'\'"
_amp_start=trainer_text.find(_amp_marker); assert _amp_start>=0
_amp_start+=len(_amp_marker); _amp_end=trainer_text.find("\'\'\'",_amp_start); assert _amp_end>_amp_start
_amp_block=trainer_text[_amp_start:_amp_end]
assert "import pandas" not in _amp_block and "pandas as" not in _amp_block
assert 'writer.writerow(["sample_id","y_score"])' in _amp_block

if V8_SCRIPT.is_file():
    assert sha256_file(V8_SCRIPT)==V8_EXPECTED_SHA, "Existing v8 trainer differs; refusing overwrite"
    trainer_action="EXISTING IDENTICAL v8 TRAINER VERIFIED"
else:
    atomic_write_bytes(V8_SCRIPT,trainer_bytes)
    assert sha256_file(V8_SCRIPT)==V8_EXPECTED_SHA
    trainer_action="NEW EXACT v8 TRAINER ATOMICALLY COMMITTED"
compile(V8_SCRIPT.read_text(encoding="utf-8"),str(V8_SCRIPT),"exec")

# Prove a real child Python process resolves and executes v8, before benchmark launch.
self_env=os.environ.copy()
self_env["GENPEPT_CELL32_TRAINER_SHA256"]=V8_EXPECTED_SHA
self_env["GENPEPT_CELL32_SELF_CHECK_ONLY"]="1"
selfcheck=subprocess.run([str(Path(os.sys.executable).resolve()),str(V8_SCRIPT)],stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True,env=self_env,check=False)
if selfcheck.returncode!=0:
    print("v8 worker-route selfcheck STDOUT:\n"+selfcheck.stdout)
    print("v8 worker-route selfcheck STDERR:\n"+selfcheck.stderr)
    raise AssertionError(f"v8 exact worker-route selfcheck failed: returncode={selfcheck.returncode}")
assert "CELL32_V8_SELF_CHECK_PASS" in selfcheck.stdout
assert str(V8_SCRIPT) in selfcheck.stdout
assert V8_EXPECTED_SHA in selfcheck.stdout
print("Worker route self-check  : PASS")
print("Worker trainer target    :",V8_SCRIPT)
print("Worker trainer SHA256    :",V8_EXPECTED_SHA)
print("AMPScannerV2 helper fix  : ampscannerv2_production_v2.py / stdlib csv / no pandas")

migration_payload={
    "schema_version":"1.0","created_at":now_iso(),"status":"CELL32_V8_EXACT_WORKER_ROUTE_RECOVERY_LOCK",
    "prior_incident":incident,"v8_sha256":V8_EXPECTED_SHA,"run_plan_sha256":sha256_file(FULL_RUN_PLAN_PATH),
    "ledger_sha256_before_v8":sha256_file(RUN_LEDGER_PATH),"ledger_status_before_v8":before_counts,
    "root_cause":"v7 parent spawned worker through stale v6 trainer path; v8 pins child command to exact committed v8 script path and verifies its SHA before every spawn",
    "ampscannerv2_helper":"ampscannerv2_production_v2.py","helper_dependency_fix":"stdlib csv; no pandas",
    "scientific_protocol_changed":False,"model_architecture_changed":False,"hyperparameters_changed":False,
    "dataset_or_split_changed":False,"seed_policy_changed":False,"threshold_policy_changed":False,
    "score_semantics_changed":False,"source_test_read":False,"external_target_read":False
}
if MIGRATION_AUDIT.is_file():
    old=json.loads(MIGRATION_AUDIT.read_text(encoding="utf-8"))
    assert old["v8_sha256"]==V8_EXPECTED_SHA and old["run_plan_sha256"]==migration_payload["run_plan_sha256"]
    migration_action="EXISTING IMMUTABLE v8 RECOVERY AUDIT VERIFIED"
else:
    atomic_write_json(MIGRATION_AUDIT,migration_payload); migration_action="NEW IMMUTABLE v8 RECOVERY AUDIT WRITTEN"

os.environ["GENPEPT_CELL32_MAX_JOBS"]="0"
os.environ["GENPEPT_CELL32_TRAINER_SHA256"]=V8_EXPECTED_SHA
os.environ["GENPEPT_CELL32_TRAINER_PATH"]=str(V8_SCRIPT)
os.environ.pop("GENPEPT_CELL32_SELF_CHECK_ONLY",None)

print("Migration audit          :",migration_action)
print("Trainer action           :",trainer_action)
print("Recovery mode            : RESUME ALL INVALID/UNFINISHED RUNS")
print("Speed mode               : 1 GPU LANE + WEIGHTED PARALLEL CPU LANE")
print("Timing mode              : TRAIN + VAL + WORKER WALL + ELAPSED + PARALLEL ETA")
print("Scientific protocol      : UNCHANGED")
print("Source TEST rows in C32  : FORBIDDEN")
print("External rows in C32     : FORBIDDEN")
print("="*128)

exec(compile(V8_SCRIPT.read_text(encoding="utf-8"),str(V8_SCRIPT),"exec"),globals(),globals())

Ledger before v8         : {'TRAINED': 429, 'PLANNED': 250, 'FAILED': 1}
Existing TRAINED-like    : 429
Existing FAILED rows     : ['ampscannerv2__GenPept_Curated_2025__seed_100']
Existing RUNNING rows    : NONE
Committed runs           : PRESERVED; NOT RETRAINED
v7 routing incident      : VERIFIED
AMPScannerV2 env preflight: python=3.6 tf=1.2.1 keras=2.0.6 numpy=1.16.0 biopython=PASS pandas_required=FALSE
Worker route self-check  : PASS
Worker trainer target    : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/scripts_manual/Cell32_Benchmark17_Production_Trainer_v8.py
Worker trainer SHA256    : 0ba627482077c879ef38c75a84e45c5430aadc6d54ebd014354ecd8a43c1b825
AMPScannerV2 helper fix  : ampscannerv2_production_v2.py / stdlib csv / no pandas
Migration audit          : NEW IMMUTABLE v8 RECOVERY AUDIT WRITTEN
Trainer action           : NEW EXACT v8 TRAINER ATOMICALLY COMMITTED
Recovery mode            : RESUME ALL INVALID/UNFINISHED RUNS
Speed mode               : 1 GPU LANE + WEIGHTED PARALLEL CPU LANE
Timing mode              : TRAIN + VAL + WORKER WALL + ELAPSED + PARALLEL ETA
Scientific protocol      : UNCHANGED
Source TEST rows in C32  : FORBIDDEN
External rows in C32     : FORBIDDEN
================================================================================================================================
TensorFlow GPU preflight: PASS - {'tensorflow': '2.21.0', 'gpu_count': 1, 'gpu': "PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')"}
Stale RUNNING recovery   : NONE
================================================================================================================================
CELL 32 v8 - FAST RESOURCE-AWARE TRAINING + TIMING + EXACT WORKER ROUTING
================================================================================================================================
Locked training jobs     : 680
Already trained          : 429
Pending this invocation  : 251
GPU-lane pending         : 51 (max concurrent=1)
CPU-lane pending         : 200
Logical CPUs             : 8
Available RAM (GiB)      : 10.6
CPU capacity units       : 2
GPU CPU reserve units    : 1
Execution mode           : GPU serial lane + weighted CPU parallel lane
Worker trainer path      : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/scripts_manual/Cell32_Benchmark17_Production_Trainer_v8.py
Worker trainer SHA256    : 0ba627482077c879ef38c75a84e45c5430aadc6d54ebd014354ecd8a43c1b825
AMPScannerV2 helper      : /home/pc/genpept_benchmark17_work/production_helpers/benchmark4_FINAL_v1/ampscannerv2_production_v2.py
Timing context           : parallel resource-aware; context is explicitly logged
Source TEST rows read    : FALSE
External target rows read: FALSE
Scientific protocol      : UNCHANGED
================================================================================================================================
[LAUNCH 1/251] GPU bilstm_attention__AMPlify_balanced__seed_109
[LAUNCH 2/251] CPU ampscannerv2__GenPept_Curated_2025__seed_100 | weight=2
[1/251] TRAINED bilstm_attention__AMPlify_balanced__seed_109
          lane=GPU | train=74.55s | val=0.32s | worker_wall=98.67s | elapsed=00:01:39 | ETA_parallel_est=05:00:00 | active=1
[LAUNCH 3/251] GPU bilstm_attention__External_Benchmark_3__seed_100
[2/251] TRAINED bilstm_attention__External_Benchmark_3__seed_100
          lane=GPU | train=116.92s | val=0.39s | worker_wall=137.86s | elapsed=00:03:57 | ETA_parallel_est=05:00:00 | active=1
[LAUNCH 4/251] GPU bilstm_attention__External_Benchmark_3__seed_101
[3/251] TRAINED bilstm_attention__External_Benchmark_3__seed_101
          lane=GPU | train=97.76s | val=0.35s | worker_wall=118.34s | elapsed=00:05:56 | ETA_parallel_est=05:00:00 | active=1
[LAUNCH 5/251] GPU bilstm_attention__External_Benchmark_3__seed_102
[4/251] TRAINED bilstm_attention__External_Benchmark_3__seed_102
          lane=GPU | train=113.99s | val=0.34s | worker_wall=134.61s | elapsed=00:08:11 | ETA_parallel_est=05:00:00 | active=1
[LAUNCH 6/251] GPU bilstm_attention__External_Benchmark_3__seed_103
[5/251] TRAINED ampscannerv2__GenPept_Curated_2025__seed_100
          lane=CPU | train=514.75s | val=0.04s | worker_wall=531.19s | elapsed=00:08:51 | ETA_parallel_est=1d 20:15:56 | active=1
[LAUNCH 7/251] CPU ampscannerv2__GenPept_Curated_2025__seed_101 | weight=2
[6/251] TRAINED bilstm_attention__External_Benchmark_3__seed_103
          lane=GPU | train=114.38s | val=0.35s | worker_wall=135.22s | elapsed=00:10:26 | ETA_parallel_est=1d 20:07:05 | active=1
[LAUNCH 8/251] GPU bilstm_attention__External_Benchmark_3__seed_104
[7/251] TRAINED bilstm_attention__External_Benchmark_3__seed_104
          lane=GPU | train=128.89s | val=0.35s | worker_wall=149.61s | elapsed=00:12:56 | ETA_parallel_est=1d 20:07:05 | active=1
[LAUNCH 9/251] GPU bilstm_attention__External_Benchmark_3__seed_105
[8/251] TRAINED bilstm_attention__External_Benchmark_3__seed_105
          lane=GPU | train=92.35s | val=0.35s | worker_wall=113.10s | elapsed=00:14:50 | ETA_parallel_est=1d 20:07:05 | active=1
[LAUNCH 10/251] GPU bilstm_attention__External_Benchmark_3__seed_106
[9/251] TRAINED bilstm_attention__External_Benchmark_3__seed_106
          lane=GPU | train=75.44s | val=0.38s | worker_wall=96.34s | elapsed=00:16:27 | ETA_parallel_est=1d 20:07:05 | active=1
[LAUNCH 11/251] GPU bilstm_attention__External_Benchmark_3__seed_107
[10/251] TRAINED ampscannerv2__GenPept_Curated_2025__seed_101
          lane=CPU | train=509.28s | val=0.03s | worker_wall=518.63s | elapsed=00:17:30 | ETA_parallel_est=1d 19:35:48 | active=1
[LAUNCH 12/251] CPU ampscannerv2__GenPept_Curated_2025__seed_102 | weight=2
[11/251] TRAINED bilstm_attention__External_Benchmark_3__seed_107
          lane=GPU | train=92.38s | val=0.35s | worker_wall=113.18s | elapsed=00:18:20 | ETA_parallel_est=1d 19:27:03 | active=1
[LAUNCH 13/251] GPU bilstm_attention__External_Benchmark_3__seed_108
[12/251] TRAINED bilstm_attention__External_Benchmark_3__seed_108
          lane=GPU | train=93.78s | val=0.35s | worker_wall=114.35s | elapsed=00:20:15 | ETA_parallel_est=1d 19:27:03 | active=1
[LAUNCH 14/251] GPU bilstm_attention__External_Benchmark_3__seed_109
[13/251] TRAINED bilstm_attention__External_Benchmark_3__seed_109
          lane=GPU | train=91.55s | val=0.34s | worker_wall=112.09s | elapsed=00:22:07 | ETA_parallel_est=1d 19:27:03 | active=1
[LAUNCH 15/251] GPU transformer_encoder__GenPept_Curated_2025__seed_100
[14/251] TRAINED transformer_encoder__GenPept_Curated_2025__seed_100
          lane=GPU | train=60.33s | val=0.40s | worker_wall=74.33s | elapsed=00:23:22 | ETA_parallel_est=1d 19:27:03 | active=1
[LAUNCH 16/251] GPU transformer_encoder__GenPept_Curated_2025__seed_101
[15/251] TRAINED transformer_encoder__GenPept_Curated_2025__seed_101
          lane=GPU | train=58.03s | val=0.41s | worker_wall=71.81s | elapsed=00:24:34 | ETA_parallel_est=1d 19:27:03 | active=1
[LAUNCH 17/251] GPU transformer_encoder__GenPept_Curated_2025__seed_102
[16/251] TRAINED transformer_encoder__GenPept_Curated_2025__seed_102
          lane=GPU | train=67.63s | val=0.40s | worker_wall=81.56s | elapsed=00:25:56 | ETA_parallel_est=1d 19:27:03 | active=1
[LAUNCH 18/251] GPU transformer_encoder__GenPept_Curated_2025__seed_103
[17/251] TRAINED ampscannerv2__GenPept_Curated_2025__seed_102
          lane=CPU | train=499.76s | val=0.04s | worker_wall=508.15s | elapsed=00:25:59 | ETA_parallel_est=1d 18:55:52 | active=1
[LAUNCH 19/251] CPU ampscannerv2__GenPept_Curated_2025__seed_103 | weight=2
[18/251] TRAINED transformer_encoder__GenPept_Curated_2025__seed_103
          lane=GPU | train=67.17s | val=0.40s | worker_wall=81.15s | elapsed=00:27:17 | ETA_parallel_est=1d 18:47:13 | active=1
[LAUNCH 20/251] GPU transformer_encoder__GenPept_Curated_2025__seed_104
[19/251] TRAINED transformer_encoder__GenPept_Curated_2025__seed_104
          lane=GPU | train=44.43s | val=0.41s | worker_wall=58.31s | elapsed=00:28:16 | ETA_parallel_est=1d 18:47:13 | active=1
[LAUNCH 21/251] GPU transformer_encoder__GenPept_Curated_2025__seed_105
[20/251] TRAINED transformer_encoder__GenPept_Curated_2025__seed_105
          lane=GPU | train=63.05s | val=0.40s | worker_wall=77.06s | elapsed=00:29:33 | ETA_parallel_est=1d 18:47:13 | active=1
[LAUNCH 22/251] GPU transformer_encoder__GenPept_Curated_2025__seed_106
[21/251] TRAINED transformer_encoder__GenPept_Curated_2025__seed_106
          lane=GPU | train=63.43s | val=0.40s | worker_wall=77.31s | elapsed=00:30:51 | ETA_parallel_est=1d 18:47:13 | active=1
[LAUNCH 23/251] GPU transformer_encoder__GenPept_Curated_2025__seed_107
[22/251] TRAINED transformer_encoder__GenPept_Curated_2025__seed_107
          lane=GPU | train=75.06s | val=0.40s | worker_wall=88.82s | elapsed=00:32:20 | ETA_parallel_est=1d 18:47:13 | active=1
[LAUNCH 24/251] GPU transformer_encoder__GenPept_Curated_2025__seed_108
[23/251] TRAINED transformer_encoder__GenPept_Curated_2025__seed_108
          lane=GPU | train=55.09s | val=0.41s | worker_wall=69.05s | elapsed=00:33:30 | ETA_parallel_est=1d 18:47:13 | active=1
[LAUNCH 25/251] GPU transformer_encoder__GenPept_Curated_2025__seed_109
[24/251] TRAINED ampscannerv2__GenPept_Curated_2025__seed_103
          lane=CPU | train=496.70s | val=0.03s | worker_wall=505.36s | elapsed=00:34:25 | ETA_parallel_est=1d 18:21:18 | active=1
[LAUNCH 26/251] CPU ampscannerv2__GenPept_Curated_2025__seed_104 | weight=2
[25/251] TRAINED transformer_encoder__GenPept_Curated_2025__seed_109
          lane=GPU | train=63.85s | val=0.42s | worker_wall=78.16s | elapsed=00:34:48 | ETA_parallel_est=1d 18:12:44 | active=1
[LAUNCH 27/251] GPU transformer_encoder__External_Benchmark_1__seed_100
[26/251] TRAINED transformer_encoder__External_Benchmark_1__seed_100
          lane=GPU | train=44.44s | val=0.42s | worker_wall=59.56s | elapsed=00:35:48 | ETA_parallel_est=1d 18:12:44 | active=1
[LAUNCH 28/251] GPU transformer_encoder__External_Benchmark_1__seed_101
[27/251] TRAINED transformer_encoder__External_Benchmark_1__seed_101
          lane=GPU | train=30.79s | val=0.42s | worker_wall=45.79s | elapsed=00:36:34 | ETA_parallel_est=1d 18:12:44 | active=1
[LAUNCH 29/251] GPU transformer_encoder__External_Benchmark_1__seed_102
[28/251] TRAINED transformer_encoder__External_Benchmark_1__seed_102
          lane=GPU | train=33.77s | val=0.41s | worker_wall=48.54s | elapsed=00:37:23 | ETA_parallel_est=1d 18:12:44 | active=1
[LAUNCH 30/251] GPU transformer_encoder__External_Benchmark_1__seed_103
[29/251] TRAINED transformer_encoder__External_Benchmark_1__seed_103
          lane=GPU | train=42.10s | val=0.42s | worker_wall=57.06s | elapsed=00:38:20 | ETA_parallel_est=1d 18:12:44 | active=1
[LAUNCH 31/251] GPU transformer_encoder__External_Benchmark_1__seed_104
[30/251] TRAINED transformer_encoder__External_Benchmark_1__seed_104
          lane=GPU | train=38.91s | val=0.42s | worker_wall=54.06s | elapsed=00:39:15 | ETA_parallel_est=1d 18:12:44 | active=1
[LAUNCH 32/251] GPU transformer_encoder__External_Benchmark_1__seed_105
[31/251] TRAINED transformer_encoder__External_Benchmark_1__seed_105
          lane=GPU | train=31.49s | val=0.41s | worker_wall=46.54s | elapsed=00:40:02 | ETA_parallel_est=1d 18:12:44 | active=1
[LAUNCH 33/251] GPU transformer_encoder__External_Benchmark_1__seed_106
[32/251] TRAINED transformer_encoder__External_Benchmark_1__seed_106
          lane=GPU | train=30.33s | val=0.43s | worker_wall=45.54s | elapsed=00:40:47 | ETA_parallel_est=1d 18:12:44 | active=1
[LAUNCH 34/251] GPU transformer_encoder__External_Benchmark_1__seed_107
[33/251] TRAINED transformer_encoder__External_Benchmark_1__seed_107
          lane=GPU | train=39.21s | val=0.42s | worker_wall=54.29s | elapsed=00:41:42 | ETA_parallel_est=1d 18:12:44 | active=1
[LAUNCH 35/251] GPU transformer_encoder__External_Benchmark_1__seed_108
[34/251] TRAINED transformer_encoder__External_Benchmark_1__seed_108
          lane=GPU | train=30.67s | val=0.42s | worker_wall=45.79s | elapsed=00:42:28 | ETA_parallel_est=1d 18:12:44 | active=1
[LAUNCH 36/251] GPU transformer_encoder__External_Benchmark_1__seed_109
[35/251] TRAINED ampscannerv2__GenPept_Curated_2025__seed_104
          lane=CPU | train=491.03s | val=0.03s | worker_wall=499.59s | elapsed=00:42:45 | ETA_parallel_est=1d 17:46:54 | active=1
[LAUNCH 37/251] CPU ampscannerv2__GenPept_Curated_2025__seed_105 | weight=2
[36/251] TRAINED transformer_encoder__External_Benchmark_1__seed_109
          lane=GPU | train=34.04s | val=0.42s | worker_wall=49.13s | elapsed=00:43:18 | ETA_parallel_est=1d 17:38:26 | active=1
[LAUNCH 38/251] GPU transformer_encoder__AMPlify_balanced__seed_100
[37/251] TRAINED transformer_encoder__AMPlify_balanced__seed_100
          lane=GPU | train=55.88s | val=0.40s | worker_wall=69.56s | elapsed=00:44:28 | ETA_parallel_est=1d 17:38:26 | active=1
[LAUNCH 39/251] GPU transformer_encoder__AMPlify_balanced__seed_101
[38/251] TRAINED transformer_encoder__AMPlify_balanced__seed_101
          lane=GPU | train=35.65s | val=0.39s | worker_wall=49.29s | elapsed=00:45:17 | ETA_parallel_est=1d 17:38:26 | active=1
[LAUNCH 40/251] GPU transformer_encoder__AMPlify_balanced__seed_102
[39/251] TRAINED transformer_encoder__AMPlify_balanced__seed_102
          lane=GPU | train=38.12s | val=0.40s | worker_wall=52.05s | elapsed=00:46:10 | ETA_parallel_est=1d 17:38:26 | active=1
[LAUNCH 41/251] GPU transformer_encoder__AMPlify_balanced__seed_103
[40/251] TRAINED transformer_encoder__AMPlify_balanced__seed_103
          lane=GPU | train=50.69s | val=0.40s | worker_wall=64.55s | elapsed=00:47:14 | ETA_parallel_est=1d 17:38:26 | active=1
[LAUNCH 42/251] GPU transformer_encoder__AMPlify_balanced__seed_104
[41/251] TRAINED transformer_encoder__AMPlify_balanced__seed_104
          lane=GPU | train=37.74s | val=0.40s | worker_wall=51.54s | elapsed=00:48:06 | ETA_parallel_est=1d 17:38:26 | active=1
[LAUNCH 43/251] GPU transformer_encoder__AMPlify_balanced__seed_105
[42/251] TRAINED transformer_encoder__AMPlify_balanced__seed_105
          lane=GPU | train=43.34s | val=0.40s | worker_wall=57.30s | elapsed=00:49:04 | ETA_parallel_est=1d 17:38:26 | active=1
[LAUNCH 44/251] GPU transformer_encoder__AMPlify_balanced__seed_106
[43/251] TRAINED transformer_encoder__AMPlify_balanced__seed_106
          lane=GPU | train=43.42s | val=0.41s | worker_wall=57.29s | elapsed=00:50:02 | ETA_parallel_est=1d 17:38:26 | active=1
[LAUNCH 45/251] GPU transformer_encoder__AMPlify_balanced__seed_107

CELL 32 v8 INTERRUPT RECEIVED - terminating active worker process groups safely...

KeyboardInterrupt:

In [44]:
# ============================================================
# CELL 32 - v9 ADAPTIVE FAST + TIMING + SAFE RECOVERY
# ONE-CELL REPLACEMENT FOR v8
# ============================================================

from pathlib import Path
from datetime import datetime
import base64, hashlib, json, os, subprocess, tempfile, zlib
import pandas as pd

PROJECT_ROOT=Path("/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026")
OUTPUT_ROOT=PROJECT_ROOT/"benchmark17_outputs"
AUDIT_DIR=OUTPUT_ROOT/"audit"
MANIFEST_DIR=OUTPUT_ROOT/"manifests"
WORK_ROOT=Path("/home/pc/genpept_benchmark17_work")
RUN_ROOT=WORK_ROOT/"runs"/"benchmark4_FINAL_v1"
SCRIPT_DIR=PROJECT_ROOT/"scripts_manual"
SCRIPT_DIR.mkdir(parents=True,exist_ok=True)
RUN_LEDGER_PATH=AUDIT_DIR/"benchmark17_FINAL_run_ledger.csv"
FULL_RUN_PLAN_PATH=AUDIT_DIR/"benchmark17_FINAL_full_680_run_plan.csv"
V9_SCRIPT=SCRIPT_DIR/"Cell32_Benchmark17_Production_Trainer_v9.py"
V9_EXPECTED_SHA="bc2276c2377e0c0730892c78412e307949547b4771b1eca10073c6ff125e5b6d"
MIGRATION_AUDIT=AUDIT_DIR/"benchmark17_CELL32_v9_adaptive_throughput_migration.json"
AMPSCANNER_ENV_PY=Path.home()/"miniconda3/envs/genpept_ampscannerv2_orig/bin/python"

def now_iso(): return datetime.now().astimezone().isoformat()
def sha256_file(path):
    h=hashlib.sha256()
    with open(path,"rb") as f:
        for chunk in iter(lambda:f.read(1024*1024),b""): h.update(chunk)
    return h.hexdigest()
def read_csv_exact(path): return pd.read_csv(path,low_memory=False,keep_default_na=False,na_filter=False)
def atomic_write_bytes(path,data):
    path=Path(path); path.parent.mkdir(parents=True,exist_ok=True)
    fd,tmp=tempfile.mkstemp(prefix="."+path.name+".",suffix=".tmp",dir=str(path.parent))
    try:
        with os.fdopen(fd,"wb") as f:
            f.write(data); f.flush(); os.fsync(f.fileno())
        os.replace(tmp,path)
    finally:
        if os.path.exists(tmp): os.unlink(tmp)
def atomic_write_json(path,obj):
    atomic_write_bytes(path,(json.dumps(obj,indent=2,sort_keys=True,ensure_ascii=False)+"\n").encode("utf-8"))

for p in [PROJECT_ROOT,OUTPUT_ROOT,AUDIT_DIR,MANIFEST_DIR,WORK_ROOT,RUN_ROOT,RUN_LEDGER_PATH,FULL_RUN_PLAN_PATH,AMPSCANNER_ENV_PY]:
    assert p.exists(), f"Missing required path: {p}"

ledger=read_csv_exact(RUN_LEDGER_PATH); plan=read_csv_exact(FULL_RUN_PLAN_PATH)
assert len(ledger)==680 and ledger["run_id"].is_unique
assert len(plan)==680 and plan["run_id"].is_unique
before_counts=ledger["status"].astype(str).value_counts().to_dict()
failed_rows=ledger.loc[ledger["status"].astype(str).eq("FAILED"),"run_id"].astype(str).tolist()
running_rows=ledger.loc[ledger["status"].astype(str).eq("RUNNING"),"run_id"].astype(str).tolist()
print("Ledger before v9         :",before_counts)
print("Existing TRAINED-like    :",int(ledger["status"].astype(str).isin(["TRAINED","EVALUATED","COMPLETE"]).sum()))
print("Existing FAILED rows     :",failed_rows or "NONE")
print("Existing RUNNING rows    :",running_rows or "NONE")
print("Committed runs           : PRESERVED; NOT RETRAINED")

preflight_code=(
    "import sys, numpy as np, tensorflow as tf, keras; "
    "from Bio import SeqIO; from keras.preprocessing import sequence; "
    "assert sys.version_info[:2]==(3,6); assert tf.__version__=='1.2.1'; assert keras.__version__=='2.0.6'; "
    "print('python=%d.%d tf=%s keras=%s numpy=%s biopython=PASS pandas_required=FALSE' % "
    "(sys.version_info[0],sys.version_info[1],tf.__version__,keras.__version__,np.__version__))"
)
pre=subprocess.run([str(AMPSCANNER_ENV_PY),"-c",preflight_code],stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True,check=False)
if pre.returncode!=0:
    print("AMPScannerV2 environment preflight STDOUT:\n"+pre.stdout)
    print("AMPScannerV2 environment preflight STDERR:\n"+pre.stderr)
    raise AssertionError(f"AMPScannerV2 exact legacy environment preflight failed: returncode={pre.returncode}")
print("AMPScannerV2 env preflight:",pre.stdout.strip())

_CELL32_V9_B64=(
    'eNrsvfty2zjSOPq/noIfZ3ctztCyJCdO4oymSrGVxL/4traTyZRWh0VJlM21RGlISrEnlVPnIc4Tnic5fQEIgBdZTmb29u3UxJJIoAE0Go3uRqN7Es9nludN'
    'lukyDjzPCmeLeZxafhTNUz8N51FSq02wzMJPb6bhUBY4h5/8YuynQRrOAvlG/ua36f0iSOSrS/icBqf+LEgW/iioicfXI/ntxk+wEfnz78k8kt9n2KD4Pk/k'
    't0U4up1mgGI/Gs9n2a8gmS9j1UwSXkf+NPt1s0xD9Ws5XMTzUZBkkNNgtpiECjYNSX6PofdDf3Rbk0+i5Wxxb/mJFS2yrkFn4AH8vxgLHCbQVz+OGkM/ydA1'
    'ms6jwHw98gEHMWFfljoQj4LxwdRPknASBvHBB7NaECXBbDjNIPfuoJ9XcRAkqo5rvQ2T9E3sj8MgSl/N50kaRtf6+wvC4es5YC9Vz82WpmEEn95sPg6msrXj'
    '+TVADkcXwTVUTaDvZp1ZkMbhKCOFes2C//zRaAm4vPeSETTo8rNVEPvXgbeIg1GIcPSXQ3/qR6Ng7JXVHMbQU37gTedJwk9H82iyJDhAQnF4x08nLb0mvElv'
    'gk+JB4/i0TyY8GOgCM9fjmRJJzciHL6XBNNgpE/VZYpTB0gbv3s9n47NOotwESD2smUkfudKxYGgRpgcBRcJKh5fAnnkJyRZzbJ5oLm5/HBQq9W+szrf8B9U'
    'P+gdH1u7bWvbOr84O3x/cHV0dmpdXXSPTnsX1tnp8S/WD9ZF7/L9SW+7+3P3ome9PjrtHnOJo9M31nH3/enBW2v1AmC9CqLRzcyPb/etofz6xKMK3qpV+w6K'
    'nC0CJnt/uj2PpvdWEK3CeB7NgFZxHtN4Pk32oaBlHQTTKfbMX6bz7cV8Go7u+cW29aZ3et47v/Kw87tt76T70fs/Z68uO01rFvgRrEioGQczP4wQu3+fDxNR'
    'cTFPwjRcweREaXAdxNbIXyQWdSS9CYF0o9V8xMuyPlddBWCjORDt/c7oJhjdLuZQ3REgJ2Gc4BqHhvXqsFCgE0AoIfQnuPNHKbTRsqbz0W0wxi5Zn26CyFJd'
    'F+DiIF5G1G0gV+vosHd6dXQACB8FNKZkCZy1MDaou3phaR3e8ZfjEBEax4J066dnVjJClgCEO7KA+NL5aD61Rjd+dB04+1nzKfUYG189sd4BxATWTnJrjZHP'
    'w2jvRMnuyTnQaRQF8Ye2dRNMoXErmsMAI8Qrk2oiWORLgifGfn6f3kCHdht7O1evW412o7VDzbQbzcYe0oM1nsMYYXfCXq7CMcxW6sJ+NQakjnGDGiUreBUk'
    'QbzCnWeMg4IlY9EitoBF+vggyYZEc5dAbVhW1sX7UyLceP4psabBJLWG9zDO++EcVt4RkEUcLxep9SmEXi5hr4PFjwzUCrAnwJg0qPE42VnEQAswziDehomz'
    'PgHp7dCsQ52dFfD0MdMDbC4IBUcBJD7F772rrgkMur7wYx8Z/CTwcbveSee3QbQ9nftjqmqyDQETCClGHAExRwQQ+GSAKyEBCONsJDTTkrDEXADLvpmPLdq0'
    'cQlSX0WnglkIA/MtRfLZfgvVry1iT9DkPCLky3dJA/d0y4+B0IDq5SzAsgBASQmmg7sFrO0Q10cy584FY6ShKIBpE7SeyHkjYj86OT+7uOqeXu0j3S8TgOuP'
    '/QWtbNmPbf+TD2hBhE6nsInNY2w/FZtuOoeC4yUMJQUpaErztj1CrJAY0IBGzsWUCiyHiVjTPFnBmEkS2kc2xysmuAtGS4KPrCy4S3FEsgcIDMAqcEjhszDB'
    'KQVahvJjFCWWEdWNoAVrFMMet82bMNSmnlmX2SoGaPRuB2jM30mCYLyT3gCsG9iUmJniBFiIBoBKC33c+NYtowb7xP/pHVx5F2dnV1aHxMS6vTOL0p3xzuX7'
    '7qvukfcmiM6DRbp9sCSBZrvdbD/1rFa78bwBX/dsp3b2/ur8vYKhg9yx7Gz3aD3zgHQXyzSxa933h0dX3uHRBVTQq0N54nZ27aR7evS6d1lRCLhCOAEKAFC4'
    'oR1fXcrmcwWRy06x2M9nF+9yw7yZz4KdxWjnOogWMEJP7+mneXwLQwNClZUUAAS7jBLbGJ3aG+3a297xee+itCKseKBUJCuP+exmYBqz23EY14H8gFySzlW8'
    'DFygUBDhvPkt/XRqtdfvj4897PH5cRf+dK/eQusK07m54HYmy+nU23ve9GBE3gKktQYwZLvW+3jVu8D3vQ/w5xHwYJ0EMWxaXrv5pOkFwDQ1qNi3497hGxjU'
    'ZtCwU8xAGAALKFD94OwUpBagMgHHoJZSUJKPe1Mf1w9InnJREY+zGXu9j72D9yg2eRnEjVsgVGZcw5MkKsBLIct7073qfUW3r2HxCVCveoCEky5Q1cadVGSV'
    '7xdh8uwYpuUrkCqEPJgi1i7yOEXqed8lfD4eOBLPkjh8Yap63av3Fz3voAvE8DUzxRuyN/KBEPIIOX//6vjo8i3g4wJ4Se8rOr5YDqdhcoNIoS3Zi4HvBflB'
    '4GLoXlwdvUbYlzCQk+7mTeDCkLsy6Ds3sK/K+Xx/yHAuoehxrwTaaDn2PbEDeWgnSORsnX44ujg7PQEx1eOFWdEfTc73iF3LtlmEB4589v7ioOcdn715cKGL'
    'Ohmdyy0fVMJrXvR5qKC/APH/8vWQQe6GIvdmpz+8AF4HI7/cFO7qhVjs8xhIFdmy0V2A98iO6gBLuyg0Oe/ybbf9dA8gzpOGmIrGdZDW7ZwqZZa3Xcu2nQZI'
    'TeGi7tQue8evsxKih/mtOxlB2TTBFbL0p7RRoSIHoF9p3T9XW9oV4hpY6+pFY3Fv12AbOQd4sJQOu1fdy97VJTTSJ13dFmKFJ8QKD8UKm/V4uyc3kawZryXf'
    'gaoyDSf3njQtrKmzC+8Gqg+Xvd4hdgDWZlqPUYCqt5pN12q1mo6j88GjQ62fU2EoAfKRlhLZpLCrgDbvjTKDj3zJxi1vQpYZ+TBAGw9QZBAk8tEN7uHXwsLj'
    'DYWJRzVxfZNeD2fy9yiKWlkTw3CapDPzl+enKUqUqpfQYpRAN2YwL4AaYNMx4UXxOWO8/gxkIVkXfiSsF67a2jPo7kz7Gcbaj2ABMy9/hk/gifYSZ44a78Je'
    'y83m8P6DZfQLJdTe4dGB2EKO35+can1FLhiOkbClCozfeSfi52LFo0ydBCk+Sf0Y1op6wpBQ3qby2MlAVL6HmVoG/I3UUf4KEj69zsRzGlGtNg4moAZ88sJk'
    'Xnes7Z9AxYj32TAVwHYTZabWBpSqOw0/wR+/zaMAfkAlnCM/haXJoJIbH1ath0bNOnLpfRJbTcA3gAthhG1weaiOL1BPRBtCRFWhs/HQdlAjmXBFsqnNY9AH'
    'l9GtFUagcQZxferPhmN/35o04sAfw+poP7G+t/DDca0hcA9VmVpvLBc4pjpBcfSh3jRugrtxeA20nx8QqlJ1/LOP4yhFVG5IWLjBpFu3l+lk+7ntOGYD31k9'
    'NMtso9iOqh5suKiYXS9BO923UPe8h7GGoErNlkkqdLuA7USj+Qy0Y9TYQP9DdLsAjvVVMgOBrBjS272d1TMyrLO6DCpfAOv11rqezoEbJTvattigEXsAA3lV'
    'EkwnvA/BGkQAOfrwkyRAk2GeJQNV8PwD+if2SciWAqO/Auq+9blQ+4stjLYpMG8gFJ2gCoV59sKJVbp3qHkXXZVAO+XlXWEwzkjNhq4iFmR/aYpRYZ6hKWEf'
    '7QbBCIbU+VwK74tosPOZP8XQ8D+D7PhtrQbjeGBvJASA0HXwzkPDKK7nJqwQGJDdsnm4PG2ANcDdmpmksmQ5qk9sbfNXDZx3Ly//lpZMEDzMGvkCXZhMl8mN'
    '0OZoVH6YBNblfZIGs95dmNabci2hEclD4UBnDfsVSx8g0+oB4unI9ZPjBQJ/CLGBsOsT2RJyAg8EG4/snnlOtBg3DoGTvoYNITCWMLyQNUU/psAaZ8FsHt93'
    'XsNqAf31NggWHrThg4buRb58HPlIo8CP+IHsiJ/OZ7ANf8LFmB+6C8vyHvtNnToFlsqdwRINVpo30aCJVMeulc4W0J9ZABMvz5WgOs7Cog7cfxLedQgylfnB'
    'shtQoQFYhgY6sKjrWrMOQwVqHE3nSVCfjPkB1JCGCNmaeBHfq2lRcwmFYCo/lUwlICz4hKJIx/5bVJhY/I9mdbzEzjOWgNJcYGxoa+20ESIaFz0/GYWhnIRk'
    'HqfebXAvMeVPcf4iP5KTYizvBs1KnTqQe0M0XTefAjYmyX00qsNrwG0E+6UqAC/jYDH1RwEPGpEppiYE+W6qoQeWOWKeZjGp53YnfLOMADG39VISkpQpKWg8'
    '2TfI+V+VlB5DOYDnMZEPduUh6imlnfGkkc4JV4Jk7soJ4F9pmnl+UWrweMaNeTZFj/8cXoFw1chJaHqQWfwjZgPt8MLWuWYeMlnoK6YBekS1MmlJ9YlKo9DU'
    '4SK0JxF+CjtiXsRRVTsWI3MCSqZ4psy48rhsHE4mQZy8hA0Qz6+hDB5U0YSAcIaNC6ElgNWjrdNSWmXsGKJNXh3I9mfQgUazcR3+udb3OOOrDhK1S2cfIAeL'
    'X6NPY/Ft6g+DacdGMRJ0VCnUQ31UrJAk7xzSDe5QL4DHA9ENNKSjGJn5XjSgbSXnYQcUMUL3ecKyR0k6xt5o1c+PznvG+yCOq9/jwOCf1oYYn/hUL+RQkTDg'
    'Ox7P0E/EPBJaHR46WnE8ExP7Xk2JlOFEjLnBM4Dqh/U/HaupSU0kn12wKa0Xx/M4L/Z+JmR/sSY+zBsf31kE6HMB9hdYkLnaB2cnJ93TQ6AfQC68v7w6PHt/'
    'tf+3SNZmnPa3W+1ms7k/KAEBVXoXF2YVQLOqUiFJc2lBY6DlTD3AfR1ZD61Z4F8st+3TS1rC+EXIgP6nonVKsS3ELJQQ01IQQgVkozf+J2m4AvH0E3ASB4nz'
    'M8jqqIhLLR2tKvBhf5H7vbSQAv+I74uiMulygrMqjifWv8lSdAVMgjXXtejq52w4Nr60CV0MXZGcnYS/Bd7wPoUe76P/Am8DSYr6P3x4+N4oT6sfgeXZABeS'
    'IxZLx1sE/q0HUow3G7KuOQG5L+VRo1kdtyt6VJdWUZyjeJn414F6dPH+svumR6qMA4vdm/l3cZIwlr5D15XlnZU9xvl8F75q6MjgpnbIhNBoij6yncMbL/n4'
    'tp4Eo3k0TsxtAGhEPM+W7zymU9ZoAbMCuxIKnDwECcApkJJ92uXJgSIwYuhovekSvuP5Mhrn64sNGBhpHMyg/DhczeZjfO9az/eeNJv8/ib3Hn641u6efA0/'
    'ktzLvWZG+eNCJ4FLjL+Mrc83+832+Mv+55n4TOjTIC4oWlWKcSs3LTogyAze6B5Rx2M4r1TILVHi0J8CdgNm/bgZwBNccQJIA81F6XIxDZK6LhRqY4P2YfOW'
    'qwvXAIBoiMeaHChPXzyxGGVFPmTNH84o1AkHhbJqhvOCrQsudEqvN6gWuCQvE3KZTCG81ADNy0BtRroopo8LDc6Zsm60bQrLWbtGBbM3jibXjIIF+gziByyi'
    'B3qHqwlmIEMmWUSQ2ywTPhZwaOzEUtlCcYjPxfEd/4DN6Py4d9WzvzzQmHCUmePkC9MYMDVqki0n42xWPSqryV64Y4O4iW4z9QyOQ84Z2MHsERLTQ1MS05r/'
    'bBSSJmPmypIiQ10coGKZDVkVlI/yRXMmZlXBfFGohhbnfcGLoDD8zBeRdiZ0eEKD/n7JJI74PCZfFOZrGd1G808g5JeCRR4h+B7AVUtGTZNeIg9C+UJVAykp'
    'kwcjz2HnsUe+UR4RfiXE9cXzwA33qmqg5cXywASakVjQu6gaXFXBQu9wg5a7NW/UJX0rKVQK6Hqx9FZroeglyokdXZtmQUqOESDRFuGUFytgKvMwIyGmtEcl'
    'ZfJgxsEqHAXFquJ5vrjJJ+UiNJlnZZVS4aqy8hfFYGCXbPiLRRDhNj9yhP/yNMlOqHKnVOtPpuQZVGEt16qXrlu6Ft2HlpYGspz+3WqSd8uJVweZJzi3isbc'
    'UnrRQInpdgsz7JZMINcb5MzQmWiDfDZxcYKWsyjp4ESZFqNMXlJ9KpeaSNEG/RnkH9TuMw1IqTPxeAJE8LA0JjSOvF2yypHCRcBcJ1rOgjikHe5LJqWhEzBs'
    '4v1/MYqprWV7bjnFVBLGwLBF4ZCF7AK4aYjZfVhEwUUKc5rOPYHJOlTvQ/WBawWoyidoIgliZDaNcTxfRL5m3hR1qHxRyACxVTjsih1+GkQoziSFvThZzqCI'
    'NFZkxdDm1GR7Baso+LQBhesFCOgkvzkILF0GYxw+DgqWL4ETPgZIWAbBv3sEBFDnnAJnFmccxqzY7CKlSVJ2q9HUCXMUB+SG4uPGl53iawUyhx0dSJnbpg6U'
    'F4TkFDazirr87eQ5O7RvcAmNenDdG+XJ89jDM2goZZqddDNlsL3aQ+UoEbcB0LUZ1KR5HF6HUcHTu2FB6cxjf+IPgcYBLZadn2c2hCCed8rc2JOGdcmO2ymq'
    'QGE0CWL0t5cO09IPHHjWMByPgyjfAnQ0uzISod0Mvut+8Nn73YZmwNLwo7uRAYJyC1QTEqpYbWGllgkJG1T+onVKcA3p3YWUxk+kEaewGZASuM4BTp18iq0M'
    'uSix09nQG6KKFUwAy6lUYL+zDufW6dmVvH90FUTJPH49ZfUe/d6lW8POzE9gp5YmpYaoTmhvWwDZF16OOow35+/xlhiU54s4ANPXLMZkABWAtJsL6LMofeKt'
    'JPDj0Q2b36zDIFhYysuUXeQTvCUA9f1UgErwbEVrhW4GBNf3QDLQKcMihaxFO5gI8DQAez/B400FgqydKJCRIdkx3DRyHpblNkJ9ZGSikGob0GIOgPTTYOjl'
    'Tpjljej3rcgPE4CX1xdtkOunYpDKzpDrEm90AJ7dO42i5Q0Iy1kYJ6WnCFq7QgXAJ+QzF9+j4QYFiP7AGeioQL6HrxzrJ6uVyTi0+PFxwSmFLE1j9KVCiIyq'
    'Y20eRHNYORilc/gmGBmgbWzOArLdbPh9W9GIPejbuMRYfh1A1zqib/LYqKoW9IoGPVyG07E9QLMmHpBITJsG89F8cS/EDbz/0cESjLjjQ+/46NWFXP9svhEb'
    'H17SEv6NhDdpcwQQCllUTKot8Cab634BNoo29r7d+DtIYQBxlDbQ8Qm9AuoExdHqEgV9OLo8enXc8w57H44OepcMoGmrUlevvYPzc+/k6JR45XHvQ++YS7XN'
    'Uq/PkNMBO/G6x8dnP3tvLs5+lj0ie7+yEgdjeQHHPE4gUOe/XL09O33bvXyL7p9UH4kT55dMLsahB9QQvEG4+2i8ASdd8QfJTuksp2PFtm2X3YJW9fFoPZ3U'
    'AApOUYqCajQJrxs4Wd7i5j7Be1ceqztJfQsGvuXUtHWAFZnYXGsrx3CXkb/yQzKawfcx8GzJfYBXb7dN9orMaKuGCwlA4lJCyPslx8lZF9E3Kw7pRtm0Abqq'
    '8OLxrkFEgQUH9V1LHcYKy6R+KKbTXpLU6BAMwPNg61s7MIb95pbA6F2GHthhYJb6IKi5Vhv/7DaaIJzT3cVOii4HIAnutrnZe67G98Bwg63fWd9jtQyLLDje'
    'N+juN8iNKFO2oECNfbcyJ5mk/nlLzdvWPoL1pNDneYD+bP3Dy2xu+PkWCxX4pN8cOF+AvpA0iMbWnJ0SwyT2BTwguQc+QA6KOKNOA0WZ6SpAUdeyt0e2S1Q3'
    '+P1OVksOa/Gw9cH9cbMz1OrjU0a8naNmdJogt2crO+60rR8ADg/TeUx1PvrMqgMWjCM+o2+oYgCCxYZRCZVPcrVjfs0VQCrbQiZFPwvaDu/UTiiH0UgW0zCl'
    'EniWObHu5AGnuQViAUZlNJkDrMxDL6nTu/52a+Dkdy4sW7VNCVaHRYDXHfZ65x5eUKM7VYc9ycsqY0hoTM61gFJdI9LCQ3EVqthi7QTaRo/wDhK/H1+v+q1B'
    'DTl2hzi1fNiGsV6dvevxbbQOHy3Jl7vw8rj7CuCUvHwCL49OD3sfy14+RbB47OG96/2iurA3qOHtN+PZs0HZjakcvOcDuhSJdz1yb16oNxtd6UNG0nncboFV'
    'gBkh1Uo9DQUmFKQ1UmVH6X/uRgCQb/GyeANDeyQEUdyawK25jtPv1LK+VPQjiJBLenP0JAV1BdTLMJmB6FR+Qkbt1oQk2lHuruQkVzKxmgfVFvkJbQFHlxe5'
    'OgJOf0s+2RrUuI9oXuRH/a3sZhw+hxI4Fdpr/IkWzBh5rWAgCGdy3RF1+nJ1DPpbqBuBYjhCUx2UIrE8bZIPTAOwMuEVjw4StY+daMGjU0vGtUDzXNBlvc5W'
    'vCX9Ojkui/Tsu88qquW0UcVwfJdVVYutvCwwOyzrJ34c+/d1qNrPlmC2y+NZf5TuPXFqIODki4u1WVJYWi7L0LItUFZDu0Ul6tJYb+1jH3qbawcFj3uz2H2+'
    'WCahfFyZ4GA0ZeBWJrRcqQwa9bxqeGJYtXcdubxqtREGhrFO/AR2tjd0Invi353P5xi5oHVYf9eY+vcg3zSO8UPIYSgF41FsHR3U0WcCL25rR653LoWS6PAL'
    '7TgfnuFS9UEJwR/uXYNG4BhFQLGGQhTsoA5fYEXDwgetbZZQpZ+a7nbLce9cCWm7FbzIIDl5Dwol+KFJkOG7PrDSTsspG32XY9Z8Mwa+EgGwS3Zysur3JUgg'
    'FMhRZP64QYR1YZzhDCqaYKgW13DRuR5B8U6SIRKl6Uo8Qsd2oAETZd3xmMKsdOXFsmpseR665XgeY2wJ3xP3++9vP8HWpyMuWaIvqNPIimdlVBEA0IDt6u+d'
    'rLFDDJhUZ6DAOMMVnWB0tkBLuNnK1aTbWvmqLXeZBN4w9BPdhdmc5a+eZPhBx0CqH/g++XUZBL8FddWpejay+p0jpne7lavG64LgJuYSSApT52OFKGok80mK'
    '1J8USKawSEopzjfITVAAzP0xRiwKxucUbGce9WbDYIz74aZUAH3yFqJy4vJeCA1+E13MQf+Q/VCzrLpW0WbZhN9p7WdVaHXSBVHQQeO003Sn4SxMaUZv/EUA'
    'UwfyqQtgU78E03c/FLtZz4ADcul8LYGeHyFZ1Qlmp95uNl3HZXa/RVvClotOk0DiVB6InOhOQzxe1xO39qyUNNVonnrBr0t/Wk/dpiPqL3zqg4fVt5w6g3Po'
    'mlQmeHe26G7pFqPjtzK0tlsuSuMgmfS3soEhYrcGDi0T77cgnjPDyRrJQTuYRytguBmcEf4W930ShJN7AztYhGG7wt8CfCtG0tlCk++WwQfiYLqEwf22UZPt'
    'yibb39Bk5Q7r1Pu/EYYGhd4xb8q6MMafHnE5bHyjAR7G8wWolMKbkcHwIwCRVUATQYEj6vCT8Ho2D8fcRDA1iYNvF//R1PEqZNssxb3SOMzl1YlCkbjoTDjy'
    'gGN4WR1sidcgiEfAeiPQjoRRQiCko+GIoChEQc3RMkZlzCspXHiJqC2djD9mPgnMHzSr6s74v+P8kuL8R09vlSiUdTpDYTbX//g1/8fQSEn8AEEm4042hGyP'
    'Beg8Uayzz28rSGn8AMmskzxwoxzLrU28VTstb3DCJjar2i1ntFsaIrcUfgRkNaNi28QPJzuGGlJ8MbTokaCQYSKSSPKoBFGCdlKl+nOynKbh28AfK2oC+du7'
    'gSeJQiw+Uj2hl0gjtwGems1UOfGA1guWwkIldK5AaSuDxzu78b0/j7f+XKd+/9BC+nF/c000dPyZEnd+65gy4Ck69k/D39itP8Ni5E2jAuQffAVnMqlcGpMg'
    'GGMMDRADxwZ5rVklBZDFpWKC1VbMZLKuW2OzwCbjn0xKRy/BmDJDQS/99+Uh8o4bX5F6F9zz9SjJV0D4JJYBME/wU6x+F+9xEeJUQSrXQJ8ZPP/mzizQjwR4'
    'B1TPvieN7tifqTMVCrVKznd+Gog1gLY22Bn0N4itrM4wSH2vZRTmR8VS7WKptlEqWCThFDCjFxPPjHKjabiIgHKMgvJhVlJ8YJxc3LYjPDaniIJ4tWm+uN/C'
    'eLeo1mCc46TDHoDvGtmTRs+Pp/eX6XyxQBaqNNk5kMw87mxhpDaEvuVabOSbhdGWqxls0xD3W+I4YjAI0UsEyK1Bf0sWMsaH8W8wxC85o3wK8BAlyZ02QVMe'
    'K1MGsgrws3J5tOgDvSAl9/jiLDqfwvz6y8cPFi93QTG9M0J1nsbenOLkIWDsEhc1BlyCqqrapQjDUU43ax2t3TPYIcop2sG4NBUWTgw71OGlNQlTRtHHNHbv'
    '4V9Nu8VBW4UPM1P/uHLvVwJysJiPbhJtgMIe5fGLrAdDjO5BmpRWVj3MyiU3y8lkGmhkoUg5+yb6FcTDeRKATl5DI7IfRpWmUDTy6v6/7AS2RX3c2kdTq4gC'
    '5eIpLmKkgX/m8T3wCKSOgQPsmpvlB/tlhUSBjKZyhbLnUPCLI2/Ti0OgnS1RDmOHbbnGBfvRopOV0pxhlTdUQ6ymxs3TLcEmE38VyEVWHy0AQ63S6WcDmWZt'
    '5uoY2igcpTjX2tRhQJcM7dJCQeRJh9NkEUEbFo60ci5a8nxKv79H3XAaaI3hSz51fvQTtPMX/vojSGSiRA2q4gAV8nRPZiycNCJkhRwAvOzUAT3jyKVLnSvR'
    'I15sFUdM1+qoC49N6bwNHRbIIWcL62+5TcfZqfM1x++/b689fhLefx1BjrqvQc7VgAto7gZIp5udBkqyxZO0rX08ShMP1rp5Qwvilyhd6uu9tS9PIESpvJM5'
    'DEQuTLU4ci7nW/uCXESJ0gsCW/vINqQEAA+4QJK5/W7lPcehb/BEvFSrZmv/4SUEy7OmQqWIWXLpZDAjODqs47NTI0bflrv1actxZUwV9vrQLuirOJl83Kcc'
    'ieSdEJc8mVwqHs8/uRjh+po1bGlcFe2KG4/ae4rqmGuCC1MYvvI4Axo018r7ATiaW9pGfpKOHkRA8zzZyK3FKK/1K/em5Aae6ctlPudTT44RmnPKxdd8tln5'
    'mlhxWS/EBDWYxLkYaF8VpTTCrypaFYE1V0ynB+Omy6YxGf4gNyEjJsO3+AEdKDdf8lZgQtjQC6i68uN9gCYFaOhMISCKSA5oAvgsCVL4jgqGYHjL5lZpFf+w'
    'Cz484m2VGw+Hx+9Y8rg9107pxmiXn8RrDVPZRgSKNnnH6a+qtm29jNi9sZfNRtOx/mKJBz8CMHigV9Ei0ed5GVG7HL4qZ5uOTuqFco6m95vhwlFxasoqVU/U'
    '+nrVbDhXUZwVqbWq5Tcx8aPpJRyuQKKmcLdL1yJyZUvufOmlDYorv6unF5cYefB+qdGLTW7xukQ56yFUXUDTasrbEEJTDkZBnaN5upbMQWNFHrxNOq2m2F65'
    'AK+pzAlDVGKZlzKFcFFt/amyArAuIOf92RkgOZ/yT15LJPzq73+ymlWrT9YpW3/ypb4E5SO5CPWKGFs9EWwEkIFpnupN9LUlr1vGEHBOccYJaLQILt9A9Djd'
    'QkfveGYfDZVtlMFoVlDM1AGSDvlTdrgPfXR1Ed+wwYF+xy+0fpR92bZa+TgLyS0A0QeO4M2Rc1ta+AQjBtPGYDp5ONQpqEZSKkAQV/SMkBNcxNjwSu8kzoeU'
    'A2XsTdAvDH30ZIgWRm2f7IDyBp+yFsBvvFE59IfhNEzvtVrU64pqOJU/wHi5eztyMh3re8sfJvViZ7YLLRl8jNsEqFm0V0q05Gl8J4uXm1+K/wbrL8EARhja'
    'LPx1KVkJ6vJ014J9yT/jqvnyj1i03AuxmTEOso5xK1LowhEZpUmCaO9rtqYx7TEIxizZ399uDWAlmg9b+yCE7KBffUksMx0YWVdwVvqDkgkZAbqRLHLdh2+w'
    'LPDGYYRhhZUeoaARc2o2nhKHyoF2zc66qkMsLjsljasf/br2QpsJ7amYjEFFjJzUJz9aVUGhhqNG5xgMlKco0DCCekba+cACuZuLUMfeF6sN6+duKZ4cHGSv'
    'C1nStHWHvSlcvn3V1WpXpG57CMbrVgZB5mzLVXEtPPQDeWlF6eI6zQKMcYhXP0agrs69pvcUACJLUmMGXgQUoN+xFKeNdAOmU7z07zQonClFo0q0WxeELlcM'
    '3KXOu8XmXca6duHCT0YwNegU0hfhUs0P9uXGv1qlW9D/OvYsiGGPg96Ie8KkBwcpK4d1PHjRAhsOOX4QjasRgh7ebw4qYo3pdIHV+txn/Uqsxop1MuHS+KSq'
    'tEkXVJweVZXXaIBLwwOjrLYXeGq1aLed2USQi22GR0CYR0PIdCJDYVGuQxL5747yqB1FVISi+FpbaVy4VsnCVNEiJ0sjUKUX8A8+U4xgmk/tWGAMFCwx6fRx'
    '3ANYGf4qkD1M8OQ3BZ5BEg6A27Hq8PcHgC4KLIIR5tESBSIqEGGBhVOxZrrvL84UYRvZIwsiik6+3ffnF6peRQLMtRC+lk1/K4v+VvZs681v3uqlmrystjah'
    'RlE1jaqoembgAvOHKmTksomuxX/voNdqqqobKYlG9IUs9UP5XmxfnQtuli7w1t7VqfwZ4c/X8u2E3r6Wb4GWdS6pMUTBH0wmKhNginJ1ye5gzTqFYCFQPgqu'
    '/fLyTbO8iiZJx0FI0xPaTL9n+zRaq2XGDT5BFRZsI6YRcmI914a5y1vKpReJLku8kbjWP4WjP5q9YRrGnKzxuVaMMyfwpYfPEalK9hUOa2WB5zK81tbEmjMx'
    'rssDRpqT/cq50APR5YLQadlQ9vlW+cxf1Cn6q5oug8ZExpR9OYX6G86gsm8ZOYDFuwWHyhEcaLN19sXcibF7eK9SBACiDbSYO0bfCaC0Ef4p8j1xGGvEqcZ4'
    'GByner88WBOfoFQRAp02Q/f7qK3YyJnwB5Bk5EcDDsbkFZ+KuC59/ByI4ZrBqiZAj369GJnq4XwQj08ioAUA3ST2p54SYGL/9JniG0qC+YKhiCngITtwfqE4'
    '5PrI6OoBjy8pGSAA8sz5icxHctwGmhooPY8nfZtkDHugL+dG8Gu95QxE0AXVgvMVcJoaHK1nzu+R3hnIefv18dGbt1f71vHZwbveoSUPjC6t7umhhXkaL785'
    'JyjO9kKFEdOTgrl6ek1XZTRzjRRxrqXn5OTVmiXBdC2ZU9OtDYy4KgsjcMcF0EeIHLksWscCA97m+lnMfulaFWksuQ9aJkruY3l2SddalxnStYqJHRlaRZZG'
    '16o674PuVqRLZIBrsh661tqshVy/KuFg6TyoYDPZRIigEjL6dX46sryan2I0XcTGMVg5ap1aljOztNY6xDs1zIhpFC/OhFNTYbtKA/JWTJK448vnOGU9qzyz'
    'rZVkrTTD51TMMeBCHIyUdnTN5Ds1zi9Z1s+1ZOHUcikkS0FUkQ2wNLn35ma+L0MLDyifUjYtRSJgLmZntIMNF4BJNNqDfIO5hi563cNfvKsz0ZAIydZ65rEz'
    'aTbXdhGOkWbVw91Si9BTLI2mcs54KtpuPSuWktKd11I5KDHFO9fYe95cU6WtEukqghI1MbNusaoQ7ESZQuLFYgUWL1Hky9ehRInFCiq1LabMjjGmEcMQPxGG'
    'yOu3UWVTdtWhbND7Mnjo1F0GxRgPTnDfNmeYbDX8QvGLbM7ozDwYFwmCa+SzvSaemYFdHoEQBOhWRiloBQzGdYaSFZJQ8LQfSotCRlLELNSDse5zi0HVOOld'
    'vT0TDOBSLDlYDK/PgJ3ItWlXgFRrzxio0ExEW7mMjd9ZF8E25XfjvHvhbMY+P3yFOsu5bg3vRRC/VoM289vgHiXTNKa4cWquMwAeX8MFqQtEslkWhElP40DV'
    '+xzgb1DM5yCz1uDGdpTrl4yW0f8MHfkyMLM7rMkxI6czn5kBUSO6I4IHDsqaFbncZbMo2OCmiAFiMRqLmX6tKOSgq6HgFOVVKmQgp8aJtYsVcrKREYYq65oj'
    'eBgtnexpX+q9A0QU2zb16kZXnQIzgxLcKQM6P1oHWms/058HFLTVG4OiQjEsMQa9tK6WcCozFKwGkNRjLSYsXWgQIWFN6LomoLdUzocMVDSuYd0thvd1OUin'
    'gZ63dVIpdqWltrSrBpw+xr0Mx0vcNnAuPcxBNPUXZQMgZUVA1sUdTWopCkFlu3FJ3b5dyAyecQsz4etaIA9tUbyvA8DXR28uzf7mgYhQKtBrcnW8fNu9APWp'
    'okpZSBaoCZztADOGJ7xf0JUd0otnPl1RaNQ4oTiyADwazAt0fZveAKSD4+7l5dFBV/c/lBxMg9G3P7I2jA6+xIIFW8u7NlbU5Us1esW802NpxXu9xsXZz7iD'
    'dHErrq4SU3LH1MfNXK+dsXXi0ZmuVjcGBipRCT6AR9fVGEDPKnfnrNvo11Z05oQXRqdA58uPxCloPgaHrz3E3HUMwCAHis/Xah+9bEyal17ZOPXIOpSrs8xH'
    '76NHw7/UYOXxsRGcXzQAeZxtBEDgQxseh0RAfNSftJpPX7jWk3ZLK8gdL5ZqN1Vsvl8Krymn7weKwkiRYkd+NI+QWmDF3mAMsUwN/fkIxJv3V6Sx4PadSXB8'
    'jF6jBHYe1/J0UaGoGuICVYV1OpYbTR6WRi0llFIoTmSzSbuKkJQfsuz3OsFIF4ypZskgFESt9xSuSSMOVWgtHeCWTVUpwyNbXdtPiFOK8M0z/x7+wR4V4tXI'
    'wOIYxmw1sX6QP0E0OTokrdiSK5YCCDcA0ulcmLk5mDSGuceLb9ts0ebhIJNB8TyMRtMlypYYQaXBQd1EnKhLdtZAjiR1DmRIBV2DOYJRs4GbbDTWHFImNppV'
    'w8jzPktgXzzeK7QA4OWl1Em5DGjPfNKjMURm0wZ/kiU0jKshwkOMufqwQ412HEKA+gi2JIqWtPyW9quG3jR6272PsClfoS9vkNbznVLn2rVsQ/FkIT5FybIF'
    's60qz6vl9cdcDmE++r0NF7jWO+JuN9qxvWi+b9XFNzx75+tF8sG21cpSHhVH4eDdsljYvWgL8cSxQhZVnjYXXmH5tPF6Sg8M8ohf2FqcJZtn07cHq+eac1lk'
    'j7JUFl8yjaysH7Byk+UQUV1AZ3YCoq/RQqnMXyE/VVm1QpW+NubM7p2RS1EqL+1dX+AkA4AHK5JcHXI4+GyLdaQ7ldgZPnDWNgQLIq6NPAOkXT/CeMpZvVe/'
    'eJLjFRGo/HEMWtwQETzJ5MkjaBSInjfrqzMQedcKnejZHCTSdIDMm32kQeBHnUbiQAPXt8+7hywdN2tHh/iw20UyxQO9lcPxaG85Fveta62I4lV1qUnLFGFQ'
    '8n/QegAwv+gTKSGzUQIeyKuTFmz2TlnJhnC3crIqdvfgsPf6zdujd8cnp+d/vbi8+vDzL9nhzzjAKxgeCVXjLL5HPUM1HVG6WaZ4sXjoqZk6kCVG89xXiiF9'
    'kW+LQToVXA9EjQUFSGdQfQERb60UApRzWRojBQ03uyedV37FuNUikLZEEPWFQDsD9h/E7zg/DFNjmrk2Ad76BmXO2OBXidyJhyFd1R2kOvxT2XeLGQC/s976'
    'sYggDbv4ENMl+jFUwfW0Qxsw7rmgCsWBSuPQ0Htatm3Q5RohGajkD9kWvm+REUSYXMZ35iTyblW9WWlECHUV+hSzLGH1nLIRWKvOCiR7oNM+gDXQA7KLZrDO'
    'AyxRtwLoPapJquAQNqWZFhH8w0etTFkVS0fmllP07mr55ow9SE/MLV2/YSsC2GjIm4bDBm9MSHoNDnBSl4mTncZNcDcOrwMaWs4qZkLrqOR45oanR3gTWJEO'
    'sEjsjDDKqVR1zq77KvDUqCfmriBnwfCB4EbRo0K2r73m3VvCzZ388nQ/L4Wr3C+4qvz9cIdoN8tGUrK3lVRStLiP5KYPgAWNDF5OABmU2q7K3CykI7aIMafC'
    'Umon4mycguUiMeMaftxiMf9C68pcyM8d/dKgaBJBZ/MzaKALirpIwgJfsk+Lnu6N6ct9zabjCO/bgg8kjUSiZRiknwJguK0m66tacZmseFLlwPs7HPgrUxkH'
    'ZPr2s32+mZF6nNuF4yzjH95G92X+eZGGojJ9grrxywGbGxkgR6oY5S+MyNJV0cC1yNPr4kMrqKUJWB8ZL3qzzKp0gX99MQ4xTZie+beBsnOxITS7xSzyaOex'
    'P5pgsnrDstmXVQbyKEI+oJOe6fwa0z2NQHi8jvFSHOamUuNBeXNy3beBPYczzJ1qD/IBK8/DRYCakabgsmktgW4HaAq6TDGMezy+pAd1VGsxx1kkwpbT7yQd'
    'M+nn/PlF5ki00omeXmQdrRd8AoHn+9P0voMna/wVjdcHIkIDPCW/c4vujsdYir/p7vnqTtedhzsoxR6BkvI3AQAup2DCD8NDXcXmQVckjhFAYSNcS1JgilGF'
    '6JFRSx/8wCmfL8C0D2tvNYMdm3LS4NlgyYwNYa/wyqYNX0ChYwJ0+eHAxGIBVxQ0CH6RmxkgsxTFBgg8QcDX+Ik1ypC1Fr21x2CRPEBzaeipHkYfuMRcTuEk'
    'DMbvXuPdscij3TDpPHXNsDFFmGuYw4juLR5k6D+gRQqtxAcf6hnKO4ho1+IT2Y4tQlxhAo5VZ7TCs8okmA1FBwos5Ao2tlzY+webNqf8K9svrOrqheyQoVyu'
    'T3jmVBCtQO4EL1alj2QvF1T3NVVVozWJNlKjTiRB6c+I4kboihejVzq8zX7kiRfpcAwTcCNoDeMpsSyYMO1kBJt/UaBcvcQ08CdlNfF5th7EkQ8tN/13vo/D'
    '+TzFLGWLDmUERMcD+YRHWlwyETmPdLZbJqQHV1J+JoM7aMVL4wBv3DxqHntY8wor/ncW/9mziJ7K3nXsj0MMWgrNUsLHR07oWwDyRsB4JUBUTW1+EykLr4ev'
    '9cfFmVi3I+MPnAYvgoEmehH1tBRiFZk8NNfm+NooPy2nfiwCOGpjyr/Kukt3Q7SO4u8CZDOOnTAKPn7GKf3Q9XBmFwRo+QbF5+n18FEkAOUbx29enVRN+3z4'
    'd4y9uwo6Nl+TQVfxDVa5idsNaQUTEODsrNT0qydrpl6bAXrA8wMzProJp2M57zopGC8KkFF9pFeqr9kjlj7lL28SB79KwObTohg0n4rXw3tkvwp4/g21ASTn'
    '+dPFja/KZY8KsPENK8NmaX72zczIUroSiO9C3gJZAHNlz6fepzCRQhjHiQtBusxD5fhkHqn79mixtPMEnwsVmkV7kpeRxG0nPQQBF3Ktj9ITzDQYGkHtuF79'
    'o1N2Hx1xEyRltcUrD9fjDbxKZSAqTFEt3tkO5yam55iRK6vlCGOqlMXQfD3HlhRYzI5Joaet5JZWxEtrIkIeQoPRGH1JQPANYksEhhOpWDG2xDxd1yc88cq/'
    'xuCqQPhpsEhszY64BgFaDeFMY+fHB0MSQTCgNievyADiZbR+c4DZ8PRrU/19F6sNqm63YownIy4g1tNus+LPkqhChas9lG2TQ/GUqN8CA+sMEe84sSBn0nlQ'
    'Qe/beoImPL/PsPvI/DubZKDR8vAQ/o0cJVpUEyNTiVXIR6OS8nDZyrQ8eI7qWpgnBJs1EpNYxaQyDyXosbJkI+U42ixLzz8YT7AflWaaLMvfw5jKp2MRWXwY'
    'ypo8PqKia+Uy+Vh6Kp/1aMfO7liU0SeP4g2z+pTndLE4C49VksNlwzwuRo4fQEVplh9Liy9tY5ofuwSAvORZCE5tlWX7+eOopZAAiHrIxR5MA2QV8gBptbVs'
    'QFaSX3ZJ6fz7XNNIC1RKiOW5gYr07OeIWaOnR+cIqqApM2mPpTIF/S5kpufi0amlKmmQlcsaVEI4d7n+ZJUFgzASCFmlGYSsQgohPY2Q9YP1QCIh47i7NJ2Q'
    'kHVsyieEsjsGV7eFU6U4/GRy3jitkNV0JBw9sZCtJRYq018ovZCmvNyVT0O7xYeUrLjoeUaE1lWdNaIANZf5xzaSDRG43Cst9U+pPdg8CuC8QHjOGNgms8KQ'
    '+4CPu0f0q13dr/Yf3K91aYsEIxxUjMTMQmBrWQhoGI/ASTEZgS3SENiYhkCrxhJkkd/rjUlTKVUUoaryBMl5Zv6xFLkuAY4xq1mD1dlwhJZYmu7IlDYKeUBs'
    'PTmOgFOdHccuvDSI0FkzqX8oeei5Kv5YIlEpWP7TyMWM5/tPoZaHcivZudxKNNX/XMb0j6C8krxLGvGNhcJN/cllX7I1pAB5VZPpeDNyfCgXE8IR8kAhG5Ot'
    'ZWPi6BkpZxKqljjKUjNJwVM2ZGYlsvXkTA8kaLLzCZpsI0GT7KPevZJMTYUduJi6yS5J3VS6eedzOdn5XE6ltUoWXiG5U2lFQuDExnRPn0VKoi927hC7fkca'
    'fj73k5w7U1y9M6eyPBHSxJaZoFSj0AyIuPjcBDiZrFnJ5RmhNljUJZCLK7ssMZSdTwxV1cdxsdiGuOEsUXnM6MDyclpZqqj/HJZYjC1abRzmxD7wk5owsklh'
    'w4JjqApZeTOn1MZ5paoONLR7hQ8dgxlppox6/Ibmw8gyVSzULp4zGQmnjBrilTgHMPJNGeXkO3PHVl/pENAuST9l6457Qn8lJGfO3cHCk9llHmG0r390rVwm'
    'GktLRWNV5qKpMCsvTKPyQjcpL9YYlBe/S/weeU+ercfW297xee/i2536uifnMIfnF2cA7eoX783F2fvzyywPR90e3eBNKVAF+3b3AF0hyROSHSFdyz7s4d93'
    'F9mk1+2be1zJN/MhB+LDmgevodqHn7Fo983b88srUffd6V/1mpFgb8BGV4BjjOPhg0YiGj98AxWxXu/o+PSvHyjm6tt3JxfQEQViMceTVrPZX7hdUfuw9zbX'
    'LNf5TRwLcWuHb7j0ATZ2XtUah49Hek7SeMlme6x++Ob0/JJahcaOT6A1BPX6iLCmVUfvMxB1/RHFo9fbB1QfHTPG3p7oCLv4KwEYiLXhzxawODDqbBwO+epe'
    'ZuNBaw9wMHlOwUc+8Gw/f46LgZEH1vfWU7bMYcR+EZgdSusnL/1WE8N8fo9Q+lBlx4qU7zlG+6Zbus1G+ynFWaZoy8+eDlSDKLnN8PIgrDrgxNzU91TVyNNN'
    'txLwqIfbgb7f0iUVPirDp7d4DWug7xLS51v2MQMDvcwGkS+EoDBWdVamcAjEGJbXsVcUTgr9yvUzIPakZ+fWX50GTsai7jSWCzIyslerwCh5pIscaTnnfc+1'
    '6Co/3kS0StelGVWNCmNZrlVtUOyHHFUfNk0fywd0/x8v9UFvKFlQnIJ8jGjmAgRwYMDD7sqrjA8RnTSDRo5OPBqbRmCa9zax4NxFDJwrda+31Xzqrp0fERR2'
    'PBEzIg8xFo0VDG90W++XzyPfbUo4Op3hK675yw8cLR0TwalzAp/xxLUwxA59USmYVNaltIn23JIcaiJlHrw1+i/BirCSVEA+q3SSl5j7GKzy8ETnHEPQecil'
    'znDRaKGOpryu7GvYC2037zpTK3OXYk+rdolfTYufsT9BliaA32GQ9pruppE5VLVaBT8f5bcTzhZLZPzQq1Ec+LjF64CUtxW7GsznQw4lKV1qhDtDK+dcUxLZ'
    'UiURtEDSp4KwfASYEkeJ0WghfDEKQ5POJQqHuoiJuRUxrSLSgfSAF5nRMGlJOWUBW0ybxSQ5giwpy4zKZUa00ljcTu1ctEctgYxlfxoWgjryfW5OdiYksokK'
    '69oRr98evXlLgcYuzq7ODs6OHSP7UKmDRbBy8HTfcAfI+VLoXgEDLcqiFoJTG62WIpE25BmwVbwjt40UTRFtrYvXLy1RjLZI2CIwMMtwGtjmjTiO/qrjxpiQ'
    'GklTRxfeBSJ8a2sLz5OsH7cx+PgMiKoLP2mFo9Z1Fk3vO1cX73tODb27wgm0XOe7I3U6h8JxPj2WaSrpDj+Awlf91uAlsx3jaRueyuw72uNdeIxINp8+gaeI'
    'JaRtepggJwmugYTo/VPgeQnsX+hqfw78E9TFS6Tz5eIEnsCvpP6ZnJAB20BFwPBeWvL3yAeEab/xAAJYl/PFqYnZBsZCeKnDfCxuQvh/KoRF+21OerQXR/Dn'
    '5BP8ORCiqP1x1Gp0xeeF+DwVn4fi80B89sTnX8XnG/H5Vnweic9j8flOfJ6Iz9fi81x8XorPK/H5s/j8RXx+oM92g+1RjZb5s23jhOLY8co6EmVdzS/uxDGQ'
    'RtJNXlNm2KTzunt82RMkR8404hGGCjSgZOTwKCCK8lBpGaFA+6sX0dEPffV9+HJMu45j/TmM/ox+aAQBuu04OJY/0WvsC2ezrctH6OW5wojsAPbVNcC5urYd'
    'Bwm3UEU+Kq8CjUyIWvzpaInpa7MdAdrqu6W9xsu5lAo3iDD8NmCrCkSw2hCEiSuNkPN4mdCZ/Loy0BtEHoXFxm5Bnb6rSrt8/xunCFYplVIok+itpf6QfiOf'
    'ypDu1EROSnwVTlBazt5xPEVAK4hTO7DeZRAogAAcxXG+p8woxXdt8c6pjdJY9AFIVqS5q8sLBsBTUfkhNn0e414quFuQ8kUuyW5EVu4MUJ17939bDRAJMVvw'
    'hGP1ZjcXVrMLfxxSrJ80Fs12sC+44wTnnM0LaWYU4B6IU4gXFGyYBpkyWnwCgGUUvInDcQdbanBgcrQe0eb8zD3AhLE13IuwezmbQxR8ov7B9FVNFzRAJ+YI'
    'wdZpJsTcnniRq55RAZZBk4pO61DFXwUXh5eyTcXQYWpxm6PVrndeXlSFbv1JUnEW/ryjzSW216d2yAu1lEs4rtorXLxNbPIL2NNMSTiMN5WEb4IpBwdlwwUF'
    '8cX9mYDg7j9ekhAIDF1E6xjdelypzh+uJXZXXRYSsW20DZ8B0lva9NkemO2WJWXxpSqqbaFrxKYwbsTjhGuo3bUEuI/B4LJQ+Ilqh2T7ygvJkh3ta+J/xZ1k'
    '8yoysi6jUqlGo9U5FveTM3GrqG8Uwl27gpEg5ZpXfUkF2WBUglYeNShV59Fjyqp+xZDSWObd1rdq/Uo9bmqyjLYRGwm5Rdq2MXpXJTd4KRW6Fo5u6jY9hf0V'
    '9VCR8rZxMwfMYbIsdDgPqcTuzjCMdkRhXVPmgGr43MnFH1urfVJq4dm43qeqLmUdwPFv09/rIALVIPViGakWnl0koAcuKCTN9vbKj8LpFEOjidVpnhXpqNJQ'
    'ohaXwWjMTLy5izI4ADyser73BHVRmsEOry5L8Q0LtCVbRszYSD8SKRv08EFZlzRNBVRpNDLjKy24C/6sJF6nn6UsGChA2KEMIgWHeGgRaJq+5m/+CG2HkTQJ'
    '72Ck2TaKmAKKxdQCm6s9iTl3hsbz5qJ78vvpPM/+UJ1HGgXNN09RGwrwfnF8b77Ze0BPevYIPSkBJUBTi4bh/Do2ntBhc4x6kiZswpYBeg9s0tDkdZBeCEd+'
    'ERrH3m3skVbR7bab2EEYAtldQLW6OD086P0VTfbvTl6fX179/AuZseEfUQTPRB8wO6hdXnWvvNPuSe9S6GWZTYZycrj2goNI+ZH6DrSEv2Ce8Bb7OODv8yQr'
    'EarC/h18nc4jjPMhylBZr9WEr9iY1/SaMBD5o9GGf0/Uzyfwb0/93IN/z9XP514LUEA35kHWIc1iGY2EI8himZJUksVkpiCFLNFQQK5FGGAgFag1xTVwj1ZR'
    'j8LzgACUAUCpXkF1RCgvnJvEwLss/ye5S1F20jKsv7Qi7C63zKuAwDnbL46BUjMS4FI/dVrHMuBMLOx7JEPXV7leU3G9t2Shcrivffqxz89+eHGMao4isFbz'
    '2EElLRNSVVsOScQY+qFZtz/armyOqlC/rrHEadfLwHkvQQepG3h3PsOTDEU8akAQDK51bP3lL1bx1Y+dFvSSgdv9VsttvRjYfA5QDgqKV0Fq72WQ6q0Xbntv'
    'YHOKNE2gViPOchIJAu/EwUKbXsmzcX4znGNtkMUFnsoL2zOFPVHRkfmOqA1Y8xiXAbUFNQrc9qB2B8lAtSe6JoKxyNqSRRVxoFUlIz/VuFYPH2E8QAHpJdn2'
    'AZ/jeYO8m2MQUsYuryh4CwuI6Qiv5Py4ffr++Jiq1L7UaEf2ZugeYyxYxCAs1wj0qsT5PPtxG8YjrNn8qu9eY6ft/wuI0KBTWqOaMgbtCx67v0/HzhgVOXui'
    'tY8PknqUdKjRzjjB6enM3GUHuarjfKmJhLTSalDWYUwXDXhapvMJGbGfOp/x8sWP2/z+T3xaw4aAekbIbkaI0FsMj/XjdtZD/KnZOpg+BDT+1ccWBm5mIYcu'
    '0CPX0Ek1630IIq4//vsySTv2q7e2m+VI6rTcX5fh6JbYk4tyU9JpBU+RFSzTOvbEHYKYdIt6dtPlUbqgKxMjk5OJudZKURPOFn/8VIpMb8G4PnOxQZg2seMY'
    'fbpzPicwKxm/FktVU5TvfqIModAh2A8S0OZBIbCbtmTasJZ+3F5GEWvfzHoXboRcD1knMCXBzOGjD/9+ag6cTqfpyNNL9RjoKvVTk5oWM2CR4wRboLCGxv6/'
    'mP3JZEkOrzEoLrYuzIGmdqmx83n84/Zi1i9U7HTCsWsamhY0PxIJ4z9RJj4AD7AZjfUF/ISxi+HhL90QYcIH8IJiNW42lnTbAkZkiBgdyjG9YMxnwoZ4mj1B'
    'kaPDH/g0Ez06kUviRAdvoBhAQigfaiD8uw7eaIHfmjRCj2LHlSIJgYl/QrOfq2QTBv4jrO22sxO5upyStdv+CxV4ohUgySUr8IQL7GkFSJbJCuxxgedaAZBu'
    'stfP8XULX1Zw6iKjFlz6x22TR1Nu22oOLWbqx21ho1WPGNyXNXbsjbuGIn2FGfsRMEByN4AYkvzmgEqs4Soyq7I5uDIeq4z0VWYZZwPwV4MIVgiCxE8YDHCP'
    '3d29NshZZcbUNJ7h6KXwC827JGIibs03wcoVI/VZQ8s2QKg0c0f1lovcuO0+gdYpjFvTbbott+3uIp8Z/rhdrLIL77gs7guwXvCjxTLkQ+VbXL4lygNVQg2k'
    'zbrvDt2RPiERoAZTbWaoQBU05UtFGdbwPYzg+k/ykB8fg2wKmwFJ6OYeTh3CPZv2al3eFvwN95CfOu1jeFdqedVb6WBh11Au3YL1lMUBaHYTWSCetLAtWLWq'
    'RbV9Zhs9tGvsk8h0keNmhzEzQ1QAbADgH7dZ09zf58/6OECnmCBKGyvYWiljtLjr5ce2S0Zv0R+XUcGhfFhY0K7U8wPYQhoUIqbTbjabrjwv53WHRNtR1LtI'
    'YX+RdnZow60cbmGoKHzYmmnVHgzQvA09sGE3S2eMa/pGexm0k8Y4z7j5w7ZbhxeIjvaj0HGNwZkJI0lKJ0fymVKhDcnlcQh7WsDXSDhojNjVlcrncEgGENiW'
    'cVXFE5Lkcbpc+C72R/zdRgQqZwok2Jd8WsNnDcD8bZ+VtKkNaDLOIfRjiGDFKzUTuoCxsMQFMkSw2mA6CcLD8wcTA5D5q5zBYIU2nJU2hW1cu2ii0htu6w0n'
    'eManpsckouo+PHTeYkhmCZ6+mKKZW3IGw9mE3arDF2USffjoBUXf3+HwBcFsfvzCpr4HD2AIqDqCebnm/IWKfs0JDFakM5iXaw5gCHrlEYzmaFhSLePmcs2o'
    'ihhzBf3qzNjtan/PYrZn0VMHGspA70EAg02OFdhAbBRfe8IQTKftXSMFn55cE4eXZZBoPZNoFMnuOOvPhScCeGLMSw/wgsqgt3raQGigBOlJfMhKzKcCWWYX'
    '6gElXMKKGIVcnhugFgewvXg+X1dca56qxNNwuKa4MJ7Ke0soDHZUctGqEZMUkXkDSolROzCM8CBLRTPVYzhTNHTydLUvvLdnJ+hicuEdH726zL547y97F/Sr'
    'd/rh6OLsVP+uXp5fnL0+Ou7p39XLk+673ofuhYClOdFClxqL+aJ+61roOObIDmM096u3WZzVDNWIghAT8/6AA0LKSYIF/EA41xjllqqhjVIDpY9DQsSZ4DnM'
    '3l8eXfXM9484eRKkU36e9NgjJLFaKfZR8UQJO92Bf252nNR61n6unSd1Z4s3QBh/3InSy3//4ySJo/TTHPff64Cvx8V4pTNcBL/rodLlQff0FLPI/SIOljAE'
    'PSVZQnYggu4gT6iJ79BHVzzHkON4wupa6ADP/pwA/j6p6eGJ3/Uuupfeq+7Bu97poT0A6S4L4QN7il7y4P1h1/twdHn0CtbnYe8DprrACrliZyfn3un7E+/q'
    'LSYTpRKtXJGTd8cPFYHXvY/nFw8Vu3rtHZyfeydHp97x2RvvuPehd4zl2rZECM00+m1GC7cQnggjw2BQIsLqq3AuMXoZ/Hp0xk+pgHyOEaVAJsbK77TX6L65'
    'YAccjI0hCsuNsMYJejrEugH9DRCVV2j7eYmyRO5xGx+fnp3mHu/i4w/F4k/oebH8U3yO2Qpzz/fw+dn7q9zjZ/gYw1Ozp698/FyUbsxuMan0wscryeLCM6WB'
    '9Oa3InCqTBwAVcXRHKzpyby/3x50OqDv7gEkUSadNDxPFvI6MKmNdgMnNkt6gCg1i7QbePBVe0fMIhGBjwHQpfjKYaoxNsgBfTtHH1xkfbGPcaqh5yD+BKAb'
    'gEB2E9Ml05aL5wNx9WsRbY04XOez/eb8vb3f/EL+fpNCJG1EHtoFzajd4mnhUQ0Vho65TBv4jFNMoPOCB7yMLziiKAaMz4+igF2EbJSc60xVaDIA7pGHBY+W'
    'FEQP+4fKCf5B5gsflJ0qiBuUM5oLon7jiMjmvyacnm0/uxdTjxvhmNqMMemAw7cFYtz7aaHAZhonxFy5pmtTqnfbGRBIWAN1TliaKKBycUBdlW4hqfcxDljD'
    '99swN32fc3rQXYxkIC6H0CUFAW7gzvw79EzkRGhp3KHuwzLBqZA/YXUg8a18/vlBvM5+8/tgxT9x0aA5qQPgfohQVb7vaHc2YN1+jydW8Nb5od/kHxH63eTS'
    'aYA83lHUwJcNLtGZnikAd0/MPEYzjDDucSY/dhBZAK2/GGDD9/BZW0FfVv4P0GF4tCrtzMrXOgM/ip35+IFAr2KhKNNm04G1vZNTKAShrdqNm6c2l8Wbn/Km'
    'pwgB99G9dz9+cO9XLmrIMkElmQcSGSqPN3wXVL7rgNUgD6+jw/acpeTrUaeClRQLOtWXGHuudolxt+2qK4zmrUXlvY8doQGWaT5ApJ9sNwo+YUhBPNsg1/4b'
    'EC9JEog7UKjBX+uTG2n8isWj+ae6ofUoyQS2d6RTpSC7nuNSGh+k29/CBdofWf/dL8JUtXBDEZeDqbaD128K2m82WZoKrBI+fZNGnIHW1GIPqGJxv1Y1VgKL'
    'kBnJGiAVF3sHXbp2FqMd6VnF75MdaHFbNLkNbb7Y3W0+bQft3b2ne7utSfBit/ni+fMX7Va7GQRPd58GzaG/+7yFDmPc3YxBQmXGRTppZZ0FCYB7UO5SBuJE'
    'kvXIGPs8Dq/J42xxn96A4sceZ7NFR+BxxxaEPVs0Jj7sYdE8yr+DR9lrYDrZW22i1Puo9L0OAhhVVgQpm6wG8EYTY/n6DTHhRFEGQHABkKRls5RJNSvfXamC'
    'VEQ6D7qwWoVy0ylRA14qvWZx7wrC4EmWHWDoAMcV43DzakpOOZG6CVAXT8yHdkFBeSnl5rJObWuaSUfXSwxEFliEpqt0vlZTETCSzh+ppOyYKoqJqflkEo7Y'
    '4Q0d4FrNbdZPxMokNzipq3CoYlJZOMrquFxfydpds3fkNJne+fkvG6gx9ALRkMncl5QL/hStgAsfpGnxGHQavl/lokYjHmK8E+Dj8P9i7Jqiv4gMWyHq/14i'
    'eonI/aRc5H5aLnLvPVrkthsiKRquojuWze5IZCrI4rt4BG/vNp43dpW4LRCTE7ibjfYuCOU1BMJ5TiMsXW/mZE9Cp4/XyRb3EqX0E/EOW7hZoiHbkEW1RrMO'
    '5ZWDpl0bfRoT+hrwBXnMHI3OiB+xx9P1GMxPgZIKX6fIkU1dxj4m+QRFQNj8r/3sCQqBZBKX1jC+jYjXEynQdOvZUxfvwdCP9i4fPuD04bGFJ5Q/9Bah33yM'
    '0dpruvjNQ8cRcTVS2tp4/D4IvUIYcjjL7vR+3xwdjNgRMhuLa4TKhjygkJnUSFhSfs9kcIn9T1xFmuQ1BpeiiQ+xJQWsPL64xUyYc8hXC6HTM5KSXeDR6pFs'
    'sgSNeJmkU7AHQVkAuujYf0MD03fWmWRUAHaxTCnoSIL3TMmdBSma0t61nzcy0tfOkDyYUxsLLWT2TgpQQX7zwF2NNzXTNV9PfLboyxqmV33G0bFEvtmsKPPq'
    'L440UleKn65hsy7IdcECGP+jTjU6mgSHNEIg9BONB+Q2wZ51oa3zoMhGa9pbwRL1fL812XvxZLQ3Gu6Omy+Grb3h6MXus+fDYPzs2eTpi+DJpBU8e94U+8ni'
    'vqOJYzvrhDEayKr1e0phVSLUy0fJT7+3WPRogUiy3f/KQmtkIYkkpFLjzv/XXgBQeNIYsSHsHD2BBbW5yTZnrQXBRthq/01MtWfnvdNXx9Cz39VWa4hyBbut'
    'ZratNNC6KhiVXpS8v7BcVokCXh1kkqxelsNtyYIUHNjl0LMuRpB0KQ6XXoHvCRmQXTqF5FBO5wd7ZULmVRcmqkzMLEqfu+XS55MKA/HTCgPxXoW0+qxcWn1e'
    'Lq2++EdIq3uNF/Y64/ELkBAfMB63G0/sWolhttxcW23e/RexPz/KerwY7bHBGGgPJXb4/a3WYgDhZKZdNhbXLNhNRnuN8wNvT7MEC4d8tM++zPLloIfOuIGp'
    'jzF5mmbyE2+yrNeuGRtnt+3UQt+988lqyGbcMIrcu4gesB03XEGJFRcRpt5wBWVWXEhYe8Nx4N4F9IQNvh+xFZhFwFoQoZW2fwdwIqTv+8Ir+A1SbUJ22zuf'
    'x4ABQMWTCI11Wm5b2fmvNAl/1I3BHz8UO0oj5q6u1vd1Vezsqqq3tTBadArh0ImE7joi/PbeE7e15xbCHrpmAG0Hb2BQNYq6i7F0ymMuY+BCcqvtyPiGVeEN'
    'xX23DscqBPCoiwg1KQtKqGIR5iMRTmO8m9BsohdmdTy+WZDG4Sjp9G1/NFrG/ojcK8gMTb7StILrzcZTsrt/ZPdNVPUKZvXwCcqeN09tNrV0tMg27r2r297Q'
    'pa5OlnXQuPTcjCSokC+hbginr262o3X6ub2MliL2yXFn8yjEhIhoV/QoBRnZ7j18683pTiK2Q9fCbLq1pkzsA+17Xnmijtn7lNZYJLRHdOA4G0KukinPnB9a'
    'jsvf98veu6pvuffZ80FOuTKEPUOpGs46auNVeCg7ahjOMjX4Liiit+Ko4aVVrUYif1EqI318q1ZINPRNdv6cjkgAN1YRpVAr9LfRHkB/SEOEHWcboyEFYbRN'
    'EYOBJ2xzQAuv9XTyInjx4sWzcXtv0hoPh3vP93bHL0atF8+ft4ZPR5MnLybNp7u7j1UYeVTT4BqW67+J5f7lv6jZnid5xz7nKfR6YgqRULKXMMMj+/Gm/fbT'
    'F23NtE/U9b9Tkd3EtJ7tHzmj+vHR619+H0UTPeZRcPxPUjj/EB+ijfXSb3AnKmioPcx/eSnSX3JJabbno3b2+9MM67mcz/+OBxxQ++Kgwx3fsZN4hP745ccR'
    'FwfOt2mYz9ZqmK32/zoVE8UOICWKru5KFS/ZVOmkWpkWiNL6wyoncuZS1ySlOc7wmhdCIp+oaTi5F2f97BUFZKDt6vgadyqU0/K12B9VVYI1kBVniQsQ9Du6'
    'QYHsgACF5xH/EG5H/IOUUOioH8YgxNcTt+Xo/k7+4Ad82DQeRoPMs4x1yXqrves0hNZQJ1i0hf6auPdJB31PvpcPDZ8m4P5Ff6EOoBo1R+9mnnpCn2MFHQE6'
    'Lqr0pTruxx7sq8Wq/UTvezCoAlCbALtKOtTSmsT1hm5kxCp9CmD5TjPoVmTwgMkGpAK2bvC2J32TEdH6gxoFbQbobj0N3VXomKGBqTcwG3y2CLIKooUzYrJi'
    'gdeHhh2DQdcNVQt0R5uODjlRGeqdLVxRISq+0FsXjdEoRpAiJjsmOOCNrir203Dg3tNfoQ22mqY6iH5RBWWyv6JqKwx7oKK2ajrjaIg8+dOC9Fa1SHDo3p/H'
    'KHb8Gb9LpbtBaqPoKJH7pwXiWTyRsaU/LSTu5ZNvdu5yXtZECGfUBc2JupHKIjvzs4Lbx8QkPO2yE59tHIu9T1Muldfwh5bUS/GvoYeacJXy3GfvLDvyI1ji'
    'ZAKo7IPTDwcYz0YqnnShW0VlJiw5LiVoaa7VK7MY1p5YRd+oZObaIkzlQOjUUK1tk9udkCEbpvud6SNCwJ4SNEkwUK1x/Ru55O3jJ8lSfrzPk02xvUXRfXze'
    'AI7CXBZQFo/I6XBB18RKTlKxuW88SRU7xqYnqUImf8xJqth+6CS10fSGeJY6br3Ye/5s9/mzvdH46e647U+Gz/1nrRe7z/EdvBq3Hn+WKlr571kqaKB7zSem'
    'cxki53+nCvqddeAD1jA4BeJ2m+LPZoeieGU6ASno12WIN3tgO4Yt8SXmM/dhsY9p88wKhwliA+TkFQZbC1DsTIPpfUNcGZuObyoQVcVmuIdkNaXqDbo1Pryv'
    'C97t+omnc6K+MCZqPHwwEAyXr58qY6cIIJjOZ/BUkKveKYPd4Y9+X7Za0shjPOWquaCu4X9zupTjs4N31vnF2eH7g6ujs1Ph5muxTnVpveq9PrvoWd3TX+Dr'
    '6cHbk+7FO+vqont0enT65ptzqgg+KhvriFhhHI7P3rfqD8dAVcFO3awuXlwsr128xKvf1lUQMjfFcjBrPJ/zLs4KJnqplIMrccQxPG4kDLLxlIEos9PqBlnV'
    'CaSq8k6U7GHGZuXWvsj5etu9fMvT9YVkY48Ntq5VFxfUvDS4S0lMNme4AetnltTFZmpA6wsgA7qTq7ZNA6LMz0IPGwnI9+EdBffD3qp7n/J0hyrxFUdx08Cy'
    'UW+0nd9j5Vy8P7V6H3sH73HdfDu437M31v/3//y/vEqtH8RS3gb18eiwS2/PTo9/qX0HlS4PjnqnV0evjw6sV2fvTw+7F/Dc2i7+B0/Js263bZ28v7yyToFs'
    'kENLF+GrHjxEyZA86owiUBWzocQR7BwcAoIKNqyj1MIEFGmQoAPob0EkgSk+mLhQW6krlrZPutQS19jWimSBuhILmXgDAPTwtJjfwt7jWxjXPKbxNL6Zg5Eg'
    'STILBU2KwgmqaNSfOgzTsbZ/wpQa0/3sQi/eGBV3HchQMP/UkDKmzBQtoBQv6uNX+ZqvmesZi4yKytOzkMWIdkFxzf5+X8uzwdWNS/EGTJV5CNNoyn6QIoOK'
    '9TIBwRw7Auv+s03k1zukPFRAe++7V/zj4Ax4Su+qZ3/ZL8vHrTpX2g5iAA94rf8RN6kF+sKx8zXgZMI6E2CWxu5rQApPWtSsQWgzAZvvNgSPkmmuiQC97gky'
    'viTIKLpuBo8cdg14LHOTiOTdBvcCtOx07u1Xt6KZHaqaKivy1e0JZFNwwKoGS8ts2KKdxev04zTEOEKJLclf9mQzSPpNcr1HBbWgQebvpO58G1zhtSACVXwD'
    'UMnYHwck0xM6Vgkdmgh1QcZwCjU9dvyW8mIWzpwN4DwuMza2Tn0Fc0dlyWwzKQVpyP7mK6jGinu+4heVo5ePCswhAddOlkPgDXX8J985Zs7dGCQjDvYQpahP'
    'RRkQU77KchAZm4iobSa2FinvyjaNtVOpsahFA/eAOiZ1IyNdxp6ol6BuwjNveA8EaA8eCT658dtP97hni2z9Srj0cnOYmpYVU5avIucwi9ANENr/OPSHsQsi'
    '2sziGyyAioRTJpzqVqpmqbythcdkkl9surYplltutYmJ1RqumGHZhuC7aqJdC02yGzJwbZJVk9ls59rgSef52Ijl0EPU6Dlyy90oWKRWjz5gpVfISCzeLRdj'
    'zIQzDcYY84ylDUpq6Frff88vE9EJLuNF8084s8KEwfGC6iChe8e9wzeoF3av3kphj5J0q3p9KeIYRhlMvUB7Fos6RloDlg+S2waGvuRg5y0WCymVSnrvDYMJ'
    'ZxJTzZApCGu5IoEpsa2/z4fw0uYcByJYUyYiZd/JvEJxnExRhyI7gWRC8AaDQiSg4J5ckvies8BbkWNlR6jE2bQei5s5rjWx30e38ES+ZXvTvvUZ6nyxVRrd'
    'ssFCEdQwqRsmkvxJSvec/2k4WowbuDuj9wzjwKNAah4Hb1RLxZxVPPzIbIMUsI3MVm6xPA3wweK09Dw+7OP7aFq6vYIdLEfTroY9aesiNXGzxSCmHs9JuB4R'
    '897zZs3YMPGNtkyAG3IIYF0b06UIZhx04rpPipdMicz6FaliSr0RzZg6lG630/O0KFa3z5sg2SVMLqlnaGG2tW/uaGSZ4EQqYggYLMaPRUgEHApRQkLLH7XK'
    'fWmTvTi6OjroHu+Trpsp46T4K/XY0lR/gIp5ZYM45PzBDSPcGmBjPOET90wazvhOmS6QZWhVLmYPwigV8kWKcY0CsgyfSAOk5hh9iAokY/SiUEt3uDOqoqCl'
    'MvnIdWpa1RHYZ30MOUXuSx6g0ZffDaqWrAhPr8vAsQxtP9Sh6vqqoL2u/YrjB1gx4zD5O/kVa2mKi+1X1C/mN6/wZhULBa15y1RbKIDK3CrBX5/wkIUSOTwQ'
    'bS0cywhtYkrEhquFWywUMZPem3OYK5qbYBEyjTQhnVY5Wintm3jh1yszG2n9Y9ORPllZTzE/8vGxd3R4acyl2Uco1Pt43ju46h16wCa6l70rs3jAd2uzQuiH'
    'ZJRA+dToaqYOupaiA/s1FkE8W1CE8grfW/4U2fm9xRUosypmSvDldEPTwpK0k5mRdqQNSYm0f4vUxm9fBJMlhdlKgL+CkD1fBTHtWft6sYn92eizEB0EJs3h'
    'sA9amUOalbvERFOa+tdIjNqcgZSzoINvAIHfFVaA10/Cu47ZHiqD1g+W3cA4jrttT0BsaJokOlcjJZR1VGwnkioMMx8LFWThe2hF6FuDW+DyD21SpS0+EB8w'
    '3zmdh3gzTEAQsyscL5Hs9XfWB7wEfm+NpvNkCXscRsdGCkDBMwVF3SKxAy3PlpCGJ2FKspaSfLiqp4sF+lKT7yXNaYqgWAY6hJzsIE2F2sI8ODu9ujg7BikI'
    '16epxMiVp+tEGnDi1WV94wqqScyjYEJOgukk1azLhWFmBUrGaTAFDU7JYCmd+ZBPeb2sMPSP0rqpYRlwSluqgJLjrNo7AwOs7S04QO1wGY2ngdkLPCOqF0wH'
    'ehfP3786Prp8C/N0cfb+qufRxHUPrjTJVf8Plq3OZtTj0oFsUr0ULaWDWk8V2gEZ2skA5fe41Ip2NCFb74s9MWfcyrSd/YyecyVySs9+bsfJl0aFaJ/9bcw3'
    'FHAC49sy2wGdKsWciPoYy4o468HocXPXAtMK5kHmTeYmnLyYXG1hrIJQKiSXYzln4N4vkzhyBu4cILHJ8DFWLL2WAZK9euH5Y39BFrD0BpB7fYOJkvCqHDB8'
    'joNMKPcw3h5UvLfXw840oIPe8TE85739wrt824XnmNpRpXhXyA5GN+R6Auvxjrr1hA0npKYCNcexcG2P0eMkCsYvrdUL8UOy/mQUoiI8CUeZhkg6kj+G/UgO'
    '0lKDhAo3wXiJ6fh2eLw7coxULw5m8AMPPK1lFGEap8SHV8L5X0bGH91zdBsj3tLB5QcrmIXktG0N7y0WVs7J2wpmb4yXM0BVRscqUNhGNyC5jDBSys4NDDdG'
    'h5lZADvhDi6nHZlLHpOTRZj1uxT/yWi+wKXzucBvbNgIkVRQhbX5rFhokHhMnAMn1qu4SZCvljtiLq2r0SMKflBbszIYReXhgsenxg8V1yEH2YnvmgoSce0H'
    'i3/J4zQnCYg1Z+zQFVWUBaCaT5edFjxCdjCZO/o6jW6z+Iv8kgJRn5wd9o5xM3t99OayL6EP1sgOFZAXy+E0TG4wXg8xaATOTOFTjC61sR4KvW+zn0cCX4tt'
    'lrVSEEhUGO1KkWUzgPLowHqELJGbCMOHpXgCkW9acxdi/xa9D6Y/jEKOEjN18xsdz+uaxk7u/CvXuLb944rfRPY3zimQLytfARG9U3AirpsvdL1YeovAv/WQ'
    'acbhOMgXkJGu5rGXzm+DKK8jGIWNAMpVhcTGBAVXQYShs6CADdqpp/wMMV8WrraxXdtsdfX39wbmzHJa9g4nDOK8I7g5sbd/JhJZSo3PD3hj7UtpYOH4Dspq'
    '/vFHp4e9j/11UsfAtXKXNgy46Je4AdRSSeQB0B95vzdBf/QOjruXl2iv7Gdj0gFl9zt0UPdloH4pB1DaE+h/dT8EDh7sxUOUWqHNFqbbPJetoOhmo5nP61wk'
    '6pGP4on3pN06zPJuUEPIkGFFwvSR/IDOuiLh38hsUaN/Ta0QU9egGxX95gB1CsMcW14JXbrzVUyDbHEF8ZUVbs+VE11C+yZ2KlAtWVqexGUPNl1tSBHkmYsW'
    'DhEQ0NOiuYk8Pzxkp7K1B7qb75g5FQbfzbN4dWxLm+p8Og3GjcXt1FQZVYxjVcG17E9DEca4uFVxqMzGeDlbyDFOMHEEC0kd8frt0Zu3mCPl/OLs6uzg7NjE'
    'QCHiVlGvNkdT7UIhLHSSm37BSwbbGASZjuMtPCibwX4YPxCfy80p0pp0s57p7+3nmH5xLBmpFHuuIb3wLk/TbhngHCEVy5TuwMVihT24BMvreFuxeCnXyqFZ'
    'uDUoAvXGQbDwkuVQVK1XjEdum+wVD9uPq1PMGqNIKY/ERq1P8/g2iC2561uzmb/YoZ2M3BxJl6Mp2dG8SGmn0A7K+KkSIuzaGjH5O+tcSsSsWGJ8MFZGQb8M'
    'gPKF2+rEh1U6WU4tIScnDesygHmCHQs5xjye5eCKqUKHWpETFCg3QckK4FoYScfisBaWQvWOzHJK656Nni9zcFd71ngOuizZ8f1hjEnUAsvPBmxOOvE0YVmd'
    'JwHL+knj4fnIKQpAbinp9KlUFNCwELzMtYadSvxJgAec1B9Y19k5ASm91CdAAOsjVtYM98z+1i1BZxTobE4e+/b+Gn6gr/+yPSyL4VlcB2ts7nJpVK2I4qow'
    'mZzoO96s+Pa+h/E/o+98s+Pbe0854f4J/dfulXz7IFRo/8eN5I8YGF9u+T2WxOL+Hz8x4mLNt3af4y/98yeDL/l8+2TQzdg/ejLyuycdxfsh7CvvgvteHM/j'
    'unnCvlbcxqBrBXCgUJWIYRsJ5qha0CXuPJacSslS1yA0tVPDPuuafLvSyEySU6uyKqxa4fTWi4qVW6iHqnAyge6mgWrWaWCm5ULZuiph/US6p2P9xdIe/tix'
    'Wg28Zc/VlalF+kZTpBRUVDhtcJn7dL1q4tAXhDNAatdOGT1h4dClRN7Wzqn9JfRBzJXRtb4N7zAsX0nX/+VPwFRX0SUAbe0wGCJNuwBDWuVVo7IbGsbRUSxf'
    'lXM6gFqFVWAFUSBE7+TgIF9Qec578XJKxfGGYTjhefGu6T4XiHEglaE+Qa6LIOZ5VZ1Ow8AbQqVbXFnzeBzgrc9+0VZ/E17f4MmUGkexdxUFX3U3Lfm6VVYO'
    'jfNoDIZRNBtPy0pM559ozGKmckUGa07tlklQcaRROP2oLvr99ya9l142eMhyvObSQ3G5mMyu5FqFyNsoSIXzAZtO2rSqOmWLK7M4lPZJhbHKoVmuw075gjSX'
    'X2fdahQI36QopXgortrMuy3pVPu9uQUz5zLolLPGfFEOElJhfoCl1oF/ZTxSOkti4Jyq+zDsZE0OJucXvcMjuhXuHZwdvz85vSxAMjcjDdAG/pelDsXVZFm4'
    'tVNBe7qbg25H47S46mJBwXmn5H7F+jLZ3ZB0rvdb7wAfvioXxAfMgqavonYnQdwm+tffrzhcGN4wL/JJEdZTWqOLLjI5i5zyu5H+i3nJ0arbaOBSMfY8cSRJ'
    '6Y81e5NtPWjtY4D2aLG0TTkzf5S71l4GI3+EPc0uNaYBjA2MbLbpd1foBUlCxVdOFZR81QcEXrsofmdVi6/Wu65MghgjXWlwSpxAjAuMCZ1xZHnEH6yQRZEW'
    '9bCd8lpkLBW49zBaxGyYjUs+pjL8DkOQlwBAqlxltYsHoRtSY1ZxNuTYX8FkMo/TulO6vnPG4GyxrzUS6wcKdJ1BG2/lzS9gzfVWs/0EZA+r7VS4E+W5ngJb'
    '/r5AmXkTIgAoPCtITegPPv+dfZgyqFM/wl5o2c7pNtqb3ul57/zKEz5NHIbh7MI77p72+MYPWpGRIbB7ru1UNYAT9ogG0IWDbiKJDcLzP/nkgMKRHKvbkSXI'
    'RA+i5sNtnncvukCg5DBy1ft4hc0u+RpWdTPATL2Rv/BHeP9oCfqovCfzQGMH5++9g+559+Do6hfv/enR1SU217QddBBrOl8l4eav5BZ3VcOfuHeHZ0hhavlR'
    'Gm5PYRFiGm+WA0jERfu3iInRKCjgc1Csc+1vdrH7sZAqrnJvAqbk8natVjikQkEIBRZTKVvnd7Ku4Ma3sDdXT2pfdbz4AHFkZQfGzWsKNGeiptRvW7tIjdcV'
    'T0I+yUBy2d5ta/6H4obavvV58UU7U9JCcfyLynlD2E1vZn58q3Pa7OET7/XRaffYW7Xs/7qa/h6upoupD8RpepGKzLzscLpNFwDRsVSkxiMHAN2XVOuU9Maz'
    'lhE7jY4LqFQnt7KwV3p5UZNcTLf4/JaQuVg+AFBc8mGlcw1AKWWTH4yKvFMK83Wve/X+ogdbysHbnnfSPT16TT4MJWDzR5TrO7v+ZsB/sst4GUNG+Uw3PHCL'
    'HBgIVlIWEKgELYBvH7kRiBNemMzrFSLlZt7DsvTmDsTVER/2dZ2/SuFv+CBDzJPwrtjvkiAL+5U3lDXrRJWWpiKjlPlyLzbpYnX7i+Jllopdr8o9utJh2dDl'
    'c96UYu3+Dp6+JaA29fF9hCBZCMLlWqo7+pU0cYPR4hs68uIZN6BdgQRtZjanmHsFAcAjkjAicj3Ym4LwZwLryyVJfnrZqizG2OEontB2RiW4Tc185dXNv9Gn'
    'W++Fl4MADf0t708hq1Lk8nLwrAFXtq17lD+69azy17e/vk1DaqSHepgeUaxUdMwKm7OGYqTepDUTMqUZdBWYAn1qYTAqiKCKow4wRp4ZPGU9hFIuq0HRFkSX'
    'KX80n81AsZpPyGkHgzVOgzSQ13zFalFrAXRFIQDptO+aN3QV0ZuXb8k7XOsCX0EehyDRcdrgkXD4ougfJStRpnyoCPGXv+sqbq2b97bLI/epa8ZT7XouhTJT'
    'IwjZKQuHQaKguK6pMfbywFswUg69K8qaUXcBwzBaH/DgX0fzJIVJoRvHMUAP0K3Lj3LQhoG6Tw2CJjD2AK9mzyXOAkpRIm5to3JiuoNNqDP5S+z6OOi28+vu'
    'EUiStlMWnEqBqBjyWlrJKju/V9BcoFRULLbb1pvz93hW8vr46M1bjKZ6eXT65ri3jRE5fz67eNe7oKs239oqg/IwcMrRIWDxAROKUZwDJTUA5+ECtHz57uxn'
    'uUIAx0YFxqzHvpNAuCmsedMKgDepKRgZfAK3miwxjPXUjzCgT5wuYUkndSP8ey5WnxZcAfcho/Wa0ry1g6ZcbzjQkRYNaGe8JLdfYCXC51OGavpsQBe80UBC'
    'Dna/OajpOIEysH4QU4yYq9ceTLqnJr3D3OReP4pA463m8SqC/MRo/rKvqNhrzAqE1IMxAKYY43nfOu9eXlrbMGH5Npwa+fog7lS3VPCJdS7M39zdnxmfX9nr'
    'pBprn+3kNoQNFeVyDqdgw/6RsEXgANoQM5l5py6TQHf15JAA+Y6x2+cXXOhdCUFEChEqOrAw4qgcfGKbD5UDYlzEZiN0w7Uo1SZUIefaGx93WY5vhHFjjzn2'
    'lEzHSQyWrLusiqdzy1/NgRdiqs1ljC9IPY9RkW8UiUty+f18XI2KnUfVNmNsiKn6RAmoEEX/f2/P2tvGkeR3/orBLIwhEZKi5N1sQpsBaJq2ddELIuVLwCUG'
    'FDWSeeYLHEmOV8vD/Yj7hfdLrqq6urt6pmdIy7kzEETs6a5+V9e7YCDwKJEPzWRpwm0oPD2VMd1hxQEJ5y9iLYMLjGjKG3xFjKuy+/3M1lbn7TZkJPbxZ43H'
    'Ble9Xn8w+Md95i5DQXZkWziGt/OH9JOIyKEMygZf4bQs+n/M7qutP+UduOhe9s+G7eCyD1evB29XoGJaBd33QMsMhsoj1lA23cvh8btubzj43p457tnuqFoC'
    'fao2JqKW+YKl/mhafwkulRQKiQjgXwA6Rn1XcZ7nye09+i4nk818BlXgqCbXq9XngPJJbR7W92kTbp9qSY9ECgDxJH4lA266JF8+JUt0UrLn0EZ9MZIzc+LU'
    's9+sEEw8bPQZHiWVoWffl6jtifaTjfQjo/IVR+STTRRTxfAYS9j4cYbnas6wsDU2ocx1O2DFeH1DhYGKr76NbcQd29XQKWz0yCqqB1tBtUseMSocGeXLaGaK'
    'xREy2cNmS4hrQhWuu1hUI4Q9g2H3pB/zjGK8Hx/7l/AuvTuHq9sfXkrncF7flORQYqyyhnkULjazlThtCgch/kWMZ84enB/mth0UJwh82b8VjcbsRJ+TEu3h'
    'uL6nw3qoRbuxVpN9l/R7W7GHAGMmunFNMJQIp7pbbe4xbo5cYMw61D48UpSWWbt48nAzM/Fhuldvj4fx2+NLIGxvrYT/8O+a0ISR26Zmbk9mRFs3ULmvG19A'
    '0zXtsxR8+FrmZB08TWo9MgdrrALm+JagkrdCzkuAfF3XzS2yIS4ZqWAmwfylw39uKFGPSVxOSwX3qRMyX+R+RANfklRP7jsFclPJdXbCTPv5BA0K0MC6EzKi'
    'V/yiRfXkQeohFQxOfqVVF5TkZaOjLCGWx8fh8Wd5z2oiROqeESGZ/hy474/WjQRBO6wHmf20e7mzMWaw7GMyCHzpMGIUYF5NGq2WDZIS4GyBH75XVKcau6FG'
    'mbCDl2wyRR6Evjef8RrNbvdD9ns+TJk3TXj0qwHHz3qteKAZGM8O+F9yF9TZd+ZQ97mS0uXw6xX2vCG5W4Ld+pMzFEhb8/Dkxco5oDoV970K+xN8alFitDgh'
    'hl2fFLOj4qRUJnM0Xb6xp+EpvDjBzDW0b5ocqQe7txb+Zhy1rYiAkc5omoqurFKUSI5y7o4AJqpvwXz22VInPhLtm2UP5Vessq1M55PZAr5yLfJo4Mhg4oZU'
    '3OOn5zZL4Y0d7V6ocS1H9/ARcbfGkO65UXUCuUaa9wsVO3qg5dUoHyZhhqaDHn+Gc4n6XhMq8TbUsCnb1RM/j9kOG05/ta1tbpbRae/sYCM7/to2hLlVkEgl'
    'jhFZCS1WepZIySNOYowkB1IZI5I/p1jf8ISt1uRHTn9PJ2tiRl4FLXQSXgLfPJ9jdCdmP/5jdQ08x2n3t/jfzt8MOFLnDuGbrs1WS2YzDRT0tEHa3BYELX60'
    '3JWRP0dtXZ1m0/iOfygZedu9GB5/7AfDD5fnV+8/XFwNA21YFlycnxz3fg+qjz/Xvr+n49OL88thFxhlhBUMrCECPq46PvUBuX/UA7REqXOIFU7Zx15lbvQr'
    'yg0kfHmC9Wo+myqDCXMLHJfuxNo7NGkkcCfU75TiVTnHwppkoMWaDud1z+KkFF7irxRXdD5ZK2A9YzIRCL/zlHLjBcN3cLYWq83Xxh3sJBDWyRK5YOV9foPT'
    'wZSMJIhfrVMF0DqRs0+3MvhgiMqRnMVgIlBdesApw9PsbIfES6Csab66g1JlIpJoOzdtEtggk8Al51sy7ts40MVDqmRS1wmtPZHF603C0n/oj5rewM/pZpWm'
    'Dd7FdUI6B7i/qfChNy75TRXLN4YViiePk9kclya+u9bsgBO+1Aa2iDD02fQAWqHXS1QPok2EOTGmK7wxnejh/rbxU+QLd/H5UeUuyyq6YbcpNr0nOoYOXo9P'
    'KtTi9MFRG3o8zGvNPz+ObKB5I3Y3X6+Np9rnR8If0Wmy6OqZ40xawec3kU5SXHMoMNYwARA2wm22lBnufokNMLgMrzdKfGdL2GAK1aEpUeXM9xShQihqB9HV'
    '2a9n5/9+hqNS/vqLayhGl8oggucceL3V54i53G1+v5BosWJlxNEuqTeK4OzezCaNdDHDPhoNAtqAwXUoR7i6N03qW1XAwAhA0QEVVF+uPiWYDhz+IPPSaJxl'
    'oG4wkacYwMXxRR95Bmi0yZcj08xxfUnL2ckw7w4hjMH0cU3hwJFvZksZazVVp3rb2xmmbUOy02wttdV4tFLab6cRrQMiEDw3CKC54fNXz5+/7Abi/3Qv7h6q'
    'Iwhg9eeau6W4Dtsdp2oNL5sM1429w/k6OX+P8ZXQkFc8mWQOjCboVTLk/Wut0v0IVGP3DYqKuqfx+zfmYniQQa2C2oPjs3fnqLDJHF58EPsoH0QUZ3lVY03H'
    'kfDxcVEvQYraS5RB4sX3I34AiRvaH3abwfBT8hX4PqYtbufkTcCvFAfVEI5yaV2mqsO5ajvdSsKDjI3JKUnSdSHqk7UxN775VUMF1SocVcfGGhP+RIDN4ESi'
    'nDffAR/B+H6xdvoyNq8iCQUAiQrs8yNEjQhEO4nZU4Clo4hqR4j1MJUFefNiMtWq+loEdQw4G3mltBNNVwmMJ/LJZLI9LDGd87IiPhG5V9C7QrJZj5aoVtA1'
    'QwTcXQov7+ayC+ItZ1QnsO64m7ez+Xw5qbZQEy4HYD9ISEB2SyBqXZpfPiWbpOqWwYmF1uTU7S7iL2hJnx+ZZa8WGI3nzuy6zqobaZ1jJHAbDDXNLdWdHmjB'
    'qoiG+L9Rxm891Z7oKY11LHEvex6mGfRaeEUopB1MqDY2KAabN4E1mU2WiFwqsfG22STaI2lxzfHYii8X4Ygo6/VDl8V71cTVie/899HhM/PfR3YHXMkPMaF5'
    'JbBgOfPjrAtlO40nc9rvik70HWFhZ8/iO3XM7sR+8cLBJ3GZi1aacf9dE8M41Aipoz7XqFCnlD1ay10bd6iNANz8ZWWobcTtmra2KiYSBwMw+zAQiQ64CAjS'
    'T8BuJkuUuAcf4RUKkKLYrFaLgLKJJkSek3IYhtIMztFC5gtqEw+blS4wS6TTRsZMKSbxuTvE46LIHP1kjezDyoYNyxvx0bzKY2QND1vwj4MAYr2C9folkJWq'
    'R0gIFtStYRiHaqv59yOo4uu2ZuDknmQY0E+iH+dpx28V3tmCxTiq5Ms8LHSUYaEzjSKVxtfXR40pA7cLPEGHQDTBjTiqB7kmJA5Q+6vDsgc/NYAxwtPRQMuD'
    'g+A/D1uNw8Pg/exNw1AiAYX7RNu1xWT6Ccg1ePW/rACY5BHRMG+eNJAcmNwcMPdmrRnUKWXRVzPoLtbv4TKiQOlrStlyp/OHFD0ErhO0aDj8EYcQ2CFcJ9MJ'
    '2kEAvRu8fFn/8ajV0IHB4KbAMnF2etgtAAfDCzbIBm4QqSeYZAO7x5nr+GZwTSgaQnrfUNQ2DZbUTXzGe/ltpVyQucNQdoRqyqTysNJ7zoHoFR+IXv5A9MoO'
    'xMt6kGtCLfq/9U6uBscf++RZd0IpriMOFxVtcca5qb2G/YGLRzNDeSGdrDdA5KLlxT3Kl6z9B5uiMMuBhiXaSARpZ6RcNRM+Sxe4Jqsg/TJZH5yfn5LFiKdz'
    'WFZx+4bnQ9iMbg/lOvHJ8enxkC4gGQ75Rn60u/XLwtZHrd2t/yrUMcW1/lbxFu9xKPLt5LnIf8Wj4e1LnI4f64GvYeX0+Cw+7Z/GdikEv7JjnL62yMweNf8W'
    'AegLeK/jARqRvB3sC1K2IZFB86gVWVGjAxJeCjyWvdViDfSqCmR6gFIgPHNfErThUtmyg4HhfhC9JPNb5JRSKyVSR7jBjsQWWQHAujrwjQmFkiFEMIc/NEq5'
    'e5hsblBFn95jRji2/r2dTwAJBo8/ASxK06MGo8nRJl3Lf++judjA6AMixNMoLIM37m6TUBx94FcP6/wV0PJkE6ePixiQ+ewaxU034jtgw5vVIlbYUJRTVEWg'
    'x5MkFaVIUcaAAG5Qahlfr1ZEjTndwYjvrheiiAKZub9nG/c3oZR28NKWmHBuWUDrr7KEgoxBwZGtgnG6VIlOIEeeykJ3yNx5BO9gJEXmO8wHFVqLYA8iDVht'
    'UB40XlaxV3Rkc72gsAINr7RUG2gVlP5nBP+OCHwmJ4NSFprD2ICYPgdEj0CoWz78cDwAcujjeU9lLlCxiyUAGHH/Y/9sqKOgGIVFlKD8IV6S8HG2fFxN2f3q'
    'hqSRD/ovQ67D366/JZUkcDr1WYJhYhlKStRKK7dpqocxQUiZib+EbhN/4lu9cRlrfdqNjIqB3D8QOLaag6tEor0sbwxlHv6WYZaGuMCm3vgVNLECKQADzvql'
    '67VwncixlEk13H/6bWVFyNjcacYmQnIYkDsbCaYaYKZIEcIKc8Xz2WJGPWNbkqIJWIZk5u85Upu23ohw0BKCDkhljC+4tWukEzUgrW3W/IVOVaqSbGX0vd72'
    'lmPHNCCYqE2eVse1ACuwesz0khfnOIMYwWdkmqMoNzhbx+lxLB59WR04y7dw7N9ROCjutOO0hJtmb6Iyc0cbAQqWs1x9qaIbG/745wpuM9mz3+LPavTi9xeL'
    'FzfDFx9enL4YvPhnZGzcgUAl4yVlYR5fnp+jhb44/GmEvz2ey1TOx/Xx5ygDcJ9UcBVlgBJ1ImC6Do9+qukC3MXg5RHqnxpWD/euOxgqU1G0U/khGALdQX/0'
    'fwNKJEAPU/V70H3XD9ik7veoVtjNiVIOGUNK1GTS3rbRAtQ27LJNsNb4mn+o3TCx37UC2DS7UChSpVez2E818+JW0xRQeANRncbTuR7FA4Ee9FEV7qugpDtP'
    'GYZuW7PT6e0LfFoEvFcMfEg0PZM4TM+jBllM2iEb7V4QukK+I3VURdhOclF2Vwy/h0KJKrCANdviNnrKUuTt5uHt1g70BAeILZXWH2lKQBC2uY8iJRDIbEZy'
    'pwLvPwRjBQmEJcdOK8X9kESleqoHT52HTz4JRLvZut1SnCafzIQpEa2MMj2da+adBDqIjLk3nqZfHKLWigiDQtGK6dGskLgxzLIjmywoYDW/aHh51Sfghs4j'
    '6srHX6o+3nVPBgJ639i0IuEg19wGD8iKxX4IrpHnhIXAMelnNCB6wgBm3wAOkKDyH5ttGfRP3pkYCepZ8Tfj+AncLGZPEuQVTOgFhFy1mMIXtsD0y1lvNGaW'
    'hHAs0uU8HjWBDrb3UCmzmUxw1shMXr/CDYqK8yrwK7aVMtxCHnAS5T5gYyIfKYE1Qc7tk7L35YiBtnaupjB5MOm6eLRXZ70P3bP3/bc+RF65RhOe3elrtQ/l'
    'TYzIOBbIGO1MGFuRkggd4ZByQzPIDWmORuOKSUx4/TXWuW2griwmhIrSEKS+29Corqho/HNbSe9X61ghGmWSr1w/M0g67l1dor8EfM98yYprRM3MFw/3Lirn'
    'P1YypBitGSvMEOxlX+UuI6P0476S3jKrwzkmTFwywfQsHNcBNz4xazRyi0osEelURtb8HyvndPSK/1+utXaCFB2myUJZGBeqOgrAFatGACAPCHc59owfy2n4'
    'lo9yZmHa7ZyKqVlzsjz/KMwSkvuJjU+ll94wmwtmGimIpSQTAAWONqMIxgavBbGC5NxNZx9jYzygZp3U9iPFZo0FN6lhT/Owp8+H3TOwybkumZItxKLqOVk1'
    'C5bniPamLJUquEfG4oPFxcgGu2BwOprbz/D6ntdIDXWJ1hXz/YExO1EMEBXzeohIMaEKJzUJ6MmgR7WnY/RKD0BXvZmhuucGzcmFCF25F0+/YVnNOtWcpj/s'
    '01YNSexIr2xH+ExjVd73uu6upg+58tOJiT2qbrCG4szrgeXX64Hl6qE83Uw7FLEo0Fxlp8XX4m6+uoYlM8yWMadEBnLKB1cVAhQsxf/B7NgIiho6zkBWtKEC'
    'tpHyU4PH+3AotYqu7KMdOEycqMcikXaxcbeVlbTz6FVUy4hRbOVMinXZJCEpIAWl1UnWxWe6t221XuoOi485eQzDwcqqPHLUrEJWwyBFiQQsxThenyqfZEeb'
    '7thPsoEQ+OhR6oLMEFES1NYHz34RkiFeV1qT1R3Rde5Ec3KjNp2tQoML29IjXZJtvcYVYt1KJVASUHlNRzfuFVpJWP4aEkaRfEtCKarjjCUrCGsDaawdxArC'
    'PUaZA5sRmrWLsJa8BFKq1nYYU1ErJ2trl1htiXZZWVy76GXLTMRts3sWHmleOygmHDMjZLu5LHObqSXs6HzcbKZ2XkrYLmA9nYuclSKa+0w/a9IDMCNoQ94Q'
    'NmRkiuuu+E19GGMix9ndEmP3K8t66zKdC83tlT3WC4WA5qm7h+OgvBGV2xzu5vTTZJN2Do9arZbPyJd4Og4UQm5+TZKDEpCsga+1T+HIH1HOVhbbjRqm3/bY'
    'a9SIhsJQlidho9cPZFGiXOmBGWS5D1yWdvAETba/RNKmlg8eWzo6WhIkNQ4VXQG0RwENaV8gQ6GaxZxa+MzCZXoYIeBv60CRqfkOfBMgWx7fIMwIDZ0lqmWA'
    'TJZfq+ZdIdpkN3Eq51Q+AFQ6xkrpGJORRcqsqR6FVseX2pqK4VZ1g9ecHwVGYsp+6QQ+UZoZDWdFmZK5KtywqvX4Q8pZcBm5g2cy27INlZpxDbssRmalUDy7'
    'i9AKMGopKBz87qUuGkfZIfG1sbXQ6iw/C6MBmd38UddKwISM2ICmd3g5oQ9JY8k8+XWinqMoFSoODFR5i5Eanx6RDfp+tnxIstOEQVeyszZ6XFpOyoSIV3af'
    '6AX2fO/jYssupdxopGn00mAHbGOAjxE2byJaq6mAPPx23CeLNclZsI5rUsg9CX/TiOur3ZTmohS3I6oZP1RkPColzqPsRK19QyP2YYRHwumiowdINZku97mI'
    'Sg/SKKq7rqJYIHw9I6a/1BKxIQN6BbCAxCBzJfWVmnQlfGECOzDRkLTy6gAl2Wpq2zjWM3nSk9g2kVQ3MG4RAnnIaIio7fW5xqhncPnoRpMS1uBQNIrKAkuR'
    'DbIaWWEDJxw6NcDV2F0dLxtV3034FgLLRi1X8AxxbeAZx6UYk4UDIgGaGXMXzW5nGAIXnZlYaAaTRQlsTH6NaXHP+RDmkY5BWSo8YOZLBDFGjFcsZC8cgBTl'
    'm649Qv5d7ZW4nyDkx6bwzQIx0ch4TsNZSr/CeSI1Bj6plORsNUcUX6sXjGPMLvurqeswdEEn2TqwL+h2k1ePOuw+Z57B8O351dBx54EpduC/uvTf3dzHy+QL'
    'rCpZEKmK4gpvSLL0JBnE1TRq0yBRyQ+ESzsgzKyFB/g/vGxKItBmJODyV4qJbgficqqJcBnOSEkLMFfFbdT2SfyLRA0ZFKZYA/UcjXDYzfXsZqykQiJEgkV3'
    '0eikixqJ4KlYpfCDJEa2B09eVe92HEQC7BOuTPv1y22g8VgEcKq3UfAvXqTOk/q/UssZfNkz+DKKAPsLkNCSaQB0FXvyUN5bXWFKFaaeCnKMyMvC+kFNjyMi'
    'KgxRMSqeBhNiSp8ZfrINUmFdS1Wdig2cGdxfZIc0z6PYnKouRsISptmkhGJ8tRXPrMyGZfw9wx0mf3yaPKSwUfQKkX3Lw81EvUkxXJN4dcskGtsJkfEyFwiB'
    'igoXiRapQMhRFD3bCiAul+ykT4TeNFb1HfeB3Ds3URE1qn+QOzZOFkk0+iWmlSf7cFFZdDw4fv/r8cnJweHLv3PUSqPes6F/ZimwjxSaCHk46cylF4mhCQ0g'
    'OQcAk5y8oqAfwDsCADStXi0SDGQJjOJNwDtIw6bIL00Rxqa6mRKJ+NT4uR7A+LbF8+DfHBCV2WLy+UUihslfFeOIV0NwO6SNyLBxTqAcQpnESxGCcvxk1KVf'
    'YepGN4ShTfTw1RtG8/NsPl/fVTXSACw7u4MVbcKGDPuXp5ksnoX+gaXd6OE3zVpU8760u2E7fog3QPKSHy9rSsk+iOhG7Szxpyztl09w/H2rq/KJi55fmyG1'
    'K7n8o+k8SdbVVvOw9n+9aXiL/txNw86+f7+8/RiBM7yK4yZlYBQ9lffgQPbqQL4l4M4zAtUY5oODgUT1Pz8QTZQLRIOuhx5mJO+4nM+4+9z5qYgvhdPLMUtl'
    'gXIU8hu1USI4zqXWrZgTwvdO2A9jCGJhC4yYmi50W0R9hteorQ2hHtb4yKHtuetH5pjTTCfrOlKhmBeVqqNgVwBUXTRYEGhM3dHYSdm5NyuZ8MWuiYS7AWpS'
    '+ZUX08x9M35hGXHO6yKZuheCFCu9LpEq+bsvEf+4O5jHAbqimCJgPECF6IPOEk+73D3cP23gZAgArQo2HlSzVGjD4Y2HEdGWfFpR3Mhv3hGvcM5AufkDObO8'
    'fM+X1hArezG5/kdJcHeu0pRXCcDV2ABHrJO5hoD62bLHSeOAD4Ln4ZvdJwv33SNclHn5+D3KRuaGaoXzyom7coPU4SrX2dze3pfHfRWI/vasdvnbsd8L5bwh'
    'pe/ITmGceZ2NrrY4+6fREyvOb5zPmo3cAu5MJ2gpx+OykFaZraIv+bmalix7+pY3Jwdsx1PiE9F98yvpfSmdWZQ/hfk4bMIwwoabLFkHJ1lYlIflse4Q00RG'
    'MGvYIWw6vAZrpDjWK9eq1Tx3rZBd10JZ5zTmjNPS5B7YksnD3Ou2MxrX9F3NmR7USqEjRzgSGqfxN8BJ5pN1SpHY/Bcmax2ZB3BP0jO/RVn+1rvCEAdrRaNi'
    'iUiJDERHftZSj3947gyx3+JP/wBCXL7Ok1jJbfAvdf07T2otSwwv6qzqipYTOLCA65tHt9sUAIQFvQGyyIP1OQR9I2BtXIKb1nmyu2/a8Z5D5xTlJ755UMx8'
    'lT/UcNoFaxT1h1270Yga8lDuJwSBqSZK+9F5EmRQ43Ab+XFOVuBTjE/yJLaWzZOUpyN14lnbGs97phAD61Kehx5mPrmUNHVyxVOcdY47fh34LGX9dIxp5EU7'
    'Mpm1M4GRGrwSTSoI3sY+zOoM7Pd40PvQf3t14kW1T1sH0bIZhbenPV4y32vG8TO/gynyMEfV24hyDLI5u5BiqUi7NgavSmNjDb4AYUy3r1Q1RB5qxtuo5uW0'
    'il9HTe15TBPahTMoNv8+LGwj+YHZErWM1RYpdP1j8t80/a/3HQOY7jeAUnN04VReYn1UuE4/FJqZ1gqkMuQ+0DDuA8WVbqUPmr5AwZtu79fzd++C//mv/7Zy'
    '+nIwIgKa4x0U4MHb3ZbiMGc9iwJ7UA+efKhnF2B0jkGfLh1uA64fAy5Y6l0Ae4UAe88D6LiRof+YgggAiw9KOcwiHxPhYfIqIxrH1UcxePTM41R8+Z6JPL9b'
    'oFSIO3VCoCxitAGBNKVmsk0QsdN5KmGwnodGfU+Ymfh3PFgZzx5NZhuyYDOt+4157bPvB5xz7jFqjT8LAXGWLFyFq8v+/xf6sVZ8efQzHYV6icJxOSCzemVL'
    'cpZ8YfljktKCrhP2KSNnwdK27J7bcJxOU/IGVCGEUECpboyyQFLp9TTHv+/tzsqKKBCqFNZk0hUq4RFKo0iwhCIgAYQcRZxzo5OaZKWzeekXtPVVEgoTGdxE'
    'SrYxJFGxbLhmxlAm+vtLcHyrtIOTfPyS4Boj7sIDAPuJG1EPvkxgrUXevCBdzzLJ78TAkSKQgwdqvfk3NF1kmdSvydfrFfRzrBNOyEwG0T+W4tIcnw37l5dX'
    'F0N0Be/Da/EWQ3WzIo0W3HFSZtOIgKL4wRmc3Cbzr81mM8onS8qrJqPcuPB0wCCU//urTF+mvScLC3PR8Aa9crJF6DyWTT6vyu7YGuiY1Lg2ImbdSD1kQPD0'
    'YbGYAJ40OTtcGw43yQ2a1R82W47lvElyU+CQYRwnIrMFiLu/3RumUKAAbQq/ifbMEQsfg/3EJMUW+THG8ZtN5nnL/JI2lMLyObb8ordeYW/Tgt6e4wUgOsyT'
    'WeUtdbd7eRE8z4tCbQ7Uz3r2Z9aeol1br4M/w9Mgm9woymUtinzJjdxq24o/eY71GxhcnZ52gUVXjgO5iypStWG0KpWq1V58wt7cqFlRGVb3zouhqhvvX9na'
    'nxxD2QNwi2oNDVgxnm+1ZlJU0CeWyuwBb/8MEWxOW+GkpbKfPTqiVGI6kaoG9W3YtJqZImWMo+V3h9QhWVNF57GKeXMMwi3NKFaaTSx0cGjoxaGh6VfAf3Ye'
    'LZkETPNPnA0sk8QrNIZHJDrHXk2XdxTh2uiRYWEf0pgVl6QjNNJJlKKYlcg5a4U7EFxIHcF/nNLXtGqJ7x5UGxYg9tCL1MMdSD2cFvbiRejhtKCX8rkWI/Kw'
    'GJGHRUg83I3EQ41mwyyaDb2YNCxHsaF8D0LfexBm34Kw6BUICwmDcCfRIC9VhnYItQfffhSEvqUaT9BaAwwHb3AdRhm6isQg+uaVptbbI61eqJyVYZlD5bDq'
    'D5PFlQ0WzNU3ciY0vPc2YQxX0Ey+b2aJFOYxqTL0XoUXyaZBycVmZHC4SUw+DDZ0RBMVxcxjYlonlom1gWD30Fc6Nv1i8hnTnBjbdScRB9uuq5w8KXneoz3o'
    'ZEq7gTyDCiKmxcuYvG1b2f9Fzz4EJgRW2Ak1mwksWkZS4SRrEwyOFgf0PvR7v16cA7GN0bKGwUkfA2Wdn/Wl3ICyhhMDuP/b5e1YZTIOuvALG3KmbxaQ6uhc'
    'g0A/16rbTMY5DcsZuYnsdXY+DH7vDw2IsJZfJS7gHMOcn0sKKcJ6IEka04LJiwNDWxzobrCJszamjVo/X4ynsO6smmnR04gmG/wLWxRiIdP82GqntYpXdJjR'
    '2O2JkQzwPh9CDmpgxTsIvCB+XrapJmQCb1Pnmuu2lzrFRE6eZNvm8UuudUnPfjSjIewKWxSKWZaHLQozMBv3lHwX6WEO8JaHecEUU+PIrZivKcTUnBODIrAv'
    'Rc3nX+Kz/m/DgnBlgbqULzEBFV9mXKofgqPWX1sBtOtfnnVPAr43QGcONEIpQ1dlHVLm1GD4oR+8O76ErviaMdKCI/AqeHtO2ACdk47PrmBI53qYPrRS1tll'
    'H1ge6uz4LRxspC8CgUsBMByfq1MvsinEyVJ0bN1VYuSf3Oo6YY1Ks90l70A4AH2UwGM272Q+54GwhEhtY9uIeV/lRfPQYedJ97qFcf8v7TkAug=='
)
trainer_bytes=zlib.decompress(base64.b64decode(_CELL32_V9_B64))
actual_embedded_sha=hashlib.sha256(trainer_bytes).hexdigest()
assert actual_embedded_sha==V9_EXPECTED_SHA, (actual_embedded_sha,V9_EXPECTED_SHA)
trainer_text=trainer_bytes.decode("utf-8")
compile(trainer_text,str(V9_SCRIPT),"exec")

assert 'SELF_TRAINER_PATH = PROJECT_ROOT / "scripts_manual" / "Cell32_Benchmark17_Production_Trainer_v9.py"' in trainer_text
assert 'ampscannerv2_production_v2.py' in trainer_text
_amp_marker="AMPSCANNER_PY = r" + (chr(39)*3)
_amp_start=trainer_text.find(_amp_marker); assert _amp_start>=0
_amp_end=trainer_text.find(chr(39)*3,_amp_start+len(_amp_marker)); assert _amp_end>_amp_start
_amp_block=trainer_text[_amp_start:_amp_end]
assert "import pandas" not in _amp_block and "pandas as" not in _amp_block
assert 'writer.writerow(["sample_id","y_score"])' in _amp_block
assert "AUTO_GPU_MAX_WORKERS" in trainer_text
assert "CPU_EXCLUSIVE_MODELS = {'ampgram'} if AVAILABLE_RAM_GB < 16.0 else set()" in trainer_text
assert "MAX_RESOURCE_RETRIES = 1" in trainer_text
assert "Source TEST rows read    : FALSE" in trainer_text
assert "External target rows read: FALSE" in trainer_text

if V9_SCRIPT.is_file():
    existing_sha=sha256_file(V9_SCRIPT)
    if existing_sha!=V9_EXPECTED_SHA:
        raise AssertionError(f"Existing v9 trainer differs; refusing overwrite: {V9_SCRIPT} sha={existing_sha} expected={V9_EXPECTED_SHA}")
    trainer_action="EXISTING IDENTICAL v9 TRAINER VERIFIED"
else:
    atomic_write_bytes(V9_SCRIPT,trainer_bytes)
    assert sha256_file(V9_SCRIPT)==V9_EXPECTED_SHA
    trainer_action="NEW EXACT v9 TRAINER ATOMICALLY COMMITTED"

self_env=os.environ.copy()
self_env["GENPEPT_CELL32_SELF_CHECK_ONLY"]="1"
self_env["GENPEPT_CELL32_TRAINER_SHA256"]=V9_EXPECTED_SHA
self_env["GENPEPT_CELL32_TRAINER_PATH"]=str(V9_SCRIPT)
self_check=subprocess.run([str(Path(os.sys.executable).resolve()),str(V9_SCRIPT)],stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True,env=self_env,check=False)
if self_check.returncode!=0:
    print("v9 worker-route self-check STDOUT:\n"+self_check.stdout)
    print("v9 worker-route self-check STDERR:\n"+self_check.stderr)
    raise AssertionError(f"v9 worker-route self-check failed: returncode={self_check.returncode}")
assert "CELL32_V9_SELF_CHECK_PASS" in self_check.stdout
assert str(V9_SCRIPT) in self_check.stdout
assert V9_EXPECTED_SHA in self_check.stdout
print("Worker route self-check  : PASS")
print("Worker trainer target    :",V9_SCRIPT)
print("Worker trainer SHA256    :",V9_EXPECTED_SHA)
print("AMPScannerV2 helper fix  : ampscannerv2_production_v2.py / stdlib csv / no pandas")

migration_payload={
    "schema_version":"1.0",
    "created_at":now_iso(),
    "status":"CELL32_V9_ADAPTIVE_THROUGHPUT_MIGRATION_LOCKED",
    "trainer_path":str(V9_SCRIPT),
    "trainer_sha256":V9_EXPECTED_SHA,
    "scientific_protocol_changed":False,
    "source_test_read":False,
    "external_target_read":False,
    "before_ledger_counts":before_counts,
    "before_failed_rows":failed_rows,
    "before_running_rows":running_rows,
    "changes":[
        "adaptive evidence-gated GPU concurrency up to 2",
        "bounded CPU concurrency up to 2 on current host class",
        "AmpGram exclusive below 16 GiB available RAM",
        "total-active and live-memory guards",
        "one resource-only backoff/retry for OOM/SIGKILL",
        "timing/ETA/resource provenance retained",
        "exact v9 worker route pinned by path and SHA256"
    ]
}
if MIGRATION_AUDIT.is_file():
    old=json.loads(MIGRATION_AUDIT.read_text(encoding="utf-8"))
    assert old.get("trainer_sha256")==V9_EXPECTED_SHA
    assert old.get("scientific_protocol_changed") is False
    print("Migration audit          : EXISTING v9 AUDIT VERIFIED")
else:
    atomic_write_json(MIGRATION_AUDIT,migration_payload)
    print("Migration audit          : NEW IMMUTABLE v9 MIGRATION AUDIT WRITTEN")

print("Trainer action           :",trainer_action)
print("Recovery mode            : RESUME ALL INVALID/UNFINISHED RUNS")
print("Speed mode               : ADAPTIVE GPU<=2 + CPU<=2 + TOTAL ACTIVE CAP + RAM GUARD")
print("Timing mode              : TRAIN + VAL + WORKER WALL + ELAPSED + PARALLEL ETA")
print("Scientific protocol      : UNCHANGED")
print("Source TEST rows in C32  : FORBIDDEN")
print("External rows in C32     : FORBIDDEN")
print("="*128)

os.environ["GENPEPT_CELL32_TRAINER_PATH"]=str(V9_SCRIPT)
os.environ["GENPEPT_CELL32_TRAINER_SHA256"]=V9_EXPECTED_SHA
exec(compile(V9_SCRIPT.read_text(encoding="utf-8"),str(V9_SCRIPT),"exec"),globals(),globals())

Ledger before v9         : {'TRAINED': 472, 'PLANNED': 206, 'FAILED': 2}
Existing TRAINED-like    : 472
Existing FAILED rows     : ['transformer_encoder__AMPlify_balanced__seed_107', 'ampscannerv2__GenPept_Curated_2025__seed_105']
Existing RUNNING rows    : NONE
Committed runs           : PRESERVED; NOT RETRAINED
AMPScannerV2 env preflight: python=3.6 tf=1.2.1 keras=2.0.6 numpy=1.16.0 biopython=PASS pandas_required=FALSE
Worker route self-check  : PASS
Worker trainer target    : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/scripts_manual/Cell32_Benchmark17_Production_Trainer_v9.py
Worker trainer SHA256    : bc2276c2377e0c0730892c78412e307949547b4771b1eca10073c6ff125e5b6d
AMPScannerV2 helper fix  : ampscannerv2_production_v2.py / stdlib csv / no pandas
Migration audit          : NEW IMMUTABLE v9 MIGRATION AUDIT WRITTEN
Trainer action           : NEW EXACT v9 TRAINER ATOMICALLY COMMITTED
Recovery mode            : RESUME ALL INVALID/UNFINISHED RUNS
Speed mode               : ADAPTIVE GPU<=2 + CPU<=2 + TOTAL ACTIVE CAP + RAM GUARD
Timing mode              : TRAIN + VAL + WORKER WALL + ELAPSED + PARALLEL ETA
Scientific protocol      : UNCHANGED
Source TEST rows in C32  : FORBIDDEN
External rows in C32     : FORBIDDEN
================================================================================================================================
TensorFlow GPU preflight: PASS - {'tensorflow': '2.21.0', 'gpu_count': 1, 'gpu': "PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')"}
Stale RUNNING recovery   : NONE
================================================================================================================================
CELL 32 v9 - ADAPTIVE FAST TRAINING + TIMING + EXACT ROUTING + SAFE RECOVERY
================================================================================================================================
Locked training jobs     : 680
Already trained          : 472
Pending this invocation  : 208
GPU-lane pending         : 13 (max concurrent=2)
CPU-lane pending         : 195 (max concurrent=2)
Total active worker cap  : 3
Logical CPUs             : 8
Available RAM (GiB)      : 11.1
Live RAM launch floor    : 2.5 GiB
GPU                      : NVIDIA GeForce RTX 3060
GPU total VRAM (MiB)     : 12288
Observed deep peak (MiB) : 598.5
AmpGram CPU exclusivity  : TRUE
Execution mode           : adaptive GPU concurrency + bounded CPU parallel lane
Worker trainer path      : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/scripts_manual/Cell32_Benchmark17_Production_Trainer_v9.py
Worker trainer SHA256    : bc2276c2377e0c0730892c78412e307949547b4771b1eca10073c6ff125e5b6d
AMPScannerV2 helper      : /home/pc/genpept_benchmark17_work/production_helpers/benchmark4_FINAL_v1/ampscannerv2_production_v2.py
Timing context           : parallel resource-aware; contention provenance logged
Source TEST rows read    : FALSE
External target rows read: FALSE
Scientific protocol      : UNCHANGED
================================================================================================================================
[LAUNCH 1/208] GPU transformer_encoder__AMPlify_balanced__seed_107 | active_gpu=1 active_cpu=0 ram_now=11.1GiB
[LAUNCH 2/208] GPU transformer_encoder__AMPlify_balanced__seed_108 | active_gpu=2 active_cpu=0 ram_now=11.1GiB
[LAUNCH 3/208] CPU ampscannerv2__GenPept_Curated_2025__seed_105 | weight=1 | active_gpu=2 active_cpu=1 ram_now=11.0GiB
[1/208] TRAINED transformer_encoder__AMPlify_balanced__seed_107
          lane=GPU | train=89.15s | val=0.51s | worker_wall=112.40s | elapsed=00:01:53 | ETA_parallel_est=04:07:42 | active_after=2
[LAUNCH 4/208] GPU transformer_encoder__AMPlify_balanced__seed_109 | active_gpu=2 active_cpu=1 ram_now=10.2GiB
[2/208] TRAINED transformer_encoder__AMPlify_balanced__seed_108
          lane=GPU | train=94.73s | val=0.41s | worker_wall=117.66s | elapsed=00:01:58 | ETA_parallel_est=04:07:42 | active_after=2
[LAUNCH 5/208] GPU transformer_encoder__External_Benchmark_3__seed_100 | active_gpu=2 active_cpu=1 ram_now=10.3GiB
[3/208] TRAINED transformer_encoder__AMPlify_balanced__seed_109
          lane=GPU | train=74.35s | val=0.52s | worker_wall=90.36s | elapsed=00:03:23 | ETA_parallel_est=04:07:42 | active_after=2
[LAUNCH 6/208] GPU transformer_encoder__External_Benchmark_3__seed_101 | active_gpu=2 active_cpu=1 ram_now=9.3GiB
[4/208] TRAINED transformer_encoder__External_Benchmark_3__seed_100
          lane=GPU | train=190.20s | val=0.73s | worker_wall=213.96s | elapsed=00:05:32 | ETA_parallel_est=04:07:42 | active_after=2
[LAUNCH 7/208] GPU transformer_encoder__External_Benchmark_3__seed_102 | active_gpu=2 active_cpu=1 ram_now=10.3GiB
[5/208] TRAINED transformer_encoder__External_Benchmark_3__seed_101
          lane=GPU | train=115.06s | val=0.50s | worker_wall=138.38s | elapsed=00:05:42 | ETA_parallel_est=04:07:42 | active_after=2
[LAUNCH 8/208] GPU transformer_encoder__External_Benchmark_3__seed_103 | active_gpu=2 active_cpu=1 ram_now=9.6GiB
[6/208] TRAINED transformer_encoder__External_Benchmark_3__seed_102
          lane=GPU | train=124.98s | val=0.70s | worker_wall=148.59s | elapsed=00:08:01 | ETA_parallel_est=04:07:42 | active_after=2
[LAUNCH 9/208] GPU transformer_encoder__External_Benchmark_3__seed_104 | active_gpu=2 active_cpu=1 ram_now=9.3GiB
[7/208] TRAINED transformer_encoder__External_Benchmark_3__seed_103
          lane=GPU | train=135.61s | val=0.51s | worker_wall=159.29s | elapsed=00:08:22 | ETA_parallel_est=04:07:42 | active_after=2
[LAUNCH 10/208] GPU transformer_encoder__External_Benchmark_3__seed_105 | active_gpu=2 active_cpu=1 ram_now=9.2GiB
[8/208] TRAINED ampscannerv2__GenPept_Curated_2025__seed_105
          lane=CPU | train=513.74s | val=0.07s | worker_wall=528.61s | elapsed=00:08:49 | ETA_parallel_est=17:15:11 | active_after=2
[LAUNCH 11/208] CPU ampscannerv2__GenPept_Curated_2025__seed_106 | weight=1 | active_gpu=2 active_cpu=1 ram_now=8.6GiB
[9/208] TRAINED transformer_encoder__External_Benchmark_3__seed_104
          lane=GPU | train=145.55s | val=0.71s | worker_wall=168.90s | elapsed=00:10:50 | ETA_parallel_est=17:10:47 | active_after=2
[LAUNCH 12/208] GPU transformer_encoder__External_Benchmark_3__seed_106 | active_gpu=2 active_cpu=1 ram_now=10.3GiB
[10/208] TRAINED transformer_encoder__External_Benchmark_3__seed_105
          lane=GPU | train=130.51s | val=0.51s | worker_wall=153.07s | elapsed=00:10:55 | ETA_parallel_est=17:10:47 | active_after=2
[LAUNCH 13/208] GPU transformer_encoder__External_Benchmark_3__seed_107 | active_gpu=2 active_cpu=1 ram_now=10.2GiB
[11/208] TRAINED transformer_encoder__External_Benchmark_3__seed_107
          lane=GPU | train=112.86s | val=0.69s | worker_wall=135.10s | elapsed=00:13:10 | ETA_parallel_est=17:10:47 | active_after=2
[LAUNCH 14/208] GPU transformer_encoder__External_Benchmark_3__seed_108 | active_gpu=2 active_cpu=1 ram_now=10.3GiB
[12/208] TRAINED transformer_encoder__External_Benchmark_3__seed_106
          lane=GPU | train=118.37s | val=0.53s | worker_wall=140.47s | elapsed=00:13:11 | ETA_parallel_est=17:10:47 | active_after=2
[LAUNCH 15/208] GPU transformer_encoder__External_Benchmark_3__seed_109 | active_gpu=2 active_cpu=1 ram_now=10.5GiB
[13/208] TRAINED transformer_encoder__External_Benchmark_3__seed_108
          lane=GPU | train=123.60s | val=0.70s | worker_wall=146.83s | elapsed=00:15:37 | ETA_parallel_est=17:10:47 | active_after=2
[LAUNCH 16/208] CPU ampscannerv2__GenPept_Curated_2025__seed_107 | weight=1 | active_gpu=1 active_cpu=2 ram_now=10.3GiB
[14/208] TRAINED transformer_encoder__External_Benchmark_3__seed_109
          lane=GPU | train=129.18s | val=0.52s | worker_wall=151.41s | elapsed=00:15:43 | ETA_parallel_est=17:10:47 | active_after=2
[15/208] TRAINED ampscannerv2__GenPept_Curated_2025__seed_106
          lane=CPU | train=502.30s | val=0.03s | worker_wall=510.50s | elapsed=00:17:20 | ETA_parallel_est=16:53:08 | active_after=1
[LAUNCH 17/208] CPU ampscannerv2__GenPept_Curated_2025__seed_108 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.6GiB
[16/208] TRAINED ampscannerv2__GenPept_Curated_2025__seed_107
          lane=CPU | train=478.67s | val=0.03s | worker_wall=487.10s | elapsed=00:23:45 | ETA_parallel_est=16:31:13 | active_after=1
[LAUNCH 18/208] CPU ampscannerv2__GenPept_Curated_2025__seed_109 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.6GiB
[17/208] TRAINED ampscannerv2__GenPept_Curated_2025__seed_108
          lane=CPU | train=477.80s | val=0.03s | worker_wall=485.82s | elapsed=00:25:26 | ETA_parallel_est=16:04:21 | active_after=1
[LAUNCH 19/208] CPU ampscannerv2__External_Benchmark_1__seed_100 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.6GiB
[18/208] TRAINED ampscannerv2__External_Benchmark_1__seed_100
          lane=CPU | train=346.46s | val=0.03s | worker_wall=354.36s | elapsed=00:31:20 | ETA_parallel_est=15:37:39 | active_after=1
[LAUNCH 20/208] CPU ampscannerv2__External_Benchmark_1__seed_101 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.6GiB
[19/208] TRAINED ampscannerv2__GenPept_Curated_2025__seed_109
          lane=CPU | train=477.31s | val=0.03s | worker_wall=485.45s | elapsed=00:31:51 | ETA_parallel_est=15:32:22 | active_after=1
[LAUNCH 21/208] CPU ampscannerv2__External_Benchmark_1__seed_102 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.6GiB
[20/208] TRAINED ampscannerv2__External_Benchmark_1__seed_101
          lane=CPU | train=347.40s | val=0.02s | worker_wall=356.47s | elapsed=00:37:17 | ETA_parallel_est=15:27:06 | active_after=1
[LAUNCH 22/208] CPU ampscannerv2__External_Benchmark_1__seed_103 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.6GiB
[21/208] TRAINED ampscannerv2__External_Benchmark_1__seed_102
          lane=CPU | train=347.40s | val=0.02s | worker_wall=355.85s | elapsed=00:37:47 | ETA_parallel_est=15:22:43 | active_after=1
[LAUNCH 23/208] CPU ampscannerv2__External_Benchmark_1__seed_104 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.6GiB
[22/208] TRAINED ampscannerv2__External_Benchmark_1__seed_103
          lane=CPU | train=347.40s | val=0.02s | worker_wall=356.45s | elapsed=00:43:14 | ETA_parallel_est=15:18:19 | active_after=1
[LAUNCH 24/208] CPU ampscannerv2__External_Benchmark_1__seed_105 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.6GiB
[23/208] TRAINED ampscannerv2__External_Benchmark_1__seed_104
          lane=CPU | train=346.81s | val=0.03s | worker_wall=355.68s | elapsed=00:43:43 | ETA_parallel_est=13:12:49 | active_after=1
[LAUNCH 25/208] CPU ampscannerv2__External_Benchmark_1__seed_106 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.6GiB
[24/208] TRAINED ampscannerv2__External_Benchmark_1__seed_105
          lane=CPU | train=347.56s | val=0.03s | worker_wall=355.89s | elapsed=00:49:10 | ETA_parallel_est=11:08:23 | active_after=1
[LAUNCH 26/208] CPU ampscannerv2__External_Benchmark_1__seed_107 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.7GiB
[25/208] TRAINED ampscannerv2__External_Benchmark_1__seed_106
          lane=CPU | train=347.34s | val=0.02s | worker_wall=356.07s | elapsed=00:49:39 | ETA_parallel_est=11:05:23 | active_after=1
[LAUNCH 27/208] CPU ampscannerv2__External_Benchmark_1__seed_108 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.6GiB
[26/208] TRAINED ampscannerv2__External_Benchmark_1__seed_107
          lane=CPU | train=347.63s | val=0.03s | worker_wall=356.68s | elapsed=00:55:07 | ETA_parallel_est=11:02:26 | active_after=1
[LAUNCH 28/208] CPU ampscannerv2__External_Benchmark_1__seed_109 | weight=1 | active_gpu=0 active_cpu=2 ram_now=10.6GiB

CELL 32 v9 INTERRUPT RECEIVED - terminating active worker process groups safely...

KeyboardInterrupt:

In [45]:
# CELL 32 - FINAL ACCELERATOR / NO SCIENTIFIC-PROTOCOL CHANGE
# Purpose:
#   * Reuse every validated TRAINED run already committed by Cell 32 v9.
#   * Use GPU for every remaining controlled-deep run that is valid under the locked master TF2.21 route.
#   * Do NOT port legacy TF1.x published methods to TF2/GPU (that would change implementation contract).
#   * Accelerate legacy CPU-only published methods with model-aware multi-process parallelism.
#   * Keep per-run timing/resources from the exact v9 worker implementation.
#   * Never read source TEST or external target rows.
#
# IMPORTANT BEFORE RUNNING THIS CELL:
#   Interrupt the currently running v9 parent ONCE. Its KeyboardInterrupt handler terminates active workers safely.
#   Then run this cell. Do not run v9 and this accelerator at the same time.

from __future__ import annotations

import csv
import hashlib
import json
import math
import os
import signal
import subprocess
import sys
import tempfile
import time
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

# ============================================================================
# 0. LOCKED PATHS / EXACT TRAINER
# ============================================================================
PROJECT_ROOT = Path("/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026")
OUTPUT_ROOT = PROJECT_ROOT / "benchmark17_outputs"
AUDIT_DIR = OUTPUT_ROOT / "audit"
MANIFEST_DIR = OUTPUT_ROOT / "manifests"
WORK_ROOT = Path("/home/pc/genpept_benchmark17_work")
RUN_ROOT = WORK_ROOT / "runs" / "benchmark4_FINAL_v1"

FULL_PLAN_PATH = AUDIT_DIR / "benchmark17_FINAL_full_680_run_plan.csv"
LEDGER_PATH = AUDIT_DIR / "benchmark17_FINAL_run_ledger.csv"
V9_TRAINER = PROJECT_ROOT / "scripts_manual" / "Cell32_Benchmark17_Production_Trainer_v9.py"
EXPECTED_V9_SHA256 = "bc2276c2377e0c0730892c78412e307949547b4771b1eca10073c6ff125e5b6d"

LOG_DIR = WORK_ROOT / "worker_logs" / "benchmark4_FINAL_v1" / "cell32_final_accel"
LOG_DIR.mkdir(parents=True, exist_ok=True)
EVENTS_PATH = AUDIT_DIR / "benchmark17_CELL32_FINAL_ACCEL_events.csv"
SUMMARY_PATH = AUDIT_DIR / "benchmark17_CELL32_FINAL_ACCEL_summary.json"

# Existing scientific contracts remain untouched.
EXPECTED_SEEDS = list(range(100, 110))
CONTROLLED_GPU_MODELS = {"cnn1d", "bilstm", "bilstm_attention", "transformer_encoder"}
PUBLISHED_MODELS = {"ampep", "ampscannerv2", "ampgram", "ampir", "ampeppy", "ai4amp", "amplify"}

# Model-aware CPU caps. These DO NOT change training algorithms; they only control
# how many independent already-locked runs may execute at once.
MODEL_CPU_CAP = {
    "ampep": 6,            # sklearn RF; independent process/run
    "ampscannerv2": 6,    # locked helper uses intra/inter_op threads=1, GPU=0
    "ampgram": 1,         # heavy two-stage ranger; keep exclusive on this 11-GB host
    "ampir": 3,           # R/caret/SVM; moderate
    "ampeppy": 4,         # official RF path uses num_processes=1
    "ai4amp": 3,          # locked TF1.9 helper uses one CPU thread
    "amplify": 2,         # 5-fold TF1.12; heavier memory/CPU load
}

# 8 logical CPUs on the user's host: use at most 6 CPU workers when GPU is idle,
# and at most 4 while GPU workers are active. Live RAM guard can reduce this.
LOGICAL_CPUS = int(os.cpu_count() or 1)
CPU_MAX_IDLE_GPU = max(1, min(6, LOGICAL_CPUS - 2 if LOGICAL_CPUS >= 4 else LOGICAL_CPUS))
CPU_MAX_WITH_GPU = max(1, min(4, LOGICAL_CPUS - 2 if LOGICAL_CPUS >= 4 else 1))
GPU_MAX_WORKERS = 2
TOTAL_ACTIVE_CAP = max(2, min(6, LOGICAL_CPUS))
RAM_LAUNCH_FLOOR_GB = 3.0
POLL_SECONDS = 0.25

# ============================================================================
# 1. UTILITIES
# ============================================================================
def now_iso() -> str:
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def load_json(path: Path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def read_csv_exact(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, low_memory=False, keep_default_na=False, na_filter=False)


def atomic_write_csv(path: Path, df: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".tmp.", dir=str(path.parent))
    os.close(fd)
    tmp = Path(tmp_name)
    try:
        with open(tmp, "w", encoding="utf-8", newline="") as f:
            df.to_csv(f, index=False)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def atomic_write_json(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".tmp.", dir=str(path.parent))
    os.close(fd)
    tmp = Path(tmp_name)
    try:
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(obj, f, indent=2, sort_keys=True)
            f.write("\n")
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def mem_available_gb() -> float:
    try:
        with open("/proc/meminfo", "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("MemAvailable:"):
                    kb = float(line.split()[1])
                    return kb / (1024.0 * 1024.0)
    except Exception:
        pass
    return 0.0


def fmt_sec(seconds: float | None) -> str:
    if seconds is None or not math.isfinite(float(seconds)):
        return "UNKNOWN"
    s = max(0, int(round(float(seconds))))
    h, rem = divmod(s, 3600)
    m, sec = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{sec:02d}"


def trained_manifest_valid(row) -> bool:
    run_dir = Path(str(row.run_dir))
    manifest_path = run_dir / "run_manifest.json"
    if not manifest_path.is_file():
        return False
    try:
        manifest = load_json(manifest_path)
        if manifest.get("status") not in {"TRAINED", "EVALUATED", "COMPLETE"}:
            return False
        if manifest.get("run_id") != str(row.run_id):
            return False
        if manifest.get("model_id") != str(row.model_id):
            return False
        if manifest.get("source_dataset") != str(row.source_dataset):
            return False
        if int(manifest.get("seed")) != int(row.seed):
            return False
        if str(manifest.get("train_index_key")) != str(row.train_index_key):
            return False
        if str(manifest.get("validation_index_key")) != str(row.validation_index_key):
            return False
        if str(manifest.get("source_test_index_key")) != str(row.source_test_index_key):
            return False
        # Cell 32 scope must remain training+validation only.
        if (run_dir / "source_test_predictions.csv").exists():
            return False
        if (run_dir / "source_test_metrics.json").exists():
            return False
        if (run_dir / "external").exists():
            return False
        required = manifest.get("training_artifacts", {})
        required_names = {
            "config.json", "validation_predictions.csv", "validation_threshold.json",
            "history.csv", "resources.json",
        }
        if not required_names.issubset(set(required)):
            return False
        for relpath, entry in required.items():
            p = run_dir / relpath
            if not p.is_file():
                return False
            if int(p.stat().st_size) != int(entry["size_bytes"]):
                return False
            if sha256_file(p) != str(entry["sha256"]):
                return False
        cp_rel = str(manifest.get("checkpoint_relative_path", ""))
        if not cp_rel:
            return False
        cp = run_dir / cp_rel
        cp_entry = manifest.get("checkpoint_artifact", {})
        if not cp.is_file():
            return False
        if int(cp.stat().st_size) != int(cp_entry.get("size_bytes", -1)):
            return False
        if sha256_file(cp) != str(cp_entry.get("sha256", "")):
            return False
        return True
    except Exception:
        return False


def update_ledger(run_id: str, **updates) -> None:
    df = read_csv_exact(LEDGER_PATH)
    mask = df["run_id"].astype(str).eq(str(run_id))
    assert int(mask.sum()) == 1, run_id
    identity_cols = ["job_no", "run_id", "model_id", "model_group", "source_dataset", "seed"]
    before = df.loc[mask, identity_cols].copy().reset_index(drop=True)
    for k, v in updates.items():
        assert k in df.columns, k
        df.loc[mask, k] = v
    after = df.loc[mask, identity_cols].copy().reset_index(drop=True)
    pd.testing.assert_frame_equal(before, after, check_dtype=False)
    atomic_write_csv(LEDGER_PATH, df)
    verify = read_csv_exact(LEDGER_PATH)
    assert len(verify) == 680 and verify["run_id"].is_unique


def tail_text(path: Path, max_chars=8000) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")[-max_chars:]
    except Exception as e:
        return f"<log read failed: {e}>"

# ============================================================================
# 2. PREFLIGHT - EXACT TRAINER / PLAN / LEDGER
# ============================================================================
assert V9_TRAINER.is_file(), f"Missing exact v9 worker trainer: {V9_TRAINER}"
actual_trainer_sha = sha256_file(V9_TRAINER)
assert actual_trainer_sha == EXPECTED_V9_SHA256, (
    f"v9 worker trainer changed: {actual_trainer_sha} != {EXPECTED_V9_SHA256}"
)
assert FULL_PLAN_PATH.is_file() and LEDGER_PATH.is_file()

plan = read_csv_exact(FULL_PLAN_PATH)
ledger = read_csv_exact(LEDGER_PATH)
assert len(plan) == 680 and plan["run_id"].is_unique
assert len(ledger) == 680 and ledger["run_id"].is_unique
assert sorted(pd.to_numeric(plan["seed"], errors="raise").astype(int).unique().tolist()) == EXPECTED_SEEDS

# Refuse concurrent parent execution. A stale RUNNING row means the prior parent
# was not cleanly interrupted yet; do not race its worker or mutate shared ledger.
running_rows = ledger.loc[ledger["status"].astype(str).eq("RUNNING"), "run_id"].astype(str).tolist()
assert not running_rows, (
    "RUNNING rows still exist. Interrupt v9 cleanly and wait for its KeyboardInterrupt cleanup first: "
    + repr(running_rows[:10])
)

# Reconcile ledger from disk truth. Valid canonical runs are never retrained.
reconciled = 0
for row in plan.itertuples(index=False):
    valid = trained_manifest_valid(row)
    run_id = str(row.run_id)
    mask = ledger["run_id"].astype(str).eq(run_id)
    status = str(ledger.loc[mask, "status"].iloc[0])
    if valid and status not in {"TRAINED", "EVALUATED", "COMPLETE"}:
        update_ledger(
            run_id,
            status="TRAINED",
            finished_at=now_iso(),
            run_manifest=str(Path(str(row.run_dir)) / "run_manifest.json"),
            last_error="",
        )
        reconciled += 1

ledger = read_csv_exact(LEDGER_PATH)
trained_before = int(ledger["status"].astype(str).isin(["TRAINED", "EVALUATED", "COMPLETE"]).sum())

# ============================================================================
# 3. LEGACY GPU PROBE - INFORMATIONAL ONLY, NO PORTING
# ============================================================================
# The exact published TF1.x helpers in the locked v9 trainer deliberately use GPU=0.
# This probe documents whether each historical environment could even see the RTX 3060.
# Even if a legacy env reports a GPU, this accelerator does NOT silently alter helper code.
LEGACY_ENVS = {
    "ampscannerv2": Path.home() / "miniconda3/envs/genpept_ampscannerv2_orig/bin/python",
    "ai4amp": Path.home() / "miniconda3/envs/genpept_ai4amp_legacy/bin/python",
    "amplify": Path.home() / "miniconda3/envs/genpept_amplify_v1/bin/python",
}
LEGACY_EXPECTED_TF = {"ampscannerv2": "1.2.1", "ai4amp": "1.9.0", "amplify": "1.12.0"}
legacy_gpu_probe = {}
probe_code = r'''
import json, tensorflow as tf
try:
    from tensorflow.python.client import device_lib
    g=[d.name for d in device_lib.list_local_devices() if getattr(d,'device_type','')=='GPU']
except Exception as e:
    g=[]
print(json.dumps({'tf':tf.__version__,'gpus':g}))
'''
for model_id, py in LEGACY_ENVS.items():
    rec = {"python": str(py), "available": False, "tf": None, "gpus": [], "error": ""}
    if py.is_file():
        env = os.environ.copy()
        env["CUDA_VISIBLE_DEVICES"] = "0"
        try:
            r = subprocess.run(
                [str(py), "-c", probe_code], text=True, stdout=subprocess.PIPE,
                stderr=subprocess.PIPE, env=env, timeout=60, check=False,
            )
            if r.returncode == 0:
                last = [x for x in r.stdout.splitlines() if x.strip()][-1]
                obj = json.loads(last)
                rec["tf"] = obj.get("tf")
                rec["gpus"] = obj.get("gpus") or []
                rec["available"] = bool(rec["gpus"])
                assert str(rec["tf"]) == LEGACY_EXPECTED_TF[model_id]
            else:
                rec["error"] = (r.stderr or r.stdout)[-2000:]
        except Exception as e:
            rec["error"] = repr(e)
    else:
        rec["error"] = "python executable missing"
    legacy_gpu_probe[model_id] = rec

# ============================================================================
# 4. BUILD PENDING QUEUES IN LOCKED PLAN ORDER
# ============================================================================
ledger = read_csv_exact(LEDGER_PATH)
status_map = dict(zip(ledger["run_id"].astype(str), ledger["status"].astype(str)))

pending_rows = []
for row in plan.itertuples(index=False):
    if trained_manifest_valid(row):
        continue
    pending_rows.append(row)

# Exact scientific worker decides the actual training implementation.
def lane_for(row) -> str:
    return "GPU" if str(row.model_id) in CONTROLLED_GPU_MODELS else "CPU"

pending_gpu = [r for r in pending_rows if lane_for(r) == "GPU"]
pending_cpu = [r for r in pending_rows if lane_for(r) == "CPU"]

# ============================================================================
# 5. EXECUTOR STATE / LOGGING
# ============================================================================
active = {}  # pid -> record
completed = 0
failed = []
stop_launching = False
start_perf = time.perf_counter()
observed_wall = defaultdict(list)
event_rows = []

# Historical timing from existing resources.json improves ETA without touching test/external.
for row in plan.itertuples(index=False):
    if trained_manifest_valid(row):
        rp = Path(str(row.run_dir)) / "resources.json"
        try:
            obj = load_json(rp)
            sec = obj.get("training_seconds")
            if sec is not None and math.isfinite(float(sec)) and float(sec) > 0:
                observed_wall[str(row.model_id)].append(float(sec))
        except Exception:
            pass


def model_active_count(model_id: str) -> int:
    return sum(1 for rec in active.values() if str(rec["row"].model_id) == model_id)


def gpu_active_count() -> int:
    return sum(1 for rec in active.values() if rec["lane"] == "GPU")


def cpu_active_count() -> int:
    return sum(1 for rec in active.values() if rec["lane"] == "CPU")


def current_cpu_global_cap() -> int:
    # Reserve more host resources while master TF2 GPU workers are active.
    cap = CPU_MAX_WITH_GPU if gpu_active_count() > 0 else CPU_MAX_IDLE_GPU
    ram = mem_available_gb()
    if ram > 0:
        if ram < 4.0:
            cap = min(cap, 1)
        elif ram < 6.0:
            cap = min(cap, 2)
        elif ram < 8.0:
            cap = min(cap, 4)
    return max(1, cap)


def can_launch_cpu(row) -> bool:
    if len(active) >= TOTAL_ACTIVE_CAP:
        return False
    if cpu_active_count() >= current_cpu_global_cap():
        return False
    ram = mem_available_gb()
    if ram > 0 and ram < RAM_LAUNCH_FLOOR_GB:
        return False
    mid = str(row.model_id)
    cap = MODEL_CPU_CAP.get(mid, 1)
    if model_active_count(mid) >= cap:
        return False
    # AmpGram is exclusive among CPU workers on this low-RAM host.
    if mid == "ampgram" and cpu_active_count() > 0:
        return False
    if any(str(rec["row"].model_id) == "ampgram" for rec in active.values() if rec["lane"] == "CPU"):
        return False
    return True


def select_cpu_index():
    if not pending_cpu:
        return None
    # Preserve locked plan order. Do not jump past an exclusive/blocking earlier model.
    first = pending_cpu[0]
    if can_launch_cpu(first):
        return 0
    return None


def estimate_remaining_seconds() -> float:
    # Coarse throughput ETA. It is operational only, not a scientific result.
    def est(row):
        vals = observed_wall.get(str(row.model_id), [])
        if vals:
            s = sorted(vals)
            return float(s[len(s)//2])
        fallback = {
            "ampscannerv2": 480.0, "ampgram": 900.0, "ampir": 180.0,
            "ampeppy": 120.0, "ai4amp": 900.0, "amplify": 1800.0,
            "cnn1d": 90.0, "bilstm": 120.0, "bilstm_attention": 130.0,
            "transformer_encoder": 130.0, "ampep": 12.0,
        }
        return fallback.get(str(row.model_id), 300.0)
    rg = list(pending_gpu) + [rec["row"] for rec in active.values() if rec["lane"] == "GPU"]
    rc = list(pending_cpu) + [rec["row"] for rec in active.values() if rec["lane"] == "CPU"]
    gpu_sec = sum(est(r) for r in rg) / max(1, GPU_MAX_WORKERS)
    # Estimate CPU by model cap and global cap; take conservative workload/global-cap ratio.
    cpu_work = sum(est(r) for r in rc)
    cpu_sec = cpu_work / max(1, current_cpu_global_cap())
    return max(gpu_sec, cpu_sec)


def append_event(rec, state, rc, wall):
    row = rec["row"]
    event_rows.append({
        "timestamp": now_iso(), "run_id": str(row.run_id), "model_id": str(row.model_id),
        "source_dataset": str(row.source_dataset), "seed": int(row.seed),
        "lane": rec["lane"], "state": state, "returncode": int(rc),
        "worker_wall_seconds": float(wall), "log_path": str(rec["log_path"]),
    })
    atomic_write_csv(EVENTS_PATH, pd.DataFrame(event_rows))


def launch(row, lane):
    run_id = str(row.run_id)
    current = read_csv_exact(LEDGER_PATH)
    mask = current["run_id"].astype(str).eq(run_id)
    assert int(mask.sum()) == 1
    attempts = int(pd.to_numeric(current.loc[mask, "attempt_count"], errors="raise").iloc[0]) + 1
    update_ledger(
        run_id, status="RUNNING", attempt_count=attempts, started_at=now_iso(),
        finished_at="", run_manifest="", last_error="",
    )
    log_path = LOG_DIR / f"{run_id}__attempt_{attempts}.log"
    fh = open(log_path, "w", encoding="utf-8")
    env = os.environ.copy()
    env["GENPEPT_CELL32_WORKER_RUN_ID"] = run_id
    env["GENPEPT_CELL32_EXECUTOR_LANE"] = lane
    env["GENPEPT_CELL32_EXECUTOR_MODE"] = "FINAL_ACCEL_EXACT_V9_WORKER"
    env["GENPEPT_CELL32_PARALLEL_CONTEXT"] = "parallel_contention_logged_no_unqualified_runtime_claims"
    env["GENPEPT_CELL32_TRAINER_PATH"] = str(V9_TRAINER)
    env["GENPEPT_CELL32_TRAINER_SHA256"] = actual_trainer_sha
    proc = subprocess.Popen(
        [str(Path(sys.executable).resolve()), str(V9_TRAINER)],
        stdout=fh, stderr=subprocess.STDOUT, text=True, env=env, start_new_session=True,
    )
    active[proc.pid] = {
        "proc": proc, "row": row, "lane": lane, "log_path": log_path,
        "fh": fh, "start": time.perf_counter(), "attempt": attempts,
    }
    print(
        f"[LAUNCH] {lane:<3} {run_id} | active_gpu={gpu_active_count()} "
        f"active_cpu={cpu_active_count()} cpu_cap_now={current_cpu_global_cap()} "
        f"RAM={mem_available_gb():.1f}GiB",
        flush=True,
    )


def terminate_all(reason: str):
    for rec in list(active.values()):
        proc = rec["proc"]
        if proc.poll() is None:
            try:
                os.killpg(proc.pid, signal.SIGTERM)
            except Exception:
                try: proc.terminate()
                except Exception: pass
    deadline = time.time() + 10
    for rec in list(active.values()):
        proc = rec["proc"]
        while proc.poll() is None and time.time() < deadline:
            time.sleep(0.1)
        if proc.poll() is None:
            try: os.killpg(proc.pid, signal.SIGKILL)
            except Exception:
                try: proc.kill()
                except Exception: pass
        try: rec["fh"].close()
        except Exception: pass
        row = rec["row"]
        if trained_manifest_valid(row):
            update_ledger(str(row.run_id), status="TRAINED", finished_at=now_iso(),
                          run_manifest=str(Path(str(row.run_dir))/"run_manifest.json"), last_error="")
        else:
            update_ledger(str(row.run_id), status="FAILED", finished_at=now_iso(),
                          run_manifest="", last_error=reason[:2000])

# ============================================================================
# 6. REPORT PREFLIGHT
# ============================================================================
print("=" * 128)
print("CELL 32 - FINAL ACCELERATOR / EXACT v9 SCIENTIFIC WORKER")
print("=" * 128)
print("Exact worker trainer SHA  :", actual_trainer_sha)
print("Reconciled from disk       :", reconciled)
print("Already TRAINED            :", trained_before)
print("Pending total              :", len(pending_rows))
print("GPU-compatible pending     :", len(pending_gpu), f"(max {GPU_MAX_WORKERS})")
print("Published/CPU pending      :", len(pending_cpu))
print("Logical CPUs               :", LOGICAL_CPUS)
print("CPU cap GPU-active         :", CPU_MAX_WITH_GPU)
print("CPU cap GPU-idle           :", CPU_MAX_IDLE_GPU)
print("Total active cap           :", TOTAL_ACTIVE_CAP)
print("Available RAM start        :", f"{mem_available_gb():.1f} GiB")
print("Legacy TF1.x GPU probes    :")
for mid, rec in legacy_gpu_probe.items():
    print(f"  {mid:<13}: tf={rec['tf']} gpu_visible={rec['available']} devices={rec['gpus']}" +
          (f" error={rec['error'][:180]}" if rec['error'] else ""))
print("Legacy published GPU rule  : EXACT v9 helpers remain unchanged; no TF1->TF2 port")
print("Source TEST rows read      : FALSE")
print("External target rows read  : FALSE")
print("Scientific protocol        : UNCHANGED")
print("=" * 128)

# ============================================================================
# 7. RUN
# ============================================================================
try:
    while pending_gpu or pending_cpu or active:
        if not stop_launching:
            while (
                pending_gpu and gpu_active_count() < GPU_MAX_WORKERS and
                len(active) < TOTAL_ACTIVE_CAP and
                (mem_available_gb() <= 0 or mem_available_gb() >= RAM_LAUNCH_FLOOR_GB)
            ):
                launch(pending_gpu.pop(0), "GPU")

        if not stop_launching:
            while pending_cpu:
                idx = select_cpu_index()
                if idx is None:
                    break
                launch(pending_cpu.pop(idx), "CPU")

        finished = []
        for pid, rec in list(active.items()):
            rc = rec["proc"].poll()
            if rc is None:
                continue
            finished.append(pid)
            try:
                rec["fh"].flush(); rec["fh"].close()
            except Exception:
                pass
            row = rec["row"]
            wall = time.perf_counter() - rec["start"]
            valid = (rc == 0) and trained_manifest_valid(row)
            if valid:
                update_ledger(
                    str(row.run_id), status="TRAINED", finished_at=now_iso(),
                    run_manifest=str(Path(str(row.run_dir))/"run_manifest.json"), last_error="",
                )
                completed += 1
                observed_wall[str(row.model_id)].append(float(wall))
                append_event(rec, "TRAINED", rc, wall)
                elapsed = time.perf_counter() - start_perf
                eta = estimate_remaining_seconds()
                try:
                    rsrc = load_json(Path(str(row.run_dir))/"resources.json")
                    tr = rsrc.get("training_seconds")
                    va = rsrc.get("validation_seconds")
                except Exception:
                    tr = va = None
                train_txt = f"{float(tr):.2f}s" if tr is not None else "NA"
                val_txt = f"{float(va):.2f}s" if va is not None else "NA"
                print(
                    f"[{completed}/{len(pending_rows)}] TRAINED {row.run_id}\n"
                    f"          lane={rec['lane']} train={train_txt} val={val_txt} "
                    f"worker_wall={wall:.2f}s elapsed={fmt_sec(elapsed)} "
                    f"ETA_operational={fmt_sec(eta)} active={len(active)-1}",
                    flush=True,
                )
            else:
                log_tail = tail_text(rec["log_path"])
                update_ledger(
                    str(row.run_id), status="FAILED", finished_at=now_iso(), run_manifest="",
                    last_error=(f"FINAL_ACCEL worker rc={rc}; valid_manifest={trained_manifest_valid(row)}")[:2000],
                )
                append_event(rec, "FAILED", rc, wall)
                failed.append((str(row.run_id), int(rc), str(rec["log_path"]), log_tail))
                stop_launching = True
                print("-" * 128)
                print("FINAL ACCELERATOR WORKER FAILURE:", row.run_id)
                print("returncode:", rc)
                print("log:", rec["log_path"])
                print(log_tail)
                print("New launches stopped: TRUE")
                print("-" * 128)

        for pid in finished:
            active.pop(pid, None)

        if stop_launching and not active:
            break
        if active:
            time.sleep(POLL_SECONDS)
        elif (pending_gpu or pending_cpu) and not stop_launching:
            time.sleep(0.5)

except KeyboardInterrupt:
    print("\nFINAL ACCELERATOR INTERRUPT - terminating active worker groups safely...", flush=True)
    terminate_all("KeyboardInterrupt in FINAL_ACCEL parent; exact retry required")
    atomic_write_json(SUMMARY_PATH, {
        "status": "INTERRUPTED", "created_at": now_iso(),
        "trainer_sha256": actual_trainer_sha, "trained_before": trained_before,
        "completed_this_invocation": completed, "failed": [x[0] for x in failed],
        "legacy_gpu_probe": legacy_gpu_probe,
        "scientific_protocol_changed": False,
        "source_test_read": False, "external_target_read": False,
    })
    raise

# ============================================================================
# 8. FINAL VERIFY / SUMMARY
# ============================================================================
final_ledger = read_csv_exact(LEDGER_PATH)
final_counts = final_ledger["status"].astype(str).value_counts().to_dict()
trained_total = int(final_ledger["status"].astype(str).isin(["TRAINED", "EVALUATED", "COMPLETE"]).sum())
failed_total = int(final_ledger["status"].astype(str).eq("FAILED").sum())
summary = {
    "schema_version": "1.0",
    "created_at": now_iso(),
    "status": "PASS" if trained_total == 680 and failed_total == 0 else ("FAILED" if failed else "CHECKPOINT"),
    "exact_worker_trainer": str(V9_TRAINER),
    "exact_worker_trainer_sha256": actual_trainer_sha,
    "scientific_protocol_changed": False,
    "trained_before": trained_before,
    "completed_this_invocation": completed,
    "trained_total": trained_total,
    "failed_total": failed_total,
    "ledger_counts": final_counts,
    "legacy_gpu_probe": legacy_gpu_probe,
    "cpu_caps": {"with_gpu": CPU_MAX_WITH_GPU, "gpu_idle": CPU_MAX_IDLE_GPU, "per_model": MODEL_CPU_CAP},
    "gpu_max_workers": GPU_MAX_WORKERS,
    "total_active_cap": TOTAL_ACTIVE_CAP,
    "elapsed_seconds": float(time.perf_counter() - start_perf),
    "source_test_read": False,
    "external_target_read": False,
    "events_path": str(EVENTS_PATH),
}
atomic_write_json(SUMMARY_PATH, summary)

print("=" * 128)
if trained_total == 680 and failed_total == 0:
    print("CELL 32 PASS - ALL 680 LOCKED SOURCE TRAININGS COMPLETED")
elif failed:
    print("CELL 32 FINAL ACCELERATOR - FAILURE CHECKPOINT")
else:
    print("CELL 32 FINAL ACCELERATOR - CHECKPOINT")
print("Ledger status             :", final_counts)
print("TRAINED total             :", trained_total, "/ 680")
print("FAILED total              :", failed_total)
print("Elapsed this invocation   :", fmt_sec(time.perf_counter() - start_perf))
print("Source TEST rows read     : FALSE")
print("External target rows read : FALSE")
print("Protocol-2 evaluation     : FALSE")
print("Scientific metrics shown  : FALSE")
print("Summary                   :", SUMMARY_PATH)
print("=" * 128)

if failed:
    run_id, rc, log_path, _ = failed[0]
    raise AssertionError(f"FINAL_ACCEL worker failed: {run_id}; rc={rc}; log={log_path}")

================================================================================================================================
CELL 32 - FINAL ACCELERATOR / EXACT v9 SCIENTIFIC WORKER
================================================================================================================================
Exact worker trainer SHA  : bc2276c2377e0c0730892c78412e307949547b4771b1eca10073c6ff125e5b6d
Reconciled from disk       : 0
Already TRAINED            : 498
Pending total              : 182
GPU-compatible pending     : 0 (max 2)
Published/CPU pending      : 182
Logical CPUs               : 8
CPU cap GPU-active         : 4
CPU cap GPU-idle           : 6
Total active cap           : 6
Available RAM start        : 11.3 GiB
Legacy TF1.x GPU probes    :
  ampscannerv2 : tf=1.2.1 gpu_visible=False devices=[]
  ai4amp       : tf=1.9.0 gpu_visible=False devices=[]
  amplify      : tf=1.12.0 gpu_visible=False devices=[]
Legacy published GPU rule  : EXACT v9 helpers remain unchanged; no TF1->TF2 port
Source TEST rows read      : FALSE
External target rows read  : FALSE
Scientific protocol        : UNCHANGED
================================================================================================================================
[LAUNCH] CPU ampscannerv2__External_Benchmark_1__seed_108 | active_gpu=0 active_cpu=1 cpu_cap_now=6 RAM=11.3GiB
[LAUNCH] CPU ampscannerv2__External_Benchmark_1__seed_109 | active_gpu=0 active_cpu=2 cpu_cap_now=6 RAM=11.3GiB
[LAUNCH] CPU ampscannerv2__AMPlify_balanced__seed_100 | active_gpu=0 active_cpu=3 cpu_cap_now=6 RAM=11.3GiB
[LAUNCH] CPU ampscannerv2__AMPlify_balanced__seed_101 | active_gpu=0 active_cpu=4 cpu_cap_now=6 RAM=11.3GiB
[LAUNCH] CPU ampscannerv2__AMPlify_balanced__seed_102 | active_gpu=0 active_cpu=5 cpu_cap_now=6 RAM=11.3GiB
[LAUNCH] CPU ampscannerv2__AMPlify_balanced__seed_103 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=11.3GiB
[1/182] TRAINED ampscannerv2__AMPlify_balanced__seed_100
          lane=CPU train=427.08s val=0.03s worker_wall=444.32s elapsed=00:07:37 ETA_operational=07:29:10 active=5
[LAUNCH] CPU ampscannerv2__AMPlify_balanced__seed_104 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=10.1GiB
[2/182] TRAINED ampscannerv2__AMPlify_balanced__seed_101
          lane=CPU train=427.45s val=0.05s worker_wall=444.64s elapsed=00:07:37 ETA_operational=07:27:51 active=5
[LAUNCH] CPU ampscannerv2__AMPlify_balanced__seed_105 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=10.5GiB
[3/182] TRAINED ampscannerv2__AMPlify_balanced__seed_103
          lane=CPU train=427.67s val=0.03s worker_wall=444.87s elapsed=00:07:37 ETA_operational=07:24:43 active=5
[LAUNCH] CPU ampscannerv2__AMPlify_balanced__seed_106 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=10.4GiB
[4/182] TRAINED ampscannerv2__External_Benchmark_1__seed_108
          lane=CPU train=427.58s val=0.03s worker_wall=445.76s elapsed=00:07:38 ETA_operational=07:23:32 active=5
[LAUNCH] CPU ampscannerv2__AMPlify_balanced__seed_107 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=10.5GiB
[5/182] TRAINED ampscannerv2__AMPlify_balanced__seed_102
          lane=CPU train=428.64s val=0.04s worker_wall=446.45s elapsed=00:07:39 ETA_operational=07:22:17 active=5
[LAUNCH] CPU ampscannerv2__AMPlify_balanced__seed_108 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=10.5GiB
[6/182] TRAINED ampscannerv2__External_Benchmark_1__seed_109
          lane=CPU train=428.34s val=0.03s worker_wall=447.72s elapsed=00:07:40 ETA_operational=07:21:05 active=5
[LAUNCH] CPU ampscannerv2__AMPlify_balanced__seed_109 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=10.3GiB
[7/182] TRAINED ampscannerv2__AMPlify_balanced__seed_104
          lane=CPU train=424.49s val=0.04s worker_wall=435.43s elapsed=00:14:52 ETA_operational=07:19:49 active=5
[8/182] TRAINED ampscannerv2__AMPlify_balanced__seed_105
          lane=CPU train=424.54s val=0.04s worker_wall=435.12s elapsed=00:14:52 ETA_operational=07:19:49 active=5
[LAUNCH] CPU ampscannerv2__External_Benchmark_3__seed_100 | active_gpu=0 active_cpu=5 cpu_cap_now=6 RAM=10.9GiB
[LAUNCH] CPU ampscannerv2__External_Benchmark_3__seed_101 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=10.9GiB
[9/182] TRAINED ampscannerv2__AMPlify_balanced__seed_106
          lane=CPU train=424.43s val=0.04s worker_wall=435.13s elapsed=00:14:53 ETA_operational=07:17:18 active=5
[10/182] TRAINED ampscannerv2__AMPlify_balanced__seed_107
          lane=CPU train=424.23s val=0.04s worker_wall=434.55s elapsed=00:14:53 ETA_operational=07:17:18 active=5
[LAUNCH] CPU ampscannerv2__External_Benchmark_3__seed_102 | active_gpu=0 active_cpu=5 cpu_cap_now=6 RAM=10.8GiB
[LAUNCH] CPU ampscannerv2__External_Benchmark_3__seed_103 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=11.0GiB
[11/182] TRAINED ampscannerv2__AMPlify_balanced__seed_108
          lane=CPU train=424.12s val=0.03s worker_wall=434.12s elapsed=00:14:53 ETA_operational=07:14:49 active=5
[LAUNCH] CPU ampscannerv2__External_Benchmark_3__seed_104 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=10.9GiB
[12/182] TRAINED ampscannerv2__AMPlify_balanced__seed_109
          lane=CPU train=425.07s val=0.03s worker_wall=435.15s elapsed=00:14:56 ETA_operational=07:13:35 active=5
[LAUNCH] CPU ampscannerv2__External_Benchmark_3__seed_105 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=10.2GiB
[13/182] TRAINED ampscannerv2__External_Benchmark_3__seed_104
          lane=CPU train=750.74s val=0.04s worker_wall=767.91s elapsed=00:27:42 ETA_operational=07:12:21 active=5
[LAUNCH] CPU ampscannerv2__External_Benchmark_3__seed_106 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=9.8GiB
[14/182] TRAINED ampscannerv2__External_Benchmark_3__seed_102
          lane=CPU train=750.86s val=0.05s worker_wall=768.97s elapsed=00:27:42 ETA_operational=07:11:07 active=5
[LAUNCH] CPU ampscannerv2__External_Benchmark_3__seed_107 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=10.4GiB
[15/182] TRAINED ampscannerv2__External_Benchmark_3__seed_100
          lane=CPU train=751.49s val=0.05s worker_wall=769.81s elapsed=00:27:43 ETA_operational=07:09:53 active=5
[LAUNCH] CPU ampscannerv2__External_Benchmark_3__seed_108 | active_gpu=0 active_cpu=6 cpu_cap_now=6 RAM=10.7GiB
[16/182] TRAINED ampscannerv2__External_Benchmark_3__seed_101
          lane=CPU train=751.65s val=0.06s worker_wall=770.11s elapsed=00:27:43 ETA_operational=07:08:40 active=5
[17/182] TRAINED ampscannerv2__External_Benchmark_3__seed_103
          lane=CPU train=751.62s val=0.05s worker_wall=769.65s elapsed=00:27:43 ETA_operational=07:08:40 active=5
[LAUNCH] CPU ampscannerv2__External_Benchmark_3__seed_109 | active_gpu=0 active_cpu=5 cpu_cap_now=6 RAM=10.9GiB
[18/182] TRAINED ampscannerv2__External_Benchmark_3__seed_105
          lane=CPU train=750.54s val=0.04s worker_wall=768.52s elapsed=00:27:44 ETA_operational=07:06:12 active=4
[19/182] TRAINED ampscannerv2__External_Benchmark_3__seed_108
          lane=CPU train=671.53s val=0.04s worker_wall=687.32s elapsed=00:39:10 ETA_operational=07:04:58 active=3
[20/182] TRAINED ampscannerv2__External_Benchmark_3__seed_106
          lane=CPU train=672.39s val=0.04s worker_wall=688.82s elapsed=00:39:11 ETA_operational=07:03:44 active=2
[21/182] TRAINED ampscannerv2__External_Benchmark_3__seed_107
          lane=CPU train=672.57s val=0.05s worker_wall=688.74s elapsed=00:39:11 ETA_operational=07:02:29 active=1
[22/182] TRAINED ampscannerv2__External_Benchmark_3__seed_109
          lane=CPU train=672.44s val=0.05s worker_wall=688.30s elapsed=00:39:12 ETA_operational=07:01:20 active=0
[LAUNCH] CPU ampgram__GenPept_Curated_2025__seed_100 | active_gpu=0 active_cpu=1 cpu_cap_now=6 RAM=11.5GiB

FINAL ACCELERATOR INTERRUPT - terminating active worker groups safely...

KeyboardInterrupt

# Tông hop

In [46]:
# ============================================================
# CELL 32A - STOP-TRAINING AUDIT / 7-MODEL SCOPE CHECK
# PURPOSE:
#   * READ-ONLY audit of all 680 planned training runs
#   * Count ONLY canonical on-disk TRAINED bundles that pass the
#     same artifact/hash validation used by the v9 trainer
#   * Identify models complete at 4 datasets x 10 seeds = 40/40
#   * DO NOT train, evaluate TEST, evaluate external targets,
#     change ledger, or choose models by performance
# ============================================================

from pathlib import Path
import json
import hashlib
import os
import tempfile
import pandas as pd

PROJECT_ROOT = Path('/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026')
OUTPUT_ROOT = PROJECT_ROOT / 'benchmark17_outputs'
AUDIT_DIR = OUTPUT_ROOT / 'audit'
FULL_RUN_PLAN_PATH = AUDIT_DIR / 'benchmark17_FINAL_full_680_run_plan.csv'
RUN_LEDGER_PATH = AUDIT_DIR / 'benchmark17_FINAL_run_ledger.csv'

OUT_MODEL = AUDIT_DIR / 'STOP_SCOPE_model_completion_audit.csv'
OUT_DATASET = AUDIT_DIR / 'STOP_SCOPE_model_dataset_completion_audit.csv'
OUT_MISSING = AUDIT_DIR / 'STOP_SCOPE_incomplete_or_invalid_runs.csv'
OUT_SUMMARY = AUDIT_DIR / 'STOP_SCOPE_summary.json'

MAIN_TARGET_MODEL_COUNT = 7


def read_csv_exact(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, low_memory=False, keep_default_na=False, na_filter=False)


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def load_json(path: Path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def atomic_write_csv(path: Path, df: pd.DataFrame):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    try:
        with os.fdopen(fd, 'w', encoding='utf-8', newline='') as f:
            df.to_csv(f, index=False)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def atomic_write_json(path: Path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    try:
        with os.fdopen(fd, 'w', encoding='utf-8') as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)
            f.write('\n')
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def validate_trained_bundle(row):
    """Return (valid: bool, reason: str, manifest_path: str).

    This mirrors the scientific bundle checks used by v9. It deliberately
    rejects any Cell-32 bundle containing source-test or external evaluation.
    """
    run_dir = Path(str(row.run_dir))
    manifest_path = run_dir / 'run_manifest.json'
    if not manifest_path.is_file():
        return False, 'missing_run_manifest', str(manifest_path)

    try:
        manifest = load_json(manifest_path)
    except Exception as e:
        return False, f'manifest_unreadable:{type(e).__name__}', str(manifest_path)

    try:
        if manifest.get('status') not in {'TRAINED', 'EVALUATED', 'COMPLETE'}:
            return False, 'manifest_status_not_trained', str(manifest_path)
        if manifest.get('run_id') != str(row.run_id):
            return False, 'run_id_mismatch', str(manifest_path)
        if manifest.get('model_id') != str(row.model_id):
            return False, 'model_id_mismatch', str(manifest_path)
        if manifest.get('source_dataset') != str(row.source_dataset):
            return False, 'source_dataset_mismatch', str(manifest_path)
        if int(manifest.get('seed')) != int(row.seed):
            return False, 'seed_mismatch', str(manifest_path)
        if str(manifest.get('train_index_key')) != str(row.train_index_key):
            return False, 'train_index_key_mismatch', str(manifest_path)
        if str(manifest.get('validation_index_key')) != str(row.validation_index_key):
            return False, 'validation_index_key_mismatch', str(manifest_path)
        if str(manifest.get('source_test_index_key')) != str(row.source_test_index_key):
            return False, 'source_test_index_key_mismatch', str(manifest_path)

        if manifest.get('cell32_source_test_read') is not False:
            return False, 'cell32_source_test_read_not_false', str(manifest_path)
        if manifest.get('cell32_external_target_read') is not False:
            return False, 'cell32_external_target_read_not_false', str(manifest_path)

        if (run_dir / 'source_test_predictions.csv').exists():
            return False, 'unexpected_source_test_predictions', str(manifest_path)
        if (run_dir / 'source_test_metrics.json').exists():
            return False, 'unexpected_source_test_metrics', str(manifest_path)
        if (run_dir / 'external').exists():
            return False, 'unexpected_external_directory', str(manifest_path)

        required = manifest.get('training_artifacts', {})
        required_names = {
            'config.json',
            'validation_predictions.csv',
            'validation_threshold.json',
            'history.csv',
            'resources.json',
        }
        if not required_names.issubset(set(required)):
            return False, 'missing_required_training_artifact_entry', str(manifest_path)

        for relpath, entry in required.items():
            p = run_dir / relpath
            if not p.is_file():
                return False, f'missing_artifact:{relpath}', str(manifest_path)
            if int(p.stat().st_size) != int(entry['size_bytes']):
                return False, f'artifact_size_mismatch:{relpath}', str(manifest_path)
            if sha256_file(p) != str(entry['sha256']):
                return False, f'artifact_sha256_mismatch:{relpath}', str(manifest_path)

        checkpoint_rel = str(manifest.get('checkpoint_relative_path', ''))
        if not checkpoint_rel:
            return False, 'missing_checkpoint_relative_path', str(manifest_path)
        checkpoint = run_dir / checkpoint_rel
        if not checkpoint.is_file():
            return False, 'missing_checkpoint', str(manifest_path)
        cp_entry = manifest.get('checkpoint_artifact', {})
        if int(checkpoint.stat().st_size) != int(cp_entry.get('size_bytes', -1)):
            return False, 'checkpoint_size_mismatch', str(manifest_path)
        if sha256_file(checkpoint) != str(cp_entry.get('sha256', '')):
            return False, 'checkpoint_sha256_mismatch', str(manifest_path)

        return True, 'VALID', str(manifest_path)
    except Exception as e:
        return False, f'validation_exception:{type(e).__name__}:{e}', str(manifest_path)


# -------------------------
# READ + HARD VALIDATION
# -------------------------
assert FULL_RUN_PLAN_PATH.is_file(), FULL_RUN_PLAN_PATH
assert RUN_LEDGER_PATH.is_file(), RUN_LEDGER_PATH

plan = read_csv_exact(FULL_RUN_PLAN_PATH)
ledger = read_csv_exact(RUN_LEDGER_PATH)

assert len(plan) == 680, f'Expected 680 planned runs, found {len(plan)}'
assert len(ledger) == 680, f'Expected 680 ledger rows, found {len(ledger)}'
assert plan['run_id'].is_unique
assert ledger['run_id'].is_unique
assert set(plan['run_id']) == set(ledger['run_id'])

identity_cols = ['run_id', 'model_id', 'model_group', 'source_dataset', 'seed']
merged_identity = plan[identity_cols].merge(
    ledger[identity_cols], on='run_id', suffixes=('_plan', '_ledger'), validate='one_to_one'
)
for col in ['model_id', 'model_group', 'source_dataset', 'seed']:
    a = merged_identity[f'{col}_plan'].astype(str)
    b = merged_identity[f'{col}_ledger'].astype(str)
    assert a.equals(b), f'Ledger identity mismatch in {col}'

ledger_status = ledger.set_index('run_id')['status'].astype(str).to_dict()

# Preserve plan order for reporting.
model_order = list(dict.fromkeys(plan['model_id'].astype(str).tolist()))
dataset_order = list(dict.fromkeys(plan['source_dataset'].astype(str).tolist()))
seed_order = sorted(plan['seed'].astype(int).unique().tolist())

print('=' * 128)
print('CELL 32A - STOP-TRAINING AUDIT / 7-MODEL SCOPE CHECK')
print('=' * 128)
print('Plan rows                 :', len(plan))
print('Ledger rows               :', len(ledger))
print('Models in old 17-model plan:', len(model_order))
print('Source datasets in plan   :', len(dataset_order), dataset_order)
print('Seeds in plan             :', seed_order)
print('Main target model count   :', MAIN_TARGET_MODEL_COUNT)
print('Training launched by cell : FALSE')
print('TEST rows read            : FALSE')
print('External target rows read : FALSE')
print('-' * 128)

# -------------------------
# DISK-FIRST BUNDLE AUDIT
# -------------------------
records = []
for row in plan.itertuples(index=False):
    valid, reason, manifest_path = validate_trained_bundle(row)
    records.append({
        'job_no': int(row.job_no),
        'run_id': str(row.run_id),
        'model_id': str(row.model_id),
        'model_group': str(row.model_group),
        'source_dataset': str(row.source_dataset),
        'seed': int(row.seed),
        'ledger_status': ledger_status.get(str(row.run_id), ''),
        'valid_trained_bundle': bool(valid),
        'audit_reason': reason,
        'run_manifest': manifest_path,
    })

audit = pd.DataFrame(records)
valid_total = int(audit['valid_trained_bundle'].sum())

# -------------------------
# DATASET-LEVEL COMPLETION
# -------------------------
dataset_rows = []
for model_id in model_order:
    for dataset in dataset_order:
        x = audit[(audit.model_id == model_id) & (audit.source_dataset == dataset)]
        expected = len(x)
        valid = int(x['valid_trained_bundle'].sum())
        valid_seeds = sorted(x.loc[x.valid_trained_bundle, 'seed'].astype(int).tolist())
        missing_seeds = sorted(x.loc[~x.valid_trained_bundle, 'seed'].astype(int).tolist())
        dataset_rows.append({
            'model_id': model_id,
            'source_dataset': dataset,
            'expected_runs': expected,
            'valid_runs': valid,
            'complete': bool(expected > 0 and valid == expected),
            'valid_seeds': ','.join(map(str, valid_seeds)),
            'missing_or_invalid_seeds': ','.join(map(str, missing_seeds)),
        })

dataset_summary = pd.DataFrame(dataset_rows)

# -------------------------
# MODEL-LEVEL COMPLETION
# -------------------------
model_rows = []
for model_id in model_order:
    x = audit[audit.model_id == model_id]
    expected = len(x)
    valid = int(x['valid_trained_bundle'].sum())
    ds = dataset_summary[dataset_summary.model_id == model_id]
    complete_datasets = int(ds['complete'].sum())
    model_rows.append({
        'model_id': model_id,
        'model_group': str(x.iloc[0]['model_group']) if len(x) else '',
        'expected_runs': expected,
        'valid_runs': valid,
        'missing_or_invalid_runs': expected - valid,
        'complete_datasets': complete_datasets,
        'expected_datasets': len(ds),
        'COMPLETE_40_OF_40': bool(expected == 40 and valid == 40 and complete_datasets == 4),
    })

model_summary = pd.DataFrame(model_rows)
complete_models = model_summary.loc[model_summary.COMPLETE_40_OF_40, 'model_id'].tolist()
incomplete_models = model_summary.loc[~model_summary.COMPLETE_40_OF_40, 'model_id'].tolist()
missing = audit.loc[~audit.valid_trained_bundle].copy()

print(model_summary.to_string(index=False))
print('-' * 128)
print(f'VALID canonical TRAINED bundles : {valid_total} / 680')
print(f'Complete models (40/40)         : {len(complete_models)}')
print('Complete model IDs             :', complete_models if complete_models else 'NONE')
print(f'Incomplete models               : {len(incomplete_models)}')
print('Incomplete model IDs           :', incomplete_models if incomplete_models else 'NONE')
print('-' * 128)

if len(complete_models) >= MAIN_TARGET_MODEL_COUNT:
    print('MAIN 7-MODEL COVERAGE          : ENOUGH COMPLETE MODELS AVAILABLE')
    print('NEXT                           : CHOOSE EXACTLY 7 BY PREDECLARED METHODOLOGICAL COVERAGE, NOT PERFORMANCE')
else:
    print('MAIN 7-MODEL COVERAGE          : NOT ENOUGH COMPLETE MODELS')
    print('NEXT                           : DO NOT AGGREGATE YET; AUDIT WHICH REQUIRED MODEL FAMILIES ARE MISSING')

# -------------------------
# SAVE AUDIT ONLY - NO STATE MUTATION
# -------------------------
atomic_write_csv(OUT_MODEL, model_summary)
atomic_write_csv(OUT_DATASET, dataset_summary)
atomic_write_csv(OUT_MISSING, missing)
summary_payload = {
    'purpose': 'stop-training scope audit only',
    'main_target_model_count': MAIN_TARGET_MODEL_COUNT,
    'planned_runs_old_17_model_protocol': 680,
    'valid_trained_bundles': valid_total,
    'complete_40_of_40_model_count': len(complete_models),
    'complete_40_of_40_models': complete_models,
    'incomplete_models': incomplete_models,
    'training_launched': False,
    'source_test_rows_read': False,
    'external_target_rows_read': False,
    'selection_by_performance_permitted': False,
}
atomic_write_json(OUT_SUMMARY, summary_payload)

print('-' * 128)
print('Audit model CSV             :', OUT_MODEL)
print('Audit model-dataset CSV     :', OUT_DATASET)
print('Audit missing/invalid CSV   :', OUT_MISSING)
print('Audit summary JSON          :', OUT_SUMMARY)
print('Model audit SHA256          :', sha256_file(OUT_MODEL))
print('Summary SHA256              :', sha256_file(OUT_SUMMARY))
print('=' * 128)
print('CELL 32A PASS - READ-ONLY TRAINING-SCOPE AUDIT COMPLETE')
print('Benchmark training          : FALSE')
print('Source TEST used            : FALSE')
print('External target used        : FALSE')
print('=' * 128)

================================================================================================================================
CELL 32A - STOP-TRAINING AUDIT / 7-MODEL SCOPE CHECK
================================================================================================================================
Plan rows                 : 680
Ledger rows               : 680
Models in old 17-model plan: 17
Source datasets in plan   : 4 ['GenPept_Curated_2025', 'External_Benchmark_1', 'AMPlify_balanced', 'External_Benchmark_3']
Seeds in plan             : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
Main target model count   : 7
Training launched by cell : FALSE
TEST rows read            : FALSE
External target rows read : FALSE
--------------------------------------------------------------------------------------------------------------------------------
              model_id          model_group  expected_runs  valid_runs  missing_or_invalid_runs  complete_datasets  expected_datasets  COMPLETE_40_OF_40
   logistic_regression  controlled_baseline             40          40                        0                  4                  4               True
 linear_svm_calibrated  controlled_baseline             40          40                        0                  4                  4               True
         random_forest  controlled_baseline             40          40                        0                  4                  4               True
           extra_trees  controlled_baseline             40          40                        0                  4                  4               True
hist_gradient_boosting  controlled_baseline             40          40                        0                  4                  4               True
              lightgbm  controlled_baseline             40          40                        0                  4                  4               True
                 cnn1d  controlled_baseline             40          40                        0                  4                  4               True
                bilstm  controlled_baseline             40          40                        0                  4                  4               True
      bilstm_attention  controlled_baseline             40          40                        0                  4                  4               True
   transformer_encoder  controlled_baseline             40          40                        0                  4                  4               True
                 ampep published_amp_method             40          40                        0                  4                  4               True
          ampscannerv2 published_amp_method             40          40                        0                  4                  4               True
               ampgram published_amp_method             40           0                       40                  0                  4              False
                 ampir published_amp_method             40           0                       40                  0                  4              False
               ampeppy published_amp_method             40          40                        0                  4                  4               True
                ai4amp published_amp_method             40           0                       40                  0                  4              False
               amplify published_amp_method             40           0                       40                  0                  4              False
--------------------------------------------------------------------------------------------------------------------------------
VALID canonical TRAINED bundles : 520 / 680
Complete models (40/40)         : 13
Complete model IDs             : ['logistic_regression', 'linear_svm_calibrated', 'random_forest', 'extra_trees', 'hist_gradient_boosting', 'lightgbm', 'cnn1d', 'bilstm', 'bilstm_attention', 'transformer_encoder', 'ampep', 'ampscannerv2', 'ampeppy']
Incomplete models               : 4
Incomplete model IDs           : ['ampgram', 'ampir', 'ai4amp', 'amplify']
--------------------------------------------------------------------------------------------------------------------------------
MAIN 7-MODEL COVERAGE          : ENOUGH COMPLETE MODELS AVAILABLE
NEXT                           : CHOOSE EXACTLY 7 BY PREDECLARED METHODOLOGICAL COVERAGE, NOT PERFORMANCE
--------------------------------------------------------------------------------------------------------------------------------
Audit model CSV             : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/STOP_SCOPE_model_completion_audit.csv
Audit model-dataset CSV     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/STOP_SCOPE_model_dataset_completion_audit.csv
Audit missing/invalid CSV   : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/STOP_SCOPE_incomplete_or_invalid_runs.csv
Audit summary JSON          : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/STOP_SCOPE_summary.json
Model audit SHA256          : 5d1f81c3af90cab17ce2599187d63bc4c297adfd296f19d7264a31b3e013d1aa
Summary SHA256              : ce24299c593c8d0ab767c4c779810ff9676e5c365b3fbb001671ed08d11e9713
================================================================================================================================
CELL 32A PASS - READ-ONLY TRAINING-SCOPE AUDIT COMPLETE
Benchmark training          : FALSE
Source TEST used            : FALSE
External target used        : FALSE
================================================================================================================================

In [47]:
# ============================================================
# CELL 32B - FINAL 13-MODEL SCOPE LOCK / NO TRAINING / NO TEST
# ============================================================
# PURPOSE
# -------
# Freeze the benchmark scope AFTER the read-only Cell 32A audit:
#   * include EVERY model with a complete 40/40 canonical training bundle
#   * exclude ONLY models with 0/40 valid canonical training bundles
#   * do NOT select by performance
#   * do NOT train anything
#   * do NOT read source TEST rows
#   * do NOT read Protocol-2 target rows
#
# FINAL SCOPE DECISION
# --------------------
# 13 models x 4 source datasets x 10 seeds = 520 training bundles.
# The original 17-model execution plan remains preserved as historical audit
# evidence; this cell creates a NEW immutable 13-model scope lock for all
# downstream evaluation/aggregation/table/figure cells.
#
# DOWNSTREAM LOCKED EVALUATION COUNTS
# -----------------------------------
# Protocol 1 / within-dataset source TEST:
#   13 models x 4 sources x 10 seeds = 520 seed-level evaluations
# Protocol 2 / cross-dataset:
#   13 models x 4 sources x 3 targets x 10 seeds = 1,560 evaluations
# No additional training is permitted/required.
# ============================================================

from pathlib import Path
from datetime import datetime
import hashlib
import json
import os
import tempfile

import pandas as pd


# ============================================================
# 1. PATHS
# ============================================================

PROJECT_ROOT = Path('/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026')
OUTPUT_ROOT = PROJECT_ROOT / 'benchmark17_outputs'
AUDIT_DIR = OUTPUT_ROOT / 'audit'
MANIFEST_DIR = OUTPUT_ROOT / 'manifests'

FULL_RUN_PLAN_PATH = AUDIT_DIR / 'benchmark17_FINAL_full_680_run_plan.csv'
EXTERNAL_EVAL_PLAN_PATH = AUDIT_DIR / 'benchmark17_FINAL_external_2040_eval_plan.csv'

STOP_MODEL_AUDIT_PATH = AUDIT_DIR / 'STOP_SCOPE_model_completion_audit.csv'
STOP_DATASET_AUDIT_PATH = AUDIT_DIR / 'STOP_SCOPE_model_dataset_completion_audit.csv'
STOP_SUMMARY_PATH = AUDIT_DIR / 'STOP_SCOPE_summary.json'

FINAL13_MODEL_SCOPE_PATH = AUDIT_DIR / 'benchmark13_FINAL_model_scope_lock.csv'
FINAL13_TRAINING_SCOPE_PATH = AUDIT_DIR / 'benchmark13_FINAL_training_run_scope_520.csv'
FINAL13_WITHIN_EVAL_PLAN_PATH = AUDIT_DIR / 'benchmark13_FINAL_within_eval_plan_520.csv'
FINAL13_PROTOCOL2_PLAN_PATH = AUDIT_DIR / 'benchmark13_FINAL_protocol2_eval_plan_1560.csv'
FINAL13_MANIFEST_PATH = MANIFEST_DIR / 'benchmark13_FINAL_scope_manifest.json'

for p in [
    FULL_RUN_PLAN_PATH,
    EXTERNAL_EVAL_PLAN_PATH,
    STOP_MODEL_AUDIT_PATH,
    STOP_DATASET_AUDIT_PATH,
    STOP_SUMMARY_PATH,
]:
    assert p.is_file(), f'Required upstream artifact missing: {p}'


# ============================================================
# 2. LOCKED EXPECTATIONS FROM CELL 32A + USER SCOPE DECISION
# ============================================================

EXPECTED_FULL_PLAN_SHA256 = '900e75614fc21e809525f4f4a7b79e4dc6532e260cdd7653c1612acd6269898a'
EXPECTED_EXTERNAL_PLAN_SHA256 = 'cf89ef02de8d6880bce463a2f890ec264a5fc650194ed7a83cf30b2ea7bd24a7'
EXPECTED_STOP_MODEL_AUDIT_SHA256 = '5d1f81c3af90cab17ce2599187d63bc4c297adfd296f19d7264a31b3e013d1aa'
EXPECTED_STOP_SUMMARY_SHA256 = 'ce24299c593c8d0ab767c4c779810ff9676e5c365b3fbb001671ed08d11e9713'

EXPECTED_DATASETS = [
    'GenPept_Curated_2025',
    'External_Benchmark_1',
    'AMPlify_balanced',
    'External_Benchmark_3',
]

EXPECTED_SEEDS = list(range(100, 110))

FINAL13_MODEL_IDS = [
    'logistic_regression',
    'linear_svm_calibrated',
    'random_forest',
    'extra_trees',
    'hist_gradient_boosting',
    'lightgbm',
    'cnn1d',
    'bilstm',
    'bilstm_attention',
    'transformer_encoder',
    'ampep',
    'ampscannerv2',
    'ampeppy',
]

EXCLUDED_INCOMPLETE_MODEL_IDS = [
    'ampgram',
    'ampir',
    'ai4amp',
    'amplify',
]

assert len(FINAL13_MODEL_IDS) == 13
assert len(EXCLUDED_INCOMPLETE_MODEL_IDS) == 4
assert len(set(FINAL13_MODEL_IDS)) == 13
assert set(FINAL13_MODEL_IDS).isdisjoint(EXCLUDED_INCOMPLETE_MODEL_IDS)


# ============================================================
# 3. HELPERS
# ============================================================

def read_csv_exact(path: Path) -> pd.DataFrame:
    return pd.read_csv(
        path,
        low_memory=False,
        keep_default_na=False,
        na_filter=False,
    )


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        while True:
            b = f.read(chunk_size)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def load_json(path: Path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def _atomic_write_bytes(path: Path, data: bytes):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    try:
        with os.fdopen(fd, 'wb') as f:
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False, lineterminator='\n').encode('utf-8')


def json_bytes(payload) -> bytes:
    text = json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + '\n'
    return text.encode('utf-8')


def assert_or_create_immutable_csv(path: Path, df: pd.DataFrame, label: str) -> str:
    expected = csv_bytes(df)
    if path.is_file():
        observed = path.read_bytes()
        assert observed == expected, (
            f'Existing {label} differs from the newly constructed scope.\n'
            f'Refusing silent overwrite: {path}'
        )
        return f'EXISTING IDENTICAL {label} VERIFIED'

    _atomic_write_bytes(path, expected)
    assert path.read_bytes() == expected
    return f'NEW {label} ATOMICALLY COMMITTED'


def assert_or_create_immutable_json(path: Path, core_payload: dict, label: str) -> str:
    # created_at is metadata only; immutable identity is the `scope` object.
    if path.is_file():
        old = load_json(path)
        assert old.get('status') == 'FINAL_13_MODEL_SCOPE_LOCKED'
        assert old.get('scope') == core_payload, (
            f'Existing {label} differs from current scope. Refusing overwrite: {path}'
        )
        return f'EXISTING IDENTICAL {label} VERIFIED'

    payload = {
        'created_at': datetime.now().astimezone().isoformat(),
        'status': 'FINAL_13_MODEL_SCOPE_LOCKED',
        'scope': core_payload,
    }
    _atomic_write_bytes(path, json_bytes(payload))
    check = load_json(path)
    assert check['status'] == 'FINAL_13_MODEL_SCOPE_LOCKED'
    assert check['scope'] == core_payload
    return f'NEW {label} ATOMICALLY COMMITTED'


# ============================================================
# 4. VERIFY UPSTREAM IMMUTABLE EVIDENCE
# ============================================================

assert sha256_file(FULL_RUN_PLAN_PATH) == EXPECTED_FULL_PLAN_SHA256, '680-run plan SHA256 drift'
assert sha256_file(EXTERNAL_EVAL_PLAN_PATH) == EXPECTED_EXTERNAL_PLAN_SHA256, '2040 external plan SHA256 drift'
assert sha256_file(STOP_MODEL_AUDIT_PATH) == EXPECTED_STOP_MODEL_AUDIT_SHA256, 'Cell 32A model audit SHA256 drift'
assert sha256_file(STOP_SUMMARY_PATH) == EXPECTED_STOP_SUMMARY_SHA256, 'Cell 32A summary SHA256 drift'

full_plan = read_csv_exact(FULL_RUN_PLAN_PATH)
external_plan = read_csv_exact(EXTERNAL_EVAL_PLAN_PATH)
model_audit = read_csv_exact(STOP_MODEL_AUDIT_PATH)
dataset_audit = read_csv_exact(STOP_DATASET_AUDIT_PATH)
stop_summary = load_json(STOP_SUMMARY_PATH)

assert len(full_plan) == 680
assert len(external_plan) == 2040
assert full_plan['run_id'].is_unique

assert stop_summary['valid_trained_bundles'] == 520
assert stop_summary['complete_40_of_40_model_count'] == 13
assert stop_summary['training_launched'] is False
assert stop_summary['source_test_rows_read'] is False
assert stop_summary['external_target_rows_read'] is False
assert stop_summary['selection_by_performance_permitted'] is False

complete_models_from_audit = model_audit.loc[
    model_audit['COMPLETE_40_OF_40'].astype(str).str.lower().eq('true'),
    'model_id',
].astype(str).tolist()

incomplete_models_from_audit = model_audit.loc[
    ~model_audit['COMPLETE_40_OF_40'].astype(str).str.lower().eq('true'),
    'model_id',
].astype(str).tolist()

assert complete_models_from_audit == FINAL13_MODEL_IDS, (
    'Cell 32A complete-model list does not exactly match the final 13-model scope.\n'
    f'Audit: {complete_models_from_audit}\nExpected: {FINAL13_MODEL_IDS}'
)
assert incomplete_models_from_audit == EXCLUDED_INCOMPLETE_MODEL_IDS

for model_id in FINAL13_MODEL_IDS:
    row = model_audit.loc[model_audit['model_id'].astype(str).eq(model_id)]
    assert len(row) == 1
    row = row.iloc[0]
    assert int(row['expected_runs']) == 40
    assert int(row['valid_runs']) == 40
    assert int(row['missing_or_invalid_runs']) == 0
    assert int(row['complete_datasets']) == 4

for model_id in EXCLUDED_INCOMPLETE_MODEL_IDS:
    row = model_audit.loc[model_audit['model_id'].astype(str).eq(model_id)]
    assert len(row) == 1
    row = row.iloc[0]
    assert int(row['expected_runs']) == 40
    assert int(row['valid_runs']) == 0
    assert int(row['missing_or_invalid_runs']) == 40
    assert int(row['complete_datasets']) == 0

# Every included model must be 10/10 on every source dataset.
selected_dataset_audit = dataset_audit[
    dataset_audit['model_id'].astype(str).isin(FINAL13_MODEL_IDS)
].copy()
assert len(selected_dataset_audit) == 13 * 4
assert selected_dataset_audit['complete'].astype(str).str.lower().eq('true').all()
assert pd.to_numeric(selected_dataset_audit['valid_runs'], errors='raise').eq(10).all()


# ============================================================
# 5. BUILD FINAL 13-MODEL MODEL-SCOPE TABLE
# ============================================================

model_scope = model_audit[
    model_audit['model_id'].astype(str).isin(FINAL13_MODEL_IDS)
].copy()

# Preserve the final, predeclared order above rather than sorting by performance.
model_order = {m: i + 1 for i, m in enumerate(FINAL13_MODEL_IDS)}
model_scope.insert(0, 'final13_model_no', model_scope['model_id'].map(model_order).astype(int))
model_scope['scope_status'] = 'INCLUDED_COMPLETE_40_OF_40'
model_scope['selection_basis'] = 'all_complete_models_before_test_or_external_evaluation;not_performance_selected'
model_scope = model_scope.sort_values('final13_model_no').reset_index(drop=True)

assert len(model_scope) == 13
assert model_scope['valid_runs'].astype(int).eq(40).all()


# ============================================================
# 6. BUILD 520-RUN FINAL TRAINING SCOPE
# ============================================================

training_scope = full_plan[
    full_plan['model_id'].astype(str).isin(FINAL13_MODEL_IDS)
].copy()

training_scope.insert(0, 'final13_training_no', range(1, len(training_scope) + 1))

assert len(training_scope) == 520
assert training_scope['run_id'].is_unique
assert training_scope.groupby('model_id').size().eq(40).all()
assert training_scope.groupby(['model_id', 'source_dataset']).size().eq(10).all()
assert training_scope['model_id'].drop_duplicates().tolist() == FINAL13_MODEL_IDS
assert training_scope['source_dataset'].drop_duplicates().tolist() == EXPECTED_DATASETS
assert sorted(training_scope['seed'].astype(int).unique().tolist()) == EXPECTED_SEEDS


# ============================================================
# 7. BUILD PROTOCOL-1 SOURCE-TEST EVALUATION PLAN (NO DATA READ)
# ============================================================

within_rows = []
for i, row in enumerate(training_scope.itertuples(index=False), start=1):
    within_rows.append({
        'eval_no': i,
        'protocol': 'P1_WITHIN_DATASET_SOURCE_TEST',
        'run_id': str(row.run_id),
        'model_id': str(row.model_id),
        'model_group': str(row.model_group),
        'source_dataset': str(row.source_dataset),
        'target_dataset': str(row.source_dataset),
        'seed': int(row.seed),
        'target_index_key': str(row.source_test_index_key),
        'target_n': int(row.source_test_n),
        'threshold_source': 'source_validation_only',
        'target_threshold_tuning': False,
        'target_retraining': False,
        'run_dir': str(row.run_dir),
    })

within_plan = pd.DataFrame(within_rows)

assert len(within_plan) == 520
assert within_plan['run_id'].is_unique
assert within_plan.groupby(['model_id', 'source_dataset']).size().eq(10).all()
assert within_plan['target_threshold_tuning'].eq(False).all()
assert within_plan['target_retraining'].eq(False).all()
assert within_plan['threshold_source'].eq('source_validation_only').all()


# ============================================================
# 8. FILTER LOCKED PROTOCOL-2 PLAN TO FINAL 13 MODELS
# ============================================================

protocol2_plan = external_plan[
    external_plan['model_id'].astype(str).isin(FINAL13_MODEL_IDS)
].copy()

protocol2_plan = protocol2_plan.rename(columns={'eval_no': 'legacy_17model_eval_no'})
protocol2_plan.insert(0, 'eval_no', range(1, len(protocol2_plan) + 1))
protocol2_plan.insert(1, 'protocol', 'P2_CROSS_DATASET')

assert len(protocol2_plan) == 1560
assert protocol2_plan.groupby('run_id').size().eq(3).all()
assert protocol2_plan.groupby(['model_id', 'source_dataset', 'target_dataset']).size().eq(10).all()
assert protocol2_plan['source_dataset'].ne(protocol2_plan['target_dataset']).all()
assert protocol2_plan['target_threshold_tuning'].astype(str).str.lower().eq('false').all()
assert protocol2_plan['target_retraining'].astype(str).str.lower().eq('false').all()
assert pd.to_numeric(protocol2_plan['residual_exact_overlap'], errors='raise').eq(0).all()

# Each selected training run must map to exactly three cross-dataset evaluations.
assert set(protocol2_plan['run_id'].astype(str)) == set(training_scope['run_id'].astype(str))


# ============================================================
# 9. CONSTRUCT IMMUTABLE SCOPE MANIFEST CORE
# ============================================================

scope_core = {
    'schema_version': '1.0',
    'benchmark_version': 'benchmark4_FINAL_v1',
    'final_scope_name': 'benchmark13_FINAL',
    'scope_decision': (
        'include every model with a complete 40/40 canonical training bundle '
        'identified by the pre-evaluation Cell 32A disk audit; exclude only models '
        'with 0/40 valid canonical training bundles; no performance-based selection'
    ),
    'manuscript_scope_note': (
        'the draft manuscript previously stated seven models; downstream manuscript '
        'text must be updated to thirteen models to reflect the final evidence-preserving scope'
    ),
    'n_models': 13,
    'model_ids': FINAL13_MODEL_IDS,
    'n_controlled_models': 10,
    'n_completed_published_models': 3,
    'excluded_incomplete_models': EXCLUDED_INCOMPLETE_MODEL_IDS,
    'excluded_model_valid_run_counts': {m: 0 for m in EXCLUDED_INCOMPLETE_MODEL_IDS},
    'n_source_datasets': 4,
    'source_datasets': EXPECTED_DATASETS,
    'n_seeds': 10,
    'seeds': EXPECTED_SEEDS,
    'training_bundles': 520,
    'additional_training_required': False,
    'protocol1_seed_level_evaluations': 520,
    'protocol1_model_dataset_configurations': 52,
    'protocol2_seed_level_evaluations': 1560,
    'protocol2_model_source_target_configurations': 156,
    'total_seed_level_evaluations': 2080,
    'threshold_policy': 'frozen_source_validation_threshold_only',
    'target_threshold_tuning': False,
    'target_retraining': False,
    'scope_locked_before_source_test_evaluation': True,
    'scope_locked_before_protocol2_evaluation': True,
    'selection_by_performance': False,
    'training_performed_in_cell32b': False,
    'source_test_rows_read_in_cell32b': False,
    'external_target_rows_read_in_cell32b': False,
    'upstream_evidence': {
        'full_680_run_plan': {
            'path': str(FULL_RUN_PLAN_PATH),
            'sha256': EXPECTED_FULL_PLAN_SHA256,
        },
        'external_2040_eval_plan': {
            'path': str(EXTERNAL_EVAL_PLAN_PATH),
            'sha256': EXPECTED_EXTERNAL_PLAN_SHA256,
        },
        'cell32a_model_completion_audit': {
            'path': str(STOP_MODEL_AUDIT_PATH),
            'sha256': EXPECTED_STOP_MODEL_AUDIT_SHA256,
        },
        'cell32a_summary': {
            'path': str(STOP_SUMMARY_PATH),
            'sha256': EXPECTED_STOP_SUMMARY_SHA256,
        },
    },
}


# ============================================================
# 10. IMMUTABLE COMMIT
# ============================================================

model_action = assert_or_create_immutable_csv(
    FINAL13_MODEL_SCOPE_PATH,
    model_scope,
    '13-MODEL SCOPE LOCK',
)
training_action = assert_or_create_immutable_csv(
    FINAL13_TRAINING_SCOPE_PATH,
    training_scope,
    '520-RUN TRAINING SCOPE',
)
within_action = assert_or_create_immutable_csv(
    FINAL13_WITHIN_EVAL_PLAN_PATH,
    within_plan,
    '520-ROW PROTOCOL-1 EVALUATION PLAN',
)
protocol2_action = assert_or_create_immutable_csv(
    FINAL13_PROTOCOL2_PLAN_PATH,
    protocol2_plan,
    '1560-ROW PROTOCOL-2 EVALUATION PLAN',
)
manifest_action = assert_or_create_immutable_json(
    FINAL13_MANIFEST_PATH,
    scope_core,
    '13-MODEL FINAL SCOPE MANIFEST',
)


# ============================================================
# 11. RE-READ + ACCEPTANCE GATE
# ============================================================

model_check = read_csv_exact(FINAL13_MODEL_SCOPE_PATH)
training_check = read_csv_exact(FINAL13_TRAINING_SCOPE_PATH)
within_check = read_csv_exact(FINAL13_WITHIN_EVAL_PLAN_PATH)
p2_check = read_csv_exact(FINAL13_PROTOCOL2_PLAN_PATH)
manifest_check = load_json(FINAL13_MANIFEST_PATH)

assert len(model_check) == 13
assert len(training_check) == 520
assert len(within_check) == 520
assert len(p2_check) == 1560
assert manifest_check['status'] == 'FINAL_13_MODEL_SCOPE_LOCKED'
assert manifest_check['scope'] == scope_core

assert model_check['model_id'].astype(str).tolist() == FINAL13_MODEL_IDS
assert training_check.groupby('model_id').size().eq(40).all()
assert within_check.groupby('model_id').size().eq(40).all()
assert p2_check.groupby('model_id').size().eq(120).all()  # 4 sources x 3 targets x 10 seeds

# Cell boundary guarantees.
TRAINING_LAUNCHED = False
SOURCE_TEST_ROWS_READ = False
EXTERNAL_TARGET_ROWS_READ = False
SCIENTIFIC_METRICS_SHOWN = False

assert TRAINING_LAUNCHED is False
assert SOURCE_TEST_ROWS_READ is False
assert EXTERNAL_TARGET_ROWS_READ is False
assert SCIENTIFIC_METRICS_SHOWN is False


# ============================================================
# 12. REPORT
# ============================================================

print('=' * 128)
print('CELL 32B - FINAL 13-MODEL SCOPE LOCK / PRE-EVALUATION FREEZE')
print('=' * 128)
print('Upstream Cell 32A audit         : VERIFIED BY SHA256')
print('Original 680-run plan           : VERIFIED BY SHA256')
print('Original 2040 Protocol-2 plan   : VERIFIED BY SHA256')
print('Scope selection by performance  : FALSE')
print('Training launched               : FALSE')
print('Source TEST rows read           : FALSE')
print('External target rows read       : FALSE')
print('-' * 128)
print('Final models                    : 13')
for i, model_id in enumerate(FINAL13_MODEL_IDS, start=1):
    group = model_scope.loc[model_scope['model_id'].astype(str).eq(model_id), 'model_group'].iloc[0]
    print(f'  {i:02d}. {model_id:<28} [{group}] 40/40')
print('-' * 128)
print('Excluded incomplete models      :', EXCLUDED_INCOMPLETE_MODEL_IDS)
print('Excluded valid runs             : 0/40 each')
print('Source datasets                 :', EXPECTED_DATASETS)
print('Seeds                           :', EXPECTED_SEEDS)
print('Training bundles locked         : 520 / 520')
print('Protocol-1 source-test plan     : 520 seed-level evals (52 model-dataset configurations)')
print('Protocol-2 cross-dataset plan   : 1560 seed-level evals (156 model-source-target configurations)')
print('Additional training required    : FALSE')
print('Threshold source                : SOURCE VALIDATION ONLY / FROZEN')
print('Target threshold tuning         : FALSE')
print('Target retraining               : FALSE')
print('-' * 128)
print('Model scope action              :', model_action)
print('Training scope action           :', training_action)
print('Protocol-1 plan action          :', within_action)
print('Protocol-2 plan action          :', protocol2_action)
print('Manifest action                 :', manifest_action)
print('-' * 128)
print('Model scope CSV                 :', FINAL13_MODEL_SCOPE_PATH)
print('  SHA256                        :', sha256_file(FINAL13_MODEL_SCOPE_PATH))
print('Training scope CSV              :', FINAL13_TRAINING_SCOPE_PATH)
print('  SHA256                        :', sha256_file(FINAL13_TRAINING_SCOPE_PATH))
print('Protocol-1 eval plan            :', FINAL13_WITHIN_EVAL_PLAN_PATH)
print('  SHA256                        :', sha256_file(FINAL13_WITHIN_EVAL_PLAN_PATH))
print('Protocol-2 eval plan            :', FINAL13_PROTOCOL2_PLAN_PATH)
print('  SHA256                        :', sha256_file(FINAL13_PROTOCOL2_PLAN_PATH))
print('Scope manifest                  :', FINAL13_MANIFEST_PATH)
print('  SHA256                        :', sha256_file(FINAL13_MANIFEST_PATH))
print('=' * 128)
print('CELL 32B PASS - FINAL 13-MODEL SCOPE IMMUTABLY LOCKED BEFORE EVALUATION')
print('NEXT                            : CELL 33 - EVALUATION ONLY; NO TRAINING')
print('=' * 128)

================================================================================================================================
CELL 32B - FINAL 13-MODEL SCOPE LOCK / PRE-EVALUATION FREEZE
================================================================================================================================
Upstream Cell 32A audit         : VERIFIED BY SHA256
Original 680-run plan           : VERIFIED BY SHA256
Original 2040 Protocol-2 plan   : VERIFIED BY SHA256
Scope selection by performance  : FALSE
Training launched               : FALSE
Source TEST rows read           : FALSE
External target rows read       : FALSE
--------------------------------------------------------------------------------------------------------------------------------
Final models                    : 13
  01. logistic_regression          [controlled_baseline] 40/40
  02. linear_svm_calibrated        [controlled_baseline] 40/40
  03. random_forest                [controlled_baseline] 40/40
  04. extra_trees                  [controlled_baseline] 40/40
  05. hist_gradient_boosting       [controlled_baseline] 40/40
  06. lightgbm                     [controlled_baseline] 40/40
  07. cnn1d                        [controlled_baseline] 40/40
  08. bilstm                       [controlled_baseline] 40/40
  09. bilstm_attention             [controlled_baseline] 40/40
  10. transformer_encoder          [controlled_baseline] 40/40
  11. ampep                        [published_amp_method] 40/40
  12. ampscannerv2                 [published_amp_method] 40/40
  13. ampeppy                      [published_amp_method] 40/40
--------------------------------------------------------------------------------------------------------------------------------
Excluded incomplete models      : ['ampgram', 'ampir', 'ai4amp', 'amplify']
Excluded valid runs             : 0/40 each
Source datasets                 : ['GenPept_Curated_2025', 'External_Benchmark_1', 'AMPlify_balanced', 'External_Benchmark_3']
Seeds                           : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
Training bundles locked         : 520 / 520
Protocol-1 source-test plan     : 520 seed-level evals (52 model-dataset configurations)
Protocol-2 cross-dataset plan   : 1560 seed-level evals (156 model-source-target configurations)
Additional training required    : FALSE
Threshold source                : SOURCE VALIDATION ONLY / FROZEN
Target threshold tuning         : FALSE
Target retraining               : FALSE
--------------------------------------------------------------------------------------------------------------------------------
Model scope action              : NEW 13-MODEL SCOPE LOCK ATOMICALLY COMMITTED
Training scope action           : NEW 520-RUN TRAINING SCOPE ATOMICALLY COMMITTED
Protocol-1 plan action          : NEW 520-ROW PROTOCOL-1 EVALUATION PLAN ATOMICALLY COMMITTED
Protocol-2 plan action          : NEW 1560-ROW PROTOCOL-2 EVALUATION PLAN ATOMICALLY COMMITTED
Manifest action                 : NEW 13-MODEL FINAL SCOPE MANIFEST ATOMICALLY COMMITTED
--------------------------------------------------------------------------------------------------------------------------------
Model scope CSV                 : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark13_FINAL_model_scope_lock.csv
  SHA256                        : 66648c9c1dd0911fc29d36a405a8f176da168d4a74459e2cd4149a45d8251f2a
Training scope CSV              : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark13_FINAL_training_run_scope_520.csv
  SHA256                        : a01215b83916ea6422cb7b86512154bfc476aadda4e4d0b513911687200a00f7
Protocol-1 eval plan            : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark13_FINAL_within_eval_plan_520.csv
  SHA256                        : 0b1b5765d2005ebe8f1875309314cab00d04a6b5d8d552d85dbdbe4319ca1b0e
Protocol-2 eval plan            : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark13_FINAL_protocol2_eval_plan_1560.csv
  SHA256                        : 7801abad304766b78416c4a78388f371e2ae9bdd1fd91f64656bb8ecec606725
Scope manifest                  : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark13_FINAL_scope_manifest.json
  SHA256                        : 1639f1480ba4dbe9b1344d1321f5049c9ac59dc15ac8cced5d3e62210b3209dc
================================================================================================================================
CELL 32B PASS - FINAL 13-MODEL SCOPE IMMUTABLY LOCKED BEFORE EVALUATION
NEXT                            : CELL 33 - EVALUATION ONLY; NO TRAINING
================================================================================================================================

In [50]:
from __future__ import annotations

# ============================================================================
# CELL 33 - FINAL 13-MODEL EVALUATION ONLY / NO TRAINING
# Benchmark: benchmark13_FINAL derived from benchmark4_FINAL_v1
# ============================================================================
# PURPOSE
#   1) Verify the immutable Cell 32B 13-model scope.
#   2) Verify all 520 canonical TRAINED bundles remain intact.
#   3) BEFORE reading any TEST / Protocol-2 target rows, perform checkpoint-
#      reload equivalence tests on SOURCE VALIDATION for all 13 model loaders.
#   4) Only after all loader self-tests pass, evaluate:
#        P1:  520 source-test seed-level evaluations
#        P2: 1560 cross-dataset seed-level evaluations
#      using the already-frozen source-validation tau* for each run.
#   5) Never fit, fine-tune, recalibrate, tune thresholds, or select models.
#   6) Keep evaluation outputs OUTSIDE canonical training run directories so
#      Cell-32 training bundles remain immutable/auditable.
#   7) Restart-safe: valid evaluation bundles are verified and skipped.
#
# IMPORTANT SCIENTIFIC BOUNDARY
#   - NO .fit(), NO retraining, NO target adaptation.
#   - TEST/target rows are not materialized until checkpoint reload equivalence
#     has passed on validation data for every included model.
#   - The 13-model scope was locked before this Cell.
# ============================================================================

from pathlib import Path
from datetime import datetime
import csv
import gc
import hashlib
import json
import math
import os
import pickle
import resource
import shutil
import subprocess
import tempfile
import time
import traceback

import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    balanced_accuracy_score,
    brier_score_loss,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    roc_auc_score,
)


# ============================================================================
# 1. LOCKED PATHS / IDENTITIES
# ============================================================================

PROJECT_ROOT = Path('/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026')
OUTPUT_ROOT = PROJECT_ROOT / 'benchmark17_outputs'
AUDIT_DIR = OUTPUT_ROOT / 'audit'
MANIFEST_DIR = OUTPUT_ROOT / 'manifests'
RESULTS_ROOT = OUTPUT_ROOT / 'results'
WORK_ROOT = Path('/home/pc/genpept_benchmark17_work')
RUN_ROOT = WORK_ROOT / 'runs' / 'benchmark4_FINAL_v1'

FINAL13_MODEL_SCOPE_PATH = AUDIT_DIR / 'benchmark13_FINAL_model_scope_lock.csv'
FINAL13_TRAINING_SCOPE_PATH = AUDIT_DIR / 'benchmark13_FINAL_training_run_scope_520.csv'
FINAL13_WITHIN_PLAN_PATH = AUDIT_DIR / 'benchmark13_FINAL_within_eval_plan_520.csv'
FINAL13_PROTOCOL2_PLAN_PATH = AUDIT_DIR / 'benchmark13_FINAL_protocol2_eval_plan_1560.csv'
FINAL13_SCOPE_MANIFEST_PATH = MANIFEST_DIR / 'benchmark13_FINAL_scope_manifest.json'

EVALUATION_CONTRACT_PATH = MANIFEST_DIR / 'benchmark17_FINAL_evaluation_contract.json'
CONTROLLED_CONTRACT_PATH = MANIFEST_DIR / 'benchmark17_FINAL_controlled_model_contract.json'
FEATURE_CACHE_MANIFEST_PATH = MANIFEST_DIR / 'benchmark17_FINAL_feature_cache_manifest.json'
LAUNCHER_CONTRACT_PATH = MANIFEST_DIR / 'benchmark17_FINAL_training_launcher_contract.json'
CUDA_PATHS_FILE = MANIFEST_DIR / 'cuda_runtime_paths.json'
ENVIRONMENT_AUDIT_PATH = MANIFEST_DIR / 'environment_audit.json'

EVAL_ROOT = RESULTS_ROOT / 'benchmark13_FINAL' / 'cell33_evaluation'
P1_ROOT = EVAL_ROOT / 'P1_source_test'
P2_ROOT = EVAL_ROOT / 'P2_cross_dataset'
HELPER_ROOT = WORK_ROOT / 'evaluation_helpers' / 'benchmark13_FINAL'
SELFTEST_ROOT = EVAL_ROOT / '_loader_selftest'

EVAL_LEDGER_PATH = AUDIT_DIR / 'benchmark13_FINAL_cell33_evaluation_ledger_2080.csv'
SEED_METRICS_PATH = RESULTS_ROOT / 'benchmark13_FINAL' / 'benchmark13_FINAL_seed_level_metrics_2080.csv'
CELL33_SUMMARY_PATH = AUDIT_DIR / 'benchmark13_FINAL_cell33_summary.json'
CELL33_SELFTEST_PATH = AUDIT_DIR / 'benchmark13_FINAL_cell33_checkpoint_reload_selftest.csv'

EXPECTED_SCOPE_SHA = '66648c9c1dd0911fc29d36a405a8f176da168d4a74459e2cd4149a45d8251f2a'
EXPECTED_TRAINING_SCOPE_SHA = 'a01215b83916ea6422cb7b86512154bfc476aadda4e4d0b513911687200a00f7'
EXPECTED_P1_PLAN_SHA = '0b1b5765d2005ebe8f1875309314cab00d04a6b5d8d552d85dbdbe4319ca1b0e'
EXPECTED_P2_PLAN_SHA = '7801abad304766b78416c4a78388f371e2ae9bdd1fd91f64656bb8ecec606725'
EXPECTED_SCOPE_MANIFEST_SHA = '1639f1480ba4dbe9b1344d1321f5049c9ac59dc15ac8cced5d3e62210b3209dc'

EXPECTED_DATASETS = [
    'GenPept_Curated_2025',
    'External_Benchmark_1',
    'AMPlify_balanced',
    'External_Benchmark_3',
]
EXPECTED_SEEDS = list(range(100, 110))
CONTROLLED_CLASSICAL = [
    'logistic_regression',
    'linear_svm_calibrated',
    'random_forest',
    'extra_trees',
    'hist_gradient_boosting',
    'lightgbm',
]
CONTROLLED_DEEP = [
    'cnn1d',
    'bilstm',
    'bilstm_attention',
    'transformer_encoder',
]
PUBLISHED_COMPLETE = ['ampep', 'ampscannerv2', 'ampeppy']
FINAL13_MODEL_IDS = CONTROLLED_CLASSICAL + CONTROLLED_DEEP + PUBLISHED_COMPLETE
assert len(FINAL13_MODEL_IDS) == 13

PREDICTION_COLUMNS = [
    'eval_id', 'run_id', 'protocol', 'model_id', 'source_dataset',
    'target_dataset', 'seed', 'sample_id', 'y_true', 'y_score', 'y_pred',
    'threshold',
]
METRIC_COLUMNS = [
    'AUROC', 'AUPRC', 'MCC', 'BACC', 'F1', 'ACC',
    'Sensitivity', 'Specificity', 'Brier', 'ECE10',
    'threshold', 'TP', 'TN', 'FP', 'FN', 'n', 'n_positive', 'n_negative',
]

for p in [
    PROJECT_ROOT, OUTPUT_ROOT, AUDIT_DIR, MANIFEST_DIR, RESULTS_ROOT, WORK_ROOT, RUN_ROOT,
]:
    assert p.is_dir(), f'Required directory missing: {p}'

for p in [
    FINAL13_MODEL_SCOPE_PATH,
    FINAL13_TRAINING_SCOPE_PATH,
    FINAL13_WITHIN_PLAN_PATH,
    FINAL13_PROTOCOL2_PLAN_PATH,
    FINAL13_SCOPE_MANIFEST_PATH,
    EVALUATION_CONTRACT_PATH,
    CONTROLLED_CONTRACT_PATH,
    FEATURE_CACHE_MANIFEST_PATH,
    LAUNCHER_CONTRACT_PATH,
]:
    assert p.is_file(), f'Required locked artifact missing: {p}'

for p in [EVAL_ROOT, P1_ROOT, P2_ROOT, HELPER_ROOT, SELFTEST_ROOT]:
    p.mkdir(parents=True, exist_ok=True)


# ============================================================================
# 2. GENERIC HELPERS
# ============================================================================

def now_iso() -> str:
    return datetime.now().astimezone().isoformat()


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(chunk_size), b''):
            h.update(chunk)
    return h.hexdigest()


def read_csv_exact(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, low_memory=False, keep_default_na=False, na_filter=False)


def load_json(path: Path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def atomic_write_json(path: Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    try:
        with os.fdopen(fd, 'w', encoding='utf-8', newline='\n') as f:
            json.dump(payload, f, indent=2, ensure_ascii=False, sort_keys=True)
            f.write('\n')
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def atomic_write_csv(path: Path, df: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    os.close(fd)
    try:
        df.to_csv(tmp, index=False, lineterminator='\n')
        with open(tmp, 'rb') as f:
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def artifact_entry(path: Path) -> dict:
    assert path.is_file(), f'Missing artifact: {path}'
    return {'size_bytes': int(path.stat().st_size), 'sha256': sha256_file(path)}


def lock_helper(path: Path, text: str) -> str:
    expected = hashlib.sha256(text.encode('utf-8')).hexdigest()
    if path.is_file():
        observed = sha256_file(path)
        assert observed == expected, f'Helper drift: {path}\nexpected={expected}\nobserved={observed}'
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
        try:
            with os.fdopen(fd, 'w', encoding='utf-8', newline='\n') as f:
                f.write(text)
                f.flush()
                os.fsync(f.fileno())
            os.replace(tmp, path)
        finally:
            if os.path.exists(tmp):
                os.unlink(tmp)
    assert sha256_file(path) == expected
    return expected


def run_cmd(cmd, *, env=None, timeout=None, cwd=None, label='command'):
    r = subprocess.run(
        [str(x) for x in cmd], cwd=None if cwd is None else str(cwd), env=env,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        timeout=timeout, check=False,
    )
    if r.returncode != 0:
        print(f'[{label}] STDOUT:\n{r.stdout}')
        print(f'[{label}] STDERR:\n{r.stderr}')
    assert r.returncode == 0, f'{label} failed with exit code {r.returncode}'
    return r


def process_peak_ram_mb() -> float:
    value = float(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
    return value / 1024.0


def fmt_seconds(sec) -> str:
    if sec is None or not np.isfinite(float(sec)):
        return 'NA'
    sec = int(round(float(sec)))
    return f'{sec//3600:02d}:{(sec%3600)//60:02d}:{sec%60:02d}'


# ============================================================================
# 3. VERIFY CELL 32B IMMUTABLE SCOPE
# ============================================================================

assert sha256_file(FINAL13_MODEL_SCOPE_PATH) == EXPECTED_SCOPE_SHA, '13-model scope SHA drift'
assert sha256_file(FINAL13_TRAINING_SCOPE_PATH) == EXPECTED_TRAINING_SCOPE_SHA, '520-run scope SHA drift'
assert sha256_file(FINAL13_WITHIN_PLAN_PATH) == EXPECTED_P1_PLAN_SHA, 'P1 plan SHA drift'
assert sha256_file(FINAL13_PROTOCOL2_PLAN_PATH) == EXPECTED_P2_PLAN_SHA, 'P2 plan SHA drift'
assert sha256_file(FINAL13_SCOPE_MANIFEST_PATH) == EXPECTED_SCOPE_MANIFEST_SHA, 'Scope manifest SHA drift'

model_scope = read_csv_exact(FINAL13_MODEL_SCOPE_PATH)
training_scope = read_csv_exact(FINAL13_TRAINING_SCOPE_PATH)
p1_plan = read_csv_exact(FINAL13_WITHIN_PLAN_PATH)
p2_plan = read_csv_exact(FINAL13_PROTOCOL2_PLAN_PATH)
scope_manifest = load_json(FINAL13_SCOPE_MANIFEST_PATH)

a = scope_manifest['scope']
assert a['n_models'] == 13
assert a['model_ids'] == FINAL13_MODEL_IDS
assert a['training_bundles'] == 520
assert a['additional_training_required'] is False
assert a['target_threshold_tuning'] is False
assert a['target_retraining'] is False
assert a['scope_locked_before_source_test_evaluation'] is True
assert a['scope_locked_before_protocol2_evaluation'] is True
assert a['selection_by_performance'] is False
assert len(training_scope) == 520 and training_scope['run_id'].is_unique
assert len(p1_plan) == 520 and p1_plan['run_id'].is_unique
assert len(p2_plan) == 1560
assert p2_plan.groupby('run_id').size().eq(3).all()
assert training_scope['model_id'].drop_duplicates().astype(str).tolist() == FINAL13_MODEL_IDS
assert sorted(pd.to_numeric(training_scope['seed'], errors='raise').astype(int).unique().tolist()) == EXPECTED_SEEDS
assert training_scope['source_dataset'].drop_duplicates().astype(str).tolist() == EXPECTED_DATASETS

# P1/P2 scientific invariants.
assert p1_plan['threshold_source'].astype(str).eq('source_validation_only').all()
assert p1_plan['target_threshold_tuning'].astype(str).str.lower().eq('false').all()
assert p1_plan['target_retraining'].astype(str).str.lower().eq('false').all()
assert p2_plan['threshold_source'].astype(str).eq('source_validation_only').all()
assert p2_plan['target_threshold_tuning'].astype(str).str.lower().eq('false').all()
assert p2_plan['target_retraining'].astype(str).str.lower().eq('false').all()
assert p2_plan['source_dataset'].astype(str).ne(p2_plan['target_dataset'].astype(str)).all()
assert pd.to_numeric(p2_plan['residual_exact_overlap'], errors='raise').eq(0).all()


# ============================================================================
# 4. VERIFY LOCKED EVALUATION / FEATURE CONTRACTS
# ============================================================================

evaluation_contract = load_json(EVALUATION_CONTRACT_PATH)
controlled_wrapper = load_json(CONTROLLED_CONTRACT_PATH)
feature_manifest = load_json(FEATURE_CACHE_MANIFEST_PATH)
launcher_wrapper = load_json(LAUNCHER_CONTRACT_PATH)

assert evaluation_contract['status'] == 'LOCKED_BEFORE_MODEL_TRAINING'
assert evaluation_contract['datasets'] == EXPECTED_DATASETS
assert evaluation_contract['model_seeds'] == EXPECTED_SEEDS
assert evaluation_contract['threshold_policy']['selection_dataset'] == 'source_validation_only'
assert evaluation_contract['threshold_policy']['optimization_objective'] == 'maximize_MCC'
assert evaluation_contract['threshold_policy']['test_based_threshold_selection'] is False
assert evaluation_contract['threshold_policy']['external_target_based_threshold_selection'] is False
assert evaluation_contract['threshold_policy']['protocol_2']['target_threshold_optimization'] is False
assert evaluation_contract['threshold_policy']['protocol_2']['target_threshold_recalibration'] is False
assert evaluation_contract['score_contract']['positive_label'] == 1
assert evaluation_contract['score_contract']['required_score_range'] == [0.0, 1.0]

controlled_contract = controlled_wrapper['contract']
MODEL_CONFIGS = controlled_contract['model_configs']
DEEP_SHARED = controlled_contract['deep_shared_training']
assert controlled_contract['controlled_model_ids'] == CONTROLLED_CLASSICAL + CONTROLLED_DEEP

cache_files = feature_manifest['files']
CLASSICAL_CACHE_PATH = Path(cache_files['X_classical']['path'])
TOKEN_CACHE_PATH = Path(cache_files['X_tokens']['path'])
LABEL_CACHE_PATH = Path(cache_files['y']['path'])
ROW_METADATA_PATH = Path(cache_files['row_metadata']['path'])
for key, path in [
    ('X_classical', CLASSICAL_CACHE_PATH),
    ('X_tokens', TOKEN_CACHE_PATH),
    ('y', LABEL_CACHE_PATH),
    ('row_metadata', ROW_METADATA_PATH),
]:
    assert path.is_file(), f'Missing cache: {path}'
    assert sha256_file(path) == cache_files[key]['sha256'], f'Cache hash drift: {key}'

launcher = launcher_wrapper['contract']
index_path = Path(launcher['immutable_inputs']['execution_index']['path'])
assert index_path.is_file()
assert sha256_file(index_path) == launcher['immutable_inputs']['execution_index']['sha256']
INDEX = np.load(index_path, allow_pickle=False)
X_CLASSICAL = np.load(CLASSICAL_CACHE_PATH, mmap_mode='r', allow_pickle=False)
X_TOKENS = np.load(TOKEN_CACHE_PATH, mmap_mode='r', allow_pickle=False)
Y = np.load(LABEL_CACHE_PATH, mmap_mode='r', allow_pickle=False)
assert X_CLASSICAL.shape == (41059, 421)
assert X_TOKENS.shape == (41059, 200)
assert Y.shape == (41059,)

TOKEN_TO_ID = controlled_contract['deep_representation']['token_to_id']
assert TOKEN_TO_ID['PAD'] == 0
ID_TO_AA = {int(v): str(k) for k, v in TOKEN_TO_ID.items() if str(k) != 'PAD'}
assert set(ID_TO_AA) == set(range(1, 21))
assert set(ID_TO_AA.values()) == set('ACDEFGHIKLMNPQRSTVWY')


# ============================================================================
# 5. VERIFY ALL 520 TRAINED BUNDLES WITHOUT READING TEST/TARGET ROWS
# ============================================================================

def verify_training_bundle(row) -> dict:
    run_dir = Path(str(row.run_dir))
    manifest_path = run_dir / 'run_manifest.json'
    assert manifest_path.is_file(), f'Missing run manifest: {manifest_path}'
    m = load_json(manifest_path)
    assert m['status'] in {'TRAINED', 'EVALUATED', 'COMPLETE'}
    assert m['run_id'] == str(row.run_id)
    assert m['model_id'] == str(row.model_id)
    assert m['source_dataset'] == str(row.source_dataset)
    assert int(m['seed']) == int(row.seed)
    assert str(m['train_index_key']) == str(row.train_index_key)
    assert str(m['validation_index_key']) == str(row.validation_index_key)
    assert str(m['source_test_index_key']) == str(row.source_test_index_key)
    assert m.get('cell32_source_test_read') is False
    assert m.get('cell32_external_target_read') is False

    # Cell 33 stores results elsewhere; canonical training dirs must still be clean.
    assert not (run_dir / 'source_test_predictions.csv').exists(), f'Training dir was mutated: {run_dir}'
    assert not (run_dir / 'source_test_metrics.json').exists(), f'Training dir was mutated: {run_dir}'
    assert not (run_dir / 'external').exists(), f'Training dir was mutated: {run_dir}'

    required = m['training_artifacts']
    for rel in ['config.json', 'validation_predictions.csv', 'validation_threshold.json', 'history.csv', 'resources.json']:
        assert rel in required
    for rel, entry in required.items():
        p = run_dir / rel
        assert p.is_file(), f'Missing training artifact: {p}'
        assert int(p.stat().st_size) == int(entry['size_bytes'])
        assert sha256_file(p) == str(entry['sha256'])

    cp_rel = str(m['checkpoint_relative_path'])
    checkpoint = run_dir / cp_rel
    assert checkpoint.is_file(), f'Missing checkpoint: {checkpoint}'
    cp_entry = m['checkpoint_artifact']
    assert int(checkpoint.stat().st_size) == int(cp_entry['size_bytes'])
    assert sha256_file(checkpoint) == str(cp_entry['sha256'])

    threshold_path = run_dir / 'validation_threshold.json'
    th = load_json(threshold_path)
    tau = float(th['tau'])
    assert 0.0 <= tau <= 1.0
    assert th['selection_dataset'] == 'source_validation_only'
    assert th['source_test_used'] is False
    assert th['external_target_used'] is False
    assert np.isclose(float(m['validation_threshold']), tau, rtol=0.0, atol=1e-15)

    return {
        'run_dir': run_dir,
        'manifest_path': manifest_path,
        'manifest_sha256': sha256_file(manifest_path),
        'checkpoint': checkpoint,
        'checkpoint_sha256': sha256_file(checkpoint),
        'threshold_path': threshold_path,
        'threshold_sha256': sha256_file(threshold_path),
        'tau': tau,
        'manifest': m,
    }


print('=' * 140)
print('CELL 33 - FINAL 13-MODEL EVALUATION ONLY / NO TRAINING')
print('=' * 140)
print('Cell 32B scope             : VERIFIED BY SHA256')
print('Models                     : 13')
print('Training bundles to verify : 520')
print('P1 planned evaluations     : 520')
print('P2 planned evaluations     : 1560')
print('Training allowed           : FALSE')
print('Threshold tuning allowed   : FALSE')
print('Target retraining allowed  : FALSE')
print('TEST/target rows read yet  : FALSE')
print('-' * 140)

TRAINING_BUNDLE_INFO = {}
for i, row in enumerate(training_scope.itertuples(index=False), start=1):
    TRAINING_BUNDLE_INFO[str(row.run_id)] = verify_training_bundle(row)
    if i % 50 == 0 or i == 520:
        print(f'[TRAIN-BUNDLE VERIFY] {i:>3}/520 PASS', flush=True)

assert len(TRAINING_BUNDLE_INFO) == 520
print('Canonical training bundles : 520/520 VERIFIED')
print('TEST/target rows read yet  : FALSE')


# ============================================================================
# 6. DATA MATERIALIZATION HELPERS
# ============================================================================

def read_metadata_for_indices(indices: np.ndarray) -> pd.DataFrame:
    indices = np.asarray(indices, dtype=np.int64)
    wanted = set(indices.tolist())
    df = pd.read_csv(
        ROW_METADATA_PATH,
        low_memory=False,
        skiprows=lambda line_no: (line_no > 0 and (line_no - 1) not in wanted),
    )
    required = {'row_index', 'sample_id', 'dataset', 'split', 'label', 'sequence_length', 'sequence_sha256'}
    assert required.issubset(df.columns)
    assert len(df) == len(wanted)
    assert df['row_index'].astype(np.int64).is_unique
    return df.set_index(df['row_index'].astype(np.int64), drop=False)


def decode_cached_sequence(row_index: int, expected_length: int) -> str:
    tokens = np.asarray(X_TOKENS[int(row_index)], dtype=np.int64)
    nonpad = tokens[tokens != 0]
    assert len(nonpad) == int(expected_length)
    seq = ''.join(ID_TO_AA[int(t)] for t in nonpad.tolist())
    assert len(seq) == int(expected_length)
    return seq


def frame_from_key(key: str, meta_by_index: pd.DataFrame, *, expected_dataset=None) -> pd.DataFrame:
    assert key in INDEX.files, f'Unknown execution index key: {key}'
    idx = np.asarray(INDEX[key], dtype=np.int64)
    assert len(idx) > 0
    assert set(idx.tolist()).issubset(set(meta_by_index.index.astype(np.int64).tolist()))
    meta = meta_by_index.loc[idx].copy()
    assert meta['row_index'].astype(np.int64).tolist() == idx.tolist()
    seqs = []
    for r in meta.itertuples(index=False):
        seq = decode_cached_sequence(int(r.row_index), int(r.sequence_length))
        assert hashlib.sha256(seq.encode('utf-8')).hexdigest() == str(r.sequence_sha256)
        seqs.append(seq)
    out = pd.DataFrame({
        'sample_id': meta['sample_id'].astype(str).tolist(),
        'sequence': seqs,
        'label': meta['label'].astype(np.int8).tolist(),
        'dataset': meta['dataset'].astype(str).tolist(),
        'split': meta['split'].astype(str).tolist(),
        'row_index': idx,
        'length': meta['sequence_length'].astype(int).tolist(),
    })
    assert np.array_equal(out['label'].to_numpy(np.int8), np.asarray(Y[idx], dtype=np.int8))
    assert set(np.unique(out['label']).tolist()) == {0, 1}
    assert out['sequence'].map(lambda s: set(s).issubset(set('ACDEFGHIKLMNPQRSTVWY'))).all()
    assert out['length'].between(10, 200).all()
    if expected_dataset is not None:
        assert set(out['dataset'].astype(str)) == {str(expected_dataset)}
    return out.reset_index(drop=True)


# ============================================================================
# 7. METRICS - EXACT LOCKED DEFINITIONS
# ============================================================================

def binary_ece(y_true, y_score, n_bins=10):
    y_true = np.asarray(y_true, dtype=int)
    y_score = np.asarray(y_score, dtype=float)
    assert len(y_true) == len(y_score) and len(y_true) > 0
    assert np.isfinite(y_score).all()
    assert ((y_score >= 0.0) & (y_score <= 1.0)).all()
    edges = np.linspace(0.0, 1.0, n_bins + 1)
    ece = 0.0
    for i in range(n_bins):
        left, right = edges[i], edges[i + 1]
        mask = ((y_score >= left) & (y_score < right)) if i < n_bins - 1 else ((y_score >= left) & (y_score <= right))
        n_bin = int(mask.sum())
        if n_bin == 0:
            continue
        ece += (n_bin / len(y_true)) * abs(float(y_true[mask].mean()) - float(y_score[mask].mean()))
    return float(ece)


def compute_binary_metrics(y_true, y_score, tau):
    y_true = np.asarray(y_true, dtype=int)
    y_score = np.asarray(y_score, dtype=float)
    assert len(y_true) == len(y_score) and len(y_true) > 0
    assert set(np.unique(y_true).tolist()) == {0, 1}
    assert np.isfinite(y_score).all()
    assert ((y_score >= 0.0) & (y_score <= 1.0)).all()
    assert 0.0 <= float(tau) <= 1.0
    y_pred = (y_score >= float(tau)).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    sensitivity = tp / (tp + fn)
    specificity = tn / (tn + fp)
    return {
        'AUROC': float(roc_auc_score(y_true, y_score)),
        'AUPRC': float(average_precision_score(y_true, y_score)),
        'MCC': float(matthews_corrcoef(y_true, y_pred)),
        'BACC': float(balanced_accuracy_score(y_true, y_pred)),
        'F1': float(f1_score(y_true, y_pred, zero_division=0)),
        'ACC': float(accuracy_score(y_true, y_pred)),
        'Sensitivity': float(sensitivity),
        'Specificity': float(specificity),
        'Brier': float(brier_score_loss(y_true, y_score)),
        'ECE10': float(binary_ece(y_true, y_score, n_bins=10)),
        'threshold': float(tau),
        'TP': int(tp), 'TN': int(tn), 'FP': int(fp), 'FN': int(fn),
        'n': int(len(y_true)),
        'n_positive': int((y_true == 1).sum()),
        'n_negative': int((y_true == 0).sum()),
    }


def prediction_frame(eval_row, target_df, scores, tau):
    scores = np.asarray(scores, dtype=float).reshape(-1)
    assert scores.shape == (len(target_df),)
    assert np.isfinite(scores).all()
    assert ((scores >= 0.0) & (scores <= 1.0)).all()
    pred = (scores >= float(tau)).astype(np.int8)
    df = pd.DataFrame({
        'eval_id': str(eval_row['eval_id']),
        'run_id': str(eval_row['run_id']),
        'protocol': str(eval_row['protocol']),
        'model_id': str(eval_row['model_id']),
        'source_dataset': str(eval_row['source_dataset']),
        'target_dataset': str(eval_row['target_dataset']),
        'seed': int(eval_row['seed']),
        'sample_id': target_df['sample_id'].astype(str).tolist(),
        'y_true': target_df['label'].astype(np.int8).tolist(),
        'y_score': scores,
        'y_pred': pred,
        'threshold': float(tau),
    })
    assert list(df.columns) == PREDICTION_COLUMNS
    return df


# ============================================================================
# 8. MODEL-SPECIFIC INFERENCE LOADERS - NO TRAINING
# ============================================================================

# ---- Controlled classical --------------------------------------------------
def positive_probability(model, X):
    p = np.asarray(model.predict_proba(X), dtype=float)
    if hasattr(model, 'classes_'):
        classes = np.asarray(model.classes_)
    elif hasattr(model, 'named_steps'):
        classes = np.asarray(model.named_steps['model'].classes_)
    else:
        classes = np.asarray(model[-1].classes_)
    pos = int(np.where(classes == 1)[0][0])
    out = p[:, pos]
    assert np.isfinite(out).all() and ((out >= 0.0) & (out <= 1.0)).all()
    return out


# ---- AmPEP exact 105 Seq2Distribution representation ----------------------
AMPEP_PROPERTY_GROUPS = [
    ('charge', ['ACFGHILMNPQSTVWY', 'DE', 'KR']),
    ('hydrophobicity', ['CFILMVW', 'AGHPSTY', 'DEKNQR']),
    ('normalized_vander_waals', ['ACDGPST', 'EILNQV', 'FHKMRWY']),
    ('polarity', ['CFILMVWY', 'AGPST', 'DEHKNQR']),
    ('polarizability', ['ADGST', 'CEILNPQV', 'FHKMRWY']),
    ('secondary_structure', ['DGNPS', 'AEHKLMQR', 'CFITVWY']),
    ('solvent_accessibility', ['ACFGILVW', 'HMPSTY', 'DEKNRQ']),
]


def ampep_distribution_positions(pos, n):
    if not pos:
        return [0.0] * 5
    count = len(pos)
    out = [100.0 * pos[0] / n]
    for frac in [0.25, 0.50, 0.75]:
        k = math.floor(count * frac)
        selected = pos[0] if k == 0 else pos[k - 1]
        out.append(100.0 * selected / n)
    out.append(100.0 * pos[-1] / n)
    return out


def ampep_feature_vector(seq: str):
    seq = str(seq).strip().upper()
    n = len(seq)
    vals = []
    for _, groups in AMPEP_PROPERTY_GROUPS:
        for group in groups:
            positions = [i for i, aa in enumerate(seq, start=1) if aa in group]
            vals.extend(ampep_distribution_positions(positions, n))
    out = np.asarray(vals, dtype=np.float64)
    assert out.shape == (105,)
    return out


def ampep_matrix(df):
    return np.vstack([ampep_feature_vector(s) for s in df['sequence'].astype(str)])


# ---- Controlled deep GPU subprocess helper --------------------------------
DEEP_INFER_HELPER_TEXT = r'''from pathlib import Path
import csv, json, sys
import numpy as np
import tensorflow as tf

MODEL_ID=sys.argv[1]
CHECKPOINT=Path(sys.argv[2])
TOKEN_PATH=Path(sys.argv[3])
INDEX_PATH=Path(sys.argv[4])
CONTROLLED_CONTRACT=Path(sys.argv[5])
REQUEST=Path(sys.argv[6])
OUT=Path(sys.argv[7])
SEED=int(sys.argv[8])

gpus=tf.config.list_physical_devices('GPU')
assert gpus, 'GPU missing in controlled-deep evaluation helper'
for gpu in gpus:
    try: tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError: pass

tf.keras.utils.set_random_seed(SEED)
wrapper=json.load(open(CONTROLLED_CONTRACT,'r',encoding='utf-8'))
contract=wrapper['contract']
cfg=contract['model_configs'][MODEL_ID]['architecture']
K=tf.keras

class MaskedGlobalMaxPooling1D(K.layers.Layer):
    def call(self, inputs):
        x, mask = inputs
        mask = tf.cast(mask, x.dtype)
        masked = tf.where(tf.expand_dims(mask > 0, -1), x, tf.cast(-1e9, x.dtype))
        return tf.reduce_max(masked, axis=1)
class MaskedGlobalAveragePooling1D(K.layers.Layer):
    def call(self, inputs):
        x, mask = inputs
        mask = tf.cast(mask, x.dtype)
        num = tf.reduce_sum(x * tf.expand_dims(mask, -1), axis=1)
        den = tf.maximum(tf.reduce_sum(mask, axis=1, keepdims=True), tf.cast(1.0, x.dtype))
        return num / den
class MaskedAdditiveAttention(K.layers.Layer):
    def __init__(self, units, **kwargs):
        super().__init__(**kwargs)
        self.proj = K.layers.Dense(units, activation='tanh')
        self.score = K.layers.Dense(1, use_bias=False)
    def call(self, inputs):
        x, mask = inputs
        mask = tf.cast(mask, tf.bool)
        s = tf.squeeze(self.score(self.proj(x)), axis=-1)
        s = tf.where(mask, s, tf.cast(-1e9, s.dtype))
        a = tf.nn.softmax(s, axis=1)
        return tf.reduce_sum(x * tf.expand_dims(a, -1), axis=1)
class AddLearnedPositionEmbedding(K.layers.Layer):
    def __init__(self, max_positions, model_dim, **kwargs):
        super().__init__(**kwargs)
        self.pos_embedding = K.layers.Embedding(max_positions, model_dim)
    def call(self, x):
        positions = tf.range(start=0, limit=tf.shape(x)[1], delta=1)
        return x + self.pos_embedding(positions)

tokens=K.Input(shape=(200,),dtype='int32',name='tokens')
mask=K.layers.Lambda(lambda t: tf.not_equal(t,0),name='padding_mask')(tokens)
if MODEL_ID=='cnn1d':
    x=K.layers.Embedding(21,int(cfg['embedding_dim']),mask_zero=True)(tokens)
    x=K.layers.Conv1D(int(cfg['conv1_filters']),int(cfg['conv1_kernel_size']),padding='same',activation='relu')(x)
    x=K.layers.Conv1D(int(cfg['conv2_filters']),int(cfg['conv2_kernel_size']),padding='same',activation='relu')(x)
    x=MaskedGlobalMaxPooling1D()([x,mask])
    x=K.layers.Dense(int(cfg['dense_units']),activation='relu')(x)
    x=K.layers.Dropout(float(cfg['dropout']))(x)
    out=K.layers.Dense(1,activation='sigmoid')(x)
elif MODEL_ID=='bilstm':
    x=K.layers.Embedding(21,int(cfg['embedding_dim']),mask_zero=True)(tokens)
    x=K.layers.Bidirectional(K.layers.LSTM(int(cfg['bilstm_units_per_direction']),return_sequences=False,dropout=float(cfg['lstm_dropout']),recurrent_dropout=float(cfg['recurrent_dropout'])))(x)
    x=K.layers.Dense(int(cfg['dense_units']),activation='relu')(x)
    x=K.layers.Dropout(float(cfg['dense_dropout']))(x)
    out=K.layers.Dense(1,activation='sigmoid')(x)
elif MODEL_ID=='bilstm_attention':
    x=K.layers.Embedding(21,int(cfg['embedding_dim']),mask_zero=True)(tokens)
    x=K.layers.Bidirectional(K.layers.LSTM(int(cfg['bilstm_units_per_direction']),return_sequences=True,dropout=float(cfg['lstm_dropout']),recurrent_dropout=float(cfg['recurrent_dropout'])))(x)
    x=MaskedAdditiveAttention(int(cfg['attention_units']))([x,mask])
    x=K.layers.Dense(int(cfg['dense_units']),activation='relu')(x)
    x=K.layers.Dropout(float(cfg['dense_dropout']))(x)
    out=K.layers.Dense(1,activation='sigmoid')(x)
elif MODEL_ID=='transformer_encoder':
    d=int(cfg['model_dimension'])
    tok=K.layers.Embedding(21,d,mask_zero=True)(tokens)
    x=AddLearnedPositionEmbedding(200,d,name='position_embedding')(tok)
    attn_mask=K.layers.Lambda(lambda m: tf.expand_dims(m,axis=1),name='attention_mask')(mask)
    for block in range(int(cfg['n_encoder_blocks'])):
        attn=K.layers.MultiHeadAttention(num_heads=int(cfg['num_attention_heads']),key_dim=int(cfg['key_dim_per_head']),dropout=float(cfg['attention_dropout']),name='mha_%d'%(block+1))(x,x,attention_mask=attn_mask)
        x=K.layers.LayerNormalization(name='attn_ln_%d'%(block+1))(x+attn)
        ff=K.layers.Dense(int(cfg['feed_forward_dimension']),activation='relu')(x)
        ff=K.layers.Dropout(float(cfg['feed_forward_dropout']))(ff)
        ff=K.layers.Dense(d)(ff)
        x=K.layers.LayerNormalization(name='ff_ln_%d'%(block+1))(x+ff)
    x=MaskedGlobalAveragePooling1D()([x,mask])
    x=K.layers.Dense(int(cfg['dense_units']),activation='relu')(x)
    x=K.layers.Dropout(float(cfg['dense_dropout']))(x)
    out=K.layers.Dense(1,activation='sigmoid')(x)
else:
    raise KeyError(MODEL_ID)
model=K.Model(tokens,out,name=MODEL_ID)
model.load_weights(str(CHECKPOINT))
X=np.load(TOKEN_PATH,mmap_mode='r',allow_pickle=False)
IDX=np.load(INDEX_PATH,allow_pickle=False)
req=json.load(open(REQUEST,'r',encoding='utf-8'))
with open(str(OUT),'w',newline='') as fh:
    w=csv.writer(fh); w.writerow(['eval_id','row_pos','y_score'])
    for item in req:
        key=item['target_index_key']; eval_id=item['eval_id']; idx=np.asarray(IDX[key],dtype=np.int64)
        score=np.asarray(model.predict(np.asarray(X[idx],dtype=np.int32),batch_size=256,verbose=0),dtype=float).reshape(-1)
        assert len(score)==len(idx); assert np.isfinite(score).all(); assert ((score>=0.0)&(score<=1.0)).all()
        for j,v in enumerate(score.tolist()): w.writerow([eval_id,j,repr(float(v))])
'''

DEEP_HELPER_PATH = HELPER_ROOT / 'controlled_deep_inference_v1.py'
DEEP_HELPER_SHA = lock_helper(DEEP_HELPER_PATH, DEEP_INFER_HELPER_TEXT)


def locked_tensorflow_subprocess_env(seed=None):
    assert CUDA_PATHS_FILE.is_file(), f'Missing CUDA path manifest: {CUDA_PATHS_FILE}'
    assert ENVIRONMENT_AUDIT_PATH.is_file(), f'Missing environment audit: {ENVIRONMENT_AUDIT_PATH}'
    cuda_payload = load_json(CUDA_PATHS_FILE)
    env_audit = load_json(ENVIRONMENT_AUDIT_PATH)
    dirs = [str(x) for x in cuda_payload.get('cuda_library_dirs', [])]
    assert len(dirs) > 1
    for d in dirs:
        assert Path(d).is_dir(), f'Locked CUDA library dir missing: {d}'
    assert int(env_audit['tensorflow']['gpu_count']) >= 1
    assert env_audit['tensorflow']['is_cuda_build'] is True
    env = os.environ.copy()
    old = env.get('LD_LIBRARY_PATH', '')
    parts = list(dirs) + ([old] if old else [])
    env['LD_LIBRARY_PATH'] = ':'.join(dict.fromkeys(parts))
    env['CUDA_VISIBLE_DEVICES'] = '0'
    env['TF_CPP_MIN_LOG_LEVEL'] = '2'
    env['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'
    if seed is not None:
        env['PYTHONHASHSEED'] = str(int(seed))
    return env


def verify_controlled_deep_gpu():
    code = """
import json, tensorflow as tf
gpus=tf.config.list_physical_devices('GPU')
assert gpus, 'GPU unavailable'
for gpu in gpus:
    try: tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError: pass
with tf.device('/GPU:0'):
    x=tf.constant([1.,2.,3.]); y=tf.reduce_sum(x*2.)
assert float(y.numpy())==12.0
print(json.dumps({'tensorflow':tf.__version__,'gpu_count':len(gpus),'gpu':str(gpus[0])}))
"""
    r = run_cmd([Path(os.sys.executable).resolve(), '-c', code], env=locked_tensorflow_subprocess_env(), timeout=120, label='controlled-deep GPU preflight')
    lines = [x for x in r.stdout.splitlines() if x.strip()]
    assert lines
    return json.loads(lines[-1])


def deep_predict_requests(model_id, checkpoint, seed, request_rows):
    tmp_dir = Path(tempfile.mkdtemp(prefix='cell33_deep_', dir=str(SELFTEST_ROOT if str(request_rows[0]['eval_id']).startswith('SELFTEST') else EVAL_ROOT)))
    try:
        req_path = tmp_dir / 'request.json'
        out_path = tmp_dir / 'scores.csv'
        atomic_write_json(req_path, request_rows)
        t0 = time.perf_counter()
        run_cmd(
            [
                Path(os.sys.executable).resolve(), DEEP_HELPER_PATH, model_id, checkpoint,
                TOKEN_CACHE_PATH, index_path, CONTROLLED_CONTRACT_PATH, req_path, out_path, int(seed),
            ],
            env=locked_tensorflow_subprocess_env(seed), timeout=7200,
            label=f'deep inference {model_id}',
        )
        wall = time.perf_counter() - t0
        pred = read_csv_exact(out_path)
        result = {}
        for item in request_rows:
            sub = pred[pred['eval_id'].astype(str).eq(str(item['eval_id']))].copy()
            sub['row_pos'] = pd.to_numeric(sub['row_pos'], errors='raise').astype(int)
            sub = sub.sort_values('row_pos')
            scores = pd.to_numeric(sub['y_score'], errors='raise').to_numpy(float)
            assert len(scores) == int(item['target_n'])
            result[str(item['eval_id'])] = scores
        return result, wall
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


# ---- AMPScannerV2 legacy TF1 inference helper ------------------------------
AMPSCANNER_INFER_HELPER_TEXT = r'''from pathlib import Path
import csv, importlib.util, os, sys
os.environ['KERAS_BACKEND']='tensorflow'; os.environ['CUDA_VISIBLE_DEVICES']=''; os.environ['OMP_NUM_THREADS']='1'; os.environ['MKL_NUM_THREADS']='1'; os.environ['NUMEXPR_NUM_THREADS']='1'; os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import numpy as np, tensorflow as tf, keras
from Bio import SeqIO
from keras import backend as K
from keras.preprocessing import sequence
from keras.models import load_model
SOURCE=Path(sys.argv[1]); MODEL=Path(sys.argv[2]); EVAL=Path(sys.argv[3]); OUT=Path(sys.argv[4])
assert sys.version_info[:2]==(3,6); assert tf.__version__=='1.2.1'; assert keras.__version__=='2.0.6'
K.set_session(tf.Session(config=tf.ConfigProto(intra_op_parallelism_threads=1,inter_op_parallelism_threads=1,device_count={'GPU':0})))
spec=importlib.util.spec_from_file_location('amp_scanner_eval',str(SOURCE)); mod=importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
def seqs(path): return [(r.id,str(r.seq)) for r in SeqIO.parse(str(path),'fasta')]
def enc(records): return sequence.pad_sequences([[mod.aa2int[a] for a in s] for _,s in records],maxlen=200)
ev=seqs(EVAL); XE=enc(ev)
try: model=load_model(str(MODEL),compile=False)
except TypeError: model=load_model(str(MODEL))
score=np.asarray(model.predict(XE,batch_size=32,verbose=0),dtype=float).reshape(-1)
assert len(score)==len(ev); assert np.isfinite(score).all(); assert ((score>=0.0)&(score<=1.0)).all()
with open(str(OUT),'w',newline='') as fh:
    w=csv.writer(fh); w.writerow(['internal_id','y_score'])
    for (sid,_),v in zip(ev,score): w.writerow([sid,repr(float(v))])
'''

AMPSCANNER_HELPER_PATH = HELPER_ROOT / 'ampscannerv2_inference_v1.py'
AMPSCANNER_HELPER_SHA = lock_helper(AMPSCANNER_HELPER_PATH, AMPSCANNER_INFER_HELPER_TEXT)
AMPSCANNER_SOURCE = Path('/home/pc/genpept_sources/amp-scanner-v2_933052e2365631fe93098892120ee535e0ba381a') / 'amp_scanner_v2_train_tf1.py'
AMPSCANNER_PY = Path.home() / 'miniconda3/envs/genpept_ampscannerv2_orig/bin/python'
assert AMPSCANNER_SOURCE.is_file() and AMPSCANNER_PY.is_file()


# ---- amPEPpy v1.0 inference helper ----------------------------------------
AMPEPPY_INFER_HELPER_TEXT = r'''from pathlib import Path
from types import SimpleNamespace
import os, sys
import pandas as pd
SOURCE=Path(sys.argv[1]); MODEL=Path(sys.argv[2]); EVAL=Path(sys.argv[3]); OUT=Path(sys.argv[4]); TMP=Path(sys.argv[5]); TMP.mkdir(parents=True,exist_ok=True)
assert '.'.join(str(x) for x in sys.version_info[:3])=='3.8.3'
sys.path.insert(0,str(SOURCE)); from amPEPpy import amPEP as mod; from amPEPpy._version import __version__; assert __version__=='1.0'
raw=TMP/'raw_predictions.tsv'
mod.predict(SimpleNamespace(model=str(MODEL),seq_file=str(EVAL),out_file=str(raw),drop_feature=None))
p=pd.read_csv(raw,sep='\t'); assert 'probability_AMP' in p.columns and 'seq_id' in p.columns
pd.DataFrame({'internal_id':p['seq_id'].astype(str),'y_score':p['probability_AMP'].astype(float)}).to_csv(OUT,index=False)
'''

AMPEPPY_HELPER_PATH = HELPER_ROOT / 'ampeppy_inference_v1.py'
AMPEPPY_HELPER_SHA = lock_helper(AMPEPPY_HELPER_PATH, AMPEPPY_INFER_HELPER_TEXT)
AMPEPPY_SOURCE = Path('/home/pc/genpept_sources/amPEPpy_v1.0_aa1f694c6cb3d09b16bc9378bed77f59e4f1e780')
AMPEPPY_PY = Path.home() / 'miniconda3/envs/genpept_ampeppy_v1/bin/python'
assert AMPEPPY_SOURCE.is_dir() and AMPEPPY_PY.is_file()


def write_combined_fasta(requests_with_df, path: Path):
    mapping = []
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        counter = 0
        for req, df in requests_with_df:
            for pos, r in enumerate(df.itertuples(index=False)):
                internal = f'E{counter:09d}'
                counter += 1
                f.write(f'>{internal}\n{str(r.sequence)}\n')
                mapping.append((internal, str(req['eval_id']), int(pos)))
    return pd.DataFrame(mapping, columns=['internal_id', 'eval_id', 'row_pos'])


def legacy_predict_requests(model_id, checkpoint, requests_with_df):
    tmp_dir = Path(tempfile.mkdtemp(prefix=f'cell33_{model_id}_', dir=str(EVAL_ROOT)))
    try:
        fasta = tmp_dir / 'combined_eval.fa'
        out = tmp_dir / 'scores.csv'
        mapping = write_combined_fasta(requests_with_df, fasta)
        t0 = time.perf_counter()
        if model_id == 'ampscannerv2':
            run_cmd([AMPSCANNER_PY, AMPSCANNER_HELPER_PATH, AMPSCANNER_SOURCE, checkpoint, fasta, out], timeout=7200, label='AMPScannerV2 checkpoint inference')
        elif model_id == 'ampeppy':
            run_cmd([AMPEPPY_PY, AMPEPPY_HELPER_PATH, AMPEPPY_SOURCE, checkpoint, fasta, out, tmp_dir], timeout=7200, label='amPEPpy checkpoint inference')
        else:
            raise KeyError(model_id)
        wall = time.perf_counter() - t0
        pred = read_csv_exact(out)
        pred['internal_id'] = pred['internal_id'].astype(str)
        merged = mapping.merge(pred[['internal_id', 'y_score']], on='internal_id', how='left', validate='one_to_one')
        assert merged['y_score'].astype(str).ne('').all()
        merged['y_score'] = pd.to_numeric(merged['y_score'], errors='raise')
        result = {}
        for req, df in requests_with_df:
            sub = merged[merged['eval_id'].astype(str).eq(str(req['eval_id']))].sort_values('row_pos')
            scores = sub['y_score'].to_numpy(float)
            assert len(scores) == len(df)
            assert np.isfinite(scores).all() and ((scores >= 0.0) & (scores <= 1.0)).all()
            result[str(req['eval_id'])] = scores
        return result, wall
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


# ============================================================================
# 9. CHECKPOINT-RELOAD EQUIVALENCE SELF-TEST - VALIDATION ONLY
#    NO TEST/TARGET ROWS ARE MATERIALIZED BEFORE THIS PASSES.
# ============================================================================

# Pick exactly one predeclared representative run per model: first source dataset, seed 100.
rep_rows = []
for model_id in FINAL13_MODEL_IDS:
    m = training_scope[
        training_scope['model_id'].astype(str).eq(model_id)
        & training_scope['source_dataset'].astype(str).eq(EXPECTED_DATASETS[0])
        & pd.to_numeric(training_scope['seed'], errors='raise').astype(int).eq(100)
    ]
    assert len(m) == 1
    rep_rows.append(m.iloc[0].to_dict())

validation_keys = [str(r['validation_index_key']) for r in rep_rows]
validation_indices = np.unique(np.concatenate([np.asarray(INDEX[k], dtype=np.int64) for k in validation_keys]))
VALIDATION_META = read_metadata_for_indices(validation_indices)
assert not VALIDATION_META['split'].astype(str).eq('test').any()

# Controlled deep GPU availability must match locked training environment.
GPU_INFO = verify_controlled_deep_gpu()
print('Controlled-deep GPU       : PASS -', GPU_INFO)

selftest_rows = []
for i, rep in enumerate(rep_rows, start=1):
    run_id = str(rep['run_id'])
    model_id = str(rep['model_id'])
    info = TRAINING_BUNDLE_INFO[run_id]
    val_df = frame_from_key(str(rep['validation_index_key']), VALIDATION_META, expected_dataset=str(rep['source_dataset']))
    saved = read_csv_exact(Path(str(rep['run_dir'])) / 'validation_predictions.csv')
    assert saved['sample_id'].astype(str).tolist() == val_df['sample_id'].astype(str).tolist()
    expected = pd.to_numeric(saved['y_score'], errors='raise').to_numpy(float)

    t0 = time.perf_counter()
    if model_id in CONTROLLED_CLASSICAL:
        with open(info['checkpoint'], 'rb') as f:
            model = pickle.load(f)
        idx = val_df['row_index'].to_numpy(np.int64)
        observed = positive_probability(model, np.asarray(X_CLASSICAL[idx], dtype=np.float32))
        del model
    elif model_id in CONTROLLED_DEEP:
        req = [{'eval_id': f'SELFTEST__{model_id}', 'target_index_key': str(rep['validation_index_key']), 'target_n': len(val_df)}]
        observed = deep_predict_requests(model_id, info['checkpoint'], int(rep['seed']), req)[0][req[0]['eval_id']]
    elif model_id == 'ampep':
        with open(info['checkpoint'], 'rb') as f:
            model = pickle.load(f)
        observed = positive_probability(model, ampep_matrix(val_df))
        del model
    elif model_id in {'ampscannerv2', 'ampeppy'}:
        req = {'eval_id': f'SELFTEST__{model_id}', 'target_index_key': str(rep['validation_index_key']), 'target_n': len(val_df)}
        observed = legacy_predict_requests(model_id, info['checkpoint'], [(req, val_df)])[0][req['eval_id']]
    else:
        raise KeyError(model_id)

    elapsed = time.perf_counter() - t0
    observed = np.asarray(observed, dtype=float).reshape(-1)
    assert observed.shape == expected.shape
    max_abs = float(np.max(np.abs(observed - expected))) if len(expected) else 0.0
    mean_abs = float(np.mean(np.abs(observed - expected))) if len(expected) else 0.0

    # ----------------------------------------------------------------------
    # Reload-equivalence policy
    # ----------------------------------------------------------------------
    # Classical / legacy CPU paths are expected to reproduce stored
    # validation scores at tight floating-point tolerance.
    #
    # Controlled deep models were trained and scored on GPU in the original
    # worker. Rebuilding the exact locked architecture in a fresh TensorFlow
    # GPU process can produce sub-millipercentage float32 differences because
    # CUDA/cuDNN kernel selection/reduction order is not bitwise reproducible
    # across processes. This is NOT a scientific-protocol change: checkpoint,
    # architecture, data indices, source-validation threshold and weights are
    # all already SHA-verified above.
    #
    # For controlled deep models the reload gate tests functional equivalence
    # at the frozen decision rule, not bitwise/rank identity across GPU processes.
    # Required:
    #   1) very small score drift (max <= 1e-3; mean <= 1e-4), and
    #   2) identical frozen-threshold class decisions on validation.
    # AUROC/AUPRC drift is recorded as a diagnostic only. Tiny float32 score
    # perturbations can swap nearly tied ranks and therefore change AUROC/AP
    # slightly even when the checkpoint function is materially unchanged.
    # Any threshold flip or score drift beyond the predeclared bounds FAILS
    # CLOSED before TEST/target rows are read.
    strict_score_close = bool(np.allclose(observed, expected, rtol=1e-5, atol=1e-6))
    tau = float(info['tau'])
    y_true_val = val_df['label'].to_numpy(int)
    expected_pred = (expected >= tau).astype(np.int8)
    observed_pred = (observed >= tau).astype(np.int8)
    hard_prediction_identical = bool(np.array_equal(expected_pred, observed_pred))

    expected_rank = {
        'AUROC': float(roc_auc_score(y_true_val, expected)),
        'AUPRC': float(average_precision_score(y_true_val, expected)),
    }
    observed_rank = {
        'AUROC': float(roc_auc_score(y_true_val, observed)),
        'AUPRC': float(average_precision_score(y_true_val, observed)),
    }
    auroc_abs_diff = abs(expected_rank['AUROC'] - observed_rank['AUROC'])
    auprc_abs_diff = abs(expected_rank['AUPRC'] - observed_rank['AUPRC'])
    rank_metric_max_abs_diff = float(max(auroc_abs_diff, auprc_abs_diff))

    if model_id in CONTROLLED_DEEP:
        score_drift_bounded = bool(max_abs <= 1e-3 and mean_abs <= 1e-4)
        rank_metrics_invariant = None  # diagnostic only for controlled deep models
        passed = bool(score_drift_bounded and hard_prediction_identical)
        equivalence_mode = 'controlled_deep_gpu_bounded_score_and_frozen_decision_equivalence'
    else:
        score_drift_bounded = strict_score_close
        rank_metrics_invariant = bool(rank_metric_max_abs_diff <= 1e-12)
        passed = bool(strict_score_close and hard_prediction_identical and rank_metrics_invariant)
        equivalence_mode = 'tight_score_equivalence'

    selftest_rows.append({
        'model_id': model_id,
        'run_id': run_id,
        'source_dataset': str(rep['source_dataset']),
        'seed': int(rep['seed']),
        'validation_n': int(len(expected)),
        'equivalence_mode': equivalence_mode,
        'max_abs_score_diff': max_abs,
        'mean_abs_score_diff': mean_abs,
        'strict_rtol': 1e-5,
        'strict_atol': 1e-6,
        'deep_max_abs_limit': 1e-3 if model_id in CONTROLLED_DEEP else None,
        'deep_mean_abs_limit': 1e-4 if model_id in CONTROLLED_DEEP else None,
        'hard_prediction_identical': hard_prediction_identical,
        'auroc_abs_diff': float(auroc_abs_diff),
        'auprc_abs_diff': float(auprc_abs_diff),
        'rank_metric_max_abs_diff': rank_metric_max_abs_diff,
        'rank_metric_gate_applied': bool(model_id not in CONTROLLED_DEEP),
        'PASS': passed,
        'seconds': float(elapsed),
    })
    print(
        f'[LOADER SELFTEST {i:02d}/13] {model_id:<26} PASS={passed} '
        f'mode={equivalence_mode} max_abs={max_abs:.3e} mean_abs={mean_abs:.3e} '
        f'hard_same={hard_prediction_identical} rank_delta={rank_metric_max_abs_diff:.3e} '
        f'rank_gate={model_id not in CONTROLLED_DEEP} wall={elapsed:.2f}s',
        flush=True,
    )
    assert passed, (
        f'Checkpoint-reload equivalence FAILED for {model_id}.\n'
        f'mode={equivalence_mode} max_abs={max_abs} mean_abs={mean_abs}\n'
        f'hard_prediction_identical={hard_prediction_identical} '
        f'AUROC_abs_diff={auroc_abs_diff} AUPRC_abs_diff={auprc_abs_diff}\n'
        f'rank_metric_gate_applied={model_id not in CONTROLLED_DEEP}\n'
        'Cell 33 refuses to read TEST/target rows until this is resolved.'
    )
    gc.collect()

selftest_df = pd.DataFrame(selftest_rows)
atomic_write_csv(CELL33_SELFTEST_PATH, selftest_df)
assert len(selftest_df) == 13 and selftest_df['PASS'].eq(True).all()

TEST_TARGET_GATE_OPEN = True
assert TEST_TARGET_GATE_OPEN is True
print('-' * 140)
print('CHECKPOINT RELOAD GATE     : PASS 13/13 ON SOURCE VALIDATION')
print('TEST/TARGET ACCESS GATE    : OPEN FOR FINAL LOCKED EVALUATION ONLY')
print('-' * 140)


# ============================================================================
# 10. BUILD 2,080-ROW EVALUATION LEDGER IDENTITY
# ============================================================================

p1_eval = p1_plan.copy()
p1_eval['eval_id'] = p1_eval.apply(lambda r: f"P1__{r['run_id']}__{r['target_dataset']}", axis=1)
p1_eval['output_dir'] = p1_eval.apply(lambda r: str(P1_ROOT / str(r['run_id'])), axis=1)

p2_eval = p2_plan.copy()
p2_eval['eval_id'] = p2_eval.apply(lambda r: f"P2__{r['run_id']}__TO__{r['target_dataset']}", axis=1)
p2_eval['output_dir'] = p2_eval.apply(lambda r: str(P2_ROOT / str(r['run_id']) / str(r['target_dataset'])), axis=1)

common_cols = [
    'eval_id', 'protocol', 'run_id', 'model_id', 'model_group', 'source_dataset',
    'target_dataset', 'seed', 'target_index_key', 'target_n', 'output_dir',
]
identity = pd.concat([p1_eval[common_cols], p2_eval[common_cols]], ignore_index=True)
identity.insert(0, 'ledger_no', range(1, len(identity) + 1))
assert len(identity) == 2080 and identity['eval_id'].is_unique
assert identity.groupby('run_id').size().eq(4).all()

ledger_cols = list(identity.columns) + ['status', 'finished_at', 'eval_manifest', 'last_error']
if EVAL_LEDGER_PATH.is_file():
    eval_ledger = read_csv_exact(EVAL_LEDGER_PATH)
    assert list(eval_ledger.columns) == ledger_cols
    pd.testing.assert_frame_equal(
        eval_ledger[list(identity.columns)].reset_index(drop=True),
        identity.reset_index(drop=True), check_dtype=False,
    )
else:
    eval_ledger = identity.copy()
    eval_ledger['status'] = 'PLANNED'
    eval_ledger['finished_at'] = ''
    eval_ledger['eval_manifest'] = ''
    eval_ledger['last_error'] = ''
    eval_ledger = eval_ledger[ledger_cols]
    atomic_write_csv(EVAL_LEDGER_PATH, eval_ledger)


# ============================================================================
# 11. TARGET METADATA - FIRST TEST/TARGET ROW ACCESS IN CELL 33
# ============================================================================

assert TEST_TARGET_GATE_OPEN
all_target_keys = identity['target_index_key'].astype(str).drop_duplicates().tolist()
for k in all_target_keys:
    assert k in INDEX.files, f'Missing target index key: {k}'
TARGET_INDICES = np.unique(np.concatenate([np.asarray(INDEX[k], dtype=np.int64) for k in all_target_keys]))
TARGET_META = read_metadata_for_indices(TARGET_INDICES)
# Every evaluation target is a held-out test row from its own dataset.
assert set(TARGET_META['split'].astype(str).unique()) == {'test'}
print(f'TEST/target rows materialized: TRUE ({len(TARGET_META):,} unique indexed rows across locked P1/P2 targets)')

TARGET_FRAME_CACHE = {}

def get_target_frame(eval_row):
    key = str(eval_row['target_index_key'])
    if key not in TARGET_FRAME_CACHE:
        df = frame_from_key(key, TARGET_META, expected_dataset=str(eval_row['target_dataset']))
        assert len(df) == int(eval_row['target_n'])
        TARGET_FRAME_CACHE[key] = df
    return TARGET_FRAME_CACHE[key]


# ============================================================================
# 12. RESTART-SAFE EVALUATION BUNDLE VALIDATION / COMMIT
# ============================================================================

def bundle_valid(eval_row) -> bool:
    out_dir = Path(str(eval_row['output_dir']))
    mp = out_dir / 'eval_manifest.json'
    if not mp.is_file():
        return False
    try:
        m = load_json(mp)
        assert m['status'] == 'EVALUATED'
        for field in ['eval_id', 'run_id', 'protocol', 'model_id', 'source_dataset', 'target_dataset']:
            assert str(m[field]) == str(eval_row[field])
        assert int(m['seed']) == int(eval_row['seed'])
        assert str(m['target_index_key']) == str(eval_row['target_index_key'])
        assert int(m['target_n']) == int(eval_row['target_n'])
        assert m['training_performed'] is False
        assert m['target_retraining'] is False
        assert m['target_threshold_tuning'] is False
        train_info = TRAINING_BUNDLE_INFO[str(eval_row['run_id'])]
        assert m['source_training_manifest_sha256'] == train_info['manifest_sha256']
        assert m['source_checkpoint_sha256'] == train_info['checkpoint_sha256']
        assert m['source_validation_threshold_sha256'] == train_info['threshold_sha256']
        for rel, entry in m['artifacts'].items():
            p = out_dir / rel
            assert p.is_file()
            assert int(p.stat().st_size) == int(entry['size_bytes'])
            assert sha256_file(p) == str(entry['sha256'])
        return True
    except Exception:
        return False


def commit_eval_bundle(eval_row, target_df, scores, tau, timing):
    final_dir = Path(str(eval_row['output_dir']))
    if final_dir.exists():
        if bundle_valid(eval_row):
            return final_dir / 'eval_manifest.json'
        raise AssertionError(f'Existing final evaluation directory is invalid; refusing overwrite: {final_dir}')

    final_dir.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=final_dir.name + '.cell33_staging.', dir=str(final_dir.parent)))
    try:
        pred = prediction_frame(eval_row, target_df, scores, tau)
        metrics = compute_binary_metrics(target_df['label'].to_numpy(int), np.asarray(scores, float), tau)
        assert metrics['n'] == int(eval_row['target_n'])

        pred_path = staging / 'predictions.csv'
        metrics_path = staging / 'metrics.json'
        resources_path = staging / 'resources.json'
        atomic_write_csv(pred_path, pred)
        atomic_write_json(metrics_path, {
            'eval_id': str(eval_row['eval_id']),
            'protocol': str(eval_row['protocol']),
            'run_id': str(eval_row['run_id']),
            'model_id': str(eval_row['model_id']),
            'source_dataset': str(eval_row['source_dataset']),
            'target_dataset': str(eval_row['target_dataset']),
            'seed': int(eval_row['seed']),
            'target_index_key': str(eval_row['target_index_key']),
            'threshold_source': 'source_validation_only_frozen',
            'metrics': metrics,
        })
        atomic_write_json(resources_path, {
            'eval_id': str(eval_row['eval_id']),
            'model_id': str(eval_row['model_id']),
            'source_dataset': str(eval_row['source_dataset']),
            'target_dataset': str(eval_row['target_dataset']),
            'seed': int(eval_row['seed']),
            **timing,
            'peak_parent_process_ram_mb': float(process_peak_ram_mb()),
        })

        train_info = TRAINING_BUNDLE_INFO[str(eval_row['run_id'])]
        manifest = {
            'status': 'EVALUATED',
            'evaluated_at': now_iso(),
            'benchmark_version': 'benchmark4_FINAL_v1',
            'final_scope': 'benchmark13_FINAL',
            'eval_id': str(eval_row['eval_id']),
            'run_id': str(eval_row['run_id']),
            'protocol': str(eval_row['protocol']),
            'model_id': str(eval_row['model_id']),
            'source_dataset': str(eval_row['source_dataset']),
            'target_dataset': str(eval_row['target_dataset']),
            'seed': int(eval_row['seed']),
            'target_index_key': str(eval_row['target_index_key']),
            'target_n': int(eval_row['target_n']),
            'training_performed': False,
            'target_retraining': False,
            'target_finetuning': False,
            'target_threshold_tuning': False,
            'target_threshold_recalibration': False,
            'threshold_source': 'source_validation_only_frozen',
            'threshold': float(tau),
            'source_training_manifest': str(train_info['manifest_path']),
            'source_training_manifest_sha256': train_info['manifest_sha256'],
            'source_checkpoint': str(train_info['checkpoint']),
            'source_checkpoint_sha256': train_info['checkpoint_sha256'],
            'source_validation_threshold': str(train_info['threshold_path']),
            'source_validation_threshold_sha256': train_info['threshold_sha256'],
            'cell32b_scope_manifest_sha256': EXPECTED_SCOPE_MANIFEST_SHA,
            'evaluation_contract_sha256': sha256_file(EVALUATION_CONTRACT_PATH),
            'execution_index_sha256': sha256_file(index_path),
            'artifacts': {
                'predictions.csv': artifact_entry(pred_path),
                'metrics.json': artifact_entry(metrics_path),
                'resources.json': artifact_entry(resources_path),
            },
        }
        atomic_write_json(staging / 'eval_manifest.json', manifest)
        os.replace(staging, final_dir)
        staging = None
        assert bundle_valid(eval_row)
        return final_dir / 'eval_manifest.json'
    finally:
        if staging is not None and staging.exists():
            failed = Path(str(staging) + '.FAILED')
            if not failed.exists():
                os.replace(staging, failed)


def update_eval_ledger(eval_id, *, status, manifest='', error=''):
    global eval_ledger
    mask = eval_ledger['eval_id'].astype(str).eq(str(eval_id))
    assert int(mask.sum()) == 1
    eval_ledger.loc[mask, 'status'] = status
    eval_ledger.loc[mask, 'finished_at'] = now_iso() if status == 'EVALUATED' else ''
    eval_ledger.loc[mask, 'eval_manifest'] = str(manifest)
    eval_ledger.loc[mask, 'last_error'] = str(error)
    atomic_write_csv(EVAL_LEDGER_PATH, eval_ledger)


# Reconcile ledger against committed evaluation bundles.
eval_by_id = {str(r.eval_id): r._asdict() for r in identity.itertuples(index=False)}
reconciled = 0
for eval_id, row in eval_by_id.items():
    valid = bundle_valid(row)
    mask = eval_ledger['eval_id'].astype(str).eq(eval_id)
    current = str(eval_ledger.loc[mask, 'status'].iloc[0])
    if valid and current != 'EVALUATED':
        update_eval_ledger(eval_id, status='EVALUATED', manifest=str(Path(row['output_dir']) / 'eval_manifest.json'))
        reconciled += 1
    elif (not valid) and current == 'EVALUATED':
        raise AssertionError(f'Ledger claims EVALUATED but valid bundle is missing/corrupt: {eval_id}')

completed_start = int(eval_ledger['status'].astype(str).eq('EVALUATED').sum())
print('Evaluation bundles reconciled:', reconciled)
print('Already EVALUATED             :', completed_start, '/ 2080')


# ============================================================================
# 13. EVALUATION EXECUTION - GROUPED BY FROZEN TRAINING RUN
# ============================================================================

# Optional operational cap: number of TRAINING-RUN groups this invocation.
# 0 = all remaining. This never changes scientific scope/configuration.
MAX_RUN_GROUPS = int(os.environ.get('GENPEPT_CELL33_MAX_RUN_GROUPS', '0'))
assert MAX_RUN_GROUPS >= 0

AMPEP_FEATURE_CACHE = {}

def get_ampep_features(eval_row, target_df):
    key = str(eval_row['target_index_key'])
    if key not in AMPEP_FEATURE_CACHE:
        AMPEP_FEATURE_CACHE[key] = ampep_matrix(target_df)
    return AMPEP_FEATURE_CACHE[key]

# Group identity rows by run_id preserving locked training-scope order.
rows_by_run = {rid: [] for rid in training_scope['run_id'].astype(str).tolist()}
for r in identity.itertuples(index=False):
    rows_by_run[str(r.run_id)].append(r._asdict())
for rid, rows in rows_by_run.items():
    assert len(rows) == 4
    assert sum(str(r['protocol']).startswith('P1') for r in rows) == 1
    assert sum(str(r['protocol']).startswith('P2') for r in rows) == 3

run_order = training_scope['run_id'].astype(str).tolist()
pending_run_ids = []
for rid in run_order:
    if any(not bundle_valid(r) for r in rows_by_run[rid]):
        pending_run_ids.append(rid)

if MAX_RUN_GROUPS > 0:
    pending_run_ids = pending_run_ids[:MAX_RUN_GROUPS]

start_wall = time.perf_counter()
new_evals = 0
new_run_groups = 0

try:
    for group_no, run_id in enumerate(pending_run_ids, start=1):
        run_row_df = training_scope[training_scope['run_id'].astype(str).eq(run_id)]
        assert len(run_row_df) == 1
        run_row = run_row_df.iloc[0].to_dict()
        model_id = str(run_row['model_id'])
        info = TRAINING_BUNDLE_INFO[run_id]
        tau = float(info['tau'])
        rows = [r for r in rows_by_run[run_id] if not bundle_valid(r)]
        if not rows:
            continue

        # Materialize all pending target frames for this source run.
        req_with_df = [(r, get_target_frame(r)) for r in rows]
        score_map = {}
        timing_map = {}

        if model_id in CONTROLLED_CLASSICAL:
            load_t0 = time.perf_counter()
            with open(info['checkpoint'], 'rb') as f:
                model = pickle.load(f)
            model_load = time.perf_counter() - load_t0
            for r, df in req_with_df:
                idx = df['row_index'].to_numpy(np.int64)
                prep_t0 = time.perf_counter()
                Xev = np.asarray(X_CLASSICAL[idx], dtype=np.float32)
                prep = time.perf_counter() - prep_t0
                pred_t0 = time.perf_counter()
                score_map[str(r['eval_id'])] = positive_probability(model, Xev)
                pred_sec = time.perf_counter() - pred_t0
                timing_map[str(r['eval_id'])] = {
                    'model_load_seconds': float(model_load),
                    'preprocessing_or_cache_load_seconds': float(prep),
                    'model_inference_seconds': float(pred_sec),
                    'combined_wrapper_seconds': None,
                    'timing_provenance': 'isolated_per_target_inference_in_current_environment',
                    'device': 'cpu',
                }
            del model

        elif model_id in CONTROLLED_DEEP:
            requests = [
                {'eval_id': str(r['eval_id']), 'target_index_key': str(r['target_index_key']), 'target_n': int(r['target_n'])}
                for r, _ in req_with_df
            ]
            score_map, batch_wall = deep_predict_requests(model_id, info['checkpoint'], int(run_row['seed']), requests)
            for r, _ in req_with_df:
                timing_map[str(r['eval_id'])] = {
                    'model_load_seconds': None,
                    'preprocessing_or_cache_load_seconds': None,
                    'model_inference_seconds': None,
                    'combined_wrapper_seconds': float(batch_wall),
                    'timing_provenance': 'one_GPU_subprocess_loaded_checkpoint_once_and_evaluated_all_pending_targets; per-target latency_not_separately_measured',
                    'device': 'gpu_tensorflow_locked_cell2_subprocess',
                }

        elif model_id == 'ampep':
            load_t0 = time.perf_counter()
            with open(info['checkpoint'], 'rb') as f:
                model = pickle.load(f)
            model_load = time.perf_counter() - load_t0
            for r, df in req_with_df:
                prep_t0 = time.perf_counter()
                Xev = get_ampep_features(r, df)
                prep = time.perf_counter() - prep_t0
                pred_t0 = time.perf_counter()
                score_map[str(r['eval_id'])] = positive_probability(model, Xev)
                pred_sec = time.perf_counter() - pred_t0
                timing_map[str(r['eval_id'])] = {
                    'model_load_seconds': float(model_load),
                    'preprocessing_or_cache_load_seconds': float(prep),
                    'model_inference_seconds': float(pred_sec),
                    'combined_wrapper_seconds': None,
                    'timing_provenance': 'AmPEP_105D_exact_features; feature cache reused by target_index_key within Cell33',
                    'device': 'cpu',
                }
            del model

        elif model_id in {'ampscannerv2', 'ampeppy'}:
            score_map, batch_wall = legacy_predict_requests(model_id, info['checkpoint'], req_with_df)
            for r, _ in req_with_df:
                timing_map[str(r['eval_id'])] = {
                    'model_load_seconds': None,
                    'preprocessing_or_cache_load_seconds': None,
                    'model_inference_seconds': None,
                    'combined_wrapper_seconds': float(batch_wall),
                    'timing_provenance': 'source-faithful_legacy_checkpoint_inference_once_over_all_pending_targets; per-target latency_not_separately_measured',
                    'device': 'legacy_cpu_exact_environment',
                }
        else:
            raise KeyError(model_id)

        for r, df in req_with_df:
            eval_id = str(r['eval_id'])
            manifest_path = commit_eval_bundle(r, df, score_map[eval_id], tau, timing_map[eval_id])
            update_eval_ledger(eval_id, status='EVALUATED', manifest=str(manifest_path))
            new_evals += 1

        new_run_groups += 1
        done = int(eval_ledger['status'].astype(str).eq('EVALUATED').sum())
        elapsed = time.perf_counter() - start_wall
        rate = new_evals / elapsed if elapsed > 0 else 0.0
        remaining = 2080 - done
        eta = remaining / rate if rate > 0 else None
        print(
            f'[{done:4d}/2080] RUN {run_id} | model={model_id:<24} '
            f'new_targets={len(rows)} elapsed={fmt_seconds(elapsed)} ETA={fmt_seconds(eta)}',
            flush=True,
        )
        gc.collect()

except KeyboardInterrupt:
    print('\nCELL 33 INTERRUPTED - completed evaluation bundles are preserved and restart-safe.', flush=True)
except Exception as exc:
    print('\nCELL 33 FAILURE:', repr(exc), flush=True)
    traceback.print_exc()
    raise
finally:
    atomic_write_csv(EVAL_LEDGER_PATH, eval_ledger)


# ============================================================================
# 14. CANONICAL SEED-LEVEL METRICS TABLE FROM VALID BUNDLES
# ============================================================================

metric_rows = []
for r in identity.itertuples(index=False):
    row = r._asdict()
    if not bundle_valid(row):
        continue
    out_dir = Path(str(row['output_dir']))
    payload = load_json(out_dir / 'metrics.json')
    resources = load_json(out_dir / 'resources.json')
    m = payload['metrics']
    record = {
        'eval_id': str(row['eval_id']),
        'protocol': str(row['protocol']),
        'run_id': str(row['run_id']),
        'model_id': str(row['model_id']),
        'model_group': str(row['model_group']),
        'source_dataset': str(row['source_dataset']),
        'target_dataset': str(row['target_dataset']),
        'seed': int(row['seed']),
        'target_index_key': str(row['target_index_key']),
        **{k: m[k] for k in METRIC_COLUMNS},
        'timing_provenance': resources.get('timing_provenance'),
        'model_inference_seconds': resources.get('model_inference_seconds'),
        'combined_wrapper_seconds': resources.get('combined_wrapper_seconds'),
        'eval_manifest': str(out_dir / 'eval_manifest.json'),
    }
    if str(row['protocol']).startswith('P2'):
        pr = p2_eval[p2_eval['eval_id'].astype(str).eq(str(row['eval_id']))]
        assert len(pr) == 1
        record['residual_exact_overlap'] = int(pr.iloc[0]['residual_exact_overlap'])
        record['locked_target_AMP'] = int(pr.iloc[0]['target_AMP'])
        record['locked_target_non_AMP'] = int(pr.iloc[0]['target_non_AMP'])
    else:
        record['residual_exact_overlap'] = 0
        record['locked_target_AMP'] = int(m['n_positive'])
        record['locked_target_non_AMP'] = int(m['n_negative'])
    metric_rows.append(record)

seed_metrics = pd.DataFrame(metric_rows)
if len(seed_metrics):
    seed_metrics = seed_metrics.sort_values(['protocol', 'model_id', 'source_dataset', 'target_dataset', 'seed'], kind='mergesort').reset_index(drop=True)
atomic_write_csv(SEED_METRICS_PATH, seed_metrics)

completed = int(eval_ledger['status'].astype(str).eq('EVALUATED').sum())
p1_completed = int(((eval_ledger['protocol'].astype(str) == 'P1_WITHIN_DATASET_SOURCE_TEST') & (eval_ledger['status'].astype(str) == 'EVALUATED')).sum())
p2_completed = int(((eval_ledger['protocol'].astype(str) == 'P2_CROSS_DATASET') & (eval_ledger['status'].astype(str) == 'EVALUATED')).sum())

summary = {
    'created_at': now_iso(),
    'status': 'COMPLETE' if completed == 2080 else 'PARTIAL_RESTART_SAFE',
    'final_scope': 'benchmark13_FINAL',
    'n_models': 13,
    'training_performed': False,
    'scope_selection_by_performance': False,
    'checkpoint_reload_selftest_passed': True,
    'checkpoint_reload_selftest_models': 13,
    'test_target_gate_opened_only_after_selftest': True,
    'threshold_source': 'source_validation_only_frozen',
    'target_threshold_tuning': False,
    'target_retraining': False,
    'target_finetuning': False,
    'planned_evaluations': 2080,
    'completed_evaluations': completed,
    'p1_planned': 520,
    'p1_completed': p1_completed,
    'p2_planned': 1560,
    'p2_completed': p2_completed,
    'seed_metrics_rows': int(len(seed_metrics)),
    'new_evaluations_this_invocation': int(new_evals),
    'new_run_groups_this_invocation': int(new_run_groups),
    'max_run_groups_operational_cap': int(MAX_RUN_GROUPS),
    'scope_manifest_sha256': EXPECTED_SCOPE_MANIFEST_SHA,
    'evaluation_contract_sha256': sha256_file(EVALUATION_CONTRACT_PATH),
    'checkpoint_reload_selftest_csv': str(CELL33_SELFTEST_PATH),
    'checkpoint_reload_selftest_sha256': sha256_file(CELL33_SELFTEST_PATH),
    'evaluation_ledger': str(EVAL_LEDGER_PATH),
    'evaluation_ledger_sha256': sha256_file(EVAL_LEDGER_PATH),
    'seed_level_metrics': str(SEED_METRICS_PATH),
    'seed_level_metrics_sha256': sha256_file(SEED_METRICS_PATH),
    'deep_inference_helper_sha256': DEEP_HELPER_SHA,
    'ampscannerv2_inference_helper_sha256': AMPSCANNER_HELPER_SHA,
    'ampeppy_inference_helper_sha256': AMPEPPY_HELPER_SHA,
}
atomic_write_json(CELL33_SUMMARY_PATH, summary)

print('=' * 140)
print('CELL 33 STATUS')
print('=' * 140)
print('Training performed            : FALSE')
print('Checkpoint reload self-test   : PASS 13/13 (SOURCE VALIDATION ONLY)')
print('Threshold source              : SOURCE VALIDATION ONLY / FROZEN')
print('Target threshold tuning       : FALSE')
print('Target retraining/fine-tuning : FALSE')
print('P1 completed                  :', p1_completed, '/ 520')
print('P2 completed                  :', p2_completed, '/ 1560')
print('TOTAL completed               :', completed, '/ 2080')
print('Seed-level metrics rows       :', len(seed_metrics), '/ 2080')
print('Evaluation ledger             :', EVAL_LEDGER_PATH)
print('Seed-level metrics            :', SEED_METRICS_PATH)
print('Summary                       :', CELL33_SUMMARY_PATH)
print('Summary SHA256                :', sha256_file(CELL33_SUMMARY_PATH))
print('=' * 140)

if completed == 2080:
    assert len(seed_metrics) == 2080
    assert p1_completed == 520
    assert p2_completed == 1560
    assert seed_metrics.groupby(['protocol', 'model_id', 'source_dataset', 'target_dataset']).size().eq(10).all()
    assert sorted(seed_metrics['seed'].astype(int).unique().tolist()) == EXPECTED_SEEDS
    assert seed_metrics[['AUROC','AUPRC','MCC','BACC','F1','ACC','Sensitivity','Specificity','Brier','ECE10']].apply(pd.to_numeric, errors='raise').notna().all().all()
    print('CELL 33 PASS - 2,080/2,080 FINAL EVALUATIONS COMPLETE; NO TRAINING')
    print('NEXT         - CELL 34: EXACT 10-SEED AGGREGATION (mean, SD ddof=1, SE, 95% Student-t CI df=9)')
else:
    print('CELL 33 PARTIAL - restart the IDENTICAL cell to continue; completed bundles will be verified and skipped.')
    if MAX_RUN_GROUPS > 0:
        print('Operational cap was active: GENPEPT_CELL33_MAX_RUN_GROUPS =', MAX_RUN_GROUPS)
print('=' * 140)

============================================================================================================================================
CELL 33 - FINAL 13-MODEL EVALUATION ONLY / NO TRAINING
============================================================================================================================================
Cell 32B scope             : VERIFIED BY SHA256
Models                     : 13
Training bundles to verify : 520
P1 planned evaluations     : 520
P2 planned evaluations     : 1560
Training allowed           : FALSE
Threshold tuning allowed   : FALSE
Target retraining allowed  : FALSE
TEST/target rows read yet  : FALSE
--------------------------------------------------------------------------------------------------------------------------------------------
[TRAIN-BUNDLE VERIFY]  50/520 PASS
[TRAIN-BUNDLE VERIFY] 100/520 PASS
[TRAIN-BUNDLE VERIFY] 150/520 PASS
[TRAIN-BUNDLE VERIFY] 200/520 PASS
[TRAIN-BUNDLE VERIFY] 250/520 PASS
[TRAIN-BUNDLE VERIFY] 300/520 PASS
[TRAIN-BUNDLE VERIFY] 350/520 PASS
[TRAIN-BUNDLE VERIFY] 400/520 PASS
[TRAIN-BUNDLE VERIFY] 450/520 PASS
[TRAIN-BUNDLE VERIFY] 500/520 PASS
[TRAIN-BUNDLE VERIFY] 520/520 PASS
Canonical training bundles : 520/520 VERIFIED
TEST/target rows read yet  : FALSE
Controlled-deep GPU       : PASS - {'tensorflow': '2.21.0', 'gpu_count': 1, 'gpu': "PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')"}
[LOADER SELFTEST 01/13] logistic_regression        PASS=True mode=tight_score_equivalence max_abs=1.110e-16 mean_abs=2.301e-17 hard_same=True rank_delta=0.000e+00 rank_gate=True wall=0.11s
[LOADER SELFTEST 02/13] linear_svm_calibrated      PASS=True mode=tight_score_equivalence max_abs=1.110e-16 mean_abs=1.787e-17 hard_same=True rank_delta=0.000e+00 rank_gate=True wall=0.01s
[LOADER SELFTEST 03/13] random_forest              PASS=True mode=tight_score_equivalence max_abs=0.000e+00 mean_abs=0.000e+00 hard_same=True rank_delta=0.000e+00 rank_gate=True wall=0.73s
[LOADER SELFTEST 04/13] extra_trees                PASS=True mode=tight_score_equivalence max_abs=0.000e+00 mean_abs=0.000e+00 hard_same=True rank_delta=0.000e+00 rank_gate=True wall=0.83s
[LOADER SELFTEST 05/13] hist_gradient_boosting     PASS=True mode=tight_score_equivalence max_abs=1.110e-16 mean_abs=3.330e-17 hard_same=True rank_delta=0.000e+00 rank_gate=True wall=0.01s
[LOADER SELFTEST 06/13] lightgbm                   PASS=True mode=tight_score_equivalence max_abs=1.110e-16 mean_abs=4.022e-17 hard_same=True rank_delta=0.000e+00 rank_gate=True wall=0.01s
[LOADER SELFTEST 07/13] cnn1d                      PASS=True mode=controlled_deep_gpu_bounded_score_and_frozen_decision_equivalence max_abs=6.356e-04 mean_abs=4.756e-05 hard_same=True rank_delta=3.368e-05 rank_gate=False wall=6.76s
[LOADER SELFTEST 08/13] bilstm                     PASS=True mode=controlled_deep_gpu_bounded_score_and_frozen_decision_equivalence max_abs=0.000e+00 mean_abs=0.000e+00 hard_same=True rank_delta=0.000e+00 rank_gate=False wall=3.92s
[LOADER SELFTEST 09/13] bilstm_attention           PASS=True mode=controlled_deep_gpu_bounded_score_and_frozen_decision_equivalence max_abs=0.000e+00 mean_abs=0.000e+00 hard_same=True rank_delta=0.000e+00 rank_gate=False wall=4.21s
[LOADER SELFTEST 10/13] transformer_encoder        PASS=True mode=controlled_deep_gpu_bounded_score_and_frozen_decision_equivalence max_abs=1.057e-04 mean_abs=1.140e-05 hard_same=True rank_delta=4.081e-06 rank_gate=False wall=9.79s
[LOADER SELFTEST 11/13] ampep                      PASS=True mode=tight_score_equivalence max_abs=0.000e+00 mean_abs=0.000e+00 hard_same=True rank_delta=0.000e+00 rank_gate=True wall=0.07s
[LOADER SELFTEST 12/13] ampscannerv2               PASS=True mode=tight_score_equivalence max_abs=0.000e+00 mean_abs=0.000e+00 hard_same=True rank_delta=0.000e+00 rank_gate=True wall=5.55s
[LOADER SELFTEST 13/13] ampeppy                    PASS=True mode=tight_score_equivalence max_abs=0.000e+00 mean_abs=0.000e+00 hard_same=True rank_delta=0.000e+00 rank_gate=True wall=5.33s
--------------------------------------------------------------------------------------------------------------------------------------------
CHECKPOINT RELOAD GATE     : PASS 13/13 ON SOURCE VALIDATION
TEST/TARGET ACCESS GATE    : OPEN FOR FINAL LOCKED EVALUATION ONLY
--------------------------------------------------------------------------------------------------------------------------------------------
TEST/target rows materialized: TRUE (7,517 unique indexed rows across locked P1/P2 targets)
Evaluation bundles reconciled: 0
Already EVALUATED             : 0 / 2080
[   4/2080] RUN logistic_regression__GenPept_Curated_2025__seed_100 | model=logistic_regression      new_targets=4 elapsed=00:00:01 ETA=00:07:38
[   8/2080] RUN logistic_regression__GenPept_Curated_2025__seed_101 | model=logistic_regression      new_targets=4 elapsed=00:00:02 ETA=00:07:11
[  12/2080] RUN logistic_regression__GenPept_Curated_2025__seed_102 | model=logistic_regression      new_targets=4 elapsed=00:00:02 ETA=00:07:03
[  16/2080] RUN logistic_regression__GenPept_Curated_2025__seed_103 | model=logistic_regression      new_targets=4 elapsed=00:00:03 ETA=00:06:55
[  20/2080] RUN logistic_regression__GenPept_Curated_2025__seed_104 | model=logistic_regression      new_targets=4 elapsed=00:00:04 ETA=00:06:51
[  24/2080] RUN logistic_regression__GenPept_Curated_2025__seed_105 | model=logistic_regression      new_targets=4 elapsed=00:00:05 ETA=00:06:48
[  28/2080] RUN logistic_regression__GenPept_Curated_2025__seed_106 | model=logistic_regression      new_targets=4 elapsed=00:00:06 ETA=00:06:43
[  32/2080] RUN logistic_regression__GenPept_Curated_2025__seed_107 | model=logistic_regression      new_targets=4 elapsed=00:00:06 ETA=00:06:40
[  36/2080] RUN logistic_regression__GenPept_Curated_2025__seed_108 | model=logistic_regression      new_targets=4 elapsed=00:00:07 ETA=00:06:39
[  40/2080] RUN logistic_regression__GenPept_Curated_2025__seed_109 | model=logistic_regression      new_targets=4 elapsed=00:00:08 ETA=00:06:39
[  44/2080] RUN logistic_regression__External_Benchmark_1__seed_100 | model=logistic_regression      new_targets=4 elapsed=00:00:09 ETA=00:06:41
[  48/2080] RUN logistic_regression__External_Benchmark_1__seed_101 | model=logistic_regression      new_targets=4 elapsed=00:00:09 ETA=00:06:38
[  52/2080] RUN logistic_regression__External_Benchmark_1__seed_102 | model=logistic_regression      new_targets=4 elapsed=00:00:10 ETA=00:06:36
[  56/2080] RUN logistic_regression__External_Benchmark_1__seed_103 | model=logistic_regression      new_targets=4 elapsed=00:00:11 ETA=00:06:34
[  60/2080] RUN logistic_regression__External_Benchmark_1__seed_104 | model=logistic_regression      new_targets=4 elapsed=00:00:12 ETA=00:06:33
[  64/2080] RUN logistic_regression__External_Benchmark_1__seed_105 | model=logistic_regression      new_targets=4 elapsed=00:00:12 ETA=00:06:32
[  68/2080] RUN logistic_regression__External_Benchmark_1__seed_106 | model=logistic_regression      new_targets=4 elapsed=00:00:13 ETA=00:06:30
[  72/2080] RUN logistic_regression__External_Benchmark_1__seed_107 | model=logistic_regression      new_targets=4 elapsed=00:00:14 ETA=00:06:29
[  76/2080] RUN logistic_regression__External_Benchmark_1__seed_108 | model=logistic_regression      new_targets=4 elapsed=00:00:15 ETA=00:06:28
[  80/2080] RUN logistic_regression__External_Benchmark_1__seed_109 | model=logistic_regression      new_targets=4 elapsed=00:00:16 ETA=00:06:29
[  84/2080] RUN logistic_regression__AMPlify_balanced__seed_100 | model=logistic_regression      new_targets=4 elapsed=00:00:16 ETA=00:06:30
[  88/2080] RUN logistic_regression__AMPlify_balanced__seed_101 | model=logistic_regression      new_targets=4 elapsed=00:00:17 ETA=00:06:29
[  92/2080] RUN logistic_regression__AMPlify_balanced__seed_102 | model=logistic_regression      new_targets=4 elapsed=00:00:18 ETA=00:06:27
[  96/2080] RUN logistic_regression__AMPlify_balanced__seed_103 | model=logistic_regression      new_targets=4 elapsed=00:00:19 ETA=00:06:26
[ 100/2080] RUN logistic_regression__AMPlify_balanced__seed_104 | model=logistic_regression      new_targets=4 elapsed=00:00:19 ETA=00:06:25
[ 104/2080] RUN logistic_regression__AMPlify_balanced__seed_105 | model=logistic_regression      new_targets=4 elapsed=00:00:20 ETA=00:06:23
[ 108/2080] RUN logistic_regression__AMPlify_balanced__seed_106 | model=logistic_regression      new_targets=4 elapsed=00:00:21 ETA=00:06:22
[ 112/2080] RUN logistic_regression__AMPlify_balanced__seed_107 | model=logistic_regression      new_targets=4 elapsed=00:00:22 ETA=00:06:21
[ 116/2080] RUN logistic_regression__AMPlify_balanced__seed_108 | model=logistic_regression      new_targets=4 elapsed=00:00:22 ETA=00:06:20
[ 120/2080] RUN logistic_regression__AMPlify_balanced__seed_109 | model=logistic_regression      new_targets=4 elapsed=00:00:23 ETA=00:06:18
[ 124/2080] RUN logistic_regression__External_Benchmark_3__seed_100 | model=logistic_regression      new_targets=4 elapsed=00:00:24 ETA=00:06:18
[ 128/2080] RUN logistic_regression__External_Benchmark_3__seed_101 | model=logistic_regression      new_targets=4 elapsed=00:00:25 ETA=00:06:17
[ 132/2080] RUN logistic_regression__External_Benchmark_3__seed_102 | model=logistic_regression      new_targets=4 elapsed=00:00:25 ETA=00:06:16
[ 136/2080] RUN logistic_regression__External_Benchmark_3__seed_103 | model=logistic_regression      new_targets=4 elapsed=00:00:26 ETA=00:06:15
[ 140/2080] RUN logistic_regression__External_Benchmark_3__seed_104 | model=logistic_regression      new_targets=4 elapsed=00:00:27 ETA=00:06:15
[ 144/2080] RUN logistic_regression__External_Benchmark_3__seed_105 | model=logistic_regression      new_targets=4 elapsed=00:00:28 ETA=00:06:14
[ 148/2080] RUN logistic_regression__External_Benchmark_3__seed_106 | model=logistic_regression      new_targets=4 elapsed=00:00:29 ETA=00:06:13
[ 152/2080] RUN logistic_regression__External_Benchmark_3__seed_107 | model=logistic_regression      new_targets=4 elapsed=00:00:29 ETA=00:06:12
[ 156/2080] RUN logistic_regression__External_Benchmark_3__seed_108 | model=logistic_regression      new_targets=4 elapsed=00:00:30 ETA=00:06:11
[ 160/2080] RUN logistic_regression__External_Benchmark_3__seed_109 | model=logistic_regression      new_targets=4 elapsed=00:00:31 ETA=00:06:10
[ 164/2080] RUN linear_svm_calibrated__GenPept_Curated_2025__seed_100 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:32 ETA=00:06:10
[ 168/2080] RUN linear_svm_calibrated__GenPept_Curated_2025__seed_101 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:32 ETA=00:06:09
[ 172/2080] RUN linear_svm_calibrated__GenPept_Curated_2025__seed_102 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:33 ETA=00:06:09
[ 176/2080] RUN linear_svm_calibrated__GenPept_Curated_2025__seed_103 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:34 ETA=00:06:08
[ 180/2080] RUN linear_svm_calibrated__GenPept_Curated_2025__seed_104 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:35 ETA=00:06:08
[ 184/2080] RUN linear_svm_calibrated__GenPept_Curated_2025__seed_105 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:36 ETA=00:06:08
[ 188/2080] RUN linear_svm_calibrated__GenPept_Curated_2025__seed_106 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:36 ETA=00:06:07
[ 192/2080] RUN linear_svm_calibrated__GenPept_Curated_2025__seed_107 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:37 ETA=00:06:06
[ 196/2080] RUN linear_svm_calibrated__GenPept_Curated_2025__seed_108 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:38 ETA=00:06:05
[ 200/2080] RUN linear_svm_calibrated__GenPept_Curated_2025__seed_109 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:39 ETA=00:06:05
[ 204/2080] RUN linear_svm_calibrated__External_Benchmark_1__seed_100 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:40 ETA=00:06:04
[ 208/2080] RUN linear_svm_calibrated__External_Benchmark_1__seed_101 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:40 ETA=00:06:03
[ 212/2080] RUN linear_svm_calibrated__External_Benchmark_1__seed_102 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:41 ETA=00:06:02
[ 216/2080] RUN linear_svm_calibrated__External_Benchmark_1__seed_103 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:42 ETA=00:06:02
[ 220/2080] RUN linear_svm_calibrated__External_Benchmark_1__seed_104 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:43 ETA=00:06:01
[ 224/2080] RUN linear_svm_calibrated__External_Benchmark_1__seed_105 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:43 ETA=00:06:00
[ 228/2080] RUN linear_svm_calibrated__External_Benchmark_1__seed_106 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:44 ETA=00:05:59
[ 232/2080] RUN linear_svm_calibrated__External_Benchmark_1__seed_107 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:45 ETA=00:05:59
[ 236/2080] RUN linear_svm_calibrated__External_Benchmark_1__seed_108 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:46 ETA=00:05:58
[ 240/2080] RUN linear_svm_calibrated__External_Benchmark_1__seed_109 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:47 ETA=00:05:57
[ 244/2080] RUN linear_svm_calibrated__AMPlify_balanced__seed_100 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:47 ETA=00:05:56
[ 248/2080] RUN linear_svm_calibrated__AMPlify_balanced__seed_101 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:48 ETA=00:05:55
[ 252/2080] RUN linear_svm_calibrated__AMPlify_balanced__seed_102 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:49 ETA=00:05:55
[ 256/2080] RUN linear_svm_calibrated__AMPlify_balanced__seed_103 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:50 ETA=00:05:54
[ 260/2080] RUN linear_svm_calibrated__AMPlify_balanced__seed_104 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:50 ETA=00:05:53
[ 264/2080] RUN linear_svm_calibrated__AMPlify_balanced__seed_105 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:51 ETA=00:05:53
[ 268/2080] RUN linear_svm_calibrated__AMPlify_balanced__seed_106 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:52 ETA=00:05:52
[ 272/2080] RUN linear_svm_calibrated__AMPlify_balanced__seed_107 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:53 ETA=00:05:51
[ 276/2080] RUN linear_svm_calibrated__AMPlify_balanced__seed_108 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:54 ETA=00:05:50
[ 280/2080] RUN linear_svm_calibrated__AMPlify_balanced__seed_109 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:54 ETA=00:05:49
[ 284/2080] RUN linear_svm_calibrated__External_Benchmark_3__seed_100 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:55 ETA=00:05:49
[ 288/2080] RUN linear_svm_calibrated__External_Benchmark_3__seed_101 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:56 ETA=00:05:48
[ 292/2080] RUN linear_svm_calibrated__External_Benchmark_3__seed_102 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:57 ETA=00:05:47
[ 296/2080] RUN linear_svm_calibrated__External_Benchmark_3__seed_103 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:57 ETA=00:05:46
[ 300/2080] RUN linear_svm_calibrated__External_Benchmark_3__seed_104 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:58 ETA=00:05:45
[ 304/2080] RUN linear_svm_calibrated__External_Benchmark_3__seed_105 | model=linear_svm_calibrated    new_targets=4 elapsed=00:00:59 ETA=00:05:45
[ 308/2080] RUN linear_svm_calibrated__External_Benchmark_3__seed_106 | model=linear_svm_calibrated    new_targets=4 elapsed=00:01:00 ETA=00:05:44
[ 312/2080] RUN linear_svm_calibrated__External_Benchmark_3__seed_107 | model=linear_svm_calibrated    new_targets=4 elapsed=00:01:01 ETA=00:05:43
[ 316/2080] RUN linear_svm_calibrated__External_Benchmark_3__seed_108 | model=linear_svm_calibrated    new_targets=4 elapsed=00:01:01 ETA=00:05:43
[ 320/2080] RUN linear_svm_calibrated__External_Benchmark_3__seed_109 | model=linear_svm_calibrated    new_targets=4 elapsed=00:01:02 ETA=00:05:42
[ 324/2080] RUN random_forest__GenPept_Curated_2025__seed_100 | model=random_forest            new_targets=4 elapsed=00:01:03 ETA=00:05:43
[ 328/2080] RUN random_forest__GenPept_Curated_2025__seed_101 | model=random_forest            new_targets=4 elapsed=00:01:05 ETA=00:05:46
[ 332/2080] RUN random_forest__GenPept_Curated_2025__seed_102 | model=random_forest            new_targets=4 elapsed=00:01:06 ETA=00:05:48
[ 336/2080] RUN random_forest__GenPept_Curated_2025__seed_103 | model=random_forest            new_targets=4 elapsed=00:01:08 ETA=00:05:50
[ 340/2080] RUN random_forest__GenPept_Curated_2025__seed_104 | model=random_forest            new_targets=4 elapsed=00:01:09 ETA=00:05:53
[ 344/2080] RUN random_forest__GenPept_Curated_2025__seed_105 | model=random_forest            new_targets=4 elapsed=00:01:10 ETA=00:05:54
[ 348/2080] RUN random_forest__GenPept_Curated_2025__seed_106 | model=random_forest            new_targets=4 elapsed=00:01:12 ETA=00:05:58
[ 352/2080] RUN random_forest__GenPept_Curated_2025__seed_107 | model=random_forest            new_targets=4 elapsed=00:01:13 ETA=00:06:00
[ 356/2080] RUN random_forest__GenPept_Curated_2025__seed_108 | model=random_forest            new_targets=4 elapsed=00:01:15 ETA=00:06:02
[ 360/2080] RUN random_forest__GenPept_Curated_2025__seed_109 | model=random_forest            new_targets=4 elapsed=00:01:16 ETA=00:06:03
[ 364/2080] RUN random_forest__External_Benchmark_1__seed_100 | model=random_forest            new_targets=4 elapsed=00:01:17 ETA=00:06:05
[ 368/2080] RUN random_forest__External_Benchmark_1__seed_101 | model=random_forest            new_targets=4 elapsed=00:01:19 ETA=00:06:07
[ 372/2080] RUN random_forest__External_Benchmark_1__seed_102 | model=random_forest            new_targets=4 elapsed=00:01:20 ETA=00:06:08
[ 376/2080] RUN random_forest__External_Benchmark_1__seed_103 | model=random_forest            new_targets=4 elapsed=00:01:21 ETA=00:06:09
[ 380/2080] RUN random_forest__External_Benchmark_1__seed_104 | model=random_forest            new_targets=4 elapsed=00:01:23 ETA=00:06:11
[ 384/2080] RUN random_forest__External_Benchmark_1__seed_105 | model=random_forest            new_targets=4 elapsed=00:01:24 ETA=00:06:12
[ 388/2080] RUN random_forest__External_Benchmark_1__seed_106 | model=random_forest            new_targets=4 elapsed=00:01:26 ETA=00:06:13
[ 392/2080] RUN random_forest__External_Benchmark_1__seed_107 | model=random_forest            new_targets=4 elapsed=00:01:27 ETA=00:06:14
[ 396/2080] RUN random_forest__External_Benchmark_1__seed_108 | model=random_forest            new_targets=4 elapsed=00:01:28 ETA=00:06:15
[ 400/2080] RUN random_forest__External_Benchmark_1__seed_109 | model=random_forest            new_targets=4 elapsed=00:01:30 ETA=00:06:16
[ 404/2080] RUN random_forest__AMPlify_balanced__seed_100 | model=random_forest            new_targets=4 elapsed=00:01:31 ETA=00:06:17
[ 408/2080] RUN random_forest__AMPlify_balanced__seed_101 | model=random_forest            new_targets=4 elapsed=00:01:32 ETA=00:06:18
[ 412/2080] RUN random_forest__AMPlify_balanced__seed_102 | model=random_forest            new_targets=4 elapsed=00:01:34 ETA=00:06:19
[ 416/2080] RUN random_forest__AMPlify_balanced__seed_103 | model=random_forest            new_targets=4 elapsed=00:01:35 ETA=00:06:20
[ 420/2080] RUN random_forest__AMPlify_balanced__seed_104 | model=random_forest            new_targets=4 elapsed=00:01:36 ETA=00:06:21
[ 424/2080] RUN random_forest__AMPlify_balanced__seed_105 | model=random_forest            new_targets=4 elapsed=00:01:38 ETA=00:06:22
[ 428/2080] RUN random_forest__AMPlify_balanced__seed_106 | model=random_forest            new_targets=4 elapsed=00:01:39 ETA=00:06:23

In [54]:
# ============================================================================
# CELL 34 - FINAL 13-MODEL EXACT 10-SEED AGGREGATION
# NO TRAINING / NO INFERENCE / NO THRESHOLD TUNING / NO BOOTSTRAP
# ============================================================================

from pathlib import Path
import hashlib
import json
import math
import os
import tempfile

import numpy as np
import pandas as pd
from scipy.stats import t as student_t


# ============================================================================
# 1. LOCKED PATHS / UPSTREAM IDENTITIES
# ============================================================================

PROJECT_ROOT = Path('/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026')
OUTPUT_ROOT = PROJECT_ROOT / 'benchmark17_outputs'
AUDIT_DIR = OUTPUT_ROOT / 'audit'
MANIFEST_DIR = OUTPUT_ROOT / 'manifests'
RESULTS_ROOT = OUTPUT_ROOT / 'results'
FINAL_RESULTS_DIR = RESULTS_ROOT / 'benchmark13_FINAL'
AGG_DIR = FINAL_RESULTS_DIR / 'cell34_10seed_aggregation'

FINAL13_MODEL_SCOPE_PATH = AUDIT_DIR / 'benchmark13_FINAL_model_scope_lock.csv'
FINAL13_SCOPE_MANIFEST_PATH = MANIFEST_DIR / 'benchmark13_FINAL_scope_manifest.json'
CELL33_SUMMARY_PATH = AUDIT_DIR / 'benchmark13_FINAL_cell33_summary.json'
EVAL_LEDGER_PATH = AUDIT_DIR / 'benchmark13_FINAL_cell33_evaluation_ledger_2080.csv'
SEED_METRICS_PATH = FINAL_RESULTS_DIR / 'benchmark13_FINAL_seed_level_metrics_2080.csv'

# Exact successful Cell 33 summary reported by the completed run.
EXPECTED_CELL33_SUMMARY_SHA256 = '0391505d09b91a7a9518b51f6c75af85af29ac7c70e225efd4b2f1c7163c178f'
EXPECTED_SCOPE_SHA256 = '66648c9c1dd0911fc29d36a405a8f176da168d4a74459e2cd4149a45d8251f2a'
EXPECTED_SCOPE_MANIFEST_SHA256 = '1639f1480ba4dbe9b1344d1321f5049c9ac59dc15ac8cced5d3e62210b3209dc'

EXPECTED_MODELS = [
    'logistic_regression',
    'linear_svm_calibrated',
    'random_forest',
    'extra_trees',
    'hist_gradient_boosting',
    'lightgbm',
    'cnn1d',
    'bilstm',
    'bilstm_attention',
    'transformer_encoder',
    'ampep',
    'ampscannerv2',
    'ampeppy',
]
EXPECTED_DATASETS = [
    'GenPept_Curated_2025',
    'External_Benchmark_1',
    'AMPlify_balanced',
    'External_Benchmark_3',
]
EXPECTED_SEEDS = list(range(100, 110))
EXPECTED_PROTOCOLS = ['P1_WITHIN_DATASET_SOURCE_TEST', 'P2_CROSS_DATASET']

PERFORMANCE_METRICS = [
    'AUROC', 'AUPRC', 'MCC', 'BACC', 'F1', 'ACC',
    'Sensitivity', 'Specificity', 'Brier', 'ECE10',
]
COUNT_METRICS = ['TP', 'TN', 'FP', 'FN']

N_SEEDS = 10
DF_T = N_SEEDS - 1
ALPHA = 0.05

# Canonical two-sided 95% Student-t critical value for df=9.
# Keep the canonical constant for byte-stable outputs across SciPy versions,
# while independently checking that the installed SciPy agrees numerically.
T_CRIT_CANONICAL = 2.2621571627982055
T_CRIT_SCIPY = float(student_t.ppf(1.0 - ALPHA / 2.0, df=DF_T))
assert math.isfinite(T_CRIT_SCIPY)
assert math.isclose(
    T_CRIT_SCIPY, T_CRIT_CANONICAL,
    rel_tol=0.0, abs_tol=1e-10,
), (
    f'Unexpected Student-t critical value for df=9: '
    f'SciPy={T_CRIT_SCIPY:.17g}, canonical={T_CRIT_CANONICAL:.17g}'
)
T_CRIT = T_CRIT_CANONICAL

ALL_AGG_PATH = AGG_DIR / 'benchmark13_FINAL_10seed_aggregate_all_208.csv'
P1_AGG_PATH = AGG_DIR / 'benchmark13_FINAL_10seed_P1_within_52.csv'
P2_AGG_PATH = AGG_DIR / 'benchmark13_FINAL_10seed_P2_cross_156.csv'
THRESHOLD_SUMMARY_PATH = AGG_DIR / 'benchmark13_FINAL_threshold_summary_52_source_configs.csv'
CONFUSION_SUMMARY_PATH = AGG_DIR / 'benchmark13_FINAL_confusion_summary_208.csv'
COMPLETENESS_PATH = AUDIT_DIR / 'benchmark13_FINAL_cell34_group_completeness_208.csv'
CELL34_MANIFEST_PATH = MANIFEST_DIR / 'benchmark13_FINAL_cell34_10seed_aggregation_manifest.json'

for p in [PROJECT_ROOT, OUTPUT_ROOT, AUDIT_DIR, MANIFEST_DIR, RESULTS_ROOT, FINAL_RESULTS_DIR]:
    assert p.is_dir(), f'Required directory missing: {p}'
for p in [FINAL13_MODEL_SCOPE_PATH, FINAL13_SCOPE_MANIFEST_PATH, CELL33_SUMMARY_PATH, EVAL_LEDGER_PATH, SEED_METRICS_PATH]:
    assert p.is_file(), f'Required upstream artifact missing: {p}'
AGG_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================================
# 2. DETERMINISTIC / ATOMIC HELPERS
# ============================================================================

def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(chunk_size), b''):
            h.update(chunk)
    return h.hexdigest()


def read_json(path: Path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def dataframe_csv_bytes(df: pd.DataFrame) -> bytes:
    # Stable column order is inherited from the dataframe; stable row order is
    # enforced before every write. 15 significant digits preserves metric values
    # without noisy platform-specific repr tails.
    text = df.to_csv(index=False, lineterminator='\n', float_format='%.15g')
    return text.encode('utf-8')


def json_bytes(obj) -> bytes:
    return (json.dumps(obj, ensure_ascii=False, indent=2, sort_keys=True) + '\n').encode('utf-8')


def atomic_commit_or_verify_bytes(path: Path, payload: bytes) -> str:
    """Create once; on rerun require byte-identical content. Never silently overwrite."""
    path.parent.mkdir(parents=True, exist_ok=True)
    new_sha = hashlib.sha256(payload).hexdigest()
    if path.exists():
        old_sha = sha256_file(path)
        assert old_sha == new_sha, (
            f'IMMUTABLE OUTPUT CONFLICT: existing file differs from deterministic Cell 34 result:\n'
            f'  path={path}\n  existing_sha={old_sha}\n  new_sha={new_sha}'
        )
        return 'VERIFIED_UNCHANGED'

    fd, tmp_name = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    try:
        with os.fdopen(fd, 'wb') as f:
            f.write(payload)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_name, path)
    finally:
        if os.path.exists(tmp_name):
            os.unlink(tmp_name)
    assert sha256_file(path) == new_sha
    return 'NEW_ATOMIC_COMMIT'


def atomic_commit_or_verify_csv(path: Path, df: pd.DataFrame) -> str:
    return atomic_commit_or_verify_bytes(path, dataframe_csv_bytes(df))


def atomic_commit_or_verify_json(path: Path, obj) -> str:
    return atomic_commit_or_verify_bytes(path, json_bytes(obj))


# ============================================================================
# 3. VERIFY EXACT CELL 33 SUCCESSFUL UPSTREAM
# ============================================================================

assert sha256_file(CELL33_SUMMARY_PATH) == EXPECTED_CELL33_SUMMARY_SHA256, (
    'Cell 33 summary SHA256 does not match the successful locked run. '
    'Cell 34 refuses to aggregate a different upstream state.'
)
assert sha256_file(FINAL13_MODEL_SCOPE_PATH) == EXPECTED_SCOPE_SHA256
assert sha256_file(FINAL13_SCOPE_MANIFEST_PATH) == EXPECTED_SCOPE_MANIFEST_SHA256

cell33 = read_json(CELL33_SUMMARY_PATH)
assert str(cell33.get('status')) == 'COMPLETE'
assert int(cell33.get('n_models')) == 13
assert bool(cell33.get('training_performed')) is False
assert bool(cell33.get('checkpoint_reload_selftest_passed')) is True
assert str(cell33.get('threshold_source')) == 'source_validation_only_frozen'
assert bool(cell33.get('target_threshold_tuning')) is False
assert bool(cell33.get('target_retraining')) is False
assert bool(cell33.get('target_finetuning')) is False
assert int(cell33.get('planned_evaluations')) == 2080
assert int(cell33.get('completed_evaluations')) == 2080
assert int(cell33.get('p1_completed')) == 520
assert int(cell33.get('p2_completed')) == 1560
assert int(cell33.get('seed_metrics_rows')) == 2080
assert str(cell33.get('seed_level_metrics_sha256')) == sha256_file(SEED_METRICS_PATH)
assert str(cell33.get('evaluation_ledger_sha256')) == sha256_file(EVAL_LEDGER_PATH)

scope = pd.read_csv(FINAL13_MODEL_SCOPE_PATH, keep_default_na=False, na_filter=False)
assert len(scope) == 13
assert scope['model_id'].astype(str).tolist() == EXPECTED_MODELS
assert scope['COMPLETE_40_OF_40'].astype(str).str.lower().eq('true').all()

print('=' * 144)
print('CELL 34 - FINAL 13-MODEL EXACT 10-SEED AGGREGATION')
print('=' * 144)
print('Cell 33 summary SHA256       : VERIFIED')
print('Cell 33 completed evals      : 2080 / 2080')
print('Models                       : 13')
print('Datasets                     : 4')
print('Seeds                        :', EXPECTED_SEEDS)
print('Training performed           : FALSE')
print('Inference performed          : FALSE')
print('Threshold tuning             : FALSE')
print('Bootstrap                    : FALSE')
print('Aggregation                  : mean, sample SD(ddof=1), SE, 95% Student-t CI')
print('Student-t df                 :', DF_T)
print('Student-t critical value     :', f'{T_CRIT:.15f}')
print('-' * 144)


# ============================================================================
# 4. LOAD + VALIDATE THE 2,080 SEED-LEVEL METRIC ROWS
# ============================================================================

seed = pd.read_csv(SEED_METRICS_PATH, keep_default_na=False, na_filter=False)

required_columns = [
    'eval_id', 'protocol', 'run_id', 'model_id', 'model_group',
    'source_dataset', 'target_dataset', 'seed',
    *PERFORMANCE_METRICS,
    'threshold', *COUNT_METRICS, 'n', 'n_positive', 'n_negative',
]
missing_cols = [c for c in required_columns if c not in seed.columns]
assert not missing_cols, f'Seed-level metrics missing required columns: {missing_cols}'
assert len(seed) == 2080
assert seed['eval_id'].astype(str).is_unique

seed['seed'] = pd.to_numeric(seed['seed'], errors='raise').astype(int)
for c in PERFORMANCE_METRICS + ['threshold']:
    seed[c] = pd.to_numeric(seed[c], errors='raise').astype(float)
for c in COUNT_METRICS + ['n', 'n_positive', 'n_negative']:
    seed[c] = pd.to_numeric(seed[c], errors='raise').astype(int)

assert seed[PERFORMANCE_METRICS + ['threshold']].apply(np.isfinite).all().all()
assert sorted(seed['model_id'].astype(str).unique().tolist()) == sorted(EXPECTED_MODELS)
assert sorted(seed['source_dataset'].astype(str).unique().tolist()) == sorted(EXPECTED_DATASETS)
assert sorted(seed['target_dataset'].astype(str).unique().tolist()) == sorted(EXPECTED_DATASETS)
assert sorted(seed['seed'].unique().tolist()) == EXPECTED_SEEDS
assert sorted(seed['protocol'].astype(str).unique().tolist()) == sorted(EXPECTED_PROTOCOLS)

p1_mask = seed['protocol'].astype(str).eq('P1_WITHIN_DATASET_SOURCE_TEST')
p2_mask = seed['protocol'].astype(str).eq('P2_CROSS_DATASET')
assert int(p1_mask.sum()) == 520
assert int(p2_mask.sum()) == 1560
assert (seed.loc[p1_mask, 'source_dataset'].astype(str).values == seed.loc[p1_mask, 'target_dataset'].astype(str).values).all()
assert (seed.loc[p2_mask, 'source_dataset'].astype(str).values != seed.loc[p2_mask, 'target_dataset'].astype(str).values).all()

# Range/integrity checks.
for c in ['AUROC', 'AUPRC', 'BACC', 'F1', 'ACC', 'Sensitivity', 'Specificity', 'Brier', 'ECE10', 'threshold']:
    assert seed[c].between(0.0, 1.0, inclusive='both').all(), f'Out-of-range values in {c}'
assert seed['MCC'].between(-1.0, 1.0, inclusive='both').all()
for c in COUNT_METRICS + ['n', 'n_positive', 'n_negative']:
    assert (seed[c] >= 0).all(), f'Negative count in {c}'
assert (seed['TP'] + seed['TN'] + seed['FP'] + seed['FN']).eq(seed['n']).all()
assert (seed['n_positive'] + seed['n_negative']).eq(seed['n']).all()
assert (seed['TP'] + seed['FN']).eq(seed['n_positive']).all()
assert (seed['TN'] + seed['FP']).eq(seed['n_negative']).all()

# Every model/source/target configuration must contain exactly seeds 100..109.
group_keys = ['protocol', 'model_id', 'model_group', 'source_dataset', 'target_dataset']
groups = seed.groupby(group_keys, sort=False, dropna=False)
assert groups.ngroups == 208
assert seed.loc[p1_mask].groupby(group_keys, sort=False, dropna=False).ngroups == 52
assert seed.loc[p2_mask].groupby(group_keys, sort=False, dropna=False).ngroups == 156

completeness_rows = []
for key, g in groups:
    observed_seeds = sorted(g['seed'].astype(int).tolist())
    unique_seeds = sorted(g['seed'].astype(int).unique().tolist())
    row = dict(zip(group_keys, key))
    row.update({
        'n_rows': int(len(g)),
        'n_unique_seeds': int(g['seed'].nunique()),
        'seeds': ','.join(map(str, unique_seeds)),
        'EXACT_10_SEEDS': bool(len(g) == 10 and unique_seeds == EXPECTED_SEEDS and observed_seeds == EXPECTED_SEEDS),
    })
    completeness_rows.append(row)

completeness = pd.DataFrame(completeness_rows)
assert len(completeness) == 208
assert completeness['EXACT_10_SEEDS'].all()

print('Seed-level metrics rows      : 2080 / 2080 VERIFIED')
print('10-seed configurations      : 208 / 208 VERIFIED')
print('  P1 within configurations  : 52 / 52')
print('  P2 cross configurations   : 156 / 156')
print('Seed completeness           : EXACT seeds 100..109 in every configuration')
print('-' * 144)


# ============================================================================
# 5. FROZEN-THRESHOLD CONSISTENCY AUDIT
# ============================================================================

# A source-trained run has one threshold chosen on SOURCE VALIDATION. That same
# threshold must be reused for P1 and all three P2 targets for the same
# (model, source_dataset, seed) tuple.
threshold_check = (
    seed.groupby(['model_id', 'source_dataset', 'seed'], sort=False)['threshold']
        .agg(['size', 'nunique', 'min', 'max'])
        .reset_index()
)
assert len(threshold_check) == 13 * 4 * 10
assert threshold_check['size'].eq(4).all()
assert threshold_check['nunique'].eq(1).all()
assert np.allclose(threshold_check['min'].to_numpy(float), threshold_check['max'].to_numpy(float), rtol=0.0, atol=0.0)

threshold_source = (
    seed[['model_id', 'model_group', 'source_dataset', 'seed', 'threshold']]
    .drop_duplicates()
    .sort_values(['model_id', 'source_dataset', 'seed'], kind='mergesort')
    .reset_index(drop=True)
)
assert len(threshold_source) == 13 * 4 * 10

threshold_rows = []
for key, g in threshold_source.groupby(['model_id', 'model_group', 'source_dataset'], sort=False, dropna=False):
    vals = g['threshold'].to_numpy(dtype=float)
    assert len(vals) == 10
    mean = float(np.mean(vals))
    sd = float(np.std(vals, ddof=1))
    se = float(sd / math.sqrt(N_SEEDS))
    margin = float(T_CRIT * se)
    row = {
        'model_id': key[0],
        'model_group': key[1],
        'source_dataset': key[2],
        'n_seeds': 10,
        'threshold_mean': mean,
        'threshold_sd': sd,
        'threshold_se': se,
        'threshold_ci95_low': mean - margin,
        'threshold_ci95_high': mean + margin,
        'threshold_min': float(np.min(vals)),
        'threshold_max': float(np.max(vals)),
    }
    threshold_rows.append(row)
threshold_summary = pd.DataFrame(threshold_rows)
assert len(threshold_summary) == 52

print('Frozen threshold reuse      : PASS - identical across 4 targets within every source run')
print('Threshold source configs    : 52 (13 models x 4 source datasets)')
print('-' * 144)


# ============================================================================
# 6. EXACT 10-SEED PERFORMANCE AGGREGATION
# ============================================================================

def summarize_metric(values: np.ndarray):
    values = np.asarray(values, dtype=float)
    assert values.shape == (N_SEEDS,)
    assert np.isfinite(values).all()
    mean = float(np.mean(values))
    sd = float(np.std(values, ddof=1))
    se = float(sd / math.sqrt(N_SEEDS))
    margin = float(T_CRIT * se)
    return mean, sd, se, mean - margin, mean + margin


agg_rows = []
confusion_rows = []

for key, g in groups:
    g = g.sort_values('seed', kind='mergesort').reset_index(drop=True)
    assert g['seed'].astype(int).tolist() == EXPECTED_SEEDS

    out = dict(zip(group_keys, key))
    out['n_seeds'] = N_SEEDS
    out['seeds'] = '100,101,102,103,104,105,106,107,108,109'
    out['ci_method'] = 'Student-t two-sided 95% CI on 10-seed mean'
    out['ci_df'] = DF_T
    out['ci_t_critical'] = T_CRIT

    for metric in PERFORMANCE_METRICS:
        mean, sd, se, low, high = summarize_metric(g[metric].to_numpy(dtype=float))
        out[f'{metric}_mean'] = mean
        out[f'{metric}_sd'] = sd
        out[f'{metric}_se'] = se
        out[f'{metric}_ci95_low'] = low
        out[f'{metric}_ci95_high'] = high

    # Target composition is fixed across seeds for a given source-target config.
    assert g['n'].nunique() == 1
    assert g['n_positive'].nunique() == 1
    assert g['n_negative'].nunique() == 1
    out['n_target'] = int(g['n'].iloc[0])
    out['n_positive'] = int(g['n_positive'].iloc[0])
    out['n_negative'] = int(g['n_negative'].iloc[0])
    agg_rows.append(out)

    cout = dict(zip(group_keys, key))
    cout['n_seeds'] = N_SEEDS
    cout['n_target'] = int(g['n'].iloc[0])
    for metric in COUNT_METRICS:
        vals = g[metric].to_numpy(dtype=float)
        mean, sd, se, low, high = summarize_metric(vals)
        cout[f'{metric}_mean'] = mean
        cout[f'{metric}_sd'] = sd
        cout[f'{metric}_se'] = se
        cout[f'{metric}_ci95_low'] = low
        cout[f'{metric}_ci95_high'] = high
    confusion_rows.append(cout)

agg = pd.DataFrame(agg_rows)
confusion = pd.DataFrame(confusion_rows)
assert len(agg) == 208
assert len(confusion) == 208

# Deterministic scientific order.
model_order = {m: i for i, m in enumerate(EXPECTED_MODELS)}
dataset_order = {d: i for i, d in enumerate(EXPECTED_DATASETS)}
protocol_order = {'P1_WITHIN_DATASET_SOURCE_TEST': 0, 'P2_CROSS_DATASET': 1}

def sort_final(df: pd.DataFrame) -> pd.DataFrame:
    z = df.copy()
    z['_p'] = z['protocol'].map(protocol_order)
    z['_m'] = z['model_id'].map(model_order)
    z['_s'] = z['source_dataset'].map(dataset_order)
    z['_t'] = z['target_dataset'].map(dataset_order)
    z = z.sort_values(['_p', '_m', '_s', '_t'], kind='mergesort').drop(columns=['_p', '_m', '_s', '_t'])
    return z.reset_index(drop=True)

agg = sort_final(agg)
confusion = sort_final(confusion)
completeness = sort_final(completeness)

p1 = agg[agg['protocol'].eq('P1_WITHIN_DATASET_SOURCE_TEST')].reset_index(drop=True)
p2 = agg[agg['protocol'].eq('P2_CROSS_DATASET')].reset_index(drop=True)
assert len(p1) == 52
assert len(p2) == 156

# Mathematical self-check on a deterministic first group using pandas ddof=1.
first_key = tuple(agg.loc[0, k] for k in group_keys)
g0 = groups.get_group(first_key).sort_values('seed')
for metric in PERFORMANCE_METRICS:
    vals = g0[metric].astype(float)
    row0 = agg.iloc[0]
    assert abs(float(row0[f'{metric}_mean']) - float(vals.mean())) < 1e-15
    assert abs(float(row0[f'{metric}_sd']) - float(vals.std(ddof=1))) < 1e-15
    assert abs(float(row0[f'{metric}_se']) - float(vals.std(ddof=1) / math.sqrt(10))) < 1e-15

print('Performance aggregation     : PASS')
print('  Metrics                   :', ', '.join(PERFORMANCE_METRICS))
print('  Rows                      : 208 configurations')
print('  Statistics/metric         : mean + SD(ddof=1) + SE + 95% Student-t CI')
print('  Bootstrap                 : NOT USED')
print('-' * 144)


# ============================================================================
# 7. COMMIT DETERMINISTIC OUTPUTS
# ============================================================================

write_actions = {}
write_actions[str(COMPLETENESS_PATH)] = atomic_commit_or_verify_csv(COMPLETENESS_PATH, completeness)
write_actions[str(THRESHOLD_SUMMARY_PATH)] = atomic_commit_or_verify_csv(THRESHOLD_SUMMARY_PATH, threshold_summary)
write_actions[str(CONFUSION_SUMMARY_PATH)] = atomic_commit_or_verify_csv(CONFUSION_SUMMARY_PATH, confusion)
write_actions[str(ALL_AGG_PATH)] = atomic_commit_or_verify_csv(ALL_AGG_PATH, agg)
write_actions[str(P1_AGG_PATH)] = atomic_commit_or_verify_csv(P1_AGG_PATH, p1)
write_actions[str(P2_AGG_PATH)] = atomic_commit_or_verify_csv(P2_AGG_PATH, p2)

manifest = {
    'cell': 'CELL 34',
    'scope': 'benchmark13_FINAL',
    'status': 'COMPLETE',
    'purpose': 'Exact 10-seed aggregation only',
    'training_performed': False,
    'inference_performed': False,
    'threshold_tuning_performed': False,
    'bootstrap_used': False,
    'n_models': 13,
    'n_datasets': 4,
    'seeds': EXPECTED_SEEDS,
    'n_seed_level_rows': 2080,
    'n_aggregate_configurations': 208,
    'n_p1_configurations': 52,
    'n_p2_configurations': 156,
    'performance_metrics': PERFORMANCE_METRICS,
    'aggregation': {
        'mean': 'arithmetic mean across exactly 10 seeds',
        'sd': 'sample standard deviation, ddof=1',
        'se': 'SD/sqrt(10)',
        'ci95': 'mean +/- t_(0.975, df=9) * SE',
        'df': DF_T,
        't_critical': T_CRIT,
    },
    'upstream': {
        'cell33_summary_path': str(CELL33_SUMMARY_PATH),
        'cell33_summary_sha256': sha256_file(CELL33_SUMMARY_PATH),
        'seed_level_metrics_path': str(SEED_METRICS_PATH),
        'seed_level_metrics_sha256': sha256_file(SEED_METRICS_PATH),
        'evaluation_ledger_path': str(EVAL_LEDGER_PATH),
        'evaluation_ledger_sha256': sha256_file(EVAL_LEDGER_PATH),
        'model_scope_path': str(FINAL13_MODEL_SCOPE_PATH),
        'model_scope_sha256': sha256_file(FINAL13_MODEL_SCOPE_PATH),
        'scope_manifest_path': str(FINAL13_SCOPE_MANIFEST_PATH),
        'scope_manifest_sha256': sha256_file(FINAL13_SCOPE_MANIFEST_PATH),
    },
    'outputs': {
        'aggregate_all_208': {'path': str(ALL_AGG_PATH), 'sha256': sha256_file(ALL_AGG_PATH)},
        'p1_within_52': {'path': str(P1_AGG_PATH), 'sha256': sha256_file(P1_AGG_PATH)},
        'p2_cross_156': {'path': str(P2_AGG_PATH), 'sha256': sha256_file(P2_AGG_PATH)},
        'threshold_summary_52': {'path': str(THRESHOLD_SUMMARY_PATH), 'sha256': sha256_file(THRESHOLD_SUMMARY_PATH)},
        'confusion_summary_208': {'path': str(CONFUSION_SUMMARY_PATH), 'sha256': sha256_file(CONFUSION_SUMMARY_PATH)},
        'group_completeness_208': {'path': str(COMPLETENESS_PATH), 'sha256': sha256_file(COMPLETENESS_PATH)},
    },
}
manifest_action = atomic_commit_or_verify_json(CELL34_MANIFEST_PATH, manifest)


# ============================================================================
# 8. FINAL HARD GATES / STATUS
# ============================================================================

# Re-read committed canonical aggregate to verify row counts and numeric completeness.
committed = pd.read_csv(ALL_AGG_PATH, keep_default_na=False, na_filter=False)
assert len(committed) == 208
assert int(committed['protocol'].eq('P1_WITHIN_DATASET_SOURCE_TEST').sum()) == 52
assert int(committed['protocol'].eq('P2_CROSS_DATASET').sum()) == 156
assert committed['n_seeds'].astype(int).eq(10).all()

stat_cols = []
for m in PERFORMANCE_METRICS:
    stat_cols.extend([f'{m}_mean', f'{m}_sd', f'{m}_se', f'{m}_ci95_low', f'{m}_ci95_high'])
assert committed[stat_cols].apply(pd.to_numeric, errors='raise').apply(np.isfinite).all().all()

print('=' * 144)
print('CELL 34 STATUS')
print('=' * 144)
print('Training performed           : FALSE')
print('Inference performed          : FALSE')
print('Threshold tuning             : FALSE')
print('Bootstrap used               : FALSE')
print('Seed-level input             : 2080 / 2080 VERIFIED')
print('Aggregate configurations     : 208 / 208')
print('P1 within rows               : 52 / 52')
print('P2 cross rows                : 156 / 156')
print('Seeds/configuration          : EXACTLY 10 (100..109)')
print('SD                           : sample SD, ddof=1')
print('SE                           : SD / sqrt(10)')
print(f'95% CI                       : Student-t, df=9, tcrit={T_CRIT:.15f}')
print('Frozen threshold reuse audit : PASS')
print('-' * 144)
print('All aggregate CSV            :', ALL_AGG_PATH)
print('  SHA256                     :', sha256_file(ALL_AGG_PATH))
print('P1 within CSV                :', P1_AGG_PATH)
print('  SHA256                     :', sha256_file(P1_AGG_PATH))
print('P2 cross CSV                 :', P2_AGG_PATH)
print('  SHA256                     :', sha256_file(P2_AGG_PATH))
print('Threshold summary CSV        :', THRESHOLD_SUMMARY_PATH)
print('  SHA256                     :', sha256_file(THRESHOLD_SUMMARY_PATH))
print('Confusion summary CSV        :', CONFUSION_SUMMARY_PATH)
print('  SHA256                     :', sha256_file(CONFUSION_SUMMARY_PATH))
print('Completeness audit CSV       :', COMPLETENESS_PATH)
print('  SHA256                     :', sha256_file(COMPLETENESS_PATH))
print('Aggregation manifest         :', CELL34_MANIFEST_PATH)
print('  SHA256                     :', sha256_file(CELL34_MANIFEST_PATH))
print('Manifest action              :', manifest_action)
print('=' * 144)
print('CELL 34 PASS - EXACT 10-SEED AGGREGATION COMPLETE; NO TRAINING / NO INFERENCE / NO BOOTSTRAP')
print('NEXT         - CELL 35: PAPER-READY TABLES + CROSS-DATASET MATRICES + FIGURES FROM LOCKED CELL 34 OUTPUTS')
print('=' * 144)

================================================================================================================================================
CELL 34 - FINAL 13-MODEL EXACT 10-SEED AGGREGATION
================================================================================================================================================
Cell 33 summary SHA256       : VERIFIED
Cell 33 completed evals      : 2080 / 2080
Models                       : 13
Datasets                     : 4
Seeds                        : [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
Training performed           : FALSE
Inference performed          : FALSE
Threshold tuning             : FALSE
Bootstrap                    : FALSE
Aggregation                  : mean, sample SD(ddof=1), SE, 95% Student-t CI
Student-t df                 : 9
Student-t critical value     : 2.262157162798205
------------------------------------------------------------------------------------------------------------------------------------------------
Seed-level metrics rows      : 2080 / 2080 VERIFIED
10-seed configurations      : 208 / 208 VERIFIED
  P1 within configurations  : 52 / 52
  P2 cross configurations   : 156 / 156
Seed completeness           : EXACT seeds 100..109 in every configuration
------------------------------------------------------------------------------------------------------------------------------------------------
Frozen threshold reuse      : PASS - identical across 4 targets within every source run
Threshold source configs    : 52 (13 models x 4 source datasets)
------------------------------------------------------------------------------------------------------------------------------------------------
Performance aggregation     : PASS
  Metrics                   : AUROC, AUPRC, MCC, BACC, F1, ACC, Sensitivity, Specificity, Brier, ECE10
  Rows                      : 208 configurations
  Statistics/metric         : mean + SD(ddof=1) + SE + 95% Student-t CI
  Bootstrap                 : NOT USED
------------------------------------------------------------------------------------------------------------------------------------------------
================================================================================================================================================
CELL 34 STATUS
================================================================================================================================================
Training performed           : FALSE
Inference performed          : FALSE
Threshold tuning             : FALSE
Bootstrap used               : FALSE
Seed-level input             : 2080 / 2080 VERIFIED
Aggregate configurations     : 208 / 208
P1 within rows               : 52 / 52
P2 cross rows                : 156 / 156
Seeds/configuration          : EXACTLY 10 (100..109)
SD                           : sample SD, ddof=1
SE                           : SD / sqrt(10)
95% CI                       : Student-t, df=9, tcrit=2.262157162798205
Frozen threshold reuse audit : PASS
------------------------------------------------------------------------------------------------------------------------------------------------
All aggregate CSV            : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell34_10seed_aggregation/benchmark13_FINAL_10seed_aggregate_all_208.csv
  SHA256                     : f13080c955c8e7fb4bd4390574ec6a1dfc462ace2c74604759543813c7c9de26
P1 within CSV                : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell34_10seed_aggregation/benchmark13_FINAL_10seed_P1_within_52.csv
  SHA256                     : 897b1ca986d5212d53ce904ee80c6ae035b2dd99d83c545c3db97f2a856ada47
P2 cross CSV                 : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell34_10seed_aggregation/benchmark13_FINAL_10seed_P2_cross_156.csv
  SHA256                     : 49cb94a0870a1b88115f3dc700cdbb4dcfe96fe69d2b5c1572c43e77631b12e4
Threshold summary CSV        : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell34_10seed_aggregation/benchmark13_FINAL_threshold_summary_52_source_configs.csv
  SHA256                     : 72a384f9cbdd3348aa5dc835f4baaf4cbf2d9ca853d08ae0efdcb8c77985304e
Confusion summary CSV        : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell34_10seed_aggregation/benchmark13_FINAL_confusion_summary_208.csv
  SHA256                     : 4c95d12a2bc95546a9f46d1170853a8904224dc1f1fc6afa3a9ee20b4f3fab3b
Completeness audit CSV       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/audit/benchmark13_FINAL_cell34_group_completeness_208.csv
  SHA256                     : f8738c36572b7b45dd674f6c5046c5d1ac7d51de2f34af5fa444317ed3080754
Aggregation manifest         : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark13_FINAL_cell34_10seed_aggregation_manifest.json
  SHA256                     : 68ea7dedcdbc36d7d48acdd7eb856a0e8a7b17b80f885cae917307a811d18869
Manifest action              : VERIFIED_UNCHANGED
================================================================================================================================================
CELL 34 PASS - EXACT 10-SEED AGGREGATION COMPLETE; NO TRAINING / NO INFERENCE / NO BOOTSTRAP
NEXT         - CELL 35: PAPER-READY TABLES + CROSS-DATASET MATRICES + FIGURES FROM LOCKED CELL 34 OUTPUTS
================================================================================================================================================

In [55]:
# ============================================================================
# CELL 35 - FINAL PAPER-READY TABLES + CROSS-DATASET MATRICES + FIGURES
# DERIVED ONLY FROM LOCKED CELL 34 OUTPUTS
# NO TRAINING / NO INFERENCE / NO THRESHOLD TUNING / NO MODEL SELECTION
# ============================================================================

from pathlib import Path
from io import BytesIO
import hashlib
import json
import math
import os
import tempfile

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg', force=True)
import matplotlib.pyplot as plt


# ============================================================================
# 1. LOCKED PATHS / EXACT UPSTREAM IDENTITIES
# ============================================================================

PROJECT_ROOT = Path('/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026')
OUTPUT_ROOT = PROJECT_ROOT / 'benchmark17_outputs'
MANIFEST_DIR = OUTPUT_ROOT / 'manifests'
RESULTS_ROOT = OUTPUT_ROOT / 'results'
FINAL_RESULTS_DIR = RESULTS_ROOT / 'benchmark13_FINAL'
CELL34_DIR = FINAL_RESULTS_DIR / 'cell34_10seed_aggregation'
CELL35_DIR = FINAL_RESULTS_DIR / 'cell35_paper_ready'
TABLE_DIR = CELL35_DIR / 'tables'
FIG_DIR = CELL35_DIR / 'figures'
MATRIX_DIR = CELL35_DIR / 'matrices'

ALL_AGG_PATH = CELL34_DIR / 'benchmark13_FINAL_10seed_aggregate_all_208.csv'
P1_AGG_PATH = CELL34_DIR / 'benchmark13_FINAL_10seed_P1_within_52.csv'
P2_AGG_PATH = CELL34_DIR / 'benchmark13_FINAL_10seed_P2_cross_156.csv'
THRESHOLD_SUMMARY_PATH = CELL34_DIR / 'benchmark13_FINAL_threshold_summary_52_source_configs.csv'
CONFUSION_SUMMARY_PATH = CELL34_DIR / 'benchmark13_FINAL_confusion_summary_208.csv'
CELL34_MANIFEST_PATH = MANIFEST_DIR / 'benchmark13_FINAL_cell34_10seed_aggregation_manifest.json'

EXPECTED_SHA256 = {
    ALL_AGG_PATH: 'f13080c955c8e7fb4bd4390574ec6a1dfc462ace2c74604759543813c7c9de26',
    P1_AGG_PATH: '897b1ca986d5212d53ce904ee80c6ae035b2dd99d83c545c3db97f2a856ada47',
    P2_AGG_PATH: '49cb94a0870a1b88115f3dc700cdbb4dcfe96fe69d2b5c1572c43e77631b12e4',
    THRESHOLD_SUMMARY_PATH: '72a384f9cbdd3348aa5dc835f4baaf4cbf2d9ca853d08ae0efdcb8c77985304e',
    CONFUSION_SUMMARY_PATH: '4c95d12a2bc95546a9f46d1170853a8904224dc1f1fc6afa3a9ee20b4f3fab3b',
    CELL34_MANIFEST_PATH: '68ea7dedcdbc36d7d48acdd7eb856a0e8a7b17b80f885cae917307a811d18869',
}

EXPECTED_MODELS = [
    'logistic_regression',
    'linear_svm_calibrated',
    'random_forest',
    'extra_trees',
    'hist_gradient_boosting',
    'lightgbm',
    'cnn1d',
    'bilstm',
    'bilstm_attention',
    'transformer_encoder',
    'ampep',
    'ampscannerv2',
    'ampeppy',
]
EXPECTED_DATASETS = [
    'GenPept_Curated_2025',
    'External_Benchmark_1',
    'AMPlify_balanced',
    'External_Benchmark_3',
]
EXPECTED_PROTOCOLS = ['P1_WITHIN_DATASET_SOURCE_TEST', 'P2_CROSS_DATASET']

MODEL_LABELS = {
    'logistic_regression': 'Logistic Regression',
    'linear_svm_calibrated': 'Linear SVM (calibrated)',
    'random_forest': 'Random Forest',
    'extra_trees': 'Extra Trees',
    'hist_gradient_boosting': 'HistGradientBoosting',
    'lightgbm': 'LightGBM',
    'cnn1d': 'CNN1D',
    'bilstm': 'BiLSTM',
    'bilstm_attention': 'BiLSTM + Attention',
    'transformer_encoder': 'Transformer Encoder',
    'ampep': 'AmPEP',
    'ampscannerv2': 'AMPScannerV2',
    'ampeppy': 'amPEPpy',
}
DATASET_LABELS = {
    'GenPept_Curated_2025': 'GenPept-Curated-2025',
    'External_Benchmark_1': 'External Benchmark 1',
    'AMPlify_balanced': 'AMPlify-balanced',
    'External_Benchmark_3': 'External Benchmark 3',
}

PERFORMANCE_METRICS = [
    'AUROC', 'AUPRC', 'MCC', 'BACC', 'F1', 'ACC',
    'Sensitivity', 'Specificity', 'Brier', 'ECE10',
]
CORE_METRICS = ['AUROC', 'AUPRC', 'MCC', 'F1']
HEATMAP_METRICS = ['AUROC', 'AUPRC']

for p in [PROJECT_ROOT, OUTPUT_ROOT, MANIFEST_DIR, RESULTS_ROOT, FINAL_RESULTS_DIR, CELL34_DIR]:
    assert p.is_dir(), f'Required directory missing: {p}'
for p in EXPECTED_SHA256:
    assert p.is_file(), f'Required locked Cell 34 artifact missing: {p}'

for p in [CELL35_DIR, TABLE_DIR, FIG_DIR, MATRIX_DIR]:
    p.mkdir(parents=True, exist_ok=True)


# ============================================================================
# 2. DETERMINISTIC HELPERS
# ============================================================================

def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(chunk_size), b''):
            h.update(chunk)
    return h.hexdigest()


def dataframe_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False, lineterminator='\n', float_format='%.15g').encode('utf-8')


def dataframe_matrix_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=True, lineterminator='\n', float_format='%.15g').encode('utf-8')


def json_bytes(obj) -> bytes:
    return (json.dumps(obj, ensure_ascii=False, indent=2, sort_keys=True) + '\n').encode('utf-8')


def atomic_commit_or_verify_bytes(path: Path, payload: bytes) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    new_sha = hashlib.sha256(payload).hexdigest()
    if path.exists():
        old_sha = sha256_file(path)
        assert old_sha == new_sha, (
            'IMMUTABLE OUTPUT CONFLICT: existing Cell 35 artifact differs from the '
            f'deterministic result.\n  path={path}\n  existing_sha={old_sha}\n  new_sha={new_sha}'
        )
        return 'VERIFIED_UNCHANGED'

    fd, tmp_name = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    try:
        with os.fdopen(fd, 'wb') as f:
            f.write(payload)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_name, path)
    finally:
        if os.path.exists(tmp_name):
            os.unlink(tmp_name)
    assert sha256_file(path) == new_sha
    return 'NEW_ATOMIC_COMMIT'


def atomic_csv(path: Path, df: pd.DataFrame, include_index: bool = False) -> str:
    payload = dataframe_matrix_csv_bytes(df) if include_index else dataframe_csv_bytes(df)
    return atomic_commit_or_verify_bytes(path, payload)


def atomic_json(path: Path, obj) -> str:
    return atomic_commit_or_verify_bytes(path, json_bytes(obj))


def format_mean_sd(mean, sd, digits=3) -> str:
    return f'{float(mean):.{digits}f} +/- {float(sd):.{digits}f}'


def format_mean_ci(mean, low, high, digits=3) -> str:
    return f'{float(mean):.{digits}f} [{float(low):.{digits}f}, {float(high):.{digits}f}]'


def render_figure_bytes(fig, fmt: str) -> bytes:
    buf = BytesIO()
    metadata = {'Creator': 'GenPept-Curated-2025 Cell 35'}
    if fmt.lower() == 'pdf':
        # Remove time-dependent PDF metadata for deterministic reruns.
        metadata.update({'CreationDate': None, 'ModDate': None})
    fig.savefig(
        buf,
        format=fmt,
        dpi=300 if fmt.lower() == 'png' else None,
        bbox_inches='tight',
        metadata=metadata,
    )
    return buf.getvalue()


def save_figure_pair(fig, stem: str, actions: dict):
    png_path = FIG_DIR / f'{stem}.png'
    pdf_path = FIG_DIR / f'{stem}.pdf'
    actions[str(png_path)] = atomic_commit_or_verify_bytes(png_path, render_figure_bytes(fig, 'png'))
    actions[str(pdf_path)] = atomic_commit_or_verify_bytes(pdf_path, render_figure_bytes(fig, 'pdf'))
    plt.close(fig)


# ============================================================================
# 3. VERIFY LOCKED CELL 34 BEFORE DERIVATION
# ============================================================================

for path, expected_sha in EXPECTED_SHA256.items():
    observed = sha256_file(path)
    assert observed == expected_sha, (
        f'Locked Cell 34 artifact SHA mismatch:\n  path={path}\n'
        f'  expected={expected_sha}\n  observed={observed}'
    )

with open(CELL34_MANIFEST_PATH, 'r', encoding='utf-8') as f:
    cell34_manifest = json.load(f)

assert cell34_manifest['status'] == 'COMPLETE'
assert int(cell34_manifest['n_models']) == 13
assert int(cell34_manifest['n_datasets']) == 4
assert int(cell34_manifest['n_seed_level_rows']) == 2080
assert int(cell34_manifest['n_aggregate_configurations']) == 208
assert int(cell34_manifest['n_p1_configurations']) == 52
assert int(cell34_manifest['n_p2_configurations']) == 156
assert cell34_manifest['seeds'] == list(range(100, 110))
assert bool(cell34_manifest['training_performed']) is False
assert bool(cell34_manifest['inference_performed']) is False
assert bool(cell34_manifest['threshold_tuning_performed']) is False
assert bool(cell34_manifest['bootstrap_used']) is False

print('=' * 144)
print('CELL 35 - FINAL PAPER-READY TABLES + CROSS-DATASET MATRICES + FIGURES')
print('=' * 144)
print('Cell 34 manifest             : VERIFIED BY SHA256')
print('Cell 34 aggregate rows       : 208')
print('Models                       : 13')
print('Datasets                     : 4')
print('Training performed           : FALSE')
print('Inference performed          : FALSE')
print('Threshold tuning             : FALSE')
print('Model selection/reranking    : FALSE')
print('Scope change                 : FALSE')
print('-' * 144)


# ============================================================================
# 4. LOAD + HARD-VALIDATE AGGREGATED INPUTS
# ============================================================================

all_agg = pd.read_csv(ALL_AGG_PATH, keep_default_na=False, na_filter=False)
p1 = pd.read_csv(P1_AGG_PATH, keep_default_na=False, na_filter=False)
p2 = pd.read_csv(P2_AGG_PATH, keep_default_na=False, na_filter=False)

required_base = ['protocol', 'model_id', 'model_group', 'source_dataset', 'target_dataset', 'n_seeds', 'seeds']
required_stats = []
for metric in PERFORMANCE_METRICS:
    required_stats += [
        f'{metric}_mean', f'{metric}_sd', f'{metric}_se',
        f'{metric}_ci95_low', f'{metric}_ci95_high',
    ]
required_columns = required_base + required_stats + ['n_target', 'n_positive', 'n_negative']
missing = [c for c in required_columns if c not in all_agg.columns]
assert not missing, f'Cell 34 aggregate is missing required columns: {missing}'

assert len(all_agg) == 208
assert len(p1) == 52
assert len(p2) == 156
assert all_agg['model_id'].drop_duplicates().tolist() == EXPECTED_MODELS
assert p1['model_id'].drop_duplicates().tolist() == EXPECTED_MODELS
assert p2['model_id'].drop_duplicates().tolist() == EXPECTED_MODELS
assert set(all_agg['source_dataset']) == set(EXPECTED_DATASETS)
assert set(all_agg['target_dataset']) == set(EXPECTED_DATASETS)
assert set(all_agg['protocol']) == set(EXPECTED_PROTOCOLS)
assert all_agg['n_seeds'].astype(int).eq(10).all()
assert all_agg['seeds'].astype(str).eq('100,101,102,103,104,105,106,107,108,109').all()
assert (p1['source_dataset'].astype(str) == p1['target_dataset'].astype(str)).all()
assert (p2['source_dataset'].astype(str) != p2['target_dataset'].astype(str)).all()

for c in required_stats:
    all_agg[c] = pd.to_numeric(all_agg[c], errors='raise').astype(float)
assert all_agg[required_stats].apply(np.isfinite).all().all()

# Confirm ALL == exact P1 + P2 content, independent of row order.
compare_keys = ['protocol', 'model_id', 'source_dataset', 'target_dataset']
all_sorted = all_agg.sort_values(compare_keys, kind='mergesort').reset_index(drop=True)
parts_sorted = pd.concat([p1, p2], ignore_index=True).sort_values(compare_keys, kind='mergesort').reset_index(drop=True)
pd.testing.assert_frame_equal(all_sorted, parts_sorted, check_dtype=False, check_exact=False, rtol=0, atol=1e-14)

# Exact configuration uniqueness.
assert not all_agg.duplicated(compare_keys).any()
assert not p1.duplicated(['model_id', 'source_dataset']).any()
assert not p2.duplicated(['model_id', 'source_dataset', 'target_dataset']).any()

print('Input integrity              : PASS')
print('P1 configurations            : 52 / 52')
print('P2 configurations            : 156 / 156')
print('All 10-seed statistics       : FINITE / COMPLETE')
print('-' * 144)


# ============================================================================
# 5. PAPER-READY LONG TABLES - NO PERFORMANCE-BASED FILTERING
# ============================================================================

model_order = {m: i for i, m in enumerate(EXPECTED_MODELS)}
dataset_order = {d: i for i, d in enumerate(EXPECTED_DATASETS)}


def add_display_columns(df: pd.DataFrame) -> pd.DataFrame:
    z = df.copy()
    z.insert(0, 'Model', z['model_id'].map(MODEL_LABELS))
    z.insert(1, 'Source dataset', z['source_dataset'].map(DATASET_LABELS))
    z.insert(2, 'Target dataset', z['target_dataset'].map(DATASET_LABELS))
    return z


def build_core_paper_table(df: pd.DataFrame) -> pd.DataFrame:
    z = add_display_columns(df)
    out = z[['Model', 'Source dataset', 'Target dataset', 'model_id', 'source_dataset', 'target_dataset']].copy()
    for metric in CORE_METRICS:
        out[f'{metric} mean+/-SD'] = [
            format_mean_sd(m, s) for m, s in zip(z[f'{metric}_mean'], z[f'{metric}_sd'])
        ]
        out[f'{metric} mean [95% CI]'] = [
            format_mean_ci(m, lo, hi)
            for m, lo, hi in zip(z[f'{metric}_mean'], z[f'{metric}_ci95_low'], z[f'{metric}_ci95_high'])
        ]
    return out


p1_paper = build_core_paper_table(p1)
p2_paper = build_core_paper_table(p2)
assert len(p1_paper) == 52
assert len(p2_paper) == 156

write_actions = {}
P1_PAPER_PATH = TABLE_DIR / 'Table_P1_within_core_metrics_52.csv'
P2_PAPER_PATH = TABLE_DIR / 'Table_P2_cross_core_metrics_156.csv'
ALL_STATS_PATH = TABLE_DIR / 'Table_Supplement_all_10seed_statistics_208.csv'

write_actions[str(P1_PAPER_PATH)] = atomic_csv(P1_PAPER_PATH, p1_paper)
write_actions[str(P2_PAPER_PATH)] = atomic_csv(P2_PAPER_PATH, p2_paper)
write_actions[str(ALL_STATS_PATH)] = atomic_csv(ALL_STATS_PATH, add_display_columns(all_agg))


# ============================================================================
# 6. P1 13x4 MATRICES FOR EACH CORE METRIC
# ============================================================================

p1_numeric_matrices = {}
p1_formatted_matrices = {}

for metric in CORE_METRICS:
    numeric = p1.pivot(index='model_id', columns='source_dataset', values=f'{metric}_mean')
    numeric = numeric.reindex(index=EXPECTED_MODELS, columns=EXPECTED_DATASETS)
    assert numeric.shape == (13, 4)
    assert np.isfinite(numeric.to_numpy(dtype=float)).all()
    numeric.index = [MODEL_LABELS[m] for m in numeric.index]
    numeric.columns = [DATASET_LABELS[d] for d in numeric.columns]
    p1_numeric_matrices[metric] = numeric

    formatted = pd.DataFrame(index=numeric.index, columns=numeric.columns, dtype=object)
    for model_id in EXPECTED_MODELS:
        for dataset in EXPECTED_DATASETS:
            r = p1[(p1['model_id'] == model_id) & (p1['source_dataset'] == dataset)]
            assert len(r) == 1
            rr = r.iloc[0]
            formatted.loc[MODEL_LABELS[model_id], DATASET_LABELS[dataset]] = format_mean_sd(
                rr[f'{metric}_mean'], rr[f'{metric}_sd']
            )
    p1_formatted_matrices[metric] = formatted

    num_path = MATRIX_DIR / f'P1_{metric}_mean_13x4.csv'
    fmt_path = MATRIX_DIR / f'P1_{metric}_meanSD_13x4.csv'
    write_actions[str(num_path)] = atomic_csv(num_path, numeric, include_index=True)
    write_actions[str(fmt_path)] = atomic_csv(fmt_path, formatted, include_index=True)


# ============================================================================
# 7. P2 13x12 CROSS-DATASET MATRICES FOR EACH CORE METRIC
# ============================================================================

pair_order = [(s, t) for s in EXPECTED_DATASETS for t in EXPECTED_DATASETS if s != t]
pair_ids = [f'{s} -> {t}' for s, t in pair_order]
pair_labels = [f'{DATASET_LABELS[s]} -> {DATASET_LABELS[t]}' for s, t in pair_order]

p2_numeric_matrices = {}
p2_formatted_matrices = {}

for metric in CORE_METRICS:
    numeric = pd.DataFrame(index=[MODEL_LABELS[m] for m in EXPECTED_MODELS], columns=pair_labels, dtype=float)
    formatted = pd.DataFrame(index=numeric.index, columns=numeric.columns, dtype=object)

    for model_id in EXPECTED_MODELS:
        for (source, target), pair_label in zip(pair_order, pair_labels):
            r = p2[
                (p2['model_id'] == model_id)
                & (p2['source_dataset'] == source)
                & (p2['target_dataset'] == target)
            ]
            assert len(r) == 1
            rr = r.iloc[0]
            numeric.loc[MODEL_LABELS[model_id], pair_label] = float(rr[f'{metric}_mean'])
            formatted.loc[MODEL_LABELS[model_id], pair_label] = format_mean_sd(
                rr[f'{metric}_mean'], rr[f'{metric}_sd']
            )

    assert numeric.shape == (13, 12)
    assert np.isfinite(numeric.to_numpy(dtype=float)).all()
    p2_numeric_matrices[metric] = numeric
    p2_formatted_matrices[metric] = formatted

    num_path = MATRIX_DIR / f'P2_{metric}_mean_13x12.csv'
    fmt_path = MATRIX_DIR / f'P2_{metric}_meanSD_13x12.csv'
    write_actions[str(num_path)] = atomic_csv(num_path, numeric, include_index=True)
    write_actions[str(fmt_path)] = atomic_csv(fmt_path, formatted, include_index=True)


# ============================================================================
# 8. FULL 4x4 SOURCE->TARGET MATRIX FOR EACH MODEL (AUROC/AUPRC)
#    DIAGONAL = P1 SOURCE TEST; OFF-DIAGONAL = P2 CROSS-DATASET
# ============================================================================

for metric in HEATMAP_METRICS:
    for model_id in EXPECTED_MODELS:
        mat = pd.DataFrame(index=EXPECTED_DATASETS, columns=EXPECTED_DATASETS, dtype=float)
        fmt = pd.DataFrame(index=EXPECTED_DATASETS, columns=EXPECTED_DATASETS, dtype=object)
        for source in EXPECTED_DATASETS:
            for target in EXPECTED_DATASETS:
                protocol = 'P1_WITHIN_DATASET_SOURCE_TEST' if source == target else 'P2_CROSS_DATASET'
                r = all_agg[
                    (all_agg['protocol'] == protocol)
                    & (all_agg['model_id'] == model_id)
                    & (all_agg['source_dataset'] == source)
                    & (all_agg['target_dataset'] == target)
                ]
                assert len(r) == 1
                rr = r.iloc[0]
                mat.loc[source, target] = float(rr[f'{metric}_mean'])
                fmt.loc[source, target] = format_mean_sd(rr[f'{metric}_mean'], rr[f'{metric}_sd'])

        mat.index = [DATASET_LABELS[d] for d in EXPECTED_DATASETS]
        mat.columns = [DATASET_LABELS[d] for d in EXPECTED_DATASETS]
        fmt.index = mat.index
        fmt.columns = mat.columns
        base = f'{model_id}_{metric}_source_target_4x4'
        write_actions[str(MATRIX_DIR / f'{base}_mean.csv')] = atomic_csv(
            MATRIX_DIR / f'{base}_mean.csv', mat, include_index=True
        )
        write_actions[str(MATRIX_DIR / f'{base}_meanSD.csv')] = atomic_csv(
            MATRIX_DIR / f'{base}_meanSD.csv', fmt, include_index=True
        )


# ============================================================================
# 9. DESCRIPTIVE MODEL-LEVEL P1 VS P2 MACRO SUMMARY
#    NOTE: THESE ARE DESCRIPTIVE MEANS ACROSS CONFIGURATIONS, NOT NEW CIs.
# ============================================================================

macro_rows = []
for model_id in EXPECTED_MODELS:
    r1 = p1[p1['model_id'] == model_id]
    r2 = p2[p2['model_id'] == model_id]
    assert len(r1) == 4
    assert len(r2) == 12
    row = {
        'model_id': model_id,
        'Model': MODEL_LABELS[model_id],
        'P1_n_configurations': 4,
        'P2_n_configurations': 12,
        'summary_type': 'descriptive_macro_mean_across_locked_configuration_means',
    }
    for metric in PERFORMANCE_METRICS:
        p1_macro = float(r1[f'{metric}_mean'].astype(float).mean())
        p2_macro = float(r2[f'{metric}_mean'].astype(float).mean())
        row[f'P1_{metric}_macro_mean'] = p1_macro
        row[f'P2_{metric}_macro_mean'] = p2_macro
        row[f'Delta_P2_minus_P1_{metric}'] = p2_macro - p1_macro
    macro_rows.append(row)

macro = pd.DataFrame(macro_rows)
assert macro['model_id'].tolist() == EXPECTED_MODELS
MACRO_PATH = TABLE_DIR / 'Table_model_level_P1_vs_P2_descriptive_macro_summary_13.csv'
write_actions[str(MACRO_PATH)] = atomic_csv(MACRO_PATH, macro)


# ============================================================================
# 10. FIGURE HELPERS
# ============================================================================

def heatmap_annotated(matrix: pd.DataFrame, title: str, cbar_label: str, vmin=None, vmax=None, figsize=(10, 8)):
    fig, ax = plt.subplots(figsize=figsize)
    im = ax.imshow(matrix.to_numpy(dtype=float), aspect='auto', vmin=vmin, vmax=vmax)
    ax.set_xticks(np.arange(matrix.shape[1]))
    ax.set_xticklabels(matrix.columns, rotation=45, ha='right', fontsize=8)
    ax.set_yticks(np.arange(matrix.shape[0]))
    ax.set_yticklabels(matrix.index, fontsize=8)
    ax.set_title(title)
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label(cbar_label)
    values = matrix.to_numpy(dtype=float)
    for i in range(values.shape[0]):
        for j in range(values.shape[1]):
            ax.text(j, i, f'{values[i, j]:.3f}', ha='center', va='center', fontsize=6)
    fig.tight_layout()
    return fig


# P1 heatmaps: 13 models x 4 datasets.
figure_actions = {}
for metric in HEATMAP_METRICS:
    fig = heatmap_annotated(
        p1_numeric_matrices[metric],
        title=f'Within-dataset performance across 10 seeds - {metric}',
        cbar_label=f'{metric} (10-seed mean)',
        vmin=0.0,
        vmax=1.0,
        figsize=(10, 8),
    )
    save_figure_pair(fig, f'Figure_P1_{metric}_heatmap_13x4', figure_actions)

# P2 heatmaps: 13 models x 12 ordered source->target pairs.
for metric in HEATMAP_METRICS:
    fig = heatmap_annotated(
        p2_numeric_matrices[metric],
        title=f'Cross-dataset generalization across 10 seeds - {metric}',
        cbar_label=f'{metric} (10-seed mean)',
        vmin=0.0,
        vmax=1.0,
        figsize=(19, 8),
    )
    save_figure_pair(fig, f'Figure_P2_{metric}_heatmap_13x12', figure_actions)

# P1-vs-P2 model-level descriptive summaries. Keep locked model order; never sort by performance.
for metric in HEATMAP_METRICS:
    x = np.arange(len(EXPECTED_MODELS))
    width = 0.38
    fig, ax = plt.subplots(figsize=(14, 6))
    ax.bar(x - width / 2, macro[f'P1_{metric}_macro_mean'].to_numpy(dtype=float), width, label='P1 within-dataset')
    ax.bar(x + width / 2, macro[f'P2_{metric}_macro_mean'].to_numpy(dtype=float), width, label='P2 cross-dataset')
    ax.set_xticks(x)
    ax.set_xticklabels([MODEL_LABELS[m] for m in EXPECTED_MODELS], rotation=45, ha='right', fontsize=8)
    ax.set_ylim(0.0, 1.0)
    ax.set_ylabel(f'{metric} descriptive macro mean')
    ax.set_title(f'Within-dataset vs cross-dataset {metric} - locked 13-model scope')
    ax.legend()
    fig.tight_layout()
    save_figure_pair(fig, f'Figure_P1_vs_P2_{metric}_macro_13models', figure_actions)

write_actions.update(figure_actions)


# ============================================================================
# 11. README + CELL 35 MANIFEST
# ============================================================================

README_PATH = CELL35_DIR / 'README_CELL35_OUTPUTS.txt'
README_TEXT = f'''CELL 35 - PAPER-READY DERIVED OUTPUTS\n\nUpstream: locked Cell 34 10-seed aggregation only.\nCell 34 manifest SHA256: {EXPECTED_SHA256[CELL34_MANIFEST_PATH]}\n\nScientific constraints preserved:\n- 13-model scope unchanged.\n- 4 datasets unchanged.\n- Seeds 100..109 unchanged.\n- No training.\n- No inference.\n- No threshold tuning.\n- No bootstrap.\n- No model inclusion/exclusion based on performance.\n- Model order in all tables/figures is the pre-locked scope order, not a performance ranking.\n\nP1 tables/matrices:\n- 52 within-dataset configurations = 13 models x 4 source datasets.\n- Each reported mean/SD/CI is the locked 10-seed statistic from Cell 34.\n\nP2 tables/matrices:\n- 156 cross-dataset configurations = 13 models x 4 sources x 3 non-source targets.\n- Each reported mean/SD/CI is the locked 10-seed statistic from Cell 34.\n\nDescriptive macro summary:\n- P1 macro = unweighted descriptive mean of the four locked P1 configuration means for each model.\n- P2 macro = unweighted descriptive mean of the twelve locked P2 configuration means for each model.\n- These macro values are descriptive summaries only; no new confidence interval or hypothesis test is attached to them.\n\nFigure formats:\n- PNG at 300 dpi for manuscript assembly (PDF vector files are also provided).\n- PDF vector output for publication-quality editing.\n\nExternal_Benchmark_1 and External_Benchmark_3 are retained exactly as locked dataset IDs.\nThey are NOT renamed here because Cell 35 does not invent manuscript-facing dataset names.\n'''
write_actions[str(README_PATH)] = atomic_commit_or_verify_bytes(README_PATH, README_TEXT.encode('utf-8'))

# Record only files produced under Cell35_DIR.
output_records = []
for path_str in sorted(write_actions):
    path = Path(path_str)
    assert path.is_file()
    output_records.append({
        'path': str(path),
        'sha256': sha256_file(path),
        'bytes': int(path.stat().st_size),
        'action': write_actions[path_str],
    })

CELL35_MANIFEST_PATH = MANIFEST_DIR / 'benchmark13_FINAL_cell35_paper_ready_manifest.json'
manifest = {
    'cell': 'CELL 35',
    'scope': 'benchmark13_FINAL',
    'status': 'COMPLETE',
    'purpose': 'Paper-ready tables, source-target matrices, and figures derived only from locked Cell 34 outputs',
    'training_performed': False,
    'inference_performed': False,
    'threshold_tuning_performed': False,
    'bootstrap_used': False,
    'model_selection_or_scope_change': False,
    'n_models': 13,
    'n_datasets': 4,
    'n_p1_configurations': 52,
    'n_p2_configurations': 156,
    'n_total_configurations': 208,
    'models_in_locked_order': EXPECTED_MODELS,
    'datasets_in_locked_order': EXPECTED_DATASETS,
    'core_metrics_for_paper_tables': CORE_METRICS,
    'figure_metrics': HEATMAP_METRICS,
    'descriptive_macro_summary': {
        'p1': 'unweighted mean of four locked P1 configuration means per model',
        'p2': 'unweighted mean of twelve locked P2 configuration means per model',
        'inferential_status': 'descriptive only; no new CI or hypothesis test',
    },
    'upstream': {
        'cell34_manifest_path': str(CELL34_MANIFEST_PATH),
        'cell34_manifest_sha256': sha256_file(CELL34_MANIFEST_PATH),
        'aggregate_all_path': str(ALL_AGG_PATH),
        'aggregate_all_sha256': sha256_file(ALL_AGG_PATH),
        'p1_path': str(P1_AGG_PATH),
        'p1_sha256': sha256_file(P1_AGG_PATH),
        'p2_path': str(P2_AGG_PATH),
        'p2_sha256': sha256_file(P2_AGG_PATH),
    },
    'outputs': output_records,
}
manifest_action = atomic_json(CELL35_MANIFEST_PATH, manifest)


# ============================================================================
# 12. FINAL HARD GATES / STATUS
# ============================================================================

# Re-read main derived tables and matrices.
assert len(pd.read_csv(P1_PAPER_PATH, keep_default_na=False, na_filter=False)) == 52
assert len(pd.read_csv(P2_PAPER_PATH, keep_default_na=False, na_filter=False)) == 156
assert len(pd.read_csv(MACRO_PATH, keep_default_na=False, na_filter=False)) == 13
for metric in CORE_METRICS:
    p1_chk = pd.read_csv(MATRIX_DIR / f'P1_{metric}_mean_13x4.csv', index_col=0)
    p2_chk = pd.read_csv(MATRIX_DIR / f'P2_{metric}_mean_13x12.csv', index_col=0)
    assert p1_chk.shape == (13, 4)
    assert p2_chk.shape == (13, 12)
    assert np.isfinite(p1_chk.to_numpy(dtype=float)).all()
    assert np.isfinite(p2_chk.to_numpy(dtype=float)).all()

# Figure existence and non-empty hard gate.
figure_paths = sorted(FIG_DIR.glob('Figure_*.*'))
assert len(figure_paths) == 12, f'Expected 12 figure files (6 PNG + 6 PDF), found {len(figure_paths)}'
for fp in figure_paths:
    assert fp.stat().st_size > 1000, f'Figure unexpectedly small/empty: {fp}'

print('=' * 144)
print('CELL 35 STATUS')
print('=' * 144)
print('Training performed           : FALSE')
print('Inference performed          : FALSE')
print('Threshold tuning             : FALSE')
print('Model selection              : FALSE')
print('Scope changed                : FALSE')
print('Locked configurations used   : 208 / 208')
print('P1 paper rows                : 52 / 52')
print('P2 paper rows                : 156 / 156')
print('Model macro rows             : 13 / 13 (DESCRIPTIVE ONLY)')
print('P1 core matrices             : 4 metrics x 13x4')
print('P2 core matrices             : 4 metrics x 13x12')
print('Per-model full matrices      : 13 models x 2 metrics x 4x4')
print('Figure files                 : 12 (6 PNG + 6 PDF)')
print('Figure model order           : LOCKED SCOPE ORDER / NOT PERFORMANCE RANKED')
print('-' * 144)
print('Paper-ready root             :', CELL35_DIR)
print('Tables                       :', TABLE_DIR)
print('Matrices                     :', MATRIX_DIR)
print('Figures                      :', FIG_DIR)
print('README                       :', README_PATH)
print('Cell 35 manifest             :', CELL35_MANIFEST_PATH)
print('  SHA256                     :', sha256_file(CELL35_MANIFEST_PATH))
print('Manifest action              :', manifest_action)
print('=' * 144)
print('CELL 35 PASS - PAPER-READY DERIVED OUTPUTS COMPLETE; NO TRAINING / NO INFERENCE / NO SCOPE CHANGE')
print('NEXT         - REVIEW CELL 35 TABLES/FIGURES, THEN MAP EXACT RESULTS INTO THE MANUSCRIPT')
print('=' * 144)

================================================================================================================================================
CELL 35 - FINAL PAPER-READY TABLES + CROSS-DATASET MATRICES + FIGURES
================================================================================================================================================
Cell 34 manifest             : VERIFIED BY SHA256
Cell 34 aggregate rows       : 208
Models                       : 13
Datasets                     : 4
Training performed           : FALSE
Inference performed          : FALSE
Threshold tuning             : FALSE
Model selection/reranking    : FALSE
Scope change                 : FALSE
------------------------------------------------------------------------------------------------------------------------------------------------
Input integrity              : PASS
P1 configurations            : 52 / 52
P2 configurations            : 156 / 156
All 10-seed statistics       : FINITE / COMPLETE
------------------------------------------------------------------------------------------------------------------------------------------------
================================================================================================================================================
CELL 35 STATUS
================================================================================================================================================
Training performed           : FALSE
Inference performed          : FALSE
Threshold tuning             : FALSE
Model selection              : FALSE
Scope changed                : FALSE
Locked configurations used   : 208 / 208
P1 paper rows                : 52 / 52
P2 paper rows                : 156 / 156
Model macro rows             : 13 / 13 (DESCRIPTIVE ONLY)
P1 core matrices             : 4 metrics x 13x4
P2 core matrices             : 4 metrics x 13x12
Per-model full matrices      : 13 models x 2 metrics x 4x4
Figure files                 : 12 (6 PNG + 6 PDF)
Figure model order           : LOCKED SCOPE ORDER / NOT PERFORMANCE RANKED
------------------------------------------------------------------------------------------------------------------------------------------------
Paper-ready root             : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready
Tables                       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/tables
Matrices                     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/matrices
Figures                      : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures
README                       : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/README_CELL35_OUTPUTS.txt
Cell 35 manifest             : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/manifests/benchmark13_FINAL_cell35_paper_ready_manifest.json
  SHA256                     : 5706726f802924ff03c3f3b24d2ddc1a32015f83d29a452ca56eb6e15c8ac094
Manifest action              : NEW_ATOMIC_COMMIT
================================================================================================================================================
CELL 35 PASS - PAPER-READY DERIVED OUTPUTS COMPLETE; NO TRAINING / NO INFERENCE / NO SCOPE CHANGE
NEXT         - REVIEW CELL 35 TABLES/FIGURES, THEN MAP EXACT RESULTS INTO THE MANUSCRIPT
================================================================================================================================================

In [56]:
from __future__ import annotations

# ============================================================================
# CELL 36 - EXACT MODEL CONFIGURATION + COMPUTATIONAL COST TABLES
# FINAL 13-MODEL BENCHMARK / READ-ONLY DERIVATION
# ============================================================================
# PURPOSE
#   Build paper-ready tables directly from the artifacts actually produced by
#   Cells 32-35. No value is guessed from memory and no model is executed.
#
#   Table A: exact model configuration / representation / training policy.
#   Table B: measured training + evaluation efficiency across 40 runs/model.
#   Table C: measured timing/resource breakdown by model x source dataset.
#   Table D: hardware/software environment and resource provenance.
#   Table E: performance + efficiency summary merged with locked Cell 35 macro.
#
# SCIENTIFIC BOUNDARY
#   - NO training
#   - NO inference
#   - NO threshold tuning
#   - NO model selection/reranking
#   - NO recomputation of performance metrics
#   - Reads only locked configs, histories, resources, manifests and Cell35 output
# ============================================================================

from pathlib import Path
from datetime import datetime
import hashlib
import json
import math
import os
import platform
import re
import subprocess

import numpy as np
import pandas as pd


# ============================================================================
# 1. LOCKED PATHS / EXPECTED HASHES
# ============================================================================

PROJECT_ROOT = Path('/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026')
OUTPUT_ROOT = PROJECT_ROOT / 'benchmark17_outputs'
AUDIT_DIR = OUTPUT_ROOT / 'audit'
MANIFEST_DIR = OUTPUT_ROOT / 'manifests'
RESULTS_ROOT = OUTPUT_ROOT / 'results'
WORK_ROOT = Path('/home/pc/genpept_benchmark17_work')

TRAINING_SCOPE_PATH = AUDIT_DIR / 'benchmark13_FINAL_training_run_scope_520.csv'
MODEL_SCOPE_PATH = AUDIT_DIR / 'benchmark13_FINAL_model_scope_lock.csv'
EVAL_LEDGER_PATH = AUDIT_DIR / 'benchmark13_FINAL_cell33_evaluation_ledger_2080.csv'
CELL33_SUMMARY_PATH = AUDIT_DIR / 'benchmark13_FINAL_cell33_summary.json'
CELL34_MANIFEST_PATH = MANIFEST_DIR / 'benchmark13_FINAL_cell34_10seed_aggregation_manifest.json'
CELL35_MANIFEST_PATH = MANIFEST_DIR / 'benchmark13_FINAL_cell35_paper_ready_manifest.json'
CONTROLLED_CONTRACT_PATH = MANIFEST_DIR / 'benchmark17_FINAL_controlled_model_contract.json'
PUBLISHED_ROUTE_CONTRACT_PATH = MANIFEST_DIR / 'benchmark17_FINAL_published_method_route_contract.json'
ENVIRONMENT_AUDIT_PATH = MANIFEST_DIR / 'environment_audit.json'
CELL32_TRAINER_PATH = PROJECT_ROOT / 'scripts_manual' / 'Cell32_Benchmark17_Production_Trainer_v9.py'

CELL35_TABLE_DIR = RESULTS_ROOT / 'benchmark13_FINAL' / 'cell35_paper_ready' / 'tables'
CELL35_MACRO_PATH = CELL35_TABLE_DIR / 'Table_model_level_P1_vs_P2_descriptive_macro_summary_13.csv'

OUT_ROOT = RESULTS_ROOT / 'benchmark13_FINAL' / 'cell36_model_config_runtime_resources'
OUT_ROOT.mkdir(parents=True, exist_ok=True)

TABLE_A_PATH = OUT_ROOT / 'Table_A_exact_model_configuration_13.csv'
TABLE_B_PATH = OUT_ROOT / 'Table_B_training_and_evaluation_efficiency_13.csv'
TABLE_C_PATH = OUT_ROOT / 'Table_C_runtime_by_model_and_source_dataset_52.csv'
TABLE_D_PATH = OUT_ROOT / 'Table_D_hardware_software_environment.csv'
TABLE_E_PATH = OUT_ROOT / 'Table_E_performance_plus_efficiency_13.csv'
FULL_CONFIG_JSON_PATH = OUT_ROOT / 'Table_A_exact_model_configuration_full_13.json'
README_PATH = OUT_ROOT / 'README_CELL36_TABLES.txt'
MANIFEST_PATH = MANIFEST_DIR / 'benchmark13_FINAL_cell36_model_config_runtime_resources_manifest.json'

EXPECTED_SHA256 = {
    CELL33_SUMMARY_PATH: '0391505d09b91a7a9518b51f6c75af85af29ac7c70e225efd4b2f1c7163c178f',
    CELL34_MANIFEST_PATH: '68ea7dedcdbc36d7d48acdd7eb856a0e8a7b17b80f885cae917307a811d18869',
    CELL35_MANIFEST_PATH: '5706726f802924ff03c3f3b24d2ddc1a32015f83d29a452ca56eb6e15c8ac094',
    CELL32_TRAINER_PATH: 'bc2276c2377e0c0730892c78412e307949547b4771b1eca10073c6ff125e5b6d',
}

EXPECTED_MODELS = [
    'logistic_regression',
    'linear_svm_calibrated',
    'random_forest',
    'extra_trees',
    'hist_gradient_boosting',
    'lightgbm',
    'cnn1d',
    'bilstm',
    'bilstm_attention',
    'transformer_encoder',
    'ampep',
    'ampscannerv2',
    'ampeppy',
]
EXPECTED_DATASETS = [
    'GenPept_Curated_2025',
    'External_Benchmark_1',
    'AMPlify_balanced',
    'External_Benchmark_3',
]
EXPECTED_SEEDS = list(range(100, 110))

MODEL_LABELS = {
    'logistic_regression': 'Logistic Regression',
    'linear_svm_calibrated': 'Calibrated Linear SVM',
    'random_forest': 'Random Forest',
    'extra_trees': 'Extra Trees',
    'hist_gradient_boosting': 'HistGradientBoosting',
    'lightgbm': 'LightGBM',
    'cnn1d': 'CNN1D',
    'bilstm': 'BiLSTM',
    'bilstm_attention': 'BiLSTM-Attention',
    'transformer_encoder': 'Transformer Encoder',
    'ampep': 'AmPEP',
    'ampscannerv2': 'AMPScannerV2',
    'ampeppy': 'amPEPpy',
}

CONTROLLED_CLASSICAL = EXPECTED_MODELS[:6]
CONTROLLED_DEEP = EXPECTED_MODELS[6:10]
PUBLISHED = EXPECTED_MODELS[10:]


# ============================================================================
# 2. GENERIC HELPERS
# ============================================================================

def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(chunk_size), b''):
            h.update(chunk)
    return h.hexdigest()


def load_json(path: Path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def read_csv_exact(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, low_memory=False, keep_default_na=False, na_filter=False)


def numeric_or_nan(value) -> float:
    try:
        if value is None or value == '':
            return float('nan')
        out = float(value)
        return out if np.isfinite(out) else float('nan')
    except Exception:
        return float('nan')


def mean_sd(series) -> tuple[float, float]:
    x = pd.to_numeric(pd.Series(series), errors='coerce').dropna().to_numpy(dtype=float)
    if len(x) == 0:
        return float('nan'), float('nan')
    return float(np.mean(x)), float(np.std(x, ddof=1)) if len(x) > 1 else 0.0


def fmt_mean_sd(mean: float, sd: float, digits: int = 2, unit: str = '') -> str:
    if not (np.isfinite(mean) and np.isfinite(sd)):
        return 'Not applicable'
    tail = f' {unit}' if unit else ''
    return f'{mean:.{digits}f} +/- {sd:.{digits}f}{tail}'


def fmt_number(x, digits=4):
    x = numeric_or_nan(x)
    if not np.isfinite(x):
        return 'Not applicable'
    return f'{x:.{digits}g}'


def unique_nonempty(values):
    out = []
    for v in values:
        if v is None:
            continue
        s = str(v).strip()
        if not s or s.lower() in {'nan', 'none'}:
            continue
        if s not in out:
            out.append(s)
    return out


def compact_json(obj, max_chars=700):
    s = json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    return s if len(s) <= max_chars else s[:max_chars - 3] + '...'


def recursive_values_by_key(obj, wanted_keys):
    wanted = {str(k).lower() for k in wanted_keys}
    found = []
    def walk(x, path=''):
        if isinstance(x, dict):
            for k, v in x.items():
                p = f'{path}.{k}' if path else str(k)
                if str(k).lower() in wanted:
                    found.append((p, v))
                walk(v, p)
        elif isinstance(x, list):
            for i, v in enumerate(x):
                walk(v, f'{path}[{i}]')
    walk(obj)
    return found


def first_recursive_value(obj, keys):
    vals = recursive_values_by_key(obj, keys)
    return vals[0][1] if vals else None


def atomic_write_text(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    data = text.encode('utf-8')
    if path.exists():
        if path.read_bytes() != data:
            raise AssertionError(f'Existing derived file differs; refusing overwrite: {path}')
        return 'VERIFIED_UNCHANGED'
    tmp = path.with_suffix(path.suffix + '.tmp')
    tmp.write_bytes(data)
    os.replace(tmp, path)
    return 'NEW_ATOMIC_COMMIT'


def atomic_write_csv(path: Path, df: pd.DataFrame):
    return atomic_write_text(path, df.to_csv(index=False, lineterminator='\n'))


def atomic_write_json(path: Path, obj):
    text = json.dumps(obj, ensure_ascii=False, indent=2, sort_keys=True) + '\n'
    return atomic_write_text(path, text)


def subprocess_stdout(cmd):
    try:
        r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=False, timeout=15)
        return r.stdout.strip() if r.returncode == 0 else ''
    except Exception:
        return ''


# ============================================================================
# 3. VERIFY LOCKED UPSTREAM ARTIFACTS
# ============================================================================

for p in [PROJECT_ROOT, OUTPUT_ROOT, AUDIT_DIR, MANIFEST_DIR, RESULTS_ROOT]:
    if not p.is_dir():
        raise FileNotFoundError(f'Required directory missing: {p}')

for p in [
    TRAINING_SCOPE_PATH, MODEL_SCOPE_PATH, EVAL_LEDGER_PATH,
    CONTROLLED_CONTRACT_PATH, PUBLISHED_ROUTE_CONTRACT_PATH,
    ENVIRONMENT_AUDIT_PATH, CELL35_MACRO_PATH,
    *EXPECTED_SHA256.keys(),
]:
    if not p.is_file():
        raise FileNotFoundError(f'Required artifact missing: {p}')

for p, expected in EXPECTED_SHA256.items():
    actual = sha256_file(p)
    if actual != expected:
        raise AssertionError(f'Locked upstream SHA mismatch: {p}\nexpected={expected}\nactual={actual}')

training_scope = read_csv_exact(TRAINING_SCOPE_PATH)
model_scope = read_csv_exact(MODEL_SCOPE_PATH)
eval_ledger = read_csv_exact(EVAL_LEDGER_PATH)
macro = read_csv_exact(CELL35_MACRO_PATH)

if len(training_scope) != 520:
    raise AssertionError(f'Expected 520 locked training runs, found {len(training_scope)}')
if len(eval_ledger) != 2080:
    raise AssertionError(f'Expected 2080 evaluation rows, found {len(eval_ledger)}')
if not eval_ledger['status'].astype(str).eq('EVALUATED').all():
    raise AssertionError('Cell 33 ledger contains non-EVALUATED rows.')
if training_scope['model_id'].drop_duplicates().tolist() != EXPECTED_MODELS:
    raise AssertionError('13-model order differs from locked scope.')
if training_scope.groupby('model_id').size().to_dict() != {m: 40 for m in EXPECTED_MODELS}:
    raise AssertionError('Expected exactly 40 training runs/model.')
if not training_scope.groupby(['model_id', 'source_dataset']).size().eq(10).all():
    raise AssertionError('Expected exactly 10 runs/model/source dataset.')
if sorted(pd.to_numeric(training_scope['seed'], errors='raise').astype(int).unique().tolist()) != EXPECTED_SEEDS:
    raise AssertionError('Seed schedule differs from locked 100..109.')
if macro['model_id'].astype(str).tolist() != EXPECTED_MODELS:
    raise AssertionError('Cell35 macro model order differs from locked scope.')

controlled_payload = load_json(CONTROLLED_CONTRACT_PATH)
controlled = controlled_payload['contract']
published_payload = load_json(PUBLISHED_ROUTE_CONTRACT_PATH)
published_methods = published_payload['contract']['methods']
env_audit = load_json(ENVIRONMENT_AUDIT_PATH)


# ============================================================================
# 4. READ EXACT 520 TRAINING RESOURCE BUNDLES
# ============================================================================

train_rows = []
config_snapshot = {}

for i, row in enumerate(training_scope.itertuples(index=False), start=1):
    run_id = str(row.run_id)
    model_id = str(row.model_id)
    run_dir = Path(str(row.run_dir))
    config_path = run_dir / 'config.json'
    resources_path = run_dir / 'resources.json'
    history_path = run_dir / 'history.csv'
    manifest_path = run_dir / 'run_manifest.json'

    for p in [config_path, resources_path, history_path]:
        if not p.is_file():
            raise FileNotFoundError(f'Missing canonical training artifact for {run_id}: {p}')

    cfg = load_json(config_path)
    res = load_json(resources_path)
    hist = read_csv_exact(history_path)

    if str(cfg['run_id']) != run_id or str(res['run_id']) != run_id:
        raise AssertionError(f'Run identity mismatch in {run_id}')
    if str(cfg['model_id']) != model_id or str(res['model_id']) != model_id:
        raise AssertionError(f'Model identity mismatch in {run_id}')

    if model_id not in config_snapshot:
        config_snapshot[model_id] = cfg
    else:
        # Scientific model configuration must not vary across seeds/sources.
        old = config_snapshot[model_id]
        if model_id in CONTROLLED_CLASSICAL + CONTROLLED_DEEP:
            if cfg.get('locked_model_config') != old.get('locked_model_config'):
                raise AssertionError(f'Controlled config drift detected: {model_id}')
        else:
            if cfg.get('locked_published_route') != old.get('locked_published_route'):
                raise AssertionError(f'Published route drift detected: {model_id}')

    epoch_values = pd.to_numeric(hist.get('epoch', pd.Series(dtype=float)), errors='coerce')
    epoch_values = epoch_values[np.isfinite(epoch_values) & (epoch_values > 0)]
    epochs_completed = int(epoch_values.max()) if len(epoch_values) else 0
    if model_id == 'ampscannerv2':
        # Exact Cell32 v9 wrapper explicitly recorded official fixed 10-epoch fit.
        epochs_completed = 10

    training_seconds = numeric_or_nan(res.get('training_seconds'))
    per_epoch_seconds = training_seconds / epochs_completed if epochs_completed > 0 and np.isfinite(training_seconds) else float('nan')
    train_n = int(getattr(row, 'train_n'))
    training_seq_per_sec = train_n / training_seconds if np.isfinite(training_seconds) and training_seconds > 0 else float('nan')

    train_rows.append({
        'run_id': run_id,
        'model_id': model_id,
        'source_dataset': str(row.source_dataset),
        'seed': int(row.seed),
        'train_n': train_n,
        'device': str(res.get('device', '')),
        'training_seconds': training_seconds,
        'epochs_completed': epochs_completed if epochs_completed > 0 else np.nan,
        'training_seconds_per_epoch': per_epoch_seconds,
        'training_sequences_per_second': training_seq_per_sec,
        'validation_seconds': numeric_or_nan(res.get('validation_seconds')),
        'feature_or_token_load_seconds': numeric_or_nan(res.get('feature_or_token_load_seconds')),
        'preprocessing_seconds': numeric_or_nan(res.get('preprocessing_seconds')),
        'peak_process_ram_mb': numeric_or_nan(res.get('peak_process_ram_mb')),
        'peak_gpu_vram_mb': numeric_or_nan(res.get('peak_gpu_vram_mb')),
        'model_parameter_count': numeric_or_nan(res.get('model_parameter_count')),
        'checkpoint_size_mb': numeric_or_nan(res.get('checkpoint_size_mb')),
        'timing_provenance': str(res.get('timing_provenance', '')),
        'executor_parallel_context': str(res.get('executor_parallel_context', '')),
    })

train_df = pd.DataFrame(train_rows)
if len(train_df) != 520:
    raise AssertionError('Training resource table is incomplete.')


# ============================================================================
# 5. READ EXACT 2080 EVALUATION RESOURCE BUNDLES AND STANDARDIZE PER-RUN COST
# ============================================================================

# Cell33 wrote four evaluation bundles for every trained checkpoint.
eval_resource_rows = []
for row in eval_ledger.itertuples(index=False):
    eval_id = str(row.eval_id)
    manifest_path = Path(str(row.eval_manifest))
    if not manifest_path.is_file():
        raise FileNotFoundError(f'Missing evaluation manifest: {manifest_path}')
    out_dir = manifest_path.parent
    resources_path = out_dir / 'resources.json'
    metrics_path = out_dir / 'metrics.json'
    if not resources_path.is_file() or not metrics_path.is_file():
        raise FileNotFoundError(f'Missing evaluation resources/metrics: {eval_id}')
    res = load_json(resources_path)
    met = load_json(metrics_path)
    m = met['metrics']
    eval_resource_rows.append({
        'eval_id': eval_id,
        'run_id': str(row.run_id),
        'model_id': str(row.model_id),
        'source_dataset': str(row.source_dataset),
        'target_dataset': str(row.target_dataset),
        'seed': int(row.seed),
        'target_n': int(m['n']),
        'device': str(res.get('device', '')),
        'model_load_seconds': numeric_or_nan(res.get('model_load_seconds')),
        'preprocessing_or_cache_load_seconds': numeric_or_nan(res.get('preprocessing_or_cache_load_seconds')),
        'model_inference_seconds': numeric_or_nan(res.get('model_inference_seconds')),
        'combined_wrapper_seconds': numeric_or_nan(res.get('combined_wrapper_seconds')),
        'peak_parent_process_ram_mb': numeric_or_nan(res.get('peak_parent_process_ram_mb')),
        'timing_provenance': str(res.get('timing_provenance', '')),
    })

eval_df = pd.DataFrame(eval_resource_rows)
if len(eval_df) != 2080:
    raise AssertionError('Evaluation resource table is incomplete.')
if not eval_df.groupby('run_id').size().eq(4).all():
    raise AssertionError('Every trained checkpoint must have exactly four final evaluation targets.')

run_eval_rows = []
for run_id, g in eval_df.groupby('run_id', sort=False):
    if len(g) != 4:
        raise AssertionError(f'Expected four evaluation rows for {run_id}')
    model_id = str(g['model_id'].iloc[0])
    source_dataset = str(g['source_dataset'].iloc[0])
    seed = int(g['seed'].iloc[0])
    total_n = int(g['target_n'].sum())

    combined = pd.to_numeric(g['combined_wrapper_seconds'], errors='coerce').dropna().to_numpy(dtype=float)
    if len(combined):
        # Deep/legacy route: Cell33 measured one wrapper call over all four targets,
        # and repeated that same value in each target resource record.
        if np.max(combined) - np.min(combined) > 1e-9:
            raise AssertionError(f'Combined wrapper timing differs within run {run_id}')
        eval_seconds = float(combined[0])
        timing_basis = 'one checkpoint load + all 4 targets; combined wrapper wall time'
    else:
        load_vals = pd.to_numeric(g['model_load_seconds'], errors='coerce').dropna().to_numpy(dtype=float)
        load_once = float(load_vals[0]) if len(load_vals) else 0.0
        if len(load_vals) and (np.max(load_vals) - np.min(load_vals) > 1e-9):
            raise AssertionError(f'Model-load timing differs within run {run_id}')
        prep = float(pd.to_numeric(g['preprocessing_or_cache_load_seconds'], errors='coerce').fillna(0.0).sum())
        infer = float(pd.to_numeric(g['model_inference_seconds'], errors='coerce').fillna(0.0).sum())
        eval_seconds = load_once + prep + infer
        timing_basis = 'one checkpoint load + sum preprocessing + model inference across all 4 targets'

    if not np.isfinite(eval_seconds) or eval_seconds <= 0:
        raise AssertionError(f'Invalid final evaluation timing for {run_id}: {eval_seconds}')

    run_eval_rows.append({
        'run_id': str(run_id),
        'model_id': model_id,
        'source_dataset': source_dataset,
        'seed': seed,
        'evaluation_targets': 4,
        'evaluation_total_sequences': total_n,
        'evaluation_4targets_seconds': eval_seconds,
        'evaluation_ms_per_sequence': 1000.0 * eval_seconds / total_n,
        'evaluation_sequences_per_second': total_n / eval_seconds,
        'evaluation_timing_basis': timing_basis,
        'evaluation_device': '; '.join(unique_nonempty(g['device'].tolist())),
        'evaluation_timing_provenance': '; '.join(unique_nonempty(g['timing_provenance'].tolist())),
    })

run_eval_df = pd.DataFrame(run_eval_rows)
if len(run_eval_df) != 520:
    raise AssertionError('Expected exactly 520 checkpoint-level final evaluation timings.')

run_resource = train_df.merge(
    run_eval_df,
    on=['run_id', 'model_id', 'source_dataset', 'seed'],
    how='inner',
    validate='one_to_one',
)
if len(run_resource) != 520:
    raise AssertionError('Training/evaluation run merge is incomplete.')


# ============================================================================
# 6. TABLE A - EXACT MODEL CONFIGURATION
# ============================================================================

classical_rep = controlled['classical_representation']
deep_rep = controlled['deep_representation']
deep_shared = controlled['deep_shared_training']
controlled_cfgs = controlled['model_configs']

full_config_payload = {
    'cell': 'CELL36_EXACT_MODEL_CONFIG_RUNTIME_RESOURCE_TABLES',
    'cell32_trainer_sha256': EXPECTED_SHA256[CELL32_TRAINER_PATH],
    'controlled_contract_sha256': sha256_file(CONTROLLED_CONTRACT_PATH),
    'published_route_contract_sha256': sha256_file(PUBLISHED_ROUTE_CONTRACT_PATH),
    'models': {},
}

config_rows = []

for model_id in EXPECTED_MODELS:
    label = MODEL_LABELS[model_id]
    tr = train_df[train_df['model_id'].eq(model_id)]
    devices = '; '.join(unique_nonempty(tr['device'].tolist()))
    param_values = pd.to_numeric(tr['model_parameter_count'], errors='coerce').dropna().unique()
    checkpoint_mean, checkpoint_sd = mean_sd(tr['checkpoint_size_mb'])

    if model_id in CONTROLLED_CLASSICAL:
        cfg = controlled_cfgs[model_id]
        representation = (
            f"{classical_rep['representation_id']} "
            f"({classical_rep['feature_dimension']}D: Length_norm + AAC20 + DPC400)"
        )
        estimator = cfg.get('estimator', cfg.get('base_estimator', {}))
        architecture_or_estimator = compact_json(cfg)
        optimizer = 'Not applicable (classical estimator)'
        lr = estimator.get('learning_rate', 'Not applicable') if isinstance(estimator, dict) else 'Not applicable'
        batch_size = 'Not applicable (non-mini-batch fit)'
        if model_id == 'hist_gradient_boosting':
            early_stopping = 'Disabled in locked config'
        else:
            early_stopping = 'Not applicable'
        parameter_text = 'Not defined as neural trainable-parameter count'
        hyper_selection = 'Hyperparameters pre-locked before training; no test/target tuning'
        max_epochs = 'Not epoch-based'
        config_source = 'benchmark17_FINAL_controlled_model_contract.json'
        full_cfg = cfg

    elif model_id in CONTROLLED_DEEP:
        cfg = controlled_cfgs[model_id]
        representation = (
            f"{deep_rep['representation_id']} (raw peptide; max length {deep_rep['maximum_length']}; "
            f"post-padding; trainable embedding)"
        )
        architecture_or_estimator = compact_json(cfg['architecture'])
        optimizer = str(deep_shared['optimizer'])
        lr = deep_shared['learning_rate']
        batch_size = deep_shared['batch_size']
        es = deep_shared['early_stopping']
        early_stopping = (
            f"Yes: {es['monitor']}, patience={es['patience']}, min_delta={es['min_delta']}, "
            f"restore_best_weights={es['restore_best_weights']}"
        )
        if len(param_values) != 1:
            raise AssertionError(f'Expected one exact parameter count for {model_id}, found {param_values}')
        parameter_text = str(int(round(float(param_values[0]))))
        hyper_selection = 'Architecture/training hyperparameters pre-locked; source validation only for early stopping and tau*'
        max_epochs = int(deep_shared['maximum_epochs'])
        config_source = 'benchmark17_FINAL_controlled_model_contract.json + measured Cell32 resources.json'
        full_cfg = cfg

    elif model_id == 'ampep':
        route = published_methods[model_id]
        representation = '105D Seq2Distribution descriptors used by the exact Cell32 v9 AmPEP wrapper'
        architecture_or_estimator = 'RandomForestClassifier(n_estimators=100, max_features=11, criterion=gini, bootstrap=True)'
        optimizer = 'Not applicable (Random Forest)'
        lr = 'Not applicable'
        batch_size = 'Not applicable'
        early_stopping = 'Not applicable (non-iterative estimator)'
        parameter_text = 'Not defined as neural trainable-parameter count'
        hyper_selection = 'Published recipe fixed before benchmark; no test/target tuning'
        max_epochs = 'Not epoch-based'
        config_source = 'Cell32 v9 exact production wrapper + locked published route'
        full_cfg = {'locked_published_route': route, 'cell32_exact_wrapper': {'features': 105, 'n_estimators': 100, 'max_features': 11}}

    elif model_id == 'ampscannerv2':
        route = published_methods[model_id]
        impl_path = MANIFEST_DIR / 'benchmark17_ampscannerv2_FINAL_implementation_contract.json'
        impl = load_json(impl_path) if impl_path.is_file() else {}
        impl_contract = impl.get('contract', impl)
        optimizer_value = first_recursive_value(impl_contract, ['optimizer'])
        batch_value = first_recursive_value(impl_contract, ['batch_size'])
        epochs_value = first_recursive_value(impl_contract, ['epochs'])
        lr_value = first_recursive_value(impl_contract, ['learning_rate', 'lr'])
        representation = 'Integer amino-acid encoding padded to length 200 + learned 128D embedding (official source route)'
        architecture_or_estimator = 'Embedding(21,128) -> Conv1D(64,k=16) -> MaxPool(5) -> LSTM(100) -> sigmoid'
        optimizer = str(optimizer_value) if optimizer_value is not None else 'Adam (official source; optimizer locked)'
        lr = lr_value if lr_value is not None else 'Not explicitly set in locked implementation contract'
        batch_size = batch_value if batch_value is not None else 32
        early_stopping = 'No benchmark-added early stopping; official fixed-epoch source fit'
        parameter_text = 'Not recorded as count_params by locked TF1 production route'
        hyper_selection = 'Official source architecture/training recipe locked; no benchmark test/target tuning'
        max_epochs = epochs_value if epochs_value is not None else 10
        config_source = 'benchmark17_ampscannerv2_FINAL_implementation_contract.json + Cell32 v9 wrapper'
        full_cfg = {'locked_published_route': route, 'implementation_contract': impl_contract}

    elif model_id == 'ampeppy':
        route = published_methods[model_id]
        representation = 'Official amPEPpy v1.0 feature pipeline (CTD/distribution descriptor family)'
        architecture_or_estimator = 'Official amPEPpy v1.0 Random Forest; num_trees=160, min_tree=23, max_tree=175'
        optimizer = 'Not applicable (Random Forest)'
        lr = 'Not applicable'
        batch_size = 'Not applicable'
        early_stopping = 'Not applicable (non-iterative estimator)'
        parameter_text = 'Not defined as neural trainable-parameter count'
        hyper_selection = 'Official source retraining recipe locked; no test/target tuning'
        max_epochs = 'Not epoch-based'
        config_source = 'benchmark17_ampeppy_FINAL_implementation_contract.json + Cell32 v9 exact wrapper'
        impl_path = MANIFEST_DIR / 'benchmark17_ampeppy_FINAL_implementation_contract.json'
        full_cfg = {'locked_published_route': route, 'implementation_contract': load_json(impl_path) if impl_path.is_file() else {}}

    else:
        raise KeyError(model_id)

    full_config_payload['models'][model_id] = full_cfg
    config_rows.append({
        'Model': label,
        'model_id': model_id,
        'Input representation': representation,
        'Trainable parameters / estimator size': parameter_text,
        'Checkpoint size MB (mean +/- SD, 40 runs)': fmt_mean_sd(checkpoint_mean, checkpoint_sd, 3),
        'Optimizer / learning algorithm': optimizer,
        'Learning rate': str(lr),
        'Batch size': str(batch_size),
        'Max epochs / iterations': str(max_epochs),
        'Early stopping': early_stopping,
        'Hyperparameter selection': hyper_selection,
        'Training device actually recorded': devices,
        'Architecture / key fixed estimator settings': architecture_or_estimator,
        'Configuration provenance': config_source,
    })

config_table = pd.DataFrame(config_rows)
if config_table['model_id'].tolist() != EXPECTED_MODELS:
    raise AssertionError('Table A model order mismatch.')


# ============================================================================
# 7. TABLE B - MODEL-LEVEL TRAINING / EVALUATION EFFICIENCY
# ============================================================================

eff_rows = []
for model_id in EXPECTED_MODELS:
    g = run_resource[run_resource['model_id'].eq(model_id)].copy()
    if len(g) != 40:
        raise AssertionError(f'Expected 40 measured runs for {model_id}, found {len(g)}')

    tr_mean, tr_sd = mean_sd(g['training_seconds'])
    ep_mean, ep_sd = mean_sd(g['epochs_completed'])
    tpe_mean, tpe_sd = mean_sd(g['training_seconds_per_epoch'])
    train_sp_mean, train_sp_sd = mean_sd(g['training_sequences_per_second'])
    ev_mean, ev_sd = mean_sd(g['evaluation_4targets_seconds'])
    ev_ms_mean, ev_ms_sd = mean_sd(g['evaluation_ms_per_sequence'])
    ev_sp_mean, ev_sp_sd = mean_sd(g['evaluation_sequences_per_second'])
    ram_mean, ram_sd = mean_sd(g['peak_process_ram_mb'])
    vram_mean, vram_sd = mean_sd(g['peak_gpu_vram_mb'])
    ck_mean, ck_sd = mean_sd(g['checkpoint_size_mb'])

    param_values = pd.to_numeric(g['model_parameter_count'], errors='coerce').dropna().unique()
    param_count = str(int(round(float(param_values[0])))) if len(param_values) == 1 else 'Not recorded / not applicable'

    timing_basis = '; '.join(unique_nonempty(g['evaluation_timing_basis'].tolist()))
    if len(unique_nonempty(g['evaluation_timing_basis'].tolist())) != 1:
        raise AssertionError(f'Multiple evaluation timing bases for {model_id}')

    eff_rows.append({
        'Model': MODEL_LABELS[model_id],
        'model_id': model_id,
        'Runs': 40,
        'Training time/run (s, mean +/- SD)': fmt_mean_sd(tr_mean, tr_sd, 2),
        'Epochs completed (mean +/- SD)': fmt_mean_sd(ep_mean, ep_sd, 2) if np.isfinite(ep_mean) else 'Not epoch-based',
        'Training time/epoch (s, mean +/- SD)': fmt_mean_sd(tpe_mean, tpe_sd, 3) if np.isfinite(tpe_mean) else 'Not epoch-based',
        'Training throughput (seq/s, mean +/- SD)': fmt_mean_sd(train_sp_mean, train_sp_sd, 2),
        'Final evaluation time / checkpoint for all 4 targets (s, mean +/- SD)': fmt_mean_sd(ev_mean, ev_sd, 2),
        'Evaluation latency (ms/sequence, mean +/- SD)': fmt_mean_sd(ev_ms_mean, ev_ms_sd, 3),
        'Evaluation throughput (seq/s, mean +/- SD)': fmt_mean_sd(ev_sp_mean, ev_sp_sd, 2),
        'Peak process RAM (MB, mean +/- SD)': fmt_mean_sd(ram_mean, ram_sd, 1),
        'Peak GPU VRAM (MB, mean +/- SD)': fmt_mean_sd(vram_mean, vram_sd, 1) if np.isfinite(vram_mean) else 'CPU / not recorded by route',
        'Checkpoint size (MB, mean +/- SD)': fmt_mean_sd(ck_mean, ck_sd, 3),
        'Exact neural parameter count': param_count,
        'Training device': '; '.join(unique_nonempty(g['device'].tolist())),
        'Evaluation device': '; '.join(unique_nonempty(g['evaluation_device'].tolist())),
        'Evaluation timing basis': timing_basis,
    })

eff_table = pd.DataFrame(eff_rows)
if eff_table['model_id'].tolist() != EXPECTED_MODELS:
    raise AssertionError('Table B model order mismatch.')


# ============================================================================
# 8. TABLE C - 13 MODELS x 4 SOURCE DATASETS = 52 MEASURED CONFIGURATIONS
# ============================================================================

by_ds_rows = []
for model_id in EXPECTED_MODELS:
    for source_dataset in EXPECTED_DATASETS:
        g = run_resource[
            run_resource['model_id'].eq(model_id) &
            run_resource['source_dataset'].eq(source_dataset)
        ].copy()
        if len(g) != 10:
            raise AssertionError(f'Expected 10 runs for {model_id} / {source_dataset}, found {len(g)}')

        tr_mean, tr_sd = mean_sd(g['training_seconds'])
        tpe_mean, tpe_sd = mean_sd(g['training_seconds_per_epoch'])
        ev_mean, ev_sd = mean_sd(g['evaluation_4targets_seconds'])
        ev_ms_mean, ev_ms_sd = mean_sd(g['evaluation_ms_per_sequence'])
        ram_mean, ram_sd = mean_sd(g['peak_process_ram_mb'])
        vram_mean, vram_sd = mean_sd(g['peak_gpu_vram_mb'])

        by_ds_rows.append({
            'Model': MODEL_LABELS[model_id],
            'model_id': model_id,
            'Source dataset': source_dataset,
            'Seeds': '100-109',
            'n_runs': 10,
            'Training time/run (s, mean +/- SD)': fmt_mean_sd(tr_mean, tr_sd, 2),
            'Training time/epoch (s, mean +/- SD)': fmt_mean_sd(tpe_mean, tpe_sd, 3) if np.isfinite(tpe_mean) else 'Not epoch-based',
            'Evaluation all 4 targets/checkpoint (s, mean +/- SD)': fmt_mean_sd(ev_mean, ev_sd, 2),
            'Evaluation latency (ms/sequence, mean +/- SD)': fmt_mean_sd(ev_ms_mean, ev_ms_sd, 3),
            'Peak process RAM (MB, mean +/- SD)': fmt_mean_sd(ram_mean, ram_sd, 1),
            'Peak GPU VRAM (MB, mean +/- SD)': fmt_mean_sd(vram_mean, vram_sd, 1) if np.isfinite(vram_mean) else 'CPU / not recorded by route',
            'Training device': '; '.join(unique_nonempty(g['device'].tolist())),
            'Evaluation device': '; '.join(unique_nonempty(g['evaluation_device'].tolist())),
        })

by_ds_table = pd.DataFrame(by_ds_rows)
if len(by_ds_table) != 52:
    raise AssertionError('Table C must have 52 rows.')


# ============================================================================
# 9. TABLE D - HARDWARE / SOFTWARE ENVIRONMENT
# ============================================================================

hardware_rows = []

def add_env(component, value, provenance):
    hardware_rows.append({'Component': component, 'Value': str(value), 'Provenance': provenance})

add_env('Python executable', env_audit.get('python', {}).get('resolved_executable', env_audit.get('python', {}).get('executable', '')), 'locked environment_audit.json')
add_env('Python version', env_audit.get('python', {}).get('version', ''), 'locked environment_audit.json')
add_env('Platform', env_audit.get('system', {}).get('platform', ''), 'locked environment_audit.json')
add_env('Machine architecture', env_audit.get('system', {}).get('machine', ''), 'locked environment_audit.json')

cpu_from_audit = str(env_audit.get('system', {}).get('processor', '')).strip()
if not cpu_from_audit:
    lscpu = subprocess_stdout(['lscpu'])
    m = re.search(r'^Model name:\s*(.+)$', lscpu, flags=re.MULTILINE)
    cpu_from_audit = m.group(1).strip() if m else 'Not recorded in locked environment audit'
    cpu_prov = 'current same-host WSL query because locked audit processor field was empty'
else:
    cpu_prov = 'locked environment_audit.json'
add_env('CPU', cpu_from_audit, cpu_prov)

# RAM was not part of the original locked Cell 2 environment schema. Report the
# current same-host WSL memory explicitly as a reporting-time supplement.
ram_total_gb = None
try:
    meminfo = Path('/proc/meminfo').read_text(encoding='utf-8')
    m = re.search(r'^MemTotal:\s+(\d+)\s+kB$', meminfo, flags=re.MULTILINE)
    if m:
        ram_total_gb = int(m.group(1)) / (1024.0 ** 2)
except Exception:
    pass
add_env('System RAM visible to WSL', f'{ram_total_gb:.2f} GB' if ram_total_gb is not None else 'Unavailable', 'current same-host WSL query; not part of original Cell 2 locked schema')

nvidia = env_audit.get('nvidia', {})
add_env('GPU', nvidia.get('gpu_name', ''), 'locked environment_audit.json')
add_env('GPU VRAM total', f"{float(nvidia.get('memory_total_mib', 0.0))/1024.0:.2f} GB", 'locked environment_audit.json')
add_env('NVIDIA driver', nvidia.get('driver_version', ''), 'locked environment_audit.json')

packages = env_audit.get('packages', {})
for pkg_label, key in [
    ('TensorFlow', 'tensorflow'),
    ('PyTorch', 'torch'),
    ('scikit-learn', 'scikit-learn'),
    ('LightGBM', 'lightgbm'),
    ('fair-esm', 'fair-esm'),
]:
    if key in packages:
        add_env(pkg_label, packages[key], 'locked environment_audit.json')

# Model-specific measured resource maxima across all 40 runs/model.
for model_id in EXPECTED_MODELS:
    g = train_df[train_df['model_id'].eq(model_id)]
    peak_ram = pd.to_numeric(g['peak_process_ram_mb'], errors='coerce').max()
    peak_vram = pd.to_numeric(g['peak_gpu_vram_mb'], errors='coerce').max()
    add_env(f'{MODEL_LABELS[model_id]} - max recorded process RAM', f'{peak_ram:.1f} MB' if np.isfinite(peak_ram) else 'Not recorded', 'Cell32 resources.json across 40 runs')
    if np.isfinite(peak_vram):
        add_env(f'{MODEL_LABELS[model_id]} - max recorded GPU VRAM', f'{peak_vram:.1f} MB', 'Cell32 resources.json across 40 runs')

hardware_table = pd.DataFrame(hardware_rows)


# ============================================================================
# 10. TABLE E - PERFORMANCE + EFFICIENCY (DESCRIPTIVE, NO NEW STATISTICS)
# ============================================================================

# Merge exact Cell35 descriptive macros with the measured efficiency table.
perf_cols = [
    'model_id', 'Model',
    'P1_AUROC_macro_mean', 'P2_AUROC_macro_mean',
    'P1_AUPRC_macro_mean', 'P2_AUPRC_macro_mean',
    'P1_MCC_macro_mean', 'P2_MCC_macro_mean',
    'P1_F1_macro_mean', 'P2_F1_macro_mean',
]
for c in perf_cols:
    if c not in macro.columns:
        raise AssertionError(f'Expected Cell35 macro column missing: {c}')

perf = macro[perf_cols].copy()
# Keep numeric raw timing columns for this combined table rather than formatted strings.
eff_numeric = []
for model_id in EXPECTED_MODELS:
    g = run_resource[run_resource['model_id'].eq(model_id)]
    tr_mean, tr_sd = mean_sd(g['training_seconds'])
    ev_mean, ev_sd = mean_sd(g['evaluation_4targets_seconds'])
    ev_ms_mean, ev_ms_sd = mean_sd(g['evaluation_ms_per_sequence'])
    ram_mean, ram_sd = mean_sd(g['peak_process_ram_mb'])
    vram_mean, vram_sd = mean_sd(g['peak_gpu_vram_mb'])
    eff_numeric.append({
        'model_id': model_id,
        'training_seconds_mean': tr_mean,
        'training_seconds_sd': tr_sd,
        'evaluation_4targets_seconds_mean': ev_mean,
        'evaluation_4targets_seconds_sd': ev_sd,
        'evaluation_ms_per_sequence_mean': ev_ms_mean,
        'evaluation_ms_per_sequence_sd': ev_ms_sd,
        'peak_process_ram_mb_mean': ram_mean,
        'peak_process_ram_mb_sd': ram_sd,
        'peak_gpu_vram_mb_mean': vram_mean,
        'peak_gpu_vram_mb_sd': vram_sd,
    })
combined_table = perf.merge(pd.DataFrame(eff_numeric), on='model_id', how='inner', validate='one_to_one')
if combined_table['model_id'].tolist() != EXPECTED_MODELS:
    raise AssertionError('Table E model order mismatch.')
combined_table.insert(2, 'summary_note', 'Performance values are Cell35 descriptive macro means; runtime values are measured across 40 locked runs/model')


# ============================================================================
# 11. WRITE DERIVED OUTPUTS ATOMICALLY
# ============================================================================

write_actions = {
    str(TABLE_A_PATH): atomic_write_csv(TABLE_A_PATH, config_table),
    str(TABLE_B_PATH): atomic_write_csv(TABLE_B_PATH, eff_table),
    str(TABLE_C_PATH): atomic_write_csv(TABLE_C_PATH, by_ds_table),
    str(TABLE_D_PATH): atomic_write_csv(TABLE_D_PATH, hardware_table),
    str(TABLE_E_PATH): atomic_write_csv(TABLE_E_PATH, combined_table),
    str(FULL_CONFIG_JSON_PATH): atomic_write_json(FULL_CONFIG_JSON_PATH, full_config_payload),
}

README = f'''CELL 36 - EXACT MODEL CONFIGURATION + COMPUTATIONAL COST TABLES\n\nScientific source of every value:\n- Model scope: locked 13-model Cell32B scope.\n- Hyperparameters/configuration: locked controlled-model contract, locked published-method route/implementation contracts, and exact Cell32 v9 production wrapper (SHA256 {EXPECTED_SHA256[CELL32_TRAINER_PATH]}).\n- Training runtime/resources: the 520 canonical Cell32 resources.json + history.csv artifacts.\n- Evaluation runtime: the 2080 committed Cell33 evaluation resources, standardized to one trained checkpoint evaluated over all four locked target datasets.\n- Performance: existing Cell35 descriptive macro table only; no performance metric was recomputed.\n\nImportant timing interpretation:\n- Classical models and AmPEP: checkpoint load once + measured preprocessing/cache load + isolated model inference summed over all four targets.\n- Controlled deep models and legacy published routes: Cell33 combined wrapper wall time for one checkpoint over all four targets.\n- These timing bases are explicitly reported in Table B; they should not be described as pure kernel-only latency.\n- Cell32 per-run training times were measured under the recorded resource-aware parallel execution context. They are valid measured wall times, but cross-model runtime claims should mention this context.\n\nParameter-count interpretation:\n- Exact count_params was recorded by Cell32 for the four controlled TensorFlow deep models.\n- Tree/linear models do not have a directly comparable neural trainable-parameter count.\n- AMPScannerV2 TF1 production route did not record count_params; this cell does not invent it.\n\nNo training, inference, threshold tuning, model selection, seed selection, or bootstrap was performed by Cell36.\n'''
write_actions[str(README_PATH)] = atomic_write_text(README_PATH, README)

manifest = {
    'schema_version': '1.0',
    'status': 'CELL36_EXACT_TABLES_COMPLETE',
    'training_performed': False,
    'inference_performed': False,
    'threshold_tuning': False,
    'model_selection': False,
    'models': EXPECTED_MODELS,
    'datasets': EXPECTED_DATASETS,
    'seeds': EXPECTED_SEEDS,
    'training_runs_read': 520,
    'evaluation_rows_read': 2080,
    'checkpoint_level_eval_runtime_rows': 520,
    'upstream_sha256': {str(p): sha256_file(p) for p in EXPECTED_SHA256},
    'outputs': {
        str(p): {'sha256': sha256_file(p), 'size_bytes': p.stat().st_size}
        for p in [TABLE_A_PATH, TABLE_B_PATH, TABLE_C_PATH, TABLE_D_PATH, TABLE_E_PATH, FULL_CONFIG_JSON_PATH, README_PATH]
    },
}
manifest_action = atomic_write_json(MANIFEST_PATH, manifest)


# ============================================================================
# 12. NOTEBOOK DISPLAY / FINAL STATUS
# ============================================================================

print('=' * 152)
print('CELL 36 - EXACT MODEL CONFIGURATION + COMPUTATIONAL COST TABLES')
print('=' * 152)
print('Cell32 v9 trainer SHA256      : VERIFIED')
print('Cell33 summary SHA256         : VERIFIED')
print('Cell34 manifest SHA256        : VERIFIED')
print('Cell35 manifest SHA256        : VERIFIED')
print('Models                        : 13')
print('Training runs read            : 520 / 520')
print('Evaluation rows read          : 2080 / 2080')
print('Checkpoint-level eval timings : 520 / 520')
print('Training performed            : FALSE')
print('Inference performed           : FALSE')
print('Threshold tuning              : FALSE')
print('Model selection/reranking     : FALSE')
print('-' * 152)
print('\nTABLE A - MODEL CONFIGURATION')
print(config_table.to_string(index=False))
print('\nTABLE B - TRAINING / EVALUATION EFFICIENCY')
print(eff_table.to_string(index=False))
print('\nTABLE D - HARDWARE / SOFTWARE ENVIRONMENT')
print(hardware_table.to_string(index=False))
print('-' * 152)
print('Table A:', TABLE_A_PATH)
print('  SHA256:', sha256_file(TABLE_A_PATH))
print('Table B:', TABLE_B_PATH)
print('  SHA256:', sha256_file(TABLE_B_PATH))
print('Table C:', TABLE_C_PATH)
print('  SHA256:', sha256_file(TABLE_C_PATH))
print('Table D:', TABLE_D_PATH)
print('  SHA256:', sha256_file(TABLE_D_PATH))
print('Table E:', TABLE_E_PATH)
print('  SHA256:', sha256_file(TABLE_E_PATH))
print('Full config JSON:', FULL_CONFIG_JSON_PATH)
print('  SHA256:', sha256_file(FULL_CONFIG_JSON_PATH))
print('Manifest:', MANIFEST_PATH)
print('  SHA256:', sha256_file(MANIFEST_PATH))
print('Manifest action:', manifest_action)
print('=' * 152)
print('CELL 36 PASS - EXACT CONFIGURATION / TRAINING TIME / EVALUATION TIME / CPU-GPU-MEMORY TABLES COMPLETE')
print('NO TRAINING / NO INFERENCE / NO NEW PERFORMANCE CALCULATION')
print('=' * 152)

========================================================================================================================================================
CELL 36 - EXACT MODEL CONFIGURATION + COMPUTATIONAL COST TABLES
========================================================================================================================================================
Cell32 v9 trainer SHA256      : VERIFIED
Cell33 summary SHA256         : VERIFIED
Cell34 manifest SHA256        : VERIFIED
Cell35 manifest SHA256        : VERIFIED
Models                        : 13
Training runs read            : 520 / 520
Evaluation rows read          : 2080 / 2080
Checkpoint-level eval timings : 520 / 520
Training performed            : FALSE
Inference performed           : FALSE
Threshold tuning              : FALSE
Model selection/reranking     : FALSE
--------------------------------------------------------------------------------------------------------------------------------------------------------

TABLE A - MODEL CONFIGURATION
                Model               model_id                                                                              Input representation                       Trainable parameters / estimator size Checkpoint size MB (mean +/- SD, 40 runs)       Optimizer / learning algorithm                                        Learning rate                          Batch size Max epochs / iterations                                                      Early stopping                                                                             Hyperparameter selection      Training device actually recorded                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Architecture / key fixed estimator settings                                                          Configuration provenance
  Logistic Regression    logistic_regression                                       Length_AAC20_DPC400_v1 (421D: Length_norm + AAC20 + DPC400)             Not defined as neural trainable-parameter count                           0.012 +/- 0.000 Not applicable (classical estimator)                                       Not applicable Not applicable (non-mini-batch fit)         Not epoch-based                                                      Not applicable                                    Hyperparameters pre-locked before training; no test/target tuning                                    cpu                                                                                                                                                                                                                                                  {"estimator":{"C":1.0,"class":"sklearn.linear_model.LogisticRegression","class_weight":null,"max_iter":2000,"penalty":"l2","random_state":null,"solver":"lbfgs","tol":0.0001},"model_id":"logistic_regression","preprocessing":{"fit_on":"source_train_only","scaler":"StandardScaler","with_mean":true,"with_std":true},"representation":"Length_AAC20_DPC400_v1"}                                  benchmark17_FINAL_controlled_model_contract.json
Calibrated Linear SVM  linear_svm_calibrated                                       Length_AAC20_DPC400_v1 (421D: Length_norm + AAC20 + DPC400)             Not defined as neural trainable-parameter count                           0.028 +/- 0.000 Not applicable (classical estimator)                                       Not applicable Not applicable (non-mini-batch fit)         Not epoch-based                                                      Not applicable                                    Hyperparameters pre-locked before training; no test/target tuning                                    cpu {"base_estimator":{"C":1.0,"class":"sklearn.svm.LinearSVC","class_weight":null,"dual":"auto","loss":"squared_hinge","max_iter":20000,"penalty":"l2","random_state":"RUN_SEED","tol":0.0001},"calibration":{"calibration_data":"source_train_only","class":"sklearn.calibration.CalibratedClassifierCV","cv":5,"cv_random_state":"RUN_SEED","cv_shuffle":true,"cv_type":"StratifiedKFold","ensemble":true,"method":"sigmoid"},"model_id":"linear_svm_calibrated","preprocessing":{"fit_on":"source_train_only","scaler":"StandardScaler","with_mean":true,"with_std":true},"representation":"Length_AAC20_DPC400_v1"}                                  benchmark17_FINAL_controlled_model_contract.json
        Random Forest          random_forest                                       Length_AAC20_DPC400_v1 (421D: Length_norm + AAC20 + DPC400)             Not defined as neural trainable-parameter count                         65.227 +/- 20.537 Not applicable (classical estimator)                                       Not applicable Not applicable (non-mini-batch fit)         Not epoch-based                                                      Not applicable                                    Hyperparameters pre-locked before training; no test/target tuning                                    cpu                                                                                                                                                                                                                                            {"estimator":{"bootstrap":true,"class":"sklearn.ensemble.RandomForestClassifier","class_weight":null,"criterion":"gini","max_depth":null,"max_features":"sqrt","min_samples_leaf":1,"min_samples_split":2,"n_estimators":500,"n_jobs":-1,"random_state":"RUN_SEED"},"model_id":"random_forest","preprocessing":{"scaler":null},"representation":"Length_AAC20_DPC400_v1"}                                  benchmark17_FINAL_controlled_model_contract.json
          Extra Trees            extra_trees                                       Length_AAC20_DPC400_v1 (421D: Length_norm + AAC20 + DPC400)             Not defined as neural trainable-parameter count                        140.627 +/- 43.763 Not applicable (classical estimator)                                       Not applicable Not applicable (non-mini-batch fit)         Not epoch-based                                                      Not applicable                                    Hyperparameters pre-locked before training; no test/target tuning                                    cpu                                                                                                                                                                                                                                               {"estimator":{"bootstrap":false,"class":"sklearn.ensemble.ExtraTreesClassifier","class_weight":null,"criterion":"gini","max_depth":null,"max_features":"sqrt","min_samples_leaf":1,"min_samples_split":2,"n_estimators":500,"n_jobs":-1,"random_state":"RUN_SEED"},"model_id":"extra_trees","preprocessing":{"scaler":null},"representation":"Length_AAC20_DPC400_v1"}                                  benchmark17_FINAL_controlled_model_contract.json
 HistGradientBoosting hist_gradient_boosting                                       Length_AAC20_DPC400_v1 (421D: Length_norm + AAC20 + DPC400)             Not defined as neural trainable-parameter count                           1.406 +/- 0.069 Not applicable (classical estimator)                                                 0.05 Not applicable (non-mini-batch fit)         Not epoch-based                                           Disabled in locked config                                    Hyperparameters pre-locked before training; no test/target tuning                                    cpu                                                                                                                                                                                                                     {"estimator":{"class":"sklearn.ensemble.HistGradientBoostingClassifier","early_stopping":false,"l2_regularization":1.0,"learning_rate":0.05,"loss":"log_loss","max_bins":255,"max_depth":null,"max_iter":300,"max_leaf_nodes":31,"min_samples_leaf":20,"random_state":"RUN_SEED"},"model_id":"hist_gradient_boosting","preprocessing":{"scaler":null},"representation":"Length_AAC20_DPC400_v1"}                                  benchmark17_FINAL_controlled_model_contract.json
             LightGBM               lightgbm                                       Length_AAC20_DPC400_v1 (421D: Length_norm + AAC20 + DPC400)             Not defined as neural trainable-parameter count                           1.698 +/- 0.004 Not applicable (classical estimator)                                                 0.05 Not applicable (non-mini-batch fit)         Not epoch-based                                                      Not applicable                                    Hyperparameters pre-locked before training; no test/target tuning                                    cpu                                                                                                              {"estimator":{"class":"lightgbm.LGBMClassifier","class_weight":null,"colsample_bytree":0.8,"deterministic":true,"device_type":"cpu","force_col_wise":true,"learning_rate":0.05,"max_depth":-1,"min_child_samples":20,"n_estimators":500,"n_jobs":-1,"num_leaves":31,"objective":"binary","random_state":"RUN_SEED","reg_alpha":0.0,"reg_lambda":1.0,"subsample":0.8,"subsample_freq":1,"verbosity":-1},"model_id":"lightgbm","preprocessing":{"scaler":null},"representation":"Length_AAC20_DPC400_v1"}                                  benchmark17_FINAL_controlled_model_contract.json
                CNN1D                  cnn1d      AA20_integer_tokens_L200_v1 (raw peptide; max length 200; post-padding; trainable embedding)                                                      100033                           1.180 +/- 0.000                                 Adam                                                0.001                                  64                      80 Yes: val_loss, patience=8, min_delta=0.0, restore_best_weights=True Architecture/training hyperparameters pre-locked; source validation only for early stopping and tau* gpu_tensorflow_locked_cell2_subprocess                                                                                                                                                                                                                                  {"conv1_activation":"relu","conv1_filters":128,"conv1_kernel_size":5,"conv1_padding":"same","conv2_activation":"relu","conv2_filters":128,"conv2_kernel_size":3,"conv2_padding":"same","dense_activation":"relu","dense_units":64,"dropout":0.3,"embedding_dim":64,"embedding_mask_zero":true,"output_activation":"sigmoid","output_units":1,"pooling":"masked_global_max_pooling"} benchmark17_FINAL_controlled_model_contract.json + measured Cell32 resources.json
               BiLSTM                 bilstm      AA20_integer_tokens_L200_v1 (raw peptide; max length 200; post-padding; trainable embedding)                                                       75713                           0.906 +/- 0.000                                 Adam                                                0.001                                  64                      80 Yes: val_loss, patience=8, min_delta=0.0, restore_best_weights=True Architecture/training hyperparameters pre-locked; source validation only for early stopping and tau* gpu_tensorflow_locked_cell2_subprocess                                                                                                                                                                                                                                                                                                                                                    {"bilstm_units_per_direction":64,"dense_activation":"relu","dense_dropout":0.3,"dense_units":64,"embedding_dim":64,"embedding_mask_zero":true,"lstm_dropout":0.2,"output_activation":"sigmoid","output_units":1,"recurrent_dropout":0.0,"return_sequences":false} benchmark17_FINAL_controlled_model_contract.json + measured Cell32 resources.json
     BiLSTM-Attention       bilstm_attention      AA20_integer_tokens_L200_v1 (raw peptide; max length 200; post-padding; trainable embedding)                                                       84033                           1.012 +/- 0.000                                 Adam                                                0.001                                  64                      80 Yes: val_loss, patience=8, min_delta=0.0, restore_best_weights=True Architecture/training hyperparameters pre-locked; source validation only for early stopping and tau* gpu_tensorflow_locked_cell2_subprocess                                                                                                                                                                                                                              {"attention_type":"trainable_masked_additive_attention","attention_units":64,"bilstm_units_per_direction":64,"dense_activation":"relu","dense_dropout":0.3,"dense_units":64,"embedding_dim":64,"embedding_mask_zero":true,"lstm_dropout":0.2,"output_activation":"sigmoid","output_units":1,"padding_mask_applied_before_softmax":true,"recurrent_dropout":0.0,"return_sequences":true} benchmark17_FINAL_controlled_model_contract.json + measured Cell32 resources.json
  Transformer Encoder    transformer_encoder      AA20_integer_tokens_L200_v1 (raw peptide; max length 200; post-padding; trainable embedding)                                                       85313                           1.091 +/- 0.000                                 Adam                                                0.001                                  64                      80 Yes: val_loss, patience=8, min_delta=0.0, restore_best_weights=True Architecture/training hyperparameters pre-locked; source validation only for early stopping and tau* gpu_tensorflow_locked_cell2_subprocess                                                                                                            {"attention_dropout":0.1,"dense_activation":"relu","dense_dropout":0.3,"dense_units":64,"feed_forward_dimension":128,"feed_forward_dropout":0.1,"key_dim_per_head":16,"layer_normalization":true,"maximum_positions":200,"model_dimension":64,"n_encoder_blocks":2,"num_attention_heads":4,"output_activation":"sigmoid","output_units":1,"padding_attention_mask":true,"positional_embedding":"learned","residual_connections":true,"sequence_pooling":"masked_global_average","token_embedding_dim":64} benchmark17_FINAL_controlled_model_contract.json + measured Cell32 resources.json
                AmPEP                  ampep                       105D Seq2Distribution descriptors used by the exact Cell32 v9 AmPEP wrapper             Not defined as neural trainable-parameter count                          10.546 +/- 3.294       Not applicable (Random Forest)                                       Not applicable                      Not applicable         Not epoch-based                            Not applicable (non-iterative estimator)                                       Published recipe fixed before benchmark; no test/target tuning                        method_specific                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            RandomForestClassifier(n_estimators=100, max_features=11, criterion=gini, bootstrap=True)                       Cell32 v9 exact production wrapper + locked published route
         AMPScannerV2           ampscannerv2 Integer amino-acid encoding padded to length 200 + learned 128D embedding (official source route) Not recorded as count_params by locked TF1 production route                           2.315 +/- 0.000                                 adam Not explicitly set in locked implementation contract                                  32                      10  No benchmark-added early stopping; official fixed-epoch source fit                 Official source architecture/training recipe locked; no benchmark test/target tuning                        method_specific                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Embedding(21,128) -> Conv1D(64,k=16) -> MaxPool(5) -> LSTM(100) -> sigmoid   benchmark17_ampscannerv2_FINAL_implementation_contract.json + Cell32 v9 wrapper
              amPEPpy                ampeppy                       Official amPEPpy v1.0 feature pipeline (CTD/distribution descriptor family)             Not defined as neural trainable-parameter count                          15.586 +/- 4.854       Not applicable (Random Forest)                                       Not applicable                      Not applicable         Not epoch-based                            Not applicable (non-iterative estimator)                                      Official source retraining recipe locked; no test/target tuning                        method_specific                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Official amPEPpy v1.0 Random Forest; num_trees=160, min_tree=23, max_tree=175  benchmark17_ampeppy_FINAL_implementation_contract.json + Cell32 v9 exact wrapper

TABLE B - TRAINING / EVALUATION EFFICIENCY
                Model               model_id  Runs Training time/run (s, mean +/- SD) Epochs completed (mean +/- SD) Training time/epoch (s, mean +/- SD) Training throughput (seq/s, mean +/- SD) Final evaluation time / checkpoint for all 4 targets (s, mean +/- SD) Evaluation latency (ms/sequence, mean +/- SD) Evaluation throughput (seq/s, mean +/- SD) Peak process RAM (MB, mean +/- SD) Peak GPU VRAM (MB, mean +/- SD) Checkpoint size (MB, mean +/- SD)  Exact neural parameter count                        Training device                      Evaluation device                                                        Evaluation timing basis

In [57]:
# CELL 37 - SHOW + EXPORT RESULTS FROM CELLS 34, 35, 36
# READ-ONLY with respect to locked experiment outputs.
# NO TRAINING / NO INFERENCE / NO THRESHOLD TUNING / NO RE-AGGREGATION.
#
# Purpose:
#   1) Show Cell 34, Cell 35, and Cell 36 outputs directly in the notebook.
#   2) Export every displayed/relevant table as BOTH CSV and JSON.
#   3) Build a file index with SHA256 provenance.
#
# Safe to rerun: this cell only reads locked outputs and writes copies/JSON
# into a separate review_export folder.

from pathlib import Path
import pandas as pd
import json
import hashlib
import shutil
from datetime import datetime

try:
    from IPython.display import display
except Exception:
    display = None

# ----------------------------------------------------------------------------------------------------------------------
# 0. PATHS
# ----------------------------------------------------------------------------------------------------------------------
PROJECT_ROOT = Path("/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026")
BENCH_ROOT = PROJECT_ROOT / "benchmark17_outputs"
RESULTS_ROOT = BENCH_ROOT / "results" / "benchmark13_FINAL"

CELL34_ROOT = RESULTS_ROOT / "cell34_10seed_aggregation"
CELL35_ROOT = RESULTS_ROOT / "cell35_paper_ready"
CELL36_ROOT = RESULTS_ROOT / "cell36_model_config_runtime_resources"

EXPORT_ROOT = RESULTS_ROOT / "cell37_review_export"
EXPORT_ROOT.mkdir(parents=True, exist_ok=True)

CELL34_EXPORT = EXPORT_ROOT / "cell34"
CELL35_EXPORT = EXPORT_ROOT / "cell35"
CELL36_EXPORT = EXPORT_ROOT / "cell36"
for p in [CELL34_EXPORT, CELL35_EXPORT, CELL36_EXPORT]:
    p.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------------------------------------------------------------------
# 1. HELPERS
# ----------------------------------------------------------------------------------------------------------------------
def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()

def read_csv_exact(path: Path) -> pd.DataFrame:
    assert path.exists(), f"Missing required file: {path}"
    return pd.read_csv(path, keep_default_na=False, na_filter=False)

def show_df(title: str, df: pd.DataFrame):
    print("\n" + "=" * 160)
    print(title)
    print("=" * 160)
    print(f"Rows: {len(df):,} | Columns: {len(df.columns):,}")
    if display is not None:
        display(df)
    else:
        with pd.option_context(
            "display.max_rows", None,
            "display.max_columns", None,
            "display.width", 300,
            "display.max_colwidth", 120,
        ):
            print(df.to_string(index=False))

def export_pair(df: pd.DataFrame, dest_dir: Path, stem: str):
    csv_path = dest_dir / f"{stem}.csv"
    json_path = dest_dir / f"{stem}.json"

    df.to_csv(csv_path, index=False, encoding="utf-8-sig")
    with json_path.open("w", encoding="utf-8") as f:
        json.dump(
            df.to_dict(orient="records"),
            f,
            ensure_ascii=False,
            indent=2,
            default=str,
        )
    return csv_path, json_path

index_rows = []

def register_export(source_cell: str, category: str, src: Path, csv_out: Path, json_out: Path, df: pd.DataFrame):
    index_rows.append({
        "source_cell": source_cell,
        "category": category,
        "source_file": str(src),
        "source_sha256": sha256_file(src),
        "rows": int(len(df)),
        "columns": int(len(df.columns)),
        "export_csv": str(csv_out),
        "export_json": str(json_out),
        "export_csv_sha256": sha256_file(csv_out),
        "export_json_sha256": sha256_file(json_out),
    })

print("=" * 160)
print("CELL 37 - SHOW + EXPORT RESULTS FROM CELLS 34, 35, 36")
print("=" * 160)
print("Training performed     : FALSE")
print("Inference performed    : FALSE")
print("Threshold tuning       : FALSE")
print("Re-aggregation         : FALSE")
print("Scope/model selection  : FALSE")
print("-" * 160)

# ----------------------------------------------------------------------------------------------------------------------
# 2. CELL 34 - LOCKED 10-SEED AGGREGATION RESULTS
# ----------------------------------------------------------------------------------------------------------------------
cell34_files = {
    "CELL34_ALL_208": CELL34_ROOT / "benchmark13_FINAL_10seed_aggregate_all_208.csv",
    "CELL34_P1_WITHIN_52": CELL34_ROOT / "benchmark13_FINAL_10seed_P1_within_52.csv",
    "CELL34_P2_CROSS_156": CELL34_ROOT / "benchmark13_FINAL_10seed_P2_cross_156.csv",
    "CELL34_THRESHOLD_52": CELL34_ROOT / "benchmark13_FINAL_threshold_summary_52_source_configs.csv",
    "CELL34_CONFUSION_208": CELL34_ROOT / "benchmark13_FINAL_confusion_summary_208.csv",
}

cell34_dfs = {}
for stem, src in cell34_files.items():
    df = read_csv_exact(src)
    cell34_dfs[stem] = df
    csv_out, json_out = export_pair(df, CELL34_EXPORT, stem)
    register_export("Cell34", "locked_10seed_aggregation", src, csv_out, json_out, df)

# Exact completeness gates from Cell 34.
assert len(cell34_dfs["CELL34_ALL_208"]) == 208
assert len(cell34_dfs["CELL34_P1_WITHIN_52"]) == 52
assert len(cell34_dfs["CELL34_P2_CROSS_156"]) == 156
assert len(cell34_dfs["CELL34_THRESHOLD_52"]) == 52
assert len(cell34_dfs["CELL34_CONFUSION_208"]) == 208

show_df("CELL 34 RESULT - ALL 208 LOCKED 10-SEED CONFIGURATIONS", cell34_dfs["CELL34_ALL_208"])
show_df("CELL 34 RESULT - P1 WITHIN-DATASET, 52 CONFIGURATIONS", cell34_dfs["CELL34_P1_WITHIN_52"])
show_df("CELL 34 RESULT - P2 CROSS-DATASET, 156 CONFIGURATIONS", cell34_dfs["CELL34_P2_CROSS_156"])
show_df("CELL 34 RESULT - FROZEN THRESHOLD SUMMARY, 52 SOURCE CONFIGURATIONS", cell34_dfs["CELL34_THRESHOLD_52"])
show_df("CELL 34 RESULT - CONFUSION SUMMARY, 208 CONFIGURATIONS", cell34_dfs["CELL34_CONFUSION_208"])

# ----------------------------------------------------------------------------------------------------------------------
# 3. CELL 35 - PAPER-READY TABLES / MATRICES / FIGURES
# ----------------------------------------------------------------------------------------------------------------------
assert CELL35_ROOT.exists(), f"Missing Cell 35 root: {CELL35_ROOT}"

cell35_csv_files = sorted(CELL35_ROOT.rglob("*.csv"))
cell35_figure_files = sorted(
    [p for p in CELL35_ROOT.rglob("*") if p.is_file() and p.suffix.lower() in {".png", ".pdf"}]
)
assert cell35_csv_files, f"No CSV files found under Cell 35 root: {CELL35_ROOT}"

print("\n" + "=" * 160)
print("CELL 35 - PAPER-READY OUTPUT INVENTORY")
print("=" * 160)
print(f"CSV/table/matrix files : {len(cell35_csv_files)}")
print(f"Figure files           : {len(cell35_figure_files)}")
print(f"Root                   : {CELL35_ROOT}")

# Export EVERY Cell35 CSV to paired CSV+JSON, preserving a flattened unique name.
cell35_tables = []
for src in cell35_csv_files:
    rel = src.relative_to(CELL35_ROOT)
    safe_stem = "__".join(rel.with_suffix("").parts)
    df = read_csv_exact(src)
    csv_out, json_out = export_pair(df, CELL35_EXPORT, safe_stem)
    register_export("Cell35", "paper_ready", src, csv_out, json_out, df)
    cell35_tables.append((src, df))

# Show ALL CSV tables in /tables.
for src, df in cell35_tables:
    if "tables" in src.relative_to(CELL35_ROOT).parts:
        show_df(f"CELL 35 TABLE - {src.name}", df)

# Show key performance matrices on screen.
key_matrix_tokens = (
    "P1_AUROC_mean",
    "P1_AUPRC_mean",
    "P1_MCC_mean",
    "P1_F1_mean",
    "P2_AUROC_mean",
    "P2_AUPRC_mean",
    "P2_MCC_mean",
    "P2_F1_mean",
)
shown_key_matrices = 0
for src, df in cell35_tables:
    name = src.stem
    if any(tok in name for tok in key_matrix_tokens):
        show_df(f"CELL 35 MATRIX - {src.name}", df)
        shown_key_matrices += 1

print("\nCELL 35 FIGURES:")
for p in cell35_figure_files:
    print(" -", p)

# ----------------------------------------------------------------------------------------------------------------------
# 4. CELL 36 - MODEL CONFIG / TRAINING-EVALUATION RUNTIME / HARDWARE / PERFORMANCE+EFFICIENCY
# ----------------------------------------------------------------------------------------------------------------------
assert CELL36_ROOT.exists(), f"Missing Cell 36 root: {CELL36_ROOT}"

cell36_csv_files = sorted(CELL36_ROOT.glob("Table_*.csv"))
assert cell36_csv_files, f"No Table_*.csv files found under Cell 36 root: {CELL36_ROOT}"

cell36_tables = {}
for src in cell36_csv_files:
    df = read_csv_exact(src)
    stem = src.stem
    cell36_tables[stem] = df
    csv_out, json_out = export_pair(df, CELL36_EXPORT, stem)
    register_export("Cell36", "config_runtime_resource", src, csv_out, json_out, df)
    show_df(f"CELL 36 TABLE - {src.name}", df)

# ----------------------------------------------------------------------------------------------------------------------
# 5. EXPORT INDEX + MANIFEST
# ----------------------------------------------------------------------------------------------------------------------
index_df = pd.DataFrame(index_rows)
index_csv = EXPORT_ROOT / "RESULT_EXPORT_INDEX.csv"
index_json = EXPORT_ROOT / "RESULT_EXPORT_INDEX.json"
index_df.to_csv(index_csv, index=False, encoding="utf-8-sig")
with index_json.open("w", encoding="utf-8") as f:
    json.dump(index_df.to_dict(orient="records"), f, ensure_ascii=False, indent=2, default=str)

manifest = {
    "cell": "CELL 37 - SHOW + EXPORT RESULTS FROM CELLS 34, 35, 36",
    "created_at": datetime.now().astimezone().isoformat(),
    "training_performed": False,
    "inference_performed": False,
    "threshold_tuning": False,
    "reaggregation": False,
    "scope_change": False,
    "source_roots": {
        "cell34": str(CELL34_ROOT),
        "cell35": str(CELL35_ROOT),
        "cell36": str(CELL36_ROOT),
    },
    "cell34_counts": {
        "all_208": len(cell34_dfs["CELL34_ALL_208"]),
        "p1_52": len(cell34_dfs["CELL34_P1_WITHIN_52"]),
        "p2_156": len(cell34_dfs["CELL34_P2_CROSS_156"]),
        "threshold_52": len(cell34_dfs["CELL34_THRESHOLD_52"]),
        "confusion_208": len(cell34_dfs["CELL34_CONFUSION_208"]),
    },
    "cell35_csv_files": len(cell35_csv_files),
    "cell35_figure_files": len(cell35_figure_files),
    "cell35_key_matrices_displayed": shown_key_matrices,
    "cell36_csv_files": len(cell36_csv_files),
    "exported_table_count": len(index_df),
    "export_index_csv": str(index_csv),
    "export_index_json": str(index_json),
    "export_root": str(EXPORT_ROOT),
}
manifest_path = EXPORT_ROOT / "CELL37_RESULT_EXPORT_MANIFEST.json"
with manifest_path.open("w", encoding="utf-8") as f:
    json.dump(manifest, f, ensure_ascii=False, indent=2)

# ----------------------------------------------------------------------------------------------------------------------
# 6. FINAL SCREEN SUMMARY
# ----------------------------------------------------------------------------------------------------------------------
print("\n" + "=" * 160)
print("CELL 37 STATUS")
print("=" * 160)
print("Training performed           : FALSE")
print("Inference performed          : FALSE")
print("Threshold tuning             : FALSE")
print("Re-aggregation               : FALSE")
print("Scope changed                : FALSE")
print("-" * 160)
print("CELL 34 all aggregate        : 208 / 208")
print("CELL 34 P1                   : 52 / 52")
print("CELL 34 P2                   : 156 / 156")
print("CELL 34 threshold summary    : 52 / 52")
print("CELL 34 confusion summary    : 208 / 208")
print(f"CELL 35 CSV/table/matrix     : {len(cell35_csv_files)} files")
print(f"CELL 35 figures              : {len(cell35_figure_files)} files")
print(f"CELL 36 tables               : {len(cell36_csv_files)} files")
print(f"Total CSV/JSON pairs exported: {len(index_df)}")
print("-" * 160)
print("Review/export root           :", EXPORT_ROOT)
print("Export index CSV             :", index_csv)
print("Export index JSON            :", index_json)
print("Manifest JSON                :", manifest_path)
print("-" * 160)
print("CELL 37 PASS - CELL 34/35/36 RESULTS DISPLAYED AND EXPORTED AS CSV + JSON")
print("=" * 160)

================================================================================================================================================================
CELL 37 - SHOW + EXPORT RESULTS FROM CELLS 34, 35, 36
================================================================================================================================================================
Training performed     : FALSE
Inference performed    : FALSE
Threshold tuning       : FALSE
Re-aggregation         : FALSE
Scope/model selection  : FALSE
----------------------------------------------------------------------------------------------------------------------------------------------------------------

================================================================================================================================================================
CELL 34 RESULT - ALL 208 LOCKED 10-SEED CONFIGURATIONS
================================================================================================================================================================
Rows: 208 | Columns: 63

,protocol,model_id,model_group,source_dataset,target_dataset,n_seeds,seeds,ci_method,ci_df,ci_t_critical,...,Brier_ci95_low,Brier_ci95_high,ECE10_mean,ECE10_sd,ECE10_se,ECE10_ci95_low,ECE10_ci95_high,n_target,n_positive,n_negative
0,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.162539,0.162539,0.035016,0.000000e+00,0.000000e+00,0.035016,0.035016,2310,1155,1155
1,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.167509,0.167509,0.053726,0.000000e+00,0.000000e+00,0.053726,0.053726,1545,889,656
2,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.092235,0.092235,0.021099,0.000000e+00,0.000000e+00,0.021099,0.021099,1592,786,806
3,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.140554,0.140554,0.036088,7.314236e-18,2.312965e-18,0.036088,0.036088,2070,1010,1060
4,P1_WITHIN_DATASET_SOURCE_TEST,linear_svm_calibrated,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.161534,0.161908,0.041683,4.099269e-03,1.296303e-03,0.038750,0.044615,2310,1155,1155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,P2_CROSS_DATASET,ampeppy,published_amp_method,AMPlify_balanced,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.267639,0.269409,0.202520,6.442817e-03,2.037398e-03,0.197911,0.207128,957,309,648
204,P2_CROSS_DATASET,ampeppy,published_amp_method,AMPlify_balanced,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.286509,0.287633,0.186631,3.017333e-03,9.541644e-04,0.184472,0.188789,1910,850,1060
205,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.244355,0.249074,0.181365,8.519587e-03,2.694130e-03,0.175271,0.187460,2301,1147,1154
206,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.262184,0.263996,0.173761,5.735641e-03,1.813769e-03,0.169658,0.177864,1322,666,656
207,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.231698,0.232804,0.148337,5.104118e-03,1.614064e-03,0.144686,0.151988,1397,593,804

================================================================================================================================================================
CELL 34 RESULT - P1 WITHIN-DATASET, 52 CONFIGURATIONS
================================================================================================================================================================
Rows: 52 | Columns: 63

,protocol,model_id,model_group,source_dataset,target_dataset,n_seeds,seeds,ci_method,ci_df,ci_t_critical,...,Brier_ci95_low,Brier_ci95_high,ECE10_mean,ECE10_sd,ECE10_se,ECE10_ci95_low,ECE10_ci95_high,n_target,n_positive,n_negative
0,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.162539,0.162539,0.035016,0.000000e+00,0.000000e+00,0.035016,0.035016,2310,1155,1155
1,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.167509,0.167509,0.053726,0.000000e+00,0.000000e+00,0.053726,0.053726,1545,889,656
2,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.092235,0.092235,0.021099,0.000000e+00,0.000000e+00,0.021099,0.021099,1592,786,806
3,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.140554,0.140554,0.036088,7.314236e-18,2.312965e-18,0.036088,0.036088,2070,1010,1060
4,P1_WITHIN_DATASET_SOURCE_TEST,linear_svm_calibrated,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.161534,0.161908,0.041683,4.099269e-03,1.296303e-03,0.038750,0.044615,2310,1155,1155
5,P1_WITHIN_DATASET_SOURCE_TEST,linear_svm_calibrated,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.163553,0.163822,0.045481,1.785097e-03,5.644973e-04,0.044204,0.046758,1545,889,656
6,P1_WITHIN_DATASET_SOURCE_TEST,linear_svm_calibrated,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.096056,0.096567,0.051462,3.036609e-03,9.602599e-04,0.049290,0.053634,1592,786,806
7,P1_WITHIN_DATASET_SOURCE_TEST,linear_svm_calibrated,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.140870,0.141081,0.052866,1.926841e-03,6.093206e-04,0.051488,0.054244,2070,1010,1060
8,P1_WITHIN_DATASET_SOURCE_TEST,random_forest,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.097994,0.098518,0.087232,1.924540e-03,6.085929e-04,0.085855,0.088609,2310,1155,1155
9,P1_WITHIN_DATASET_SOURCE_TEST,random_forest,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.140865,0.141436,0.077358,2.530859e-03,8.003278e-04,0.075548,0.079169,1545,889,656
10,P1_WITHIN_DATASET_SOURCE_TEST,random_forest,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.085964,0.086409,0.132735,1.338457e-03,4.232572e-04,0.131777,0.133692,1592,786,806
11,P1_WITHIN_DATASET_SOURCE_TEST,random_forest,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.129484,0.129922,0.094025,1.368477e-03,4.327503e-04,0.093046,0.095004,2070,1010,1060
12,P1_WITHIN_DATASET_SOURCE_TEST,extra_trees,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.099450,0.099908,0.106055,1.512922e-03,4.784280e-04,0.104972,0.107137,2310,1155,1155
13,P1_WITHIN_DATASET_SOURCE_TEST,extra_trees,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.142128,0.142677,0.089494,3.034492e-03,9.595907e-04,0.087324,0.091665,1545,889,656
14,P1_WITHIN_DATASET_SOURCE_TEST,extra_trees,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.083829,0.084260,0.140256,2.439020e-03,7.712857e-04,0.138511,0.142001,1592,786,806
15,P1_WITHIN_DATASET_SOURCE_TEST,extra_trees,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.133609,0.133849,0.109998,1.710811e-03,5.410059e-04,0.108774,0.111222,2070,1010,1060
16,P1_WITHIN_DATASET_SOURCE_TEST,hist_gradient_boosting,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.077126,0.077126,0.028528,0.000000e+00,0.000000e+00,0.028528,0.028528,2310,1155,1155
17,P1_WITHIN_DATASET_SOURCE_TEST,hist_gradient_boosting,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.136022,0.136022,0.047631,0.000000e+00,0.000000e+00,0.047631,0.047631,1545,889,656
18,P1_WITHIN_DATASET_SOURCE_TEST,hist_gradient_boosting,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.066606,0.066606,0.021960,3.657118e-18,1.156482e-18,0.021960,0.021960,1592,786,806
19,P1_WITHIN_DATASET_SOURCE_TEST,hist_gradient_boosting,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.113019,0.113019,0.018355,3.657118e-18,1.156482e-18,0.018355,0.018355,2070,1010,1060
20,P1_WITHIN_DATASET_SOURCE_TEST,lightgbm,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.076570,0.077374,0.037111,1.020502e-03,3.227111e-04,0.036381,0.037841,2310,1155,1155
21,P1_WITHIN_DATASET_SOURCE_TEST,lightgbm,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.133200,0.134929,0.061479,4.505154e-03,1.424655e-03,0.058256,0.064702,1545,889,656
22,P1_WITHIN_DATASET_SOURCE_TEST,lightgbm,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.062486,0.063816,0.017875,3.320744e-03,1.050111e-03,0.015500,0.020251,1592,786,806
23,P1_WITHIN_DATASET_SOURCE_TEST,lightgbm,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.109580,0.110699,0.026433,3.065562e-03,9.694159e-04,0.024240,0.028626,2070,1010,1060
24,P1_WITHIN_DATASET_SOURCE_TEST,cnn1d,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.089572,0.093931,0.036750,1.377137e-02,4.354890e-03,0.026898,0.046601,2310,1155,1155
25,P1_WITHIN_DATASET_SOURCE_TEST,cnn1d,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.145360,0.160635,0.066394,2.451709e-02,7.752984e-03,0.048856,0.083933,1545,889,656
26,P1_WITHIN_DATASET_SOURCE_TEST,cnn1d,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.062599,0.066632,0.030135,8.886361e-03,2.810114e-03,0.023778,0.036492,1592,786,806
27,P1_WITHIN_DATASET_SOURCE_TEST,cnn1d,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.114746,0.119037,0.042306,1.696724e-02,5.365513e-03,0.030168,0.054443,2070,1010,1060
28,P1_WITHIN_DATASET_SOURCE_TEST,bilstm,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.099418,0.112359,0.030926,8.970821e-03,2.836823e-03,0.024509,0.037344,2310,1155,1155
29,P1_WITHIN_DATASET_SOURCE_TEST,bilstm,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.138051,0.143794,0.034684,6.053026e-03,1.914135e-03,0.030354,0.039015,1545,889,656
30,P1_WITHIN_DATASET_SOURCE_TEST,bilstm,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.067271,0.071962,0.023281,6.085688e-03,1.924464e-03,0.018927,0.027634,1592,786,806
31,P1_WITHIN_DATASET_SOURCE_TEST,bilstm,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.111318,0.114695,0.027780,5.504653e-03,1.740724e-03,0.023842,0.031718,2070,1010,1060
32,P1_WITHIN_DATASET_SOURCE_TEST,bilstm_attention,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.105942,0.117249,0.033097,8.598890e-03,2.719208e-03,0.026946,0.039249,2310,1155,1155
33,P1_WITHIN_DATASET_SOURCE_TEST,bilstm_attention,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.135389,0.153724,0.040309,2.210073e-02,6.988865e-03,0.024499,0.056119,1545,889,656
34,P1_WITHIN_DATASET_SOURCE_TEST,bilstm_attention,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.076084,0.080049,0.027196,4.712824e-03,1.490326e-03,0.023824,0.030567,1592,786,806
35,P1_WITHIN_DATASET_SOURCE_TEST,bilstm_attention,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.115430,0.117252,0.028746,5.611816e-03,1.774612e-03,0.024732,0.032761,2070,1010,1060
36,P1_WITHIN_DATASET_SOURCE_TEST,transformer_encoder,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.120798,0.130350,0.047162,2.174960e-02,6.877827e-03,0.031603,0.062721,2310,1155,1155
37,P1_WITHIN_DATASET_SOURCE_TEST,transformer_encoder,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.145708,0.155917,0.054091,2.438428e-02,7.710987e-03,0.036647,0.071534,1545,889,656
38,P1_WITHIN_DATASET_SOURCE_TEST,transformer_encoder,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.078454,0.083904,0.045406,8.519335e-03,2.694050e-03,0.039311,0.051500,1592,786,806
39,P1_WITHIN_DATASET_SOURCE_TEST,transformer_encoder,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.113685,0.120558,0.030616,8.943236e-03,2.828100e-03,0.024218,0.037013,2070,1010,1060
40,P1_WITHIN_DATASET_SOURCE_TEST,ampep,published_amp_method,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.108245,0.109229,0.064809,2.728253e-03,8.627495e-04,0.062857,0.066760,2310,1155,1155
41,P1_WITHIN_DATASET_SOURCE_TEST,ampep,published_amp_method,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.160783,0.161786,0.063595,3.556692e-03,1.124725e-03,0.061051,0.066140,1545,889,656
42,P1_WITHIN_DATASET_SOURCE_TEST,ampep,published_amp_method,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.088819,0.089852,0.069012,3.353292e-03,1.060404e-03,0.066613,0.071411,1592,786,806
43,P1_WITHIN_DATASET_SOURCE_TEST,ampep,published_amp_method,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.156295,0.157475,0.051674,5.316571e-03,1.681247e-03,0.047871,0.055478,2070,1010,1060
44,P1_WITHIN_DATASET_SOURCE_TEST,ampscannerv2,published_amp_method,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.088691,0.096829,0.077221,5.267797e-03,1.665824e-03,0.073452,0.080989,2310,1155,1155
45,P1_WITHIN_DATASET_SOURCE_TEST,ampscannerv2,published_amp_method,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.150020,0.160704,0.115071,1.523909e-02,4.819023e-03,0.104170,0.125973,1545,889,656
46,P1_WITHIN_DATASET_SOURCE_TEST,ampscannerv2,published_amp_method,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.060634,0.067729,0.049737,7.435624e-03,2.351351e-03,0.044418,0.055056,1592,786,806
47,P1_WITHIN_DATASET_SOURCE_TEST,ampscannerv2,published_amp_method,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.135261,0.142580,0.115252,5.954106e-03,1.882854e-03,0.110992,0.119511,2070,1010,1060
48,P1_WITHIN_DATASET_SOURCE_TEST,ampeppy,published_amp_method,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.107741,0.108462,0.069837,2.147251e-03,6.790205e-04,0.068301,0.071373,2310,1155,1155
49,P1_WITHIN_DATASET_SOURCE_TEST,ampeppy,published_amp_method,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.160897,0.161556,0.067027,5.001841e-03,1.581721e-03,0.063449,0.070605,1545,889,656
50,P1_WITHIN_DATASET_SOURCE_TEST,ampeppy,published_amp_method,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.089294,0.089886,0.071490,2.667595e-03,8.435676e-04,0.069582,0.073399,1592,786,806
51,P1_WITHIN_DATASET_SOURCE_TEST,ampeppy,published_amp_method,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.156746,0.157610,0.058741,4.422425e-03,1.398494e-03,0.055578,0.061905,2070,1010,1060

================================================================================================================================================================
CELL 34 RESULT - P2 CROSS-DATASET, 156 CONFIGURATIONS
================================================================================================================================================================
Rows: 156 | Columns: 63

,protocol,model_id,model_group,source_dataset,target_dataset,n_seeds,seeds,ci_method,ci_df,ci_t_critical,...,Brier_ci95_low,Brier_ci95_high,ECE10_mean,ECE10_sd,ECE10_se,ECE10_ci95_low,ECE10_ci95_high,n_target,n_positive,n_negative
0,P2_CROSS_DATASET,logistic_regression,controlled_baseline,GenPept_Curated_2025,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.312902,0.312902,0.240066,0.000000e+00,0.000000e+00,0.240066,0.240066,1530,874,656
1,P2_CROSS_DATASET,logistic_regression,controlled_baseline,GenPept_Curated_2025,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.331234,0.331234,0.265535,5.851389e-17,1.850372e-17,0.265535,0.265535,1582,784,798
2,P2_CROSS_DATASET,logistic_regression,controlled_baseline,GenPept_Curated_2025,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.312147,0.312147,0.238141,2.925695e-17,9.251859e-18,0.238141,0.238141,2061,1001,1060
3,P2_CROSS_DATASET,logistic_regression,controlled_baseline,External_Benchmark_1,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.300389,0.300389,0.221161,2.925695e-17,9.251859e-18,0.221161,0.221161,2290,1137,1153
4,P2_CROSS_DATASET,logistic_regression,controlled_baseline,External_Benchmark_1,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.234754,0.234754,0.256281,0.000000e+00,0.000000e+00,0.256281,0.256281,1156,366,790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,P2_CROSS_DATASET,ampeppy,published_amp_method,AMPlify_balanced,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.267639,0.269409,0.202520,6.442817e-03,2.037398e-03,0.197911,0.207128,957,309,648
152,P2_CROSS_DATASET,ampeppy,published_amp_method,AMPlify_balanced,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.286509,0.287633,0.186631,3.017333e-03,9.541644e-04,0.184472,0.188789,1910,850,1060
153,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.244355,0.249074,0.181365,8.519587e-03,2.694130e-03,0.175271,0.187460,2301,1147,1154
154,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.262184,0.263996,0.173761,5.735641e-03,1.813769e-03,0.169658,0.177864,1322,666,656
155,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",Student-t two-sided 95% CI on 10-seed mean,9,2.262157,...,0.231698,0.232804,0.148337,5.104118e-03,1.614064e-03,0.144686,0.151988,1397,593,804

================================================================================================================================================================
CELL 34 RESULT - FROZEN THRESHOLD SUMMARY, 52 SOURCE CONFIGURATIONS
================================================================================================================================================================
Rows: 52 | Columns: 11

,model_id,model_group,source_dataset,n_seeds,threshold_mean,threshold_sd,threshold_se,threshold_ci95_low,threshold_ci95_high,threshold_min,threshold_max
0,ampep,published_amp_method,AMPlify_balanced,10,0.518500,3.951441e-02,1.249555e-02,0.490233,0.546767,0.460000,0.575000
1,ampep,published_amp_method,External_Benchmark_1,10,0.496000,3.195483e-02,1.010500e-02,0.473141,0.518859,0.430000,0.535000
2,ampep,published_amp_method,External_Benchmark_3,10,0.500500,3.022600e-02,9.558301e-03,0.478878,0.522122,0.450000,0.545000
3,ampep,published_amp_method,GenPept_Curated_2025,10,0.496500,2.160890e-02,6.833333e-03,0.481042,0.511958,0.470000,0.535000
4,ampeppy,published_amp_method,AMPlify_balanced,10,0.527500,3.949552e-02,1.248958e-02,0.499247,0.555753,0.443750,0.584375
5,ampeppy,published_amp_method,External_Benchmark_1,10,0.490625,4.042418e-02,1.278325e-02,0.461707,0.519543,0.431250,0.553125
6,ampeppy,published_amp_method,External_Benchmark_3,10,0.481250,2.088535e-02,6.604528e-03,0.466310,0.496190,0.456250,0.521875
7,ampeppy,published_amp_method,GenPept_Curated_2025,10,0.465938,3.215529e-02,1.016840e-02,0.442935,0.488940,0.425000,0.515625
8,ampscannerv2,published_amp_method,AMPlify_balanced,10,0.603649,2.451789e-01,7.753239e-02,0.428259,0.779040,0.125985,0.914111
9,ampscannerv2,published_amp_method,External_Benchmark_1,10,0.691298,2.007687e-01,6.348865e-02,0.547677,0.834920,0.272388,0.903462
10,ampscannerv2,published_amp_method,External_Benchmark_3,10,0.907283,2.543992e-02,8.044810e-03,0.889084,0.925481,0.869013,0.954138
11,ampscannerv2,published_amp_method,GenPept_Curated_2025,10,0.363230,1.706864e-01,5.397576e-02,0.241128,0.485332,0.183220,0.639407
12,bilstm,controlled_baseline,AMPlify_balanced,10,0.426817,5.029536e-02,1.590479e-02,0.390838,0.462796,0.369540,0.498176
13,bilstm,controlled_baseline,External_Benchmark_1,10,0.459938,7.251283e-02,2.293057e-02,0.408066,0.511811,0.328059,0.546978
14,bilstm,controlled_baseline,External_Benchmark_3,10,0.452671,5.865217e-02,1.854744e-02,0.410713,0.494628,0.372040,0.541461
15,bilstm,controlled_baseline,GenPept_Curated_2025,10,0.407423,9.950050e-02,3.146482e-02,0.336245,0.478601,0.224600,0.573474
16,bilstm_attention,controlled_baseline,AMPlify_balanced,10,0.457002,1.273197e-01,4.026202e-02,0.365923,0.548081,0.247965,0.699877
17,bilstm_attention,controlled_baseline,External_Benchmark_1,10,0.576468,1.012275e-01,3.201094e-02,0.504054,0.648882,0.468203,0.812541
18,bilstm_attention,controlled_baseline,External_Benchmark_3,10,0.492437,4.891174e-02,1.546725e-02,0.457448,0.527426,0.434281,0.608094
19,bilstm_attention,controlled_baseline,GenPept_Curated_2025,10,0.335318,1.140463e-01,3.606461e-02,0.253734,0.416902,0.107038,0.488029
20,cnn1d,controlled_baseline,AMPlify_balanced,10,0.447405,1.290595e-01,4.081221e-02,0.355081,0.539728,0.285899,0.744956
21,cnn1d,controlled_baseline,External_Benchmark_1,10,0.650471,1.457892e-01,4.610260e-02,0.546180,0.754762,0.397358,0.824563
22,cnn1d,controlled_baseline,External_Benchmark_3,10,0.595753,1.483115e-01,4.690022e-02,0.489657,0.701849,0.411734,0.834490
23,cnn1d,controlled_baseline,GenPept_Curated_2025,10,0.374388,1.362972e-01,4.310095e-02,0.276887,0.471890,0.145270,0.637774
24,extra_trees,controlled_baseline,AMPlify_balanced,10,0.522400,2.863254e-02,9.054403e-03,0.501918,0.542882,0.460000,0.551000
25,extra_trees,controlled_baseline,External_Benchmark_1,10,0.525800,2.115971e-02,6.691288e-03,0.510663,0.540937,0.492000,0.548000
26,extra_trees,controlled_baseline,External_Benchmark_3,10,0.538900,3.112859e-02,9.843723e-03,0.516632,0.561168,0.458000,0.561000
27,extra_trees,controlled_baseline,GenPept_Curated_2025,10,0.559200,5.942278e-02,1.879113e-02,0.516692,0.601708,0.466000,0.617000
28,hist_gradient_boosting,controlled_baseline,AMPlify_balanced,10,0.383226,0.000000e+00,0.000000e+00,0.383226,0.383226,0.383226,0.383226
29,hist_gradient_boosting,controlled_baseline,External_Benchmark_1,10,0.582679,0.000000e+00,0.000000e+00,0.582679,0.582679,0.582679,0.582679
30,hist_gradient_boosting,controlled_baseline,External_Benchmark_3,10,0.578475,1.170278e-16,3.700743e-17,0.578475,0.578475,0.578475,0.578475
31,hist_gradient_boosting,controlled_baseline,GenPept_Curated_2025,10,0.660101,0.000000e+00,0.000000e+00,0.660101,0.660101,0.660101,0.660101
32,lightgbm,controlled_baseline,AMPlify_balanced,10,0.490755,9.282686e-02,2.935443e-02,0.424351,0.557160,0.353299,0.660819
33,lightgbm,controlled_baseline,External_Benchmark_1,10,0.514002,7.649697e-02,2.419047e-02,0.459280,0.568725,0.420006,0.657357
34,lightgbm,controlled_baseline,External_Benchmark_3,10,0.581613,6.839874e-02,2.162958e-02,0.532683,0.630542,0.496244,0.713366
35,lightgbm,controlled_baseline,GenPept_Curated_2025,10,0.622279,8.342277e-02,2.638060e-02,0.562602,0.681956,0.500000,0.766668
36,linear_svm_calibrated,controlled_baseline,AMPlify_balanced,10,0.622611,3.140722e-02,9.931834e-03,0.600144,0.645079,0.547926,0.650287
37,linear_svm_calibrated,controlled_baseline,External_Benchmark_1,10,0.497496,3.941626e-02,1.246451e-02,0.469299,0.525693,0.458328,0.596037
38,linear_svm_calibrated,controlled_baseline,External_Benchmark_3,10,0.545415,1.316171e-02,4.162098e-03,0.535999,0.554830,0.528584,0.567981
39,linear_svm_calibrated,controlled_baseline,GenPept_Curated_2025,10,0.501407,1.012817e-02,3.202809e-03,0.494161,0.508652,0.486800,0.515695
40,logistic_regression,controlled_baseline,AMPlify_balanced,10,0.578764,0.000000e+00,0.000000e+00,0.578764,0.578764,0.578764,0.578764
41,logistic_regression,controlled_baseline,External_Benchmark_1,10,0.483210,0.000000e+00,0.000000e+00,0.483210,0.483210,0.483210,0.483210
42,logistic_regression,controlled_baseline,External_Benchmark_3,10,0.527194,0.000000e+00,0.000000e+00,0.527194,0.527194,0.527194,0.527194
43,logistic_regression,controlled_baseline,GenPept_Curated_2025,10,0.505865,0.000000e+00,0.000000e+00,0.505865,0.505865,0.505865,0.505865
44,random_forest,controlled_baseline,AMPlify_balanced,10,0.488500,2.760133e-02,8.728306e-03,0.468755,0.508245,0.448000,0.529000
45,random_forest,controlled_baseline,External_Benchmark_1,10,0.537100,1.738102e-02,5.496362e-03,0.524666,0.549534,0.511000,0.566000
46,random_forest,controlled_baseline,External_Benchmark_3,10,0.528500,4.040971e-02,1.277867e-02,0.499593,0.557407,0.462000,0.575000
47,random_forest,controlled_baseline,GenPept_Curated_2025,10,0.554200,4.750860e-02,1.502354e-02,0.520214,0.588186,0.434000,0.597000
48,transformer_encoder,controlled_baseline,AMPlify_balanced,10,0.431815,1.721906e-01,5.445146e-02,0.308637,0.554993,0.200826,0.666048
49,transformer_encoder,controlled_baseline,External_Benchmark_1,10,0.584873,8.069284e-02,2.551732e-02,0.527149,0.642598,0.474862,0.732059
50,transformer_encoder,controlled_baseline,External_Benchmark_3,10,0.580614,9.078141e-02,2.870760e-02,0.515673,0.645556,0.436798,0.701169
51,transformer_encoder,controlled_baseline,GenPept_Curated_2025,10,0.458543,1.390490e-01,4.397115e-02,0.359074,0.558013,0.222926,0.649171

================================================================================================================================================================
CELL 34 RESULT - CONFUSION SUMMARY, 208 CONFIGURATIONS
================================================================================================================================================================
Rows: 208 | Columns: 27

,protocol,model_id,model_group,source_dataset,target_dataset,n_seeds,n_target,TP_mean,TP_sd,TP_se,...,FP_mean,FP_sd,FP_se,FP_ci95_low,FP_ci95_high,FN_mean,FN_sd,FN_se,FN_ci95_low,FN_ci95_high
0,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,2310,935.0,0.000000,0.000000,...,318.0,0.000000,0.000000,318.000000,318.000000,220.0,0.000000,0.000000,220.000000,220.000000
1,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,1545,669.0,0.000000,0.000000,...,149.0,0.000000,0.000000,149.000000,149.000000,220.0,0.000000,0.000000,220.000000,220.000000
2,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,1592,683.0,0.000000,0.000000,...,91.0,0.000000,0.000000,91.000000,91.000000,103.0,0.000000,0.000000,103.000000,103.000000
3,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,2070,768.0,0.000000,0.000000,...,156.0,0.000000,0.000000,156.000000,156.000000,242.0,0.000000,0.000000,242.000000,242.000000
4,P1_WITHIN_DATASET_SOURCE_TEST,linear_svm_calibrated,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,2310,944.1,11.628031,3.677106,...,326.2,10.580905,3.345976,318.630876,333.769124,210.9,11.628031,3.677106,202.581808,219.218192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,P2_CROSS_DATASET,ampeppy,published_amp_method,AMPlify_balanced,External_Benchmark_1,10,957,112.8,10.443499,3.302524,...,175.2,21.054427,6.657994,160.138570,190.261430,196.2,10.443499,3.302524,188.729171,203.670829
204,P2_CROSS_DATASET,ampeppy,published_amp_method,AMPlify_balanced,External_Benchmark_3,10,1910,415.0,34.412530,10.882197,...,418.0,52.668776,16.655329,380.323027,455.676973,435.0,34.412530,10.882197,410.382759,459.617241
205,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,GenPept_Curated_2025,10,2301,1105.3,11.076000,3.502539,...,867.9,26.400547,8.348586,849.014186,886.785814,41.7,11.076000,3.502539,33.776707,49.623293
206,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,External_Benchmark_1,10,1322,481.1,19.289894,6.100000,...,286.4,10.616549,3.357248,278.805378,293.994622,184.9,19.289894,6.100000,171.100841,198.699159
207,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,AMPlify_balanced,10,1397,470.3,19.922349,6.300000,...,348.7,34.036092,10.763157,324.352047,373.047953,122.7,19.922349,6.300000,108.448410,136.951590

================================================================================================================================================================
CELL 35 - PAPER-READY OUTPUT INVENTORY
================================================================================================================================================================
CSV/table/matrix files : 72
Figure files           : 12
Root                   : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready

================================================================================================================================================================
CELL 35 TABLE - Table_P1_within_core_metrics_52.csv
================================================================================================================================================================
Rows: 52 | Columns: 14

,Model,Source dataset,Target dataset,model_id,source_dataset,target_dataset,AUROC mean+/-SD,AUROC mean [95% CI],AUPRC mean+/-SD,AUPRC mean [95% CI],MCC mean+/-SD,MCC mean [95% CI],F1 mean+/-SD,F1 mean [95% CI]
0,Logistic Regression,GenPept-Curated-2025,GenPept-Curated-2025,logistic_regression,GenPept_Curated_2025,GenPept_Curated_2025,0.839 +/- 0.000,"0.839 [0.839, 0.839]",0.804 +/- 0.000,"0.804 [0.804, 0.804]",0.536 +/- 0.000,"0.536 [0.536, 0.536]",0.777 +/- 0.000,"0.777 [0.777, 0.777]"
1,Logistic Regression,External Benchmark 1,External Benchmark 1,logistic_regression,External_Benchmark_1,External_Benchmark_1,0.835 +/- 0.000,"0.835 [0.835, 0.835]",0.883 +/- 0.000,"0.883 [0.883, 0.883]",0.520 +/- 0.000,"0.520 [0.520, 0.520]",0.784 +/- 0.000,"0.784 [0.784, 0.784]"
2,Logistic Regression,AMPlify-balanced,AMPlify-balanced,logistic_regression,AMPlify_balanced,AMPlify_balanced,0.940 +/- 0.000,"0.940 [0.940, 0.940]",0.919 +/- 0.000,"0.919 [0.919, 0.919]",0.756 +/- 0.000,"0.756 [0.756, 0.756]",0.876 +/- 0.000,"0.876 [0.876, 0.876]"
3,Logistic Regression,External Benchmark 3,External Benchmark 3,logistic_regression,External_Benchmark_3,External_Benchmark_3,0.873 +/- 0.000,"0.873 [0.873, 0.873]",0.882 +/- 0.000,"0.882 [0.882, 0.882]",0.617 +/- 0.000,"0.617 [0.617, 0.617]",0.794 +/- 0.000,"0.794 [0.794, 0.794]"
4,Linear SVM (calibrated),GenPept-Curated-2025,GenPept-Curated-2025,linear_svm_calibrated,GenPept_Curated_2025,GenPept_Curated_2025,0.842 +/- 0.000,"0.842 [0.842, 0.842]",0.809 +/- 0.001,"0.809 [0.809, 0.810]",0.538 +/- 0.003,"0.538 [0.536, 0.540]",0.779 +/- 0.003,"0.779 [0.777, 0.780]"
5,Linear SVM (calibrated),External Benchmark 1,External Benchmark 1,linear_svm_calibrated,External_Benchmark_1,External_Benchmark_1,0.837 +/- 0.000,"0.837 [0.837, 0.837]",0.885 +/- 0.000,"0.885 [0.885, 0.885]",0.527 +/- 0.004,"0.527 [0.524, 0.531]",0.782 +/- 0.011,"0.782 [0.774, 0.789]"
6,Linear SVM (calibrated),AMPlify-balanced,AMPlify-balanced,linear_svm_calibrated,AMPlify_balanced,AMPlify_balanced,0.940 +/- 0.000,"0.940 [0.940, 0.940]",0.922 +/- 0.001,"0.922 [0.921, 0.923]",0.738 +/- 0.009,"0.738 [0.732, 0.744]",0.859 +/- 0.008,"0.859 [0.853, 0.865]"
7,Linear SVM (calibrated),External Benchmark 3,External Benchmark 3,linear_svm_calibrated,External_Benchmark_3,External_Benchmark_3,0.873 +/- 0.000,"0.873 [0.873, 0.874]",0.882 +/- 0.000,"0.882 [0.882, 0.882]",0.614 +/- 0.003,"0.614 [0.612, 0.616]",0.788 +/- 0.003,"0.788 [0.785, 0.790]"
8,Random Forest,GenPept-Curated-2025,GenPept-Curated-2025,random_forest,GenPept_Curated_2025,GenPept_Curated_2025,0.945 +/- 0.001,"0.945 [0.944, 0.945]",0.930 +/- 0.002,"0.930 [0.929, 0.931]",0.757 +/- 0.005,"0.757 [0.754, 0.761]",0.883 +/- 0.002,"0.883 [0.881, 0.884]"
9,Random Forest,External Benchmark 1,External Benchmark 1,random_forest,External_Benchmark_1,External_Benchmark_1,0.887 +/- 0.001,"0.887 [0.886, 0.888]",0.928 +/- 0.001,"0.928 [0.928, 0.928]",0.627 +/- 0.005,"0.627 [0.623, 0.631]",0.813 +/- 0.004,"0.813 [0.810, 0.816]"
10,Random Forest,AMPlify-balanced,AMPlify-balanced,random_forest,AMPlify_balanced,AMPlify_balanced,0.972 +/- 0.001,"0.972 [0.972, 0.973]",0.974 +/- 0.001,"0.974 [0.974, 0.974]",0.822 +/- 0.007,"0.822 [0.817, 0.827]",0.909 +/- 0.003,"0.909 [0.907, 0.911]"
11,Random Forest,External Benchmark 3,External Benchmark 3,random_forest,External_Benchmark_3,External_Benchmark_3,0.906 +/- 0.000,"0.906 [0.906, 0.906]",0.918 +/- 0.001,"0.918 [0.918, 0.918]",0.666 +/- 0.011,"0.666 [0.658, 0.673]",0.811 +/- 0.007,"0.811 [0.806, 0.816]"
12,Extra Trees,GenPept-Curated-2025,GenPept-Curated-2025,extra_trees,GenPept_Curated_2025,GenPept_Curated_2025,0.950 +/- 0.000,"0.950 [0.950, 0.951]",0.940 +/- 0.001,"0.940 [0.939, 0.941]",0.770 +/- 0.005,"0.770 [0.767, 0.774]",0.889 +/- 0.003,"0.889 [0.887, 0.890]"
13,Extra Trees,External Benchmark 1,External Benchmark 1,extra_trees,External_Benchmark_1,External_Benchmark_1,0.888 +/- 0.001,"0.888 [0.887, 0.888]",0.929 +/- 0.001,"0.929 [0.929, 0.930]",0.628 +/- 0.005,"0.628 [0.624, 0.631]",0.811 +/- 0.008,"0.811 [0.805, 0.816]"
14,Extra Trees,AMPlify-balanced,AMPlify-balanced,extra_trees,AMPlify_balanced,AMPlify_balanced,0.976 +/- 0.000,"0.976 [0.976, 0.976]",0.978 +/- 0.000,"0.978 [0.978, 0.978]",0.840 +/- 0.005,"0.840 [0.836, 0.843]",0.914 +/- 0.003,"0.914 [0.912, 0.916]"
15,Extra Trees,External Benchmark 3,External Benchmark 3,extra_trees,External_Benchmark_3,External_Benchmark_3,0.904 +/- 0.001,"0.904 [0.904, 0.905]",0.917 +/- 0.001,"0.917 [0.916, 0.917]",0.665 +/- 0.005,"0.665 [0.661, 0.668]",0.803 +/- 0.009,"0.803 [0.797, 0.810]"
16,HistGradientBoosting,GenPept-Curated-2025,GenPept-Curated-2025,hist_gradient_boosting,GenPept_Curated_2025,GenPept_Curated_2025,0.960 +/- 0.000,"0.960 [0.960, 0.960]",0.952 +/- 0.000,"0.952 [0.952, 0.952]",0.787 +/- 0.000,"0.787 [0.787, 0.787]",0.895 +/- 0.000,"0.895 [0.895, 0.895]"
17,HistGradientBoosting,External Benchmark 1,External Benchmark 1,hist_gradient_boosting,External_Benchmark_1,External_Benchmark_1,0.886 +/- 0.000,"0.886 [0.886, 0.886]",0.928 +/- 0.000,"0.928 [0.928, 0.928]",0.628 +/- 0.000,"0.628 [0.628, 0.628]",0.817 +/- 0.000,"0.817 [0.817, 0.817]"
18,HistGradientBoosting,AMPlify-balanced,AMPlify-balanced,hist_gradient_boosting,AMPlify_balanced,AMPlify_balanced,0.969 +/- 0.000,"0.969 [0.969, 0.969]",0.970 +/- 0.000,"0.970 [0.970, 0.970]",0.805 +/- 0.000,"0.805 [0.805, 0.805]",0.903 +/- 0.000,"0.903 [0.903, 0.903]"
19,HistGradientBoosting,External Benchmark 3,External Benchmark 3,hist_gradient_boosting,External_Benchmark_3,External_Benchmark_3,0.915 +/- 0.000,"0.915 [0.915, 0.915]",0.926 +/- 0.000,"0.926 [0.926, 0.926]",0.694 +/- 0.000,"0.694 [0.694, 0.694]",0.829 +/- 0.000,"0.829 [0.829, 0.829]"
20,LightGBM,GenPept-Curated-2025,GenPept-Curated-2025,lightgbm,GenPept_Curated_2025,GenPept_Curated_2025,0.960 +/- 0.001,"0.960 [0.959, 0.960]",0.951 +/- 0.001,"0.951 [0.950, 0.952]",0.800 +/- 0.005,"0.800 [0.796, 0.804]",0.902 +/- 0.003,"0.902 [0.900, 0.904]"
21,LightGBM,External Benchmark 1,External Benchmark 1,lightgbm,External_Benchmark_1,External_Benchmark_1,0.894 +/- 0.001,"0.894 [0.893, 0.895]",0.933 +/- 0.001,"0.933 [0.932, 0.933]",0.632 +/- 0.011,"0.632 [0.624, 0.639]",0.831 +/- 0.005,"0.831 [0.827, 0.835]"
22,LightGBM,AMPlify-balanced,AMPlify-balanced,lightgbm,AMPlify_balanced,AMPlify_balanced,0.972 +/- 0.001,"0.972 [0.971, 0.972]",0.973 +/- 0.001,"0.973 [0.972, 0.973]",0.829 +/- 0.009,"0.829 [0.822, 0.835]",0.913 +/- 0.004,"0.913 [0.910, 0.916]"
23,LightGBM,External Benchmark 3,External Benchmark 3,lightgbm,External_Benchmark_3,External_Benchmark_3,0.919 +/- 0.001,"0.919 [0.918, 0.920]",0.929 +/- 0.001,"0.929 [0.928, 0.929]",0.703 +/- 0.008,"0.703 [0.697, 0.709]",0.834 +/- 0.011,"0.834 [0.826, 0.841]"
24,CNN1D,GenPept-Curated-2025,GenPept-Curated-2025,cnn1d,GenPept_Curated_2025,GenPept_Curated_2025,0.942 +/- 0.004,"0.942 [0.940, 0.945]",0.927 +/- 0.005,"0.927 [0.924, 0.931]",0.758 +/- 0.011,"0.758 [0.751, 0.766]",0.883 +/- 0.005,"0.883 [0.879, 0.887]"
25,CNN1D,External Benchmark 1,External Benchmark 1,cnn1d,External_Benchmark_1,External_Benchmark_1,0.862 +/- 0.010,"0.862 [0.856, 0.869]",0.911 +/- 0.008,"0.911 [0.906, 0.917]",0.578 +/- 0.026,"0.578 [0.560, 0.597]",0.794 +/- 0.016,"0.794 [0.783, 0.806]"
26,CNN1D,AMPlify-balanced,AMPlify-balanced,cnn1d,AMPlify_balanced,AMPlify_balanced,0.972 +/- 0.002,"0.972 [0.970, 0.974]",0.974 +/- 0.003,"0.974 [0.972, 0.975]",0.822 +/- 0.011,"0.822 [0.814, 0.830]",0.910 +/- 0.006,"0.910 [0.906, 0.914]"
27,CNN1D,External Benchmark 3,External Benchmark 3,cnn1d,External_Benchmark_3,External_Benchmark_3,0.914 +/- 0.004,"0.914 [0.911, 0.917]",0.925 +/- 0.003,"0.925 [0.923, 0.927]",0.684 +/- 0.012,"0.684 [0.676, 0.692]",0.820 +/- 0.011,"0.820 [0.813, 0.828]"
28,BiLSTM,GenPept-Curated-2025,GenPept-Curated-2025,bilstm,GenPept_Curated_2025,GenPept_Curated_2025,0.920 +/- 0.013,"0.920 [0.911, 0.929]",0.890 +/- 0.017,"0.890 [0.878, 0.903]",0.720 +/- 0.029,"0.720 [0.700, 0.740]",0.866 +/- 0.013,"0.866 [0.856, 0.875]"
29,BiLSTM,External Benchmark 1,External Benchmark 1,bilstm,External_Benchmark_1,External_Benchmark_1,0.876 +/- 0.007,"0.876 [0.871, 0.881]",0.918 +/- 0.005,"0.918 [0.914, 0.922]",0.573 +/- 0.018,"0.573 [0.560, 0.585]",0.809 +/- 0.017,"0.809 [0.797, 0.822]"
30,BiLSTM,AMPlify-balanced,AMPlify-balanced,bilstm,AMPlify_balanced,AMPlify_balanced,0.965 +/- 0.003,"0.965 [0.963, 0.967]",0.968 +/- 0.003,"0.968 [0.966, 0.970]",0.812 +/- 0.013,"0.812 [0.803, 0.821]",0.905 +/- 0.007,"0.905 [0.900, 0.910]"
31,BiLSTM,External Benchmark 3,External Benchmark 3,bilstm,External_Benchmark_3,External_Benchmark_3,0.915 +/- 0.002,"0.915 [0.913, 0.917]",0.928 +/- 0.002,"0.928 [0.926, 0.929]",0.681 +/- 0.014,"0.681 [0.671, 0.690]",0.829 +/- 0.006,"0.829 [0.825, 0.833]"
32,BiLSTM + Attention,GenPept-Curated-2025,GenPept-Curated-2025,bilstm_attention,GenPept_Curated_2025,GenPept_Curated_2025,0.908 +/- 0.014,"0.908 [0.898, 0.918]",0.874 +/- 0.020,"0.874 [0.859, 0.888]",0.710 +/- 0.017,"0.710 [0.697, 0.722]",0.861 +/- 0.008,"0.861 [0.855, 0.867]"
33,BiLSTM + Attention,External Benchmark 1,External Benchmark 1,bilstm_attention,External_Benchmark_1,External_Benchmark_1,0.871 +/- 0.017,"0.871 [0.859, 0.883]",0.913 +/- 0.011,"0.913 [0.905, 0.922]",0.579 +/- 0.023,"0.579 [0.562, 0.595]",0.791 +/- 0.022,"0.791 [0.776, 0.807]"
34,BiLSTM + Attention,AMPlify-balanced,AMPlify-balanced,bilstm_attention,AMPlify_balanced,AMPlify_balanced,0.957 +/- 0.004,"0.957 [0.955, 0.960]",0.958 +/- 0.006,"0.958 [0.954, 0.962]",0.786 +/- 0.009,"0.786 [0.780, 0.793]",0.889 +/- 0.005,"0.889 [0.886, 0.893]"
35,BiLSTM + Attention,External Benchmark 3,External Benchmark 3,bilstm_attention,External_Benchmark_3,External_Benchmark_3,0.910 +/- 0.003,"0.910 [0.908, 0.912]",0.924 +/- 0.002,"0.924 [0.922, 0.925]",0.673 +/- 0.011,"0.673 [0.665, 0.681]",0.820 +/- 0.004,"0.820 [0.817, 0.823]"
36,Transformer Encoder,GenPept-Curated-2025,GenPept-Curated-2025,transformer_encoder,GenPept_Curated_2025,GenPept_Curated_2025,0.897 +/- 0.010,"0.897 [0.890, 0.904]",0.863 +/- 0.017,"0.863 [0.851, 0.875]",0.664 +/- 0.017,"0.664 [0.652, 0.676]",0.840 +/- 0.007,"0.840 [0.834, 0.845]"
37,Transformer Encoder,External Benchmark 1,External Benchmark 1,transformer_encoder,External_Benchmark_1,External_Benchmark_1,0.865 +/- 0.012,"0.865 [0.857, 0.874]",0.912 +/- 0.008,"0.912 [0.907, 0.918]",0.571 +/- 0.022,"0.571 [0.555, 0.587]",0.791 +/- 0.014,"0.791 [0.781, 0.800]"
38,Transformer Encoder,AMPlify-balanced,AMPlify-balanced,transformer_encoder,AMPlify_balanced,AMPlify_balanced,0.957 +/- 0.004,"0.957 [0.954, 0.960]",0.957 +/- 0.004,"0.957 [0.954, 0.960]",0.792 +/- 0.017,"0.792 [0.779, 0.804]",0.894 +/- 0.008,"0.894 [0.889, 0.900]"
39,Transformer Encoder,External Benchmark 3,External Benchmark 3,transformer_encoder,External_Benchmark_3,External_Benchmark_3,0.910 +/- 0.006,"0.910 [0.905, 0.914]",0.923 +/- 0.004,"0.923 [0.920, 0.926]",0.678 +/- 0.017,"0.678 [0.666, 0.690]",0.815 +/- 0.009,"0.815 [0.809, 0.822]"
40,AmPEP,GenPept-Curated-2025,GenPept-Curated-2025,ampep,GenPept_Curated_2025,GenPept_Curated_2025,0.921 +/- 0.002,"0.921 [0.920, 0.922]",0.895 +/- 0.004,"0.895 [0.892, 0.898]",0.733 +/- 0.004,"0.733 [0.730, 0.736]",0.872 +/- 0.002,"0.872 [0.870, 0.873]"
41,AmPEP,External Benchmark 1,External Benchmark 1,ampep,External_Benchmark_1,External_Benchmark_1,0.850 +/- 0.002,"0.850 [0.848, 0.852]",0.897 +/- 0.001,"0.897 [0.896, 0.898]",0.530 +/- 0.020,"0.530 [0.516, 0.544]",0.776 +/- 0.012,"0.776 [0.767, 0.784]"
42,AmPEP,AMPlify-balanced,AMPlify-balanced,ampep,AMPlify_balanced,AMPlify_balanced,0.956 +/- 0.001,"0.956 [0.955, 0.957]",0.960 +/- 0.001,"0.960 [0.959, 0.961]",0.765 +/- 0.007,"0.765 [0.760, 0.770]",0.877 +/- 0.006,"0.877 [0.873, 0.882]"
43,AmPEP,External Benchmark 3,External Benchmark 3,ampep,External_Benchmark_3,External_Benchmark_3,0.855 +/- 0.002,"0.855 [0.853, 0.856]",0.866 +/- 0.002,"0.866 [0.865, 0.868]",0.548 +/- 0.007,"0.548 [0.543, 0.553]",0.732 +/- 0.020,"0.732 [0.718, 0.746]"
44,AMPScannerV2,GenPept-Curated-2025,GenPept-Curated-2025,ampscannerv2,GenPept_Curated_2025,GenPept_Curated_2025,0.943 +/- 0.005,"0.943 [0.939, 0.947]",0.921 +/- 0.009,"0.921 [0.915, 0.928]",0.789 +/- 0.009,"0.789 [0.783, 0.796]",0.898 +/- 0.004,"0.898 [0.894, 0.901]"
45,AMPScannerV2,External Benchmark 1,External Benchmark 1,ampscannerv2,External_Benchmark_1,External_Benchmark_1,0.876 +/- 0.009,"0.876 [0.870, 0.882]",0.923 +/- 0.005,"0.923 [0.919, 0.926]",0.619 +/- 0.015,"0.619 [0.608, 0.629]",0.807 +/- 0.019,"0.807 [0.793, 0.820]"
46,AMPScannerV2,AMPlify-balanced,AMPlify-balanced,ampscannerv2,AMPlify_balanced,AMPlify_balanced,0.977 +/- 0.003,"0.977 [0.975, 0.979]",0.979 +/- 0.003,"0.979 [0.977, 0.981]",0.844 +/- 0.012,"0.844 [0.836, 0.853]",0.919 +/- 0.008,"0.919 [0.914, 0.925]"
47,AMPScannerV2,External Benchmark 3,External Benchmark 3,ampscannerv2,External_Benchmark_3,External_Benchmark_3,0.905 +/- 0.005,"0.905 [0.902, 0.909]",0.920 +/- 0.004,"0.920 [0.917, 0.922]",0.681 +/- 0.010,"0.681 [0.673, 0.688]",0.815 +/- 0.007,"0.815 [0.810, 0.820]"
48,amPEPpy,GenPept-Curated-2025,GenPept-Curated-2025,ampeppy,GenPept_Curated_2025,GenPept_Curated_2025,0.923 +/- 0.001,"0.923 [0.922, 0.924]",0.897 +/- 0.003,"0.897 [0.895, 0.900]",0.734 +/- 0.004,"0.734 [0.732, 0.737]",0.873 +/- 0.002,"0.873 [0.871, 0.874]"
49,amPEPpy,External Benchmark 1,External Benchmark 1,ampeppy,External_Benchmark_1,External_Benchmark_1,0.852 +/- 0.002,"0.852 [0.850, 0.853]",0.899 +/- 0.001,"0.899 [0.898, 0.900]",0.524 +/- 0.016,"0.524 [0.512, 0.535]",0.775 +/- 0.019,"0.775 [0.762, 0.789]"
50,amPEPpy,AMPlify-balanced,AMPlify-balanced,ampeppy,AMPlify_balanced,AMPlify_balanced,0.956 +/- 0.001,"0.956 [0.956, 0.957]",0.961 +/- 0.001,"0.961 [0.960, 0.961]",0.764 +/- 0.006,"0.764 [0.760, 0.769]",0.876 +/- 0.007,"0.876 [0.871, 0.881]"
51,amPEPpy,External Benchmark 3,External Benchmark 3,ampeppy,External_Benchmark_3,External_Benchmark_3,0.856 +/- 0.002,"0.856 [0.855, 0.857]",0.869 +/- 0.002,"0.869 [0.868, 0.870]",0.555 +/- 0.009,"0.555 [0.549, 0.561]",0.746 +/- 0.015,"0.746 [0.735, 0.756]"

================================================================================================================================================================
CELL 35 TABLE - Table_P2_cross_core_metrics_156.csv
================================================================================================================================================================
Rows: 156 | Columns: 14

,Model,Source dataset,Target dataset,model_id,source_dataset,target_dataset,AUROC mean+/-SD,AUROC mean [95% CI],AUPRC mean+/-SD,AUPRC mean [95% CI],MCC mean+/-SD,MCC mean [95% CI],F1 mean+/-SD,F1 mean [95% CI]
0,Logistic Regression,GenPept-Curated-2025,External Benchmark 1,logistic_regression,GenPept_Curated_2025,External_Benchmark_1,0.587 +/- 0.000,"0.587 [0.587, 0.587]",0.684 +/- 0.000,"0.684 [0.684, 0.684]",0.106 +/- 0.000,"0.106 [0.106, 0.106]",0.589 +/- 0.000,"0.589 [0.589, 0.589]"
1,Logistic Regression,GenPept-Curated-2025,AMPlify-balanced,logistic_regression,GenPept_Curated_2025,AMPlify_balanced,0.581 +/- 0.000,"0.581 [0.581, 0.581]",0.577 +/- 0.000,"0.577 [0.577, 0.577]",0.119 +/- 0.000,"0.119 [0.119, 0.119]",0.573 +/- 0.000,"0.573 [0.573, 0.573]"
2,Logistic Regression,GenPept-Curated-2025,External Benchmark 3,logistic_regression,GenPept_Curated_2025,External_Benchmark_3,0.588 +/- 0.000,"0.588 [0.588, 0.588]",0.589 +/- 0.000,"0.589 [0.589, 0.589]",0.137 +/- 0.000,"0.137 [0.137, 0.137]",0.542 +/- 0.000,"0.542 [0.542, 0.542]"
3,Logistic Regression,External Benchmark 1,GenPept-Curated-2025,logistic_regression,External_Benchmark_1,GenPept_Curated_2025,0.583 +/- 0.000,"0.583 [0.583, 0.583]",0.538 +/- 0.000,"0.538 [0.538, 0.538]",0.079 +/- 0.000,"0.079 [0.079, 0.079]",0.362 +/- 0.000,"0.362 [0.362, 0.362]"
4,Logistic Regression,External Benchmark 1,AMPlify-balanced,logistic_regression,External_Benchmark_1,AMPlify_balanced,0.825 +/- 0.000,"0.825 [0.825, 0.825]",0.616 +/- 0.000,"0.616 [0.616, 0.616]",0.444 +/- 0.000,"0.444 [0.444, 0.444]",0.637 +/- 0.000,"0.637 [0.637, 0.637]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,amPEPpy,AMPlify-balanced,External Benchmark 1,ampeppy,AMPlify_balanced,External_Benchmark_1,0.505 +/- 0.004,"0.505 [0.503, 0.508]",0.369 +/- 0.004,"0.369 [0.366, 0.372]",0.097 +/- 0.017,"0.097 [0.085, 0.109]",0.377 +/- 0.018,"0.377 [0.364, 0.390]"
152,amPEPpy,AMPlify-balanced,External Benchmark 3,ampeppy,AMPlify_balanced,External_Benchmark_3,0.528 +/- 0.002,"0.528 [0.527, 0.530]",0.509 +/- 0.004,"0.509 [0.506, 0.512]",0.095 +/- 0.013,"0.095 [0.085, 0.104]",0.492 +/- 0.016,"0.492 [0.481, 0.504]"
153,amPEPpy,External Benchmark 3,GenPept-Curated-2025,ampeppy,External_Benchmark_3,GenPept_Curated_2025,0.715 +/- 0.011,"0.715 [0.707, 0.723]",0.686 +/- 0.007,"0.686 [0.681, 0.691]",0.303 +/- 0.008,"0.303 [0.297, 0.309]",0.708 +/- 0.002,"0.708 [0.707, 0.710]"
154,amPEPpy,External Benchmark 3,External Benchmark 1,ampeppy,External_Benchmark_3,External_Benchmark_1,0.653 +/- 0.003,"0.653 [0.652, 0.655]",0.605 +/- 0.004,"0.605 [0.602, 0.608]",0.290 +/- 0.018,"0.290 [0.277, 0.303]",0.671 +/- 0.014,"0.671 [0.661, 0.681]"
155,amPEPpy,External Benchmark 3,AMPlify-balanced,ampeppy,External_Benchmark_3,AMPlify_balanced,0.725 +/- 0.002,"0.725 [0.724, 0.727]",0.617 +/- 0.005,"0.617 [0.614, 0.621]",0.362 +/- 0.010,"0.362 [0.355, 0.369]",0.666 +/- 0.005,"0.666 [0.662, 0.670]"

================================================================================================================================================================
CELL 35 TABLE - Table_Supplement_all_10seed_statistics_208.csv
================================================================================================================================================================
Rows: 208 | Columns: 66

,Model,Source dataset,Target dataset,protocol,model_id,model_group,source_dataset,target_dataset,n_seeds,seeds,...,Brier_ci95_low,Brier_ci95_high,ECE10_mean,ECE10_sd,ECE10_se,ECE10_ci95_low,ECE10_ci95_high,n_target,n_positive,n_negative
0,Logistic Regression,GenPept-Curated-2025,GenPept-Curated-2025,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",...,0.162539,0.162539,0.035016,0.000000e+00,0.000000e+00,0.035016,0.035016,2310,1155,1155
1,Logistic Regression,External Benchmark 1,External Benchmark 1,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,External_Benchmark_1,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",...,0.167509,0.167509,0.053726,0.000000e+00,0.000000e+00,0.053726,0.053726,1545,889,656
2,Logistic Regression,AMPlify-balanced,AMPlify-balanced,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,AMPlify_balanced,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",...,0.092235,0.092235,0.021099,0.000000e+00,0.000000e+00,0.021099,0.021099,1592,786,806
3,Logistic Regression,External Benchmark 3,External Benchmark 3,P1_WITHIN_DATASET_SOURCE_TEST,logistic_regression,controlled_baseline,External_Benchmark_3,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",...,0.140554,0.140554,0.036088,7.314236e-18,2.312965e-18,0.036088,0.036088,2070,1010,1060
4,Linear SVM (calibrated),GenPept-Curated-2025,GenPept-Curated-2025,P1_WITHIN_DATASET_SOURCE_TEST,linear_svm_calibrated,controlled_baseline,GenPept_Curated_2025,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",...,0.161534,0.161908,0.041683,4.099269e-03,1.296303e-03,0.038750,0.044615,2310,1155,1155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,amPEPpy,AMPlify-balanced,External Benchmark 1,P2_CROSS_DATASET,ampeppy,published_amp_method,AMPlify_balanced,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",...,0.267639,0.269409,0.202520,6.442817e-03,2.037398e-03,0.197911,0.207128,957,309,648
204,amPEPpy,AMPlify-balanced,External Benchmark 3,P2_CROSS_DATASET,ampeppy,published_amp_method,AMPlify_balanced,External_Benchmark_3,10,"100,101,102,103,104,105,106,107,108,109",...,0.286509,0.287633,0.186631,3.017333e-03,9.541644e-04,0.184472,0.188789,1910,850,1060
205,amPEPpy,External Benchmark 3,GenPept-Curated-2025,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,GenPept_Curated_2025,10,"100,101,102,103,104,105,106,107,108,109",...,0.244355,0.249074,0.181365,8.519587e-03,2.694130e-03,0.175271,0.187460,2301,1147,1154
206,amPEPpy,External Benchmark 3,External Benchmark 1,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,External_Benchmark_1,10,"100,101,102,103,104,105,106,107,108,109",...,0.262184,0.263996,0.173761,5.735641e-03,1.813769e-03,0.169658,0.177864,1322,666,656
207,amPEPpy,External Benchmark 3,AMPlify-balanced,P2_CROSS_DATASET,ampeppy,published_amp_method,External_Benchmark_3,AMPlify_balanced,10,"100,101,102,103,104,105,106,107,108,109",...,0.231698,0.232804,0.148337,5.104118e-03,1.614064e-03,0.144686,0.151988,1397,593,804

================================================================================================================================================================
CELL 35 TABLE - Table_model_level_P1_vs_P2_descriptive_macro_summary_13.csv
================================================================================================================================================================
Rows: 13 | Columns: 35

,model_id,Model,P1_n_configurations,P2_n_configurations,summary_type,P1_AUROC_macro_mean,P2_AUROC_macro_mean,Delta_P2_minus_P1_AUROC,P1_AUPRC_macro_mean,P2_AUPRC_macro_mean,...,Delta_P2_minus_P1_Sensitivity,P1_Specificity_macro_mean,P2_Specificity_macro_mean,Delta_P2_minus_P1_Specificity,P1_Brier_macro_mean,P2_Brier_macro_mean,Delta_P2_minus_P1_Brier,P1_ECE10_macro_mean,P2_ECE10_macro_mean,Delta_P2_minus_P1_ECE10
0,logistic_regression,Logistic Regression,4,12,descriptive_macro_mean_across_locked_configura...,0.871834,0.654186,-0.217648,0.872124,0.608605,...,-0.211414,0.809367,0.630909,-0.178458,0.140709,0.275670,0.134961,0.036482,0.209573,0.173091
1,linear_svm_calibrated,Linear SVM (calibrated),4,12,descriptive_macro_mean_across_locked_configura...,0.873199,0.654529,-0.218670,0.874525,0.610097,...,-0.216230,0.822731,0.658363,-0.164368,0.140674,0.255607,0.114933,0.047873,0.165913,0.118041
2,random_forest,Random Forest,4,12,descriptive_macro_mean_across_locked_configura...,0.927465,0.667551,-0.259914,0.937584,0.654603,...,-0.410522,0.883557,0.811179,-0.072378,0.113824,0.238097,0.124272,0.097838,0.161069,0.063232
3,extra_trees,Extra Trees,4,12,descriptive_macro_mean_across_locked_configura...,0.929564,0.673827,-0.255737,0.941055,0.659420,...,-0.406542,0.900122,0.817586,-0.082536,0.114964,0.229851,0.114887,0.111451,0.148879,0.037428
4,hist_gradient_boosting,HistGradientBoosting,4,12,descriptive_macro_mean_across_locked_configura...,0.932545,0.707050,-0.225495,0.943878,0.677869,...,-0.337567,0.888625,0.781816,-0.106809,0.098193,0.251662,0.153468,0.029118,0.193458,0.164339
5,lightgbm,LightGBM,4,12,descriptive_macro_mean_across_locked_configura...,0.936097,0.707836,-0.228261,0.946256,0.676665,...,-0.341221,0.886410,0.768605,-0.117805,0.096082,0.263324,0.167243,0.035725,0.218445,0.182721
6,cnn1d,CNN1D,4,12,descriptive_macro_mean_across_locked_configura...,0.922607,0.657424,-0.265183,0.934396,0.638225,...,-0.299291,0.871307,0.695865,-0.175442,0.106564,0.296865,0.190301,0.043896,0.255613,0.211717
7,bilstm,BiLSTM,4,12,descriptive_macro_mean_across_locked_configura...,0.919137,0.660237,-0.258900,0.926181,0.637036,...,-0.267951,0.836909,0.639786,-0.197123,0.107359,0.290594,0.183235,0.029168,0.245401,0.216233
8,bilstm_attention,BiLSTM + Attention,4,12,descriptive_macro_mean_across_locked_configura...,0.911737,0.651843,-0.259894,0.917205,0.618958,...,-0.253223,0.852109,0.654641,-0.197468,0.112640,0.295657,0.183017,0.032337,0.253947,0.221610
9,transformer_encoder,Transformer Encoder,4,12,descriptive_macro_mean_across_locked_configura...,0.907250,0.650419,-0.256830,0.913768,0.620414,...,-0.248645,0.851393,0.650191,-0.201202,0.118672,0.305147,0.186475,0.044318,0.262956,0.218637
10,ampep,AmPEP,4,12,descriptive_macro_mean_across_locked_configura...,0.895344,0.616939,-0.278404,0.904685,0.583425,...,-0.258328,0.843187,0.628255,-0.214933,0.129061,0.262891,0.133830,0.062273,0.181350,0.119077
11,ampscannerv2,AMPScannerV2,4,12,descriptive_macro_mean_across_locked_configura...,0.925307,0.665956,-0.259352,0.935579,0.650224,...,-0.294714,0.899744,0.717831,-0.181912,0.112806,0.325342,0.212536,0.089320,0.306291,0.216971
12,ampeppy,amPEPpy,4,12,descriptive_macro_mean_across_locked_configura...,0.896687,0.616521,-0.280167,0.906447,0.585254,...,-0.253153,0.833638,0.615540,-0.218098,0.129024,0.262188,0.133164,0.066774,0.181795,0.115021

================================================================================================================================================================
CELL 35 MATRIX - P1_AUPRC_meanSD_13x4.csv
================================================================================================================================================================
Rows: 13 | Columns: 5

,Unnamed: 0,GenPept-Curated-2025,External Benchmark 1,AMPlify-balanced,External Benchmark 3
0,Logistic Regression,0.804 +/- 0.000,0.883 +/- 0.000,0.919 +/- 0.000,0.882 +/- 0.000
1,Linear SVM (calibrated),0.809 +/- 0.001,0.885 +/- 0.000,0.922 +/- 0.001,0.882 +/- 0.000
2,Random Forest,0.930 +/- 0.002,0.928 +/- 0.001,0.974 +/- 0.001,0.918 +/- 0.001
3,Extra Trees,0.940 +/- 0.001,0.929 +/- 0.001,0.978 +/- 0.000,0.917 +/- 0.001
4,HistGradientBoosting,0.952 +/- 0.000,0.928 +/- 0.000,0.970 +/- 0.000,0.926 +/- 0.000
5,LightGBM,0.951 +/- 0.001,0.933 +/- 0.001,0.973 +/- 0.001,0.929 +/- 0.001
6,CNN1D,0.927 +/- 0.005,0.911 +/- 0.008,0.974 +/- 0.003,0.925 +/- 0.003
7,BiLSTM,0.890 +/- 0.017,0.918 +/- 0.005,0.968 +/- 0.003,0.928 +/- 0.002
8,BiLSTM + Attention,0.874 +/- 0.020,0.913 +/- 0.011,0.958 +/- 0.006,0.924 +/- 0.002
9,Transformer Encoder,0.863 +/- 0.017,0.912 +/- 0.008,0.957 +/- 0.004,0.923 +/- 0.004
10,AmPEP,0.895 +/- 0.004,0.897 +/- 0.001,0.960 +/- 0.001,0.866 +/- 0.002
11,AMPScannerV2,0.921 +/- 0.009,0.923 +/- 0.005,0.979 +/- 0.003,0.920 +/- 0.004
12,amPEPpy,0.897 +/- 0.003,0.899 +/- 0.001,0.961 +/- 0.001,0.869 +/- 0.002

================================================================================================================================================================
CELL 35 MATRIX - P1_AUPRC_mean_13x4.csv
================================================================================================================================================================
Rows: 13 | Columns: 5

,Unnamed: 0,GenPept-Curated-2025,External Benchmark 1,AMPlify-balanced,External Benchmark 3
0,Logistic Regression,0.803995,0.883232,0.919420,0.881849
1,Linear SVM (calibrated),0.809312,0.884820,0.921933,0.882035
2,Random Forest,0.930119,0.928092,0.974034,0.918093
3,Extra Trees,0.940032,0.929317,0.978030,0.916843
4,HistGradientBoosting,0.952465,0.927666,0.969644,0.925737
5,LightGBM,0.950964,0.932807,0.972550,0.928702
6,CNN1D,0.927479,0.911403,0.973521,0.925180
7,BiLSTM,0.890476,0.918202,0.968313,0.927732
8,BiLSTM + Attention,0.873791,0.913499,0.957871,0.923661
9,Transformer Encoder,0.862745,0.912279,0.957352,0.922696
10,AmPEP,0.895155,0.897341,0.960003,0.866240
11,AMPScannerV2,0.921322,0.922588,0.978863,0.919544
12,amPEPpy,0.897455,0.898916,0.960658,0.868760

================================================================================================================================================================
CELL 35 MATRIX - P1_AUROC_meanSD_13x4.csv
================================================================================================================================================================
Rows: 13 | Columns: 5

,Unnamed: 0,GenPept-Curated-2025,External Benchmark 1,AMPlify-balanced,External Benchmark 3
0,Logistic Regression,0.839 +/- 0.000,0.835 +/- 0.000,0.940 +/- 0.000,0.873 +/- 0.000
1,Linear SVM (calibrated),0.842 +/- 0.000,0.837 +/- 0.000,0.940 +/- 0.000,0.873 +/- 0.000
2,Random Forest,0.945 +/- 0.001,0.887 +/- 0.001,0.972 +/- 0.001,0.906 +/- 0.000
3,Extra Trees,0.950 +/- 0.000,0.888 +/- 0.001,0.976 +/- 0.000,0.904 +/- 0.001
4,HistGradientBoosting,0.960 +/- 0.000,0.886 +/- 0.000,0.969 +/- 0.000,0.915 +/- 0.000
5,LightGBM,0.960 +/- 0.001,0.894 +/- 0.001,0.972 +/- 0.001,0.919 +/- 0.001
6,CNN1D,0.942 +/- 0.004,0.862 +/- 0.010,0.972 +/- 0.002,0.914 +/- 0.004
7,BiLSTM,0.920 +/- 0.013,0.876 +/- 0.007,0.965 +/- 0.003,0.915 +/- 0.002
8,BiLSTM + Attention,0.908 +/- 0.014,0.871 +/- 0.017,0.957 +/- 0.004,0.910 +/- 0.003
9,Transformer Encoder,0.897 +/- 0.010,0.865 +/- 0.012,0.957 +/- 0.004,0.910 +/- 0.006
10,AmPEP,0.921 +/- 0.002,0.850 +/- 0.002,0.956 +/- 0.001,0.855 +/- 0.002
11,AMPScannerV2,0.943 +/- 0.005,0.876 +/- 0.009,0.977 +/- 0.003,0.905 +/- 0.005
12,amPEPpy,0.923 +/- 0.001,0.852 +/- 0.002,0.956 +/- 0.001,0.856 +/- 0.002

================================================================================================================================================================
CELL 35 MATRIX - P1_AUROC_mean_13x4.csv
================================================================================================================================================================
Rows: 13 | Columns: 5

,Unnamed: 0,GenPept-Curated-2025,External Benchmark 1,AMPlify-balanced,External Benchmark 3
0,Logistic Regression,0.839292,0.835328,0.939924,0.872791
1,Linear SVM (calibrated),0.842129,0.837052,0.940165,0.873449
2,Random Forest,0.944682,0.887037,0.972239,0.905902
3,Extra Trees,0.950454,0.887555,0.976106,0.904144
4,HistGradientBoosting,0.959645,0.886072,0.969152,0.915313
5,LightGBM,0.959511,0.894053,0.971622,0.919204
6,CNN1D,0.942283,0.862420,0.971984,0.913743
7,BiLSTM,0.919923,0.876393,0.965363,0.914870
8,BiLSTM + Attention,0.908232,0.871274,0.957416,0.910026
9,Transformer Encoder,0.897081,0.865386,0.956815,0.909716
10,AmPEP,0.921039,0.849900,0.955830,0.854606
11,AMPScannerV2,0.943052,0.876020,0.976764,0.905393
12,amPEPpy,0.922767,0.851775,0.956297,0.855910

================================================================================================================================================================
CELL 35 MATRIX - P1_F1_meanSD_13x4.csv
================================================================================================================================================================
Rows: 13 | Columns: 5

,Unnamed: 0,GenPept-Curated-2025,External Benchmark 1,AMPlify-balanced,External Benchmark 3
0,Logistic Regression,0.777 +/- 0.000,0.784 +/- 0.000,0.876 +/- 0.000,0.794 +/- 0.000
1,Linear SVM (calibrated),0.779 +/- 0.003,0.782 +/- 0.011,0.859 +/- 0.008,0.788 +/- 0.003
2,Random Forest,0.883 +/- 0.002,0.813 +/- 0.004,0.909 +/- 0.003,0.811 +/- 0.007
3,Extra Trees,0.889 +/- 0.003,0.811 +/- 0.008,0.914 +/- 0.003,0.803 +/- 0.009
4,HistGradientBoosting,0.895 +/- 0.000,0.817 +/- 0.000,0.903 +/- 0.000,0.829 +/- 0.000
5,LightGBM,0.902 +/- 0.003,0.831 +/- 0.005,0.913 +/- 0.004,0.834 +/- 0.011
6,CNN1D,0.883 +/- 0.005,0.794 +/- 0.016,0.910 +/- 0.006,0.820 +/- 0.011
7,BiLSTM,0.866 +/- 0.013,0.809 +/- 0.017,0.905 +/- 0.007,0.829 +/- 0.006
8,BiLSTM + Attention,0.861 +/- 0.008,0.791 +/- 0.022,0.889 +/- 0.005,0.820 +/- 0.004
9,Transformer Encoder,0.840 +/- 0.007,0.791 +/- 0.014,0.894 +/- 0.008,0.815 +/- 0.009
10,AmPEP,0.872 +/- 0.002,0.776 +/- 0.012,0.877 +/- 0.006,0.732 +/- 0.020
11,AMPScannerV2,0.898 +/- 0.004,0.807 +/- 0.019,0.919 +/- 0.008,0.815 +/- 0.007
12,amPEPpy,0.873 +/- 0.002,0.775 +/- 0.019,0.876 +/- 0.007,0.746 +/- 0.015

================================================================================================================================================================
CELL 35 MATRIX - P1_F1_mean_13x4.csv
================================================================================================================================================================
Rows: 13 | Columns: 5

,Unnamed: 0,GenPept-Curated-2025,External Benchmark 1,AMPlify-balanced,External Benchmark 3
0,Logistic Regression,0.776578,0.783831,0.875641,0.794209
1,Linear SVM (calibrated),0.778523,0.781547,0.859230,0.787696
2,Random Forest,0.882653,0.813394,0.908923,0.810828
3,Extra Trees,0.888547,0.810542,0.913959,0.803416
4,HistGradientBoosting,0.894938,0.817178,0.903226,0.828541
5,LightGBM,0.902000,0.831083,0.912760,0.833763
6,CNN1D,0.882832,0.794332,0.910009,0.820430
7,BiLSTM,0.865634,0.809264,0.904949,0.829459
8,BiLSTM + Attention,0.861104,0.791351,0.889427,0.820301
9,Transformer Encoder,0.839546,0.790597,0.894482,0.815434
10,AmPEP,0.871765,0.775926,0.877267,0.731839
11,AMPScannerV2,0.897525,0.806802,0.919375,0.815147
12,amPEPpy,0.872510,0.775338,0.875855,0.745715

================================================================================================================================================================
CELL 35 MATRIX - P1_MCC_meanSD_13x4.csv
================================================================================================================================================================
Rows: 13 | Columns: 5

,Unnamed: 0,GenPept-Curated-2025,External Benchmark 1,AMPlify-balanced,External Benchmark 3
0,Logistic Regression,0.536 +/- 0.000,0.520 +/- 0.000,0.756 +/- 0.000,0.617 +/- 0.000
1,Linear SVM (calibrated),0.538 +/- 0.003,0.527 +/- 0.004,0.738 +/- 0.009,0.614 +/- 0.003
2,Random Forest,0.757 +/- 0.005,0.627 +/- 0.005,0.822 +/- 0.007,0.666 +/- 0.011
3,Extra Trees,0.770 +/- 0.005,0.628 +/- 0.005,0.840 +/- 0.005,0.665 +/- 0.005
4,HistGradientBoosting,0.787 +/- 0.000,0.628 +/- 0.000,0.805 +/- 0.000,0.694 +/- 0.000
5,LightGBM,0.800 +/- 0.005,0.632 +/- 0.011,0.829 +/- 0.009,0.703 +/- 0.008
6,CNN1D,0.758 +/- 0.011,0.578 +/- 0.026,0.822 +/- 0.011,0.684 +/- 0.012
7,BiLSTM,0.720 +/- 0.029,0.573 +/- 0.018,0.812 +/- 0.013,0.681 +/- 0.014
8,BiLSTM + Attention,0.710 +/- 0.017,0.579 +/- 0.023,0.786 +/- 0.009,0.673 +/- 0.011
9,Transformer Encoder,0.664 +/- 0.017,0.571 +/- 0.022,0.792 +/- 0.017,0.678 +/- 0.017
10,AmPEP,0.733 +/- 0.004,0.530 +/- 0.020,0.765 +/- 0.007,0.548 +/- 0.007
11,AMPScannerV2,0.789 +/- 0.009,0.619 +/- 0.015,0.844 +/- 0.012,0.681 +/- 0.010
12,amPEPpy,0.734 +/- 0.004,0.524 +/- 0.016,0.764 +/- 0.006,0.555 +/- 0.009

================================================================================================================================================================
CELL 35 MATRIX - P1_MCC_mean_13x4.csv
================================================================================================================================================================
Rows: 13 | Columns: 5

,Unnamed: 0,GenPept-Curated-2025,External Benchmark 1,AMPlify-balanced,External Benchmark 3
0,Logistic Regression,0.536133,0.520291,0.756283,0.616604
1,Linear SVM (calibrated),0.537758,0.527452,0.737738,0.614386
2,Random Forest,0.757358,0.626765,0.822090,0.665665
3,Extra Trees,0.770381,0.627729,0.839728,0.664699
4,HistGradientBoosting,0.786643,0.628089,0.805129,0.694289
5,LightGBM,0.799953,0.631868,0.828799,0.703245
6,CNN1D,0.758438,0.578466,0.821795,0.683985
7,BiLSTM,0.720094,0.572626,0.812135,0.680547
8,BiLSTM + Attention,0.709692,0.578542,0.786364,0.673304
9,Transformer Encoder,0.663796,0.571183,0.791567,0.678016
10,AmPEP,0.732567,0.530015,0.765128,0.548322
11,AMPScannerV2,0.789234,0.618626,0.844410,0.680743
12,amPEPpy,0.734291,0.523645,0.764291,0.555180

================================================================================================================================================================
CELL 35 MATRIX - P2_AUPRC_meanSD_13x12.csv
================================================================================================================================================================
Rows: 13 | Columns: 13

,Unnamed: 0,GenPept-Curated-2025 -> External Benchmark 1,GenPept-Curated-2025 -> AMPlify-balanced,GenPept-Curated-2025 -> External Benchmark 3,External Benchmark 1 -> GenPept-Curated-2025,External Benchmark 1 -> AMPlify-balanced,External Benchmark 1 -> External Benchmark 3,AMPlify-balanced -> GenPept-Curated-2025,AMPlify-balanced -> External Benchmark 1,AMPlify-balanced -> External Benchmark 3,External Benchmark 3 -> GenPept-Curated-2025,External Benchmark 3 -> External Benchmark 1,External Benchmark 3 -> AMPlify-balanced
0,Logistic Regression,0.684 +/- 0.000,0.577 +/- 0.000,0.589 +/- 0.000,0.538 +/- 0.000,0.616 +/- 0.000,0.780 +/- 0.000,0.543 +/- 0.000,0.376 +/- 0.000,0.663 +/- 0.000,0.560 +/- 0.000,0.819 +/- 0.000,0.559 +/- 0.000
1,Linear SVM (calibrated),0.685 +/- 0.001,0.588 +/- 0.002,0.588 +/- 0.001,0.538 +/- 0.001,0.613 +/- 0.002,0.781 +/- 0.001,0.546 +/- 0.001,0.379 +/- 0.001,0.668 +/- 0.001,0.558 +/- 0.001,0.818 +/- 0.000,0.559 +/- 0.001
2,Random Forest,0.526 +/- 0.002,0.476 +/- 0.002,0.548 +/- 0.002,0.499 +/- 0.002,0.831 +/- 0.002,0.853 +/- 0.001,0.593 +/- 0.002,0.512 +/- 0.002,0.807 +/- 0.002,0.570 +/- 0.003,0.842 +/- 0.001,0.797 +/- 0.004
3,Extra Trees,0.532 +/- 0.001,0.465 +/- 0.003,0.536 +/- 0.004,0.511 +/- 0.002,0.843 +/- 0.001,0.854 +/- 0.001,0.589 +/- 0.004,0.519 +/- 0.003,0.812 +/- 0.001,0.573 +/- 0.003,0.869 +/- 0.001,0.810 +/- 0.003
4,HistGradientBoosting,0.601 +/- 0.000,0.530 +/- 0.000,0.666 +/- 0.000,0.567 +/- 0.000,0.755 +/- 0.000,0.839 +/- 0.000,0.611 +/- 0.000,0.518 +/- 0.000,0.787 +/- 0.000,0.685 +/- 0.000,0.831 +/- 0.000,0.742 +/- 0.000
5,LightGBM,0.604 +/- 0.004,0.529 +/- 0.003,0.655 +/- 0.004,0.544 +/- 0.006,0.758 +/- 0.004,0.842 +/- 0.002,0.606 +/- 0.004,0.514 +/- 0.004,0.795 +/- 0.002,0.684 +/- 0.004,0.836 +/- 0.003,0.753 +/- 0.005
6,CNN1D,0.579 +/- 0.014,0.533 +/- 0.017,0.587 +/- 0.017,0.573 +/- 0.028,0.785 +/- 0.040,0.854 +/- 0.006,0.515 +/- 0.032,0.427 +/- 0.014,0.669 +/- 0.022,0.595 +/- 0.016,0.827 +/- 0.022,0.714 +/- 0.038
7,BiLSTM,0.596 +/- 0.028,0.550 +/- 0.017,0.655 +/- 0.018,0.565 +/- 0.022,0.808 +/- 0.025,0.831 +/- 0.014,0.494 +/- 0.025,0.420 +/- 0.019,0.644 +/- 0.024,0.636 +/- 0.024,0.741 +/- 0.023,0.704 +/- 0.038
8,BiLSTM + Attention,0.584 +/- 0.026,0.557 +/- 0.029,0.601 +/- 0.026,0.556 +/- 0.028,0.752 +/- 0.039,0.833 +/- 0.011,0.470 +/- 0.022,0.403 +/- 0.013,0.644 +/- 0.018,0.654 +/- 0.024,0.710 +/- 0.018,0.663 +/- 0.025
9,Transformer Encoder,0.599 +/- 0.024,0.538 +/- 0.030,0.650 +/- 0.033,0.583 +/- 0.013,0.729 +/- 0.076,0.808 +/- 0.011,0.486 +/- 0.035,0.407 +/- 0.019,0.617 +/- 0.021,0.707 +/- 0.019,0.697 +/- 0.027,0.624 +/- 0.054
10,AmPEP,0.532 +/- 0.003,0.511 +/- 0.004,0.608 +/- 0.004,0.545 +/- 0.014,0.805 +/- 0.002,0.728 +/- 0.003,0.507 +/- 0.008,0.368 +/- 0.005,0.501 +/- 0.003,0.680 +/- 0.009,0.601 +/- 0.007,0.615 +/- 0.006
11,AMPScannerV2,0.576 +/- 0.024,0.503 +/- 0.015,0.596 +/- 0.015,0.529 +/- 0.022,0.824 +/- 0.015,0.832 +/- 0.012,0.525 +/- 0.033,0.454 +/- 0.017,0.714 +/- 0.024,0.587 +/- 0.017,0.848 +/- 0.013,0.816 +/- 0.021
12,amPEPpy,0.535 +/- 0.002,0.505 +/- 0.003,0.607 +/- 0.004,0.547 +/- 0.013,0.803 +/- 0.003,0.729 +/- 0.002,0.511 +/- 0.009,0.369 +/- 0.004,0.509 +/- 0.004,0.686 +/- 0.007,0.605 +/- 0.004,0.617 +/- 0.005

================================================================================================================================================================
CELL 35 MATRIX - P2_AUPRC_mean_13x12.csv
================================================================================================================================================================
Rows: 13 | Columns: 13

,Unnamed: 0,GenPept-Curated-2025 -> External Benchmark 1,GenPept-Curated-2025 -> AMPlify-balanced,GenPept-Curated-2025 -> External Benchmark 3,External Benchmark 1 -> GenPept-Curated-2025,External Benchmark 1 -> AMPlify-balanced,External Benchmark 1 -> External Benchmark 3,AMPlify-balanced -> GenPept-Curated-2025,AMPlify-balanced -> External Benchmark 1,AMPlify-balanced -> External Benchmark 3,External Benchmark 3 -> GenPept-Curated-2025,External Benchmark 3 -> External Benchmark 1,External Benchmark 3 -> AMPlify-balanced
0,Logistic Regression,0.684111,0.576974,0.589320,0.538105,0.615737,0.779829,0.543158,0.375821,0.662815,0.559922,0.818568,0.558901
1,Linear SVM (calibrated),0.684722,0.588471,0.587843,0.537545,0.612591,0.781265,0.546001,0.379053,0.668484,0.557630,0.818320,0.559239
2,Random Forest,0.526432,0.475526,0.548429,0.499201,0.831345,0.853308,0.592934,0.512111,0.807272,0.569959,0.841590,0.797127
3,Extra Trees,0.532008,0.464627,0.535999,0.511170,0.843405,0.853921,0.588676,0.519200,0.812399,0.572882,0.869090,0.809668
4,HistGradientBoosting,0.601349,0.530124,0.666148,0.567019,0.755470,0.839087,0.611423,0.518459,0.787412,0.684784,0.831100,0.742049
5,LightGBM,0.603865,0.529106,0.655441,0.544378,0.758350,0.841835,0.605695,0.514204,0.794606,0.683663,0.836114,0.752722
6,CNN1D,0.578620,0.532942,0.586900,0.572759,0.784892,0.854430,0.515434,0.427000,0.669035,0.595394,0.827029,0.714262
7,BiLSTM,0.595871,0.550496,0.654630,0.565281,0.808108,0.830721,0.494323,0.419639,0.644227,0.635913,0.741260,0.703966
8,BiLSTM + Attention,0.583939,0.557383,0.601216,0.556288,0.751886,0.832890,0.469984,0.402879,0.644226,0.653800,0.710029,0.662970
9,Transformer Encoder,0.599090,0.538400,0.649609,0.583474,0.729387,0.808427,0.485903,0.406595,0.617273,0.706527,0.696570,0.623718
10,AmPEP,0.531765,0.510593,0.608410,0.545223,0.804619,0.728067,0.507478,0.367834,0.500877,0.680158,0.600874,0.615201
11,AMPScannerV2,0.576125,0.502706,0.595868,0.529490,0.823508,0.831691,0.524533,0.453996,0.713750,0.587298,0.847901,0.815819
12,amPEPpy,0.534924,0.504742,0.607376,0.546650,0.802660,0.729261,0.510640,0.369207,0.509064,0.685773,0.605263,0.617492

================================================================================================================================================================
CELL 35 MATRIX - P2_AUROC_meanSD_13x12.csv
================================================================================================================================================================
Rows: 13 | Columns: 13

,Unnamed: 0,GenPept-Curated-2025 -> External Benchmark 1,GenPept-Curated-2025 -> AMPlify-balanced,GenPept-Curated-2025 -> External Benchmark 3,External Benchmark 1 -> GenPept-Curated-2025,External Benchmark 1 -> AMPlify-balanced,External Benchmark 1 -> External Benchmark 3,AMPlify-balanced -> GenPept-Curated-2025,AMPlify-balanced -> External Benchmark 1,AMPlify-balanced -> External Benchmark 3,External Benchmark 3 -> GenPept-Curated-2025,External Benchmark 3 -> External Benchmark 1,External Benchmark 3 -> AMPlify-balanced
0,Logistic Regression,0.587 +/- 0.000,0.581 +/- 0.000,0.588 +/- 0.000,0.583 +/- 0.000,0.825 +/- 0.000,0.788 +/- 0.000,0.578 +/- 0.000,0.533 +/- 0.000,0.661 +/- 0.000,0.601 +/- 0.000,0.811 +/- 0.000,0.713 +/- 0.000
1,Linear SVM (calibrated),0.587 +/- 0.001,0.589 +/- 0.001,0.588 +/- 0.001,0.580 +/- 0.001,0.825 +/- 0.001,0.790 +/- 0.000,0.578 +/- 0.001,0.533 +/- 0.001,0.666 +/- 0.001,0.599 +/- 0.001,0.811 +/- 0.000,0.710 +/- 0.001
2,Random Forest,0.460 +/- 0.002,0.513 +/- 0.004,0.555 +/- 0.003,0.487 +/- 0.004,0.877 +/- 0.002,0.848 +/- 0.001,0.594 +/- 0.003,0.636 +/- 0.002,0.805 +/- 0.002,0.540 +/- 0.005,0.836 +/- 0.001,0.860 +/- 0.002
3,Extra Trees,0.449 +/- 0.002,0.489 +/- 0.005,0.532 +/- 0.002,0.519 +/- 0.006,0.890 +/- 0.001,0.847 +/- 0.001,0.612 +/- 0.005,0.651 +/- 0.004,0.808 +/- 0.001,0.569 +/- 0.003,0.851 +/- 0.001,0.869 +/- 0.001
4,HistGradientBoosting,0.549 +/- 0.000,0.575 +/- 0.000,0.671 +/- 0.000,0.577 +/- 0.000,0.855 +/- 0.000,0.836 +/- 0.000,0.611 +/- 0.000,0.643 +/- 0.000,0.792 +/- 0.000,0.701 +/- 0.000,0.833 +/- 0.000,0.842 +/- 0.000
5,LightGBM,0.559 +/- 0.002,0.577 +/- 0.003,0.669 +/- 0.002,0.554 +/- 0.008,0.858 +/- 0.002,0.838 +/- 0.002,0.613 +/- 0.004,0.639 +/- 0.005,0.795 +/- 0.002,0.703 +/- 0.003,0.839 +/- 0.002,0.850 +/- 0.002
6,CNN1D,0.522 +/- 0.019,0.555 +/- 0.021,0.577 +/- 0.018,0.583 +/- 0.037,0.872 +/- 0.018,0.848 +/- 0.005,0.504 +/- 0.029,0.543 +/- 0.019,0.647 +/- 0.024,0.600 +/- 0.020,0.833 +/- 0.011,0.806 +/- 0.026
7,BiLSTM,0.543 +/- 0.025,0.595 +/- 0.020,0.650 +/- 0.019,0.546 +/- 0.021,0.876 +/- 0.008,0.837 +/- 0.011,0.490 +/- 0.026,0.532 +/- 0.013,0.631 +/- 0.021,0.640 +/- 0.031,0.790 +/- 0.013,0.791 +/- 0.017
8,BiLSTM + Attention,0.536 +/- 0.032,0.605 +/- 0.023,0.632 +/- 0.018,0.543 +/- 0.034,0.849 +/- 0.017,0.834 +/- 0.013,0.455 +/- 0.036,0.531 +/- 0.014,0.640 +/- 0.017,0.664 +/- 0.035,0.770 +/- 0.011,0.765 +/- 0.013
9,Transformer Encoder,0.548 +/- 0.024,0.577 +/- 0.034,0.662 +/- 0.016,0.593 +/- 0.019,0.829 +/- 0.030,0.809 +/- 0.006,0.462 +/- 0.035,0.521 +/- 0.020,0.605 +/- 0.018,0.715 +/- 0.028,0.746 +/- 0.016,0.737 +/- 0.039
10,AmPEP,0.473 +/- 0.003,0.580 +/- 0.006,0.593 +/- 0.004,0.564 +/- 0.011,0.836 +/- 0.003,0.751 +/- 0.004,0.491 +/- 0.007,0.505 +/- 0.005,0.526 +/- 0.004,0.710 +/- 0.012,0.651 +/- 0.005,0.723 +/- 0.003
11,AMPScannerV2,0.523 +/- 0.026,0.538 +/- 0.023,0.602 +/- 0.011,0.525 +/- 0.029,0.884 +/- 0.008,0.821 +/- 0.012,0.520 +/- 0.038,0.569 +/- 0.025,0.700 +/- 0.029,0.598 +/- 0.031,0.840 +/- 0.010,0.870 +/- 0.010
12,amPEPpy,0.473 +/- 0.003,0.572 +/- 0.004,0.587 +/- 0.003,0.562 +/- 0.009,0.835 +/- 0.004,0.749 +/- 0.003,0.492 +/- 0.007,0.505 +/- 0.004,0.528 +/- 0.002,0.715 +/- 0.011,0.653 +/- 0.003,0.725 +/- 0.002

================================================================================================================================================================
CELL 35 MATRIX - P2_AUROC_mean_13x12.csv
================================================================================================================================================================
Rows: 13 | Columns: 13

,Unnamed: 0,GenPept-Curated-2025 -> External Benchmark 1,GenPept-Curated-2025 -> AMPlify-balanced,GenPept-Curated-2025 -> External Benchmark 3,External Benchmark 1 -> GenPept-Curated-2025,External Benchmark 1 -> AMPlify-balanced,External Benchmark 1 -> External Benchmark 3,AMPlify-balanced -> GenPept-Curated-2025,AMPlify-balanced -> External Benchmark 1,AMPlify-balanced -> External Benchmark 3,External Benchmark 3 -> GenPept-Curated-2025,External Benchmark 3 -> External Benchmark 1,External Benchmark 3 -> AMPlify-balanced
0,Logistic Regression,0.587197,0.580937,0.587977,0.582685,0.825130,0.788495,0.578136,0.533211,0.660698,0.601272,0.811388,0.713100
1,Linear SVM (calibrated),0.587110,0.588659,0.587509,0.579667,0.824538,0.789982,0.577794,0.532760,0.665907,0.599264,0.811297,0.709858
2,Random Forest,0.459689,0.513159,0.555033,0.486864,0.877016,0.847755,0.594429,0.635513,0.804999,0.539663,0.836302,0.860194
3,Extra Trees,0.449347,0.488540,0.532088,0.518976,0.889922,0.846617,0.612471,0.650729,0.807744,0.569040,0.851281,0.869169
4,HistGradientBoosting,0.548725,0.574756,0.670563,0.577419,0.854928,0.836261,0.610941,0.643269,0.791674,0.701339,0.833047,0.841679
5,LightGBM,0.558739,0.577073,0.668524,0.553686,0.857859,0.838238,0.613323,0.639253,0.795475,0.702587,0.839200,0.850081
6,CNN1D,0.522067,0.554623,0.576826,0.582639,0.872359,0.847765,0.503816,0.543329,0.647324,0.599601,0.832844,0.805901
7,BiLSTM,0.543326,0.595393,0.650271,0.546208,0.876415,0.836727,0.490444,0.532189,0.631113,0.639770,0.790030,0.790952
8,BiLSTM + Attention,0.536001,0.604957,0.631562,0.542769,0.848641,0.833535,0.455491,0.530652,0.639577,0.664072,0.769905,0.764953
9,Transformer Encoder,0.548300,0.577273,0.661764,0.592844,0.828746,0.808960,0.462096,0.521006,0.604966,0.715495,0.746355,0.737229
10,AmPEP,0.472944,0.580401,0.592516,0.564270,0.835681,0.751292,0.490853,0.505296,0.526177,0.710135,0.650568,0.723140
11,AMPScannerV2,0.522651,0.537850,0.602191,0.525423,0.884287,0.821176,0.520040,0.569283,0.700446,0.598385,0.839642,0.870094
12,amPEPpy,0.473010,0.572287,0.587469,0.562184,0.834648,0.748615,0.492475,0.505463,0.528125,0.715238,0.653348,0.725385

================================================================================================================================================================
CELL 35 MATRIX - P2_F1_meanSD_13x12.csv
================================================================================================================================================================
Rows: 13 | Columns: 13

,Unnamed: 0,GenPept-Curated-2025 -> External Benchmark 1,GenPept-Curated-2025 -> AMPlify-balanced,GenPept-Curated-2025 -> External Benchmark 3,External Benchmark 1 -> GenPept-Curated-2025,External Benchmark 1 -> AMPlify-balanced,External Benchmark 1 -> External Benchmark 3,AMPlify-balanced -> GenPept-Curated-2025,AMPlify-balanced -> External Benchmark 1,AMPlify-balanced -> External Benchmark 3,External Benchmark 3 -> GenPept-Curated-2025,External Benchmark 3 -> External Benchmark 1,External Benchmark 3 -> AMPlify-balanced
0,Logistic Regression,0.589 +/- 0.000,0.573 +/- 0.000,0.542 +/- 0.000,0.362 +/- 0.000,0.637 +/- 0.000,0.690 +/- 0.000,0.505 +/- 0.000,0.306 +/- 0.000,0.541 +/- 0.000,0.600 +/- 0.000,0.740 +/- 0.000,0.661 +/- 0.000
1,Linear SVM (calibrated),0.592 +/- 0.004,0.581 +/- 0.004,0.544 +/- 0.005,0.331 +/- 0.068,0.642 +/- 0.014,0.689 +/- 0.012,0.477 +/- 0.019,0.287 +/- 0.019,0.520 +/- 0.015,0.569 +/- 0.018,0.741 +/- 0.003,0.659 +/- 0.002
2,Random Forest,0.367 +/- 0.045,0.124 +/- 0.047,0.378 +/- 0.030,0.139 +/- 0.013,0.658 +/- 0.011,0.745 +/- 0.010,0.178 +/- 0.039,0.387 +/- 0.027,0.646 +/- 0.022,0.300 +/- 0.054,0.773 +/- 0.006,0.758 +/- 0.005
3,Extra Trees,0.422 +/- 0.069,0.188 +/- 0.086,0.399 +/- 0.036,0.119 +/- 0.020,0.674 +/- 0.014,0.748 +/- 0.008,0.086 +/- 0.039,0.325 +/- 0.046,0.603 +/- 0.040,0.262 +/- 0.061,0.775 +/- 0.006,0.771 +/- 0.005
4,HistGradientBoosting,0.516 +/- 0.000,0.297 +/- 0.000,0.485 +/- 0.000,0.269 +/- 0.000,0.667 +/- 0.000,0.721 +/- 0.000,0.337 +/- 0.000,0.455 +/- 0.000,0.668 +/- 0.000,0.481 +/- 0.000,0.777 +/- 0.000,0.757 +/- 0.000
5,LightGBM,0.554 +/- 0.032,0.362 +/- 0.040,0.517 +/- 0.028,0.335 +/- 0.056,0.643 +/- 0.010,0.738 +/- 0.010,0.232 +/- 0.044,0.407 +/- 0.025,0.647 +/- 0.022,0.481 +/- 0.066,0.786 +/- 0.006,0.760 +/- 0.003
6,CNN1D,0.584 +/- 0.053,0.475 +/- 0.059,0.503 +/- 0.034,0.216 +/- 0.058,0.683 +/- 0.026,0.741 +/- 0.014,0.138 +/- 0.080,0.371 +/- 0.026,0.573 +/- 0.025,0.567 +/- 0.067,0.768 +/- 0.006,0.701 +/- 0.016
7,BiLSTM,0.604 +/- 0.042,0.477 +/- 0.067,0.559 +/- 0.029,0.354 +/- 0.103,0.686 +/- 0.022,0.736 +/- 0.030,0.102 +/- 0.048,0.373 +/- 0.016,0.567 +/- 0.019,0.677 +/- 0.017,0.752 +/- 0.005,0.674 +/- 0.011
8,BiLSTM + Attention,0.637 +/- 0.037,0.530 +/- 0.051,0.578 +/- 0.041,0.214 +/- 0.057,0.669 +/- 0.017,0.731 +/- 0.027,0.075 +/- 0.048,0.351 +/- 0.033,0.560 +/- 0.016,0.689 +/- 0.024,0.743 +/- 0.007,0.678 +/- 0.011
9,Transformer Encoder,0.572 +/- 0.064,0.436 +/- 0.111,0.563 +/- 0.044,0.478 +/- 0.079,0.630 +/- 0.018,0.703 +/- 0.012,0.173 +/- 0.104,0.364 +/- 0.016,0.553 +/- 0.011,0.691 +/- 0.035,0.722 +/- 0.013,0.672 +/- 0.023
10,AmPEP,0.465 +/- 0.031,0.264 +/- 0.056,0.433 +/- 0.023,0.592 +/- 0.031,0.632 +/- 0.030,0.644 +/- 0.015,0.180 +/- 0.069,0.374 +/- 0.015,0.495 +/- 0.012,0.712 +/- 0.004,0.659 +/- 0.020,0.657 +/- 0.012
11,AMPScannerV2,0.604 +/- 0.048,0.443 +/- 0.080,0.525 +/- 0.036,0.188 +/- 0.063,0.701 +/- 0.022,0.719 +/- 0.029,0.218 +/- 0.069,0.349 +/- 0.016,0.584 +/- 0.019,0.590 +/- 0.071,0.775 +/- 0.008,0.760 +/- 0.011
12,amPEPpy,0.501 +/- 0.041,0.315 +/- 0.066,0.452 +/- 0.028,0.593 +/- 0.030,0.626 +/- 0.027,0.642 +/- 0.023,0.146 +/- 0.076,0.377 +/- 0.018,0.492 +/- 0.016,0.708 +/- 0.002,0.671 +/- 0.014,0.666 +/- 0.005

================================================================================================================================================================
CELL 35 MATRIX - P2_F1_mean_13x12.csv
================================================================================================================================================================
Rows: 13 | Columns: 13

,Unnamed: 0,GenPept-Curated-2025 -> External Benchmark 1,GenPept-Curated-2025 -> AMPlify-balanced,GenPept-Curated-2025 -> External Benchmark 3,External Benchmark 1 -> GenPept-Curated-2025,External Benchmark 1 -> AMPlify-balanced,External Benchmark 1 -> External Benchmark 3,AMPlify-balanced -> GenPept-Curated-2025,AMPlify-balanced -> External Benchmark 1,AMPlify-balanced -> External Benchmark 3,External Benchmark 3 -> GenPept-Curated-2025,External Benchmark 3 -> External Benchmark 1,External Benchmark 3 -> AMPlify-balanced
0,Logistic Regression,0.588661,0.573350,0.542075,0.362110,0.637066,0.690201,0.505197,0.306483,0.540505,0.599918,0.739628,0.660793
1,Linear SVM (calibrated),0.591794,0.581117,0.544278,0.330539,0.641564,0.689238,0.476671,0.287352,0.520235,0.569427,0.741069,0.658918
2,Random Forest,0.366816,0.124316,0.377717,0.138509,0.658346,0.745448,0.177816,0.387358,0.646076,0.299996,0.772642,0.758334
3,Extra Trees,0.421601,0.188347,0.398884,0.118719,0.673911,0.747606,0.085738,0.325374,0.602712,0.262367,0.774751,0.771035
4,HistGradientBoosting,0.516497,0.297153,0.485340,0.268759,0.667377,0.720637,0.336815,0.455342,0.668377,0.481418,0.777439,0.756640
5,LightGBM,0.554265,0.362056,0.517221,0.334526,0.642960,0.738447,0.231549,0.406881,0.647486,0.480842,0.785967,0.759687
6,CNN1D,0.583590,0.475060,0.502589,0.216047,0.683139,0.740967,0.137882,0.370800,0.573016,0.566712,0.767693,0.700507
7,BiLSTM,0.604034,0.477368,0.559034,0.353864,0.685637,0.736096,0.102261,0.372718,0.566968,0.677140,0.752179,0.673748
8,BiLSTM + Attention,0.637107,0.530116,0.577621,0.214168,0.668908,0.730845,0.074901,0.351296,0.560033,0.689148,0.742632,0.677584
9,Transformer Encoder,0.572300,0.436293,0.562730,0.478090,0.629740,0.702985,0.172988,0.364077,0.552585,0.691014,0.721722,0.671926
10,AmPEP,0.464563,0.263674,0.433359,0.592068,0.631759,0.643583,0.179800,0.374181,0.495177,0.711638,0.659131,0.656844
11,AMPScannerV2,0.603952,0.442959,0.524775,0.187758,0.701158,0.719075,0.218212,0.348761,0.583855,0.590257,0.774625,0.759983
12,amPEPpy,0.500772,0.314899,0.452031,0.593438,0.626381,0.641779,0.146132,0.377254,0.492477,0.708496,0.670986,0.666054

================================================================================================================================================================
CELL 35 MATRIX - P2_MCC_meanSD_13x12.csv
================================================================================================================================================================
Rows: 13 | Columns: 13

,Unnamed: 0,GenPept-Curated-2025 -> External Benchmark 1,GenPept-Curated-2025 -> AMPlify-balanced,GenPept-Curated-2025 -> External Benchmark 3,External Benchmark 1 -> GenPept-Curated-2025,External Benchmark 1 -> AMPlify-balanced,External Benchmark 1 -> External Benchmark 3,AMPlify-balanced -> GenPept-Curated-2025,AMPlify-balanced -> External Benchmark 1,AMPlify-balanced -> External Benchmark 3,External Benchmark 3 -> GenPept-Curated-2025,External Benchmark 3 -> External Benchmark 1,External Benchmark 3 -> AMPlify-balanced
0,Logistic Regression,0.106 +/- 0.000,0.119 +/- 0.000,0.137 +/- 0.000,0.079 +/- 0.000,0.444 +/- 0.000,0.456 +/- 0.000,0.046 +/- 0.000,0.074 +/- 0.000,0.255 +/- 0.000,0.154 +/- 0.000,0.451 +/- 0.000,0.327 +/- 0.000
1,Linear SVM (calibrated),0.104 +/- 0.006,0.130 +/- 0.005,0.140 +/- 0.005,0.067 +/- 0.029,0.450 +/- 0.023,0.465 +/- 0.005,0.040 +/- 0.005,0.108 +/- 0.011,0.270 +/- 0.003,0.151 +/- 0.010,0.467 +/- 0.006,0.325 +/- 0.006
2,Random Forest,-0.176 +/- 0.025,-0.101 +/- 0.013,0.109 +/- 0.009,-0.008 +/- 0.011,0.476 +/- 0.018,0.591 +/- 0.007,0.101 +/- 0.009,0.222 +/- 0.010,0.491 +/- 0.006,0.090 +/- 0.013,0.559 +/- 0.011,0.553 +/- 0.010
3,Extra Trees,-0.146 +/- 0.032,-0.085 +/- 0.018,0.093 +/- 0.025,-0.013 +/- 0.013,0.503 +/- 0.022,0.599 +/- 0.010,0.041 +/- 0.014,0.236 +/- 0.015,0.494 +/- 0.016,0.076 +/- 0.008,0.567 +/- 0.011,0.579 +/- 0.010
4,HistGradientBoosting,0.016 +/- 0.000,-0.005 +/- 0.000,0.206 +/- 0.000,0.084 +/- 0.000,0.491 +/- 0.000,0.553 +/- 0.000,0.152 +/- 0.000,0.228 +/- 0.000,0.448 +/- 0.000,0.239 +/- 0.000,0.559 +/- 0.000,0.549 +/- 0.000
5,LightGBM,0.039 +/- 0.014,0.031 +/- 0.015,0.214 +/- 0.011,0.053 +/- 0.010,0.452 +/- 0.016,0.559 +/- 0.010,0.109 +/- 0.012,0.221 +/- 0.011,0.463 +/- 0.007,0.238 +/- 0.023,0.573 +/- 0.010,0.556 +/- 0.006
6,CNN1D,0.034 +/- 0.044,0.074 +/- 0.030,0.118 +/- 0.025,0.074 +/- 0.026,0.517 +/- 0.042,0.584 +/- 0.027,0.032 +/- 0.041,0.104 +/- 0.026,0.238 +/- 0.036,0.151 +/- 0.038,0.513 +/- 0.024,0.425 +/- 0.039
7,BiLSTM,0.054 +/- 0.040,0.103 +/- 0.036,0.207 +/- 0.020,0.095 +/- 0.034,0.522 +/- 0.034,0.543 +/- 0.039,-0.009 +/- 0.038,0.092 +/- 0.019,0.219 +/- 0.035,0.205 +/- 0.038,0.453 +/- 0.016,0.361 +/- 0.028
8,BiLSTM + Attention,0.077 +/- 0.040,0.146 +/- 0.039,0.199 +/- 0.032,0.092 +/- 0.033,0.493 +/- 0.028,0.566 +/- 0.027,-0.024 +/- 0.032,0.082 +/- 0.023,0.221 +/- 0.020,0.251 +/- 0.058,0.437 +/- 0.020,0.370 +/- 0.029
9,Transformer Encoder,0.042 +/- 0.060,0.075 +/- 0.083,0.244 +/- 0.034,0.088 +/- 0.046,0.427 +/- 0.032,0.510 +/- 0.024,-0.015 +/- 0.059,0.090 +/- 0.022,0.189 +/- 0.040,0.307 +/- 0.051,0.399 +/- 0.021,0.364 +/- 0.053
10,AmPEP,-0.101 +/- 0.025,-0.037 +/- 0.042,0.118 +/- 0.014,0.107 +/- 0.024,0.428 +/- 0.054,0.394 +/- 0.021,0.042 +/- 0.032,0.087 +/- 0.011,0.088 +/- 0.019,0.314 +/- 0.015,0.275 +/- 0.024,0.351 +/- 0.016
11,AMPScannerV2,0.033 +/- 0.049,0.027 +/- 0.046,0.136 +/- 0.017,0.041 +/- 0.033,0.547 +/- 0.034,0.561 +/- 0.025,0.043 +/- 0.050,0.134 +/- 0.023,0.332 +/- 0.036,0.169 +/- 0.038,0.534 +/- 0.022,0.556 +/- 0.021
12,amPEPpy,-0.077 +/- 0.030,-0.011 +/- 0.043,0.107 +/- 0.004,0.098 +/- 0.014,0.419 +/- 0.048,0.386 +/- 0.020,0.047 +/- 0.042,0.097 +/- 0.017,0.095 +/- 0.013,0.303 +/- 0.008,0.290 +/- 0.018,0.362 +/- 0.010

================================================================================================================================================================
CELL 35 MATRIX - P2_MCC_mean_13x12.csv
================================================================================================================================================================
Rows: 13 | Columns: 13

,Unnamed: 0,GenPept-Curated-2025 -> External Benchmark 1,GenPept-Curated-2025 -> AMPlify-balanced,GenPept-Curated-2025 -> External Benchmark 3,External Benchmark 1 -> GenPept-Curated-2025,External Benchmark 1 -> AMPlify-balanced,External Benchmark 1 -> External Benchmark 3,AMPlify-balanced -> GenPept-Curated-2025,AMPlify-balanced -> External Benchmark 1,AMPlify-balanced -> External Benchmark 3,External Benchmark 3 -> GenPept-Curated-2025,External Benchmark 3 -> External Benchmark 1,External Benchmark 3 -> AMPlify-balanced
0,Logistic Regression,0.106073,0.118613,0.137262,0.079375,0.444077,0.456228,0.045773,0.073780,0.255273,0.154049,0.451130,0.327237
1,Linear SVM (calibrated),0.103551,0.130388,0.139600,0.066514,0.450013,0.465297,0.039736,0.108138,0.270212,0.151062,0.467371,0.325269
2,Random Forest,-0.176494,-0.101393,0.109225,-0.007818,0.475655,0.591191,0.100915,0.222419,0.490946,0.089774,0.559192,0.553296
3,Extra Trees,-0.145921,-0.085222,0.092502,-0.013252,0.502940,0.599458,0.041034,0.235991,0.494254,0.076228,0.567047,0.578910
4,HistGradientBoosting,0.015871,-0.004603,0.206269,0.083788,0.490617,0.553313,0.152030,0.227562,0.448062,0.239122,0.558577,0.548673
5,LightGBM,0.039313,0.031143,0.213756,0.053440,0.451522,0.558627,0.108781,0.220887,0.463497,0.238257,0.572788,0.555573
6,CNN1D,0.033903,0.073680,0.118009,0.073680,0.517445,0.584450,0.032062,0.104286,0.237794,0.151054,0.513155,0.425390
7,BiLSTM,0.054451,0.103099,0.206907,0.095477,0.521912,0.542759,-0.009157,0.091982,0.219493,0.204661,0.452635,0.360555
8,BiLSTM + Attention,0.077452,0.146121,0.198625,0.092419,0.492639,0.565982,-0.023509,0.081767,0.220557,0.250967,0.436821,0.369889
9,Transformer Encoder,0.041628,0.074803,0.243589,0.087618,0.426921,0.509530,-0.014684,0.089863,0.188561,0.306896,0.399087,0.363501
10,AmPEP,-0.101339,-0.036528,0.117911,0.106601,0.427848,0.393544,0.042187,0.086805,0.088269,0.314239,0.274910,0.351496
11,AMPScannerV2,0.033204,0.027262,0.135503,0.041183,0.546766,0.561442,0.043307,0.133893,0.332054,0.168836,0.534277,0.556081
12,amPEPpy,-0.077428,-0.010608,0.107236,0.098026,0.419118,0.386248,0.047047,0.096790,0.094550,0.302984,0.289916,0.361620

CELL 35 FIGURES:
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P1_AUPRC_heatmap_13x4.pdf
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P1_AUPRC_heatmap_13x4.png
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P1_AUROC_heatmap_13x4.pdf
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P1_AUROC_heatmap_13x4.png
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P1_vs_P2_AUPRC_macro_13models.pdf
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P1_vs_P2_AUPRC_macro_13models.png
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P1_vs_P2_AUROC_macro_13models.pdf
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P1_vs_P2_AUROC_macro_13models.png
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P2_AUPRC_heatmap_13x12.pdf
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P2_AUPRC_heatmap_13x12.png
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P2_AUROC_heatmap_13x12.pdf
 - /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell35_paper_ready/figures/Figure_P2_AUROC_heatmap_13x12.png

================================================================================================================================================================
CELL 36 TABLE - Table_A_exact_model_configuration_13.csv
================================================================================================================================================================
Rows: 13 | Columns: 14

,Model,model_id,Input representation,Trainable parameters / estimator size,"Checkpoint size MB (mean +/- SD, 40 runs)",Optimizer / learning algorithm,Learning rate,Batch size,Max epochs / iterations,Early stopping,Hyperparameter selection,Training device actually recorded,Architecture / key fixed estimator settings,Configuration provenance
0,Logistic Regression,logistic_regression,Length_AAC20_DPC400_v1 (421D: Length_norm + AA...,Not defined as neural trainable-parameter count,0.012 +/- 0.000,Not applicable (classical estimator),Not applicable,Not applicable (non-mini-batch fit),Not epoch-based,Not applicable,Hyperparameters pre-locked before training; no...,cpu,"{""estimator"":{""C"":1.0,""class"":""sklearn.linear_...",benchmark17_FINAL_controlled_model_contract.json
1,Calibrated Linear SVM,linear_svm_calibrated,Length_AAC20_DPC400_v1 (421D: Length_norm + AA...,Not defined as neural trainable-parameter count,0.028 +/- 0.000,Not applicable (classical estimator),Not applicable,Not applicable (non-mini-batch fit),Not epoch-based,Not applicable,Hyperparameters pre-locked before training; no...,cpu,"{""base_estimator"":{""C"":1.0,""class"":""sklearn.sv...",benchmark17_FINAL_controlled_model_contract.json
2,Random Forest,random_forest,Length_AAC20_DPC400_v1 (421D: Length_norm + AA...,Not defined as neural trainable-parameter count,65.227 +/- 20.537,Not applicable (classical estimator),Not applicable,Not applicable (non-mini-batch fit),Not epoch-based,Not applicable,Hyperparameters pre-locked before training; no...,cpu,"{""estimator"":{""bootstrap"":true,""class"":""sklear...",benchmark17_FINAL_controlled_model_contract.json
3,Extra Trees,extra_trees,Length_AAC20_DPC400_v1 (421D: Length_norm + AA...,Not defined as neural trainable-parameter count,140.627 +/- 43.763,Not applicable (classical estimator),Not applicable,Not applicable (non-mini-batch fit),Not epoch-based,Not applicable,Hyperparameters pre-locked before training; no...,cpu,"{""estimator"":{""bootstrap"":false,""class"":""sklea...",benchmark17_FINAL_controlled_model_contract.json
4,HistGradientBoosting,hist_gradient_boosting,Length_AAC20_DPC400_v1 (421D: Length_norm + AA...,Not defined as neural trainable-parameter count,1.406 +/- 0.069,Not applicable (classical estimator),0.05,Not applicable (non-mini-batch fit),Not epoch-based,Disabled in locked config,Hyperparameters pre-locked before training; no...,cpu,"{""estimator"":{""class"":""sklearn.ensemble.HistGr...",benchmark17_FINAL_controlled_model_contract.json
5,LightGBM,lightgbm,Length_AAC20_DPC400_v1 (421D: Length_norm + AA...,Not defined as neural trainable-parameter count,1.698 +/- 0.004,Not applicable (classical estimator),0.05,Not applicable (non-mini-batch fit),Not epoch-based,Not applicable,Hyperparameters pre-locked before training; no...,cpu,"{""estimator"":{""class"":""lightgbm.LGBMClassifier...",benchmark17_FINAL_controlled_model_contract.json
6,CNN1D,cnn1d,AA20_integer_tokens_L200_v1 (raw peptide; max ...,100033,1.180 +/- 0.000,Adam,0.001,64,80,"Yes: val_loss, patience=8, min_delta=0.0, rest...",Architecture/training hyperparameters pre-lock...,gpu_tensorflow_locked_cell2_subprocess,"{""conv1_activation"":""relu"",""conv1_filters"":128...",benchmark17_FINAL_controlled_model_contract.js...
7,BiLSTM,bilstm,AA20_integer_tokens_L200_v1 (raw peptide; max ...,75713,0.906 +/- 0.000,Adam,0.001,64,80,"Yes: val_loss, patience=8, min_delta=0.0, rest...",Architecture/training hyperparameters pre-lock...,gpu_tensorflow_locked_cell2_subprocess,"{""bilstm_units_per_direction"":64,""dense_activa...",benchmark17_FINAL_controlled_model_contract.js...
8,BiLSTM-Attention,bilstm_attention,AA20_integer_tokens_L200_v1 (raw peptide; max ...,84033,1.012 +/- 0.000,Adam,0.001,64,80,"Yes: val_loss, patience=8, min_delta=0.0, rest...",Architecture/training hyperparameters pre-lock...,gpu_tensorflow_locked_cell2_subprocess,"{""attention_type"":""trainable_masked_additive_a...",benchmark17_FINAL_controlled_model_contract.js...
9,Transformer Encoder,transformer_encoder,AA20_integer_tokens_L200_v1 (raw peptide; max ...,85313,1.091 +/- 0.000,Adam,0.001,64,80,"Yes: val_loss, patience=8, min_delta=0.0, rest...",Architecture/training hyperparameters pre-lock...,gpu_tensorflow_locked_cell2_subprocess,"{""attention_dropout"":0.1,""dense_activation"":""r...",benchmark17_FINAL_controlled_model_contract.js...
10,AmPEP,ampep,105D Seq2Distribution descriptors used by the ...,Not defined as neural trainable-parameter count,10.546 +/- 3.294,Not applicable (Random Forest),Not applicable,Not applicable,Not epoch-based,Not applicable (non-iterative estimator),Published recipe fixed before benchmark; no te...,method_specific,"RandomForestClassifier(n_estimators=100, max_f...",Cell32 v9 exact production wrapper + locked pu...
11,AMPScannerV2,ampscannerv2,Integer amino-acid encoding padded to length 2...,Not recorded as count_params by locked TF1 pro...,2.315 +/- 0.000,adam,Not explicitly set in locked implementation co...,32,10,No benchmark-added early stopping; official fi...,Official source architecture/training recipe l...,method_specific,"Embedding(21,128) -> Conv1D(64,k=16) -> MaxPool(...",benchmark17_ampscannerv2_FINAL_implementation_...
12,amPEPpy,ampeppy,Official amPEPpy v1.0 feature pipeline (CTD/di...,Not defined as neural trainable-parameter count,15.586 +/- 4.854,Not applicable (Random Forest),Not applicable,Not applicable,Not epoch-based,Not applicable (non-iterative estimator),Official source retraining recipe locked; no t...,method_specific,Official amPEPpy v1.0 Random Forest; num_trees...,benchmark17_ampeppy_FINAL_implementation_contr...

================================================================================================================================================================
CELL 36 TABLE - Table_B_training_and_evaluation_efficiency_13.csv
================================================================================================================================================================
Rows: 13 | Columns: 17

,Model,model_id,Runs,"Training time/run (s, mean +/- SD)",Epochs completed (mean +/- SD),"Training time/epoch (s, mean +/- SD)","Training throughput (seq/s, mean +/- SD)","Final evaluation time / checkpoint for all 4 targets (s, mean +/- SD)","Evaluation latency (ms/sequence, mean +/- SD)","Evaluation throughput (seq/s, mean +/- SD)","Peak process RAM (MB, mean +/- SD)","Peak GPU VRAM (MB, mean +/- SD)","Checkpoint size (MB, mean +/- SD)",Exact neural parameter count,Training device,Evaluation device,Evaluation timing basis
0,Logistic Regression,logistic_regression,40,1.57 +/- 0.28,Not epoch-based,Not epoch-based,4661.65 +/- 1543.86,0.01 +/- 0.01,0.002 +/- 0.001,728879.56 +/- 255793.04,1194.5 +/- 31.5,CPU / not recorded by route,0.012 +/- 0.000,Not recorded / not applicable,cpu,cpu,one checkpoint load + sum preprocessing + mode...
1,Calibrated Linear SVM,linear_svm_calibrated,40,2.42 +/- 1.08,Not epoch-based,Not epoch-based,3243.25 +/- 802.75,0.03 +/- 0.01,0.004 +/- 0.001,253237.17 +/- 47022.57,1287.3 +/- 6.8,CPU / not recorded by route,0.028 +/- 0.000,Not recorded / not applicable,cpu,cpu,one checkpoint load + sum preprocessing + mode...
2,Random Forest,random_forest,40,1.09 +/- 0.30,Not epoch-based,Not epoch-based,6587.52 +/- 714.51,0.63 +/- 0.04,0.090 +/- 0.007,11190.44 +/- 947.36,1396.2 +/- 47.1,CPU / not recorded by route,65.227 +/- 20.537,Not recorded / not applicable,cpu,cpu,one checkpoint load + sum preprocessing + mode...
3,Extra Trees,extra_trees,40,0.89 +/- 0.21,Not epoch-based,Not epoch-based,7992.38 +/- 733.95,0.87 +/- 0.20,0.124 +/- 0.028,8467.74 +/- 1966.09,1594.6 +/- 48.9,CPU / not recorded by route,140.627 +/- 43.763,Not recorded / not applicable,cpu,cpu,one checkpoint load + sum preprocessing + mode...
4,HistGradientBoosting,hist_gradient_boosting,40,2.27 +/- 0.25,Not epoch-based,Not epoch-based,3077.14 +/- 499.11,0.04 +/- 0.00,0.006 +/- 0.001,173911.12 +/- 17822.27,1754.6 +/- 2.1,CPU / not recorded by route,1.406 +/- 0.069,Not recorded / not applicable,cpu,cpu,one checkpoint load + sum preprocessing + mode...
5,LightGBM,lightgbm,40,1.29 +/- 0.61,Not epoch-based,Not epoch-based,6260.74 +/- 2216.84,0.04 +/- 0.01,0.006 +/- 0.002,169990.31 +/- 41481.15,1757.1 +/- 0.0,CPU / not recorded by route,1.698 +/- 0.004,Not recorded / not applicable,cpu,cpu,one checkpoint load + sum preprocessing + mode...
6,CNN1D,cnn1d,40,18.39 +/- 4.02,14.15 +/- 1.85,1.314 +/- 0.307,385.00 +/- 48.27,7.15 +/- 0.85,1.015 +/- 0.128,999.65 +/- 116.20,1757.1 +/- 0.0,142.3 +/- 0.1,1.180 +/- 0.000,100033,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess,one checkpoint load + all 4 targets; combined ...
7,BiLSTM,bilstm,40,62.39 +/- 28.47,25.80 +/- 8.63,2.378 +/- 0.587,128.89 +/- 41.42,4.05 +/- 0.16,0.575 +/- 0.031,1745.26 +/- 89.71,1757.1 +/- 0.0,174.5 +/- 46.6,0.906 +/- 0.000,75713,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess,one checkpoint load + all 4 targets; combined ...
8,BiLSTM-Attention,bilstm_attention,40,86.28 +/- 38.15,31.00 +/- 9.97,2.745 +/- 0.704,94.48 +/- 38.63,4.55 +/- 0.21,0.646 +/- 0.031,1551.90 +/- 70.90,1757.1 +/- 0.0,176.5 +/- 48.1,1.012 +/- 0.000,84033,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess,one checkpoint load + all 4 targets; combined ...
9,Transformer Encoder,transformer_encoder,40,71.57 +/- 40.26,13.25 +/- 2.70,5.466 +/- 3.075,116.73 +/- 37.30,19.97 +/- 2.01,2.839 +/- 0.343,357.17 +/- 42.15,1757.1 +/- 0.0,597.7 +/- 1.5,1.091 +/- 0.000,85313,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess,one checkpoint load + all 4 targets; combined ...
10,AmPEP,ampep,40,2.78 +/- 0.91,Not epoch-based,Not epoch-based,2624.65 +/- 321.88,0.14 +/- 0.09,0.019 +/- 0.013,62952.74 +/- 18456.26,1757.1 +/- 0.0,CPU / not recorded by route,10.546 +/- 3.294,Not recorded / not applicable,method_specific,cpu,one checkpoint load + sum preprocessing + mode...
11,AMPScannerV2,ampscannerv2,40,501.22 +/- 138.79,10.00 +/- 0.00,50.122 +/- 13.879,14.25 +/- 1.32,14.58 +/- 0.51,2.066 +/- 0.023,483.97 +/- 5.34,1757.1 +/- 0.0,CPU / not recorded by route,2.315 +/- 0.000,Not recorded / not applicable,method_specific,legacy_cpu_exact_environment,one checkpoint load + all 4 targets; combined ...
12,amPEPpy,ampeppy,40,11.30 +/- 3.38,Not epoch-based,Not epoch-based,636.40 +/- 60.00,29.72 +/- 1.17,4.212 +/- 0.028,237.45 +/- 1.59,1757.1 +/- 0.0,CPU / not recorded by route,15.586 +/- 4.854,Not recorded / not applicable,method_specific,legacy_cpu_exact_environment,one checkpoint load + all 4 targets; combined ...

================================================================================================================================================================
CELL 36 TABLE - Table_C_runtime_by_model_and_source_dataset_52.csv
================================================================================================================================================================
Rows: 52 | Columns: 13

,Model,model_id,Source dataset,Seeds,n_runs,"Training time/run (s, mean +/- SD)","Training time/epoch (s, mean +/- SD)","Evaluation all 4 targets/checkpoint (s, mean +/- SD)","Evaluation latency (ms/sequence, mean +/- SD)","Peak process RAM (MB, mean +/- SD)","Peak GPU VRAM (MB, mean +/- SD)",Training device,Evaluation device
0,Logistic Regression,logistic_regression,GenPept_Curated_2025,100-109,10,1.99 +/- 0.07,Not epoch-based,0.02 +/- 0.02,0.002 +/- 0.003,1164.6 +/- 1.7,CPU / not recorded by route,cpu,cpu
1,Logistic Regression,logistic_regression,External_Benchmark_1,100-109,10,1.34 +/- 0.10,Not epoch-based,0.01 +/- 0.00,0.001 +/- 0.000,1178.6 +/- 0.0,CPU / not recorded by route,cpu,cpu
2,Logistic Regression,logistic_regression,AMPlify_balanced,100-109,10,1.59 +/- 0.07,Not epoch-based,0.01 +/- 0.00,0.002 +/- 0.001,1188.4 +/- 0.0,CPU / not recorded by route,cpu,cpu
3,Logistic Regression,logistic_regression,External_Benchmark_3,100-109,10,1.34 +/- 0.07,Not epoch-based,0.01 +/- 0.00,0.002 +/- 0.000,1246.3 +/- 0.0,CPU / not recorded by route,cpu,cpu
4,Calibrated Linear SVM,linear_svm_calibrated,GenPept_Curated_2025,100-109,10,3.93 +/- 0.26,Not epoch-based,0.03 +/- 0.00,0.004 +/- 0.001,1283.5 +/- 0.0,CPU / not recorded by route,cpu,cpu
5,Calibrated Linear SVM,linear_svm_calibrated,External_Benchmark_1,100-109,10,1.52 +/- 0.06,Not epoch-based,0.03 +/- 0.00,0.004 +/- 0.000,1283.5 +/- 0.0,CPU / not recorded by route,cpu,cpu
6,Calibrated Linear SVM,linear_svm_calibrated,AMPlify_balanced,100-109,10,1.35 +/- 0.04,Not epoch-based,0.03 +/- 0.01,0.004 +/- 0.002,1283.5 +/- 0.0,CPU / not recorded by route,cpu,cpu
7,Calibrated Linear SVM,linear_svm_calibrated,External_Benchmark_3,100-109,10,2.89 +/- 0.12,Not epoch-based,0.03 +/- 0.01,0.004 +/- 0.001,1298.9 +/- 0.7,CPU / not recorded by route,cpu,cpu
8,Random Forest,random_forest,GenPept_Curated_2025,100-109,10,1.39 +/- 0.08,Not epoch-based,0.62 +/- 0.06,0.083 +/- 0.008,1348.4 +/- 15.7,CPU / not recorded by route,cpu,cpu
9,Random Forest,random_forest,External_Benchmark_1,100-109,10,0.85 +/- 0.03,Not epoch-based,0.63 +/- 0.01,0.091 +/- 0.001,1373.7 +/- 7.9,CPU / not recorded by route,cpu,cpu
10,Random Forest,random_forest,AMPlify_balanced,100-109,10,0.76 +/- 0.02,Not epoch-based,0.62 +/- 0.01,0.092 +/- 0.001,1396.5 +/- 3.8,CPU / not recorded by route,cpu,cpu
11,Random Forest,random_forest,External_Benchmark_3,100-109,10,1.37 +/- 0.04,Not epoch-based,0.66 +/- 0.05,0.093 +/- 0.007,1466.2 +/- 27.6,CPU / not recorded by route,cpu,cpu
12,Extra Trees,extra_trees,GenPept_Curated_2025,100-109,10,0.84 +/- 0.03,Not epoch-based,0.77 +/- 0.13,0.103 +/- 0.018,1552.4 +/- 22.4,CPU / not recorded by route,cpu,cpu
13,Extra Trees,extra_trees,External_Benchmark_1,100-109,10,0.74 +/- 0.02,Not epoch-based,0.78 +/- 0.06,0.114 +/- 0.008,1573.0 +/- 2.0,CPU / not recorded by route,cpu,cpu
14,Extra Trees,extra_trees,AMPlify_balanced,100-109,10,0.72 +/- 0.03,Not epoch-based,0.78 +/- 0.09,0.116 +/- 0.013,1583.3 +/- 4.2,CPU / not recorded by route,cpu,cpu
15,Extra Trees,extra_trees,External_Benchmark_3,100-109,10,1.24 +/- 0.05,Not epoch-based,1.15 +/- 0.15,0.162 +/- 0.022,1669.7 +/- 30.8,CPU / not recorded by route,cpu,cpu
16,HistGradientBoosting,hist_gradient_boosting,GenPept_Curated_2025,100-109,10,2.55 +/- 0.05,Not epoch-based,0.04 +/- 0.01,0.005 +/- 0.001,1752.5 +/- 2.5,CPU / not recorded by route,cpu,cpu
17,HistGradientBoosting,hist_gradient_boosting,External_Benchmark_1,100-109,10,2.03 +/- 0.01,Not epoch-based,0.04 +/- 0.00,0.006 +/- 0.000,1754.4 +/- 0.0,CPU / not recorded by route,cpu,cpu
18,HistGradientBoosting,hist_gradient_boosting,AMPlify_balanced,100-109,10,2.03 +/- 0.03,Not epoch-based,0.04 +/- 0.00,0.006 +/- 0.000,1754.4 +/- 0.0,CPU / not recorded by route,cpu,cpu
19,HistGradientBoosting,hist_gradient_boosting,External_Benchmark_3,100-109,10,2.49 +/- 0.02,Not epoch-based,0.04 +/- 0.00,0.006 +/- 0.000,1757.1 +/- 0.0,CPU / not recorded by route,cpu,cpu
20,LightGBM,lightgbm,GenPept_Curated_2025,100-109,10,2.31 +/- 0.06,Not epoch-based,0.04 +/- 0.00,0.005 +/- 0.001,1757.1 +/- 0.0,CPU / not recorded by route,cpu,cpu
21,LightGBM,lightgbm,External_Benchmark_1,100-109,10,0.99 +/- 0.03,Not epoch-based,0.06 +/- 0.02,0.008 +/- 0.002,1757.1 +/- 0.0,CPU / not recorded by route,cpu,cpu
22,LightGBM,lightgbm,AMPlify_balanced,100-109,10,0.80 +/- 0.02,Not epoch-based,0.04 +/- 0.01,0.007 +/- 0.002,1757.1 +/- 0.0,CPU / not recorded by route,cpu,cpu
23,LightGBM,lightgbm,External_Benchmark_3,100-109,10,1.04 +/- 0.03,Not epoch-based,0.04 +/- 0.01,0.006 +/- 0.002,1757.1 +/- 0.0,CPU / not recorded by route,cpu,cpu
24,CNN1D,cnn1d,GenPept_Curated_2025,100-109,10,18.28 +/- 2.08,1.311 +/- 0.063,7.07 +/- 1.18,0.944 +/- 0.158,1757.1 +/- 0.0,142.3 +/- 0.1,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
25,CNN1D,cnn1d,External_Benchmark_1,100-109,10,15.12 +/- 1.89,1.106 +/- 0.030,7.08 +/- 0.52,1.027 +/- 0.075,1757.1 +/- 0.0,142.3 +/- 0.0,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
26,CNN1D,cnn1d,AMPlify_balanced,100-109,10,16.00 +/- 1.41,1.034 +/- 0.026,7.25 +/- 0.79,1.073 +/- 0.117,1757.1 +/- 0.0,142.3 +/- 0.0,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
27,CNN1D,cnn1d,External_Benchmark_3,100-109,10,24.14 +/- 2.24,1.804 +/- 0.035,7.19 +/- 0.92,1.014 +/- 0.129,1757.1 +/- 0.0,142.3 +/- 0.1,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
28,BiLSTM,bilstm,GenPept_Curated_2025,100-109,10,97.94 +/- 23.38,2.913 +/- 0.046,4.10 +/- 0.17,0.548 +/- 0.023,1757.1 +/- 0.0,237.0 +/- 11.0,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
29,BiLSTM,bilstm,External_Benchmark_1,100-109,10,36.32 +/- 16.86,1.913 +/- 0.123,4.09 +/- 0.21,0.593 +/- 0.030,1757.1 +/- 0.0,198.1 +/- 8.7,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
30,BiLSTM,bilstm,AMPlify_balanced,100-109,10,46.10 +/- 7.14,1.705 +/- 0.048,4.04 +/- 0.17,0.598 +/- 0.025,1757.1 +/- 0.0,128.6 +/- 9.1,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
31,BiLSTM,bilstm,External_Benchmark_3,100-109,10,69.20 +/- 11.08,2.982 +/- 0.084,3.96 +/- 0.04,0.559 +/- 0.005,1757.1 +/- 0.0,134.4 +/- 6.3,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
32,BiLSTM-Attention,bilstm_attention,GenPept_Curated_2025,100-109,10,130.17 +/- 33.26,3.289 +/- 0.069,4.68 +/- 0.40,0.626 +/- 0.053,1757.1 +/- 0.0,244.2 +/- 5.3,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
33,BiLSTM-Attention,bilstm_attention,External_Benchmark_1,100-109,10,48.31 +/- 17.09,2.199 +/- 0.083,4.51 +/- 0.06,0.655 +/- 0.009,1757.1 +/- 0.0,196.9 +/- 5.3,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
34,BiLSTM-Attention,bilstm_attention,AMPlify_balanced,100-109,10,64.88 +/- 11.47,1.932 +/- 0.046,4.50 +/- 0.07,0.667 +/- 0.011,1757.1 +/- 0.0,129.0 +/- 6.0,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
35,BiLSTM-Attention,bilstm_attention,External_Benchmark_3,100-109,10,101.74 +/- 16.08,3.561 +/- 0.041,4.51 +/- 0.06,0.636 +/- 0.008,1757.1 +/- 0.0,135.9 +/- 5.2,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
36,Transformer Encoder,transformer_encoder,GenPept_Curated_2025,100-109,10,61.81 +/- 8.23,4.242 +/- 0.084,18.41 +/- 1.11,2.460 +/- 0.149,1757.1 +/- 0.0,598.4 +/- 0.0,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
37,Transformer Encoder,transformer_encoder,External_Benchmark_1,100-109,10,35.57 +/- 5.19,3.340 +/- 0.103,19.52 +/- 1.64,2.831 +/- 0.238,1757.1 +/- 0.0,598.4 +/- 0.0,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
38,Transformer Encoder,transformer_encoder,AMPlify_balanced,100-109,10,56.31 +/- 21.98,3.744 +/- 1.425,21.03 +/- 1.82,3.114 +/- 0.270,1757.1 +/- 0.0,595.3 +/- 1.1,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
39,Transformer Encoder,transformer_encoder,External_Benchmark_3,100-109,10,132.59 +/- 22.48,10.536 +/- 0.622,20.92 +/- 2.24,2.951 +/- 0.316,1757.1 +/- 0.0,598.5 +/- 0.0,gpu_tensorflow_locked_cell2_subprocess,gpu_tensorflow_locked_cell2_subprocess
40,AmPEP,ampep,GenPept_Curated_2025,100-109,10,3.36 +/- 0.17,Not epoch-based,0.14 +/- 0.10,0.018 +/- 0.014,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,cpu
41,AmPEP,ampep,External_Benchmark_1,100-109,10,2.07 +/- 0.11,Not epoch-based,0.13 +/- 0.09,0.019 +/- 0.013,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,cpu
42,AmPEP,ampep,AMPlify_balanced,100-109,10,1.78 +/- 0.05,Not epoch-based,0.11 +/- 0.08,0.016 +/- 0.012,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,cpu
43,AmPEP,ampep,External_Benchmark_3,100-109,10,3.93 +/- 0.21,Not epoch-based,0.17 +/- 0.10,0.024 +/- 0.014,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,cpu
44,AMPScannerV2,ampscannerv2,GenPept_Curated_2025,100-109,10,496.13 +/- 14.54,49.613 +/- 1.454,15.34 +/- 0.26,2.050 +/- 0.035,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,legacy_cpu_exact_environment
45,AMPScannerV2,ampscannerv2,External_Benchmark_1,100-109,10,363.39 +/- 34.03,36.339 +/- 3.403,14.31 +/- 0.10,2.075 +/- 0.014,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,legacy_cpu_exact_environment
46,AMPScannerV2,ampscannerv2,AMPlify_balanced,100-109,10,425.77 +/- 1.73,42.577 +/- 0.173,14.05 +/- 0.07,2.080 +/- 0.011,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,legacy_cpu_exact_environment
47,AMPScannerV2,ampscannerv2,External_Benchmark_3,100-109,10,719.58 +/- 40.75,71.958 +/- 4.075,14.62 +/- 0.09,2.062 +/- 0.013,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,legacy_cpu_exact_environment
48,amPEPpy,ampeppy,GenPept_Curated_2025,100-109,10,11.63 +/- 0.55,Not epoch-based,31.43 +/- 0.25,4.200 +/- 0.034,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,legacy_cpu_exact_environment
49,amPEPpy,ampeppy,External_Benchmark_1,100-109,10,9.30 +/- 0.38,Not epoch-based,29.03 +/- 0.11,4.210 +/- 0.016,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,legacy_cpu_exact_environment
50,amPEPpy,ampeppy,AMPlify_balanced,100-109,10,7.77 +/- 0.31,Not epoch-based,28.40 +/- 0.19,4.205 +/- 0.028,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,legacy_cpu_exact_environment
51,amPEPpy,ampeppy,External_Benchmark_3,100-109,10,16.50 +/- 0.78,Not epoch-based,30.01 +/- 0.17,4.232 +/- 0.024,1757.1 +/- 0.0,CPU / not recorded by route,method_specific,legacy_cpu_exact_environment

================================================================================================================================================================
CELL 36 TABLE - Table_D_hardware_software_environment.csv
================================================================================================================================================================
Rows: 31 | Columns: 3

,Component,Value,Provenance
0,Python executable,/home/pc/miniconda3/envs/genpept_benchmark10_m...,locked environment_audit.json
1,Python version,3.11.16,locked environment_audit.json
2,Platform,Linux-6.18.33.2-microsoft-standard-WSL2-x86_64...,locked environment_audit.json
3,Machine architecture,x86_64,locked environment_audit.json
4,CPU,x86_64,locked environment_audit.json
5,System RAM visible to WSL,15.40 GB,current same-host WSL query; not part of origi...
6,GPU,NVIDIA GeForce RTX 3060,locked environment_audit.json
7,GPU VRAM total,12.00 GB,locked environment_audit.json
8,NVIDIA driver,610.88,locked environment_audit.json
9,TensorFlow,2.21.0,locked environment_audit.json
10,PyTorch,2.11.0+cu128,locked environment_audit.json
11,scikit-learn,1.9.0,locked environment_audit.json
12,LightGBM,4.7.0,locked environment_audit.json
13,fair-esm,2.0.0,locked environment_audit.json
14,Logistic Regression - max recorded process RAM,1246.3 MB,Cell32 resources.json across 40 runs
15,Calibrated Linear SVM - max recorded process RAM,1299.8 MB,Cell32 resources.json across 40 runs
16,Random Forest - max recorded process RAM,1490.2 MB,Cell32 resources.json across 40 runs
17,Extra Trees - max recorded process RAM,1713.8 MB,Cell32 resources.json across 40 runs
18,HistGradientBoosting - max recorded process RAM,1757.1 MB,Cell32 resources.json across 40 runs
19,LightGBM - max recorded process RAM,1757.1 MB,Cell32 resources.json across 40 runs
20,CNN1D - max recorded process RAM,1757.1 MB,Cell32 resources.json across 40 runs
21,CNN1D - max recorded GPU VRAM,142.4 MB,Cell32 resources.json across 40 runs
22,BiLSTM - max recorded process RAM,1757.1 MB,Cell32 resources.json across 40 runs
23,BiLSTM - max recorded GPU VRAM,254.1 MB,Cell32 resources.json across 40 runs
24,BiLSTM-Attention - max recorded process RAM,1757.1 MB,Cell32 resources.json across 40 runs
25,BiLSTM-Attention - max recorded GPU VRAM,254.5 MB,Cell32 resources.json across 40 runs
26,Transformer Encoder - max recorded process RAM,1757.1 MB,Cell32 resources.json across 40 runs
27,Transformer Encoder - max recorded GPU VRAM,598.5 MB,Cell32 resources.json across 40 runs
28,AmPEP - max recorded process RAM,1757.1 MB,Cell32 resources.json across 40 runs
29,AMPScannerV2 - max recorded process RAM,1757.1 MB,Cell32 resources.json across 40 runs
30,amPEPpy - max recorded process RAM,1757.1 MB,Cell32 resources.json across 40 runs

================================================================================================================================================================
CELL 36 TABLE - Table_E_performance_plus_efficiency_13.csv
================================================================================================================================================================
Rows: 13 | Columns: 21

,model_id,Model,summary_note,P1_AUROC_macro_mean,P2_AUROC_macro_mean,P1_AUPRC_macro_mean,P2_AUPRC_macro_mean,P1_MCC_macro_mean,P2_MCC_macro_mean,P1_F1_macro_mean,...,training_seconds_mean,training_seconds_sd,evaluation_4targets_seconds_mean,evaluation_4targets_seconds_sd,evaluation_ms_per_sequence_mean,evaluation_ms_per_sequence_sd,peak_process_ram_mb_mean,peak_process_ram_mb_sd,peak_gpu_vram_mb_mean,peak_gpu_vram_mb_sd
0,logistic_regression,Logistic Regression,Performance values are Cell35 descriptive macr...,0.871834,0.654186,0.872124,0.608605,0.607327,0.220739,0.807565,...,1.566284,0.279232,0.012080,0.010305,0.001702,0.001378,1194.478027,31.494182,,
1,linear_svm_calibrated,Linear SVM (calibrated),Performance values are Cell35 descriptive macr...,0.873199,0.654529,0.874525,0.610097,0.604333,0.226429,0.801749,...,2.423840,1.078129,0.029233,0.007983,0.004147,0.001153,1287.317090,6.779108,,
2,random_forest,Random Forest,Performance values are Cell35 descriptive macr...,0.927465,0.667551,0.937584,0.654603,0.717969,0.242242,0.853949,...,1.090059,0.298051,0.633365,0.040956,0.089892,0.006509,1396.179785,47.134103,,
3,extra_trees,Extra Trees,Performance values are Cell35 descriptive macr...,0.929564,0.673827,0.941055,0.659420,0.725634,0.245331,0.854116,...,0.885453,0.214155,0.873126,0.195481,0.123869,0.027563,1594.603418,48.930377,,
4,hist_gradient_boosting,HistGradientBoosting,Performance values are Cell35 descriptive macr...,0.932545,0.707050,0.943878,0.677869,0.728537,0.293273,0.860971,...,2.273256,0.248658,0.040894,0.003595,0.005810,0.000600,1754.590234,2.058835,,
5,lightgbm,LightGBM,Performance values are Cell35 descriptive macr...,0.936097,0.707836,0.946256,0.676665,0.740966,0.292299,0.869901,...,1.285795,0.609211,0.044554,0.013479,0.006349,0.002030,1757.144531,0.000000,,
6,cnn1d,CNN1D,Performance values are Cell35 descriptive macr...,0.922607,0.657424,0.934396,0.638225,0.710671,0.238742,0.851901,...,18.386750,4.017104,7.146768,0.853392,1.014663,0.127552,1757.144531,0.000000,142.30623779296874,0.05798141299000378
7,bilstm,BiLSTM,Performance values are Cell35 descriptive macr...,0.919137,0.660237,0.926181,0.637036,0.696350,0.237065,0.852327,...,62.389551,28.465160,4.048213,0.163216,0.574526,0.030915,1757.144531,0.000000,174.53981323242186,46.59484837387107
8,bilstm_attention,BiLSTM + Attention,Performance values are Cell35 descriptive macr...,0.911737,0.651843,0.917205,0.618958,0.686976,0.242478,0.840546,...,86.275829,38.145687,4.552088,0.212012,0.645748,0.031088,1757.144531,0.000000,176.52258911132813,48.078312131638995
9,transformer_encoder,Transformer Encoder,Performance values are Cell35 descriptive macr...,0.907250,0.650419,0.913768,0.620414,0.676141,0.226443,0.835015,...,71.569770,40.264589,19.970410,2.008359,2.838874,0.342853,1757.144531,0.000000,597.6591674804688,1.4872179962366308
10,ampep,AmPEP,Performance values are Cell35 descriptive macr...,0.895344,0.616939,0.904685,0.583425,0.644008,0.172162,0.814199,...,2.783726,0.911468,0.136271,0.091849,0.019288,0.012920,1757.144531,0.000000,,
11,ampscannerv2,AMPScannerV2,Performance values are Cell35 descriptive macr...,0.925307,0.665956,0.935579,0.650224,0.733253,0.259484,0.859712,...,501.219549,138.792951,14.577382,0.510329,2.066477,0.022961,1757.144531,0.000000,,
12,ampeppy,amPEPpy,Performance values are Cell35 descriptive macr...,0.896687,0.616521,0.906447,0.585254,0.644352,0.176292,0.817354,...,11.303058,3.384134,29.715701,1.171782,4.211622,0.028216,1757.144531,0.000000,,

================================================================================================================================================================
CELL 37 STATUS
================================================================================================================================================================
Training performed           : FALSE
Inference performed          : FALSE
Threshold tuning             : FALSE
Re-aggregation               : FALSE
Scope changed                : FALSE
----------------------------------------------------------------------------------------------------------------------------------------------------------------
CELL 34 all aggregate        : 208 / 208
CELL 34 P1                   : 52 / 52
CELL 34 P2                   : 156 / 156
CELL 34 threshold summary    : 52 / 52
CELL 34 confusion summary    : 208 / 208
CELL 35 CSV/table/matrix     : 72 files
CELL 35 figures              : 12 files
CELL 36 tables               : 5 files
Total CSV/JSON pairs exported: 82
----------------------------------------------------------------------------------------------------------------------------------------------------------------
Review/export root           : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell37_review_export
Export index CSV             : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell37_review_export/RESULT_EXPORT_INDEX.csv
Export index JSON            : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell37_review_export/RESULT_EXPORT_INDEX.json
Manifest JSON                : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell37_review_export/CELL37_RESULT_EXPORT_MANIFEST.json
----------------------------------------------------------------------------------------------------------------------------------------------------------------
CELL 37 PASS - CELL 34/35/36 RESULTS DISPLAYED AND EXPORTED AS CSV + JSON
================================================================================================================================================================

# Thí nghiệm so sánh dataset của mình với các bộ dataset khác trên phần bù

In [5]:
from __future__ import annotations

# ============================================================================
# CELL 38 - GENPEPT-CURATED-2025 FULL-COMPLEMENT BIDIRECTIONAL VALIDATION
# Protocol: P3_FULL_COMPLEMENT_BIDIRECTIONAL_GENPEPT
# ============================================================================
# PURPOSE
#   Dataset-centered validation requested by the advisor:
#     1) GenPept -> (External final-QC \ GenPept)
#     2) External -> (GenPept final-QC \ External)
#   for the three retained external comparators.
#
# SCIENTIFIC LOCKS
#   - NO training, fitting, fine-tuning, recalibration, or target adaptation.
#   - Reuse the 520 canonical training bundles from Cell 32B only.
#   - Reuse the frozen source-validation threshold tau* from each run only.
#   - Exact sequence overlap is removed using the ENTIRE source cohort.
#   - Six bidirectional full-complement directions.
#   - 13 models x 6 directions x 10 seeds = 780 inference-only evaluations.
#   - Restart-safe: valid evaluation bundles are verified and skipped.
#   - Existing Cell 32/33/34/35/36/37 artifacts are read-only.
#
# IMPORTANT
#   This cell is STANDALONE after a kernel restart. Do NOT rerun Cell 33.
# ============================================================================

from pathlib import Path
from datetime import datetime
import gc
import hashlib
import json
import math
import os
import pickle
import shutil
import subprocess
import sys
import tempfile
import time

import numpy as np
import pandas as pd
from scipy.stats import t as student_t
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    balanced_accuracy_score,
    brier_score_loss,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    roc_auc_score,
)


# ============================================================================
# 0. FIXED IDENTITY / PATHS / PROTOCOL
# ============================================================================

CELL38_SCHEMA_VERSION = '2.0.0'
PROTOCOL = 'P3_FULL_COMPLEMENT_BIDIRECTIONAL_GENPEPT'

EXPECTED_PYTHON = Path(
    '/home/pc/miniconda3/envs/genpept_benchmark10_master/bin/python'
).resolve()
CURRENT_PYTHON = Path(sys.executable).resolve()
assert CURRENT_PYTHON == EXPECTED_PYTHON, (
    'WRONG KERNEL\n'
    f'Expected: {EXPECTED_PYTHON}\n'
    f'Current : {CURRENT_PYTHON}'
)

PROJECT_ROOT = Path('/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026')
OUTPUT_ROOT = PROJECT_ROOT / 'benchmark17_outputs'
AUDIT_DIR = OUTPUT_ROOT / 'audit'
MANIFEST_DIR = OUTPUT_ROOT / 'manifests'
RESULTS_ROOT = OUTPUT_ROOT / 'results'
WORK_ROOT = Path('/home/pc/genpept_benchmark17_work')
RUN_ROOT = WORK_ROOT / 'runs' / 'benchmark4_FINAL_v1'

FINAL13_MODEL_SCOPE_PATH = AUDIT_DIR / 'benchmark13_FINAL_model_scope_lock.csv'
FINAL13_TRAINING_SCOPE_PATH = AUDIT_DIR / 'benchmark13_FINAL_training_run_scope_520.csv'
FINAL13_WITHIN_PLAN_PATH = AUDIT_DIR / 'benchmark13_FINAL_within_eval_plan_520.csv'
FINAL13_PROTOCOL2_PLAN_PATH = AUDIT_DIR / 'benchmark13_FINAL_protocol2_eval_plan_1560.csv'
FINAL13_SCOPE_MANIFEST_PATH = MANIFEST_DIR / 'benchmark13_FINAL_scope_manifest.json'

EVALUATION_CONTRACT_PATH = MANIFEST_DIR / 'benchmark17_FINAL_evaluation_contract.json'
CONTROLLED_CONTRACT_PATH = MANIFEST_DIR / 'benchmark17_FINAL_controlled_model_contract.json'
FEATURE_CACHE_MANIFEST_PATH = MANIFEST_DIR / 'benchmark17_FINAL_feature_cache_manifest.json'
LAUNCHER_CONTRACT_PATH = MANIFEST_DIR / 'benchmark17_FINAL_training_launcher_contract.json'
CUDA_PATHS_FILE = MANIFEST_DIR / 'cuda_runtime_paths.json'
ENVIRONMENT_AUDIT_PATH = MANIFEST_DIR / 'environment_audit.json'

CELL33_SUMMARY_PATH = AUDIT_DIR / 'benchmark13_FINAL_cell33_summary.json'
CELL33_SELFTEST_PATH = AUDIT_DIR / 'benchmark13_FINAL_cell33_checkpoint_reload_selftest.csv'

HELPER_ROOT = WORK_ROOT / 'evaluation_helpers' / 'benchmark13_FINAL'
DEEP_HELPER_PATH = HELPER_ROOT / 'controlled_deep_inference_v1.py'
AMPSCANNER_HELPER_PATH = HELPER_ROOT / 'ampscannerv2_inference_v1.py'
AMPEPPY_HELPER_PATH = HELPER_ROOT / 'ampeppy_inference_v1.py'

AMPSCANNER_SOURCE = (
    Path('/home/pc/genpept_sources/amp-scanner-v2_933052e2365631fe93098892120ee535e0ba381a')
    / 'amp_scanner_v2_train_tf1.py'
)
AMPSCANNER_PY = Path.home() / 'miniconda3/envs/genpept_ampscannerv2_orig/bin/python'
AMPEPPY_SOURCE = Path('/home/pc/genpept_sources/amPEPpy_v1.0_aa1f694c6cb3d09b16bc9378bed77f59e4f1e780')
AMPEPPY_PY = Path.home() / 'miniconda3/envs/genpept_ampeppy_v1/bin/python'

CELL38_ROOT = (
    RESULTS_ROOT
    / 'benchmark13_FINAL'
    / 'cell38_full_complement_genpept_validation'
)
EVAL_BUNDLE_ROOT = CELL38_ROOT / 'evaluation_bundles'
FULL_COMPLEMENT_ROOT = CELL38_ROOT / 'full_complements'
TMP_ROOT = CELL38_ROOT / '_tmp'
STAGING_ROOT = CELL38_ROOT / '_staging'

TABLE38A_PATH = CELL38_ROOT / 'Table38A_final_QC_overlap_novelty.csv'
TABLE38B_PATH = CELL38_ROOT / 'Table38B_full_complement_direction_sizes.csv'
PLAN_PATH = CELL38_ROOT / 'cell38_evaluation_plan_780.csv'
TABLE38C_PATH = CELL38_ROOT / 'Table38C_seed_level_metrics_780.csv'
TABLE38D_PATH = CELL38_ROOT / 'Table38D_10seed_aggregate_78.csv'
TABLE38E_PATH = CELL38_ROOT / 'Table38E_genpept_bidirectional_model_comparison_39.csv'
TABLE38F_PATH = CELL38_ROOT / 'Table38F_genpept_bidirectional_dataset_summary.csv'
CUSTOM_INDEX_PATH = CELL38_ROOT / 'cell38_full_complement_indices.npz'
CELL38_MANIFEST_PATH = MANIFEST_DIR / 'benchmark13_FINAL_cell38_full_complement_manifest.json'

EXPECTED_SCOPE_SHA = '66648c9c1dd0911fc29d36a405a8f176da168d4a74459e2cd4149a45d8251f2a'
EXPECTED_TRAINING_SCOPE_SHA = 'a01215b83916ea6422cb7b86512154bfc476aadda4e4d0b513911687200a00f7'
EXPECTED_P1_PLAN_SHA = '0b1b5765d2005ebe8f1875309314cab00d04a6b5d8d552d85dbdbe4319ca1b0e'
EXPECTED_P2_PLAN_SHA = '7801abad304766b78416c4a78388f371e2ae9bdd1fd91f64656bb8ecec606725'
EXPECTED_SCOPE_MANIFEST_SHA = '1639f1480ba4dbe9b1344d1321f5049c9ac59dc15ac8cced5d3e62210b3209dc'

EXPECTED_DATASETS = [
    'GenPept_Curated_2025',
    'External_Benchmark_1',
    'AMPlify_balanced',
    'External_Benchmark_3',
]
GENPEPT = 'GenPept_Curated_2025'
COMPARATORS = [
    'External_Benchmark_1',
    'AMPlify_balanced',
    'External_Benchmark_3',
]
EXPECTED_SEEDS = list(range(100, 110))

CONTROLLED_CLASSICAL = [
    'logistic_regression',
    'linear_svm_calibrated',
    'random_forest',
    'extra_trees',
    'hist_gradient_boosting',
    'lightgbm',
]
CONTROLLED_DEEP = [
    'cnn1d',
    'bilstm',
    'bilstm_attention',
    'transformer_encoder',
]
PUBLISHED_COMPLETE = ['ampep', 'ampscannerv2', 'ampeppy']
FINAL13_MODEL_IDS = CONTROLLED_CLASSICAL + CONTROLLED_DEEP + PUBLISHED_COMPLETE
assert len(FINAL13_MODEL_IDS) == 13

MODEL_LABELS = {
    'logistic_regression': 'Logistic Regression',
    'linear_svm_calibrated': 'Linear SVM (calibrated)',
    'random_forest': 'Random Forest',
    'extra_trees': 'Extra Trees',
    'hist_gradient_boosting': 'HistGradientBoosting',
    'lightgbm': 'LightGBM',
    'cnn1d': 'CNN1D',
    'bilstm': 'BiLSTM',
    'bilstm_attention': 'BiLSTM + Attention',
    'transformer_encoder': 'Transformer Encoder',
    'ampep': 'AmPEP',
    'ampscannerv2': 'AMPScannerV2',
    'ampeppy': 'amPEPpy',
}

DATASET_LABELS = {
    'GenPept_Curated_2025': 'GenPept-Curated-2025',
    'External_Benchmark_1': 'SSFGM-BD1',
    'AMPlify_balanced': 'AMPlify-balanced',
    'External_Benchmark_3': 'SSFGM-BD3',
}

EXPECTED_FINAL_COUNTS = {
    'GenPept_Curated_2025': {'n': 11000, 'AMP': 5500, 'nonAMP': 5500},
    'External_Benchmark_1': {'n': 8156, 'AMP': 4602, 'nonAMP': 3554},
    'AMPlify_balanced': {'n': 8068, 'AMP': 4034, 'nonAMP': 4034},
    'External_Benchmark_3': {'n': 13835, 'AMP': 6764, 'nonAMP': 7071},
}

EXPECTED_OVERLAP = {
    'External_Benchmark_1': {'shared': 81, 'conflicts': 10},
    'AMPlify_balanced': {'shared': 84, 'conflicts': 7},
    'External_Benchmark_3': {'shared': 63, 'conflicts': 5},
}

DIRECTION_SPECS = [
    {'direction_id': 'FC_01', 'source': GENPEPT, 'target': 'External_Benchmark_1', 'expected_n': 8075},
    {'direction_id': 'FC_02', 'source': 'External_Benchmark_1', 'target': GENPEPT, 'expected_n': 10919},
    {'direction_id': 'FC_03', 'source': GENPEPT, 'target': 'AMPlify_balanced', 'expected_n': 7984},
    {'direction_id': 'FC_04', 'source': 'AMPlify_balanced', 'target': GENPEPT, 'expected_n': 10916},
    {'direction_id': 'FC_05', 'source': GENPEPT, 'target': 'External_Benchmark_3', 'expected_n': 13772},
    {'direction_id': 'FC_06', 'source': 'External_Benchmark_3', 'target': GENPEPT, 'expected_n': 10937},
]
DIRECTION_BY_PAIR = {(d['source'], d['target']): d for d in DIRECTION_SPECS}
TARGETS_BY_SOURCE = {
    GENPEPT: ['External_Benchmark_1', 'AMPlify_balanced', 'External_Benchmark_3'],
    'External_Benchmark_1': [GENPEPT],
    'AMPlify_balanced': [GENPEPT],
    'External_Benchmark_3': [GENPEPT],
}

AA20 = set('ACDEFGHIKLMNPQRSTVWY')
METRICS = [
    'AUROC', 'AUPRC', 'MCC', 'BACC', 'F1', 'ACC',
    'Sensitivity', 'Specificity', 'Brier', 'ECE10',
]
CORE_METRICS = ['AUROC', 'AUPRC', 'MCC', 'F1', 'ACC']

for p in [PROJECT_ROOT, OUTPUT_ROOT, AUDIT_DIR, MANIFEST_DIR, RESULTS_ROOT, WORK_ROOT, RUN_ROOT]:
    assert p.is_dir(), f'Required directory missing: {p}'
for p in [CELL38_ROOT, EVAL_BUNDLE_ROOT, FULL_COMPLEMENT_ROOT, TMP_ROOT, STAGING_ROOT]:
    p.mkdir(parents=True, exist_ok=True)


# ============================================================================
# 1. GENERIC HELPERS
# ============================================================================

def now_iso() -> str:
    return datetime.now().astimezone().isoformat()


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(chunk_size), b''):
            h.update(chunk)
    return h.hexdigest()


def sha256_int64_array(values) -> str:
    arr = np.asarray(values, dtype='<i8').reshape(-1)
    return hashlib.sha256(arr.tobytes(order='C')).hexdigest()


def read_csv_exact(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, low_memory=False, keep_default_na=False, na_filter=False)


def load_json(path: Path):
    with path.open('r', encoding='utf-8') as f:
        return json.load(f)


def atomic_write_json(path: Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    try:
        with os.fdopen(fd, 'w', encoding='utf-8', newline='\n') as f:
            json.dump(payload, f, indent=2, ensure_ascii=False, sort_keys=True)
            f.write('\n')
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def atomic_write_csv(path: Path, df: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    os.close(fd)
    try:
        df.to_csv(tmp, index=False, lineterminator='\n')
        with open(tmp, 'rb') as f:
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def write_npz_atomic(path: Path, arrays: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    os.close(fd)
    try:
        with open(tmp, 'wb') as f:
            np.savez_compressed(f, **arrays)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def artifact_record(actual_path: Path, final_path: Path | None = None) -> dict:
    assert actual_path.is_file(), f'Missing artifact: {actual_path}'
    return {
        'path': str(final_path if final_path is not None else actual_path),
        'size_bytes': int(actual_path.stat().st_size),
        'sha256': sha256_file(actual_path),
    }


def run_cmd(cmd, *, env=None, timeout=None, cwd=None, label='command'):
    r = subprocess.run(
        [str(x) for x in cmd],
        cwd=None if cwd is None else str(cwd),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        timeout=timeout,
        check=False,
    )
    if r.returncode != 0:
        print(f'[{label}] STDOUT:\n{r.stdout}')
        print(f'[{label}] STDERR:\n{r.stderr}')
    assert r.returncode == 0, f'{label} failed with exit code {r.returncode}'
    return r


# ============================================================================
# 2. VERIFY LOCKED CELL 32B SCOPE AND CELL 33 COMPLETION
# ============================================================================

for p in [
    FINAL13_MODEL_SCOPE_PATH,
    FINAL13_TRAINING_SCOPE_PATH,
    FINAL13_WITHIN_PLAN_PATH,
    FINAL13_PROTOCOL2_PLAN_PATH,
    FINAL13_SCOPE_MANIFEST_PATH,
    EVALUATION_CONTRACT_PATH,
    CONTROLLED_CONTRACT_PATH,
    FEATURE_CACHE_MANIFEST_PATH,
    LAUNCHER_CONTRACT_PATH,
    CELL33_SUMMARY_PATH,
    CELL33_SELFTEST_PATH,
    DEEP_HELPER_PATH,
    AMPSCANNER_HELPER_PATH,
    AMPEPPY_HELPER_PATH,
]:
    assert p.is_file(), f'Required locked artifact missing: {p}'

assert sha256_file(FINAL13_MODEL_SCOPE_PATH) == EXPECTED_SCOPE_SHA, '13-model scope SHA drift'
assert sha256_file(FINAL13_TRAINING_SCOPE_PATH) == EXPECTED_TRAINING_SCOPE_SHA, '520-run scope SHA drift'
assert sha256_file(FINAL13_WITHIN_PLAN_PATH) == EXPECTED_P1_PLAN_SHA, 'P1 plan SHA drift'
assert sha256_file(FINAL13_PROTOCOL2_PLAN_PATH) == EXPECTED_P2_PLAN_SHA, 'P2 plan SHA drift'
assert sha256_file(FINAL13_SCOPE_MANIFEST_PATH) == EXPECTED_SCOPE_MANIFEST_SHA, 'Scope manifest SHA drift'

model_scope = read_csv_exact(FINAL13_MODEL_SCOPE_PATH)
training_scope = read_csv_exact(FINAL13_TRAINING_SCOPE_PATH)
p1_plan = read_csv_exact(FINAL13_WITHIN_PLAN_PATH)
p2_plan = read_csv_exact(FINAL13_PROTOCOL2_PLAN_PATH)
scope_manifest = load_json(FINAL13_SCOPE_MANIFEST_PATH)
cell33_summary = load_json(CELL33_SUMMARY_PATH)

scope = scope_manifest['scope']
assert scope['n_models'] == 13
assert scope['model_ids'] == FINAL13_MODEL_IDS
assert scope['training_bundles'] == 520
assert scope['additional_training_required'] is False
assert scope['target_threshold_tuning'] is False
assert scope['target_retraining'] is False
assert scope['selection_by_performance'] is False

assert len(training_scope) == 520 and training_scope['run_id'].astype(str).is_unique
assert training_scope['model_id'].drop_duplicates().astype(str).tolist() == FINAL13_MODEL_IDS
assert training_scope['source_dataset'].drop_duplicates().astype(str).tolist() == EXPECTED_DATASETS
assert sorted(pd.to_numeric(training_scope['seed'], errors='raise').astype(int).unique().tolist()) == EXPECTED_SEEDS
assert training_scope.groupby(['model_id', 'source_dataset']).size().eq(10).all()

assert len(p1_plan) == 520
assert len(p2_plan) == 1560
assert p1_plan['target_threshold_tuning'].astype(str).str.lower().eq('false').all()
assert p1_plan['target_retraining'].astype(str).str.lower().eq('false').all()
assert p2_plan['threshold_source'].astype(str).eq('source_validation_only').all()
assert p2_plan['target_threshold_tuning'].astype(str).str.lower().eq('false').all()
assert p2_plan['target_retraining'].astype(str).str.lower().eq('false').all()
assert p2_plan['source_dataset'].astype(str).ne(p2_plan['target_dataset'].astype(str)).all()
assert pd.to_numeric(p2_plan['residual_exact_overlap'], errors='raise').eq(0).all()

assert cell33_summary['training_performed'] is False
assert cell33_summary['checkpoint_reload_selftest_passed'] is True
assert int(cell33_summary['checkpoint_reload_selftest_models']) == 13
assert int(cell33_summary['completed_evaluations']) == 2080
assert int(cell33_summary['p1_completed']) == 520
assert int(cell33_summary['p2_completed']) == 1560
assert int(cell33_summary['seed_metrics_rows']) == 2080
assert cell33_summary['target_threshold_tuning'] is False
assert cell33_summary['target_retraining'] is False
assert cell33_summary['target_finetuning'] is False
assert cell33_summary['scope_manifest_sha256'] == EXPECTED_SCOPE_MANIFEST_SHA
assert cell33_summary['evaluation_contract_sha256'] == sha256_file(EVALUATION_CONTRACT_PATH)
assert cell33_summary['deep_inference_helper_sha256'] == sha256_file(DEEP_HELPER_PATH)
assert cell33_summary['ampscannerv2_inference_helper_sha256'] == sha256_file(AMPSCANNER_HELPER_PATH)
assert cell33_summary['ampeppy_inference_helper_sha256'] == sha256_file(AMPEPPY_HELPER_PATH)
assert cell33_summary['checkpoint_reload_selftest_sha256'] == sha256_file(CELL33_SELFTEST_PATH)

print('=' * 132)
print('CELL 38 - STANDALONE FULL-COMPLEMENT BIDIRECTIONAL GENPEPT VALIDATION')
print('=' * 132)
print('Kernel / Python             : PASS', CURRENT_PYTHON)
print('Cell 32B immutable scope    : PASS')
print('Cell 33 completion          : PASS 2080/2080')
print('Cell 33 loader self-tests   : PASS 13/13')
print('Training in Cell 38         : FORBIDDEN / FALSE')
print('Target tuning / adaptation  : FORBIDDEN / FALSE')
print('-' * 132)


# ============================================================================
# 3. VERIFY FEATURE / EVALUATION CONTRACTS AND LOAD LOCKED CACHES
# ============================================================================

evaluation_contract = load_json(EVALUATION_CONTRACT_PATH)
controlled_wrapper = load_json(CONTROLLED_CONTRACT_PATH)
feature_manifest = load_json(FEATURE_CACHE_MANIFEST_PATH)
launcher_wrapper = load_json(LAUNCHER_CONTRACT_PATH)

assert evaluation_contract['status'] == 'LOCKED_BEFORE_MODEL_TRAINING'
assert evaluation_contract['datasets'] == EXPECTED_DATASETS
assert evaluation_contract['model_seeds'] == EXPECTED_SEEDS
assert evaluation_contract['threshold_policy']['selection_dataset'] == 'source_validation_only'
assert evaluation_contract['threshold_policy']['optimization_objective'] == 'maximize_MCC'
assert evaluation_contract['threshold_policy']['test_based_threshold_selection'] is False
assert evaluation_contract['threshold_policy']['external_target_based_threshold_selection'] is False
assert evaluation_contract['threshold_policy']['protocol_2']['target_threshold_optimization'] is False
assert evaluation_contract['threshold_policy']['protocol_2']['target_threshold_recalibration'] is False
assert evaluation_contract['score_contract']['positive_label'] == 1
assert evaluation_contract['score_contract']['required_score_range'] == [0.0, 1.0]

controlled_contract = controlled_wrapper['contract']
assert controlled_contract['controlled_model_ids'] == CONTROLLED_CLASSICAL + CONTROLLED_DEEP

cache_files = feature_manifest['files']
CLASSICAL_CACHE_PATH = Path(cache_files['X_classical']['path'])
TOKEN_CACHE_PATH = Path(cache_files['X_tokens']['path'])
LABEL_CACHE_PATH = Path(cache_files['y']['path'])
ROW_METADATA_PATH = Path(cache_files['row_metadata']['path'])

for key, path in [
    ('X_classical', CLASSICAL_CACHE_PATH),
    ('X_tokens', TOKEN_CACHE_PATH),
    ('y', LABEL_CACHE_PATH),
    ('row_metadata', ROW_METADATA_PATH),
]:
    assert path.is_file(), f'Missing cache: {path}'
    assert sha256_file(path) == cache_files[key]['sha256'], f'Cache hash drift: {key}'

launcher = launcher_wrapper['contract']
EXECUTION_INDEX_PATH = Path(launcher['immutable_inputs']['execution_index']['path'])
assert EXECUTION_INDEX_PATH.is_file()
assert sha256_file(EXECUTION_INDEX_PATH) == launcher['immutable_inputs']['execution_index']['sha256']

X_CLASSICAL = np.load(CLASSICAL_CACHE_PATH, mmap_mode='r', allow_pickle=False)
X_TOKENS = np.load(TOKEN_CACHE_PATH, mmap_mode='r', allow_pickle=False)
Y = np.load(LABEL_CACHE_PATH, mmap_mode='r', allow_pickle=False)
assert X_CLASSICAL.shape == (41059, 421)
assert X_TOKENS.shape == (41059, 200)
assert Y.shape == (41059,)

TOKEN_TO_ID = controlled_contract['deep_representation']['token_to_id']
assert TOKEN_TO_ID['PAD'] == 0
ID_TO_AA = {int(v): str(k) for k, v in TOKEN_TO_ID.items() if str(k) != 'PAD'}
assert set(ID_TO_AA) == set(range(1, 21))
assert set(ID_TO_AA.values()) == AA20


# ============================================================================
# 4. VERIFY ALL 520 CANONICAL TRAINING BUNDLES AND FROZEN THRESHOLDS
# ============================================================================

def verify_training_bundle(row) -> dict:
    run_dir = Path(str(row.run_dir))
    manifest_path = run_dir / 'run_manifest.json'
    assert manifest_path.is_file(), f'Missing run manifest: {manifest_path}'
    m = load_json(manifest_path)

    assert m['status'] in {'TRAINED', 'EVALUATED', 'COMPLETE'}
    assert m['run_id'] == str(row.run_id)
    assert m['model_id'] == str(row.model_id)
    assert m['source_dataset'] == str(row.source_dataset)
    assert int(m['seed']) == int(row.seed)
    assert str(m['train_index_key']) == str(row.train_index_key)
    assert str(m['validation_index_key']) == str(row.validation_index_key)
    assert str(m['source_test_index_key']) == str(row.source_test_index_key)
    assert m.get('cell32_source_test_read') is False
    assert m.get('cell32_external_target_read') is False

    assert not (run_dir / 'source_test_predictions.csv').exists(), f'Training dir mutated: {run_dir}'
    assert not (run_dir / 'source_test_metrics.json').exists(), f'Training dir mutated: {run_dir}'
    assert not (run_dir / 'external').exists(), f'Training dir mutated: {run_dir}'

    required = m['training_artifacts']
    for rel in ['config.json', 'validation_predictions.csv', 'validation_threshold.json', 'history.csv', 'resources.json']:
        assert rel in required
    for rel, entry in required.items():
        p = run_dir / rel
        assert p.is_file(), f'Missing training artifact: {p}'
        assert int(p.stat().st_size) == int(entry['size_bytes'])
        assert sha256_file(p) == str(entry['sha256'])

    cp_rel = str(m['checkpoint_relative_path'])
    checkpoint = run_dir / cp_rel
    assert checkpoint.is_file(), f'Missing checkpoint: {checkpoint}'
    cp_entry = m['checkpoint_artifact']
    assert int(checkpoint.stat().st_size) == int(cp_entry['size_bytes'])
    assert sha256_file(checkpoint) == str(cp_entry['sha256'])

    threshold_path = run_dir / 'validation_threshold.json'
    th = load_json(threshold_path)
    tau = float(th['tau'])
    assert 0.0 <= tau <= 1.0
    assert th['selection_dataset'] == 'source_validation_only'
    assert th['source_test_used'] is False
    assert th['external_target_used'] is False
    assert np.isclose(float(m['validation_threshold']), tau, rtol=0.0, atol=1e-15)

    return {
        'run_dir': run_dir,
        'manifest_path': manifest_path,
        'manifest_sha256': sha256_file(manifest_path),
        'checkpoint': checkpoint,
        'checkpoint_sha256': sha256_file(checkpoint),
        'threshold_path': threshold_path,
        'threshold_sha256': sha256_file(threshold_path),
        'tau': tau,
    }


TRAINING_BUNDLE_INFO = {}
for i, row in enumerate(training_scope.itertuples(index=False), start=1):
    TRAINING_BUNDLE_INFO[str(row.run_id)] = verify_training_bundle(row)
    if i % 50 == 0 or i == 520:
        print(f'[TRAIN-BUNDLE VERIFY] {i:>3}/520 PASS', flush=True)
assert len(TRAINING_BUNDLE_INFO) == 520
print('Canonical training bundles  : PASS 520/520')


# ============================================================================
# 5. MATERIALIZE THE FOUR FINAL-QC DATASETS FROM LOCKED ROW METADATA + TOKENS
#    IMPORTANT: row_index remains ONLY a normal column; no ambiguous index level.
# ============================================================================

meta = read_csv_exact(ROW_METADATA_PATH)
required_meta_cols = {
    'row_index', 'sample_id', 'dataset', 'split', 'label',
    'sequence_length', 'sequence_sha256',
}
assert required_meta_cols.issubset(meta.columns)
assert len(meta) == 41059

meta['row_index'] = pd.to_numeric(meta['row_index'], errors='raise').astype(np.int64)
meta['label'] = pd.to_numeric(meta['label'], errors='raise').astype(np.int8)
meta['sequence_length'] = pd.to_numeric(meta['sequence_length'], errors='raise').astype(np.int64)
assert meta['row_index'].is_unique
assert np.array_equal(
    np.sort(meta['row_index'].to_numpy(np.int64)),
    np.arange(41059, dtype=np.int64),
)
assert set(meta['dataset'].astype(str).unique().tolist()) == set(EXPECTED_DATASETS)


def decode_sequence(row_index: int, expected_length: int, expected_sha256: str) -> str:
    tokens = np.asarray(X_TOKENS[int(row_index)], dtype=np.int64)
    nonpad = tokens[tokens != 0]
    assert len(nonpad) == int(expected_length)
    seq = ''.join(ID_TO_AA[int(t)] for t in nonpad.tolist())
    assert len(seq) == int(expected_length)
    assert set(seq).issubset(AA20)
    assert hashlib.sha256(seq.encode('utf-8')).hexdigest() == str(expected_sha256)
    return seq


FULL_FRAMES = {}
for dataset in EXPECTED_DATASETS:
    m = meta.loc[meta['dataset'].astype(str).eq(dataset)].copy()
    m = m.sort_values(by=['row_index'], kind='mergesort', ignore_index=True)

    sequences = [
        decode_sequence(
            int(r.row_index),
            int(r.sequence_length),
            str(r.sequence_sha256),
        )
        for r in m.itertuples(index=False)
    ]

    df = pd.DataFrame({
        'sample_id': m['sample_id'].astype(str).tolist(),
        'sequence': sequences,
        'sequence_sha256': m['sequence_sha256'].astype(str).tolist(),
        'label': m['label'].astype(np.int8).tolist(),
        'dataset': m['dataset'].astype(str).tolist(),
        'split': m['split'].astype(str).tolist(),
        'row_index': m['row_index'].astype(np.int64).tolist(),
        'length': m['sequence_length'].astype(int).tolist(),
    })

    exp = EXPECTED_FINAL_COUNTS[dataset]
    assert len(df) == int(exp['n'])
    assert int((df['label'] == 1).sum()) == int(exp['AMP'])
    assert int((df['label'] == 0).sum()) == int(exp['nonAMP'])
    assert df['row_index'].is_unique
    assert df['sequence'].is_unique, f'Internal exact duplicate in {dataset}'
    assert df['sequence_sha256'].is_unique, f'Internal sequence hash duplicate in {dataset}'
    assert set(df['label'].unique().tolist()) == {0, 1}
    assert df['length'].between(10, 200).all()
    assert df['sequence'].map(lambda s: set(s).issubset(AA20)).all()

    idx = df['row_index'].to_numpy(np.int64)
    assert np.array_equal(
        df['label'].to_numpy(np.int8),
        np.asarray(Y[idx], dtype=np.int8),
    )
    FULL_FRAMES[dataset] = df.reset_index(drop=True)

print('FINAL-QC DATASETS MATERIALIZED: PASS')
for dataset in EXPECTED_DATASETS:
    x = FULL_FRAMES[dataset]
    print(
        f"{dataset:<28} n={len(x):>6,} | "
        f"AMP={(x['label'] == 1).sum():>6,} | "
        f"nonAMP={(x['label'] == 0).sum():>6,}"
    )


# ============================================================================
# 6. EXACT FINAL-QC OVERLAP / NOVELTY AUDIT
# ============================================================================

G = FULL_FRAMES[GENPEPT]
G_label_map = G.set_index('sequence')['label'].astype(int).to_dict()
G_set = set(G_label_map)
overlap_rows = []

for ext in COMPARATORS:
    E = FULL_FRAMES[ext]
    E_label_map = E.set_index('sequence')['label'].astype(int).to_dict()
    E_set = set(E_label_map)
    shared = G_set & E_set
    conflicts = int(sum(G_label_map[s] != E_label_map[s] for s in shared))
    same_label = int(len(shared) - conflicts)
    union_n = len(G_set | E_set)

    expected = EXPECTED_OVERLAP[ext]
    assert len(shared) == int(expected['shared']), (
        f'Unexpected final-QC overlap for {ext}: expected {expected["shared"]}, got {len(shared)}'
    )
    assert conflicts == int(expected['conflicts']), (
        f'Unexpected label-conflict count for {ext}: expected {expected["conflicts"]}, got {conflicts}'
    )

    overlap_rows.append({
        'GenPept_dataset': GENPEPT,
        'comparator_dataset': ext,
        'GenPept_label': DATASET_LABELS[GENPEPT],
        'comparator_label': DATASET_LABELS[ext],
        'GenPept_n': len(G),
        'comparator_n': len(E),
        'exact_shared': len(shared),
        'same_label_shared': same_label,
        'label_conflicts': conflicts,
        'GenPept_only': len(G_set - E_set),
        'comparator_only': len(E_set - G_set),
        'pct_GenPept_overlap': 100.0 * len(shared) / len(G_set),
        'pct_comparator_overlap': 100.0 * len(shared) / len(E_set),
        'jaccard_pct': 100.0 * len(shared) / union_n,
        'overlap_definition': 'exact_normalized_canonical_amino_acid_sequence',
    })

OVERLAP_DF = pd.DataFrame(overlap_rows)
assert len(OVERLAP_DF) == 3
atomic_write_csv(TABLE38A_PATH, OVERLAP_DF)

print('\nFINAL-QC EXACT OVERLAP AUDIT: PASS')
print(
    OVERLAP_DF[
        ['comparator_label', 'exact_shared', 'same_label_shared', 'label_conflicts', 'GenPept_only', 'comparator_only']
    ].to_string(index=False)
)


# ============================================================================
# 7. BUILD AND LOCK THE SIX FULL COMPLEMENTS
# ============================================================================

FULL_COMPLEMENTS = {}
direction_rows = []
custom_index_arrays = {}

for spec in DIRECTION_SPECS:
    direction_id = spec['direction_id']
    source = spec['source']
    target = spec['target']
    src = FULL_FRAMES[source]
    tgt = FULL_FRAMES[target]
    src_set = set(src['sequence'].astype(str))

    overlap_mask = tgt['sequence'].astype(str).isin(src_set)
    removed = tgt.loc[overlap_mask].copy()
    clean = tgt.loc[~overlap_mask].copy().reset_index(drop=True)

    assert len(clean) == int(spec['expected_n']), (
        f'{direction_id}: expected complement n={spec["expected_n"]}, got {len(clean)}'
    )
    assert int(clean['sequence'].isin(src_set).sum()) == 0
    assert set(clean['label'].unique().tolist()) == {0, 1}
    assert clean['row_index'].is_unique

    src_label_map = src.set_index('sequence')['label'].astype(int).to_dict()
    conflict_removed = int(
        sum(src_label_map[str(seq)] != int(y) for seq, y in zip(removed['sequence'], removed['label']))
    )

    pair_expected = EXPECTED_OVERLAP[target if source == GENPEPT else source]
    assert int(overlap_mask.sum()) == int(pair_expected['shared'])
    assert conflict_removed == int(pair_expected['conflicts'])

    row_idx = clean['row_index'].to_numpy(np.int64)
    row_idx_sha = sha256_int64_array(row_idx)
    FULL_COMPLEMENTS[(source, target)] = clean
    custom_index_arrays[direction_id] = row_idx

    cohort_path = FULL_COMPLEMENT_ROOT / f'{direction_id}__{source}__TO__{target}.csv'
    atomic_write_csv(cohort_path, clean)

    direction_rows.append({
        'direction_id': direction_id,
        'source_dataset': source,
        'target_dataset': target,
        'source_label': DATASET_LABELS[source],
        'target_label': DATASET_LABELS[target],
        'source_full_n': len(src),
        'target_full_raw_n': len(tgt),
        'exact_overlap_removed': int(overlap_mask.sum()),
        'label_conflicts_removed': conflict_removed,
        'target_full_complement_n': len(clean),
        'target_AMP': int((clean['label'] == 1).sum()),
        'target_nonAMP': int((clean['label'] == 0).sum()),
        'residual_exact_overlap': 0,
        'target_row_index_sha256': row_idx_sha,
        'target_definition': 'entire_final_QC_target_minus_entire_source_exact_normalized_sequence',
        'cohort_csv': str(cohort_path),
    })

DIRECTION_DF = pd.DataFrame(direction_rows)
assert len(DIRECTION_DF) == 6
atomic_write_csv(TABLE38B_PATH, DIRECTION_DF)

# Keep an existing NPZ only if its scientific contents are exactly identical.
if CUSTOM_INDEX_PATH.is_file():
    existing_idx = np.load(CUSTOM_INDEX_PATH, allow_pickle=False)
    assert set(existing_idx.files) == set(custom_index_arrays), (
        f'Existing Cell38 custom index keys differ: {existing_idx.files}'
    )
    for key, expected_arr in custom_index_arrays.items():
        assert np.array_equal(np.asarray(existing_idx[key], dtype=np.int64), expected_arr), (
            f'Existing Cell38 custom index drift: {key}'
        )
    existing_idx.close()
else:
    write_npz_atomic(CUSTOM_INDEX_PATH, custom_index_arrays)

check_idx = np.load(CUSTOM_INDEX_PATH, allow_pickle=False)
for key, arr in custom_index_arrays.items():
    assert np.array_equal(np.asarray(check_idx[key], dtype=np.int64), arr)
check_idx.close()
CUSTOM_INDEX_SHA = sha256_file(CUSTOM_INDEX_PATH)

print('\nFULL-COMPLEMENT CONSTRUCTION: PASS 6/6')
print(
    DIRECTION_DF[
        ['direction_id', 'source_label', 'target_label', 'exact_overlap_removed', 'target_full_complement_n', 'residual_exact_overlap']
    ].to_string(index=False)
)


# ============================================================================
# 8. EXACT METRIC DEFINITIONS (IDENTICAL TO CELL 33)
# ============================================================================

def binary_ece(y_true, y_score, n_bins=10):
    y_true = np.asarray(y_true, dtype=int)
    y_score = np.asarray(y_score, dtype=float)
    assert len(y_true) == len(y_score) and len(y_true) > 0
    assert np.isfinite(y_score).all()
    assert ((y_score >= 0.0) & (y_score <= 1.0)).all()
    edges = np.linspace(0.0, 1.0, n_bins + 1)
    ece = 0.0
    for i in range(n_bins):
        left, right = edges[i], edges[i + 1]
        mask = (
            ((y_score >= left) & (y_score < right))
            if i < n_bins - 1
            else ((y_score >= left) & (y_score <= right))
        )
        n_bin = int(mask.sum())
        if n_bin == 0:
            continue
        ece += (n_bin / len(y_true)) * abs(
            float(y_true[mask].mean()) - float(y_score[mask].mean())
        )
    return float(ece)


def compute_binary_metrics(y_true, y_score, tau):
    y_true = np.asarray(y_true, dtype=int)
    y_score = np.asarray(y_score, dtype=float)
    assert len(y_true) == len(y_score) and len(y_true) > 0
    assert set(np.unique(y_true).tolist()) == {0, 1}
    assert np.isfinite(y_score).all()
    assert ((y_score >= 0.0) & (y_score <= 1.0)).all()
    assert 0.0 <= float(tau) <= 1.0

    y_pred = (y_score >= float(tau)).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    sensitivity = tp / (tp + fn)
    specificity = tn / (tn + fp)

    return {
        'AUROC': float(roc_auc_score(y_true, y_score)),
        'AUPRC': float(average_precision_score(y_true, y_score)),
        'MCC': float(matthews_corrcoef(y_true, y_pred)),
        'BACC': float(balanced_accuracy_score(y_true, y_pred)),
        'F1': float(f1_score(y_true, y_pred, zero_division=0)),
        'ACC': float(accuracy_score(y_true, y_pred)),
        'Sensitivity': float(sensitivity),
        'Specificity': float(specificity),
        'Brier': float(brier_score_loss(y_true, y_score)),
        'ECE10': float(binary_ece(y_true, y_score, n_bins=10)),
        'threshold': float(tau),
        'TP': int(tp),
        'TN': int(tn),
        'FP': int(fp),
        'FN': int(fn),
        'n': int(len(y_true)),
        'n_positive': int((y_true == 1).sum()),
        'n_negative': int((y_true == 0).sum()),
    }


# ============================================================================
# 9. MODEL-SPECIFIC INFERENCE HELPERS - NO TRAINING
# ============================================================================

def positive_probability(model, X):
    p = np.asarray(model.predict_proba(X), dtype=float)
    if hasattr(model, 'classes_'):
        classes = np.asarray(model.classes_)
    elif hasattr(model, 'named_steps'):
        classes = np.asarray(model.named_steps['model'].classes_)
    else:
        classes = np.asarray(model[-1].classes_)
    pos = int(np.where(classes == 1)[0][0])
    out = p[:, pos]
    assert np.isfinite(out).all()
    assert ((out >= 0.0) & (out <= 1.0)).all()
    return out


AMPEP_PROPERTY_GROUPS = [
    ('charge', ['ACFGHILMNPQSTVWY', 'DE', 'KR']),
    ('hydrophobicity', ['CFILMVW', 'AGHPSTY', 'DEKNQR']),
    ('normalized_vander_waals', ['ACDGPST', 'EILNQV', 'FHKMRWY']),
    ('polarity', ['CFILMVWY', 'AGPST', 'DEHKNQR']),
    ('polarizability', ['ADGST', 'CEILNPQV', 'FHKMRWY']),
    ('secondary_structure', ['DGNPS', 'AEHKLMQR', 'CFITVWY']),
    ('solvent_accessibility', ['ACFGILVW', 'HMPSTY', 'DEKNRQ']),
]


def ampep_distribution_positions(pos, n):
    if not pos:
        return [0.0] * 5
    count = len(pos)
    out = [100.0 * pos[0] / n]
    for frac in [0.25, 0.50, 0.75]:
        k = math.floor(count * frac)
        selected = pos[0] if k == 0 else pos[k - 1]
        out.append(100.0 * selected / n)
    out.append(100.0 * pos[-1] / n)
    return out


def ampep_feature_vector(seq: str):
    seq = str(seq).strip().upper()
    n = len(seq)
    vals = []
    for _, groups in AMPEP_PROPERTY_GROUPS:
        for group in groups:
            positions = [i for i, aa in enumerate(seq, start=1) if aa in group]
            vals.extend(ampep_distribution_positions(positions, n))
    out = np.asarray(vals, dtype=np.float64)
    assert out.shape == (105,)
    return out


def ampep_matrix(df):
    return np.vstack([ampep_feature_vector(s) for s in df['sequence'].astype(str)])


def locked_tensorflow_subprocess_env(seed=None):
    assert CUDA_PATHS_FILE.is_file(), f'Missing CUDA path manifest: {CUDA_PATHS_FILE}'
    assert ENVIRONMENT_AUDIT_PATH.is_file(), f'Missing environment audit: {ENVIRONMENT_AUDIT_PATH}'
    cuda_payload = load_json(CUDA_PATHS_FILE)
    env_audit = load_json(ENVIRONMENT_AUDIT_PATH)
    dirs = [str(x) for x in cuda_payload.get('cuda_library_dirs', [])]
    assert len(dirs) > 1
    for d in dirs:
        assert Path(d).is_dir(), f'Locked CUDA library dir missing: {d}'
    assert int(env_audit['tensorflow']['gpu_count']) >= 1
    assert env_audit['tensorflow']['is_cuda_build'] is True

    env = os.environ.copy()
    old = env.get('LD_LIBRARY_PATH', '')
    parts = list(dirs) + ([old] if old else [])
    env['LD_LIBRARY_PATH'] = ':'.join(dict.fromkeys(parts))
    env['CUDA_VISIBLE_DEVICES'] = '0'
    env['TF_CPP_MIN_LOG_LEVEL'] = '2'
    env['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'
    if seed is not None:
        env['PYTHONHASHSEED'] = str(int(seed))
    return env


def verify_controlled_deep_gpu():
    code = """
import json, tensorflow as tf
gpus=tf.config.list_physical_devices('GPU')
assert gpus, 'GPU unavailable'
for gpu in gpus:
    try: tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError: pass
with tf.device('/GPU:0'):
    x=tf.constant([1.,2.,3.]); y=tf.reduce_sum(x*2.)
assert float(y.numpy())==12.0
print(json.dumps({'tensorflow':tf.__version__,'gpu_count':len(gpus),'gpu':str(gpus[0])}))
"""
    r = run_cmd(
        [CURRENT_PYTHON, '-c', code],
        env=locked_tensorflow_subprocess_env(),
        timeout=120,
        label='Cell38 controlled-deep GPU preflight',
    )
    lines = [x for x in r.stdout.splitlines() if x.strip()]
    assert lines
    return json.loads(lines[-1])


def deep_predict_requests(model_id, checkpoint, seed, request_rows):
    tmp_dir = Path(tempfile.mkdtemp(prefix='cell38_deep_', dir=str(TMP_ROOT)))
    try:
        req_path = tmp_dir / 'request.json'
        out_path = tmp_dir / 'scores.csv'
        atomic_write_json(req_path, request_rows)
        t0 = time.perf_counter()
        run_cmd(
            [
                CURRENT_PYTHON,
                DEEP_HELPER_PATH,
                model_id,
                checkpoint,
                TOKEN_CACHE_PATH,
                CUSTOM_INDEX_PATH,
                CONTROLLED_CONTRACT_PATH,
                req_path,
                out_path,
                int(seed),
            ],
            env=locked_tensorflow_subprocess_env(seed),
            timeout=7200,
            label=f'Cell38 deep inference {model_id}',
        )
        wall = time.perf_counter() - t0
        pred = read_csv_exact(out_path)
        result = {}
        for item in request_rows:
            sub = pred[pred['eval_id'].astype(str).eq(str(item['eval_id']))].copy()
            sub['row_pos'] = pd.to_numeric(sub['row_pos'], errors='raise').astype(int)
            sub = sub.sort_values('row_pos', kind='mergesort')
            assert sub['row_pos'].tolist() == list(range(int(item['target_n'])))
            scores = pd.to_numeric(sub['y_score'], errors='raise').to_numpy(float)
            assert len(scores) == int(item['target_n'])
            assert np.isfinite(scores).all()
            assert ((scores >= 0.0) & (scores <= 1.0)).all()
            result[str(item['eval_id'])] = scores
        return result, wall
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


def write_combined_fasta(requests_with_df, path: Path):
    mapping = []
    with path.open('w', encoding='utf-8', newline='\n') as f:
        counter = 0
        for req, df in requests_with_df:
            for pos, r in enumerate(df.itertuples(index=False)):
                internal = f'E{counter:09d}'
                counter += 1
                f.write(f'>{internal}\n{str(r.sequence)}\n')
                mapping.append((internal, str(req['eval_id']), int(pos)))
    return pd.DataFrame(mapping, columns=['internal_id', 'eval_id', 'row_pos'])


def legacy_predict_requests(model_id, checkpoint, requests_with_df):
    tmp_dir = Path(tempfile.mkdtemp(prefix=f'cell38_{model_id}_', dir=str(TMP_ROOT)))
    try:
        fasta = tmp_dir / 'combined_eval.fa'
        out = tmp_dir / 'scores.csv'
        mapping = write_combined_fasta(requests_with_df, fasta)
        t0 = time.perf_counter()

        if model_id == 'ampscannerv2':
            run_cmd(
                [AMPSCANNER_PY, AMPSCANNER_HELPER_PATH, AMPSCANNER_SOURCE, checkpoint, fasta, out],
                timeout=7200,
                label='Cell38 AMPScannerV2 checkpoint inference',
            )
        elif model_id == 'ampeppy':
            run_cmd(
                [AMPEPPY_PY, AMPEPPY_HELPER_PATH, AMPEPPY_SOURCE, checkpoint, fasta, out, tmp_dir],
                timeout=7200,
                label='Cell38 amPEPpy checkpoint inference',
            )
        else:
            raise KeyError(model_id)

        wall = time.perf_counter() - t0
        pred = read_csv_exact(out)
        pred['internal_id'] = pred['internal_id'].astype(str)
        merged = mapping.merge(
            pred[['internal_id', 'y_score']],
            on='internal_id',
            how='left',
            validate='one_to_one',
        )
        assert merged['y_score'].astype(str).ne('').all()
        merged['y_score'] = pd.to_numeric(merged['y_score'], errors='raise')

        result = {}
        for req, df in requests_with_df:
            sub = merged[
                merged['eval_id'].astype(str).eq(str(req['eval_id']))
            ].sort_values('row_pos', kind='mergesort')
            assert sub['row_pos'].tolist() == list(range(len(df)))
            scores = sub['y_score'].to_numpy(float)
            assert len(scores) == len(df)
            assert np.isfinite(scores).all()
            assert ((scores >= 0.0) & (scores <= 1.0)).all()
            result[str(req['eval_id'])] = scores
        return result, wall
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


assert AMPSCANNER_SOURCE.is_file()
assert AMPSCANNER_PY.is_file()
assert AMPEPPY_SOURCE.is_dir()
assert AMPEPPY_PY.is_file()


# ============================================================================
# 10. BUILD THE EXACT 780-EVALUATION PLAN
# ============================================================================

plan_rows = []
for rr in training_scope.itertuples(index=False):
    run_id = str(rr.run_id)
    model_id = str(rr.model_id)
    source = str(rr.source_dataset)
    seed = int(rr.seed)
    info = TRAINING_BUNDLE_INFO[run_id]

    for target in TARGETS_BY_SOURCE[source]:
        spec = DIRECTION_BY_PAIR[(source, target)]
        target_df = FULL_COMPLEMENTS[(source, target)]
        eval_id = f'{PROTOCOL}__{model_id}__{source}__TO__{target}__seed{seed}'
        plan_rows.append({
            'eval_id': eval_id,
            'protocol': PROTOCOL,
            'direction_id': spec['direction_id'],
            'run_id': run_id,
            'model_id': model_id,
            'model': MODEL_LABELS[model_id],
            'source_dataset': source,
            'target_dataset': target,
            'source_label': DATASET_LABELS[source],
            'target_label': DATASET_LABELS[target],
            'seed': seed,
            'target_index_key': spec['direction_id'],
            'target_n': int(len(target_df)),
            'target_AMP': int((target_df['label'] == 1).sum()),
            'target_nonAMP': int((target_df['label'] == 0).sum()),
            'target_row_index_sha256': sha256_int64_array(target_df['row_index'].to_numpy(np.int64)),
            'threshold_source': 'source_validation_only_frozen',
            'threshold': float(info['tau']),
            'training_manifest_sha256': info['manifest_sha256'],
            'checkpoint_sha256': info['checkpoint_sha256'],
            'threshold_sha256': info['threshold_sha256'],
            'training_performed': False,
            'target_threshold_tuning': False,
            'target_retraining': False,
            'target_finetuning': False,
        })

PLAN_DF = pd.DataFrame(plan_rows)
assert len(PLAN_DF) == 780
assert PLAN_DF['eval_id'].is_unique
assert PLAN_DF.groupby(['model_id', 'source_dataset', 'target_dataset']).size().eq(10).all()
assert PLAN_DF.groupby(['direction_id', 'model_id']).size().eq(10).all()
assert PLAN_DF['model_id'].drop_duplicates().tolist() == FINAL13_MODEL_IDS
assert sorted(PLAN_DF['seed'].unique().tolist()) == EXPECTED_SEEDS
assert PLAN_DF['training_performed'].eq(False).all()
assert PLAN_DF['target_threshold_tuning'].eq(False).all()
assert PLAN_DF['target_retraining'].eq(False).all()
assert PLAN_DF['target_finetuning'].eq(False).all()
atomic_write_csv(PLAN_PATH, PLAN_DF)
PLAN_SHA = sha256_file(PLAN_PATH)
print('\nCELL38 EVALUATION PLAN: PASS 780/780')


# ============================================================================
# 11. RESTART-SAFE PER-EVALUATION BUNDLES
# ============================================================================

INT_METRIC_KEYS = {'TP', 'TN', 'FP', 'FN', 'n', 'n_positive', 'n_negative'}
FLOAT_METRIC_KEYS = set(METRICS + ['threshold'])


def eval_dir_for(eval_id: str) -> Path:
    return EVAL_BUNDLE_ROOT / str(eval_id)


def _assert_float_close(a, b, *, name, atol=1e-12):
    assert np.isclose(float(a), float(b), rtol=0.0, atol=atol), (
        f'{name} mismatch: {a} != {b}'
    )


def validate_eval_bundle(plan_row: dict, *, strict_existing=True) -> bool:
    eval_id = str(plan_row['eval_id'])
    final_dir = eval_dir_for(eval_id)
    if not final_dir.exists():
        return False

    try:
        assert final_dir.is_dir()
        manifest_path = final_dir / 'eval_manifest.json'
        metrics_path = final_dir / 'metrics.json'
        predictions_path = final_dir / 'predictions.npz'
        assert manifest_path.is_file()
        assert metrics_path.is_file()
        assert predictions_path.is_file()

        manifest = load_json(manifest_path)
        assert manifest['schema_version'] == CELL38_SCHEMA_VERSION
        assert manifest['protocol'] == PROTOCOL
        assert manifest['status'] == 'COMPLETE'
        assert manifest['eval_id'] == eval_id
        assert manifest['run_id'] == str(plan_row['run_id'])
        assert manifest['model_id'] == str(plan_row['model_id'])
        assert manifest['source_dataset'] == str(plan_row['source_dataset'])
        assert manifest['target_dataset'] == str(plan_row['target_dataset'])
        assert int(manifest['seed']) == int(plan_row['seed'])
        assert manifest['direction_id'] == str(plan_row['direction_id'])
        assert int(manifest['target_n']) == int(plan_row['target_n'])
        assert manifest['target_row_index_sha256'] == str(plan_row['target_row_index_sha256'])
        assert manifest['training_performed'] is False
        assert manifest['target_threshold_tuning'] is False
        assert manifest['target_retraining'] is False
        assert manifest['target_finetuning'] is False
        assert manifest['threshold_source'] == 'source_validation_only_frozen'
        assert manifest['source_training_manifest_sha256'] == str(plan_row['training_manifest_sha256'])
        assert manifest['source_checkpoint_sha256'] == str(plan_row['checkpoint_sha256'])
        assert manifest['source_validation_threshold_sha256'] == str(plan_row['threshold_sha256'])

        for name, actual_path in [
            ('metrics.json', metrics_path),
            ('predictions.npz', predictions_path),
        ]:
            rec = manifest['artifacts'][name]
            assert Path(rec['path']) == actual_path
            assert int(rec['size_bytes']) == int(actual_path.stat().st_size)
            assert str(rec['sha256']) == sha256_file(actual_path)

        payload = load_json(metrics_path)
        assert payload['schema_version'] == CELL38_SCHEMA_VERSION
        assert payload['protocol'] == PROTOCOL
        assert payload['eval_id'] == eval_id
        assert payload['run_id'] == str(plan_row['run_id'])
        assert payload['model_id'] == str(plan_row['model_id'])
        assert payload['source_dataset'] == str(plan_row['source_dataset'])
        assert payload['target_dataset'] == str(plan_row['target_dataset'])
        assert int(payload['seed']) == int(plan_row['seed'])
        assert int(payload['target_n']) == int(plan_row['target_n'])
        _assert_float_close(payload['threshold'], plan_row['threshold'], name=f'{eval_id} threshold', atol=1e-15)

        z = np.load(predictions_path, allow_pickle=False)
        expected_npz_keys = {'sample_id', 'row_index', 'y_true', 'y_score', 'y_pred'}
        assert set(z.files) == expected_npz_keys

        source = str(plan_row['source_dataset'])
        target = str(plan_row['target_dataset'])
        target_df = FULL_COMPLEMENTS[(source, target)]
        expected_rows = target_df['row_index'].to_numpy(np.int64)
        expected_y = target_df['label'].to_numpy(np.int8)
        expected_sample = target_df['sample_id'].astype(str).to_numpy(dtype='U')

        row_idx = np.asarray(z['row_index'], dtype=np.int64)
        y_true = np.asarray(z['y_true'], dtype=np.int8)
        y_score = np.asarray(z['y_score'], dtype=float)
        y_pred = np.asarray(z['y_pred'], dtype=np.int8)
        sample_id = np.asarray(z['sample_id']).astype(str)
        z.close()

        assert len(row_idx) == int(plan_row['target_n'])
        assert np.array_equal(row_idx, expected_rows)
        assert sha256_int64_array(row_idx) == str(plan_row['target_row_index_sha256'])
        assert np.array_equal(y_true, expected_y)
        assert np.array_equal(sample_id, expected_sample)
        assert np.isfinite(y_score).all()
        assert ((y_score >= 0.0) & (y_score <= 1.0)).all()

        tau = float(plan_row['threshold'])
        assert np.array_equal(y_pred, (y_score >= tau).astype(np.int8))

        recomputed = compute_binary_metrics(y_true, y_score, tau)
        stored_metrics = payload['metrics']
        for k in FLOAT_METRIC_KEYS:
            _assert_float_close(stored_metrics[k], recomputed[k], name=f'{eval_id} metric {k}')
        for k in INT_METRIC_KEYS:
            assert int(stored_metrics[k]) == int(recomputed[k]), (
                f'{eval_id} metric {k} mismatch'
            )

        return True

    except Exception as exc:
        if strict_existing:
            raise AssertionError(
                f'INVALID EXISTING CELL38 EVALUATION BUNDLE: {final_dir}\n{type(exc).__name__}: {exc}'
            ) from exc
        return False


def commit_evaluation(plan_row: dict, scores, batch_wall_seconds: float) -> None:
    eval_id = str(plan_row['eval_id'])
    final_dir = eval_dir_for(eval_id)
    assert not final_dir.exists(), f'Cannot overwrite existing evaluation bundle: {final_dir}'

    source = str(plan_row['source_dataset'])
    target = str(plan_row['target_dataset'])
    target_df = FULL_COMPLEMENTS[(source, target)]
    tau = float(plan_row['threshold'])

    scores = np.asarray(scores, dtype=float).reshape(-1)
    assert len(scores) == len(target_df) == int(plan_row['target_n'])
    assert np.isfinite(scores).all()
    assert ((scores >= 0.0) & (scores <= 1.0)).all()

    y_true = target_df['label'].to_numpy(np.int8)
    y_pred = (scores >= tau).astype(np.int8)
    metrics = compute_binary_metrics(y_true, scores, tau)

    staging_dir = Path(tempfile.mkdtemp(prefix=eval_id + '.', dir=str(STAGING_ROOT)))
    try:
        staging_metrics = staging_dir / 'metrics.json'
        staging_predictions = staging_dir / 'predictions.npz'
        staging_manifest = staging_dir / 'eval_manifest.json'

        final_metrics = final_dir / 'metrics.json'
        final_predictions = final_dir / 'predictions.npz'

        metrics_payload = {
            'schema_version': CELL38_SCHEMA_VERSION,
            'protocol': PROTOCOL,
            'eval_id': eval_id,
            'run_id': str(plan_row['run_id']),
            'direction_id': str(plan_row['direction_id']),
            'model_id': str(plan_row['model_id']),
            'source_dataset': source,
            'target_dataset': target,
            'seed': int(plan_row['seed']),
            'target_n': int(plan_row['target_n']),
            'target_row_index_sha256': str(plan_row['target_row_index_sha256']),
            'threshold_source': 'source_validation_only_frozen',
            'threshold': tau,
            'batch_inference_wall_seconds': float(batch_wall_seconds),
            'metrics': metrics,
        }
        atomic_write_json(staging_metrics, metrics_payload)

        write_npz_atomic(
            staging_predictions,
            {
                'sample_id': target_df['sample_id'].astype(str).to_numpy(dtype='U'),
                'row_index': target_df['row_index'].to_numpy(np.int64),
                'y_true': y_true,
                'y_score': scores.astype(np.float64),
                'y_pred': y_pred,
            },
        )

        manifest_payload = {
            'schema_version': CELL38_SCHEMA_VERSION,
            'status': 'COMPLETE',
            'created_at': now_iso(),
            'protocol': PROTOCOL,
            'eval_id': eval_id,
            'run_id': str(plan_row['run_id']),
            'direction_id': str(plan_row['direction_id']),
            'model_id': str(plan_row['model_id']),
            'source_dataset': source,
            'target_dataset': target,
            'seed': int(plan_row['seed']),
            'target_n': int(plan_row['target_n']),
            'target_row_index_sha256': str(plan_row['target_row_index_sha256']),
            'training_performed': False,
            'target_threshold_tuning': False,
            'target_retraining': False,
            'target_finetuning': False,
            'threshold_source': 'source_validation_only_frozen',
            'threshold': tau,
            'source_training_manifest_sha256': str(plan_row['training_manifest_sha256']),
            'source_checkpoint_sha256': str(plan_row['checkpoint_sha256']),
            'source_validation_threshold_sha256': str(plan_row['threshold_sha256']),
            'cell32b_scope_manifest_sha256': EXPECTED_SCOPE_MANIFEST_SHA,
            'cell38_plan_sha256': PLAN_SHA,
            'artifacts': {
                'metrics.json': artifact_record(staging_metrics, final_metrics),
                'predictions.npz': artifact_record(staging_predictions, final_predictions),
            },
        }
        atomic_write_json(staging_manifest, manifest_payload)

        assert not final_dir.exists()
        os.replace(staging_dir, final_dir)
        assert validate_eval_bundle(plan_row, strict_existing=True)

    except Exception:
        if staging_dir.exists():
            shutil.rmtree(staging_dir, ignore_errors=True)
        raise


# ============================================================================
# 12. AUDIT EXISTING CELL38 BUNDLES ONCE, THEN RUN ONLY MISSING EVALUATIONS
# ============================================================================

PLAN_RECORDS = PLAN_DF.to_dict(orient='records')
PLAN_BY_EVAL = {str(r['eval_id']): r for r in PLAN_RECORDS}
PLAN_BY_RUN = {str(rid): [] for rid in training_scope['run_id'].astype(str).tolist()}
for r in PLAN_RECORDS:
    PLAN_BY_RUN[str(r['run_id'])].append(r)

completed_ids = set()
for i, r in enumerate(PLAN_RECORDS, start=1):
    if validate_eval_bundle(r, strict_existing=True):
        completed_ids.add(str(r['eval_id']))
    if i % 100 == 0 or i == 780:
        print(f'[CELL38 STARTUP BUNDLE AUDIT] scanned={i:>3}/780 | valid_existing={len(completed_ids):>3}', flush=True)

print(f'Existing valid Cell38 evaluations: {len(completed_ids)}/780')

MAX_RUN_GROUPS = int(os.environ.get('GENPEPT_CELL38_MAX_RUN_GROUPS', '0'))
assert MAX_RUN_GROUPS >= 0
run_groups_this_invocation = 0
new_evals_this_invocation = 0

pending_deep = any(
    str(r['eval_id']) not in completed_ids and str(r['model_id']) in CONTROLLED_DEEP
    for r in PLAN_RECORDS
)
if pending_deep:
    gpu_info = verify_controlled_deep_gpu()
    print('Controlled-deep GPU preflight: PASS', gpu_info)

AMPEP_FULLCOMP_CACHE = {}

def ampep_features_for_pair(source: str, target: str):
    key = (source, target)
    if key not in AMPEP_FULLCOMP_CACHE:
        AMPEP_FULLCOMP_CACHE[key] = ampep_matrix(FULL_COMPLEMENTS[key])
    return AMPEP_FULLCOMP_CACHE[key]


run_order = training_scope['run_id'].astype(str).tolist()
for run_id in run_order:
    pending_rows = [
        r for r in PLAN_BY_RUN[run_id]
        if str(r['eval_id']) not in completed_ids
    ]
    if not pending_rows:
        continue

    if MAX_RUN_GROUPS > 0 and run_groups_this_invocation >= MAX_RUN_GROUPS:
        break

    run_groups_this_invocation += 1
    model_id = str(pending_rows[0]['model_id'])
    source = str(pending_rows[0]['source_dataset'])
    seed = int(pending_rows[0]['seed'])
    assert all(str(r['model_id']) == model_id for r in pending_rows)
    assert all(str(r['source_dataset']) == source for r in pending_rows)
    assert all(int(r['seed']) == seed for r in pending_rows)

    info = TRAINING_BUNDLE_INFO[run_id]
    checkpoint = info['checkpoint']

    requests = []
    requests_with_df = []
    for r in pending_rows:
        target = str(r['target_dataset'])
        target_df = FULL_COMPLEMENTS[(source, target)]
        req = {
            'eval_id': str(r['eval_id']),
            'target_index_key': str(r['target_index_key']),
            'target_n': int(r['target_n']),
        }
        requests.append(req)
        requests_with_df.append((req, target_df))

    score_map = {}
    batch_wall = 0.0

    if model_id in CONTROLLED_CLASSICAL:
        t0 = time.perf_counter()
        with open(checkpoint, 'rb') as f:
            model = pickle.load(f)
        for req, target_df in requests_with_df:
            idx = target_df['row_index'].to_numpy(np.int64)
            Xev = np.asarray(X_CLASSICAL[idx], dtype=np.float32)
            score_map[str(req['eval_id'])] = positive_probability(model, Xev)
        batch_wall = time.perf_counter() - t0
        del model

    elif model_id in CONTROLLED_DEEP:
        score_map, batch_wall = deep_predict_requests(
            model_id,
            checkpoint,
            seed,
            requests,
        )

    elif model_id == 'ampep':
        t0 = time.perf_counter()
        with open(checkpoint, 'rb') as f:
            model = pickle.load(f)
        for req, target_df in requests_with_df:
            target = str(target_df['dataset'].iloc[0])
            Xev = ampep_features_for_pair(source, target)
            score_map[str(req['eval_id'])] = positive_probability(model, Xev)
        batch_wall = time.perf_counter() - t0
        del model

    elif model_id in {'ampscannerv2', 'ampeppy'}:
        score_map, batch_wall = legacy_predict_requests(
            model_id,
            checkpoint,
            requests_with_df,
        )

    else:
        raise KeyError(f'Unsupported model_id: {model_id}')

    for r in pending_rows:
        eval_id = str(r['eval_id'])
        assert eval_id in score_map
        commit_evaluation(r, score_map[eval_id], batch_wall)
        completed_ids.add(eval_id)
        new_evals_this_invocation += 1

    gc.collect()
    print(
        f'[CELL38 RUN GROUP] {run_groups_this_invocation:>3} this invocation | '
        f'run_id={run_id} | model={model_id} | source={source} | seed={seed} | '
        f'new_evals={new_evals_this_invocation} | total_valid={len(completed_ids)}/780',
        flush=True,
    )


# ============================================================================
# 13. FINAL FULL AUDIT; AGGREGATE ONLY WHEN ALL 780 ARE COMPLETE
# ============================================================================

final_valid_ids = set()
for i, r in enumerate(PLAN_RECORDS, start=1):
    if validate_eval_bundle(r, strict_existing=True):
        final_valid_ids.add(str(r['eval_id']))
    if i % 100 == 0 or i == 780:
        print(f'[CELL38 FINAL BUNDLE AUDIT] scanned={i:>3}/780 | valid={len(final_valid_ids):>3}', flush=True)

completed = len(final_valid_ids)
assert final_valid_ids.issubset(set(PLAN_BY_EVAL))

if completed < 780:
    print('\n' + '=' * 132)
    print('CELL 38 PARTIAL / RESTART-SAFE')
    print('=' * 132)
    print('Training performed             : FALSE')
    print('Valid evaluations on disk      :', completed, '/ 780')
    print('New evaluations this invocation:', new_evals_this_invocation)
    print('Run groups this invocation     :', run_groups_this_invocation)
    print('Operational run-group cap      :', MAX_RUN_GROUPS)
    print('Aggregation                    : NOT RUN until 780/780 are valid')
    print('Action                         : rerun THIS SAME Cell 38; valid bundles will be skipped')
    print('=' * 132)

else:
    # ------------------------------------------------------------------------
    # 13A. Rebuild the canonical seed-level table from verified on-disk bundles
    # ------------------------------------------------------------------------
    seed_rows = []
    for r in PLAN_RECORDS:
        eval_id = str(r['eval_id'])
        payload = load_json(eval_dir_for(eval_id) / 'metrics.json')
        m = payload['metrics']
        seed_rows.append({
            'eval_id': eval_id,
            'protocol': PROTOCOL,
            'direction_id': str(r['direction_id']),
            'run_id': str(r['run_id']),
            'model_id': str(r['model_id']),
            'model': MODEL_LABELS[str(r['model_id'])],
            'source_dataset': str(r['source_dataset']),
            'target_dataset': str(r['target_dataset']),
            'source_label': DATASET_LABELS[str(r['source_dataset'])],
            'target_label': DATASET_LABELS[str(r['target_dataset'])],
            'seed': int(r['seed']),
            'target_n': int(r['target_n']),
            'target_AMP': int(r['target_AMP']),
            'target_nonAMP': int(r['target_nonAMP']),
            **m,
        })

    SEED_DF = pd.DataFrame(seed_rows)
    assert len(SEED_DF) == 780
    assert SEED_DF['eval_id'].is_unique
    assert SEED_DF.groupby(['model_id', 'source_dataset', 'target_dataset']).size().eq(10).all()
    atomic_write_csv(TABLE38C_PATH, SEED_DF)

    # ------------------------------------------------------------------------
    # 13B. Exact 10-seed aggregation: mean +/- sample SD, Student-t 95% CI
    # ------------------------------------------------------------------------
    T_CRIT = float(student_t.ppf(0.975, df=9))
    assert np.isclose(T_CRIT, 2.2621571627982055, rtol=0.0, atol=1e-15)

    agg_rows = []
    for spec in DIRECTION_SPECS:
        source = spec['source']
        target = spec['target']
        for model_id in FINAL13_MODEL_IDS:
            g = SEED_DF[
                SEED_DF['direction_id'].eq(spec['direction_id'])
                & SEED_DF['model_id'].eq(model_id)
            ].sort_values('seed', kind='mergesort')
            assert len(g) == 10
            assert g['seed'].tolist() == EXPECTED_SEEDS
            assert g['target_n'].nunique() == 1

            row = {
                'direction_id': spec['direction_id'],
                'model_id': model_id,
                'model': MODEL_LABELS[model_id],
                'source_dataset': source,
                'target_dataset': target,
                'source_label': DATASET_LABELS[source],
                'target_label': DATASET_LABELS[target],
                'n_seeds': 10,
                'target_n': int(g['target_n'].iloc[0]),
            }
            for metric in METRICS:
                x = pd.to_numeric(g[metric], errors='raise').to_numpy(float)
                assert np.isfinite(x).all()
                mean = float(np.mean(x))
                sd = float(np.std(x, ddof=1))
                se = sd / math.sqrt(10.0)
                row[f'{metric}_mean'] = mean
                row[f'{metric}_sd'] = sd
                row[f'{metric}_ci95_low'] = mean - T_CRIT * se
                row[f'{metric}_ci95_high'] = mean + T_CRIT * se
            agg_rows.append(row)

    AGG_DF = pd.DataFrame(agg_rows)
    assert len(AGG_DF) == 78
    assert AGG_DF.groupby(['direction_id']).size().eq(13).all()
    atomic_write_csv(TABLE38D_PATH, AGG_DF)

    # ------------------------------------------------------------------------
    # 13C. GenPept-centered model-wise bidirectional comparison (39 rows)
    # ------------------------------------------------------------------------
    compare_rows = []
    for ext in COMPARATORS:
        fwd_spec = DIRECTION_BY_PAIR[(GENPEPT, ext)]
        rev_spec = DIRECTION_BY_PAIR[(ext, GENPEPT)]

        for model_id in FINAL13_MODEL_IDS:
            fwd = AGG_DF[
                AGG_DF['direction_id'].eq(fwd_spec['direction_id'])
                & AGG_DF['model_id'].eq(model_id)
            ]
            rev = AGG_DF[
                AGG_DF['direction_id'].eq(rev_spec['direction_id'])
                & AGG_DF['model_id'].eq(model_id)
            ]
            assert len(fwd) == 1 and len(rev) == 1
            fr = fwd.iloc[0]
            rr = rev.iloc[0]

            row = {
                'comparator_dataset': ext,
                'comparator_label': DATASET_LABELS[ext],
                'model_id': model_id,
                'model': MODEL_LABELS[model_id],
                'forward_direction': f'{DATASET_LABELS[GENPEPT]} -> {DATASET_LABELS[ext]} minus {DATASET_LABELS[GENPEPT]}',
                'reverse_direction': f'{DATASET_LABELS[ext]} -> {DATASET_LABELS[GENPEPT]} minus {DATASET_LABELS[ext]}',
                'forward_n': int(fr['target_n']),
                'reverse_n': int(rr['target_n']),
                'comparison_scope': 'descriptive_bidirectional_transfer; target_sets_differ',
            }

            for metric in CORE_METRICS:
                fm = float(fr[f'{metric}_mean'])
                fs = float(fr[f'{metric}_sd'])
                rm = float(rr[f'{metric}_mean'])
                rs = float(rr[f'{metric}_sd'])
                row[f'forward_{metric}_mean'] = fm
                row[f'forward_{metric}_sd'] = fs
                row[f'forward_{metric}_mean_sd'] = f'{fm:.4f} \u00b1 {fs:.4f}'
                row[f'reverse_{metric}_mean'] = rm
                row[f'reverse_{metric}_sd'] = rs
                row[f'reverse_{metric}_mean_sd'] = f'{rm:.4f} \u00b1 {rs:.4f}'
                row[f'delta_forward_minus_reverse_{metric}'] = fm - rm
                row[f'GenPept_forward_better_{metric}'] = bool(fm > rm)

            compare_rows.append(row)

    PAIR_COMPARE_DF = pd.DataFrame(compare_rows)
    assert len(PAIR_COMPARE_DF) == 39
    assert PAIR_COMPARE_DF.groupby('comparator_dataset').size().eq(13).all()
    atomic_write_csv(TABLE38E_PATH, PAIR_COMPARE_DF)

    # ------------------------------------------------------------------------
    # 13D. Descriptive dataset-level summary across 13 predeclared model probes
    #      No inferential test because forward/reverse target sets differ.
    # ------------------------------------------------------------------------
    summary_rows = []
    for ext in COMPARATORS:
        sub = PAIR_COMPARE_DF[
            PAIR_COMPARE_DF['comparator_dataset'].eq(ext)
        ].copy()
        assert len(sub) == 13

        for metric in CORE_METRICS:
            f = pd.to_numeric(sub[f'forward_{metric}_mean'], errors='raise').to_numpy(float)
            r = pd.to_numeric(sub[f'reverse_{metric}_mean'], errors='raise').to_numpy(float)
            assert len(f) == len(r) == 13

            forward_wins = int(np.sum(f > r))
            reverse_wins = int(np.sum(r > f))
            ties = int(13 - forward_wins - reverse_wins)
            assert forward_wins + reverse_wins + ties == 13

            summary_rows.append({
                'comparator_dataset': ext,
                'comparator_label': DATASET_LABELS[ext],
                'metric': metric,
                'GenPept_to_comparator_macro_over_13_model_means': float(np.mean(f)),
                'comparator_to_GenPept_macro_over_13_model_means': float(np.mean(r)),
                'delta_forward_minus_reverse': float(np.mean(f) - np.mean(r)),
                'models_GenPept_forward_better': forward_wins,
                'models_reverse_better': reverse_wins,
                'models_tied': ties,
                'n_models': 13,
                'interpretation_scope': 'descriptive_only; forward_and_reverse_targets_differ; no_paired_case_significance_claim',
            })

    DATASET_SUMMARY_DF = pd.DataFrame(summary_rows)
    assert len(DATASET_SUMMARY_DF) == 15
    atomic_write_csv(TABLE38F_PATH, DATASET_SUMMARY_DF)

    # ------------------------------------------------------------------------
    # 13E. Final manifest with immutable input and output provenance
    # ------------------------------------------------------------------------
    cohort_files = sorted(FULL_COMPLEMENT_ROOT.glob('FC_*.csv'))
    assert len(cohort_files) == 6
    output_files = [
        TABLE38A_PATH,
        TABLE38B_PATH,
        PLAN_PATH,
        TABLE38C_PATH,
        TABLE38D_PATH,
        TABLE38E_PATH,
        TABLE38F_PATH,
        CUSTOM_INDEX_PATH,
    ]

    manifest = {
        'schema_version': CELL38_SCHEMA_VERSION,
        'cell': 'CELL 38 - GENPEPT FULL-COMPLEMENT BIDIRECTIONAL VALIDATION',
        'protocol': PROTOCOL,
        'created_at': now_iso(),
        'python_executable': str(CURRENT_PYTHON),
        'training_performed': False,
        'target_training': False,
        'target_validation_used_for_selection': False,
        'target_threshold_tuning': False,
        'target_retraining': False,
        'target_finetuning': False,
        'threshold_source': 'source_validation_only_frozen_from_existing_training_bundle',
        'source_models_reused': 13,
        'training_bundles_reused': 520,
        'seeds': EXPECTED_SEEDS,
        'directions': [
            {
                'direction_id': d['direction_id'],
                'source_dataset': d['source'],
                'target_dataset': d['target'],
                'target_full_complement_n': d['expected_n'],
            }
            for d in DIRECTION_SPECS
        ],
        'seed_level_evaluations': 780,
        'aggregated_configurations': 78,
        'genpept_centered_model_rows': 39,
        'dataset_summary_rows': 15,
        'exact_overlap_definition': 'normalized exact canonical amino-acid sequence',
        'target_definition': 'entire final-QC target cohort minus every exact sequence present in the entire source cohort',
        'interpretation_boundary': 'bidirectional comparison is descriptive because forward and reverse target sets differ',
        'locked_inputs': {
            'model_scope_sha256': EXPECTED_SCOPE_SHA,
            'training_scope_sha256': EXPECTED_TRAINING_SCOPE_SHA,
            'p1_plan_sha256': EXPECTED_P1_PLAN_SHA,
            'p2_plan_sha256': EXPECTED_P2_PLAN_SHA,
            'scope_manifest_sha256': EXPECTED_SCOPE_MANIFEST_SHA,
            'evaluation_contract_sha256': sha256_file(EVALUATION_CONTRACT_PATH),
            'controlled_contract_sha256': sha256_file(CONTROLLED_CONTRACT_PATH),
            'feature_cache_manifest_sha256': sha256_file(FEATURE_CACHE_MANIFEST_PATH),
            'launcher_contract_sha256': sha256_file(LAUNCHER_CONTRACT_PATH),
            'execution_index_sha256': sha256_file(EXECUTION_INDEX_PATH),
            'cell33_summary_observed_sha256': sha256_file(CELL33_SUMMARY_PATH),
            'cell33_loader_selftest_sha256': sha256_file(CELL33_SELFTEST_PATH),
            'deep_inference_helper_sha256': sha256_file(DEEP_HELPER_PATH),
            'ampscannerv2_inference_helper_sha256': sha256_file(AMPSCANNER_HELPER_PATH),
            'ampeppy_inference_helper_sha256': sha256_file(AMPEPPY_HELPER_PATH),
        },
        'cell38_plan_sha256': PLAN_SHA,
        'outputs': {
            p.name: artifact_record(p)
            for p in output_files
        },
        'full_complement_cohorts': {
            p.name: artifact_record(p)
            for p in cohort_files
        },
        'evaluation_bundle_root': str(EVAL_BUNDLE_ROOT),
        'completed_evaluation_bundles': 780,
        'new_evaluations_this_invocation': int(new_evals_this_invocation),
        'new_run_groups_this_invocation': int(run_groups_this_invocation),
        'max_run_groups_operational_cap': int(MAX_RUN_GROUPS),
    }
    atomic_write_json(CELL38_MANIFEST_PATH, manifest)

    print('\n' + '=' * 152)
    print('CELL 38 PASS - GENPEPT FULL-COMPLEMENT BIDIRECTIONAL VALIDATION COMPLETE')
    print('=' * 152)
    print('Training performed             : FALSE')
    print('Target tuning / adaptation     : FALSE')
    print('Inference evaluations          : 780 / 780')
    print('Aggregated directional configs : 78 / 78')
    print('GenPept-centered model rows    : 39 / 39')
    print('Final-QC overlap rows          : 3 / 3')
    print('Dataset summary rows           : 15 / 15')
    print('Residual exact overlap         : 0 in all 6 full-complement directions')
    print('Output root                    :', CELL38_ROOT)
    print('Manifest                       :', CELL38_MANIFEST_PATH)
    print('Manifest SHA256                :', sha256_file(CELL38_MANIFEST_PATH))
    print('-' * 152)
    print('\nTABLE 38A - FINAL-QC OVERLAP / NOVELTY')
    print(OVERLAP_DF.to_string(index=False, float_format=lambda x: f'{x:.4f}'))
    print('\nTABLE 38B - FULL-COMPLEMENT DIRECTION SIZES')
    print(DIRECTION_DF.to_string(index=False))
    print('\nTABLE 38F - DESCRIPTIVE DATASET-LEVEL SUMMARY')
    print(DATASET_SUMMARY_DF.to_string(index=False, float_format=lambda x: f'{x:.4f}'))
    print('=' * 152)

====================================================================================================================================
CELL 38 - STANDALONE FULL-COMPLEMENT BIDIRECTIONAL GENPEPT VALIDATION
====================================================================================================================================
Kernel / Python             : PASS /home/pc/miniconda3/envs/genpept_benchmark10_master/bin/python3.11
Cell 32B immutable scope    : PASS
Cell 33 completion          : PASS 2080/2080
Cell 33 loader self-tests   : PASS 13/13
Training in Cell 38         : FORBIDDEN / FALSE
Target tuning / adaptation  : FORBIDDEN / FALSE
------------------------------------------------------------------------------------------------------------------------------------
[TRAIN-BUNDLE VERIFY]  50/520 PASS
[TRAIN-BUNDLE VERIFY] 100/520 PASS
[TRAIN-BUNDLE VERIFY] 150/520 PASS
[TRAIN-BUNDLE VERIFY] 200/520 PASS
[TRAIN-BUNDLE VERIFY] 250/520 PASS
[TRAIN-BUNDLE VERIFY] 300/520 PASS
[TRAIN-BUNDLE VERIFY] 350/520 PASS
[TRAIN-BUNDLE VERIFY] 400/520 PASS
[TRAIN-BUNDLE VERIFY] 450/520 PASS
[TRAIN-BUNDLE VERIFY] 500/520 PASS
[TRAIN-BUNDLE VERIFY] 520/520 PASS
Canonical training bundles  : PASS 520/520
FINAL-QC DATASETS MATERIALIZED: PASS
GenPept_Curated_2025         n=11,000 | AMP= 5,500 | nonAMP= 5,500
External_Benchmark_1         n= 8,156 | AMP= 4,602 | nonAMP= 3,554
AMPlify_balanced             n= 8,068 | AMP= 4,034 | nonAMP= 4,034
External_Benchmark_3         n=13,835 | AMP= 6,764 | nonAMP= 7,071

FINAL-QC EXACT OVERLAP AUDIT: PASS
comparator_label  exact_shared  same_label_shared  label_conflicts  GenPept_only  comparator_only
       SSFGM-BD1            81                 71               10         10919             8075
AMPlify-balanced            84                 77                7         10916             7984
       SSFGM-BD3            63                 58                5         10937            13772

FULL-COMPLEMENT CONSTRUCTION: PASS 6/6
direction_id         source_label         target_label  exact_overlap_removed  target_full_complement_n  residual_exact_overlap
       FC_01 GenPept-Curated-2025            SSFGM-BD1                     81                      8075                       0
       FC_02            SSFGM-BD1 GenPept-Curated-2025                     81                     10919                       0
       FC_03 GenPept-Curated-2025     AMPlify-balanced                     84                      7984                       0
       FC_04     AMPlify-balanced GenPept-Curated-2025                     84                     10916                       0
       FC_05 GenPept-Curated-2025            SSFGM-BD3                     63                     13772                       0
       FC_06            SSFGM-BD3 GenPept-Curated-2025                     63                     10937                       0

CELL38 EVALUATION PLAN: PASS 780/780
[CELL38 STARTUP BUNDLE AUDIT] scanned=100/780 | valid_existing=  0
[CELL38 STARTUP BUNDLE AUDIT] scanned=200/780 | valid_existing=  0
[CELL38 STARTUP BUNDLE AUDIT] scanned=300/780 | valid_existing=  0
[CELL38 STARTUP BUNDLE AUDIT] scanned=400/780 | valid_existing=  0
[CELL38 STARTUP BUNDLE AUDIT] scanned=500/780 | valid_existing=  0
[CELL38 STARTUP BUNDLE AUDIT] scanned=600/780 | valid_existing=  0
[CELL38 STARTUP BUNDLE AUDIT] scanned=700/780 | valid_existing=  0
[CELL38 STARTUP BUNDLE AUDIT] scanned=780/780 | valid_existing=  0
Existing valid Cell38 evaluations: 0/780
Controlled-deep GPU preflight: PASS {'tensorflow': '2.21.0', 'gpu_count': 1, 'gpu': "PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')"}
[CELL38 RUN GROUP]   1 this invocation | run_id=logistic_regression__GenPept_Curated_2025__seed_100 | model=logistic_regression | source=GenPept_Curated_2025 | seed=100 | new_evals=3 | total_valid=3/780
[CELL38 RUN GROUP]   2 this invocation | run_id=logistic_regression__GenPept_Curated_2025__seed_101 | model=logistic_regression | source=GenPept_Curated_2025 | seed=101 | new_evals=6 | total_valid=6/780
[CELL38 RUN GROUP]   3 this invocation | run_id=logistic_regression__GenPept_Curated_2025__seed_102 | model=logistic_regression | source=GenPept_Curated_2025 | seed=102 | new_evals=9 | total_valid=9/780
[CELL38 RUN GROUP]   4 this invocation | run_id=logistic_regression__GenPept_Curated_2025__seed_103 | model=logistic_regression | source=GenPept_Curated_2025 | seed=103 | new_evals=12 | total_valid=12/780
[CELL38 RUN GROUP]   5 this invocation | run_id=logistic_regression__GenPept_Curated_2025__seed_104 | model=logistic_regression | source=GenPept_Curated_2025 | seed=104 | new_evals=15 | total_valid=15/780
[CELL38 RUN GROUP]   6 this invocation | run_id=logistic_regression__GenPept_Curated_2025__seed_105 | model=logistic_regression | source=GenPept_Curated_2025 | seed=105 | new_evals=18 | total_valid=18/780
[CELL38 RUN GROUP]   7 this invocation | run_id=logistic_regression__GenPept_Curated_2025__seed_106 | model=logistic_regression | source=GenPept_Curated_2025 | seed=106 | new_evals=21 | total_valid=21/780
[CELL38 RUN GROUP]   8 this invocation | run_id=logistic_regression__GenPept_Curated_2025__seed_107 | model=logistic_regression | source=GenPept_Curated_2025 | seed=107 | new_evals=24 | total_valid=24/780
[CELL38 RUN GROUP]   9 this invocation | run_id=logistic_regression__GenPept_Curated_2025__seed_108 | model=logistic_regression | source=GenPept_Curated_2025 | seed=108 | new_evals=27 | total_valid=27/780
[CELL38 RUN GROUP]  10 this invocation | run_id=logistic_regression__GenPept_Curated_2025__seed_109 | model=logistic_regression | source=GenPept_Curated_2025 | seed=109 | new_evals=30 | total_valid=30/780
[CELL38 RUN GROUP]  11 this invocation | run_id=logistic_regression__External_Benchmark_1__seed_100 | model=logistic_regression | source=External_Benchmark_1 | seed=100 | new_evals=31 | total_valid=31/780
[CELL38 RUN GROUP]  12 this invocation | run_id=logistic_regression__External_Benchmark_1__seed_101 | model=logistic_regression | source=External_Benchmark_1 | seed=101 | new_evals=32 | total_valid=32/780
[CELL38 RUN GROUP]  13 this invocation | run_id=logistic_regression__External_Benchmark_1__seed_102 | model=logistic_regression | source=External_Benchmark_1 | seed=102 | new_evals=33 | total_valid=33/780
[CELL38 RUN GROUP]  14 this invocation | run_id=logistic_regression__External_Benchmark_1__seed_103 | model=logistic_regression | source=External_Benchmark_1 | seed=103 | new_evals=34 | total_valid=34/780
[CELL38 RUN GROUP]  15 this invocation | run_id=logistic_regression__External_Benchmark_1__seed_104 | model=logistic_regression | source=External_Benchmark_1 | seed=104 | new_evals=35 | total_valid=35/780
[CELL38 RUN GROUP]  16 this invocation | run_id=logistic_regression__External_Benchmark_1__seed_105 | model=logistic_regression | source=External_Benchmark_1 | seed=105 | new_evals=36 | total_valid=36/780
[CELL38 RUN GROUP]  17 this invocation | run_id=logistic_regression__External_Benchmark_1__seed_106 | model=logistic_regression | source=External_Benchmark_1 | seed=106 | new_evals=37 | total_valid=37/780
[CELL38 RUN GROUP]  18 this invocation | run_id=logistic_regression__External_Benchmark_1__seed_107 | model=logistic_regression | source=External_Benchmark_1 | seed=107 | new_evals=38 | total_valid=38/780
[CELL38 RUN GROUP]  19 this invocation | run_id=logistic_regression__External_Benchmark_1__seed_108 | model=logistic_regression | source=External_Benchmark_1 | seed=108 | new_evals=39 | total_valid=39/780
[CELL38 RUN GROUP]  20 this invocation | run_id=logistic_regression__External_Benchmark_1__seed_109 | model=logistic_regression | source=External_Benchmark_1 | seed=109 | new_evals=40 | total_valid=40/780
[CELL38 RUN GROUP]  21 this invocation | run_id=logistic_regression__AMPlify_balanced__seed_100 | model=logistic_regression | source=AMPlify_balanced | seed=100 | new_evals=41 | total_valid=41/780
[CELL38 RUN GROUP]  22 this invocation | run_id=logistic_regression__AMPlify_balanced__seed_101 | model=logistic_regression | source=AMPlify_balanced | seed=101 | new_evals=42 | total_valid=42/780
[CELL38 RUN GROUP]  23 this invocation | run_id=logistic_regression__AMPlify_balanced__seed_102 | model=logistic_regression | source=AMPlify_balanced | seed=102 | new_evals=43 | total_valid=43/780
[CELL38 RUN GROUP]  24 this invocation | run_id=logistic_regression__AMPlify_balanced__seed_103 | model=logistic_regression | source=AMPlify_balanced | seed=103 | new_evals=44 | total_valid=44/780
[CELL38 RUN GROUP]  25 this invocation | run_id=logistic_regression__AMPlify_balanced__seed_104 | model=logistic_regression | source=AMPlify_balanced | seed=104 | new_evals=45 | total_valid=45/780
[CELL38 RUN GROUP]  26 this invocation | run_id=logistic_regression__AMPlify_balanced__seed_105 | model=logistic_regression | source=AMPlify_balanced | seed=105 | new_evals=46 | total_valid=46/780
[CELL38 RUN GROUP]  27 this invocation | run_id=logistic_regression__AMPlify_balanced__seed_106 | model=logistic_regression | source=AMPlify_balanced | seed=106 | new_evals=47 | total_valid=47/780
[CELL38 RUN GROUP]  28 this invocation | run_id=logistic_regression__AMPlify_balanced__seed_107 | model=logistic_regression | source=AMPlify_balanced | seed=107 | new_evals=48 | total_valid=48/780
[CELL38 RUN GROUP]  29 this invocation | run_id=logistic_regression__AMPlify_balanced__seed_108 | model=logistic_regression | source=AMPlify_balanced | seed=108 | new_evals=49 | total_valid=49/780
[CELL38 RUN GROUP]  30 this invocation | run_id=logistic_regression__AMPlify_balanced__seed_109 | model=logistic_regression | source=AMPlify_balanced | seed=109 | new_evals=50 | total_valid=50/780
[CELL38 RUN GROUP]  31 this invocation | run_id=logistic_regression__External_Benchmark_3__seed_100 | model=logistic_regression | source=External_Benchmark_3 | seed=100 | new_evals=51 | total_valid=51/780
[CELL38 RUN GROUP]  32 this invocation | run_id=logistic_regression__External_Benchmark_3__seed_101 | model=logistic_regression | source=External_Benchmark_3 | seed=101 | new_evals=52 | total_valid=52/780
[CELL38 RUN GROUP]  33 this invocation | run_id=logistic_regression__External_Benchmark_3__seed_102 | model=logistic_regression | source=External_Benchmark_3 | seed=102 | new_evals=53 | total_valid=53/780
[CELL38 RUN GROUP]  34 this invocation | run_id=logistic_regression__External_Benchmark_3__seed_103 | model=logistic_regression | source=External_Benchmark_3 | seed=103 | new_evals=54 | total_valid=54/780
[CELL38 RUN GROUP]  35 this invocation | run_id=logistic_regression__External_Benchmark_3__seed_104 | model=logistic_regression | source=External_Benchmark_3 | seed=104 | new_evals=55 | total_valid=55/780
[CELL38 RUN GROUP]  36 this invocation | run_id=logistic_regression__External_Benchmark_3__seed_105 | model=logistic_regression | source=External_Benchmark_3 | seed=105 | new_evals=56 | total_valid=56/780
[CELL38 RUN GROUP]  37 this invocation | run_id=logistic_regression__External_Benchmark_3__seed_106 | model=logistic_regression | source=External_Benchmark_3 | seed=106 | new_evals=57 | total_valid=57/780
[CELL38 RUN GROUP]  38 this invocation | run_id=logistic_regression__External_Benchmark_3__seed_107 | model=logistic_regression | source=External_Benchmark_3 | seed=107 | new_evals=58 | total_valid=58/780
[CELL38 RUN GROUP]  39 this invocation | run_id=logistic_regression__External_Benchmark_3__seed_108 | model=logistic_regression | source=External_Benchmark_3 | seed=108 | new_evals=59 | total_valid=59/780
[CELL38 RUN GROUP]  40 this invocation | run_id=logistic_regression__External_Benchmark_3__seed_109 | model=logistic_regression | source=External_Benchmark_3 | seed=109 | new_evals=60 | total_valid=60/780
[CELL38 RUN GROUP]  41 this invocation | run_id=linear_svm_calibrated__GenPept_Curated_2025__seed_100 | model=linear_svm_calibrated | source=GenPept_Curated_2025 | seed=100 | new_evals=63 | total_valid=63/780
[CELL38 RUN GROUP]  42 this invocation | run_id=linear_svm_calibrated__GenPept_Curated_2025__seed_101 | model=linear_svm_calibrated | source=GenPept_Curated_2025 | seed=101 | new_evals=66 | total_valid=66/780
[CELL38 RUN GROUP]  43 this invocation | run_id=linear_svm_calibrated__GenPept_Curated_2025__seed_102 | model=linear_svm_calibrated | source=GenPept_Curated_2025 | seed=102 | new_evals=69 | total_valid=69/780
[CELL38 RUN GROUP]  44 this invocation | run_id=linear_svm_calibrated__GenPept_Curated_2025__seed_103 | model=linear_svm_calibrated | source=GenPept_Curated_2025 | seed=103 | new_evals=72 | total_valid=72/780
[CELL38 RUN GROUP]  45 this invocation | run_id=linear_svm_calibrated__GenPept_Curated_2025__seed_104 | model=linear_svm_calibrated | source=GenPept_Curated_2025 | seed=104 | new_evals=75 | total_valid=75/780
[CELL38 RUN GROUP]  46 this invocation | run_id=linear_svm_calibrated__GenPept_Curated_2025__seed_105 | model=linear_svm_calibrated | source=GenPept_Curated_2025 | seed=105 | new_evals=78 | total_valid=78/780
[CELL38 RUN GROUP]  47 this invocation | run_id=linear_svm_calibrated__GenPept_Curated_2025__seed_106 | model=linear_svm_calibrated | source=GenPept_Curated_2025 | seed=106 | new_evals=81 | total_valid=81/780
[CELL38 RUN GROUP]  48 this invocation | run_id=linear_svm_calibrated__GenPept_Curated_2025__seed_107 | model=linear_svm_calibrated | source=GenPept_Curated_2025 | seed=107 | new_evals=84 | total_valid=84/780
[CELL38 RUN GROUP]  49 this invocation | run_id=linear_svm_calibrated__GenPept_Curated_2025__seed_108 | model=linear_svm_calibrated | source=GenPept_Curated_2025 | seed=108 | new_evals=87 | total_valid=87/780
[CELL38 RUN GROUP]  50 this invocation | run_id=linear_svm_calibrated__GenPept_Curated_2025__seed_109 | model=linear_svm_calibrated | source=GenPept_Curated_2025 | seed=109 | new_evals=90 | total_valid=90/780
[CELL38 RUN GROUP]  51 this invocation | run_id=linear_svm_calibrated__External_Benchmark_1__seed_100 | model=linear_svm_calibrated | source=External_Benchmark_1 | seed=100 | new_evals=91 | total_valid=91/780
[CELL38 RUN GROUP]  52 this invocation | run_id=linear_svm_calibrated__External_Benchmark_1__seed_101 | model=linear_svm_calibrated | source=External_Benchmark_1 | seed=101 | new_evals=92 | total_valid=92/780
[CELL38 RUN GROUP]  53 this invocation | run_id=linear_svm_calibrated__External_Benchmark_1__seed_102 | model=linear_svm_calibrated | source=External_Benchmark_1 | seed=102 | new_evals=93 | total_valid=93/780
[CELL38 RUN GROUP]  54 this invocation | run_id=linear_svm_calibrated__External_Benchmark_1__seed_103 | model=linear_svm_calibrated | source=External_Benchmark_1 | seed=103 | new_evals=94 | total_valid=94/780
[CELL38 RUN GROUP]  55 this invocation | run_id=linear_svm_calibrated__External_Benchmark_1__seed_104 | model=linear_svm_calibrated | source=External_Benchmark_1 | seed=104 | new_evals=95 | total_valid=95/780
[CELL38 RUN GROUP]  56 this invocation | run_id=linear_svm_calibrated__External_Benchmark_1__seed_105 | model=linear_svm_calibrated | source=External_Benchmark_1 | seed=105 | new_evals=96 | total_valid=96/780
[CELL38 RUN GROUP]  57 this invocation | run_id=linear_svm_calibrated__External_Benchmark_1__seed_106 | model=linear_svm_calibrated | source=External_Benchmark_1 | seed=106 | new_evals=97 | total_valid=97/780
[CELL38 RUN GROUP]  58 this invocation | run_id=linear_svm_calibrated__External_Benchmark_1__seed_107 | model=linear_svm_calibrated | source=External_Benchmark_1 | seed=107 | new_evals=98 | total_valid=98/780
[CELL38 RUN GROUP]  59 this invocation | run_id=linear_svm_calibrated__External_Benchmark_1__seed_108 | model=linear_svm_calibrated | source=External_Benchmark_1 | seed=108 | new_evals=99 | total_valid=99/780
[CELL38 RUN GROUP]  60 this invocation | run_id=linear_svm_calibrated__External_Benchmark_1__seed_109 | model=linear_svm_calibrated | source=External_Benchmark_1 | seed=109 | new_evals=100 | total_valid=100/780
[CELL38 RUN GROUP]  61 this invocation | run_id=linear_svm_calibrated__AMPlify_balanced__seed_100 | model=linear_svm_calibrated | source=AMPlify_balanced | seed=100 | new_evals=101 | total_valid=101/780
[CELL38 RUN GROUP]  62 this invocation | run_id=linear_svm_calibrated__AMPlify_balanced__seed_101 | model=linear_svm_calibrated | source=AMPlify_balanced | seed=101 | new_evals=102 | total_valid=102/780
[CELL38 RUN GROUP]  63 this invocation | run_id=linear_svm_calibrated__AMPlify_balanced__seed_102 | model=linear_svm_calibrated | source=AMPlify_balanced | seed=102 | new_evals=103 | total_valid=103/780
[CELL38 RUN GROUP]  64 this invocation | run_id=linear_svm_calibrated__AMPlify_balanced__seed_103 | model=linear_svm_calibrated | source=AMPlify_balanced | seed=103 | new_evals=104 | total_valid=104/780
[CELL38 RUN GROUP]  65 this invocation | run_id=linear_svm_calibrated__AMPlify_balanced__seed_104 | model=linear_svm_calibrated | source=AMPlify_balanced | seed=104 | new_evals=105 | total_valid=105/780
[CELL38 RUN GROUP]  66 this invocation | run_id=linear_svm_calibrated__AMPlify_balanced__seed_105 | model=linear_svm_calibrated | source=AMPlify_balanced | seed=105 | new_evals=106 | total_valid=106/780
[CELL38 RUN GROUP]  67 this invocation | run_id=linear_svm_calibrated__AMPlify_balanced__seed_106 | model=linear_svm_calibrated | source=AMPlify_balanced | seed=106 | new_evals=107 | total_valid=107/780
[CELL38 RUN GROUP]  68 this invocation | run_id=linear_svm_calibrated__AMPlify_balanced__seed_107 | model=linear_svm_calibrated | source=AMPlify_balanced | seed=107 | new_evals=108 | total_valid=108/780
[CELL38 RUN GROUP]  69 this invocation | run_id=linear_svm_calibrated__AMPlify_balanced__seed_108 | model=linear_svm_calibrated | source=AMPlify_balanced | seed=108 | new_evals=109 | total_valid=109/780
[CELL38 RUN GROUP]  70 this invocation | run_id=linear_svm_calibrated__AMPlify_balanced__seed_109 | model=linear_svm_calibrated | source=AMPlify_balanced | seed=109 | new_evals=110 | total_valid=110/780
[CELL38 RUN GROUP]  71 this invocation | run_id=linear_svm_calibrated__External_Benchmark_3__seed_100 | model=linear_svm_calibrated | source=External_Benchmark_3 | seed=100 | new_evals=111 | total_valid=111/780
[CELL38 RUN GROUP]  72 this invocation | run_id=linear_svm_calibrated__External_Benchmark_3__seed_101 | model=linear_svm_calibrated | source=External_Benchmark_3 | seed=101 | new_evals=112 | total_valid=112/780
[CELL38 RUN GROUP]  73 this invocation | run_id=linear_svm_calibrated__External_Benchmark_3__seed_102 | model=linear_svm_calibrated | source=External_Benchmark_3 | seed=102 | new_evals=113 | total_valid=113/780
[CELL38 RUN GROUP]  74 this invocation | run_id=linear_svm_calibrated__External_Benchmark_3__seed_103 | model=linear_svm_calibrated | source=External_Benchmark_3 | seed=103 | new_evals=114 | total_valid=114/780
[CELL38 RUN GROUP]  75 this invocation | run_id=linear_svm_calibrated__External_Benchmark_3__seed_104 | model=linear_svm_calibrated | source=External_Benchmark_3 | seed=104 | new_evals=115 | total_valid=115/780
[CELL38 RUN GROUP]  76 this invocation | run_id=linear_svm_calibrated__External_Benchmark_3__seed_105 | model=linear_svm_calibrated | source=External_Benchmark_3 | seed=105 | new_evals=116 | total_valid=116/780
[CELL38 RUN GROUP]  77 this invocation | run_id=linear_svm_calibrated__External_Benchmark_3__seed_106 | model=linear_svm_calibrated | source=External_Benchmark_3 | seed=106 | new_evals=117 | total_valid=117/780
[CELL38 RUN GROUP]  78 this invocation | run_id=linear_svm_calibrated__External_Benchmark_3__seed_107 | model=linear_svm_calibrated | source=External_Benchmark_3 | seed=107 | new_evals=118 | total_valid=118/780
[CELL38 RUN GROUP]  79 this invocation | run_id=linear_svm_calibrated__External_Benchmark_3__seed_108 | model=linear_svm_calibrated | source=External_Benchmark_3 | seed=108 | new_evals=119 | total_valid=119/780

In [6]:
from __future__ import annotations

# ============================================================================
# CELL 39 - ADVISOR-REQUESTED FINAL TABLES
# ============================================================================
# PURPOSE
#   Export exactly 3 tables requested by the advisor:
#
#   TABLE 1
#   Pairwise exact overlap / non-overlap statistics for ALL 6 pairs
#   among the 4 final-QC datasets.
#
#   TABLE 2
#   Models trained on GenPept-Curated-2025 and tested on the FULL
#   exact-sequence complement of each of the 3 external datasets.
#
#   TABLE 3
#   Models trained on each external dataset and tested on the FULL
#   exact-sequence complement of GenPept-Curated-2025.
#
# SCIENTIFIC LOCKS
#   - NO training.
#   - NO inference.
#   - NO threshold tuning.
#   - NO target adaptation.
#   - Read-only use of locked Cell 38 outputs and locked row metadata.
#   - Cell 38 must already be complete: 780/780 evaluations.
# ============================================================================

from pathlib import Path
from itertools import combinations
from datetime import datetime, timezone
import hashlib
import json
import os
import tempfile

import numpy as np
import pandas as pd
from IPython.display import display


# ============================================================================
# 0. FIXED PATHS / IDENTITIES
# ============================================================================

PROJECT_ROOT = Path(
    "/mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026"
)

OUTPUT_ROOT = PROJECT_ROOT / "benchmark17_outputs"
MANIFEST_DIR = OUTPUT_ROOT / "manifests"
RESULTS_ROOT = OUTPUT_ROOT / "results"

CELL38_ROOT = (
    RESULTS_ROOT
    / "benchmark13_FINAL"
    / "cell38_full_complement_genpept_validation"
)

CELL38_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark13_FINAL_cell38_full_complement_manifest.json"
)

FEATURE_CACHE_MANIFEST_PATH = (
    MANIFEST_DIR
    / "benchmark17_FINAL_feature_cache_manifest.json"
)

TABLE38A_PATH = (
    CELL38_ROOT
    / "Table38A_final_QC_overlap_novelty.csv"
)

TABLE38D_PATH = (
    CELL38_ROOT
    / "Table38D_10seed_aggregate_78.csv"
)


# New Cell 39 output directory
CELL39_ROOT = (
    CELL38_ROOT
    / "cell39_advisor_tables"
)

CELL39_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

TABLE1_PATH = (
    CELL39_ROOT
    / "Table1_overlap_nonoverlap_all_6_pairs.csv"
)

TABLE2_PATH = (
    CELL39_ROOT
    / "Table2_GenPept_to_external_full_complements.csv"
)

TABLE3_PATH = (
    CELL39_ROOT
    / "Table3_external_to_GenPept_full_complements.csv"
)

CELL39_MANIFEST_PATH = (
    CELL39_ROOT
    / "cell39_advisor_tables_manifest.json"
)


# ============================================================================
# 1. LOCKED DATASET / MODEL ORDER
# ============================================================================

GENPEPT = "GenPept_Curated_2025"

DATASET_ORDER = [
    "GenPept_Curated_2025",
    "External_Benchmark_1",
    "AMPlify_balanced",
    "External_Benchmark_3",
]

DATASET_LABELS = {
    "GenPept_Curated_2025":
        "GenPept-Curated-2025",

    "External_Benchmark_1":
        "SSFGM-BD1",

    "AMPlify_balanced":
        "AMPlify-balanced",

    "External_Benchmark_3":
        "SSFGM-BD3",
}

EXPECTED_FINAL_COUNTS = {
    "GenPept_Curated_2025": 11000,
    "External_Benchmark_1": 8156,
    "AMPlify_balanced": 8068,
    "External_Benchmark_3": 13835,
}

COMPARATOR_ORDER = [
    "External_Benchmark_1",
    "AMPlify_balanced",
    "External_Benchmark_3",
]

MODEL_ORDER = [
    "logistic_regression",
    "linear_svm_calibrated",
    "random_forest",
    "extra_trees",
    "hist_gradient_boosting",
    "lightgbm",
    "cnn1d",
    "bilstm",
    "bilstm_attention",
    "transformer_encoder",
    "ampep",
    "ampscannerv2",
    "ampeppy",
]

CORE_METRICS = [
    "AUROC",
    "AUPRC",
    "MCC",
    "F1",
    "ACC",
]


# ============================================================================
# 2. HELPERS
# ============================================================================

def sha256_file(
    path: Path,
    chunk_size: int = 1024 * 1024,
) -> str:

    h = hashlib.sha256()

    with path.open("rb") as f:

        while True:

            chunk = f.read(
                chunk_size
            )

            if not chunk:
                break

            h.update(
                chunk
            )

    return h.hexdigest()


def load_json(
    path: Path,
):

    with path.open(
        "r",
        encoding="utf-8",
    ) as f:

        return json.load(
            f
        )


def atomic_write_csv(
    path: Path,
    df: pd.DataFrame,
) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fd, tmp = tempfile.mkstemp(
        prefix=path.name + ".",
        suffix=".tmp",
        dir=str(
            path.parent
        ),
    )

    os.close(
        fd
    )

    try:

        df.to_csv(
            tmp,
            index=False,
            lineterminator="\n",
            encoding="utf-8-sig",
        )

        os.replace(
            tmp,
            path,
        )

    finally:

        if os.path.exists(
            tmp
        ):
            os.unlink(
                tmp
            )


def atomic_write_json(
    path: Path,
    payload: dict,
) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fd, tmp = tempfile.mkstemp(
        prefix=path.name + ".",
        suffix=".tmp",
        dir=str(
            path.parent
        ),
    )

    try:

        with os.fdopen(
            fd,
            "w",
            encoding="utf-8",
            newline="\n",
        ) as f:

            json.dump(
                payload,
                f,
                indent=2,
                ensure_ascii=False,
                sort_keys=True,
            )

            f.write(
                "\n"
            )

        os.replace(
            tmp,
            path,
        )

    finally:

        if os.path.exists(
            tmp
        ):
            os.unlink(
                tmp
            )


def metric_mean_sd(
    row: pd.Series,
    metric: str,
) -> str:

    mean = float(
        row[
            f"{metric}_mean"
        ]
    )

    sd = float(
        row[
            f"{metric}_sd"
        ]
    )

    return (
        f"{mean:.4f} +/- {sd:.4f}"
    )


# ============================================================================
# 3. VERIFY CELL 38 COMPLETE
# ============================================================================

for p in [
    CELL38_MANIFEST_PATH,
    FEATURE_CACHE_MANIFEST_PATH,
    TABLE38A_PATH,
    TABLE38D_PATH,
]:

    assert p.is_file(), (
        f"Missing required artifact: {p}"
    )


cell38_manifest = load_json(
    CELL38_MANIFEST_PATH
)


assert (
    cell38_manifest[
        "training_performed"
    ]
    is False
)

assert (
    cell38_manifest[
        "target_training"
    ]
    is False
)

assert (
    cell38_manifest[
        "target_threshold_tuning"
    ]
    is False
)

assert (
    cell38_manifest[
        "target_retraining"
    ]
    is False
)

assert (
    cell38_manifest[
        "target_finetuning"
    ]
    is False
)

assert int(
    cell38_manifest[
        "completed_evaluation_bundles"
    ]
) == 780

assert int(
    cell38_manifest[
        "seed_level_evaluations"
    ]
) == 780

assert int(
    cell38_manifest[
        "aggregated_configurations"
    ]
) == 78

assert int(
    cell38_manifest[
        "genpept_centered_model_rows"
    ]
) == 39


# Verify Cell38D hash
out_entry = (
    cell38_manifest[
        "outputs"
    ][
        TABLE38D_PATH.name
    ]
)

assert (
    sha256_file(
        TABLE38D_PATH
    )
    ==
    str(
        out_entry[
            "sha256"
        ]
    )
), (
    "Cell 38 aggregate table hash drift detected."
)


print(
    "CELL 38 COMPLETION / PROVENANCE: PASS 780/780"
)


# ============================================================================
# 4. TABLE 1
#    OVERLAP / NON-OVERLAP OF ALL 4 DATASETS = 6 PAIRS
# ============================================================================

feature_manifest = load_json(
    FEATURE_CACHE_MANIFEST_PATH
)

row_meta_entry = (
    feature_manifest[
        "files"
    ][
        "row_metadata"
    ]
)

ROW_METADATA_PATH = Path(
    row_meta_entry[
        "path"
    ]
)


assert ROW_METADATA_PATH.is_file()

assert (
    sha256_file(
        ROW_METADATA_PATH
    )
    ==
    str(
        row_meta_entry[
            "sha256"
        ]
    )
), (
    "Locked row_metadata hash drift detected."
)


meta = pd.read_csv(
    ROW_METADATA_PATH,
    low_memory=False,
    keep_default_na=False,
    na_filter=False,
)


required_cols = {
    "dataset",
    "label",
    "sequence_sha256",
}

assert (
    required_cols
    .issubset(
        meta.columns
    )
)

assert len(
    meta
) == 41059


meta[
    "dataset"
] = (
    meta[
        "dataset"
    ]
    .astype(
        str
    )
)

meta[
    "sequence_sha256"
] = (
    meta[
        "sequence_sha256"
    ]
    .astype(
        str
    )
)

meta[
    "label"
] = (
    pd.to_numeric(
        meta[
            "label"
        ],
        errors="raise",
    )
    .astype(
        np.int8
    )
)


assert (
    set(
        meta[
            "dataset"
        ]
        .unique()
    )
    ==
    set(
        DATASET_ORDER
    )
)


DATA = {}

for ds in DATASET_ORDER:

    d = (
        meta.loc[
            meta[
                "dataset"
            ].eq(
                ds
            ),
            [
                "sequence_sha256",
                "label",
            ],
        ]
        .copy()
    )

    assert len(
        d
    ) == EXPECTED_FINAL_COUNTS[
        ds
    ]

    assert (
        d[
            "sequence_sha256"
        ]
        .is_unique
    )

    assert (
        set(
            d[
                "label"
            ]
            .unique()
        )
        ==
        {0, 1}
    )

    DATA[
        ds
    ] = (
        d
        .set_index(
            "sequence_sha256"
        )[
            "label"
        ]
        .to_dict()
    )


pair_rows = []

for a, b in combinations(
    DATASET_ORDER,
    2,
):

    map_a = DATA[a]
    map_b = DATA[b]

    set_a = set(
        map_a
    )

    set_b = set(
        map_b
    )

    shared = (
        set_a
        &
        set_b
    )

    same_label = sum(
        int(
            map_a[s]
            ==
            map_b[s]
        )
        for s in shared
    )

    conflicts = (
        len(
            shared
        )
        -
        same_label
    )

    a_only = len(
        set_a
        -
        set_b
    )

    b_only = len(
        set_b
        -
        set_a
    )

    union_n = len(
        set_a
        |
        set_b
    )


    assert (
        len(
            shared
        )
        +
        a_only
        ==
        len(
            set_a
        )
    )

    assert (
        len(
            shared
        )
        +
        b_only
        ==
        len(
            set_b
        )
    )

    assert (
        same_label
        +
        conflicts
        ==
        len(
            shared
        )
    )


    pair_rows.append(
        {
            "Dataset_A":
                DATASET_LABELS[a],

            "Dataset_B":
                DATASET_LABELS[b],

            "N_A":
                len(
                    set_a
                ),

            "N_B":
                len(
                    set_b
                ),

            "Exact_shared":
                len(
                    shared
                ),

            "Shared_same_label":
                same_label,

            "Shared_label_conflict":
                conflicts,

            "A_only_nonoverlap":
                a_only,

            "B_only_nonoverlap":
                b_only,

            "Union_unique":
                union_n,

            "Overlap_pct_of_A":
                (
                    100.0
                    *
                    len(
                        shared
                    )
                    /
                    len(
                        set_a
                    )
                ),

            "Overlap_pct_of_B":
                (
                    100.0
                    *
                    len(
                        shared
                    )
                    /
                    len(
                        set_b
                    )
                ),

            "Jaccard_pct":
                (
                    100.0
                    *
                    len(
                        shared
                    )
                    /
                    union_n
                ),
        }
    )


TABLE1 = pd.DataFrame(
    pair_rows
)

assert len(
    TABLE1
) == 6


# --------------------------------------------------------------------------
# Cross-check GenPept-centered 3 pairs against Cell 38
# --------------------------------------------------------------------------

t38a = pd.read_csv(
    TABLE38A_PATH,
    low_memory=False,
)


for _, r in t38a.iterrows():

    comparator = str(
        r[
            "comparator_label"
        ]
    )

    x = TABLE1.loc[
        TABLE1[
            "Dataset_A"
        ].eq(
            "GenPept-Curated-2025"
        )
        &
        TABLE1[
            "Dataset_B"
        ].eq(
            comparator
        )
    ]

    assert len(
        x
    ) == 1

    x = x.iloc[
        0
    ]

    assert int(
        x[
            "Exact_shared"
        ]
    ) == int(
        r[
            "exact_shared"
        ]
    )

    assert int(
        x[
            "Shared_same_label"
        ]
    ) == int(
        r[
            "same_label_shared"
        ]
    )

    assert int(
        x[
            "Shared_label_conflict"
        ]
    ) == int(
        r[
            "label_conflicts"
        ]
    )

    assert int(
        x[
            "A_only_nonoverlap"
        ]
    ) == int(
        r[
            "GenPept_only"
        ]
    )

    assert int(
        x[
            "B_only_nonoverlap"
        ]
    ) == int(
        r[
            "comparator_only"
        ]
    )


atomic_write_csv(
    TABLE1_PATH,
    TABLE1,
)


# ============================================================================
# 5. LOAD CELL 38 10-SEED RESULTS
# ============================================================================

AGG = pd.read_csv(
    TABLE38D_PATH,
    low_memory=False,
)


assert len(
    AGG
) == 78

assert (
    set(
        AGG[
            "model_id"
        ]
        .astype(
            str
        )
    )
    ==
    set(
        MODEL_ORDER
    )
)

assert (
    pd.to_numeric(
        AGG[
            "n_seeds"
        ],
        errors="raise",
    )
    .eq(
        10
    )
    .all()
)


for metric in CORE_METRICS:

    for suffix in [
        "mean",
        "sd",
    ]:

        col = (
            f"{metric}_{suffix}"
        )

        assert (
            col
            in
            AGG.columns
        )

        vals = pd.to_numeric(
            AGG[
                col
            ],
            errors="raise",
        ).to_numpy(
            float
        )

        assert (
            np.isfinite(
                vals
            )
            .all()
        )


model_rank = {
    model_id: i
    for i, model_id
    in enumerate(
        MODEL_ORDER
    )
}

comparator_label_rank = {
    DATASET_LABELS[d]: i
    for i, d
    in enumerate(
        COMPARATOR_ORDER
    )
}


def build_result_table(
    df: pd.DataFrame,
    mode: str,
) -> pd.DataFrame:

    rows = []

    for _, r in df.iterrows():

        source = str(
            r[
                "source_dataset"
            ]
        )

        target = str(
            r[
                "target_dataset"
            ]
        )

        model_id = str(
            r[
                "model_id"
            ]
        )


        if (
            mode
            ==
            "genpept_to_external"
        ):

            comparator = target

            train_label = (
                DATASET_LABELS[
                    GENPEPT
                ]
            )

            test_label = (
                f"{DATASET_LABELS[target]}"
                f" \\ {DATASET_LABELS[GENPEPT]}"
            )


        elif (
            mode
            ==
            "external_to_genpept"
        ):

            comparator = source

            train_label = (
                DATASET_LABELS[
                    source
                ]
            )

            test_label = (
                f"{DATASET_LABELS[GENPEPT]}"
                f" \\ {DATASET_LABELS[source]}"
            )

        else:

            raise ValueError(
                mode
            )


        out = {
            "Comparator":
                DATASET_LABELS[
                    comparator
                ],

            "Train_dataset":
                train_label,

            "Test_full_complement":
                test_label,

            "Test_n":
                int(
                    r[
                        "target_n"
                    ]
                ),

            "Model":
                str(
                    r[
                        "model"
                    ]
                ),

            "model_id":
                model_id,
        }


        for metric in CORE_METRICS:

            out[
                f"{metric}_mean_SD"
            ] = metric_mean_sd(
                r,
                metric,
            )


        rows.append(
            out
        )


    out_df = pd.DataFrame(
        rows
    )


    out_df[
        "_comp_rank"
    ] = (
        out_df[
            "Comparator"
        ]
        .map(
            comparator_label_rank
        )
    )


    out_df[
        "_model_rank"
    ] = (
        out_df[
            "model_id"
        ]
        .map(
            model_rank
        )
    )


    out_df = (
        out_df
        .sort_values(
            [
                "_comp_rank",
                "_model_rank",
            ],
            kind="mergesort",
        )
        .drop(
            columns=[
                "_comp_rank",
                "_model_rank",
            ]
        )
        .reset_index(
            drop=True
        )
    )


    return out_df


# ============================================================================
# 6. TABLE 2
#    TRAIN GENPEPT -> TEST 3 EXTERNAL FULL COMPLEMENTS
# ============================================================================

forward = (
    AGG.loc[
        AGG[
            "source_dataset"
        ]
        .astype(
            str
        )
        .eq(
            GENPEPT
        )
        &
        AGG[
            "target_dataset"
        ]
        .astype(
            str
        )
        .isin(
            COMPARATOR_ORDER
        )
    ]
    .copy()
)


assert len(
    forward
) == 39


assert (
    forward
    .groupby(
        "target_dataset"
    )
    .size()
    .eq(
        13
    )
    .all()
)


TABLE2 = build_result_table(
    forward,
    "genpept_to_external",
)


assert len(
    TABLE2
) == 39


assert (
    TABLE2
    .groupby(
        "Comparator"
    )
    .size()
    .eq(
        13
    )
    .all()
)


atomic_write_csv(
    TABLE2_PATH,
    TABLE2,
)


# ============================================================================
# 7. TABLE 3
#    TRAIN EACH EXTERNAL -> TEST GENPEPT FULL COMPLEMENT
# ============================================================================

reverse = (
    AGG.loc[
        AGG[
            "source_dataset"
        ]
        .astype(
            str
        )
        .isin(
            COMPARATOR_ORDER
        )
        &
        AGG[
            "target_dataset"
        ]
        .astype(
            str
        )
        .eq(
            GENPEPT
        )
    ]
    .copy()
)


assert len(
    reverse
) == 39


assert (
    reverse
    .groupby(
        "source_dataset"
    )
    .size()
    .eq(
        13
    )
    .all()
)


TABLE3 = build_result_table(
    reverse,
    "external_to_genpept",
)


assert len(
    TABLE3
) == 39


assert (
    TABLE3
    .groupby(
        "Comparator"
    )
    .size()
    .eq(
        13
    )
    .all()
)


atomic_write_csv(
    TABLE3_PATH,
    TABLE3,
)


# ============================================================================
# 8. MANIFEST
# ============================================================================

manifest = {

    "cell":
        "CELL 39 - ADVISOR-REQUESTED FINAL TABLES",

    "created_at_utc":
        datetime.now(
            timezone.utc
        ).isoformat(),

    "training_performed":
        False,

    "inference_performed":
        False,

    "threshold_tuning_performed":
        False,

    "cell38_manifest_sha256":
        sha256_file(
            CELL38_MANIFEST_PATH
        ),

    "cell38_aggregate_input_sha256":
        sha256_file(
            TABLE38D_PATH
        ),

    "row_metadata_sha256":
        sha256_file(
            ROW_METADATA_PATH
        ),

    "table_1": {

        "path":
            str(
                TABLE1_PATH
            ),

        "rows":
            len(
                TABLE1
            ),

        "sha256":
            sha256_file(
                TABLE1_PATH
            ),

        "scope":
            (
                "all 6 pairwise comparisons "
                "among 4 final-QC datasets"
            ),
    },

    "table_2": {

        "path":
            str(
                TABLE2_PATH
            ),

        "rows":
            len(
                TABLE2
            ),

        "sha256":
            sha256_file(
                TABLE2_PATH
            ),

        "scope":
            (
                "GenPept-Curated-2025 trained models "
                "tested on each external full complement"
            ),
    },

    "table_3": {

        "path":
            str(
                TABLE3_PATH
            ),

        "rows":
            len(
                TABLE3
            ),

        "sha256":
            sha256_file(
                TABLE3_PATH
            ),

        "scope":
            (
                "each external trained model tested on "
                "GenPept-Curated-2025 full complement"
            ),
    },
}


atomic_write_json(
    CELL39_MANIFEST_PATH,
    manifest,
)


# ============================================================================
# 9. DISPLAY FINAL TABLES
# ============================================================================

print(
    "\n"
    +
    "=" * 140
)

print(
    "CELL 39 PASS - THREE ADVISOR-REQUESTED TABLES EXPORTED"
)

print(
    "=" * 140
)

print(
    "Training performed   : FALSE"
)

print(
    "Inference performed  : FALSE"
)

print(
    "Table 1 rows         : 6 / 6"
)

print(
    "Table 2 rows         : 39 / 39"
)

print(
    "Table 3 rows         : 39 / 39"
)

print(
    "Output directory     :",
    CELL39_ROOT,
)

print(
    "Manifest             :",
    CELL39_MANIFEST_PATH,
)


print(
    "\nTABLE 1 - OVERLAP / NON-OVERLAP OF ALL 4 DATASETS (6 PAIRS)"
)

display(
    TABLE1.style.format(
        {
            "Overlap_pct_of_A":
                "{:.4f}",

            "Overlap_pct_of_B":
                "{:.4f}",

            "Jaccard_pct":
                "{:.4f}",
        }
    )
)


print(
    "\nTABLE 2 - TRAIN GENPEPT-CURATED-2025 -> TEST EXTERNAL FULL COMPLEMENTS"
)

display(
    TABLE2.drop(
        columns=[
            "model_id"
        ]
    )
)


print(
    "\nTABLE 3 - TRAIN EXTERNAL DATASETS -> TEST GENPEPT-CURATED-2025 FULL COMPLEMENTS"
)

display(
    TABLE3.drop(
        columns=[
            "model_id"
        ]
    )
)


print(
    "\nCSV OUTPUTS:"
)

print(
    "1.",
    TABLE1_PATH,
)

print(
    "2.",
    TABLE2_PATH,
)

print(
    "3.",
    TABLE3_PATH,
)

print(
    "=" * 140
)

CELL 38 COMPLETION / PROVENANCE: PASS 780/780

============================================================================================================================================
CELL 39 PASS - THREE ADVISOR-REQUESTED TABLES EXPORTED
============================================================================================================================================
Training performed   : FALSE
Inference performed  : FALSE
Table 1 rows         : 6 / 6
Table 2 rows         : 39 / 39
Table 3 rows         : 39 / 39
Output directory     : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell38_full_complement_genpept_validation/cell39_advisor_tables
Manifest             : /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell38_full_complement_genpept_validation/cell39_advisor_tables/cell39_advisor_tables_manifest.json

TABLE 1 - OVERLAP / NON-OVERLAP OF ALL 4 DATASETS (6 PAIRS)

TABLE 2 - TRAIN GENPEPT-CURATED-2025 -> TEST EXTERNAL FULL COMPLEMENTS

,Comparator,Train_dataset,Test_full_complement,Test_n,Model,AUROC_mean_SD,AUPRC_mean_SD,MCC_mean_SD,F1_mean_SD,ACC_mean_SD
0,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,Logistic Regression,0.5769 +/- 0.0000,0.6579 +/- 0.0000,0.1021 +/- 0.0000,0.5808 +/- 0.0000,0.5517 +/- 0.0000
1,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,Linear SVM (calibrated),0.5780 +/- 0.0008,0.6593 +/- 0.0007,0.1053 +/- 0.0022,0.5864 +/- 0.0047,0.5543 +/- 0.0011
2,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,Random Forest,0.4734 +/- 0.0013,0.5230 +/- 0.0008,-0.1514 +/- 0.0217,0.3712 +/- 0.0419,0.4126 +/- 0.0147
3,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,Extra Trees,0.4646 +/- 0.0011,0.5285 +/- 0.0008,-0.1220 +/- 0.0308,0.4214 +/- 0.0676,0.4323 +/- 0.0238
4,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,HistGradientBoosting,0.5604 +/- 0.0000,0.6028 +/- 0.0000,0.0185 +/- 0.0000,0.5052 +/- 0.0000,0.5024 +/- 0.0000
5,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,LightGBM,0.5648 +/- 0.0026,0.6001 +/- 0.0029,0.0454 +/- 0.0078,0.5459 +/- 0.0290,0.5218 +/- 0.0091
6,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,CNN1D,0.5281 +/- 0.0160,0.5724 +/- 0.0115,0.0413 +/- 0.0335,0.5790 +/- 0.0487,0.5282 +/- 0.0230
7,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,BiLSTM,0.5615 +/- 0.0262,0.5992 +/- 0.0272,0.0757 +/- 0.0408,0.6002 +/- 0.0398,0.5463 +/- 0.0248
8,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,BiLSTM + Attention,0.5506 +/- 0.0287,0.5809 +/- 0.0251,0.0927 +/- 0.0375,0.6302 +/- 0.0366,0.5597 +/- 0.0221
9,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,Transformer Encoder,0.5595 +/- 0.0207,0.5953 +/- 0.0204,0.0573 +/- 0.0530,0.5739 +/- 0.0597,0.5331 +/- 0.0336
10,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,AmPEP,0.4854 +/- 0.0034,0.5312 +/- 0.0020,-0.0794 +/- 0.0241,0.4709 +/- 0.0319,0.4569 +/- 0.0155
11,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,AMPScannerV2,0.5382 +/- 0.0228,0.5795 +/- 0.0210,0.0510 +/- 0.0461,0.5987 +/- 0.0472,0.5362 +/- 0.0285
12,SSFGM-BD1,GenPept-Curated-2025,SSFGM-BD1 \ GenPept-Curated-2025,8075,amPEPpy,0.4839 +/- 0.0025,0.5313 +/- 0.0015,-0.0594 +/- 0.0282,0.5045 +/- 0.0385,0.4717 +/- 0.0192
13,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,Logistic Regression,0.5788 +/- 0.0000,0.5750 +/- 0.0000,0.0965 +/- 0.0000,0.5617 +/- 0.0000,0.5482 +/- 0.0000
14,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,Linear SVM (calibrated),0.5855 +/- 0.0013,0.5845 +/- 0.0016,0.1094 +/- 0.0018,0.5699 +/- 0.0040,0.5546 +/- 0.0009
15,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,Random Forest,0.5704 +/- 0.0031,0.5246 +/- 0.0022,-0.0140 +/- 0.0152,0.1717 +/- 0.0568,0.4956 +/- 0.0051
16,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,Extra Trees,0.5488 +/- 0.0046,0.5179 +/- 0.0032,0.0031 +/- 0.0126,0.2433 +/- 0.0906,0.5011 +/- 0.0050
17,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,HistGradientBoosting,0.6293 +/- 0.0000,0.5877 +/- 0.0000,0.0952 +/- 0.0000,0.3746 +/- 0.0000,0.5400 +/- 0.0000
18,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,LightGBM,0.6334 +/- 0.0020,0.5844 +/- 0.0036,0.1226 +/- 0.0131,0.4358 +/- 0.0413,0.5553 +/- 0.0083
19,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,CNN1D,0.6005 +/- 0.0155,0.5714 +/- 0.0129,0.1342 +/- 0.0243,0.5119 +/- 0.0591,0.5649 +/- 0.0135
20,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,BiLSTM,0.6365 +/- 0.0115,0.6031 +/- 0.0114,0.1704 +/- 0.0244,0.5233 +/- 0.0560,0.5821 +/- 0.0145
21,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,BiLSTM + Attention,0.6514 +/- 0.0186,0.6094 +/- 0.0261,0.2156 +/- 0.0327,0.5737 +/- 0.0453,0.6052 +/- 0.0160
22,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,Transformer Encoder,0.6228 +/- 0.0315,0.5887 +/- 0.0277,0.1470 +/- 0.0692,0.4883 +/- 0.0941,0.5700 +/- 0.0362
23,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,AmPEP,0.6295 +/- 0.0051,0.5515 +/- 0.0039,0.0532 +/- 0.0382,0.3316 +/- 0.0539,0.5222 +/- 0.0166
24,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,AMPScannerV2,0.5901 +/- 0.0193,0.5521 +/- 0.0133,0.1079 +/- 0.0411,0.4978 +/- 0.0722,0.5521 +/- 0.0205
25,AMPlify-balanced,GenPept-Curated-2025,AMPlify-balanced \ GenPept-Curated-2025,7984,amPEPpy,0.6266 +/- 0.0043,0.5484 +/- 0.0037,0.0789 +/- 0.0357,0.3841 +/- 0.0609,0.5348 +/- 0.0176
26,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,Logistic Regression,0.5827 +/- 0.0000,0.5757 +/- 0.0000,0.1273 +/- 0.0000,0.5356 +/- 0.0000,0.5646 +/- 0.0000
27,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,Linear SVM (calibrated),0.5837 +/- 0.0009,0.5762 +/- 0.0009,0.1280 +/- 0.0034,0.5391 +/- 0.0035,0.5649 +/- 0.0018
28,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,Random Forest,0.5622 +/- 0.0022,0.5608 +/- 0.0013,0.1248 +/- 0.0027,0.3854 +/- 0.0280,0.5597 +/- 0.0023
29,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,Extra Trees,0.5402 +/- 0.0012,0.5526 +/- 0.0018,0.1083 +/- 0.0260,0.4074 +/- 0.0340,0.5531 +/- 0.0107
30,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,HistGradientBoosting,0.6680 +/- 0.0000,0.6659 +/- 0.0000,0.2253 +/- 0.0000,0.4915 +/- 0.0000,0.6075 +/- 0.0000
31,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,LightGBM,0.6663 +/- 0.0018,0.6610 +/- 0.0028,0.2254 +/- 0.0046,0.5168 +/- 0.0244,0.6098 +/- 0.0035
32,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,CNN1D,0.5821 +/- 0.0176,0.5924 +/- 0.0182,0.1250 +/- 0.0292,0.5026 +/- 0.0334,0.5630 +/- 0.0135
33,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,BiLSTM,0.6426 +/- 0.0144,0.6466 +/- 0.0133,0.1984 +/- 0.0174,0.5477 +/- 0.0313,0.5996 +/- 0.0091
34,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,BiLSTM + Attention,0.6322 +/- 0.0170,0.6080 +/- 0.0227,0.2012 +/- 0.0310,0.5751 +/- 0.0405,0.6004 +/- 0.0152
35,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,Transformer Encoder,0.6635 +/- 0.0190,0.6567 +/- 0.0322,0.2464 +/- 0.0372,0.5586 +/- 0.0484,0.6216 +/- 0.0190
36,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,AmPEP,0.6031 +/- 0.0026,0.6256 +/- 0.0026,0.1416 +/- 0.0060,0.4448 +/- 0.0182,0.5697 +/- 0.0021
37,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,AMPScannerV2,0.6062 +/- 0.0123,0.6026 +/- 0.0179,0.1408 +/- 0.0170,0.5234 +/- 0.0360,0.5708 +/- 0.0091
38,SSFGM-BD3,GenPept-Curated-2025,SSFGM-BD3 \ GenPept-Curated-2025,13772,amPEPpy,0.6005 +/- 0.0017,0.6264 +/- 0.0019,0.1298 +/- 0.0059,0.4627 +/- 0.0247,0.5652 +/- 0.0022

TABLE 3 - TRAIN EXTERNAL DATASETS -> TEST GENPEPT-CURATED-2025 FULL COMPLEMENTS

,Comparator,Train_dataset,Test_full_complement,Test_n,Model,AUROC_mean_SD,AUPRC_mean_SD,MCC_mean_SD,F1_mean_SD,ACC_mean_SD
0,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,Logistic Regression,0.5708 +/- 0.0000,0.5279 +/- 0.0000,0.0582 +/- 0.0000,0.3509 +/- 0.0000,0.5261 +/- 0.0000
1,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,Linear SVM (calibrated),0.5676 +/- 0.0013,0.5268 +/- 0.0010,0.0494 +/- 0.0194,0.3212 +/- 0.0603,0.5222 +/- 0.0083
2,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,Random Forest,0.4843 +/- 0.0044,0.4893 +/- 0.0020,-0.0161 +/- 0.0078,0.1447 +/- 0.0129,0.4975 +/- 0.0025
3,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,Extra Trees,0.5063 +/- 0.0042,0.4983 +/- 0.0018,-0.0335 +/- 0.0058,0.1243 +/- 0.0195,0.4930 +/- 0.0024
4,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,HistGradientBoosting,0.5710 +/- 0.0000,0.5500 +/- 0.0000,0.0651 +/- 0.0000,0.2586 +/- 0.0000,0.5248 +/- 0.0000
5,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,LightGBM,0.5501 +/- 0.0065,0.5335 +/- 0.0043,0.0533 +/- 0.0083,0.3351 +/- 0.0509,0.5236 +/- 0.0043
6,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,CNN1D,0.5675 +/- 0.0349,0.5526 +/- 0.0260,0.0526 +/- 0.0255,0.2167 +/- 0.0593,0.5193 +/- 0.0098
7,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,BiLSTM,0.5480 +/- 0.0221,0.5562 +/- 0.0224,0.0966 +/- 0.0368,0.3605 +/- 0.0980,0.5422 +/- 0.0189
8,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,BiLSTM + Attention,0.5310 +/- 0.0326,0.5340 +/- 0.0261,0.0597 +/- 0.0336,0.2118 +/- 0.0547,0.5207 +/- 0.0114
9,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,Transformer Encoder,0.5761 +/- 0.0207,0.5632 +/- 0.0127,0.0614 +/- 0.0473,0.4658 +/- 0.0720,0.5284 +/- 0.0213
10,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,AmPEP,0.5560 +/- 0.0094,0.5319 +/- 0.0125,0.0977 +/- 0.0251,0.5884 +/- 0.0335,0.5464 +/- 0.0112
11,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,AMPScannerV2,0.5278 +/- 0.0300,0.5277 +/- 0.0240,0.0338 +/- 0.0357,0.2007 +/- 0.0615,0.5117 +/- 0.0112
12,SSFGM-BD1,SSFGM-BD1,GenPept-Curated-2025 \ SSFGM-BD1,10919,amPEPpy,0.5565 +/- 0.0086,0.5358 +/- 0.0119,0.1001 +/- 0.0145,0.5947 +/- 0.0300,0.5471 +/- 0.0055
13,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,Logistic Regression,0.5764 +/- 0.0000,0.5474 +/- 0.0000,0.0292 +/- 0.0000,0.5000 +/- 0.0000,0.5146 +/- 0.0000
14,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,Linear SVM (calibrated),0.5768 +/- 0.0006,0.5523 +/- 0.0009,0.0204 +/- 0.0076,0.4683 +/- 0.0204,0.5100 +/- 0.0039
15,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,Random Forest,0.6016 +/- 0.0032,0.5983 +/- 0.0019,0.1134 +/- 0.0049,0.1897 +/- 0.0388,0.5302 +/- 0.0047
16,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,Extra Trees,0.6126 +/- 0.0048,0.5937 +/- 0.0031,0.0644 +/- 0.0151,0.1004 +/- 0.0467,0.5128 +/- 0.0067
17,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,HistGradientBoosting,0.6131 +/- 0.0000,0.6139 +/- 0.0000,0.1576 +/- 0.0000,0.3461 +/- 0.0000,0.5594 +/- 0.0000
18,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,LightGBM,0.6116 +/- 0.0039,0.6053 +/- 0.0040,0.1191 +/- 0.0087,0.2451 +/- 0.0416,0.5373 +/- 0.0060
19,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,CNN1D,0.5125 +/- 0.0242,0.5191 +/- 0.0268,0.0276 +/- 0.0354,0.1433 +/- 0.0787,0.5079 +/- 0.0111
20,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,BiLSTM,0.5071 +/- 0.0242,0.5027 +/- 0.0227,-0.0039 +/- 0.0372,0.1075 +/- 0.0490,0.4999 +/- 0.0090
21,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,BiLSTM + Attention,0.4655 +/- 0.0371,0.4763 +/- 0.0234,-0.0234 +/- 0.0272,0.0759 +/- 0.0522,0.4954 +/- 0.0058
22,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,Transformer Encoder,0.4686 +/- 0.0343,0.4876 +/- 0.0342,-0.0123 +/- 0.0531,0.1732 +/- 0.1034,0.4979 +/- 0.0150
23,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,AmPEP,0.4973 +/- 0.0054,0.5079 +/- 0.0067,0.0393 +/- 0.0315,0.1626 +/- 0.0641,0.5091 +/- 0.0094
24,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,AMPScannerV2,0.5476 +/- 0.0339,0.5423 +/- 0.0316,0.0637 +/- 0.0523,0.2318 +/- 0.0704,0.5213 +/- 0.0176
25,AMPlify-balanced,AMPlify-balanced,GenPept-Curated-2025 \ AMPlify-balanced,10916,amPEPpy,0.5003 +/- 0.0065,0.5131 +/- 0.0078,0.0510 +/- 0.0345,0.1355 +/- 0.0735,0.5103 +/- 0.0109
26,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,Logistic Regression,0.5765 +/- 0.0000,0.5330 +/- 0.0000,0.1163 +/- 0.0000,0.5864 +/- 0.0000,0.5572 +/- 0.0000
27,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,Linear SVM (calibrated),0.5732 +/- 0.0005,0.5294 +/- 0.0004,0.1161 +/- 0.0023,0.5574 +/- 0.0139,0.5580 +/- 0.0011
28,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,Random Forest,0.5412 +/- 0.0052,0.5663 +/- 0.0030,0.0811 +/- 0.0109,0.3022 +/- 0.0508,0.5317 +/- 0.0018
29,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,Extra Trees,0.5615 +/- 0.0029,0.5671 +/- 0.0022,0.0727 +/- 0.0095,0.2713 +/- 0.0592,0.5278 +/- 0.0064
30,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,HistGradientBoosting,0.6924 +/- 0.0000,0.6681 +/- 0.0000,0.2254 +/- 0.0000,0.4729 +/- 0.0000,0.6002 +/- 0.0000
31,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,LightGBM,0.6920 +/- 0.0033,0.6677 +/- 0.0031,0.2183 +/- 0.0240,0.4680 +/- 0.0650,0.5973 +/- 0.0169
32,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,CNN1D,0.5941 +/- 0.0202,0.5856 +/- 0.0156,0.1420 +/- 0.0291,0.5644 +/- 0.0628,0.5687 +/- 0.0137
33,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,BiLSTM,0.6309 +/- 0.0281,0.6274 +/- 0.0223,0.1940 +/- 0.0324,0.6744 +/- 0.0142,0.5681 +/- 0.0096
34,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,BiLSTM + Attention,0.6524 +/- 0.0398,0.6460 +/- 0.0248,0.2271 +/- 0.0617,0.6812 +/- 0.0270,0.5801 +/- 0.0150
35,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,Transformer Encoder,0.7083 +/- 0.0271,0.6965 +/- 0.0201,0.2907 +/- 0.0439,0.6851 +/- 0.0348,0.6253 +/- 0.0287
36,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,AmPEP,0.7083 +/- 0.0139,0.6715 +/- 0.0106,0.3162 +/- 0.0142,0.7116 +/- 0.0040,0.6151 +/- 0.0110
37,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,AMPScannerV2,0.5957 +/- 0.0337,0.5845 +/- 0.0189,0.1600 +/- 0.0388,0.5867 +/- 0.0699,0.5771 +/- 0.0179
38,SSFGM-BD3,SSFGM-BD3,GenPept-Curated-2025 \ SSFGM-BD3,10937,amPEPpy,0.7144 +/- 0.0116,0.6786 +/- 0.0082,0.3081 +/- 0.0070,0.7092 +/- 0.0019,0.6080 +/- 0.0067

CSV OUTPUTS:
1. /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell38_full_complement_genpept_validation/cell39_advisor_tables/Table1_overlap_nonoverlap_all_6_pairs.csv
2. /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell38_full_complement_genpept_validation/cell39_advisor_tables/Table2_GenPept_to_external_full_complements.csv
3. /mnt/d/SUABAI_GenPept-Curated-2025_ 12.8.2026/benchmark17_outputs/results/benchmark13_FINAL/cell38_full_complement_genpept_validation/cell39_advisor_tables/Table3_external_to_GenPept_full_complements.csv
============================================================================================================================================